/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */
/*[File]            : wf_wfdma_mcu_dma0.h
 *[Revision time]   : Mon Apr 15 14:14:49 2019
 *[Description]     : This file is auto generated by CODA
 *[Copyright]       : Copyright (C) 2019 Mediatek Incorportion.
 *                    All rights reserved.
 */

#ifndef __WF_WFDMA_MCU_DMA0_REGS_H__
#define __WF_WFDMA_MCU_DMA0_REGS_H__

#ifdef __cplusplus
extern "C" {
#endif


/****************************************************************************
 *
 *                     WF_WFDMA_HOST_DMA0 CR Definitions
 *
 ****************************************************************************
 */

#define WF_WFDMA_MCU_DMA0_BASE                                 0x54000000

#define WF_WFDMA_MCU_DMA0_WPDMA_DBG_IDX_ADDR \
	(WF_WFDMA_MCU_DMA0_BASE + 0x124)
#define WF_WFDMA_MCU_DMA0_WPDMA_DBG_PROBE_ADDR \
	(WF_WFDMA_MCU_DMA0_BASE + 0x128)
#define WF_WFDMA_MCU_DMA0_WPDMA_TX_RING0_CTRL0_ADDR \
	(WF_WFDMA_MCU_DMA0_BASE + 0x300)
#define WF_WFDMA_MCU_DMA0_WPDMA_RX_RING0_CTRL0_ADDR \
	(WF_WFDMA_MCU_DMA0_BASE + 0x500)
#define WF_WFDMA_MCU_DMA0_WPDMA_RX_RING1_CTRL0_ADDR \
	(WF_WFDMA_MCU_DMA0_BASE + 0x510)


#ifdef __cplusplus
}
#endif

#endif /* __WF_WFDMA_MCU_DMA0_REGS_H__ */
