/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */
//[File]            : conn_rf_spi_mst_reg.h
//[Revision time]   : Mon Nov  9 19:42:49 2020

#ifndef __CONN_RF_SPI_MST_REG_REGS_H__
#define __CONN_RF_SPI_MST_REG_REGS_H__

//****************************************************************************
//
//                     CONN_RF_SPI_MST_REG CR Definitions
//
//****************************************************************************

#define CONN_RF_SPI_MST_REG_BASE                               (CONN_REG_CONN_RF_SPI_MST_REG_ADDR) // 0x1800_4000

#define CONN_RF_SPI_MST_REG_SPI_STA_ADDR                       (CONN_RF_SPI_MST_REG_BASE + 0x000) // 4000
#define CONN_RF_SPI_MST_REG_SPI_CRTL_ADDR                      (CONN_RF_SPI_MST_REG_BASE + 0x004) // 4004
#define CONN_RF_SPI_MST_REG_SPI_CRTL2_ADDR                     (CONN_RF_SPI_MST_REG_BASE + 0x008) // 4008
#define CONN_RF_SPI_MST_REG_FM_CTRL_ADDR                       (CONN_RF_SPI_MST_REG_BASE + 0x00C) // 400C
#define CONN_RF_SPI_MST_REG_SPI_WF_ADDR_ADDR                   (CONN_RF_SPI_MST_REG_BASE + 0x010) // 4010
#define CONN_RF_SPI_MST_REG_SPI_WF_WDAT_ADDR                   (CONN_RF_SPI_MST_REG_BASE + 0x014) // 4014
#define CONN_RF_SPI_MST_REG_SPI_WF_RDAT_ADDR                   (CONN_RF_SPI_MST_REG_BASE + 0x018) // 4018
#define CONN_RF_SPI_MST_REG_SPI_BT_ADDR_ADDR                   (CONN_RF_SPI_MST_REG_BASE + 0x020) // 4020
#define CONN_RF_SPI_MST_REG_SPI_BT_WDAT_ADDR                   (CONN_RF_SPI_MST_REG_BASE + 0x024) // 4024
#define CONN_RF_SPI_MST_REG_SPI_BT_RDAT_ADDR                   (CONN_RF_SPI_MST_REG_BASE + 0x028) // 4028
#define CONN_RF_SPI_MST_REG_SPI_FM_ADDR_ADDR                   (CONN_RF_SPI_MST_REG_BASE + 0x030) // 4030
#define CONN_RF_SPI_MST_REG_SPI_FM_WDAT_ADDR                   (CONN_RF_SPI_MST_REG_BASE + 0x034) // 4034
#define CONN_RF_SPI_MST_REG_SPI_FM_RDAT_ADDR                   (CONN_RF_SPI_MST_REG_BASE + 0x038) // 4038
#define CONN_RF_SPI_MST_REG_SPI_GPS_ADDR_ADDR                  (CONN_RF_SPI_MST_REG_BASE + 0x040) // 4040
#define CONN_RF_SPI_MST_REG_SPI_GPS_WDAT_ADDR                  (CONN_RF_SPI_MST_REG_BASE + 0x044) // 4044
#define CONN_RF_SPI_MST_REG_SPI_GPS_RDAT_ADDR                  (CONN_RF_SPI_MST_REG_BASE + 0x048) // 4048
#define CONN_RF_SPI_MST_REG_SPI_TOP_ADDR_ADDR                  (CONN_RF_SPI_MST_REG_BASE + 0x050) // 4050
#define CONN_RF_SPI_MST_REG_SPI_TOP_WDAT_ADDR                  (CONN_RF_SPI_MST_REG_BASE + 0x054) // 4054
#define CONN_RF_SPI_MST_REG_SPI_TOP_RDAT_ADDR                  (CONN_RF_SPI_MST_REG_BASE + 0x058) // 4058
#define CONN_RF_SPI_MST_REG_SPI_SLP_ADDR_ADDR                  (CONN_RF_SPI_MST_REG_BASE + 0x060) // 4060
#define CONN_RF_SPI_MST_REG_SLP_WDAT_ADDR                      (CONN_RF_SPI_MST_REG_BASE + 0x064) // 4064
#define CONN_RF_SPI_MST_REG_SLP_RDAT_ADDR                      (CONN_RF_SPI_MST_REG_BASE + 0x068) // 4068
#define CONN_RF_SPI_MST_REG_THM_ADDR_ADDR                      (CONN_RF_SPI_MST_REG_BASE + 0x070) // 4070
#define CONN_RF_SPI_MST_REG_THM_WDAT_ADDR                      (CONN_RF_SPI_MST_REG_BASE + 0x074) // 4074
#define CONN_RF_SPI_MST_REG_THM_RDAT_ADDR                      (CONN_RF_SPI_MST_REG_BASE + 0x078) // 4078
#define CONN_RF_SPI_MST_REG_SPI_INT_ADDR                       (CONN_RF_SPI_MST_REG_BASE + 0x080) // 4080
#define CONN_RF_SPI_MST_REG_SPI_HW_DMY_CMD_ADDR                (CONN_RF_SPI_MST_REG_BASE + 0x084) // 4084
#define CONN_RF_SPI_MST_REG_SPI_DBG_ADDR                       (CONN_RF_SPI_MST_REG_BASE + 0x090) // 4090
#define CONN_RF_SPI_MST_REG_SPI_STA1_ADDR                      (CONN_RF_SPI_MST_REG_BASE + 0x094) // 4094
#define CONN_RF_SPI_MST_REG_SPI_STA2_ADDR                      (CONN_RF_SPI_MST_REG_BASE + 0x098) // 4098
#define CONN_RF_SPI_MST_REG_SPI_STA3_ADDR                      (CONN_RF_SPI_MST_REG_BASE + 0x09C) // 409C
#define CONN_RF_SPI_MST_REG_SPI_STA4_ADDR                      (CONN_RF_SPI_MST_REG_BASE + 0x100) // 4100
#define CONN_RF_SPI_MST_REG_SPI_STA5_ADDR                      (CONN_RF_SPI_MST_REG_BASE + 0x104) // 4104
#define CONN_RF_SPI_MST_REG_SPI_HSCK_CTL_ADDR                  (CONN_RF_SPI_MST_REG_BASE + 0x108) // 4108
#define CONN_RF_SPI_MST_REG_SPI_GPS_GPS_ADDR_ADDR              (CONN_RF_SPI_MST_REG_BASE + 0x210) // 4210
#define CONN_RF_SPI_MST_REG_SPI_GPS_GPS_WDAT_ADDR              (CONN_RF_SPI_MST_REG_BASE + 0x214) // 4214
#define CONN_RF_SPI_MST_REG_SPI_GPS_GPS_RDAT_ADDR              (CONN_RF_SPI_MST_REG_BASE + 0x218) // 4218
#define CONN_RF_SPI_MST_REG_SPI_GPS_RFDIG_ADDR_ADDR            (CONN_RF_SPI_MST_REG_BASE + 0x220) // 4220
#define CONN_RF_SPI_MST_REG_SPI_GPS_RFDIG_WDAT_ADDR            (CONN_RF_SPI_MST_REG_BASE + 0x224) // 4224
#define CONN_RF_SPI_MST_REG_SPI_GPS_RFDIG_RDAT_ADDR            (CONN_RF_SPI_MST_REG_BASE + 0x228) // 4228

#define CONN_RF_SPI_MST_REG_FM_CTRL_FM_RD_EXT_EN_ADDR          CONN_RF_SPI_MST_REG_FM_CTRL_ADDR
#define CONN_RF_SPI_MST_REG_FM_CTRL_FM_RD_EXT_EN_MASK          0x00008000                // FM_RD_EXT_EN[15]
#define CONN_RF_SPI_MST_REG_FM_CTRL_FM_RD_EXT_EN_SHFT          15

#define CONN_RF_SPI_MST_REG_FM_CTRL_FM_RD_EXT_CNT_ADDR         CONN_RF_SPI_MST_REG_FM_CTRL_ADDR
#define CONN_RF_SPI_MST_REG_FM_CTRL_FM_RD_EXT_CNT_MASK         0x000000FF                // FM_RD_EXT_CNT[7..0]
#define CONN_RF_SPI_MST_REG_FM_CTRL_FM_RD_EXT_CNT_SHFT         0

#define CONN_RF_SPI_MST_REG_SPI_HSCK_CTL_FM_SPI_CK_CTL_ADDR    CONN_RF_SPI_MST_REG_SPI_HSCK_CTL_ADDR
#define CONN_RF_SPI_MST_REG_SPI_HSCK_CTL_FM_SPI_CK_CTL_MASK    0x00000020                // FM_SPI_CK_CTL[5]
#define CONN_RF_SPI_MST_REG_SPI_HSCK_CTL_FM_SPI_CK_CTL_SHFT    5
#define CONN_RF_SPI_MST_REG_SPI_HSCK_CTL_FM_HS_EN_ADDR         CONN_RF_SPI_MST_REG_SPI_HSCK_CTL_ADDR
#define CONN_RF_SPI_MST_REG_SPI_HSCK_CTL_FM_HS_EN_MASK         0x00000010                // FM_HS_EN[4]
#define CONN_RF_SPI_MST_REG_SPI_HSCK_CTL_FM_HS_EN_SHFT         4
#define CONN_RF_SPI_MST_REG_SPI_HSCK_CTL_GPS_HS_EN_ADDR        CONN_RF_SPI_MST_REG_SPI_HSCK_CTL_ADDR
#define CONN_RF_SPI_MST_REG_SPI_HSCK_CTL_GPS_HS_EN_MASK        0x00000008                // GPS_HS_EN[3]
#define CONN_RF_SPI_MST_REG_SPI_HSCK_CTL_GPS_HS_EN_SHFT        3
#define CONN_RF_SPI_MST_REG_SPI_HSCK_CTL_BT_HS_EN_ADDR         CONN_RF_SPI_MST_REG_SPI_HSCK_CTL_ADDR
#define CONN_RF_SPI_MST_REG_SPI_HSCK_CTL_BT_HS_EN_MASK         0x00000004                // BT_HS_EN[2]
#define CONN_RF_SPI_MST_REG_SPI_HSCK_CTL_BT_HS_EN_SHFT         2
#define CONN_RF_SPI_MST_REG_SPI_HSCK_CTL_WF_HS_EN_ADDR         CONN_RF_SPI_MST_REG_SPI_HSCK_CTL_ADDR
#define CONN_RF_SPI_MST_REG_SPI_HSCK_CTL_WF_HS_EN_MASK         0x00000002                // WF_HS_EN[1]
#define CONN_RF_SPI_MST_REG_SPI_HSCK_CTL_WF_HS_EN_SHFT         1
#define CONN_RF_SPI_MST_REG_SPI_HSCK_CTL_TOP_HS_EN_ADDR        CONN_RF_SPI_MST_REG_SPI_HSCK_CTL_ADDR
#define CONN_RF_SPI_MST_REG_SPI_HSCK_CTL_TOP_HS_EN_MASK        0x00000001                // TOP_HS_EN[0]
#define CONN_RF_SPI_MST_REG_SPI_HSCK_CTL_TOP_HS_EN_SHFT        0



#endif // __CONN_RF_SPI_MST_REG_REGS_H__
