/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */
//[File]            : conn_bus_cr.h
//[Revision time]   : Mon Nov  9 19:42:04 2020
//Base: 0x1800_E000
//Size: 0x3d8

#ifndef __CONN_BUS_CR_REGS_H__
#define __CONN_BUS_CR_REGS_H__

//****************************************************************************
//
//                     CONN_BUS_CR CR Definitions
//
//****************************************************************************

#define CONN_BUS_CR_BASE                                       (CONN_REG_CONN_INFRA_BUS_CR_ADDR) //0x1800_E000

#define CONN_BUS_CR_LIGHT_SECURITY_CTRL_ADDR                   (CONN_BUS_CR_BASE + 0x238) // E238
#define CONN_BUS_CR_GALS_AP2CONN_GALS_DBG_ADDR                 (CONN_BUS_CR_BASE + 0x2A0) // E2A0
#define CONN_BUS_CR_GALS_CONN2AP_GALS_DBG_ADDR                 (CONN_BUS_CR_BASE + 0x2A4) // E2A4
#define CONN_BUS_CR_GALS_BT2CONN_GALS_DBG_ADDR                 (CONN_BUS_CR_BASE + 0x2A8) // E2A8
#define CONN_BUS_CR_GALS_CONN2BT_GALS_DBG_ADDR                 (CONN_BUS_CR_BASE + 0x2AC) // E2AC
#define CONN_BUS_CR_GALS_GPS2CONN_GALS_DBG_ADDR                (CONN_BUS_CR_BASE + 0x2B0) // E2B0
#define CONN_BUS_CR_GALS_CONN2GPS_GALS_DBG_ADDR                (CONN_BUS_CR_BASE + 0x2B4) // E2B4
#define CONN_BUS_CR_CONN_INFRA_BUS_OFF_TIMEOUT_CTRL_ADDR       (CONN_BUS_CR_BASE + 0x300) // E300
#define CONN_BUS_CR_CONN_INFRA_BUS_ON_TIMEOUT_CTRL_ADDR        (CONN_BUS_CR_BASE + 0x31C) // E31C
#define CONN_BUS_CR_CONN_INFRA_CONN2AP_EMI_PATH_ADDR_START_ADDR (CONN_BUS_CR_BASE + 0x360) // E360
#define CONN_BUS_CR_CONN_INFRA_CONN2AP_EMI_PATH_ADDR_END_ADDR  (CONN_BUS_CR_BASE + 0x364) // E364
#define CONN_BUS_CR_CONN_INFRA_LOW_POWER_LAYER_CTRL_ADDR       (CONN_BUS_CR_BASE + 0x370) // E370

#define CONN_BUS_CR_CONN_INFRA_BUS_ON_TIMEOUT_CTRL_CONN_INFRA_ON_TIMEOUT_LIMIT_ADDR CONN_BUS_CR_CONN_INFRA_BUS_ON_TIMEOUT_CTRL_ADDR
#define CONN_BUS_CR_CONN_INFRA_BUS_ON_TIMEOUT_CTRL_CONN_INFRA_ON_TIMEOUT_LIMIT_MASK 0x00007F80                // CONN_INFRA_ON_TIMEOUT_LIMIT[14..7]
#define CONN_BUS_CR_CONN_INFRA_BUS_ON_TIMEOUT_CTRL_CONN_INFRA_ON_TIMEOUT_LIMIT_SHFT 7


#define CONN_BUS_CR_CONN_INFRA_BUS_OFF_TIMEOUT_CTRL_CONN_INFRA_OFF_TIMEOUT_LIMIT_ADDR CONN_BUS_CR_CONN_INFRA_BUS_OFF_TIMEOUT_CTRL_ADDR
#define CONN_BUS_CR_CONN_INFRA_BUS_OFF_TIMEOUT_CTRL_CONN_INFRA_OFF_TIMEOUT_LIMIT_MASK 0x00007F80                // CONN_INFRA_OFF_TIMEOUT_LIMIT[14..7]
#define CONN_BUS_CR_CONN_INFRA_BUS_OFF_TIMEOUT_CTRL_CONN_INFRA_OFF_TIMEOUT_LIMIT_SHFT 7


#endif // __CONN_BUS_CR_REGS_H__
