/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */
//[File]            : conn_therm_ctl.h
//[Revision time]   : Mon Nov  9 19:45:04 2020

#ifndef __CONN_THERM_CTL_REGS_H__
#define __CONN_THERM_CTL_REGS_H__

//****************************************************************************
//
//                     CONN_THERM_CTL CR Definitions
//
//****************************************************************************

#define CONN_THERM_CTL_BASE                                    (CONN_REG_CONN_THERM_CTL_ADDR)// 0x18002000

#define CONN_THERM_CTL_THERMCR0_ADDR                           (CONN_THERM_CTL_BASE + 0x000) // 2000
#define CONN_THERM_CTL_THERMCR1_ADDR                           (CONN_THERM_CTL_BASE + 0x004) // 2004
#define CONN_THERM_CTL_THERMCR2_ADDR                           (CONN_THERM_CTL_BASE + 0x008) // 2008
#define CONN_THERM_CTL_THERMISR_ADDR                           (CONN_THERM_CTL_BASE + 0x00C) // 200C
#define CONN_THERM_CTL_THERM_ACL_ADDR                          (CONN_THERM_CTL_BASE + 0x010) // 2010
#define CONN_THERM_CTL_THERM_ATHERM_ADDR                       (CONN_THERM_CTL_BASE + 0x014) // 2014
#define CONN_THERM_CTL_THERM_AADDR_ADDR                        (CONN_THERM_CTL_BASE + 0x018) // 2018
#define CONN_THERM_CTL_THERMEN1_ADDR                           (CONN_THERM_CTL_BASE + 0x01C) // 201C
#define CONN_THERM_CTL_THERMEN2_ADDR                           (CONN_THERM_CTL_BASE + 0x020) // 2020
#define CONN_THERM_CTL_THERMEN3_ADDR                           (CONN_THERM_CTL_BASE + 0x024) // 2024
#define CONN_THERM_CTL_THERMEN4_ADDR                           (CONN_THERM_CTL_BASE + 0x028) // 2028


#define CONN_THERM_CTL_THERMCR0_THERM_MEASURE_CNT_ADDR         CONN_THERM_CTL_THERMCR0_ADDR
#define CONN_THERM_CTL_THERMCR0_THERM_MEASURE_CNT_MASK         0x1F000000                // THERM_MEASURE_CNT[28..24]
#define CONN_THERM_CTL_THERMCR0_THERM_MEASURE_CNT_SHFT         24
#define CONN_THERM_CTL_THERMCR0_THERM_CAL_EN_ADDR              CONN_THERM_CTL_THERMCR0_ADDR
#define CONN_THERM_CTL_THERMCR0_THERM_CAL_EN_MASK              0x00080000                // THERM_CAL_EN[19]
#define CONN_THERM_CTL_THERMCR0_THERM_CAL_EN_SHFT              19
#define CONN_THERM_CTL_THERMCR0_THERM_TRIGGER_ADDR             CONN_THERM_CTL_THERMCR0_ADDR
#define CONN_THERM_CTL_THERMCR0_THERM_TRIGGER_MASK             0x00040000                // THERM_TRIGGER[18]
#define CONN_THERM_CTL_THERMCR0_THERM_TRIGGER_SHFT             18
#define CONN_THERM_CTL_THERMCR0_THERM_BUSY_ADDR                CONN_THERM_CTL_THERMCR0_ADDR
#define CONN_THERM_CTL_THERMCR0_THERM_BUSY_MASK                0x00010000                // THERM_BUSY[16]
#define CONN_THERM_CTL_THERMCR0_THERM_BUSY_SHFT                16
#define CONN_THERM_CTL_THERMCR0_THERM_CAL_VAL_ADDR             CONN_THERM_CTL_THERMCR0_ADDR
#define CONN_THERM_CTL_THERMCR0_THERM_CAL_VAL_MASK             0x00007F00                // THERM_CAL_VAL[14..8]
#define CONN_THERM_CTL_THERMCR0_THERM_CAL_VAL_SHFT             8
#define CONN_THERM_CTL_THERMCR0_THERM_RAW_VAL_ADDR             CONN_THERM_CTL_THERMCR0_ADDR
#define CONN_THERM_CTL_THERMCR0_THERM_RAW_VAL_MASK             0x0000007F                // THERM_RAW_VAL[6..0]
#define CONN_THERM_CTL_THERMCR0_THERM_RAW_VAL_SHFT             0

#define CONN_THERM_CTL_THERMCR1_THERM_2ND_MAX_ADDR             CONN_THERM_CTL_THERMCR1_ADDR
#define CONN_THERM_CTL_THERMCR1_THERM_2ND_MAX_MASK             0x7F000000                // THERM_2ND_MAX[30..24]
#define CONN_THERM_CTL_THERMCR1_THERM_2ND_MAX_SHFT             24
#define CONN_THERM_CTL_THERMCR1_THERM_AR_FACTOR_ADDR           CONN_THERM_CTL_THERMCR1_ADDR
#define CONN_THERM_CTL_THERMCR1_THERM_AR_FACTOR_MASK           0x00030000                // THERM_AR_FACTOR[17..16]
#define CONN_THERM_CTL_THERMCR1_THERM_AR_FACTOR_SHFT           16
#define CONN_THERM_CTL_THERMCR1_THERM_MIN_ADDR                 CONN_THERM_CTL_THERMCR1_ADDR
#define CONN_THERM_CTL_THERMCR1_THERM_MIN_MASK                 0x00007F00                // THERM_MIN[14..8]
#define CONN_THERM_CTL_THERMCR1_THERM_MIN_SHFT                 8
#define CONN_THERM_CTL_THERMCR1_THERM_EXCEED_EN_ADDR           CONN_THERM_CTL_THERMCR1_ADDR
#define CONN_THERM_CTL_THERMCR1_THERM_EXCEED_EN_MASK           0x00000080                // THERM_EXCEED_EN[7]
#define CONN_THERM_CTL_THERMCR1_THERM_EXCEED_EN_SHFT           7
#define CONN_THERM_CTL_THERMCR1_THERM_MAX_ADDR                 CONN_THERM_CTL_THERMCR1_ADDR
#define CONN_THERM_CTL_THERMCR1_THERM_MAX_MASK                 0x0000007F                // THERM_MAX[6..0]
#define CONN_THERM_CTL_THERMCR1_THERM_MAX_SHFT                 0

#define CONN_THERM_CTL_THERMCR2_THERMAL_MAX_INT_EN_ADDR        CONN_THERM_CTL_THERMCR2_ADDR
#define CONN_THERM_CTL_THERMCR2_THERMAL_MAX_INT_EN_MASK        0x01000000                // THERMAL_MAX_INT_EN[24]
#define CONN_THERM_CTL_THERMCR2_THERMAL_MAX_INT_EN_SHFT        24
#define CONN_THERM_CTL_THERMCR2_THERMAL_SCND_MAX_INT_EN_ADDR   CONN_THERM_CTL_THERMCR2_ADDR
#define CONN_THERM_CTL_THERMCR2_THERMAL_SCND_MAX_INT_EN_MASK   0x00100000                // THERMAL_SCND_MAX_INT_EN[20]
#define CONN_THERM_CTL_THERMCR2_THERMAL_SCND_MAX_INT_EN_SHFT   20
#define CONN_THERM_CTL_THERMCR2_THERMAL_MIN_INT_EN_ADDR        CONN_THERM_CTL_THERMCR2_ADDR
#define CONN_THERM_CTL_THERMCR2_THERMAL_MIN_INT_EN_MASK        0x00010000                // THERMAL_MIN_INT_EN[16]
#define CONN_THERM_CTL_THERMCR2_THERMAL_MIN_INT_EN_SHFT        16
#define CONN_THERM_CTL_THERMCR2_RG_THAD_RSV_ADDR               CONN_THERM_CTL_THERMCR2_ADDR
#define CONN_THERM_CTL_THERMCR2_RG_THAD_RSV_MASK               0x0000FF00                // RG_THAD_RSV[15..8]
#define CONN_THERM_CTL_THERMCR2_RG_THAD_RSV_SHFT               8
#define CONN_THERM_CTL_THERMCR2_UPDATE_TIME_ADDR               CONN_THERM_CTL_THERMCR2_ADDR
#define CONN_THERM_CTL_THERMCR2_UPDATE_TIME_MASK               0x0000003F                // UPDATE_TIME[5..0]
#define CONN_THERM_CTL_THERMCR2_UPDATE_TIME_SHFT               0

#define CONN_THERM_CTL_THERMISR_THERMAL_MAX_INT_ADDR           CONN_THERM_CTL_THERMISR_ADDR
#define CONN_THERM_CTL_THERMISR_THERMAL_MAX_INT_MASK           0x01000000                // THERMAL_MAX_INT[24]
#define CONN_THERM_CTL_THERMISR_THERMAL_MAX_INT_SHFT           24
#define CONN_THERM_CTL_THERMISR_THERMAL_SCND_MAX_INT_ADDR      CONN_THERM_CTL_THERMISR_ADDR
#define CONN_THERM_CTL_THERMISR_THERMAL_SCND_MAX_INT_MASK      0x00100000                // THERMAL_SCND_MAX_INT[20]
#define CONN_THERM_CTL_THERMISR_THERMAL_SCND_MAX_INT_SHFT      20
#define CONN_THERM_CTL_THERMISR_THERMAL_MIN_INT_ADDR           CONN_THERM_CTL_THERMISR_ADDR
#define CONN_THERM_CTL_THERMISR_THERMAL_MIN_INT_MASK           0x00010000                // THERMAL_MIN_INT[16]
#define CONN_THERM_CTL_THERMISR_THERMAL_MIN_INT_SHFT           16

#define CONN_THERM_CTL_THERM_ACL_ADIE_TOPCLK_EN_ADDR           CONN_THERM_CTL_THERM_ACL_ADDR
#define CONN_THERM_CTL_THERM_ACL_ADIE_TOPCLK_EN_MASK           0xFFFFFFFF                // ADIE_TOPCLK_EN[31..0]
#define CONN_THERM_CTL_THERM_ACL_ADIE_TOPCLK_EN_SHFT           0

#define CONN_THERM_CTL_THERM_ATHERM_ADIE_THERM_CTL_ADDR        CONN_THERM_CTL_THERM_ATHERM_ADDR
#define CONN_THERM_CTL_THERM_ATHERM_ADIE_THERM_CTL_MASK        0xFFFFFFFF                // ADIE_THERM_CTL[31..0]
#define CONN_THERM_CTL_THERM_ATHERM_ADIE_THERM_CTL_SHFT        0

#define CONN_THERM_CTL_THERM_AADDR_ADIE_THERM_GRP_ADDR         CONN_THERM_CTL_THERM_AADDR_ADDR
#define CONN_THERM_CTL_THERM_AADDR_ADIE_THERM_GRP_MASK         0x70000000                // ADIE_THERM_GRP[30..28]
#define CONN_THERM_CTL_THERM_AADDR_ADIE_THERM_GRP_SHFT         28
#define CONN_THERM_CTL_THERM_AADDR_ADIE_THERM_ADDR_ADDR        CONN_THERM_CTL_THERM_AADDR_ADDR
#define CONN_THERM_CTL_THERM_AADDR_ADIE_THERM_ADDR_MASK        0x0FFF0000                // ADIE_THERM_ADDR[27..16]
#define CONN_THERM_CTL_THERM_AADDR_ADIE_THERM_ADDR_SHFT        16
#define CONN_THERM_CTL_THERM_AADDR_ADIE_CLK_GRP_ADDR           CONN_THERM_CTL_THERM_AADDR_ADDR
#define CONN_THERM_CTL_THERM_AADDR_ADIE_CLK_GRP_MASK           0x00007000                // ADIE_CLK_GRP[14..12]
#define CONN_THERM_CTL_THERM_AADDR_ADIE_CLK_GRP_SHFT           12
#define CONN_THERM_CTL_THERM_AADDR_ADIE_CLK_ADDR_ADDR          CONN_THERM_CTL_THERM_AADDR_ADDR
#define CONN_THERM_CTL_THERM_AADDR_ADIE_CLK_ADDR_MASK          0x00000FFF                // ADIE_CLK_ADDR[11..0]
#define CONN_THERM_CTL_THERM_AADDR_ADIE_CLK_ADDR_SHFT          0

#define CONN_THERM_CTL_THERMEN1_THERM_CAL_EN_1_ADDR            CONN_THERM_CTL_THERMEN1_ADDR
#define CONN_THERM_CTL_THERMEN1_THERM_CAL_EN_1_MASK            0x00080000                // THERM_CAL_EN_1[19]
#define CONN_THERM_CTL_THERMEN1_THERM_CAL_EN_1_SHFT            19
#define CONN_THERM_CTL_THERMEN1_THERM_TRIGGER_1_ADDR           CONN_THERM_CTL_THERMEN1_ADDR
#define CONN_THERM_CTL_THERMEN1_THERM_TRIGGER_1_MASK           0x00040000                // THERM_TRIGGER_1[18]
#define CONN_THERM_CTL_THERMEN1_THERM_TRIGGER_1_SHFT           18
#define CONN_THERM_CTL_THERMEN1_THERM_BUSY_1_ADDR              CONN_THERM_CTL_THERMEN1_ADDR
#define CONN_THERM_CTL_THERMEN1_THERM_BUSY_1_MASK              0x00010000                // THERM_BUSY_1[16]
#define CONN_THERM_CTL_THERMEN1_THERM_BUSY_1_SHFT              16
#define CONN_THERM_CTL_THERMEN1_THERM_CAL_VAL_1_ADDR           CONN_THERM_CTL_THERMEN1_ADDR
#define CONN_THERM_CTL_THERMEN1_THERM_CAL_VAL_1_MASK           0x00007F00                // THERM_CAL_VAL_1[14..8]
#define CONN_THERM_CTL_THERMEN1_THERM_CAL_VAL_1_SHFT           8
#define CONN_THERM_CTL_THERMEN1_THERM_RAW_VAL_1_ADDR           CONN_THERM_CTL_THERMEN1_ADDR
#define CONN_THERM_CTL_THERMEN1_THERM_RAW_VAL_1_MASK           0x0000007F                // THERM_RAW_VAL_1[6..0]
#define CONN_THERM_CTL_THERMEN1_THERM_RAW_VAL_1_SHFT           0

#define CONN_THERM_CTL_THERMEN2_THERM_CAL_EN_2_ADDR            CONN_THERM_CTL_THERMEN2_ADDR
#define CONN_THERM_CTL_THERMEN2_THERM_CAL_EN_2_MASK            0x00080000                // THERM_CAL_EN_2[19]
#define CONN_THERM_CTL_THERMEN2_THERM_CAL_EN_2_SHFT            19
#define CONN_THERM_CTL_THERMEN2_THERM_TRIGGER_2_ADDR           CONN_THERM_CTL_THERMEN2_ADDR
#define CONN_THERM_CTL_THERMEN2_THERM_TRIGGER_2_MASK           0x00040000                // THERM_TRIGGER_2[18]
#define CONN_THERM_CTL_THERMEN2_THERM_TRIGGER_2_SHFT           18
#define CONN_THERM_CTL_THERMEN2_THERM_BUSY_2_ADDR              CONN_THERM_CTL_THERMEN2_ADDR
#define CONN_THERM_CTL_THERMEN2_THERM_BUSY_2_MASK              0x00010000                // THERM_BUSY_2[16]
#define CONN_THERM_CTL_THERMEN2_THERM_BUSY_2_SHFT              16
#define CONN_THERM_CTL_THERMEN2_THERM_CAL_VAL_2_ADDR           CONN_THERM_CTL_THERMEN2_ADDR
#define CONN_THERM_CTL_THERMEN2_THERM_CAL_VAL_2_MASK           0x00007F00                // THERM_CAL_VAL_2[14..8]
#define CONN_THERM_CTL_THERMEN2_THERM_CAL_VAL_2_SHFT           8
#define CONN_THERM_CTL_THERMEN2_THERM_RAW_VAL_2_ADDR           CONN_THERM_CTL_THERMEN2_ADDR
#define CONN_THERM_CTL_THERMEN2_THERM_RAW_VAL_2_MASK           0x0000007F                // THERM_RAW_VAL_2[6..0]
#define CONN_THERM_CTL_THERMEN2_THERM_RAW_VAL_2_SHFT           0

#define CONN_THERM_CTL_THERMEN3_THERM_CAL_EN_3_ADDR            CONN_THERM_CTL_THERMEN3_ADDR
#define CONN_THERM_CTL_THERMEN3_THERM_CAL_EN_3_MASK            0x00080000                // THERM_CAL_EN_3[19]
#define CONN_THERM_CTL_THERMEN3_THERM_CAL_EN_3_SHFT            19
#define CONN_THERM_CTL_THERMEN3_THERM_TRIGGER_3_ADDR           CONN_THERM_CTL_THERMEN3_ADDR
#define CONN_THERM_CTL_THERMEN3_THERM_TRIGGER_3_MASK           0x00040000                // THERM_TRIGGER_3[18]
#define CONN_THERM_CTL_THERMEN3_THERM_TRIGGER_3_SHFT           18
#define CONN_THERM_CTL_THERMEN3_THERM_BUSY_3_ADDR              CONN_THERM_CTL_THERMEN3_ADDR
#define CONN_THERM_CTL_THERMEN3_THERM_BUSY_3_MASK              0x00010000                // THERM_BUSY_3[16]
#define CONN_THERM_CTL_THERMEN3_THERM_BUSY_3_SHFT              16
#define CONN_THERM_CTL_THERMEN3_THERM_CAL_VAL_3_ADDR           CONN_THERM_CTL_THERMEN3_ADDR
#define CONN_THERM_CTL_THERMEN3_THERM_CAL_VAL_3_MASK           0x00007F00                // THERM_CAL_VAL_3[14..8]
#define CONN_THERM_CTL_THERMEN3_THERM_CAL_VAL_3_SHFT           8
#define CONN_THERM_CTL_THERMEN3_THERM_RAW_VAL_3_ADDR           CONN_THERM_CTL_THERMEN3_ADDR
#define CONN_THERM_CTL_THERMEN3_THERM_RAW_VAL_3_MASK           0x0000007F                // THERM_RAW_VAL_3[6..0]
#define CONN_THERM_CTL_THERMEN3_THERM_RAW_VAL_3_SHFT           0

#define CONN_THERM_CTL_THERMEN4_THERM_CAL_EN_4_ADDR            CONN_THERM_CTL_THERMEN4_ADDR
#define CONN_THERM_CTL_THERMEN4_THERM_CAL_EN_4_MASK            0x00080000                // THERM_CAL_EN_4[19]
#define CONN_THERM_CTL_THERMEN4_THERM_CAL_EN_4_SHFT            19
#define CONN_THERM_CTL_THERMEN4_THERM_TRIGGER_4_ADDR           CONN_THERM_CTL_THERMEN4_ADDR
#define CONN_THERM_CTL_THERMEN4_THERM_TRIGGER_4_MASK           0x00040000                // THERM_TRIGGER_4[18]
#define CONN_THERM_CTL_THERMEN4_THERM_TRIGGER_4_SHFT           18
#define CONN_THERM_CTL_THERMEN4_THERM_BUSY_4_ADDR              CONN_THERM_CTL_THERMEN4_ADDR
#define CONN_THERM_CTL_THERMEN4_THERM_BUSY_4_MASK              0x00010000                // THERM_BUSY_4[16]
#define CONN_THERM_CTL_THERMEN4_THERM_BUSY_4_SHFT              16
#define CONN_THERM_CTL_THERMEN4_THERM_CAL_VAL_4_ADDR           CONN_THERM_CTL_THERMEN4_ADDR
#define CONN_THERM_CTL_THERMEN4_THERM_CAL_VAL_4_MASK           0x00007F00                // THERM_CAL_VAL_4[14..8]
#define CONN_THERM_CTL_THERMEN4_THERM_CAL_VAL_4_SHFT           8
#define CONN_THERM_CTL_THERMEN4_THERM_RAW_VAL_4_ADDR           CONN_THERM_CTL_THERMEN4_ADDR
#define CONN_THERM_CTL_THERMEN4_THERM_RAW_VAL_4_MASK           0x0000007F                // THERM_RAW_VAL_4[6..0]
#define CONN_THERM_CTL_THERMEN4_THERM_RAW_VAL_4_SHFT           0

#endif // __CONN_THERM_CTL_REGS_H__
