/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2021 MediaTek Inc.
 */

#ifndef _DBG_MT6639_H
#define _DBG_MT6639_H

#include "coda/mt6639/cb_infra_misc0.h"
#include "coda/mt6639/cb_infra_slp_ctrl.h"
#include "coda/mt6639/cb_infra_rgu.h"
#include "coda/mt6639/conn_bus_cr_on.h"
#include "coda/mt6639/conn_cfg.h"
#include "coda/mt6639/conn_dbg_ctl.h"
#include "coda/mt6639/conn_host_csr_top.h"
#include "coda/mt6639/conn_mcu_bus_cr.h"
#include "coda/mt6639/conn_mcu_confg_ls.h"
#include "coda/mt6639/top_misc.h"
#include "coda/mt6639/wf_mcusys_vdnr_gen_bus_u_debug_ctrl_ao.h"
#include "coda/mt6639/wf_top_cfg_on.h"


struct dump_cr_set {
	u_int8_t read;
	uint32_t addr;
	uint32_t mask;
	uint32_t shift;
	uint32_t value;
};

struct dump_cr_set cbtop_dump_list[] = {
	{
		TRUE,
		CB_INFRA_MISC0_AP2CONN_GALS_MST_DBG_ADDR,
		CB_INFRA_MISC0_AP2CONN_GALS_MST_DBG_AP2CONN_GALS_MST_DBG_OUT_MASK,
		CB_INFRA_MISC0_AP2CONN_GALS_MST_DBG_AP2CONN_GALS_MST_DBG_OUT_SHFT
	},
	{
		TRUE,
		CONN_BUS_CR_ON_ADDR_AP2CONN_AHB_GALS_DBG_ADDR,
		CONN_BUS_CR_ON_ADDR_AP2CONN_AHB_GALS_DBG_conn_infra_top2conn_gals_rx_debug_out_MASK,
		CONN_BUS_CR_ON_ADDR_AP2CONN_AHB_GALS_DBG_conn_infra_top2conn_gals_rx_debug_out_SHFT
	},
	{
		FALSE,
		CB_INFRA_SLP_CTRL_CB_INFRA_SLP_DBG_SEL_ADDR,
		CB_INFRA_SLP_CTRL_CB_INFRA_SLP_DBG_SEL_CR_CB_INFRA_SLP_CTRL_DBG_PROBE_SEL_HW0_MASK,
		CB_INFRA_SLP_CTRL_CB_INFRA_SLP_DBG_SEL_CR_CB_INFRA_SLP_CTRL_DBG_PROBE_SEL_HW0_SHFT,
		0x10
	},
	{
		FALSE,
		CB_INFRA_SLP_CTRL_CB_INFRA_SLP_DBG_SEL_ADDR,
		CB_INFRA_SLP_CTRL_CB_INFRA_SLP_DBG_SEL_CR_CB_INFRA_SLP_CTRL_DBG_PROBE_SEL_HW1_MASK,
		CB_INFRA_SLP_CTRL_CB_INFRA_SLP_DBG_SEL_CR_CB_INFRA_SLP_CTRL_DBG_PROBE_SEL_HW1_SHFT,
		0x11
	},
	{
		TRUE,
		0x70025304,
		0xFFFFFFFF,
		0
	},
	{
		FALSE,
		CB_INFRA_SLP_CTRL_CB_INFRA_SLP_DBG_SEL_ADDR,
		CB_INFRA_SLP_CTRL_CB_INFRA_SLP_DBG_SEL_CR_CB_INFRA_SLP_CTRL_DBG_PROBE_SEL_HW0_MASK,
		CB_INFRA_SLP_CTRL_CB_INFRA_SLP_DBG_SEL_CR_CB_INFRA_SLP_CTRL_DBG_PROBE_SEL_HW0_SHFT,
		0xF
	},
	{
		FALSE,
		CB_INFRA_SLP_CTRL_CB_INFRA_SLP_DBG_SEL_ADDR,
		CB_INFRA_SLP_CTRL_CB_INFRA_SLP_DBG_SEL_CR_CB_INFRA_SLP_CTRL_DBG_PROBE_SEL_HW1_MASK,
		CB_INFRA_SLP_CTRL_CB_INFRA_SLP_DBG_SEL_CR_CB_INFRA_SLP_CTRL_DBG_PROBE_SEL_HW1_SHFT,
		0xE
	},
	{
		TRUE,
		0x70025304,
		0xFFFFFFFF,
		0
	},
	{
		FALSE,
		CB_INFRA_SLP_CTRL_CB_INFRA_SLP_DBG_SEL_ADDR,
		CB_INFRA_SLP_CTRL_CB_INFRA_SLP_DBG_SEL_CR_CB_INFRA_SLP_CTRL_DBG_PROBE_SEL_HW0_MASK,
		CB_INFRA_SLP_CTRL_CB_INFRA_SLP_DBG_SEL_CR_CB_INFRA_SLP_CTRL_DBG_PROBE_SEL_HW0_SHFT,
		0xD
	},
	{
		FALSE,
		CB_INFRA_SLP_CTRL_CB_INFRA_SLP_DBG_SEL_ADDR,
		CB_INFRA_SLP_CTRL_CB_INFRA_SLP_DBG_SEL_CR_CB_INFRA_SLP_CTRL_DBG_PROBE_SEL_HW1_MASK,
		CB_INFRA_SLP_CTRL_CB_INFRA_SLP_DBG_SEL_CR_CB_INFRA_SLP_CTRL_DBG_PROBE_SEL_HW1_SHFT,
		0xC
	},
	{
		TRUE,
		0x70025304,
		0xFFFFFFFF,
		0
	},
};

struct dump_cr_set n45_general_dump_list[] = {
	{
		FALSE,
		CONN_MCU_CONFG_CFG_DBG1_ADDR,
		CONN_MCU_CONFG_CFG_DBG1_DBG_CTRL_SEL_MASK,
		CONN_MCU_CONFG_CFG_DBG1_DBG_CTRL_SEL_SHFT,
		0x0
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		(0x1000 + 0x0)
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		(0x1000 + 0x1)
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		(0x1000 + 0x2)
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		(0x1000 + 0x3)
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		(0x1000 + 0x4)
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		(0x1000 + 0x5)
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		(0x1000 + 0x6)
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		(0x1000 + 0x7)
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		(0x1000 + 0x8)
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		(0x1000 + 0x9)
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		(0x1000 + 0xA)
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		(0x1000 + 0xB)
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		(0x1000 + 0xC)
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		(0x1000 + 0xD)
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		(0x1000 + 0xE)
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		(0x1000 + 0xF)
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		(0x1000 + 0x10)
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		(0x1000 + 0x11)
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		(0x1000 + 0x12)
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		(0x1000 + 0x13)
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		(0x1000 + 0x14)
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		(0x1000 + 0x15)
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		(0x1000 + 0x16)
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		(0x1000 + 0x17)
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		(0x1000 + 0x18)
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		(0x1000 + 0x19)
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		(0x1000 + 0x1A)
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		(0x1000 + 0x1B)
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		(0x1000 + 0x1C)
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		(0x1000 + 0x1D)
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		(0x1000 + 0x1E)
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		(0x1000 + 0x1F)
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
};

struct dump_cr_set n45_ctrl_status_dump_list[] = {
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		0x300
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		0x341
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		0x342
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		0x343
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
	{
		FALSE,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK,
		CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT,
		0x7C9
	},
	{
		TRUE,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK,
		CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT
	},
};

#endif
