/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */

#ifndef __CSIRX_MAC_TOP0_C_HEADER_H__
#define __CSIRX_MAC_TOP0_C_HEADER_H__

#define CSIRX_MAC_TOP_CTRL 0x0000
#define SENINF_TOP_SW_RST_SHIFT 0
#define SENINF_TOP_SW_RST_MASK (0x1 << 0)
#define RG_8PIX_SHARE_16PIX_DATA_SHIFT 16
#define RG_8PIX_SHARE_16PIX_DATA_MASK (0x1 << 16)

#define CSIRX_MAC_VERSION_CODE 0x0004
#define RO_MAC_VERSION_CODE_SHIFT 0
#define RO_MAC_VERSION_CODE_MASK (0xffffffff << 0)

#define CSIRX_MAC_TOP_PHY_CTRL_CSI0 0x0040
#define PHY_SENINF_MUX0_DPHY_EN_SHIFT 0
#define PHY_SENINF_MUX0_DPHY_EN_MASK (0x1 << 0)
#define PHY_SENINF_MUX0_CPHY_EN_SHIFT 1
#define PHY_SENINF_MUX0_CPHY_EN_MASK (0x1 << 1)
#define RG_PHY_SENINF_MUX0_CPHY_MODE_SHIFT 8
#define RG_PHY_SENINF_MUX0_CPHY_MODE_MASK (0x3 << 8)

#define CSIRX_MAC_PRBS_GEN 0x0070
#define RG_PRBS0A_GEN_EN_SHIFT 0
#define RG_PRBS0A_GEN_EN_MASK (0x1 << 0)
#define RG_PRBS0A_GEN_MODE_SHIFT 1
#define RG_PRBS0A_GEN_MODE_MASK (0x1 << 1)
#define RG_PRBS0B_GEN_EN_SHIFT 2
#define RG_PRBS0B_GEN_EN_MASK (0x1 << 2)
#define RG_PRBS0B_GEN_MODE_SHIFT 3
#define RG_PRBS0B_GEN_MODE_MASK (0x1 << 3)
#define RG_PRBS_CHECK_SHIFT 4
#define RG_PRBS_CHECK_MASK (0x1 << 4)

#define CSIRX_MAC_TOP_PHY_CHK_EN 0x0090
#define PHY_SENINF_MUX0_PHYD2MAC_DPHY_CHK_EN_SHIFT 0
#define PHY_SENINF_MUX0_PHYD2MAC_DPHY_CHK_EN_MASK (0x1 << 0)
#define PHY_SENINF_MUX0_PHYD2MAC_CPHY_CHK_EN_SHIFT 8
#define PHY_SENINF_MUX0_PHYD2MAC_CPHY_CHK_EN_MASK (0x1 << 8)

#define CSIRX_MAC_TOP_PHY_CHK_MODE 0x0094
#define RG_PHY_SENINF_MUX0_PHYD2MAC_DPHY_CHK_MODE_SHIFT 0
#define RG_PHY_SENINF_MUX0_PHYD2MAC_DPHY_CHK_MODE_MASK (0x1 << 0)
#define RG_PHY_SENINF_MUX0_PHYD2MAC_CPHY_CHK_MODE_SHIFT 8
#define RG_PHY_SENINF_MUX0_PHYD2MAC_CPHY_CHK_MODE_MASK (0x1 << 8)

#define CSIRX_MAC_TOP_PHY_CHK_RES0 0x00a0
#define RO_PHY_SENINF_MUX0_PHYD2MAC_DPHY_L0_CHK_DONE_SHIFT 0
#define RO_PHY_SENINF_MUX0_PHYD2MAC_DPHY_L0_CHK_DONE_MASK (0x1 << 0)
#define RO_PHY_SENINF_MUX0_PHYD2MAC_DPHY_L1_CHK_DONE_SHIFT 8
#define RO_PHY_SENINF_MUX0_PHYD2MAC_DPHY_L1_CHK_DONE_MASK (0x1 << 8)
#define RO_PHY_SENINF_MUX0_PHYD2MAC_DPHY_L2_CHK_DONE_SHIFT 16
#define RO_PHY_SENINF_MUX0_PHYD2MAC_DPHY_L2_CHK_DONE_MASK (0x1 << 16)
#define RO_PHY_SENINF_MUX0_PHYD2MAC_DPHY_L3_CHK_DONE_SHIFT 24
#define RO_PHY_SENINF_MUX0_PHYD2MAC_DPHY_L3_CHK_DONE_MASK (0x1 << 24)

#define CSIRX_MAC_TOP_PHY_CHK_RES1 0x00a4
#define RO_PHY_SENINF_MUX0_PHYD2MAC_DPHY_L0_CHK_FAIL_SHIFT 0
#define RO_PHY_SENINF_MUX0_PHYD2MAC_DPHY_L0_CHK_FAIL_MASK (0x1 << 0)
#define RO_PHY_SENINF_MUX0_PHYD2MAC_DPHY_L1_CHK_FAIL_SHIFT 8
#define RO_PHY_SENINF_MUX0_PHYD2MAC_DPHY_L1_CHK_FAIL_MASK (0x1 << 8)
#define RO_PHY_SENINF_MUX0_PHYD2MAC_DPHY_L2_CHK_FAIL_SHIFT 16
#define RO_PHY_SENINF_MUX0_PHYD2MAC_DPHY_L2_CHK_FAIL_MASK (0x1 << 16)
#define RO_PHY_SENINF_MUX0_PHYD2MAC_DPHY_L3_CHK_FAIL_SHIFT 24
#define RO_PHY_SENINF_MUX0_PHYD2MAC_DPHY_L3_CHK_FAIL_MASK (0x1 << 24)

#define CSIRX_MAC_TOP_PHY_CHK_RES2 0x00a8
#define RO_PHY_SENINF_MUX0_PHYD2MAC_CPHY_T0_CHK_DONE_SHIFT 0
#define RO_PHY_SENINF_MUX0_PHYD2MAC_CPHY_T0_CHK_DONE_MASK (0x1 << 0)
#define RO_PHY_SENINF_MUX0_PHYD2MAC_CPHY_T1_CHK_DONE_SHIFT 8
#define RO_PHY_SENINF_MUX0_PHYD2MAC_CPHY_T1_CHK_DONE_MASK (0x1 << 8)
#define RO_PHY_SENINF_MUX0_PHYD2MAC_CPHY_T2_CHK_DONE_SHIFT 16
#define RO_PHY_SENINF_MUX0_PHYD2MAC_CPHY_T2_CHK_DONE_MASK (0x1 << 16)
#define RO_PHY_SENINF_MUX0_PHYD2MAC_CPHY_T3_CHK_DONE_SHIFT 24
#define RO_PHY_SENINF_MUX0_PHYD2MAC_CPHY_T3_CHK_DONE_MASK (0x1 << 24)

#define CSIRX_MAC_TOP_PHY_CHK_RES3 0x00ac
#define RO_PHY_SENINF_MUX0_PHYD2MAC_CPHY_T0_CHK_FAIL_SHIFT 0
#define RO_PHY_SENINF_MUX0_PHYD2MAC_CPHY_T0_CHK_FAIL_MASK (0x1 << 0)
#define RO_PHY_SENINF_MUX0_PHYD2MAC_CPHY_T1_CHK_FAIL_SHIFT 8
#define RO_PHY_SENINF_MUX0_PHYD2MAC_CPHY_T1_CHK_FAIL_MASK (0x1 << 8)
#define RO_PHY_SENINF_MUX0_PHYD2MAC_CPHY_T2_CHK_FAIL_SHIFT 16
#define RO_PHY_SENINF_MUX0_PHYD2MAC_CPHY_T2_CHK_FAIL_MASK (0x1 << 16)
#define RO_PHY_SENINF_MUX0_PHYD2MAC_CPHY_T3_CHK_FAIL_SHIFT 24
#define RO_PHY_SENINF_MUX0_PHYD2MAC_CPHY_T3_CHK_FAIL_MASK (0x1 << 24)

#define CSIRX_MAC_TOP_PHY_CSIRX_MAC_MUX0_DBG_CTRL 0x00c0
#define RG_PHY_SENINF_MUX0_DBG_EN_SHIFT 0
#define RG_PHY_SENINF_MUX0_DBG_EN_MASK (0x1 << 0)
#define RG_PHY_SENINF_MUX0_DBG_SEL_SHIFT 8
#define RG_PHY_SENINF_MUX0_DBG_SEL_MASK (0x1f << 8)

#define CSIRX_MAC_TOP_PHY_CSIRX_MAC_MUX0_DBG_OUT 0x00c4
#define RO_PHY_SENINF_MUX0_DBG_OUT_SHIFT 0
#define RO_PHY_SENINF_MUX0_DBG_OUT_MASK (0xffffffff << 0)

#define CSIRX_MAC_TOP_VALID_CNT_CTRL 0x00e8
#define RG_LANE0_VALID_CNT_EN_SHIFT 0
#define RG_LANE0_VALID_CNT_EN_MASK (0x1 << 0)
#define RG_LANE0_VALID_CNT_CLR_SHIFT 1
#define RG_LANE0_VALID_CNT_CLR_MASK (0x1 << 1)
#define RG_LANE1_VALID_CNT_EN_SHIFT 8
#define RG_LANE1_VALID_CNT_EN_MASK (0x1 << 8)
#define RG_LANE1_VALID_CNT_CLR_SHIFT 9
#define RG_LANE1_VALID_CNT_CLR_MASK (0x1 << 9)
#define RG_LANE2_VALID_CNT_EN_SHIFT 16
#define RG_LANE2_VALID_CNT_EN_MASK (0x1 << 16)
#define RG_LANE2_VALID_CNT_CLR_SHIFT 17
#define RG_LANE2_VALID_CNT_CLR_MASK (0x1 << 17)
#define RG_LANE3_VALID_CNT_EN_SHIFT 24
#define RG_LANE3_VALID_CNT_EN_MASK (0x1 << 24)
#define RG_LANE3_VALID_CNT_CLR_SHIFT 25
#define RG_LANE3_VALID_CNT_CLR_MASK (0x1 << 25)

#define CSIRX_MAC_TOP_VALID_CNT 0x00ec
#define RO_LANE0_VALID_CNT_SHIFT 0
#define RO_LANE0_VALID_CNT_MASK (0xff << 0)
#define RO_LANE1_VALID_CNT_SHIFT 8
#define RO_LANE1_VALID_CNT_MASK (0xff << 8)
#define RO_LANE2_VALID_CNT_SHIFT 16
#define RO_LANE2_VALID_CNT_MASK (0xff << 16)
#define RO_LANE3_VALID_CNT_SHIFT 24
#define RO_LANE3_VALID_CNT_MASK (0xff << 24)

#define CSIRX_MAC_CSI2_PRBS_PAT_CTRL 0x00f0
#define RG_CSI2_PRBS_PAT_CHECKER_EN_SHIFT 0
#define RG_CSI2_PRBS_PAT_CHECKER_EN_MASK (0x1 << 0)
#define RG_CSI2_PRBS_PAT_GEN_LANE_NUM_SHIFT 1
#define RG_CSI2_PRBS_PAT_GEN_LANE_NUM_MASK (0x7 << 1)
#define RG_CSI2_PRBS_PAT_LONG_PKT_CNT_SHIFT 8
#define RG_CSI2_PRBS_PAT_LONG_PKT_CNT_MASK (0x1f << 8)
#define RG_CSI2_PRBS_PAT_TIMEOUT_CNT_SHIFT 16
#define RG_CSI2_PRBS_PAT_TIMEOUT_CNT_MASK (0xffff << 16)

#define CSIRX_MAC_CSI2_PRBS_PAT_DBGOUT 0x00f4
#define RO_CSI2_PRBS_PAT_DATA_ERROR_SHIFT 0
#define RO_CSI2_PRBS_PAT_DATA_ERROR_MASK (0x1 << 0)
#define RO_CSI2_PRBS_PAT_CONFIG_ERROR_SHIFT 1
#define RO_CSI2_PRBS_PAT_CONFIG_ERROR_MASK (0x1 << 1)
#define RO_CSI2_PRBS_PAT_TIMEOUT_ERROR_SHIFT 2
#define RO_CSI2_PRBS_PAT_TIMEOUT_ERROR_MASK (0x1 << 2)
#define RO_CSI2_PRBS_PAT_CHECK_DONE_SHIFT 3
#define RO_CSI2_PRBS_PAT_CHECK_DONE_MASK (0x1 << 3)
#define RO_CSI2_PRBS_PAT_ERROR_CNT_SHIFT 4
#define RO_CSI2_PRBS_PAT_ERROR_CNT_MASK (0xff << 4)
#define RO_CSI2_PRBS_PAT_DBG_SHIFT 12
#define RO_CSI2_PRBS_PAT_DBG_MASK (0xfffff << 12)

#define CSIRX_MAC_TOP_SPARE 0x00f8
#define RG_SENINF_TOP_SPARE_0_SHIFT 0
#define RG_SENINF_TOP_SPARE_0_MASK (0xff << 0)
#define RG_SENINF_TOP_SPARE_1_SHIFT 16
#define RG_SENINF_TOP_SPARE_1_MASK (0xff << 16)

#endif
