/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */

#ifndef __CSI0_DPHY_TOP_REG_C_HEADER_H__
#define __CSI0_DPHY_TOP_REG_C_HEADER_H__

#define DPHY_RX_LANE_EN 0x0000
#define DPHY_RX_LC0_EN_SHIFT 0
#define DPHY_RX_LC0_EN_MASK (0x1 << 0)
#define DPHY_RX_LC1_EN_SHIFT 1
#define DPHY_RX_LC1_EN_MASK (0x1 << 1)
#define DPHY_RX_LD0_EN_SHIFT 8
#define DPHY_RX_LD0_EN_MASK (0x1 << 8)
#define DPHY_RX_LD1_EN_SHIFT 9
#define DPHY_RX_LD1_EN_MASK (0x1 << 9)
#define DPHY_RX_LD2_EN_SHIFT 10
#define DPHY_RX_LD2_EN_MASK (0x1 << 10)
#define DPHY_RX_LD3_EN_SHIFT 11
#define DPHY_RX_LD3_EN_MASK (0x1 << 11)
#define DPHY_RX_SW_RST_SHIFT 31
#define DPHY_RX_SW_RST_MASK (0x1 << 31)

#define DPHY_RX_LANE_SELECT 0x0004
#define RG_DPHY_RX_LC0_SEL_SHIFT 0
#define RG_DPHY_RX_LC0_SEL_MASK (0x7 << 0)
#define RG_DPHY_RX_LC1_SEL_SHIFT 4
#define RG_DPHY_RX_LC1_SEL_MASK (0x7 << 4)
#define RG_DPHY_RX_LD0_SEL_SHIFT 8
#define RG_DPHY_RX_LD0_SEL_MASK (0x7 << 8)
#define RG_DPHY_RX_LD1_SEL_SHIFT 12
#define RG_DPHY_RX_LD1_SEL_MASK (0x7 << 12)
#define RG_DPHY_RX_LD2_SEL_SHIFT 16
#define RG_DPHY_RX_LD2_SEL_MASK (0x7 << 16)
#define RG_DPHY_RX_LD3_SEL_SHIFT 20
#define RG_DPHY_RX_LD3_SEL_MASK (0x7 << 20)
#define DPHY_RX_CK_DATA_MUX_EN_SHIFT 31
#define DPHY_RX_CK_DATA_MUX_EN_MASK (0x1 << 31)

#define DPHY_RX_HS_RX_EN_SW 0x0008
#define RG_DPHY_RX_LC0_HSRX_EN_SW_SHIFT 0
#define RG_DPHY_RX_LC0_HSRX_EN_SW_MASK (0x1 << 0)
#define RG_DPHY_RX_LC1_HSRX_EN_SW_SHIFT 1
#define RG_DPHY_RX_LC1_HSRX_EN_SW_MASK (0x1 << 1)
#define RG_DPHY_RX_LD0_HSRX_EN_SW_SHIFT 8
#define RG_DPHY_RX_LD0_HSRX_EN_SW_MASK (0x1 << 8)
#define RG_DPHY_RX_LD1_HSRX_EN_SW_SHIFT 9
#define RG_DPHY_RX_LD1_HSRX_EN_SW_MASK (0x1 << 9)
#define RG_DPHY_RX_LD2_HSRX_EN_SW_SHIFT 10
#define RG_DPHY_RX_LD2_HSRX_EN_SW_MASK (0x1 << 10)
#define RG_DPHY_RX_LD3_HSRX_EN_SW_SHIFT 11
#define RG_DPHY_RX_LD3_HSRX_EN_SW_MASK (0x1 << 11)
#define RG_DPHY_PHY_PN_SWAP_EN_SHIFT 12
#define RG_DPHY_PHY_PN_SWAP_EN_MASK (0x3f << 12)

#define DPHY_RX_CLOCK_LANE0_HS_PARAMETER 0x0010
#define RG_DPHY_RX_LC0_HS_PREPARE_PARAMETER_SHIFT 0
#define RG_DPHY_RX_LC0_HS_PREPARE_PARAMETER_MASK (0xff << 0)
#define RG_DPHY_RX_LC0_HS_SETTLE_PARAMETER_SHIFT 16
#define RG_DPHY_RX_LC0_HS_SETTLE_PARAMETER_MASK (0xff << 16)
#define RG_DPHY_RX_LC0_HS_PREPARE_EN_SHIFT 28
#define RG_DPHY_RX_LC0_HS_PREPARE_EN_MASK (0x1 << 28)
#define RG_DPHY_RX_LC0_HS_OPTION_SHIFT 30
#define RG_DPHY_RX_LC0_HS_OPTION_MASK (0x1 << 30)

#define DPHY_RX_CLOCK_LANE1_HS_PARAMETER 0x0014
#define RG_DPHY_RX_LC1_HS_PREPARE_PARAMETER_SHIFT 0
#define RG_DPHY_RX_LC1_HS_PREPARE_PARAMETER_MASK (0xff << 0)
#define RG_DPHY_RX_LC1_HS_SETTLE_PARAMETER_SHIFT 16
#define RG_DPHY_RX_LC1_HS_SETTLE_PARAMETER_MASK (0xff << 16)
#define RG_DPHY_RX_LC1_HS_PREPARE_EN_SHIFT 28
#define RG_DPHY_RX_LC1_HS_PREPARE_EN_MASK (0x1 << 28)
#define RG_DPHY_RX_LC1_HS_OPTION_SHIFT 30
#define RG_DPHY_RX_LC1_HS_OPTION_MASK (0x1 << 30)

#define DPHY_RX_DATA_LANE0_HS_PARAMETER 0x0020
#define RG_CDPHY_RX_LD0_TRIO0_HS_PREPARE_PARAMETER_SHIFT 0
#define RG_CDPHY_RX_LD0_TRIO0_HS_PREPARE_PARAMETER_MASK (0xff << 0)
#define RG_CDPHY_RX_LD0_TRIO0_HS_TRAIL_PARAMETER_SHIFT 8
#define RG_CDPHY_RX_LD0_TRIO0_HS_TRAIL_PARAMETER_MASK (0x3ff << 8)
#define RG_CDPHY_RX_LD0_TRIO0_HS_SETTLE_PARAMETER_SHIFT 18
#define RG_CDPHY_RX_LD0_TRIO0_HS_SETTLE_PARAMETER_MASK (0xff << 18)
#define RG_CDPHY_RX_LD0_TRIO0_HS_PREPARE_EN_SHIFT 28
#define RG_CDPHY_RX_LD0_TRIO0_HS_PREPARE_EN_MASK (0x1 << 28)
#define RG_CDPHY_RX_LD0_TRIO0_HS_TRAIL_EN_SHIFT 29
#define RG_CDPHY_RX_LD0_TRIO0_HS_TRAIL_EN_MASK (0x1 << 29)
#define RG_CDPHY_RX_LD0_HS_LP00_START_EN_SHIFT 30
#define RG_CDPHY_RX_LD0_HS_LP00_START_EN_MASK (0x1 << 30)

#define DPHY_RX_DATA_LANE1_HS_PARAMETER 0x0024
#define RG_CDPHY_RX_LD1_TRIO1_HS_PREPARE_PARAMETER_SHIFT 0
#define RG_CDPHY_RX_LD1_TRIO1_HS_PREPARE_PARAMETER_MASK (0xff << 0)
#define RG_CDPHY_RX_LD1_TRIO1_HS_TRAIL_PARAMETER_SHIFT 8
#define RG_CDPHY_RX_LD1_TRIO1_HS_TRAIL_PARAMETER_MASK (0x3ff << 8)
#define RG_CDPHY_RX_LD1_TRIO1_HS_SETTLE_PARAMETER_SHIFT 18
#define RG_CDPHY_RX_LD1_TRIO1_HS_SETTLE_PARAMETER_MASK (0xff << 18)
#define RG_CDPHY_RX_LD1_TRIO1_HS_PREPARE_EN_SHIFT 28
#define RG_CDPHY_RX_LD1_TRIO1_HS_PREPARE_EN_MASK (0x1 << 28)
#define RG_CDPHY_RX_LD1_TRIO1_HS_TRAIL_EN_SHIFT 29
#define RG_CDPHY_RX_LD1_TRIO1_HS_TRAIL_EN_MASK (0x1 << 29)
#define RG_CDPHY_RX_LD1_HS_LP00_START_EN_SHIFT 30
#define RG_CDPHY_RX_LD1_HS_LP00_START_EN_MASK (0x1 << 30)

#define DPHY_RX_DATA_LANE2_HS_PARAMETER 0x0028
#define RG_CDPHY_RX_LD2_TRIO2_HS_PREPARE_PARAMETER_SHIFT 0
#define RG_CDPHY_RX_LD2_TRIO2_HS_PREPARE_PARAMETER_MASK (0xff << 0)
#define RG_CDPHY_RX_LD2_TRIO2_HS_TRAIL_PARAMETER_SHIFT 8
#define RG_CDPHY_RX_LD2_TRIO2_HS_TRAIL_PARAMETER_MASK (0x3ff << 8)
#define RG_CDPHY_RX_LD2_TRIO2_HS_SETTLE_PARAMETER_SHIFT 18
#define RG_CDPHY_RX_LD2_TRIO2_HS_SETTLE_PARAMETER_MASK (0xff << 18)
#define RG_CDPHY_RX_LD2_TRIO2_HS_PREPARE_EN_SHIFT 28
#define RG_CDPHY_RX_LD2_TRIO2_HS_PREPARE_EN_MASK (0x1 << 28)
#define RG_CDPHY_RX_LD2_TRIO2_HS_TRAIL_EN_SHIFT 29
#define RG_CDPHY_RX_LD2_TRIO2_HS_TRAIL_EN_MASK (0x1 << 29)
#define RG_CDPHY_RX_LD2_HS_LP00_START_EN_SHIFT 30
#define RG_CDPHY_RX_LD2_HS_LP00_START_EN_MASK (0x1 << 30)

#define DPHY_RX_DATA_LANE3_HS_PARAMETER 0x002c
#define RG_CDPHY_RX_LD3_TRIO3_HS_PREPARE_PARAMETER_SHIFT 0
#define RG_CDPHY_RX_LD3_TRIO3_HS_PREPARE_PARAMETER_MASK (0xff << 0)
#define RG_CDPHY_RX_LD3_TRIO3_HS_TRAIL_PARAMETER_SHIFT 8
#define RG_CDPHY_RX_LD3_TRIO3_HS_TRAIL_PARAMETER_MASK (0x3ff << 8)
#define RG_CDPHY_RX_LD3_TRIO3_HS_SETTLE_PARAMETER_SHIFT 18
#define RG_CDPHY_RX_LD3_TRIO3_HS_SETTLE_PARAMETER_MASK (0xff << 18)
#define RG_CDPHY_RX_LD3_TRIO3_HS_PREPARE_EN_SHIFT 28
#define RG_CDPHY_RX_LD3_TRIO3_HS_PREPARE_EN_MASK (0x1 << 28)
#define RG_CDPHY_RX_LD3_TRIO3_HS_TRAIL_EN_SHIFT 29
#define RG_CDPHY_RX_LD3_TRIO3_HS_TRAIL_EN_MASK (0x1 << 29)
#define RG_CDPHY_RX_LD3_HS_LP00_START_EN_SHIFT 30
#define RG_CDPHY_RX_LD3_HS_LP00_START_EN_MASK (0x1 << 30)

#define DPHY_RX_CLOCK_LANE_FSM 0x0030
#define RO_DPHY_RX_CL0_FSM_SHIFT 0
#define RO_DPHY_RX_CL0_FSM_MASK (0x3f << 0)
#define RO_DPHY_RX_CL1_FSM_SHIFT 8
#define RO_DPHY_RX_CL1_FSM_MASK (0x3f << 8)

#define DPHY_RX_DATA_LANE_FSM_0 0x0034
#define RO_DPHY_RX_DL0_FSM_SHIFT 0
#define RO_DPHY_RX_DL0_FSM_MASK (0x1ff << 0)
#define RO_DPHY_RX_DL1_FSM_SHIFT 9
#define RO_DPHY_RX_DL1_FSM_MASK (0x1ff << 9)
#define RO_DPHY_RX_DL2_FSM_SHIFT 18
#define RO_DPHY_RX_DL2_FSM_MASK (0x1ff << 18)

#define DPHY_RX_DATA_LANE_FSM_1 0x0038
#define RO_DPHY_RX_DL3_FSM_SHIFT 0
#define RO_DPHY_RX_DL3_FSM_MASK (0x1ff << 0)

#define DPHY_RX_DATA_LANE_SYNC_DETECT_ALP_TRAIL 0x003c
#define RG_DPHY_RX_LD_SYNC_SEQ_PAT_ALP_TRAIL_SHIFT 0
#define RG_DPHY_RX_LD_SYNC_SEQ_PAT_ALP_TRAIL_MASK (0xffff << 0)
#define RG_DPHY_RX_LD_SYNC_SEQ_MASK_ALP_TRAIL_SHIFT 16
#define RG_DPHY_RX_LD_SYNC_SEQ_MASK_ALP_TRAIL_MASK (0xffff << 16)

#define DPHY_RX_DATA_LANE_SYNC_DETECT_NORMAL 0x0040
#define RG_DPHY_RX_LD_SYNC_SEQ_PAT_NORM_SHIFT 0
#define RG_DPHY_RX_LD_SYNC_SEQ_PAT_NORM_MASK (0xffff << 0)
#define RG_DPHY_RX_LD_SYNC_SEQ_MASK_NORM_SHIFT 16
#define RG_DPHY_RX_LD_SYNC_SEQ_MASK_NORM_MASK (0xffff << 16)

#define DPHY_RX_DATA_LANE_SYNC_DETECT_DESKEW 0x0044
#define RG_DPHY_RX_LD_SYNC_SEQ_PAT_DESKEW_SHIFT 0
#define RG_DPHY_RX_LD_SYNC_SEQ_PAT_DESKEW_MASK (0xffff << 0)
#define RG_DPHY_RX_LD_SYNC_SEQ_MASK_DESKEW_SHIFT 16
#define RG_DPHY_RX_LD_SYNC_SEQ_MASK_DESKEW_MASK (0xffff << 16)

#define DPHY_RX_DATA_LANE_SYNC_DETECT_ALTCAL 0x0048
#define RG_DPHY_RX_LD_SYNC_SEQ_PAT_ALT_CAL_SHIFT 0
#define RG_DPHY_RX_LD_SYNC_SEQ_PAT_ALT_CAL_MASK (0xffff << 0)
#define RG_DPHY_RX_LD_SYNC_SEQ_MASK_ALT_CAL_SHIFT 16
#define RG_DPHY_RX_LD_SYNC_SEQ_MASK_ALT_CAL_MASK (0xffff << 16)

#define DPHY_RX_DATA_LANE_SYNC_DETECT_PRESEQ 0x004c
#define RG_DPHY_RX_LD_SYNC_SEQ_PAT_PRE_SEQ_SHIFT 0
#define RG_DPHY_RX_LD_SYNC_SEQ_PAT_PRE_SEQ_MASK (0xffff << 0)
#define RG_DPHY_RX_LD_SYNC_SEQ_MASK_PRE_SEQ_SHIFT 16
#define RG_DPHY_RX_LD_SYNC_SEQ_MASK_PRE_SEQ_MASK (0xffff << 16)

#define DPHY_RX_DESKEW_CTRL 0x0050
#define RG_DPHY_RX_DESKEW_INITIAL_SETUP_SHIFT 0
#define RG_DPHY_RX_DESKEW_INITIAL_SETUP_MASK (0xf << 0)
#define RG_DPHY_RX_DESKEW_OFFSET_SHIFT 4
#define RG_DPHY_RX_DESKEW_OFFSET_MASK (0xf << 4)
#define RG_DPHY_RX_DESKEW_EN_SHIFT 8
#define RG_DPHY_RX_DESKEW_EN_MASK (0x1 << 8)
#define RG_DPHY_RX_DESKEW_CODE_UNIT_SEL_SHIFT 9
#define RG_DPHY_RX_DESKEW_CODE_UNIT_SEL_MASK (0x3 << 9)
#define RG_DPHY_RX_DESKEW_DELAY_APPLY_OPT_SHIFT 11
#define RG_DPHY_RX_DESKEW_DELAY_APPLY_OPT_MASK (0x1 << 11)
#define RG_DPHY_RX_DESKEW_ACC_MODE_SHIFT 12
#define RG_DPHY_RX_DESKEW_ACC_MODE_MASK (0xf << 12)
#define RG_DPHY_RX_DESKEW_APPLY_MODE_SHIFT 16
#define RG_DPHY_RX_DESKEW_APPLY_MODE_MASK (0xf << 16)
#define RG_DPHY_RX_DESKEW_LENGTH_SHIFT 24
#define RG_DPHY_RX_DESKEW_LENGTH_MASK (0x3f << 24)
#define DPHY_RX_DESKEW_LP11_IDLE_EN_SHIFT 30
#define DPHY_RX_DESKEW_LP11_IDLE_EN_MASK (0x1 << 30)
#define DPHY_RX_DESKEW_SW_RST_SHIFT 31
#define DPHY_RX_DESKEW_SW_RST_MASK (0x1 << 31)

#define DPHY_RX_DESKEW_TIMING_CTRL 0x0054
#define RG_DPHY_RX_DESKEW_SETUP_CNT_SHIFT 0
#define RG_DPHY_RX_DESKEW_SETUP_CNT_MASK (0x3f << 0)
#define RG_DPHY_RX_DESKEW_HOLD_CNT_SHIFT 8
#define RG_DPHY_RX_DESKEW_HOLD_CNT_MASK (0x3f << 8)
#define RG_DPHY_RX_DESKEW_DETECT_CNT_SHIFT 16
#define RG_DPHY_RX_DESKEW_DETECT_CNT_MASK (0x7f << 16)
#define RG_DPHY_RX_DESKEW_CMPLENGTH_SHIFT 24
#define RG_DPHY_RX_DESKEW_CMPLENGTH_MASK (0xf << 24)

#define DPHY_RX_DESKEW_LANE_SWAP 0x0058
#define RG_DPHY_RX_DESKEW_LANE0_SWAP_SHIFT 0
#define RG_DPHY_RX_DESKEW_LANE0_SWAP_MASK (0x3 << 0)
#define RG_DPHY_RX_DESKEW_LANE1_SWAP_SHIFT 2
#define RG_DPHY_RX_DESKEW_LANE1_SWAP_MASK (0x3 << 2)
#define RG_DPHY_RX_DESKEW_LANE2_SWAP_SHIFT 4
#define RG_DPHY_RX_DESKEW_LANE2_SWAP_MASK (0x3 << 4)
#define RG_DPHY_RX_DESKEW_LANE3_SWAP_SHIFT 6
#define RG_DPHY_RX_DESKEW_LANE3_SWAP_MASK (0x3 << 6)
#define RG_MIN_CODE_SHIFT 24
#define RG_MIN_CODE_MASK (0x7 << 24)
#define RG_MIN_CODE_EN_SHIFT 28
#define RG_MIN_CODE_EN_MASK (0x1 << 28)
#define RG_DBG_CLR_SHIFT 29
#define RG_DBG_CLR_MASK (0x1 << 29)
#define RG_APPLY_ONLY_1ST_PAT_SHIFT 30
#define RG_APPLY_ONLY_1ST_PAT_MASK (0x1 << 30)
#define RG_DBGST_OPT_SHIFT 31
#define RG_DBGST_OPT_MASK (0x1 << 31)

#define DPHY_RX_DESKEW_LANE0_CTRL 0x0060
#define DPHY_RX_DESKEW_L0_DELAY_EN_SHIFT 0
#define DPHY_RX_DESKEW_L0_DELAY_EN_MASK (0x1 << 0)
#define RG_DPHY_RX_DESKEW_L0_DELAY_APPLY_SHIFT 1
#define RG_DPHY_RX_DESKEW_L0_DELAY_APPLY_MASK (0x1 << 1)
#define RG_DPHY_RX_DESKEW_L0_DELAY_CODE_SHIFT 8
#define RG_DPHY_RX_DESKEW_L0_DELAY_CODE_MASK (0x3f << 8)
#define RG_DPHY_RX_DESKEW_L0_PERIODIC_SHIFT 16
#define RG_DPHY_RX_DESKEW_L0_PERIODIC_MASK (0x1 << 16)
#define RG_DPHY_RX_DESKEW_L0_PERIODIC_1DIR_ONLY_SHIFT 17
#define RG_DPHY_RX_DESKEW_L0_PERIODIC_1DIR_ONLY_MASK (0x1 << 17)
#define RG_DPHY_RX_DESKEW_L0_PERIODIC_DELAY_CODE_CNT_SHIFT 20
#define RG_DPHY_RX_DESKEW_L0_PERIODIC_DELAY_CODE_CNT_MASK (0xf << 20)

#define DPHY_RX_DESKEW_LANE1_CTRL 0x0064
#define DPHY_RX_DESKEW_L1_DELAY_EN_SHIFT 0
#define DPHY_RX_DESKEW_L1_DELAY_EN_MASK (0x1 << 0)
#define RG_DPHY_RX_DESKEW_L1_DELAY_APPLY_SHIFT 1
#define RG_DPHY_RX_DESKEW_L1_DELAY_APPLY_MASK (0x1 << 1)
#define RG_DPHY_RX_DESKEW_L1_DELAY_CODE_SHIFT 8
#define RG_DPHY_RX_DESKEW_L1_DELAY_CODE_MASK (0x3f << 8)
#define RG_DPHY_RX_DESKEW_L1_PERIODIC_SHIFT 16
#define RG_DPHY_RX_DESKEW_L1_PERIODIC_MASK (0x1 << 16)
#define RG_DPHY_RX_DESKEW_L1_PERIODIC_1DIR_ONLY_SHIFT 17
#define RG_DPHY_RX_DESKEW_L1_PERIODIC_1DIR_ONLY_MASK (0x1 << 17)
#define RG_DPHY_RX_DESKEW_L1_PERIODIC_DELAY_CODE_CNT_SHIFT 20
#define RG_DPHY_RX_DESKEW_L1_PERIODIC_DELAY_CODE_CNT_MASK (0xf << 20)

#define DPHY_RX_DESKEW_LANE2_CTRL 0x0068
#define DPHY_RX_DESKEW_L2_DELAY_EN_SHIFT 0
#define DPHY_RX_DESKEW_L2_DELAY_EN_MASK (0x1 << 0)
#define RG_DPHY_RX_DESKEW_L2_DELAY_APPLY_SHIFT 1
#define RG_DPHY_RX_DESKEW_L2_DELAY_APPLY_MASK (0x1 << 1)
#define RG_DPHY_RX_DESKEW_L2_DELAY_CODE_SHIFT 8
#define RG_DPHY_RX_DESKEW_L2_DELAY_CODE_MASK (0x3f << 8)
#define RG_DPHY_RX_DESKEW_L2_PERIODIC_SHIFT 16
#define RG_DPHY_RX_DESKEW_L2_PERIODIC_MASK (0x1 << 16)
#define RG_DPHY_RX_DESKEW_L2_PERIODIC_1DIR_ONLY_SHIFT 17
#define RG_DPHY_RX_DESKEW_L2_PERIODIC_1DIR_ONLY_MASK (0x1 << 17)
#define RG_DPHY_RX_DESKEW_L2_PERIODIC_DELAY_CODE_CNT_SHIFT 20
#define RG_DPHY_RX_DESKEW_L2_PERIODIC_DELAY_CODE_CNT_MASK (0xf << 20)

#define DPHY_RX_DESKEW_LANE3_CTRL 0x006c
#define DPHY_RX_DESKEW_L3_DELAY_EN_SHIFT 0
#define DPHY_RX_DESKEW_L3_DELAY_EN_MASK (0x1 << 0)
#define RG_DPHY_RX_DESKEW_L3_DELAY_APPLY_SHIFT 1
#define RG_DPHY_RX_DESKEW_L3_DELAY_APPLY_MASK (0x1 << 1)
#define RG_DPHY_RX_DESKEW_L3_DELAY_CODE_SHIFT 8
#define RG_DPHY_RX_DESKEW_L3_DELAY_CODE_MASK (0x3f << 8)
#define RG_DPHY_RX_DESKEW_L3_PERIODIC_SHIFT 16
#define RG_DPHY_RX_DESKEW_L3_PERIODIC_MASK (0x1 << 16)
#define RG_DPHY_RX_DESKEW_L3_PERIODIC_1DIR_ONLY_SHIFT 17
#define RG_DPHY_RX_DESKEW_L3_PERIODIC_1DIR_ONLY_MASK (0x1 << 17)
#define RG_DPHY_RX_DESKEW_L3_PERIODIC_DELAY_CODE_CNT_SHIFT 20
#define RG_DPHY_RX_DESKEW_L3_PERIODIC_DELAY_CODE_CNT_MASK (0xf << 20)

#define DPHY_RX_DESKEW_LANE0_DA_READ 0x0070
#define RO_DA_DPHY_L0_DELAY_EN_SHIFT 0
#define RO_DA_DPHY_L0_DELAY_EN_MASK (0x1 << 0)
#define RO_DA_DPHY_L0_DELAY_APPLY_SHIFT 1
#define RO_DA_DPHY_L0_DELAY_APPLY_MASK (0x1 << 1)
#define RO_DA_DPHY_L0_DELAY_CODE_SHIFT 8
#define RO_DA_DPHY_L0_DELAY_CODE_MASK (0xff << 8)

#define DPHY_RX_DESKEW_LANE1_DA_READ 0x0074
#define RO_DA_DPHY_L1_DELAY_EN_SHIFT 0
#define RO_DA_DPHY_L1_DELAY_EN_MASK (0x1 << 0)
#define RO_DA_DPHY_L1_DELAY_APPLY_SHIFT 1
#define RO_DA_DPHY_L1_DELAY_APPLY_MASK (0x1 << 1)
#define RO_DA_DPHY_L1_DELAY_CODE_SHIFT 8
#define RO_DA_DPHY_L1_DELAY_CODE_MASK (0xff << 8)

#define DPHY_RX_DESKEW_LANE2_DA_READ 0x0078
#define RO_DA_DPHY_L2_DELAY_EN_SHIFT 0
#define RO_DA_DPHY_L2_DELAY_EN_MASK (0x1 << 0)
#define RO_DA_DPHY_L2_DELAY_APPLY_SHIFT 1
#define RO_DA_DPHY_L2_DELAY_APPLY_MASK (0x1 << 1)
#define RO_DA_DPHY_L2_DELAY_CODE_SHIFT 8
#define RO_DA_DPHY_L2_DELAY_CODE_MASK (0xff << 8)

#define DPHY_RX_DESKEW_LANE3_DA_READ 0x007c
#define RO_DA_DPHY_L3_DELAY_EN_SHIFT 0
#define RO_DA_DPHY_L3_DELAY_EN_MASK (0x1 << 0)
#define RO_DA_DPHY_L3_DELAY_APPLY_SHIFT 1
#define RO_DA_DPHY_L3_DELAY_APPLY_MASK (0x1 << 1)
#define RO_DA_DPHY_L3_DELAY_CODE_SHIFT 8
#define RO_DA_DPHY_L3_DELAY_CODE_MASK (0xff << 8)

#define DPHY_RX_DESKEW_LANE4_DA_READ 0x0080
#define RO_DA_DPHY_L4_DELAY_EN_SHIFT 0
#define RO_DA_DPHY_L4_DELAY_EN_MASK (0x1 << 0)
#define RO_DA_DPHY_L4_DELAY_APPLY_SHIFT 1
#define RO_DA_DPHY_L4_DELAY_APPLY_MASK (0x1 << 1)
#define RO_DA_DPHY_L4_DELAY_CODE_SHIFT 8
#define RO_DA_DPHY_L4_DELAY_CODE_MASK (0xff << 8)

#define DPHY_RX_DESKEW_LANE5_DA_READ 0x0084
#define RO_DA_DPHY_L5_DELAY_EN_SHIFT 0
#define RO_DA_DPHY_L5_DELAY_EN_MASK (0x1 << 0)
#define RO_DA_DPHY_L5_DELAY_APPLY_SHIFT 1
#define RO_DA_DPHY_L5_DELAY_APPLY_MASK (0x1 << 1)
#define RO_DA_DPHY_L5_DELAY_CODE_SHIFT 8
#define RO_DA_DPHY_L5_DELAY_CODE_MASK (0xff << 8)

#define DPHY_RX_DESKEW_IRQ_EN 0x0088
#define RG_DPHY_RX_DESKEW_IRQ_EN_SHIFT 0
#define RG_DPHY_RX_DESKEW_IRQ_EN_MASK (0xffffffff << 0)

#define DPHY_RX_DESKEW_IRQ_CLR 0x008c
#define RG_DPHY_RX_DESKEW_IRQ_CLR_SHIFT 0
#define RG_DPHY_RX_DESKEW_IRQ_CLR_MASK (0xffffffff << 0)

#define DPHY_RX_DESKEW_IRQ_STATUS 0x0090
#define RO_DPHY_RX_DESKEW_IRQ_STATUS_SHIFT 0
#define RO_DPHY_RX_DESKEW_IRQ_STATUS_MASK (0xffffffff << 0)

#define DPHY_RX_IRQ_EN 0x0094
#define RG_DPHY_RX_ERR_SOT_SYNC_HS_L0_IRQ_EN_SHIFT 0
#define RG_DPHY_RX_ERR_SOT_SYNC_HS_L0_IRQ_EN_MASK (0x1 << 0)
#define RG_DPHY_RX_ERR_SOT_SYNC_HS_L1_IRQ_EN_SHIFT 1
#define RG_DPHY_RX_ERR_SOT_SYNC_HS_L1_IRQ_EN_MASK (0x1 << 1)
#define RG_DPHY_RX_ERR_SOT_SYNC_HS_L2_IRQ_EN_SHIFT 2
#define RG_DPHY_RX_ERR_SOT_SYNC_HS_L2_IRQ_EN_MASK (0x1 << 2)
#define RG_DPHY_RX_ERR_SOT_SYNC_HS_L3_IRQ_EN_SHIFT 3
#define RG_DPHY_RX_ERR_SOT_SYNC_HS_L3_IRQ_EN_MASK (0x1 << 3)
#define RG_DPHY_RX_DESKEW_IRQ_W1C_EN_SHIFT 30
#define RG_DPHY_RX_DESKEW_IRQ_W1C_EN_MASK (0x1 << 30)
#define RG_DPHY_RX_IRQ_W1C_EN_SHIFT 31
#define RG_DPHY_RX_IRQ_W1C_EN_MASK (0x1 << 31)

#define DPHY_RX_IRQ_CLR 0x0098
#define RG_DPHY_RX_IRQ_CLR_SHIFT 0
#define RG_DPHY_RX_IRQ_CLR_MASK (0xffffffff << 0)

#define DPHY_RX_IRQ_STATUS 0x009c
#define DPHY_RX_ERR_SOT_SYNC_HS_L0_IRQ_SHIFT 0
#define DPHY_RX_ERR_SOT_SYNC_HS_L0_IRQ_MASK (0x1 << 0)
#define DPHY_RX_ERR_SOT_SYNC_HS_L1_IRQ_SHIFT 1
#define DPHY_RX_ERR_SOT_SYNC_HS_L1_IRQ_MASK (0x1 << 1)
#define DPHY_RX_ERR_SOT_SYNC_HS_L2_IRQ_SHIFT 2
#define DPHY_RX_ERR_SOT_SYNC_HS_L2_IRQ_MASK (0x1 << 2)
#define DPHY_RX_ERR_SOT_SYNC_HS_L3_IRQ_SHIFT 3
#define DPHY_RX_ERR_SOT_SYNC_HS_L3_IRQ_MASK (0x1 << 3)

#define DPHY_RX_STATUS_0 0x00a0
#define RO_DPHY_RX_LD0_SYNC_SEQ_POS_NORM_SHIFT 0
#define RO_DPHY_RX_LD0_SYNC_SEQ_POS_NORM_MASK (0x3f << 0)
#define RO_DPHY_RX_LD1_SYNC_SEQ_POS_NORM_SHIFT 8
#define RO_DPHY_RX_LD1_SYNC_SEQ_POS_NORM_MASK (0x3f << 8)
#define RO_DPHY_RX_LD2_SYNC_SEQ_POS_NORM_SHIFT 16
#define RO_DPHY_RX_LD2_SYNC_SEQ_POS_NORM_MASK (0x3f << 16)
#define RO_DPHY_RX_LD3_SYNC_SEQ_POS_NORM_SHIFT 24
#define RO_DPHY_RX_LD3_SYNC_SEQ_POS_NORM_MASK (0x3f << 24)

#define DPHY_RX_STATUS_1 0x00a4
#define RO_DPHY_RX_LD0_SYNC_SEQ_POS_DESKEW_SHIFT 0
#define RO_DPHY_RX_LD0_SYNC_SEQ_POS_DESKEW_MASK (0x3f << 0)
#define RO_DPHY_RX_LD1_SYNC_SEQ_POS_DESKEW_SHIFT 8
#define RO_DPHY_RX_LD1_SYNC_SEQ_POS_DESKEW_MASK (0x3f << 8)
#define RO_DPHY_RX_LD2_SYNC_SEQ_POS_DESKEW_SHIFT 16
#define RO_DPHY_RX_LD2_SYNC_SEQ_POS_DESKEW_MASK (0x3f << 16)
#define RO_DPHY_RX_LD3_SYNC_SEQ_POS_DESKEW_SHIFT 24
#define RO_DPHY_RX_LD3_SYNC_SEQ_POS_DESKEW_MASK (0x3f << 24)

#define DPHY_RX_STATUS_2 0x00b0
#define RO_ERR_SOT_SYNC_HS_CNT_LNRD0_SHIFT 0
#define RO_ERR_SOT_SYNC_HS_CNT_LNRD0_MASK (0xffff << 0)
#define RO_ERR_SOT_SYNC_HS_CNT_LNRD1_SHIFT 16
#define RO_ERR_SOT_SYNC_HS_CNT_LNRD1_MASK (0xffff << 16)

#define DPHY_RX_STATUS_3 0x00b4
#define RO_ERR_SOT_SYNC_HS_CNT_LNRD2_SHIFT 0
#define RO_ERR_SOT_SYNC_HS_CNT_LNRD2_MASK (0xffff << 0)
#define RO_ERR_SOT_SYNC_HS_CNT_LNRD3_SHIFT 16
#define RO_ERR_SOT_SYNC_HS_CNT_LNRD3_MASK (0xffff << 16)

#define DPHY_RX_DESKEW_DBG_MUX 0x00e0
#define RG_DPHY_RX_DESKEW_DBG_MUX_SHIFT 0
#define RG_DPHY_RX_DESKEW_DBG_MUX_MASK (0xff << 0)

#define DPHY_RX_DESKEW_OUT 0x00e4
#define RO_DPHY_RX_DESKEW_DBG_OUT_SHIFT 0
#define RO_DPHY_RX_DESKEW_DBG_OUT_MASK (0xffffffff << 0)

#define DPHY_RX_DESKEW_PATTERN_LENGTH_0 0x00e8
#define RO_DPHY_RX_DESKEW_PATTERN_LENGTH_0_SHIFT 0
#define RO_DPHY_RX_DESKEW_PATTERN_LENGTH_0_MASK (0x3ff << 0)
#define RO_DPHY_RX_DESKEW_PATTERN_LENGTH_1_SHIFT 16
#define RO_DPHY_RX_DESKEW_PATTERN_LENGTH_1_MASK (0x3ff << 16)

#define DPHY_RX_DESKEW_PATTERN_LENGTH_1 0x00ec
#define RO_DPHY_RX_DESKEW_PATTERN_LENGTH_2_SHIFT 0
#define RO_DPHY_RX_DESKEW_PATTERN_LENGTH_2_MASK (0x3ff << 0)
#define RO_DPHY_RX_DESKEW_PATTERN_LENGTH_3_SHIFT 16
#define RO_DPHY_RX_DESKEW_PATTERN_LENGTH_3_MASK (0x3ff << 16)

#define DPHY_RX_SPARE0 0x00f0
#define RG_DPHY_RX_SPARE0_SHIFT 0
#define RG_DPHY_RX_SPARE0_MASK (0xffffffff << 0)

#define DPHY_RX_SPARE1 0x00f4
#define RG_DPHY_RX_SPARE1_SHIFT 0
#define RG_DPHY_RX_SPARE1_MASK (0x3f << 0)
#define RG_POST_CNT_SHIFT 6
#define RG_POST_CNT_MASK (0x3f << 6)
#define RG_DPHY_RX_SPARE0_2_SHIFT 12
#define RG_DPHY_RX_SPARE0_2_MASK (0xfffff << 12)

#define DPHY_RX_BIST_ENABLE 0x0100
#define DPHY_RX_BIST_EN_LANE0_SHIFT 0
#define DPHY_RX_BIST_EN_LANE0_MASK (0x1 << 0)
#define DPHY_RX_BIST_EN_LANE1_SHIFT 1
#define DPHY_RX_BIST_EN_LANE1_MASK (0x1 << 1)
#define DPHY_RX_BIST_EN_LANE2_SHIFT 2
#define DPHY_RX_BIST_EN_LANE2_MASK (0x1 << 2)
#define DPHY_RX_BIST_EN_LANE3_SHIFT 3
#define DPHY_RX_BIST_EN_LANE3_MASK (0x1 << 3)
#define RG_PHY2MAC_CDPHY_GEN_EN_SHIFT 8
#define RG_PHY2MAC_CDPHY_GEN_EN_MASK (0x1 << 8)
#define RG_PHY2MAC_CDPHY_GEN_MODE_SHIFT 9
#define RG_PHY2MAC_CDPHY_GEN_MODE_MASK (0x1 << 9)
#define RG_PHY2MAC_CDPHY_GEN_SEL_SHIFT 10
#define RG_PHY2MAC_CDPHY_GEN_SEL_MASK (0x1 << 10)

#define DPHY_RX_BIST_STATUS 0x0104
#define RO_DPHY_RX_BIST_OK_LANE0_SHIFT 0
#define RO_DPHY_RX_BIST_OK_LANE0_MASK (0x1 << 0)
#define RO_DPHY_RX_BIST_OK_LANE1_SHIFT 1
#define RO_DPHY_RX_BIST_OK_LANE1_MASK (0x1 << 1)
#define RO_DPHY_RX_BIST_OK_LANE2_SHIFT 2
#define RO_DPHY_RX_BIST_OK_LANE2_MASK (0x1 << 2)
#define RO_DPHY_RX_BIST_OK_LANE3_SHIFT 3
#define RO_DPHY_RX_BIST_OK_LANE3_MASK (0x1 << 3)
#define RO_DPHY_RX_BIST_HS_MODE_OK_LANE0_SHIFT 8
#define RO_DPHY_RX_BIST_HS_MODE_OK_LANE0_MASK (0x1 << 8)
#define RO_DPHY_RX_BIST_HS_MODE_OK_LANE1_SHIFT 9
#define RO_DPHY_RX_BIST_HS_MODE_OK_LANE1_MASK (0x1 << 9)
#define RO_DPHY_RX_BIST_HS_MODE_OK_LANE2_SHIFT 10
#define RO_DPHY_RX_BIST_HS_MODE_OK_LANE2_MASK (0x1 << 10)
#define RO_DPHY_RX_BIST_HS_MODE_OK_LANE3_SHIFT 11
#define RO_DPHY_RX_BIST_HS_MODE_OK_LANE3_MASK (0x1 << 11)
#define RO_DPHY_RX_BIST_LP_MODE_OK_LANE0_SHIFT 16
#define RO_DPHY_RX_BIST_LP_MODE_OK_LANE0_MASK (0x1 << 16)
#define RO_DPHY_RX_BIST_LP_MODE_OK_LANE1_SHIFT 17
#define RO_DPHY_RX_BIST_LP_MODE_OK_LANE1_MASK (0x1 << 17)
#define RO_DPHY_RX_BIST_LP_MODE_OK_LANE2_SHIFT 18
#define RO_DPHY_RX_BIST_LP_MODE_OK_LANE2_MASK (0x1 << 18)
#define RO_DPHY_RX_BIST_LP_MODE_OK_LANE3_SHIFT 19
#define RO_DPHY_RX_BIST_LP_MODE_OK_LANE3_MASK (0x1 << 19)

#define DPHY_RX_BIST_CONFIG_0_LANE0 0x0110
#define RG_DPHY_RX_BIST_MODE_LANE0_SHIFT 0
#define RG_DPHY_RX_BIST_MODE_LANE0_MASK (0x3 << 0)
#define RG_DPHY_RX_BIST_PRBS_OUTMODE_LANE0_SHIFT 2
#define RG_DPHY_RX_BIST_PRBS_OUTMODE_LANE0_MASK (0x3 << 2)
#define RG_DPHY_RX_BIST_PRBS_PAT_SEL_LANE0_SHIFT 4
#define RG_DPHY_RX_BIST_PRBS_PAT_SEL_LANE0_MASK (0x7 << 4)
#define RG_DPHY_RX_BIST_PRBS_REVERSE_LANE0_SHIFT 7
#define RG_DPHY_RX_BIST_PRBS_REVERSE_LANE0_MASK (0x1 << 7)
#define RG_DPHY_RX_BIST_HS_RAN_PAT_MASK_N_LANE0_SHIFT 8
#define RG_DPHY_RX_BIST_HS_RAN_PAT_MASK_N_LANE0_MASK (0xff << 8)
#define RG_DPHY_RX_BIST_HS_LENGTH_LANE0_H15B_SHIFT 16
#define RG_DPHY_RX_BIST_HS_LENGTH_LANE0_H15B_MASK (0x7fff << 16)
#define RG_DPHY_RX_BIST_HS_FIX_PAT_LANE0_SHIFT 31
#define RG_DPHY_RX_BIST_HS_FIX_PAT_LANE0_MASK (0x1 << 31)

#define DPHY_RX_BIST_CONFIG_1_LANE0 0x0114
#define RG_DPHY_RX_BIST_HS_LENGTH_LANE0_SHIFT 0
#define RG_DPHY_RX_BIST_HS_LENGTH_LANE0_MASK (0xffffffff << 0)

#define DPHY_RX_BIST_CONFIG_2_LANE0 0x0118
#define RG_DPHY_RX_BIST_LP_MODE_SEQ0_LANE0_SHIFT 0
#define RG_DPHY_RX_BIST_LP_MODE_SEQ0_LANE0_MASK (0x3 << 0)
#define RG_DPHY_RX_BIST_LP_MODE_SEQ1_LANE0_SHIFT 2
#define RG_DPHY_RX_BIST_LP_MODE_SEQ1_LANE0_MASK (0x3 << 2)
#define RG_DPHY_RX_BIST_LP_MODE_SEQ2_LANE0_SHIFT 4
#define RG_DPHY_RX_BIST_LP_MODE_SEQ2_LANE0_MASK (0x3 << 4)
#define RG_DPHY_RX_BIST_LP_MODE_SEQ3_LANE0_SHIFT 6
#define RG_DPHY_RX_BIST_LP_MODE_SEQ3_LANE0_MASK (0x3 << 6)
#define RG_DPHY_RX_BIST_LP_MODE_SEQ4_LANE0_SHIFT 8
#define RG_DPHY_RX_BIST_LP_MODE_SEQ4_LANE0_MASK (0x3 << 8)
#define RG_DPHY_RX_BIST_LP_MODE_LENGTH_LANE0_SHIFT 16
#define RG_DPHY_RX_BIST_LP_MODE_LENGTH_LANE0_MASK (0x7 << 16)
#define RG_DPHY_RX_BIST_HS_LENGTH_LANE0_H12B_SHIFT 19
#define RG_DPHY_RX_BIST_HS_LENGTH_LANE0_H12B_MASK (0xfff << 19)
#define RG_DPHY_RX_BIST_HS_SYNC_DET_UNBLOCK_LANE0_SHIFT 31
#define RG_DPHY_RX_BIST_HS_SYNC_DET_UNBLOCK_LANE0_MASK (0x1 << 31)

#define DPHY_RX_BIST_STATUS_LANE0 0x011c
#define RO_DPHY_RX_BIST_START_LANE0_SHIFT 0
#define RO_DPHY_RX_BIST_START_LANE0_MASK (0x1 << 0)
#define RO_DPHY_RX_BIST_HS_OK_LANE0_SHIFT 1
#define RO_DPHY_RX_BIST_HS_OK_LANE0_MASK (0x1 << 1)
#define RO_DPHY_RX_BIST_DATA_OK_LANE0_SHIFT 2
#define RO_DPHY_RX_BIST_DATA_OK_LANE0_MASK (0x1 << 2)
#define RO_DPHY_RX_BIST_FSM_OK_LANE0_SHIFT 3
#define RO_DPHY_RX_BIST_FSM_OK_LANE0_MASK (0x1 << 3)
#define RO_DPHY_RX_BIST_LP_FAIL_SEQ_NUMBER_LANE0_SHIFT 8
#define RO_DPHY_RX_BIST_LP_FAIL_SEQ_NUMBER_LANE0_MASK (0x7 << 8)
#define RO_DPHY_RX_BIST_LP_FAIL_SEQ_LANE0_SHIFT 12
#define RO_DPHY_RX_BIST_LP_FAIL_SEQ_LANE0_MASK (0x3 << 12)

#define DPHY_RX_BIST_CONFIG_0_LANE1 0x0120
#define RG_DPHY_RX_BIST_MODE_LANE1_SHIFT 0
#define RG_DPHY_RX_BIST_MODE_LANE1_MASK (0x3 << 0)
#define RG_DPHY_RX_BIST_PRBS_OUTMODE_LANE1_SHIFT 2
#define RG_DPHY_RX_BIST_PRBS_OUTMODE_LANE1_MASK (0x3 << 2)
#define RG_DPHY_RX_BIST_PRBS_PAT_SEL_LANE1_SHIFT 4
#define RG_DPHY_RX_BIST_PRBS_PAT_SEL_LANE1_MASK (0x7 << 4)
#define RG_DPHY_RX_BIST_PRBS_REVERSE_LANE1_SHIFT 7
#define RG_DPHY_RX_BIST_PRBS_REVERSE_LANE1_MASK (0x1 << 7)
#define RG_DPHY_RX_BIST_HS_RAN_PAT_MASK_N_LANE1_SHIFT 8
#define RG_DPHY_RX_BIST_HS_RAN_PAT_MASK_N_LANE1_MASK (0xff << 8)
#define RG_DPHY_RX_BIST_HS_LENGTH_LANE1_H15B_SHIFT 16
#define RG_DPHY_RX_BIST_HS_LENGTH_LANE1_H15B_MASK (0x7fff << 16)
#define RG_DPHY_RX_BIST_HS_FIX_PAT_LANE1_SHIFT 31
#define RG_DPHY_RX_BIST_HS_FIX_PAT_LANE1_MASK (0x1 << 31)

#define DPHY_RX_BIST_CONFIG_1_LANE1 0x0124
#define RG_DPHY_RX_BIST_HS_LENGTH_LANE1_SHIFT 0
#define RG_DPHY_RX_BIST_HS_LENGTH_LANE1_MASK (0xffffffff << 0)

#define DPHY_RX_BIST_CONFIG_2_LANE1 0x0128
#define RG_DPHY_RX_BIST_LP_MODE_SEQ0_LANE1_SHIFT 0
#define RG_DPHY_RX_BIST_LP_MODE_SEQ0_LANE1_MASK (0x3 << 0)
#define RG_DPHY_RX_BIST_LP_MODE_SEQ1_LANE1_SHIFT 2
#define RG_DPHY_RX_BIST_LP_MODE_SEQ1_LANE1_MASK (0x3 << 2)
#define RG_DPHY_RX_BIST_LP_MODE_SEQ2_LANE1_SHIFT 4
#define RG_DPHY_RX_BIST_LP_MODE_SEQ2_LANE1_MASK (0x3 << 4)
#define RG_DPHY_RX_BIST_LP_MODE_SEQ3_LANE1_SHIFT 6
#define RG_DPHY_RX_BIST_LP_MODE_SEQ3_LANE1_MASK (0x3 << 6)
#define RG_DPHY_RX_BIST_LP_MODE_SEQ4_LANE1_SHIFT 8
#define RG_DPHY_RX_BIST_LP_MODE_SEQ4_LANE1_MASK (0x3 << 8)
#define RG_DPHY_RX_BIST_LP_MODE_LENGTH_LANE1_SHIFT 16
#define RG_DPHY_RX_BIST_LP_MODE_LENGTH_LANE1_MASK (0x7 << 16)
#define RG_DPHY_RX_BIST_HS_LENGTH_LANE1_H12B_SHIFT 19
#define RG_DPHY_RX_BIST_HS_LENGTH_LANE1_H12B_MASK (0xfff << 19)
#define RG_DPHY_RX_BIST_HS_SYNC_DET_UNBLOCK_LANE1_SHIFT 31
#define RG_DPHY_RX_BIST_HS_SYNC_DET_UNBLOCK_LANE1_MASK (0x1 << 31)

#define DPHY_RX_BIST_STATUS_LANE1 0x012c
#define RO_DPHY_RX_BIST_START_LANE1_SHIFT 0
#define RO_DPHY_RX_BIST_START_LANE1_MASK (0x1 << 0)
#define RO_DPHY_RX_BIST_HS_OK_LANE1_SHIFT 1
#define RO_DPHY_RX_BIST_HS_OK_LANE1_MASK (0x1 << 1)
#define RO_DPHY_RX_BIST_DATA_OK_LANE1_SHIFT 2
#define RO_DPHY_RX_BIST_DATA_OK_LANE1_MASK (0x1 << 2)
#define RO_DPHY_RX_BIST_FSM_OK_LANE1_SHIFT 3
#define RO_DPHY_RX_BIST_FSM_OK_LANE1_MASK (0x1 << 3)
#define RO_DPHY_RX_BIST_LP_FAIL_SEQ_NUMBER_LANE1_SHIFT 8
#define RO_DPHY_RX_BIST_LP_FAIL_SEQ_NUMBER_LANE1_MASK (0x7 << 8)
#define RO_DPHY_RX_BIST_LP_FAIL_SEQ_LANE1_SHIFT 12
#define RO_DPHY_RX_BIST_LP_FAIL_SEQ_LANE1_MASK (0x3 << 12)

#define DPHY_RX_BIST_CONFIG_0_LANE2 0x0130
#define RG_DPHY_RX_BIST_MODE_LANE2_SHIFT 0
#define RG_DPHY_RX_BIST_MODE_LANE2_MASK (0x3 << 0)
#define RG_DPHY_RX_BIST_PRBS_OUTMODE_LANE2_SHIFT 2
#define RG_DPHY_RX_BIST_PRBS_OUTMODE_LANE2_MASK (0x3 << 2)
#define RG_DPHY_RX_BIST_PRBS_PAT_SEL_LANE2_SHIFT 4
#define RG_DPHY_RX_BIST_PRBS_PAT_SEL_LANE2_MASK (0x7 << 4)
#define RG_DPHY_RX_BIST_PRBS_REVERSE_LANE2_SHIFT 7
#define RG_DPHY_RX_BIST_PRBS_REVERSE_LANE2_MASK (0x1 << 7)
#define RG_DPHY_RX_BIST_HS_RAN_PAT_MASK_N_LANE2_SHIFT 8
#define RG_DPHY_RX_BIST_HS_RAN_PAT_MASK_N_LANE2_MASK (0xff << 8)
#define RG_DPHY_RX_BIST_HS_LENGTH_LANE2_H15B_SHIFT 16
#define RG_DPHY_RX_BIST_HS_LENGTH_LANE2_H15B_MASK (0x7fff << 16)
#define RG_DPHY_RX_BIST_HS_FIX_PAT_LANE2_SHIFT 31
#define RG_DPHY_RX_BIST_HS_FIX_PAT_LANE2_MASK (0x1 << 31)

#define DPHY_RX_BIST_CONFIG_1_LANE2 0x0134
#define RG_DPHY_RX_BIST_HS_LENGTH_LANE2_SHIFT 0
#define RG_DPHY_RX_BIST_HS_LENGTH_LANE2_MASK (0xffffffff << 0)

#define DPHY_RX_BIST_CONFIG_2_LANE2 0x0138
#define RG_DPHY_RX_BIST_LP_MODE_SEQ0_LANE2_SHIFT 0
#define RG_DPHY_RX_BIST_LP_MODE_SEQ0_LANE2_MASK (0x3 << 0)
#define RG_DPHY_RX_BIST_LP_MODE_SEQ1_LANE2_SHIFT 2
#define RG_DPHY_RX_BIST_LP_MODE_SEQ1_LANE2_MASK (0x3 << 2)
#define RG_DPHY_RX_BIST_LP_MODE_SEQ2_LANE2_SHIFT 4
#define RG_DPHY_RX_BIST_LP_MODE_SEQ2_LANE2_MASK (0x3 << 4)
#define RG_DPHY_RX_BIST_LP_MODE_SEQ3_LANE2_SHIFT 6
#define RG_DPHY_RX_BIST_LP_MODE_SEQ3_LANE2_MASK (0x3 << 6)
#define RG_DPHY_RX_BIST_LP_MODE_SEQ4_LANE2_SHIFT 8
#define RG_DPHY_RX_BIST_LP_MODE_SEQ4_LANE2_MASK (0x3 << 8)
#define RG_DPHY_RX_BIST_LP_MODE_LENGTH_LANE2_SHIFT 16
#define RG_DPHY_RX_BIST_LP_MODE_LENGTH_LANE2_MASK (0x7 << 16)
#define RG_DPHY_RX_BIST_HS_LENGTH_LANE2_H12B_SHIFT 19
#define RG_DPHY_RX_BIST_HS_LENGTH_LANE2_H12B_MASK (0xfff << 19)
#define RG_DPHY_RX_BIST_HS_SYNC_DET_UNBLOCK_LANE2_SHIFT 31
#define RG_DPHY_RX_BIST_HS_SYNC_DET_UNBLOCK_LANE2_MASK (0x1 << 31)

#define DPHY_RX_BIST_STATUS_LANE2 0x013c
#define RO_DPHY_RX_BIST_START_LANE2_SHIFT 0
#define RO_DPHY_RX_BIST_START_LANE2_MASK (0x1 << 0)
#define RO_DPHY_RX_BIST_HS_OK_LANE2_SHIFT 1
#define RO_DPHY_RX_BIST_HS_OK_LANE2_MASK (0x1 << 1)
#define RO_DPHY_RX_BIST_DATA_OK_LANE2_SHIFT 2
#define RO_DPHY_RX_BIST_DATA_OK_LANE2_MASK (0x1 << 2)
#define RO_DPHY_RX_BIST_FSM_OK_LANE2_SHIFT 3
#define RO_DPHY_RX_BIST_FSM_OK_LANE2_MASK (0x1 << 3)
#define RO_DPHY_RX_BIST_LP_FAIL_SEQ_NUMBER_LANE2_SHIFT 8
#define RO_DPHY_RX_BIST_LP_FAIL_SEQ_NUMBER_LANE2_MASK (0x7 << 8)
#define RO_DPHY_RX_BIST_LP_FAIL_SEQ_LANE2_SHIFT 12
#define RO_DPHY_RX_BIST_LP_FAIL_SEQ_LANE2_MASK (0x3 << 12)

#define DPHY_RX_BIST_CONFIG_0_LANE3 0x0140
#define RG_DPHY_RX_BIST_MODE_LANE3_SHIFT 0
#define RG_DPHY_RX_BIST_MODE_LANE3_MASK (0x3 << 0)
#define RG_DPHY_RX_BIST_PRBS_OUTMODE_LANE3_SHIFT 2
#define RG_DPHY_RX_BIST_PRBS_OUTMODE_LANE3_MASK (0x3 << 2)
#define RG_DPHY_RX_BIST_PRBS_PAT_SEL_LANE3_SHIFT 4
#define RG_DPHY_RX_BIST_PRBS_PAT_SEL_LANE3_MASK (0x7 << 4)
#define RG_DPHY_RX_BIST_PRBS_REVERSE_LANE3_SHIFT 7
#define RG_DPHY_RX_BIST_PRBS_REVERSE_LANE3_MASK (0x1 << 7)
#define RG_DPHY_RX_BIST_HS_RAN_PAT_MASK_N_LANE3_SHIFT 8
#define RG_DPHY_RX_BIST_HS_RAN_PAT_MASK_N_LANE3_MASK (0xff << 8)
#define RG_DPHY_RX_BIST_HS_LENGTH_LANE3_H15B_SHIFT 16
#define RG_DPHY_RX_BIST_HS_LENGTH_LANE3_H15B_MASK (0x7fff << 16)
#define RG_DPHY_RX_BIST_HS_FIX_PAT_LANE3_SHIFT 31
#define RG_DPHY_RX_BIST_HS_FIX_PAT_LANE3_MASK (0x1 << 31)

#define DPHY_RX_BIST_CONFIG_1_LANE3 0x0144
#define RG_DPHY_RX_BIST_HS_LENGTH_LANE3_SHIFT 0
#define RG_DPHY_RX_BIST_HS_LENGTH_LANE3_MASK (0xffffffff << 0)

#define DPHY_RX_BIST_CONFIG_2_LANE3 0x0148
#define RG_DPHY_RX_BIST_LP_MODE_SEQ0_LANE3_SHIFT 0
#define RG_DPHY_RX_BIST_LP_MODE_SEQ0_LANE3_MASK (0x3 << 0)
#define RG_DPHY_RX_BIST_LP_MODE_SEQ1_LANE3_SHIFT 2
#define RG_DPHY_RX_BIST_LP_MODE_SEQ1_LANE3_MASK (0x3 << 2)
#define RG_DPHY_RX_BIST_LP_MODE_SEQ2_LANE3_SHIFT 4
#define RG_DPHY_RX_BIST_LP_MODE_SEQ2_LANE3_MASK (0x3 << 4)
#define RG_DPHY_RX_BIST_LP_MODE_SEQ3_LANE3_SHIFT 6
#define RG_DPHY_RX_BIST_LP_MODE_SEQ3_LANE3_MASK (0x3 << 6)
#define RG_DPHY_RX_BIST_LP_MODE_SEQ4_LANE3_SHIFT 8
#define RG_DPHY_RX_BIST_LP_MODE_SEQ4_LANE3_MASK (0x3 << 8)
#define RG_DPHY_RX_BIST_LP_MODE_LENGTH_LANE3_SHIFT 16
#define RG_DPHY_RX_BIST_LP_MODE_LENGTH_LANE3_MASK (0x7 << 16)
#define RG_DPHY_RX_BIST_HS_LENGTH_LANE3_H12B_SHIFT 19
#define RG_DPHY_RX_BIST_HS_LENGTH_LANE3_H12B_MASK (0xfff << 19)
#define RG_DPHY_RX_BIST_HS_SYNC_DET_UNBLOCK_LANE3_SHIFT 31
#define RG_DPHY_RX_BIST_HS_SYNC_DET_UNBLOCK_LANE3_MASK (0x1 << 31)

#define DPHY_RX_BIST_STATUS_LANE3 0x014c
#define RO_DPHY_RX_BIST_START_LANE3_SHIFT 0
#define RO_DPHY_RX_BIST_START_LANE3_MASK (0x1 << 0)
#define RO_DPHY_RX_BIST_HS_OK_LANE3_SHIFT 1
#define RO_DPHY_RX_BIST_HS_OK_LANE3_MASK (0x1 << 1)
#define RO_DPHY_RX_BIST_DATA_OK_LANE3_SHIFT 2
#define RO_DPHY_RX_BIST_DATA_OK_LANE3_MASK (0x1 << 2)
#define RO_DPHY_RX_BIST_FSM_OK_LANE3_SHIFT 3
#define RO_DPHY_RX_BIST_FSM_OK_LANE3_MASK (0x1 << 3)
#define RO_DPHY_RX_BIST_LP_FAIL_SEQ_NUMBER_LANE3_SHIFT 8
#define RO_DPHY_RX_BIST_LP_FAIL_SEQ_NUMBER_LANE3_MASK (0x7 << 8)
#define RO_DPHY_RX_BIST_LP_FAIL_SEQ_LANE3_SHIFT 12
#define RO_DPHY_RX_BIST_LP_FAIL_SEQ_LANE3_MASK (0x3 << 12)

#define DPHY_RX_BIST_STATUS_WORD_CNT_LANE0 0x0150
#define RO_DPHY_RX_BIST_WORD_CNT_LANE0_0_SHIFT 0
#define RO_DPHY_RX_BIST_WORD_CNT_LANE0_0_MASK (0xffffffff << 0)

#define DPHY_RX_BIST_STATUS_WORD_CNT_LANE0_1 0x0154
#define RO_DPHY_RX_BIST_WORD_CNT_LANE0_1_SHIFT 0
#define RO_DPHY_RX_BIST_WORD_CNT_LANE0_1_MASK (0x7fff << 0)

#define DPHY_RX_BIST_STATUS_WORD_ERR_CNT_LANE0 0x0158
#define RO_DPHY_RX_BIST_WORD_ERR_CNT_LANE0_SHIFT 0
#define RO_DPHY_RX_BIST_WORD_ERR_CNT_LANE0_MASK (0xffffffff << 0)

#define DPHY_RX_BIST_STATUS_WORD_CNT_LANE1 0x015c
#define RO_DPHY_RX_BIST_WORD_CNT_LANE1_0_SHIFT 0
#define RO_DPHY_RX_BIST_WORD_CNT_LANE1_0_MASK (0xffffffff << 0)

#define DPHY_RX_BIST_STATUS_WORD_CNT_LANE1_1 0x0160
#define RO_DPHY_RX_BIST_WORD_CNT_LANE1_1_SHIFT 0
#define RO_DPHY_RX_BIST_WORD_CNT_LANE1_1_MASK (0x7fff << 0)

#define DPHY_RX_BIST_STATUS_WORD_ERR_CNT_LANE1 0x0164
#define RO_DPHY_RX_BIST_WORD_ERR_CNT_LANE1_SHIFT 0
#define RO_DPHY_RX_BIST_WORD_ERR_CNT_LANE1_MASK (0xffffffff << 0)

#define DPHY_RX_BIST_STATUS_WORD_CNT_LANE2 0x0168
#define RO_DPHY_RX_BIST_WORD_CNT_LANE2_0_SHIFT 0
#define RO_DPHY_RX_BIST_WORD_CNT_LANE2_0_MASK (0xffffffff << 0)

#define DPHY_RX_BIST_STATUS_WORD_CNT_LANE2_1 0x016c
#define RO_DPHY_RX_BIST_WORD_CNT_LANE2_1_SHIFT 0
#define RO_DPHY_RX_BIST_WORD_CNT_LANE2_1_MASK (0x7fff << 0)

#define DPHY_RX_BIST_STATUS_WORD_ERR_CNT_LANE2 0x0170
#define RO_DPHY_RX_BIST_WORD_ERR_CNT_LANE2_SHIFT 0
#define RO_DPHY_RX_BIST_WORD_ERR_CNT_LANE2_MASK (0xffffffff << 0)

#define DPHY_RX_BIST_STATUS_WORD_CNT_LANE3 0x0174
#define RO_DPHY_RX_BIST_WORD_CNT_LANE3_0_SHIFT 0
#define RO_DPHY_RX_BIST_WORD_CNT_LANE3_0_MASK (0xffffffff << 0)

#define DPHY_RX_BIST_STATUS_WORD_CNT_LANE3_1 0x0178
#define RO_DPHY_RX_BIST_WORD_CNT_LANE3_1_SHIFT 0
#define RO_DPHY_RX_BIST_WORD_CNT_LANE3_1_MASK (0x7fff << 0)

#define DPHY_RX_BIST_STATUS_WORD_ERR_CNT_LANE3 0x017c
#define RO_DPHY_RX_BIST_WORD_ERR_CNT_LANE3_SHIFT 0
#define RO_DPHY_RX_BIST_WORD_ERR_CNT_LANE3_MASK (0xffffffff << 0)

#define DPHY_DPHYV21_CTRL 0x0180
#define RG_DPHY_CAL_EN_SHIFT 0
#define RG_DPHY_CAL_EN_MASK (0x1 << 0)
#define RG_DPHY_PREAMBLE_EN_SHIFT 1
#define RG_DPHY_PREAMBLE_EN_MASK (0x1 << 1)
#define RG_HSIDLE_EN_SHIFT 2
#define RG_HSIDLE_EN_MASK (0x1 << 2)
#define RG_DPHY_RX_SYNC_METH_SEL_SHIFT 3
#define RG_DPHY_RX_SYNC_METH_SEL_MASK (0x1 << 3)
#define RG_DPHYALP_EN_SHIFT 4
#define RG_DPHYALP_EN_MASK (0x1 << 4)
#define RG_DPHYALP_EN_SEL_SHIFT 5
#define RG_DPHYALP_EN_SEL_MASK (0x1 << 5)
#define RG_DPHYALP_HSRX_EN_SEL_SHIFT 6
#define RG_DPHYALP_HSRX_EN_SEL_MASK (0x1 << 6)
#define RG_DPHYALP_TRAIL_CNT_SHIFT 8
#define RG_DPHYALP_TRAIL_CNT_MASK (0xff << 8)
#define RG_DPHYALP_PKT_END_CNT_SHIFT 16
#define RG_DPHYALP_PKT_END_CNT_MASK (0xff << 16)
#define RG_DPHYALP_SETTLE_CNT_SHIFT 24
#define RG_DPHYALP_SETTLE_CNT_MASK (0xff << 24)

#define DPHY_PRBS_SEED 0x0184
#define CSR_RLRN_PRBS_SEED_SHIFT 0
#define CSR_RLRN_PRBS_SEED_MASK (0xffffffff << 0)

#define DPHY_HS_IDLE_CNT 0x0188
#define RG_CK_DET_BYTE_CK_DIV_SHIFT 0
#define RG_CK_DET_BYTE_CK_DIV_MASK (0xff << 0)
#define RG_CK_DET_CK_CNT_SHIFT 8
#define RG_CK_DET_CK_CNT_MASK (0xff << 8)
#define RG_HSRX_EN_MASK_CNT_SHIFT 16
#define RG_HSRX_EN_MASK_CNT_MASK (0x3f << 16)
#define RG_DIV_CK_DET_SEL_SHIFT 24
#define RG_DIV_CK_DET_SEL_MASK (0x1 << 24)

#define DPHY_DFT_CLR 0x018c
#define RG_DPHY_LP00_2_SYNC_CODE_CLR_SHIFT 0
#define RG_DPHY_LP00_2_SYNC_CODE_CLR_MASK (0x1 << 0)
#define RG_DPHY_ERROR_CMP_CLR_LANE0_SHIFT 1
#define RG_DPHY_ERROR_CMP_CLR_LANE0_MASK (0x1 << 1)
#define RG_DPHY_ERROR_CMP_CLR_LANE1_SHIFT 2
#define RG_DPHY_ERROR_CMP_CLR_LANE1_MASK (0x1 << 2)
#define RG_DPHY_ERROR_CMP_CLR_LANE2_SHIFT 3
#define RG_DPHY_ERROR_CMP_CLR_LANE2_MASK (0x1 << 3)
#define RG_DPHY_ERROR_CMP_CLR_LANE3_SHIFT 4
#define RG_DPHY_ERROR_CMP_CLR_LANE3_MASK (0x1 << 4)
#define DPHY_RX_ERR_SOT_SYNC_HS_CNT_INIT_LNRD3_SHIFT 28
#define DPHY_RX_ERR_SOT_SYNC_HS_CNT_INIT_LNRD3_MASK (0x1 << 28)
#define DPHY_RX_ERR_SOT_SYNC_HS_CNT_INIT_LNRD2_SHIFT 29
#define DPHY_RX_ERR_SOT_SYNC_HS_CNT_INIT_LNRD2_MASK (0x1 << 29)
#define DPHY_RX_ERR_SOT_SYNC_HS_CNT_INIT_LNRD1_SHIFT 30
#define DPHY_RX_ERR_SOT_SYNC_HS_CNT_INIT_LNRD1_MASK (0x1 << 30)
#define DPHY_RX_ERR_SOT_SYNC_HS_CNT_INIT_LNRD0_SHIFT 31
#define DPHY_RX_ERR_SOT_SYNC_HS_CNT_INIT_LNRD0_MASK (0x1 << 31)

#define DPHY_ALT_CAL_CTRL_LANE0 0x0190
#define RG_ALT_CAL_MODE_LANE0_SHIFT 0
#define RG_ALT_CAL_MODE_LANE0_MASK (0x3f << 0)

#define DPHY_ALT_CAL_WORD_CNT0_LANE0 0x0194
#define RG_ALT_CAL_WORD_CNT1_LANE0_SHIFT 0
#define RG_ALT_CAL_WORD_CNT1_LANE0_MASK (0xffff << 0)

#define DPHY_ALT_CAL_WORD_CNT1_LANE0 0x0198
#define RG_ALT_CAL_WORD_CNT0_LANE0_SHIFT 0
#define RG_ALT_CAL_WORD_CNT0_LANE0_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_ERR_CNT_LANE0 0x019c
#define DPHY_ALT_CAL_ERR_CNT_LANE0_RO_ALT_CAL_ERR_CNT_LANE0_SHIFT 0
#define DPHY_ALT_CAL_ERR_CNT_LANE0_RO_ALT_CAL_ERR_CNT_LANE0_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_CTRL_LANE1 0x01a0
#define RG_ALT_CAL_MODE_LANE1_SHIFT 0
#define RG_ALT_CAL_MODE_LANE1_MASK (0x3f << 0)

#define DPHY_ALT_CAL_WORD_CNT0_LANE1 0x01a4
#define RG_ALT_CAL_WORD_CNT1_LANE1_SHIFT 0
#define RG_ALT_CAL_WORD_CNT1_LANE1_MASK (0xffff << 0)

#define DPHY_ALT_CAL_WORD_CNT1_LANE1 0x01a8
#define RG_ALT_CAL_WORD_CNT0_LANE1_SHIFT 0
#define RG_ALT_CAL_WORD_CNT0_LANE1_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_ERR_CNT_LANE1 0x01ac
#define DPHY_ALT_CAL_ERR_CNT_LANE1_RO_ALT_CAL_ERR_CNT_LANE1_SHIFT 0
#define DPHY_ALT_CAL_ERR_CNT_LANE1_RO_ALT_CAL_ERR_CNT_LANE1_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_CTRL_LANE2 0x01b0
#define RG_ALT_CAL_MODE_LANE2_SHIFT 0
#define RG_ALT_CAL_MODE_LANE2_MASK (0x3f << 0)

#define DPHY_ALT_CAL_WORD_CNT0_LANE2 0x01b4
#define RG_ALT_CAL_WORD_CNT1_LANE2_SHIFT 0
#define RG_ALT_CAL_WORD_CNT1_LANE2_MASK (0xffff << 0)

#define DPHY_ALT_CAL_WORD_CNT1_LANE2 0x01b8
#define RG_ALT_CAL_WORD_CNT0_LANE2_SHIFT 0
#define RG_ALT_CAL_WORD_CNT0_LANE2_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_ERR_CNT_LANE2 0x01bc
#define DPHY_ALT_CAL_ERR_CNT_LANE2_RO_ALT_CAL_ERR_CNT_LANE2_SHIFT 0
#define DPHY_ALT_CAL_ERR_CNT_LANE2_RO_ALT_CAL_ERR_CNT_LANE2_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_CTRL_LANE3 0x01c0
#define RG_ALT_CAL_MODE_LANE3_SHIFT 0
#define RG_ALT_CAL_MODE_LANE3_MASK (0x3f << 0)

#define DPHY_ALT_CAL_WORD_CNT0_LANE3 0x01c4
#define RG_ALT_CAL_WORD_CNT1_LANE3_SHIFT 0
#define RG_ALT_CAL_WORD_CNT1_LANE3_MASK (0xffff << 0)

#define DPHY_ALT_CAL_WORD_CNT1_LANE3 0x01c8
#define RG_ALT_CAL_WORD_CNT0_LANE3_SHIFT 0
#define RG_ALT_CAL_WORD_CNT0_LANE3_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_ERR_CNT_LANE3 0x01cc
#define DPHY_ALT_CAL_ERR_CNT_LANE3_RO_ALT_CAL_ERR_CNT_LANE3_SHIFT 0
#define DPHY_ALT_CAL_ERR_CNT_LANE3_RO_ALT_CAL_ERR_CNT_LANE3_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_BURST_CNT_LANE0 0x01d0
#define RG_DPHY_PRBS_BURST_CNT_LANE0_SHIFT 0
#define RG_DPHY_PRBS_BURST_CNT_LANE0_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_BURST_ERRCNT_LANE0 0x01d4
#define RO_DPHY_PRBS_BURST_ERR_CNT_LANE0_SHIFT 0
#define RO_DPHY_PRBS_BURST_ERR_CNT_LANE0_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_BURST_CNT_LANE1 0x01d8
#define RG_DPHY_PRBS_BURST_CNT_LANE1_SHIFT 0
#define RG_DPHY_PRBS_BURST_CNT_LANE1_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_BURST_ERRCNT_LANE1 0x01dc
#define RO_DPHY_PRBS_BURST_ERR_CNT_LANE1_SHIFT 0
#define RO_DPHY_PRBS_BURST_ERR_CNT_LANE1_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_BURST_CNT_LANE2 0x01e0
#define RG_DPHY_PRBS_BURST_CNT_LANE2_SHIFT 0
#define RG_DPHY_PRBS_BURST_CNT_LANE2_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_BURST_ERRCNT_LANE2 0x01e4
#define RO_DPHY_PRBS_BURST_ERR_CNT_LANE2_SHIFT 0
#define RO_DPHY_PRBS_BURST_ERR_CNT_LANE2_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_BURST_CNT_LANE3 0x01e8
#define RG_DPHY_PRBS_BURST_CNT_LANE3_SHIFT 0
#define RG_DPHY_PRBS_BURST_CNT_LANE3_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_BURST_ERRCNT_LANE3 0x01ec
#define RO_DPHY_PRBS_BURST_ERR_CNT_LANE3_SHIFT 0
#define RO_DPHY_PRBS_BURST_ERR_CNT_LANE3_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_PKT_CNT0 0x01f0
#define RG_ALT_CAL_PKT_CNT0_SHIFT 0
#define RG_ALT_CAL_PKT_CNT0_MASK (0xffffffff << 0)

#define DPHY_ALT_CAL_PKT_CNT1 0x01f4
#define RG_ALT_CAL_PKT_CNT1_SHIFT 0
#define RG_ALT_CAL_PKT_CNT1_MASK (0xffff << 0)

#define DPHY_DFT_DATA_SEL 0x0200
#define DPHY_DFT_DATA_SEL_SHIFT 0
#define DPHY_DFT_DATA_SEL_MASK (0x3 << 0)

#define DPHY_USER_DEF_DATA0 0x0224
#define DPHY_USER_DEF_DATA0_SHIFT 0
#define DPHY_USER_DEF_DATA0_MASK (0xffffffff << 0)

#define DPHY_USER_DEF_DATA1 0x0228
#define DPHY_USER_DEF_DATA1_SHIFT 0
#define DPHY_USER_DEF_DATA1_MASK (0xffffffff << 0)

#define DPHY_USER_DEF_DATA2 0x022c
#define DPHY_USER_DEF_DATA2_SHIFT 0
#define DPHY_USER_DEF_DATA2_MASK (0xffffffff << 0)

#define DPHY_USER_DEF_DATA3 0x0230
#define DPHY_USER_DEF_DATA3_SHIFT 0
#define DPHY_USER_DEF_DATA3_MASK (0xffffffff << 0)

#define DPHY_LP00_0_SYNCCODE 0x0234
#define RO_LP00_2_SYNC_CODE_MAX0_SHIFT 0
#define RO_LP00_2_SYNC_CODE_MAX0_MASK (0xffff << 0)
#define RO_LP00_2_SYNC_CODE_MIN0_SHIFT 16
#define RO_LP00_2_SYNC_CODE_MIN0_MASK (0xffff << 16)

#define DPHY_LP00_1_SYNCCODE 0x0238
#define RO_LP00_2_SYNC_CODE_MAX1_SHIFT 0
#define RO_LP00_2_SYNC_CODE_MAX1_MASK (0xffff << 0)
#define RO_LP00_2_SYNC_CODE_MIN1_SHIFT 16
#define RO_LP00_2_SYNC_CODE_MIN1_MASK (0xffff << 16)

#define DPHY_LP00_2_SYNCCODE 0x023c
#define RO_LP00_2_SYNC_CODE_MAX2_SHIFT 0
#define RO_LP00_2_SYNC_CODE_MAX2_MASK (0xffff << 0)
#define RO_LP00_2_SYNC_CODE_MIN2_SHIFT 16
#define RO_LP00_2_SYNC_CODE_MIN2_MASK (0xffff << 16)

#define DPHY_LP00_3_SYNCCODE 0x0240
#define RO_LP00_2_SYNC_CODE_MAX3_SHIFT 0
#define RO_LP00_2_SYNC_CODE_MAX3_MASK (0xffff << 0)
#define RO_LP00_2_SYNC_CODE_MIN3_SHIFT 16
#define RO_LP00_2_SYNC_CODE_MIN3_MASK (0xffff << 16)

#define DPHY_HSYNC_DATA0_0 0x0244
#define RO_DPHY_SYNC_DATA0_0_SHIFT 0
#define RO_DPHY_SYNC_DATA0_0_MASK (0xffffffff << 0)

#define DPHY_HSYNC_DATA0_1 0x0248
#define RO_DPHY_SYNC_DATA0_1_SHIFT 0
#define RO_DPHY_SYNC_DATA0_1_MASK (0xffffffff << 0)

#define DPHY_HSYNC_DATA0_2 0x024c
#define RO_DPHY_SYNC_DATA0_2_SHIFT 0
#define RO_DPHY_SYNC_DATA0_2_MASK (0xffffffff << 0)

#define DPHY_HSYNC_DATA0_3 0x0250
#define RO_DPHY_SYNC_DATA0_3_SHIFT 0
#define RO_DPHY_SYNC_DATA0_3_MASK (0xffffffff << 0)

#define DPHY_HSYNC_DATA1_0 0x0254
#define RO_DPHY_SYNC_DATA1_0_SHIFT 0
#define RO_DPHY_SYNC_DATA1_0_MASK (0xffffffff << 0)

#define DPHY_HSYNC_DATA1_1 0x0258
#define RO_DPHY_SYNC_DATA1_1_SHIFT 0
#define RO_DPHY_SYNC_DATA1_1_MASK (0xffffffff << 0)

#define DPHY_HSYNC_DATA1_2 0x025c
#define RO_DPHY_SYNC_DATA1_2_SHIFT 0
#define RO_DPHY_SYNC_DATA1_2_MASK (0xffffffff << 0)

#define DPHY_HSYNC_DATA1_3 0x0260
#define RO_DPHY_SYNC_DATA1_3_SHIFT 0
#define RO_DPHY_SYNC_DATA1_3_MASK (0xffffffff << 0)

#define DPHY_HSYNC_DATA2_0 0x0264
#define RO_DPHY_SYNC_DATA2_0_SHIFT 0
#define RO_DPHY_SYNC_DATA2_0_MASK (0xffffffff << 0)

#define DPHY_HSYNC_DATA2_1 0x0268
#define RO_DPHY_SYNC_DATA2_1_SHIFT 0
#define RO_DPHY_SYNC_DATA2_1_MASK (0xffffffff << 0)

#define DPHY_HSYNC_DATA2_2 0x026c
#define RO_DPHY_SYNC_DATA2_2_SHIFT 0
#define RO_DPHY_SYNC_DATA2_2_MASK (0xffffffff << 0)

#define DPHY_HSYNC_DATA2_3 0x0270
#define RO_DPHY_SYNC_DATA2_3_SHIFT 0
#define RO_DPHY_SYNC_DATA2_3_MASK (0xffffffff << 0)

#define DPHY_HSYNC_DATA3_0 0x0274
#define RO_DPHY_SYNC_DATA3_0_SHIFT 0
#define RO_DPHY_SYNC_DATA3_0_MASK (0xffffffff << 0)

#define DPHY_HSYNC_DATA3_1 0x0278
#define RO_DPHY_SYNC_DATA3_1_SHIFT 0
#define RO_DPHY_SYNC_DATA3_1_MASK (0xffffffff << 0)

#define DPHY_HSYNC_DATA3_2 0x027c
#define RO_DPHY_SYNC_DATA3_2_SHIFT 0
#define RO_DPHY_SYNC_DATA3_2_MASK (0xffffffff << 0)

#define DPHY_HSYNC_DATA3_3 0x0280
#define RO_DPHY_SYNC_DATA3_3_SHIFT 0
#define RO_DPHY_SYNC_DATA3_3_MASK (0xffffffff << 0)

#define DPHY_ERR_DATA0_0 0x0284
#define RO_DPHY_ERR_DATA0_0_SHIFT 0
#define RO_DPHY_ERR_DATA0_0_MASK (0xffffffff << 0)

#define DPHY_ERR_DATA0_1 0x0288
#define RO_DPHY_ERR_DATA0_1_SHIFT 0
#define RO_DPHY_ERR_DATA0_1_MASK (0xffffffff << 0)

#define DPHY_ERR_DATA0_2 0x028c
#define RO_DPHY_ERR_DATA0_2_SHIFT 0
#define RO_DPHY_ERR_DATA0_2_MASK (0xffffffff << 0)

#define DPHY_ERR_DATA0_3 0x0300
#define RO_DPHY_ERR_DATA0_3_SHIFT 0
#define RO_DPHY_ERR_DATA0_3_MASK (0xffffffff << 0)

#define DPHY_ERR_DATA1_0 0x0304
#define RO_DPHY_ERR_DATA1_0_SHIFT 0
#define RO_DPHY_ERR_DATA1_0_MASK (0xffffffff << 0)

#define DPHY_ERR_DATA1_1 0x0308
#define RO_DPHY_ERR_DATA1_1_SHIFT 0
#define RO_DPHY_ERR_DATA1_1_MASK (0xffffffff << 0)

#define DPHY_ERR_DATA1_2 0x030c
#define RO_DPHY_ERR_DATA1_2_SHIFT 0
#define RO_DPHY_ERR_DATA1_2_MASK (0xffffffff << 0)

#define DPHY_ERR_DATA1_3 0x0310
#define RO_DPHY_ERR_DATA1_3_SHIFT 0
#define RO_DPHY_ERR_DATA1_3_MASK (0xffffffff << 0)

#define DPHY_ERR_DATA2_0 0x0314
#define RO_DPHY_ERR_DATA2_0_SHIFT 0
#define RO_DPHY_ERR_DATA2_0_MASK (0xffffffff << 0)

#define DPHY_ERR_DATA2_1 0x0318
#define RO_DPHY_ERR_DATA2_1_SHIFT 0
#define RO_DPHY_ERR_DATA2_1_MASK (0xffffffff << 0)

#define DPHY_ERR_DATA2_2 0x031c
#define RO_DPHY_ERR_DATA2_2_SHIFT 0
#define RO_DPHY_ERR_DATA2_2_MASK (0xffffffff << 0)

#define DPHY_ERR_DATA2_3 0x0320
#define RO_DPHY_ERR_DATA2_3_SHIFT 0
#define RO_DPHY_ERR_DATA2_3_MASK (0xffffffff << 0)

#define DPHY_ERR_DATA3_0 0x0324
#define RO_DPHY_ERR_DATA3_0_SHIFT 0
#define RO_DPHY_ERR_DATA3_0_MASK (0xffffffff << 0)

#define DPHY_ERR_DATA3_1 0x0328
#define RO_DPHY_ERR_DATA3_1_SHIFT 0
#define RO_DPHY_ERR_DATA3_1_MASK (0xffffffff << 0)

#define DPHY_ERR_DATA3_2 0x032c
#define RO_DPHY_ERR_DATA3_2_SHIFT 0
#define RO_DPHY_ERR_DATA3_2_MASK (0xffffffff << 0)

#define DPHY_ERR_DATA3_3 0x0330
#define RO_DPHY_ERR_DATA3_3_SHIFT 0
#define RO_DPHY_ERR_DATA3_3_MASK (0xffffffff << 0)

#define DPHY_RX_STATE_CHK_EN 0x0334
#define DPHY_RX_STATE_CHK_EN_LANE0_SHIFT 0
#define DPHY_RX_STATE_CHK_EN_LANE0_MASK (0x1 << 0)
#define DPHY_RX_STATE_CHK_EN_LANE1_SHIFT 1
#define DPHY_RX_STATE_CHK_EN_LANE1_MASK (0x1 << 1)
#define DPHY_RX_STATE_CHK_EN_LANE2_SHIFT 2
#define DPHY_RX_STATE_CHK_EN_LANE2_MASK (0x1 << 2)
#define DPHY_RX_STATE_CHK_EN_LANE3_SHIFT 3
#define DPHY_RX_STATE_CHK_EN_LANE3_MASK (0x1 << 3)

#define DPHY_RX_STATE_CHK_TIMER 0x0338
#define RG_DPHY_RX_STATE_CHK_RX_TIMER_CNT_SHIFT 0
#define RG_DPHY_RX_STATE_CHK_RX_TIMER_CNT_MASK (0xffffffff << 0)

#define DPHY_RX_STATE_CHK_STATUS_LANE0 0x033c
#define RO_DPHY_RX_STATE_CHK_ERR_LANE0_SHIFT 0
#define RO_DPHY_RX_STATE_CHK_ERR_LANE0_MASK (0x1 << 0)
#define RO_DPHY_RX_STATE_CHK_ERR_CNT_LANE0_SHIFT 4
#define RO_DPHY_RX_STATE_CHK_ERR_CNT_LANE0_MASK (0x7 << 4)
#define RO_DPHY_RX_STATE_CHK_FAIL_SEQ0_LANE0_SHIFT 16
#define RO_DPHY_RX_STATE_CHK_FAIL_SEQ0_LANE0_MASK (0x7 << 16)
#define RO_DPHY_RX_STATE_CHK_FAIL_SEQ1_LANE0_SHIFT 20
#define RO_DPHY_RX_STATE_CHK_FAIL_SEQ1_LANE0_MASK (0x7 << 20)
#define RO_DPHY_RX_STATE_CHK_FAIL_SEQ2_LANE0_SHIFT 24
#define RO_DPHY_RX_STATE_CHK_FAIL_SEQ2_LANE0_MASK (0x7 << 24)
#define RO_DPHY_RX_STATE_CHK_FAIL_SEQ3_LANE0_SHIFT 28
#define RO_DPHY_RX_STATE_CHK_FAIL_SEQ3_LANE0_MASK (0x7 << 28)

#define DPHY_RX_STATE_CHK_STATUS_LANE1 0x0340
#define RO_DPHY_RX_STATE_CHK_ERR_LANE1_SHIFT 0
#define RO_DPHY_RX_STATE_CHK_ERR_LANE1_MASK (0x1 << 0)
#define RO_DPHY_RX_STATE_CHK_ERR_CNT_LANE1_SHIFT 4
#define RO_DPHY_RX_STATE_CHK_ERR_CNT_LANE1_MASK (0x7 << 4)
#define RO_DPHY_RX_STATE_CHK_FAIL_SEQ0_LANE1_SHIFT 16
#define RO_DPHY_RX_STATE_CHK_FAIL_SEQ0_LANE1_MASK (0x7 << 16)
#define RO_DPHY_RX_STATE_CHK_FAIL_SEQ1_LANE1_SHIFT 20
#define RO_DPHY_RX_STATE_CHK_FAIL_SEQ1_LANE1_MASK (0x7 << 20)
#define RO_DPHY_RX_STATE_CHK_FAIL_SEQ2_LANE1_SHIFT 24
#define RO_DPHY_RX_STATE_CHK_FAIL_SEQ2_LANE1_MASK (0x7 << 24)
#define RO_DPHY_RX_STATE_CHK_FAIL_SEQ3_LANE1_SHIFT 28
#define RO_DPHY_RX_STATE_CHK_FAIL_SEQ3_LANE1_MASK (0x7 << 28)

#define DPHY_RX_STATE_CHK_STATUS_LANE2 0x0344
#define RO_DPHY_RX_STATE_CHK_ERR_LANE2_SHIFT 0
#define RO_DPHY_RX_STATE_CHK_ERR_LANE2_MASK (0x1 << 0)
#define RO_DPHY_RX_STATE_CHK_ERR_CNT_LANE2_SHIFT 4
#define RO_DPHY_RX_STATE_CHK_ERR_CNT_LANE2_MASK (0x7 << 4)
#define RO_DPHY_RX_STATE_CHK_FAIL_SEQ0_LANE2_SHIFT 16
#define RO_DPHY_RX_STATE_CHK_FAIL_SEQ0_LANE2_MASK (0x7 << 16)
#define RO_DPHY_RX_STATE_CHK_FAIL_SEQ1_LANE2_SHIFT 20
#define RO_DPHY_RX_STATE_CHK_FAIL_SEQ1_LANE2_MASK (0x7 << 20)
#define RO_DPHY_RX_STATE_CHK_FAIL_SEQ2_LANE2_SHIFT 24
#define RO_DPHY_RX_STATE_CHK_FAIL_SEQ2_LANE2_MASK (0x7 << 24)
#define RO_DPHY_RX_STATE_CHK_FAIL_SEQ3_LANE2_SHIFT 28
#define RO_DPHY_RX_STATE_CHK_FAIL_SEQ3_LANE2_MASK (0x7 << 28)

#define DPHY_RX_STATE_CHK_STATUS_LANE3 0x0348
#define RO_DPHY_RX_STATE_CHK_ERR_LANE3_SHIFT 0
#define RO_DPHY_RX_STATE_CHK_ERR_LANE3_MASK (0x1 << 0)
#define RO_DPHY_RX_STATE_CHK_ERR_CNT_LANE3_SHIFT 4
#define RO_DPHY_RX_STATE_CHK_ERR_CNT_LANE3_MASK (0x7 << 4)
#define RO_DPHY_RX_STATE_CHK_FAIL_SEQ0_LANE3_SHIFT 16
#define RO_DPHY_RX_STATE_CHK_FAIL_SEQ0_LANE3_MASK (0x7 << 16)
#define RO_DPHY_RX_STATE_CHK_FAIL_SEQ1_LANE3_SHIFT 20
#define RO_DPHY_RX_STATE_CHK_FAIL_SEQ1_LANE3_MASK (0x7 << 20)
#define RO_DPHY_RX_STATE_CHK_FAIL_SEQ2_LANE3_SHIFT 24
#define RO_DPHY_RX_STATE_CHK_FAIL_SEQ2_LANE3_MASK (0x7 << 24)
#define RO_DPHY_RX_STATE_CHK_FAIL_SEQ3_LANE3_SHIFT 28
#define RO_DPHY_RX_STATE_CHK_FAIL_SEQ3_LANE3_MASK (0x7 << 28)

#define CDPHY_DEBUG_PORT_SELECT 0x034c
#define RG_CSI_CDPHY_DBG_PORT_SEL_SHIFT 0
#define RG_CSI_CDPHY_DBG_PORT_SEL_MASK (0xffffffff << 0)

#define CDPHY_DEBUG_MODE_SELECT 0x0350
#define RG_CSI_CDPHY_DBG_MODE_SEL_SHIFT 0
#define RG_CSI_CDPHY_DBG_MODE_SEL_MASK (0xffff << 0)

#define CDPHY_DEBUG_OUT_READ 0x0354
#define RO_CSI_CDPHY_DBG_OUT_READ_SHIFT 0
#define RO_CSI_CDPHY_DBG_OUT_READ_MASK (0xffffffff << 0)

#define DPHY_RX_INIT 0x0358
#define RG_DPHY_CSI2_TINIT_CNT_SHIFT 0
#define RG_DPHY_CSI2_TINIT_CNT_MASK (0xfffff << 0)
#define RG_DPHY_CSI2_TINIT_CNT_EN_SHIFT 31
#define RG_DPHY_CSI2_TINIT_CNT_EN_MASK (0x1 << 31)

#define DPHY_SETTLE_TO_SYNC_DET_CNT_CTRL 0x035c
#define DPHY_SETTLE_TO_SYNC_DET_CNT_RST_SHIFT 0
#define DPHY_SETTLE_TO_SYNC_DET_CNT_RST_MASK (0x1 << 0)

#define DPHY_SETTLE_TO_SYNC_DET_CNT_RD 0x0360
#define RO_DPHY_SETTLE_TO_SYNC_DET_MIN_CNT_LD0_SHIFT 0
#define RO_DPHY_SETTLE_TO_SYNC_DET_MIN_CNT_LD0_MASK (0xff << 0)
#define RO_DPHY_SETTLE_TO_SYNC_DET_MIN_CNT_LD1_SHIFT 8
#define RO_DPHY_SETTLE_TO_SYNC_DET_MIN_CNT_LD1_MASK (0xff << 8)
#define RO_DPHY_SETTLE_TO_SYNC_DET_MIN_CNT_LD2_SHIFT 16
#define RO_DPHY_SETTLE_TO_SYNC_DET_MIN_CNT_LD2_MASK (0xff << 16)
#define RO_DPHY_SETTLE_TO_SYNC_DET_MIN_CNT_LD3_SHIFT 24
#define RO_DPHY_SETTLE_TO_SYNC_DET_MIN_CNT_LD3_MASK (0xff << 24)

#define DPHY_CK_TIME_IN_POST_CTRL 0x0364
#define DPHY_RX_CK_TIME_IN_POST_CNT_RST_SHIFT 0
#define DPHY_RX_CK_TIME_IN_POST_CNT_RST_MASK (0x1 << 0)

#define DPHY_CK_TIME_IN_POST_DATA 0x0368
#define RO_DPHY_RX_CK_TIME_IN_POST_MIN_CNT_LD0_SHIFT 0
#define RO_DPHY_RX_CK_TIME_IN_POST_MIN_CNT_LD0_MASK (0xff << 0)
#define RO_DPHY_RX_CK_TIME_IN_POST_MIN_CNT_LD1_SHIFT 8
#define RO_DPHY_RX_CK_TIME_IN_POST_MIN_CNT_LD1_MASK (0xff << 8)
#define RO_DPHY_RX_CK_TIME_IN_POST_MIN_CNT_LD2_SHIFT 16
#define RO_DPHY_RX_CK_TIME_IN_POST_MIN_CNT_LD2_MASK (0xff << 16)
#define RO_DPHY_RX_CK_TIME_IN_POST_MIN_CNT_LD3_SHIFT 24
#define RO_DPHY_RX_CK_TIME_IN_POST_MIN_CNT_LD3_MASK (0xff << 24)

#define DPHY_FSM_FLUSH_CTRL 0x0370
#define CSI_DPHY_LN0_FLUSH_EN_SHIFT 0
#define CSI_DPHY_LN0_FLUSH_EN_MASK (0x1 << 0)
#define CSI_DPHY_LN1_FLUSH_EN_SHIFT 1
#define CSI_DPHY_LN1_FLUSH_EN_MASK (0x1 << 1)
#define CSI_DPHY_LN2_FLUSH_EN_SHIFT 2
#define CSI_DPHY_LN2_FLUSH_EN_MASK (0x1 << 2)
#define CSI_DPHY_LN3_FLUSH_EN_SHIFT 3
#define CSI_DPHY_LN3_FLUSH_EN_MASK (0x1 << 3)

#define DPHY_FSM_TRAIL_RTERM_OFF 0x0374
#define CSI_DPHY_LN0_TRAIL_RTERM_OFF_SHIFT 0
#define CSI_DPHY_LN0_TRAIL_RTERM_OFF_MASK (0x1 << 0)
#define CSI_DPHY_LN1_TRAIL_RTERM_OFF_SHIFT 1
#define CSI_DPHY_LN1_TRAIL_RTERM_OFF_MASK (0x1 << 1)
#define CSI_DPHY_LN2_TRAIL_RTERM_OFF_SHIFT 2
#define CSI_DPHY_LN2_TRAIL_RTERM_OFF_MASK (0x1 << 2)
#define CSI_DPHY_LN3_TRAIL_RTERM_OFF_SHIFT 3
#define CSI_DPHY_LN3_TRAIL_RTERM_OFF_MASK (0x1 << 3)

#define DPHY_FSM_ANA_SYNC_INIT_CTRL 0x0378
#define CSI_DPHY_L0_ANA_SYNC_INIT_EARLY_SHIFT 0
#define CSI_DPHY_L0_ANA_SYNC_INIT_EARLY_MASK (0x1 << 0)
#define CSI_DPHY_L1_ANA_SYNC_INIT_EARLY_SHIFT 1
#define CSI_DPHY_L1_ANA_SYNC_INIT_EARLY_MASK (0x1 << 1)
#define CSI_DPHY_L2_ANA_SYNC_INIT_EARLY_SHIFT 2
#define CSI_DPHY_L2_ANA_SYNC_INIT_EARLY_MASK (0x1 << 2)
#define CSI_DPHY_L3_ANA_SYNC_INIT_EARLY_SHIFT 3
#define CSI_DPHY_L3_ANA_SYNC_INIT_EARLY_MASK (0x1 << 3)

#define DPHY_ALP_PKT_END_USE_TRAIL 0x0380
#define CSI_DPHY_L0_ALP_PKT_END_USE_TRAIL_SHIFT 0
#define CSI_DPHY_L0_ALP_PKT_END_USE_TRAIL_MASK (0x1 << 0)
#define CSI_DPHY_L0_ALP_PKT_END_TRAIL_HIT_CNT_SHIFT 1
#define CSI_DPHY_L0_ALP_PKT_END_TRAIL_HIT_CNT_MASK (0x7f << 1)
#define CSI_DPHY_L1_ALP_PKT_END_USE_TRAIL_SHIFT 8
#define CSI_DPHY_L1_ALP_PKT_END_USE_TRAIL_MASK (0x1 << 8)
#define CSI_DPHY_L1_ALP_PKT_END_TRAIL_HIT_CNT_SHIFT 9
#define CSI_DPHY_L1_ALP_PKT_END_TRAIL_HIT_CNT_MASK (0x7f << 9)
#define CSI_DPHY_L2_ALP_PKT_END_USE_TRAIL_SHIFT 16
#define CSI_DPHY_L2_ALP_PKT_END_USE_TRAIL_MASK (0x1 << 16)
#define CSI_DPHY_L2_ALP_PKT_END_TRAIL_HIT_CNT_SHIFT 17
#define CSI_DPHY_L2_ALP_PKT_END_TRAIL_HIT_CNT_MASK (0x7f << 17)
#define CSI_DPHY_L3_ALP_PKT_END_USE_TRAIL_SHIFT 24
#define CSI_DPHY_L3_ALP_PKT_END_USE_TRAIL_MASK (0x1 << 24)
#define CSI_DPHY_L3_ALP_PKT_END_TRAIL_HIT_CNT_SHIFT 25
#define CSI_DPHY_L3_ALP_PKT_END_TRAIL_HIT_CNT_MASK (0x7f << 25)

#define DPHY_MISC_COUNTER_CTRL 0x0384
#define CSI_MISSING_SYNC_INIT_DET_CNT_EN_SHIFT 0
#define CSI_MISSING_SYNC_INIT_DET_CNT_EN_MASK (0xf << 0)
#define CSI_SYNC_DET_CNT_EN_SHIFT 4
#define CSI_SYNC_DET_CNT_EN_MASK (0xf << 4)
#define CSI_SYNC_INIT_CNT_EN_SHIFT 8
#define CSI_SYNC_INIT_CNT_EN_MASK (0xf << 8)
#define CSI_LANE_SKEW_CNT_MASK_SHIFT 12
#define CSI_LANE_SKEW_CNT_MASK_MASK (0xf << 12)
#define CSI_LANE_SKEW_CNT_EN_SHIFT 16
#define CSI_LANE_SKEW_CNT_EN_MASK (0x1 << 16)
#define CSI_DPHY_MEA_TRAIL_CNT_EN_SHIFT 17
#define CSI_DPHY_MEA_TRAIL_CNT_EN_MASK (0xf << 17)

#define DPHY_LD0_SYNC_INIT_DET_CNT 0x0388
#define DPHY_LD0_SYNC_DET_CNT_SHIFT 0
#define DPHY_LD0_SYNC_DET_CNT_MASK (0xffff << 0)
#define DPHY_LD0_SYNC_INIT_CNT_SHIFT 16
#define DPHY_LD0_SYNC_INIT_CNT_MASK (0xffff << 16)

#define DPHY_LD0_MISSING_SYNC_INIT_DET_CNT 0x038c
#define DPHY_LD0_MISSING_SYNC_DET_CNT_SHIFT 0
#define DPHY_LD0_MISSING_SYNC_DET_CNT_MASK (0x7fff << 0)
#define DPHY_LD0_MISSING_SYNC_DET_SHIFT 15
#define DPHY_LD0_MISSING_SYNC_DET_MASK (0x1 << 15)
#define DPHY_LD0_MISSING_SYNC_INIT_CNT_SHIFT 16
#define DPHY_LD0_MISSING_SYNC_INIT_CNT_MASK (0x7fff << 16)
#define DPHY_LD0_MISSING_SYNC_INIT_SHIFT 31
#define DPHY_LD0_MISSING_SYNC_INIT_MASK (0x1 << 31)

#define DPHY_LD1_SYNC_INIT_DET_CNT 0x0390
#define DPHY_LD1_SYNC_DET_CNT_SHIFT 0
#define DPHY_LD1_SYNC_DET_CNT_MASK (0xffff << 0)
#define DPHY_LD1_SYNC_INIT_CNT_SHIFT 16
#define DPHY_LD1_SYNC_INIT_CNT_MASK (0xffff << 16)

#define DPHY_LD1_MISSING_SYNC_INIT_DET_CNT 0x0394
#define DPHY_LD1_MISSING_SYNC_DET_CNT_SHIFT 0
#define DPHY_LD1_MISSING_SYNC_DET_CNT_MASK (0x7fff << 0)
#define DPHY_LD1_MISSING_SYNC_DET_SHIFT 15
#define DPHY_LD1_MISSING_SYNC_DET_MASK (0x1 << 15)
#define DPHY_LD1_MISSING_SYNC_INIT_CNT_SHIFT 16
#define DPHY_LD1_MISSING_SYNC_INIT_CNT_MASK (0x7fff << 16)
#define DPHY_LD1_MISSING_SYNC_INIT_SHIFT 31
#define DPHY_LD1_MISSING_SYNC_INIT_MASK (0x1 << 31)

#define DPHY_LD2_SYNC_INIT_DET_CNT 0x0398
#define DPHY_LD2_SYNC_DET_CNT_SHIFT 0
#define DPHY_LD2_SYNC_DET_CNT_MASK (0xffff << 0)
#define DPHY_LD2_SYNC_INIT_CNT_SHIFT 16
#define DPHY_LD2_SYNC_INIT_CNT_MASK (0xffff << 16)

#define DPHY_LD2_MISSING_SYNC_INIT_DET_CNT 0x039c
#define DPHY_LD2_MISSING_SYNC_DET_CNT_SHIFT 0
#define DPHY_LD2_MISSING_SYNC_DET_CNT_MASK (0x7fff << 0)
#define DPHY_LD2_MISSING_SYNC_DET_SHIFT 15
#define DPHY_LD2_MISSING_SYNC_DET_MASK (0x1 << 15)
#define DPHY_LD2_MISSING_SYNC_INIT_CNT_SHIFT 16
#define DPHY_LD2_MISSING_SYNC_INIT_CNT_MASK (0x7fff << 16)
#define DPHY_LD2_MISSING_SYNC_INIT_SHIFT 31
#define DPHY_LD2_MISSING_SYNC_INIT_MASK (0x1 << 31)

#define DPHY_LD3_SYNC_INIT_DET_CNT 0x03a0
#define DPHY_LD3_SYNC_DET_CNT_SHIFT 0
#define DPHY_LD3_SYNC_DET_CNT_MASK (0xffff << 0)
#define DPHY_LD3_SYNC_INIT_CNT_SHIFT 16
#define DPHY_LD3_SYNC_INIT_CNT_MASK (0xffff << 16)

#define DPHY_LD3_MISSING_SYNC_INIT_DET_CNT 0x03a4
#define DPHY_LD3_MISSING_SYNC_DET_CNT_SHIFT 0
#define DPHY_LD3_MISSING_SYNC_DET_CNT_MASK (0x7fff << 0)
#define DPHY_LD3_MISSING_SYNC_DET_SHIFT 15
#define DPHY_LD3_MISSING_SYNC_DET_MASK (0x1 << 15)
#define DPHY_LD3_MISSING_SYNC_INIT_CNT_SHIFT 16
#define DPHY_LD3_MISSING_SYNC_INIT_CNT_MASK (0x7fff << 16)
#define DPHY_LD3_MISSING_SYNC_INIT_SHIFT 31
#define DPHY_LD3_MISSING_SYNC_INIT_MASK (0x1 << 31)

#define DPHY_LANE_SKEW_CNT_0 0x03a8
#define LD0_SKEW_CNT_MIN_SHIFT 0
#define LD0_SKEW_CNT_MIN_MASK (0xf << 0)
#define LD0_SKEW_CNT_MAX_SHIFT 4
#define LD0_SKEW_CNT_MAX_MASK (0xf << 4)
#define LD0_SKEW_CNT_SHIFT 8
#define LD0_SKEW_CNT_MASK (0xf << 8)
#define LD1_SKEW_CNT_MIN_SHIFT 16
#define LD1_SKEW_CNT_MIN_MASK (0xf << 16)
#define LD1_SKEW_CNT_MAX_SHIFT 20
#define LD1_SKEW_CNT_MAX_MASK (0xf << 20)
#define LD1_SKEW_CNT_SHIFT 24
#define LD1_SKEW_CNT_MASK (0xf << 24)

#define DPHY_LANE_SKEW_CNT_1 0x03ac
#define LD2_SKEW_CNT_MIN_SHIFT 0
#define LD2_SKEW_CNT_MIN_MASK (0xf << 0)
#define LD2_SKEW_CNT_MAX_SHIFT 4
#define LD2_SKEW_CNT_MAX_MASK (0xf << 4)
#define LD2_SKEW_CNT_SHIFT 8
#define LD2_SKEW_CNT_MASK (0xf << 8)
#define LD3_SKEW_CNT_MIN_SHIFT 16
#define LD3_SKEW_CNT_MIN_MASK (0xf << 16)
#define LD3_SKEW_CNT_MAX_SHIFT 20
#define LD3_SKEW_CNT_MAX_MASK (0xf << 20)
#define LD3_SKEW_CNT_SHIFT 24
#define LD3_SKEW_CNT_MASK (0xf << 24)

#define DPHY_ALP_TRAIL_HIT_CNT 0x03b0
#define RO_DPHY_L0_ALP_TRAIL_HIT_CNT_SHIFT 0
#define RO_DPHY_L0_ALP_TRAIL_HIT_CNT_MASK (0x7f << 0)
#define RO_DPHY_L1_ALP_TRAIL_HIT_CNT_SHIFT 8
#define RO_DPHY_L1_ALP_TRAIL_HIT_CNT_MASK (0x7f << 8)
#define RO_DPHY_L2_ALP_TRAIL_HIT_CNT_SHIFT 16
#define RO_DPHY_L2_ALP_TRAIL_HIT_CNT_MASK (0x7f << 16)
#define RO_DPHY_L3_ALP_TRAIL_HIT_CNT_SHIFT 24
#define RO_DPHY_L3_ALP_TRAIL_HIT_CNT_MASK (0x7f << 24)

#define DPHY_VALID_PIPE_CTRL 0x03b4
#define DPHY_VALID_PIPE_EN_SHIFT 0
#define DPHY_VALID_PIPE_EN_MASK (0x1 << 0)

#define DPHY_MEA_TRAIL_CNT_0 0x03b8
#define RO_DPHY_L0_MEA_TRAIL_CNT_SHIFT 0
#define RO_DPHY_L0_MEA_TRAIL_CNT_MASK (0x3ff << 0)
#define RO_DPHY_L0_MEA_TRAIL_CNT_MIN_SHIFT 10
#define RO_DPHY_L0_MEA_TRAIL_CNT_MIN_MASK (0x3ff << 10)
#define RO_DPHY_L0_MEA_TRAIL_CNT_MAX_SHIFT 20
#define RO_DPHY_L0_MEA_TRAIL_CNT_MAX_MASK (0x3ff << 20)

#define DPHY_MEA_TRAIL_CNT_1 0x03bc
#define RO_DPHY_L1_MEA_TRAIL_CNT_SHIFT 0
#define RO_DPHY_L1_MEA_TRAIL_CNT_MASK (0x3ff << 0)
#define RO_DPHY_L1_MEA_TRAIL_CNT_MIN_SHIFT 10
#define RO_DPHY_L1_MEA_TRAIL_CNT_MIN_MASK (0x3ff << 10)
#define RO_DPHY_L1_MEA_TRAIL_CNT_MAX_SHIFT 20
#define RO_DPHY_L1_MEA_TRAIL_CNT_MAX_MASK (0x3ff << 20)

#define DPHY_MEA_TRAIL_CNT_2 0x03c0
#define RO_DPHY_L2_MEA_TRAIL_CNT_SHIFT 0
#define RO_DPHY_L2_MEA_TRAIL_CNT_MASK (0x3ff << 0)
#define RO_DPHY_L2_MEA_TRAIL_CNT_MIN_SHIFT 10
#define RO_DPHY_L2_MEA_TRAIL_CNT_MIN_MASK (0x3ff << 10)
#define RO_DPHY_L2_MEA_TRAIL_CNT_MAX_SHIFT 20
#define RO_DPHY_L2_MEA_TRAIL_CNT_MAX_MASK (0x3ff << 20)

#define DPHY_MEA_TRAIL_CNT_3 0x03c4
#define RO_DPHY_L3_MEA_TRAIL_CNT_SHIFT 0
#define RO_DPHY_L3_MEA_TRAIL_CNT_MASK (0x3ff << 0)
#define RO_DPHY_L3_MEA_TRAIL_CNT_MIN_SHIFT 10
#define RO_DPHY_L3_MEA_TRAIL_CNT_MIN_MASK (0x3ff << 10)
#define RO_DPHY_L3_MEA_TRAIL_CNT_MAX_SHIFT 20
#define RO_DPHY_L3_MEA_TRAIL_CNT_MAX_MASK (0x3ff << 20)

#define DPHY_LRTE_CTRL 0x0400
#define DPHY_LRTE_PHYA_SYNC_INIT_ENABLE_SHIFT 0
#define DPHY_LRTE_PHYA_SYNC_INIT_ENABLE_MASK (0x1 << 0)

#define DPHY_PRBS_PAT_GEN_CTRL_0 0x0404
#define PRBS_PAT_GEN_LP01_STAGE_CNT_SHIFT 0
#define PRBS_PAT_GEN_LP01_STAGE_CNT_MASK (0x1f << 0)
#define PRBS_PAT_GEN_IDLE_STAGE_CNT_SHIFT 5
#define PRBS_PAT_GEN_IDLE_STAGE_CNT_MASK (0x3 << 5)
#define PRBS_PAT_GEN_PRE_STAGE_CNT_SHIFT 7
#define PRBS_PAT_GEN_PRE_STAGE_CNT_MASK (0x1ff << 7)
#define PRBS_PAT_GEN_LONG_PKT_CNT_SHIFT 16
#define PRBS_PAT_GEN_LONG_PKT_CNT_MASK (0x1f << 16)
#define PRBS_PAT_GEN_DT_SHIFT 22
#define PRBS_PAT_GEN_DT_MASK (0x1 << 22)
#define PRBS_PAT_GEN_VC_SHIFT 23
#define PRBS_PAT_GEN_VC_MASK (0x1f << 23)
#define CDPHY_PRBS_PAT_GEN_MODE_SHIFT 28
#define CDPHY_PRBS_PAT_GEN_MODE_MASK (0x7 << 28)
#define PRBS_PAT_GEN_DPHY_EN_SHIFT 31
#define PRBS_PAT_GEN_DPHY_EN_MASK (0x1 << 31)

#define DPHY_PRBS_PAT_GEN_CTRL_1 0x0408
#define PRBS_PAT_GEN_CPHY_LRTE_FOOT_CNT_SHIFT 12
#define PRBS_PAT_GEN_CPHY_LRTE_FOOT_CNT_MASK (0x1f << 12)
#define PRBS_PAT_GEN_LRTE_EN_SHIFT 17
#define PRBS_PAT_GEN_LRTE_EN_MASK (0x1 << 17)
#define PRBS_PAT_GEN_TRAIL_STAGE_CNT_SHIFT 23
#define PRBS_PAT_GEN_TRAIL_STAGE_CNT_MASK (0xff << 23)

#define DPHY_PRBS_PAT_GEN_CTRL_2 0x040c
#define DPHY_PRBS_PAT_GEN_LN3_SKEW_CYCLE_CNT_SHIFT 0
#define DPHY_PRBS_PAT_GEN_LN3_SKEW_CYCLE_CNT_MASK (0x7 << 0)
#define DPHY_PRBS_PAT_GEN_LN2_SKEW_CYCLE_CNT_SHIFT 3
#define DPHY_PRBS_PAT_GEN_LN2_SKEW_CYCLE_CNT_MASK (0x7 << 3)
#define DPHY_PRBS_PAT_GEN_LN1_SKEW_CYCLE_CNT_SHIFT 6
#define DPHY_PRBS_PAT_GEN_LN1_SKEW_CYCLE_CNT_MASK (0x7 << 6)
#define DPHY_PRBS_PAT_GEN_LN0_SKEW_CYCLE_CNT_SHIFT 9
#define DPHY_PRBS_PAT_GEN_LN0_SKEW_CYCLE_CNT_MASK (0x7 << 9)
#define DPHY_PRBS_PAT_GEN_SKEW_EN_SHIFT 12
#define DPHY_PRBS_PAT_GEN_SKEW_EN_MASK (0x1 << 12)
#define DPHY_PRBS_PAT_GEN_NONSTOP_LONG_PKT_EN_SHIFT 13
#define DPHY_PRBS_PAT_GEN_NONSTOP_LONG_PKT_EN_MASK (0x1 << 13)

#define DPHY_PRBS_PAT_GEN_STATUS 0x0410
#define PRBS_PAT_GEN_DONE_SHIFT 0
#define PRBS_PAT_GEN_DONE_MASK (0x1 << 0)

#define DPHY_LP_CNT_CTRL 0x0414
#define DPHY_LP11_CNT_SHIFT 0
#define DPHY_LP11_CNT_MASK (0x7f << 0)
#define DPHY_LP11_CNT_EN_SHIFT 7
#define DPHY_LP11_CNT_EN_MASK (0x1 << 7)
#define DPHY_LP10_CNT_SHIFT 8
#define DPHY_LP10_CNT_MASK (0x7f << 8)
#define DPHY_LP10_CNT_EN_SHIFT 15
#define DPHY_LP10_CNT_EN_MASK (0x1 << 15)
#define DPHY_LP01_CNT_SHIFT 16
#define DPHY_LP01_CNT_MASK (0x7f << 16)
#define DPHY_LP01_CNT_EN_SHIFT 23
#define DPHY_LP01_CNT_EN_MASK (0x1 << 23)
#define DPHY_LP00_CNT_SHIFT 24
#define DPHY_LP00_CNT_MASK (0x7f << 24)
#define DPHY_LP00_CNT_EN_SHIFT 31
#define DPHY_LP00_CNT_EN_MASK (0x1 << 31)

#define DPHY_IDLE_SYNC_INIT_CTRL 0x0418
#define DPHY_IDLE_SYNC_INIT_CNT_SHIFT 0
#define DPHY_IDLE_SYNC_INIT_CNT_MASK (0xff << 0)
#define DPHY_IDLE_DUMMY_VALID_EN_SHIFT 8
#define DPHY_IDLE_DUMMY_VALID_EN_MASK (0x1 << 8)

#endif
