/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */

#ifndef __SENINF_TOP_C_HEADER_H__
#define __SENINF_TOP_C_HEADER_H__

#define SENINF_TOP_CTRL 0x0000
#define SENINF_TOP_SW_RST_SHIFT 0
#define SENINF_TOP_SW_RST_MASK (0x1 << 0)
#define SENINF_TOP_N3D_SW_RST_SHIFT 4
#define SENINF_TOP_N3D_SW_RST_MASK (0x1 << 4)
#define RG_SENINF1_PCAM_PCLK_SEL_SHIFT 8
#define RG_SENINF1_PCAM_PCLK_SEL_MASK (0x1 << 8)
#define RG_SENINF2_PCAM_PCLK_SEL_SHIFT 9
#define RG_SENINF2_PCAM_PCLK_SEL_MASK (0x1 << 9)
#define RG_SENINF1_PCAM_PCLK_EN_SHIFT 12
#define RG_SENINF1_PCAM_PCLK_EN_MASK (0x1 << 12)
#define RG_SENINF2_PCAM_PCLK_EN_SHIFT 13
#define RG_SENINF2_PCAM_PCLK_EN_MASK (0x1 << 13)
#define RG_SLICE_FIFO_FULL_OPT_SHIFT 16
#define RG_SLICE_FIFO_FULL_OPT_MASK (0x1 << 16)
#define RG_SENINF_MUX_RDY_OPT_SHIFT 20
#define RG_SENINF_MUX_RDY_OPT_MASK (0x1 << 20)
#define RG_SENINF_CSIPORT_SPLIT_SHIFT 24
#define RG_SENINF_CSIPORT_SPLIT_MASK (0x3f << 24)

#define SENINF_TOP_CTRL2 0x0004
#define RG_CSI2_AFIFOA_POP_HALF_EN_SHIFT 0
#define RG_CSI2_AFIFOA_POP_HALF_EN_MASK (0x3f << 0)
#define RG_CSI2_AFIFOB_POP_HALF_EN_SHIFT 8
#define RG_CSI2_AFIFOB_POP_HALF_EN_MASK (0x3f << 8)

#define SENINF_TOP_DBG_CTRL 0x0008
#define RG_SENINF_TOP_DBG_SEL_SHIFT 0
#define RG_SENINF_TOP_DBG_SEL_MASK (0x1f << 0)
#define RG_SENINF_TOP_DBG_BYTE0_SEL_SHIFT 16
#define RG_SENINF_TOP_DBG_BYTE0_SEL_MASK (0x3 << 16)
#define RG_SENINF_TOP_DBG_BYTE1_SEL_SHIFT 20
#define RG_SENINF_TOP_DBG_BYTE1_SEL_MASK (0x3 << 20)
#define RG_SENINF_TOP_DBG_BYTE2_SEL_SHIFT 24
#define RG_SENINF_TOP_DBG_BYTE2_SEL_MASK (0x3 << 24)
#define RG_SENINF_TOP_DBG_BYTE3_SEL_SHIFT 28
#define RG_SENINF_TOP_DBG_BYTE3_SEL_MASK (0x3 << 28)

#define SENINF_TOP_MUX_CTRL_0 0x0010
#define RG_SENINF_MUX1_SRC_SEL_SHIFT 0
#define RG_SENINF_MUX1_SRC_SEL_MASK (0x1f << 0)
#define RG_SENINF_MUX2_SRC_SEL_SHIFT 8
#define RG_SENINF_MUX2_SRC_SEL_MASK (0x1f << 8)
#define RG_SENINF_MUX3_SRC_SEL_SHIFT 16
#define RG_SENINF_MUX3_SRC_SEL_MASK (0x1f << 16)
#define RG_SENINF_MUX4_SRC_SEL_SHIFT 24
#define RG_SENINF_MUX4_SRC_SEL_MASK (0x1f << 24)

#define SENINF_TOP_MUX_CTRL_1 0x0014
#define RG_SENINF_MUX5_SRC_SEL_SHIFT 0
#define RG_SENINF_MUX5_SRC_SEL_MASK (0x1f << 0)
#define RG_SENINF_MUX6_SRC_SEL_SHIFT 8
#define RG_SENINF_MUX6_SRC_SEL_MASK (0x1f << 8)
#define RG_SENINF_MUX7_SRC_SEL_SHIFT 16
#define RG_SENINF_MUX7_SRC_SEL_MASK (0x1f << 16)
#define RG_SENINF_MUX8_SRC_SEL_SHIFT 24
#define RG_SENINF_MUX8_SRC_SEL_MASK (0x1f << 24)

#define SENINF_TOP_MUX_CTRL_2 0x0018
#define RG_SENINF_MUX9_SRC_SEL_SHIFT 0
#define RG_SENINF_MUX9_SRC_SEL_MASK (0x1f << 0)
#define RG_SENINF_MUX10_SRC_SEL_SHIFT 8
#define RG_SENINF_MUX10_SRC_SEL_MASK (0x1f << 8)
#define RG_SENINF_MUX11_SRC_SEL_SHIFT 16
#define RG_SENINF_MUX11_SRC_SEL_MASK (0x1f << 16)
#define RG_SENINF_MUX12_SRC_SEL_SHIFT 24
#define RG_SENINF_MUX12_SRC_SEL_MASK (0x1f << 24)

#define SENINF_TOP_MUX_CTRL_3 0x001c
#define RG_SENINF_MUX13_SRC_SEL_SHIFT 0
#define RG_SENINF_MUX13_SRC_SEL_MASK (0x1f << 0)
#define RG_SENINF_MUX14_SRC_SEL_SHIFT 8
#define RG_SENINF_MUX14_SRC_SEL_MASK (0x1f << 8)
#define RG_SENINF_MUX15_SRC_SEL_SHIFT 16
#define RG_SENINF_MUX15_SRC_SEL_MASK (0x1f << 16)
#define RG_SENINF_MUX16_SRC_SEL_SHIFT 24
#define RG_SENINF_MUX16_SRC_SEL_MASK (0x1f << 24)

#define SENINF_TOP_MUX_CTRL_4 0x0020
#define RG_SENINF_MUX17_SRC_SEL_SHIFT 0
#define RG_SENINF_MUX17_SRC_SEL_MASK (0x1f << 0)
#define RG_SENINF_MUX18_SRC_SEL_SHIFT 8
#define RG_SENINF_MUX18_SRC_SEL_MASK (0x1f << 8)
#define RG_SENINF_MUX19_SRC_SEL_SHIFT 16
#define RG_SENINF_MUX19_SRC_SEL_MASK (0x1f << 16)
#define RG_SENINF_MUX20_SRC_SEL_SHIFT 24
#define RG_SENINF_MUX20_SRC_SEL_MASK (0x1f << 24)

#define SENINF_TOP_MUX_CTRL_5 0x0024
#define RG_SENINF_MUX21_SRC_SEL_SHIFT 0
#define RG_SENINF_MUX21_SRC_SEL_MASK (0x1f << 0)
#define RG_SENINF_MUX22_SRC_SEL_SHIFT 8
#define RG_SENINF_MUX22_SRC_SEL_MASK (0x1f << 8)

#define SENINF_TOP_SLICE_CHK_CTRL 0x0050
#define RG_PRBS_CHK_MODE_SHIFT 0
#define RG_PRBS_CHK_MODE_MASK (0x3f << 0)

#define SENINF_TOP_SLICE_CHK_EN 0x0054
#define RG_PRBS_CHK_EN_SHIFT 0
#define RG_PRBS_CHK_EN_MASK (0x3f << 0)

#define SENINF_TOP_SLICE_CHK_STATUS 0x0058
#define RO_PRBS_CHK_DONE_SHIFT 0
#define RO_PRBS_CHK_DONE_MASK (0x3f << 0)
#define RO_PRBS_CHK_FAIL_SHIFT 16
#define RO_PRBS_CHK_FAIL_MASK (0x3f << 16)

#define SENINF_TOP_N3D_A_CTRL 0x0070
#define RG_N3D_SENINF1_VSYNC_SRC_SEL_A_SHIFT 0
#define RG_N3D_SENINF1_VSYNC_SRC_SEL_A_MASK (0xf << 0)
#define RG_N3D_SENINF2_VSYNC_SRC_SEL_A_SHIFT 8
#define RG_N3D_SENINF2_VSYNC_SRC_SEL_A_MASK (0xf << 8)

#define SENINF_TOP_N3D_B_CTRL 0x0074
#define RG_N3D_SENINF1_VSYNC_SRC_SEL_B_SHIFT 0
#define RG_N3D_SENINF1_VSYNC_SRC_SEL_B_MASK (0xf << 0)
#define RG_N3D_SENINF2_VSYNC_SRC_SEL_B_SHIFT 8
#define RG_N3D_SENINF2_VSYNC_SRC_SEL_B_MASK (0xf << 8)

#define SENINF_TOP_IRQ_EN 0x0080
#define RG_SENINF_TOP_IRQ_EN_SHIFT 0
#define RG_SENINF_TOP_IRQ_EN_MASK (0xfff << 0)

#define SENINF_TOP_IRQ_STS 0x0084
#define RG_SENINF_TOP_IRQ_STATUS_SHIFT 0
#define RG_SENINF_TOP_IRQ_STATUS_MASK (0xfff << 0)

#define SENINF_TOP_AFIFOBIST_CTRL0 0x0090
#define RG_CSI2_AFIFO_BISTA_RST_B_SHIFT 0
#define RG_CSI2_AFIFO_BISTA_RST_B_MASK (0x3f << 0)
#define RG_CSI2_AFIFO_BISTB_RST_B_SHIFT 8
#define RG_CSI2_AFIFO_BISTB_RST_B_MASK (0x3f << 8)

#define SENINF_TOP_AFIFOBIST_CTRL1 0x0094
#define RG_CSI2_AFIFO_BISTA_EN_SHIFT 0
#define RG_CSI2_AFIFO_BISTA_EN_MASK (0x3f << 0)
#define RG_CSI2_AFIFO_BISTB_EN_SHIFT 8
#define RG_CSI2_AFIFO_BISTB_EN_MASK (0x3f << 8)

#define SENINF_TOP_AFIFOBIST_CTRL2 0x0098
#define RG_CSI2_AFIFO_BISTA_MODE_SHIFT 0
#define RG_CSI2_AFIFO_BISTA_MODE_MASK (0x3f << 0)
#define RG_CSI2_AFIFO_BISTB_MODE_SHIFT 8
#define RG_CSI2_AFIFO_BISTB_MODE_MASK (0x3f << 8)

#define SENINF_TOP_AFIFOBIST_SETTING 0x009c
#define RG_CSI2_SENINF_TOP_AFIFO_BIST_WRT_LENGTH_SHIFT 0
#define RG_CSI2_SENINF_TOP_AFIFO_BIST_WRT_LENGTH_MASK (0xf << 0)
#define RG_CSI2_SENINF_TOP_AFIFO_BIST_STP_LENGTH_SHIFT 4
#define RG_CSI2_SENINF_TOP_AFIFO_BIST_STP_LENGTH_MASK (0xf << 4)
#define RG_CSI2_SENINF_TOP_AFIFO_BIST_SEED_SEL_SHIFT 8
#define RG_CSI2_SENINF_TOP_AFIFO_BIST_SEED_SEL_MASK (0x1 << 8)
#define RG_CSI2_SENINF_TOP_AFIFO_BIST_LENGTH_SHIFT 16
#define RG_CSI2_SENINF_TOP_AFIFO_BIST_LENGTH_MASK (0xffff << 16)

#define SENINF_TOP_AFIFOBIST_STATUS0 0x00a0
#define RO_CSI2_ISP_AFIFO_BIST0A_DONE_SHIFT 0
#define RO_CSI2_ISP_AFIFO_BIST0A_DONE_MASK (0x1 << 0)
#define RO_CSI2_ISP_AFIFO_BIST0A_PASS_SHIFT 1
#define RO_CSI2_ISP_AFIFO_BIST0A_PASS_MASK (0x1ff << 1)
#define RO_CSI2_ISP_AFIFO_BIST0A_FAIL_SHIFT 10
#define RO_CSI2_ISP_AFIFO_BIST0A_FAIL_MASK (0x1ff << 10)
#define RO_CSI2_ISP_AFIFO_BIST0B_DONE_SHIFT 20
#define RO_CSI2_ISP_AFIFO_BIST0B_DONE_MASK (0x1 << 20)
#define RO_CSI2_ISP_AFIFO_BIST0B_PASS_SHIFT 21
#define RO_CSI2_ISP_AFIFO_BIST0B_PASS_MASK (0x1f << 21)
#define RO_CSI2_ISP_AFIFO_BIST0B_FAIL_SHIFT 26
#define RO_CSI2_ISP_AFIFO_BIST0B_FAIL_MASK (0x1f << 26)

#define SENINF_TOP_AFIFOBIST_STATUS1 0x00a4
#define RO_CSI2_ISP_AFIFO_BIST1A_DONE_SHIFT 0
#define RO_CSI2_ISP_AFIFO_BIST1A_DONE_MASK (0x1 << 0)
#define RO_CSI2_ISP_AFIFO_BIST1A_PASS_SHIFT 1
#define RO_CSI2_ISP_AFIFO_BIST1A_PASS_MASK (0x1ff << 1)
#define RO_CSI2_ISP_AFIFO_BIST1A_FAIL_SHIFT 10
#define RO_CSI2_ISP_AFIFO_BIST1A_FAIL_MASK (0x1ff << 10)
#define RO_CSI2_ISP_AFIFO_BIST1B_DONE_SHIFT 20
#define RO_CSI2_ISP_AFIFO_BIST1B_DONE_MASK (0x1 << 20)
#define RO_CSI2_ISP_AFIFO_BIST1B_PASS_SHIFT 21
#define RO_CSI2_ISP_AFIFO_BIST1B_PASS_MASK (0x1f << 21)
#define RO_CSI2_ISP_AFIFO_BIST1B_FAIL_SHIFT 26
#define RO_CSI2_ISP_AFIFO_BIST1B_FAIL_MASK (0x1f << 26)

#define SENINF_TOP_AFIFOBIST_STATUS2 0x00a8
#define RO_CSI2_ISP_AFIFO_BIST2A_DONE_SHIFT 0
#define RO_CSI2_ISP_AFIFO_BIST2A_DONE_MASK (0x1 << 0)
#define RO_CSI2_ISP_AFIFO_BIST2A_PASS_SHIFT 1
#define RO_CSI2_ISP_AFIFO_BIST2A_PASS_MASK (0x1ff << 1)
#define RO_CSI2_ISP_AFIFO_BIST2A_FAIL_SHIFT 10
#define RO_CSI2_ISP_AFIFO_BIST2A_FAIL_MASK (0x1ff << 10)
#define RO_CSI2_ISP_AFIFO_BIST2B_DONE_SHIFT 20
#define RO_CSI2_ISP_AFIFO_BIST2B_DONE_MASK (0x1 << 20)
#define RO_CSI2_ISP_AFIFO_BIST2B_PASS_SHIFT 21
#define RO_CSI2_ISP_AFIFO_BIST2B_PASS_MASK (0x1f << 21)
#define RO_CSI2_ISP_AFIFO_BIST2B_FAIL_SHIFT 26
#define RO_CSI2_ISP_AFIFO_BIST2B_FAIL_MASK (0x1f << 26)

#define SENINF_TOP_AFIFOBIST_STATUS3 0x00ac
#define RO_CSI2_ISP_AFIFO_BIST3A_DONE_SHIFT 0
#define RO_CSI2_ISP_AFIFO_BIST3A_DONE_MASK (0x1 << 0)
#define RO_CSI2_ISP_AFIFO_BIST3A_PASS_SHIFT 1
#define RO_CSI2_ISP_AFIFO_BIST3A_PASS_MASK (0x1ff << 1)
#define RO_CSI2_ISP_AFIFO_BIST3A_FAIL_SHIFT 10
#define RO_CSI2_ISP_AFIFO_BIST3A_FAIL_MASK (0x1ff << 10)
#define RO_CSI2_ISP_AFIFO_BIST3B_DONE_SHIFT 20
#define RO_CSI2_ISP_AFIFO_BIST3B_DONE_MASK (0x1 << 20)
#define RO_CSI2_ISP_AFIFO_BIST3B_PASS_SHIFT 21
#define RO_CSI2_ISP_AFIFO_BIST3B_PASS_MASK (0x1f << 21)
#define RO_CSI2_ISP_AFIFO_BIST3B_FAIL_SHIFT 26
#define RO_CSI2_ISP_AFIFO_BIST3B_FAIL_MASK (0x1f << 26)

#define SENINF_TOP_AFIFOBIST_STATUS4 0x00b0
#define RO_CSI2_ISP_AFIFO_BIST4A_DONE_SHIFT 0
#define RO_CSI2_ISP_AFIFO_BIST4A_DONE_MASK (0x1 << 0)
#define RO_CSI2_ISP_AFIFO_BIST4A_PASS_SHIFT 1
#define RO_CSI2_ISP_AFIFO_BIST4A_PASS_MASK (0x1ff << 1)
#define RO_CSI2_ISP_AFIFO_BIST4A_FAIL_SHIFT 10
#define RO_CSI2_ISP_AFIFO_BIST4A_FAIL_MASK (0x1ff << 10)
#define RO_CSI2_ISP_AFIFO_BIST4B_DONE_SHIFT 20
#define RO_CSI2_ISP_AFIFO_BIST4B_DONE_MASK (0x1 << 20)
#define RO_CSI2_ISP_AFIFO_BIST4B_PASS_SHIFT 21
#define RO_CSI2_ISP_AFIFO_BIST4B_PASS_MASK (0x1f << 21)
#define RO_CSI2_ISP_AFIFO_BIST4B_FAIL_SHIFT 26
#define RO_CSI2_ISP_AFIFO_BIST4B_FAIL_MASK (0x1f << 26)

#define SENINF_TOP_AFIFOBIST_STATUS5 0x00b4
#define RO_CSI2_ISP_AFIFO_BIST5A_DONE_SHIFT 0
#define RO_CSI2_ISP_AFIFO_BIST5A_DONE_MASK (0x1 << 0)
#define RO_CSI2_ISP_AFIFO_BIST5A_PASS_SHIFT 1
#define RO_CSI2_ISP_AFIFO_BIST5A_PASS_MASK (0x1ff << 1)
#define RO_CSI2_ISP_AFIFO_BIST5A_FAIL_SHIFT 10
#define RO_CSI2_ISP_AFIFO_BIST5A_FAIL_MASK (0x1ff << 10)
#define RO_CSI2_ISP_AFIFO_BIST5B_DONE_SHIFT 20
#define RO_CSI2_ISP_AFIFO_BIST5B_DONE_MASK (0x1 << 20)
#define RO_CSI2_ISP_AFIFO_BIST5B_PASS_SHIFT 21
#define RO_CSI2_ISP_AFIFO_BIST5B_PASS_MASK (0x1f << 21)
#define RO_CSI2_ISP_AFIFO_BIST5B_FAIL_SHIFT 26
#define RO_CSI2_ISP_AFIFO_BIST5B_FAIL_MASK (0x1f << 26)

#define SENINF_TOP_AOV_SECURE_TOP_MUX0 0x00c0
#define RG_SECURE_TOP_MUX_LOCK_SHIFT 0
#define RG_SECURE_TOP_MUX_LOCK_MASK (0x3fffff << 0)

#define SENINF_TOP_AOV_SECURE_TOP_MUX1 0x00c4
#define RG_TOP_MUX_AOV_SECURE_EXCLUDE_0_SHIFT 0
#define RG_TOP_MUX_AOV_SECURE_EXCLUDE_0_MASK (0xfff << 0)

#define SENINF_TOP_AOV_SECURE_TOP_MUX2 0x00c8
#define RG_TOP_MUX_AOV_SECURE_EXCLUDE_1_SHIFT 0
#define RG_TOP_MUX_AOV_SECURE_EXCLUDE_1_MASK (0xfff << 0)

#define SENINF_TOP_AOV_SECURE_TOP_MUX3 0x00cc
#define RO_SECURE_EXCLUDE_MASK_VIO_STATUS_SHIFT 0
#define RO_SECURE_EXCLUDE_MASK_VIO_STATUS_MASK (0x3fffff << 0)

#define SENINF_TOP_AOV_SECURE_SENINF_MUX 0x00d0
#define RG_SECURE_SENINF_MUX_LOCK_SHIFT 0
#define RG_SECURE_SENINF_MUX_LOCK_MASK (0x3fffff << 0)

#define SENINF_TOP_SPARE 0x00f8
#define RG_SENINF_TOP_SPARE_0_SHIFT 0
#define RG_SENINF_TOP_SPARE_0_MASK (0xff << 0)
#define RG_SENINF_TOP_SPARE_1_SHIFT 16
#define RG_SENINF_TOP_SPARE_1_MASK (0xff << 16)

#define SENINF_TOP_FIFO_THRESH 0x00fc
#define RG_FIFO_ALMOST_FULL_THRESHOLD_SHIFT 0
#define RG_FIFO_ALMOST_FULL_THRESHOLD_MASK (0xffff << 0)
#define RG_FIFO_ALMOST_FULL_PULSE_WIDTH_SHIFT 16
#define RG_FIFO_ALMOST_FULL_PULSE_WIDTH_MASK (0xffff << 16)

#endif
