/*  SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (C) 2019 MediaTek Inc.
 */
#ifndef __MET_GPU_MONITOR_H__
#define __MET_GPU_MONITOR_H__

#define	MET_GPU_STALL_MONITOR
#define IO_ADDR_GPU_STALL		0x1021c000
#define IO_SIZE_GPU_STALL		0x1000
#define OFFSET_STALL_GPU_M0_CHECK	0x200
#define OFFSET_STALL_GPU_M1_CHECK	0x204
#define OFFSET_STALL_GPU_M0_EMI_CHECK	0x208
#define OFFSET_STALL_GPU_M1_EMI_CHECK	0x20c

#endif	/* __MET_GPU_MONITOR_H__ */
