/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * Copyright (c) 2021 MediaTek Inc.
 */

#ifndef __CB_INFRA_RGU_REGS_H__
#define __CB_INFRA_RGU_REGS_H__
#include "hal_common.h"
#ifdef __cplusplus
extern "C" {
#endif
#define CB_INFRA_RGU_BASE \
	0x70028000
#define CB_INFRA_RGU_HIF_MEM_CTL_PD_ADDR \
	(CB_INFRA_RGU_BASE + 0x01C)
#define CB_INFRA_RGU_WF_SUBSYS_RST_ADDR \
	(CB_INFRA_RGU_BASE + 0x600)
#define CB_INFRA_RGU_BT_SUBSYS_RST_ADDR \
	(CB_INFRA_RGU_BASE + 0x610)
#define CB_INFRA_RGU_SLP_PROT_RDY_STAT_ADDR \
	(CB_INFRA_RGU_BASE + 0x730)
#define CB_INFRA_RGU_HIF_MEM_CTL_PD_DUMMY_ECO_ADDR \
	CB_INFRA_RGU_HIF_MEM_CTL_PD_ADDR
#define CB_INFRA_RGU_HIF_MEM_CTL_PD_DUMMY_ECO_MASK \
	0xFF000000
#define CB_INFRA_RGU_HIF_MEM_CTL_PD_DUMMY_ECO_SHFT \
	24
#define CB_INFRA_RGU_WF_SUBSYS_RST_BYPASS_WFDMA_2_SLP_PROT_ADDR \
	CB_INFRA_RGU_WF_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_WF_SUBSYS_RST_BYPASS_WFDMA_2_SLP_PROT_MASK \
	0x00010000
#define CB_INFRA_RGU_WF_SUBSYS_RST_BYPASS_WFDMA_2_SLP_PROT_SHFT \
	16
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_WHOLE_PATH_RST_REVERT_CYCLE_ADDR \
	CB_INFRA_RGU_WF_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_WHOLE_PATH_RST_REVERT_CYCLE_MASK \
	0x0000FF00
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_WHOLE_PATH_RST_REVERT_CYCLE_SHFT \
	8
#define CB_INFRA_RGU_WF_SUBSYS_RST_PAD_WF_SUBSYS_RST_EN_ADDR \
	CB_INFRA_RGU_WF_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_WF_SUBSYS_RST_PAD_WF_SUBSYS_RST_EN_MASK \
	0x00000080
#define CB_INFRA_RGU_WF_SUBSYS_RST_PAD_WF_SUBSYS_RST_EN_SHFT \
	7
#define CB_INFRA_RGU_WF_SUBSYS_RST_BYPASS_WFDMA_SLP_PROT_ADDR \
	CB_INFRA_RGU_WF_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_WF_SUBSYS_RST_BYPASS_WFDMA_SLP_PROT_MASK \
	0x00000040
#define CB_INFRA_RGU_WF_SUBSYS_RST_BYPASS_WFDMA_SLP_PROT_SHFT \
	6
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_WHOLE_PATH_RST_REVERT_EN_ADDR \
	CB_INFRA_RGU_WF_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_WHOLE_PATH_RST_REVERT_EN_MASK \
	0x00000020
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_WHOLE_PATH_RST_REVERT_EN_SHFT \
	5
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_SUBSYS_RST_ADDR \
	CB_INFRA_RGU_WF_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_SUBSYS_RST_MASK \
	0x00000010
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_SUBSYS_RST_SHFT \
	4
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_CRYPTO_BYPASS_SUBSYS_RST_ADDR \
	CB_INFRA_RGU_WF_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_CRYPTO_BYPASS_SUBSYS_RST_MASK \
	0x00000008
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_CRYPTO_BYPASS_SUBSYS_RST_SHFT \
	3
#define CB_INFRA_RGU_WF_SUBSYS_RST_WFSYS_PDN_RST_EN_ADDR \
	CB_INFRA_RGU_WF_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_WF_SUBSYS_RST_WFSYS_PDN_RST_EN_MASK \
	0x00000004
#define CB_INFRA_RGU_WF_SUBSYS_RST_WFSYS_PDN_RST_EN_SHFT \
	2
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_PATH_BUS_RST_ADDR \
	CB_INFRA_RGU_WF_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_PATH_BUS_RST_MASK \
	0x00000002
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_PATH_BUS_RST_SHFT \
	1
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_WHOLE_PATH_RST_ADDR \
	CB_INFRA_RGU_WF_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_WHOLE_PATH_RST_MASK \
	0x00000001
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_WHOLE_PATH_RST_SHFT \
	0
#define CB_INFRA_RGU_BT_SUBSYS_RST_BYPASS_BTDMA_2_SLP_PROT_ADDR \
	CB_INFRA_RGU_BT_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_BT_SUBSYS_RST_BYPASS_BTDMA_2_SLP_PROT_MASK \
	0x00010000
#define CB_INFRA_RGU_BT_SUBSYS_RST_BYPASS_BTDMA_2_SLP_PROT_SHFT \
	16
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_WHOLE_PATH_RST_REVERT_CYCLE_ADDR \
	CB_INFRA_RGU_BT_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_WHOLE_PATH_RST_REVERT_CYCLE_MASK \
	0x0000FF00
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_WHOLE_PATH_RST_REVERT_CYCLE_SHFT \
	8
#define CB_INFRA_RGU_BT_SUBSYS_RST_PAD_BT_SUBSYS_RST_EN_ADDR \
	CB_INFRA_RGU_BT_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_BT_SUBSYS_RST_PAD_BT_SUBSYS_RST_EN_MASK \
	0x00000080
#define CB_INFRA_RGU_BT_SUBSYS_RST_PAD_BT_SUBSYS_RST_EN_SHFT \
	7
#define CB_INFRA_RGU_BT_SUBSYS_RST_BYPASS_WFDMA_2_SLP_PROT_ADDR \
	CB_INFRA_RGU_BT_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_BT_SUBSYS_RST_BYPASS_WFDMA_2_SLP_PROT_MASK \
	0x00000040
#define CB_INFRA_RGU_BT_SUBSYS_RST_BYPASS_WFDMA_2_SLP_PROT_SHFT \
	6
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_WHOLE_PATH_RST_REVERT_EN_ADDR \
	CB_INFRA_RGU_BT_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_WHOLE_PATH_RST_REVERT_EN_MASK \
	0x00000020
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_WHOLE_PATH_RST_REVERT_EN_SHFT \
	5
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_SUBSYS_RST_ADDR \
	CB_INFRA_RGU_BT_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_SUBSYS_RST_MASK \
	0x00000010
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_SUBSYS_RST_SHFT \
	4
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_CRYPTO_BYPASS_SUBSYS_RST_ADDR \
	CB_INFRA_RGU_BT_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_CRYPTO_BYPASS_SUBSYS_RST_MASK \
	0x00000008
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_CRYPTO_BYPASS_SUBSYS_RST_SHFT \
	3
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_PATH_BUS_RST_ADDR \
	CB_INFRA_RGU_BT_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_PATH_BUS_RST_MASK \
	0x00000002
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_PATH_BUS_RST_SHFT \
	1
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_WHOLE_PATH_RST_ADDR \
	CB_INFRA_RGU_BT_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_WHOLE_PATH_RST_MASK \
	0x00000001
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_WHOLE_PATH_RST_SHFT \
	0
#ifdef __cplusplus
}
#endif
#endif
