/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * Copyright (c) 2021 MediaTek Inc.
 */

#ifndef __CONN_RF_SPI_MST_REG_REGS_H__
#define __CONN_RF_SPI_MST_REG_REGS_H__

#include "hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif

#define CONN_RF_SPI_MST_REG_BASE \
	(0x18098000 + CONN_INFRA_REMAPPING_OFFSET)

#define CONN_RF_SPI_MST_REG_SPI_STA_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x000)
#define CONN_RF_SPI_MST_REG_SPI_CRTL_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x004)
#define CONN_RF_SPI_MST_REG_SPI_CRTL2_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x008)
#define CONN_RF_SPI_MST_REG_FM_CTRL_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x00C)
#define CONN_RF_SPI_MST_REG_SPI_WF_ADDR_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x010)
#define CONN_RF_SPI_MST_REG_SPI_WF_WDAT_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x014)
#define CONN_RF_SPI_MST_REG_SPI_WF_RDAT_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x018)
#define CONN_RF_SPI_MST_REG_SPI_BT_ADDR_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x020)
#define CONN_RF_SPI_MST_REG_SPI_BT_WDAT_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x024)
#define CONN_RF_SPI_MST_REG_SPI_BT_RDAT_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x028)
#define CONN_RF_SPI_MST_REG_SPI_FM_ADDR_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x030)
#define CONN_RF_SPI_MST_REG_SPI_FM_WDAT_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x034)
#define CONN_RF_SPI_MST_REG_SPI_FM_RDAT_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x038)
#define CONN_RF_SPI_MST_REG_SPI_GPS_ADDR_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x040)
#define CONN_RF_SPI_MST_REG_SPI_GPS_WDAT_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x044)
#define CONN_RF_SPI_MST_REG_SPI_GPS_RDAT_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x048)
#define CONN_RF_SPI_MST_REG_SPI_TOP_ADDR_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x050)
#define CONN_RF_SPI_MST_REG_SPI_TOP_WDAT_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x054)
#define CONN_RF_SPI_MST_REG_SPI_TOP_RDAT_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x058)
#define CONN_RF_SPI_MST_REG_SPI_SLP_ADDR_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x060)
#define CONN_RF_SPI_MST_REG_SLP_WDAT_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x064)
#define CONN_RF_SPI_MST_REG_SLP_RDAT_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x068)
#define CONN_RF_SPI_MST_REG_THM_ADDR_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x070)
#define CONN_RF_SPI_MST_REG_THM_WDAT_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x074)
#define CONN_RF_SPI_MST_REG_THM_RDAT_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x078)
#define CONN_RF_SPI_MST_REG_SPI_INT_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x080)
#define CONN_RF_SPI_MST_REG_SPI_HW_DMY_CMD_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x084)
#define CONN_RF_SPI_MST_REG_SPI_DBG_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x090)
#define CONN_RF_SPI_MST_REG_SPI_STA1_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x094)
#define CONN_RF_SPI_MST_REG_SPI_STA2_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x098)
#define CONN_RF_SPI_MST_REG_SPI_STA3_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x09C)
#define CONN_RF_SPI_MST_REG_SPI_STA4_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x100)
#define CONN_RF_SPI_MST_REG_SPI_STA5_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x104)
#define CONN_RF_SPI_MST_REG_SPI_HSCK_CTL_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x108)
#define CONN_RF_SPI_MST_REG_SPI_HSCK_CTL_SET_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x10C)
#define CONN_RF_SPI_MST_REG_SPI_HSCK_CTL_CLR_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x110)
#define CONN_RF_SPI_MST_REG_SPI_GPS_GPS_ADDR_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x210)
#define CONN_RF_SPI_MST_REG_SPI_GPS_GPS_WDAT_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x214)
#define CONN_RF_SPI_MST_REG_SPI_GPS_GPS_RDAT_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x218)
#define CONN_RF_SPI_MST_REG_SPI_GPS_RFDIG_ADDR_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x220)
#define CONN_RF_SPI_MST_REG_SPI_GPS_RFDIG_WDAT_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x224)
#define CONN_RF_SPI_MST_REG_SPI_GPS_RFDIG_RDAT_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x228)
#define CONN_RF_SPI_MST_REG_SPI_MCU_RECORD_ADDR_0_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x300)
#define CONN_RF_SPI_MST_REG_SPI_MCU_RECORD_ADDR_1_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x304)
#define CONN_RF_SPI_MST_REG_SPI_MCU_RECORD_ADDR_2_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x308)
#define CONN_RF_SPI_MST_REG_SPI_MCU_RECORD_ADDR_3_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x30C)
#define CONN_RF_SPI_MST_REG_SPI_MCU_RECORD_DATA_0_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x310)
#define CONN_RF_SPI_MST_REG_SPI_MCU_RECORD_DATA_1_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x314)
#define CONN_RF_SPI_MST_REG_SPI_MCU_RECORD_DATA_2_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x318)
#define CONN_RF_SPI_MST_REG_SPI_MCU_RECORD_DATA_3_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x31C)
#define CONN_RF_SPI_MST_REG_SPI_MCU_RECORD_CTL_ADDR \
	(CONN_RF_SPI_MST_REG_BASE + 0x320)

#ifdef __cplusplus
}
#endif

#endif /* __CONN_RF_SPI_MST_REG_REGS_H__ */
