/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * Copyright (c) 2021 MediaTek Inc.
 */

#ifndef __CONN_BUS_CR_VON_REGS_H__
#define __CONN_BUS_CR_VON_REGS_H__

#ifdef __cplusplus
extern "C" {
#endif


/*******************************************************************************
*                        CONN_BUS_CR_VON CR Definitions
********************************************************************************
*/

#define \
CONN_BUS_CR_VON_BASE                                  \
	(0x18095000 + CONN_INFRA_REMAPPING_OFFSET)

#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_0_10_ADDR \
	(CONN_BUS_CR_VON_BASE + 0x0000)
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_0_32_ADDR \
	(CONN_BUS_CR_VON_BASE + 0x0004)
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_0_54_ADDR \
	(CONN_BUS_CR_VON_BASE + 0x0008)
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_0_76_ADDR \
	(CONN_BUS_CR_VON_BASE + 0x000C)
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_0_98_ADDR \
	(CONN_BUS_CR_VON_BASE + 0x0010)
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_0_BA_ADDR \
	(CONN_BUS_CR_VON_BASE + 0x0014)
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_0_DC_ADDR \
	(CONN_BUS_CR_VON_BASE + 0x0018)
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_0_FE_ADDR \
	(CONN_BUS_CR_VON_BASE + 0x001C)
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_1_10_ADDR \
	(CONN_BUS_CR_VON_BASE + 0x0020)
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_1_32_ADDR \
	(CONN_BUS_CR_VON_BASE + 0x0024)
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_1_54_ADDR \
	(CONN_BUS_CR_VON_BASE + 0x0028)
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_1_76_ADDR \
	(CONN_BUS_CR_VON_BASE + 0x002C)
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_1_98_ADDR \
	(CONN_BUS_CR_VON_BASE + 0x0030)
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_1_BA_ADDR \
	(CONN_BUS_CR_VON_BASE + 0x0034)
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_0_10_ADDR \
	(CONN_BUS_CR_VON_BASE + 0x0040)
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_0_32_ADDR \
	(CONN_BUS_CR_VON_BASE + 0x0044)
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_0_54_ADDR \
	(CONN_BUS_CR_VON_BASE + 0x0048)
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_0_76_ADDR \
	(CONN_BUS_CR_VON_BASE + 0x004C)
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_0_98_ADDR \
	(CONN_BUS_CR_VON_BASE + 0x0050)
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_0_BA_ADDR \
	(CONN_BUS_CR_VON_BASE + 0x0054)
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_0_DC_ADDR \
	(CONN_BUS_CR_VON_BASE + 0x0058)
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_0_FE_ADDR \
	(CONN_BUS_CR_VON_BASE + 0x005C)
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_1_10_ADDR \
	(CONN_BUS_CR_VON_BASE + 0x0060)
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_1_32_ADDR \
	(CONN_BUS_CR_VON_BASE + 0x0064)
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_1_54_ADDR \
	(CONN_BUS_CR_VON_BASE + 0x0068)
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_1_76_ADDR \
	(CONN_BUS_CR_VON_BASE + 0x006C)
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_1_98_ADDR \
	(CONN_BUS_CR_VON_BASE + 0x0070)
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_1_BA_ADDR \
	(CONN_BUS_CR_VON_BASE + 0x0074)
#define \
CONN_BUS_CR_VON_CONN_VON_IDLE_MASK_ADDR               \
	(CONN_BUS_CR_VON_BASE + 0x0200)
#define \
CONN_BUS_CR_VON_CONN_VON_BUS_IDLE_DEBOUNCE_ADDR       \
	(CONN_BUS_CR_VON_BASE + 0x0204)
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_ADDR \
	(CONN_BUS_CR_VON_BASE + 0x0208)
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_1_ADDR \
	(CONN_BUS_CR_VON_BASE + 0x020C)

#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_10_CR_PCIE2AP_PUBLIC_REMAPPING_WF_01_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_0_10_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_10_CR_PCIE2AP_PUBLIC_REMAPPING_WF_01_MASK \
	0xFFFF0000
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_10_CR_PCIE2AP_PUBLIC_REMAPPING_WF_01_SHFT \
	16
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_10_CR_PCIE2AP_PUBLIC_REMAPPING_WF_00_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_0_10_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_10_CR_PCIE2AP_PUBLIC_REMAPPING_WF_00_MASK \
	0x0000FFFF
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_10_CR_PCIE2AP_PUBLIC_REMAPPING_WF_00_SHFT \
	0

#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_32_CR_PCIE2AP_PUBLIC_REMAPPING_WF_03_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_0_32_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_32_CR_PCIE2AP_PUBLIC_REMAPPING_WF_03_MASK \
	0xFFFF0000
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_32_CR_PCIE2AP_PUBLIC_REMAPPING_WF_03_SHFT \
	16
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_32_CR_PCIE2AP_PUBLIC_REMAPPING_WF_02_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_0_32_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_32_CR_PCIE2AP_PUBLIC_REMAPPING_WF_02_MASK \
	0x0000FFFF
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_32_CR_PCIE2AP_PUBLIC_REMAPPING_WF_02_SHFT \
	0

#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_54_CR_PCIE2AP_PUBLIC_REMAPPING_WF_05_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_0_54_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_54_CR_PCIE2AP_PUBLIC_REMAPPING_WF_05_MASK \
	0xFFFF0000
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_54_CR_PCIE2AP_PUBLIC_REMAPPING_WF_05_SHFT \
	16
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_54_CR_PCIE2AP_PUBLIC_REMAPPING_WF_04_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_0_54_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_54_CR_PCIE2AP_PUBLIC_REMAPPING_WF_04_MASK \
	0x0000FFFF
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_54_CR_PCIE2AP_PUBLIC_REMAPPING_WF_04_SHFT \
	0

#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_76_CR_PCIE2AP_PUBLIC_REMAPPING_WF_07_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_0_76_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_76_CR_PCIE2AP_PUBLIC_REMAPPING_WF_07_MASK \
	0xFFFF0000
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_76_CR_PCIE2AP_PUBLIC_REMAPPING_WF_07_SHFT \
	16
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_76_CR_PCIE2AP_PUBLIC_REMAPPING_WF_06_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_0_76_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_76_CR_PCIE2AP_PUBLIC_REMAPPING_WF_06_MASK \
	0x0000FFFF
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_76_CR_PCIE2AP_PUBLIC_REMAPPING_WF_06_SHFT \
	0

#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_98_CR_PCIE2AP_PUBLIC_REMAPPING_WF_09_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_0_98_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_98_CR_PCIE2AP_PUBLIC_REMAPPING_WF_09_MASK \
	0xFFFF0000
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_98_CR_PCIE2AP_PUBLIC_REMAPPING_WF_09_SHFT \
	16
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_98_CR_PCIE2AP_PUBLIC_REMAPPING_WF_08_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_0_98_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_98_CR_PCIE2AP_PUBLIC_REMAPPING_WF_08_MASK \
	0x0000FFFF
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_98_CR_PCIE2AP_PUBLIC_REMAPPING_WF_08_SHFT \
	0

#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_BA_CR_PCIE2AP_PUBLIC_REMAPPING_WF_0B_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_0_BA_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_BA_CR_PCIE2AP_PUBLIC_REMAPPING_WF_0B_MASK \
	0xFFFF0000
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_BA_CR_PCIE2AP_PUBLIC_REMAPPING_WF_0B_SHFT \
	16
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_BA_CR_PCIE2AP_PUBLIC_REMAPPING_WF_0A_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_0_BA_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_BA_CR_PCIE2AP_PUBLIC_REMAPPING_WF_0A_MASK \
	0x0000FFFF
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_BA_CR_PCIE2AP_PUBLIC_REMAPPING_WF_0A_SHFT \
	0

#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_DC_CR_PCIE2AP_PUBLIC_REMAPPING_WF_0D_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_0_DC_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_DC_CR_PCIE2AP_PUBLIC_REMAPPING_WF_0D_MASK \
	0xFFFF0000
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_DC_CR_PCIE2AP_PUBLIC_REMAPPING_WF_0D_SHFT \
	16
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_DC_CR_PCIE2AP_PUBLIC_REMAPPING_WF_0C_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_0_DC_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_DC_CR_PCIE2AP_PUBLIC_REMAPPING_WF_0C_MASK \
	0x0000FFFF
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_DC_CR_PCIE2AP_PUBLIC_REMAPPING_WF_0C_SHFT \
	0

#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_FE_CR_PCIE2AP_PUBLIC_REMAPPING_WF_0F_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_0_FE_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_FE_CR_PCIE2AP_PUBLIC_REMAPPING_WF_0F_MASK \
	0xFFFF0000
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_FE_CR_PCIE2AP_PUBLIC_REMAPPING_WF_0F_SHFT \
	16
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_FE_CR_PCIE2AP_PUBLIC_REMAPPING_WF_0E_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_0_FE_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_FE_CR_PCIE2AP_PUBLIC_REMAPPING_WF_0E_MASK \
	0x0000FFFF
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_0_FE_CR_PCIE2AP_PUBLIC_REMAPPING_WF_0E_SHFT \
	0

#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_10_CR_PCIE2AP_PUBLIC_REMAPPING_WF_11_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_1_10_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_10_CR_PCIE2AP_PUBLIC_REMAPPING_WF_11_MASK \
	0xFFFF0000
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_10_CR_PCIE2AP_PUBLIC_REMAPPING_WF_11_SHFT \
	16
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_10_CR_PCIE2AP_PUBLIC_REMAPPING_WF_10_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_1_10_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_10_CR_PCIE2AP_PUBLIC_REMAPPING_WF_10_MASK \
	0x0000FFFF
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_10_CR_PCIE2AP_PUBLIC_REMAPPING_WF_10_SHFT \
	0

#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_32_CR_PCIE2AP_PUBLIC_REMAPPING_WF_13_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_1_32_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_32_CR_PCIE2AP_PUBLIC_REMAPPING_WF_13_MASK \
	0xFFFF0000
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_32_CR_PCIE2AP_PUBLIC_REMAPPING_WF_13_SHFT \
	16
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_32_CR_PCIE2AP_PUBLIC_REMAPPING_WF_12_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_1_32_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_32_CR_PCIE2AP_PUBLIC_REMAPPING_WF_12_MASK \
	0x0000FFFF
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_32_CR_PCIE2AP_PUBLIC_REMAPPING_WF_12_SHFT \
	0

#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_54_CR_PCIE2AP_PUBLIC_REMAPPING_WF_15_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_1_54_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_54_CR_PCIE2AP_PUBLIC_REMAPPING_WF_15_MASK \
	0xFFFF0000
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_54_CR_PCIE2AP_PUBLIC_REMAPPING_WF_15_SHFT \
	16
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_54_CR_PCIE2AP_PUBLIC_REMAPPING_WF_14_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_1_54_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_54_CR_PCIE2AP_PUBLIC_REMAPPING_WF_14_MASK \
	0x0000FFFF
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_54_CR_PCIE2AP_PUBLIC_REMAPPING_WF_14_SHFT \
	0

#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_76_CR_PCIE2AP_PUBLIC_REMAPPING_WF_17_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_1_76_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_76_CR_PCIE2AP_PUBLIC_REMAPPING_WF_17_MASK \
	0xFFFF0000
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_76_CR_PCIE2AP_PUBLIC_REMAPPING_WF_17_SHFT \
	16
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_76_CR_PCIE2AP_PUBLIC_REMAPPING_WF_16_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_1_76_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_76_CR_PCIE2AP_PUBLIC_REMAPPING_WF_16_MASK \
	0x0000FFFF
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_76_CR_PCIE2AP_PUBLIC_REMAPPING_WF_16_SHFT \
	0

#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_98_CR_PCIE2AP_PUBLIC_REMAPPING_WF_19_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_1_98_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_98_CR_PCIE2AP_PUBLIC_REMAPPING_WF_19_MASK \
	0xFFFF0000
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_98_CR_PCIE2AP_PUBLIC_REMAPPING_WF_19_SHFT \
	16
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_98_CR_PCIE2AP_PUBLIC_REMAPPING_WF_18_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_1_98_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_98_CR_PCIE2AP_PUBLIC_REMAPPING_WF_18_MASK \
	0x0000FFFF
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_98_CR_PCIE2AP_PUBLIC_REMAPPING_WF_18_SHFT \
	0

#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_BA_CR_PCIE2AP_PUBLIC_REMAPPING_WF_1B_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_1_BA_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_BA_CR_PCIE2AP_PUBLIC_REMAPPING_WF_1B_MASK \
	0xFFFF0000
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_BA_CR_PCIE2AP_PUBLIC_REMAPPING_WF_1B_SHFT \
	16
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_BA_CR_PCIE2AP_PUBLIC_REMAPPING_WF_1A_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_1_BA_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_BA_CR_PCIE2AP_PUBLIC_REMAPPING_WF_1A_MASK \
	0x0000FFFF
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF\
_1_BA_CR_PCIE2AP_PUBLIC_REMAPPING_WF_1A_SHFT \
	0

#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_10_CR_PCIE2AP_PUBLIC_REMAPPING_BT_01_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_0_10_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_10_CR_PCIE2AP_PUBLIC_REMAPPING_BT_01_MASK \
	0xFFFF0000
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_10_CR_PCIE2AP_PUBLIC_REMAPPING_BT_01_SHFT \
	16
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_10_CR_PCIE2AP_PUBLIC_REMAPPING_BT_00_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_0_10_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_10_CR_PCIE2AP_PUBLIC_REMAPPING_BT_00_MASK \
	0x0000FFFF
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_10_CR_PCIE2AP_PUBLIC_REMAPPING_BT_00_SHFT \
	0

#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_32_CR_PCIE2AP_PUBLIC_REMAPPING_BT_03_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_0_32_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_32_CR_PCIE2AP_PUBLIC_REMAPPING_BT_03_MASK \
	0xFFFF0000
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_32_CR_PCIE2AP_PUBLIC_REMAPPING_BT_03_SHFT \
	16
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_32_CR_PCIE2AP_PUBLIC_REMAPPING_BT_02_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_0_32_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_32_CR_PCIE2AP_PUBLIC_REMAPPING_BT_02_MASK \
	0x0000FFFF
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_32_CR_PCIE2AP_PUBLIC_REMAPPING_BT_02_SHFT \
	0

#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_54_CR_PCIE2AP_PUBLIC_REMAPPING_BT_05_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_0_54_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_54_CR_PCIE2AP_PUBLIC_REMAPPING_BT_05_MASK \
	0xFFFF0000
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_54_CR_PCIE2AP_PUBLIC_REMAPPING_BT_05_SHFT \
	16
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_54_CR_PCIE2AP_PUBLIC_REMAPPING_BT_04_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_0_54_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_54_CR_PCIE2AP_PUBLIC_REMAPPING_BT_04_MASK \
	0x0000FFFF
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_54_CR_PCIE2AP_PUBLIC_REMAPPING_BT_04_SHFT \
	0

#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_76_CR_PCIE2AP_PUBLIC_REMAPPING_BT_07_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_0_76_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_76_CR_PCIE2AP_PUBLIC_REMAPPING_BT_07_MASK \
	0xFFFF0000
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_76_CR_PCIE2AP_PUBLIC_REMAPPING_BT_07_SHFT \
	16
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_76_CR_PCIE2AP_PUBLIC_REMAPPING_BT_06_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_0_76_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_76_CR_PCIE2AP_PUBLIC_REMAPPING_BT_06_MASK \
	0x0000FFFF
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_76_CR_PCIE2AP_PUBLIC_REMAPPING_BT_06_SHFT \
	0

#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_98_CR_PCIE2AP_PUBLIC_REMAPPING_BT_09_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_0_98_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_98_CR_PCIE2AP_PUBLIC_REMAPPING_BT_09_MASK \
	0xFFFF0000
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_98_CR_PCIE2AP_PUBLIC_REMAPPING_BT_09_SHFT \
	16
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_98_CR_PCIE2AP_PUBLIC_REMAPPING_BT_08_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_0_98_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_98_CR_PCIE2AP_PUBLIC_REMAPPING_BT_08_MASK \
	0x0000FFFF
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_98_CR_PCIE2AP_PUBLIC_REMAPPING_BT_08_SHFT \
	0

#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_BA_CR_PCIE2AP_PUBLIC_REMAPPING_BT_0B_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_0_BA_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_BA_CR_PCIE2AP_PUBLIC_REMAPPING_BT_0B_MASK \
	0xFFFF0000
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_BA_CR_PCIE2AP_PUBLIC_REMAPPING_BT_0B_SHFT \
	16
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_BA_CR_PCIE2AP_PUBLIC_REMAPPING_BT_0A_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_0_BA_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_BA_CR_PCIE2AP_PUBLIC_REMAPPING_BT_0A_MASK \
	0x0000FFFF
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_BA_CR_PCIE2AP_PUBLIC_REMAPPING_BT_0A_SHFT \
	0

#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_DC_CR_PCIE2AP_PUBLIC_REMAPPING_BT_0D_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_0_DC_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_DC_CR_PCIE2AP_PUBLIC_REMAPPING_BT_0D_MASK \
	0xFFFF0000
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_DC_CR_PCIE2AP_PUBLIC_REMAPPING_BT_0D_SHFT \
	16
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_DC_CR_PCIE2AP_PUBLIC_REMAPPING_BT_0C_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_0_DC_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_DC_CR_PCIE2AP_PUBLIC_REMAPPING_BT_0C_MASK \
	0x0000FFFF
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_DC_CR_PCIE2AP_PUBLIC_REMAPPING_BT_0C_SHFT \
	0

#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_FE_CR_PCIE2AP_PUBLIC_REMAPPING_BT_0F_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_0_FE_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_FE_CR_PCIE2AP_PUBLIC_REMAPPING_BT_0F_MASK \
	0xFFFF0000
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_FE_CR_PCIE2AP_PUBLIC_REMAPPING_BT_0F_SHFT \
	16
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_FE_CR_PCIE2AP_PUBLIC_REMAPPING_BT_0E_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_0_FE_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_FE_CR_PCIE2AP_PUBLIC_REMAPPING_BT_0E_MASK \
	0x0000FFFF
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_0_FE_CR_PCIE2AP_PUBLIC_REMAPPING_BT_0E_SHFT \
	0

#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_10_CR_PCIE2AP_PUBLIC_REMAPPING_BT_11_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_1_10_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_10_CR_PCIE2AP_PUBLIC_REMAPPING_BT_11_MASK \
	0xFFFF0000
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_10_CR_PCIE2AP_PUBLIC_REMAPPING_BT_11_SHFT \
	16
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_10_CR_PCIE2AP_PUBLIC_REMAPPING_BT_10_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_1_10_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_10_CR_PCIE2AP_PUBLIC_REMAPPING_BT_10_MASK \
	0x0000FFFF
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_10_CR_PCIE2AP_PUBLIC_REMAPPING_BT_10_SHFT \
	0

#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_32_CR_PCIE2AP_PUBLIC_REMAPPING_BT_13_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_1_32_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_32_CR_PCIE2AP_PUBLIC_REMAPPING_BT_13_MASK \
	0xFFFF0000
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_32_CR_PCIE2AP_PUBLIC_REMAPPING_BT_13_SHFT \
	16
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_32_CR_PCIE2AP_PUBLIC_REMAPPING_BT_12_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_1_32_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_32_CR_PCIE2AP_PUBLIC_REMAPPING_BT_12_MASK \
	0x0000FFFF
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_32_CR_PCIE2AP_PUBLIC_REMAPPING_BT_12_SHFT \
	0

#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_54_CR_PCIE2AP_PUBLIC_REMAPPING_BT_15_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_1_54_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_54_CR_PCIE2AP_PUBLIC_REMAPPING_BT_15_MASK \
	0xFFFF0000
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_54_CR_PCIE2AP_PUBLIC_REMAPPING_BT_15_SHFT \
	16
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_54_CR_PCIE2AP_PUBLIC_REMAPPING_BT_14_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_1_54_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_54_CR_PCIE2AP_PUBLIC_REMAPPING_BT_14_MASK \
	0x0000FFFF
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_54_CR_PCIE2AP_PUBLIC_REMAPPING_BT_14_SHFT \
	0

#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_76_CR_PCIE2AP_PUBLIC_REMAPPING_BT_17_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_1_76_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_76_CR_PCIE2AP_PUBLIC_REMAPPING_BT_17_MASK \
	0xFFFF0000
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_76_CR_PCIE2AP_PUBLIC_REMAPPING_BT_17_SHFT \
	16
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_76_CR_PCIE2AP_PUBLIC_REMAPPING_BT_16_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_1_76_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_76_CR_PCIE2AP_PUBLIC_REMAPPING_BT_16_MASK \
	0x0000FFFF
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_76_CR_PCIE2AP_PUBLIC_REMAPPING_BT_16_SHFT \
	0

#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_98_CR_PCIE2AP_PUBLIC_REMAPPING_BT_19_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_1_98_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_98_CR_PCIE2AP_PUBLIC_REMAPPING_BT_19_MASK \
	0xFFFF0000
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_98_CR_PCIE2AP_PUBLIC_REMAPPING_BT_19_SHFT \
	16
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_98_CR_PCIE2AP_PUBLIC_REMAPPING_BT_18_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_1_98_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_98_CR_PCIE2AP_PUBLIC_REMAPPING_BT_18_MASK \
	0x0000FFFF
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_98_CR_PCIE2AP_PUBLIC_REMAPPING_BT_18_SHFT \
	0

#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_BA_CR_PCIE2AP_PUBLIC_REMAPPING_BT_1B_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_1_BA_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_BA_CR_PCIE2AP_PUBLIC_REMAPPING_BT_1B_MASK \
	0xFFFF0000
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_BA_CR_PCIE2AP_PUBLIC_REMAPPING_BT_1B_SHFT \
	16
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_BA_CR_PCIE2AP_PUBLIC_REMAPPING_BT_1A_ADDR \
	CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT_1_BA_ADDR
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_BA_CR_PCIE2AP_PUBLIC_REMAPPING_BT_1A_MASK \
	0x0000FFFF
#define \
CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_BT\
_1_BA_CR_PCIE2AP_PUBLIC_REMAPPING_BT_1A_SHFT \
	0

#define \
CONN_BUS_CR_VON_CONN_VON_IDLE_MASK_CR_VON_BUS_IDLE_MASK_ADDR \
	CONN_BUS_CR_VON_CONN_VON_IDLE_MASK_ADDR
#define \
CONN_BUS_CR_VON_CONN_VON_IDLE_MASK_CR_VON_BUS_IDLE_MASK_MASK \
	0xFFFFFFFF
#define \
CONN_BUS_CR_VON_CONN_VON_IDLE_MASK_CR_VON_BUS_IDLE_MASK_SHFT \
	0

#define \
CONN_BUS_CR_VON_CONN_VON_BUS_IDLE_DEBOUNCE_CR_VON_BUS_IDLE_DEBOUNCE_ADDR \
	CONN_BUS_CR_VON_CONN_VON_BUS_IDLE_DEBOUNCE_ADDR
#define \
CONN_BUS_CR_VON_CONN_VON_BUS_IDLE_DEBOUNCE_CR_VON_BUS_IDLE_DEBOUNCE_MASK \
	0x0000001F
#define \
CONN_BUS_CR_VON_CONN_VON_BUS_IDLE_DEBOUNCE_CR_VON_BUS_IDLE_DEBOUNCE_SHFT \
	0

#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_FORCE_ON_HOST_CK_DCM_ADDR \
	CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_ADDR
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_FORCE_ON_HOST_CK_DCM_MASK \
	0x80000000
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_FORCE_ON_HOST_CK_DCM_SHFT \
	31
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_DBC_CTRL_DBC_EN_ADDR \
	CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_ADDR
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_DBC_CTRL_DBC_EN_MASK \
	0x40000000
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_DBC_CTRL_DBC_EN_SHFT \
	30
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_DBC_CTRL_DBC_NUM_ADDR \
	CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_ADDR
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_DBC_CTRL_DBC_NUM_MASK \
	0x3FFC0000
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_DBC_CTRL_DBC_NUM_SHFT \
	18
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_CTRL_SFSEL_ADDR \
	CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_ADDR
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_CTRL_SFSEL_MASK \
	0x0003E000
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_CTRL_SFSEL_SHFT \
	13
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_CTRL_FSEL_ADDR \
	CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_ADDR
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_CTRL_FSEL_MASK \
	0x00001F00
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_CTRL_FSEL_SHFT \
	8
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_CTRL_FORCE_ON_ADDR \
	CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_ADDR
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_CTRL_FORCE_ON_MASK \
	0x00000080
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_CTRL_FORCE_ON_SHFT \
	7
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_CTRL_FORCE_CLKSLOW_ADDR \
	CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_ADDR
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_CTRL_FORCE_CLKSLOW_MASK \
	0x00000040
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_CTRL_FORCE_CLKSLOW_SHFT \
	6
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_CTRL_FORCE_CLKOFF_ADDR \
	CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_ADDR
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_CTRL_FORCE_CLKOFF_MASK \
	0x00000020
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_CTRL_FORCE_CLKOFF_SHFT \
	5
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_CTRL_CLKSLOW_EN_ADDR \
	CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_ADDR
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_CTRL_CLKSLOW_EN_MASK \
	0x00000010
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_CTRL_CLKSLOW_EN_SHFT \
	4
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_CTRL_CLKOFF_EN_ADDR \
	CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_ADDR
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_CTRL_CLKOFF_EN_MASK \
	0x00000008
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_CTRL_CLKOFF_EN_SHFT \
	3
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_GROUP_CTRL_PLLCK_SEL_2_CLK_RDY_ON_DCM_ADDR \
	CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_ADDR
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_GROUP_CTRL_PLLCK_SEL_2_CLK_RDY_ON_DCM_MASK \
	0x00000004
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_GROUP_CTRL_PLLCK_SEL_2_CLK_RDY_ON_DCM_SHFT \
	2
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_GROUP_CTRL_PLLCK_SEL_NO_SPM_ADDR \
	CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_ADDR
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_GROUP_CTRL_PLLCK_SEL_NO_SPM_MASK \
	0x00000002
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_GROUP_CTRL_PLLCK_SEL_NO_SPM_SHFT \
	1
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_GROUP_CTRL_SC_AXI_DCM_DIS_EN_ADDR \
	CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_ADDR
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_GROUP_CTRL_SC_AXI_DCM_DIS_EN_MASK \
	0x00000001
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_0_CR_CONN_VON_VDNR_DCM_HOST_CK\
_GROUP_CTRL_SC_AXI_DCM_DIS_EN_SHFT \
	0

#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_1_CR_CONN_VON_VDNR_DCM_HOST_CK_BUS_IDLE_SYNC_MASK_ADDR \
	CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_1_ADDR
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_1_CR_CONN_VON_VDNR_DCM_HOST_CK_BUS_IDLE_SYNC_MASK_MASK \
	0x00000002
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_1_CR_CONN_VON_VDNR_DCM_HOST_CK_BUS_IDLE_SYNC_MASK_SHFT \
	1
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_1_CR_CONN_VON_VDNR_DCM_SC_AXI_DCM_DIS_ADDR \
	CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_1_ADDR
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_1_CR_CONN_VON_VDNR_DCM_SC_AXI_DCM_DIS_MASK \
	0x00000001
#define \
CONN_BUS_CR_VON_ADDR_CONN_VON_BUS_GLUE\
_DCM_CTL_1_CR_CONN_VON_VDNR_DCM_SC_AXI_DCM_DIS_SHFT \
	0

#ifdef __cplusplus
}
#endif

#endif
