/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * Copyright (c) 2021 MediaTek Inc.
 */

#ifndef __CONN_CFG_REGS_H__
#define __CONN_CFG_REGS_H__
#include "hal_common.h"
#ifdef __cplusplus
extern "C" {
#endif
#define CONNINFRA_CONN_CFG_BASE \
	(0x18011000 + CONN_INFRA_REMAPPING_OFFSET)

#define CONN_CFG_IP_VERSION_ADDR \
	(CONNINFRA_CONN_CFG_BASE + 0x000)
#define CONN_CFG_PLL_STATUS_ADDR \
	(CONNINFRA_CONN_CFG_BASE + 0x030)
#define CONN_CFG_EMI_CTL_0_ADDR \
	(CONNINFRA_CONN_CFG_BASE + 0x100)
#define CONN_CFG_EMI_PROBE_ADDR \
	(CONNINFRA_CONN_CFG_BASE + 0x130)
#define CONN_CFG_EMI_PROBE_1_ADDR \
	(CONNINFRA_CONN_CFG_BASE + 0x134)
#define CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_ADDR \
	(CONNINFRA_CONN_CFG_BASE + 0x404)
#define CONN_CFG_CONN_INFRA_CONN2AP_EMI_SLP_STATUS_ADDR \
	(CONNINFRA_CONN_CFG_BASE + 0x408)
#define CONN_CFG_CONN_INFRA_OFF_BUS_SLP_STATUS_ADDR \
	(CONNINFRA_CONN_CFG_BASE + 0x434)
#define CONN_CFG_CONN_INFRA_WF_SLP_STATUS_ADDR \
	(CONNINFRA_CONN_CFG_BASE + 0x4A4)
#define CONN_CFG_GALS_CONN2BT_SLP_STATUS_ADDR \
	(CONNINFRA_CONN_CFG_BASE + 0x454)
#define CONN_CFG_GALS_BT2CONN_SLP_STATUS_ADDR \
	(CONNINFRA_CONN_CFG_BASE + 0x464)
#define CONN_CFG_GALS_CONN2GPS_SLP_STATUS_ADDR \
	(CONNINFRA_CONN_CFG_BASE + 0x474)
#define CONN_CFG_GALS_GPS2CONN_SLP_STATUS_ADDR \
	(CONNINFRA_CONN_CFG_BASE + 0x484)

#define CONN_CFG_IP_VERSION_IP_VERSION_ADDR \
	CONN_CFG_IP_VERSION_ADDR
#define CONN_CFG_IP_VERSION_IP_VERSION_MASK \
	0xFFFFFFFF
#define CONN_CFG_IP_VERSION_IP_VERSION_SHFT \
	0
#define CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_CONN2AP_GALS_CTRL_PROT_EN_ADDR \
	CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_ADDR
#define CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_CONN2AP_GALS_CTRL_PROT_EN_MASK \
	0x80000000
#define CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_CONN2AP_GALS_CTRL_PROT_EN_SHFT \
	31
#define CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_CONN2AP_GALS_CTRL_PROT_TX_EN_ADDR \
	CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_ADDR
#define CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_CONN2AP_GALS_CTRL_PROT_TX_EN_MASK \
	0x20000000
#define CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_CONN2AP_GALS_CTRL_PROT_TX_EN_SHFT \
	29
#define CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_CONN2AP_GALS_CTRL_PROT_RX_EN_ADDR \
	CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_ADDR
#define CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_CONN2AP_GALS_CTRL_PROT_RX_EN_MASK \
	0x10000000
#define CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_CONN2AP_GALS_CTRL_PROT_RX_EN_SHFT \
	28
#define CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_CONN2AP_GALS_CTRL_PROT_TX_RDY_ADDR \
	CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_ADDR
#define CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_CONN2AP_GALS_CTRL_PROT_TX_RDY_MASK \
	0x00800000
#define CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_CONN2AP_GALS_CTRL_PROT_TX_RDY_SHFT \
	23
#define CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_CONN2AP_GALS_CTRL_PROT_RX_RDY_ADDR \
	CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_ADDR
#define CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_CONN2AP_GALS_CTRL_PROT_RX_RDY_MASK \
	0x00400000
#define CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_CONN2AP_GALS_CTRL_PROT_RX_RDY_SHFT \
	22
#define CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_CONN2AP_GALS_CTRL_PROT_RDY_OUT_ADDR \
	CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_ADDR
#define CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_CONN2AP_GALS_CTRL_PROT_RDY_OUT_MASK \
	0x00080000
#define CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_CONN2AP_GALS_CTRL_PROT_RDY_OUT_SHFT \
	19
#define CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_CONN2AP_GALS_CTRL_TIMEOUT_ADDR \
	CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_ADDR
#define CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_CONN2AP_GALS_CTRL_TIMEOUT_MASK \
	0x00008000
#define CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_CONN2AP_GALS_CTRL_TIMEOUT_SHFT \
	15
#define CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_CONN2AP_GALS_CTRL_EN_TIMEOUT_ADDR \
	CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_ADDR
#define CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_CONN2AP_GALS_CTRL_EN_TIMEOUT_MASK \
	0x00002000
#define CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_CONN2AP_GALS_CTRL_EN_TIMEOUT_SHFT \
	13
#define CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_CONN2AP_GALS_CTRL_DIS_TIMEOUT_ADDR \
	CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_ADDR
#define CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_CONN2AP_GALS_CTRL_DIS_TIMEOUT_MASK \
	0x00001000
#define CONN_CFG_CONN_INFRA_CONN2AP_SLP_STATUS_CONN2AP_GALS_CTRL_DIS_TIMEOUT_SHFT \
	12
#define CONN_CFG_EMI_CTL_0_EMI_CTL_DEBUG_1_SEL_ADDR \
	CONN_CFG_EMI_CTL_0_ADDR
#define CONN_CFG_EMI_CTL_0_EMI_CTL_DEBUG_1_SEL_MASK \
	0x00600000
#define CONN_CFG_EMI_CTL_0_EMI_CTL_DEBUG_1_SEL_SHFT \
	21
#ifdef __cplusplus
}
#endif
#endif
