/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * Copyright (c) 2021 MediaTek Inc.
 */

#ifndef __CONN_CFG_ON_REGS_H__
#define __CONN_CFG_ON_REGS_H__

#include "hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif

#define CONN_CFG_ON_REMAP_BASE \
	(0x18001000 + CONN_INFRA_REMAPPING_OFFSET)

#define CONN_CFG_ON_BOOT_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x000)
#define CONN_CFG_ON_CONN_INFRA_CFG_ON_XTAL_CTL_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x004)
#define CONN_CFG_ON_ADIE_CTL_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x010)
#define CONN_CFG_ON_CONN_INFRA_SLP_CNT_CTL_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x020)
#define CONN_CFG_ON_CONN_INFRA_CONN_INFRA_SLP_CNT_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x024)
#define CONN_CFG_ON_CONN_INFRA_WFSYS_SLP_CNT_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x028)
#define CONN_CFG_ON_CONN_INFRA_BGFSYS_SLP_CNT_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x02C)
#define CONN_CFG_ON_CONN_INFRA_GPSSYS_SLP_CNT_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x030)
#define CONN_CFG_ON_CONN_INFRA_SLP_TIMER_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x034)
#define CONN_CFG_ON_CONN_INFRA_SLP_COUNTER_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x038)
#define CONN_CFG_ON_CONN_INFRA_CFG_CONN2AP_MAILBOX_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x100)
#define CONN_CFG_ON_CONN_INFRA_CFG_AP2CONN_MAILBOX_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x104)
#define CONN_CFG_ON_CONN_INFRA_CFG_BT_MANUAL_CTRL_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x108)
#define CONN_CFG_ON_CONN_INFRA_CFG_GPS_MANUAL_CTRL_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x10C)
#define CONN_CFG_ON_BGF_DUMMY_CR_0_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x110)
#define CONN_CFG_ON_BGF_DUMMY_CR_1_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x114)
#define CONN_CFG_ON_BGF_DUMMY_CR_2_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x118)
#define CONN_CFG_ON_BGF_DUMMY_CR_3_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x11C)
#define CONN_CFG_ON_WF_DUMMY_CR_0_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x120)
#define CONN_CFG_ON_WF_DUMMY_CR_1_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x124)
#define CONN_CFG_ON_WF_DUMMY_CR_2_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x128)
#define CONN_CFG_ON_WF_DUMMY_CR_3_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x12C)
#define CONN_CFG_ON_CONN_FPGA_DUMMY0_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x130)
#define CONN_CFG_ON_CONN_FPGA_DUMMY1_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x134)
#define CONN_CFG_ON_CONN_INFRA_CFG_PWRCTRL0_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x200)
#define CONN_CFG_ON_CONN_INFRA_CFG_FM_PWRCTRL0_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x204)
#define CONN_CFG_ON_CONN_INFRA_CFG_BT_PWRCTRL0_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x208)
#define CONN_CFG_ON_CONN_INFRA_CFG_GPS_PWRCTRL0_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x20C)
#define CONN_CFG_ON_CONN_INFRA_CFG_PWRCTRL1_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x210)
#define CONN_CFG_ON_CONN_INFRA_CFG_PWRCTRL2_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x214)
#define CONN_CFG_ON_CONN_INFRA_CFG_CMDBT_CTL_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x220)
#define CONN_CFG_ON_CONN_INFRA_REQ_MASK_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x230)
#define CONN_CFG_ON_CONN_INFRA_REQ_MASK_1_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x234)
#define CONN_CFG_ON_OSC_CTL_0_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x300)
#define CONN_CFG_ON_OSC_CTL_1_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x304)
#define CONN_CFG_ON_OSC_MASK_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x308)
#define CONN_CFG_ON_OSC_STATUS_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x30C)
#define CONN_CFG_ON_OSC_2X_CTL_0_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x310)
#define CONN_CFG_ON_OSC_2X_CTL_1_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x314)
#define CONN_CFG_ON_OSC_2X_MASK_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x318)
#define CONN_CFG_ON_OSC_2X_STATUS_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x31C)
#define CONN_CFG_ON_CONN_INFRA_CFG_OSC_MASK1_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x320)
#define CONN_CFG_ON_CONN_INFRA_CFG_LP_OSC_MASK_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x324)
#define CONN_CFG_ON_CONN_INFRA_CFG_FUNC_GRNT_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x330)
#define CONN_CFG_ON_LP_OSC_CTL_0_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x334)
#define CONN_CFG_ON_CONN_INFRA_CFG_RC_CTL_0_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x340)
#define CONN_CFG_ON_CONN_INFRA_CFG_RC_STATUS_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x344)
#define CONN_CFG_ON_CONN_INFRA_CFG_RC_CTL_1_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x348)
#define CONN_CFG_ON_CONN_INFRA_CFG_RC_CTL_2_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x34C)
#define CONN_CFG_ON_CONN_INFRA_CFG_RC_CTL_0_GPS_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x350)
#define CONN_CFG_ON_CONN_INFRA_CFG_RC_CTL_1_GPS_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x354)
#define CONN_CFG_ON_CONN_INFRA_CFG_RC_CTL_2_GPS_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x358)
#define CONN_CFG_ON_CONN_INFRA_CFG_RC_CTL_0_BT_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x360)
#define CONN_CFG_ON_CONN_INFRA_CFG_RC_CTL_1_BT_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x364)
#define CONN_CFG_ON_CONN_INFRA_CFG_RC_CTL_2_BT_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x368)
#define CONN_CFG_ON_CONN_INFRA_CFG_RC_CTL_0_WF_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x370)
#define CONN_CFG_ON_CONN_INFRA_CFG_RC_CTL_1_WF_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x374)
#define CONN_CFG_ON_CONN_INFRA_CFG_RC_CTL_2_WF_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x378)
#define CONN_CFG_ON_CONN_INFRA_CFG_RC_CTL_0_TOP_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x380)
#define CONN_CFG_ON_CONN_INFRA_CFG_RC_CTL_1_TOP_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x384)
#define CONN_CFG_ON_EMI_CTL_0_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x3A0)
#define CONN_CFG_ON_RF_LDO_CTRL_0_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x3B0)
#define CONN_CFG_ON_RF_LDO_CTRL_1_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x3B4)
#define CONN_CFG_ON_RF_LDO_STATUS_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x3B8)
#define CONN_CFG_ON_RF_LDO_TIMER_0_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x3C0)
#define CONN_CFG_ON_RF_LDO_TIMER_1_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x3C4)
#define CONN_CFG_ON_RF_LDO_TIMER_2_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x3C8)
#define CONN_CFG_ON_RF_LDO_TIMER_3_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x3CC)
#define CONN_CFG_ON_GPS_LP_OSC_ACK_FORCE_ON_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x3D0)
#define CONN_CFG_ON_BGF_LP_OSC_ACK_FORCE_ON_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x3D4)
#define CONN_CFG_ON_WF_LP_OSC_ACK_FORCE_ON_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x3D8)
#define CONN_CFG_ON_CONN_INFRA_LP_OSC_ACK_FORCE_ON_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x3E0)
#define CONN_CFG_ON_CONN_INFRA_AP2CONN_SLP_CTRL_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x410)
#define CONN_CFG_ON_CONN_INFRA_ON_BUS_SLP_CTRL_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x420)
#define CONN_CFG_ON_CONN_INFRA_ON_BUS_SLP_STATUS_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x424)
#define CONN_CFG_ON_HOST_CSR_IRQ_EN_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x600)
#define CONN_CFG_ON_CSR_BGF_ON_FW_OWN_IRQ_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x604)
#define CONN_CFG_ON_CSR_MD_ON_IRQ_STATUS_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x610)
#define CONN_CFG_ON_CSR_MD_ON_HOST_CSR_MISC_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x614)
#define CONN_CFG_ON_CSR_WF_B0_ON_IRQ_STATUS_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x620)
#define CONN_CFG_ON_CSR_WF_B0_ON_HOST_CSR_MISC_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x624)
#define CONN_CFG_ON_CSR_WF_B1_ON_IRQ_STATUS_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x630)
#define CONN_CFG_ON_CSR_WF_B1_ON_HOST_CSR_MISC_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x634)
#define CONN_CFG_ON_CSR_BGF_ON_IRQ_STATUS_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x640)
#define CONN_CFG_ON_CSR_BGF_ON_HOST_CSR_MISC_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x644)
#define CONN_CFG_ON_CSR_GPS_ON_IRQ_STATUS_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x650)
#define CONN_CFG_ON_CSR_GPS_ON_HOST_CSR_MISC_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x654)
#define CONN_CFG_ON_CONN_SENSORHUB_CFG0_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x700)
#define CONN_CFG_ON_CONN_SENSORHUB_CFG1_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x704)
#define CONN_CFG_ON_CONNSYS_XGF_EXTPLL_DE_GLITCH_MANUAL_MODE_ADDR \
	(CONN_CFG_ON_REMAP_BASE + 0x800)

#ifdef __cplusplus
}
#endif

#endif /* __CONN_CFG_ON_REGS_H__ */
