/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * Copyright (c) 2021 MediaTek Inc.
 */

#ifndef __WF_UMIB_TOP_REGS_H__
#define __WF_UMIB_TOP_REGS_H__
#include "hal_common.h"
#ifdef __cplusplus
extern "C" {
#endif
#define WF_UMIB_TOP_BASE \
	0x820cd000
#define WF_UMIB_TOP_MCR_ADDR \
	(WF_UMIB_TOP_BASE + 0x01C)
#define WF_UMIB_TOP_MMCR_ADDR \
	(WF_UMIB_TOP_BASE + 0x0F0)
#define WF_UMIB_TOP_MVCR_ADDR \
	(WF_UMIB_TOP_BASE + 0x3FC)
#define WF_UMIB_TOP_ANCR_ADDR \
	(WF_UMIB_TOP_BASE + 0x400)
#define WF_UMIB_TOP_B0BROCR_ADDR \
	(WF_UMIB_TOP_BASE + 0x480)
#define WF_UMIB_TOP_B0BRBCR_ADDR \
	(WF_UMIB_TOP_BASE + 0x4D0)
#define WF_UMIB_TOP_B0BRDCR_ADDR \
	(WF_UMIB_TOP_BASE + 0x520)
#define WF_UMIB_TOP_B0BRMCR_ADDR \
	(WF_UMIB_TOP_BASE + 0x530)
#define WF_UMIB_TOP_B0BRPDCR_ADDR \
	(WF_UMIB_TOP_BASE + 0x540)
#define WF_UMIB_TOP_B0ARCR_ADDR \
	(WF_UMIB_TOP_BASE + 0x550)
#define WF_UMIB_TOP_B0RPDCR_ADDR \
	(WF_UMIB_TOP_BASE + 0x560)
#define WF_UMIB_TOP_B0BRIPCR0_ADDR \
	(WF_UMIB_TOP_BASE + 0x564)
#define WF_UMIB_TOP_B0BRIPCR1_ADDR \
	(WF_UMIB_TOP_BASE + 0x574)
#define WF_UMIB_TOP_B0BRIPCR2_ADDR \
	(WF_UMIB_TOP_BASE + 0x584)
#define WF_UMIB_TOP_B0BRIPCR3_ADDR \
	(WF_UMIB_TOP_BASE + 0x594)
#define WF_UMIB_TOP_B0BRIPCR4_ADDR \
	(WF_UMIB_TOP_BASE + 0x5A4)
#define WF_UMIB_TOP_B1BROCR_ADDR \
	(WF_UMIB_TOP_BASE + 0x5B4)
#define WF_UMIB_TOP_B1BRBCR_ADDR \
	(WF_UMIB_TOP_BASE + 0x604)
#define WF_UMIB_TOP_B1BRDCR_ADDR \
	(WF_UMIB_TOP_BASE + 0x654)
#define WF_UMIB_TOP_B1BRMCR_ADDR \
	(WF_UMIB_TOP_BASE + 0x664)
#define WF_UMIB_TOP_B1BRPDCR_ADDR \
	(WF_UMIB_TOP_BASE + 0x674)
#define WF_UMIB_TOP_B1ARCR_ADDR \
	(WF_UMIB_TOP_BASE + 0x684)
#define WF_UMIB_TOP_B1RPDCR_ADDR \
	(WF_UMIB_TOP_BASE + 0x694)
#define WF_UMIB_TOP_B1BRIPCR0_ADDR \
	(WF_UMIB_TOP_BASE + 0x698)
#define WF_UMIB_TOP_B1BRIPCR1_ADDR \
	(WF_UMIB_TOP_BASE + 0x6A8)
#define WF_UMIB_TOP_B1BRIPCR2_ADDR \
	(WF_UMIB_TOP_BASE + 0x6B8)
#define WF_UMIB_TOP_B1BRIPCR3_ADDR \
	(WF_UMIB_TOP_BASE + 0x6C8)
#define WF_UMIB_TOP_B1BRIPCR4_ADDR \
	(WF_UMIB_TOP_BASE + 0x6D8)
#define WF_UMIB_TOP_B2BROCR_ADDR \
	(WF_UMIB_TOP_BASE + 0x6E8)
#define WF_UMIB_TOP_B2BRBCR_ADDR \
	(WF_UMIB_TOP_BASE + 0x738)
#define WF_UMIB_TOP_B2BRDCR_ADDR \
	(WF_UMIB_TOP_BASE + 0x788)
#define WF_UMIB_TOP_B2BRMCR_ADDR \
	(WF_UMIB_TOP_BASE + 0x798)
#define WF_UMIB_TOP_B2BRPDCR_ADDR \
	(WF_UMIB_TOP_BASE + 0x7A8)
#define WF_UMIB_TOP_B2ARCR_ADDR \
	(WF_UMIB_TOP_BASE + 0x7B8)
#define WF_UMIB_TOP_B2RPDCR_ADDR \
	(WF_UMIB_TOP_BASE + 0x7C8)
#define WF_UMIB_TOP_B2BRIPCR0_ADDR \
	(WF_UMIB_TOP_BASE + 0x7CC)
#define WF_UMIB_TOP_B2BRIPCR1_ADDR \
	(WF_UMIB_TOP_BASE + 0x7DC)
#define WF_UMIB_TOP_B2BRIPCR2_ADDR \
	(WF_UMIB_TOP_BASE + 0x7EC)
#define WF_UMIB_TOP_B2BRIPCR3_ADDR \
	(WF_UMIB_TOP_BASE + 0x7FC)
#define WF_UMIB_TOP_B2BRIPCR4_ADDR \
	(WF_UMIB_TOP_BASE + 0x80C)
#define WF_UMIB_TOP_MCR_MBSS_2_BSS0_ADDR \
	WF_UMIB_TOP_MCR_ADDR
#define WF_UMIB_TOP_MCR_MBSS_2_BSS0_MASK \
	0x00000001
#define WF_UMIB_TOP_MCR_MBSS_2_BSS0_SHFT \
	0
#define WF_UMIB_TOP_MMCR_MODE_ADDR \
	WF_UMIB_TOP_MMCR_ADDR
#define WF_UMIB_TOP_MMCR_MODE_MASK \
	0x80000000
#define WF_UMIB_TOP_MMCR_MODE_SHFT \
	31
#define WF_UMIB_TOP_MMCR_RESET_ADDR \
	WF_UMIB_TOP_MMCR_ADDR
#define WF_UMIB_TOP_MMCR_RESET_MASK \
	0x00000001
#define WF_UMIB_TOP_MMCR_RESET_SHFT \
	0
#define WF_UMIB_TOP_MVCR_VERSION_CODE_ADDR \
	WF_UMIB_TOP_MVCR_ADDR
#define WF_UMIB_TOP_MVCR_VERSION_CODE_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_MVCR_VERSION_CODE_SHFT \
	0
#define WF_UMIB_TOP_ANCR_AMSDU_COUNTn_ADDR \
	WF_UMIB_TOP_ANCR_ADDR
#define WF_UMIB_TOP_ANCR_AMSDU_COUNTn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_ANCR_AMSDU_COUNTn_SHFT \
	0
#define WF_UMIB_TOP_B0BROCR_RX_OK_COUNTn_ADDR \
	WF_UMIB_TOP_B0BROCR_ADDR
#define WF_UMIB_TOP_B0BROCR_RX_OK_COUNTn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B0BROCR_RX_OK_COUNTn_SHFT \
	0
#define WF_UMIB_TOP_B0BRBCR_RX_BYTE_COUNTn_ADDR \
	WF_UMIB_TOP_B0BRBCR_ADDR
#define WF_UMIB_TOP_B0BRBCR_RX_BYTE_COUNTn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B0BRBCR_RX_BYTE_COUNTn_SHFT \
	0
#define WF_UMIB_TOP_B0BRDCR_RX_DATA_COUNTn_ADDR \
	WF_UMIB_TOP_B0BRDCR_ADDR
#define WF_UMIB_TOP_B0BRDCR_RX_DATA_COUNTn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B0BRDCR_RX_DATA_COUNTn_SHFT \
	0
#define WF_UMIB_TOP_B0BRMCR_RX_MSDU_COUNTn_ADDR \
	WF_UMIB_TOP_B0BRMCR_ADDR
#define WF_UMIB_TOP_B0BRMCR_RX_MSDU_COUNTn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B0BRMCR_RX_MSDU_COUNTn_SHFT \
	0
#define WF_UMIB_TOP_B0BRPDCR_PF_DROP_COUNTn_ADDR \
	WF_UMIB_TOP_B0BRPDCR_ADDR
#define WF_UMIB_TOP_B0BRPDCR_PF_DROP_COUNTn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B0BRPDCR_PF_DROP_COUNTn_SHFT \
	0
#define WF_UMIB_TOP_B0ARCR_RX_COUNT_ACn_ADDR \
	WF_UMIB_TOP_B0ARCR_ADDR
#define WF_UMIB_TOP_B0ARCR_RX_COUNT_ACn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B0ARCR_RX_COUNT_ACn_SHFT \
	0
#define WF_UMIB_TOP_B0RPDCR_PF_DROP_COUNT_ADDR \
	WF_UMIB_TOP_B0RPDCR_ADDR
#define WF_UMIB_TOP_B0RPDCR_PF_DROP_COUNT_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B0RPDCR_PF_DROP_COUNT_SHFT \
	0
#define WF_UMIB_TOP_B0BRIPCR0_RX_IPV4_COUNTn_ADDR \
	WF_UMIB_TOP_B0BRIPCR0_ADDR
#define WF_UMIB_TOP_B0BRIPCR0_RX_IPV4_COUNTn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B0BRIPCR0_RX_IPV4_COUNTn_SHFT \
	0
#define WF_UMIB_TOP_B0BRIPCR1_RX_IPV4_DROP_COUNTn_ADDR \
	WF_UMIB_TOP_B0BRIPCR1_ADDR
#define WF_UMIB_TOP_B0BRIPCR1_RX_IPV4_DROP_COUNTn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B0BRIPCR1_RX_IPV4_DROP_COUNTn_SHFT \
	0
#define WF_UMIB_TOP_B0BRIPCR2_RX_ICMP4_COUNTn_ADDR \
	WF_UMIB_TOP_B0BRIPCR2_ADDR
#define WF_UMIB_TOP_B0BRIPCR2_RX_ICMP4_COUNTn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B0BRIPCR2_RX_ICMP4_COUNTn_SHFT \
	0
#define WF_UMIB_TOP_B0BRIPCR3_RX_IPV6_COUNTn_ADDR \
	WF_UMIB_TOP_B0BRIPCR3_ADDR
#define WF_UMIB_TOP_B0BRIPCR3_RX_IPV6_COUNTn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B0BRIPCR3_RX_IPV6_COUNTn_SHFT \
	0
#define WF_UMIB_TOP_B0BRIPCR4_RX_IPV6_DROP_COUNTn_ADDR \
	WF_UMIB_TOP_B0BRIPCR4_ADDR
#define WF_UMIB_TOP_B0BRIPCR4_RX_IPV6_DROP_COUNTn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B0BRIPCR4_RX_IPV6_DROP_COUNTn_SHFT \
	0
#define WF_UMIB_TOP_B1BROCR_RX_OK_COUNTn_ADDR \
	WF_UMIB_TOP_B1BROCR_ADDR
#define WF_UMIB_TOP_B1BROCR_RX_OK_COUNTn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B1BROCR_RX_OK_COUNTn_SHFT \
	0
#define WF_UMIB_TOP_B1BRBCR_RX_BYTE_COUNTn_ADDR \
	WF_UMIB_TOP_B1BRBCR_ADDR
#define WF_UMIB_TOP_B1BRBCR_RX_BYTE_COUNTn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B1BRBCR_RX_BYTE_COUNTn_SHFT \
	0
#define WF_UMIB_TOP_B1BRDCR_RX_DATA_COUNTn_ADDR \
	WF_UMIB_TOP_B1BRDCR_ADDR
#define WF_UMIB_TOP_B1BRDCR_RX_DATA_COUNTn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B1BRDCR_RX_DATA_COUNTn_SHFT \
	0
#define WF_UMIB_TOP_B1BRMCR_RX_MSDU_COUNTn_ADDR \
	WF_UMIB_TOP_B1BRMCR_ADDR
#define WF_UMIB_TOP_B1BRMCR_RX_MSDU_COUNTn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B1BRMCR_RX_MSDU_COUNTn_SHFT \
	0
#define WF_UMIB_TOP_B1BRPDCR_PF_DROP_COUNTn_ADDR \
	WF_UMIB_TOP_B1BRPDCR_ADDR
#define WF_UMIB_TOP_B1BRPDCR_PF_DROP_COUNTn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B1BRPDCR_PF_DROP_COUNTn_SHFT \
	0
#define WF_UMIB_TOP_B1ARCR_RX_COUNT_ACn_ADDR \
	WF_UMIB_TOP_B1ARCR_ADDR
#define WF_UMIB_TOP_B1ARCR_RX_COUNT_ACn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B1ARCR_RX_COUNT_ACn_SHFT \
	0
#define WF_UMIB_TOP_B1RPDCR_PF_DROP_COUNT_ADDR \
	WF_UMIB_TOP_B1RPDCR_ADDR
#define WF_UMIB_TOP_B1RPDCR_PF_DROP_COUNT_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B1RPDCR_PF_DROP_COUNT_SHFT \
	0
#define WF_UMIB_TOP_B1BRIPCR0_RX_IPV4_COUNTn_ADDR \
	WF_UMIB_TOP_B1BRIPCR0_ADDR
#define WF_UMIB_TOP_B1BRIPCR0_RX_IPV4_COUNTn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B1BRIPCR0_RX_IPV4_COUNTn_SHFT \
	0
#define WF_UMIB_TOP_B1BRIPCR1_RX_IPV4_DROP_COUNTn_ADDR \
	WF_UMIB_TOP_B1BRIPCR1_ADDR
#define WF_UMIB_TOP_B1BRIPCR1_RX_IPV4_DROP_COUNTn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B1BRIPCR1_RX_IPV4_DROP_COUNTn_SHFT \
	0
#define WF_UMIB_TOP_B1BRIPCR2_RX_ICMP4_COUNTn_ADDR \
	WF_UMIB_TOP_B1BRIPCR2_ADDR
#define WF_UMIB_TOP_B1BRIPCR2_RX_ICMP4_COUNTn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B1BRIPCR2_RX_ICMP4_COUNTn_SHFT \
	0
#define WF_UMIB_TOP_B1BRIPCR3_RX_IPV6_COUNTn_ADDR \
	WF_UMIB_TOP_B1BRIPCR3_ADDR
#define WF_UMIB_TOP_B1BRIPCR3_RX_IPV6_COUNTn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B1BRIPCR3_RX_IPV6_COUNTn_SHFT \
	0
#define WF_UMIB_TOP_B1BRIPCR4_RX_IPV6_DROP_COUNTn_ADDR \
	WF_UMIB_TOP_B1BRIPCR4_ADDR
#define WF_UMIB_TOP_B1BRIPCR4_RX_IPV6_DROP_COUNTn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B1BRIPCR4_RX_IPV6_DROP_COUNTn_SHFT \
	0
#define WF_UMIB_TOP_B2BROCR_RX_OK_COUNTn_ADDR \
	WF_UMIB_TOP_B2BROCR_ADDR
#define WF_UMIB_TOP_B2BROCR_RX_OK_COUNTn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B2BROCR_RX_OK_COUNTn_SHFT \
	0
#define WF_UMIB_TOP_B2BRBCR_RX_BYTE_COUNTn_ADDR \
	WF_UMIB_TOP_B2BRBCR_ADDR
#define WF_UMIB_TOP_B2BRBCR_RX_BYTE_COUNTn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B2BRBCR_RX_BYTE_COUNTn_SHFT \
	0
#define WF_UMIB_TOP_B2BRDCR_RX_DATA_COUNTn_ADDR \
	WF_UMIB_TOP_B2BRDCR_ADDR
#define WF_UMIB_TOP_B2BRDCR_RX_DATA_COUNTn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B2BRDCR_RX_DATA_COUNTn_SHFT \
	0
#define WF_UMIB_TOP_B2BRMCR_RX_MSDU_COUNTn_ADDR \
	WF_UMIB_TOP_B2BRMCR_ADDR
#define WF_UMIB_TOP_B2BRMCR_RX_MSDU_COUNTn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B2BRMCR_RX_MSDU_COUNTn_SHFT \
	0
#define WF_UMIB_TOP_B2BRPDCR_PF_DROP_COUNTn_ADDR \
	WF_UMIB_TOP_B2BRPDCR_ADDR
#define WF_UMIB_TOP_B2BRPDCR_PF_DROP_COUNTn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B2BRPDCR_PF_DROP_COUNTn_SHFT \
	0
#define WF_UMIB_TOP_B2ARCR_RX_COUNT_ACn_ADDR \
	WF_UMIB_TOP_B2ARCR_ADDR
#define WF_UMIB_TOP_B2ARCR_RX_COUNT_ACn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B2ARCR_RX_COUNT_ACn_SHFT \
	0
#define WF_UMIB_TOP_B2RPDCR_PF_DROP_COUNT_ADDR \
	WF_UMIB_TOP_B2RPDCR_ADDR
#define WF_UMIB_TOP_B2RPDCR_PF_DROP_COUNT_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B2RPDCR_PF_DROP_COUNT_SHFT \
	0
#define WF_UMIB_TOP_B2BRIPCR0_RX_IPV4_COUNTn_ADDR \
	WF_UMIB_TOP_B2BRIPCR0_ADDR
#define WF_UMIB_TOP_B2BRIPCR0_RX_IPV4_COUNTn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B2BRIPCR0_RX_IPV4_COUNTn_SHFT \
	0
#define WF_UMIB_TOP_B2BRIPCR1_RX_IPV4_DROP_COUNTn_ADDR \
	WF_UMIB_TOP_B2BRIPCR1_ADDR
#define WF_UMIB_TOP_B2BRIPCR1_RX_IPV4_DROP_COUNTn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B2BRIPCR1_RX_IPV4_DROP_COUNTn_SHFT \
	0
#define WF_UMIB_TOP_B2BRIPCR2_RX_ICMP4_COUNTn_ADDR \
	WF_UMIB_TOP_B2BRIPCR2_ADDR
#define WF_UMIB_TOP_B2BRIPCR2_RX_ICMP4_COUNTn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B2BRIPCR2_RX_ICMP4_COUNTn_SHFT \
	0
#define WF_UMIB_TOP_B2BRIPCR3_RX_IPV6_COUNTn_ADDR \
	WF_UMIB_TOP_B2BRIPCR3_ADDR
#define WF_UMIB_TOP_B2BRIPCR3_RX_IPV6_COUNTn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B2BRIPCR3_RX_IPV6_COUNTn_SHFT \
	0
#define WF_UMIB_TOP_B2BRIPCR4_RX_IPV6_DROP_COUNTn_ADDR \
	WF_UMIB_TOP_B2BRIPCR4_ADDR
#define WF_UMIB_TOP_B2BRIPCR4_RX_IPV6_DROP_COUNTn_MASK \
	0xFFFFFFFF
#define WF_UMIB_TOP_B2BRIPCR4_RX_IPV6_DROP_COUNTn_SHFT \
	0
#ifdef __cplusplus
}
#endif
#endif
