/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * Copyright (c) 2021 MediaTek Inc.
 */

#ifndef __WF_UWTBL_TOP_REGS_H__
#define __WF_UWTBL_TOP_REGS_H__
#include "hal_common.h"
#ifdef __cplusplus
extern "C" {
#endif
#define WF_UWTBL_TOP_BASE \
	0x820c4000
#define WF_UWTBL_TOP_KTVLBR0_ADDR \
	(WF_UWTBL_TOP_BASE + 0x0000)
#define WF_UWTBL_TOP_UCR_ADDR \
	(WF_UWTBL_TOP_BASE + 0x0100)
#define WF_UWTBL_TOP_WDUCR_ADDR \
	(WF_UWTBL_TOP_BASE + 0x0104)
#define WF_UWTBL_TOP_KTCR_ADDR \
	(WF_UWTBL_TOP_BASE + 0x0108)
#define WF_UWTBL_TOP_WIUCR_ADDR \
	(WF_UWTBL_TOP_BASE + 0x0110)
#define WF_UWTBL_TOP_WMUDR_ADDR \
	(WF_UWTBL_TOP_BASE + 0x0114)
#define WF_UWTBL_TOP_WMUMR_ADDR \
	(WF_UWTBL_TOP_BASE + 0x0118)
#define WF_UWTBL_TOP_PICR0_ADDR \
	(WF_UWTBL_TOP_BASE + 0x0120)
#define WF_UWTBL_TOP_PICR1_ADDR \
	(WF_UWTBL_TOP_BASE + 0x0124)
#define WF_UWTBL_TOP_ITCR_ADDR \
	(WF_UWTBL_TOP_BASE + 0x0130)
#define WF_UWTBL_TOP_ITDR0_ADDR \
	(WF_UWTBL_TOP_BASE + 0x0138)
#define WF_UWTBL_TOP_ITDR1_ADDR \
	(WF_UWTBL_TOP_BASE + 0x013C)
#define WF_UWTBL_TOP_DFR_ADDR \
	(WF_UWTBL_TOP_BASE + 0x1FE0)
#define WF_UWTBL_TOP_DMY0_ADDR \
	(WF_UWTBL_TOP_BASE + 0x1FF0)
#define WF_UWTBL_TOP_DMY1_ADDR \
	(WF_UWTBL_TOP_BASE + 0x1FF4)
#define WF_UWTBL_TOP_KTVLBR0_VLB_ADDR \
	WF_UWTBL_TOP_KTVLBR0_ADDR
#define WF_UWTBL_TOP_KTVLBR0_VLB_MASK \
	0xFFFFFFFF
#define WF_UWTBL_TOP_KTVLBR0_VLB_SHFT \
	0
#define WF_UWTBL_TOP_UCR_MAX_BIPN_RANGE_ADDR \
	WF_UWTBL_TOP_UCR_ADDR
#define WF_UWTBL_TOP_UCR_MAX_BIPN_RANGE_MASK \
	0xFFFF0000
#define WF_UWTBL_TOP_UCR_MAX_BIPN_RANGE_SHFT \
	16
#define WF_UWTBL_TOP_UCR_MGMT_SYNC_PNSN_ADDR \
	WF_UWTBL_TOP_UCR_ADDR
#define WF_UWTBL_TOP_UCR_MGMT_SYNC_PNSN_MASK \
	0x00000002
#define WF_UWTBL_TOP_UCR_MGMT_SYNC_PNSN_SHFT \
	1
#define WF_UWTBL_TOP_UCR_PN_INCR_MODE_ADDR \
	WF_UWTBL_TOP_UCR_ADDR
#define WF_UWTBL_TOP_UCR_PN_INCR_MODE_MASK \
	0x00000001
#define WF_UWTBL_TOP_UCR_PN_INCR_MODE_SHFT \
	0
#define WF_UWTBL_TOP_WDUCR_TARGET_ADDR \
	WF_UWTBL_TOP_WDUCR_ADDR
#define WF_UWTBL_TOP_WDUCR_TARGET_MASK \
	0x80000000
#define WF_UWTBL_TOP_WDUCR_TARGET_SHFT \
	31
#define WF_UWTBL_TOP_WDUCR_GROUP_ADDR \
	WF_UWTBL_TOP_WDUCR_ADDR
#define WF_UWTBL_TOP_WDUCR_GROUP_MASK \
	0x0000003F
#define WF_UWTBL_TOP_WDUCR_GROUP_SHFT \
	0
#define WF_UWTBL_TOP_KTCR_REASON_ADDR \
	WF_UWTBL_TOP_KTCR_ADDR
#define WF_UWTBL_TOP_KTCR_REASON_MASK \
	0xC0000000
#define WF_UWTBL_TOP_KTCR_REASON_SHFT \
	30
#define WF_UWTBL_TOP_KTCR_OPERATION_ADDR \
	WF_UWTBL_TOP_KTCR_ADDR
#define WF_UWTBL_TOP_KTCR_OPERATION_MASK \
	0x0000C000
#define WF_UWTBL_TOP_KTCR_OPERATION_SHFT \
	14
#define WF_UWTBL_TOP_KTCR_INDEX_ADDR \
	WF_UWTBL_TOP_KTCR_ADDR
#define WF_UWTBL_TOP_KTCR_INDEX_MASK \
	0x00001FFF
#define WF_UWTBL_TOP_KTCR_INDEX_SHFT \
	0
#define WF_UWTBL_TOP_WIUCR_IU_BUSY_ADDR \
	WF_UWTBL_TOP_WIUCR_ADDR
#define WF_UWTBL_TOP_WIUCR_IU_BUSY_MASK \
	0x80000000
#define WF_UWTBL_TOP_WIUCR_IU_BUSY_SHFT \
	31
#define WF_UWTBL_TOP_WIUCR_DW_ADDR \
	WF_UWTBL_TOP_WIUCR_ADDR
#define WF_UWTBL_TOP_WIUCR_DW_MASK \
	0x0F000000
#define WF_UWTBL_TOP_WIUCR_DW_SHFT \
	24
#define WF_UWTBL_TOP_WIUCR_MASK_UPDATE_ADDR \
	WF_UWTBL_TOP_WIUCR_ADDR
#define WF_UWTBL_TOP_WIUCR_MASK_UPDATE_MASK \
	0x00100000
#define WF_UWTBL_TOP_WIUCR_MASK_UPDATE_SHFT \
	20
#define WF_UWTBL_TOP_WIUCR_PNSN_CLEAR_ADDR \
	WF_UWTBL_TOP_WIUCR_ADDR
#define WF_UWTBL_TOP_WIUCR_PNSN_CLEAR_MASK \
	0x00040000
#define WF_UWTBL_TOP_WIUCR_PNSN_CLEAR_SHFT \
	18
#define WF_UWTBL_TOP_WIUCR_PEERINFO_UPDATE_ADDR \
	WF_UWTBL_TOP_WIUCR_ADDR
#define WF_UWTBL_TOP_WIUCR_PEERINFO_UPDATE_MASK \
	0x00002000
#define WF_UWTBL_TOP_WIUCR_PEERINFO_UPDATE_SHFT \
	13
#define WF_UWTBL_TOP_WIUCR_INDEX_ADDR \
	WF_UWTBL_TOP_WIUCR_ADDR
#define WF_UWTBL_TOP_WIUCR_INDEX_MASK \
	0x00000FFF
#define WF_UWTBL_TOP_WIUCR_INDEX_SHFT \
	0
#define WF_UWTBL_TOP_WMUDR_UPDATE_DATA_ADDR \
	WF_UWTBL_TOP_WMUDR_ADDR
#define WF_UWTBL_TOP_WMUDR_UPDATE_DATA_MASK \
	0xFFFFFFFF
#define WF_UWTBL_TOP_WMUDR_UPDATE_DATA_SHFT \
	0
#define WF_UWTBL_TOP_WMUMR_UPDATE_MASK_ADDR \
	WF_UWTBL_TOP_WMUMR_ADDR
#define WF_UWTBL_TOP_WMUMR_UPDATE_MASK_MASK \
	0xFFFFFFFF
#define WF_UWTBL_TOP_WMUMR_UPDATE_MASK_SHFT \
	0
#define WF_UWTBL_TOP_PICR0_DW0_WTBL_ADDR \
	WF_UWTBL_TOP_PICR0_ADDR
#define WF_UWTBL_TOP_PICR0_DW0_WTBL_MASK \
	0xFFFFFFFF
#define WF_UWTBL_TOP_PICR0_DW0_WTBL_SHFT \
	0
#define WF_UWTBL_TOP_PICR1_DW1_WTBL_ADDR \
	WF_UWTBL_TOP_PICR1_ADDR
#define WF_UWTBL_TOP_PICR1_DW1_WTBL_MASK \
	0xFFFFFFFF
#define WF_UWTBL_TOP_PICR1_DW1_WTBL_SHFT \
	0
#define WF_UWTBL_TOP_ITCR_EXECUTE_ADDR \
	WF_UWTBL_TOP_ITCR_ADDR
#define WF_UWTBL_TOP_ITCR_EXECUTE_MASK \
	0x80000000
#define WF_UWTBL_TOP_ITCR_EXECUTE_SHFT \
	31
#define WF_UWTBL_TOP_ITCR_SELECT_ADDR \
	WF_UWTBL_TOP_ITCR_ADDR
#define WF_UWTBL_TOP_ITCR_SELECT_MASK \
	0x03000000
#define WF_UWTBL_TOP_ITCR_SELECT_SHFT \
	24
#define WF_UWTBL_TOP_ITCR_OP_ADDR \
	WF_UWTBL_TOP_ITCR_ADDR
#define WF_UWTBL_TOP_ITCR_OP_MASK \
	0x00010000
#define WF_UWTBL_TOP_ITCR_OP_SHFT \
	16
#define WF_UWTBL_TOP_ITCR_INDEX_ADDR \
	WF_UWTBL_TOP_ITCR_ADDR
#define WF_UWTBL_TOP_ITCR_INDEX_MASK \
	0x0000003F
#define WF_UWTBL_TOP_ITCR_INDEX_SHFT \
	0
#define WF_UWTBL_TOP_ITDR0_INDIRECT_TABLE_DATA_ADDR \
	WF_UWTBL_TOP_ITDR0_ADDR
#define WF_UWTBL_TOP_ITDR0_INDIRECT_TABLE_DATA_MASK \
	0xFFFFFFFF
#define WF_UWTBL_TOP_ITDR0_INDIRECT_TABLE_DATA_SHFT \
	0
#define WF_UWTBL_TOP_ITDR1_INDIRECT_TABLE_DATA_ADDR \
	WF_UWTBL_TOP_ITDR1_ADDR
#define WF_UWTBL_TOP_ITDR1_INDIRECT_TABLE_DATA_MASK \
	0xFFFFFFFF
#define WF_UWTBL_TOP_ITDR1_INDIRECT_TABLE_DATA_SHFT \
	0
#define WF_UWTBL_TOP_DFR_DEBUG_FSM_ADDR \
	WF_UWTBL_TOP_DFR_ADDR
#define WF_UWTBL_TOP_DFR_DEBUG_FSM_MASK \
	0xFFFFFFFF
#define WF_UWTBL_TOP_DFR_DEBUG_FSM_SHFT \
	0
#define WF_UWTBL_TOP_DMY0_DMY0_ADDR \
	WF_UWTBL_TOP_DMY0_ADDR
#define WF_UWTBL_TOP_DMY0_DMY0_MASK \
	0xFFFFFFFF
#define WF_UWTBL_TOP_DMY0_DMY0_SHFT \
	0
#define WF_UWTBL_TOP_DMY1_DMY1_ADDR \
	WF_UWTBL_TOP_DMY1_ADDR
#define WF_UWTBL_TOP_DMY1_DMY1_MASK \
	0xFFFFFFFF
#define WF_UWTBL_TOP_DMY1_DMY1_SHFT \
	0
#ifdef __cplusplus
}
#endif
#endif
