/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * Copyright (c) 2021 MediaTek Inc.
 */

#ifndef __WF_WTBLON_TOP_REGS_H__
#define __WF_WTBLON_TOP_REGS_H__
#include "hal_common.h"
#ifdef __cplusplus
extern "C" {
#endif
#define WF_WTBLON_TOP_BASE \
	0x820d4000
#define WF_WTBLON_TOP_RVCDAR00_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0000)
#define WF_WTBLON_TOP_RVCDAR01_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0004)
#define WF_WTBLON_TOP_RVCDAR02_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0008)
#define WF_WTBLON_TOP_RVCDAR03_ADDR \
	(WF_WTBLON_TOP_BASE + 0x000C)
#define WF_WTBLON_TOP_RVCDAR_EXT_00_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0080)
#define WF_WTBLON_TOP_PSCDAR00_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0100)
#define WF_WTBLON_TOP_PSCDAR01_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0104)
#define WF_WTBLON_TOP_PSCDAR02_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0108)
#define WF_WTBLON_TOP_PSCDAR03_ADDR \
	(WF_WTBLON_TOP_BASE + 0x010C)
#define WF_WTBLON_TOP_PSCDAR_EXT_00_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0180)
#define WF_WTBLON_TOP_TCGSBR_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0300)
#define WF_WTBLON_TOP_TCGSBRe_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0308)
#define WF_WTBLON_TOP_ACGSBR_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0320)
#define WF_WTBLON_TOP_ACGSBRe_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0328)
#define WF_WTBLON_TOP_RCGSBR_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0340)
#define WF_WTBLON_TOP_RSCR_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0360)
#define WF_WTBLON_TOP_RDWLR0_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0364)
#define WF_WTBLON_TOP_RDWLR1_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0368)
#define WF_WTBLON_TOP_RDWLR2_ADDR \
	(WF_WTBLON_TOP_BASE + 0x036C)
#define WF_WTBLON_TOP_WDUCR_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0370)
#define WF_WTBLON_TOP_WTBLOR_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0374)
#define WF_WTBLON_TOP_WIUCR_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0380)
#define WF_WTBLON_TOP_WMUDR_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0384)
#define WF_WTBLON_TOP_WMUMR_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0388)
#define WF_WTBLON_TOP_RICR0_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0390)
#define WF_WTBLON_TOP_RICR1_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0394)
#define WF_WTBLON_TOP_RIUCR0_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03A0)
#define WF_WTBLON_TOP_RIUCR1_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03A4)
#define WF_WTBLON_TOP_RIUCR2_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03A8)
#define WF_WTBLON_TOP_RIUCR3_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03AC)
#define WF_WTBLON_TOP_ITCR_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03B0)
#define WF_WTBLON_TOP_ITDR0_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03B8)
#define WF_WTBLON_TOP_ITDR1_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03BC)
#define WF_WTBLON_TOP_MBIST_0_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03D0)
#define WF_WTBLON_TOP_MBIST_3_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03D4)
#define WF_WTBLON_TOP_MBIST_4_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03D8)
#define WF_WTBLON_TOP_MBIST_5_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03DC)
#define WF_WTBLON_TOP_MBIST_11_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03E0)
#define WF_WTBLON_TOP_MBIST_12_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03E4)
#define WF_WTBLON_TOP_MBIST_13_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03E8)
#define WF_WTBLON_TOP_MBIST_14_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03EC)
#define WF_WTBLON_TOP_DMY0_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03F0)
#define WF_WTBLON_TOP_DMY1_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03F4)
#define WF_WTBLON_TOP_DFR_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03F8)
#define WF_WTBLON_TOP_DBG_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03FC)
#define WF_WTBLON_TOP_RVCDAR00_RVCDAR00_02_ADDR \
	WF_WTBLON_TOP_RVCDAR00_ADDR
#define WF_WTBLON_TOP_RVCDAR00_RVCDAR00_02_MASK \
	0xFFFF0000
#define WF_WTBLON_TOP_RVCDAR00_RVCDAR00_02_SHFT \
	16
#define WF_WTBLON_TOP_RVCDAR00_RVCDAR00_01_ADDR \
	WF_WTBLON_TOP_RVCDAR00_ADDR
#define WF_WTBLON_TOP_RVCDAR00_RVCDAR00_01_MASK \
	0x0000FF00
#define WF_WTBLON_TOP_RVCDAR00_RVCDAR00_01_SHFT \
	8
#define WF_WTBLON_TOP_RVCDAR00_RVCDAR00_ADDR \
	WF_WTBLON_TOP_RVCDAR00_ADDR
#define WF_WTBLON_TOP_RVCDAR00_RVCDAR00_MASK \
	0x000000FF
#define WF_WTBLON_TOP_RVCDAR00_RVCDAR00_SHFT \
	0
#define WF_WTBLON_TOP_RVCDAR01_RVCDAR01_ADDR \
	WF_WTBLON_TOP_RVCDAR01_ADDR
#define WF_WTBLON_TOP_RVCDAR01_RVCDAR01_MASK \
	0xFFFFFFFF
#define WF_WTBLON_TOP_RVCDAR01_RVCDAR01_SHFT \
	0
#define WF_WTBLON_TOP_RVCDAR02_RVCDAR02_ADDR \
	WF_WTBLON_TOP_RVCDAR02_ADDR
#define WF_WTBLON_TOP_RVCDAR02_RVCDAR02_MASK \
	0xFFFFFFFF
#define WF_WTBLON_TOP_RVCDAR02_RVCDAR02_SHFT \
	0
#define WF_WTBLON_TOP_RVCDAR03_RVCDAR03_ADDR \
	WF_WTBLON_TOP_RVCDAR03_ADDR
#define WF_WTBLON_TOP_RVCDAR03_RVCDAR03_MASK \
	0xFFFFFFFF
#define WF_WTBLON_TOP_RVCDAR03_RVCDAR03_SHFT \
	0
#define WF_WTBLON_TOP_RVCDAR_EXT_00_RVCDAR_EXT_00_01_ADDR \
	WF_WTBLON_TOP_RVCDAR_EXT_00_ADDR
#define WF_WTBLON_TOP_RVCDAR_EXT_00_RVCDAR_EXT_00_01_MASK \
	0x000000F0
#define WF_WTBLON_TOP_RVCDAR_EXT_00_RVCDAR_EXT_00_01_SHFT \
	4
#define WF_WTBLON_TOP_RVCDAR_EXT_00_RVCDAR_EXT_00_ADDR \
	WF_WTBLON_TOP_RVCDAR_EXT_00_ADDR
#define WF_WTBLON_TOP_RVCDAR_EXT_00_RVCDAR_EXT_00_MASK \
	0x0000000F
#define WF_WTBLON_TOP_RVCDAR_EXT_00_RVCDAR_EXT_00_SHFT \
	0
#define WF_WTBLON_TOP_PSCDAR00_PSCDAR00_02_ADDR \
	WF_WTBLON_TOP_PSCDAR00_ADDR
#define WF_WTBLON_TOP_PSCDAR00_PSCDAR00_02_MASK \
	0xFFFF0000
#define WF_WTBLON_TOP_PSCDAR00_PSCDAR00_02_SHFT \
	16
#define WF_WTBLON_TOP_PSCDAR00_PSCDAR00_01_ADDR \
	WF_WTBLON_TOP_PSCDAR00_ADDR
#define WF_WTBLON_TOP_PSCDAR00_PSCDAR00_01_MASK \
	0x0000FF00
#define WF_WTBLON_TOP_PSCDAR00_PSCDAR00_01_SHFT \
	8
#define WF_WTBLON_TOP_PSCDAR00_PSCDAR00_ADDR \
	WF_WTBLON_TOP_PSCDAR00_ADDR
#define WF_WTBLON_TOP_PSCDAR00_PSCDAR00_MASK \
	0x000000FF
#define WF_WTBLON_TOP_PSCDAR00_PSCDAR00_SHFT \
	0
#define WF_WTBLON_TOP_PSCDAR01_PSCDAR01_ADDR \
	WF_WTBLON_TOP_PSCDAR01_ADDR
#define WF_WTBLON_TOP_PSCDAR01_PSCDAR01_MASK \
	0xFFFFFFFF
#define WF_WTBLON_TOP_PSCDAR01_PSCDAR01_SHFT \
	0
#define WF_WTBLON_TOP_PSCDAR02_PSCDAR02_ADDR \
	WF_WTBLON_TOP_PSCDAR02_ADDR
#define WF_WTBLON_TOP_PSCDAR02_PSCDAR02_MASK \
	0xFFFFFFFF
#define WF_WTBLON_TOP_PSCDAR02_PSCDAR02_SHFT \
	0
#define WF_WTBLON_TOP_PSCDAR03_PSCDAR03_ADDR \
	WF_WTBLON_TOP_PSCDAR03_ADDR
#define WF_WTBLON_TOP_PSCDAR03_PSCDAR03_MASK \
	0xFFFFFFFF
#define WF_WTBLON_TOP_PSCDAR03_PSCDAR03_SHFT \
	0
#define WF_WTBLON_TOP_PSCDAR_EXT_00_PSCDAR_EXT_00_01_ADDR \
	WF_WTBLON_TOP_PSCDAR_EXT_00_ADDR
#define WF_WTBLON_TOP_PSCDAR_EXT_00_PSCDAR_EXT_00_01_MASK \
	0x000000F0
#define WF_WTBLON_TOP_PSCDAR_EXT_00_PSCDAR_EXT_00_01_SHFT \
	4
#define WF_WTBLON_TOP_PSCDAR_EXT_00_PSCDAR_EXT_00_ADDR \
	WF_WTBLON_TOP_PSCDAR_EXT_00_ADDR
#define WF_WTBLON_TOP_PSCDAR_EXT_00_PSCDAR_EXT_00_MASK \
	0x0000000F
#define WF_WTBLON_TOP_PSCDAR_EXT_00_PSCDAR_EXT_00_SHFT \
	0
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_64_127_ADDR \
	WF_WTBLON_TOP_TCGSBR_ADDR
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_64_127_MASK \
	0x0000FF00
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_64_127_SHFT \
	8
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_32_63_ADDR \
	WF_WTBLON_TOP_TCGSBR_ADDR
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_32_63_MASK \
	0x000000F0
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_32_63_SHFT \
	4
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_16_31_ADDR \
	WF_WTBLON_TOP_TCGSBR_ADDR
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_16_31_MASK \
	0x0000000C
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_16_31_SHFT \
	2
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_8_15_ADDR \
	WF_WTBLON_TOP_TCGSBR_ADDR
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_8_15_MASK \
	0x00000002
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_8_15_SHFT \
	1
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_0_7_ADDR \
	WF_WTBLON_TOP_TCGSBR_ADDR
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_0_7_MASK \
	0x00000001
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_0_7_SHFT \
	0
#define WF_WTBLON_TOP_TCGSBRe_TX_CNT_STATUS_BITMAP_e0_7_ADDR \
	WF_WTBLON_TOP_TCGSBRe_ADDR
#define WF_WTBLON_TOP_TCGSBRe_TX_CNT_STATUS_BITMAP_e0_7_MASK \
	0x00000001
#define WF_WTBLON_TOP_TCGSBRe_TX_CNT_STATUS_BITMAP_e0_7_SHFT \
	0
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_64_127_ADDR \
	WF_WTBLON_TOP_ACGSBR_ADDR
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_64_127_MASK \
	0x0000FF00
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_64_127_SHFT \
	8
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_32_63_ADDR \
	WF_WTBLON_TOP_ACGSBR_ADDR
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_32_63_MASK \
	0x000000F0
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_32_63_SHFT \
	4
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_16_31_ADDR \
	WF_WTBLON_TOP_ACGSBR_ADDR
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_16_31_MASK \
	0x0000000C
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_16_31_SHFT \
	2
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_8_15_ADDR \
	WF_WTBLON_TOP_ACGSBR_ADDR
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_8_15_MASK \
	0x00000002
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_8_15_SHFT \
	1
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_0_7_ADDR \
	WF_WTBLON_TOP_ACGSBR_ADDR
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_0_7_MASK \
	0x00000001
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_0_7_SHFT \
	0
#define WF_WTBLON_TOP_ACGSBRe_ADM_CNT_STATUS_BITMAP_e0_7_ADDR \
	WF_WTBLON_TOP_ACGSBRe_ADDR
#define WF_WTBLON_TOP_ACGSBRe_ADM_CNT_STATUS_BITMAP_e0_7_MASK \
	0x00000001
#define WF_WTBLON_TOP_ACGSBRe_ADM_CNT_STATUS_BITMAP_e0_7_SHFT \
	0
#define WF_WTBLON_TOP_RCGSBR_RATE_CHANGE_STATUS_BITMAP_ADDR \
	WF_WTBLON_TOP_RCGSBR_ADDR
#define WF_WTBLON_TOP_RCGSBR_RATE_CHANGE_STATUS_BITMAP_MASK \
	0xFFFFFFFF
#define WF_WTBLON_TOP_RCGSBR_RATE_CHANGE_STATUS_BITMAP_SHFT \
	0
#define WF_WTBLON_TOP_RSCR_WTBL_ACCESS_CONCURRENT_ADDR \
	WF_WTBLON_TOP_RSCR_ADDR
#define WF_WTBLON_TOP_RSCR_WTBL_ACCESS_CONCURRENT_MASK \
	0x80000000
#define WF_WTBLON_TOP_RSCR_WTBL_ACCESS_CONCURRENT_SHFT \
	31
#define WF_WTBLON_TOP_RSCR_WTBL_ENABLE_RA_SEARCH_ADDR \
	WF_WTBLON_TOP_RSCR_ADDR
#define WF_WTBLON_TOP_RSCR_WTBL_ENABLE_RA_SEARCH_MASK \
	0x00000020
#define WF_WTBLON_TOP_RSCR_WTBL_ENABLE_RA_SEARCH_SHFT \
	5
#define WF_WTBLON_TOP_RSCR_WTBL_RA_SEARCH_CHECK_BAND_ADDR \
	WF_WTBLON_TOP_RSCR_ADDR
#define WF_WTBLON_TOP_RSCR_WTBL_RA_SEARCH_CHECK_BAND_MASK \
	0x00000010
#define WF_WTBLON_TOP_RSCR_WTBL_RA_SEARCH_CHECK_BAND_SHFT \
	4
#define WF_WTBLON_TOP_RSCR_WTBL_TA_SEARCH_CHECK_BAND_ADDR \
	WF_WTBLON_TOP_RSCR_ADDR
#define WF_WTBLON_TOP_RSCR_WTBL_TA_SEARCH_CHECK_BAND_MASK \
	0x00000008
#define WF_WTBLON_TOP_RSCR_WTBL_TA_SEARCH_CHECK_BAND_SHFT \
	3
#define WF_WTBLON_TOP_RSCR_WTBL_PRECISE_MATCH_ADDR \
	WF_WTBLON_TOP_RSCR_ADDR
#define WF_WTBLON_TOP_RSCR_WTBL_PRECISE_MATCH_MASK \
	0x00000002
#define WF_WTBLON_TOP_RSCR_WTBL_PRECISE_MATCH_SHFT \
	1
#define WF_WTBLON_TOP_RSCR_WTBL_SU_SEARCH_ADDR \
	WF_WTBLON_TOP_RSCR_ADDR
#define WF_WTBLON_TOP_RSCR_WTBL_SU_SEARCH_MASK \
	0x00000001
#define WF_WTBLON_TOP_RSCR_WTBL_SU_SEARCH_SHFT \
	0
#define WF_WTBLON_TOP_RDWLR0_RXD_DUP_WHITE_LIST3_ADDR \
	WF_WTBLON_TOP_RDWLR0_ADDR
#define WF_WTBLON_TOP_RDWLR0_RXD_DUP_WHITE_LIST3_MASK \
	0xFF000000
#define WF_WTBLON_TOP_RDWLR0_RXD_DUP_WHITE_LIST3_SHFT \
	24
#define WF_WTBLON_TOP_RDWLR0_RXD_DUP_WHITE_LIST2_ADDR \
	WF_WTBLON_TOP_RDWLR0_ADDR
#define WF_WTBLON_TOP_RDWLR0_RXD_DUP_WHITE_LIST2_MASK \
	0x00FF0000
#define WF_WTBLON_TOP_RDWLR0_RXD_DUP_WHITE_LIST2_SHFT \
	16
#define WF_WTBLON_TOP_RDWLR0_RXD_DUP_WHITE_LIST1_ADDR \
	WF_WTBLON_TOP_RDWLR0_ADDR
#define WF_WTBLON_TOP_RDWLR0_RXD_DUP_WHITE_LIST1_MASK \
	0x0000FF00
#define WF_WTBLON_TOP_RDWLR0_RXD_DUP_WHITE_LIST1_SHFT \
	8
#define WF_WTBLON_TOP_RDWLR0_RXD_DUP_WHITE_LIST0_ADDR \
	WF_WTBLON_TOP_RDWLR0_ADDR
#define WF_WTBLON_TOP_RDWLR0_RXD_DUP_WHITE_LIST0_MASK \
	0x000000FF
#define WF_WTBLON_TOP_RDWLR0_RXD_DUP_WHITE_LIST0_SHFT \
	0
#define WF_WTBLON_TOP_RDWLR1_RXD_DUP_WHITE_LIST7_ADDR \
	WF_WTBLON_TOP_RDWLR1_ADDR
#define WF_WTBLON_TOP_RDWLR1_RXD_DUP_WHITE_LIST7_MASK \
	0xFF000000
#define WF_WTBLON_TOP_RDWLR1_RXD_DUP_WHITE_LIST7_SHFT \
	24
#define WF_WTBLON_TOP_RDWLR1_RXD_DUP_WHITE_LIST6_ADDR \
	WF_WTBLON_TOP_RDWLR1_ADDR
#define WF_WTBLON_TOP_RDWLR1_RXD_DUP_WHITE_LIST6_MASK \
	0x00FF0000
#define WF_WTBLON_TOP_RDWLR1_RXD_DUP_WHITE_LIST6_SHFT \
	16
#define WF_WTBLON_TOP_RDWLR1_RXD_DUP_WHITE_LIST5_ADDR \
	WF_WTBLON_TOP_RDWLR1_ADDR
#define WF_WTBLON_TOP_RDWLR1_RXD_DUP_WHITE_LIST5_MASK \
	0x0000FF00
#define WF_WTBLON_TOP_RDWLR1_RXD_DUP_WHITE_LIST5_SHFT \
	8
#define WF_WTBLON_TOP_RDWLR1_RXD_DUP_WHITE_LIST4_ADDR \
	WF_WTBLON_TOP_RDWLR1_ADDR
#define WF_WTBLON_TOP_RDWLR1_RXD_DUP_WHITE_LIST4_MASK \
	0x000000FF
#define WF_WTBLON_TOP_RDWLR1_RXD_DUP_WHITE_LIST4_SHFT \
	0
#define WF_WTBLON_TOP_RDWLR2_RXD_DUP_WHITE_LIST11_ADDR \
	WF_WTBLON_TOP_RDWLR2_ADDR
#define WF_WTBLON_TOP_RDWLR2_RXD_DUP_WHITE_LIST11_MASK \
	0xFF000000
#define WF_WTBLON_TOP_RDWLR2_RXD_DUP_WHITE_LIST11_SHFT \
	24
#define WF_WTBLON_TOP_RDWLR2_RXD_DUP_WHITE_LIST10_ADDR \
	WF_WTBLON_TOP_RDWLR2_ADDR
#define WF_WTBLON_TOP_RDWLR2_RXD_DUP_WHITE_LIST10_MASK \
	0x00FF0000
#define WF_WTBLON_TOP_RDWLR2_RXD_DUP_WHITE_LIST10_SHFT \
	16
#define WF_WTBLON_TOP_RDWLR2_RXD_DUP_WHITE_LIST9_ADDR \
	WF_WTBLON_TOP_RDWLR2_ADDR
#define WF_WTBLON_TOP_RDWLR2_RXD_DUP_WHITE_LIST9_MASK \
	0x0000FF00
#define WF_WTBLON_TOP_RDWLR2_RXD_DUP_WHITE_LIST9_SHFT \
	8
#define WF_WTBLON_TOP_RDWLR2_RXD_DUP_WHITE_LIST8_ADDR \
	WF_WTBLON_TOP_RDWLR2_ADDR
#define WF_WTBLON_TOP_RDWLR2_RXD_DUP_WHITE_LIST8_MASK \
	0x000000FF
#define WF_WTBLON_TOP_RDWLR2_RXD_DUP_WHITE_LIST8_SHFT \
	0
#define WF_WTBLON_TOP_WDUCR_GROUP_ADDR \
	WF_WTBLON_TOP_WDUCR_ADDR
#define WF_WTBLON_TOP_WDUCR_GROUP_MASK \
	0x0000001F
#define WF_WTBLON_TOP_WDUCR_GROUP_SHFT \
	0
#define WF_WTBLON_TOP_WTBLOR_LOCK_RX_STAT_CNT_ADDR \
	WF_WTBLON_TOP_WTBLOR_ADDR
#define WF_WTBLON_TOP_WTBLOR_LOCK_RX_STAT_CNT_MASK \
	0x10000000
#define WF_WTBLON_TOP_WTBLOR_LOCK_RX_STAT_CNT_SHFT \
	28
#define WF_WTBLON_TOP_WTBLOR_LOCK_TX_CNT_ADDR \
	WF_WTBLON_TOP_WTBLOR_ADDR
#define WF_WTBLON_TOP_WTBLOR_LOCK_TX_CNT_MASK \
	0x01000000
#define WF_WTBLON_TOP_WTBLOR_LOCK_TX_CNT_SHFT \
	24
#define WF_WTBLON_TOP_WTBLOR_LOCK_ADM_CNT_ADDR \
	WF_WTBLON_TOP_WTBLOR_ADDR
#define WF_WTBLON_TOP_WTBLOR_LOCK_ADM_CNT_MASK \
	0x00100000
#define WF_WTBLON_TOP_WTBLOR_LOCK_ADM_CNT_SHFT \
	20
#define WF_WTBLON_TOP_WTBLOR_LOCK_RATE_ADDR \
	WF_WTBLON_TOP_WTBLOR_ADDR
#define WF_WTBLON_TOP_WTBLOR_LOCK_RATE_MASK \
	0x00001000
#define WF_WTBLON_TOP_WTBLOR_LOCK_RATE_SHFT \
	12
#define WF_WTBLON_TOP_WTBLOR_LOCK_WLAN_IDX_ADDR \
	WF_WTBLON_TOP_WTBLOR_ADDR
#define WF_WTBLON_TOP_WTBLOR_LOCK_WLAN_IDX_MASK \
	0x00000FFF
#define WF_WTBLON_TOP_WTBLOR_LOCK_WLAN_IDX_SHFT \
	0
#define WF_WTBLON_TOP_WIUCR_IU_BUSY_ADDR \
	WF_WTBLON_TOP_WIUCR_ADDR
#define WF_WTBLON_TOP_WIUCR_IU_BUSY_MASK \
	0x80000000
#define WF_WTBLON_TOP_WIUCR_IU_BUSY_SHFT \
	31
#define WF_WTBLON_TOP_WIUCR_DW_ADDR \
	WF_WTBLON_TOP_WIUCR_ADDR
#define WF_WTBLON_TOP_WIUCR_DW_MASK \
	0x3F000000
#define WF_WTBLON_TOP_WIUCR_DW_SHFT \
	24
#define WF_WTBLON_TOP_WIUCR_MASK_UPDATE_ADDR \
	WF_WTBLON_TOP_WIUCR_ADDR
#define WF_WTBLON_TOP_WIUCR_MASK_UPDATE_MASK \
	0x00100000
#define WF_WTBLON_TOP_WIUCR_MASK_UPDATE_SHFT \
	20
#define WF_WTBLON_TOP_WIUCR_RETRY_CNT_CLEAR_ADDR \
	WF_WTBLON_TOP_WIUCR_ADDR
#define WF_WTBLON_TOP_WIUCR_RETRY_CNT_CLEAR_MASK \
	0x00080000
#define WF_WTBLON_TOP_WIUCR_RETRY_CNT_CLEAR_SHFT \
	19
#define WF_WTBLON_TOP_WIUCR_RTS_CNT_CLEAR_ADDR \
	WF_WTBLON_TOP_WIUCR_ADDR
#define WF_WTBLON_TOP_WIUCR_RTS_CNT_CLEAR_MASK \
	0x00040000
#define WF_WTBLON_TOP_WIUCR_RTS_CNT_CLEAR_SHFT \
	18
#define WF_WTBLON_TOP_WIUCR_RX_CNT_CLEAR_ADDR \
	WF_WTBLON_TOP_WIUCR_ADDR
#define WF_WTBLON_TOP_WIUCR_RX_CNT_CLEAR_MASK \
	0x00020000
#define WF_WTBLON_TOP_WIUCR_RX_CNT_CLEAR_SHFT \
	17
#define WF_WTBLON_TOP_WIUCR_TX_RATE_CNT_CLEAR_ADDR \
	WF_WTBLON_TOP_WIUCR_ADDR
#define WF_WTBLON_TOP_WIUCR_TX_RATE_CNT_CLEAR_MASK \
	0x00010000
#define WF_WTBLON_TOP_WIUCR_TX_RATE_CNT_CLEAR_SHFT \
	16
#define WF_WTBLON_TOP_WIUCR_RATE_UPDATE_ADDR \
	WF_WTBLON_TOP_WIUCR_ADDR
#define WF_WTBLON_TOP_WIUCR_RATE_UPDATE_MASK \
	0x00008000
#define WF_WTBLON_TOP_WIUCR_RATE_UPDATE_SHFT \
	15
#define WF_WTBLON_TOP_WIUCR_ADM_CNT_CLEAR_ADDR \
	WF_WTBLON_TOP_WIUCR_ADDR
#define WF_WTBLON_TOP_WIUCR_ADM_CNT_CLEAR_MASK \
	0x00004000
#define WF_WTBLON_TOP_WIUCR_ADM_CNT_CLEAR_SHFT \
	14
#define WF_WTBLON_TOP_WIUCR_PEERINFO_UPDATE_ADDR \
	WF_WTBLON_TOP_WIUCR_ADDR
#define WF_WTBLON_TOP_WIUCR_PEERINFO_UPDATE_MASK \
	0x00002000
#define WF_WTBLON_TOP_WIUCR_PEERINFO_UPDATE_SHFT \
	13
#define WF_WTBLON_TOP_WIUCR_WLAN_IDX_ADDR \
	WF_WTBLON_TOP_WIUCR_ADDR
#define WF_WTBLON_TOP_WIUCR_WLAN_IDX_MASK \
	0x00000FFF
#define WF_WTBLON_TOP_WIUCR_WLAN_IDX_SHFT \
	0
#define WF_WTBLON_TOP_WMUDR_UPDATE_DATA_ADDR \
	WF_WTBLON_TOP_WMUDR_ADDR
#define WF_WTBLON_TOP_WMUDR_UPDATE_DATA_MASK \
	0xFFFFFFFF
#define WF_WTBLON_TOP_WMUDR_UPDATE_DATA_SHFT \
	0
#define WF_WTBLON_TOP_WMUMR_UPDATE_MASK_ADDR \
	WF_WTBLON_TOP_WMUMR_ADDR
#define WF_WTBLON_TOP_WMUMR_UPDATE_MASK_MASK \
	0xFFFFFFFF
#define WF_WTBLON_TOP_WMUMR_UPDATE_MASK_SHFT \
	0
#define WF_WTBLON_TOP_RICR0_DW0_WTBL_ADDR \
	WF_WTBLON_TOP_RICR0_ADDR
#define WF_WTBLON_TOP_RICR0_DW0_WTBL_MASK \
	0xFFFFFFFF
#define WF_WTBLON_TOP_RICR0_DW0_WTBL_SHFT \
	0
#define WF_WTBLON_TOP_RICR1_DW1_WTBL_ADDR \
	WF_WTBLON_TOP_RICR1_ADDR
#define WF_WTBLON_TOP_RICR1_DW1_WTBL_MASK \
	0xFFFFFFFF
#define WF_WTBLON_TOP_RICR1_DW1_WTBL_SHFT \
	0
#define WF_WTBLON_TOP_RIUCR0_DW10_WTBL_ADDR \
	WF_WTBLON_TOP_RIUCR0_ADDR
#define WF_WTBLON_TOP_RIUCR0_DW10_WTBL_MASK \
	0xFFFFFFFF
#define WF_WTBLON_TOP_RIUCR0_DW10_WTBL_SHFT \
	0
#define WF_WTBLON_TOP_RIUCR1_DW11_WTBL_ADDR \
	WF_WTBLON_TOP_RIUCR1_ADDR
#define WF_WTBLON_TOP_RIUCR1_DW11_WTBL_MASK \
	0xFFFFFFFF
#define WF_WTBLON_TOP_RIUCR1_DW11_WTBL_SHFT \
	0
#define WF_WTBLON_TOP_RIUCR2_DW12_WTBL_ADDR \
	WF_WTBLON_TOP_RIUCR2_ADDR
#define WF_WTBLON_TOP_RIUCR2_DW12_WTBL_MASK \
	0xFFFFFFFF
#define WF_WTBLON_TOP_RIUCR2_DW12_WTBL_SHFT \
	0
#define WF_WTBLON_TOP_RIUCR3_DW13_WTBL_ADDR \
	WF_WTBLON_TOP_RIUCR3_ADDR
#define WF_WTBLON_TOP_RIUCR3_DW13_WTBL_MASK \
	0xFFFFFFFF
#define WF_WTBLON_TOP_RIUCR3_DW13_WTBL_SHFT \
	0
#define WF_WTBLON_TOP_ITCR_EXECUTE_ADDR \
	WF_WTBLON_TOP_ITCR_ADDR
#define WF_WTBLON_TOP_ITCR_EXECUTE_MASK \
	0x80000000
#define WF_WTBLON_TOP_ITCR_EXECUTE_SHFT \
	31
#define WF_WTBLON_TOP_ITCR_SELECT_ADDR \
	WF_WTBLON_TOP_ITCR_ADDR
#define WF_WTBLON_TOP_ITCR_SELECT_MASK \
	0x03000000
#define WF_WTBLON_TOP_ITCR_SELECT_SHFT \
	24
#define WF_WTBLON_TOP_ITCR_OP_ADDR \
	WF_WTBLON_TOP_ITCR_ADDR
#define WF_WTBLON_TOP_ITCR_OP_MASK \
	0x00010000
#define WF_WTBLON_TOP_ITCR_OP_SHFT \
	16
#define WF_WTBLON_TOP_ITCR_INDEX_ADDR \
	WF_WTBLON_TOP_ITCR_ADDR
#define WF_WTBLON_TOP_ITCR_INDEX_MASK \
	0x0000003F
#define WF_WTBLON_TOP_ITCR_INDEX_SHFT \
	0
#define WF_WTBLON_TOP_ITDR0_INDIRECT_TABLE_DATA_ADDR \
	WF_WTBLON_TOP_ITDR0_ADDR
#define WF_WTBLON_TOP_ITDR0_INDIRECT_TABLE_DATA_MASK \
	0xFFFFFFFF
#define WF_WTBLON_TOP_ITDR0_INDIRECT_TABLE_DATA_SHFT \
	0
#define WF_WTBLON_TOP_ITDR1_INDIRECT_TABLE_DATA_ADDR \
	WF_WTBLON_TOP_ITDR1_ADDR
#define WF_WTBLON_TOP_ITDR1_INDIRECT_TABLE_DATA_MASK \
	0xFFFFFFFF
#define WF_WTBLON_TOP_ITDR1_INDIRECT_TABLE_DATA_SHFT \
	0
#define WF_WTBLON_TOP_MBIST_0_MEM_USE_DEFAULT_DELSEL_ADDR \
	WF_WTBLON_TOP_MBIST_0_ADDR
#define WF_WTBLON_TOP_MBIST_0_MEM_USE_DEFAULT_DELSEL_MASK \
	0x00000008
#define WF_WTBLON_TOP_MBIST_0_MEM_USE_DEFAULT_DELSEL_SHFT \
	3
#define WF_WTBLON_TOP_MBIST_3_MEM_DELSEL_0_ADDR \
	WF_WTBLON_TOP_MBIST_3_ADDR
#define WF_WTBLON_TOP_MBIST_3_MEM_DELSEL_0_MASK \
	0xFFFFFFFF
#define WF_WTBLON_TOP_MBIST_3_MEM_DELSEL_0_SHFT \
	0
#define WF_WTBLON_TOP_MBIST_4_MEM_DELSEL_1_ADDR \
	WF_WTBLON_TOP_MBIST_4_ADDR
#define WF_WTBLON_TOP_MBIST_4_MEM_DELSEL_1_MASK \
	0xFFFFFFFF
#define WF_WTBLON_TOP_MBIST_4_MEM_DELSEL_1_SHFT \
	0
#define WF_WTBLON_TOP_MBIST_5_MEM_DELSEL_2_ADDR \
	WF_WTBLON_TOP_MBIST_5_ADDR
#define WF_WTBLON_TOP_MBIST_5_MEM_DELSEL_2_MASK \
	0xFFFFFFFF
#define WF_WTBLON_TOP_MBIST_5_MEM_DELSEL_2_SHFT \
	0
#define WF_WTBLON_TOP_MBIST_11_MBIST_REG_FUSE_SEL_ADDR \
	WF_WTBLON_TOP_MBIST_11_ADDR
#define WF_WTBLON_TOP_MBIST_11_MBIST_REG_FUSE_SEL_MASK \
	0x00000001
#define WF_WTBLON_TOP_MBIST_11_MBIST_REG_FUSE_SEL_SHFT \
	0
#define WF_WTBLON_TOP_MBIST_12_LMACON_MBIST_PREFUSE_0_ADDR \
	WF_WTBLON_TOP_MBIST_12_ADDR
#define WF_WTBLON_TOP_MBIST_12_LMACON_MBIST_PREFUSE_0_MASK \
	0x0000FFFF
#define WF_WTBLON_TOP_MBIST_12_LMACON_MBIST_PREFUSE_0_SHFT \
	0
#define WF_WTBLON_TOP_MBIST_13_LMACON_MBIST_PREFUSE_D_0_ADDR \
	WF_WTBLON_TOP_MBIST_13_ADDR
#define WF_WTBLON_TOP_MBIST_13_LMACON_MBIST_PREFUSE_D_0_MASK \
	0x0000FFFF
#define WF_WTBLON_TOP_MBIST_13_LMACON_MBIST_PREFUSE_D_0_SHFT \
	0
#define WF_WTBLON_TOP_MBIST_14_FUSE_LOAD_SEL_ADDR \
	WF_WTBLON_TOP_MBIST_14_ADDR
#define WF_WTBLON_TOP_MBIST_14_FUSE_LOAD_SEL_MASK \
	0x00000001
#define WF_WTBLON_TOP_MBIST_14_FUSE_LOAD_SEL_SHFT \
	0
#define WF_WTBLON_TOP_DMY0_DMY0_ADDR \
	WF_WTBLON_TOP_DMY0_ADDR
#define WF_WTBLON_TOP_DMY0_DMY0_MASK \
	0xFFFFFFFF
#define WF_WTBLON_TOP_DMY0_DMY0_SHFT \
	0
#define WF_WTBLON_TOP_DMY1_DMY1_ADDR \
	WF_WTBLON_TOP_DMY1_ADDR
#define WF_WTBLON_TOP_DMY1_DMY1_MASK \
	0xFFFFFFFF
#define WF_WTBLON_TOP_DMY1_DMY1_SHFT \
	0
#define WF_WTBLON_TOP_DFR_SIFIF_CS_ADDR \
	WF_WTBLON_TOP_DFR_ADDR
#define WF_WTBLON_TOP_DFR_SIFIF_CS_MASK \
	0x70000000
#define WF_WTBLON_TOP_DFR_SIFIF_CS_SHFT \
	28
#define WF_WTBLON_TOP_DFR_MLOIF_DBG_ADDR \
	WF_WTBLON_TOP_DFR_ADDR
#define WF_WTBLON_TOP_DFR_MLOIF_DBG_MASK \
	0x00F00000
#define WF_WTBLON_TOP_DFR_MLOIF_DBG_SHFT \
	20
#define WF_WTBLON_TOP_DFR_SRAMIF_CS_ADDR \
	WF_WTBLON_TOP_DFR_ADDR
#define WF_WTBLON_TOP_DFR_SRAMIF_CS_MASK \
	0x0000FFFF
#define WF_WTBLON_TOP_DFR_SRAMIF_CS_SHFT \
	0
#define WF_WTBLON_TOP_DBG_CKEN_ERROR_ADDR \
	WF_WTBLON_TOP_DBG_ADDR
#define WF_WTBLON_TOP_DBG_CKEN_ERROR_MASK \
	0x80000000
#define WF_WTBLON_TOP_DBG_CKEN_ERROR_SHFT \
	31
#define WF_WTBLON_TOP_DBG_DBG_MODE_ADDR \
	WF_WTBLON_TOP_DBG_ADDR
#define WF_WTBLON_TOP_DBG_DBG_MODE_MASK \
	0x00008000
#define WF_WTBLON_TOP_DBG_DBG_MODE_SHFT \
	15
#define WF_WTBLON_TOP_DBG_DBG_USER_SEL_ADDR \
	WF_WTBLON_TOP_DBG_ADDR
#define WF_WTBLON_TOP_DBG_DBG_USER_SEL_MASK \
	0x0000003F
#define WF_WTBLON_TOP_DBG_DBG_USER_SEL_SHFT \
	0
#ifdef __cplusplus
}
#endif
#endif
