# SPDX-License-Identifier: GPL-2.0-only
# Support GKI mixed build
ifeq ($(DEVICE_MODULES_PATH),)
DEVICE_MODULES_PATH = $(srctree)
else
LINUXINCLUDE := $(DEVCIE_MODULES_INCLUDE) $(LINUXINCLUDE)
endif

KO_CODE_PATH := $(if $(filter /%,$(src)),,$(srctree)/)$(src)

IMGSYS_ISP7SP_MODULE := mtk_imgsys_isp7sp

#platform dependent
ccflags-y += -I$(KO_CODE_PATH)/../../../mtk-hcp/legacy
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/cmdq/mailbox/
ccflags-y += -I$(KO_CODE_PATH)/../../common/
ccflags-y += -I$(KO_CODE_PATH)/../cmdq/legacy
ccflags-y += -I$(KO_CODE_PATH)/
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/mtk-interconnect/
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/smi/
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/iommu
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/iommu
ccflags-y += -I$(DEVICE_MODULES_PATH)/include/soc/mediatek
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include/

ccflags-y += -ferror-limit=0

$(info "imgsys, isp7sp device_module_path = $(DEVICE_MODULES_PATH)")
$(info "imgsys, isp7sp srctree_path = $(srctree)")
$(info "imgsys, isp7sp src_path = $(src)")
$(info "imgsys, isp7sp ko_code_path = $(KO_CODE_PATH)")

#register TF CB
ifneq ($(wildcard $(DEVICE_MODULES_PATH)/include/dt-bindings/memory/mt6897-larb-port.h),)
subdir-ccflags-y += -DIMGSYS_TF_DUMP_7SP_P
endif

ifneq ($(wildcard $(DEVICE_MODULES_PATH)/include/dt-bindings/memory/mt6989-larb-port.h),)
subdir-ccflags-y += -DIMGSYS_TF_DUMP_7SP_L
endif

$(info "imgsys, subdir-ccflags-y = $(subdir-ccflags-y)")

subdir-ccflags-y += -DMTK_IOVA_SINK2KERNEL

$(info imgsys DEVICE_MODULES_PATH=$(DEVICE_MODULES_PATH))
NOTDIR_DEVICE_MODULES_PATH = $(notdir $(DEVICE_MODULES_PATH))
$(info imgsys NOTDIR_DEVICE_MODULES_PATH=$(NOTDIR_DEVICE_MODULES_PATH))
KERNEL_VERSION = $(patsubst kernel_device_modules-%,%,$(NOTDIR_DEVICE_MODULES_PATH))
$(info imgsys KERNEL_VERSION=$(KERNEL_VERSION))

#$(info mtk_aov sort=$(sort 6.6 $(KERNEL_VERSION)))
#$(info mtk_aov word=$(word 1,$(sort 6.6 $(KERNEL_VERSION))))

ifeq (6.6,$(word 1,$(sort 6.6 $(KERNEL_VERSION))))
ccflags-y += -DNEW_DMA_BUF_API
endif

$(IMGSYS_ISP7SP_MODULE)-objs := \
mtk_imgsys-v4l2.o \
mtk_imgsys-dev.o \
mtk_imgsys-sys.o \
mtk_imgsys-isp7sp.o \
mtk_imgsys-debug.o \
imgsys_modules/mtk_imgsys-dip.o \
imgsys_modules/mtk_imgsys-traw.o \
imgsys_modules/mtk_imgsys-pqdip.o \
imgsys_modules/mtk_imgsys-wpe.o \
imgsys_modules/mtk_imgsys-me.o \
imgsys_modules/mtk_imgsys-adl.o

obj-${CONFIG_VIDEO_MTK_ISP_IMGSYS_7SP} += $(IMGSYS_ISP7SP_MODULE).o

