/* SPDX-License-Identifier: GPL-2.0 OR BSD-3-Clause */
/*
 * Copyright (c) 2021 MediaTek Inc.
 */

#ifndef __CONN_BUS_CR_ON_REGS_H__
#define __CONN_BUS_CR_ON_REGS_H__

#include "hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif


/* ************************************************************************** */
/*  */
/* CONN_BUS_CR_ON CR Definitions */
/*  */
/* ************************************************************************** */

#define CONN_BUS_CR_ON_BASE        (0x1800E000 + CONN_INFRA_REMAPPING_OFFSET)

#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x000) /* E000 */
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_1_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x004) /* E004 */
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_ON_DCM_CTL_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x008) /* E008 */
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x00C) /* E00C */
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_1_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x010) /* E010 */
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_2_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x014) /* E014 */
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x018) /* E018 */
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_4_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x01C) /* E01C */
#define CONN_BUS_CR_ON_CONN_VON_IDLE_MASK_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x100) /* E100 */
#define CONN_BUS_CR_ON_CONN_VON_BUS_IDLE_DEBOUNCE_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x104) /* E104 */
#define CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_EN_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x108) /* E108 */
#define CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_THRE_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x10C) /* E10C */
#define CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_CLR_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x110) /* E110 */
#define CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_IRQ_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x114) /* E114 */
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_EN_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x118) /* E118 */
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_THRE_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x11C) /* E11C */
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_CLR_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x120) /* E120 */
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_IRQ_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x124) /* E124 */
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N7_TIMEOUT_INFO_0_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x128) /* E128 */
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N7_TIMEOUT_INFO_1_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x12C) /* E12C */
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N7_TIMEOUT_ADDR_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x130) /* E130 */
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N7_TIMEOUT_WDATA_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x134) /* E134 */
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N9_TIMEOUT_INFO_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x138) /* E138 */
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N9_TIMEOUT_ADDR_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x13C) /* E13C */
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N9_TIMEOUT_WDATA_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x140) /* E140 */
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_APB_SLV_ACCESS_DETECT_EN_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x200) /* E200 */
#define CONN_BUS_CR_ON_CONN_INFRA_CKSYS_CK_CTRL_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x320) /* E320 */
#define CONN_BUS_CR_ON_CONN_INFRA_PCIE2AP_REMAP_DOMAIN_ID_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x400) /* E400 */
#define CONN_BUS_CR_ON_CONN_INFRA_PCIE2AP_REMAP_WF__1__0_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x410) /* E410 */
#define CONN_BUS_CR_ON_CONN_INFRA_PCIE2AP_REMAP_WF__3__2_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x414) /* E414 */
#define CONN_BUS_CR_ON_CONN_INFRA_PCIE2AP_REMAP_WF__5__4_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x418) /* E418 */
#define CONN_BUS_CR_ON_CONN_INFRA_PCIE2AP_REMAP_WF__7__6_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x41C) /* E41C */
#define CONN_BUS_CR_ON_CONN_INFRA_PCIE2AP_REMAP_WF__9__8_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x420) /* E420 */
#define CONN_BUS_CR_ON_CONN_INFRA_PCIE2AP_REMAP_WF_11_10_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x424) /* E424 */
#define CONN_BUS_CR_ON_CONN_INFRA_PCIE2AP_REMAP_WF_13_12_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x428) /* E428 */
#define CONN_BUS_CR_ON_CONN_INFRA_PCIE2AP_REMAP_WF_15_14_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x42C) /* E42C */
#define CONN_BUS_CR_ON_CONN_INFRA_PCIE2AP_REMAP_BT__1__0_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x430) /* E430 */
#define CONN_BUS_CR_ON_CONN_INFRA_PCIE2AP_REMAP_BT__3__2_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x434) /* E434 */
#define CONN_BUS_CR_ON_CONN_INFRA_PCIE2AP_REMAP_BT__5__4_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x438) /* E438 */
#define CONN_BUS_CR_ON_CONN_INFRA_PCIE2AP_REMAP_BT__7__6_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x43C) /* E43C */
#define CONN_BUS_CR_ON_CONN_INFRA_PCIE2AP_REMAP_BT__9__8_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x440) /* E440 */
#define CONN_BUS_CR_ON_CONN_INFRA_PCIE2AP_REMAP_BT_11_10_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x444) /* E444 */
#define CONN_BUS_CR_ON_CONN_INFRA_PCIE2AP_REMAP_BT_13_12_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x448) /* E448 */
#define CONN_BUS_CR_ON_CONN_INFRA_PCIE2AP_REMAP_BT_15_14_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x44C) /* E44C */
#define CONN_BUS_CR_ON_CONN_INFRA_SECURITY_CTRL_ADDR \
	(CONN_BUS_CR_ON_BASE + 0x500) /* E500 */
#define CONN_BUS_CR_ON_ADDR_AP2CONN_AHB_GALS_CFG_ADDR \
	(CONN_BUS_CR_ON_BASE + 0xA00) /* EA00 */
#define CONN_BUS_CR_ON_ADDR_AP2CONN_AHB_GALS_DBG_ADDR \
	(CONN_BUS_CR_ON_BASE + 0xA04) /* EA04 */

#ifdef __cplusplus
}
#endif

#endif /* __CONN_BUS_CR_ON_REGS_H__ */
