/* SPDX-License-Identifier: BSD-2-Clause */
//[File]            : cb_ckgen_top.h
//[Revision time]   : Thu Jul 28 18:15:10 2022
//[Description]     : This file is auto generated by CODA
//[Copyright]       : Copyright (C) 2022 Mediatek Incorportion. All rights reserved.

#ifndef __CB_CKGEN_TOP_REGS_H__
#define __CB_CKGEN_TOP_REGS_H__

#include "hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif


//****************************************************************************
//
//                     CB_CKGEN_TOP CR Definitions                     
//
//****************************************************************************

#define CB_CKGEN_TOP_BASE                                      0x70000000

#define CB_CKGEN_TOP_CBTOP_OSC_STA_ADDR                        (CB_CKGEN_TOP_BASE + 0x000) // 0000
#define CB_CKGEN_TOP_CBTOP_CKGEN0_ADDR                         (CB_CKGEN_TOP_BASE + 0x100) // 0100
#define CB_CKGEN_TOP_CBTOP_CKGEN2_ADDR                         (CB_CKGEN_TOP_BASE + 0x108) // 0108
#define CB_CKGEN_TOP_CBTOP_PWRCTLCR_ADDR                       (CB_CKGEN_TOP_BASE + 0x110) // 0110
#define CB_CKGEN_TOP_CBTOP_RSV_ADDR                            (CB_CKGEN_TOP_BASE + 0x130) // 0130
#define CB_CKGEN_TOP_CBTOP_MISC2_ADDR                          (CB_CKGEN_TOP_BASE + 0x134) // 0134
#define CB_CKGEN_TOP_CBTOP_CKGEN5_ADDR                         (CB_CKGEN_TOP_BASE + 0x148) // 0148
#define CB_CKGEN_TOP_CBTOP_CKGEN6_ADDR                         (CB_CKGEN_TOP_BASE + 0x14C) // 014C
#define CB_CKGEN_TOP_CBTOP_CKGEN7_ADDR                         (CB_CKGEN_TOP_BASE + 0x150) // 0150
#define CB_CKGEN_TOP_CBTOP_CKGEN8_ADDR                         (CB_CKGEN_TOP_BASE + 0x154) // 0154
#define CB_CKGEN_TOP_CBTOP_CKGEN9_ADDR                         (CB_CKGEN_TOP_BASE + 0x158) // 0158
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_ADDR                        (CB_CKGEN_TOP_BASE + 0x200) // 0200
#define CB_CKGEN_TOP_CBTOP_PLLGP_1_ADDR                        (CB_CKGEN_TOP_BASE + 0x204) // 0204
#define CB_CKGEN_TOP_CBTOP_PLLGP_2_ADDR                        (CB_CKGEN_TOP_BASE + 0x208) // 0208
#define CB_CKGEN_TOP_CBTOP_PLLGP_3_ADDR                        (CB_CKGEN_TOP_BASE + 0x20C) // 020C
#define CB_CKGEN_TOP_CBTOP_PLLGP_4_ADDR                        (CB_CKGEN_TOP_BASE + 0x210) // 0210
#define CB_CKGEN_TOP_CBTOP_PLLGP_5_ADDR                        (CB_CKGEN_TOP_BASE + 0x214) // 0214
#define CB_CKGEN_TOP_CBTOP_ULPOSC_0_ADDR                       (CB_CKGEN_TOP_BASE + 0x240) // 0240
#define CB_CKGEN_TOP_CBTOP_ULPOSC_1_ADDR                       (CB_CKGEN_TOP_BASE + 0x244) // 0244
#define CB_CKGEN_TOP_CBTOP_ULPOSC_2_ADDR                       (CB_CKGEN_TOP_BASE + 0x248) // 0248
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_ADDR                       (CB_CKGEN_TOP_BASE + 0x24C) // 024C
#define CB_CKGEN_TOP_CBTOP_ULPOSC_4_ADDR                       (CB_CKGEN_TOP_BASE + 0x250) // 0250




/* =====================================================================================

  ---CBTOP_OSC_STA (0x70000000 + 0x000)---

    xo_state[2..0]               - (RO) xo_state for debug
    RESERVED3[31..3]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_OSC_STA_xo_state_ADDR               CB_CKGEN_TOP_CBTOP_OSC_STA_ADDR
#define CB_CKGEN_TOP_CBTOP_OSC_STA_xo_state_MASK               0x00000007                // xo_state[2..0]
#define CB_CKGEN_TOP_CBTOP_OSC_STA_xo_state_SHFT               0

/* =====================================================================================

  ---CBTOP_CKGEN0 (0x70000000 + 0x100)---

    RESERVED0[17..0]             - (RO) Reserved bits
    PMU_32k_DIV_SEL_SW[18]       - (RW) Int 32k xtal divider selection switch
                                     0: XTAL divider ratio is HW mapping by XTAL_FREQ[10:0]
                                       [10]: XTAL=52  MHz ,11'd1586, 52   MHz/1587=32.766..KHz
                                       [9] : XTAL=40   MHz ,11'd1220, 40   MHz/1221=32.760..KHz
                                       [8] : XTAL=38.4MHz ,11'd1170, 38.4MHz/1171=32.792..KHz
                                       [6] : XTAL=26   MHz ,11'd  793, 26   MHz/  794=32.745..KHz
                                       [5] : XTAL=24   MHz ,11'd  732, 24   MHz/  733=32.742..KHz
                                       [4] : XTAL=20   MHz ,11'd  610, 20   MHz/  611=32.733..KHz
                                       [3] : XTAL=19.2MHz ,11'd  585, 19.2MHz/  586=32.764..KHZ
                                     1: XTAL divider ratio from 32K_DIV_SEL[10:0]
    PMU_32k_DIV_EN[19]           - (RW) Int 32k xtal divider enable switch
                                     0: divider disable
                                     1: divider enable
    RESERVED20[20]               - (RO) Reserved bits
    PMU_32k_DIV_SEL[31..21]      - (RW) Divider for Int 32k
                                     clk div is set to N, the divided clock is xtal clock/ (N+1).
                                     Default : 26MHz/(793+1) = 32.745..KHz

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_CKGEN0_PMU_32k_DIV_SEL_ADDR         CB_CKGEN_TOP_CBTOP_CKGEN0_ADDR
#define CB_CKGEN_TOP_CBTOP_CKGEN0_PMU_32k_DIV_SEL_MASK         0xFFE00000                // PMU_32k_DIV_SEL[31..21]
#define CB_CKGEN_TOP_CBTOP_CKGEN0_PMU_32k_DIV_SEL_SHFT         21
#define CB_CKGEN_TOP_CBTOP_CKGEN0_PMU_32k_DIV_EN_ADDR          CB_CKGEN_TOP_CBTOP_CKGEN0_ADDR
#define CB_CKGEN_TOP_CBTOP_CKGEN0_PMU_32k_DIV_EN_MASK          0x00080000                // PMU_32k_DIV_EN[19]
#define CB_CKGEN_TOP_CBTOP_CKGEN0_PMU_32k_DIV_EN_SHFT          19
#define CB_CKGEN_TOP_CBTOP_CKGEN0_PMU_32k_DIV_SEL_SW_ADDR      CB_CKGEN_TOP_CBTOP_CKGEN0_ADDR
#define CB_CKGEN_TOP_CBTOP_CKGEN0_PMU_32k_DIV_SEL_SW_MASK      0x00040000                // PMU_32k_DIV_SEL_SW[18]
#define CB_CKGEN_TOP_CBTOP_CKGEN0_PMU_32k_DIV_SEL_SW_SHFT      18

/* =====================================================================================

  ---CBTOP_CKGEN2 (0x70000000 + 0x108)---

    RESERVED0[20..0]             - (RO) Reserved bits
    cr_hif_xtal_sel_manual[21]   - (RW)  xxx 
    cr_hif_xtal_sel[22]          - (RW)  xxx 
    RESERVED23[31..23]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_CKGEN2_cr_hif_xtal_sel_ADDR         CB_CKGEN_TOP_CBTOP_CKGEN2_ADDR
#define CB_CKGEN_TOP_CBTOP_CKGEN2_cr_hif_xtal_sel_MASK         0x00400000                // cr_hif_xtal_sel[22]
#define CB_CKGEN_TOP_CBTOP_CKGEN2_cr_hif_xtal_sel_SHFT         22
#define CB_CKGEN_TOP_CBTOP_CKGEN2_cr_hif_xtal_sel_manual_ADDR  CB_CKGEN_TOP_CBTOP_CKGEN2_ADDR
#define CB_CKGEN_TOP_CBTOP_CKGEN2_cr_hif_xtal_sel_manual_MASK  0x00200000                // cr_hif_xtal_sel_manual[21]
#define CB_CKGEN_TOP_CBTOP_CKGEN2_cr_hif_xtal_sel_manual_SHFT  21

/* =====================================================================================

  ---CBTOP_PWRCTLCR (0x70000000 + 0x110)---

    XTAL_FREQ[10..0]             - (RW) Should set as 1 hot
                                     [10] : XTAL=52MHz
                                     [9] :   XTAL=40MHz
                                     [8] :   XTAL=38.4MHz
                                     [6] :   XTAL=26MHz (default)
                                     [5] :   XTAL=24MHz
                                     [4] :   XTAL=20MHz
                                     [3] :   XTAL=19.2MHz
                                     [2] :   XTAL=25MHz
    RESERVED11[31..11]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_PWRCTLCR_XTAL_FREQ_ADDR             CB_CKGEN_TOP_CBTOP_PWRCTLCR_ADDR
#define CB_CKGEN_TOP_CBTOP_PWRCTLCR_XTAL_FREQ_MASK             0x000007FF                // XTAL_FREQ[10..0]
#define CB_CKGEN_TOP_CBTOP_PWRCTLCR_XTAL_FREQ_SHFT             0

/* =====================================================================================

  ---CBTOP_RSV (0x70000000 + 0x130)---

    sdio_wrapper_ck_bt_req[0]    - (RW)  xxx 
    sdio_wrapper_ck_wf_req[1]    - (RW)  xxx 
    cr_reserved_0[13..2]         - (RW)  xxx 
    d_polling_timeout_flag[14]   - (RW) polling d die timeout flag(SE used)
    a_polling_timeout_flag[15]   - (RW) polling a die timeout flag(SE used)
    cr_reserved_1[31..16]        - (RW)  xxx 

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_RSV_cr_reserved_1_ADDR              CB_CKGEN_TOP_CBTOP_RSV_ADDR
#define CB_CKGEN_TOP_CBTOP_RSV_cr_reserved_1_MASK              0xFFFF0000                // cr_reserved_1[31..16]
#define CB_CKGEN_TOP_CBTOP_RSV_cr_reserved_1_SHFT              16
#define CB_CKGEN_TOP_CBTOP_RSV_a_polling_timeout_flag_ADDR     CB_CKGEN_TOP_CBTOP_RSV_ADDR
#define CB_CKGEN_TOP_CBTOP_RSV_a_polling_timeout_flag_MASK     0x00008000                // a_polling_timeout_flag[15]
#define CB_CKGEN_TOP_CBTOP_RSV_a_polling_timeout_flag_SHFT     15
#define CB_CKGEN_TOP_CBTOP_RSV_d_polling_timeout_flag_ADDR     CB_CKGEN_TOP_CBTOP_RSV_ADDR
#define CB_CKGEN_TOP_CBTOP_RSV_d_polling_timeout_flag_MASK     0x00004000                // d_polling_timeout_flag[14]
#define CB_CKGEN_TOP_CBTOP_RSV_d_polling_timeout_flag_SHFT     14
#define CB_CKGEN_TOP_CBTOP_RSV_cr_reserved_0_ADDR              CB_CKGEN_TOP_CBTOP_RSV_ADDR
#define CB_CKGEN_TOP_CBTOP_RSV_cr_reserved_0_MASK              0x00003FFC                // cr_reserved_0[13..2]
#define CB_CKGEN_TOP_CBTOP_RSV_cr_reserved_0_SHFT              2
#define CB_CKGEN_TOP_CBTOP_RSV_sdio_wrapper_ck_wf_req_ADDR     CB_CKGEN_TOP_CBTOP_RSV_ADDR
#define CB_CKGEN_TOP_CBTOP_RSV_sdio_wrapper_ck_wf_req_MASK     0x00000002                // sdio_wrapper_ck_wf_req[1]
#define CB_CKGEN_TOP_CBTOP_RSV_sdio_wrapper_ck_wf_req_SHFT     1
#define CB_CKGEN_TOP_CBTOP_RSV_sdio_wrapper_ck_bt_req_ADDR     CB_CKGEN_TOP_CBTOP_RSV_ADDR
#define CB_CKGEN_TOP_CBTOP_RSV_sdio_wrapper_ck_bt_req_MASK     0x00000001                // sdio_wrapper_ck_bt_req[0]
#define CB_CKGEN_TOP_CBTOP_RSV_sdio_wrapper_ck_bt_req_SHFT     0

/* =====================================================================================

  ---CBTOP_MISC2 (0x70000000 + 0x134)---

    RESERVED0[9..0]              - (RO) Reserved bits
    NO_CG_XTAL[10]               - (RW) 0 : XTAL clock to subsys will be gated by VCORE_RDY signal
                                     1 : XTAL clock to subsys will not be gated by VCORE_RDY signal
    RESERVED11[28..11]           - (RO) Reserved bits
    DBG_SEL[31..29]              - (RW) Debug port selection

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_MISC2_DBG_SEL_ADDR                  CB_CKGEN_TOP_CBTOP_MISC2_ADDR
#define CB_CKGEN_TOP_CBTOP_MISC2_DBG_SEL_MASK                  0xE0000000                // DBG_SEL[31..29]
#define CB_CKGEN_TOP_CBTOP_MISC2_DBG_SEL_SHFT                  29
#define CB_CKGEN_TOP_CBTOP_MISC2_NO_CG_XTAL_ADDR               CB_CKGEN_TOP_CBTOP_MISC2_ADDR
#define CB_CKGEN_TOP_CBTOP_MISC2_NO_CG_XTAL_MASK               0x00000400                // NO_CG_XTAL[10]
#define CB_CKGEN_TOP_CBTOP_MISC2_NO_CG_XTAL_SHFT               10

/* =====================================================================================

  ---CBTOP_CKGEN5 (0x70000000 + 0x148)---

    pllgp_ref_cken[0]            - (RW)  xxx 
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_CKGEN5_pllgp_ref_cken_ADDR          CB_CKGEN_TOP_CBTOP_CKGEN5_ADDR
#define CB_CKGEN_TOP_CBTOP_CKGEN5_pllgp_ref_cken_MASK          0x00000001                // pllgp_ref_cken[0]
#define CB_CKGEN_TOP_CBTOP_CKGEN5_pllgp_ref_cken_SHFT          0

/* =====================================================================================

  ---CBTOP_CKGEN6 (0x70000000 + 0x14C)---

    pcie_phya_ref_cken[0]        - (RW)  xxx 
    RESERVED1[3..1]              - (RO) Reserved bits
    pcie_phyd_ref_cken[4]        - (RW)  xxx 
    RESERVED5[31..5]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_CKGEN6_pcie_phyd_ref_cken_ADDR      CB_CKGEN_TOP_CBTOP_CKGEN6_ADDR
#define CB_CKGEN_TOP_CBTOP_CKGEN6_pcie_phyd_ref_cken_MASK      0x00000010                // pcie_phyd_ref_cken[4]
#define CB_CKGEN_TOP_CBTOP_CKGEN6_pcie_phyd_ref_cken_SHFT      4
#define CB_CKGEN_TOP_CBTOP_CKGEN6_pcie_phya_ref_cken_ADDR      CB_CKGEN_TOP_CBTOP_CKGEN6_ADDR
#define CB_CKGEN_TOP_CBTOP_CKGEN6_pcie_phya_ref_cken_MASK      0x00000001                // pcie_phya_ref_cken[0]
#define CB_CKGEN_TOP_CBTOP_CKGEN6_pcie_phya_ref_cken_SHFT      0

/* =====================================================================================

  ---CBTOP_CKGEN7 (0x70000000 + 0x150)---

    usb20_phya_ref_cken[0]       - (RW)  xxx 
    RESERVED1[3..1]              - (RO) Reserved bits
    usb20_phyd_ref_cken[4]       - (RW)  xxx 
    RESERVED5[31..5]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_CKGEN7_usb20_phyd_ref_cken_ADDR     CB_CKGEN_TOP_CBTOP_CKGEN7_ADDR
#define CB_CKGEN_TOP_CBTOP_CKGEN7_usb20_phyd_ref_cken_MASK     0x00000010                // usb20_phyd_ref_cken[4]
#define CB_CKGEN_TOP_CBTOP_CKGEN7_usb20_phyd_ref_cken_SHFT     4
#define CB_CKGEN_TOP_CBTOP_CKGEN7_usb20_phya_ref_cken_ADDR     CB_CKGEN_TOP_CBTOP_CKGEN7_ADDR
#define CB_CKGEN_TOP_CBTOP_CKGEN7_usb20_phya_ref_cken_MASK     0x00000001                // usb20_phya_ref_cken[0]
#define CB_CKGEN_TOP_CBTOP_CKGEN7_usb20_phya_ref_cken_SHFT     0

/* =====================================================================================

  ---CBTOP_CKGEN8 (0x70000000 + 0x154)---

    usb30_phya_ref_cken[0]       - (RW)  xxx 
    RESERVED1[3..1]              - (RO) Reserved bits
    usb30_phyd_ref_cken[4]       - (RW)  xxx 
    RESERVED5[7..5]              - (RO) Reserved bits
    usb30_phyd_osc_ref_cken[8]   - (RW)  xxx 
    RESERVED9[11..9]             - (RO) Reserved bits
    usb30_phyd_rosc_ref_cken[12] - (RW)  xxx 
    RESERVED13[31..13]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_CKGEN8_usb30_phyd_rosc_ref_cken_ADDR CB_CKGEN_TOP_CBTOP_CKGEN8_ADDR
#define CB_CKGEN_TOP_CBTOP_CKGEN8_usb30_phyd_rosc_ref_cken_MASK 0x00001000                // usb30_phyd_rosc_ref_cken[12]
#define CB_CKGEN_TOP_CBTOP_CKGEN8_usb30_phyd_rosc_ref_cken_SHFT 12
#define CB_CKGEN_TOP_CBTOP_CKGEN8_usb30_phyd_osc_ref_cken_ADDR CB_CKGEN_TOP_CBTOP_CKGEN8_ADDR
#define CB_CKGEN_TOP_CBTOP_CKGEN8_usb30_phyd_osc_ref_cken_MASK 0x00000100                // usb30_phyd_osc_ref_cken[8]
#define CB_CKGEN_TOP_CBTOP_CKGEN8_usb30_phyd_osc_ref_cken_SHFT 8
#define CB_CKGEN_TOP_CBTOP_CKGEN8_usb30_phyd_ref_cken_ADDR     CB_CKGEN_TOP_CBTOP_CKGEN8_ADDR
#define CB_CKGEN_TOP_CBTOP_CKGEN8_usb30_phyd_ref_cken_MASK     0x00000010                // usb30_phyd_ref_cken[4]
#define CB_CKGEN_TOP_CBTOP_CKGEN8_usb30_phyd_ref_cken_SHFT     4
#define CB_CKGEN_TOP_CBTOP_CKGEN8_usb30_phya_ref_cken_ADDR     CB_CKGEN_TOP_CBTOP_CKGEN8_ADDR
#define CB_CKGEN_TOP_CBTOP_CKGEN8_usb30_phya_ref_cken_MASK     0x00000001                // usb30_phya_ref_cken[0]
#define CB_CKGEN_TOP_CBTOP_CKGEN8_usb30_phya_ref_cken_SHFT     0

/* =====================================================================================

  ---CBTOP_CKGEN9 (0x70000000 + 0x158)---

    connsys_156M_gfmux_sel[1..0] - (RW)  xxx 
    RESERVED2[15..2]             - (RO) Reserved bits
    infra_156M_gfmux_sel[16]     - (RW)  xxx 
    RESERVED17[31..17]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_CKGEN9_infra_156M_gfmux_sel_ADDR    CB_CKGEN_TOP_CBTOP_CKGEN9_ADDR
#define CB_CKGEN_TOP_CBTOP_CKGEN9_infra_156M_gfmux_sel_MASK    0x00010000                // infra_156M_gfmux_sel[16]
#define CB_CKGEN_TOP_CBTOP_CKGEN9_infra_156M_gfmux_sel_SHFT    16
#define CB_CKGEN_TOP_CBTOP_CKGEN9_connsys_156M_gfmux_sel_ADDR  CB_CKGEN_TOP_CBTOP_CKGEN9_ADDR
#define CB_CKGEN_TOP_CBTOP_CKGEN9_connsys_156M_gfmux_sel_MASK  0x00000003                // connsys_156M_gfmux_sel[1..0]
#define CB_CKGEN_TOP_CBTOP_CKGEN9_connsys_156M_gfmux_sel_SHFT  0

/* =====================================================================================

  ---CBTOP_PLLGP_0 (0x70000000 + 0x200)---

    rg_pll_sdm_fra_en[0]         - (RW)  xxx 
    rg_pll_ck_en[1]              - (RW)  xxx 
    rg_pll_sdm_pcw_chg[2]        - (RW)  xxx 
    rg_pll_posdiv[5..3]          - (RW)  xxx 
    rg_pll_reserve[11..6]        - (RW)  xxx 
    rg_pllgp_prediv[13..12]      - (RW)  xxx 
    rg_pllgp_lvrod_en[14]        - (RW)  xxx 
    rg_pllgpgh_tst_en[15]        - (RW)  xxx 
    rg_pllgpgh_tstck_en[16]      - (RW)  xxx 
    rg_pllgpgh_tst_sel[18..17]   - (RW)  xxx 
    rg_pllgpgh_tstod_en[19]      - (RW)  xxx 
    rg_pllgpgh_a2dck_en[20]      - (RW)  xxx 
    rg_pllgpgh_vod_en[21]        - (RW)  xxx 
    rg_pllgpgh_tstop_en[22]      - (RW)  xxx 
    pllgp_reserved_0[31..23]     - (RW)  xxx 

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_pllgp_reserved_0_ADDR       CB_CKGEN_TOP_CBTOP_PLLGP_0_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_pllgp_reserved_0_MASK       0xFF800000                // pllgp_reserved_0[31..23]
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_pllgp_reserved_0_SHFT       23
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pllgpgh_tstop_en_ADDR    CB_CKGEN_TOP_CBTOP_PLLGP_0_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pllgpgh_tstop_en_MASK    0x00400000                // rg_pllgpgh_tstop_en[22]
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pllgpgh_tstop_en_SHFT    22
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pllgpgh_vod_en_ADDR      CB_CKGEN_TOP_CBTOP_PLLGP_0_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pllgpgh_vod_en_MASK      0x00200000                // rg_pllgpgh_vod_en[21]
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pllgpgh_vod_en_SHFT      21
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pllgpgh_a2dck_en_ADDR    CB_CKGEN_TOP_CBTOP_PLLGP_0_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pllgpgh_a2dck_en_MASK    0x00100000                // rg_pllgpgh_a2dck_en[20]
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pllgpgh_a2dck_en_SHFT    20
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pllgpgh_tstod_en_ADDR    CB_CKGEN_TOP_CBTOP_PLLGP_0_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pllgpgh_tstod_en_MASK    0x00080000                // rg_pllgpgh_tstod_en[19]
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pllgpgh_tstod_en_SHFT    19
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pllgpgh_tst_sel_ADDR     CB_CKGEN_TOP_CBTOP_PLLGP_0_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pllgpgh_tst_sel_MASK     0x00060000                // rg_pllgpgh_tst_sel[18..17]
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pllgpgh_tst_sel_SHFT     17
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pllgpgh_tstck_en_ADDR    CB_CKGEN_TOP_CBTOP_PLLGP_0_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pllgpgh_tstck_en_MASK    0x00010000                // rg_pllgpgh_tstck_en[16]
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pllgpgh_tstck_en_SHFT    16
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pllgpgh_tst_en_ADDR      CB_CKGEN_TOP_CBTOP_PLLGP_0_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pllgpgh_tst_en_MASK      0x00008000                // rg_pllgpgh_tst_en[15]
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pllgpgh_tst_en_SHFT      15
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pllgp_lvrod_en_ADDR      CB_CKGEN_TOP_CBTOP_PLLGP_0_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pllgp_lvrod_en_MASK      0x00004000                // rg_pllgp_lvrod_en[14]
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pllgp_lvrod_en_SHFT      14
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pllgp_prediv_ADDR        CB_CKGEN_TOP_CBTOP_PLLGP_0_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pllgp_prediv_MASK        0x00003000                // rg_pllgp_prediv[13..12]
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pllgp_prediv_SHFT        12
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pll_reserve_ADDR         CB_CKGEN_TOP_CBTOP_PLLGP_0_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pll_reserve_MASK         0x00000FC0                // rg_pll_reserve[11..6]
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pll_reserve_SHFT         6
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pll_posdiv_ADDR          CB_CKGEN_TOP_CBTOP_PLLGP_0_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pll_posdiv_MASK          0x00000038                // rg_pll_posdiv[5..3]
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pll_posdiv_SHFT          3
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pll_sdm_pcw_chg_ADDR     CB_CKGEN_TOP_CBTOP_PLLGP_0_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pll_sdm_pcw_chg_MASK     0x00000004                // rg_pll_sdm_pcw_chg[2]
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pll_sdm_pcw_chg_SHFT     2
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pll_ck_en_ADDR           CB_CKGEN_TOP_CBTOP_PLLGP_0_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pll_ck_en_MASK           0x00000002                // rg_pll_ck_en[1]
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pll_ck_en_SHFT           1
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pll_sdm_fra_en_ADDR      CB_CKGEN_TOP_CBTOP_PLLGP_0_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pll_sdm_fra_en_MASK      0x00000001                // rg_pll_sdm_fra_en[0]
#define CB_CKGEN_TOP_CBTOP_PLLGP_0_rg_pll_sdm_fra_en_SHFT      0

/* =====================================================================================

  ---CBTOP_PLLGP_1 (0x70000000 + 0x204)---

    rg_pll_sdm_pcw[31..0]        - (RW)  xxx 

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_PLLGP_1_rg_pll_sdm_pcw_ADDR         CB_CKGEN_TOP_CBTOP_PLLGP_1_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_1_rg_pll_sdm_pcw_MASK         0xFFFFFFFF                // rg_pll_sdm_pcw[31..0]
#define CB_CKGEN_TOP_CBTOP_PLLGP_1_rg_pll_sdm_pcw_SHFT         0

/* =====================================================================================

  ---CBTOP_PLLGP_2 (0x70000000 + 0x208)---

    rg_pll1_bw[2..0]             - (RW)  xxx 
    rg_pll1_glitch_free_en[3]    - (RW)  xxx 
    rg_pllgp_4h_fs[5..4]         - (RW)  xxx 
    RESERVED6[6]                 - (RO) Reserved bits
    rg_pllgp_4h_fs_en[7]         - (RW)  xxx 
    rg_pllgp_4h_ichp[9..8]       - (RW)  xxx 
    rg_pllgp_4h_ibias[11..10]    - (RW)  xxx 
    rg_pllgp_4h_rst_dly[13..12]  - (RW)  xxx 
    rg_pllgp_4h_lvr_refsel[15..14] - (RW)  xxx 
    RESERVED16[31..16]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_PLLGP_2_rg_pllgp_4h_lvr_refsel_ADDR CB_CKGEN_TOP_CBTOP_PLLGP_2_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_2_rg_pllgp_4h_lvr_refsel_MASK 0x0000C000                // rg_pllgp_4h_lvr_refsel[15..14]
#define CB_CKGEN_TOP_CBTOP_PLLGP_2_rg_pllgp_4h_lvr_refsel_SHFT 14
#define CB_CKGEN_TOP_CBTOP_PLLGP_2_rg_pllgp_4h_rst_dly_ADDR    CB_CKGEN_TOP_CBTOP_PLLGP_2_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_2_rg_pllgp_4h_rst_dly_MASK    0x00003000                // rg_pllgp_4h_rst_dly[13..12]
#define CB_CKGEN_TOP_CBTOP_PLLGP_2_rg_pllgp_4h_rst_dly_SHFT    12
#define CB_CKGEN_TOP_CBTOP_PLLGP_2_rg_pllgp_4h_ibias_ADDR      CB_CKGEN_TOP_CBTOP_PLLGP_2_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_2_rg_pllgp_4h_ibias_MASK      0x00000C00                // rg_pllgp_4h_ibias[11..10]
#define CB_CKGEN_TOP_CBTOP_PLLGP_2_rg_pllgp_4h_ibias_SHFT      10
#define CB_CKGEN_TOP_CBTOP_PLLGP_2_rg_pllgp_4h_ichp_ADDR       CB_CKGEN_TOP_CBTOP_PLLGP_2_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_2_rg_pllgp_4h_ichp_MASK       0x00000300                // rg_pllgp_4h_ichp[9..8]
#define CB_CKGEN_TOP_CBTOP_PLLGP_2_rg_pllgp_4h_ichp_SHFT       8
#define CB_CKGEN_TOP_CBTOP_PLLGP_2_rg_pllgp_4h_fs_en_ADDR      CB_CKGEN_TOP_CBTOP_PLLGP_2_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_2_rg_pllgp_4h_fs_en_MASK      0x00000080                // rg_pllgp_4h_fs_en[7]
#define CB_CKGEN_TOP_CBTOP_PLLGP_2_rg_pllgp_4h_fs_en_SHFT      7
#define CB_CKGEN_TOP_CBTOP_PLLGP_2_rg_pllgp_4h_fs_ADDR         CB_CKGEN_TOP_CBTOP_PLLGP_2_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_2_rg_pllgp_4h_fs_MASK         0x00000030                // rg_pllgp_4h_fs[5..4]
#define CB_CKGEN_TOP_CBTOP_PLLGP_2_rg_pllgp_4h_fs_SHFT         4
#define CB_CKGEN_TOP_CBTOP_PLLGP_2_rg_pll1_glitch_free_en_ADDR CB_CKGEN_TOP_CBTOP_PLLGP_2_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_2_rg_pll1_glitch_free_en_MASK 0x00000008                // rg_pll1_glitch_free_en[3]
#define CB_CKGEN_TOP_CBTOP_PLLGP_2_rg_pll1_glitch_free_en_SHFT 3
#define CB_CKGEN_TOP_CBTOP_PLLGP_2_rg_pll1_bw_ADDR             CB_CKGEN_TOP_CBTOP_PLLGP_2_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_2_rg_pll1_bw_MASK             0x00000007                // rg_pll1_bw[2..0]
#define CB_CKGEN_TOP_CBTOP_PLLGP_2_rg_pll1_bw_SHFT             0

/* =====================================================================================

  ---CBTOP_PLLGP_3 (0x70000000 + 0x20C)---

    rg_pllgp_sw_mode[0]          - (RW)  xxx 
    rg_rg_pll_en[1]              - (RW)  xxx 
    rg_da_pll_sdm_iso_en[2]      - (RW)  xxx 
    rg_da_pll_sdm_pwr_on[3]      - (RW)  xxx 
    RESERVED4[31..4]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_PLLGP_3_rg_da_pll_sdm_pwr_on_ADDR   CB_CKGEN_TOP_CBTOP_PLLGP_3_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_3_rg_da_pll_sdm_pwr_on_MASK   0x00000008                // rg_da_pll_sdm_pwr_on[3]
#define CB_CKGEN_TOP_CBTOP_PLLGP_3_rg_da_pll_sdm_pwr_on_SHFT   3
#define CB_CKGEN_TOP_CBTOP_PLLGP_3_rg_da_pll_sdm_iso_en_ADDR   CB_CKGEN_TOP_CBTOP_PLLGP_3_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_3_rg_da_pll_sdm_iso_en_MASK   0x00000004                // rg_da_pll_sdm_iso_en[2]
#define CB_CKGEN_TOP_CBTOP_PLLGP_3_rg_da_pll_sdm_iso_en_SHFT   2
#define CB_CKGEN_TOP_CBTOP_PLLGP_3_rg_rg_pll_en_ADDR           CB_CKGEN_TOP_CBTOP_PLLGP_3_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_3_rg_rg_pll_en_MASK           0x00000002                // rg_rg_pll_en[1]
#define CB_CKGEN_TOP_CBTOP_PLLGP_3_rg_rg_pll_en_SHFT           1
#define CB_CKGEN_TOP_CBTOP_PLLGP_3_rg_pllgp_sw_mode_ADDR       CB_CKGEN_TOP_CBTOP_PLLGP_3_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_3_rg_pllgp_sw_mode_MASK       0x00000001                // rg_pllgp_sw_mode[0]
#define CB_CKGEN_TOP_CBTOP_PLLGP_3_rg_pllgp_sw_mode_SHFT       0

/* =====================================================================================

  ---CBTOP_PLLGP_4 (0x70000000 + 0x210)---

    pllgp_reserved_4[31..0]      - (RW)  xxx 

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_PLLGP_4_pllgp_reserved_4_ADDR       CB_CKGEN_TOP_CBTOP_PLLGP_4_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_4_pllgp_reserved_4_MASK       0xFFFFFFFF                // pllgp_reserved_4[31..0]
#define CB_CKGEN_TOP_CBTOP_PLLGP_4_pllgp_reserved_4_SHFT       0

/* =====================================================================================

  ---CBTOP_PLLGP_5 (0x70000000 + 0x214)---

    ad_pll_sdm_pwr_ack[0]        - (RO)  xxx 
    da_pll_sdm_pwr_on[1]         - (RO)  xxx 
    da_pll_sdm_iso_en[2]         - (RO)  xxx 
    rg_pll_en[3]                 - (RO)  xxx 
    RESERVED4[9..4]              - (RO) Reserved bits
    cbtop_pll_div8[10]           - (RO)  xxx 
    RESERVED11[31..11]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_PLLGP_5_cbtop_pll_div8_ADDR         CB_CKGEN_TOP_CBTOP_PLLGP_5_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_5_cbtop_pll_div8_MASK         0x00000400                // cbtop_pll_div8[10]
#define CB_CKGEN_TOP_CBTOP_PLLGP_5_cbtop_pll_div8_SHFT         10
#define CB_CKGEN_TOP_CBTOP_PLLGP_5_rg_pll_en_ADDR              CB_CKGEN_TOP_CBTOP_PLLGP_5_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_5_rg_pll_en_MASK              0x00000008                // rg_pll_en[3]
#define CB_CKGEN_TOP_CBTOP_PLLGP_5_rg_pll_en_SHFT              3
#define CB_CKGEN_TOP_CBTOP_PLLGP_5_da_pll_sdm_iso_en_ADDR      CB_CKGEN_TOP_CBTOP_PLLGP_5_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_5_da_pll_sdm_iso_en_MASK      0x00000004                // da_pll_sdm_iso_en[2]
#define CB_CKGEN_TOP_CBTOP_PLLGP_5_da_pll_sdm_iso_en_SHFT      2
#define CB_CKGEN_TOP_CBTOP_PLLGP_5_da_pll_sdm_pwr_on_ADDR      CB_CKGEN_TOP_CBTOP_PLLGP_5_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_5_da_pll_sdm_pwr_on_MASK      0x00000002                // da_pll_sdm_pwr_on[1]
#define CB_CKGEN_TOP_CBTOP_PLLGP_5_da_pll_sdm_pwr_on_SHFT      1
#define CB_CKGEN_TOP_CBTOP_PLLGP_5_ad_pll_sdm_pwr_ack_ADDR     CB_CKGEN_TOP_CBTOP_PLLGP_5_ADDR
#define CB_CKGEN_TOP_CBTOP_PLLGP_5_ad_pll_sdm_pwr_ack_MASK     0x00000001                // ad_pll_sdm_pwr_ack[0]
#define CB_CKGEN_TOP_CBTOP_PLLGP_5_ad_pll_sdm_pwr_ack_SHFT     0

/* =====================================================================================

  ---CBTOP_ULPOSC_0 (0x70000000 + 0x240)---

    rg_osc_rsv1[7..0]            - (RW)  xxx 
    rg_osc_rsv2[15..8]           - (RW)  xxx 
    rg_osc_cali_value[22..16]    - (RW)  xxx 
    RESERVED23[23]               - (RO) Reserved bits
    rg_da_osc_en[24]             - (RW)  xxx 
    RESERVED25[27..25]           - (RO) Reserved bits
    rg_da_osc_rst[28]            - (RW)  xxx 
    RESERVED29[31..29]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_ULPOSC_0_rg_da_osc_rst_ADDR         CB_CKGEN_TOP_CBTOP_ULPOSC_0_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_0_rg_da_osc_rst_MASK         0x10000000                // rg_da_osc_rst[28]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_0_rg_da_osc_rst_SHFT         28
#define CB_CKGEN_TOP_CBTOP_ULPOSC_0_rg_da_osc_en_ADDR          CB_CKGEN_TOP_CBTOP_ULPOSC_0_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_0_rg_da_osc_en_MASK          0x01000000                // rg_da_osc_en[24]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_0_rg_da_osc_en_SHFT          24
#define CB_CKGEN_TOP_CBTOP_ULPOSC_0_rg_osc_cali_value_ADDR     CB_CKGEN_TOP_CBTOP_ULPOSC_0_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_0_rg_osc_cali_value_MASK     0x007F0000                // rg_osc_cali_value[22..16]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_0_rg_osc_cali_value_SHFT     16
#define CB_CKGEN_TOP_CBTOP_ULPOSC_0_rg_osc_rsv2_ADDR           CB_CKGEN_TOP_CBTOP_ULPOSC_0_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_0_rg_osc_rsv2_MASK           0x0000FF00                // rg_osc_rsv2[15..8]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_0_rg_osc_rsv2_SHFT           8
#define CB_CKGEN_TOP_CBTOP_ULPOSC_0_rg_osc_rsv1_ADDR           CB_CKGEN_TOP_CBTOP_ULPOSC_0_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_0_rg_osc_rsv1_MASK           0x000000FF                // rg_osc_rsv1[7..0]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_0_rg_osc_rsv1_SHFT           0

/* =====================================================================================

  ---CBTOP_ULPOSC_1 (0x70000000 + 0x244)---

    rg_ckgen_k1[7..0]            - (RW)  xxx 
    RESERVED8[11..8]             - (RO) Reserved bits
    rg_freq_offset_value[19..12] - (RW)  xxx 
    rg_abist_meter_sw_en[20]     - (RW)  xxx 
    RESERVED21[23..21]           - (RO) Reserved bits
    rg_ckgen_tri_cal[24]         - (RW)  xxx 
    RESERVED25[27..25]           - (RO) Reserved bits
    rg_mux_sel[31..28]           - (RW)  xxx 

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_ULPOSC_1_rg_mux_sel_ADDR            CB_CKGEN_TOP_CBTOP_ULPOSC_1_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_1_rg_mux_sel_MASK            0xF0000000                // rg_mux_sel[31..28]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_1_rg_mux_sel_SHFT            28
#define CB_CKGEN_TOP_CBTOP_ULPOSC_1_rg_ckgen_tri_cal_ADDR      CB_CKGEN_TOP_CBTOP_ULPOSC_1_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_1_rg_ckgen_tri_cal_MASK      0x01000000                // rg_ckgen_tri_cal[24]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_1_rg_ckgen_tri_cal_SHFT      24
#define CB_CKGEN_TOP_CBTOP_ULPOSC_1_rg_abist_meter_sw_en_ADDR  CB_CKGEN_TOP_CBTOP_ULPOSC_1_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_1_rg_abist_meter_sw_en_MASK  0x00100000                // rg_abist_meter_sw_en[20]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_1_rg_abist_meter_sw_en_SHFT  20
#define CB_CKGEN_TOP_CBTOP_ULPOSC_1_rg_freq_offset_value_ADDR  CB_CKGEN_TOP_CBTOP_ULPOSC_1_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_1_rg_freq_offset_value_MASK  0x000FF000                // rg_freq_offset_value[19..12]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_1_rg_freq_offset_value_SHFT  12
#define CB_CKGEN_TOP_CBTOP_ULPOSC_1_rg_ckgen_k1_ADDR           CB_CKGEN_TOP_CBTOP_ULPOSC_1_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_1_rg_ckgen_k1_MASK           0x000000FF                // rg_ckgen_k1[7..0]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_1_rg_ckgen_k1_SHFT           0

/* =====================================================================================

  ---CBTOP_ULPOSC_2 (0x70000000 + 0x248)---

    ckgen_cal_cnt[15..0]         - (RO)  xxx 
    ckgen_cal_ok[16]             - (RO)  xxx 
    RESERVED17[19..17]           - (RO) Reserved bits
    ckgen_cal_valid[20]          - (RO)  xxx 
    RESERVED21[23..21]           - (RO) Reserved bits
    kdone_OSC_CALI[30..24]       - (RO)  xxx 
    ulposc_ready[31]             - (RO)  xxx 

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_ULPOSC_2_ulposc_ready_ADDR          CB_CKGEN_TOP_CBTOP_ULPOSC_2_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_2_ulposc_ready_MASK          0x80000000                // ulposc_ready[31]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_2_ulposc_ready_SHFT          31
#define CB_CKGEN_TOP_CBTOP_ULPOSC_2_kdone_OSC_CALI_ADDR        CB_CKGEN_TOP_CBTOP_ULPOSC_2_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_2_kdone_OSC_CALI_MASK        0x7F000000                // kdone_OSC_CALI[30..24]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_2_kdone_OSC_CALI_SHFT        24
#define CB_CKGEN_TOP_CBTOP_ULPOSC_2_ckgen_cal_valid_ADDR       CB_CKGEN_TOP_CBTOP_ULPOSC_2_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_2_ckgen_cal_valid_MASK       0x00100000                // ckgen_cal_valid[20]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_2_ckgen_cal_valid_SHFT       20
#define CB_CKGEN_TOP_CBTOP_ULPOSC_2_ckgen_cal_ok_ADDR          CB_CKGEN_TOP_CBTOP_ULPOSC_2_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_2_ckgen_cal_ok_MASK          0x00010000                // ckgen_cal_ok[16]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_2_ckgen_cal_ok_SHFT          16
#define CB_CKGEN_TOP_CBTOP_ULPOSC_2_ckgen_cal_cnt_ADDR         CB_CKGEN_TOP_CBTOP_ULPOSC_2_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_2_ckgen_cal_cnt_MASK         0x0000FFFF                // ckgen_cal_cnt[15..0]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_2_ckgen_cal_cnt_SHFT         0

/* =====================================================================================

  ---CBTOP_ULPOSC_3 (0x70000000 + 0x24C)---

    topaon_ulposc_52M_rdy[0]     - (RO)  xxx 
    lvts_ulposc_26M_rdy[1]       - (RO)  xxx 
    connsys_ulposc_52M_rdy[2]    - (RO)  xxx 
    connsys_ulposc_156M_rdy[3]   - (RO)  xxx 
    cbinfra_ulposc_26M_rdy[4]    - (RO)  xxx 
    cbinfra_ulposc_52M_rdy[5]    - (RO)  xxx 
    cbinfra_ulposc_156M_rdy[6]   - (RO)  xxx 
    RESERVED7[15..7]             - (RO) Reserved bits
    topaon_ulposc_52M_req[16]    - (RO)  xxx 
    lvts_ulposc_26M_req[17]      - (RO)  xxx 
    connsys_ulposc_52M_req[18]   - (RO)  xxx 
    connsys_ulposc_156M_req[19]  - (RO)  xxx 
    cbinfra_ulposc_26M_req[20]   - (RO)  xxx 
    cbinfra_ulposc_52M_req[21]   - (RO)  xxx 
    cbinfra_ulposc_156M_req[22]  - (RO)  xxx 
    RESERVED23[31..23]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_156M_req_ADDR CB_CKGEN_TOP_CBTOP_ULPOSC_3_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_156M_req_MASK 0x00400000                // cbinfra_ulposc_156M_req[22]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_156M_req_SHFT 22
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_52M_req_ADDR CB_CKGEN_TOP_CBTOP_ULPOSC_3_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_52M_req_MASK 0x00200000                // cbinfra_ulposc_52M_req[21]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_52M_req_SHFT 21
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_26M_req_ADDR CB_CKGEN_TOP_CBTOP_ULPOSC_3_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_26M_req_MASK 0x00100000                // cbinfra_ulposc_26M_req[20]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_26M_req_SHFT 20
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_connsys_ulposc_156M_req_ADDR CB_CKGEN_TOP_CBTOP_ULPOSC_3_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_connsys_ulposc_156M_req_MASK 0x00080000                // connsys_ulposc_156M_req[19]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_connsys_ulposc_156M_req_SHFT 19
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_connsys_ulposc_52M_req_ADDR CB_CKGEN_TOP_CBTOP_ULPOSC_3_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_connsys_ulposc_52M_req_MASK 0x00040000                // connsys_ulposc_52M_req[18]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_connsys_ulposc_52M_req_SHFT 18
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_lvts_ulposc_26M_req_ADDR   CB_CKGEN_TOP_CBTOP_ULPOSC_3_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_lvts_ulposc_26M_req_MASK   0x00020000                // lvts_ulposc_26M_req[17]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_lvts_ulposc_26M_req_SHFT   17
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_topaon_ulposc_52M_req_ADDR CB_CKGEN_TOP_CBTOP_ULPOSC_3_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_topaon_ulposc_52M_req_MASK 0x00010000                // topaon_ulposc_52M_req[16]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_topaon_ulposc_52M_req_SHFT 16
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_156M_rdy_ADDR CB_CKGEN_TOP_CBTOP_ULPOSC_3_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_156M_rdy_MASK 0x00000040                // cbinfra_ulposc_156M_rdy[6]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_156M_rdy_SHFT 6
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_52M_rdy_ADDR CB_CKGEN_TOP_CBTOP_ULPOSC_3_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_52M_rdy_MASK 0x00000020                // cbinfra_ulposc_52M_rdy[5]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_52M_rdy_SHFT 5
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_26M_rdy_ADDR CB_CKGEN_TOP_CBTOP_ULPOSC_3_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_26M_rdy_MASK 0x00000010                // cbinfra_ulposc_26M_rdy[4]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_26M_rdy_SHFT 4
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_connsys_ulposc_156M_rdy_ADDR CB_CKGEN_TOP_CBTOP_ULPOSC_3_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_connsys_ulposc_156M_rdy_MASK 0x00000008                // connsys_ulposc_156M_rdy[3]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_connsys_ulposc_156M_rdy_SHFT 3
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_connsys_ulposc_52M_rdy_ADDR CB_CKGEN_TOP_CBTOP_ULPOSC_3_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_connsys_ulposc_52M_rdy_MASK 0x00000004                // connsys_ulposc_52M_rdy[2]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_connsys_ulposc_52M_rdy_SHFT 2
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_lvts_ulposc_26M_rdy_ADDR   CB_CKGEN_TOP_CBTOP_ULPOSC_3_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_lvts_ulposc_26M_rdy_MASK   0x00000002                // lvts_ulposc_26M_rdy[1]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_lvts_ulposc_26M_rdy_SHFT   1
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_topaon_ulposc_52M_rdy_ADDR CB_CKGEN_TOP_CBTOP_ULPOSC_3_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_topaon_ulposc_52M_rdy_MASK 0x00000001                // topaon_ulposc_52M_rdy[0]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_topaon_ulposc_52M_rdy_SHFT 0

/* =====================================================================================

  ---CBTOP_ULPOSC_4 (0x70000000 + 0x250)---

    ckgen_load_cnt[9..0]         - (RW)  xxx 
    RESERVED10[31..10]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_ULPOSC_4_ckgen_load_cnt_ADDR        CB_CKGEN_TOP_CBTOP_ULPOSC_4_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_4_ckgen_load_cnt_MASK        0x000003FF                // ckgen_load_cnt[9..0]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_4_ckgen_load_cnt_SHFT        0

#ifdef __cplusplus
}
#endif

#endif // __CB_CKGEN_TOP_REGS_H__
