/* SPDX-License-Identifier: BSD-2-Clause */
//[File]            : cb_infra_rgu.h
//[Revision time]   : Fri Jul  1 18:50:31 2022
//[Description]     : This file is auto generated by CODA
//[Copyright]       : Copyright (C) 2022 Mediatek Incorportion. All rights reserved.

#ifndef __CB_INFRA_RGU_REGS_H__
#define __CB_INFRA_RGU_REGS_H__

#include "hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif


//****************************************************************************
//
//                     CB_INFRA_RGU CR Definitions                     
//
//****************************************************************************

#define CB_INFRA_RGU_BASE                                      0x70028000

#define CB_INFRA_RGU_RGU_DUMMY_ADDR                            (CB_INFRA_RGU_BASE + 0x018) // 8018
#define CB_INFRA_RGU_HIF_MEM_CTL_PD_ADDR                       (CB_INFRA_RGU_BASE + 0x01C) // 801C
#define CB_INFRA_RGU_HIF_MEM_CTL_PD_2_ADDR                     (CB_INFRA_RGU_BASE + 0x024) // 8024
#define CB_INFRA_RGU_CB_INFRA_DBG_SEL_ADDR                     (CB_INFRA_RGU_BASE + 0x02C) // 802C
#define CB_INFRA_RGU_HIFCR_3_ADDR                              (CB_INFRA_RGU_BASE + 0x034) // 8034
#define CB_INFRA_RGU_CBTOP_PCIE_LP_EINT_ADDR                   (CB_INFRA_RGU_BASE + 0x350) // 8350
#define CB_INFRA_RGU_CBTOP_PCIE_2_LP_EINT_ADDR                 (CB_INFRA_RGU_BASE + 0x354) // 8354
#define CB_INFRA_RGU_CB_INFRA_TMBIST_0_ADDR                    (CB_INFRA_RGU_BASE + 0x360) // 8360
#define CB_INFRA_RGU_CB_INFRA_TMBIST_1_ADDR                    (CB_INFRA_RGU_BASE + 0x364) // 8364
#define CB_INFRA_RGU_CB_INFRA_TMBIST_2_ADDR                    (CB_INFRA_RGU_BASE + 0x368) // 8368
#define CB_INFRA_RGU_CB_INFRA_TMBIST_3_ADDR                    (CB_INFRA_RGU_BASE + 0x36C) // 836C
#define CB_INFRA_RGU_CB_INFRA_TMBIST_4_ADDR                    (CB_INFRA_RGU_BASE + 0x370) // 8370
#define CB_INFRA_RGU_CB_INFRA_TMBIST_5_ADDR                    (CB_INFRA_RGU_BASE + 0x374) // 8374
#define CB_INFRA_RGU_CB_INFRA_TMBIST_6_ADDR                    (CB_INFRA_RGU_BASE + 0x378) // 8378
#define CB_INFRA_RGU_CB_INFRA_TMBIST_7_ADDR                    (CB_INFRA_RGU_BASE + 0x37C) // 837C
#define CB_INFRA_RGU_TOP_RGU_WDT_RST_EN_ADDR                   (CB_INFRA_RGU_BASE + 0x400) // 8400
#define CB_INFRA_RGU_CB_INFRA_SW_RST_B_ADDR                    (CB_INFRA_RGU_BASE + 0x410) // 8410
#define CB_INFRA_RGU_CB_INFRA_EFUSE_AUTOLOAD_ADDR              (CB_INFRA_RGU_BASE + 0x420) // 8420
#define CB_INFRA_RGU_WF_MISC_ADDR                              (CB_INFRA_RGU_BASE + 0x500) // 8500
#define CB_INFRA_RGU_WF_L05_RECOV_ADDR                         (CB_INFRA_RGU_BASE + 0x504) // 8504
#define CB_INFRA_RGU_BT_MISC_ADDR                              (CB_INFRA_RGU_BASE + 0x510) // 8510
#define CB_INFRA_RGU_BT_L05_RECOV_ADDR                         (CB_INFRA_RGU_BASE + 0x514) // 8514
#define CB_INFRA_RGU_WF_SUBSYS_RST_ADDR                        (CB_INFRA_RGU_BASE + 0x600) // 8600
#define CB_INFRA_RGU_WF_SUBSYS_PWR_ADDR                        (CB_INFRA_RGU_BASE + 0x604) // 8604
#define CB_INFRA_RGU_BT_SUBSYS_RST_ADDR                        (CB_INFRA_RGU_BASE + 0x610) // 8610
#define CB_INFRA_RGU_FLR_CTL_ADDR                              (CB_INFRA_RGU_BASE + 0x620) // 8620
#define CB_INFRA_RGU_SLP_PROT_RDY_STAT_ADDR                    (CB_INFRA_RGU_BASE + 0x730) // 8730
#define CB_INFRA_RGU_SLP_PROT_TIMEOUT_CTRL_ADDR                (CB_INFRA_RGU_BASE + 0x734) // 8734
#define CB_INFRA_RGU_SLP_PROT_TIMEOUT_STA_ADDR                 (CB_INFRA_RGU_BASE + 0x738) // 8738
#define CB_INFRA_RGU_PCIE_RSV_SW_0_IRQ_ADDR                    (CB_INFRA_RGU_BASE + 0x800) // 8800
#define CB_INFRA_RGU_PCIE_RSV_SW_0_IRQ_SET_ADDR                (CB_INFRA_RGU_BASE + 0x804) // 8804
#define CB_INFRA_RGU_PCIE_RSV_SW_0_IRQ_CLR_ADDR                (CB_INFRA_RGU_BASE + 0x808) // 8808
#define CB_INFRA_RGU_PCIE_RSV_SW_1_IRQ_ADDR                    (CB_INFRA_RGU_BASE + 0x810) // 8810
#define CB_INFRA_RGU_PCIE_RSV_SW_1_IRQ_SET_ADDR                (CB_INFRA_RGU_BASE + 0x814) // 8814
#define CB_INFRA_RGU_PCIE_RSV_SW_1_IRQ_CLR_ADDR                (CB_INFRA_RGU_BASE + 0x818) // 8818
#define CB_INFRA_RGU_PCIE_RSV_SW_2_IRQ_ADDR                    (CB_INFRA_RGU_BASE + 0x820) // 8820
#define CB_INFRA_RGU_PCIE_RSV_SW_2_IRQ_SET_ADDR                (CB_INFRA_RGU_BASE + 0x824) // 8824
#define CB_INFRA_RGU_PCIE_RSV_SW_2_IRQ_CLR_ADDR                (CB_INFRA_RGU_BASE + 0x828) // 8828
#define CB_INFRA_RGU_PCIE_RSV_SW_3_IRQ_ADDR                    (CB_INFRA_RGU_BASE + 0x830) // 8830
#define CB_INFRA_RGU_PCIE_RSV_SW_3_IRQ_SET_ADDR                (CB_INFRA_RGU_BASE + 0x834) // 8834
#define CB_INFRA_RGU_PCIE_RSV_SW_3_IRQ_CLR_ADDR                (CB_INFRA_RGU_BASE + 0x838) // 8838
#define CB_INFRA_RGU_PCIE_RSV_SW_4_IRQ_ADDR                    (CB_INFRA_RGU_BASE + 0x840) // 8840
#define CB_INFRA_RGU_PCIE_RSV_SW_4_IRQ_SET_ADDR                (CB_INFRA_RGU_BASE + 0x844) // 8844
#define CB_INFRA_RGU_PCIE_RSV_SW_4_IRQ_CLR_ADDR                (CB_INFRA_RGU_BASE + 0x848) // 8848
#define CB_INFRA_RGU_PCIE_RSV_SW_5_IRQ_ADDR                    (CB_INFRA_RGU_BASE + 0x850) // 8850
#define CB_INFRA_RGU_PCIE_RSV_SW_5_IRQ_SET_ADDR                (CB_INFRA_RGU_BASE + 0x854) // 8854
#define CB_INFRA_RGU_PCIE_RSV_SW_5_IRQ_CLR_ADDR                (CB_INFRA_RGU_BASE + 0x858) // 8858
#define CB_INFRA_RGU_PCIE_RSV_SW_6_IRQ_ADDR                    (CB_INFRA_RGU_BASE + 0x860) // 8860
#define CB_INFRA_RGU_PCIE_RSV_SW_6_IRQ_SET_ADDR                (CB_INFRA_RGU_BASE + 0x864) // 8864
#define CB_INFRA_RGU_PCIE_RSV_SW_6_IRQ_CLR_ADDR                (CB_INFRA_RGU_BASE + 0x868) // 8868
#define CB_INFRA_RGU_PCIE_RSV_SW_7_IRQ_ADDR                    (CB_INFRA_RGU_BASE + 0x870) // 8870
#define CB_INFRA_RGU_PCIE_RSV_SW_7_IRQ_SET_ADDR                (CB_INFRA_RGU_BASE + 0x874) // 8874
#define CB_INFRA_RGU_PCIE_RSV_SW_7_IRQ_CLR_ADDR                (CB_INFRA_RGU_BASE + 0x878) // 8878
#define CB_INFRA_RGU_PCIE_RSV_SW_8_IRQ_ADDR                    (CB_INFRA_RGU_BASE + 0x880) // 8880
#define CB_INFRA_RGU_PCIE_RSV_SW_8_IRQ_SET_ADDR                (CB_INFRA_RGU_BASE + 0x884) // 8884
#define CB_INFRA_RGU_PCIE_RSV_SW_8_IRQ_CLR_ADDR                (CB_INFRA_RGU_BASE + 0x888) // 8888
#define CB_INFRA_RGU_PCIE_RSV_SW_9_IRQ_ADDR                    (CB_INFRA_RGU_BASE + 0x890) // 8890
#define CB_INFRA_RGU_PCIE_RSV_SW_9_IRQ_SET_ADDR                (CB_INFRA_RGU_BASE + 0x894) // 8894
#define CB_INFRA_RGU_PCIE_RSV_SW_9_IRQ_CLR_ADDR                (CB_INFRA_RGU_BASE + 0x898) // 8898
#define CB_INFRA_RGU_PCIE_RSV_SW_10_IRQ_ADDR                   (CB_INFRA_RGU_BASE + 0x8A0) // 88A0
#define CB_INFRA_RGU_PCIE_RSV_SW_10_IRQ_SET_ADDR               (CB_INFRA_RGU_BASE + 0x8A4) // 88A4
#define CB_INFRA_RGU_PCIE_RSV_SW_10_IRQ_CLR_ADDR               (CB_INFRA_RGU_BASE + 0x8A8) // 88A8
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_ADDR                (CB_INFRA_RGU_BASE + 0x900) // 8900
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_SET_ADDR            (CB_INFRA_RGU_BASE + 0x904) // 8904
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_CLR_ADDR            (CB_INFRA_RGU_BASE + 0x908) // 8908




/* =====================================================================================

  ---RGU_DUMMY (0x70028000 + 0x018)---

    RESERVED0[9..0]              - (RO) Reserved bits
    DUMMY[15..10]                - (RW) dummy register, do not W/R
    RESERVED16[23..16]           - (RO) Reserved bits
    DEBUG_SEL[31..24]            - (RW)  xxx 

 =====================================================================================*/
#define CB_INFRA_RGU_RGU_DUMMY_DEBUG_SEL_ADDR                  CB_INFRA_RGU_RGU_DUMMY_ADDR
#define CB_INFRA_RGU_RGU_DUMMY_DEBUG_SEL_MASK                  0xFF000000                // DEBUG_SEL[31..24]
#define CB_INFRA_RGU_RGU_DUMMY_DEBUG_SEL_SHFT                  24
#define CB_INFRA_RGU_RGU_DUMMY_DUMMY_ADDR                      CB_INFRA_RGU_RGU_DUMMY_ADDR
#define CB_INFRA_RGU_RGU_DUMMY_DUMMY_MASK                      0x0000FC00                // DUMMY[15..10]
#define CB_INFRA_RGU_RGU_DUMMY_DUMMY_SHFT                      10

/* =====================================================================================

  ---HIF_MEM_CTL_PD (0x70028000 + 0x01C)---

    RESERVED0[23..0]             - (RO) Reserved bits
    DUMMY_ECO[31..24]            - (RW)  xxx 

 =====================================================================================*/
#define CB_INFRA_RGU_HIF_MEM_CTL_PD_DUMMY_ECO_ADDR             CB_INFRA_RGU_HIF_MEM_CTL_PD_ADDR
#define CB_INFRA_RGU_HIF_MEM_CTL_PD_DUMMY_ECO_MASK             0xFF000000                // DUMMY_ECO[31..24]
#define CB_INFRA_RGU_HIF_MEM_CTL_PD_DUMMY_ECO_SHFT             24

/* =====================================================================================

  ---HIF_MEM_CTL_PD_2 (0x70028000 + 0x024)---

    RESERVED0[11..0]             - (RO) Reserved bits
    DUMMY_ECO_2[31..12]          - (RW)  xxx 

 =====================================================================================*/
#define CB_INFRA_RGU_HIF_MEM_CTL_PD_2_DUMMY_ECO_2_ADDR         CB_INFRA_RGU_HIF_MEM_CTL_PD_2_ADDR
#define CB_INFRA_RGU_HIF_MEM_CTL_PD_2_DUMMY_ECO_2_MASK         0xFFFFF000                // DUMMY_ECO_2[31..12]
#define CB_INFRA_RGU_HIF_MEM_CTL_PD_2_DUMMY_ECO_2_SHFT         12

/* =====================================================================================

  ---CB_INFRA_DBG_SEL (0x70028000 + 0x02C)---

    CB_INFRA_DBG_SEL_0[7..0]     - (RW)  xxx 
    CB_INFRA_DBG_SEL_1[15..8]    - (RW)  xxx 
    RESERVED16[31..16]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_CB_INFRA_DBG_SEL_CB_INFRA_DBG_SEL_1_ADDR  CB_INFRA_RGU_CB_INFRA_DBG_SEL_ADDR
#define CB_INFRA_RGU_CB_INFRA_DBG_SEL_CB_INFRA_DBG_SEL_1_MASK  0x0000FF00                // CB_INFRA_DBG_SEL_1[15..8]
#define CB_INFRA_RGU_CB_INFRA_DBG_SEL_CB_INFRA_DBG_SEL_1_SHFT  8
#define CB_INFRA_RGU_CB_INFRA_DBG_SEL_CB_INFRA_DBG_SEL_0_ADDR  CB_INFRA_RGU_CB_INFRA_DBG_SEL_ADDR
#define CB_INFRA_RGU_CB_INFRA_DBG_SEL_CB_INFRA_DBG_SEL_0_MASK  0x000000FF                // CB_INFRA_DBG_SEL_0[7..0]
#define CB_INFRA_RGU_CB_INFRA_DBG_SEL_CB_INFRA_DBG_SEL_0_SHFT  0

/* =====================================================================================

  ---HIFCR_3 (0x70028000 + 0x034)---

    RESERVED0[11..0]             - (RO) Reserved bits
    FORCE_HIF_AXB_MODE[12]       - (RW)  xxx 
    HIF_TESTMODE_PROBE_SEL[14..13] - (RW)  xxx 
    RESERVED15[31..15]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_HIFCR_3_HIF_TESTMODE_PROBE_SEL_ADDR       CB_INFRA_RGU_HIFCR_3_ADDR
#define CB_INFRA_RGU_HIFCR_3_HIF_TESTMODE_PROBE_SEL_MASK       0x00006000                // HIF_TESTMODE_PROBE_SEL[14..13]
#define CB_INFRA_RGU_HIFCR_3_HIF_TESTMODE_PROBE_SEL_SHFT       13
#define CB_INFRA_RGU_HIFCR_3_FORCE_HIF_AXB_MODE_ADDR           CB_INFRA_RGU_HIFCR_3_ADDR
#define CB_INFRA_RGU_HIFCR_3_FORCE_HIF_AXB_MODE_MASK           0x00001000                // FORCE_HIF_AXB_MODE[12]
#define CB_INFRA_RGU_HIFCR_3_FORCE_HIF_AXB_MODE_SHFT           12

/* =====================================================================================

  ---CBTOP_PCIE_LP_EINT (0x70028000 + 0x350)---

    PCIE_RG_PWR_EINT_EN[2..0]    - (RW)  xxx 
    RESERVED3[7..3]              - (RO) Reserved bits
    PCIE_RG_PWR_EINT_MASK[10..8] - (RW)  xxx 
    RESERVED11[15..11]           - (RO) Reserved bits
    PCIE_RG_PWR_EINT_CLR[18..16] - (WO)  xxx 
    RESERVED19[23..19]           - (RO) Reserved bits
    PCIE_RG_PWR_EINT_STATUS[26..24] - (RO)  xxx 
    RESERVED27[31..27]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_CBTOP_PCIE_LP_EINT_PCIE_RG_PWR_EINT_STATUS_ADDR CB_INFRA_RGU_CBTOP_PCIE_LP_EINT_ADDR
#define CB_INFRA_RGU_CBTOP_PCIE_LP_EINT_PCIE_RG_PWR_EINT_STATUS_MASK 0x07000000                // PCIE_RG_PWR_EINT_STATUS[26..24]
#define CB_INFRA_RGU_CBTOP_PCIE_LP_EINT_PCIE_RG_PWR_EINT_STATUS_SHFT 24
#define CB_INFRA_RGU_CBTOP_PCIE_LP_EINT_PCIE_RG_PWR_EINT_CLR_ADDR CB_INFRA_RGU_CBTOP_PCIE_LP_EINT_ADDR
#define CB_INFRA_RGU_CBTOP_PCIE_LP_EINT_PCIE_RG_PWR_EINT_CLR_MASK 0x00070000                // PCIE_RG_PWR_EINT_CLR[18..16]
#define CB_INFRA_RGU_CBTOP_PCIE_LP_EINT_PCIE_RG_PWR_EINT_CLR_SHFT 16
#define CB_INFRA_RGU_CBTOP_PCIE_LP_EINT_PCIE_RG_PWR_EINT_MASK_ADDR CB_INFRA_RGU_CBTOP_PCIE_LP_EINT_ADDR
#define CB_INFRA_RGU_CBTOP_PCIE_LP_EINT_PCIE_RG_PWR_EINT_MASK_MASK 0x00000700                // PCIE_RG_PWR_EINT_MASK[10..8]
#define CB_INFRA_RGU_CBTOP_PCIE_LP_EINT_PCIE_RG_PWR_EINT_MASK_SHFT 8
#define CB_INFRA_RGU_CBTOP_PCIE_LP_EINT_PCIE_RG_PWR_EINT_EN_ADDR CB_INFRA_RGU_CBTOP_PCIE_LP_EINT_ADDR
#define CB_INFRA_RGU_CBTOP_PCIE_LP_EINT_PCIE_RG_PWR_EINT_EN_MASK 0x00000007                // PCIE_RG_PWR_EINT_EN[2..0]
#define CB_INFRA_RGU_CBTOP_PCIE_LP_EINT_PCIE_RG_PWR_EINT_EN_SHFT 0

/* =====================================================================================

  ---CBTOP_PCIE_2_LP_EINT (0x70028000 + 0x354)---

    PCIE_2_RG_PWR_EINT_EN[2..0]  - (RW)  xxx 
    RESERVED3[7..3]              - (RO) Reserved bits
    PCIE_2_RG_PWR_EINT_MASK[10..8] - (RW)  xxx 
    RESERVED11[15..11]           - (RO) Reserved bits
    PCIE_2_RG_PWR_EINT_CLR[18..16] - (WO)  xxx 
    RESERVED19[23..19]           - (RO) Reserved bits
    PCIE_2_RG_PWR_EINT_STATUS[26..24] - (RO)  xxx 
    RESERVED27[31..27]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_CBTOP_PCIE_2_LP_EINT_PCIE_2_RG_PWR_EINT_STATUS_ADDR CB_INFRA_RGU_CBTOP_PCIE_2_LP_EINT_ADDR
#define CB_INFRA_RGU_CBTOP_PCIE_2_LP_EINT_PCIE_2_RG_PWR_EINT_STATUS_MASK 0x07000000                // PCIE_2_RG_PWR_EINT_STATUS[26..24]
#define CB_INFRA_RGU_CBTOP_PCIE_2_LP_EINT_PCIE_2_RG_PWR_EINT_STATUS_SHFT 24
#define CB_INFRA_RGU_CBTOP_PCIE_2_LP_EINT_PCIE_2_RG_PWR_EINT_CLR_ADDR CB_INFRA_RGU_CBTOP_PCIE_2_LP_EINT_ADDR
#define CB_INFRA_RGU_CBTOP_PCIE_2_LP_EINT_PCIE_2_RG_PWR_EINT_CLR_MASK 0x00070000                // PCIE_2_RG_PWR_EINT_CLR[18..16]
#define CB_INFRA_RGU_CBTOP_PCIE_2_LP_EINT_PCIE_2_RG_PWR_EINT_CLR_SHFT 16
#define CB_INFRA_RGU_CBTOP_PCIE_2_LP_EINT_PCIE_2_RG_PWR_EINT_MASK_ADDR CB_INFRA_RGU_CBTOP_PCIE_2_LP_EINT_ADDR
#define CB_INFRA_RGU_CBTOP_PCIE_2_LP_EINT_PCIE_2_RG_PWR_EINT_MASK_MASK 0x00000700                // PCIE_2_RG_PWR_EINT_MASK[10..8]
#define CB_INFRA_RGU_CBTOP_PCIE_2_LP_EINT_PCIE_2_RG_PWR_EINT_MASK_SHFT 8
#define CB_INFRA_RGU_CBTOP_PCIE_2_LP_EINT_PCIE_2_RG_PWR_EINT_EN_ADDR CB_INFRA_RGU_CBTOP_PCIE_2_LP_EINT_ADDR
#define CB_INFRA_RGU_CBTOP_PCIE_2_LP_EINT_PCIE_2_RG_PWR_EINT_EN_MASK 0x00000007                // PCIE_2_RG_PWR_EINT_EN[2..0]
#define CB_INFRA_RGU_CBTOP_PCIE_2_LP_EINT_PCIE_2_RG_PWR_EINT_EN_SHFT 0

/* =====================================================================================

  ---CB_INFRA_TMBIST_0 (0x70028000 + 0x360)---

    CR_TMBIST_DELSEL_0[19..0]    - (RW)  xxx 
    CR_TMBIST_USE_DEFAULT_DELSEL_0[20] - (RW)  xxx 
    RESERVED21[31..21]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_CB_INFRA_TMBIST_0_CR_TMBIST_USE_DEFAULT_DELSEL_0_ADDR CB_INFRA_RGU_CB_INFRA_TMBIST_0_ADDR
#define CB_INFRA_RGU_CB_INFRA_TMBIST_0_CR_TMBIST_USE_DEFAULT_DELSEL_0_MASK 0x00100000                // CR_TMBIST_USE_DEFAULT_DELSEL_0[20]
#define CB_INFRA_RGU_CB_INFRA_TMBIST_0_CR_TMBIST_USE_DEFAULT_DELSEL_0_SHFT 20
#define CB_INFRA_RGU_CB_INFRA_TMBIST_0_CR_TMBIST_DELSEL_0_ADDR CB_INFRA_RGU_CB_INFRA_TMBIST_0_ADDR
#define CB_INFRA_RGU_CB_INFRA_TMBIST_0_CR_TMBIST_DELSEL_0_MASK 0x000FFFFF                // CR_TMBIST_DELSEL_0[19..0]
#define CB_INFRA_RGU_CB_INFRA_TMBIST_0_CR_TMBIST_DELSEL_0_SHFT 0

/* =====================================================================================

  ---CB_INFRA_TMBIST_1 (0x70028000 + 0x364)---

    CR_TMBIST_DELSEL_1[19..0]    - (RW)  xxx 
    CR_TMBIST_USE_DEFAULT_DELSEL_1[20] - (RW)  xxx 
    RESERVED21[31..21]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_CB_INFRA_TMBIST_1_CR_TMBIST_USE_DEFAULT_DELSEL_1_ADDR CB_INFRA_RGU_CB_INFRA_TMBIST_1_ADDR
#define CB_INFRA_RGU_CB_INFRA_TMBIST_1_CR_TMBIST_USE_DEFAULT_DELSEL_1_MASK 0x00100000                // CR_TMBIST_USE_DEFAULT_DELSEL_1[20]
#define CB_INFRA_RGU_CB_INFRA_TMBIST_1_CR_TMBIST_USE_DEFAULT_DELSEL_1_SHFT 20
#define CB_INFRA_RGU_CB_INFRA_TMBIST_1_CR_TMBIST_DELSEL_1_ADDR CB_INFRA_RGU_CB_INFRA_TMBIST_1_ADDR
#define CB_INFRA_RGU_CB_INFRA_TMBIST_1_CR_TMBIST_DELSEL_1_MASK 0x000FFFFF                // CR_TMBIST_DELSEL_1[19..0]
#define CB_INFRA_RGU_CB_INFRA_TMBIST_1_CR_TMBIST_DELSEL_1_SHFT 0

/* =====================================================================================

  ---CB_INFRA_TMBIST_2 (0x70028000 + 0x368)---

    CR_TMBIST_DELSEL_1[19..0]    - (RW)  xxx 
    CR_TMBIST_USE_DEFAULT_DELSEL_1[20] - (RW)  xxx 
    RESERVED21[31..21]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_CB_INFRA_TMBIST_2_CR_TMBIST_USE_DEFAULT_DELSEL_1_ADDR CB_INFRA_RGU_CB_INFRA_TMBIST_2_ADDR
#define CB_INFRA_RGU_CB_INFRA_TMBIST_2_CR_TMBIST_USE_DEFAULT_DELSEL_1_MASK 0x00100000                // CR_TMBIST_USE_DEFAULT_DELSEL_1[20]
#define CB_INFRA_RGU_CB_INFRA_TMBIST_2_CR_TMBIST_USE_DEFAULT_DELSEL_1_SHFT 20
#define CB_INFRA_RGU_CB_INFRA_TMBIST_2_CR_TMBIST_DELSEL_1_ADDR CB_INFRA_RGU_CB_INFRA_TMBIST_2_ADDR
#define CB_INFRA_RGU_CB_INFRA_TMBIST_2_CR_TMBIST_DELSEL_1_MASK 0x000FFFFF                // CR_TMBIST_DELSEL_1[19..0]
#define CB_INFRA_RGU_CB_INFRA_TMBIST_2_CR_TMBIST_DELSEL_1_SHFT 0

/* =====================================================================================

  ---CB_INFRA_TMBIST_3 (0x70028000 + 0x36C)---

    CR_TMBIST_DELSEL_1[19..0]    - (RW)  xxx 
    CR_TMBIST_USE_DEFAULT_DELSEL_1[20] - (RW)  xxx 
    RESERVED21[31..21]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_CB_INFRA_TMBIST_3_CR_TMBIST_USE_DEFAULT_DELSEL_1_ADDR CB_INFRA_RGU_CB_INFRA_TMBIST_3_ADDR
#define CB_INFRA_RGU_CB_INFRA_TMBIST_3_CR_TMBIST_USE_DEFAULT_DELSEL_1_MASK 0x00100000                // CR_TMBIST_USE_DEFAULT_DELSEL_1[20]
#define CB_INFRA_RGU_CB_INFRA_TMBIST_3_CR_TMBIST_USE_DEFAULT_DELSEL_1_SHFT 20
#define CB_INFRA_RGU_CB_INFRA_TMBIST_3_CR_TMBIST_DELSEL_1_ADDR CB_INFRA_RGU_CB_INFRA_TMBIST_3_ADDR
#define CB_INFRA_RGU_CB_INFRA_TMBIST_3_CR_TMBIST_DELSEL_1_MASK 0x000FFFFF                // CR_TMBIST_DELSEL_1[19..0]
#define CB_INFRA_RGU_CB_INFRA_TMBIST_3_CR_TMBIST_DELSEL_1_SHFT 0

/* =====================================================================================

  ---CB_INFRA_TMBIST_4 (0x70028000 + 0x370)---

    CR_TMBIST_DELSEL_1[19..0]    - (RW)  xxx 
    CR_TMBIST_USE_DEFAULT_DELSEL_1[20] - (RW)  xxx 
    RESERVED21[31..21]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_CB_INFRA_TMBIST_4_CR_TMBIST_USE_DEFAULT_DELSEL_1_ADDR CB_INFRA_RGU_CB_INFRA_TMBIST_4_ADDR
#define CB_INFRA_RGU_CB_INFRA_TMBIST_4_CR_TMBIST_USE_DEFAULT_DELSEL_1_MASK 0x00100000                // CR_TMBIST_USE_DEFAULT_DELSEL_1[20]
#define CB_INFRA_RGU_CB_INFRA_TMBIST_4_CR_TMBIST_USE_DEFAULT_DELSEL_1_SHFT 20
#define CB_INFRA_RGU_CB_INFRA_TMBIST_4_CR_TMBIST_DELSEL_1_ADDR CB_INFRA_RGU_CB_INFRA_TMBIST_4_ADDR
#define CB_INFRA_RGU_CB_INFRA_TMBIST_4_CR_TMBIST_DELSEL_1_MASK 0x000FFFFF                // CR_TMBIST_DELSEL_1[19..0]
#define CB_INFRA_RGU_CB_INFRA_TMBIST_4_CR_TMBIST_DELSEL_1_SHFT 0

/* =====================================================================================

  ---CB_INFRA_TMBIST_5 (0x70028000 + 0x374)---

    CR_TMBIST_DELSEL_1[19..0]    - (RW)  xxx 
    CR_TMBIST_USE_DEFAULT_DELSEL_1[20] - (RW)  xxx 
    RESERVED21[31..21]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_CB_INFRA_TMBIST_5_CR_TMBIST_USE_DEFAULT_DELSEL_1_ADDR CB_INFRA_RGU_CB_INFRA_TMBIST_5_ADDR
#define CB_INFRA_RGU_CB_INFRA_TMBIST_5_CR_TMBIST_USE_DEFAULT_DELSEL_1_MASK 0x00100000                // CR_TMBIST_USE_DEFAULT_DELSEL_1[20]
#define CB_INFRA_RGU_CB_INFRA_TMBIST_5_CR_TMBIST_USE_DEFAULT_DELSEL_1_SHFT 20
#define CB_INFRA_RGU_CB_INFRA_TMBIST_5_CR_TMBIST_DELSEL_1_ADDR CB_INFRA_RGU_CB_INFRA_TMBIST_5_ADDR
#define CB_INFRA_RGU_CB_INFRA_TMBIST_5_CR_TMBIST_DELSEL_1_MASK 0x000FFFFF                // CR_TMBIST_DELSEL_1[19..0]
#define CB_INFRA_RGU_CB_INFRA_TMBIST_5_CR_TMBIST_DELSEL_1_SHFT 0

/* =====================================================================================

  ---CB_INFRA_TMBIST_6 (0x70028000 + 0x378)---

    CR_TMBIST_REG_FUSE_SEL[0]    - (RW)  xxx 
    CR_TMBIST_REG_FUSE_LOAD[1]   - (RW)  xxx 
    CR_TMBIST_REG_CTL_RST[2]     - (RW)  xxx 
    RESERVED3[31..3]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_CB_INFRA_TMBIST_6_CR_TMBIST_REG_CTL_RST_ADDR CB_INFRA_RGU_CB_INFRA_TMBIST_6_ADDR
#define CB_INFRA_RGU_CB_INFRA_TMBIST_6_CR_TMBIST_REG_CTL_RST_MASK 0x00000004                // CR_TMBIST_REG_CTL_RST[2]
#define CB_INFRA_RGU_CB_INFRA_TMBIST_6_CR_TMBIST_REG_CTL_RST_SHFT 2
#define CB_INFRA_RGU_CB_INFRA_TMBIST_6_CR_TMBIST_REG_FUSE_LOAD_ADDR CB_INFRA_RGU_CB_INFRA_TMBIST_6_ADDR
#define CB_INFRA_RGU_CB_INFRA_TMBIST_6_CR_TMBIST_REG_FUSE_LOAD_MASK 0x00000002                // CR_TMBIST_REG_FUSE_LOAD[1]
#define CB_INFRA_RGU_CB_INFRA_TMBIST_6_CR_TMBIST_REG_FUSE_LOAD_SHFT 1
#define CB_INFRA_RGU_CB_INFRA_TMBIST_6_CR_TMBIST_REG_FUSE_SEL_ADDR CB_INFRA_RGU_CB_INFRA_TMBIST_6_ADDR
#define CB_INFRA_RGU_CB_INFRA_TMBIST_6_CR_TMBIST_REG_FUSE_SEL_MASK 0x00000001                // CR_TMBIST_REG_FUSE_SEL[0]
#define CB_INFRA_RGU_CB_INFRA_TMBIST_6_CR_TMBIST_REG_FUSE_SEL_SHFT 0

/* =====================================================================================

  ---CB_INFRA_TMBIST_7 (0x70028000 + 0x37C)---

    CB_INFRA_TMBIST_PREFUSE[15..0] - (RO)  xxx 
    RESERVED16[31..16]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_CB_INFRA_TMBIST_7_CB_INFRA_TMBIST_PREFUSE_ADDR CB_INFRA_RGU_CB_INFRA_TMBIST_7_ADDR
#define CB_INFRA_RGU_CB_INFRA_TMBIST_7_CB_INFRA_TMBIST_PREFUSE_MASK 0x0000FFFF                // CB_INFRA_TMBIST_PREFUSE[15..0]
#define CB_INFRA_RGU_CB_INFRA_TMBIST_7_CB_INFRA_TMBIST_PREFUSE_SHFT 0

/* =====================================================================================

  ---TOP_RGU_WDT_RST_EN (0x70028000 + 0x400)---

    WDT_RST_BYPASS[7..0]         - (RW)  xxx 
    RESERVED8[8]                 - (RO) Reserved bits
    L05_RECOV_CONNSYS_SEL[9]     - (RW) 0:00
    RESERVED10[31..10]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_TOP_RGU_WDT_RST_EN_L05_RECOV_CONNSYS_SEL_ADDR CB_INFRA_RGU_TOP_RGU_WDT_RST_EN_ADDR
#define CB_INFRA_RGU_TOP_RGU_WDT_RST_EN_L05_RECOV_CONNSYS_SEL_MASK 0x00000200                // L05_RECOV_CONNSYS_SEL[9]
#define CB_INFRA_RGU_TOP_RGU_WDT_RST_EN_L05_RECOV_CONNSYS_SEL_SHFT 9
#define CB_INFRA_RGU_TOP_RGU_WDT_RST_EN_WDT_RST_BYPASS_ADDR    CB_INFRA_RGU_TOP_RGU_WDT_RST_EN_ADDR
#define CB_INFRA_RGU_TOP_RGU_WDT_RST_EN_WDT_RST_BYPASS_MASK    0x000000FF                // WDT_RST_BYPASS[7..0]
#define CB_INFRA_RGU_TOP_RGU_WDT_RST_EN_WDT_RST_BYPASS_SHFT    0

/* =====================================================================================

  ---CB_INFRA_SW_RST_B (0x70028000 + 0x410)---

    CB_INFRA_SW_RSTB_REG[15..0]  - (RW)  xxx 
    RESERVED16[31..16]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_CB_INFRA_SW_RST_B_CB_INFRA_SW_RSTB_REG_ADDR CB_INFRA_RGU_CB_INFRA_SW_RST_B_ADDR
#define CB_INFRA_RGU_CB_INFRA_SW_RST_B_CB_INFRA_SW_RSTB_REG_MASK 0x0000FFFF                // CB_INFRA_SW_RSTB_REG[15..0]
#define CB_INFRA_RGU_CB_INFRA_SW_RST_B_CB_INFRA_SW_RSTB_REG_SHFT 0

/* =====================================================================================

  ---CB_INFRA_EFUSE_AUTOLOAD (0x70028000 + 0x420)---

    EFUSE_AUTOLOAD_VALID[8..0]   - (RO)  xxx 
    RESERVED9[31..9]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_CB_INFRA_EFUSE_AUTOLOAD_EFUSE_AUTOLOAD_VALID_ADDR CB_INFRA_RGU_CB_INFRA_EFUSE_AUTOLOAD_ADDR
#define CB_INFRA_RGU_CB_INFRA_EFUSE_AUTOLOAD_EFUSE_AUTOLOAD_VALID_MASK 0x000001FF                // EFUSE_AUTOLOAD_VALID[8..0]
#define CB_INFRA_RGU_CB_INFRA_EFUSE_AUTOLOAD_EFUSE_AUTOLOAD_VALID_SHFT 0

/* =====================================================================================

  ---WF_MISC (0x70028000 + 0x500)---

    WF_CALIBRATION_DONE[0]       - (RW)  xxx 
    RESERVED1[8..1]              - (RO) Reserved bits
    WF_JTAG_ATCH_STATUS_B[9]     - (RO)  xxx 
    RESERVED10[31..10]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_WF_MISC_WF_JTAG_ATCH_STATUS_B_ADDR        CB_INFRA_RGU_WF_MISC_ADDR
#define CB_INFRA_RGU_WF_MISC_WF_JTAG_ATCH_STATUS_B_MASK        0x00000200                // WF_JTAG_ATCH_STATUS_B[9]
#define CB_INFRA_RGU_WF_MISC_WF_JTAG_ATCH_STATUS_B_SHFT        9
#define CB_INFRA_RGU_WF_MISC_WF_CALIBRATION_DONE_ADDR          CB_INFRA_RGU_WF_MISC_ADDR
#define CB_INFRA_RGU_WF_MISC_WF_CALIBRATION_DONE_MASK          0x00000001                // WF_CALIBRATION_DONE[0]
#define CB_INFRA_RGU_WF_MISC_WF_CALIBRATION_DONE_SHFT          0

/* =====================================================================================

  ---WF_L05_RECOV (0x70028000 + 0x504)---

    WF_L05_RECOV_TIMER_SET[15..0] - (RW)  xxx 
    WF_L05_RECOV_EN[16]          - (RW)  xxx 
    RESERVED17[31..17]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_WF_L05_RECOV_WF_L05_RECOV_EN_ADDR         CB_INFRA_RGU_WF_L05_RECOV_ADDR
#define CB_INFRA_RGU_WF_L05_RECOV_WF_L05_RECOV_EN_MASK         0x00010000                // WF_L05_RECOV_EN[16]
#define CB_INFRA_RGU_WF_L05_RECOV_WF_L05_RECOV_EN_SHFT         16
#define CB_INFRA_RGU_WF_L05_RECOV_WF_L05_RECOV_TIMER_SET_ADDR  CB_INFRA_RGU_WF_L05_RECOV_ADDR
#define CB_INFRA_RGU_WF_L05_RECOV_WF_L05_RECOV_TIMER_SET_MASK  0x0000FFFF                // WF_L05_RECOV_TIMER_SET[15..0]
#define CB_INFRA_RGU_WF_L05_RECOV_WF_L05_RECOV_TIMER_SET_SHFT  0

/* =====================================================================================

  ---BT_MISC (0x70028000 + 0x510)---

    BT_CALIBRATION_DONE[0]       - (RW)  xxx 
    CBTOP_BT_OFF[1]              - (RW)  xxx 
    RESERVED2[9..2]              - (RO) Reserved bits
    BT_JTAG_ATCH_STATUS_B[10]    - (RO)  xxx 
    RESERVED11[31..11]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_BT_MISC_BT_JTAG_ATCH_STATUS_B_ADDR        CB_INFRA_RGU_BT_MISC_ADDR
#define CB_INFRA_RGU_BT_MISC_BT_JTAG_ATCH_STATUS_B_MASK        0x00000400                // BT_JTAG_ATCH_STATUS_B[10]
#define CB_INFRA_RGU_BT_MISC_BT_JTAG_ATCH_STATUS_B_SHFT        10
#define CB_INFRA_RGU_BT_MISC_CBTOP_BT_OFF_ADDR                 CB_INFRA_RGU_BT_MISC_ADDR
#define CB_INFRA_RGU_BT_MISC_CBTOP_BT_OFF_MASK                 0x00000002                // CBTOP_BT_OFF[1]
#define CB_INFRA_RGU_BT_MISC_CBTOP_BT_OFF_SHFT                 1
#define CB_INFRA_RGU_BT_MISC_BT_CALIBRATION_DONE_ADDR          CB_INFRA_RGU_BT_MISC_ADDR
#define CB_INFRA_RGU_BT_MISC_BT_CALIBRATION_DONE_MASK          0x00000001                // BT_CALIBRATION_DONE[0]
#define CB_INFRA_RGU_BT_MISC_BT_CALIBRATION_DONE_SHFT          0

/* =====================================================================================

  ---BT_L05_RECOV (0x70028000 + 0x514)---

    WF_L05_RECOV_TIMER_SET[15..0] - (RW)  xxx 
    WF_L05_RECOV_EN[16]          - (RW)  xxx 
    RESERVED17[31..17]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_BT_L05_RECOV_WF_L05_RECOV_EN_ADDR         CB_INFRA_RGU_BT_L05_RECOV_ADDR
#define CB_INFRA_RGU_BT_L05_RECOV_WF_L05_RECOV_EN_MASK         0x00010000                // WF_L05_RECOV_EN[16]
#define CB_INFRA_RGU_BT_L05_RECOV_WF_L05_RECOV_EN_SHFT         16
#define CB_INFRA_RGU_BT_L05_RECOV_WF_L05_RECOV_TIMER_SET_ADDR  CB_INFRA_RGU_BT_L05_RECOV_ADDR
#define CB_INFRA_RGU_BT_L05_RECOV_WF_L05_RECOV_TIMER_SET_MASK  0x0000FFFF                // WF_L05_RECOV_TIMER_SET[15..0]
#define CB_INFRA_RGU_BT_L05_RECOV_WF_L05_RECOV_TIMER_SET_SHFT  0

/* =====================================================================================

  ---WF_SUBSYS_RST (0x70028000 + 0x600)---

    WF_WHOLE_PATH_RST[0]         - (RW)  xxx 
    WF_PATH_BUS_RST[1]           - (RW)  xxx 
    WFSYS_PDN_RST_EN[2]          - (RW)  xxx 
    WF_CRYPTO_BYPASS_SUBSYS_RST[3] - (RW)  xxx 
    WF_SUBSYS_RST[4]             - (RW)  xxx 
    WF_WHOLE_PATH_RST_REVERT_EN[5] - (RW)  xxx 
    BYPASS_WFDMA_SLP_PROT[6]     - (RW)  xxx 
    PAD_WF_SUBSYS_RST_EN[7]      - (RW)  xxx 
    WF_WHOLE_PATH_RST_REVERT_CYCLE[15..8] - (RW)  xxx 
    BYPASS_WFDMA_2_SLP_PROT[16]  - (RW)  xxx 
    RESERVED17[31..17]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_WF_SUBSYS_RST_BYPASS_WFDMA_2_SLP_PROT_ADDR CB_INFRA_RGU_WF_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_WF_SUBSYS_RST_BYPASS_WFDMA_2_SLP_PROT_MASK 0x00010000                // BYPASS_WFDMA_2_SLP_PROT[16]
#define CB_INFRA_RGU_WF_SUBSYS_RST_BYPASS_WFDMA_2_SLP_PROT_SHFT 16
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_WHOLE_PATH_RST_REVERT_CYCLE_ADDR CB_INFRA_RGU_WF_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_WHOLE_PATH_RST_REVERT_CYCLE_MASK 0x0000FF00                // WF_WHOLE_PATH_RST_REVERT_CYCLE[15..8]
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_WHOLE_PATH_RST_REVERT_CYCLE_SHFT 8
#define CB_INFRA_RGU_WF_SUBSYS_RST_PAD_WF_SUBSYS_RST_EN_ADDR   CB_INFRA_RGU_WF_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_WF_SUBSYS_RST_PAD_WF_SUBSYS_RST_EN_MASK   0x00000080                // PAD_WF_SUBSYS_RST_EN[7]
#define CB_INFRA_RGU_WF_SUBSYS_RST_PAD_WF_SUBSYS_RST_EN_SHFT   7
#define CB_INFRA_RGU_WF_SUBSYS_RST_BYPASS_WFDMA_SLP_PROT_ADDR  CB_INFRA_RGU_WF_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_WF_SUBSYS_RST_BYPASS_WFDMA_SLP_PROT_MASK  0x00000040                // BYPASS_WFDMA_SLP_PROT[6]
#define CB_INFRA_RGU_WF_SUBSYS_RST_BYPASS_WFDMA_SLP_PROT_SHFT  6
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_WHOLE_PATH_RST_REVERT_EN_ADDR CB_INFRA_RGU_WF_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_WHOLE_PATH_RST_REVERT_EN_MASK 0x00000020                // WF_WHOLE_PATH_RST_REVERT_EN[5]
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_WHOLE_PATH_RST_REVERT_EN_SHFT 5
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_SUBSYS_RST_ADDR          CB_INFRA_RGU_WF_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_SUBSYS_RST_MASK          0x00000010                // WF_SUBSYS_RST[4]
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_SUBSYS_RST_SHFT          4
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_CRYPTO_BYPASS_SUBSYS_RST_ADDR CB_INFRA_RGU_WF_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_CRYPTO_BYPASS_SUBSYS_RST_MASK 0x00000008                // WF_CRYPTO_BYPASS_SUBSYS_RST[3]
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_CRYPTO_BYPASS_SUBSYS_RST_SHFT 3
#define CB_INFRA_RGU_WF_SUBSYS_RST_WFSYS_PDN_RST_EN_ADDR       CB_INFRA_RGU_WF_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_WF_SUBSYS_RST_WFSYS_PDN_RST_EN_MASK       0x00000004                // WFSYS_PDN_RST_EN[2]
#define CB_INFRA_RGU_WF_SUBSYS_RST_WFSYS_PDN_RST_EN_SHFT       2
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_PATH_BUS_RST_ADDR        CB_INFRA_RGU_WF_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_PATH_BUS_RST_MASK        0x00000002                // WF_PATH_BUS_RST[1]
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_PATH_BUS_RST_SHFT        1
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_WHOLE_PATH_RST_ADDR      CB_INFRA_RGU_WF_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_WHOLE_PATH_RST_MASK      0x00000001                // WF_WHOLE_PATH_RST[0]
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_WHOLE_PATH_RST_SHFT      0

/* =====================================================================================

  ---WF_SUBSYS_PWR (0x70028000 + 0x604)---

    CR_PRESET_N_DBC_EN[0]        - (RW)  xxx 
    CBTOP_WF_ON_USB[1]           - (RW)  xxx 
    CR_PRESET_N_2_DBC_EN[2]      - (RW)  xxx 
    RESERVED3[31..3]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_WF_SUBSYS_PWR_CR_PRESET_N_2_DBC_EN_ADDR   CB_INFRA_RGU_WF_SUBSYS_PWR_ADDR
#define CB_INFRA_RGU_WF_SUBSYS_PWR_CR_PRESET_N_2_DBC_EN_MASK   0x00000004                // CR_PRESET_N_2_DBC_EN[2]
#define CB_INFRA_RGU_WF_SUBSYS_PWR_CR_PRESET_N_2_DBC_EN_SHFT   2
#define CB_INFRA_RGU_WF_SUBSYS_PWR_CBTOP_WF_ON_USB_ADDR        CB_INFRA_RGU_WF_SUBSYS_PWR_ADDR
#define CB_INFRA_RGU_WF_SUBSYS_PWR_CBTOP_WF_ON_USB_MASK        0x00000002                // CBTOP_WF_ON_USB[1]
#define CB_INFRA_RGU_WF_SUBSYS_PWR_CBTOP_WF_ON_USB_SHFT        1
#define CB_INFRA_RGU_WF_SUBSYS_PWR_CR_PRESET_N_DBC_EN_ADDR     CB_INFRA_RGU_WF_SUBSYS_PWR_ADDR
#define CB_INFRA_RGU_WF_SUBSYS_PWR_CR_PRESET_N_DBC_EN_MASK     0x00000001                // CR_PRESET_N_DBC_EN[0]
#define CB_INFRA_RGU_WF_SUBSYS_PWR_CR_PRESET_N_DBC_EN_SHFT     0

/* =====================================================================================

  ---BT_SUBSYS_RST (0x70028000 + 0x610)---

    BT_WHOLE_PATH_RST[0]         - (RW)  xxx 
    BT_PATH_BUS_RST[1]           - (RW)  xxx 
    RESERVED2[2]                 - (RO) Reserved bits
    BT_CRYPTO_BYPASS_SUBSYS_RST[3] - (RW)  xxx 
    BT_SUBSYS_RST[4]             - (RW)  xxx 
    BT_WHOLE_PATH_RST_REVERT_EN[5] - (RW)  xxx 
    BYPASS_WFDMA_2_SLP_PROT[6]   - (RW)  xxx 
    PAD_BT_SUBSYS_RST_EN[7]      - (RW)  xxx 
    BT_WHOLE_PATH_RST_REVERT_CYCLE[15..8] - (RW)  xxx 
    BYPASS_BTDMA_2_SLP_PROT[16]  - (RW)  xxx 
    RESERVED17[31..17]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_BT_SUBSYS_RST_BYPASS_BTDMA_2_SLP_PROT_ADDR CB_INFRA_RGU_BT_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_BT_SUBSYS_RST_BYPASS_BTDMA_2_SLP_PROT_MASK 0x00010000                // BYPASS_BTDMA_2_SLP_PROT[16]
#define CB_INFRA_RGU_BT_SUBSYS_RST_BYPASS_BTDMA_2_SLP_PROT_SHFT 16
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_WHOLE_PATH_RST_REVERT_CYCLE_ADDR CB_INFRA_RGU_BT_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_WHOLE_PATH_RST_REVERT_CYCLE_MASK 0x0000FF00                // BT_WHOLE_PATH_RST_REVERT_CYCLE[15..8]
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_WHOLE_PATH_RST_REVERT_CYCLE_SHFT 8
#define CB_INFRA_RGU_BT_SUBSYS_RST_PAD_BT_SUBSYS_RST_EN_ADDR   CB_INFRA_RGU_BT_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_BT_SUBSYS_RST_PAD_BT_SUBSYS_RST_EN_MASK   0x00000080                // PAD_BT_SUBSYS_RST_EN[7]
#define CB_INFRA_RGU_BT_SUBSYS_RST_PAD_BT_SUBSYS_RST_EN_SHFT   7
#define CB_INFRA_RGU_BT_SUBSYS_RST_BYPASS_WFDMA_2_SLP_PROT_ADDR CB_INFRA_RGU_BT_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_BT_SUBSYS_RST_BYPASS_WFDMA_2_SLP_PROT_MASK 0x00000040                // BYPASS_WFDMA_2_SLP_PROT[6]
#define CB_INFRA_RGU_BT_SUBSYS_RST_BYPASS_WFDMA_2_SLP_PROT_SHFT 6
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_WHOLE_PATH_RST_REVERT_EN_ADDR CB_INFRA_RGU_BT_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_WHOLE_PATH_RST_REVERT_EN_MASK 0x00000020                // BT_WHOLE_PATH_RST_REVERT_EN[5]
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_WHOLE_PATH_RST_REVERT_EN_SHFT 5
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_SUBSYS_RST_ADDR          CB_INFRA_RGU_BT_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_SUBSYS_RST_MASK          0x00000010                // BT_SUBSYS_RST[4]
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_SUBSYS_RST_SHFT          4
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_CRYPTO_BYPASS_SUBSYS_RST_ADDR CB_INFRA_RGU_BT_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_CRYPTO_BYPASS_SUBSYS_RST_MASK 0x00000008                // BT_CRYPTO_BYPASS_SUBSYS_RST[3]
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_CRYPTO_BYPASS_SUBSYS_RST_SHFT 3
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_PATH_BUS_RST_ADDR        CB_INFRA_RGU_BT_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_PATH_BUS_RST_MASK        0x00000002                // BT_PATH_BUS_RST[1]
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_PATH_BUS_RST_SHFT        1
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_WHOLE_PATH_RST_ADDR      CB_INFRA_RGU_BT_SUBSYS_RST_ADDR
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_WHOLE_PATH_RST_MASK      0x00000001                // BT_WHOLE_PATH_RST[0]
#define CB_INFRA_RGU_BT_SUBSYS_RST_BT_WHOLE_PATH_RST_SHFT      0

/* =====================================================================================

  ---FLR_CTL (0x70028000 + 0x620)---

    FLR_EN[0]                    - (RW) FLR HW mode enable
    RESERVED1[15..1]             - (RO) Reserved bits
    FLR_RST_CYCLE[23..16]        - (RW)  xxx 
    RESERVED24[31..24]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_FLR_CTL_FLR_RST_CYCLE_ADDR                CB_INFRA_RGU_FLR_CTL_ADDR
#define CB_INFRA_RGU_FLR_CTL_FLR_RST_CYCLE_MASK                0x00FF0000                // FLR_RST_CYCLE[23..16]
#define CB_INFRA_RGU_FLR_CTL_FLR_RST_CYCLE_SHFT                16
#define CB_INFRA_RGU_FLR_CTL_FLR_EN_ADDR                       CB_INFRA_RGU_FLR_CTL_ADDR
#define CB_INFRA_RGU_FLR_CTL_FLR_EN_MASK                       0x00000001                // FLR_EN[0]
#define CB_INFRA_RGU_FLR_CTL_FLR_EN_SHFT                       0

/* =====================================================================================

  ---SLP_PROT_RDY_STAT (0x70028000 + 0x730)---

    CR_SLPPROT_RDY[22..0]        - (RO)  xxx 
    RESERVED23[31..23]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_SLP_PROT_RDY_STAT_CR_SLPPROT_RDY_ADDR     CB_INFRA_RGU_SLP_PROT_RDY_STAT_ADDR
#define CB_INFRA_RGU_SLP_PROT_RDY_STAT_CR_SLPPROT_RDY_MASK     0x007FFFFF                // CR_SLPPROT_RDY[22..0]
#define CB_INFRA_RGU_SLP_PROT_RDY_STAT_CR_SLPPROT_RDY_SHFT     0

/* =====================================================================================

  ---SLP_PROT_TIMEOUT_CTRL (0x70028000 + 0x734)---

    CR_SLPPROT_TMOUT_LMT[19..0]  - (RW)  xxx 
    CR_SLPPROT_TMOUT_CLR[20]     - (RW)  xxx 
    CR_SLPPROT_TMOUT_EN[21]      - (RW)  xxx 
    RESERVED22[31..22]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_SLP_PROT_TIMEOUT_CTRL_CR_SLPPROT_TMOUT_EN_ADDR CB_INFRA_RGU_SLP_PROT_TIMEOUT_CTRL_ADDR
#define CB_INFRA_RGU_SLP_PROT_TIMEOUT_CTRL_CR_SLPPROT_TMOUT_EN_MASK 0x00200000                // CR_SLPPROT_TMOUT_EN[21]
#define CB_INFRA_RGU_SLP_PROT_TIMEOUT_CTRL_CR_SLPPROT_TMOUT_EN_SHFT 21
#define CB_INFRA_RGU_SLP_PROT_TIMEOUT_CTRL_CR_SLPPROT_TMOUT_CLR_ADDR CB_INFRA_RGU_SLP_PROT_TIMEOUT_CTRL_ADDR
#define CB_INFRA_RGU_SLP_PROT_TIMEOUT_CTRL_CR_SLPPROT_TMOUT_CLR_MASK 0x00100000                // CR_SLPPROT_TMOUT_CLR[20]
#define CB_INFRA_RGU_SLP_PROT_TIMEOUT_CTRL_CR_SLPPROT_TMOUT_CLR_SHFT 20
#define CB_INFRA_RGU_SLP_PROT_TIMEOUT_CTRL_CR_SLPPROT_TMOUT_LMT_ADDR CB_INFRA_RGU_SLP_PROT_TIMEOUT_CTRL_ADDR
#define CB_INFRA_RGU_SLP_PROT_TIMEOUT_CTRL_CR_SLPPROT_TMOUT_LMT_MASK 0x000FFFFF                // CR_SLPPROT_TMOUT_LMT[19..0]
#define CB_INFRA_RGU_SLP_PROT_TIMEOUT_CTRL_CR_SLPPROT_TMOUT_LMT_SHFT 0

/* =====================================================================================

  ---SLP_PROT_TIMEOUT_STA (0x70028000 + 0x738)---

    SLPPROT_TMOUT[0]             - (RO)  xxx 
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_SLP_PROT_TIMEOUT_STA_SLPPROT_TMOUT_ADDR   CB_INFRA_RGU_SLP_PROT_TIMEOUT_STA_ADDR
#define CB_INFRA_RGU_SLP_PROT_TIMEOUT_STA_SLPPROT_TMOUT_MASK   0x00000001                // SLPPROT_TMOUT[0]
#define CB_INFRA_RGU_SLP_PROT_TIMEOUT_STA_SLPPROT_TMOUT_SHFT   0

/* =====================================================================================

  ---PCIE_RSV_SW_0_IRQ (0x70028000 + 0x800)---

    PCIE_RSV_SW_0_IRQ[0]         - (RW) irq_status
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_PCIE_RSV_SW_0_IRQ_PCIE_RSV_SW_0_IRQ_ADDR  CB_INFRA_RGU_PCIE_RSV_SW_0_IRQ_ADDR
#define CB_INFRA_RGU_PCIE_RSV_SW_0_IRQ_PCIE_RSV_SW_0_IRQ_MASK  0x00000001                // PCIE_RSV_SW_0_IRQ[0]
#define CB_INFRA_RGU_PCIE_RSV_SW_0_IRQ_PCIE_RSV_SW_0_IRQ_SHFT  0

/* =====================================================================================

  ---PCIE_RSV_SW_0_IRQ_SET (0x70028000 + 0x804)---

    PCIE_RSV_SW_0_IRQ_SET[0]     - (WO) set irq
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_PCIE_RSV_SW_0_IRQ_SET_PCIE_RSV_SW_0_IRQ_SET_ADDR CB_INFRA_RGU_PCIE_RSV_SW_0_IRQ_SET_ADDR
#define CB_INFRA_RGU_PCIE_RSV_SW_0_IRQ_SET_PCIE_RSV_SW_0_IRQ_SET_MASK 0x00000001                // PCIE_RSV_SW_0_IRQ_SET[0]
#define CB_INFRA_RGU_PCIE_RSV_SW_0_IRQ_SET_PCIE_RSV_SW_0_IRQ_SET_SHFT 0

/* =====================================================================================

  ---PCIE_RSV_SW_0_IRQ_CLR (0x70028000 + 0x808)---

    PCIE_RSV_SW_0_IRQ_CLR[0]     - (WO) clear irq
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_PCIE_RSV_SW_0_IRQ_CLR_PCIE_RSV_SW_0_IRQ_CLR_ADDR CB_INFRA_RGU_PCIE_RSV_SW_0_IRQ_CLR_ADDR
#define CB_INFRA_RGU_PCIE_RSV_SW_0_IRQ_CLR_PCIE_RSV_SW_0_IRQ_CLR_MASK 0x00000001                // PCIE_RSV_SW_0_IRQ_CLR[0]
#define CB_INFRA_RGU_PCIE_RSV_SW_0_IRQ_CLR_PCIE_RSV_SW_0_IRQ_CLR_SHFT 0

/* =====================================================================================

  ---PCIE_RSV_SW_1_IRQ (0x70028000 + 0x810)---

    PCIE_RSV_SW_1_IRQ[0]         - (RW) irq_status
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_PCIE_RSV_SW_1_IRQ_PCIE_RSV_SW_1_IRQ_ADDR  CB_INFRA_RGU_PCIE_RSV_SW_1_IRQ_ADDR
#define CB_INFRA_RGU_PCIE_RSV_SW_1_IRQ_PCIE_RSV_SW_1_IRQ_MASK  0x00000001                // PCIE_RSV_SW_1_IRQ[0]
#define CB_INFRA_RGU_PCIE_RSV_SW_1_IRQ_PCIE_RSV_SW_1_IRQ_SHFT  0

/* =====================================================================================

  ---PCIE_RSV_SW_1_IRQ_SET (0x70028000 + 0x814)---

    PCIE_RSV_SW_1_IRQ_SET[0]     - (WO) set irq
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_PCIE_RSV_SW_1_IRQ_SET_PCIE_RSV_SW_1_IRQ_SET_ADDR CB_INFRA_RGU_PCIE_RSV_SW_1_IRQ_SET_ADDR
#define CB_INFRA_RGU_PCIE_RSV_SW_1_IRQ_SET_PCIE_RSV_SW_1_IRQ_SET_MASK 0x00000001                // PCIE_RSV_SW_1_IRQ_SET[0]
#define CB_INFRA_RGU_PCIE_RSV_SW_1_IRQ_SET_PCIE_RSV_SW_1_IRQ_SET_SHFT 0

/* =====================================================================================

  ---PCIE_RSV_SW_1_IRQ_CLR (0x70028000 + 0x818)---

    PCIE_RSV_SW_1_IRQ_CLR[0]     - (WO) clear irq
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_PCIE_RSV_SW_1_IRQ_CLR_PCIE_RSV_SW_1_IRQ_CLR_ADDR CB_INFRA_RGU_PCIE_RSV_SW_1_IRQ_CLR_ADDR
#define CB_INFRA_RGU_PCIE_RSV_SW_1_IRQ_CLR_PCIE_RSV_SW_1_IRQ_CLR_MASK 0x00000001                // PCIE_RSV_SW_1_IRQ_CLR[0]
#define CB_INFRA_RGU_PCIE_RSV_SW_1_IRQ_CLR_PCIE_RSV_SW_1_IRQ_CLR_SHFT 0

/* =====================================================================================

  ---PCIE_RSV_SW_2_IRQ (0x70028000 + 0x820)---

    PCIE_RSV_SW_2_IRQ[0]         - (RW) irq_status
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_PCIE_RSV_SW_2_IRQ_PCIE_RSV_SW_2_IRQ_ADDR  CB_INFRA_RGU_PCIE_RSV_SW_2_IRQ_ADDR
#define CB_INFRA_RGU_PCIE_RSV_SW_2_IRQ_PCIE_RSV_SW_2_IRQ_MASK  0x00000001                // PCIE_RSV_SW_2_IRQ[0]
#define CB_INFRA_RGU_PCIE_RSV_SW_2_IRQ_PCIE_RSV_SW_2_IRQ_SHFT  0

/* =====================================================================================

  ---PCIE_RSV_SW_2_IRQ_SET (0x70028000 + 0x824)---

    PCIE_RSV_SW_2_IRQ_SET[0]     - (WO) set irq
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_PCIE_RSV_SW_2_IRQ_SET_PCIE_RSV_SW_2_IRQ_SET_ADDR CB_INFRA_RGU_PCIE_RSV_SW_2_IRQ_SET_ADDR
#define CB_INFRA_RGU_PCIE_RSV_SW_2_IRQ_SET_PCIE_RSV_SW_2_IRQ_SET_MASK 0x00000001                // PCIE_RSV_SW_2_IRQ_SET[0]
#define CB_INFRA_RGU_PCIE_RSV_SW_2_IRQ_SET_PCIE_RSV_SW_2_IRQ_SET_SHFT 0

/* =====================================================================================

  ---PCIE_RSV_SW_2_IRQ_CLR (0x70028000 + 0x828)---

    PCIE_RSV_SW_2_IRQ_CLR[0]     - (WO) clear irq
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_PCIE_RSV_SW_2_IRQ_CLR_PCIE_RSV_SW_2_IRQ_CLR_ADDR CB_INFRA_RGU_PCIE_RSV_SW_2_IRQ_CLR_ADDR
#define CB_INFRA_RGU_PCIE_RSV_SW_2_IRQ_CLR_PCIE_RSV_SW_2_IRQ_CLR_MASK 0x00000001                // PCIE_RSV_SW_2_IRQ_CLR[0]
#define CB_INFRA_RGU_PCIE_RSV_SW_2_IRQ_CLR_PCIE_RSV_SW_2_IRQ_CLR_SHFT 0

/* =====================================================================================

  ---PCIE_RSV_SW_3_IRQ (0x70028000 + 0x830)---

    PCIE_RSV_SW_3_IRQ[0]         - (RW) irq_status
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_PCIE_RSV_SW_3_IRQ_PCIE_RSV_SW_3_IRQ_ADDR  CB_INFRA_RGU_PCIE_RSV_SW_3_IRQ_ADDR
#define CB_INFRA_RGU_PCIE_RSV_SW_3_IRQ_PCIE_RSV_SW_3_IRQ_MASK  0x00000001                // PCIE_RSV_SW_3_IRQ[0]
#define CB_INFRA_RGU_PCIE_RSV_SW_3_IRQ_PCIE_RSV_SW_3_IRQ_SHFT  0

/* =====================================================================================

  ---PCIE_RSV_SW_3_IRQ_SET (0x70028000 + 0x834)---

    PCIE_RSV_SW_3_IRQ_SET[0]     - (WO) set irq
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_PCIE_RSV_SW_3_IRQ_SET_PCIE_RSV_SW_3_IRQ_SET_ADDR CB_INFRA_RGU_PCIE_RSV_SW_3_IRQ_SET_ADDR
#define CB_INFRA_RGU_PCIE_RSV_SW_3_IRQ_SET_PCIE_RSV_SW_3_IRQ_SET_MASK 0x00000001                // PCIE_RSV_SW_3_IRQ_SET[0]
#define CB_INFRA_RGU_PCIE_RSV_SW_3_IRQ_SET_PCIE_RSV_SW_3_IRQ_SET_SHFT 0

/* =====================================================================================

  ---PCIE_RSV_SW_3_IRQ_CLR (0x70028000 + 0x838)---

    PCIE_RSV_SW_3_IRQ_CLR[0]     - (WO) clear irq
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_PCIE_RSV_SW_3_IRQ_CLR_PCIE_RSV_SW_3_IRQ_CLR_ADDR CB_INFRA_RGU_PCIE_RSV_SW_3_IRQ_CLR_ADDR
#define CB_INFRA_RGU_PCIE_RSV_SW_3_IRQ_CLR_PCIE_RSV_SW_3_IRQ_CLR_MASK 0x00000001                // PCIE_RSV_SW_3_IRQ_CLR[0]
#define CB_INFRA_RGU_PCIE_RSV_SW_3_IRQ_CLR_PCIE_RSV_SW_3_IRQ_CLR_SHFT 0

/* =====================================================================================

  ---PCIE_RSV_SW_4_IRQ (0x70028000 + 0x840)---

    PCIE_RSV_SW_4_IRQ[0]         - (RW) irq_status
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_PCIE_RSV_SW_4_IRQ_PCIE_RSV_SW_4_IRQ_ADDR  CB_INFRA_RGU_PCIE_RSV_SW_4_IRQ_ADDR
#define CB_INFRA_RGU_PCIE_RSV_SW_4_IRQ_PCIE_RSV_SW_4_IRQ_MASK  0x00000001                // PCIE_RSV_SW_4_IRQ[0]
#define CB_INFRA_RGU_PCIE_RSV_SW_4_IRQ_PCIE_RSV_SW_4_IRQ_SHFT  0

/* =====================================================================================

  ---PCIE_RSV_SW_4_IRQ_SET (0x70028000 + 0x844)---

    PCIE_RSV_SW_4_IRQ_SET[0]     - (WO) set irq
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_PCIE_RSV_SW_4_IRQ_SET_PCIE_RSV_SW_4_IRQ_SET_ADDR CB_INFRA_RGU_PCIE_RSV_SW_4_IRQ_SET_ADDR
#define CB_INFRA_RGU_PCIE_RSV_SW_4_IRQ_SET_PCIE_RSV_SW_4_IRQ_SET_MASK 0x00000001                // PCIE_RSV_SW_4_IRQ_SET[0]
#define CB_INFRA_RGU_PCIE_RSV_SW_4_IRQ_SET_PCIE_RSV_SW_4_IRQ_SET_SHFT 0

/* =====================================================================================

  ---PCIE_RSV_SW_4_IRQ_CLR (0x70028000 + 0x848)---

    PCIE_RSV_SW_4_IRQ_CLR[0]     - (WO) clear irq
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_PCIE_RSV_SW_4_IRQ_CLR_PCIE_RSV_SW_4_IRQ_CLR_ADDR CB_INFRA_RGU_PCIE_RSV_SW_4_IRQ_CLR_ADDR
#define CB_INFRA_RGU_PCIE_RSV_SW_4_IRQ_CLR_PCIE_RSV_SW_4_IRQ_CLR_MASK 0x00000001                // PCIE_RSV_SW_4_IRQ_CLR[0]
#define CB_INFRA_RGU_PCIE_RSV_SW_4_IRQ_CLR_PCIE_RSV_SW_4_IRQ_CLR_SHFT 0

/* =====================================================================================

  ---PCIE_RSV_SW_5_IRQ (0x70028000 + 0x850)---

    PCIE_RSV_SW_5_IRQ[0]         - (RW) irq_status
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_PCIE_RSV_SW_5_IRQ_PCIE_RSV_SW_5_IRQ_ADDR  CB_INFRA_RGU_PCIE_RSV_SW_5_IRQ_ADDR
#define CB_INFRA_RGU_PCIE_RSV_SW_5_IRQ_PCIE_RSV_SW_5_IRQ_MASK  0x00000001                // PCIE_RSV_SW_5_IRQ[0]
#define CB_INFRA_RGU_PCIE_RSV_SW_5_IRQ_PCIE_RSV_SW_5_IRQ_SHFT  0

/* =====================================================================================

  ---PCIE_RSV_SW_5_IRQ_SET (0x70028000 + 0x854)---

    PCIE_RSV_SW_5_IRQ_SET[0]     - (WO) set irq
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_PCIE_RSV_SW_5_IRQ_SET_PCIE_RSV_SW_5_IRQ_SET_ADDR CB_INFRA_RGU_PCIE_RSV_SW_5_IRQ_SET_ADDR
#define CB_INFRA_RGU_PCIE_RSV_SW_5_IRQ_SET_PCIE_RSV_SW_5_IRQ_SET_MASK 0x00000001                // PCIE_RSV_SW_5_IRQ_SET[0]
#define CB_INFRA_RGU_PCIE_RSV_SW_5_IRQ_SET_PCIE_RSV_SW_5_IRQ_SET_SHFT 0

/* =====================================================================================

  ---PCIE_RSV_SW_5_IRQ_CLR (0x70028000 + 0x858)---

    PCIE_RSV_SW_5_IRQ_CLR[0]     - (WO) clear irq
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_PCIE_RSV_SW_5_IRQ_CLR_PCIE_RSV_SW_5_IRQ_CLR_ADDR CB_INFRA_RGU_PCIE_RSV_SW_5_IRQ_CLR_ADDR
#define CB_INFRA_RGU_PCIE_RSV_SW_5_IRQ_CLR_PCIE_RSV_SW_5_IRQ_CLR_MASK 0x00000001                // PCIE_RSV_SW_5_IRQ_CLR[0]
#define CB_INFRA_RGU_PCIE_RSV_SW_5_IRQ_CLR_PCIE_RSV_SW_5_IRQ_CLR_SHFT 0

/* =====================================================================================

  ---PCIE_RSV_SW_6_IRQ (0x70028000 + 0x860)---

    PCIE_RSV_SW_6_IRQ[0]         - (RW) irq_status
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_PCIE_RSV_SW_6_IRQ_PCIE_RSV_SW_6_IRQ_ADDR  CB_INFRA_RGU_PCIE_RSV_SW_6_IRQ_ADDR
#define CB_INFRA_RGU_PCIE_RSV_SW_6_IRQ_PCIE_RSV_SW_6_IRQ_MASK  0x00000001                // PCIE_RSV_SW_6_IRQ[0]
#define CB_INFRA_RGU_PCIE_RSV_SW_6_IRQ_PCIE_RSV_SW_6_IRQ_SHFT  0

/* =====================================================================================

  ---PCIE_RSV_SW_6_IRQ_SET (0x70028000 + 0x864)---

    PCIE_RSV_SW_6_IRQ_SET[0]     - (WO) set irq
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_PCIE_RSV_SW_6_IRQ_SET_PCIE_RSV_SW_6_IRQ_SET_ADDR CB_INFRA_RGU_PCIE_RSV_SW_6_IRQ_SET_ADDR
#define CB_INFRA_RGU_PCIE_RSV_SW_6_IRQ_SET_PCIE_RSV_SW_6_IRQ_SET_MASK 0x00000001                // PCIE_RSV_SW_6_IRQ_SET[0]
#define CB_INFRA_RGU_PCIE_RSV_SW_6_IRQ_SET_PCIE_RSV_SW_6_IRQ_SET_SHFT 0

/* =====================================================================================

  ---PCIE_RSV_SW_6_IRQ_CLR (0x70028000 + 0x868)---

    PCIE_RSV_SW_6_IRQ_CLR[0]     - (WO) clear irq
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_PCIE_RSV_SW_6_IRQ_CLR_PCIE_RSV_SW_6_IRQ_CLR_ADDR CB_INFRA_RGU_PCIE_RSV_SW_6_IRQ_CLR_ADDR
#define CB_INFRA_RGU_PCIE_RSV_SW_6_IRQ_CLR_PCIE_RSV_SW_6_IRQ_CLR_MASK 0x00000001                // PCIE_RSV_SW_6_IRQ_CLR[0]
#define CB_INFRA_RGU_PCIE_RSV_SW_6_IRQ_CLR_PCIE_RSV_SW_6_IRQ_CLR_SHFT 0

/* =====================================================================================

  ---PCIE_RSV_SW_7_IRQ (0x70028000 + 0x870)---

    PCIE_RSV_SW_7_IRQ[0]         - (RW) irq_status
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_PCIE_RSV_SW_7_IRQ_PCIE_RSV_SW_7_IRQ_ADDR  CB_INFRA_RGU_PCIE_RSV_SW_7_IRQ_ADDR
#define CB_INFRA_RGU_PCIE_RSV_SW_7_IRQ_PCIE_RSV_SW_7_IRQ_MASK  0x00000001                // PCIE_RSV_SW_7_IRQ[0]
#define CB_INFRA_RGU_PCIE_RSV_SW_7_IRQ_PCIE_RSV_SW_7_IRQ_SHFT  0

/* =====================================================================================

  ---PCIE_RSV_SW_7_IRQ_SET (0x70028000 + 0x874)---

    PCIE_RSV_SW_7_IRQ_SET[0]     - (WO) set irq
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_PCIE_RSV_SW_7_IRQ_SET_PCIE_RSV_SW_7_IRQ_SET_ADDR CB_INFRA_RGU_PCIE_RSV_SW_7_IRQ_SET_ADDR
#define CB_INFRA_RGU_PCIE_RSV_SW_7_IRQ_SET_PCIE_RSV_SW_7_IRQ_SET_MASK 0x00000001                // PCIE_RSV_SW_7_IRQ_SET[0]
#define CB_INFRA_RGU_PCIE_RSV_SW_7_IRQ_SET_PCIE_RSV_SW_7_IRQ_SET_SHFT 0

/* =====================================================================================

  ---PCIE_RSV_SW_7_IRQ_CLR (0x70028000 + 0x878)---

    PCIE_RSV_SW_7_IRQ_CLR[0]     - (WO) clear irq
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_PCIE_RSV_SW_7_IRQ_CLR_PCIE_RSV_SW_7_IRQ_CLR_ADDR CB_INFRA_RGU_PCIE_RSV_SW_7_IRQ_CLR_ADDR
#define CB_INFRA_RGU_PCIE_RSV_SW_7_IRQ_CLR_PCIE_RSV_SW_7_IRQ_CLR_MASK 0x00000001                // PCIE_RSV_SW_7_IRQ_CLR[0]
#define CB_INFRA_RGU_PCIE_RSV_SW_7_IRQ_CLR_PCIE_RSV_SW_7_IRQ_CLR_SHFT 0

/* =====================================================================================

  ---PCIE_RSV_SW_8_IRQ (0x70028000 + 0x880)---

    PCIE_RSV_SW_8_IRQ[0]         - (RW) irq_status
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_PCIE_RSV_SW_8_IRQ_PCIE_RSV_SW_8_IRQ_ADDR  CB_INFRA_RGU_PCIE_RSV_SW_8_IRQ_ADDR
#define CB_INFRA_RGU_PCIE_RSV_SW_8_IRQ_PCIE_RSV_SW_8_IRQ_MASK  0x00000001                // PCIE_RSV_SW_8_IRQ[0]
#define CB_INFRA_RGU_PCIE_RSV_SW_8_IRQ_PCIE_RSV_SW_8_IRQ_SHFT  0

/* =====================================================================================

  ---PCIE_RSV_SW_8_IRQ_SET (0x70028000 + 0x884)---

    PCIE_RSV_SW_8_IRQ_SET[0]     - (WO) set irq
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_PCIE_RSV_SW_8_IRQ_SET_PCIE_RSV_SW_8_IRQ_SET_ADDR CB_INFRA_RGU_PCIE_RSV_SW_8_IRQ_SET_ADDR
#define CB_INFRA_RGU_PCIE_RSV_SW_8_IRQ_SET_PCIE_RSV_SW_8_IRQ_SET_MASK 0x00000001                // PCIE_RSV_SW_8_IRQ_SET[0]
#define CB_INFRA_RGU_PCIE_RSV_SW_8_IRQ_SET_PCIE_RSV_SW_8_IRQ_SET_SHFT 0

/* =====================================================================================

  ---PCIE_RSV_SW_8_IRQ_CLR (0x70028000 + 0x888)---

    PCIE_RSV_SW_8_IRQ_CLR[0]     - (WO) clear irq
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_PCIE_RSV_SW_8_IRQ_CLR_PCIE_RSV_SW_8_IRQ_CLR_ADDR CB_INFRA_RGU_PCIE_RSV_SW_8_IRQ_CLR_ADDR
#define CB_INFRA_RGU_PCIE_RSV_SW_8_IRQ_CLR_PCIE_RSV_SW_8_IRQ_CLR_MASK 0x00000001                // PCIE_RSV_SW_8_IRQ_CLR[0]
#define CB_INFRA_RGU_PCIE_RSV_SW_8_IRQ_CLR_PCIE_RSV_SW_8_IRQ_CLR_SHFT 0

/* =====================================================================================

  ---PCIE_RSV_SW_9_IRQ (0x70028000 + 0x890)---

    PCIE_RSV_SW_9_IRQ[0]         - (RW) irq_status
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_PCIE_RSV_SW_9_IRQ_PCIE_RSV_SW_9_IRQ_ADDR  CB_INFRA_RGU_PCIE_RSV_SW_9_IRQ_ADDR
#define CB_INFRA_RGU_PCIE_RSV_SW_9_IRQ_PCIE_RSV_SW_9_IRQ_MASK  0x00000001                // PCIE_RSV_SW_9_IRQ[0]
#define CB_INFRA_RGU_PCIE_RSV_SW_9_IRQ_PCIE_RSV_SW_9_IRQ_SHFT  0

/* =====================================================================================

  ---PCIE_RSV_SW_9_IRQ_SET (0x70028000 + 0x894)---

    PCIE_RSV_SW_9_IRQ_SET[0]     - (WO) set irq
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_PCIE_RSV_SW_9_IRQ_SET_PCIE_RSV_SW_9_IRQ_SET_ADDR CB_INFRA_RGU_PCIE_RSV_SW_9_IRQ_SET_ADDR
#define CB_INFRA_RGU_PCIE_RSV_SW_9_IRQ_SET_PCIE_RSV_SW_9_IRQ_SET_MASK 0x00000001                // PCIE_RSV_SW_9_IRQ_SET[0]
#define CB_INFRA_RGU_PCIE_RSV_SW_9_IRQ_SET_PCIE_RSV_SW_9_IRQ_SET_SHFT 0

/* =====================================================================================

  ---PCIE_RSV_SW_9_IRQ_CLR (0x70028000 + 0x898)---

    PCIE_RSV_SW_9_IRQ_CLR[0]     - (WO) clear irq
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_PCIE_RSV_SW_9_IRQ_CLR_PCIE_RSV_SW_9_IRQ_CLR_ADDR CB_INFRA_RGU_PCIE_RSV_SW_9_IRQ_CLR_ADDR
#define CB_INFRA_RGU_PCIE_RSV_SW_9_IRQ_CLR_PCIE_RSV_SW_9_IRQ_CLR_MASK 0x00000001                // PCIE_RSV_SW_9_IRQ_CLR[0]
#define CB_INFRA_RGU_PCIE_RSV_SW_9_IRQ_CLR_PCIE_RSV_SW_9_IRQ_CLR_SHFT 0

/* =====================================================================================

  ---PCIE_RSV_SW_10_IRQ (0x70028000 + 0x8A0)---

    PCIE_RSV_SW_10_IRQ[0]        - (RW) irq_status
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_PCIE_RSV_SW_10_IRQ_PCIE_RSV_SW_10_IRQ_ADDR CB_INFRA_RGU_PCIE_RSV_SW_10_IRQ_ADDR
#define CB_INFRA_RGU_PCIE_RSV_SW_10_IRQ_PCIE_RSV_SW_10_IRQ_MASK 0x00000001                // PCIE_RSV_SW_10_IRQ[0]
#define CB_INFRA_RGU_PCIE_RSV_SW_10_IRQ_PCIE_RSV_SW_10_IRQ_SHFT 0

/* =====================================================================================

  ---PCIE_RSV_SW_10_IRQ_SET (0x70028000 + 0x8A4)---

    PCIE_RSV_SW_10_IRQ_SET[0]    - (WO) set irq
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_PCIE_RSV_SW_10_IRQ_SET_PCIE_RSV_SW_10_IRQ_SET_ADDR CB_INFRA_RGU_PCIE_RSV_SW_10_IRQ_SET_ADDR
#define CB_INFRA_RGU_PCIE_RSV_SW_10_IRQ_SET_PCIE_RSV_SW_10_IRQ_SET_MASK 0x00000001                // PCIE_RSV_SW_10_IRQ_SET[0]
#define CB_INFRA_RGU_PCIE_RSV_SW_10_IRQ_SET_PCIE_RSV_SW_10_IRQ_SET_SHFT 0

/* =====================================================================================

  ---PCIE_RSV_SW_10_IRQ_CLR (0x70028000 + 0x8A8)---

    PCIE_RSV_SW_10_IRQ_CLR[0]    - (WO) clear irq
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_PCIE_RSV_SW_10_IRQ_CLR_PCIE_RSV_SW_10_IRQ_CLR_ADDR CB_INFRA_RGU_PCIE_RSV_SW_10_IRQ_CLR_ADDR
#define CB_INFRA_RGU_PCIE_RSV_SW_10_IRQ_CLR_PCIE_RSV_SW_10_IRQ_CLR_MASK 0x00000001                // PCIE_RSV_SW_10_IRQ_CLR[0]
#define CB_INFRA_RGU_PCIE_RSV_SW_10_IRQ_CLR_PCIE_RSV_SW_10_IRQ_CLR_SHFT 0

/* =====================================================================================

  ---CB_INFRA_ON_CLK_SW_CG (0x70028000 + 0x900)---

    ULPOSC_52M_CG[0]             - (RW)  xxx 
    ULPOSC_26M_CG[1]             - (RW)  xxx 
    CBTOP_BUS_CK_EN[2]           - (RW)  xxx 
    SEJ_CK_EN[3]                 - (RW)  xxx 
    RESERVED4[31..4]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_SEJ_CK_EN_ADDR      CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_ADDR
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_SEJ_CK_EN_MASK      0x00000008                // SEJ_CK_EN[3]
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_SEJ_CK_EN_SHFT      3
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_CBTOP_BUS_CK_EN_ADDR CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_ADDR
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_CBTOP_BUS_CK_EN_MASK 0x00000004                // CBTOP_BUS_CK_EN[2]
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_CBTOP_BUS_CK_EN_SHFT 2
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_ULPOSC_26M_CG_ADDR  CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_ADDR
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_ULPOSC_26M_CG_MASK  0x00000002                // ULPOSC_26M_CG[1]
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_ULPOSC_26M_CG_SHFT  1
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_ULPOSC_52M_CG_ADDR  CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_ADDR
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_ULPOSC_52M_CG_MASK  0x00000001                // ULPOSC_52M_CG[0]
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_ULPOSC_52M_CG_SHFT  0

/* =====================================================================================

  ---CB_INFRA_ON_CLK_SW_CG_SET (0x70028000 + 0x904)---

    ULPOSC_52M_CG_SET[0]         - (WO)  xxx 
    ULPOSC_26M_CG_SET[1]         - (WO)  xxx 
    CBTOP_BUS_CK_EN_SET[2]       - (WO)  xxx 
    SEJ_CK_EN_SET[3]             - (WO)  xxx 
    RESERVED4[31..4]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_SET_SEJ_CK_EN_SET_ADDR CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_SET_ADDR
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_SET_SEJ_CK_EN_SET_MASK 0x00000008                // SEJ_CK_EN_SET[3]
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_SET_SEJ_CK_EN_SET_SHFT 3
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_SET_CBTOP_BUS_CK_EN_SET_ADDR CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_SET_ADDR
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_SET_CBTOP_BUS_CK_EN_SET_MASK 0x00000004                // CBTOP_BUS_CK_EN_SET[2]
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_SET_CBTOP_BUS_CK_EN_SET_SHFT 2
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_SET_ULPOSC_26M_CG_SET_ADDR CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_SET_ADDR
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_SET_ULPOSC_26M_CG_SET_MASK 0x00000002                // ULPOSC_26M_CG_SET[1]
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_SET_ULPOSC_26M_CG_SET_SHFT 1
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_SET_ULPOSC_52M_CG_SET_ADDR CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_SET_ADDR
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_SET_ULPOSC_52M_CG_SET_MASK 0x00000001                // ULPOSC_52M_CG_SET[0]
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_SET_ULPOSC_52M_CG_SET_SHFT 0

/* =====================================================================================

  ---CB_INFRA_ON_CLK_SW_CG_CLR (0x70028000 + 0x908)---

    ULPOSC_52M_CG_CLR[0]         - (WO)  xxx 
    ULPOSC_26M_CG_CLR[1]         - (WO)  xxx 
    CBTOP_BUS_CK_EN_CLR[2]       - (WO)  xxx 
    SEJ_CK_EN_CLR[3]             - (WO)  xxx 
    RESERVED4[31..4]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_CLR_SEJ_CK_EN_CLR_ADDR CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_CLR_ADDR
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_CLR_SEJ_CK_EN_CLR_MASK 0x00000008                // SEJ_CK_EN_CLR[3]
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_CLR_SEJ_CK_EN_CLR_SHFT 3
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_CLR_CBTOP_BUS_CK_EN_CLR_ADDR CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_CLR_ADDR
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_CLR_CBTOP_BUS_CK_EN_CLR_MASK 0x00000004                // CBTOP_BUS_CK_EN_CLR[2]
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_CLR_CBTOP_BUS_CK_EN_CLR_SHFT 2
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_CLR_ULPOSC_26M_CG_CLR_ADDR CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_CLR_ADDR
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_CLR_ULPOSC_26M_CG_CLR_MASK 0x00000002                // ULPOSC_26M_CG_CLR[1]
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_CLR_ULPOSC_26M_CG_CLR_SHFT 1
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_CLR_ULPOSC_52M_CG_CLR_ADDR CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_CLR_ADDR
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_CLR_ULPOSC_52M_CG_CLR_MASK 0x00000001                // ULPOSC_52M_CG_CLR[0]
#define CB_INFRA_RGU_CB_INFRA_ON_CLK_SW_CG_CLR_ULPOSC_52M_CG_CLR_SHFT 0

#ifdef __cplusplus
}
#endif

#endif // __CB_INFRA_RGU_REGS_H__
