/* SPDX-License-Identifier: BSD-2-Clause */

//[File]            : cb_infra_misc0.h
//[Revision time]   : Fri Jul  1 18:50:21 2022
//[Description]     : This file is auto generated by CODA
//[Copyright]       : Copyright (C) 2022 Mediatek Incorportion. All rights reserved.

#ifndef __CB_INFRA_MISC0_REGS_H__
#define __CB_INFRA_MISC0_REGS_H__

#include "hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif


//****************************************************************************
//
//                     CB_INFRA_MISC0 CR Definitions                     
//
//****************************************************************************

#define CB_INFRA_MISC0_BASE                                    0x70026000

#define CB_INFRA_MISC0_CONN2AP_GALS_SLV_DBG_ADDR               (CB_INFRA_MISC0_BASE + 0X000) // 6000
#define CB_INFRA_MISC0_CONN2AP_GALS_SLV_CTL_ADDR               (CB_INFRA_MISC0_BASE + 0x004) // 6004
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_DBG_ADDR               (CB_INFRA_MISC0_BASE + 0X008) // 6008
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_ADDR               (CB_INFRA_MISC0_BASE + 0X00C) // 600C
#define CB_INFRA_MISC0_CONN2AP_X2H_BRIDGE_DBG_ADDR             (CB_INFRA_MISC0_BASE + 0x014) // 6014
#define CB_INFRA_MISC0_AP2CONN_X2H_BRIDGE_DBG_ADDR             (CB_INFRA_MISC0_BASE + 0x018) // 6018
#define CB_INFRA_MISC0_AHB_SLV_DECODER_ADDR                    (CB_INFRA_MISC0_BASE + 0x020) // 6020
#define CB_INFRA_MISC0_AHB_SLV_DECODER_ERR_ADDR                (CB_INFRA_MISC0_BASE + 0x024) // 6024
#define CB_INFRA_MISC0_AHB_SLV_DECODER_ERR_ADDR_ADDR           (CB_INFRA_MISC0_BASE + 0x028) // 6028
#define CB_INFRA_MISC0_AHB_FREQ_BRIDGE_ADDR                    (CB_INFRA_MISC0_BASE + 0x030) // 6030
#define CB_INFRA_MISC0_H2S_CMDBT_IDLE_ADDR                     (CB_INFRA_MISC0_BASE + 0x034) // 6034
#define CB_INFRA_MISC0_H2S_OSC_IDLE_ADDR                       (CB_INFRA_MISC0_BASE + 0x040) // 6040
#define CB_INFRA_MISC0_H2S_SF_H2S_IDLE_ADDR                    (CB_INFRA_MISC0_BASE + 0x050) // 6050
#define CB_INFRA_MISC0_H2S_SYSRAM_ADDR                         (CB_INFRA_MISC0_BASE + 0x080) // 6080
#define CB_INFRA_MISC0_BTDMA2AP_GALS_SLV_DBG_ADDR              (CB_INFRA_MISC0_BASE + 0X090) // 6090
#define CB_INFRA_MISC0_PDMA2AP_GALS_SLV_DBG_ADDR               (CB_INFRA_MISC0_BASE + 0X100) // 6100
#define CB_INFRA_MISC0_PDMA2AP_GALS_SLV_CTL_ADDR               (CB_INFRA_MISC0_BASE + 0x104) // 6104
#define CB_INFRA_MISC0_PDMA2AP_GALS_2_SLV_DBG_ADDR             (CB_INFRA_MISC0_BASE + 0x108) // 6108
#define CB_INFRA_MISC0_PDMA2AP_GALS_2_SLV_CTL_ADDR             (CB_INFRA_MISC0_BASE + 0x10C) // 610C
#define CB_INFRA_MISC0_CBTOP_CMDBT_STATUS_ADDR                 (CB_INFRA_MISC0_BASE + 0x110) // 6110
#define CB_INFRA_MISC0_PCIE_AXI_DOWNSIZER_ADDR                 (CB_INFRA_MISC0_BASE + 0x140) // 6140
#define CB_INFRA_MISC0_SPI2AHB_PROB_ADDR                       (CB_INFRA_MISC0_BASE + 0x200) // 6200
#define CB_INFRA_MISC0_FPGA_MISC_CTRL_ADDR                     (CB_INFRA_MISC0_BASE + 0x300) // 6300
#define CB_INFRA_MISC0_BUS_CTL_RESERVED_A_ADDR                 (CB_INFRA_MISC0_BASE + 0x400) // 6400
#define CB_INFRA_MISC0_BUS_CTL_RESERVED_B_ADDR                 (CB_INFRA_MISC0_BASE + 0x404) // 6404
#define CB_INFRA_MISC0_CR_SLP_PROTECT_0_ADDR                   (CB_INFRA_MISC0_BASE + 0x420) // 6420
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_ADDR                 (CB_INFRA_MISC0_BASE + 0x500) // 6500
#define CB_INFRA_MISC0_CBTOP_LP_THROT_AXI_MTR_ADDR             (CB_INFRA_MISC0_BASE + 0x504) // 6504
#define CB_INFRA_MISC0_CBTOP_LP_THROT_TIME_TICK_CNT_ADDR       (CB_INFRA_MISC0_BASE + 0x508) // 6508
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_ADDR              (CB_INFRA_MISC0_BASE + 0x50C) // 650C
#define CB_INFRA_MISC0_CBTOP_PCIE_BUS_STATUS_0_ADDR            (CB_INFRA_MISC0_BASE + 0x510) // 6510
#define CB_INFRA_MISC0_CBTOP_PCIE_BUS_STATUS_1_ADDR            (CB_INFRA_MISC0_BASE + 0x514) // 6514
#define CB_INFRA_MISC0_CBTOP_FREQ_METER_DET_CTL_ADDR           (CB_INFRA_MISC0_BASE + 0x540) // 6540
#define CB_INFRA_MISC0_CBTOP_FREQ_METER_STATUS_ADDR            (CB_INFRA_MISC0_BASE + 0x54C) // 654C
#define CB_INFRA_MISC0_CBTOP_DEBUG_SEL_ADDR                    (CB_INFRA_MISC0_BASE + 0x550) // 6550
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_ADDR                (CB_INFRA_MISC0_BASE + 0x554) // 6554
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_BT_ADDR             (CB_INFRA_MISC0_BASE + 0x558) // 6558
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_BT_ADDR                (CB_INFRA_MISC0_BASE + 0x55C) // 655C
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_2_ADDR              (CB_INFRA_MISC0_BASE + 0x560) // 6560
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_BT_2_ADDR           (CB_INFRA_MISC0_BASE + 0x564) // 6564
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_BT_2_ADDR              (CB_INFRA_MISC0_BASE + 0x568) // 6568
#define CB_INFRA_MISC0_CBTOP_OFF_DBG_MUX_ADDR                  (CB_INFRA_MISC0_BASE + 0X700) // 6700
#define CB_INFRA_MISC0_AP2CONN_GALS_VIO_ADDRESS_ADDR           (CB_INFRA_MISC0_BASE + 0X704) // 6704
#define CB_INFRA_MISC0_CONN2AP_X2H_VIO_ADDRESS_ADDR            (CB_INFRA_MISC0_BASE + 0x708) // 6708
#define CB_INFRA_MISC0_AP2CONN_X2H_VIO_ADDRESS_ADDR            (CB_INFRA_MISC0_BASE + 0X70C) // 670C
#define CB_INFRA_MISC0_SDIO_CTL2WRAP_AHB_GALS_MST_ADDR         (CB_INFRA_MISC0_BASE + 0x800) // 6800
#define CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_ADDR            (CB_INFRA_MISC0_BASE + 0xA00) // 6A00
#define CB_INFRA_MISC0_CBIP_BIST_IDLE_ADDR                     (CB_INFRA_MISC0_BASE + 0xA04) // 6A04
#define CB_INFRA_MISC0_CBTOP_GALS_BIST_SW_RST_B_ADDR           (CB_INFRA_MISC0_BASE + 0xA08) // 6A08
#define CB_INFRA_MISC0_CBTOP_LP_MONITOR_EN_ADDR                (CB_INFRA_MISC0_BASE + 0xA0C) // 6A0C
#define CB_INFRA_MISC0_CBTOP_LP_MONITOR_0_ADDR                 (CB_INFRA_MISC0_BASE + 0xA10) // 6A10
#define CB_INFRA_MISC0_CBTOP_LP_MONITOR_1_ADDR                 (CB_INFRA_MISC0_BASE + 0xA14) // 6A14
#define CB_INFRA_MISC0_CBTOP_LP_MONITOR_2_ADDR                 (CB_INFRA_MISC0_BASE + 0xA18) // 6A18
#define CB_INFRA_MISC0_DCM_IDLE_CONTROL_ADDR                   (CB_INFRA_MISC0_BASE + 0xA1C) // 6A1C
#define CB_INFRA_MISC0_JTAG_SEJ_STATUS_ADDR                    (CB_INFRA_MISC0_BASE + 0xA20) // 6A20
#define CB_INFRA_MISC0_CBTOP_LP_MONITOR_3_ADDR                 (CB_INFRA_MISC0_BASE + 0xA24) // 6A24
#define CB_INFRA_MISC0_CBTOP_LP_MONITOR_4_ADDR                 (CB_INFRA_MISC0_BASE + 0xA28) // 6A28
#define CB_INFRA_MISC0_CBTOP_LP_MONITOR_CNT_ADDR               (CB_INFRA_MISC0_BASE + 0xA2C) // 6A2C




/* =====================================================================================

  ---CONN2AP_GALS_SLV_DBG (0x70026000 + 0X000)---

    CONN2AP_GALS_SLV_DBG_OUT[31..0] - (RO) [27:20]: debug_clp
                                                   {3'd0, slpprot_axi_idle_async, idle_b_async, slpprot_rdy, slpprot_en_sync, slpprot_en}
                                     [19:  0]: debug_lp
                                                   {1'b0,  wcnt_overflow_portect, rcnt_overflow_protect, bcnt_overflow_protect,
                                                     1'b0, wcnt_empty, rcnt_empty, bcnt_empty,
                                                     in_awvalid, in_awready, in_arvalid, in_arready,
                                                     in_wvalid, in_wready, in_rvalid, in_rready,
                                                     in_bvalid, in_bready, 2'b00}

 =====================================================================================*/
#define CB_INFRA_MISC0_CONN2AP_GALS_SLV_DBG_CONN2AP_GALS_SLV_DBG_OUT_ADDR CB_INFRA_MISC0_CONN2AP_GALS_SLV_DBG_ADDR
#define CB_INFRA_MISC0_CONN2AP_GALS_SLV_DBG_CONN2AP_GALS_SLV_DBG_OUT_MASK 0xFFFFFFFF                // CONN2AP_GALS_SLV_DBG_OUT[31..0]
#define CB_INFRA_MISC0_CONN2AP_GALS_SLV_DBG_CONN2AP_GALS_SLV_DBG_OUT_SHFT 0

/* =====================================================================================

  ---CONN2AP_GALS_SLV_CTL (0x70026000 + 0x004)---

    CONN2AP_GALS_MST_SYNC_SEL[1..0] - (RW)  xxx 
    CONN2AP_GALS_SLV_SYNC_SEL[3..2] - (RW)  xxx 
    CONN2AP_GALS_SAMPLE_SEL[4]   - (RW)  xxx 
    RESERVED5[31..5]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_MISC0_CONN2AP_GALS_SLV_CTL_CONN2AP_GALS_SAMPLE_SEL_ADDR CB_INFRA_MISC0_CONN2AP_GALS_SLV_CTL_ADDR
#define CB_INFRA_MISC0_CONN2AP_GALS_SLV_CTL_CONN2AP_GALS_SAMPLE_SEL_MASK 0x00000010                // CONN2AP_GALS_SAMPLE_SEL[4]
#define CB_INFRA_MISC0_CONN2AP_GALS_SLV_CTL_CONN2AP_GALS_SAMPLE_SEL_SHFT 4
#define CB_INFRA_MISC0_CONN2AP_GALS_SLV_CTL_CONN2AP_GALS_SLV_SYNC_SEL_ADDR CB_INFRA_MISC0_CONN2AP_GALS_SLV_CTL_ADDR
#define CB_INFRA_MISC0_CONN2AP_GALS_SLV_CTL_CONN2AP_GALS_SLV_SYNC_SEL_MASK 0x0000000C                // CONN2AP_GALS_SLV_SYNC_SEL[3..2]
#define CB_INFRA_MISC0_CONN2AP_GALS_SLV_CTL_CONN2AP_GALS_SLV_SYNC_SEL_SHFT 2
#define CB_INFRA_MISC0_CONN2AP_GALS_SLV_CTL_CONN2AP_GALS_MST_SYNC_SEL_ADDR CB_INFRA_MISC0_CONN2AP_GALS_SLV_CTL_ADDR
#define CB_INFRA_MISC0_CONN2AP_GALS_SLV_CTL_CONN2AP_GALS_MST_SYNC_SEL_MASK 0x00000003                // CONN2AP_GALS_MST_SYNC_SEL[1..0]
#define CB_INFRA_MISC0_CONN2AP_GALS_SLV_CTL_CONN2AP_GALS_MST_SYNC_SEL_SHFT 0

/* =====================================================================================

  ---AP2CONN_GALS_MST_DBG (0x70026000 + 0X008)---

    AP2CONN_GALS_MST_DBG_OUT[31..0] - (RO) [29:28]: vio_slpprot, vio_slpprot_event
                                     [27:24]: protect_en, protect_rdy, hreset_rst_b_raw_scan, hreset_rst_b_m
                                     [23:16]: vio_slpprot_cmd_cnt
                                     [15:12]: hsel_m, hwrite_m, hready_m, slv_ready_m
                                     [11:10]: mo_st_idle_b_m, conn_infra_ap2conn_GALS_M2S_bridge_idle_m2s_b
                                     [  9:  8]: bridge_sync_idle_m, bridge_async_idle_m
                                     [  7:  0]: queue_full, mi_st

 =====================================================================================*/
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_DBG_AP2CONN_GALS_MST_DBG_OUT_ADDR CB_INFRA_MISC0_AP2CONN_GALS_MST_DBG_ADDR
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_DBG_AP2CONN_GALS_MST_DBG_OUT_MASK 0xFFFFFFFF                // AP2CONN_GALS_MST_DBG_OUT[31..0]
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_DBG_AP2CONN_GALS_MST_DBG_OUT_SHFT 0

/* =====================================================================================

  ---AP2CONN_GALS_MST_CTL (0x70026000 + 0X00C)---

    AP2CONN_GALS_MST_VIO_DOMAIN[3..0] - (RO)  xxx 
    AP2CONN_GALS_MST_VIO_ID[10..4] - (RO)  xxx 
    AP2CONN_GALS_MST_VIO_WR[11]  - (RO)  xxx 
    AP2CONN_GALS_MST_VIO_RD[12]  - (RO)  xxx 
    AP2CONN_GALS_MST_VIO_SLPPROT[13] - (RO)  xxx 
    AP2CONN_GALS_MST_RG_AFIFO_SYNC_SEL[15..14] - (RW)  xxx 
    AP2CONN_GALS_MST_RG_CMD_CNT_CLR[16] - (RW)  xxx 
    AP2CONN_GALS_MST_RG_MONITOR_MODE[17] - (RW)  xxx 
    AP2CONN_GALS_MS_ERROR_FLAG_EN[18] - (RW)  xxx 
    AP2CONN_GALS_MS_POSTWRITE_DIS[19] - (RW)  xxx 
    AP2CONN_GALS_MST_AHB_FLUSH_THRE[21..20] - (RW) Enable flush signals by bit
                                     1'b1: Enable flush function
                                     1'b0: Disable flush function
    RESERVED22[31..22]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_AP2CONN_GALS_MST_AHB_FLUSH_THRE_ADDR CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_ADDR
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_AP2CONN_GALS_MST_AHB_FLUSH_THRE_MASK 0x00300000                // AP2CONN_GALS_MST_AHB_FLUSH_THRE[21..20]
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_AP2CONN_GALS_MST_AHB_FLUSH_THRE_SHFT 20
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_AP2CONN_GALS_MS_POSTWRITE_DIS_ADDR CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_ADDR
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_AP2CONN_GALS_MS_POSTWRITE_DIS_MASK 0x00080000                // AP2CONN_GALS_MS_POSTWRITE_DIS[19]
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_AP2CONN_GALS_MS_POSTWRITE_DIS_SHFT 19
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_AP2CONN_GALS_MS_ERROR_FLAG_EN_ADDR CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_ADDR
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_AP2CONN_GALS_MS_ERROR_FLAG_EN_MASK 0x00040000                // AP2CONN_GALS_MS_ERROR_FLAG_EN[18]
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_AP2CONN_GALS_MS_ERROR_FLAG_EN_SHFT 18
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_AP2CONN_GALS_MST_RG_MONITOR_MODE_ADDR CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_ADDR
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_AP2CONN_GALS_MST_RG_MONITOR_MODE_MASK 0x00020000                // AP2CONN_GALS_MST_RG_MONITOR_MODE[17]
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_AP2CONN_GALS_MST_RG_MONITOR_MODE_SHFT 17
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_AP2CONN_GALS_MST_RG_CMD_CNT_CLR_ADDR CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_ADDR
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_AP2CONN_GALS_MST_RG_CMD_CNT_CLR_MASK 0x00010000                // AP2CONN_GALS_MST_RG_CMD_CNT_CLR[16]
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_AP2CONN_GALS_MST_RG_CMD_CNT_CLR_SHFT 16
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_AP2CONN_GALS_MST_RG_AFIFO_SYNC_SEL_ADDR CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_ADDR
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_AP2CONN_GALS_MST_RG_AFIFO_SYNC_SEL_MASK 0x0000C000                // AP2CONN_GALS_MST_RG_AFIFO_SYNC_SEL[15..14]
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_AP2CONN_GALS_MST_RG_AFIFO_SYNC_SEL_SHFT 14
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_AP2CONN_GALS_MST_VIO_SLPPROT_ADDR CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_ADDR
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_AP2CONN_GALS_MST_VIO_SLPPROT_MASK 0x00002000                // AP2CONN_GALS_MST_VIO_SLPPROT[13]
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_AP2CONN_GALS_MST_VIO_SLPPROT_SHFT 13
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_AP2CONN_GALS_MST_VIO_RD_ADDR CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_ADDR
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_AP2CONN_GALS_MST_VIO_RD_MASK 0x00001000                // AP2CONN_GALS_MST_VIO_RD[12]
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_AP2CONN_GALS_MST_VIO_RD_SHFT 12
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_AP2CONN_GALS_MST_VIO_WR_ADDR CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_ADDR
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_AP2CONN_GALS_MST_VIO_WR_MASK 0x00000800                // AP2CONN_GALS_MST_VIO_WR[11]
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_AP2CONN_GALS_MST_VIO_WR_SHFT 11
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_AP2CONN_GALS_MST_VIO_ID_ADDR CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_ADDR
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_AP2CONN_GALS_MST_VIO_ID_MASK 0x000007F0                // AP2CONN_GALS_MST_VIO_ID[10..4]
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_AP2CONN_GALS_MST_VIO_ID_SHFT 4
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_AP2CONN_GALS_MST_VIO_DOMAIN_ADDR CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_ADDR
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_AP2CONN_GALS_MST_VIO_DOMAIN_MASK 0x0000000F                // AP2CONN_GALS_MST_VIO_DOMAIN[3..0]
#define CB_INFRA_MISC0_AP2CONN_GALS_MST_CTL_AP2CONN_GALS_MST_VIO_DOMAIN_SHFT 0

/* =====================================================================================

  ---CONN2AP_X2H_BRIDGE_DBG (0x70026000 + 0x014)---

    CONN2AP_X2H_VIO_RD[0]        - (RO)  xxx 
    CONN2AP_X2H_VIO_WR[1]        - (RO)  xxx 
    RESERVED2[2]                 - (RO) Reserved bits
    CONN2AP_X2H_VIO_ID[13..3]    - (RO)  xxx 
    CONN2AP_X2H_VIO_ADDR_UNALIGN[14] - (RO)  xxx 
    CONN2AP_X2H_VIO_DOMAIN[18..15] - (RO)  xxx 
    RESERVED19[31..19]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_MISC0_CONN2AP_X2H_BRIDGE_DBG_CONN2AP_X2H_VIO_DOMAIN_ADDR CB_INFRA_MISC0_CONN2AP_X2H_BRIDGE_DBG_ADDR
#define CB_INFRA_MISC0_CONN2AP_X2H_BRIDGE_DBG_CONN2AP_X2H_VIO_DOMAIN_MASK 0x00078000                // CONN2AP_X2H_VIO_DOMAIN[18..15]
#define CB_INFRA_MISC0_CONN2AP_X2H_BRIDGE_DBG_CONN2AP_X2H_VIO_DOMAIN_SHFT 15
#define CB_INFRA_MISC0_CONN2AP_X2H_BRIDGE_DBG_CONN2AP_X2H_VIO_ADDR_UNALIGN_ADDR CB_INFRA_MISC0_CONN2AP_X2H_BRIDGE_DBG_ADDR
#define CB_INFRA_MISC0_CONN2AP_X2H_BRIDGE_DBG_CONN2AP_X2H_VIO_ADDR_UNALIGN_MASK 0x00004000                // CONN2AP_X2H_VIO_ADDR_UNALIGN[14]
#define CB_INFRA_MISC0_CONN2AP_X2H_BRIDGE_DBG_CONN2AP_X2H_VIO_ADDR_UNALIGN_SHFT 14
#define CB_INFRA_MISC0_CONN2AP_X2H_BRIDGE_DBG_CONN2AP_X2H_VIO_ID_ADDR CB_INFRA_MISC0_CONN2AP_X2H_BRIDGE_DBG_ADDR
#define CB_INFRA_MISC0_CONN2AP_X2H_BRIDGE_DBG_CONN2AP_X2H_VIO_ID_MASK 0x00003FF8                // CONN2AP_X2H_VIO_ID[13..3]
#define CB_INFRA_MISC0_CONN2AP_X2H_BRIDGE_DBG_CONN2AP_X2H_VIO_ID_SHFT 3
#define CB_INFRA_MISC0_CONN2AP_X2H_BRIDGE_DBG_CONN2AP_X2H_VIO_WR_ADDR CB_INFRA_MISC0_CONN2AP_X2H_BRIDGE_DBG_ADDR
#define CB_INFRA_MISC0_CONN2AP_X2H_BRIDGE_DBG_CONN2AP_X2H_VIO_WR_MASK 0x00000002                // CONN2AP_X2H_VIO_WR[1]
#define CB_INFRA_MISC0_CONN2AP_X2H_BRIDGE_DBG_CONN2AP_X2H_VIO_WR_SHFT 1
#define CB_INFRA_MISC0_CONN2AP_X2H_BRIDGE_DBG_CONN2AP_X2H_VIO_RD_ADDR CB_INFRA_MISC0_CONN2AP_X2H_BRIDGE_DBG_ADDR
#define CB_INFRA_MISC0_CONN2AP_X2H_BRIDGE_DBG_CONN2AP_X2H_VIO_RD_MASK 0x00000001                // CONN2AP_X2H_VIO_RD[0]
#define CB_INFRA_MISC0_CONN2AP_X2H_BRIDGE_DBG_CONN2AP_X2H_VIO_RD_SHFT 0

/* =====================================================================================

  ---AP2CONN_X2H_BRIDGE_DBG (0x70026000 + 0x018)---

    AP2CONN_X2H_VIO_RD[0]        - (RO)  xxx 
    AP2CONN_X2H_VIO_WR[1]        - (RO)  xxx 
    AP2CONN_X2H_VIO_DOMAIN[5..2] - (RO)  xxx 
    AP2CONN_X2H_VIO_ID[12..6]    - (RO)  xxx 
    AP2CONN_X2H_VIO_ADDR_UNALIGN[13] - (RO)  xxx 
    AP2CONN_X2H_SINGLE_BEAT[14]  - (RO)  xxx 
    AP2CONN_X2H_IDLE[15]         - (RO)  xxx 
    AP2CONN_X2H_BYPASS_MODE_OUT[16] - (RO)  xxx 
    RESERVED17[31..17]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_MISC0_AP2CONN_X2H_BRIDGE_DBG_AP2CONN_X2H_BYPASS_MODE_OUT_ADDR CB_INFRA_MISC0_AP2CONN_X2H_BRIDGE_DBG_ADDR
#define CB_INFRA_MISC0_AP2CONN_X2H_BRIDGE_DBG_AP2CONN_X2H_BYPASS_MODE_OUT_MASK 0x00010000                // AP2CONN_X2H_BYPASS_MODE_OUT[16]
#define CB_INFRA_MISC0_AP2CONN_X2H_BRIDGE_DBG_AP2CONN_X2H_BYPASS_MODE_OUT_SHFT 16
#define CB_INFRA_MISC0_AP2CONN_X2H_BRIDGE_DBG_AP2CONN_X2H_IDLE_ADDR CB_INFRA_MISC0_AP2CONN_X2H_BRIDGE_DBG_ADDR
#define CB_INFRA_MISC0_AP2CONN_X2H_BRIDGE_DBG_AP2CONN_X2H_IDLE_MASK 0x00008000                // AP2CONN_X2H_IDLE[15]
#define CB_INFRA_MISC0_AP2CONN_X2H_BRIDGE_DBG_AP2CONN_X2H_IDLE_SHFT 15
#define CB_INFRA_MISC0_AP2CONN_X2H_BRIDGE_DBG_AP2CONN_X2H_SINGLE_BEAT_ADDR CB_INFRA_MISC0_AP2CONN_X2H_BRIDGE_DBG_ADDR
#define CB_INFRA_MISC0_AP2CONN_X2H_BRIDGE_DBG_AP2CONN_X2H_SINGLE_BEAT_MASK 0x00004000                // AP2CONN_X2H_SINGLE_BEAT[14]
#define CB_INFRA_MISC0_AP2CONN_X2H_BRIDGE_DBG_AP2CONN_X2H_SINGLE_BEAT_SHFT 14
#define CB_INFRA_MISC0_AP2CONN_X2H_BRIDGE_DBG_AP2CONN_X2H_VIO_ADDR_UNALIGN_ADDR CB_INFRA_MISC0_AP2CONN_X2H_BRIDGE_DBG_ADDR
#define CB_INFRA_MISC0_AP2CONN_X2H_BRIDGE_DBG_AP2CONN_X2H_VIO_ADDR_UNALIGN_MASK 0x00002000                // AP2CONN_X2H_VIO_ADDR_UNALIGN[13]
#define CB_INFRA_MISC0_AP2CONN_X2H_BRIDGE_DBG_AP2CONN_X2H_VIO_ADDR_UNALIGN_SHFT 13
#define CB_INFRA_MISC0_AP2CONN_X2H_BRIDGE_DBG_AP2CONN_X2H_VIO_ID_ADDR CB_INFRA_MISC0_AP2CONN_X2H_BRIDGE_DBG_ADDR
#define CB_INFRA_MISC0_AP2CONN_X2H_BRIDGE_DBG_AP2CONN_X2H_VIO_ID_MASK 0x00001FC0                // AP2CONN_X2H_VIO_ID[12..6]
#define CB_INFRA_MISC0_AP2CONN_X2H_BRIDGE_DBG_AP2CONN_X2H_VIO_ID_SHFT 6
#define CB_INFRA_MISC0_AP2CONN_X2H_BRIDGE_DBG_AP2CONN_X2H_VIO_DOMAIN_ADDR CB_INFRA_MISC0_AP2CONN_X2H_BRIDGE_DBG_ADDR
#define CB_INFRA_MISC0_AP2CONN_X2H_BRIDGE_DBG_AP2CONN_X2H_VIO_DOMAIN_MASK 0x0000003C                // AP2CONN_X2H_VIO_DOMAIN[5..2]
#define CB_INFRA_MISC0_AP2CONN_X2H_BRIDGE_DBG_AP2CONN_X2H_VIO_DOMAIN_SHFT 2
#define CB_INFRA_MISC0_AP2CONN_X2H_BRIDGE_DBG_AP2CONN_X2H_VIO_WR_ADDR CB_INFRA_MISC0_AP2CONN_X2H_BRIDGE_DBG_ADDR
#define CB_INFRA_MISC0_AP2CONN_X2H_BRIDGE_DBG_AP2CONN_X2H_VIO_WR_MASK 0x00000002                // AP2CONN_X2H_VIO_WR[1]
#define CB_INFRA_MISC0_AP2CONN_X2H_BRIDGE_DBG_AP2CONN_X2H_VIO_WR_SHFT 1
#define CB_INFRA_MISC0_AP2CONN_X2H_BRIDGE_DBG_AP2CONN_X2H_VIO_RD_ADDR CB_INFRA_MISC0_AP2CONN_X2H_BRIDGE_DBG_ADDR
#define CB_INFRA_MISC0_AP2CONN_X2H_BRIDGE_DBG_AP2CONN_X2H_VIO_RD_MASK 0x00000001                // AP2CONN_X2H_VIO_RD[0]
#define CB_INFRA_MISC0_AP2CONN_X2H_BRIDGE_DBG_AP2CONN_X2H_VIO_RD_SHFT 0

/* =====================================================================================

  ---AHB_SLV_DECODER (0x70026000 + 0x020)---

    DECODE_AHB_SLV_DECODER_IDLE[0] - (RO)  xxx 
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_MISC0_AHB_SLV_DECODER_DECODE_AHB_SLV_DECODER_IDLE_ADDR CB_INFRA_MISC0_AHB_SLV_DECODER_ADDR
#define CB_INFRA_MISC0_AHB_SLV_DECODER_DECODE_AHB_SLV_DECODER_IDLE_MASK 0x00000001                // DECODE_AHB_SLV_DECODER_IDLE[0]
#define CB_INFRA_MISC0_AHB_SLV_DECODER_DECODE_AHB_SLV_DECODER_IDLE_SHFT 0

/* =====================================================================================

  ---AHB_SLV_DECODER_ERR (0x70026000 + 0x024)---

    DECODE_ERR_DECERR[0]         - (RO)  xxx 
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_MISC0_AHB_SLV_DECODER_ERR_DECODE_ERR_DECERR_ADDR CB_INFRA_MISC0_AHB_SLV_DECODER_ERR_ADDR
#define CB_INFRA_MISC0_AHB_SLV_DECODER_ERR_DECODE_ERR_DECERR_MASK 0x00000001                // DECODE_ERR_DECERR[0]
#define CB_INFRA_MISC0_AHB_SLV_DECODER_ERR_DECODE_ERR_DECERR_SHFT 0

/* =====================================================================================

  ---AHB_SLV_DECODER_ERR_ADDR (0x70026000 + 0x028)---

    DECODE_ERR_ADDR[31..0]       - (RO)  xxx 

 =====================================================================================*/
#define CB_INFRA_MISC0_AHB_SLV_DECODER_ERR_ADDR_DECODE_ERR_ADDR_ADDR CB_INFRA_MISC0_AHB_SLV_DECODER_ERR_ADDR_ADDR
#define CB_INFRA_MISC0_AHB_SLV_DECODER_ERR_ADDR_DECODE_ERR_ADDR_MASK 0xFFFFFFFF                // DECODE_ERR_ADDR[31..0]
#define CB_INFRA_MISC0_AHB_SLV_DECODER_ERR_ADDR_DECODE_ERR_ADDR_SHFT 0

/* =====================================================================================

  ---AHB_FREQ_BRIDGE (0x70026000 + 0x030)---

    IDLE_M_REG[0]                - (RO)  xxx 
    IDLE_M[1]                    - (RO)  xxx 
    RESERVED2[31..2]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_MISC0_AHB_FREQ_BRIDGE_IDLE_M_ADDR             CB_INFRA_MISC0_AHB_FREQ_BRIDGE_ADDR
#define CB_INFRA_MISC0_AHB_FREQ_BRIDGE_IDLE_M_MASK             0x00000002                // IDLE_M[1]
#define CB_INFRA_MISC0_AHB_FREQ_BRIDGE_IDLE_M_SHFT             1
#define CB_INFRA_MISC0_AHB_FREQ_BRIDGE_IDLE_M_REG_ADDR         CB_INFRA_MISC0_AHB_FREQ_BRIDGE_ADDR
#define CB_INFRA_MISC0_AHB_FREQ_BRIDGE_IDLE_M_REG_MASK         0x00000001                // IDLE_M_REG[0]
#define CB_INFRA_MISC0_AHB_FREQ_BRIDGE_IDLE_M_REG_SHFT         0

/* =====================================================================================

  ---H2S_CMDBT_IDLE (0x70026000 + 0x034)---

    h2s_cmdbt_idle[0]            - (RO)  xxx 
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_MISC0_H2S_CMDBT_IDLE_h2s_cmdbt_idle_ADDR      CB_INFRA_MISC0_H2S_CMDBT_IDLE_ADDR
#define CB_INFRA_MISC0_H2S_CMDBT_IDLE_h2s_cmdbt_idle_MASK      0x00000001                // h2s_cmdbt_idle[0]
#define CB_INFRA_MISC0_H2S_CMDBT_IDLE_h2s_cmdbt_idle_SHFT      0

/* =====================================================================================

  ---H2S_OSC_IDLE (0x70026000 + 0x040)---

    h2s_osc_idle[0]              - (RO)  xxx 
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_MISC0_H2S_OSC_IDLE_h2s_osc_idle_ADDR          CB_INFRA_MISC0_H2S_OSC_IDLE_ADDR
#define CB_INFRA_MISC0_H2S_OSC_IDLE_h2s_osc_idle_MASK          0x00000001                // h2s_osc_idle[0]
#define CB_INFRA_MISC0_H2S_OSC_IDLE_h2s_osc_idle_SHFT          0

/* =====================================================================================

  ---H2S_SF_H2S_IDLE (0x70026000 + 0x050)---

    h2s_sf_h2s_idle[0]           - (RO)  xxx 
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_MISC0_H2S_SF_H2S_IDLE_h2s_sf_h2s_idle_ADDR    CB_INFRA_MISC0_H2S_SF_H2S_IDLE_ADDR
#define CB_INFRA_MISC0_H2S_SF_H2S_IDLE_h2s_sf_h2s_idle_MASK    0x00000001                // h2s_sf_h2s_idle[0]
#define CB_INFRA_MISC0_H2S_SF_H2S_IDLE_h2s_sf_h2s_idle_SHFT    0

/* =====================================================================================

  ---H2S_SYSRAM (0x70026000 + 0x080)---

    h2s_sysram_reg_slave_way_en[0] - (RW)  xxx 
    h2s_sysram_ctrl_update_status[1] - (RO)  xxx 
    h2s_sysram_h2s_idle[2]       - (RO)  xxx 
    h2s_sysram_reg_force_slast[3] - (RW)  xxx 
    RESERVED4[31..4]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_MISC0_H2S_SYSRAM_h2s_sysram_reg_force_slast_ADDR CB_INFRA_MISC0_H2S_SYSRAM_ADDR
#define CB_INFRA_MISC0_H2S_SYSRAM_h2s_sysram_reg_force_slast_MASK 0x00000008                // h2s_sysram_reg_force_slast[3]
#define CB_INFRA_MISC0_H2S_SYSRAM_h2s_sysram_reg_force_slast_SHFT 3
#define CB_INFRA_MISC0_H2S_SYSRAM_h2s_sysram_h2s_idle_ADDR     CB_INFRA_MISC0_H2S_SYSRAM_ADDR
#define CB_INFRA_MISC0_H2S_SYSRAM_h2s_sysram_h2s_idle_MASK     0x00000004                // h2s_sysram_h2s_idle[2]
#define CB_INFRA_MISC0_H2S_SYSRAM_h2s_sysram_h2s_idle_SHFT     2
#define CB_INFRA_MISC0_H2S_SYSRAM_h2s_sysram_ctrl_update_status_ADDR CB_INFRA_MISC0_H2S_SYSRAM_ADDR
#define CB_INFRA_MISC0_H2S_SYSRAM_h2s_sysram_ctrl_update_status_MASK 0x00000002                // h2s_sysram_ctrl_update_status[1]
#define CB_INFRA_MISC0_H2S_SYSRAM_h2s_sysram_ctrl_update_status_SHFT 1
#define CB_INFRA_MISC0_H2S_SYSRAM_h2s_sysram_reg_slave_way_en_ADDR CB_INFRA_MISC0_H2S_SYSRAM_ADDR
#define CB_INFRA_MISC0_H2S_SYSRAM_h2s_sysram_reg_slave_way_en_MASK 0x00000001                // h2s_sysram_reg_slave_way_en[0]
#define CB_INFRA_MISC0_H2S_SYSRAM_h2s_sysram_reg_slave_way_en_SHFT 0

/* =====================================================================================

  ---BTDMA2AP_GALS_SLV_DBG (0x70026000 + 0X090)---

    BTDMA2AP_GALS_SLV_DBG_OUT[31..0] - (RO) [27:20]: debug_clp
                                                   {3'd0, slpprot_axi_idle_async, idle_b_async, slpprot_rdy, slpprot_en_sync, slpprot_en}
                                     [19:  0]: debug_lp
                                                   {1'b0,  wcnt_overflow_portect, rcnt_overflow_protect, bcnt_overflow_protect,
                                                     1'b0, wcnt_empty, rcnt_empty, bcnt_empty,
                                                     in_awvalid, in_awready, in_arvalid, in_arready,
                                                     in_wvalid, in_wready, in_rvalid, in_rready,
                                                     in_bvalid, in_bready, 2'b00}

 =====================================================================================*/
#define CB_INFRA_MISC0_BTDMA2AP_GALS_SLV_DBG_BTDMA2AP_GALS_SLV_DBG_OUT_ADDR CB_INFRA_MISC0_BTDMA2AP_GALS_SLV_DBG_ADDR
#define CB_INFRA_MISC0_BTDMA2AP_GALS_SLV_DBG_BTDMA2AP_GALS_SLV_DBG_OUT_MASK 0xFFFFFFFF                // BTDMA2AP_GALS_SLV_DBG_OUT[31..0]
#define CB_INFRA_MISC0_BTDMA2AP_GALS_SLV_DBG_BTDMA2AP_GALS_SLV_DBG_OUT_SHFT 0

/* =====================================================================================

  ---PDMA2AP_GALS_SLV_DBG (0x70026000 + 0X100)---

    PDMA2AP_GALS_SLV_DBG_OUT[31..0] - (RO) [27:20]: debug_clp
                                                   {3'd0, slpprot_axi_idle_async, idle_b_async, slpprot_rdy, slpprot_en_sync, slpprot_en}
                                     [19:  0]: debug_lp
                                                   {1'b0,  wcnt_overflow_portect, rcnt_overflow_protect, bcnt_overflow_protect,
                                                     1'b0, wcnt_empty, rcnt_empty, bcnt_empty,
                                                     in_awvalid, in_awready, in_arvalid, in_arready,
                                                     in_wvalid, in_wready, in_rvalid, in_rready,
                                                     in_bvalid, in_bready, 2'b00}

 =====================================================================================*/
#define CB_INFRA_MISC0_PDMA2AP_GALS_SLV_DBG_PDMA2AP_GALS_SLV_DBG_OUT_ADDR CB_INFRA_MISC0_PDMA2AP_GALS_SLV_DBG_ADDR
#define CB_INFRA_MISC0_PDMA2AP_GALS_SLV_DBG_PDMA2AP_GALS_SLV_DBG_OUT_MASK 0xFFFFFFFF                // PDMA2AP_GALS_SLV_DBG_OUT[31..0]
#define CB_INFRA_MISC0_PDMA2AP_GALS_SLV_DBG_PDMA2AP_GALS_SLV_DBG_OUT_SHFT 0

/* =====================================================================================

  ---PDMA2AP_GALS_SLV_CTL (0x70026000 + 0x104)---

    PDMA2AP_GALS_MST_SYNC_SEL[1..0] - (RW)  xxx 
    PDMA2AP_GALS_SLV_SYNC_SEL[3..2] - (RW)  xxx 
    PDMA2AP_GALS_SAMPLE_SEL[4]   - (RW)  xxx 
    RESERVED5[31..5]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_MISC0_PDMA2AP_GALS_SLV_CTL_PDMA2AP_GALS_SAMPLE_SEL_ADDR CB_INFRA_MISC0_PDMA2AP_GALS_SLV_CTL_ADDR
#define CB_INFRA_MISC0_PDMA2AP_GALS_SLV_CTL_PDMA2AP_GALS_SAMPLE_SEL_MASK 0x00000010                // PDMA2AP_GALS_SAMPLE_SEL[4]
#define CB_INFRA_MISC0_PDMA2AP_GALS_SLV_CTL_PDMA2AP_GALS_SAMPLE_SEL_SHFT 4
#define CB_INFRA_MISC0_PDMA2AP_GALS_SLV_CTL_PDMA2AP_GALS_SLV_SYNC_SEL_ADDR CB_INFRA_MISC0_PDMA2AP_GALS_SLV_CTL_ADDR
#define CB_INFRA_MISC0_PDMA2AP_GALS_SLV_CTL_PDMA2AP_GALS_SLV_SYNC_SEL_MASK 0x0000000C                // PDMA2AP_GALS_SLV_SYNC_SEL[3..2]
#define CB_INFRA_MISC0_PDMA2AP_GALS_SLV_CTL_PDMA2AP_GALS_SLV_SYNC_SEL_SHFT 2
#define CB_INFRA_MISC0_PDMA2AP_GALS_SLV_CTL_PDMA2AP_GALS_MST_SYNC_SEL_ADDR CB_INFRA_MISC0_PDMA2AP_GALS_SLV_CTL_ADDR
#define CB_INFRA_MISC0_PDMA2AP_GALS_SLV_CTL_PDMA2AP_GALS_MST_SYNC_SEL_MASK 0x00000003                // PDMA2AP_GALS_MST_SYNC_SEL[1..0]
#define CB_INFRA_MISC0_PDMA2AP_GALS_SLV_CTL_PDMA2AP_GALS_MST_SYNC_SEL_SHFT 0

/* =====================================================================================

  ---PDMA2AP_GALS_2_SLV_DBG (0x70026000 + 0x108)---

    PDMA2AP_GALS_2_SLV_DBG_OUT[31..0] - (RO)  xxx 

 =====================================================================================*/
#define CB_INFRA_MISC0_PDMA2AP_GALS_2_SLV_DBG_PDMA2AP_GALS_2_SLV_DBG_OUT_ADDR CB_INFRA_MISC0_PDMA2AP_GALS_2_SLV_DBG_ADDR
#define CB_INFRA_MISC0_PDMA2AP_GALS_2_SLV_DBG_PDMA2AP_GALS_2_SLV_DBG_OUT_MASK 0xFFFFFFFF                // PDMA2AP_GALS_2_SLV_DBG_OUT[31..0]
#define CB_INFRA_MISC0_PDMA2AP_GALS_2_SLV_DBG_PDMA2AP_GALS_2_SLV_DBG_OUT_SHFT 0

/* =====================================================================================

  ---PDMA2AP_GALS_2_SLV_CTL (0x70026000 + 0x10C)---

    PDMA2AP_GALS_2_MST_SYNC_SEL[1..0] - (RW)  xxx 
    PDMA2AP_GALS_2_SLV_SYNC_SEL[3..2] - (RW)  xxx 
    PDMA2AP_GALS_2_SAMPLE_SEL[4] - (RW)  xxx 
    RESERVED5[31..5]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_MISC0_PDMA2AP_GALS_2_SLV_CTL_PDMA2AP_GALS_2_SAMPLE_SEL_ADDR CB_INFRA_MISC0_PDMA2AP_GALS_2_SLV_CTL_ADDR
#define CB_INFRA_MISC0_PDMA2AP_GALS_2_SLV_CTL_PDMA2AP_GALS_2_SAMPLE_SEL_MASK 0x00000010                // PDMA2AP_GALS_2_SAMPLE_SEL[4]
#define CB_INFRA_MISC0_PDMA2AP_GALS_2_SLV_CTL_PDMA2AP_GALS_2_SAMPLE_SEL_SHFT 4
#define CB_INFRA_MISC0_PDMA2AP_GALS_2_SLV_CTL_PDMA2AP_GALS_2_SLV_SYNC_SEL_ADDR CB_INFRA_MISC0_PDMA2AP_GALS_2_SLV_CTL_ADDR
#define CB_INFRA_MISC0_PDMA2AP_GALS_2_SLV_CTL_PDMA2AP_GALS_2_SLV_SYNC_SEL_MASK 0x0000000C                // PDMA2AP_GALS_2_SLV_SYNC_SEL[3..2]
#define CB_INFRA_MISC0_PDMA2AP_GALS_2_SLV_CTL_PDMA2AP_GALS_2_SLV_SYNC_SEL_SHFT 2
#define CB_INFRA_MISC0_PDMA2AP_GALS_2_SLV_CTL_PDMA2AP_GALS_2_MST_SYNC_SEL_ADDR CB_INFRA_MISC0_PDMA2AP_GALS_2_SLV_CTL_ADDR
#define CB_INFRA_MISC0_PDMA2AP_GALS_2_SLV_CTL_PDMA2AP_GALS_2_MST_SYNC_SEL_MASK 0x00000003                // PDMA2AP_GALS_2_MST_SYNC_SEL[1..0]
#define CB_INFRA_MISC0_PDMA2AP_GALS_2_SLV_CTL_PDMA2AP_GALS_2_MST_SYNC_SEL_SHFT 0

/* =====================================================================================

  ---CBTOP_CMDBT_STATUS (0x70026000 + 0x110)---

    cbtop_cmdbt_debug_flag_b0[7..0] - (RO)  xxx 
    cbtop_cmdbt_debug_flag_b1[15..8] - (RO)  xxx 
    cbtop_cmdbt_int[16]          - (RO)  xxx 
    RESERVED17[31..17]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_MISC0_CBTOP_CMDBT_STATUS_cbtop_cmdbt_int_ADDR CB_INFRA_MISC0_CBTOP_CMDBT_STATUS_ADDR
#define CB_INFRA_MISC0_CBTOP_CMDBT_STATUS_cbtop_cmdbt_int_MASK 0x00010000                // cbtop_cmdbt_int[16]
#define CB_INFRA_MISC0_CBTOP_CMDBT_STATUS_cbtop_cmdbt_int_SHFT 16
#define CB_INFRA_MISC0_CBTOP_CMDBT_STATUS_cbtop_cmdbt_debug_flag_b1_ADDR CB_INFRA_MISC0_CBTOP_CMDBT_STATUS_ADDR
#define CB_INFRA_MISC0_CBTOP_CMDBT_STATUS_cbtop_cmdbt_debug_flag_b1_MASK 0x0000FF00                // cbtop_cmdbt_debug_flag_b1[15..8]
#define CB_INFRA_MISC0_CBTOP_CMDBT_STATUS_cbtop_cmdbt_debug_flag_b1_SHFT 8
#define CB_INFRA_MISC0_CBTOP_CMDBT_STATUS_cbtop_cmdbt_debug_flag_b0_ADDR CB_INFRA_MISC0_CBTOP_CMDBT_STATUS_ADDR
#define CB_INFRA_MISC0_CBTOP_CMDBT_STATUS_cbtop_cmdbt_debug_flag_b0_MASK 0x000000FF                // cbtop_cmdbt_debug_flag_b0[7..0]
#define CB_INFRA_MISC0_CBTOP_CMDBT_STATUS_cbtop_cmdbt_debug_flag_b0_SHFT 0

/* =====================================================================================

  ---PCIE_AXI_DOWNSIZER (0x70026000 + 0x140)---

    PCIE_AXI_DOWNSIZER_WRAP_ERR_FLAG[0] - (RO)  xxx 
    PCIE_AXI_DOWNSIZER_IDLE[1]   - (RO)  xxx 
    PCIE_AXI_DOWNSIZER_2_WRAP_ERR_FLAG[2] - (RO)  xxx 
    PCIE_AXI_DOWNSIZER_2_IDLE[3] - (RO)  xxx 
    RESERVED4[31..4]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_MISC0_PCIE_AXI_DOWNSIZER_PCIE_AXI_DOWNSIZER_2_IDLE_ADDR CB_INFRA_MISC0_PCIE_AXI_DOWNSIZER_ADDR
#define CB_INFRA_MISC0_PCIE_AXI_DOWNSIZER_PCIE_AXI_DOWNSIZER_2_IDLE_MASK 0x00000008                // PCIE_AXI_DOWNSIZER_2_IDLE[3]
#define CB_INFRA_MISC0_PCIE_AXI_DOWNSIZER_PCIE_AXI_DOWNSIZER_2_IDLE_SHFT 3
#define CB_INFRA_MISC0_PCIE_AXI_DOWNSIZER_PCIE_AXI_DOWNSIZER_2_WRAP_ERR_FLAG_ADDR CB_INFRA_MISC0_PCIE_AXI_DOWNSIZER_ADDR
#define CB_INFRA_MISC0_PCIE_AXI_DOWNSIZER_PCIE_AXI_DOWNSIZER_2_WRAP_ERR_FLAG_MASK 0x00000004                // PCIE_AXI_DOWNSIZER_2_WRAP_ERR_FLAG[2]
#define CB_INFRA_MISC0_PCIE_AXI_DOWNSIZER_PCIE_AXI_DOWNSIZER_2_WRAP_ERR_FLAG_SHFT 2
#define CB_INFRA_MISC0_PCIE_AXI_DOWNSIZER_PCIE_AXI_DOWNSIZER_IDLE_ADDR CB_INFRA_MISC0_PCIE_AXI_DOWNSIZER_ADDR
#define CB_INFRA_MISC0_PCIE_AXI_DOWNSIZER_PCIE_AXI_DOWNSIZER_IDLE_MASK 0x00000002                // PCIE_AXI_DOWNSIZER_IDLE[1]
#define CB_INFRA_MISC0_PCIE_AXI_DOWNSIZER_PCIE_AXI_DOWNSIZER_IDLE_SHFT 1
#define CB_INFRA_MISC0_PCIE_AXI_DOWNSIZER_PCIE_AXI_DOWNSIZER_WRAP_ERR_FLAG_ADDR CB_INFRA_MISC0_PCIE_AXI_DOWNSIZER_ADDR
#define CB_INFRA_MISC0_PCIE_AXI_DOWNSIZER_PCIE_AXI_DOWNSIZER_WRAP_ERR_FLAG_MASK 0x00000001                // PCIE_AXI_DOWNSIZER_WRAP_ERR_FLAG[0]
#define CB_INFRA_MISC0_PCIE_AXI_DOWNSIZER_PCIE_AXI_DOWNSIZER_WRAP_ERR_FLAG_SHFT 0

/* =====================================================================================

  ---SPI2AHB_PROB (0x70026000 + 0x200)---

    SPI2AHB_PROB[31..0]          - (RO)  xxx 

 =====================================================================================*/
#define CB_INFRA_MISC0_SPI2AHB_PROB_SPI2AHB_PROB_ADDR          CB_INFRA_MISC0_SPI2AHB_PROB_ADDR
#define CB_INFRA_MISC0_SPI2AHB_PROB_SPI2AHB_PROB_MASK          0xFFFFFFFF                // SPI2AHB_PROB[31..0]
#define CB_INFRA_MISC0_SPI2AHB_PROB_SPI2AHB_PROB_SHFT          0

/* =====================================================================================

  ---FPGA_MISC_CTRL (0x70026000 + 0x300)---

    FPGA_DBG_SEL[1..0]           - (RW) FPGA debug bus select:
                                     2'b11 : 32'h0
                                     2'b10 : Debug bus is USB debug monitor
                                     2'b01 : Debug bus is PCIe debug monitor
                                     2'b00 : Debug bus is conn_test_do
    FPGA_CR_RSV_0[6..2]          - (RW) Reserved
    FPGA_BUS_DFS_CTRL[7]         - (RW) CONNSYS BUS DFS control:
                                     1'b1 : BUS clock frequency is 10MHz
                                     1'b0 : BUS clock frequency is 5MHz
                                     
                                     For FPGA, default is 1'b1
    FPGA_WFDMA_DFS_CTRL[9..8]    - (RW) WFDMA DFS control:
                                     2'b10 : WFDMA clock frequency is 5MHz
                                     2'b01 : WFDMA clock frequency is 10MHz
                                     2'b00 : WFDMA clock frequency is 20MHz
    FPGA_UMAC_DFS_CTRL[11..10]   - (RW) UMAC DFS control:
                                     2'b10 : UMAC clock frequency is 5MHz
                                     2'b01 : UMAC clock frequency is 10MHz
                                     2'b00 : UMAC clock frequency is 20MHz
    FPGA_CR_RSV_1[13..12]        - (RW) Reserved
    FPGA_BAND0_BUS_SEL[14]       - (RW) Band0 M2M bus0 control:
                                     1'b1 : Select band0 bus0_2nd (MU setup)
                                     1'b0 : Select band0 bus0 (SU setup)
    FPGA_BAND1_BUS_SEL[15]       - (RW) Band1 M2M bus0 control:
                                     1'b1 : Select band1 bus0_2nd (MU setup)
                                     1'b0 : Select band1 bus0 (SU setup)
    FPGA_CR_RSV_2[31..16]        - (RW) Reserved

 =====================================================================================*/
#define CB_INFRA_MISC0_FPGA_MISC_CTRL_FPGA_CR_RSV_2_ADDR       CB_INFRA_MISC0_FPGA_MISC_CTRL_ADDR
#define CB_INFRA_MISC0_FPGA_MISC_CTRL_FPGA_CR_RSV_2_MASK       0xFFFF0000                // FPGA_CR_RSV_2[31..16]
#define CB_INFRA_MISC0_FPGA_MISC_CTRL_FPGA_CR_RSV_2_SHFT       16
#define CB_INFRA_MISC0_FPGA_MISC_CTRL_FPGA_BAND1_BUS_SEL_ADDR  CB_INFRA_MISC0_FPGA_MISC_CTRL_ADDR
#define CB_INFRA_MISC0_FPGA_MISC_CTRL_FPGA_BAND1_BUS_SEL_MASK  0x00008000                // FPGA_BAND1_BUS_SEL[15]
#define CB_INFRA_MISC0_FPGA_MISC_CTRL_FPGA_BAND1_BUS_SEL_SHFT  15
#define CB_INFRA_MISC0_FPGA_MISC_CTRL_FPGA_BAND0_BUS_SEL_ADDR  CB_INFRA_MISC0_FPGA_MISC_CTRL_ADDR
#define CB_INFRA_MISC0_FPGA_MISC_CTRL_FPGA_BAND0_BUS_SEL_MASK  0x00004000                // FPGA_BAND0_BUS_SEL[14]
#define CB_INFRA_MISC0_FPGA_MISC_CTRL_FPGA_BAND0_BUS_SEL_SHFT  14
#define CB_INFRA_MISC0_FPGA_MISC_CTRL_FPGA_CR_RSV_1_ADDR       CB_INFRA_MISC0_FPGA_MISC_CTRL_ADDR
#define CB_INFRA_MISC0_FPGA_MISC_CTRL_FPGA_CR_RSV_1_MASK       0x00003000                // FPGA_CR_RSV_1[13..12]
#define CB_INFRA_MISC0_FPGA_MISC_CTRL_FPGA_CR_RSV_1_SHFT       12
#define CB_INFRA_MISC0_FPGA_MISC_CTRL_FPGA_UMAC_DFS_CTRL_ADDR  CB_INFRA_MISC0_FPGA_MISC_CTRL_ADDR
#define CB_INFRA_MISC0_FPGA_MISC_CTRL_FPGA_UMAC_DFS_CTRL_MASK  0x00000C00                // FPGA_UMAC_DFS_CTRL[11..10]
#define CB_INFRA_MISC0_FPGA_MISC_CTRL_FPGA_UMAC_DFS_CTRL_SHFT  10
#define CB_INFRA_MISC0_FPGA_MISC_CTRL_FPGA_WFDMA_DFS_CTRL_ADDR CB_INFRA_MISC0_FPGA_MISC_CTRL_ADDR
#define CB_INFRA_MISC0_FPGA_MISC_CTRL_FPGA_WFDMA_DFS_CTRL_MASK 0x00000300                // FPGA_WFDMA_DFS_CTRL[9..8]
#define CB_INFRA_MISC0_FPGA_MISC_CTRL_FPGA_WFDMA_DFS_CTRL_SHFT 8
#define CB_INFRA_MISC0_FPGA_MISC_CTRL_FPGA_BUS_DFS_CTRL_ADDR   CB_INFRA_MISC0_FPGA_MISC_CTRL_ADDR
#define CB_INFRA_MISC0_FPGA_MISC_CTRL_FPGA_BUS_DFS_CTRL_MASK   0x00000080                // FPGA_BUS_DFS_CTRL[7]
#define CB_INFRA_MISC0_FPGA_MISC_CTRL_FPGA_BUS_DFS_CTRL_SHFT   7
#define CB_INFRA_MISC0_FPGA_MISC_CTRL_FPGA_CR_RSV_0_ADDR       CB_INFRA_MISC0_FPGA_MISC_CTRL_ADDR
#define CB_INFRA_MISC0_FPGA_MISC_CTRL_FPGA_CR_RSV_0_MASK       0x0000007C                // FPGA_CR_RSV_0[6..2]
#define CB_INFRA_MISC0_FPGA_MISC_CTRL_FPGA_CR_RSV_0_SHFT       2
#define CB_INFRA_MISC0_FPGA_MISC_CTRL_FPGA_DBG_SEL_ADDR        CB_INFRA_MISC0_FPGA_MISC_CTRL_ADDR
#define CB_INFRA_MISC0_FPGA_MISC_CTRL_FPGA_DBG_SEL_MASK        0x00000003                // FPGA_DBG_SEL[1..0]
#define CB_INFRA_MISC0_FPGA_MISC_CTRL_FPGA_DBG_SEL_SHFT        0

/* =====================================================================================

  ---BUS_CTL_RESERVED_A (0x70026000 + 0x400)---

    BUS_CTL_RSV_A[31..0]         - (RW)  xxx 

 =====================================================================================*/
#define CB_INFRA_MISC0_BUS_CTL_RESERVED_A_BUS_CTL_RSV_A_ADDR   CB_INFRA_MISC0_BUS_CTL_RESERVED_A_ADDR
#define CB_INFRA_MISC0_BUS_CTL_RESERVED_A_BUS_CTL_RSV_A_MASK   0xFFFFFFFF                // BUS_CTL_RSV_A[31..0]
#define CB_INFRA_MISC0_BUS_CTL_RESERVED_A_BUS_CTL_RSV_A_SHFT   0

/* =====================================================================================

  ---BUS_CTL_RESERVED_B (0x70026000 + 0x404)---

    BUS_CTL_RSV_B[31..0]         - (RW)  xxx 

 =====================================================================================*/
#define CB_INFRA_MISC0_BUS_CTL_RESERVED_B_BUS_CTL_RSV_B_ADDR   CB_INFRA_MISC0_BUS_CTL_RESERVED_B_ADDR
#define CB_INFRA_MISC0_BUS_CTL_RESERVED_B_BUS_CTL_RSV_B_MASK   0xFFFFFFFF                // BUS_CTL_RSV_B[31..0]
#define CB_INFRA_MISC0_BUS_CTL_RESERVED_B_BUS_CTL_RSV_B_SHFT   0

/* =====================================================================================

  ---CR_SLP_PROTECT_0 (0x70026000 + 0x420)---

    RESERVED0[7..0]              - (RO) Reserved bits
    CR_MMIO_SLP_PROTECT_EN[8]    - (RW)  xxx 
    CR_MMIO_SLP_PROTECT_SW_CTL[9] - (RW)  xxx 
    MMIO_SLP_PROTECT_IDLE[10]    - (RO)  xxx 
    MMIO_SLP_PROTECT_READY[11]   - (RO)  xxx 
    CR_MMIO_2_SLP_PROTECT_EN[12] - (RW)  xxx 
    CR_MMIO_2_SLP_PROTECT_SW_CTL[13] - (RW)  xxx 
    MMIO_2_SLP_PROTECT_IDLE[14]  - (RO)  xxx 
    MMIO_2_SLP_PROTECT_READY[15] - (RO)  xxx 
    RESERVED16[31..16]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_MISC0_CR_SLP_PROTECT_0_MMIO_2_SLP_PROTECT_READY_ADDR CB_INFRA_MISC0_CR_SLP_PROTECT_0_ADDR
#define CB_INFRA_MISC0_CR_SLP_PROTECT_0_MMIO_2_SLP_PROTECT_READY_MASK 0x00008000                // MMIO_2_SLP_PROTECT_READY[15]
#define CB_INFRA_MISC0_CR_SLP_PROTECT_0_MMIO_2_SLP_PROTECT_READY_SHFT 15
#define CB_INFRA_MISC0_CR_SLP_PROTECT_0_MMIO_2_SLP_PROTECT_IDLE_ADDR CB_INFRA_MISC0_CR_SLP_PROTECT_0_ADDR
#define CB_INFRA_MISC0_CR_SLP_PROTECT_0_MMIO_2_SLP_PROTECT_IDLE_MASK 0x00004000                // MMIO_2_SLP_PROTECT_IDLE[14]
#define CB_INFRA_MISC0_CR_SLP_PROTECT_0_MMIO_2_SLP_PROTECT_IDLE_SHFT 14
#define CB_INFRA_MISC0_CR_SLP_PROTECT_0_CR_MMIO_2_SLP_PROTECT_SW_CTL_ADDR CB_INFRA_MISC0_CR_SLP_PROTECT_0_ADDR
#define CB_INFRA_MISC0_CR_SLP_PROTECT_0_CR_MMIO_2_SLP_PROTECT_SW_CTL_MASK 0x00002000                // CR_MMIO_2_SLP_PROTECT_SW_CTL[13]
#define CB_INFRA_MISC0_CR_SLP_PROTECT_0_CR_MMIO_2_SLP_PROTECT_SW_CTL_SHFT 13
#define CB_INFRA_MISC0_CR_SLP_PROTECT_0_CR_MMIO_2_SLP_PROTECT_EN_ADDR CB_INFRA_MISC0_CR_SLP_PROTECT_0_ADDR
#define CB_INFRA_MISC0_CR_SLP_PROTECT_0_CR_MMIO_2_SLP_PROTECT_EN_MASK 0x00001000                // CR_MMIO_2_SLP_PROTECT_EN[12]
#define CB_INFRA_MISC0_CR_SLP_PROTECT_0_CR_MMIO_2_SLP_PROTECT_EN_SHFT 12
#define CB_INFRA_MISC0_CR_SLP_PROTECT_0_MMIO_SLP_PROTECT_READY_ADDR CB_INFRA_MISC0_CR_SLP_PROTECT_0_ADDR
#define CB_INFRA_MISC0_CR_SLP_PROTECT_0_MMIO_SLP_PROTECT_READY_MASK 0x00000800                // MMIO_SLP_PROTECT_READY[11]
#define CB_INFRA_MISC0_CR_SLP_PROTECT_0_MMIO_SLP_PROTECT_READY_SHFT 11
#define CB_INFRA_MISC0_CR_SLP_PROTECT_0_MMIO_SLP_PROTECT_IDLE_ADDR CB_INFRA_MISC0_CR_SLP_PROTECT_0_ADDR
#define CB_INFRA_MISC0_CR_SLP_PROTECT_0_MMIO_SLP_PROTECT_IDLE_MASK 0x00000400                // MMIO_SLP_PROTECT_IDLE[10]
#define CB_INFRA_MISC0_CR_SLP_PROTECT_0_MMIO_SLP_PROTECT_IDLE_SHFT 10
#define CB_INFRA_MISC0_CR_SLP_PROTECT_0_CR_MMIO_SLP_PROTECT_SW_CTL_ADDR CB_INFRA_MISC0_CR_SLP_PROTECT_0_ADDR
#define CB_INFRA_MISC0_CR_SLP_PROTECT_0_CR_MMIO_SLP_PROTECT_SW_CTL_MASK 0x00000200                // CR_MMIO_SLP_PROTECT_SW_CTL[9]
#define CB_INFRA_MISC0_CR_SLP_PROTECT_0_CR_MMIO_SLP_PROTECT_SW_CTL_SHFT 9
#define CB_INFRA_MISC0_CR_SLP_PROTECT_0_CR_MMIO_SLP_PROTECT_EN_ADDR CB_INFRA_MISC0_CR_SLP_PROTECT_0_ADDR
#define CB_INFRA_MISC0_CR_SLP_PROTECT_0_CR_MMIO_SLP_PROTECT_EN_MASK 0x00000100                // CR_MMIO_SLP_PROTECT_EN[8]
#define CB_INFRA_MISC0_CR_SLP_PROTECT_0_CR_MMIO_SLP_PROTECT_EN_SHFT 8

/* =====================================================================================

  ---CBTOP_LP_THROT_CTL (0x70026000 + 0x500)---

    CR_LP_THROT_AXIMTR_EN[0]     - (RW) It only influence timer for AXI traffic, irrelated to wf_mac_dis_lowpower.
    CR_LP_THROT_CK_CKEN[1]       - (RW) Clk on and off for lp_tjrottle.
    RESERVED2[3..2]              - (RO) Reserved bits
    CR_LP_THROT_AXI_L1PM_EN[4]   - (RW) Enable signal for axi monitor and it's about disable_lowpower.(L1PM)
    CR_LP_THROT_AXI_L0S_EN[5]    - (RW) Enable signal for axi monitor and it's about disable_lowpower.(L0S)
    CR_LP_THROT_WFMAC_L1PM_EN[6] - (RW) Enable signal for WFMAC and it's about disable_lowpower.(L1PM)
    CR_LP_THROT_WFMAC_L0S_EN[7]  - (RW) Enable signal for WFMAC and it's about disable_lowpower.(L0S)
    CR_CBTOP_PCIE_MTR_EN[8]      - (RW)  xxx 
    CR_CBTOP_PCIE_MTR_RST[9]     - (RW)  xxx 
    CR_CBTOP_PCIE_MTR_PAUSE[10]  - (RW)  xxx 
    CR_CBTOP_PCIE_MTR_TIME_TICK_EN[11] - (RW)  xxx 
    RESERVED12[15..12]           - (RO) Reserved bits
    CR_LP_THROT_CNT_CYCLE[27..16] - (RW) Set the number about the counter
    CR_LP_THROT_RSVD[31..28]     - (RW)  xxx 

 =====================================================================================*/
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_LP_THROT_RSVD_ADDR CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_LP_THROT_RSVD_MASK 0xF0000000                // CR_LP_THROT_RSVD[31..28]
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_LP_THROT_RSVD_SHFT 28
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_LP_THROT_CNT_CYCLE_ADDR CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_LP_THROT_CNT_CYCLE_MASK 0x0FFF0000                // CR_LP_THROT_CNT_CYCLE[27..16]
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_LP_THROT_CNT_CYCLE_SHFT 16
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_CBTOP_PCIE_MTR_TIME_TICK_EN_ADDR CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_CBTOP_PCIE_MTR_TIME_TICK_EN_MASK 0x00000800                // CR_CBTOP_PCIE_MTR_TIME_TICK_EN[11]
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_CBTOP_PCIE_MTR_TIME_TICK_EN_SHFT 11
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_CBTOP_PCIE_MTR_PAUSE_ADDR CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_CBTOP_PCIE_MTR_PAUSE_MASK 0x00000400                // CR_CBTOP_PCIE_MTR_PAUSE[10]
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_CBTOP_PCIE_MTR_PAUSE_SHFT 10
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_CBTOP_PCIE_MTR_RST_ADDR CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_CBTOP_PCIE_MTR_RST_MASK 0x00000200                // CR_CBTOP_PCIE_MTR_RST[9]
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_CBTOP_PCIE_MTR_RST_SHFT 9
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_CBTOP_PCIE_MTR_EN_ADDR CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_CBTOP_PCIE_MTR_EN_MASK 0x00000100                // CR_CBTOP_PCIE_MTR_EN[8]
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_CBTOP_PCIE_MTR_EN_SHFT 8
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_LP_THROT_WFMAC_L0S_EN_ADDR CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_LP_THROT_WFMAC_L0S_EN_MASK 0x00000080                // CR_LP_THROT_WFMAC_L0S_EN[7]
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_LP_THROT_WFMAC_L0S_EN_SHFT 7
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_LP_THROT_WFMAC_L1PM_EN_ADDR CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_LP_THROT_WFMAC_L1PM_EN_MASK 0x00000040                // CR_LP_THROT_WFMAC_L1PM_EN[6]
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_LP_THROT_WFMAC_L1PM_EN_SHFT 6
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_LP_THROT_AXI_L0S_EN_ADDR CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_LP_THROT_AXI_L0S_EN_MASK 0x00000020                // CR_LP_THROT_AXI_L0S_EN[5]
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_LP_THROT_AXI_L0S_EN_SHFT 5
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_LP_THROT_AXI_L1PM_EN_ADDR CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_LP_THROT_AXI_L1PM_EN_MASK 0x00000010                // CR_LP_THROT_AXI_L1PM_EN[4]
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_LP_THROT_AXI_L1PM_EN_SHFT 4
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_LP_THROT_CK_CKEN_ADDR CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_LP_THROT_CK_CKEN_MASK 0x00000002                // CR_LP_THROT_CK_CKEN[1]
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_LP_THROT_CK_CKEN_SHFT 1
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_LP_THROT_AXIMTR_EN_ADDR CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_LP_THROT_AXIMTR_EN_MASK 0x00000001                // CR_LP_THROT_AXIMTR_EN[0]
#define CB_INFRA_MISC0_CBTOP_LP_THROT_CTL_CR_LP_THROT_AXIMTR_EN_SHFT 0

/* =====================================================================================

  ---CBTOP_LP_THROT_AXI_MTR (0x70026000 + 0x504)---

    AP2CONN_AR_PENDING_COUNTER[3..0] - (RO)  xxx 
    RESERVED4[7..4]              - (RO) Reserved bits
    AP2CONN_Aw_PENDING_COUNTER[11..8] - (RO)  xxx 
    RESERVED12[15..12]           - (RO) Reserved bits
    CONN2AP_AR_PENDING_COUNTER[19..16] - (RO)  xxx 
    RESERVED20[23..20]           - (RO) Reserved bits
    CONN2AP_AW_PENDING_COUNTER[27..24] - (RO)  xxx 
    RESERVED28[31..28]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_MISC0_CBTOP_LP_THROT_AXI_MTR_CONN2AP_AW_PENDING_COUNTER_ADDR CB_INFRA_MISC0_CBTOP_LP_THROT_AXI_MTR_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_THROT_AXI_MTR_CONN2AP_AW_PENDING_COUNTER_MASK 0x0F000000                // CONN2AP_AW_PENDING_COUNTER[27..24]
#define CB_INFRA_MISC0_CBTOP_LP_THROT_AXI_MTR_CONN2AP_AW_PENDING_COUNTER_SHFT 24
#define CB_INFRA_MISC0_CBTOP_LP_THROT_AXI_MTR_CONN2AP_AR_PENDING_COUNTER_ADDR CB_INFRA_MISC0_CBTOP_LP_THROT_AXI_MTR_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_THROT_AXI_MTR_CONN2AP_AR_PENDING_COUNTER_MASK 0x000F0000                // CONN2AP_AR_PENDING_COUNTER[19..16]
#define CB_INFRA_MISC0_CBTOP_LP_THROT_AXI_MTR_CONN2AP_AR_PENDING_COUNTER_SHFT 16
#define CB_INFRA_MISC0_CBTOP_LP_THROT_AXI_MTR_AP2CONN_Aw_PENDING_COUNTER_ADDR CB_INFRA_MISC0_CBTOP_LP_THROT_AXI_MTR_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_THROT_AXI_MTR_AP2CONN_Aw_PENDING_COUNTER_MASK 0x00000F00                // AP2CONN_Aw_PENDING_COUNTER[11..8]
#define CB_INFRA_MISC0_CBTOP_LP_THROT_AXI_MTR_AP2CONN_Aw_PENDING_COUNTER_SHFT 8
#define CB_INFRA_MISC0_CBTOP_LP_THROT_AXI_MTR_AP2CONN_AR_PENDING_COUNTER_ADDR CB_INFRA_MISC0_CBTOP_LP_THROT_AXI_MTR_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_THROT_AXI_MTR_AP2CONN_AR_PENDING_COUNTER_MASK 0x0000000F                // AP2CONN_AR_PENDING_COUNTER[3..0]
#define CB_INFRA_MISC0_CBTOP_LP_THROT_AXI_MTR_AP2CONN_AR_PENDING_COUNTER_SHFT 0

/* =====================================================================================

  ---CBTOP_LP_THROT_TIME_TICK_CNT (0x70026000 + 0x508)---

    CR_LP_THROT_TIME_TICK_CNT[11..0] - (RW)  xxx 
    RESERVED12[31..12]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_MISC0_CBTOP_LP_THROT_TIME_TICK_CNT_CR_LP_THROT_TIME_TICK_CNT_ADDR CB_INFRA_MISC0_CBTOP_LP_THROT_TIME_TICK_CNT_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_THROT_TIME_TICK_CNT_CR_LP_THROT_TIME_TICK_CNT_MASK 0x00000FFF                // CR_LP_THROT_TIME_TICK_CNT[11..0]
#define CB_INFRA_MISC0_CBTOP_LP_THROT_TIME_TICK_CNT_CR_LP_THROT_TIME_TICK_CNT_SHFT 0

/* =====================================================================================

  ---CBTOP_LP_THROT_STATUS (0x70026000 + 0x50C)---

    PEXTP_MAC_DIS_LOWPOWER[1..0] - (RO)  xxx 
    RESERVED2[3..2]              - (RO) Reserved bits
    AP2CONN_AXI_BUSY[4]          - (RO)  xxx 
    CONN2AP_AXI_BUSY[5]          - (RO)  xxx 
    WF_MAC_DIS_LOWPOWER[6]       - (RO)  xxx 
    LP_THROT_ACTIVE[7]           - (RO)  xxx 
    CNT_32K_EN[8]                - (RO)  xxx 
    CNT_32K_CLR[9]               - (RO)  xxx 
    RESERVED10[11..10]           - (RO) Reserved bits
    CNT_CLR_AFIFO_REMPTY[12]     - (RO)  xxx 
    DIS_CLR_AFIFO_WFULL[13]      - (RO)  xxx 
    RESERVED14[15..14]           - (RO) Reserved bits
    PEXTP_MAC_POWER_STATE[22..16] - (RO)  xxx 
    RESERVED23[23]               - (RO) Reserved bits
    PEXTP_MAC_SLEEP[24]          - (RO)  xxx 
    PEXTP_MAC_ACTIVE[25]         - (RO)  xxx 
    RESERVED26[27..26]           - (RO) Reserved bits
    CBTOP_PCIE_NRM_REQ[28]       - (RO)  xxx 
    CBTOP_PCIE_NRM_ACK[29]       - (RO)  xxx 
    RESERVED30[31..30]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_CBTOP_PCIE_NRM_ACK_ADDR CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_CBTOP_PCIE_NRM_ACK_MASK 0x20000000                // CBTOP_PCIE_NRM_ACK[29]
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_CBTOP_PCIE_NRM_ACK_SHFT 29
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_CBTOP_PCIE_NRM_REQ_ADDR CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_CBTOP_PCIE_NRM_REQ_MASK 0x10000000                // CBTOP_PCIE_NRM_REQ[28]
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_CBTOP_PCIE_NRM_REQ_SHFT 28
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_PEXTP_MAC_ACTIVE_ADDR CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_PEXTP_MAC_ACTIVE_MASK 0x02000000                // PEXTP_MAC_ACTIVE[25]
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_PEXTP_MAC_ACTIVE_SHFT 25
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_PEXTP_MAC_SLEEP_ADDR CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_PEXTP_MAC_SLEEP_MASK 0x01000000                // PEXTP_MAC_SLEEP[24]
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_PEXTP_MAC_SLEEP_SHFT 24
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_PEXTP_MAC_POWER_STATE_ADDR CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_PEXTP_MAC_POWER_STATE_MASK 0x007F0000                // PEXTP_MAC_POWER_STATE[22..16]
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_PEXTP_MAC_POWER_STATE_SHFT 16
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_DIS_CLR_AFIFO_WFULL_ADDR CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_DIS_CLR_AFIFO_WFULL_MASK 0x00002000                // DIS_CLR_AFIFO_WFULL[13]
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_DIS_CLR_AFIFO_WFULL_SHFT 13
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_CNT_CLR_AFIFO_REMPTY_ADDR CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_CNT_CLR_AFIFO_REMPTY_MASK 0x00001000                // CNT_CLR_AFIFO_REMPTY[12]
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_CNT_CLR_AFIFO_REMPTY_SHFT 12
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_CNT_32K_CLR_ADDR  CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_CNT_32K_CLR_MASK  0x00000200                // CNT_32K_CLR[9]
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_CNT_32K_CLR_SHFT  9
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_CNT_32K_EN_ADDR   CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_CNT_32K_EN_MASK   0x00000100                // CNT_32K_EN[8]
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_CNT_32K_EN_SHFT   8
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_LP_THROT_ACTIVE_ADDR CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_LP_THROT_ACTIVE_MASK 0x00000080                // LP_THROT_ACTIVE[7]
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_LP_THROT_ACTIVE_SHFT 7
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_WF_MAC_DIS_LOWPOWER_ADDR CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_WF_MAC_DIS_LOWPOWER_MASK 0x00000040                // WF_MAC_DIS_LOWPOWER[6]
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_WF_MAC_DIS_LOWPOWER_SHFT 6
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_CONN2AP_AXI_BUSY_ADDR CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_CONN2AP_AXI_BUSY_MASK 0x00000020                // CONN2AP_AXI_BUSY[5]
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_CONN2AP_AXI_BUSY_SHFT 5
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_AP2CONN_AXI_BUSY_ADDR CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_AP2CONN_AXI_BUSY_MASK 0x00000010                // AP2CONN_AXI_BUSY[4]
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_AP2CONN_AXI_BUSY_SHFT 4
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_PEXTP_MAC_DIS_LOWPOWER_ADDR CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_PEXTP_MAC_DIS_LOWPOWER_MASK 0x00000003                // PEXTP_MAC_DIS_LOWPOWER[1..0]
#define CB_INFRA_MISC0_CBTOP_LP_THROT_STATUS_PEXTP_MAC_DIS_LOWPOWER_SHFT 0

/* =====================================================================================

  ---CBTOP_PCIE_BUS_STATUS_0 (0x70026000 + 0x510)---

    REQ_AVG_LAT[9..0]            - (RO)  xxx 
    REQ_PEAK_LAT[19..10]         - (RO)  xxx 
    REQ_LAT[29..20]              - (RO) {Recovery, L2, L1.2, L1.1, L1PM }
    RESERVED30[31..30]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_MISC0_CBTOP_PCIE_BUS_STATUS_0_REQ_LAT_ADDR    CB_INFRA_MISC0_CBTOP_PCIE_BUS_STATUS_0_ADDR
#define CB_INFRA_MISC0_CBTOP_PCIE_BUS_STATUS_0_REQ_LAT_MASK    0x3FF00000                // REQ_LAT[29..20]
#define CB_INFRA_MISC0_CBTOP_PCIE_BUS_STATUS_0_REQ_LAT_SHFT    20
#define CB_INFRA_MISC0_CBTOP_PCIE_BUS_STATUS_0_REQ_PEAK_LAT_ADDR CB_INFRA_MISC0_CBTOP_PCIE_BUS_STATUS_0_ADDR
#define CB_INFRA_MISC0_CBTOP_PCIE_BUS_STATUS_0_REQ_PEAK_LAT_MASK 0x000FFC00                // REQ_PEAK_LAT[19..10]
#define CB_INFRA_MISC0_CBTOP_PCIE_BUS_STATUS_0_REQ_PEAK_LAT_SHFT 10
#define CB_INFRA_MISC0_CBTOP_PCIE_BUS_STATUS_0_REQ_AVG_LAT_ADDR CB_INFRA_MISC0_CBTOP_PCIE_BUS_STATUS_0_ADDR
#define CB_INFRA_MISC0_CBTOP_PCIE_BUS_STATUS_0_REQ_AVG_LAT_MASK 0x000003FF                // REQ_AVG_LAT[9..0]
#define CB_INFRA_MISC0_CBTOP_PCIE_BUS_STATUS_0_REQ_AVG_LAT_SHFT 0

/* =====================================================================================

  ---CBTOP_PCIE_BUS_STATUS_1 (0x70026000 + 0x514)---

    ACK_AVG_LAT[9..0]            - (RO)  xxx 
    ACK_PEAK_LAT[19..10]         - (RO)  xxx 
    ACK_LAT[29..20]              - (RO) { L0s, L0 }
    RESERVED30[31..30]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_MISC0_CBTOP_PCIE_BUS_STATUS_1_ACK_LAT_ADDR    CB_INFRA_MISC0_CBTOP_PCIE_BUS_STATUS_1_ADDR
#define CB_INFRA_MISC0_CBTOP_PCIE_BUS_STATUS_1_ACK_LAT_MASK    0x3FF00000                // ACK_LAT[29..20]
#define CB_INFRA_MISC0_CBTOP_PCIE_BUS_STATUS_1_ACK_LAT_SHFT    20
#define CB_INFRA_MISC0_CBTOP_PCIE_BUS_STATUS_1_ACK_PEAK_LAT_ADDR CB_INFRA_MISC0_CBTOP_PCIE_BUS_STATUS_1_ADDR
#define CB_INFRA_MISC0_CBTOP_PCIE_BUS_STATUS_1_ACK_PEAK_LAT_MASK 0x000FFC00                // ACK_PEAK_LAT[19..10]
#define CB_INFRA_MISC0_CBTOP_PCIE_BUS_STATUS_1_ACK_PEAK_LAT_SHFT 10
#define CB_INFRA_MISC0_CBTOP_PCIE_BUS_STATUS_1_ACK_AVG_LAT_ADDR CB_INFRA_MISC0_CBTOP_PCIE_BUS_STATUS_1_ADDR
#define CB_INFRA_MISC0_CBTOP_PCIE_BUS_STATUS_1_ACK_AVG_LAT_MASK 0x000003FF                // ACK_AVG_LAT[9..0]
#define CB_INFRA_MISC0_CBTOP_PCIE_BUS_STATUS_1_ACK_AVG_LAT_SHFT 0

/* =====================================================================================

  ---CBTOP_FREQ_METER_DET_CTL (0x70026000 + 0x540)---

    DET_CNT_CYCLE[2..0]          - (RW) reference cycle count  by 32KHz, count range = 1 ~ 6
    DET_EN[3]                    - (RW) detection enable
                                     1'h0: disable
                                     1'h1: enable
    FREQ_METER_CAL_CK_CKEN[4]    - (RW) clock gating of freq meter target clock
    FREQ_METER_CAL_CK_MUX_CKSEL[7..5] - (RW) To select freq meter target clock:
                                     2'b00: hclk_ck
                                     2'b01: osc_ck
                                     2'b10: mcu_cal_ck
    FREQ_METER_RSVD[15..8]       - (RW)  xxx 
    RESERVED16[31..16]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_MISC0_CBTOP_FREQ_METER_DET_CTL_FREQ_METER_RSVD_ADDR CB_INFRA_MISC0_CBTOP_FREQ_METER_DET_CTL_ADDR
#define CB_INFRA_MISC0_CBTOP_FREQ_METER_DET_CTL_FREQ_METER_RSVD_MASK 0x0000FF00                // FREQ_METER_RSVD[15..8]
#define CB_INFRA_MISC0_CBTOP_FREQ_METER_DET_CTL_FREQ_METER_RSVD_SHFT 8
#define CB_INFRA_MISC0_CBTOP_FREQ_METER_DET_CTL_FREQ_METER_CAL_CK_MUX_CKSEL_ADDR CB_INFRA_MISC0_CBTOP_FREQ_METER_DET_CTL_ADDR
#define CB_INFRA_MISC0_CBTOP_FREQ_METER_DET_CTL_FREQ_METER_CAL_CK_MUX_CKSEL_MASK 0x000000E0                // FREQ_METER_CAL_CK_MUX_CKSEL[7..5]
#define CB_INFRA_MISC0_CBTOP_FREQ_METER_DET_CTL_FREQ_METER_CAL_CK_MUX_CKSEL_SHFT 5
#define CB_INFRA_MISC0_CBTOP_FREQ_METER_DET_CTL_FREQ_METER_CAL_CK_CKEN_ADDR CB_INFRA_MISC0_CBTOP_FREQ_METER_DET_CTL_ADDR
#define CB_INFRA_MISC0_CBTOP_FREQ_METER_DET_CTL_FREQ_METER_CAL_CK_CKEN_MASK 0x00000010                // FREQ_METER_CAL_CK_CKEN[4]
#define CB_INFRA_MISC0_CBTOP_FREQ_METER_DET_CTL_FREQ_METER_CAL_CK_CKEN_SHFT 4
#define CB_INFRA_MISC0_CBTOP_FREQ_METER_DET_CTL_DET_EN_ADDR    CB_INFRA_MISC0_CBTOP_FREQ_METER_DET_CTL_ADDR
#define CB_INFRA_MISC0_CBTOP_FREQ_METER_DET_CTL_DET_EN_MASK    0x00000008                // DET_EN[3]
#define CB_INFRA_MISC0_CBTOP_FREQ_METER_DET_CTL_DET_EN_SHFT    3
#define CB_INFRA_MISC0_CBTOP_FREQ_METER_DET_CTL_DET_CNT_CYCLE_ADDR CB_INFRA_MISC0_CBTOP_FREQ_METER_DET_CTL_ADDR
#define CB_INFRA_MISC0_CBTOP_FREQ_METER_DET_CTL_DET_CNT_CYCLE_MASK 0x00000007                // DET_CNT_CYCLE[2..0]
#define CB_INFRA_MISC0_CBTOP_FREQ_METER_DET_CTL_DET_CNT_CYCLE_SHFT 0

/* =====================================================================================

  ---CBTOP_FREQ_METER_STATUS (0x70026000 + 0x54C)---

    DET_VLD[0]                   - (RO) calculation clock detection done indicator
                                     1'h0 = detection is not completed
                                     1'h1 = detection is completed
    RESERVED1[7..1]              - (RO) Reserved bits
    DET_DBG[15..8]               - (RO)  xxx 
    DET_CAL_COUNTER[31..16]      - (RO) calculation cycle count  by calculation clock

 =====================================================================================*/
#define CB_INFRA_MISC0_CBTOP_FREQ_METER_STATUS_DET_CAL_COUNTER_ADDR CB_INFRA_MISC0_CBTOP_FREQ_METER_STATUS_ADDR
#define CB_INFRA_MISC0_CBTOP_FREQ_METER_STATUS_DET_CAL_COUNTER_MASK 0xFFFF0000                // DET_CAL_COUNTER[31..16]
#define CB_INFRA_MISC0_CBTOP_FREQ_METER_STATUS_DET_CAL_COUNTER_SHFT 16
#define CB_INFRA_MISC0_CBTOP_FREQ_METER_STATUS_DET_DBG_ADDR    CB_INFRA_MISC0_CBTOP_FREQ_METER_STATUS_ADDR
#define CB_INFRA_MISC0_CBTOP_FREQ_METER_STATUS_DET_DBG_MASK    0x0000FF00                // DET_DBG[15..8]
#define CB_INFRA_MISC0_CBTOP_FREQ_METER_STATUS_DET_DBG_SHFT    8
#define CB_INFRA_MISC0_CBTOP_FREQ_METER_STATUS_DET_VLD_ADDR    CB_INFRA_MISC0_CBTOP_FREQ_METER_STATUS_ADDR
#define CB_INFRA_MISC0_CBTOP_FREQ_METER_STATUS_DET_VLD_MASK    0x00000001                // DET_VLD[0]
#define CB_INFRA_MISC0_CBTOP_FREQ_METER_STATUS_DET_VLD_SHFT    0

/* =====================================================================================

  ---CBTOP_DEBUG_SEL (0x70026000 + 0x550)---

    reg_sel_0[7..0]              - (RW) select different debug port
    reg_sel_1[15..8]             - (RW) select different debug port

 =====================================================================================*/
#define CB_INFRA_MISC0_CBTOP_DEBUG_SEL_reg_sel_1_ADDR          CB_INFRA_MISC0_CBTOP_DEBUG_SEL_ADDR
#define CB_INFRA_MISC0_CBTOP_DEBUG_SEL_reg_sel_1_MASK          0x0000FF00                // reg_sel_1[15..8]
#define CB_INFRA_MISC0_CBTOP_DEBUG_SEL_reg_sel_1_SHFT          8
#define CB_INFRA_MISC0_CBTOP_DEBUG_SEL_reg_sel_0_ADDR          CB_INFRA_MISC0_CBTOP_DEBUG_SEL_ADDR
#define CB_INFRA_MISC0_CBTOP_DEBUG_SEL_reg_sel_0_MASK          0x000000FF                // reg_sel_0[7..0]
#define CB_INFRA_MISC0_CBTOP_DEBUG_SEL_reg_sel_0_SHFT          0

/* =====================================================================================

  ---CBTOP_PCIE_REMAP_WF (0x70026000 + 0x554)---

    pcie_remap_wf_rg0[15..0]     - (RW) Remapping register (wf_rg0)
    pcie_remap_wf_rg1[31..16]    - (RW) Remapping register (wf_rg1)

 =====================================================================================*/
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_pcie_remap_wf_rg1_ADDR CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_ADDR
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_pcie_remap_wf_rg1_MASK 0xFFFF0000                // pcie_remap_wf_rg1[31..16]
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_pcie_remap_wf_rg1_SHFT 16
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_pcie_remap_wf_rg0_ADDR CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_ADDR
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_pcie_remap_wf_rg0_MASK 0x0000FFFF                // pcie_remap_wf_rg0[15..0]
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_pcie_remap_wf_rg0_SHFT 0

/* =====================================================================================

  ---CBTOP_PCIE_REMAP_WF_BT (0x70026000 + 0x558)---

    pcie_remap_wf_rg2[15..0]     - (RW) Remapping register (wf_rg2)
    pcie_remap_bt_rg0[31..16]    - (RW) Remapping register (bt_rg0)

 =====================================================================================*/
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_BT_pcie_remap_bt_rg0_ADDR CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_BT_ADDR
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_BT_pcie_remap_bt_rg0_MASK 0xFFFF0000                // pcie_remap_bt_rg0[31..16]
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_BT_pcie_remap_bt_rg0_SHFT 16
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_BT_pcie_remap_wf_rg2_ADDR CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_BT_ADDR
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_BT_pcie_remap_wf_rg2_MASK 0x0000FFFF                // pcie_remap_wf_rg2[15..0]
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_BT_pcie_remap_wf_rg2_SHFT 0

/* =====================================================================================

  ---CBTOP_PCIE_REMAP_BT (0x70026000 + 0x55C)---

    pcie_remap_bt_rg1[15..0]     - (RW) Remapping register (bt_rg1)
    pcie_remap_bt_rg2[31..16]    - (RW) Remapping register (bt_rg2)

 =====================================================================================*/
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_BT_pcie_remap_bt_rg2_ADDR CB_INFRA_MISC0_CBTOP_PCIE_REMAP_BT_ADDR
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_BT_pcie_remap_bt_rg2_MASK 0xFFFF0000                // pcie_remap_bt_rg2[31..16]
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_BT_pcie_remap_bt_rg2_SHFT 16
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_BT_pcie_remap_bt_rg1_ADDR CB_INFRA_MISC0_CBTOP_PCIE_REMAP_BT_ADDR
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_BT_pcie_remap_bt_rg1_MASK 0x0000FFFF                // pcie_remap_bt_rg1[15..0]
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_BT_pcie_remap_bt_rg1_SHFT 0

/* =====================================================================================

  ---CBTOP_PCIE_REMAP_WF_2 (0x70026000 + 0x560)---

    pcie_remap_wf_rg0_2[15..0]   - (RW) Remapping register (wf_rg0)
    pcie_remap_wf_rg1_2[31..16]  - (RW) Remapping register (wf_rg1)

 =====================================================================================*/
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_2_pcie_remap_wf_rg1_2_ADDR CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_2_ADDR
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_2_pcie_remap_wf_rg1_2_MASK 0xFFFF0000                // pcie_remap_wf_rg1_2[31..16]
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_2_pcie_remap_wf_rg1_2_SHFT 16
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_2_pcie_remap_wf_rg0_2_ADDR CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_2_ADDR
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_2_pcie_remap_wf_rg0_2_MASK 0x0000FFFF                // pcie_remap_wf_rg0_2[15..0]
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_2_pcie_remap_wf_rg0_2_SHFT 0

/* =====================================================================================

  ---CBTOP_PCIE_REMAP_WF_BT_2 (0x70026000 + 0x564)---

    pcie_remap_wf_rg2_2[15..0]   - (RW) Remapping register (wf_rg2)
    pcie_remap_bt_rg0_2[31..16]  - (RW) Remapping register (bt_rg0)

 =====================================================================================*/
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_BT_2_pcie_remap_bt_rg0_2_ADDR CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_BT_2_ADDR
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_BT_2_pcie_remap_bt_rg0_2_MASK 0xFFFF0000                // pcie_remap_bt_rg0_2[31..16]
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_BT_2_pcie_remap_bt_rg0_2_SHFT 16
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_BT_2_pcie_remap_wf_rg2_2_ADDR CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_BT_2_ADDR
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_BT_2_pcie_remap_wf_rg2_2_MASK 0x0000FFFF                // pcie_remap_wf_rg2_2[15..0]
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_BT_2_pcie_remap_wf_rg2_2_SHFT 0

/* =====================================================================================

  ---CBTOP_PCIE_REMAP_BT_2 (0x70026000 + 0x568)---

    pcie_remap_bt_rg1_2[15..0]   - (RW) Remapping register (bt_rg1)
    pcie_remap_bt_rg2_2[31..16]  - (RW) Remapping register (bt_rg2)

 =====================================================================================*/
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_BT_2_pcie_remap_bt_rg2_2_ADDR CB_INFRA_MISC0_CBTOP_PCIE_REMAP_BT_2_ADDR
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_BT_2_pcie_remap_bt_rg2_2_MASK 0xFFFF0000                // pcie_remap_bt_rg2_2[31..16]
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_BT_2_pcie_remap_bt_rg2_2_SHFT 16
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_BT_2_pcie_remap_bt_rg1_2_ADDR CB_INFRA_MISC0_CBTOP_PCIE_REMAP_BT_2_ADDR
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_BT_2_pcie_remap_bt_rg1_2_MASK 0x0000FFFF                // pcie_remap_bt_rg1_2[15..0]
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_BT_2_pcie_remap_bt_rg1_2_SHFT 0

/* =====================================================================================

  ---CBTOP_OFF_DBG_MUX (0x70026000 + 0X700)---

    CBTOP_OFF_DBG_SEL[31..0]     - (RW)  xxx 

 =====================================================================================*/
#define CB_INFRA_MISC0_CBTOP_OFF_DBG_MUX_CBTOP_OFF_DBG_SEL_ADDR CB_INFRA_MISC0_CBTOP_OFF_DBG_MUX_ADDR
#define CB_INFRA_MISC0_CBTOP_OFF_DBG_MUX_CBTOP_OFF_DBG_SEL_MASK 0xFFFFFFFF                // CBTOP_OFF_DBG_SEL[31..0]
#define CB_INFRA_MISC0_CBTOP_OFF_DBG_MUX_CBTOP_OFF_DBG_SEL_SHFT 0

/* =====================================================================================

  ---AP2CONN_GALS_VIO_ADDRESS (0x70026000 + 0X704)---

    AP2CONN_GALS_VIO_ADDR[31..0] - (RO)  xxx 

 =====================================================================================*/
#define CB_INFRA_MISC0_AP2CONN_GALS_VIO_ADDRESS_AP2CONN_GALS_VIO_ADDR_ADDR CB_INFRA_MISC0_AP2CONN_GALS_VIO_ADDRESS_ADDR
#define CB_INFRA_MISC0_AP2CONN_GALS_VIO_ADDRESS_AP2CONN_GALS_VIO_ADDR_MASK 0xFFFFFFFF                // AP2CONN_GALS_VIO_ADDR[31..0]
#define CB_INFRA_MISC0_AP2CONN_GALS_VIO_ADDRESS_AP2CONN_GALS_VIO_ADDR_SHFT 0

/* =====================================================================================

  ---CONN2AP_X2H_VIO_ADDRESS (0x70026000 + 0x708)---

    CONN2AP_X2H_VIO_ADDR[31..0]  - (RO)  xxx 

 =====================================================================================*/
#define CB_INFRA_MISC0_CONN2AP_X2H_VIO_ADDRESS_CONN2AP_X2H_VIO_ADDR_ADDR CB_INFRA_MISC0_CONN2AP_X2H_VIO_ADDRESS_ADDR
#define CB_INFRA_MISC0_CONN2AP_X2H_VIO_ADDRESS_CONN2AP_X2H_VIO_ADDR_MASK 0xFFFFFFFF                // CONN2AP_X2H_VIO_ADDR[31..0]
#define CB_INFRA_MISC0_CONN2AP_X2H_VIO_ADDRESS_CONN2AP_X2H_VIO_ADDR_SHFT 0

/* =====================================================================================

  ---AP2CONN_X2H_VIO_ADDRESS (0x70026000 + 0X70C)---

    AP2CONN_X2H_VIO_ADDR[31..0]  - (RO)  xxx 

 =====================================================================================*/
#define CB_INFRA_MISC0_AP2CONN_X2H_VIO_ADDRESS_AP2CONN_X2H_VIO_ADDR_ADDR CB_INFRA_MISC0_AP2CONN_X2H_VIO_ADDRESS_ADDR
#define CB_INFRA_MISC0_AP2CONN_X2H_VIO_ADDRESS_AP2CONN_X2H_VIO_ADDR_MASK 0xFFFFFFFF                // AP2CONN_X2H_VIO_ADDR[31..0]
#define CB_INFRA_MISC0_AP2CONN_X2H_VIO_ADDRESS_AP2CONN_X2H_VIO_ADDR_SHFT 0

/* =====================================================================================

  ---SDIO_CTL2WRAP_AHB_GALS_MST (0x70026000 + 0x800)---

    cr_sdio_gals_mst_postwrite_dis[0] - (RW)  xxx 
    cr_sdio_gals_mst_protect_en[1] - (RW)  xxx 
    cr_sdio_gals_mst_error_flag_en[2] - (RW)  xxx 
    cr_sdio_gals_mst_rg_monitor_mode[3] - (RW)  xxx 
    cr_sdio_gals_mst_rg_cmd_cnt_clr[4] - (RW)  xxx 
    RESERVED5[31..5]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_MISC0_SDIO_CTL2WRAP_AHB_GALS_MST_cr_sdio_gals_mst_rg_cmd_cnt_clr_ADDR CB_INFRA_MISC0_SDIO_CTL2WRAP_AHB_GALS_MST_ADDR
#define CB_INFRA_MISC0_SDIO_CTL2WRAP_AHB_GALS_MST_cr_sdio_gals_mst_rg_cmd_cnt_clr_MASK 0x00000010                // cr_sdio_gals_mst_rg_cmd_cnt_clr[4]
#define CB_INFRA_MISC0_SDIO_CTL2WRAP_AHB_GALS_MST_cr_sdio_gals_mst_rg_cmd_cnt_clr_SHFT 4
#define CB_INFRA_MISC0_SDIO_CTL2WRAP_AHB_GALS_MST_cr_sdio_gals_mst_rg_monitor_mode_ADDR CB_INFRA_MISC0_SDIO_CTL2WRAP_AHB_GALS_MST_ADDR
#define CB_INFRA_MISC0_SDIO_CTL2WRAP_AHB_GALS_MST_cr_sdio_gals_mst_rg_monitor_mode_MASK 0x00000008                // cr_sdio_gals_mst_rg_monitor_mode[3]
#define CB_INFRA_MISC0_SDIO_CTL2WRAP_AHB_GALS_MST_cr_sdio_gals_mst_rg_monitor_mode_SHFT 3
#define CB_INFRA_MISC0_SDIO_CTL2WRAP_AHB_GALS_MST_cr_sdio_gals_mst_error_flag_en_ADDR CB_INFRA_MISC0_SDIO_CTL2WRAP_AHB_GALS_MST_ADDR
#define CB_INFRA_MISC0_SDIO_CTL2WRAP_AHB_GALS_MST_cr_sdio_gals_mst_error_flag_en_MASK 0x00000004                // cr_sdio_gals_mst_error_flag_en[2]
#define CB_INFRA_MISC0_SDIO_CTL2WRAP_AHB_GALS_MST_cr_sdio_gals_mst_error_flag_en_SHFT 2
#define CB_INFRA_MISC0_SDIO_CTL2WRAP_AHB_GALS_MST_cr_sdio_gals_mst_protect_en_ADDR CB_INFRA_MISC0_SDIO_CTL2WRAP_AHB_GALS_MST_ADDR
#define CB_INFRA_MISC0_SDIO_CTL2WRAP_AHB_GALS_MST_cr_sdio_gals_mst_protect_en_MASK 0x00000002                // cr_sdio_gals_mst_protect_en[1]
#define CB_INFRA_MISC0_SDIO_CTL2WRAP_AHB_GALS_MST_cr_sdio_gals_mst_protect_en_SHFT 1
#define CB_INFRA_MISC0_SDIO_CTL2WRAP_AHB_GALS_MST_cr_sdio_gals_mst_postwrite_dis_ADDR CB_INFRA_MISC0_SDIO_CTL2WRAP_AHB_GALS_MST_ADDR
#define CB_INFRA_MISC0_SDIO_CTL2WRAP_AHB_GALS_MST_cr_sdio_gals_mst_postwrite_dis_MASK 0x00000001                // cr_sdio_gals_mst_postwrite_dis[0]
#define CB_INFRA_MISC0_SDIO_CTL2WRAP_AHB_GALS_MST_cr_sdio_gals_mst_postwrite_dis_SHFT 0

/* =====================================================================================

  ---AP2CONN_AHB_BIST_TX_CTL (0x70026000 + 0xA00)---

    AP2CONN_AHB_GALS_BIST_TX_BIST_EN[0] - (RW) BIST enable signal of master side partition
    AP2CONN_AHB_GALS_BIST_TX_BIST_DONE[1] - (RO) BIST test finish signal of master side partition
    AP2CONN_AHB_GALS_BIST_TX_BIST_FAIL[2] - (RO) BIST test fail signal of master side partition
    RESERVED3[3]                 - (RO) Reserved bits
    AP2CONN_AHB_GALS_BIST_TX_HADDR_EN[5..4] - (RW) burst initial address enable/disalbe (1'b1: enable / 1'b0: disable)
                                     [1]: initial address pattern 0xFFFFFFC0
                                     [0]: initial address pattern 0x00000000
    AP2CONN_AHB_GALS_BIST_TX_HSIZE_EN[8..6] - (RW) hsize pattern enable/disalbe (1'b1: enable / 1'b0: disable)
                                     [2]: hsize pattern 2'b10 (word)
                                     [1]: hsize pattern 2'b01 (half word)
                                     [0]: hsize pattern 2'b00 (byte)
    AP2CONN_AHB_GALS_BIST_TX_HBURST_EN[12..9] - (RW) hburst pattern enable/disalbe (1'b1: enable / 1'b0: disable)
                                     [3]: hburst pattern 3'b111 (INCR16)
                                     [2]: hburst pattern 3'b101 (INCR8)
                                     [1]: hburst pattern 3'b010 (WRAP4)
                                     [0]: hburst pattern 3'b000 (SINGLE)
    AP2CONN_AHB_GALS_BIST_TX_HPROT_EN[14..13] - (RW) hprot pattern enable/disalbe (1'b1: enable / 1'b0: disable)
                                     [1]: hprot pattern 4'b1111
                                     [0]: hprot pattern 4'b0000
    AP2CONN_AHB_GALS_BIST_TX_DATA_EN[18..15] - (RW) hwdata & hwstrb & hrdata pattern enable/disalbe (1'b1: enable / 1'b0: disable)
                                     [3]: data pattern 0x0/0xffffffff alternates every beat
                                     [2]: data pattern 0x55555555/0xaaaaaaaa alternates every beat
                                     [1]: data pattern 0xffffffff
                                     [0]: data pattern 0x0
                                     hwstrb pattern is same as data pattern except bit width
    AP2CONN_AHB_GALS_BIST_TX_WR_RD_EN[20..19] - (RW) hwrite pattern enable/disalbe (1'b1: enable / 1'b0: disable)
                                     [1]: write pattern enable/disalbe
                                     [0]: read pattern enable/disalbe
    AP2CONN_AHB_GALS_BIST_TX_SIDEBAND_EN[22..21] - (RW) sideband & QOS signal pattern enable/disalbe (1'b1: enable / 1'b0: disable)
                                     [1]: sideband & hsecure_b & QOS pattern all 1 enable/disalbe 
                                     [0]: sideband & hsecure_b & QOS pattern all 0 enable/disalbe
    RESERVED23[31..23]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_AP2CONN_AHB_GALS_BIST_TX_SIDEBAND_EN_ADDR CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_ADDR
#define CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_AP2CONN_AHB_GALS_BIST_TX_SIDEBAND_EN_MASK 0x00600000                // AP2CONN_AHB_GALS_BIST_TX_SIDEBAND_EN[22..21]
#define CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_AP2CONN_AHB_GALS_BIST_TX_SIDEBAND_EN_SHFT 21
#define CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_AP2CONN_AHB_GALS_BIST_TX_WR_RD_EN_ADDR CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_ADDR
#define CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_AP2CONN_AHB_GALS_BIST_TX_WR_RD_EN_MASK 0x00180000                // AP2CONN_AHB_GALS_BIST_TX_WR_RD_EN[20..19]
#define CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_AP2CONN_AHB_GALS_BIST_TX_WR_RD_EN_SHFT 19
#define CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_AP2CONN_AHB_GALS_BIST_TX_DATA_EN_ADDR CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_ADDR
#define CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_AP2CONN_AHB_GALS_BIST_TX_DATA_EN_MASK 0x00078000                // AP2CONN_AHB_GALS_BIST_TX_DATA_EN[18..15]
#define CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_AP2CONN_AHB_GALS_BIST_TX_DATA_EN_SHFT 15
#define CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_AP2CONN_AHB_GALS_BIST_TX_HPROT_EN_ADDR CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_ADDR
#define CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_AP2CONN_AHB_GALS_BIST_TX_HPROT_EN_MASK 0x00006000                // AP2CONN_AHB_GALS_BIST_TX_HPROT_EN[14..13]
#define CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_AP2CONN_AHB_GALS_BIST_TX_HPROT_EN_SHFT 13
#define CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_AP2CONN_AHB_GALS_BIST_TX_HBURST_EN_ADDR CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_ADDR
#define CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_AP2CONN_AHB_GALS_BIST_TX_HBURST_EN_MASK 0x00001E00                // AP2CONN_AHB_GALS_BIST_TX_HBURST_EN[12..9]
#define CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_AP2CONN_AHB_GALS_BIST_TX_HBURST_EN_SHFT 9
#define CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_AP2CONN_AHB_GALS_BIST_TX_HSIZE_EN_ADDR CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_ADDR
#define CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_AP2CONN_AHB_GALS_BIST_TX_HSIZE_EN_MASK 0x000001C0                // AP2CONN_AHB_GALS_BIST_TX_HSIZE_EN[8..6]
#define CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_AP2CONN_AHB_GALS_BIST_TX_HSIZE_EN_SHFT 6
#define CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_AP2CONN_AHB_GALS_BIST_TX_HADDR_EN_ADDR CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_ADDR
#define CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_AP2CONN_AHB_GALS_BIST_TX_HADDR_EN_MASK 0x00000030                // AP2CONN_AHB_GALS_BIST_TX_HADDR_EN[5..4]
#define CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_AP2CONN_AHB_GALS_BIST_TX_HADDR_EN_SHFT 4
#define CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_AP2CONN_AHB_GALS_BIST_TX_BIST_FAIL_ADDR CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_ADDR
#define CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_AP2CONN_AHB_GALS_BIST_TX_BIST_FAIL_MASK 0x00000004                // AP2CONN_AHB_GALS_BIST_TX_BIST_FAIL[2]
#define CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_AP2CONN_AHB_GALS_BIST_TX_BIST_FAIL_SHFT 2
#define CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_AP2CONN_AHB_GALS_BIST_TX_BIST_DONE_ADDR CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_ADDR
#define CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_AP2CONN_AHB_GALS_BIST_TX_BIST_DONE_MASK 0x00000002                // AP2CONN_AHB_GALS_BIST_TX_BIST_DONE[1]
#define CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_AP2CONN_AHB_GALS_BIST_TX_BIST_DONE_SHFT 1
#define CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_AP2CONN_AHB_GALS_BIST_TX_BIST_EN_ADDR CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_ADDR
#define CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_AP2CONN_AHB_GALS_BIST_TX_BIST_EN_MASK 0x00000001                // AP2CONN_AHB_GALS_BIST_TX_BIST_EN[0]
#define CB_INFRA_MISC0_AP2CONN_AHB_BIST_TX_CTL_AP2CONN_AHB_GALS_BIST_TX_BIST_EN_SHFT 0

/* =====================================================================================

  ---CBIP_BIST_IDLE (0x70026000 + 0xA04)---

    AP2CONN_AHB_GALS_BIST_TX_IDLE[0] - (RO)  xxx 
    CONN2AP_AXI_GALS_BIST_RX_IDLE[1] - (RO)  xxx 
    WFDMA2AP_AXI_GALS_BIST_RX_IDLE[2] - (RO)  xxx 
    WFDMA1_2AP_AXI_GALS_BIST_RX_IDLE[3] - (RO)  xxx 
    RESERVED4[31..4]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_MISC0_CBIP_BIST_IDLE_WFDMA1_2AP_AXI_GALS_BIST_RX_IDLE_ADDR CB_INFRA_MISC0_CBIP_BIST_IDLE_ADDR
#define CB_INFRA_MISC0_CBIP_BIST_IDLE_WFDMA1_2AP_AXI_GALS_BIST_RX_IDLE_MASK 0x00000008                // WFDMA1_2AP_AXI_GALS_BIST_RX_IDLE[3]
#define CB_INFRA_MISC0_CBIP_BIST_IDLE_WFDMA1_2AP_AXI_GALS_BIST_RX_IDLE_SHFT 3
#define CB_INFRA_MISC0_CBIP_BIST_IDLE_WFDMA2AP_AXI_GALS_BIST_RX_IDLE_ADDR CB_INFRA_MISC0_CBIP_BIST_IDLE_ADDR
#define CB_INFRA_MISC0_CBIP_BIST_IDLE_WFDMA2AP_AXI_GALS_BIST_RX_IDLE_MASK 0x00000004                // WFDMA2AP_AXI_GALS_BIST_RX_IDLE[2]
#define CB_INFRA_MISC0_CBIP_BIST_IDLE_WFDMA2AP_AXI_GALS_BIST_RX_IDLE_SHFT 2
#define CB_INFRA_MISC0_CBIP_BIST_IDLE_CONN2AP_AXI_GALS_BIST_RX_IDLE_ADDR CB_INFRA_MISC0_CBIP_BIST_IDLE_ADDR
#define CB_INFRA_MISC0_CBIP_BIST_IDLE_CONN2AP_AXI_GALS_BIST_RX_IDLE_MASK 0x00000002                // CONN2AP_AXI_GALS_BIST_RX_IDLE[1]
#define CB_INFRA_MISC0_CBIP_BIST_IDLE_CONN2AP_AXI_GALS_BIST_RX_IDLE_SHFT 1
#define CB_INFRA_MISC0_CBIP_BIST_IDLE_AP2CONN_AHB_GALS_BIST_TX_IDLE_ADDR CB_INFRA_MISC0_CBIP_BIST_IDLE_ADDR
#define CB_INFRA_MISC0_CBIP_BIST_IDLE_AP2CONN_AHB_GALS_BIST_TX_IDLE_MASK 0x00000001                // AP2CONN_AHB_GALS_BIST_TX_IDLE[0]
#define CB_INFRA_MISC0_CBIP_BIST_IDLE_AP2CONN_AHB_GALS_BIST_TX_IDLE_SHFT 0

/* =====================================================================================

  ---CBTOP_GALS_BIST_SW_RST_B (0x70026000 + 0xA08)---

    CBTOP_GALS_BIST_SW_RST_B[0]  - (RW) sw reset for gals bist
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_MISC0_CBTOP_GALS_BIST_SW_RST_B_CBTOP_GALS_BIST_SW_RST_B_ADDR CB_INFRA_MISC0_CBTOP_GALS_BIST_SW_RST_B_ADDR
#define CB_INFRA_MISC0_CBTOP_GALS_BIST_SW_RST_B_CBTOP_GALS_BIST_SW_RST_B_MASK 0x00000001                // CBTOP_GALS_BIST_SW_RST_B[0]
#define CB_INFRA_MISC0_CBTOP_GALS_BIST_SW_RST_B_CBTOP_GALS_BIST_SW_RST_B_SHFT 0

/* =====================================================================================

  ---CBTOP_LP_MONITOR_EN (0x70026000 + 0xA0C)---

    CR_LOW_POWER_EN[0]           - (RW)  xxx 
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_MISC0_CBTOP_LP_MONITOR_EN_CR_LOW_POWER_EN_ADDR CB_INFRA_MISC0_CBTOP_LP_MONITOR_EN_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_MONITOR_EN_CR_LOW_POWER_EN_MASK 0x00000001                // CR_LOW_POWER_EN[0]
#define CB_INFRA_MISC0_CBTOP_LP_MONITOR_EN_CR_LOW_POWER_EN_SHFT 0

/* =====================================================================================

  ---CBTOP_LP_MONITOR_0 (0x70026000 + 0xA10)---

    low_power_monitor_0[31..0]   - (RO)  xxx 

 =====================================================================================*/
#define CB_INFRA_MISC0_CBTOP_LP_MONITOR_0_low_power_monitor_0_ADDR CB_INFRA_MISC0_CBTOP_LP_MONITOR_0_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_MONITOR_0_low_power_monitor_0_MASK 0xFFFFFFFF                // low_power_monitor_0[31..0]
#define CB_INFRA_MISC0_CBTOP_LP_MONITOR_0_low_power_monitor_0_SHFT 0

/* =====================================================================================

  ---CBTOP_LP_MONITOR_1 (0x70026000 + 0xA14)---

    low_power_monitor_1[31..0]   - (RO)  xxx 

 =====================================================================================*/
#define CB_INFRA_MISC0_CBTOP_LP_MONITOR_1_low_power_monitor_1_ADDR CB_INFRA_MISC0_CBTOP_LP_MONITOR_1_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_MONITOR_1_low_power_monitor_1_MASK 0xFFFFFFFF                // low_power_monitor_1[31..0]
#define CB_INFRA_MISC0_CBTOP_LP_MONITOR_1_low_power_monitor_1_SHFT 0

/* =====================================================================================

  ---CBTOP_LP_MONITOR_2 (0x70026000 + 0xA18)---

    low_power_monitor_2[31..0]   - (RO)  xxx 

 =====================================================================================*/
#define CB_INFRA_MISC0_CBTOP_LP_MONITOR_2_low_power_monitor_2_ADDR CB_INFRA_MISC0_CBTOP_LP_MONITOR_2_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_MONITOR_2_low_power_monitor_2_MASK 0xFFFFFFFF                // low_power_monitor_2[31..0]
#define CB_INFRA_MISC0_CBTOP_LP_MONITOR_2_low_power_monitor_2_SHFT 0

/* =====================================================================================

  ---DCM_IDLE_CONTROL (0x70026000 + 0xA1C)---

    cr_uhw_early_wakeup[0]       - (RW)  xxx 
    cr_udma_early_wakeup[1]      - (RW)  xxx 
    cr_pcie_mmio_early_wakeup[2] - (RW)  xxx 
    cr_cmdbt_early_wakeup[3]     - (RW)  xxx 
    cr_conn2ap_early_wakeup[4]   - (RW)  xxx 
    cr_dma2ap_early_wakeup[5]    - (RW)  xxx 
    cr_pcie_2_mmio_early_wakeup[6] - (RW)  xxx 
    cr_dma2ap1_early_wakeup[7]   - (RW)  xxx 
    cr_ap2conn_GALS_bridge_async_idle_m[8] - (RW)  xxx 
    cr_ap2conn_GALS_bridge_sync_idle_m[9] - (RW)  xxx 
    RESERVED10[31..10]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_MISC0_DCM_IDLE_CONTROL_cr_ap2conn_GALS_bridge_sync_idle_m_ADDR CB_INFRA_MISC0_DCM_IDLE_CONTROL_ADDR
#define CB_INFRA_MISC0_DCM_IDLE_CONTROL_cr_ap2conn_GALS_bridge_sync_idle_m_MASK 0x00000200                // cr_ap2conn_GALS_bridge_sync_idle_m[9]
#define CB_INFRA_MISC0_DCM_IDLE_CONTROL_cr_ap2conn_GALS_bridge_sync_idle_m_SHFT 9
#define CB_INFRA_MISC0_DCM_IDLE_CONTROL_cr_ap2conn_GALS_bridge_async_idle_m_ADDR CB_INFRA_MISC0_DCM_IDLE_CONTROL_ADDR
#define CB_INFRA_MISC0_DCM_IDLE_CONTROL_cr_ap2conn_GALS_bridge_async_idle_m_MASK 0x00000100                // cr_ap2conn_GALS_bridge_async_idle_m[8]
#define CB_INFRA_MISC0_DCM_IDLE_CONTROL_cr_ap2conn_GALS_bridge_async_idle_m_SHFT 8
#define CB_INFRA_MISC0_DCM_IDLE_CONTROL_cr_dma2ap1_early_wakeup_ADDR CB_INFRA_MISC0_DCM_IDLE_CONTROL_ADDR
#define CB_INFRA_MISC0_DCM_IDLE_CONTROL_cr_dma2ap1_early_wakeup_MASK 0x00000080                // cr_dma2ap1_early_wakeup[7]
#define CB_INFRA_MISC0_DCM_IDLE_CONTROL_cr_dma2ap1_early_wakeup_SHFT 7
#define CB_INFRA_MISC0_DCM_IDLE_CONTROL_cr_pcie_2_mmio_early_wakeup_ADDR CB_INFRA_MISC0_DCM_IDLE_CONTROL_ADDR
#define CB_INFRA_MISC0_DCM_IDLE_CONTROL_cr_pcie_2_mmio_early_wakeup_MASK 0x00000040                // cr_pcie_2_mmio_early_wakeup[6]
#define CB_INFRA_MISC0_DCM_IDLE_CONTROL_cr_pcie_2_mmio_early_wakeup_SHFT 6
#define CB_INFRA_MISC0_DCM_IDLE_CONTROL_cr_dma2ap_early_wakeup_ADDR CB_INFRA_MISC0_DCM_IDLE_CONTROL_ADDR
#define CB_INFRA_MISC0_DCM_IDLE_CONTROL_cr_dma2ap_early_wakeup_MASK 0x00000020                // cr_dma2ap_early_wakeup[5]
#define CB_INFRA_MISC0_DCM_IDLE_CONTROL_cr_dma2ap_early_wakeup_SHFT 5
#define CB_INFRA_MISC0_DCM_IDLE_CONTROL_cr_conn2ap_early_wakeup_ADDR CB_INFRA_MISC0_DCM_IDLE_CONTROL_ADDR
#define CB_INFRA_MISC0_DCM_IDLE_CONTROL_cr_conn2ap_early_wakeup_MASK 0x00000010                // cr_conn2ap_early_wakeup[4]
#define CB_INFRA_MISC0_DCM_IDLE_CONTROL_cr_conn2ap_early_wakeup_SHFT 4
#define CB_INFRA_MISC0_DCM_IDLE_CONTROL_cr_cmdbt_early_wakeup_ADDR CB_INFRA_MISC0_DCM_IDLE_CONTROL_ADDR
#define CB_INFRA_MISC0_DCM_IDLE_CONTROL_cr_cmdbt_early_wakeup_MASK 0x00000008                // cr_cmdbt_early_wakeup[3]
#define CB_INFRA_MISC0_DCM_IDLE_CONTROL_cr_cmdbt_early_wakeup_SHFT 3
#define CB_INFRA_MISC0_DCM_IDLE_CONTROL_cr_pcie_mmio_early_wakeup_ADDR CB_INFRA_MISC0_DCM_IDLE_CONTROL_ADDR
#define CB_INFRA_MISC0_DCM_IDLE_CONTROL_cr_pcie_mmio_early_wakeup_MASK 0x00000004                // cr_pcie_mmio_early_wakeup[2]
#define CB_INFRA_MISC0_DCM_IDLE_CONTROL_cr_pcie_mmio_early_wakeup_SHFT 2
#define CB_INFRA_MISC0_DCM_IDLE_CONTROL_cr_udma_early_wakeup_ADDR CB_INFRA_MISC0_DCM_IDLE_CONTROL_ADDR
#define CB_INFRA_MISC0_DCM_IDLE_CONTROL_cr_udma_early_wakeup_MASK 0x00000002                // cr_udma_early_wakeup[1]
#define CB_INFRA_MISC0_DCM_IDLE_CONTROL_cr_udma_early_wakeup_SHFT 1
#define CB_INFRA_MISC0_DCM_IDLE_CONTROL_cr_uhw_early_wakeup_ADDR CB_INFRA_MISC0_DCM_IDLE_CONTROL_ADDR
#define CB_INFRA_MISC0_DCM_IDLE_CONTROL_cr_uhw_early_wakeup_MASK 0x00000001                // cr_uhw_early_wakeup[0]
#define CB_INFRA_MISC0_DCM_IDLE_CONTROL_cr_uhw_early_wakeup_SHFT 0

/* =====================================================================================

  ---JTAG_SEJ_STATUS (0x70026000 + 0xA20)---

    mp_niden[0]                  - (RO)  xxx 
    mp_dbgen[1]                  - (RO)  xxx 
    RESERVED2[31..2]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_INFRA_MISC0_JTAG_SEJ_STATUS_mp_dbgen_ADDR           CB_INFRA_MISC0_JTAG_SEJ_STATUS_ADDR
#define CB_INFRA_MISC0_JTAG_SEJ_STATUS_mp_dbgen_MASK           0x00000002                // mp_dbgen[1]
#define CB_INFRA_MISC0_JTAG_SEJ_STATUS_mp_dbgen_SHFT           1
#define CB_INFRA_MISC0_JTAG_SEJ_STATUS_mp_niden_ADDR           CB_INFRA_MISC0_JTAG_SEJ_STATUS_ADDR
#define CB_INFRA_MISC0_JTAG_SEJ_STATUS_mp_niden_MASK           0x00000001                // mp_niden[0]
#define CB_INFRA_MISC0_JTAG_SEJ_STATUS_mp_niden_SHFT           0

/* =====================================================================================

  ---CBTOP_LP_MONITOR_3 (0x70026000 + 0xA24)---

    low_power_monitor_3[31..0]   - (RO)  xxx 

 =====================================================================================*/
#define CB_INFRA_MISC0_CBTOP_LP_MONITOR_3_low_power_monitor_3_ADDR CB_INFRA_MISC0_CBTOP_LP_MONITOR_3_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_MONITOR_3_low_power_monitor_3_MASK 0xFFFFFFFF                // low_power_monitor_3[31..0]
#define CB_INFRA_MISC0_CBTOP_LP_MONITOR_3_low_power_monitor_3_SHFT 0

/* =====================================================================================

  ---CBTOP_LP_MONITOR_4 (0x70026000 + 0xA28)---

    low_power_monitor_4[31..0]   - (RO)  xxx 

 =====================================================================================*/
#define CB_INFRA_MISC0_CBTOP_LP_MONITOR_4_low_power_monitor_4_ADDR CB_INFRA_MISC0_CBTOP_LP_MONITOR_4_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_MONITOR_4_low_power_monitor_4_MASK 0xFFFFFFFF                // low_power_monitor_4[31..0]
#define CB_INFRA_MISC0_CBTOP_LP_MONITOR_4_low_power_monitor_4_SHFT 0

/* =====================================================================================

  ---CBTOP_LP_MONITOR_CNT (0x70026000 + 0xA2C)---

    low_power_monitor_CNT[31..0] - (RO)  xxx 

 =====================================================================================*/
#define CB_INFRA_MISC0_CBTOP_LP_MONITOR_CNT_low_power_monitor_CNT_ADDR CB_INFRA_MISC0_CBTOP_LP_MONITOR_CNT_ADDR
#define CB_INFRA_MISC0_CBTOP_LP_MONITOR_CNT_low_power_monitor_CNT_MASK 0xFFFFFFFF                // low_power_monitor_CNT[31..0]
#define CB_INFRA_MISC0_CBTOP_LP_MONITOR_CNT_low_power_monitor_CNT_SHFT 0

#ifdef __cplusplus
}
#endif

#endif // __CB_INFRA_MISC0_REGS_H__
