/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * Copyright (c) 2023 MediaTek Inc.
 */

//[File]            : wf_uwtbl_top.h
//[Revision time]   : Wed Jan  4 12:37:05 2023
//[Description]     : This file is auto generated by CODA
//[Copyright]       : Copyright (C) 2023 Mediatek Incorportion. All rights reserved.
// remove HW description see https://wiki.mediatek.inc/display/WTKB/CODA+HW+description+separation


#ifndef __WF_UWTBL_TOP_REGS_H__
#define __WF_UWTBL_TOP_REGS_H__

#include "hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif








#define WF_UWTBL_TOP_BASE                                      0x820c4000

#define WF_UWTBL_TOP_KTVLBR0_ADDR                              (WF_UWTBL_TOP_BASE + 0x0000) 
#define WF_UWTBL_TOP_UCR_ADDR                                  (WF_UWTBL_TOP_BASE + 0x0100) 
#define WF_UWTBL_TOP_WDUCR_ADDR                                (WF_UWTBL_TOP_BASE + 0x0104) 
#define WF_UWTBL_TOP_KTCR_ADDR                                 (WF_UWTBL_TOP_BASE + 0x0108) 
#define WF_UWTBL_TOP_WIUCR_ADDR                                (WF_UWTBL_TOP_BASE + 0x0110) 
#define WF_UWTBL_TOP_WMUDR_ADDR                                (WF_UWTBL_TOP_BASE + 0x0114) 
#define WF_UWTBL_TOP_WMUMR_ADDR                                (WF_UWTBL_TOP_BASE + 0x0118) 
#define WF_UWTBL_TOP_PICR0_ADDR                                (WF_UWTBL_TOP_BASE + 0x0120) 
#define WF_UWTBL_TOP_PICR1_ADDR                                (WF_UWTBL_TOP_BASE + 0x0124) 
#define WF_UWTBL_TOP_ITCR_ADDR                                 (WF_UWTBL_TOP_BASE + 0x0130) 
#define WF_UWTBL_TOP_ITDR0_ADDR                                (WF_UWTBL_TOP_BASE + 0x0138) 
#define WF_UWTBL_TOP_ITDR1_ADDR                                (WF_UWTBL_TOP_BASE + 0x013C) 
#define WF_UWTBL_TOP_PSCCR_ADDR                                (WF_UWTBL_TOP_BASE + 0x0140) 
#define WF_UWTBL_TOP_DSCR00_ADDR                               (WF_UWTBL_TOP_BASE + 0x0200) 
#define WF_UWTBL_TOP_DSCR01_ADDR                               (WF_UWTBL_TOP_BASE + 0x0204) 
#define WF_UWTBL_TOP_DSCR02_ADDR                               (WF_UWTBL_TOP_BASE + 0x0208) 
#define WF_UWTBL_TOP_DSCR03_ADDR                               (WF_UWTBL_TOP_BASE + 0x020C) 
#define WF_UWTBL_TOP_DSCR_EXT_00_ADDR                          (WF_UWTBL_TOP_BASE + 0x0280) 
#define WF_UWTBL_TOP_SRCR00_ADDR                               (WF_UWTBL_TOP_BASE + 0x0300) 
#define WF_UWTBL_TOP_SRCR01_ADDR                               (WF_UWTBL_TOP_BASE + 0x0304) 
#define WF_UWTBL_TOP_SRCR02_ADDR                               (WF_UWTBL_TOP_BASE + 0x0308) 
#define WF_UWTBL_TOP_SRCR03_ADDR                               (WF_UWTBL_TOP_BASE + 0x030C) 
#define WF_UWTBL_TOP_SRCR_EXT_00_ADDR                          (WF_UWTBL_TOP_BASE + 0x0380) 
#define WF_UWTBL_TOP_NSEPPCR00_ADDR                            (WF_UWTBL_TOP_BASE + 0x0400) 
#define WF_UWTBL_TOP_NSEPPCR01_ADDR                            (WF_UWTBL_TOP_BASE + 0x0404) 
#define WF_UWTBL_TOP_NSEPPCR02_ADDR                            (WF_UWTBL_TOP_BASE + 0x0408) 
#define WF_UWTBL_TOP_NSEPPCR03_ADDR                            (WF_UWTBL_TOP_BASE + 0x040C) 
#define WF_UWTBL_TOP_NSEPPCR_EXT_00_ADDR                       (WF_UWTBL_TOP_BASE + 0x0480) 
#define WF_UWTBL_TOP_DFR_ADDR                                  (WF_UWTBL_TOP_BASE + 0x1FD0) 
#define WF_UWTBL_TOP_WTBLSNO_ADDR                              (WF_UWTBL_TOP_BASE + 0x1FE0) 
#define WF_UWTBL_TOP_WTBLENO_ADDR                              (WF_UWTBL_TOP_BASE + 0x1FE4) 
#define WF_UWTBL_TOP_KTBLNO_ADDR                               (WF_UWTBL_TOP_BASE + 0x1FE8) 
#define WF_UWTBL_TOP_DMY0_ADDR                                 (WF_UWTBL_TOP_BASE + 0x1FF0) 
#define WF_UWTBL_TOP_DMY1_ADDR                                 (WF_UWTBL_TOP_BASE + 0x1FF4) 
#define WF_UWTBL_TOP_WTBL_DW_ADDR                              (WF_UWTBL_TOP_BASE + 0x1FF8) 
#define WF_UWTBL_TOP_WTBL_BASE_ADDR                            (WF_UWTBL_TOP_BASE + 0x1FFC) 





#define WF_UWTBL_TOP_KTVLBR0_VLB_ADDR                          WF_UWTBL_TOP_KTVLBR0_ADDR
#define WF_UWTBL_TOP_KTVLBR0_VLB_MASK                          0xFFFFFFFF                
#define WF_UWTBL_TOP_KTVLBR0_VLB_SHFT                          0


#define WF_UWTBL_TOP_UCR_MAX_BIPN_RANGE_ADDR                   WF_UWTBL_TOP_UCR_ADDR
#define WF_UWTBL_TOP_UCR_MAX_BIPN_RANGE_MASK                   0xFFFF0000                
#define WF_UWTBL_TOP_UCR_MAX_BIPN_RANGE_SHFT                   16
#define WF_UWTBL_TOP_UCR_PN_INCR_MODE_ADDR                     WF_UWTBL_TOP_UCR_ADDR
#define WF_UWTBL_TOP_UCR_PN_INCR_MODE_MASK                     0x00000001                
#define WF_UWTBL_TOP_UCR_PN_INCR_MODE_SHFT                     0


#define WF_UWTBL_TOP_WDUCR_TARGET_ADDR                         WF_UWTBL_TOP_WDUCR_ADDR
#define WF_UWTBL_TOP_WDUCR_TARGET_MASK                         0x80000000                
#define WF_UWTBL_TOP_WDUCR_TARGET_SHFT                         31
#define WF_UWTBL_TOP_WDUCR_GROUP_ADDR                          WF_UWTBL_TOP_WDUCR_ADDR
#define WF_UWTBL_TOP_WDUCR_GROUP_MASK                          0x0000003F                
#define WF_UWTBL_TOP_WDUCR_GROUP_SHFT                          0


#define WF_UWTBL_TOP_KTCR_REASON_ADDR                          WF_UWTBL_TOP_KTCR_ADDR
#define WF_UWTBL_TOP_KTCR_REASON_MASK                          0xC0000000                
#define WF_UWTBL_TOP_KTCR_REASON_SHFT                          30
#define WF_UWTBL_TOP_KTCR_OPERATION_ADDR                       WF_UWTBL_TOP_KTCR_ADDR
#define WF_UWTBL_TOP_KTCR_OPERATION_MASK                       0x0000C000                
#define WF_UWTBL_TOP_KTCR_OPERATION_SHFT                       14
#define WF_UWTBL_TOP_KTCR_INDEX_ADDR                           WF_UWTBL_TOP_KTCR_ADDR
#define WF_UWTBL_TOP_KTCR_INDEX_MASK                           0x00001FFF                
#define WF_UWTBL_TOP_KTCR_INDEX_SHFT                           0


#define WF_UWTBL_TOP_WIUCR_IU_BUSY_ADDR                        WF_UWTBL_TOP_WIUCR_ADDR
#define WF_UWTBL_TOP_WIUCR_IU_BUSY_MASK                        0x80000000                
#define WF_UWTBL_TOP_WIUCR_IU_BUSY_SHFT                        31
#define WF_UWTBL_TOP_WIUCR_DW_ADDR                             WF_UWTBL_TOP_WIUCR_ADDR
#define WF_UWTBL_TOP_WIUCR_DW_MASK                             0x0F000000                
#define WF_UWTBL_TOP_WIUCR_DW_SHFT                             24
#define WF_UWTBL_TOP_WIUCR_MASK_UPDATE_ADDR                    WF_UWTBL_TOP_WIUCR_ADDR
#define WF_UWTBL_TOP_WIUCR_MASK_UPDATE_MASK                    0x00100000                
#define WF_UWTBL_TOP_WIUCR_MASK_UPDATE_SHFT                    20
#define WF_UWTBL_TOP_WIUCR_PNSN_CLEAR_ADDR                     WF_UWTBL_TOP_WIUCR_ADDR
#define WF_UWTBL_TOP_WIUCR_PNSN_CLEAR_MASK                     0x00040000                
#define WF_UWTBL_TOP_WIUCR_PNSN_CLEAR_SHFT                     18
#define WF_UWTBL_TOP_WIUCR_PEERINFO_UPDATE_ADDR                WF_UWTBL_TOP_WIUCR_ADDR
#define WF_UWTBL_TOP_WIUCR_PEERINFO_UPDATE_MASK                0x00002000                
#define WF_UWTBL_TOP_WIUCR_PEERINFO_UPDATE_SHFT                13
#define WF_UWTBL_TOP_WIUCR_INDEX_ADDR                          WF_UWTBL_TOP_WIUCR_ADDR
#define WF_UWTBL_TOP_WIUCR_INDEX_MASK                          0x00000FFF                
#define WF_UWTBL_TOP_WIUCR_INDEX_SHFT                          0


#define WF_UWTBL_TOP_WMUDR_UPDATE_DATA_ADDR                    WF_UWTBL_TOP_WMUDR_ADDR
#define WF_UWTBL_TOP_WMUDR_UPDATE_DATA_MASK                    0xFFFFFFFF                
#define WF_UWTBL_TOP_WMUDR_UPDATE_DATA_SHFT                    0


#define WF_UWTBL_TOP_WMUMR_UPDATE_MASK_ADDR                    WF_UWTBL_TOP_WMUMR_ADDR
#define WF_UWTBL_TOP_WMUMR_UPDATE_MASK_MASK                    0xFFFFFFFF                
#define WF_UWTBL_TOP_WMUMR_UPDATE_MASK_SHFT                    0


#define WF_UWTBL_TOP_PICR0_DW0_WTBL_ADDR                       WF_UWTBL_TOP_PICR0_ADDR
#define WF_UWTBL_TOP_PICR0_DW0_WTBL_MASK                       0xFFFFFFFF                
#define WF_UWTBL_TOP_PICR0_DW0_WTBL_SHFT                       0


#define WF_UWTBL_TOP_PICR1_DW1_WTBL_ADDR                       WF_UWTBL_TOP_PICR1_ADDR
#define WF_UWTBL_TOP_PICR1_DW1_WTBL_MASK                       0xFFFFFFFF                
#define WF_UWTBL_TOP_PICR1_DW1_WTBL_SHFT                       0


#define WF_UWTBL_TOP_ITCR_EXECUTE_ADDR                         WF_UWTBL_TOP_ITCR_ADDR
#define WF_UWTBL_TOP_ITCR_EXECUTE_MASK                         0x80000000                
#define WF_UWTBL_TOP_ITCR_EXECUTE_SHFT                         31
#define WF_UWTBL_TOP_ITCR_SELECT_ADDR                          WF_UWTBL_TOP_ITCR_ADDR
#define WF_UWTBL_TOP_ITCR_SELECT_MASK                          0x03000000                
#define WF_UWTBL_TOP_ITCR_SELECT_SHFT                          24
#define WF_UWTBL_TOP_ITCR_OP_ADDR                              WF_UWTBL_TOP_ITCR_ADDR
#define WF_UWTBL_TOP_ITCR_OP_MASK                              0x00010000                
#define WF_UWTBL_TOP_ITCR_OP_SHFT                              16
#define WF_UWTBL_TOP_ITCR_INDEX_ADDR                           WF_UWTBL_TOP_ITCR_ADDR
#define WF_UWTBL_TOP_ITCR_INDEX_MASK                           0x0000003F                
#define WF_UWTBL_TOP_ITCR_INDEX_SHFT                           0


#define WF_UWTBL_TOP_ITDR0_INDIRECT_TABLE_DATA_ADDR            WF_UWTBL_TOP_ITDR0_ADDR
#define WF_UWTBL_TOP_ITDR0_INDIRECT_TABLE_DATA_MASK            0xFFFFFFFF                
#define WF_UWTBL_TOP_ITDR0_INDIRECT_TABLE_DATA_SHFT            0


#define WF_UWTBL_TOP_ITDR1_INDIRECT_TABLE_DATA_ADDR            WF_UWTBL_TOP_ITDR1_ADDR
#define WF_UWTBL_TOP_ITDR1_INDIRECT_TABLE_DATA_MASK            0xFFFFFFFF                
#define WF_UWTBL_TOP_ITDR1_INDIRECT_TABLE_DATA_SHFT            0


#define WF_UWTBL_TOP_PSCCR_EXECUTE_ADDR                        WF_UWTBL_TOP_PSCCR_ADDR
#define WF_UWTBL_TOP_PSCCR_EXECUTE_MASK                        0x80000000                
#define WF_UWTBL_TOP_PSCCR_EXECUTE_SHFT                        31
#define WF_UWTBL_TOP_PSCCR_OP_ADDR                             WF_UWTBL_TOP_PSCCR_ADDR
#define WF_UWTBL_TOP_PSCCR_OP_MASK                             0x01000000                
#define WF_UWTBL_TOP_PSCCR_OP_SHFT                             24
#define WF_UWTBL_TOP_PSCCR_TARGET_ADDR                         WF_UWTBL_TOP_PSCCR_ADDR
#define WF_UWTBL_TOP_PSCCR_TARGET_MASK                         0x00070000                
#define WF_UWTBL_TOP_PSCCR_TARGET_SHFT                         16
#define WF_UWTBL_TOP_PSCCR_MLD_ID_ADDR                         WF_UWTBL_TOP_PSCCR_ADDR
#define WF_UWTBL_TOP_PSCCR_MLD_ID_MASK                         0x00000FFF                
#define WF_UWTBL_TOP_PSCCR_MLD_ID_SHFT                         0


#define WF_UWTBL_TOP_DSCR00_DSCR00_02_ADDR                     WF_UWTBL_TOP_DSCR00_ADDR
#define WF_UWTBL_TOP_DSCR00_DSCR00_02_MASK                     0xFFFF0000                
#define WF_UWTBL_TOP_DSCR00_DSCR00_02_SHFT                     16
#define WF_UWTBL_TOP_DSCR00_DSCR00_01_ADDR                     WF_UWTBL_TOP_DSCR00_ADDR
#define WF_UWTBL_TOP_DSCR00_DSCR00_01_MASK                     0x0000FF00                
#define WF_UWTBL_TOP_DSCR00_DSCR00_01_SHFT                     8
#define WF_UWTBL_TOP_DSCR00_DSCR00_ADDR                        WF_UWTBL_TOP_DSCR00_ADDR
#define WF_UWTBL_TOP_DSCR00_DSCR00_MASK                        0x000000FF                
#define WF_UWTBL_TOP_DSCR00_DSCR00_SHFT                        0


#define WF_UWTBL_TOP_DSCR01_DSCR01_ADDR                        WF_UWTBL_TOP_DSCR01_ADDR
#define WF_UWTBL_TOP_DSCR01_DSCR01_MASK                        0xFFFFFFFF                
#define WF_UWTBL_TOP_DSCR01_DSCR01_SHFT                        0


#define WF_UWTBL_TOP_DSCR02_DSCR02_ADDR                        WF_UWTBL_TOP_DSCR02_ADDR
#define WF_UWTBL_TOP_DSCR02_DSCR02_MASK                        0xFFFFFFFF                
#define WF_UWTBL_TOP_DSCR02_DSCR02_SHFT                        0


#define WF_UWTBL_TOP_DSCR03_DSCR03_ADDR                        WF_UWTBL_TOP_DSCR03_ADDR
#define WF_UWTBL_TOP_DSCR03_DSCR03_MASK                        0xFFFFFFFF                
#define WF_UWTBL_TOP_DSCR03_DSCR03_SHFT                        0


#define WF_UWTBL_TOP_DSCR_EXT_00_DSCR_EXT_00_01_ADDR           WF_UWTBL_TOP_DSCR_EXT_00_ADDR
#define WF_UWTBL_TOP_DSCR_EXT_00_DSCR_EXT_00_01_MASK           0x000000F0                
#define WF_UWTBL_TOP_DSCR_EXT_00_DSCR_EXT_00_01_SHFT           4
#define WF_UWTBL_TOP_DSCR_EXT_00_DSCR_EXT_00_ADDR              WF_UWTBL_TOP_DSCR_EXT_00_ADDR
#define WF_UWTBL_TOP_DSCR_EXT_00_DSCR_EXT_00_MASK              0x0000000F                
#define WF_UWTBL_TOP_DSCR_EXT_00_DSCR_EXT_00_SHFT              0


#define WF_UWTBL_TOP_SRCR00_SRCR00_02_ADDR                     WF_UWTBL_TOP_SRCR00_ADDR
#define WF_UWTBL_TOP_SRCR00_SRCR00_02_MASK                     0xFFFF0000                
#define WF_UWTBL_TOP_SRCR00_SRCR00_02_SHFT                     16
#define WF_UWTBL_TOP_SRCR00_SRCR00_01_ADDR                     WF_UWTBL_TOP_SRCR00_ADDR
#define WF_UWTBL_TOP_SRCR00_SRCR00_01_MASK                     0x0000FF00                
#define WF_UWTBL_TOP_SRCR00_SRCR00_01_SHFT                     8
#define WF_UWTBL_TOP_SRCR00_SRCR00_ADDR                        WF_UWTBL_TOP_SRCR00_ADDR
#define WF_UWTBL_TOP_SRCR00_SRCR00_MASK                        0x000000FF                
#define WF_UWTBL_TOP_SRCR00_SRCR00_SHFT                        0


#define WF_UWTBL_TOP_SRCR01_SRCR01_ADDR                        WF_UWTBL_TOP_SRCR01_ADDR
#define WF_UWTBL_TOP_SRCR01_SRCR01_MASK                        0xFFFFFFFF                
#define WF_UWTBL_TOP_SRCR01_SRCR01_SHFT                        0


#define WF_UWTBL_TOP_SRCR02_SRCR02_ADDR                        WF_UWTBL_TOP_SRCR02_ADDR
#define WF_UWTBL_TOP_SRCR02_SRCR02_MASK                        0xFFFFFFFF                
#define WF_UWTBL_TOP_SRCR02_SRCR02_SHFT                        0


#define WF_UWTBL_TOP_SRCR03_SRCR03_ADDR                        WF_UWTBL_TOP_SRCR03_ADDR
#define WF_UWTBL_TOP_SRCR03_SRCR03_MASK                        0xFFFFFFFF                
#define WF_UWTBL_TOP_SRCR03_SRCR03_SHFT                        0


#define WF_UWTBL_TOP_SRCR_EXT_00_SRCR_EXT_00_01_ADDR           WF_UWTBL_TOP_SRCR_EXT_00_ADDR
#define WF_UWTBL_TOP_SRCR_EXT_00_SRCR_EXT_00_01_MASK           0x000000F0                
#define WF_UWTBL_TOP_SRCR_EXT_00_SRCR_EXT_00_01_SHFT           4
#define WF_UWTBL_TOP_SRCR_EXT_00_SRCR_EXT_00_ADDR              WF_UWTBL_TOP_SRCR_EXT_00_ADDR
#define WF_UWTBL_TOP_SRCR_EXT_00_SRCR_EXT_00_MASK              0x0000000F                
#define WF_UWTBL_TOP_SRCR_EXT_00_SRCR_EXT_00_SHFT              0


#define WF_UWTBL_TOP_NSEPPCR00_NSEPPCR00_02_ADDR               WF_UWTBL_TOP_NSEPPCR00_ADDR
#define WF_UWTBL_TOP_NSEPPCR00_NSEPPCR00_02_MASK               0xFFFF0000                
#define WF_UWTBL_TOP_NSEPPCR00_NSEPPCR00_02_SHFT               16
#define WF_UWTBL_TOP_NSEPPCR00_NSEPPCR00_01_ADDR               WF_UWTBL_TOP_NSEPPCR00_ADDR
#define WF_UWTBL_TOP_NSEPPCR00_NSEPPCR00_01_MASK               0x0000FF00                
#define WF_UWTBL_TOP_NSEPPCR00_NSEPPCR00_01_SHFT               8
#define WF_UWTBL_TOP_NSEPPCR00_NSEPPCR00_ADDR                  WF_UWTBL_TOP_NSEPPCR00_ADDR
#define WF_UWTBL_TOP_NSEPPCR00_NSEPPCR00_MASK                  0x000000FF                
#define WF_UWTBL_TOP_NSEPPCR00_NSEPPCR00_SHFT                  0


#define WF_UWTBL_TOP_NSEPPCR01_NSEPPCR01_ADDR                  WF_UWTBL_TOP_NSEPPCR01_ADDR
#define WF_UWTBL_TOP_NSEPPCR01_NSEPPCR01_MASK                  0xFFFFFFFF                
#define WF_UWTBL_TOP_NSEPPCR01_NSEPPCR01_SHFT                  0


#define WF_UWTBL_TOP_NSEPPCR02_NSEPPCR02_ADDR                  WF_UWTBL_TOP_NSEPPCR02_ADDR
#define WF_UWTBL_TOP_NSEPPCR02_NSEPPCR02_MASK                  0xFFFFFFFF                
#define WF_UWTBL_TOP_NSEPPCR02_NSEPPCR02_SHFT                  0


#define WF_UWTBL_TOP_NSEPPCR03_NSEPPCR03_ADDR                  WF_UWTBL_TOP_NSEPPCR03_ADDR
#define WF_UWTBL_TOP_NSEPPCR03_NSEPPCR03_MASK                  0xFFFFFFFF                
#define WF_UWTBL_TOP_NSEPPCR03_NSEPPCR03_SHFT                  0


#define WF_UWTBL_TOP_NSEPPCR_EXT_00_NSEPPCR_EXT_00_01_ADDR     WF_UWTBL_TOP_NSEPPCR_EXT_00_ADDR
#define WF_UWTBL_TOP_NSEPPCR_EXT_00_NSEPPCR_EXT_00_01_MASK     0x000000F0                
#define WF_UWTBL_TOP_NSEPPCR_EXT_00_NSEPPCR_EXT_00_01_SHFT     4
#define WF_UWTBL_TOP_NSEPPCR_EXT_00_NSEPPCR_EXT_00_ADDR        WF_UWTBL_TOP_NSEPPCR_EXT_00_ADDR
#define WF_UWTBL_TOP_NSEPPCR_EXT_00_NSEPPCR_EXT_00_MASK        0x0000000F                
#define WF_UWTBL_TOP_NSEPPCR_EXT_00_NSEPPCR_EXT_00_SHFT        0


#define WF_UWTBL_TOP_DFR_DEBUG_FSM_ADDR                        WF_UWTBL_TOP_DFR_ADDR
#define WF_UWTBL_TOP_DFR_DEBUG_FSM_MASK                        0xFFFFFFFF                
#define WF_UWTBL_TOP_DFR_DEBUG_FSM_SHFT                        0


#define WF_UWTBL_TOP_WTBLSNO_WTBL_STD_NO_ADDR                  WF_UWTBL_TOP_WTBLSNO_ADDR
#define WF_UWTBL_TOP_WTBLSNO_WTBL_STD_NO_MASK                  0xFFFFFFFF                
#define WF_UWTBL_TOP_WTBLSNO_WTBL_STD_NO_SHFT                  0


#define WF_UWTBL_TOP_WTBLENO_WTBL_EXT_NO_ADDR                  WF_UWTBL_TOP_WTBLENO_ADDR
#define WF_UWTBL_TOP_WTBLENO_WTBL_EXT_NO_MASK                  0xFFFFFFFF                
#define WF_UWTBL_TOP_WTBLENO_WTBL_EXT_NO_SHFT                  0


#define WF_UWTBL_TOP_KTBLNO_KTBL_NO_ADDR                       WF_UWTBL_TOP_KTBLNO_ADDR
#define WF_UWTBL_TOP_KTBLNO_KTBL_NO_MASK                       0xFFFFFFFF                
#define WF_UWTBL_TOP_KTBLNO_KTBL_NO_SHFT                       0


#define WF_UWTBL_TOP_DMY0_DMY0_ADDR                            WF_UWTBL_TOP_DMY0_ADDR
#define WF_UWTBL_TOP_DMY0_DMY0_MASK                            0xFFFFFFFF                
#define WF_UWTBL_TOP_DMY0_DMY0_SHFT                            0


#define WF_UWTBL_TOP_DMY1_DMY1_ADDR                            WF_UWTBL_TOP_DMY1_ADDR
#define WF_UWTBL_TOP_DMY1_DMY1_MASK                            0xFFFFFFFF                
#define WF_UWTBL_TOP_DMY1_DMY1_SHFT                            0


#define WF_UWTBL_TOP_WTBL_DW_WTBL_DW_ADDR                      WF_UWTBL_TOP_WTBL_DW_ADDR
#define WF_UWTBL_TOP_WTBL_DW_WTBL_DW_MASK                      0xFFFFFFFF                
#define WF_UWTBL_TOP_WTBL_DW_WTBL_DW_SHFT                      0


#define WF_UWTBL_TOP_WTBL_BASE_WTBL_BASE_ADDR                  WF_UWTBL_TOP_WTBL_BASE_ADDR
#define WF_UWTBL_TOP_WTBL_BASE_WTBL_BASE_MASK                  0xFFFFFFFF                
#define WF_UWTBL_TOP_WTBL_BASE_WTBL_BASE_SHFT                  0

#ifdef __cplusplus
}
#endif

#endif // __WF_UWTBL_TOP_REGS_H__
