LINUX_SRC=/lib/modules/$(shell uname -r)/build

PWD=$(shell pwd)
DRIVER_DIR=$(PWD)

all: driver

driver:
	cd $(DRIVER_DIR) && make -C $(LINUX_SRC) M=$(DRIVER_DIR) modules

clean: driver_clean

driver_clean:
	cd $(DRIVER_DIR) && make -C $(LINUX_SRC) M=$(DRIVER_DIR) clean

.PHONY: all clean driver driver_clean
