/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2018 MediaTek Inc.
 *
 * Author: Floria Huang <floria.huang@mediatek.com>
 *
 */

#ifndef _MTK_IMGSYS_PORT_H_
#define _MTK_IMGSYS_PORT_H_

struct mtk_imgsys_port_table;
#include "imgsys_modules/mtk_imgsys-pqdip.h"
#include "imgsys_modules/mtk_imgsys-me.h"
#include "imgsys_modules/mtk_imgsys-traw.h"

#ifdef IMGSYS_TF_DUMP_8_L
#include <dt-bindings/memory/mt6991-larb-port.h>
static struct mtk_imgsys_port_table imgsys_dma_port_mt6991[] = {
	/* Larb9 -- 9*/
	{SMMU_L9_P0_IMGI_T1_B         , imgsys_ltraw_tfault_callback},
	{SMMU_L9_P1_IMGCI_T1_B        , imgsys_ltraw_tfault_callback},
	{SMMU_L9_P2_SMTI_T1_B         , imgsys_ltraw_tfault_callback},
	{SMMU_L9_P3_YUVO_T1_B         , imgsys_ltraw_tfault_callback},
	{SMMU_L9_P4_YUVCO_T1_B        , imgsys_ltraw_tfault_callback},
	{SMMU_L9_P5_YUVO_T2_B         , imgsys_ltraw_tfault_callback},
	{SMMU_L9_P6_YUVBO_T2_B        , imgsys_ltraw_tfault_callback},
	{SMMU_L9_P7_TNCSTO_T1_B       , imgsys_ltraw_tfault_callback},
	{SMMU_L9_P8_TNCSTI_T2_B       , imgsys_ltraw_tfault_callback},
	{SMMU_L9_P9_YUFETI_T1_B       , imgsys_ltraw_tfault_callback},
	{SMMU_L9_P10_STG_T1_B         , imgsys_ltraw_tfault_callback},
	{SMMU_L9_P11_STG_T2_B         , imgsys_ltraw_tfault_callback},
	{SMMU_L9_P12_ME_RDMA_0        , ME_TranslationFault_callback},
	{SMMU_L9_P13_ME_WDMA_0        , ME_TranslationFault_callback},
	{SMMU_L9_P14_MEMMG_RDMA_0     , ME_TranslationFault_callback},
	{SMMU_L9_P15_MEMMG_WDMA_0     , ME_TranslationFault_callback},
	{SMMU_L9_P16_ME_2ND_RDMA_0    , ME_TranslationFault_callback},
	{SMMU_L9_P17_ME_2ND_WDMA_0    , ME_TranslationFault_callback},
	{SMMU_L9_P18_MEMMG_2ND_RDMA_0 , ME_TranslationFault_callback},
	{SMMU_L9_P19_MEMMG_2ND_WDMA_0 , ME_TranslationFault_callback},
	{SMMU_L9_P20_STSCMD_ME0       , ME_TranslationFault_callback},
	{SMMU_L9_P21_STSCMD_ME1       , ME_TranslationFault_callback},
	{SMMU_L9_P22_IMGI_T1_N_B      , imgsys_ltraw_tfault_callback},
	{SMMU_L9_P23_SMTO_T1_B        , imgsys_ltraw_tfault_callback},
	{SMMU_L9_P24_TNCSO_T1_B       , imgsys_ltraw_tfault_callback},
	{SMMU_L9_P25_YUFETO_T1_B      , imgsys_ltraw_tfault_callback},
	{SMMU_L9_P26_DUMMY            , NULL},
	/* Larb10 -- 10*/
	{SMMU_L10_P0_IMGI_D1          , imgsys_dip_tfault_callback},
	{SMMU_L10_P1_IMGCI_D1         , imgsys_dip_tfault_callback},
	{SMMU_L10_P2_RECI_D1          , imgsys_dip_tfault_callback},
	{SMMU_L10_P3_RECI_D1_N        , imgsys_dip_tfault_callback},
	{SMMU_L10_P4_TNRCI_D1         , imgsys_dip_tfault_callback},
	{SMMU_L10_P5_TNRCI_D1_N       , imgsys_dip_tfault_callback},
	{SMMU_L10_P6_STG_D1           , imgsys_dip_tfault_callback},
	{SMMU_L10_P7_IMGDI_D1         , imgsys_dip_tfault_callback},
	{SMMU_L10_P8_DUMMY            , NULL},
	/* Larb11 -- 11*/
	{SMMU_L11_P0_WPE_RDMA_0       , imgsys_wpe_tfault_callback},
	{SMMU_L11_P1_WPE_RDMA_1       , imgsys_wpe_tfault_callback},
	{SMMU_L11_P2_WPE_RDMA_2       , imgsys_wpe_tfault_callback},
	{SMMU_L11_P3_PIMGI_P1         , imgsys_pqdip_tfault_callback},
	{SMMU_L11_P4_STG_P1           , imgsys_pqdip_tfault_callback},
	{SMMU_L11_P5_STS_P2           , imgsys_wpe_tfault_callback},
	{SMMU_L11_P6_STS_P3           , imgsys_pqdip_tfault_callback},
	{SMMU_L11_P7_OMC_RDMA_0       , NULL},
	{SMMU_L11_P8_OMC_RDMA_1       , NULL},
	{SMMU_L11_P9_STS_P4           , imgsys_wpe_tfault_callback},
	{SMMU_L11_P10_PIMGCI_P1       , imgsys_pqdip_tfault_callback},
	{SMMU_L11_P11_WPE_WDMA_0      , imgsys_wpe_tfault_callback},
	{SMMU_L11_P12_WROT_P1         , imgsys_pqdip_tfault_callback},
	{SMMU_L11_P13_IOSO_P1         , imgsys_pqdip_tfault_callback},
	{SMMU_L11_P14_OMC_WDMA_0      , NULL},
	{SMMU_L11_P15_DUMMY           , NULL},
	/* Larb15 -- 7*/
	{SMMU_L15_P0_VIPI_D1          , imgsys_dip_tfault_callback},
	{SMMU_L15_P1_VIPCI_D1         , imgsys_dip_tfault_callback},
	{SMMU_L15_P2_IMG3O_D1         , imgsys_dip_tfault_callback},
	{SMMU_L15_P3_IMG3CO_D1        , imgsys_dip_tfault_callback},
	{SMMU_L15_P4_IMG7O_D1         , imgsys_dip_tfault_callback},
	{SMMU_L15_P5_IMG7CO_D1        , imgsys_dip_tfault_callback},
	{SMMU_L15_P6_IMG2O_D1         , imgsys_dip_tfault_callback},
	{SMMU_L15_P7_IMG5O_D1         , imgsys_dip_tfault_callback},
	{SMMU_L15_P8_DHZAI_D1         , imgsys_dip_tfault_callback},
	{SMMU_L15_P9_STG_D4           , imgsys_dip_tfault_callback},
	{SMMU_L15_P10_DUMMY           , NULL},
	{SMMU_L15_P11_DUMMY           , NULL},
	/* Larb22 -- 11*/
	{SMMU_L22_P0_WPE_RDMA_0       , NULL},
	{SMMU_L22_P1_WPE_RDMA_1       , NULL},
	{SMMU_L22_P2_WPE_RDMA_2       , NULL},
	{SMMU_L22_P3_PIMGI_P1         , imgsys_pqdip_tfault_callback},
	{SMMU_L22_P4_STG_P1           , imgsys_pqdip_tfault_callback},
	{SMMU_L22_P5_STS_P2           , NULL},
	{SMMU_L22_P6_STS_P3           , imgsys_pqdip_tfault_callback},
	{SMMU_L22_P7_OMC_RDMA_0       , imgsys_omc_tfault_callback},
	{SMMU_L22_P8_OMC_RDMA_1       , imgsys_omc_tfault_callback},
	{SMMU_L22_P9_STS_P4           , NULL},
	{SMMU_L22_P10_PIMGCI_P1       , imgsys_pqdip_tfault_callback},
	{SMMU_L22_P11_WPE_WDMA_0      , NULL},
	{SMMU_L22_P12_WROT_P1         , imgsys_pqdip_tfault_callback},
	{SMMU_L22_P13_IOSO_P1         , imgsys_pqdip_tfault_callback},
	{SMMU_L22_P14_OMC_WDMA_0      , imgsys_omc_tfault_callback},
	{SMMU_L22_P15_DUMMY           , NULL},
	/* Larb23 -- 11*/
	{SMMU_L23_P0_WPE_RDMA_0       , imgsys_wpe_tfault_callback},
	{SMMU_L23_P1_WPE_RDMA_1       , imgsys_wpe_tfault_callback},
	{SMMU_L23_P2_WPE_RDMA_2       , imgsys_wpe_tfault_callback},
	{SMMU_L23_P3_PIMGI_P1         , NULL},
	{SMMU_L23_P4_STG_P1           , NULL},
	{SMMU_L23_P5_STS_P2           , imgsys_wpe_tfault_callback},
	{SMMU_L23_P6_STS_P3           , NULL},
	{SMMU_L23_P7_OMC_RDMA_0       , imgsys_omc_tfault_callback},
	{SMMU_L23_P8_OMC_RDMA_1       , imgsys_omc_tfault_callback},
	{SMMU_L23_P9_STS_P4           , NULL},
	{SMMU_L23_P10_PIMGCI_P1       , NULL},
	{SMMU_L23_P11_WPE_WDMA_0      , imgsys_wpe_tfault_callback},
	{SMMU_L23_P12_WROT_P1         , NULL},
	{SMMU_L23_P13_IOSO_P1         , NULL},
	{SMMU_L23_P14_OMC_WDMA_0      , imgsys_omc_tfault_callback},
	/* Larb12 */
	/* Larb28 */
	{SMMU_L28_P0_IMGI_T1_A        , imgsys_traw_tfault_callback},
	{SMMU_L28_P1_IMGCI_T1_A       , imgsys_traw_tfault_callback},
	{SMMU_L28_P2_YUVO_T1_A        , imgsys_traw_tfault_callback},
	{SMMU_L28_P3_YUVCO_T1_A       , imgsys_traw_tfault_callback},
	{SMMU_L28_P4_YUVO_T2_A        , imgsys_traw_tfault_callback},
	{SMMU_L28_P5_YUVBO_T2_A       , imgsys_traw_tfault_callback},
	{SMMU_L28_P6_STG_T1_A         , imgsys_traw_tfault_callback},
	{SMMU_L28_P7_IMGI_T1_N_A      , imgsys_traw_tfault_callback},
	{SMMU_L28_P8_DUMMY            , NULL},
	/* Larb38 -- 14*/
	{SMMU_L38_P0_TNRWI_D1         , imgsys_dip_tfault_callback},
	{SMMU_L38_P1_RECBI_D1         , imgsys_dip_tfault_callback},
	{SMMU_L38_P2_RECI_D3          , imgsys_dip_tfault_callback},
	{SMMU_L38_P3_SMTI_D1          , imgsys_dip_tfault_callback},
	{SMMU_L38_P4_SMTCI_D1         , imgsys_dip_tfault_callback},
	{SMMU_L38_P5_IMG4O_D1         , imgsys_dip_tfault_callback},
	{SMMU_L38_P6_IMG4CO_D1        , imgsys_dip_tfault_callback},
	{SMMU_L38_P7_TNRMO_D1         , imgsys_dip_tfault_callback},
	{SMMU_L38_P8_STG_D2           , imgsys_dip_tfault_callback},
	{SMMU_L38_P9_STG_D3           , imgsys_dip_tfault_callback},
	{SMMU_L38_P10_DUMMY           , NULL},
	{SMMU_L38_P11_SMTO_D1         , imgsys_dip_tfault_callback},
	{SMMU_L38_P12_SMTCO_D1        , imgsys_dip_tfault_callback},
	{SMMU_L38_P13_YUFETO_D1       , imgsys_dip_tfault_callback},
	{SMMU_L38_P14_DUMMY           , NULL},
	/* Larb39 -- 18*/
	{SMMU_L39_P0_EECSI_D1         , imgsys_dip_tfault_callback},
	{SMMU_L39_P1_SNRCSI_D1        , imgsys_dip_tfault_callback},
	{SMMU_L39_P2_SNRCSI_D1_N      , imgsys_dip_tfault_callback},
	{SMMU_L39_P3_SMTI_D4          , imgsys_dip_tfault_callback},
	{SMMU_L39_P4_SMTI_D10         , imgsys_dip_tfault_callback},
	{SMMU_L39_P5_SMTCI_D4         , imgsys_dip_tfault_callback},
	{SMMU_L39_P6_YUFETI_D2        , imgsys_dip_tfault_callback},
	{SMMU_L39_P7_BOKMI_D1         , imgsys_dip_tfault_callback},
	{SMMU_L39_P8_BOKMI_D1_N       , imgsys_dip_tfault_callback},
	{SMMU_L39_P9_CNRO_D1          , imgsys_dip_tfault_callback},
	{SMMU_L39_P10_BOKMO_D1        , imgsys_dip_tfault_callback},
	{SMMU_L39_P11_STG_D5          , imgsys_dip_tfault_callback},
	{SMMU_L39_P12_STG_D6          , imgsys_dip_tfault_callback},
	{SMMU_L39_P13_DUMMY           , NULL},
	{SMMU_L39_P14_TNCO_D1         , imgsys_dip_tfault_callback},
	{SMMU_L39_P15_SMTO_D4         , imgsys_dip_tfault_callback},
	{SMMU_L39_P16_SMTO_D10        , imgsys_dip_tfault_callback},
	{SMMU_L39_P17_SMTCO_D4        , imgsys_dip_tfault_callback},
	{SMMU_L39_P18_YUFETO_D2       , imgsys_dip_tfault_callback},
	{SMMU_L39_P19_DUMMY           , NULL},
	/* Larb40 */
	{SMMU_L40_P0_SMTI_T1_A        , imgsys_traw_tfault_callback},
	{SMMU_L40_P1_SMTI_T4_A        , imgsys_traw_tfault_callback},
	{SMMU_L40_P2_TNCSTI_T2_A      , imgsys_traw_tfault_callback},
	{SMMU_L40_P3_LTMSTI_T1_A      , imgsys_traw_tfault_callback},
	{SMMU_L40_P4_FBWO_T1_A        , imgsys_traw_tfault_callback},
	{SMMU_L40_P5_TIMGO_T1_A       , imgsys_traw_tfault_callback},
	{SMMU_L40_P6_TNCSTO_T1_A      , imgsys_traw_tfault_callback},
	{SMMU_L40_P7_YUFETI_T1_A      , imgsys_traw_tfault_callback},
	{SMMU_L40_P8_STG_T2_A         , imgsys_traw_tfault_callback},
	{SMMU_L40_P9_STG_T3_A         , imgsys_traw_tfault_callback},
	{SMMU_L40_P10_DUMMY           , NULL},
	{SMMU_L40_P11_TNCSO_T1_A      , imgsys_traw_tfault_callback},
	{SMMU_L40_P12_SMTO_T1_A       , imgsys_traw_tfault_callback},
	{SMMU_L40_P13_SMTO_T4_A       , imgsys_traw_tfault_callback},
	{SMMU_L40_P14_LTMSBO_T1_A     , imgsys_traw_tfault_callback},
	{SMMU_L40_P15_YUFETO_T1_A     , imgsys_traw_tfault_callback},
	{SMMU_L40_P16_DUMMY           , NULL},
};
#endif

#ifdef IMGSYS_TF_DUMP_8_P
#include <dt-bindings/memory/mt6899-larb-port.h>
static struct mtk_imgsys_port_table imgsys_dma_port_mt6899[] = {
	/* Larb9 -- 9*/
	{M4U_L9_P0_IMGI_T1_B         , imgsys_traw_tfault_callback},
	{M4U_L9_P1_IMGCI_T1_B        , imgsys_traw_tfault_callback},
	{M4U_L9_P2_SMTI_T1_B         , imgsys_traw_tfault_callback},
	{M4U_L9_P3_YUVO_T1_B         , imgsys_traw_tfault_callback},
	{M4U_L9_P4_YUVCO_T1_B        , imgsys_traw_tfault_callback},
	{M4U_L9_P5_YUVO_T2_B         , imgsys_traw_tfault_callback},
	{M4U_L9_P6_YUVBO_T2_B        , imgsys_traw_tfault_callback},
	{M4U_L9_P7_TNCSTO_T1_B       , imgsys_traw_tfault_callback},
	{M4U_L9_P8_TNCSTI_T2_B       , imgsys_traw_tfault_callback},
	{M4U_L9_P9_YUFETI_T1_B       , imgsys_traw_tfault_callback},
	{M4U_L9_P10_STG_T1_B         , imgsys_traw_tfault_callback},
	{M4U_L9_P11_STG_T2_B         , imgsys_traw_tfault_callback},
	{M4U_L9_P12_ME_RDMA_0        , ME_TranslationFault_callback},
	{M4U_L9_P13_ME_WDMA_0        , ME_TranslationFault_callback},
	{M4U_L9_P14_MEMMG_RDMA_0     , ME_TranslationFault_callback},
	{M4U_L9_P15_MEMMG_WDMA_0     , ME_TranslationFault_callback},
	{M4U_L9_P16_ME_2ND_RDMA_0    , ME_TranslationFault_callback},
	{M4U_L9_P17_ME_2ND_WDMA_0    , ME_TranslationFault_callback},
	{M4U_L9_P18_MEMMG_2ND_RDMA_0 , ME_TranslationFault_callback},
	{M4U_L9_P19_MEMMG_2ND_WDMA_0 , ME_TranslationFault_callback},
	{M4U_L9_P20_STSCMD_ME0       , ME_TranslationFault_callback},
	{M4U_L9_P21_STSCMD_ME1       , ME_TranslationFault_callback},
	{M4U_L9_P22_IMGI_T1_N_B      , imgsys_traw_tfault_callback},
	{M4U_L9_P23_SMTO_T1_B        , imgsys_traw_tfault_callback},
	{M4U_L9_P24_TNCSO_T1_B       , imgsys_traw_tfault_callback},
	{M4U_L9_P25_YUFETO_T1_B      , imgsys_traw_tfault_callback},
	{M4U_L9_P26_RESERVED            , NULL},
	/* Larb10 -- dummy*/
	/* Larb11 -- 16*/
	{M4U_L11_P0_WPE_RDMA_0        , imgsys_wpe_tfault_callback},
	{M4U_L11_P1_WPE_RDMA_1        , imgsys_wpe_tfault_callback},
	{M4U_L11_P2_WPE_RDMA_2        , imgsys_wpe_tfault_callback},
	{M4U_L11_P3_PIMGI_P1          , imgsys_pqdip_tfault_callback},
	{M4U_L11_P4_STG_P1            , imgsys_pqdip_tfault_callback},
	{M4U_L11_P5_STG_P2            , imgsys_wpe_tfault_callback},
	{M4U_L11_P6_STG_P3_WROT       , imgsys_pqdip_tfault_callback},
	{M4U_L11_P7_OMC_RDMA_0        , NULL},
	{M4U_L11_P8_OMC_RDMA_1        , NULL},
	{M4U_L11_P9_STG_P4            , imgsys_wpe_tfault_callback},
	{M4U_L11_P10_PIMGCI_P1        , imgsys_pqdip_tfault_callback},
	{M4U_L11_P11_WPE_WDMA_0       , imgsys_wpe_tfault_callback},
	{M4U_L11_P12_WROT_P1          , imgsys_pqdip_tfault_callback},
	{M4U_L11_P13_IOSO_P1          , imgsys_pqdip_tfault_callback},
	{M4U_L11_P14_OMC_WDMA_0       , NULL},
	{M4U_L11_P15_RESERVE          , NULL},
	/* Larb15 -- 32*/
	{M4U_L15_P0_VIPI_D1           , imgsys_dip_tfault_callback},
	{M4U_L15_P1_VIPCI_D1          , imgsys_dip_tfault_callback},
	{M4U_L15_P2_IMG3O_D1          , imgsys_dip_tfault_callback},
	{M4U_L15_P3_IMG3CO_D1         , imgsys_dip_tfault_callback},
	{M4U_L15_P4_IMG7O_D1          , imgsys_dip_tfault_callback},
	{M4U_L15_P5_IMG7CO_D1         , imgsys_dip_tfault_callback},
	{M4U_L15_P6_IMG2O_D1          , imgsys_dip_tfault_callback},
	{M4U_L15_P7_IMG5O_D1          , imgsys_dip_tfault_callback},
	{M4U_L15_P8_DHZAI_D1          , imgsys_dip_tfault_callback},
	{M4U_L15_P9_STG_D4            , imgsys_dip_tfault_callback},
	{M4U_L15_P10_RESERVED         , NULL},
	{M4U_L15_P11_RESERVED         , NULL},
	{M4U_L15_P12_EECSI_D1         , imgsys_dip_tfault_callback},
	{M4U_L15_P13_SNRCSI_D1        , imgsys_dip_tfault_callback},
	{M4U_L15_P14_SNRCSI_D1_N      , imgsys_dip_tfault_callback},
	{M4U_L15_P15_SMTI_D4          , imgsys_dip_tfault_callback},
	{M4U_L15_P16_SMTI_D10         , imgsys_dip_tfault_callback},
	{M4U_L15_P17_SMTCI_D4         , imgsys_dip_tfault_callback},
	{M4U_L15_P18_YUFETI_D2        , imgsys_dip_tfault_callback},
	{M4U_L15_P19_BOKMI_D1         , imgsys_dip_tfault_callback},
	{M4U_L15_P20_BOKMI_D1_N       , imgsys_dip_tfault_callback},
	{M4U_L15_P21_CNRO_D1          , imgsys_dip_tfault_callback},
	{M4U_L15_P22_BOKMO_D1         , imgsys_dip_tfault_callback},
	{M4U_L15_P23_STG_D5           , imgsys_dip_tfault_callback},
	{M4U_L15_P24_STG_D6           , imgsys_dip_tfault_callback},
	{M4U_L15_P25_RESERVED         , NULL},
	{M4U_L15_P26_TNCO_D1          , imgsys_dip_tfault_callback},
	{M4U_L15_P27_SMTO_D4          , imgsys_dip_tfault_callback},
	{M4U_L15_P28_SMTO_D10         , imgsys_dip_tfault_callback},
	{M4U_L15_P29_SMTCO_D4         , imgsys_dip_tfault_callback},
	{M4U_L15_P30_YUFETO_D2        , imgsys_dip_tfault_callback},
	{M4U_L15_P31_RESERVED         , NULL},
	/* Larb22 -- 16*/
	{M4U_L22_P0_WPE_RDMA_0        , NULL},
	{M4U_L22_P1_WPE_RDMA_1        , NULL},
	{M4U_L22_P2_WPE_RDMA_2        , NULL},
	{M4U_L22_P3_PIMGI_P1          , imgsys_pqdip_tfault_callback},
	{M4U_L22_P4_STG_P1            , imgsys_pqdip_tfault_callback},
	{M4U_L22_P5_STG_P2            , NULL},
	{M4U_L22_P6_STG_P3_WROT       , imgsys_pqdip_tfault_callback},
	{M4U_L22_P7_OMC_RDMA_0        , imgsys_omc_tfault_callback},
	{M4U_L22_P8_OMC_RDMA_1        , imgsys_omc_tfault_callback},
	{M4U_L22_P9_STG_P4            , NULL},
	{M4U_L22_P10_PIMGCI_P1        , imgsys_pqdip_tfault_callback},
	{M4U_L22_P11_WPE_WDMA_0       , NULL},
	{M4U_L22_P12_WROT_P1          , imgsys_pqdip_tfault_callback},
	{M4U_L22_P13_IOSO_P1          , imgsys_pqdip_tfault_callback},
	{M4U_L22_P14_OMC_WDMA_0       , imgsys_omc_tfault_callback},
	{M4U_L22_P15_RESERVE          , NULL},
	/* Larb23 -- 11*/
	{M4U_L23_P0_WPE_RDMA_0       , imgsys_wpe_tfault_callback},
	{M4U_L23_P1_WPE_RDMA_1       , imgsys_wpe_tfault_callback},
	{M4U_L23_P2_WPE_RDMA_2       , imgsys_wpe_tfault_callback},
	{M4U_L23_P3_PIMGI_P1         , NULL},
	{M4U_L23_P4_STG_P1           , NULL},
	{M4U_L23_P5_STG_P2           , imgsys_wpe_tfault_callback},
	{M4U_L23_P6_STG_P3_WROT      , NULL},
	{M4U_L23_P7_OMC_RDMA_0       , imgsys_omc_tfault_callback},
	{M4U_L23_P8_OMC_RDMA_1       , imgsys_omc_tfault_callback},
	{M4U_L23_P9_STG_P4           , NULL},
	{M4U_L23_P10_PIMGCI_P1       , NULL},
	{M4U_L23_P11_WPE_WDMA_0      , imgsys_wpe_tfault_callback},
	{M4U_L23_P12_WROT_P1         , NULL},
	{M4U_L23_P13_IOSO_P1         , NULL},
	{M4U_L23_P14_OMC_WDMA_0      , imgsys_omc_tfault_callback},
	/* Larb12 */
	/* Larb28 */
	{M4U_L28_P0_IMGI_T1_A        , imgsys_traw_tfault_callback},
	{M4U_L28_P1_IMGCI_T1_A       , imgsys_traw_tfault_callback},
	{M4U_L28_P2_YUVO_T1_A        , imgsys_traw_tfault_callback},
	{M4U_L28_P3_YUVCO_T1_A       , imgsys_traw_tfault_callback},
	{M4U_L28_P4_YUVO_T2_A        , imgsys_traw_tfault_callback},
	{M4U_L28_P5_YUVBO_T2_A       , imgsys_traw_tfault_callback},
	{M4U_L28_P6_STG_T1_A         , imgsys_traw_tfault_callback},
	{M4U_L28_P7_IMGI_T1_N_A      , imgsys_traw_tfault_callback},
	{M4U_L28_P8_RESERVED            , NULL},
	{M4U_L28_P9_RESERVED        , imgsys_traw_tfault_callback},
	{M4U_L28_P10_SMTI_T1_A       , imgsys_traw_tfault_callback},
	{M4U_L28_P11_SMTI_T4_A        , imgsys_traw_tfault_callback},
	{M4U_L28_P12_TNCSTI_T2_A       , imgsys_traw_tfault_callback},
	{M4U_L28_P13_LTMSTI_T1_A        , imgsys_traw_tfault_callback},
	{M4U_L28_P14_FBWO_T1_A       , imgsys_traw_tfault_callback},
	{M4U_L28_P15_TIMGO_T1_A         , imgsys_traw_tfault_callback},
	{M4U_L28_P16_TNCSTO_T1_A      , imgsys_traw_tfault_callback},
	{M4U_L28_P17_YUFETI_T1_A            , imgsys_traw_tfault_callback},
	{M4U_L28_P18_STG_T2_A        , imgsys_traw_tfault_callback},
	{M4U_L28_P19_STG_T3_A       , imgsys_traw_tfault_callback},
	{M4U_L28_P20_RESERVED        , NULL},
	{M4U_L28_P21_TNCSO_T1_A       , imgsys_traw_tfault_callback},
	{M4U_L28_P22_SMTO_T1_A        , imgsys_traw_tfault_callback},
	{M4U_L28_P23_SMTO_T4_A       , imgsys_traw_tfault_callback},
	{M4U_L28_P25_YUFETO_T1_A         , imgsys_traw_tfault_callback},
	{M4U_L28_P26_RESERVED      , NULL},
	{M4U_L28_P27_RESERVED            , NULL},
	/* Larb38 -- 26*/
	{M4U_L38_P0_TNRWI_D1          , imgsys_dip_tfault_callback},
	{M4U_L38_P1_RECBI_D1          , imgsys_dip_tfault_callback},
	{M4U_L38_P2_RECI_D3           , imgsys_dip_tfault_callback},
	{M4U_L38_P3_SMTI_D1           , imgsys_dip_tfault_callback},
	{M4U_L38_P4_SMTCI_D1          , imgsys_dip_tfault_callback},
	{M4U_L38_P5_IMG4O_D1          , imgsys_dip_tfault_callback},
	{M4U_L38_P6_IMG4CO_D1         , imgsys_dip_tfault_callback},
	{M4U_L38_P7_TNRMO_D1          , imgsys_dip_tfault_callback},
	{M4U_L38_P8_STG_D2            , imgsys_dip_tfault_callback},
	{M4U_L38_P9_STG_D3            , imgsys_dip_tfault_callback},
	{M4U_L38_P10_RESERVED         , NULL},
	{M4U_L38_P11_SMTO_D1          , imgsys_dip_tfault_callback},
	{M4U_L38_P12_SMTCO_D1         , imgsys_dip_tfault_callback},
	{M4U_L38_P13_YUFETO_D1        , imgsys_dip_tfault_callback},
	{M4U_L38_P14_RESERVED         , NULL},
	{M4U_L38_P15_RESERVED         , NULL},
	{M4U_L38_P16_IMGI_D1          , imgsys_dip_tfault_callback},
	{M4U_L38_P17_IMGCI_D1         , imgsys_dip_tfault_callback},
	{M4U_L38_P18_RECI_D1          , imgsys_dip_tfault_callback},
	{M4U_L38_P19_RECI_D1_N        , imgsys_dip_tfault_callback},
	{M4U_L38_P20_TNRCI_D1         , imgsys_dip_tfault_callback},
	{M4U_L38_P21_TNRCI_D1_N       , imgsys_dip_tfault_callback},
	{M4U_L38_P22_STG_D1           , imgsys_dip_tfault_callback},
	{M4U_L38_P23_IMGDI_D1         , imgsys_dip_tfault_callback},
	{M4U_L38_P24_RESERVED         , NULL},
	{M4U_L38_P25_RESERVED         , NULL},
	/* Larb39 -- dummy*/
};
#endif

#endif /* _MTK_IMGSYS_PORT_H_ */
