# SPDX-License-Identifier: GPL-2.0

include $(wildcard $(KERNEL_SRC)/$(DEVICE_MODULES_REL_DIR)/Makefile.include)

KBUILD_OPTIONS += BUILD_RULE=OOT
KBUILD_OPTIONS += CONFIG_MALI_MEMORY_GROUP_MANAGER=y
KBUILD_OPTIONS += CONFIG_MALI_PROTECTED_MEMORY_ALLOCATOR=y
KBUILD_OPTIONS += CONFIG_DMA_SHARED_BUFFER_TEST_EXPORTER=y

modules modules_install clean:
	$(MAKE) -C $(KERNEL_SRC) M=$(M) $(KBUILD_OPTIONS) EXTRA_CFLAGS="$(EXTRA_CFLAGS)" KBUILD_EXTRA_SYMBOLS="$(EXTRA_SYMBOLS)" $(@)
