// SPDX-License-Identifier: GPL-2.0
/*
 * Copyright (c) 2020 MediaTek Inc.
 */

#ifndef __MTK_MFG_COUNTER_H_
#define __MTK_MFG_COUNTER_H_

#include <mtk_gpu_utility.h>
#include <mtk_gpufreq.h>

#define MALI_HWC_TYPES					4

#if IS_ENABLED(CONFIG_MALI_PMU_CPB128)
#define MALI_COUNTERS_PER_BLOCK			128
#else
#define MALI_COUNTERS_PER_BLOCK			64
#endif

#if IS_ENABLED(CONFIG_MALI_PMU_LP4)
#define L2_CNT 4
#else
#define L2_CNT 1
#endif

enum {
	PMU_OK = 0,
	PMU_NG = 1,
	/* reset PMU value if needed */
	PMU_RESET_VALUE = 2,
};

extern int (*mtk_get_gpu_pmu_init_fp)(struct GPU_PMU *pmus, int pmu_size, int *ret_size);
extern int (*mtk_get_gpu_pmu_deinit_fp)(void);
extern int (*mtk_get_gpu_pmu_swapnreset_fp)(struct GPU_PMU *pmus, int pmu_size);
extern int (*mtk_get_gpu_pmu_swapnreset_stop_fp)(void);
/* Need to get current gpu freq from GPU DVFS module */

void mtk_mfg_counter_init(void);
void mtk_mfg_counter_destroy(void);
int gator_gpu_pmu_init(void);
//stall counter
int mtk_gpu_stall_create_subfs(void);
void mtk_gpu_stall_delete_subfs(void);
void mtk_gpu_stall_start(void);
void mtk_gpu_stall_stop(void);
void mtk_GPU_STALL_RAW(unsigned int *diff, int size);

//MTK PMU COUNTER
typedef enum {
	VINSTR_GPU_FREQ,
	VINSTR_GPU_VOLT,
	VINSTR_GPU_LOADING,
	VINSTR_GPU_ACTIVE,
	VINSTR_EXEC_INSTR_FMA,
	VINSTR_EXEC_INSTR_CVT,
	VINSTR_EXEC_INSTR_SFU,
	VINSTR_EXEC_INSTR_MSG,
	VINSTR_EXEC_CORE_ACTIVE,
	VINSTR_FRAG_ACTIVE,
	VINSTR_TILER_ACTIVE,
	VINSTR_VARY_SLOT_32,
	VINSTR_VARY_SLOT_16,
	VINSTR_TEX_FILT_NUM_OPERATIONS,
	VINSTR_LS_MEM_READ_FULL,
	VINSTR_LS_MEM_WRITE_FULL,
	VINSTR_LS_MEM_READ_SHORT,
	VINSTR_LS_MEM_WRITE_SHORT,
	VINSTR_L2_EXT_WRITE_BEATS,
	VINSTR_L2_EXT_READ_BEATS,
	VINSTR_L2_EXT_RRESP_0_127,
	VINSTR_L2_EXT_RRESP_128_191,
	VINSTR_L2_EXT_RRESP_192_255,
	VINSTR_L2_EXT_RRESP_256_319,
	VINSTR_L2_EXT_RRESP_320_383,
	VINSTR_L2_ANY_LOOKUP,
	VINSTR_JS0_ACTIVE,
	VINSTR_JS1_ACTIVE,
	VINSTR_STALL0,
	VINSTR_STALL1,
	VINSTR_STALL2,
	VINSTR_STALL3,
	VINSTR_TRIANGLES,
	VINSTR_POINTS,
	VINSTR_LINES,
	VINSTR_LS_MEM_ATOMIC,
	VINSTR_PERF_COUNTER_LAST
} mtk_vinstr_perf_counter;

/*
count_bit[9:11] = index_cnt
count_bit[0:8] = index
*/
static unsigned int gpu_pmu_index[] = {

#if IS_ENABLED(CONFIG_MALI_PMU_CPB128)
			[VINSTR_GPU_ACTIVE] = 4
			, [VINSTR_EXEC_INSTR_FMA] = 795
			, [VINSTR_EXEC_INSTR_CVT] = 796
			, [VINSTR_EXEC_INSTR_SFU] = 797
			, [VINSTR_EXEC_INSTR_MSG] = 798
			, [VINSTR_EXEC_CORE_ACTIVE] = 794
			, [VINSTR_FRAG_ACTIVE] = 772
			, [VINSTR_TILER_ACTIVE] = 132
			, [VINSTR_VARY_SLOT_32] = 818
			, [VINSTR_VARY_SLOT_16] = 819
			, [VINSTR_TEX_FILT_NUM_OPERATIONS] = 807
			, [VINSTR_LS_MEM_READ_FULL] = 812
			, [VINSTR_LS_MEM_WRITE_FULL] = 814
			, [VINSTR_LS_MEM_READ_SHORT] = 813
			, [VINSTR_LS_MEM_WRITE_SHORT] = 815
			, [VINSTR_L2_EXT_WRITE_BEATS] = 303
			, [VINSTR_L2_EXT_READ_BEATS] = 288
			, [VINSTR_L2_EXT_RRESP_0_127] = 293
			, [VINSTR_L2_EXT_RRESP_128_191] = 294
			, [VINSTR_L2_EXT_RRESP_192_255] = 295
			, [VINSTR_L2_EXT_RRESP_256_319] = 296
			, [VINSTR_L2_EXT_RRESP_320_383] = 297
			, [VINSTR_L2_ANY_LOOKUP] = 281
			, [VINSTR_JS0_ACTIVE] = 0
			, [VINSTR_JS1_ACTIVE] = 0
			, [VINSTR_TRIANGLES] = 134
			, [VINSTR_POINTS] = 136
			, [VINSTR_LINES] = 135
			, [VINSTR_LS_MEM_ATOMIC] = 816
	
#elif IS_ENABLED(CONFIG_MALI_PMU_LP4)

			  [VINSTR_GPU_ACTIVE] = 4
			, [VINSTR_EXEC_INSTR_FMA] = 411
			, [VINSTR_EXEC_INSTR_CVT] = 412
			, [VINSTR_EXEC_INSTR_SFU] = 413
			, [VINSTR_EXEC_INSTR_MSG] = 414
			, [VINSTR_EXEC_CORE_ACTIVE] = 410
			, [VINSTR_FRAG_ACTIVE] = 388
			, [VINSTR_TILER_ACTIVE] = 68
			, [VINSTR_VARY_SLOT_32] = 434
			, [VINSTR_VARY_SLOT_16] = 435
			, [VINSTR_TEX_FILT_NUM_OPERATIONS] = 423
			, [VINSTR_LS_MEM_READ_FULL] = 428
			, [VINSTR_LS_MEM_WRITE_FULL] = 430
			, [VINSTR_LS_MEM_READ_SHORT] = 429
			, [VINSTR_LS_MEM_WRITE_SHORT] = 431
			, [VINSTR_L2_EXT_WRITE_BEATS] = 175
			, [VINSTR_L2_EXT_READ_BEATS] = 160
			, [VINSTR_L2_EXT_RRESP_0_127] = 165
			, [VINSTR_L2_EXT_RRESP_128_191] = 166
			, [VINSTR_L2_EXT_RRESP_192_255] = 167
			, [VINSTR_L2_EXT_RRESP_256_319] = 168
			, [VINSTR_L2_EXT_RRESP_320_383] = 169
			, [VINSTR_L2_ANY_LOOKUP] = 153
			, [VINSTR_JS0_ACTIVE] = 0
			, [VINSTR_JS1_ACTIVE] = 0
			, [VINSTR_TRIANGLES] = 70
			, [VINSTR_POINTS] = 72
			, [VINSTR_LINES] = 71
			, [VINSTR_LS_MEM_ATOMIC] = 432

#else

		#if IS_ENABLED(CONFIG_MALI_CSF_SUPPORT)
			  [VINSTR_GPU_ACTIVE] = 6
			, [VINSTR_EXEC_INSTR_FMA] = 411
			, [VINSTR_EXEC_INSTR_CVT] = 412
			, [VINSTR_EXEC_INSTR_SFU] = 413
			, [VINSTR_EXEC_INSTR_MSG] = 414
			, [VINSTR_EXEC_CORE_ACTIVE] = 410
			, [VINSTR_FRAG_ACTIVE] = 388
			, [VINSTR_TILER_ACTIVE] = 68
			, [VINSTR_VARY_SLOT_32] = 434
			, [VINSTR_VARY_SLOT_16] = 435
			, [VINSTR_TEX_FILT_NUM_OPERATIONS] = 423
			, [VINSTR_LS_MEM_READ_FULL] = 428
			, [VINSTR_LS_MEM_WRITE_FULL] = 430
			, [VINSTR_LS_MEM_READ_SHORT] = 429
			, [VINSTR_LS_MEM_WRITE_SHORT] = 431
			, [VINSTR_L2_EXT_WRITE_BEATS] = 175
			, [VINSTR_L2_EXT_READ_BEATS] = 160
			, [VINSTR_L2_EXT_RRESP_0_127] = 165
			, [VINSTR_L2_EXT_RRESP_128_191] = 166
			, [VINSTR_L2_EXT_RRESP_192_255] = 167
			, [VINSTR_L2_EXT_RRESP_256_319] = 168
			, [VINSTR_L2_EXT_RRESP_320_383] = 169
			, [VINSTR_L2_ANY_LOOKUP] = 153
			, [VINSTR_JS0_ACTIVE] = 10
			, [VINSTR_JS1_ACTIVE] = 18
			, [VINSTR_TRIANGLES] = 70
			, [VINSTR_POINTS] = 72
			, [VINSTR_LINES] = 71
			, [VINSTR_LS_MEM_ATOMIC] = 432

		#else
			 [VINSTR_GPU_ACTIVE] = 6
			, [VINSTR_EXEC_INSTR_FMA] = 219
			, [VINSTR_EXEC_INSTR_CVT] = 220
			, [VINSTR_EXEC_INSTR_SFU] = 221
			, [VINSTR_EXEC_INSTR_MSG] = 222
			, [VINSTR_EXEC_CORE_ACTIVE] = 218
			, [VINSTR_FRAG_ACTIVE] = 196
			, [VINSTR_TILER_ACTIVE] = 68
			, [VINSTR_VARY_SLOT_32] = 242
			, [VINSTR_VARY_SLOT_16] = 243
			, [VINSTR_TEX_FILT_NUM_OPERATIONS] = 231
			, [VINSTR_LS_MEM_READ_FULL] = 236
			, [VINSTR_LS_MEM_WRITE_FULL] = 238
			, [VINSTR_LS_MEM_READ_SHORT] = 237
			, [VINSTR_LS_MEM_WRITE_SHORT] = 239
			, [VINSTR_L2_EXT_WRITE_BEATS] = 175
			, [VINSTR_L2_EXT_READ_BEATS] = 160
			, [VINSTR_L2_EXT_RRESP_0_127] = 165
			, [VINSTR_L2_EXT_RRESP_128_191] = 166
			, [VINSTR_L2_EXT_RRESP_192_255] = 167
			, [VINSTR_L2_EXT_RRESP_256_319] = 168
			, [VINSTR_L2_EXT_RRESP_320_383] = 169
			, [VINSTR_L2_ANY_LOOKUP] = 153
			, [VINSTR_JS0_ACTIVE] = 10
			, [VINSTR_JS1_ACTIVE] = 18
			, [VINSTR_TRIANGLES] = 70
			, [VINSTR_POINTS] = 72
			, [VINSTR_LINES] = 71
			, [VINSTR_LS_MEM_ATOMIC] = 240

		#endif
#endif

};


#endif
