/*
 * Copyright (C) 2019 MediaTek Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See http://www.gnu.org/licenses/gpl-2.0.html for more details.
 */
#ifndef __GPS_RGU_ON_REGS_H__
#define __GPS_RGU_ON_REGS_H__

#define GPS_RGU_ON_BASE                                        0x80000000

#define GPS_RGU_ON_GPS_TOP_RGU_CR_ADDR                         (GPS_RGU_ON_BASE + 0x0004)
#define GPS_RGU_ON_GPS_TOP_DSLEEP_MANUAL_ADDR                  (GPS_RGU_ON_BASE + 0x0008)
#define GPS_RGU_ON_GPS_TOP_RGU_DELAY_ADDR                      (GPS_RGU_ON_BASE + 0x000C)
#define GPS_RGU_ON_BGF_TOP_PWR_ACK_ST_ADDR                     (GPS_RGU_ON_BASE + 0x0010)
#define GPS_RGU_ON_GPS_L1_CR_ADDR                              (GPS_RGU_ON_BASE + 0x0014)
#define GPS_RGU_ON_GPS_L1_PWR_ST_ADDR                          (GPS_RGU_ON_BASE + 0x0018)
#define GPS_RGU_ON_GPS_L1_PON_S_EN_ADDR                        (GPS_RGU_ON_BASE + 0x001C)
#define GPS_RGU_ON_GPS_L1_RGU_RESERVED_ADDR                    (GPS_RGU_ON_BASE + 0x0030)
#define GPS_RGU_ON_GPS_L1_CROM_PDN_EN_ADDR                     (GPS_RGU_ON_BASE + 0x0040)
#define GPS_RGU_ON_GPS_L1_DSPPROM_PDN_EN_ADDR                  (GPS_RGU_ON_BASE + 0x0044)
#define GPS_RGU_ON_GPS_L1_DSPPRAM_PDN_EN_ADDR                  (GPS_RGU_ON_BASE + 0x0048)
#define GPS_RGU_ON_GPS_L1_DSPPRAM_SLP_EN_ADDR                  (GPS_RGU_ON_BASE + 0x004C)
#define GPS_RGU_ON_GPS_L1_DSPXRAM_PDN_EN_ADDR                  (GPS_RGU_ON_BASE + 0x0050)
#define GPS_RGU_ON_GPS_L1_DSPXRAM_SLP_EN_ADDR                  (GPS_RGU_ON_BASE + 0x0054)
#define GPS_RGU_ON_GPS_L1_DSPYRAM_PDN_EN_ADDR                  (GPS_RGU_ON_BASE + 0x0058)
#define GPS_RGU_ON_GPS_L1_DSPYRAM_SLP_EN_ADDR                  (GPS_RGU_ON_BASE + 0x005C)
#define GPS_RGU_ON_GPS_L1_DSPURAM_PDN_EN_ADDR                  (GPS_RGU_ON_BASE + 0x0060)
#define GPS_RGU_ON_GPS_L1_DSPURAM_SLP_EN_ADDR                  (GPS_RGU_ON_BASE + 0x0064)
#define GPS_RGU_ON_GPS_L1_CROM_PDN_ADDR                        (GPS_RGU_ON_BASE + 0x0068)
#define GPS_RGU_ON_GPS_L1_DSPPROM_PDN_ADDR                     (GPS_RGU_ON_BASE + 0x006C)
#define GPS_RGU_ON_GPS_L1_DSPPRAM_PDN_ADDR                     (GPS_RGU_ON_BASE + 0x0070)
#define GPS_RGU_ON_GPS_L1_DSPPRAM_SLP_ADDR                     (GPS_RGU_ON_BASE + 0x0074)
#define GPS_RGU_ON_GPS_L1_DSPPRAM_ISO_ADDR                     (GPS_RGU_ON_BASE + 0x0078)
#define GPS_RGU_ON_GPS_L1_DSPPRAM_ISOINT_ADDR                  (GPS_RGU_ON_BASE + 0x007C)
#define GPS_RGU_ON_GPS_L1_DSPXRAM_PDN_ADDR                     (GPS_RGU_ON_BASE + 0x0080)
#define GPS_RGU_ON_GPS_L1_DSPXRAM_SLP_ADDR                     (GPS_RGU_ON_BASE + 0x0084)
#define GPS_RGU_ON_GPS_L1_DSPXRAM_ISO_ADDR                     (GPS_RGU_ON_BASE + 0x0088)
#define GPS_RGU_ON_GPS_L1_DSPXRAM_ISOINT_ADDR                  (GPS_RGU_ON_BASE + 0x008C)
#define GPS_RGU_ON_GPS_L1_DSPYRAM_PDN_ADDR                     (GPS_RGU_ON_BASE + 0x0090)
#define GPS_RGU_ON_GPS_L1_DSPYRAM_SLP_ADDR                     (GPS_RGU_ON_BASE + 0x0094)
#define GPS_RGU_ON_GPS_L1_DSPYRAM_ISO_ADDR                     (GPS_RGU_ON_BASE + 0x0098)
#define GPS_RGU_ON_GPS_L1_DSPYRAM_ISOINT_ADDR                  (GPS_RGU_ON_BASE + 0x009C)
#define GPS_RGU_ON_GPS_L1_DSPURAM_PDN_ADDR                     (GPS_RGU_ON_BASE + 0x00A0)
#define GPS_RGU_ON_GPS_L1_DSPURAM_SLP_ADDR                     (GPS_RGU_ON_BASE + 0x00A4)
#define GPS_RGU_ON_GPS_L1_DSPURAM_ISO_ADDR                     (GPS_RGU_ON_BASE + 0x00A8)
#define GPS_RGU_ON_GPS_L1_DSPURAM_ISOINT_ADDR                  (GPS_RGU_ON_BASE + 0x00AC)
#define GPS_RGU_ON_GPS_L1_CROM_PDN_STAT_ADDR                   (GPS_RGU_ON_BASE + 0x00B0)
#define GPS_RGU_ON_GPS_L1_DSPPROM_PDN_STAT_ADDR                (GPS_RGU_ON_BASE + 0x00B4)
#define GPS_RGU_ON_GPS_L1_DSPPRAM_PDN_STAT_ADDR                (GPS_RGU_ON_BASE + 0x00C0)
#define GPS_RGU_ON_GPS_L1_DSPPRAM_SLP_STAT_ADDR                (GPS_RGU_ON_BASE + 0x00C4)
#define GPS_RGU_ON_GPS_L1_DSPPRAM_ISO_STAT_ADDR                (GPS_RGU_ON_BASE + 0x00C8)
#define GPS_RGU_ON_GPS_L1_DSPPRAM_ISOINT_STAT_ADDR             (GPS_RGU_ON_BASE + 0x00CC)
#define GPS_RGU_ON_GPS_L1_DSPXRAM_PDN_STAT_ADDR                (GPS_RGU_ON_BASE + 0x00D0)
#define GPS_RGU_ON_GPS_L1_DSPXRAM_SLP_STAT_ADDR                (GPS_RGU_ON_BASE + 0x00D4)
#define GPS_RGU_ON_GPS_L1_DSPXRAM_ISO_STAT_ADDR                (GPS_RGU_ON_BASE + 0x00D8)
#define GPS_RGU_ON_GPS_L1_DSPXRAM_ISOINT_STAT_ADDR             (GPS_RGU_ON_BASE + 0x00DC)
#define GPS_RGU_ON_GPS_L1_DSPYRAM_PDN_STAT_ADDR                (GPS_RGU_ON_BASE + 0x00E0)
#define GPS_RGU_ON_GPS_L1_DSPYRAM_SLP_STAT_ADDR                (GPS_RGU_ON_BASE + 0x00E4)
#define GPS_RGU_ON_GPS_L1_DSPYRAM_ISO_STAT_ADDR                (GPS_RGU_ON_BASE + 0x00E8)
#define GPS_RGU_ON_GPS_L1_DSPYRAM_ISOINT_STAT_ADDR             (GPS_RGU_ON_BASE + 0x00EC)
#define GPS_RGU_ON_GPS_L1_DSPURAM_PDN_STAT_ADDR                (GPS_RGU_ON_BASE + 0x00F0)
#define GPS_RGU_ON_GPS_L1_DSPURAM_SLP_STAT_ADDR                (GPS_RGU_ON_BASE + 0x00F4)
#define GPS_RGU_ON_GPS_L1_DSPURAM_ISO_STAT_ADDR                (GPS_RGU_ON_BASE + 0x00F8)
#define GPS_RGU_ON_GPS_L1_DSPURAM_ISOINT_STAT_ADDR             (GPS_RGU_ON_BASE + 0x00FC)
#define GPS_RGU_ON_GPS_L1_CROM_RST_ADDR                        (GPS_RGU_ON_BASE + 0x0100)
#define GPS_RGU_ON_GPS_L1_CHN_MEM_DYN_OFF_ADDR                 (GPS_RGU_ON_BASE + 0x0104)
#define GPS_RGU_ON_GPS_L1_CH2_DELAY_CHAIN_MASK_ADDR            (GPS_RGU_ON_BASE + 0x0108)
#define GPS_RGU_ON_GPS_L1_CH3_DELAY_CHAIN_MASK_ADDR            (GPS_RGU_ON_BASE + 0x010C)
#define GPS_RGU_ON_GPS_L1_CH4_DELAY_CHAIN_MASK_ADDR            (GPS_RGU_ON_BASE + 0x0110)
#define GPS_RGU_ON_GPS_L1_CH11_DELAY_CHAIN_MASK_ADDR           (GPS_RGU_ON_BASE + 0x012C)
#define GPS_RGU_ON_GPS_L1_CH0_MEM_PDN_STAT_ADDR                (GPS_RGU_ON_BASE + 0x0130)
#define GPS_RGU_ON_GPS_L1_CH1_MEM_PDN_STAT_ADDR                (GPS_RGU_ON_BASE + 0x0134)
#define GPS_RGU_ON_GPS_L1_CH2_MEM_PDN_STAT_ADDR                (GPS_RGU_ON_BASE + 0x0138)
#define GPS_RGU_ON_GPS_L1_CH3_MEM_PDN_STAT_ADDR                (GPS_RGU_ON_BASE + 0x013C)
#define GPS_RGU_ON_GPS_L1_CH4_MEM_PDN_STAT_ADDR                (GPS_RGU_ON_BASE + 0x0140)
#define GPS_RGU_ON_GPS_L1_CH11_MEM_PDN_STAT_ADDR               (GPS_RGU_ON_BASE + 0x015C)
#define GPS_RGU_ON_GPS_L1_DLY_CHAIN_CTL_ADDR                   (GPS_RGU_ON_BASE + 0x0160)
#define GPS_RGU_ON_GPS_L1_MEM_DLY_CTL_ADDR                     (GPS_RGU_ON_BASE + 0x0164)
#define GPS_RGU_ON_GPS_L5_CR_ADDR                              (GPS_RGU_ON_BASE + 0x0214)
#define GPS_RGU_ON_GPS_L5_PWR_ST_ADDR                          (GPS_RGU_ON_BASE + 0x0218)
#define GPS_RGU_ON_GPS_L5_PON_S_EN_ADDR                        (GPS_RGU_ON_BASE + 0x021C)
#define GPS_RGU_ON_GPS_L5_RGU_RESERVED_ADDR                    (GPS_RGU_ON_BASE + 0x0230)
#define GPS_RGU_ON_GPS_L5_SEC_CROM_PDN_EN_ADDR                 (GPS_RGU_ON_BASE + 0x0240)
#define GPS_RGU_ON_GPS_L5_DSPPROM_PDN_EN_ADDR                  (GPS_RGU_ON_BASE + 0x0244)
#define GPS_RGU_ON_GPS_L5_DSPPRAM_PDN_EN_ADDR                  (GPS_RGU_ON_BASE + 0x0248)
#define GPS_RGU_ON_GPS_L5_DSPPRAM_SLP_EN_ADDR                  (GPS_RGU_ON_BASE + 0x024C)
#define GPS_RGU_ON_GPS_L5_DSPXRAM_PDN_EN_ADDR                  (GPS_RGU_ON_BASE + 0x0250)
#define GPS_RGU_ON_GPS_L5_DSPXRAM_SLP_EN_ADDR                  (GPS_RGU_ON_BASE + 0x0254)
#define GPS_RGU_ON_GPS_L5_DSPYRAM_PDN_EN_ADDR                  (GPS_RGU_ON_BASE + 0x0258)
#define GPS_RGU_ON_GPS_L5_DSPYRAM_SLP_EN_ADDR                  (GPS_RGU_ON_BASE + 0x025C)
#define GPS_RGU_ON_GPS_L5_DSPURAM_PDN_EN_ADDR                  (GPS_RGU_ON_BASE + 0x0260)
#define GPS_RGU_ON_GPS_L5_DSPURAM_SLP_EN_ADDR                  (GPS_RGU_ON_BASE + 0x0264)
#define GPS_RGU_ON_GPS_L5_SEC_CROM_PDN_ADDR                    (GPS_RGU_ON_BASE + 0x0268)
#define GPS_RGU_ON_GPS_L5_DSPPROM_PDN_ADDR                     (GPS_RGU_ON_BASE + 0x026C)
#define GPS_RGU_ON_GPS_L5_DSPPRAM_PDN_ADDR                     (GPS_RGU_ON_BASE + 0x0270)
#define GPS_RGU_ON_GPS_L5_DSPPRAM_SLP_ADDR                     (GPS_RGU_ON_BASE + 0x0274)
#define GPS_RGU_ON_GPS_L5_DSPPRAM_ISO_ADDR                     (GPS_RGU_ON_BASE + 0x0278)
#define GPS_RGU_ON_GPS_L5_DSPPRAM_ISOINT_ADDR                  (GPS_RGU_ON_BASE + 0x027C)
#define GPS_RGU_ON_GPS_L5_DSPXRAM_PDN_ADDR                     (GPS_RGU_ON_BASE + 0x0280)
#define GPS_RGU_ON_GPS_L5_DSPXRAM_SLP_ADDR                     (GPS_RGU_ON_BASE + 0x0284)
#define GPS_RGU_ON_GPS_L5_DSPXRAM_ISO_ADDR                     (GPS_RGU_ON_BASE + 0x0288)
#define GPS_RGU_ON_GPS_L5_DSPXRAM_ISOINT_ADDR                  (GPS_RGU_ON_BASE + 0x028C)
#define GPS_RGU_ON_GPS_L5_DSPYRAM_PDN_ADDR                     (GPS_RGU_ON_BASE + 0x0290)
#define GPS_RGU_ON_GPS_L5_DSPYRAM_SLP_ADDR                     (GPS_RGU_ON_BASE + 0x0294)
#define GPS_RGU_ON_GPS_L5_DSPYRAM_ISO_ADDR                     (GPS_RGU_ON_BASE + 0x0298)
#define GPS_RGU_ON_GPS_L5_DSPYRAM_ISOINT_ADDR                  (GPS_RGU_ON_BASE + 0x029C)
#define GPS_RGU_ON_GPS_L5_DSPURAM_PDN_ADDR                     (GPS_RGU_ON_BASE + 0x02A0)
#define GPS_RGU_ON_GPS_L5_DSPURAM_SLP_ADDR                     (GPS_RGU_ON_BASE + 0x02A4)
#define GPS_RGU_ON_GPS_L5_DSPURAM_ISO_ADDR                     (GPS_RGU_ON_BASE + 0x02A8)
#define GPS_RGU_ON_GPS_L5_DSPURAM_ISOINT_ADDR                  (GPS_RGU_ON_BASE + 0x02AC)
#define GPS_RGU_ON_GPS_L5_SEC_CROM_PDN_STAT_ADDR               (GPS_RGU_ON_BASE + 0x02B0)
#define GPS_RGU_ON_GPS_L5_DSPPROM_PDN_STAT_ADDR                (GPS_RGU_ON_BASE + 0x02B4)
#define GPS_RGU_ON_GPS_L5_DSPPRAM_PDN_STAT_ADDR                (GPS_RGU_ON_BASE + 0x02C0)
#define GPS_RGU_ON_GPS_L5_DSPPRAM_SLP_STAT_ADDR                (GPS_RGU_ON_BASE + 0x02C4)
#define GPS_RGU_ON_GPS_L5_DSPPRAM_ISO_STAT_ADDR                (GPS_RGU_ON_BASE + 0x02C8)
#define GPS_RGU_ON_GPS_L5_DSPPRAM_ISOINT_STAT_ADDR             (GPS_RGU_ON_BASE + 0x02CC)
#define GPS_RGU_ON_GPS_L5_DSPXRAM_PDN_STAT_ADDR                (GPS_RGU_ON_BASE + 0x02D0)
#define GPS_RGU_ON_GPS_L5_DSPXRAM_SLP_STAT_ADDR                (GPS_RGU_ON_BASE + 0x02D4)
#define GPS_RGU_ON_GPS_L5_DSPXRAM_ISO_STAT_ADDR                (GPS_RGU_ON_BASE + 0x02D8)
#define GPS_RGU_ON_GPS_L5_DSPXRAM_ISOINT_STAT_ADDR             (GPS_RGU_ON_BASE + 0x02DC)
#define GPS_RGU_ON_GPS_L5_DSPYRAM_PDN_STAT_ADDR                (GPS_RGU_ON_BASE + 0x02E0)
#define GPS_RGU_ON_GPS_L5_DSPYRAM_SLP_STAT_ADDR                (GPS_RGU_ON_BASE + 0x02E4)
#define GPS_RGU_ON_GPS_L5_DSPYRAM_ISO_STAT_ADDR                (GPS_RGU_ON_BASE + 0x02E8)
#define GPS_RGU_ON_GPS_L5_DSPYRAM_ISOINT_STAT_ADDR             (GPS_RGU_ON_BASE + 0x02EC)
#define GPS_RGU_ON_GPS_L5_DSPURAM_PDN_STAT_ADDR                (GPS_RGU_ON_BASE + 0x02F0)
#define GPS_RGU_ON_GPS_L5_DSPURAM_SLP_STAT_ADDR                (GPS_RGU_ON_BASE + 0x02F4)
#define GPS_RGU_ON_GPS_L5_DSPURAM_ISO_STAT_ADDR                (GPS_RGU_ON_BASE + 0x02F8)
#define GPS_RGU_ON_GPS_L5_DSPURAM_ISOINT_STAT_ADDR             (GPS_RGU_ON_BASE + 0x02FC)
#define GPS_RGU_ON_GPS_L5_SEC_CROM_RST_ADDR                    (GPS_RGU_ON_BASE + 0x0300)
#define GPS_RGU_ON_GPS_L5_CHN_MEM_DYN_OFF_ADDR                 (GPS_RGU_ON_BASE + 0x0304)
#define GPS_RGU_ON_GPS_L5_CH0_MEM_PDN_STAT_ADDR                (GPS_RGU_ON_BASE + 0x0330)
#define GPS_RGU_ON_GPS_L5_CH1_MEM_PDN_STAT_ADDR                (GPS_RGU_ON_BASE + 0x0334)
#define GPS_RGU_ON_GPS_L5_DLY_CHAIN_CTL_ADDR                   (GPS_RGU_ON_BASE + 0x0360)
#define GPS_RGU_ON_GPS_L5_MEM_DLY_CTL_ADDR                     (GPS_RGU_ON_BASE + 0x0364)


#define GPS_RGU_ON_GPS_TOP_RGU_CR_GPS_TOP_HWCTL_ADDR           GPS_RGU_ON_GPS_TOP_RGU_CR_ADDR
#define GPS_RGU_ON_GPS_TOP_RGU_CR_GPS_TOP_HWCTL_MASK           0x00000001
#define GPS_RGU_ON_GPS_TOP_RGU_CR_GPS_TOP_HWCTL_SHFT           0

#define GPS_RGU_ON_GPS_TOP_DSLEEP_MANUAL_GPS_TOP_PWR_CTL_MANUAL_ENABLE_ADDR GPS_RGU_ON_GPS_TOP_DSLEEP_MANUAL_ADDR
#define GPS_RGU_ON_GPS_TOP_DSLEEP_MANUAL_GPS_TOP_PWR_CTL_MANUAL_ENABLE_MASK 0x80000000
#define GPS_RGU_ON_GPS_TOP_DSLEEP_MANUAL_GPS_TOP_PWR_CTL_MANUAL_ENABLE_SHFT 31
#define GPS_RGU_ON_GPS_TOP_DSLEEP_MANUAL_GPS_TOP_PWR_CTL_MANUAL_DEASSERT_PWR_ON_DELAY_ADDR \
	GPS_RGU_ON_GPS_TOP_DSLEEP_MANUAL_ADDR
#define GPS_RGU_ON_GPS_TOP_DSLEEP_MANUAL_GPS_TOP_PWR_CTL_MANUAL_DEASSERT_PWR_ON_DELAY_MASK 0x7C000000
#define GPS_RGU_ON_GPS_TOP_DSLEEP_MANUAL_GPS_TOP_PWR_CTL_MANUAL_DEASSERT_PWR_ON_DELAY_SHFT 26
#define GPS_RGU_ON_GPS_TOP_DSLEEP_MANUAL_GPS_TOP_PWR_CTL_MANUAL_ASSERT_ISO_DELAY_ADDR \
	GPS_RGU_ON_GPS_TOP_DSLEEP_MANUAL_ADDR
#define GPS_RGU_ON_GPS_TOP_DSLEEP_MANUAL_GPS_TOP_PWR_CTL_MANUAL_ASSERT_ISO_DELAY_MASK 0x03E00000
#define GPS_RGU_ON_GPS_TOP_DSLEEP_MANUAL_GPS_TOP_PWR_CTL_MANUAL_ASSERT_ISO_DELAY_SHFT 21
#define GPS_RGU_ON_GPS_TOP_DSLEEP_MANUAL_GPS_TOP_PWR_CTL_MANUAL_ASSERT_RST_DELAY_ADDR \
	GPS_RGU_ON_GPS_TOP_DSLEEP_MANUAL_ADDR
#define GPS_RGU_ON_GPS_TOP_DSLEEP_MANUAL_GPS_TOP_PWR_CTL_MANUAL_ASSERT_RST_DELAY_MASK 0x001F0000
#define GPS_RGU_ON_GPS_TOP_DSLEEP_MANUAL_GPS_TOP_PWR_CTL_MANUAL_ASSERT_RST_DELAY_SHFT 16
#define GPS_RGU_ON_GPS_TOP_DSLEEP_MANUAL_GPS_TOP_PWR_CTL_MANUAL_ASSERT_PWR_ON_DELAY_ADDR \
	GPS_RGU_ON_GPS_TOP_DSLEEP_MANUAL_ADDR
#define GPS_RGU_ON_GPS_TOP_DSLEEP_MANUAL_GPS_TOP_PWR_CTL_MANUAL_ASSERT_PWR_ON_DELAY_MASK 0x00007C00
#define GPS_RGU_ON_GPS_TOP_DSLEEP_MANUAL_GPS_TOP_PWR_CTL_MANUAL_ASSERT_PWR_ON_DELAY_SHFT 10
#define GPS_RGU_ON_GPS_TOP_DSLEEP_MANUAL_GPS_TOP_PWR_CTL_MANUAL_DEASSERT_ISO_DELAY_ADDR \
	GPS_RGU_ON_GPS_TOP_DSLEEP_MANUAL_ADDR
#define GPS_RGU_ON_GPS_TOP_DSLEEP_MANUAL_GPS_TOP_PWR_CTL_MANUAL_DEASSERT_ISO_DELAY_MASK 0x000003E0
#define GPS_RGU_ON_GPS_TOP_DSLEEP_MANUAL_GPS_TOP_PWR_CTL_MANUAL_DEASSERT_ISO_DELAY_SHFT 5
#define GPS_RGU_ON_GPS_TOP_DSLEEP_MANUAL_GPS_TOP_PWR_CTL_MANUAL_DEASSERT_RST_DELAY_ADDR \
	GPS_RGU_ON_GPS_TOP_DSLEEP_MANUAL_ADDR
#define GPS_RGU_ON_GPS_TOP_DSLEEP_MANUAL_GPS_TOP_PWR_CTL_MANUAL_DEASSERT_RST_DELAY_MASK 0x0000001F
#define GPS_RGU_ON_GPS_TOP_DSLEEP_MANUAL_GPS_TOP_PWR_CTL_MANUAL_DEASSERT_RST_DELAY_SHFT 0

#define GPS_RGU_ON_GPS_TOP_RGU_DELAY_GPS_RGU_TOP_PWR_ENABLE_DLY_MASK_ADDR GPS_RGU_ON_GPS_TOP_RGU_DELAY_ADDR
#define GPS_RGU_ON_GPS_TOP_RGU_DELAY_GPS_RGU_TOP_PWR_ENABLE_DLY_MASK_MASK 0x00000020
#define GPS_RGU_ON_GPS_TOP_RGU_DELAY_GPS_RGU_TOP_PWR_ENABLE_DLY_MASK_SHFT 5
#define GPS_RGU_ON_GPS_TOP_RGU_DELAY_GPS_RGU_TOP_PWR_ENABLE_DLY_EN_ADDR GPS_RGU_ON_GPS_TOP_RGU_DELAY_ADDR
#define GPS_RGU_ON_GPS_TOP_RGU_DELAY_GPS_RGU_TOP_PWR_ENABLE_DLY_EN_MASK 0x00000010
#define GPS_RGU_ON_GPS_TOP_RGU_DELAY_GPS_RGU_TOP_PWR_ENABLE_DLY_EN_SHFT 4
#define GPS_RGU_ON_GPS_TOP_RGU_DELAY_GPS_RGU_TOP_PWR_ENABLE_DLY_SEL_ADDR GPS_RGU_ON_GPS_TOP_RGU_DELAY_ADDR
#define GPS_RGU_ON_GPS_TOP_RGU_DELAY_GPS_RGU_TOP_PWR_ENABLE_DLY_SEL_MASK 0x0000000F
#define GPS_RGU_ON_GPS_TOP_RGU_DELAY_GPS_RGU_TOP_PWR_ENABLE_DLY_SEL_SHFT 0

#define GPS_RGU_ON_BGF_TOP_PWR_ACK_ST_MX_TOP_PWR_ACK_ADDR      GPS_RGU_ON_BGF_TOP_PWR_ACK_ST_ADDR
#define GPS_RGU_ON_BGF_TOP_PWR_ACK_ST_MX_TOP_PWR_ACK_MASK      0x02000000
#define GPS_RGU_ON_BGF_TOP_PWR_ACK_ST_MX_TOP_PWR_ACK_SHFT      25
#define GPS_RGU_ON_BGF_TOP_PWR_ACK_ST_AN_TOP_PWR_ACK_S_ADDR    GPS_RGU_ON_BGF_TOP_PWR_ACK_ST_ADDR
#define GPS_RGU_ON_BGF_TOP_PWR_ACK_ST_AN_TOP_PWR_ACK_S_MASK    0x01000000
#define GPS_RGU_ON_BGF_TOP_PWR_ACK_ST_AN_TOP_PWR_ACK_S_SHFT    24
#define GPS_RGU_ON_BGF_TOP_PWR_ACK_ST_MX_TOP_PWR_ACK_S_ADDR    GPS_RGU_ON_BGF_TOP_PWR_ACK_ST_ADDR
#define GPS_RGU_ON_BGF_TOP_PWR_ACK_ST_MX_TOP_PWR_ACK_S_MASK    0x00FFFFFF
#define GPS_RGU_ON_BGF_TOP_PWR_ACK_ST_MX_TOP_PWR_ACK_S_SHFT    0

#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_SCAN_PWR_ACK_ADDR      GPS_RGU_ON_GPS_L1_CR_ADDR
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_SCAN_PWR_ACK_MASK      0x00000800
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_SCAN_PWR_ACK_SHFT      11
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_SCAN_PWR_ACK_S_ADDR    GPS_RGU_ON_GPS_L1_CR_ADDR
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_SCAN_PWR_ACK_S_MASK    0x00000400
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_SCAN_PWR_ACK_S_SHFT    10
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_CROM_RST_B_ADDR        GPS_RGU_ON_GPS_L1_CR_ADDR
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_CROM_RST_B_MASK        0x00000200
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_CROM_RST_B_SHFT        9
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_RST_B_ADDR             GPS_RGU_ON_GPS_L1_CR_ADDR
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_RST_B_MASK             0x00000100
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_RST_B_SHFT             8
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_SOFT_RST_B_ADDR        GPS_RGU_ON_GPS_L1_CR_ADDR
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_SOFT_RST_B_MASK        0x00000020
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_SOFT_RST_B_SHFT        5
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_SOFT_ISO_EN_ADDR       GPS_RGU_ON_GPS_L1_CR_ADDR
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_SOFT_ISO_EN_MASK       0x00000010
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_SOFT_ISO_EN_SHFT       4
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_SOFT_PWR_ON_ADDR       GPS_RGU_ON_GPS_L1_CR_ADDR
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_SOFT_PWR_ON_MASK       0x00000008
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_SOFT_PWR_ON_SHFT       3
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_SOFT_PWR_ON_S_ADDR     GPS_RGU_ON_GPS_L1_CR_ADDR
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_SOFT_PWR_ON_S_MASK     0x00000004
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_SOFT_PWR_ON_S_SHFT     2
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_HWCTL_ADDR             GPS_RGU_ON_GPS_L1_CR_ADDR
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_HWCTL_MASK             0x00000002
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_HWCTL_SHFT             1
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_ON_ADDR                GPS_RGU_ON_GPS_L1_CR_ADDR
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_ON_MASK                0x00000001
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_ON_SHFT                0

#define GPS_RGU_ON_GPS_L1_PWR_ST_RGU_GPS_L1_PWR_STATE_ADDR     GPS_RGU_ON_GPS_L1_PWR_ST_ADDR
#define GPS_RGU_ON_GPS_L1_PWR_ST_RGU_GPS_L1_PWR_STATE_MASK     0x7C000000
#define GPS_RGU_ON_GPS_L1_PWR_ST_RGU_GPS_L1_PWR_STATE_SHFT     26
#define GPS_RGU_ON_GPS_L1_PWR_ST_AN_GPSSYS_L1_PWR_ACK_S_ADDR   GPS_RGU_ON_GPS_L1_PWR_ST_ADDR
#define GPS_RGU_ON_GPS_L1_PWR_ST_AN_GPSSYS_L1_PWR_ACK_S_MASK   0x02000000
#define GPS_RGU_ON_GPS_L1_PWR_ST_AN_GPSSYS_L1_PWR_ACK_S_SHFT   25
#define GPS_RGU_ON_GPS_L1_PWR_ST_MX_GPSSYS_L1_PWR_ACK_ADDR     GPS_RGU_ON_GPS_L1_PWR_ST_ADDR
#define GPS_RGU_ON_GPS_L1_PWR_ST_MX_GPSSYS_L1_PWR_ACK_MASK     0x01000000
#define GPS_RGU_ON_GPS_L1_PWR_ST_MX_GPSSYS_L1_PWR_ACK_SHFT     24
#define GPS_RGU_ON_GPS_L1_PWR_ST_MX_GPSSYS_L1_PWR_ACK_S_ADDR   GPS_RGU_ON_GPS_L1_PWR_ST_ADDR
#define GPS_RGU_ON_GPS_L1_PWR_ST_MX_GPSSYS_L1_PWR_ACK_S_MASK   0x00000001
#define GPS_RGU_ON_GPS_L1_PWR_ST_MX_GPSSYS_L1_PWR_ACK_S_SHFT   0

#define GPS_RGU_ON_GPS_L1_PON_S_EN_RGU_GPS_L1_PWR_ON_S_EN_ADDR GPS_RGU_ON_GPS_L1_PON_S_EN_ADDR
#define GPS_RGU_ON_GPS_L1_PON_S_EN_RGU_GPS_L1_PWR_ON_S_EN_MASK 0x00000001
#define GPS_RGU_ON_GPS_L1_PON_S_EN_RGU_GPS_L1_PWR_ON_S_EN_SHFT 0

#define GPS_RGU_ON_GPS_L1_RGU_RESERVED_RGU_GPS_L1_RESERVED4_ADDR GPS_RGU_ON_GPS_L1_RGU_RESERVED_ADDR
#define GPS_RGU_ON_GPS_L1_RGU_RESERVED_RGU_GPS_L1_RESERVED4_MASK 0xFFFFFFC0
#define GPS_RGU_ON_GPS_L1_RGU_RESERVED_RGU_GPS_L1_RESERVED4_SHFT 6
#define GPS_RGU_ON_GPS_L1_RGU_RESERVED_RGU_GPS_L1_RESERVED3_ADDR GPS_RGU_ON_GPS_L1_RGU_RESERVED_ADDR
#define GPS_RGU_ON_GPS_L1_RGU_RESERVED_RGU_GPS_L1_RESERVED3_MASK 0x00000030
#define GPS_RGU_ON_GPS_L1_RGU_RESERVED_RGU_GPS_L1_RESERVED3_SHFT 4
#define GPS_RGU_ON_GPS_L1_RGU_RESERVED_RGU_GPS_L1_RESERVED2_ADDR GPS_RGU_ON_GPS_L1_RGU_RESERVED_ADDR
#define GPS_RGU_ON_GPS_L1_RGU_RESERVED_RGU_GPS_L1_RESERVED2_MASK 0x0000000C
#define GPS_RGU_ON_GPS_L1_RGU_RESERVED_RGU_GPS_L1_RESERVED2_SHFT 2
#define GPS_RGU_ON_GPS_L1_RGU_RESERVED_RGU_GPS_L1_RESERVED1_ADDR GPS_RGU_ON_GPS_L1_RGU_RESERVED_ADDR
#define GPS_RGU_ON_GPS_L1_RGU_RESERVED_RGU_GPS_L1_RESERVED1_MASK 0x00000002
#define GPS_RGU_ON_GPS_L1_RGU_RESERVED_RGU_GPS_L1_RESERVED1_SHFT 1
#define GPS_RGU_ON_GPS_L1_RGU_RESERVED_RGU_GPS_L1_RESERVED0_ADDR GPS_RGU_ON_GPS_L1_RGU_RESERVED_ADDR
#define GPS_RGU_ON_GPS_L1_RGU_RESERVED_RGU_GPS_L1_RESERVED0_MASK 0x00000001
#define GPS_RGU_ON_GPS_L1_RGU_RESERVED_RGU_GPS_L1_RESERVED0_SHFT 0

#define GPS_RGU_ON_GPS_L1_CROM_PDN_EN_RGU_GPS_L1_CROM_HWCTL_PDN_ADDR GPS_RGU_ON_GPS_L1_CROM_PDN_EN_ADDR
#define GPS_RGU_ON_GPS_L1_CROM_PDN_EN_RGU_GPS_L1_CROM_HWCTL_PDN_MASK 0x0000003F
#define GPS_RGU_ON_GPS_L1_CROM_PDN_EN_RGU_GPS_L1_CROM_HWCTL_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPPROM_PDN_EN_RGU_GPS_L1_PROM_HWCTL_PDN_ADDR GPS_RGU_ON_GPS_L1_DSPPROM_PDN_EN_ADDR
#define GPS_RGU_ON_GPS_L1_DSPPROM_PDN_EN_RGU_GPS_L1_PROM_HWCTL_PDN_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L1_DSPPROM_PDN_EN_RGU_GPS_L1_PROM_HWCTL_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPPRAM_PDN_EN_RGU_GPS_L1_PRAM_HWCTL_PDN_ADDR GPS_RGU_ON_GPS_L1_DSPPRAM_PDN_EN_ADDR
#define GPS_RGU_ON_GPS_L1_DSPPRAM_PDN_EN_RGU_GPS_L1_PRAM_HWCTL_PDN_MASK 0x000001FF
#define GPS_RGU_ON_GPS_L1_DSPPRAM_PDN_EN_RGU_GPS_L1_PRAM_HWCTL_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPPRAM_SLP_EN_RGU_GPS_L1_PRAM_HWCTL_SLP_ADDR GPS_RGU_ON_GPS_L1_DSPPRAM_SLP_EN_ADDR
#define GPS_RGU_ON_GPS_L1_DSPPRAM_SLP_EN_RGU_GPS_L1_PRAM_HWCTL_SLP_MASK 0x000001FF
#define GPS_RGU_ON_GPS_L1_DSPPRAM_SLP_EN_RGU_GPS_L1_PRAM_HWCTL_SLP_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPXRAM_PDN_EN_RGU_GPS_L1_XRAM_HWCTL_PDN_ADDR GPS_RGU_ON_GPS_L1_DSPXRAM_PDN_EN_ADDR
#define GPS_RGU_ON_GPS_L1_DSPXRAM_PDN_EN_RGU_GPS_L1_XRAM_HWCTL_PDN_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L1_DSPXRAM_PDN_EN_RGU_GPS_L1_XRAM_HWCTL_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPXRAM_SLP_EN_RGU_GPS_L1_XRAM_HWCTL_SLP_ADDR GPS_RGU_ON_GPS_L1_DSPXRAM_SLP_EN_ADDR
#define GPS_RGU_ON_GPS_L1_DSPXRAM_SLP_EN_RGU_GPS_L1_XRAM_HWCTL_SLP_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L1_DSPXRAM_SLP_EN_RGU_GPS_L1_XRAM_HWCTL_SLP_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPYRAM_PDN_EN_RGU_GPS_L1_YRAM_HWCTL_PDN_ADDR GPS_RGU_ON_GPS_L1_DSPYRAM_PDN_EN_ADDR
#define GPS_RGU_ON_GPS_L1_DSPYRAM_PDN_EN_RGU_GPS_L1_YRAM_HWCTL_PDN_MASK 0x000001FF
#define GPS_RGU_ON_GPS_L1_DSPYRAM_PDN_EN_RGU_GPS_L1_YRAM_HWCTL_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPYRAM_SLP_EN_RGU_GPS_L1_YRAM_HWCTL_SLP_ADDR GPS_RGU_ON_GPS_L1_DSPYRAM_SLP_EN_ADDR
#define GPS_RGU_ON_GPS_L1_DSPYRAM_SLP_EN_RGU_GPS_L1_YRAM_HWCTL_SLP_MASK 0x000001FF
#define GPS_RGU_ON_GPS_L1_DSPYRAM_SLP_EN_RGU_GPS_L1_YRAM_HWCTL_SLP_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPURAM_PDN_EN_RGU_GPS_L1_URAM_HWCTL_PDN_ADDR GPS_RGU_ON_GPS_L1_DSPURAM_PDN_EN_ADDR
#define GPS_RGU_ON_GPS_L1_DSPURAM_PDN_EN_RGU_GPS_L1_URAM_HWCTL_PDN_MASK 0x00000003
#define GPS_RGU_ON_GPS_L1_DSPURAM_PDN_EN_RGU_GPS_L1_URAM_HWCTL_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPURAM_SLP_EN_RGU_GPS_L1_URAM_HWCTL_SLP_ADDR GPS_RGU_ON_GPS_L1_DSPURAM_SLP_EN_ADDR
#define GPS_RGU_ON_GPS_L1_DSPURAM_SLP_EN_RGU_GPS_L1_URAM_HWCTL_SLP_MASK 0x00000003
#define GPS_RGU_ON_GPS_L1_DSPURAM_SLP_EN_RGU_GPS_L1_URAM_HWCTL_SLP_SHFT 0

#define GPS_RGU_ON_GPS_L1_CROM_PDN_RGU_GPS_L1_CROM_SWCTL_PDN_ADDR GPS_RGU_ON_GPS_L1_CROM_PDN_ADDR
#define GPS_RGU_ON_GPS_L1_CROM_PDN_RGU_GPS_L1_CROM_SWCTL_PDN_MASK 0x0000003F
#define GPS_RGU_ON_GPS_L1_CROM_PDN_RGU_GPS_L1_CROM_SWCTL_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPPROM_PDN_RGU_GPS_L1_PROM_SWCTL_PDN_ADDR GPS_RGU_ON_GPS_L1_DSPPROM_PDN_ADDR
#define GPS_RGU_ON_GPS_L1_DSPPROM_PDN_RGU_GPS_L1_PROM_SWCTL_PDN_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L1_DSPPROM_PDN_RGU_GPS_L1_PROM_SWCTL_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPPRAM_PDN_RGU_GPS_L1_PRAM_SWCTL_PDN_ADDR GPS_RGU_ON_GPS_L1_DSPPRAM_PDN_ADDR
#define GPS_RGU_ON_GPS_L1_DSPPRAM_PDN_RGU_GPS_L1_PRAM_SWCTL_PDN_MASK 0x000001FF
#define GPS_RGU_ON_GPS_L1_DSPPRAM_PDN_RGU_GPS_L1_PRAM_SWCTL_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPPRAM_SLP_RGU_GPS_L1_PRAM_SWCTL_SLP_ADDR GPS_RGU_ON_GPS_L1_DSPPRAM_SLP_ADDR
#define GPS_RGU_ON_GPS_L1_DSPPRAM_SLP_RGU_GPS_L1_PRAM_SWCTL_SLP_MASK 0x000001FF
#define GPS_RGU_ON_GPS_L1_DSPPRAM_SLP_RGU_GPS_L1_PRAM_SWCTL_SLP_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPPRAM_ISO_RGU_GPS_L1_PRAM_SWCTL_ISO_ADDR GPS_RGU_ON_GPS_L1_DSPPRAM_ISO_ADDR
#define GPS_RGU_ON_GPS_L1_DSPPRAM_ISO_RGU_GPS_L1_PRAM_SWCTL_ISO_MASK 0x000001FF
#define GPS_RGU_ON_GPS_L1_DSPPRAM_ISO_RGU_GPS_L1_PRAM_SWCTL_ISO_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPPRAM_ISOINT_RGU_GPS_L1_PRAM_SWCTL_ISOINT_ADDR GPS_RGU_ON_GPS_L1_DSPPRAM_ISOINT_ADDR
#define GPS_RGU_ON_GPS_L1_DSPPRAM_ISOINT_RGU_GPS_L1_PRAM_SWCTL_ISOINT_MASK 0x000001FF
#define GPS_RGU_ON_GPS_L1_DSPPRAM_ISOINT_RGU_GPS_L1_PRAM_SWCTL_ISOINT_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPXRAM_PDN_RGU_GPS_L1_XRAM_SWCTL_PDN_ADDR GPS_RGU_ON_GPS_L1_DSPXRAM_PDN_ADDR
#define GPS_RGU_ON_GPS_L1_DSPXRAM_PDN_RGU_GPS_L1_XRAM_SWCTL_PDN_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L1_DSPXRAM_PDN_RGU_GPS_L1_XRAM_SWCTL_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPXRAM_SLP_RGU_GPS_L1_XRAM_SWCTL_SLP_ADDR GPS_RGU_ON_GPS_L1_DSPXRAM_SLP_ADDR
#define GPS_RGU_ON_GPS_L1_DSPXRAM_SLP_RGU_GPS_L1_XRAM_SWCTL_SLP_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L1_DSPXRAM_SLP_RGU_GPS_L1_XRAM_SWCTL_SLP_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPXRAM_ISO_RGU_GPS_L1_XRAM_SWCTL_ISO_ADDR GPS_RGU_ON_GPS_L1_DSPXRAM_ISO_ADDR
#define GPS_RGU_ON_GPS_L1_DSPXRAM_ISO_RGU_GPS_L1_XRAM_SWCTL_ISO_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L1_DSPXRAM_ISO_RGU_GPS_L1_XRAM_SWCTL_ISO_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPXRAM_ISOINT_RGU_GPS_L1_XRAM_SWCTL_ISOINT_ADDR GPS_RGU_ON_GPS_L1_DSPXRAM_ISOINT_ADDR
#define GPS_RGU_ON_GPS_L1_DSPXRAM_ISOINT_RGU_GPS_L1_XRAM_SWCTL_ISOINT_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L1_DSPXRAM_ISOINT_RGU_GPS_L1_XRAM_SWCTL_ISOINT_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPYRAM_PDN_RGU_GPS_L1_YRAM_SWCTL_PDN_ADDR GPS_RGU_ON_GPS_L1_DSPYRAM_PDN_ADDR
#define GPS_RGU_ON_GPS_L1_DSPYRAM_PDN_RGU_GPS_L1_YRAM_SWCTL_PDN_MASK 0x000001FF
#define GPS_RGU_ON_GPS_L1_DSPYRAM_PDN_RGU_GPS_L1_YRAM_SWCTL_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPYRAM_SLP_RGU_GPS_L1_YRAM_SWCTL_SLP_ADDR GPS_RGU_ON_GPS_L1_DSPYRAM_SLP_ADDR
#define GPS_RGU_ON_GPS_L1_DSPYRAM_SLP_RGU_GPS_L1_YRAM_SWCTL_SLP_MASK 0x000001FF
#define GPS_RGU_ON_GPS_L1_DSPYRAM_SLP_RGU_GPS_L1_YRAM_SWCTL_SLP_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPYRAM_ISO_RGU_GPS_L1_YRAM_SWCTL_ISO_ADDR GPS_RGU_ON_GPS_L1_DSPYRAM_ISO_ADDR
#define GPS_RGU_ON_GPS_L1_DSPYRAM_ISO_RGU_GPS_L1_YRAM_SWCTL_ISO_MASK 0x000001FF
#define GPS_RGU_ON_GPS_L1_DSPYRAM_ISO_RGU_GPS_L1_YRAM_SWCTL_ISO_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPYRAM_ISOINT_RGU_GPS_L1_YRAM_SWCTL_ISOINT_ADDR GPS_RGU_ON_GPS_L1_DSPYRAM_ISOINT_ADDR
#define GPS_RGU_ON_GPS_L1_DSPYRAM_ISOINT_RGU_GPS_L1_YRAM_SWCTL_ISOINT_MASK 0x000001FF
#define GPS_RGU_ON_GPS_L1_DSPYRAM_ISOINT_RGU_GPS_L1_YRAM_SWCTL_ISOINT_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPURAM_PDN_RGU_GPS_L1_URAM_SWCTL_PDN_ADDR GPS_RGU_ON_GPS_L1_DSPURAM_PDN_ADDR
#define GPS_RGU_ON_GPS_L1_DSPURAM_PDN_RGU_GPS_L1_URAM_SWCTL_PDN_MASK 0x00000003
#define GPS_RGU_ON_GPS_L1_DSPURAM_PDN_RGU_GPS_L1_URAM_SWCTL_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPURAM_SLP_RGU_GPS_L1_URAM_SWCTL_SLP_ADDR GPS_RGU_ON_GPS_L1_DSPURAM_SLP_ADDR
#define GPS_RGU_ON_GPS_L1_DSPURAM_SLP_RGU_GPS_L1_URAM_SWCTL_SLP_MASK 0x00000003
#define GPS_RGU_ON_GPS_L1_DSPURAM_SLP_RGU_GPS_L1_URAM_SWCTL_SLP_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPURAM_ISO_RGU_GPS_L1_URAM_SWCTL_ISO_ADDR GPS_RGU_ON_GPS_L1_DSPURAM_ISO_ADDR
#define GPS_RGU_ON_GPS_L1_DSPURAM_ISO_RGU_GPS_L1_URAM_SWCTL_ISO_MASK 0x00000003
#define GPS_RGU_ON_GPS_L1_DSPURAM_ISO_RGU_GPS_L1_URAM_SWCTL_ISO_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPURAM_ISOINT_RGU_GPS_L1_URAM_SWCTL_ISOINT_ADDR GPS_RGU_ON_GPS_L1_DSPURAM_ISOINT_ADDR
#define GPS_RGU_ON_GPS_L1_DSPURAM_ISOINT_RGU_GPS_L1_URAM_SWCTL_ISOINT_MASK 0x00000003
#define GPS_RGU_ON_GPS_L1_DSPURAM_ISOINT_RGU_GPS_L1_URAM_SWCTL_ISOINT_SHFT 0

#define GPS_RGU_ON_GPS_L1_CROM_PDN_STAT_GPSSYS_L1_CROM_PWR_DOWN_ADDR GPS_RGU_ON_GPS_L1_CROM_PDN_STAT_ADDR
#define GPS_RGU_ON_GPS_L1_CROM_PDN_STAT_GPSSYS_L1_CROM_PWR_DOWN_MASK 0x0000003F
#define GPS_RGU_ON_GPS_L1_CROM_PDN_STAT_GPSSYS_L1_CROM_PWR_DOWN_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPPROM_PDN_STAT_GPSSYS_L1_PROM_PWR_DOWN_ADDR GPS_RGU_ON_GPS_L1_DSPPROM_PDN_STAT_ADDR
#define GPS_RGU_ON_GPS_L1_DSPPROM_PDN_STAT_GPSSYS_L1_PROM_PWR_DOWN_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L1_DSPPROM_PDN_STAT_GPSSYS_L1_PROM_PWR_DOWN_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPPRAM_PDN_STAT_GPSSYS_L1_PRAM_MEM_PDN_ADDR GPS_RGU_ON_GPS_L1_DSPPRAM_PDN_STAT_ADDR
#define GPS_RGU_ON_GPS_L1_DSPPRAM_PDN_STAT_GPSSYS_L1_PRAM_MEM_PDN_MASK 0x000001FF
#define GPS_RGU_ON_GPS_L1_DSPPRAM_PDN_STAT_GPSSYS_L1_PRAM_MEM_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPPRAM_SLP_STAT_GPSSYS_L1_PRAM_MEM_SLP_ADDR GPS_RGU_ON_GPS_L1_DSPPRAM_SLP_STAT_ADDR
#define GPS_RGU_ON_GPS_L1_DSPPRAM_SLP_STAT_GPSSYS_L1_PRAM_MEM_SLP_MASK 0x000001FF
#define GPS_RGU_ON_GPS_L1_DSPPRAM_SLP_STAT_GPSSYS_L1_PRAM_MEM_SLP_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPPRAM_ISO_STAT_GPSSYS_L1_PRAM_MEM_ISO_ADDR GPS_RGU_ON_GPS_L1_DSPPRAM_ISO_STAT_ADDR
#define GPS_RGU_ON_GPS_L1_DSPPRAM_ISO_STAT_GPSSYS_L1_PRAM_MEM_ISO_MASK 0x000001FF
#define GPS_RGU_ON_GPS_L1_DSPPRAM_ISO_STAT_GPSSYS_L1_PRAM_MEM_ISO_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPPRAM_ISOINT_STAT_GPSSYS_L1_PRAM_MEM_ISOINT_ADDR GPS_RGU_ON_GPS_L1_DSPPRAM_ISOINT_STAT_ADDR
#define GPS_RGU_ON_GPS_L1_DSPPRAM_ISOINT_STAT_GPSSYS_L1_PRAM_MEM_ISOINT_MASK 0x000001FF
#define GPS_RGU_ON_GPS_L1_DSPPRAM_ISOINT_STAT_GPSSYS_L1_PRAM_MEM_ISOINT_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPXRAM_PDN_STAT_GPSSYS_L1_XRAM_MEM_PDN_ADDR GPS_RGU_ON_GPS_L1_DSPXRAM_PDN_STAT_ADDR
#define GPS_RGU_ON_GPS_L1_DSPXRAM_PDN_STAT_GPSSYS_L1_XRAM_MEM_PDN_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L1_DSPXRAM_PDN_STAT_GPSSYS_L1_XRAM_MEM_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPXRAM_SLP_STAT_GPSSYS_L1_XRAM_MEM_SLP_ADDR GPS_RGU_ON_GPS_L1_DSPXRAM_SLP_STAT_ADDR
#define GPS_RGU_ON_GPS_L1_DSPXRAM_SLP_STAT_GPSSYS_L1_XRAM_MEM_SLP_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L1_DSPXRAM_SLP_STAT_GPSSYS_L1_XRAM_MEM_SLP_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPXRAM_ISO_STAT_GPSSYS_L1_XRAM_MEM_ISO_ADDR GPS_RGU_ON_GPS_L1_DSPXRAM_ISO_STAT_ADDR
#define GPS_RGU_ON_GPS_L1_DSPXRAM_ISO_STAT_GPSSYS_L1_XRAM_MEM_ISO_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L1_DSPXRAM_ISO_STAT_GPSSYS_L1_XRAM_MEM_ISO_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPXRAM_ISOINT_STAT_GPSSYS_L1_XRAM_MEM_ISOINT_ADDR GPS_RGU_ON_GPS_L1_DSPXRAM_ISOINT_STAT_ADDR
#define GPS_RGU_ON_GPS_L1_DSPXRAM_ISOINT_STAT_GPSSYS_L1_XRAM_MEM_ISOINT_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L1_DSPXRAM_ISOINT_STAT_GPSSYS_L1_XRAM_MEM_ISOINT_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPYRAM_PDN_STAT_GPSSYS_L1_YRAM_MEM_PDN_ADDR GPS_RGU_ON_GPS_L1_DSPYRAM_PDN_STAT_ADDR
#define GPS_RGU_ON_GPS_L1_DSPYRAM_PDN_STAT_GPSSYS_L1_YRAM_MEM_PDN_MASK 0x000001FF
#define GPS_RGU_ON_GPS_L1_DSPYRAM_PDN_STAT_GPSSYS_L1_YRAM_MEM_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPYRAM_SLP_STAT_GPSSYS_L1_YRAM_MEM_SLP_ADDR GPS_RGU_ON_GPS_L1_DSPYRAM_SLP_STAT_ADDR
#define GPS_RGU_ON_GPS_L1_DSPYRAM_SLP_STAT_GPSSYS_L1_YRAM_MEM_SLP_MASK 0x000001FF
#define GPS_RGU_ON_GPS_L1_DSPYRAM_SLP_STAT_GPSSYS_L1_YRAM_MEM_SLP_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPYRAM_ISO_STAT_GPSSYS_L1_YRAM_MEM_ISO_ADDR GPS_RGU_ON_GPS_L1_DSPYRAM_ISO_STAT_ADDR
#define GPS_RGU_ON_GPS_L1_DSPYRAM_ISO_STAT_GPSSYS_L1_YRAM_MEM_ISO_MASK 0x000001FF
#define GPS_RGU_ON_GPS_L1_DSPYRAM_ISO_STAT_GPSSYS_L1_YRAM_MEM_ISO_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPYRAM_ISOINT_STAT_GPSSYS_L1_YRAM_MEM_ISOINT_ADDR GPS_RGU_ON_GPS_L1_DSPYRAM_ISOINT_STAT_ADDR
#define GPS_RGU_ON_GPS_L1_DSPYRAM_ISOINT_STAT_GPSSYS_L1_YRAM_MEM_ISOINT_MASK 0x000001FF
#define GPS_RGU_ON_GPS_L1_DSPYRAM_ISOINT_STAT_GPSSYS_L1_YRAM_MEM_ISOINT_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPURAM_PDN_STAT_GPSSYS_L1_URAM_MEM_PDN_ADDR GPS_RGU_ON_GPS_L1_DSPURAM_PDN_STAT_ADDR
#define GPS_RGU_ON_GPS_L1_DSPURAM_PDN_STAT_GPSSYS_L1_URAM_MEM_PDN_MASK 0x00000003
#define GPS_RGU_ON_GPS_L1_DSPURAM_PDN_STAT_GPSSYS_L1_URAM_MEM_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPURAM_SLP_STAT_GPSSYS_L1_URAM_MEM_SLP_ADDR GPS_RGU_ON_GPS_L1_DSPURAM_SLP_STAT_ADDR
#define GPS_RGU_ON_GPS_L1_DSPURAM_SLP_STAT_GPSSYS_L1_URAM_MEM_SLP_MASK 0x00000003
#define GPS_RGU_ON_GPS_L1_DSPURAM_SLP_STAT_GPSSYS_L1_URAM_MEM_SLP_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPURAM_ISO_STAT_GPSSYS_L1_URAM_MEM_ISO_ADDR GPS_RGU_ON_GPS_L1_DSPURAM_ISO_STAT_ADDR
#define GPS_RGU_ON_GPS_L1_DSPURAM_ISO_STAT_GPSSYS_L1_URAM_MEM_ISO_MASK 0x00000003
#define GPS_RGU_ON_GPS_L1_DSPURAM_ISO_STAT_GPSSYS_L1_URAM_MEM_ISO_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPURAM_ISOINT_STAT_GPSSYS_L1_URAM_MEM_ISOINT_ADDR GPS_RGU_ON_GPS_L1_DSPURAM_ISOINT_STAT_ADDR
#define GPS_RGU_ON_GPS_L1_DSPURAM_ISOINT_STAT_GPSSYS_L1_URAM_MEM_ISOINT_MASK 0x00000003
#define GPS_RGU_ON_GPS_L1_DSPURAM_ISOINT_STAT_GPSSYS_L1_URAM_MEM_ISOINT_SHFT 0

#define GPS_RGU_ON_GPS_L1_CROM_RST_REG_GPS_L1_CROM_RST_B_ADDR  GPS_RGU_ON_GPS_L1_CROM_RST_ADDR
#define GPS_RGU_ON_GPS_L1_CROM_RST_REG_GPS_L1_CROM_RST_B_MASK  0x00000001
#define GPS_RGU_ON_GPS_L1_CROM_RST_REG_GPS_L1_CROM_RST_B_SHFT  0

#define GPS_RGU_ON_GPS_L1_CHN_MEM_DYN_OFF_GPS_L1_CH11_MEM_DYN_OFF_ADDR GPS_RGU_ON_GPS_L1_CHN_MEM_DYN_OFF_ADDR
#define GPS_RGU_ON_GPS_L1_CHN_MEM_DYN_OFF_GPS_L1_CH11_MEM_DYN_OFF_MASK 0x00000800
#define GPS_RGU_ON_GPS_L1_CHN_MEM_DYN_OFF_GPS_L1_CH11_MEM_DYN_OFF_SHFT 11
#define GPS_RGU_ON_GPS_L1_CHN_MEM_DYN_OFF_GPS_L1_CH4_MEM_DYN_OFF_ADDR GPS_RGU_ON_GPS_L1_CHN_MEM_DYN_OFF_ADDR
#define GPS_RGU_ON_GPS_L1_CHN_MEM_DYN_OFF_GPS_L1_CH4_MEM_DYN_OFF_MASK 0x00000010
#define GPS_RGU_ON_GPS_L1_CHN_MEM_DYN_OFF_GPS_L1_CH4_MEM_DYN_OFF_SHFT 4
#define GPS_RGU_ON_GPS_L1_CHN_MEM_DYN_OFF_GPS_L1_CH3_MEM_DYN_OFF_ADDR GPS_RGU_ON_GPS_L1_CHN_MEM_DYN_OFF_ADDR
#define GPS_RGU_ON_GPS_L1_CHN_MEM_DYN_OFF_GPS_L1_CH3_MEM_DYN_OFF_MASK 0x00000008
#define GPS_RGU_ON_GPS_L1_CHN_MEM_DYN_OFF_GPS_L1_CH3_MEM_DYN_OFF_SHFT 3
#define GPS_RGU_ON_GPS_L1_CHN_MEM_DYN_OFF_GPS_L1_CH2_MEM_DYN_OFF_ADDR GPS_RGU_ON_GPS_L1_CHN_MEM_DYN_OFF_ADDR
#define GPS_RGU_ON_GPS_L1_CHN_MEM_DYN_OFF_GPS_L1_CH2_MEM_DYN_OFF_MASK 0x00000004
#define GPS_RGU_ON_GPS_L1_CHN_MEM_DYN_OFF_GPS_L1_CH2_MEM_DYN_OFF_SHFT 2
#define GPS_RGU_ON_GPS_L1_CHN_MEM_DYN_OFF_GPS_L1_CH1_MEM_DYN_OFF_ADDR GPS_RGU_ON_GPS_L1_CHN_MEM_DYN_OFF_ADDR
#define GPS_RGU_ON_GPS_L1_CHN_MEM_DYN_OFF_GPS_L1_CH1_MEM_DYN_OFF_MASK 0x00000002
#define GPS_RGU_ON_GPS_L1_CHN_MEM_DYN_OFF_GPS_L1_CH1_MEM_DYN_OFF_SHFT 1
#define GPS_RGU_ON_GPS_L1_CHN_MEM_DYN_OFF_GPS_L1_CH0_MEM_DYN_OFF_ADDR GPS_RGU_ON_GPS_L1_CHN_MEM_DYN_OFF_ADDR
#define GPS_RGU_ON_GPS_L1_CHN_MEM_DYN_OFF_GPS_L1_CH0_MEM_DYN_OFF_MASK 0x00000001
#define GPS_RGU_ON_GPS_L1_CHN_MEM_DYN_OFF_GPS_L1_CH0_MEM_DYN_OFF_SHFT 0

#define GPS_RGU_ON_GPS_L1_CH2_DELAY_CHAIN_MASK_GPS_L1_CH2_MEM_DYN_OFF_MASK_ADDR \
	GPS_RGU_ON_GPS_L1_CH2_DELAY_CHAIN_MASK_ADDR
#define GPS_RGU_ON_GPS_L1_CH2_DELAY_CHAIN_MASK_GPS_L1_CH2_MEM_DYN_OFF_MASK_MASK 0x00003FFF
#define GPS_RGU_ON_GPS_L1_CH2_DELAY_CHAIN_MASK_GPS_L1_CH2_MEM_DYN_OFF_MASK_SHFT 0

#define GPS_RGU_ON_GPS_L1_CH3_DELAY_CHAIN_MASK_GPS_L1_CH3_MEM_DYN_OFF_MASK_ADDR \
	GPS_RGU_ON_GPS_L1_CH3_DELAY_CHAIN_MASK_ADDR
#define GPS_RGU_ON_GPS_L1_CH3_DELAY_CHAIN_MASK_GPS_L1_CH3_MEM_DYN_OFF_MASK_MASK 0x00003FFF
#define GPS_RGU_ON_GPS_L1_CH3_DELAY_CHAIN_MASK_GPS_L1_CH3_MEM_DYN_OFF_MASK_SHFT 0

#define GPS_RGU_ON_GPS_L1_CH4_DELAY_CHAIN_MASK_GPS_L1_CH4_MEM_DYN_OFF_MASK_ADDR \
	GPS_RGU_ON_GPS_L1_CH4_DELAY_CHAIN_MASK_ADDR
#define GPS_RGU_ON_GPS_L1_CH4_DELAY_CHAIN_MASK_GPS_L1_CH4_MEM_DYN_OFF_MASK_MASK 0x00003FFF
#define GPS_RGU_ON_GPS_L1_CH4_DELAY_CHAIN_MASK_GPS_L1_CH4_MEM_DYN_OFF_MASK_SHFT 0

#define GPS_RGU_ON_GPS_L1_CH11_DELAY_CHAIN_MASK_GPS_L1_CH11_MEM_DYN_OFF_MASK_ADDR \
	GPS_RGU_ON_GPS_L1_CH11_DELAY_CHAIN_MASK_ADDR
#define GPS_RGU_ON_GPS_L1_CH11_DELAY_CHAIN_MASK_GPS_L1_CH11_MEM_DYN_OFF_MASK_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L1_CH11_DELAY_CHAIN_MASK_GPS_L1_CH11_MEM_DYN_OFF_MASK_SHFT 0

#define GPS_RGU_ON_GPS_L1_CH0_MEM_PDN_STAT_GPSSYS_L1_CH0MEM_PWR_DOWN_ADDR GPS_RGU_ON_GPS_L1_CH0_MEM_PDN_STAT_ADDR
#define GPS_RGU_ON_GPS_L1_CH0_MEM_PDN_STAT_GPSSYS_L1_CH0MEM_PWR_DOWN_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L1_CH0_MEM_PDN_STAT_GPSSYS_L1_CH0MEM_PWR_DOWN_SHFT 0

#define GPS_RGU_ON_GPS_L1_CH1_MEM_PDN_STAT_GPSSYS_L1_CH1MEM_PWR_DOWN_ADDR GPS_RGU_ON_GPS_L1_CH1_MEM_PDN_STAT_ADDR
#define GPS_RGU_ON_GPS_L1_CH1_MEM_PDN_STAT_GPSSYS_L1_CH1MEM_PWR_DOWN_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L1_CH1_MEM_PDN_STAT_GPSSYS_L1_CH1MEM_PWR_DOWN_SHFT 0

#define GPS_RGU_ON_GPS_L1_CH2_MEM_PDN_STAT_GPSSYS_L1_CH2MEM_PWR_DOWN_ADDR GPS_RGU_ON_GPS_L1_CH2_MEM_PDN_STAT_ADDR
#define GPS_RGU_ON_GPS_L1_CH2_MEM_PDN_STAT_GPSSYS_L1_CH2MEM_PWR_DOWN_MASK 0x00003FFF
#define GPS_RGU_ON_GPS_L1_CH2_MEM_PDN_STAT_GPSSYS_L1_CH2MEM_PWR_DOWN_SHFT 0

#define GPS_RGU_ON_GPS_L1_CH3_MEM_PDN_STAT_GPSSYS_L1_CH3MEM_PWR_DOWN_ADDR GPS_RGU_ON_GPS_L1_CH3_MEM_PDN_STAT_ADDR
#define GPS_RGU_ON_GPS_L1_CH3_MEM_PDN_STAT_GPSSYS_L1_CH3MEM_PWR_DOWN_MASK 0x00003FFF
#define GPS_RGU_ON_GPS_L1_CH3_MEM_PDN_STAT_GPSSYS_L1_CH3MEM_PWR_DOWN_SHFT 0

#define GPS_RGU_ON_GPS_L1_CH4_MEM_PDN_STAT_GPSSYS_L1_CH4MEM_PWR_DOWN_ADDR GPS_RGU_ON_GPS_L1_CH4_MEM_PDN_STAT_ADDR
#define GPS_RGU_ON_GPS_L1_CH4_MEM_PDN_STAT_GPSSYS_L1_CH4MEM_PWR_DOWN_MASK 0x00003FFF
#define GPS_RGU_ON_GPS_L1_CH4_MEM_PDN_STAT_GPSSYS_L1_CH4MEM_PWR_DOWN_SHFT 0

#define GPS_RGU_ON_GPS_L1_CH11_MEM_PDN_STAT_GPSSYS_L1_CH11MEM_PWR_DOWN_ADDR GPS_RGU_ON_GPS_L1_CH11_MEM_PDN_STAT_ADDR
#define GPS_RGU_ON_GPS_L1_CH11_MEM_PDN_STAT_GPSSYS_L1_CH11MEM_PWR_DOWN_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L1_CH11_MEM_PDN_STAT_GPSSYS_L1_CH11MEM_PWR_DOWN_SHFT 0

#define GPS_RGU_ON_GPS_L1_DLY_CHAIN_CTL_RGU_GPS_L1_MEM_ISO_DLY_SHIFT_EN_ADDR GPS_RGU_ON_GPS_L1_DLY_CHAIN_CTL_ADDR
#define GPS_RGU_ON_GPS_L1_DLY_CHAIN_CTL_RGU_GPS_L1_MEM_ISO_DLY_SHIFT_EN_MASK 0x80000000
#define GPS_RGU_ON_GPS_L1_DLY_CHAIN_CTL_RGU_GPS_L1_MEM_ISO_DLY_SHIFT_EN_SHFT 31
#define GPS_RGU_ON_GPS_L1_DLY_CHAIN_CTL_RGU_GPS_L1_MEM_ISO_DELAY_NUM_ADDR GPS_RGU_ON_GPS_L1_DLY_CHAIN_CTL_ADDR
#define GPS_RGU_ON_GPS_L1_DLY_CHAIN_CTL_RGU_GPS_L1_MEM_ISO_DELAY_NUM_MASK 0x00700000
#define GPS_RGU_ON_GPS_L1_DLY_CHAIN_CTL_RGU_GPS_L1_MEM_ISO_DELAY_NUM_SHFT 20
#define GPS_RGU_ON_GPS_L1_DLY_CHAIN_CTL_RGU_GPS_L1_MEM_PDN_DELAY_DUMMY_NUM_ADDR GPS_RGU_ON_GPS_L1_DLY_CHAIN_CTL_ADDR
#define GPS_RGU_ON_GPS_L1_DLY_CHAIN_CTL_RGU_GPS_L1_MEM_PDN_DELAY_DUMMY_NUM_MASK 0x000F0000
#define GPS_RGU_ON_GPS_L1_DLY_CHAIN_CTL_RGU_GPS_L1_MEM_PDN_DELAY_DUMMY_NUM_SHFT 16
#define GPS_RGU_ON_GPS_L1_DLY_CHAIN_CTL_RGU_GPSSYS_L1_MEM_ISO_PRE_ADDR GPS_RGU_ON_GPS_L1_DLY_CHAIN_CTL_ADDR
#define GPS_RGU_ON_GPS_L1_DLY_CHAIN_CTL_RGU_GPSSYS_L1_MEM_ISO_PRE_MASK 0x000003FF
#define GPS_RGU_ON_GPS_L1_DLY_CHAIN_CTL_RGU_GPSSYS_L1_MEM_ISO_PRE_SHFT 0

#define GPS_RGU_ON_GPS_L1_MEM_DLY_CTL_RGU_GPSSYS_L1_MEM_ADJ_DLY_EN_ADDR GPS_RGU_ON_GPS_L1_MEM_DLY_CTL_ADDR
#define GPS_RGU_ON_GPS_L1_MEM_DLY_CTL_RGU_GPSSYS_L1_MEM_ADJ_DLY_EN_MASK 0x80000000
#define GPS_RGU_ON_GPS_L1_MEM_DLY_CTL_RGU_GPSSYS_L1_MEM_ADJ_DLY_EN_SHFT 31
#define GPS_RGU_ON_GPS_L1_MEM_DLY_CTL_RGU_GPSSYS_L1_MEM_PON_DLY_ADDR GPS_RGU_ON_GPS_L1_MEM_DLY_CTL_ADDR
#define GPS_RGU_ON_GPS_L1_MEM_DLY_CTL_RGU_GPSSYS_L1_MEM_PON_DLY_MASK 0x03FF0000
#define GPS_RGU_ON_GPS_L1_MEM_DLY_CTL_RGU_GPSSYS_L1_MEM_PON_DLY_SHFT 16
#define GPS_RGU_ON_GPS_L1_MEM_DLY_CTL_RGU_GPSSYS_L1_MEM_PDN_DLY_ADDR GPS_RGU_ON_GPS_L1_MEM_DLY_CTL_ADDR
#define GPS_RGU_ON_GPS_L1_MEM_DLY_CTL_RGU_GPSSYS_L1_MEM_PDN_DLY_MASK 0x000003FF
#define GPS_RGU_ON_GPS_L1_MEM_DLY_CTL_RGU_GPSSYS_L1_MEM_PDN_DLY_SHFT 0

#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_SCAN_PWR_ACK_ADDR      GPS_RGU_ON_GPS_L5_CR_ADDR
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_SCAN_PWR_ACK_MASK      0x00000800
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_SCAN_PWR_ACK_SHFT      11
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_SCAN_PWR_ACK_S_ADDR    GPS_RGU_ON_GPS_L5_CR_ADDR
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_SCAN_PWR_ACK_S_MASK    0x00000400
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_SCAN_PWR_ACK_S_SHFT    10
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_SEC_CROM_RST_B_ADDR    GPS_RGU_ON_GPS_L5_CR_ADDR
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_SEC_CROM_RST_B_MASK    0x00000200
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_SEC_CROM_RST_B_SHFT    9
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_RST_B_ADDR             GPS_RGU_ON_GPS_L5_CR_ADDR
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_RST_B_MASK             0x00000100
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_RST_B_SHFT             8
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_SOFT_RST_B_ADDR        GPS_RGU_ON_GPS_L5_CR_ADDR
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_SOFT_RST_B_MASK        0x00000020
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_SOFT_RST_B_SHFT        5
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_SOFT_ISO_EN_ADDR       GPS_RGU_ON_GPS_L5_CR_ADDR
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_SOFT_ISO_EN_MASK       0x00000010
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_SOFT_ISO_EN_SHFT       4
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_SOFT_PWR_ON_ADDR       GPS_RGU_ON_GPS_L5_CR_ADDR
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_SOFT_PWR_ON_MASK       0x00000008
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_SOFT_PWR_ON_SHFT       3
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_SOFT_PWR_ON_S_ADDR     GPS_RGU_ON_GPS_L5_CR_ADDR
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_SOFT_PWR_ON_S_MASK     0x00000004
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_SOFT_PWR_ON_S_SHFT     2
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_HWCTL_ADDR             GPS_RGU_ON_GPS_L5_CR_ADDR
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_HWCTL_MASK             0x00000002
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_HWCTL_SHFT             1
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_ON_ADDR                GPS_RGU_ON_GPS_L5_CR_ADDR
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_ON_MASK                0x00000001
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_ON_SHFT                0

#define GPS_RGU_ON_GPS_L5_PWR_ST_RGU_GPS_L5_PWR_STATE_ADDR     GPS_RGU_ON_GPS_L5_PWR_ST_ADDR
#define GPS_RGU_ON_GPS_L5_PWR_ST_RGU_GPS_L5_PWR_STATE_MASK     0x7C000000
#define GPS_RGU_ON_GPS_L5_PWR_ST_RGU_GPS_L5_PWR_STATE_SHFT     26
#define GPS_RGU_ON_GPS_L5_PWR_ST_AN_GPSSYS_L5_PWR_ACK_S_ADDR   GPS_RGU_ON_GPS_L5_PWR_ST_ADDR
#define GPS_RGU_ON_GPS_L5_PWR_ST_AN_GPSSYS_L5_PWR_ACK_S_MASK   0x02000000
#define GPS_RGU_ON_GPS_L5_PWR_ST_AN_GPSSYS_L5_PWR_ACK_S_SHFT   25
#define GPS_RGU_ON_GPS_L5_PWR_ST_MX_GPSSYS_L5_PWR_ACK_ADDR     GPS_RGU_ON_GPS_L5_PWR_ST_ADDR
#define GPS_RGU_ON_GPS_L5_PWR_ST_MX_GPSSYS_L5_PWR_ACK_MASK     0x01000000
#define GPS_RGU_ON_GPS_L5_PWR_ST_MX_GPSSYS_L5_PWR_ACK_SHFT     24
#define GPS_RGU_ON_GPS_L5_PWR_ST_MX_GPSSYS_L5_PWR_ACK_S_ADDR   GPS_RGU_ON_GPS_L5_PWR_ST_ADDR
#define GPS_RGU_ON_GPS_L5_PWR_ST_MX_GPSSYS_L5_PWR_ACK_S_MASK   0x00000001
#define GPS_RGU_ON_GPS_L5_PWR_ST_MX_GPSSYS_L5_PWR_ACK_S_SHFT   0

#define GPS_RGU_ON_GPS_L5_PON_S_EN_RGU_GPS_L5_PWR_ON_S_EN_ADDR GPS_RGU_ON_GPS_L5_PON_S_EN_ADDR
#define GPS_RGU_ON_GPS_L5_PON_S_EN_RGU_GPS_L5_PWR_ON_S_EN_MASK 0x00000001
#define GPS_RGU_ON_GPS_L5_PON_S_EN_RGU_GPS_L5_PWR_ON_S_EN_SHFT 0

#define GPS_RGU_ON_GPS_L5_RGU_RESERVED_RGU_GPS_L5_RESERVED4_ADDR GPS_RGU_ON_GPS_L5_RGU_RESERVED_ADDR
#define GPS_RGU_ON_GPS_L5_RGU_RESERVED_RGU_GPS_L5_RESERVED4_MASK 0xFFFFFFC0
#define GPS_RGU_ON_GPS_L5_RGU_RESERVED_RGU_GPS_L5_RESERVED4_SHFT 6
#define GPS_RGU_ON_GPS_L5_RGU_RESERVED_RGU_GPS_L5_RESERVED3_ADDR GPS_RGU_ON_GPS_L5_RGU_RESERVED_ADDR
#define GPS_RGU_ON_GPS_L5_RGU_RESERVED_RGU_GPS_L5_RESERVED3_MASK 0x00000030
#define GPS_RGU_ON_GPS_L5_RGU_RESERVED_RGU_GPS_L5_RESERVED3_SHFT 4
#define GPS_RGU_ON_GPS_L5_RGU_RESERVED_RGU_GPS_L5_RESERVED2_ADDR GPS_RGU_ON_GPS_L5_RGU_RESERVED_ADDR
#define GPS_RGU_ON_GPS_L5_RGU_RESERVED_RGU_GPS_L5_RESERVED2_MASK 0x0000000C
#define GPS_RGU_ON_GPS_L5_RGU_RESERVED_RGU_GPS_L5_RESERVED2_SHFT 2
#define GPS_RGU_ON_GPS_L5_RGU_RESERVED_RGU_GPS_L5_RESERVED1_ADDR GPS_RGU_ON_GPS_L5_RGU_RESERVED_ADDR
#define GPS_RGU_ON_GPS_L5_RGU_RESERVED_RGU_GPS_L5_RESERVED1_MASK 0x00000002
#define GPS_RGU_ON_GPS_L5_RGU_RESERVED_RGU_GPS_L5_RESERVED1_SHFT 1
#define GPS_RGU_ON_GPS_L5_RGU_RESERVED_RGU_GPS_L5_RESERVED0_ADDR GPS_RGU_ON_GPS_L5_RGU_RESERVED_ADDR
#define GPS_RGU_ON_GPS_L5_RGU_RESERVED_RGU_GPS_L5_RESERVED0_MASK 0x00000001
#define GPS_RGU_ON_GPS_L5_RGU_RESERVED_RGU_GPS_L5_RESERVED0_SHFT 0

#define GPS_RGU_ON_GPS_L5_SEC_CROM_PDN_EN_RGU_GPS_L5_SEC_CROM_HWCTL_PDN_ADDR GPS_RGU_ON_GPS_L5_SEC_CROM_PDN_EN_ADDR
#define GPS_RGU_ON_GPS_L5_SEC_CROM_PDN_EN_RGU_GPS_L5_SEC_CROM_HWCTL_PDN_MASK 0x00000003
#define GPS_RGU_ON_GPS_L5_SEC_CROM_PDN_EN_RGU_GPS_L5_SEC_CROM_HWCTL_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPPROM_PDN_EN_RGU_GPS_L5_PROM_HWCTL_PDN_ADDR GPS_RGU_ON_GPS_L5_DSPPROM_PDN_EN_ADDR
#define GPS_RGU_ON_GPS_L5_DSPPROM_PDN_EN_RGU_GPS_L5_PROM_HWCTL_PDN_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L5_DSPPROM_PDN_EN_RGU_GPS_L5_PROM_HWCTL_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPPRAM_PDN_EN_RGU_GPS_L5_PRAM_HWCTL_PDN_ADDR GPS_RGU_ON_GPS_L5_DSPPRAM_PDN_EN_ADDR
#define GPS_RGU_ON_GPS_L5_DSPPRAM_PDN_EN_RGU_GPS_L5_PRAM_HWCTL_PDN_MASK 0x000003FF
#define GPS_RGU_ON_GPS_L5_DSPPRAM_PDN_EN_RGU_GPS_L5_PRAM_HWCTL_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPPRAM_SLP_EN_RGU_GPS_L5_PRAM_HWCTL_SLP_ADDR GPS_RGU_ON_GPS_L5_DSPPRAM_SLP_EN_ADDR
#define GPS_RGU_ON_GPS_L5_DSPPRAM_SLP_EN_RGU_GPS_L5_PRAM_HWCTL_SLP_MASK 0x000003FF
#define GPS_RGU_ON_GPS_L5_DSPPRAM_SLP_EN_RGU_GPS_L5_PRAM_HWCTL_SLP_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPXRAM_PDN_EN_RGU_GPS_L5_XRAM_HWCTL_PDN_ADDR GPS_RGU_ON_GPS_L5_DSPXRAM_PDN_EN_ADDR
#define GPS_RGU_ON_GPS_L5_DSPXRAM_PDN_EN_RGU_GPS_L5_XRAM_HWCTL_PDN_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L5_DSPXRAM_PDN_EN_RGU_GPS_L5_XRAM_HWCTL_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPXRAM_SLP_EN_RGU_GPS_L5_XRAM_HWCTL_SLP_ADDR GPS_RGU_ON_GPS_L5_DSPXRAM_SLP_EN_ADDR
#define GPS_RGU_ON_GPS_L5_DSPXRAM_SLP_EN_RGU_GPS_L5_XRAM_HWCTL_SLP_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L5_DSPXRAM_SLP_EN_RGU_GPS_L5_XRAM_HWCTL_SLP_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPYRAM_PDN_EN_RGU_GPS_L5_YRAM_HWCTL_PDN_ADDR GPS_RGU_ON_GPS_L5_DSPYRAM_PDN_EN_ADDR
#define GPS_RGU_ON_GPS_L5_DSPYRAM_PDN_EN_RGU_GPS_L5_YRAM_HWCTL_PDN_MASK 0x000003FF
#define GPS_RGU_ON_GPS_L5_DSPYRAM_PDN_EN_RGU_GPS_L5_YRAM_HWCTL_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPYRAM_SLP_EN_RGU_GPS_L5_YRAM_HWCTL_SLP_ADDR GPS_RGU_ON_GPS_L5_DSPYRAM_SLP_EN_ADDR
#define GPS_RGU_ON_GPS_L5_DSPYRAM_SLP_EN_RGU_GPS_L5_YRAM_HWCTL_SLP_MASK 0x000003FF
#define GPS_RGU_ON_GPS_L5_DSPYRAM_SLP_EN_RGU_GPS_L5_YRAM_HWCTL_SLP_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPURAM_PDN_EN_RGU_GPS_L5_URAM_HWCTL_PDN_ADDR GPS_RGU_ON_GPS_L5_DSPURAM_PDN_EN_ADDR
#define GPS_RGU_ON_GPS_L5_DSPURAM_PDN_EN_RGU_GPS_L5_URAM_HWCTL_PDN_MASK 0x00000003
#define GPS_RGU_ON_GPS_L5_DSPURAM_PDN_EN_RGU_GPS_L5_URAM_HWCTL_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPURAM_SLP_EN_RGU_GPS_L5_URAM_HWCTL_SLP_ADDR GPS_RGU_ON_GPS_L5_DSPURAM_SLP_EN_ADDR
#define GPS_RGU_ON_GPS_L5_DSPURAM_SLP_EN_RGU_GPS_L5_URAM_HWCTL_SLP_MASK 0x00000003
#define GPS_RGU_ON_GPS_L5_DSPURAM_SLP_EN_RGU_GPS_L5_URAM_HWCTL_SLP_SHFT 0

#define GPS_RGU_ON_GPS_L5_SEC_CROM_PDN_RGU_GPS_L5_SEC_CROM_SWCTL_PDN_ADDR GPS_RGU_ON_GPS_L5_SEC_CROM_PDN_ADDR
#define GPS_RGU_ON_GPS_L5_SEC_CROM_PDN_RGU_GPS_L5_SEC_CROM_SWCTL_PDN_MASK 0x00000003
#define GPS_RGU_ON_GPS_L5_SEC_CROM_PDN_RGU_GPS_L5_SEC_CROM_SWCTL_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPPROM_PDN_RGU_GPS_L5_PROM_SWCTL_PDN_ADDR GPS_RGU_ON_GPS_L5_DSPPROM_PDN_ADDR
#define GPS_RGU_ON_GPS_L5_DSPPROM_PDN_RGU_GPS_L5_PROM_SWCTL_PDN_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L5_DSPPROM_PDN_RGU_GPS_L5_PROM_SWCTL_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPPRAM_PDN_RGU_GPS_L5_PRAM_SWCTL_PDN_ADDR GPS_RGU_ON_GPS_L5_DSPPRAM_PDN_ADDR
#define GPS_RGU_ON_GPS_L5_DSPPRAM_PDN_RGU_GPS_L5_PRAM_SWCTL_PDN_MASK 0x000003FF
#define GPS_RGU_ON_GPS_L5_DSPPRAM_PDN_RGU_GPS_L5_PRAM_SWCTL_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPPRAM_SLP_RGU_GPS_L5_PRAM_SWCTL_SLP_ADDR GPS_RGU_ON_GPS_L5_DSPPRAM_SLP_ADDR
#define GPS_RGU_ON_GPS_L5_DSPPRAM_SLP_RGU_GPS_L5_PRAM_SWCTL_SLP_MASK 0x000003FF
#define GPS_RGU_ON_GPS_L5_DSPPRAM_SLP_RGU_GPS_L5_PRAM_SWCTL_SLP_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPPRAM_ISO_RGU_GPS_L5_PRAM_SWCTL_ISO_ADDR GPS_RGU_ON_GPS_L5_DSPPRAM_ISO_ADDR
#define GPS_RGU_ON_GPS_L5_DSPPRAM_ISO_RGU_GPS_L5_PRAM_SWCTL_ISO_MASK 0x000003FF
#define GPS_RGU_ON_GPS_L5_DSPPRAM_ISO_RGU_GPS_L5_PRAM_SWCTL_ISO_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPPRAM_ISOINT_RGU_GPS_L5_PRAM_SWCTL_ISOINT_ADDR GPS_RGU_ON_GPS_L5_DSPPRAM_ISOINT_ADDR
#define GPS_RGU_ON_GPS_L5_DSPPRAM_ISOINT_RGU_GPS_L5_PRAM_SWCTL_ISOINT_MASK 0x000003FF
#define GPS_RGU_ON_GPS_L5_DSPPRAM_ISOINT_RGU_GPS_L5_PRAM_SWCTL_ISOINT_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPXRAM_PDN_RGU_GPS_L5_XRAM_SWCTL_PDN_ADDR GPS_RGU_ON_GPS_L5_DSPXRAM_PDN_ADDR
#define GPS_RGU_ON_GPS_L5_DSPXRAM_PDN_RGU_GPS_L5_XRAM_SWCTL_PDN_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L5_DSPXRAM_PDN_RGU_GPS_L5_XRAM_SWCTL_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPXRAM_SLP_RGU_GPS_L5_XRAM_SWCTL_SLP_ADDR GPS_RGU_ON_GPS_L5_DSPXRAM_SLP_ADDR
#define GPS_RGU_ON_GPS_L5_DSPXRAM_SLP_RGU_GPS_L5_XRAM_SWCTL_SLP_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L5_DSPXRAM_SLP_RGU_GPS_L5_XRAM_SWCTL_SLP_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPXRAM_ISO_RGU_GPS_L5_XRAM_SWCTL_ISO_ADDR GPS_RGU_ON_GPS_L5_DSPXRAM_ISO_ADDR
#define GPS_RGU_ON_GPS_L5_DSPXRAM_ISO_RGU_GPS_L5_XRAM_SWCTL_ISO_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L5_DSPXRAM_ISO_RGU_GPS_L5_XRAM_SWCTL_ISO_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPXRAM_ISOINT_RGU_GPS_L5_XRAM_SWCTL_ISOINT_ADDR GPS_RGU_ON_GPS_L5_DSPXRAM_ISOINT_ADDR
#define GPS_RGU_ON_GPS_L5_DSPXRAM_ISOINT_RGU_GPS_L5_XRAM_SWCTL_ISOINT_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L5_DSPXRAM_ISOINT_RGU_GPS_L5_XRAM_SWCTL_ISOINT_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPYRAM_PDN_RGU_GPS_L5_YRAM_SWCTL_PDN_ADDR GPS_RGU_ON_GPS_L5_DSPYRAM_PDN_ADDR
#define GPS_RGU_ON_GPS_L5_DSPYRAM_PDN_RGU_GPS_L5_YRAM_SWCTL_PDN_MASK 0x000003FF
#define GPS_RGU_ON_GPS_L5_DSPYRAM_PDN_RGU_GPS_L5_YRAM_SWCTL_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPYRAM_SLP_RGU_GPS_L5_YRAM_SWCTL_SLP_ADDR GPS_RGU_ON_GPS_L5_DSPYRAM_SLP_ADDR
#define GPS_RGU_ON_GPS_L5_DSPYRAM_SLP_RGU_GPS_L5_YRAM_SWCTL_SLP_MASK 0x000003FF
#define GPS_RGU_ON_GPS_L5_DSPYRAM_SLP_RGU_GPS_L5_YRAM_SWCTL_SLP_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPYRAM_ISO_RGU_GPS_L5_YRAM_SWCTL_ISO_ADDR GPS_RGU_ON_GPS_L5_DSPYRAM_ISO_ADDR
#define GPS_RGU_ON_GPS_L5_DSPYRAM_ISO_RGU_GPS_L5_YRAM_SWCTL_ISO_MASK 0x000003FF
#define GPS_RGU_ON_GPS_L5_DSPYRAM_ISO_RGU_GPS_L5_YRAM_SWCTL_ISO_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPYRAM_ISOINT_RGU_GPS_L5_YRAM_SWCTL_ISOINT_ADDR GPS_RGU_ON_GPS_L5_DSPYRAM_ISOINT_ADDR
#define GPS_RGU_ON_GPS_L5_DSPYRAM_ISOINT_RGU_GPS_L5_YRAM_SWCTL_ISOINT_MASK 0x000003FF
#define GPS_RGU_ON_GPS_L5_DSPYRAM_ISOINT_RGU_GPS_L5_YRAM_SWCTL_ISOINT_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPURAM_PDN_RGU_GPS_L5_URAM_SWCTL_PDN_ADDR GPS_RGU_ON_GPS_L5_DSPURAM_PDN_ADDR
#define GPS_RGU_ON_GPS_L5_DSPURAM_PDN_RGU_GPS_L5_URAM_SWCTL_PDN_MASK 0x00000003
#define GPS_RGU_ON_GPS_L5_DSPURAM_PDN_RGU_GPS_L5_URAM_SWCTL_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPURAM_SLP_RGU_GPS_L5_URAM_SWCTL_SLP_ADDR GPS_RGU_ON_GPS_L5_DSPURAM_SLP_ADDR
#define GPS_RGU_ON_GPS_L5_DSPURAM_SLP_RGU_GPS_L5_URAM_SWCTL_SLP_MASK 0x00000003
#define GPS_RGU_ON_GPS_L5_DSPURAM_SLP_RGU_GPS_L5_URAM_SWCTL_SLP_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPURAM_ISO_RGU_GPS_L5_URAM_SWCTL_ISO_ADDR GPS_RGU_ON_GPS_L5_DSPURAM_ISO_ADDR
#define GPS_RGU_ON_GPS_L5_DSPURAM_ISO_RGU_GPS_L5_URAM_SWCTL_ISO_MASK 0x00000003
#define GPS_RGU_ON_GPS_L5_DSPURAM_ISO_RGU_GPS_L5_URAM_SWCTL_ISO_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPURAM_ISOINT_RGU_GPS_L5_URAM_SWCTL_ISOINT_ADDR GPS_RGU_ON_GPS_L5_DSPURAM_ISOINT_ADDR
#define GPS_RGU_ON_GPS_L5_DSPURAM_ISOINT_RGU_GPS_L5_URAM_SWCTL_ISOINT_MASK 0x00000003
#define GPS_RGU_ON_GPS_L5_DSPURAM_ISOINT_RGU_GPS_L5_URAM_SWCTL_ISOINT_SHFT 0

#define GPS_RGU_ON_GPS_L5_SEC_CROM_PDN_STAT_GPSSYS_L5_SEC_CROM_PWR_DOWN_ADDR GPS_RGU_ON_GPS_L5_SEC_CROM_PDN_STAT_ADDR
#define GPS_RGU_ON_GPS_L5_SEC_CROM_PDN_STAT_GPSSYS_L5_SEC_CROM_PWR_DOWN_MASK 0x00000003
#define GPS_RGU_ON_GPS_L5_SEC_CROM_PDN_STAT_GPSSYS_L5_SEC_CROM_PWR_DOWN_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPPROM_PDN_STAT_GPSSYS_L5_PROM_PWR_DOWN_ADDR GPS_RGU_ON_GPS_L5_DSPPROM_PDN_STAT_ADDR
#define GPS_RGU_ON_GPS_L5_DSPPROM_PDN_STAT_GPSSYS_L5_PROM_PWR_DOWN_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L5_DSPPROM_PDN_STAT_GPSSYS_L5_PROM_PWR_DOWN_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPPRAM_PDN_STAT_GPSSYS_L5_PRAM_MEM_PDN_ADDR GPS_RGU_ON_GPS_L5_DSPPRAM_PDN_STAT_ADDR
#define GPS_RGU_ON_GPS_L5_DSPPRAM_PDN_STAT_GPSSYS_L5_PRAM_MEM_PDN_MASK 0x000003FF
#define GPS_RGU_ON_GPS_L5_DSPPRAM_PDN_STAT_GPSSYS_L5_PRAM_MEM_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPPRAM_SLP_STAT_GPSSYS_L5_PRAM_MEM_SLP_ADDR GPS_RGU_ON_GPS_L5_DSPPRAM_SLP_STAT_ADDR
#define GPS_RGU_ON_GPS_L5_DSPPRAM_SLP_STAT_GPSSYS_L5_PRAM_MEM_SLP_MASK 0x000003FF
#define GPS_RGU_ON_GPS_L5_DSPPRAM_SLP_STAT_GPSSYS_L5_PRAM_MEM_SLP_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPPRAM_ISO_STAT_GPSSYS_L5_PRAM_MEM_ISO_ADDR GPS_RGU_ON_GPS_L5_DSPPRAM_ISO_STAT_ADDR
#define GPS_RGU_ON_GPS_L5_DSPPRAM_ISO_STAT_GPSSYS_L5_PRAM_MEM_ISO_MASK 0x000003FF
#define GPS_RGU_ON_GPS_L5_DSPPRAM_ISO_STAT_GPSSYS_L5_PRAM_MEM_ISO_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPPRAM_ISOINT_STAT_GPSSYS_L5_PRAM_MEM_ISOINT_ADDR GPS_RGU_ON_GPS_L5_DSPPRAM_ISOINT_STAT_ADDR
#define GPS_RGU_ON_GPS_L5_DSPPRAM_ISOINT_STAT_GPSSYS_L5_PRAM_MEM_ISOINT_MASK 0x000003FF
#define GPS_RGU_ON_GPS_L5_DSPPRAM_ISOINT_STAT_GPSSYS_L5_PRAM_MEM_ISOINT_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPXRAM_PDN_STAT_GPSSYS_L5_XRAM_MEM_PDN_ADDR GPS_RGU_ON_GPS_L5_DSPXRAM_PDN_STAT_ADDR
#define GPS_RGU_ON_GPS_L5_DSPXRAM_PDN_STAT_GPSSYS_L5_XRAM_MEM_PDN_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L5_DSPXRAM_PDN_STAT_GPSSYS_L5_XRAM_MEM_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPXRAM_SLP_STAT_GPSSYS_L5_XRAM_MEM_SLP_ADDR GPS_RGU_ON_GPS_L5_DSPXRAM_SLP_STAT_ADDR
#define GPS_RGU_ON_GPS_L5_DSPXRAM_SLP_STAT_GPSSYS_L5_XRAM_MEM_SLP_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L5_DSPXRAM_SLP_STAT_GPSSYS_L5_XRAM_MEM_SLP_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPXRAM_ISO_STAT_GPSSYS_L5_XRAM_MEM_ISO_ADDR GPS_RGU_ON_GPS_L5_DSPXRAM_ISO_STAT_ADDR
#define GPS_RGU_ON_GPS_L5_DSPXRAM_ISO_STAT_GPSSYS_L5_XRAM_MEM_ISO_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L5_DSPXRAM_ISO_STAT_GPSSYS_L5_XRAM_MEM_ISO_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPXRAM_ISOINT_STAT_GPSSYS_L5_XRAM_MEM_ISOINT_ADDR GPS_RGU_ON_GPS_L5_DSPXRAM_ISOINT_STAT_ADDR
#define GPS_RGU_ON_GPS_L5_DSPXRAM_ISOINT_STAT_GPSSYS_L5_XRAM_MEM_ISOINT_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L5_DSPXRAM_ISOINT_STAT_GPSSYS_L5_XRAM_MEM_ISOINT_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPYRAM_PDN_STAT_GPSSYS_L5_YRAM_MEM_PDN_ADDR GPS_RGU_ON_GPS_L5_DSPYRAM_PDN_STAT_ADDR
#define GPS_RGU_ON_GPS_L5_DSPYRAM_PDN_STAT_GPSSYS_L5_YRAM_MEM_PDN_MASK 0x000003FF
#define GPS_RGU_ON_GPS_L5_DSPYRAM_PDN_STAT_GPSSYS_L5_YRAM_MEM_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPYRAM_SLP_STAT_GPSSYS_L5_YRAM_MEM_SLP_ADDR GPS_RGU_ON_GPS_L5_DSPYRAM_SLP_STAT_ADDR
#define GPS_RGU_ON_GPS_L5_DSPYRAM_SLP_STAT_GPSSYS_L5_YRAM_MEM_SLP_MASK 0x000003FF
#define GPS_RGU_ON_GPS_L5_DSPYRAM_SLP_STAT_GPSSYS_L5_YRAM_MEM_SLP_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPYRAM_ISO_STAT_GPSSYS_L5_YRAM_MEM_ISO_ADDR GPS_RGU_ON_GPS_L5_DSPYRAM_ISO_STAT_ADDR
#define GPS_RGU_ON_GPS_L5_DSPYRAM_ISO_STAT_GPSSYS_L5_YRAM_MEM_ISO_MASK 0x000003FF
#define GPS_RGU_ON_GPS_L5_DSPYRAM_ISO_STAT_GPSSYS_L5_YRAM_MEM_ISO_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPYRAM_ISOINT_STAT_GPSSYS_L5_YRAM_MEM_ISOINT_ADDR GPS_RGU_ON_GPS_L5_DSPYRAM_ISOINT_STAT_ADDR
#define GPS_RGU_ON_GPS_L5_DSPYRAM_ISOINT_STAT_GPSSYS_L5_YRAM_MEM_ISOINT_MASK 0x000003FF
#define GPS_RGU_ON_GPS_L5_DSPYRAM_ISOINT_STAT_GPSSYS_L5_YRAM_MEM_ISOINT_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPURAM_PDN_STAT_GPSSYS_L5_URAM_MEM_PDN_ADDR GPS_RGU_ON_GPS_L5_DSPURAM_PDN_STAT_ADDR
#define GPS_RGU_ON_GPS_L5_DSPURAM_PDN_STAT_GPSSYS_L5_URAM_MEM_PDN_MASK 0x00000003
#define GPS_RGU_ON_GPS_L5_DSPURAM_PDN_STAT_GPSSYS_L5_URAM_MEM_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPURAM_SLP_STAT_GPSSYS_L5_URAM_MEM_SLP_ADDR GPS_RGU_ON_GPS_L5_DSPURAM_SLP_STAT_ADDR
#define GPS_RGU_ON_GPS_L5_DSPURAM_SLP_STAT_GPSSYS_L5_URAM_MEM_SLP_MASK 0x00000003
#define GPS_RGU_ON_GPS_L5_DSPURAM_SLP_STAT_GPSSYS_L5_URAM_MEM_SLP_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPURAM_ISO_STAT_GPSSYS_L5_URAM_MEM_ISO_ADDR GPS_RGU_ON_GPS_L5_DSPURAM_ISO_STAT_ADDR
#define GPS_RGU_ON_GPS_L5_DSPURAM_ISO_STAT_GPSSYS_L5_URAM_MEM_ISO_MASK 0x00000003
#define GPS_RGU_ON_GPS_L5_DSPURAM_ISO_STAT_GPSSYS_L5_URAM_MEM_ISO_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPURAM_ISOINT_STAT_GPSSYS_L5_URAM_MEM_ISOINT_ADDR GPS_RGU_ON_GPS_L5_DSPURAM_ISOINT_STAT_ADDR
#define GPS_RGU_ON_GPS_L5_DSPURAM_ISOINT_STAT_GPSSYS_L5_URAM_MEM_ISOINT_MASK 0x00000003
#define GPS_RGU_ON_GPS_L5_DSPURAM_ISOINT_STAT_GPSSYS_L5_URAM_MEM_ISOINT_SHFT 0

#define GPS_RGU_ON_GPS_L5_SEC_CROM_RST_REG_GPS_L5_SEC_CROM_RST_B_ADDR GPS_RGU_ON_GPS_L5_SEC_CROM_RST_ADDR
#define GPS_RGU_ON_GPS_L5_SEC_CROM_RST_REG_GPS_L5_SEC_CROM_RST_B_MASK 0x00000001
#define GPS_RGU_ON_GPS_L5_SEC_CROM_RST_REG_GPS_L5_SEC_CROM_RST_B_SHFT 0

#define GPS_RGU_ON_GPS_L5_CHN_MEM_DYN_OFF_GPS_L5_CH1_MEM_DYN_OFF_ADDR GPS_RGU_ON_GPS_L5_CHN_MEM_DYN_OFF_ADDR
#define GPS_RGU_ON_GPS_L5_CHN_MEM_DYN_OFF_GPS_L5_CH1_MEM_DYN_OFF_MASK 0x00000002
#define GPS_RGU_ON_GPS_L5_CHN_MEM_DYN_OFF_GPS_L5_CH1_MEM_DYN_OFF_SHFT 1
#define GPS_RGU_ON_GPS_L5_CHN_MEM_DYN_OFF_GPS_L5_CH0_MEM_DYN_OFF_ADDR GPS_RGU_ON_GPS_L5_CHN_MEM_DYN_OFF_ADDR
#define GPS_RGU_ON_GPS_L5_CHN_MEM_DYN_OFF_GPS_L5_CH0_MEM_DYN_OFF_MASK 0x00000001
#define GPS_RGU_ON_GPS_L5_CHN_MEM_DYN_OFF_GPS_L5_CH0_MEM_DYN_OFF_SHFT 0

#define GPS_RGU_ON_GPS_L5_CH0_MEM_PDN_STAT_GPSSYS_L5_CH0MEM_PWR_DOWN_ADDR GPS_RGU_ON_GPS_L5_CH0_MEM_PDN_STAT_ADDR
#define GPS_RGU_ON_GPS_L5_CH0_MEM_PDN_STAT_GPSSYS_L5_CH0MEM_PWR_DOWN_MASK 0x0000001F
#define GPS_RGU_ON_GPS_L5_CH0_MEM_PDN_STAT_GPSSYS_L5_CH0MEM_PWR_DOWN_SHFT 0

#define GPS_RGU_ON_GPS_L5_CH1_MEM_PDN_STAT_GPSSYS_L5_CH1MEM_PWR_DOWN_ADDR GPS_RGU_ON_GPS_L5_CH1_MEM_PDN_STAT_ADDR
#define GPS_RGU_ON_GPS_L5_CH1_MEM_PDN_STAT_GPSSYS_L5_CH1MEM_PWR_DOWN_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L5_CH1_MEM_PDN_STAT_GPSSYS_L5_CH1MEM_PWR_DOWN_SHFT 0

#define GPS_RGU_ON_GPS_L5_DLY_CHAIN_CTL_RGU_GPS_L5_MEM_ISO_DLY_SHIFT_EN_ADDR GPS_RGU_ON_GPS_L5_DLY_CHAIN_CTL_ADDR
#define GPS_RGU_ON_GPS_L5_DLY_CHAIN_CTL_RGU_GPS_L5_MEM_ISO_DLY_SHIFT_EN_MASK 0x80000000
#define GPS_RGU_ON_GPS_L5_DLY_CHAIN_CTL_RGU_GPS_L5_MEM_ISO_DLY_SHIFT_EN_SHFT 31
#define GPS_RGU_ON_GPS_L5_DLY_CHAIN_CTL_RGU_GPS_L5_MEM_ISO_DELAY_NUM_ADDR GPS_RGU_ON_GPS_L5_DLY_CHAIN_CTL_ADDR
#define GPS_RGU_ON_GPS_L5_DLY_CHAIN_CTL_RGU_GPS_L5_MEM_ISO_DELAY_NUM_MASK 0x00700000
#define GPS_RGU_ON_GPS_L5_DLY_CHAIN_CTL_RGU_GPS_L5_MEM_ISO_DELAY_NUM_SHFT 20
#define GPS_RGU_ON_GPS_L5_DLY_CHAIN_CTL_RGU_GPS_L5_MEM_PDN_DELAY_DUMMY_NUM_ADDR GPS_RGU_ON_GPS_L5_DLY_CHAIN_CTL_ADDR
#define GPS_RGU_ON_GPS_L5_DLY_CHAIN_CTL_RGU_GPS_L5_MEM_PDN_DELAY_DUMMY_NUM_MASK 0x000F0000
#define GPS_RGU_ON_GPS_L5_DLY_CHAIN_CTL_RGU_GPS_L5_MEM_PDN_DELAY_DUMMY_NUM_SHFT 16
#define GPS_RGU_ON_GPS_L5_DLY_CHAIN_CTL_RGU_GPSSYS_L5_MEM_ISO_PRE_ADDR GPS_RGU_ON_GPS_L5_DLY_CHAIN_CTL_ADDR
#define GPS_RGU_ON_GPS_L5_DLY_CHAIN_CTL_RGU_GPSSYS_L5_MEM_ISO_PRE_MASK 0x000003FF
#define GPS_RGU_ON_GPS_L5_DLY_CHAIN_CTL_RGU_GPSSYS_L5_MEM_ISO_PRE_SHFT 0

#define GPS_RGU_ON_GPS_L5_MEM_DLY_CTL_RGU_GPSSYS_L5_MEM_ADJ_DLY_EN_ADDR GPS_RGU_ON_GPS_L5_MEM_DLY_CTL_ADDR
#define GPS_RGU_ON_GPS_L5_MEM_DLY_CTL_RGU_GPSSYS_L5_MEM_ADJ_DLY_EN_MASK 0x80000000
#define GPS_RGU_ON_GPS_L5_MEM_DLY_CTL_RGU_GPSSYS_L5_MEM_ADJ_DLY_EN_SHFT 31
#define GPS_RGU_ON_GPS_L5_MEM_DLY_CTL_RGU_GPSSYS_L5_MEM_PON_DLY_ADDR GPS_RGU_ON_GPS_L5_MEM_DLY_CTL_ADDR
#define GPS_RGU_ON_GPS_L5_MEM_DLY_CTL_RGU_GPSSYS_L5_MEM_PON_DLY_MASK 0x03FF0000
#define GPS_RGU_ON_GPS_L5_MEM_DLY_CTL_RGU_GPSSYS_L5_MEM_PON_DLY_SHFT 16
#define GPS_RGU_ON_GPS_L5_MEM_DLY_CTL_RGU_GPSSYS_L5_MEM_PDN_DLY_ADDR GPS_RGU_ON_GPS_L5_MEM_DLY_CTL_ADDR
#define GPS_RGU_ON_GPS_L5_MEM_DLY_CTL_RGU_GPSSYS_L5_MEM_PDN_DLY_MASK 0x000003FF
#define GPS_RGU_ON_GPS_L5_MEM_DLY_CTL_RGU_GPSSYS_L5_MEM_PDN_DLY_SHFT 0

#endif /* __GPS_RGU_ON_REGS_H__ */

