/*
 * Copyright (C) 2019 MediaTek Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See http://www.gnu.org/licenses/gpl-2.0.html for more details.
 */
#ifndef __GPS_AON_TOP_REGS_H__
#define __GPS_AON_TOP_REGS_H__

#define GPS_AON_TOP_BASE                                       0x80073000

#define GPS_AON_TOP_TCXO_DIV_ADDR                              (GPS_AON_TOP_BASE + 0x0100)
#define GPS_AON_TOP_TCXO_MS_CTL_ADDR                           (GPS_AON_TOP_BASE + 0x0104)
#define GPS_AON_TOP_DSLEEP_CTL_ADDR                            (GPS_AON_TOP_BASE + 0x0108)
#define GPS_AON_TOP_WAKEUP_MS_CNT_ADDR                         (GPS_AON_TOP_BASE + 0x010C)
#define GPS_AON_TOP_WAKEUP_CTL_ADDR                            (GPS_AON_TOP_BASE + 0x0110)
#define GPS_AON_TOP_TCXO_MS_H_ADDR                             (GPS_AON_TOP_BASE + 0x0114)
#define GPS_AON_TOP_TCXO_MS_L_ADDR                             (GPS_AON_TOP_BASE + 0x0118)
#define GPS_AON_TOP_APB2ZBUS_EN_ADDR                           (GPS_AON_TOP_BASE + 0x0120)
#define GPS_AON_TOP_GPS_RTC_TIMER_CTL_ADDR                     (GPS_AON_TOP_BASE + 0x0124)
#define GPS_AON_TOP_GPS_RTC_TIMER_CNT_ADDR                     (GPS_AON_TOP_BASE + 0x0128)
#define GPS_AON_TOP_GPS_RTC_TIMER_CNT_READ_ADDR                (GPS_AON_TOP_BASE + 0x012C)
#define GPS_AON_TOP_GPS_HW_VERSION_ADDR                        (GPS_AON_TOP_BASE + 0x0130)
#define GPS_AON_TOP_GPS_SW_VERSION_ADDR                        (GPS_AON_TOP_BASE + 0x0134)
#define GPS_AON_TOP_GPS_CONFIG_ID_ADDR                         (GPS_AON_TOP_BASE + 0x0138)
#define GPS_AON_TOP_CMD_ICAP_STATUS_ADDR                       (GPS_AON_TOP_BASE + 0x013C)
#define GPS_AON_TOP_CMD_ADC_CLKDIV_ADDR                        (GPS_AON_TOP_BASE + 0x0140)
#define GPS_AON_TOP_GPS_SCLK_CTL_ADDR                          (GPS_AON_TOP_BASE + 0x0144)
#define GPS_AON_TOP_GPS_DSP_SEL_ADDR                           (GPS_AON_TOP_BASE + 0x0148)
#define GPS_AON_TOP_GPS_SYNC_CTL_ADDR                          (GPS_AON_TOP_BASE + 0x014C)
#define GPS_AON_TOP_GPS_MTCMOS_CTL_ADDR                        (GPS_AON_TOP_BASE + 0x0150)
#define GPS_AON_TOP_GPS_MTCMOS_STA_ADDR                        (GPS_AON_TOP_BASE + 0x0154)
#define GPS_AON_TOP_GPS_SLP_CTL_ADDR                           (GPS_AON_TOP_BASE + 0x0158)
#define GPS_AON_TOP_AON_DUMMY_ADDR                             (GPS_AON_TOP_BASE + 0x0160)
#define GPS_AON_TOP_RBIST_CLEAR_ADDR                           (GPS_AON_TOP_BASE + 0x0180)
#define GPS_AON_TOP_RBIST_RESET_ADDR                           (GPS_AON_TOP_BASE + 0x0184)
#define GPS_AON_TOP_RBIST_LENGTH_ADDR                          (GPS_AON_TOP_BASE + 0x0188)
#define GPS_AON_TOP_RBIST_OFFSET_ADDR                          (GPS_AON_TOP_BASE + 0x018C)
#define GPS_AON_TOP_RBIST_CONTROL_ADDR                         (GPS_AON_TOP_BASE + 0x0190)
#define GPS_AON_TOP_RBIST_DEBUG_OPTION_ADDR                    (GPS_AON_TOP_BASE + 0x0194)
#define GPS_AON_TOP_RBIST_FIFO_THRESHOLD_ADDR                  (GPS_AON_TOP_BASE + 0x0198)
#define GPS_AON_TOP_RBIST_FIFO_READ_0_ADDR                     (GPS_AON_TOP_BASE + 0x01A0)
#define GPS_AON_TOP_RBIST_FIFO_READ_1_ADDR                     (GPS_AON_TOP_BASE + 0x01A4)
#define GPS_AON_TOP_RBIST_FIFO_READ_2_ADDR                     (GPS_AON_TOP_BASE + 0x01A8)
#define GPS_AON_TOP_RBIST_DEBUG_RESULT_ADDR                    (GPS_AON_TOP_BASE + 0x01C0)


#define GPS_AON_TOP_TCXO_DIV_TCXO_CLK_DIV_ADDR                 GPS_AON_TOP_TCXO_DIV_ADDR
#define GPS_AON_TOP_TCXO_DIV_TCXO_CLK_DIV_MASK                 0x0000FFFF
#define GPS_AON_TOP_TCXO_DIV_TCXO_CLK_DIV_SHFT                 0

#define GPS_AON_TOP_TCXO_MS_CTL_TCXO_SYNC_PULSE_ADDR           GPS_AON_TOP_TCXO_MS_CTL_ADDR
#define GPS_AON_TOP_TCXO_MS_CTL_TCXO_SYNC_PULSE_MASK           0x00000004
#define GPS_AON_TOP_TCXO_MS_CTL_TCXO_SYNC_PULSE_SHFT           2
#define GPS_AON_TOP_TCXO_MS_CTL_TCXO_SYNC_EN_ADDR              GPS_AON_TOP_TCXO_MS_CTL_ADDR
#define GPS_AON_TOP_TCXO_MS_CTL_TCXO_SYNC_EN_MASK              0x00000002
#define GPS_AON_TOP_TCXO_MS_CTL_TCXO_SYNC_EN_SHFT              1
#define GPS_AON_TOP_TCXO_MS_CTL_TCXO_SYNC_LOAD_ADDR            GPS_AON_TOP_TCXO_MS_CTL_ADDR
#define GPS_AON_TOP_TCXO_MS_CTL_TCXO_SYNC_LOAD_MASK            0x00000001
#define GPS_AON_TOP_TCXO_MS_CTL_TCXO_SYNC_LOAD_SHFT            0

#define GPS_AON_TOP_DSLEEP_CTL_FORCE_OSC_EN_ON_ADDR            GPS_AON_TOP_DSLEEP_CTL_ADDR
#define GPS_AON_TOP_DSLEEP_CTL_FORCE_OSC_EN_ON_MASK            0x00000008
#define GPS_AON_TOP_DSLEEP_CTL_FORCE_OSC_EN_ON_SHFT            3
#define GPS_AON_TOP_DSLEEP_CTL_FORCE_RFRST_B_ADDR              GPS_AON_TOP_DSLEEP_CTL_ADDR
#define GPS_AON_TOP_DSLEEP_CTL_FORCE_RFRST_B_MASK              0x00000004
#define GPS_AON_TOP_DSLEEP_CTL_FORCE_RFRST_B_SHFT              2
#define GPS_AON_TOP_DSLEEP_CTL_GPS_PWR_STAT_ADDR               GPS_AON_TOP_DSLEEP_CTL_ADDR
#define GPS_AON_TOP_DSLEEP_CTL_GPS_PWR_STAT_MASK               0x00000003
#define GPS_AON_TOP_DSLEEP_CTL_GPS_PWR_STAT_SHFT               0

#define GPS_AON_TOP_WAKEUP_MS_CNT_WAKEUP_MS_CNT_ADDR           GPS_AON_TOP_WAKEUP_MS_CNT_ADDR
#define GPS_AON_TOP_WAKEUP_MS_CNT_WAKEUP_MS_CNT_MASK           0x0000FFFF
#define GPS_AON_TOP_WAKEUP_MS_CNT_WAKEUP_MS_CNT_SHFT           0

#define GPS_AON_TOP_WAKEUP_CTL_TCXO_MS_RST_EN_ADDR             GPS_AON_TOP_WAKEUP_CTL_ADDR
#define GPS_AON_TOP_WAKEUP_CTL_TCXO_MS_RST_EN_MASK             0x00000002
#define GPS_AON_TOP_WAKEUP_CTL_TCXO_MS_RST_EN_SHFT             1
#define GPS_AON_TOP_WAKEUP_CTL_WAKEUP_MS_EN_ADDR               GPS_AON_TOP_WAKEUP_CTL_ADDR
#define GPS_AON_TOP_WAKEUP_CTL_WAKEUP_MS_EN_MASK               0x00000001
#define GPS_AON_TOP_WAKEUP_CTL_WAKEUP_MS_EN_SHFT               0

#define GPS_AON_TOP_TCXO_MS_H_TCXO_MS_H_ADDR                   GPS_AON_TOP_TCXO_MS_H_ADDR
#define GPS_AON_TOP_TCXO_MS_H_TCXO_MS_H_MASK                   0x0000FFFF
#define GPS_AON_TOP_TCXO_MS_H_TCXO_MS_H_SHFT                   0

#define GPS_AON_TOP_TCXO_MS_L_TCXO_MS_L_ADDR                   GPS_AON_TOP_TCXO_MS_L_ADDR
#define GPS_AON_TOP_TCXO_MS_L_TCXO_MS_L_MASK                   0x0000FFFF
#define GPS_AON_TOP_TCXO_MS_L_TCXO_MS_L_SHFT                   0

#define GPS_AON_TOP_apb2zbus_en_a2z_clk_ctl_rb_ADDR            GPS_AON_TOP_APB2ZBUS_EN_ADDR
#define GPS_AON_TOP_apb2zbus_en_a2z_clk_ctl_rb_MASK            0x00001000
#define GPS_AON_TOP_apb2zbus_en_a2z_clk_ctl_rb_SHFT            12
#define GPS_AON_TOP_apb2zbus_en_apb2zbus_tm_off_ADDR           GPS_AON_TOP_APB2ZBUS_EN_ADDR
#define GPS_AON_TOP_apb2zbus_en_apb2zbus_tm_off_MASK           0x00000100
#define GPS_AON_TOP_apb2zbus_en_apb2zbus_tm_off_SHFT           8
#define GPS_AON_TOP_apb2zbus_en_apb2zbus_en_ADDR               GPS_AON_TOP_APB2ZBUS_EN_ADDR
#define GPS_AON_TOP_apb2zbus_en_apb2zbus_en_MASK               0x00000001
#define GPS_AON_TOP_apb2zbus_en_apb2zbus_en_SHFT               0

#define GPS_AON_TOP_GPS_RTC_TIMER_CTL_TR_INTEN_ADDR            GPS_AON_TOP_GPS_RTC_TIMER_CTL_ADDR
#define GPS_AON_TOP_GPS_RTC_TIMER_CTL_TR_INTEN_MASK            0x00000002
#define GPS_AON_TOP_GPS_RTC_TIMER_CTL_TR_INTEN_SHFT            1

#define GPS_AON_TOP_GPS_RTC_TIMER_CNT_TIMER_CNT_ADDR           GPS_AON_TOP_GPS_RTC_TIMER_CNT_ADDR
#define GPS_AON_TOP_GPS_RTC_TIMER_CNT_TIMER_CNT_MASK           0x0000FFFF
#define GPS_AON_TOP_GPS_RTC_TIMER_CNT_TIMER_CNT_SHFT           0

#define GPS_AON_TOP_GPS_RTC_TIMER_CNT_READ_TIMER_CNT_READ_ADDR GPS_AON_TOP_GPS_RTC_TIMER_CNT_READ_ADDR
#define GPS_AON_TOP_GPS_RTC_TIMER_CNT_READ_TIMER_CNT_READ_MASK 0x0000FFFF
#define GPS_AON_TOP_GPS_RTC_TIMER_CNT_READ_TIMER_CNT_READ_SHFT 0

#define GPS_AON_TOP_GPS_HW_VERSION_HW_VERSION_ADDR             GPS_AON_TOP_GPS_HW_VERSION_ADDR
#define GPS_AON_TOP_GPS_HW_VERSION_HW_VERSION_MASK             0xFFFFFFFF
#define GPS_AON_TOP_GPS_HW_VERSION_HW_VERSION_SHFT             0

#define GPS_AON_TOP_GPS_SW_VERSION_SW_VERSION_ADDR             GPS_AON_TOP_GPS_SW_VERSION_ADDR
#define GPS_AON_TOP_GPS_SW_VERSION_SW_VERSION_MASK             0xFFFFFFFF
#define GPS_AON_TOP_GPS_SW_VERSION_SW_VERSION_SHFT             0

#define GPS_AON_TOP_GPS_CONFIG_ID_GPS_CONFIG_ID_ADDR           GPS_AON_TOP_GPS_CONFIG_ID_ADDR
#define GPS_AON_TOP_GPS_CONFIG_ID_GPS_CONFIG_ID_MASK           0xFFFFFFFF
#define GPS_AON_TOP_GPS_CONFIG_ID_GPS_CONFIG_ID_SHFT           0

#define GPS_AON_TOP_CMD_ICAP_STATUS_GPS_ICAP_STATUS_R2_ADDR    GPS_AON_TOP_CMD_ICAP_STATUS_ADDR
#define GPS_AON_TOP_CMD_ICAP_STATUS_GPS_ICAP_STATUS_R2_MASK    0x00000001
#define GPS_AON_TOP_CMD_ICAP_STATUS_GPS_ICAP_STATUS_R2_SHFT    0

#define GPS_AON_TOP_CMD_ADC_CLKDIV_ADCCLK_SYNC_CNT_ADDR        GPS_AON_TOP_CMD_ADC_CLKDIV_ADDR
#define GPS_AON_TOP_CMD_ADC_CLKDIV_ADCCLK_SYNC_CNT_MASK        0x03E00000
#define GPS_AON_TOP_CMD_ADC_CLKDIV_ADCCLK_SYNC_CNT_SHFT        21
#define GPS_AON_TOP_CMD_ADC_CLKDIV_ADC_CLKDIV_ADDR             GPS_AON_TOP_CMD_ADC_CLKDIV_ADDR
#define GPS_AON_TOP_CMD_ADC_CLKDIV_ADC_CLKDIV_MASK             0x001FFFFF
#define GPS_AON_TOP_CMD_ADC_CLKDIV_ADC_CLKDIV_SHFT             0

#define GPS_AON_TOP_GPS_SCLK_CTL_subms_en_ADDR                 GPS_AON_TOP_GPS_SCLK_CTL_ADDR
#define GPS_AON_TOP_GPS_SCLK_CTL_subms_en_MASK                 0x00000010
#define GPS_AON_TOP_GPS_SCLK_CTL_subms_en_SHFT                 4
#define GPS_AON_TOP_GPS_SCLK_CTL_sclk_sel_ADDR                 GPS_AON_TOP_GPS_SCLK_CTL_ADDR
#define GPS_AON_TOP_GPS_SCLK_CTL_sclk_sel_MASK                 0x00000003
#define GPS_AON_TOP_GPS_SCLK_CTL_sclk_sel_SHFT                 0

#define GPS_AON_TOP_GPS_DSP_SEL_rtc_ctrl_sel_ADDR              GPS_AON_TOP_GPS_DSP_SEL_ADDR
#define GPS_AON_TOP_GPS_DSP_SEL_rtc_ctrl_sel_MASK              0x00000002
#define GPS_AON_TOP_GPS_DSP_SEL_rtc_ctrl_sel_SHFT              1
#define GPS_AON_TOP_GPS_DSP_SEL_prim_dsp_ADDR                  GPS_AON_TOP_GPS_DSP_SEL_ADDR
#define GPS_AON_TOP_GPS_DSP_SEL_prim_dsp_MASK                  0x00000001
#define GPS_AON_TOP_GPS_DSP_SEL_prim_dsp_SHFT                  0

#define GPS_AON_TOP_GPS_SYNC_CTL_ext_snc_req_ADDR              GPS_AON_TOP_GPS_SYNC_CTL_ADDR
#define GPS_AON_TOP_GPS_SYNC_CTL_ext_snc_req_MASK              0x00000002
#define GPS_AON_TOP_GPS_SYNC_CTL_ext_snc_req_SHFT              1
#define GPS_AON_TOP_GPS_SYNC_CTL_tbench_sync_ADDR              GPS_AON_TOP_GPS_SYNC_CTL_ADDR
#define GPS_AON_TOP_GPS_SYNC_CTL_tbench_sync_MASK              0x00000001
#define GPS_AON_TOP_GPS_SYNC_CTL_tbench_sync_SHFT              0

#define GPS_AON_TOP_GPS_MTCMOS_CTL_gps_mtcmos_ctrl_ADDR        GPS_AON_TOP_GPS_MTCMOS_CTL_ADDR
#define GPS_AON_TOP_GPS_MTCMOS_CTL_gps_mtcmos_ctrl_MASK        0xFFFFFFFF
#define GPS_AON_TOP_GPS_MTCMOS_CTL_gps_mtcmos_ctrl_SHFT        0

#define GPS_AON_TOP_GPS_MTCMOS_STA_l5_mtcmos_force_sta_ADDR    GPS_AON_TOP_GPS_MTCMOS_STA_ADDR
#define GPS_AON_TOP_GPS_MTCMOS_STA_l5_mtcmos_force_sta_MASK    0x00000002
#define GPS_AON_TOP_GPS_MTCMOS_STA_l5_mtcmos_force_sta_SHFT    1
#define GPS_AON_TOP_GPS_MTCMOS_STA_l1_mtcmos_force_sta_ADDR    GPS_AON_TOP_GPS_MTCMOS_STA_ADDR
#define GPS_AON_TOP_GPS_MTCMOS_STA_l1_mtcmos_force_sta_MASK    0x00000001
#define GPS_AON_TOP_GPS_MTCMOS_STA_l1_mtcmos_force_sta_SHFT    0

#define GPS_AON_TOP_GPS_SLP_CTL_force_host_ctl_ADDR            GPS_AON_TOP_GPS_SLP_CTL_ADDR
#define GPS_AON_TOP_GPS_SLP_CTL_force_host_ctl_MASK            0x01000000
#define GPS_AON_TOP_GPS_SLP_CTL_force_host_ctl_SHFT            24
#define GPS_AON_TOP_GPS_SLP_CTL_host_l5_hw_on_manual_on_ADDR   GPS_AON_TOP_GPS_SLP_CTL_ADDR
#define GPS_AON_TOP_GPS_SLP_CTL_host_l5_hw_on_manual_on_MASK   0x00400000
#define GPS_AON_TOP_GPS_SLP_CTL_host_l5_hw_on_manual_on_SHFT   22
#define GPS_AON_TOP_GPS_SLP_CTL_host_l5_hw_on_manual_en_ADDR   GPS_AON_TOP_GPS_SLP_CTL_ADDR
#define GPS_AON_TOP_GPS_SLP_CTL_host_l5_hw_on_manual_en_MASK   0x00200000
#define GPS_AON_TOP_GPS_SLP_CTL_host_l5_hw_on_manual_en_SHFT   21
#define GPS_AON_TOP_GPS_SLP_CTL_host_l5_hw_on_ctl_en_ADDR      GPS_AON_TOP_GPS_SLP_CTL_ADDR
#define GPS_AON_TOP_GPS_SLP_CTL_host_l5_hw_on_ctl_en_MASK      0x00100000
#define GPS_AON_TOP_GPS_SLP_CTL_host_l5_hw_on_ctl_en_SHFT      20
#define GPS_AON_TOP_GPS_SLP_CTL_host_l1_hw_on_manual_on_ADDR   GPS_AON_TOP_GPS_SLP_CTL_ADDR
#define GPS_AON_TOP_GPS_SLP_CTL_host_l1_hw_on_manual_on_MASK   0x00040000
#define GPS_AON_TOP_GPS_SLP_CTL_host_l1_hw_on_manual_on_SHFT   18
#define GPS_AON_TOP_GPS_SLP_CTL_host_l1_hw_on_manual_en_ADDR   GPS_AON_TOP_GPS_SLP_CTL_ADDR
#define GPS_AON_TOP_GPS_SLP_CTL_host_l1_hw_on_manual_en_MASK   0x00020000
#define GPS_AON_TOP_GPS_SLP_CTL_host_l1_hw_on_manual_en_SHFT   17
#define GPS_AON_TOP_GPS_SLP_CTL_host_l1_hw_on_ctl_en_ADDR      GPS_AON_TOP_GPS_SLP_CTL_ADDR
#define GPS_AON_TOP_GPS_SLP_CTL_host_l1_hw_on_ctl_en_MASK      0x00010000
#define GPS_AON_TOP_GPS_SLP_CTL_host_l1_hw_on_ctl_en_SHFT      16
#define GPS_AON_TOP_GPS_SLP_CTL_l5_hw_on_manual_on_ADDR        GPS_AON_TOP_GPS_SLP_CTL_ADDR
#define GPS_AON_TOP_GPS_SLP_CTL_l5_hw_on_manual_on_MASK        0x00000040
#define GPS_AON_TOP_GPS_SLP_CTL_l5_hw_on_manual_on_SHFT        6
#define GPS_AON_TOP_GPS_SLP_CTL_l5_hw_on_manual_en_ADDR        GPS_AON_TOP_GPS_SLP_CTL_ADDR
#define GPS_AON_TOP_GPS_SLP_CTL_l5_hw_on_manual_en_MASK        0x00000020
#define GPS_AON_TOP_GPS_SLP_CTL_l5_hw_on_manual_en_SHFT        5
#define GPS_AON_TOP_GPS_SLP_CTL_l5_hw_on_ctl_en_ADDR           GPS_AON_TOP_GPS_SLP_CTL_ADDR
#define GPS_AON_TOP_GPS_SLP_CTL_l5_hw_on_ctl_en_MASK           0x00000010
#define GPS_AON_TOP_GPS_SLP_CTL_l5_hw_on_ctl_en_SHFT           4
#define GPS_AON_TOP_GPS_SLP_CTL_l1_hw_on_manual_on_ADDR        GPS_AON_TOP_GPS_SLP_CTL_ADDR
#define GPS_AON_TOP_GPS_SLP_CTL_l1_hw_on_manual_on_MASK        0x00000004
#define GPS_AON_TOP_GPS_SLP_CTL_l1_hw_on_manual_on_SHFT        2
#define GPS_AON_TOP_GPS_SLP_CTL_l1_hw_on_manual_en_ADDR        GPS_AON_TOP_GPS_SLP_CTL_ADDR
#define GPS_AON_TOP_GPS_SLP_CTL_l1_hw_on_manual_en_MASK        0x00000002
#define GPS_AON_TOP_GPS_SLP_CTL_l1_hw_on_manual_en_SHFT        1
#define GPS_AON_TOP_GPS_SLP_CTL_l1_hw_on_ctl_en_ADDR           GPS_AON_TOP_GPS_SLP_CTL_ADDR
#define GPS_AON_TOP_GPS_SLP_CTL_l1_hw_on_ctl_en_MASK           0x00000001
#define GPS_AON_TOP_GPS_SLP_CTL_l1_hw_on_ctl_en_SHFT           0

#define GPS_AON_TOP_AON_DUMMY_gps_aon_dummy_ADDR               GPS_AON_TOP_AON_DUMMY_ADDR
#define GPS_AON_TOP_AON_DUMMY_gps_aon_dummy_MASK               0xFFFFFFFF
#define GPS_AON_TOP_AON_DUMMY_gps_aon_dummy_SHFT               0

#define GPS_AON_TOP_RBIST_CLEAR_RBIST_WCLEAR_ADDR              GPS_AON_TOP_RBIST_CLEAR_ADDR
#define GPS_AON_TOP_RBIST_CLEAR_RBIST_WCLEAR_MASK              0x00000001
#define GPS_AON_TOP_RBIST_CLEAR_RBIST_WCLEAR_SHFT              0
#define GPS_AON_TOP_RBIST_CLEAR_RBIST_RCLEAR_ADDR              GPS_AON_TOP_RBIST_CLEAR_ADDR
#define GPS_AON_TOP_RBIST_CLEAR_RBIST_RCLEAR_MASK              0x00000100
#define GPS_AON_TOP_RBIST_CLEAR_RBIST_RCLEAR_SHFT              8

#define GPS_AON_TOP_RBIST_RESET_RBIST_APB_W_N_ADDR             GPS_AON_TOP_RBIST_RESET_ADDR
#define GPS_AON_TOP_RBIST_RESET_RBIST_APB_W_N_MASK             0x00000001
#define GPS_AON_TOP_RBIST_RESET_RBIST_APB_W_N_SHFT             0
#define GPS_AON_TOP_RBIST_RESET_RBIST_APB_R_N_ADDR             GPS_AON_TOP_RBIST_RESET_ADDR
#define GPS_AON_TOP_RBIST_RESET_RBIST_APB_R_N_MASK             0x00000100
#define GPS_AON_TOP_RBIST_RESET_RBIST_APB_R_N_SHFT             8

#define GPS_AON_TOP_RBIST_LENGTH_RBIST_LENGTH_ADDR             GPS_AON_TOP_RBIST_LENGTH_ADDR
#define GPS_AON_TOP_RBIST_LENGTH_RBIST_LENGTH_MASK             0x00007FFF
#define GPS_AON_TOP_RBIST_LENGTH_RBIST_LENGTH_SHFT             0

#define GPS_AON_TOP_RBIST_OFFSET_RBIST_SYSRAM_START_ADDR_ADDR  GPS_AON_TOP_RBIST_OFFSET_ADDR
#define GPS_AON_TOP_RBIST_OFFSET_RBIST_SYSRAM_START_ADDR_MASK  0x00007FFF
#define GPS_AON_TOP_RBIST_OFFSET_RBIST_SYSRAM_START_ADDR_SHFT  0

#define GPS_AON_TOP_RBIST_CONTROL_RBIST_START_ADDR             GPS_AON_TOP_RBIST_CONTROL_ADDR
#define GPS_AON_TOP_RBIST_CONTROL_RBIST_START_MASK             0x00000001
#define GPS_AON_TOP_RBIST_CONTROL_RBIST_START_SHFT             0
#define GPS_AON_TOP_RBIST_CONTROL_RBIST_STOP_ADDR              GPS_AON_TOP_RBIST_CONTROL_ADDR
#define GPS_AON_TOP_RBIST_CONTROL_RBIST_STOP_MASK              0x00000100
#define GPS_AON_TOP_RBIST_CONTROL_RBIST_STOP_SHFT              8

#define GPS_AON_TOP_RBIST_DEBUG_OPTION_RBIST_DEBUG_EN_ADDR     GPS_AON_TOP_RBIST_DEBUG_OPTION_ADDR
#define GPS_AON_TOP_RBIST_DEBUG_OPTION_RBIST_DEBUG_EN_MASK     0x00000001
#define GPS_AON_TOP_RBIST_DEBUG_OPTION_RBIST_DEBUG_EN_SHFT     0
#define GPS_AON_TOP_RBIST_DEBUG_OPTION_RBIST_DEBUG_SEL_ADDR    GPS_AON_TOP_RBIST_DEBUG_OPTION_ADDR
#define GPS_AON_TOP_RBIST_DEBUG_OPTION_RBIST_DEBUG_SEL_MASK    0x00000F00
#define GPS_AON_TOP_RBIST_DEBUG_OPTION_RBIST_DEBUG_SEL_SHFT    8

#define GPS_AON_TOP_RBIST_FIFO_THRESHOLD_RBIST_W_THRESHOLD_ADDR GPS_AON_TOP_RBIST_FIFO_THRESHOLD_ADDR
#define GPS_AON_TOP_RBIST_FIFO_THRESHOLD_RBIST_W_THRESHOLD_MASK 0x00000F00
#define GPS_AON_TOP_RBIST_FIFO_THRESHOLD_RBIST_W_THRESHOLD_SHFT 8
#define GPS_AON_TOP_RBIST_FIFO_THRESHOLD_RBIST_R_THRESHOLD_ADDR GPS_AON_TOP_RBIST_FIFO_THRESHOLD_ADDR
#define GPS_AON_TOP_RBIST_FIFO_THRESHOLD_RBIST_R_THRESHOLD_MASK 0x0000000F
#define GPS_AON_TOP_RBIST_FIFO_THRESHOLD_RBIST_R_THRESHOLD_SHFT 0

#define GPS_AON_TOP_RBIST_FIFO_READ_0_RBIST_DONE_ADDR          GPS_AON_TOP_RBIST_FIFO_READ_0_ADDR
#define GPS_AON_TOP_RBIST_FIFO_READ_0_RBIST_DONE_MASK          0x00000001
#define GPS_AON_TOP_RBIST_FIFO_READ_0_RBIST_DONE_SHFT          0
#define GPS_AON_TOP_RBIST_FIFO_READ_0_RBIST_EMPTY_ADDR         GPS_AON_TOP_RBIST_FIFO_READ_0_ADDR
#define GPS_AON_TOP_RBIST_FIFO_READ_0_RBIST_EMPTY_MASK         0x00010000
#define GPS_AON_TOP_RBIST_FIFO_READ_0_RBIST_EMPTY_SHFT         16
#define GPS_AON_TOP_RBIST_FIFO_READ_0_RBIST_FULL_ADDR          GPS_AON_TOP_RBIST_FIFO_READ_0_ADDR
#define GPS_AON_TOP_RBIST_FIFO_READ_0_RBIST_FULL_MASK          0x01000000
#define GPS_AON_TOP_RBIST_FIFO_READ_0_RBIST_FULL_SHFT          24

#define GPS_AON_TOP_RBIST_FIFO_READ_1_RBIST_WFIFO_CNT_ADDR     GPS_AON_TOP_RBIST_FIFO_READ_1_ADDR
#define GPS_AON_TOP_RBIST_FIFO_READ_1_RBIST_WFIFO_CNT_MASK     0x0000000F
#define GPS_AON_TOP_RBIST_FIFO_READ_1_RBIST_WFIFO_CNT_SHFT     0
#define GPS_AON_TOP_RBIST_FIFO_READ_1_RBIST_RFIFO_CNT_ADDR     GPS_AON_TOP_RBIST_FIFO_READ_1_ADDR
#define GPS_AON_TOP_RBIST_FIFO_READ_1_RBIST_RFIFO_CNT_MASK     0x00000F00
#define GPS_AON_TOP_RBIST_FIFO_READ_1_RBIST_RFIFO_CNT_SHFT     8

#define GPS_AON_TOP_RBIST_FIFO_READ_2_RBIST_R_READY_ADDR       GPS_AON_TOP_RBIST_FIFO_READ_2_ADDR
#define GPS_AON_TOP_RBIST_FIFO_READ_2_RBIST_R_READY_MASK       0x00000001
#define GPS_AON_TOP_RBIST_FIFO_READ_2_RBIST_R_READY_SHFT       0
#define GPS_AON_TOP_RBIST_FIFO_READ_2_RBIST_W_READY_ADDR       GPS_AON_TOP_RBIST_FIFO_READ_2_ADDR
#define GPS_AON_TOP_RBIST_FIFO_READ_2_RBIST_W_READY_MASK       0x00000100
#define GPS_AON_TOP_RBIST_FIFO_READ_2_RBIST_W_READY_SHFT       8

#define GPS_AON_TOP_RBIST_DEBUG_RESULT_RBIST_DEBUG_BUS_ADDR    GPS_AON_TOP_RBIST_DEBUG_RESULT_ADDR
#define GPS_AON_TOP_RBIST_DEBUG_RESULT_RBIST_DEBUG_BUS_MASK    0x000000FF
#define GPS_AON_TOP_RBIST_DEBUG_RESULT_RBIST_DEBUG_BUS_SHFT    0

#endif /* __GPS_AON_TOP_REGS_H__ */

