/*
 * Copyright (C) 2019 MediaTek Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See http://www.gnu.org/licenses/gpl-2.0.html for more details.
 */
#ifndef __GPS_L5_SYS_ADRDEC_REGS_H__
#define __GPS_L5_SYS_ADRDEC_REGS_H__

#define GPS_L5_SYS_ADRDEC_BASE                                 0x80080400

#define GPS_L5_SYS_ADRDEC_SYSDMY_ADDR                          (GPS_L5_SYS_ADRDEC_BASE + 0x0050)
#define GPS_L5_SYS_ADRDEC_SYSVAR0_ADDR                         (GPS_L5_SYS_ADRDEC_BASE + 0x0054)
#define GPS_L5_SYS_ADRDEC_SYSVAR1_ADDR                         (GPS_L5_SYS_ADRDEC_BASE + 0x0058)
#define GPS_L5_SYS_ADRDEC_SYSVAR2_ADDR                         (GPS_L5_SYS_ADRDEC_BASE + 0x005C)
#define GPS_L5_SYS_ADRDEC_SYSVAR3_ADDR                         (GPS_L5_SYS_ADRDEC_BASE + 0x0060)
#define GPS_L5_SYS_ADRDEC_SYSVAR4_ADDR                         (GPS_L5_SYS_ADRDEC_BASE + 0x0064)
#define GPS_L5_SYS_ADRDEC_SYSVAR5_ADDR                         (GPS_L5_SYS_ADRDEC_BASE + 0x0068)
#define GPS_L5_SYS_ADRDEC_SYSVAR6_ADDR                         (GPS_L5_SYS_ADRDEC_BASE + 0x006C)
#define GPS_L5_SYS_ADRDEC_CLKS_ADDR                            (GPS_L5_SYS_ADRDEC_BASE + 0x0080)
#define GPS_L5_SYS_ADRDEC_PDN_ADDR                             (GPS_L5_SYS_ADRDEC_BASE + 0x0084)
#define GPS_L5_SYS_ADRDEC_SYS_RST_ADDR                         (GPS_L5_SYS_ADRDEC_BASE + 0x0088)
#define GPS_L5_SYS_ADRDEC_SYS_SET_ADDR                         (GPS_L5_SYS_ADRDEC_BASE + 0x008C)
#define GPS_L5_SYS_ADRDEC_WDOG_CFG_ADDR                        (GPS_L5_SYS_ADRDEC_BASE + 0x00A0)
#define GPS_L5_SYS_ADRDEC_WDOG_LEN_ADDR                        (GPS_L5_SYS_ADRDEC_BASE + 0x00A4)
#define GPS_L5_SYS_ADRDEC_STRAP_ADDR                           (GPS_L5_SYS_ADRDEC_BASE + 0x00A8)
#define GPS_L5_SYS_ADRDEC_PAGE_ADDR                            (GPS_L5_SYS_ADRDEC_BASE + 0x00B0)
#define GPS_L5_SYS_ADRDEC_GPS_PWR_STAT_ADDR                    (GPS_L5_SYS_ADRDEC_BASE + 0x00B4)
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_ADDR                     (GPS_L5_SYS_ADRDEC_BASE + 0x00C0)
#define GPS_L5_SYS_ADRDEC_BIST_BYTESEL_ADDR                    (GPS_L5_SYS_ADRDEC_BASE + 0x00C4)
#define GPS_L5_SYS_ADRDEC_BIST_DONE_ADDR                       (GPS_L5_SYS_ADRDEC_BASE + 0x00C8)
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_ADDR                     (GPS_L5_SYS_ADRDEC_BASE + 0x00CC)
#define GPS_L5_SYS_ADRDEC_REPAIR_MONSEL_ADDR                   (GPS_L5_SYS_ADRDEC_BASE + 0x00D0)
#define GPS_L5_SYS_ADRDEC_REPAIR_MON_ADDR                      (GPS_L5_SYS_ADRDEC_BASE + 0x00D4)
#define GPS_L5_SYS_ADRDEC_BIST_PAT_ADDR                        (GPS_L5_SYS_ADRDEC_BASE + 0x00D8)
#define GPS_L5_SYS_ADRDEC_DELSEL0_L_ADDR                       (GPS_L5_SYS_ADRDEC_BASE + 0x00DC)
#define GPS_L5_SYS_ADRDEC_DELSEL1_L_ADDR                       (GPS_L5_SYS_ADRDEC_BASE + 0x00E0)
#define GPS_L5_SYS_ADRDEC_DELSEL2_L_ADDR                       (GPS_L5_SYS_ADRDEC_BASE + 0x00E4)
#define GPS_L5_SYS_ADRDEC_DELSEL3_L_ADDR                       (GPS_L5_SYS_ADRDEC_BASE + 0x00E8)
#define GPS_L5_SYS_ADRDEC_DELSEL4_L_ADDR                       (GPS_L5_SYS_ADRDEC_BASE + 0x00EC)
#define GPS_L5_SYS_ADRDEC_DELSEL5_L_ADDR                       (GPS_L5_SYS_ADRDEC_BASE + 0x00F0)
#define GPS_L5_SYS_ADRDEC_DELSEL6_L_ADDR                       (GPS_L5_SYS_ADRDEC_BASE + 0x00F4)
#define GPS_L5_SYS_ADRDEC_DELSEL7_L_ADDR                       (GPS_L5_SYS_ADRDEC_BASE + 0x00F8)
#define GPS_L5_SYS_ADRDEC_LOAD_FUSE_ADDR                       (GPS_L5_SYS_ADRDEC_BASE + 0x00FC)
#define GPS_L5_SYS_ADRDEC_ECLK_CTL_ADDR                        (GPS_L5_SYS_ADRDEC_BASE + 0x0100)
#define GPS_L5_SYS_ADRDEC_ECLKL_ADDR                           (GPS_L5_SYS_ADRDEC_BASE + 0x0104)
#define GPS_L5_SYS_ADRDEC_ECLKH_ADDR                           (GPS_L5_SYS_ADRDEC_BASE + 0x0108)
#define GPS_L5_SYS_ADRDEC_ECLKSTAL_ADDR                        (GPS_L5_SYS_ADRDEC_BASE + 0x010C)
#define GPS_L5_SYS_ADRDEC_ECLKSTAH_ADDR                        (GPS_L5_SYS_ADRDEC_BASE + 0x0110)
#define GPS_L5_SYS_ADRDEC_DELSEL8_L_ADDR                       (GPS_L5_SYS_ADRDEC_BASE + 0x0114)
#define GPS_L5_SYS_ADRDEC_DELSEL9_L_ADDR                       (GPS_L5_SYS_ADRDEC_BASE + 0x0118)
#define GPS_L5_SYS_ADRDEC_DELSEL10_L_ADDR                      (GPS_L5_SYS_ADRDEC_BASE + 0x011C)
#define GPS_L5_SYS_ADRDEC_DELSEL11_L_ADDR                      (GPS_L5_SYS_ADRDEC_BASE + 0x0124)
#define GPS_L5_SYS_ADRDEC_DELSEL12_L_ADDR                      (GPS_L5_SYS_ADRDEC_BASE + 0x0128)
#define GPS_L5_SYS_ADRDEC_DELSEL13_L_ADDR                      (GPS_L5_SYS_ADRDEC_BASE + 0x012C)
#define GPS_L5_SYS_ADRDEC_DELSEL14_L_ADDR                      (GPS_L5_SYS_ADRDEC_BASE + 0x0130)
#define GPS_L5_SYS_ADRDEC_DELSEL15_L_ADDR                      (GPS_L5_SYS_ADRDEC_BASE + 0x0134)
#define GPS_L5_SYS_ADRDEC_DELSEL16_L_ADDR                      (GPS_L5_SYS_ADRDEC_BASE + 0x0138)
#define GPS_L5_SYS_ADRDEC_DELSEL17_L_ADDR                      (GPS_L5_SYS_ADRDEC_BASE + 0x013C)
#define GPS_L5_SYS_ADRDEC_MONCFG_ADDR                          (GPS_L5_SYS_ADRDEC_BASE + 0x0140)
#define GPS_L5_SYS_ADRDEC_MONOUT_ADDR                          (GPS_L5_SYS_ADRDEC_BASE + 0x0144)
#define GPS_L5_SYS_ADRDEC_MONIN_ADDR                           (GPS_L5_SYS_ADRDEC_BASE + 0x0148)
#define GPS_L5_SYS_ADRDEC_GRPSEL_ADDR                          (GPS_L5_SYS_ADRDEC_BASE + 0x0168)
#define GPS_L5_SYS_ADRDEC_FLAGSEL_ADDR                         (GPS_L5_SYS_ADRDEC_BASE + 0x016C)
#define GPS_L5_SYS_ADRDEC_BIST_RESETB_ADDR                     (GPS_L5_SYS_ADRDEC_BASE + 0x0180)
#define GPS_L5_SYS_ADRDEC_BIST_RPRSTB_ADDR                     (GPS_L5_SYS_ADRDEC_BASE + 0x0188)
#define GPS_L5_SYS_ADRDEC_BIST_RP_FAIL_ADDR                    (GPS_L5_SYS_ADRDEC_BASE + 0x018C)
#define GPS_L5_SYS_ADRDEC_BIST_RP_OK_ADDR                      (GPS_L5_SYS_ADRDEC_BASE + 0x0190)
#define GPS_L5_SYS_ADRDEC_REPAIR_ADDR_0_ADDR                   (GPS_L5_SYS_ADRDEC_BASE + 0x0194)
#define GPS_L5_SYS_ADRDEC_REPAIR_ADDR_1_ADDR                   (GPS_L5_SYS_ADRDEC_BASE + 0x0198)
#define GPS_L5_SYS_ADRDEC_REPAIR_ADDR_2_ADDR                   (GPS_L5_SYS_ADRDEC_BASE + 0x019C)
#define GPS_L5_SYS_ADRDEC_REPAIR_FUSE_0_ADDR                   (GPS_L5_SYS_ADRDEC_BASE + 0x01A0)
#define GPS_L5_SYS_ADRDEC_REPAIR_FUSE_1_ADDR                   (GPS_L5_SYS_ADRDEC_BASE + 0x01A4)
#define GPS_L5_SYS_ADRDEC_REPAIR_FUSE_2_ADDR                   (GPS_L5_SYS_ADRDEC_BASE + 0x01A8)
#define GPS_L5_SYS_ADRDEC_REPAIR_FUSE_3_ADDR                   (GPS_L5_SYS_ADRDEC_BASE + 0x01AC)
#define GPS_L5_SYS_ADRDEC_REPAIR_FUSE_4_ADDR                   (GPS_L5_SYS_ADRDEC_BASE + 0x01B0)
#define GPS_L5_SYS_ADRDEC_REPAIR_FUSE_5_ADDR                   (GPS_L5_SYS_ADRDEC_BASE + 0x01B4)
#define GPS_L5_SYS_ADRDEC_MBIST_CROM_FAIL_BUS_ADDR             (GPS_L5_SYS_ADRDEC_BASE + 0x01CC)
#define GPS_L5_SYS_ADRDEC_MBIST_GRAM_FAIL_BUS_ADDR             (GPS_L5_SYS_ADRDEC_BASE + 0x01D0)
#define GPS_L5_SYS_ADRDEC_MBIST_GRAM_RP_FAIL_BUS_ADDR          (GPS_L5_SYS_ADRDEC_BASE + 0x01D4)
#define GPS_L5_SYS_ADRDEC_MBIST_GRAM_RP_OKBUS_ADDR             (GPS_L5_SYS_ADRDEC_BASE + 0x01D8)
#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_FAIL_BUS_0_ADDR           (GPS_L5_SYS_ADRDEC_BASE + 0x01DC)
#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_FAIL_BUS_1_ADDR           (GPS_L5_SYS_ADRDEC_BASE + 0x01E0)
#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_FAIL_BUS_2_ADDR           (GPS_L5_SYS_ADRDEC_BASE + 0x01E4)
#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_RP_FAIL_BUS_0_ADDR        (GPS_L5_SYS_ADRDEC_BASE + 0x01E8)
#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_RP_FAIL_BUS_1_ADDR        (GPS_L5_SYS_ADRDEC_BASE + 0x01EC)
#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_RP_FAIL_BUS_2_ADDR        (GPS_L5_SYS_ADRDEC_BASE + 0x01F0)
#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_RP_OK_BUS_0_ADDR          (GPS_L5_SYS_ADRDEC_BASE + 0x01F4)
#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_RP_OK_BUS_1_ADDR          (GPS_L5_SYS_ADRDEC_BASE + 0x01F8)
#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_RP_OK_BUS_2_ADDR          (GPS_L5_SYS_ADRDEC_BASE + 0x01FC)
#define GPS_L5_SYS_ADRDEC_MBIST_PRAM_FAIL_BUS_ADDR             (GPS_L5_SYS_ADRDEC_BASE + 0x0200)
#define GPS_L5_SYS_ADRDEC_MBIST_PRAM_RP_FAIL_BUS_ADDR          (GPS_L5_SYS_ADRDEC_BASE + 0x0204)
#define GPS_L5_SYS_ADRDEC_MBIST_PRAM_RP_OKBUS_ADDR             (GPS_L5_SYS_ADRDEC_BASE + 0x0208)
#define GPS_L5_SYS_ADRDEC_MBIST_XRAM_FAIL_BUS_ADDR             (GPS_L5_SYS_ADRDEC_BASE + 0x020C)
#define GPS_L5_SYS_ADRDEC_MBIST_XRAM_RP_FAIL_BUS_ADDR          (GPS_L5_SYS_ADRDEC_BASE + 0x0210)
#define GPS_L5_SYS_ADRDEC_MBIST_XRAM_RP_OKBUS_ADDR             (GPS_L5_SYS_ADRDEC_BASE + 0x0214)
#define GPS_L5_SYS_ADRDEC_MBIST_YRAM_FAIL_BUS_ADDR             (GPS_L5_SYS_ADRDEC_BASE + 0x0218)
#define GPS_L5_SYS_ADRDEC_MBIST_YRAM_RP_FAIL_BUS_ADDR          (GPS_L5_SYS_ADRDEC_BASE + 0x021C)
#define GPS_L5_SYS_ADRDEC_MBIST_YRAM_RP_OKBUS_ADDR             (GPS_L5_SYS_ADRDEC_BASE + 0x0220)
#define GPS_L5_SYS_ADRDEC_MBIST_URAM_FAIL_BUS_ADDR             (GPS_L5_SYS_ADRDEC_BASE + 0x0224)
#define GPS_L5_SYS_ADRDEC_MBIST_URAM_RP_FAIL_BUS_ADDR          (GPS_L5_SYS_ADRDEC_BASE + 0x0228)
#define GPS_L5_SYS_ADRDEC_MBIST_URAM_RP_OKBUS_ADDR             (GPS_L5_SYS_ADRDEC_BASE + 0x022C)
#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_FAIL_BUS_0_ADDR           (GPS_L5_SYS_ADRDEC_BASE + 0x0230)
#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_FAIL_BUS_1_ADDR           (GPS_L5_SYS_ADRDEC_BASE + 0x0234)
#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_FAIL_BUS_2_ADDR           (GPS_L5_SYS_ADRDEC_BASE + 0x0238)
#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_RP_FAIL_BUS_0_ADDR        (GPS_L5_SYS_ADRDEC_BASE + 0x023C)
#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_RP_FAIL_BUS_1_ADDR        (GPS_L5_SYS_ADRDEC_BASE + 0x0240)
#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_RP_FAIL_BUS_2_ADDR        (GPS_L5_SYS_ADRDEC_BASE + 0x0244)
#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_RP_OK_BUS_0_ADDR          (GPS_L5_SYS_ADRDEC_BASE + 0x0248)
#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_RP_OK_BUS_1_ADDR          (GPS_L5_SYS_ADRDEC_BASE + 0x024C)
#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_RP_OK_BUS_2_ADDR          (GPS_L5_SYS_ADRDEC_BASE + 0x0250)
#define GPS_L5_SYS_ADRDEC_MEM_MISC_ADDR                        (GPS_L5_SYS_ADRDEC_BASE + 0x0254)
#define GPS_L5_SYS_ADRDEC_TMBIST_FUSE_SEL_ADDR                 (GPS_L5_SYS_ADRDEC_BASE + 0x0258)
#define GPS_L5_SYS_ADRDEC_BIST_CROM_DOTEST_ADDR                (GPS_L5_SYS_ADRDEC_BASE + 0x025C)
#define GPS_L5_SYS_ADRDEC_BIST_GRAM_DOTEST_ADDR                (GPS_L5_SYS_ADRDEC_BASE + 0x0260)
#define GPS_L5_SYS_ADRDEC_BIST_TRAM_DOTEST_ADDR                (GPS_L5_SYS_ADRDEC_BASE + 0x0264)
#define GPS_L5_SYS_ADRDEC_BIST_MRAM_DOTEST_ADDR                (GPS_L5_SYS_ADRDEC_BASE + 0x0268)
#define GPS_L5_SYS_ADRDEC_MBIST_SHARE_FAIL_BUS_ADDR            (GPS_L5_SYS_ADRDEC_BASE + 0x026C)
#define GPS_L5_SYS_ADRDEC_MBIST_SHARE_RP_FAIL_BUS_ADDR         (GPS_L5_SYS_ADRDEC_BASE + 0x0270)
#define GPS_L5_SYS_ADRDEC_MBIST_SHARE_RP_OKBUS_ADDR            (GPS_L5_SYS_ADRDEC_BASE + 0x0274)
#define GPS_L5_SYS_ADRDEC_SHARE_MISC_ADDR                      (GPS_L5_SYS_ADRDEC_BASE + 0x0278)
#define GPS_L5_SYS_ADRDEC_ANACTL_0_ADDR                        (GPS_L5_SYS_ADRDEC_BASE + 0x0280)
#define GPS_L5_SYS_ADRDEC_ANACTL_1_ADDR                        (GPS_L5_SYS_ADRDEC_BASE + 0x0284)
#define GPS_L5_SYS_ADRDEC_RFCTL_0_ADDR                         (GPS_L5_SYS_ADRDEC_BASE + 0x02C0)
#define GPS_L5_SYS_ADRDEC_RFCTL_1_ADDR                         (GPS_L5_SYS_ADRDEC_BASE + 0x02C4)
#define GPS_L5_SYS_ADRDEC_RFCTL_2_ADDR                         (GPS_L5_SYS_ADRDEC_BASE + 0x02C8)
#define GPS_L5_SYS_ADRDEC_RFCTL_3_ADDR                         (GPS_L5_SYS_ADRDEC_BASE + 0x02CC)
#define GPS_L5_SYS_ADRDEC_MBIST_SLP0_ADDR                      (GPS_L5_SYS_ADRDEC_BASE + 0x0300)
#define GPS_L5_SYS_ADRDEC_MBIST_SLP1_ADDR                      (GPS_L5_SYS_ADRDEC_BASE + 0x0304)
#define GPS_L5_SYS_ADRDEC_MBIST_SLP2_ADDR                      (GPS_L5_SYS_ADRDEC_BASE + 0x0308)
#define GPS_L5_SYS_ADRDEC_MBIST_SLP3_ADDR                      (GPS_L5_SYS_ADRDEC_BASE + 0x030C)
#define GPS_L5_SYS_ADRDEC_PROM_SIGNATURE_0_ADDR                (GPS_L5_SYS_ADRDEC_BASE + 0x0340)
#define GPS_L5_SYS_ADRDEC_PROM_SIGNATURE_1_ADDR                (GPS_L5_SYS_ADRDEC_BASE + 0x0344)
#define GPS_L5_SYS_ADRDEC_CROM_SIGNATURE_L_0_ADDR              (GPS_L5_SYS_ADRDEC_BASE + 0x0348)
#define GPS_L5_SYS_ADRDEC_CROM_SIGNATURE_L_1_ADDR              (GPS_L5_SYS_ADRDEC_BASE + 0x034C)
#define GPS_L5_SYS_ADRDEC_CROM_SIGNATURE_H_0_ADDR              (GPS_L5_SYS_ADRDEC_BASE + 0x0350)
#define GPS_L5_SYS_ADRDEC_CROM_SIGNATURE_H_1_ADDR              (GPS_L5_SYS_ADRDEC_BASE + 0x0354)
#define GPS_L5_SYS_ADRDEC_MBIST_DIAG_SEL_ADDR                  (GPS_L5_SYS_ADRDEC_BASE + 0x0358)
#define GPS_L5_SYS_ADRDEC_PROM_SIGNATURE_2_ADDR                (GPS_L5_SYS_ADRDEC_BASE + 0x035C)
#define GPS_L5_SYS_ADRDEC_PROM_SIGNATURE_3_ADDR                (GPS_L5_SYS_ADRDEC_BASE + 0x0360)
#define GPS_L5_SYS_ADRDEC_DELSEL0_H_ADDR                       (GPS_L5_SYS_ADRDEC_BASE + 0x0380)
#define GPS_L5_SYS_ADRDEC_DELSEL1_H_ADDR                       (GPS_L5_SYS_ADRDEC_BASE + 0x0384)
#define GPS_L5_SYS_ADRDEC_DELSEL2_H_ADDR                       (GPS_L5_SYS_ADRDEC_BASE + 0x0388)
#define GPS_L5_SYS_ADRDEC_DELSEL3_H_ADDR                       (GPS_L5_SYS_ADRDEC_BASE + 0x038C)
#define GPS_L5_SYS_ADRDEC_DELSEL4_H_ADDR                       (GPS_L5_SYS_ADRDEC_BASE + 0x0390)
#define GPS_L5_SYS_ADRDEC_DELSEL5_H_ADDR                       (GPS_L5_SYS_ADRDEC_BASE + 0x0394)
#define GPS_L5_SYS_ADRDEC_DELSEL6_H_ADDR                       (GPS_L5_SYS_ADRDEC_BASE + 0x0398)
#define GPS_L5_SYS_ADRDEC_DELSEL7_H_ADDR                       (GPS_L5_SYS_ADRDEC_BASE + 0x039C)
#define GPS_L5_SYS_ADRDEC_DELSEL8_H_ADDR                       (GPS_L5_SYS_ADRDEC_BASE + 0x03A0)
#define GPS_L5_SYS_ADRDEC_DELSEL9_H_ADDR                       (GPS_L5_SYS_ADRDEC_BASE + 0x03A4)
#define GPS_L5_SYS_ADRDEC_DELSEL10_H_ADDR                      (GPS_L5_SYS_ADRDEC_BASE + 0x03A8)
#define GPS_L5_SYS_ADRDEC_DELSEL11_H_ADDR                      (GPS_L5_SYS_ADRDEC_BASE + 0x03AC)
#define GPS_L5_SYS_ADRDEC_DELSEL12_H_ADDR                      (GPS_L5_SYS_ADRDEC_BASE + 0x03B0)
#define GPS_L5_SYS_ADRDEC_DELSEL13_H_ADDR                      (GPS_L5_SYS_ADRDEC_BASE + 0x03B4)
#define GPS_L5_SYS_ADRDEC_DELSEL14_H_ADDR                      (GPS_L5_SYS_ADRDEC_BASE + 0x03B8)
#define GPS_L5_SYS_ADRDEC_DELSEL15_H_ADDR                      (GPS_L5_SYS_ADRDEC_BASE + 0x03BC)
#define GPS_L5_SYS_ADRDEC_DELSEL16_H_ADDR                      (GPS_L5_SYS_ADRDEC_BASE + 0x03C0)
#define GPS_L5_SYS_ADRDEC_DELSEL17_H_ADDR                      (GPS_L5_SYS_ADRDEC_BASE + 0x03C4)
#define GPS_L5_SYS_ADRDEC_DELSEL18_L_ADDR                      (GPS_L5_SYS_ADRDEC_BASE + 0x03C8)
#define GPS_L5_SYS_ADRDEC_DELSEL18_H_ADDR                      (GPS_L5_SYS_ADRDEC_BASE + 0x03CC)


#define GPS_L5_SYS_ADRDEC_SYSDMY_REG_DMY_ADDR                  GPS_L5_SYS_ADRDEC_SYSDMY_ADDR
#define GPS_L5_SYS_ADRDEC_SYSDMY_REG_DMY_MASK                  0x0000FFFF
#define GPS_L5_SYS_ADRDEC_SYSDMY_REG_DMY_SHFT                  0

#define GPS_L5_SYS_ADRDEC_SYSVAR0_REG_VAR0_ADDR                GPS_L5_SYS_ADRDEC_SYSVAR0_ADDR
#define GPS_L5_SYS_ADRDEC_SYSVAR0_REG_VAR0_MASK                0x0000FFFF
#define GPS_L5_SYS_ADRDEC_SYSVAR0_REG_VAR0_SHFT                0

#define GPS_L5_SYS_ADRDEC_SYSVAR1_REG_VAR1_ADDR                GPS_L5_SYS_ADRDEC_SYSVAR1_ADDR
#define GPS_L5_SYS_ADRDEC_SYSVAR1_REG_VAR1_MASK                0x0000FFFF
#define GPS_L5_SYS_ADRDEC_SYSVAR1_REG_VAR1_SHFT                0

#define GPS_L5_SYS_ADRDEC_SYSVAR2_REG_VAR2_ADDR                GPS_L5_SYS_ADRDEC_SYSVAR2_ADDR
#define GPS_L5_SYS_ADRDEC_SYSVAR2_REG_VAR2_MASK                0x0000FFFF
#define GPS_L5_SYS_ADRDEC_SYSVAR2_REG_VAR2_SHFT                0

#define GPS_L5_SYS_ADRDEC_SYSVAR3_REG_VAR3_ADDR                GPS_L5_SYS_ADRDEC_SYSVAR3_ADDR
#define GPS_L5_SYS_ADRDEC_SYSVAR3_REG_VAR3_MASK                0x0000FFFF
#define GPS_L5_SYS_ADRDEC_SYSVAR3_REG_VAR3_SHFT                0

#define GPS_L5_SYS_ADRDEC_SYSVAR4_REG_VAR4_ADDR                GPS_L5_SYS_ADRDEC_SYSVAR4_ADDR
#define GPS_L5_SYS_ADRDEC_SYSVAR4_REG_VAR4_MASK                0x0000FFFF
#define GPS_L5_SYS_ADRDEC_SYSVAR4_REG_VAR4_SHFT                0

#define GPS_L5_SYS_ADRDEC_SYSVAR5_REG_VAR5_ADDR                GPS_L5_SYS_ADRDEC_SYSVAR5_ADDR
#define GPS_L5_SYS_ADRDEC_SYSVAR5_REG_VAR5_MASK                0x0000FFFF
#define GPS_L5_SYS_ADRDEC_SYSVAR5_REG_VAR5_SHFT                0

#define GPS_L5_SYS_ADRDEC_SYSVAR6_REG_VAR6_ADDR                GPS_L5_SYS_ADRDEC_SYSVAR6_ADDR
#define GPS_L5_SYS_ADRDEC_SYSVAR6_REG_VAR6_MASK                0x0000FFFF
#define GPS_L5_SYS_ADRDEC_SYSVAR6_REG_VAR6_SHFT                0

#define GPS_L5_SYS_ADRDEC_CLKS_DCLK_DIV_SEL_ADDR               GPS_L5_SYS_ADRDEC_CLKS_ADDR
#define GPS_L5_SYS_ADRDEC_CLKS_DCLK_DIV_SEL_MASK               0x00000800
#define GPS_L5_SYS_ADRDEC_CLKS_DCLK_DIV_SEL_SHFT               11
#define GPS_L5_SYS_ADRDEC_CLKS_DCLK_IS_PLLCK_ADDR              GPS_L5_SYS_ADRDEC_CLKS_ADDR
#define GPS_L5_SYS_ADRDEC_CLKS_DCLK_IS_PLLCK_MASK              0x00000400
#define GPS_L5_SYS_ADRDEC_CLKS_DCLK_IS_PLLCK_SHFT              10
#define GPS_L5_SYS_ADRDEC_CLKS_PCLK_SEL_ADDR                   GPS_L5_SYS_ADRDEC_CLKS_ADDR
#define GPS_L5_SYS_ADRDEC_CLKS_PCLK_SEL_MASK                   0x00000300
#define GPS_L5_SYS_ADRDEC_CLKS_PCLK_SEL_SHFT                   8

#define GPS_L5_SYS_ADRDEC_PDN_URAM_MEM_PDN_ADDR                GPS_L5_SYS_ADRDEC_PDN_ADDR
#define GPS_L5_SYS_ADRDEC_PDN_URAM_MEM_PDN_MASK                0x00004000
#define GPS_L5_SYS_ADRDEC_PDN_URAM_MEM_PDN_SHFT                14
#define GPS_L5_SYS_ADRDEC_PDN_GPS_MEM_PDN_ADDR                 GPS_L5_SYS_ADRDEC_PDN_ADDR
#define GPS_L5_SYS_ADRDEC_PDN_GPS_MEM_PDN_MASK                 0x00002000
#define GPS_L5_SYS_ADRDEC_PDN_GPS_MEM_PDN_SHFT                 13
#define GPS_L5_SYS_ADRDEC_PDN_GLC_MEM_PDN_ADDR                 GPS_L5_SYS_ADRDEC_PDN_ADDR
#define GPS_L5_SYS_ADRDEC_PDN_GLC_MEM_PDN_MASK                 0x00001000
#define GPS_L5_SYS_ADRDEC_PDN_GLC_MEM_PDN_SHFT                 12
#define GPS_L5_SYS_ADRDEC_PDN_RFREC_PDN_ADDR                   GPS_L5_SYS_ADRDEC_PDN_ADDR
#define GPS_L5_SYS_ADRDEC_PDN_RFREC_PDN_MASK                   0x00000400
#define GPS_L5_SYS_ADRDEC_PDN_RFREC_PDN_SHFT                   10
#define GPS_L5_SYS_ADRDEC_PDN_RS232_T0_PDN_ADDR                GPS_L5_SYS_ADRDEC_PDN_ADDR
#define GPS_L5_SYS_ADRDEC_PDN_RS232_T0_PDN_MASK                0x00000100
#define GPS_L5_SYS_ADRDEC_PDN_RS232_T0_PDN_SHFT                8
#define GPS_L5_SYS_ADRDEC_PDN_RS232_R0_PDN_ADDR                GPS_L5_SYS_ADRDEC_PDN_ADDR
#define GPS_L5_SYS_ADRDEC_PDN_RS232_R0_PDN_MASK                0x00000040
#define GPS_L5_SYS_ADRDEC_PDN_RS232_R0_PDN_SHFT                6
#define GPS_L5_SYS_ADRDEC_PDN_RS232_DSP_DEC_PDN_ADDR           GPS_L5_SYS_ADRDEC_PDN_ADDR
#define GPS_L5_SYS_ADRDEC_PDN_RS232_DSP_DEC_PDN_MASK           0x00000020
#define GPS_L5_SYS_ADRDEC_PDN_RS232_DSP_DEC_PDN_SHFT           5
#define GPS_L5_SYS_ADRDEC_PDN_HSSP_PDN_ADDR                    GPS_L5_SYS_ADRDEC_PDN_ADDR
#define GPS_L5_SYS_ADRDEC_PDN_HSSP_PDN_MASK                    0x00000010
#define GPS_L5_SYS_ADRDEC_PDN_HSSP_PDN_SHFT                    4
#define GPS_L5_SYS_ADRDEC_PDN_I2C_MM_PDN_ADDR                  GPS_L5_SYS_ADRDEC_PDN_ADDR
#define GPS_L5_SYS_ADRDEC_PDN_I2C_MM_PDN_MASK                  0x00000008
#define GPS_L5_SYS_ADRDEC_PDN_I2C_MM_PDN_SHFT                  3
#define GPS_L5_SYS_ADRDEC_PDN_WDOG_PDN_ADDR                    GPS_L5_SYS_ADRDEC_PDN_ADDR
#define GPS_L5_SYS_ADRDEC_PDN_WDOG_PDN_MASK                    0x00000002
#define GPS_L5_SYS_ADRDEC_PDN_WDOG_PDN_SHFT                    1
#define GPS_L5_SYS_ADRDEC_PDN_DSP_ENV_PDN_ADDR                 GPS_L5_SYS_ADRDEC_PDN_ADDR
#define GPS_L5_SYS_ADRDEC_PDN_DSP_ENV_PDN_MASK                 0x00000001
#define GPS_L5_SYS_ADRDEC_PDN_DSP_ENV_PDN_SHFT                 0

#define GPS_L5_SYS_ADRDEC_SYS_RST_PATCH_RST_ADDR               GPS_L5_SYS_ADRDEC_SYS_RST_ADDR
#define GPS_L5_SYS_ADRDEC_SYS_RST_PATCH_RST_MASK               0x00004000
#define GPS_L5_SYS_ADRDEC_SYS_RST_PATCH_RST_SHFT               14
#define GPS_L5_SYS_ADRDEC_SYS_RST_RF_RST_ADDR                  GPS_L5_SYS_ADRDEC_SYS_RST_ADDR
#define GPS_L5_SYS_ADRDEC_SYS_RST_RF_RST_MASK                  0x00002000
#define GPS_L5_SYS_ADRDEC_SYS_RST_RF_RST_SHFT                  13
#define GPS_L5_SYS_ADRDEC_SYS_RST_GLC_MEM_RST_ADDR             GPS_L5_SYS_ADRDEC_SYS_RST_ADDR
#define GPS_L5_SYS_ADRDEC_SYS_RST_GLC_MEM_RST_MASK             0x00001000
#define GPS_L5_SYS_ADRDEC_SYS_RST_GLC_MEM_RST_SHFT             12
#define GPS_L5_SYS_ADRDEC_SYS_RST_USRT_RST_ADDR                GPS_L5_SYS_ADRDEC_SYS_RST_ADDR
#define GPS_L5_SYS_ADRDEC_SYS_RST_USRT_RST_MASK                0x00000020
#define GPS_L5_SYS_ADRDEC_SYS_RST_USRT_RST_SHFT                5
#define GPS_L5_SYS_ADRDEC_SYS_RST_WDOG_RST_ADDR                GPS_L5_SYS_ADRDEC_SYS_RST_ADDR
#define GPS_L5_SYS_ADRDEC_SYS_RST_WDOG_RST_MASK                0x00000002
#define GPS_L5_SYS_ADRDEC_SYS_RST_WDOG_RST_SHFT                1
#define GPS_L5_SYS_ADRDEC_SYS_RST_DSP_ENV_RST_ADDR             GPS_L5_SYS_ADRDEC_SYS_RST_ADDR
#define GPS_L5_SYS_ADRDEC_SYS_RST_DSP_ENV_RST_MASK             0x00000001
#define GPS_L5_SYS_ADRDEC_SYS_RST_DSP_ENV_RST_SHFT             0

#define GPS_L5_SYS_ADRDEC_SYS_SET_PLL_RDY_ADDR                 GPS_L5_SYS_ADRDEC_SYS_SET_ADDR
#define GPS_L5_SYS_ADRDEC_SYS_SET_PLL_RDY_MASK                 0x00001000
#define GPS_L5_SYS_ADRDEC_SYS_SET_PLL_RDY_SHFT                 12
#define GPS_L5_SYS_ADRDEC_SYS_SET_TEST_REFSEL_ADDR             GPS_L5_SYS_ADRDEC_SYS_SET_ADDR
#define GPS_L5_SYS_ADRDEC_SYS_SET_TEST_REFSEL_MASK             0x000000C0
#define GPS_L5_SYS_ADRDEC_SYS_SET_TEST_REFSEL_SHFT             6
#define GPS_L5_SYS_ADRDEC_SYS_SET_HOST_SEL_ADDR                GPS_L5_SYS_ADRDEC_SYS_SET_ADDR
#define GPS_L5_SYS_ADRDEC_SYS_SET_HOST_SEL_MASK                0x00000010
#define GPS_L5_SYS_ADRDEC_SYS_SET_HOST_SEL_SHFT                4
#define GPS_L5_SYS_ADRDEC_SYS_SET_RF_ONLY_MODE_ADDR            GPS_L5_SYS_ADRDEC_SYS_SET_ADDR
#define GPS_L5_SYS_ADRDEC_SYS_SET_RF_ONLY_MODE_MASK            0x00000002
#define GPS_L5_SYS_ADRDEC_SYS_SET_RF_ONLY_MODE_SHFT            1
#define GPS_L5_SYS_ADRDEC_SYS_SET_IF_REPLAY_MODE_ADDR          GPS_L5_SYS_ADRDEC_SYS_SET_ADDR
#define GPS_L5_SYS_ADRDEC_SYS_SET_IF_REPLAY_MODE_MASK          0x00000001
#define GPS_L5_SYS_ADRDEC_SYS_SET_IF_REPLAY_MODE_SHFT          0

#define GPS_L5_SYS_ADRDEC_WDOG_CFG_WDOG_EN_ADDR                GPS_L5_SYS_ADRDEC_WDOG_CFG_ADDR
#define GPS_L5_SYS_ADRDEC_WDOG_CFG_WDOG_EN_MASK                0x00000080
#define GPS_L5_SYS_ADRDEC_WDOG_CFG_WDOG_EN_SHFT                7
#define GPS_L5_SYS_ADRDEC_WDOG_CFG_WDOG_RST_ALL_EN_ADDR        GPS_L5_SYS_ADRDEC_WDOG_CFG_ADDR
#define GPS_L5_SYS_ADRDEC_WDOG_CFG_WDOG_RST_ALL_EN_MASK        0x00000020
#define GPS_L5_SYS_ADRDEC_WDOG_CFG_WDOG_RST_ALL_EN_SHFT        5
#define GPS_L5_SYS_ADRDEC_WDOG_CFG_WDOG_RST_ARM_EN_ADDR        GPS_L5_SYS_ADRDEC_WDOG_CFG_ADDR
#define GPS_L5_SYS_ADRDEC_WDOG_CFG_WDOG_RST_ARM_EN_MASK        0x00000010
#define GPS_L5_SYS_ADRDEC_WDOG_CFG_WDOG_RST_ARM_EN_SHFT        4
#define GPS_L5_SYS_ADRDEC_WDOG_CFG_RST_WIDTH_ADDR              GPS_L5_SYS_ADRDEC_WDOG_CFG_ADDR
#define GPS_L5_SYS_ADRDEC_WDOG_CFG_RST_WIDTH_MASK              0x0000000F
#define GPS_L5_SYS_ADRDEC_WDOG_CFG_RST_WIDTH_SHFT              0

#define GPS_L5_SYS_ADRDEC_WDOG_LEN_WDOG_LENGTH_ADDR            GPS_L5_SYS_ADRDEC_WDOG_LEN_ADDR
#define GPS_L5_SYS_ADRDEC_WDOG_LEN_WDOG_LENGTH_MASK            0x0000FFFF
#define GPS_L5_SYS_ADRDEC_WDOG_LEN_WDOG_LENGTH_SHFT            0

#define GPS_L5_SYS_ADRDEC_STRAP_EXT_INT_SEL_ADDR               GPS_L5_SYS_ADRDEC_STRAP_ADDR
#define GPS_L5_SYS_ADRDEC_STRAP_EXT_INT_SEL_MASK               0x00008000
#define GPS_L5_SYS_ADRDEC_STRAP_EXT_INT_SEL_SHFT               15
#define GPS_L5_SYS_ADRDEC_STRAP_TEAK_JTAG_EN_ADDR              GPS_L5_SYS_ADRDEC_STRAP_ADDR
#define GPS_L5_SYS_ADRDEC_STRAP_TEAK_JTAG_EN_MASK              0x00000040
#define GPS_L5_SYS_ADRDEC_STRAP_TEAK_JTAG_EN_SHFT              6
#define GPS_L5_SYS_ADRDEC_STRAP_TEAK_PGTEST_ADDR               GPS_L5_SYS_ADRDEC_STRAP_ADDR
#define GPS_L5_SYS_ADRDEC_STRAP_TEAK_PGTEST_MASK               0x00000020
#define GPS_L5_SYS_ADRDEC_STRAP_TEAK_PGTEST_SHFT               5
#define GPS_L5_SYS_ADRDEC_STRAP_EXTP_ADDR                      GPS_L5_SYS_ADRDEC_STRAP_ADDR
#define GPS_L5_SYS_ADRDEC_STRAP_EXTP_MASK                      0x00000004
#define GPS_L5_SYS_ADRDEC_STRAP_EXTP_SHFT                      2
#define GPS_L5_SYS_ADRDEC_STRAP_BOOT_ADDR                      GPS_L5_SYS_ADRDEC_STRAP_ADDR
#define GPS_L5_SYS_ADRDEC_STRAP_BOOT_MASK                      0x00000002
#define GPS_L5_SYS_ADRDEC_STRAP_BOOT_SHFT                      1
#define GPS_L5_SYS_ADRDEC_STRAP_REMAP_ADDR                     GPS_L5_SYS_ADRDEC_STRAP_ADDR
#define GPS_L5_SYS_ADRDEC_STRAP_REMAP_MASK                     0x00000001
#define GPS_L5_SYS_ADRDEC_STRAP_REMAP_SHFT                     0

#define GPS_L5_SYS_ADRDEC_PAGE_yram_page_ADDR                  GPS_L5_SYS_ADRDEC_PAGE_ADDR
#define GPS_L5_SYS_ADRDEC_PAGE_yram_page_MASK                  0x00000003
#define GPS_L5_SYS_ADRDEC_PAGE_yram_page_SHFT                  0

#define GPS_L5_SYS_ADRDEC_GPS_PWR_STAT_GPS_PWR_STAT_ADDR       GPS_L5_SYS_ADRDEC_GPS_PWR_STAT_ADDR
#define GPS_L5_SYS_ADRDEC_GPS_PWR_STAT_GPS_PWR_STAT_MASK       0x00000003
#define GPS_L5_SYS_ADRDEC_GPS_PWR_STAT_GPS_PWR_STAT_SHFT       0

#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_MRAM_REPAIR_EN_ADDR      GPS_L5_SYS_ADRDEC_BIST_DOTEST_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_MRAM_REPAIR_EN_MASK      0x00008000
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_MRAM_REPAIR_EN_SHFT      15
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_XRAM_REPAIR_EN_ADDR      GPS_L5_SYS_ADRDEC_BIST_DOTEST_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_XRAM_REPAIR_EN_MASK      0x00004000
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_XRAM_REPAIR_EN_SHFT      14
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_YRAM_REPAIR_EN_ADDR      GPS_L5_SYS_ADRDEC_BIST_DOTEST_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_YRAM_REPAIR_EN_MASK      0x00002000
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_YRAM_REPAIR_EN_SHFT      13
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_SHARE_DO_TEST_ADDR       GPS_L5_SYS_ADRDEC_BIST_DOTEST_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_SHARE_DO_TEST_MASK       0x00001000
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_SHARE_DO_TEST_SHFT       12
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_YRAM_DO_TEST_1_ADDR      GPS_L5_SYS_ADRDEC_BIST_DOTEST_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_YRAM_DO_TEST_1_MASK      0x00000800
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_YRAM_DO_TEST_1_SHFT      11
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_PROM_DO_TEST_ADDR        GPS_L5_SYS_ADRDEC_BIST_DOTEST_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_PROM_DO_TEST_MASK        0x00000100
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_PROM_DO_TEST_SHFT        8
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_GRAM_DO_TEST_ADDR        GPS_L5_SYS_ADRDEC_BIST_DOTEST_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_GRAM_DO_TEST_MASK        0x00000040
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_GRAM_DO_TEST_SHFT        6
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_FTRAM_DO_TEST_ADDR       GPS_L5_SYS_ADRDEC_BIST_DOTEST_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_FTRAM_DO_TEST_MASK       0x00000020
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_FTRAM_DO_TEST_SHFT       5
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_PRAM_DO_TEST_1_ADDR      GPS_L5_SYS_ADRDEC_BIST_DOTEST_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_PRAM_DO_TEST_1_MASK      0x00000010
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_PRAM_DO_TEST_1_SHFT      4
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_XRAM_DO_TEST_ADDR        GPS_L5_SYS_ADRDEC_BIST_DOTEST_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_XRAM_DO_TEST_MASK        0x00000008
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_XRAM_DO_TEST_SHFT        3
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_YRAM_DO_TEST_ADDR        GPS_L5_SYS_ADRDEC_BIST_DOTEST_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_YRAM_DO_TEST_MASK        0x00000004
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_YRAM_DO_TEST_SHFT        2
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_PRAM_DO_TEST_ADDR        GPS_L5_SYS_ADRDEC_BIST_DOTEST_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_PRAM_DO_TEST_MASK        0x00000002
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_PRAM_DO_TEST_SHFT        1
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_URAM_DO_TEST_ADDR        GPS_L5_SYS_ADRDEC_BIST_DOTEST_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_URAM_DO_TEST_MASK        0x00000001
#define GPS_L5_SYS_ADRDEC_BIST_DOTEST_URAM_DO_TEST_SHFT        0

#define GPS_L5_SYS_ADRDEC_BIST_BYTESEL_MRAM_BYTE_SEL_ADDR      GPS_L5_SYS_ADRDEC_BIST_BYTESEL_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_BYTESEL_MRAM_BYTE_SEL_MASK      0x000000FF
#define GPS_L5_SYS_ADRDEC_BIST_BYTESEL_MRAM_BYTE_SEL_SHFT      0

#define GPS_L5_SYS_ADRDEC_BIST_DONE_CROM_TEST_DONE_ADDR        GPS_L5_SYS_ADRDEC_BIST_DONE_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_DONE_CROM_TEST_DONE_MASK        0x00002000
#define GPS_L5_SYS_ADRDEC_BIST_DONE_CROM_TEST_DONE_SHFT        13
#define GPS_L5_SYS_ADRDEC_BIST_DONE_PROM_TEST_DONE_ADDR        GPS_L5_SYS_ADRDEC_BIST_DONE_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_DONE_PROM_TEST_DONE_MASK        0x00001000
#define GPS_L5_SYS_ADRDEC_BIST_DONE_PROM_TEST_DONE_SHFT        12
#define GPS_L5_SYS_ADRDEC_BIST_DONE_FTRAM_BIST_DONE_ADDR       GPS_L5_SYS_ADRDEC_BIST_DONE_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_DONE_FTRAM_BIST_DONE_MASK       0x00000200
#define GPS_L5_SYS_ADRDEC_BIST_DONE_FTRAM_BIST_DONE_SHFT       9
#define GPS_L5_SYS_ADRDEC_BIST_DONE_SPRAM_BIST_DONE_ADDR       GPS_L5_SYS_ADRDEC_BIST_DONE_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_DONE_SPRAM_BIST_DONE_MASK       0x00000100
#define GPS_L5_SYS_ADRDEC_BIST_DONE_SPRAM_BIST_DONE_SHFT       8
#define GPS_L5_SYS_ADRDEC_BIST_DONE_SHARE_TEST_DONE_ADDR       GPS_L5_SYS_ADRDEC_BIST_DONE_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_DONE_SHARE_TEST_DONE_MASK       0x00000080
#define GPS_L5_SYS_ADRDEC_BIST_DONE_SHARE_TEST_DONE_SHFT       7
#define GPS_L5_SYS_ADRDEC_BIST_DONE_GRAM_TEST_DONE_ADDR        GPS_L5_SYS_ADRDEC_BIST_DONE_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_DONE_GRAM_TEST_DONE_MASK        0x00000040
#define GPS_L5_SYS_ADRDEC_BIST_DONE_GRAM_TEST_DONE_SHFT        6
#define GPS_L5_SYS_ADRDEC_BIST_DONE_TRAM_TEST_DONE_ADDR        GPS_L5_SYS_ADRDEC_BIST_DONE_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_DONE_TRAM_TEST_DONE_MASK        0x00000020
#define GPS_L5_SYS_ADRDEC_BIST_DONE_TRAM_TEST_DONE_SHFT        5
#define GPS_L5_SYS_ADRDEC_BIST_DONE_MRAM_TEST_DONE_ADDR        GPS_L5_SYS_ADRDEC_BIST_DONE_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_DONE_MRAM_TEST_DONE_MASK        0x00000010
#define GPS_L5_SYS_ADRDEC_BIST_DONE_MRAM_TEST_DONE_SHFT        4
#define GPS_L5_SYS_ADRDEC_BIST_DONE_XRAM_TEST_DONE_ADDR        GPS_L5_SYS_ADRDEC_BIST_DONE_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_DONE_XRAM_TEST_DONE_MASK        0x00000008
#define GPS_L5_SYS_ADRDEC_BIST_DONE_XRAM_TEST_DONE_SHFT        3
#define GPS_L5_SYS_ADRDEC_BIST_DONE_YRAM_TEST_DONE_ADDR        GPS_L5_SYS_ADRDEC_BIST_DONE_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_DONE_YRAM_TEST_DONE_MASK        0x00000004
#define GPS_L5_SYS_ADRDEC_BIST_DONE_YRAM_TEST_DONE_SHFT        2
#define GPS_L5_SYS_ADRDEC_BIST_DONE_PRAM_TEST_DONE_ADDR        GPS_L5_SYS_ADRDEC_BIST_DONE_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_DONE_PRAM_TEST_DONE_MASK        0x00000002
#define GPS_L5_SYS_ADRDEC_BIST_DONE_PRAM_TEST_DONE_SHFT        1
#define GPS_L5_SYS_ADRDEC_BIST_DONE_URAM_TEST_DONE_ADDR        GPS_L5_SYS_ADRDEC_BIST_DONE_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_DONE_URAM_TEST_DONE_MASK        0x00000001
#define GPS_L5_SYS_ADRDEC_BIST_DONE_URAM_TEST_DONE_SHFT        0

#define GPS_L5_SYS_ADRDEC_BIST_STATUS_CROM_TEST_FAIL_ADDR      GPS_L5_SYS_ADRDEC_BIST_STATUS_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_CROM_TEST_FAIL_MASK      0x00002000
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_CROM_TEST_FAIL_SHFT      13
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_PROM_TEST_FAIL_ADDR      GPS_L5_SYS_ADRDEC_BIST_STATUS_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_PROM_TEST_FAIL_MASK      0x00001000
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_PROM_TEST_FAIL_SHFT      12
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_FTRAM_BIST_FAIL_ADDR     GPS_L5_SYS_ADRDEC_BIST_STATUS_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_FTRAM_BIST_FAIL_MASK     0x00000200
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_FTRAM_BIST_FAIL_SHFT     9
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_SPRAM_BIST_FAIL_ADDR     GPS_L5_SYS_ADRDEC_BIST_STATUS_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_SPRAM_BIST_FAIL_MASK     0x00000100
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_SPRAM_BIST_FAIL_SHFT     8
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_SHARE_TEST_FAIL_ADDR     GPS_L5_SYS_ADRDEC_BIST_STATUS_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_SHARE_TEST_FAIL_MASK     0x00000080
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_SHARE_TEST_FAIL_SHFT     7
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_GRAM_TEST_FAIL_ADDR      GPS_L5_SYS_ADRDEC_BIST_STATUS_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_GRAM_TEST_FAIL_MASK      0x00000040
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_GRAM_TEST_FAIL_SHFT      6
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_TRAM_TEST_FAIL_ADDR      GPS_L5_SYS_ADRDEC_BIST_STATUS_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_TRAM_TEST_FAIL_MASK      0x00000020
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_TRAM_TEST_FAIL_SHFT      5
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_MRAM_TEST_FAIL_ADDR      GPS_L5_SYS_ADRDEC_BIST_STATUS_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_MRAM_TEST_FAIL_MASK      0x00000010
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_MRAM_TEST_FAIL_SHFT      4
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_XRAM_TEST_FAIL_ADDR      GPS_L5_SYS_ADRDEC_BIST_STATUS_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_XRAM_TEST_FAIL_MASK      0x00000008
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_XRAM_TEST_FAIL_SHFT      3
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_YRAM_TEST_FAIL_ADDR      GPS_L5_SYS_ADRDEC_BIST_STATUS_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_YRAM_TEST_FAIL_MASK      0x00000004
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_YRAM_TEST_FAIL_SHFT      2
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_PRAM_TEST_FAIL_ADDR      GPS_L5_SYS_ADRDEC_BIST_STATUS_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_PRAM_TEST_FAIL_MASK      0x00000002
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_PRAM_TEST_FAIL_SHFT      1
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_URAM_TEST_FAIL_ADDR      GPS_L5_SYS_ADRDEC_BIST_STATUS_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_URAM_TEST_FAIL_MASK      0x00000001
#define GPS_L5_SYS_ADRDEC_BIST_STATUS_URAM_TEST_FAIL_SHFT      0

#define GPS_L5_SYS_ADRDEC_REPAIR_MONSEL_REPAIR_BIT_SEL_ADDR    GPS_L5_SYS_ADRDEC_REPAIR_MONSEL_ADDR
#define GPS_L5_SYS_ADRDEC_REPAIR_MONSEL_REPAIR_BIT_SEL_MASK    0x00007F00
#define GPS_L5_SYS_ADRDEC_REPAIR_MONSEL_REPAIR_BIT_SEL_SHFT    8
#define GPS_L5_SYS_ADRDEC_REPAIR_MONSEL_REPAIR_MONSEL_ADDR     GPS_L5_SYS_ADRDEC_REPAIR_MONSEL_ADDR
#define GPS_L5_SYS_ADRDEC_REPAIR_MONSEL_REPAIR_MONSEL_MASK     0x0000003F
#define GPS_L5_SYS_ADRDEC_REPAIR_MONSEL_REPAIR_MONSEL_SHFT     0

#define GPS_L5_SYS_ADRDEC_REPAIR_MON_REPAIR_MON_ADDR           GPS_L5_SYS_ADRDEC_REPAIR_MON_ADDR
#define GPS_L5_SYS_ADRDEC_REPAIR_MON_REPAIR_MON_MASK           0x0000FFFF
#define GPS_L5_SYS_ADRDEC_REPAIR_MON_REPAIR_MON_SHFT           0

#define GPS_L5_SYS_ADRDEC_BIST_PAT_BIST_PATTERN_ADDR           GPS_L5_SYS_ADRDEC_BIST_PAT_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_PAT_BIST_PATTERN_MASK           0x0000FFFF
#define GPS_L5_SYS_ADRDEC_BIST_PAT_BIST_PATTERN_SHFT           0

#define GPS_L5_SYS_ADRDEC_DELSEL0_L_CH0_FTRAM_DELSEL_L_ADDR    GPS_L5_SYS_ADRDEC_DELSEL0_L_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL0_L_CH0_FTRAM_DELSEL_L_MASK    0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL0_L_CH0_FTRAM_DELSEL_L_SHFT    0

#define GPS_L5_SYS_ADRDEC_DELSEL1_L_CH1_FTRAM_DELSEL_L_ADDR    GPS_L5_SYS_ADRDEC_DELSEL1_L_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL1_L_CH1_FTRAM_DELSEL_L_MASK    0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL1_L_CH1_FTRAM_DELSEL_L_SHFT    0

#define GPS_L5_SYS_ADRDEC_DELSEL2_L_CH0_SPRAM_DELSEL_L_ADDR    GPS_L5_SYS_ADRDEC_DELSEL2_L_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL2_L_CH0_SPRAM_DELSEL_L_MASK    0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL2_L_CH0_SPRAM_DELSEL_L_SHFT    0

#define GPS_L5_SYS_ADRDEC_DELSEL3_L_CH1_SPRAM_DELSEL_L_ADDR    GPS_L5_SYS_ADRDEC_DELSEL3_L_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL3_L_CH1_SPRAM_DELSEL_L_MASK    0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL3_L_CH1_SPRAM_DELSEL_L_SHFT    0

#define GPS_L5_SYS_ADRDEC_DELSEL4_L_GRAM_DELSEL_L_ADDR         GPS_L5_SYS_ADRDEC_DELSEL4_L_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL4_L_GRAM_DELSEL_L_MASK         0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL4_L_GRAM_DELSEL_L_SHFT         0

#define GPS_L5_SYS_ADRDEC_DELSEL5_L_TRAM_DELSEL_1KX64_L_ADDR   GPS_L5_SYS_ADRDEC_DELSEL5_L_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL5_L_TRAM_DELSEL_1KX64_L_MASK   0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL5_L_TRAM_DELSEL_1KX64_L_SHFT   0

#define GPS_L5_SYS_ADRDEC_DELSEL6_L_MRAM_DELSEL_1KX32_L_ADDR   GPS_L5_SYS_ADRDEC_DELSEL6_L_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL6_L_MRAM_DELSEL_1KX32_L_MASK   0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL6_L_MRAM_DELSEL_1KX32_L_SHFT   0

#define GPS_L5_SYS_ADRDEC_DELSEL7_L_MRAM_DELSEL_1KX64_L_ADDR   GPS_L5_SYS_ADRDEC_DELSEL7_L_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL7_L_MRAM_DELSEL_1KX64_L_MASK   0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL7_L_MRAM_DELSEL_1KX64_L_SHFT   0

#define GPS_L5_SYS_ADRDEC_LOAD_FUSE_FUSE_SEL_ADDR              GPS_L5_SYS_ADRDEC_LOAD_FUSE_ADDR
#define GPS_L5_SYS_ADRDEC_LOAD_FUSE_FUSE_SEL_MASK              0x00000002
#define GPS_L5_SYS_ADRDEC_LOAD_FUSE_FUSE_SEL_SHFT              1
#define GPS_L5_SYS_ADRDEC_LOAD_FUSE_LOAD_FUSE_ADDR             GPS_L5_SYS_ADRDEC_LOAD_FUSE_ADDR
#define GPS_L5_SYS_ADRDEC_LOAD_FUSE_LOAD_FUSE_MASK             0x00000001
#define GPS_L5_SYS_ADRDEC_LOAD_FUSE_LOAD_FUSE_SHFT             0

#define GPS_L5_SYS_ADRDEC_ECLK_CTL_RCNT_FINISH_ADDR            GPS_L5_SYS_ADRDEC_ECLK_CTL_ADDR
#define GPS_L5_SYS_ADRDEC_ECLK_CTL_RCNT_FINISH_MASK            0x00000020
#define GPS_L5_SYS_ADRDEC_ECLK_CTL_RCNT_FINISH_SHFT            5
#define GPS_L5_SYS_ADRDEC_ECLK_CTL_RCNT_EN_ADDR                GPS_L5_SYS_ADRDEC_ECLK_CTL_ADDR
#define GPS_L5_SYS_ADRDEC_ECLK_CTL_RCNT_EN_MASK                0x00000010
#define GPS_L5_SYS_ADRDEC_ECLK_CTL_RCNT_EN_SHFT                4
#define GPS_L5_SYS_ADRDEC_ECLK_CTL_ECNT_FINISH_ADDR            GPS_L5_SYS_ADRDEC_ECLK_CTL_ADDR
#define GPS_L5_SYS_ADRDEC_ECLK_CTL_ECNT_FINISH_MASK            0x00000002
#define GPS_L5_SYS_ADRDEC_ECLK_CTL_ECNT_FINISH_SHFT            1
#define GPS_L5_SYS_ADRDEC_ECLK_CTL_ECNT_EN_ADDR                GPS_L5_SYS_ADRDEC_ECLK_CTL_ADDR
#define GPS_L5_SYS_ADRDEC_ECLK_CTL_ECNT_EN_MASK                0x00000001
#define GPS_L5_SYS_ADRDEC_ECLK_CTL_ECNT_EN_SHFT                0

#define GPS_L5_SYS_ADRDEC_ECLKL_CLK_CNT_LIM_ADDR               GPS_L5_SYS_ADRDEC_ECLKL_ADDR
#define GPS_L5_SYS_ADRDEC_ECLKL_CLK_CNT_LIM_MASK               0x0000FFFF
#define GPS_L5_SYS_ADRDEC_ECLKL_CLK_CNT_LIM_SHFT               0

#define GPS_L5_SYS_ADRDEC_ECLKH_CLK_CNT_LIM_ADDR               GPS_L5_SYS_ADRDEC_ECLKH_ADDR
#define GPS_L5_SYS_ADRDEC_ECLKH_CLK_CNT_LIM_MASK               0x000003FF
#define GPS_L5_SYS_ADRDEC_ECLKH_CLK_CNT_LIM_SHFT               0

#define GPS_L5_SYS_ADRDEC_ECLKSTAL_ECLK_CNT_L_ADDR             GPS_L5_SYS_ADRDEC_ECLKSTAL_ADDR
#define GPS_L5_SYS_ADRDEC_ECLKSTAL_ECLK_CNT_L_MASK             0x0000FFFF
#define GPS_L5_SYS_ADRDEC_ECLKSTAL_ECLK_CNT_L_SHFT             0

#define GPS_L5_SYS_ADRDEC_ECLKSTAH_ECLK_CNT_H_ADDR             GPS_L5_SYS_ADRDEC_ECLKSTAH_ADDR
#define GPS_L5_SYS_ADRDEC_ECLKSTAH_ECLK_CNT_H_MASK             0x00000FFF
#define GPS_L5_SYS_ADRDEC_ECLKSTAH_ECLK_CNT_H_SHFT             0

#define GPS_L5_SYS_ADRDEC_DELSEL8_L_URAM_DELSEL_L_ADDR         GPS_L5_SYS_ADRDEC_DELSEL8_L_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL8_L_URAM_DELSEL_L_MASK         0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL8_L_URAM_DELSEL_L_SHFT         0

#define GPS_L5_SYS_ADRDEC_DELSEL9_L_YRAM_1KX16_DELSEL_L_ADDR   GPS_L5_SYS_ADRDEC_DELSEL9_L_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL9_L_YRAM_1KX16_DELSEL_L_MASK   0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL9_L_YRAM_1KX16_DELSEL_L_SHFT   0

#define GPS_L5_SYS_ADRDEC_DELSEL10_L_DSPRAM_4KX16_DELSEL_L_ADDR GPS_L5_SYS_ADRDEC_DELSEL10_L_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL10_L_DSPRAM_4KX16_DELSEL_L_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL10_L_DSPRAM_4KX16_DELSEL_L_SHFT 0

#define GPS_L5_SYS_ADRDEC_DELSEL11_L_DSPRAM_3328X16_DELSEL_L_ADDR GPS_L5_SYS_ADRDEC_DELSEL11_L_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL11_L_DSPRAM_3328X16_DELSEL_L_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL11_L_DSPRAM_3328X16_DELSEL_L_SHFT 0

#define GPS_L5_SYS_ADRDEC_DELSEL12_L_DSPRAM_3584X16_DELSEL_L_ADDR GPS_L5_SYS_ADRDEC_DELSEL12_L_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL12_L_DSPRAM_3584X16_DELSEL_L_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL12_L_DSPRAM_3584X16_DELSEL_L_SHFT 0

#define GPS_L5_SYS_ADRDEC_DELSEL13_L_TRAM_DELSEL_1KX128_L_ADDR GPS_L5_SYS_ADRDEC_DELSEL13_L_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL13_L_TRAM_DELSEL_1KX128_L_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL13_L_TRAM_DELSEL_1KX128_L_SHFT 0

#define GPS_L5_SYS_ADRDEC_DELSEL14_L_TRAM_DELSEL_512X64_L_ADDR GPS_L5_SYS_ADRDEC_DELSEL14_L_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL14_L_TRAM_DELSEL_512X64_L_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL14_L_TRAM_DELSEL_512X64_L_SHFT 0

#define GPS_L5_SYS_ADRDEC_DELSEL15_L_MRAM_DELSEL_512X32_L_ADDR GPS_L5_SYS_ADRDEC_DELSEL15_L_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL15_L_MRAM_DELSEL_512X32_L_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL15_L_MRAM_DELSEL_512X32_L_SHFT 0

#define GPS_L5_SYS_ADRDEC_DELSEL16_L_PROM_DELSEL_8KX16_L_ADDR  GPS_L5_SYS_ADRDEC_DELSEL16_L_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL16_L_PROM_DELSEL_8KX16_L_MASK  0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL16_L_PROM_DELSEL_8KX16_L_SHFT  0

#define GPS_L5_SYS_ADRDEC_DELSEL17_L_CROM_DELSEL_6656X32_L_ADDR GPS_L5_SYS_ADRDEC_DELSEL17_L_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL17_L_CROM_DELSEL_6656X32_L_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL17_L_CROM_DELSEL_6656X32_L_SHFT 0

#define GPS_L5_SYS_ADRDEC_MONCFG_MONCFG_ADDR                   GPS_L5_SYS_ADRDEC_MONCFG_ADDR
#define GPS_L5_SYS_ADRDEC_MONCFG_MONCFG_MASK                   0x0000FFFF
#define GPS_L5_SYS_ADRDEC_MONCFG_MONCFG_SHFT                   0

#define GPS_L5_SYS_ADRDEC_MONOUT_MONOUT_ADDR                   GPS_L5_SYS_ADRDEC_MONOUT_ADDR
#define GPS_L5_SYS_ADRDEC_MONOUT_MONOUT_MASK                   0x0000FFFF
#define GPS_L5_SYS_ADRDEC_MONOUT_MONOUT_SHFT                   0

#define GPS_L5_SYS_ADRDEC_MONIN_MON_IN_ADDR                    GPS_L5_SYS_ADRDEC_MONIN_ADDR
#define GPS_L5_SYS_ADRDEC_MONIN_MON_IN_MASK                    0x0000FFFF
#define GPS_L5_SYS_ADRDEC_MONIN_MON_IN_SHFT                    0

#define GPS_L5_SYS_ADRDEC_GRPSEL_GRPB_SEL_ADDR                 GPS_L5_SYS_ADRDEC_GRPSEL_ADDR
#define GPS_L5_SYS_ADRDEC_GRPSEL_GRPB_SEL_MASK                 0x000000F0
#define GPS_L5_SYS_ADRDEC_GRPSEL_GRPB_SEL_SHFT                 4
#define GPS_L5_SYS_ADRDEC_GRPSEL_GRPA_SEL_ADDR                 GPS_L5_SYS_ADRDEC_GRPSEL_ADDR
#define GPS_L5_SYS_ADRDEC_GRPSEL_GRPA_SEL_MASK                 0x0000000F
#define GPS_L5_SYS_ADRDEC_GRPSEL_GRPA_SEL_SHFT                 0

#define GPS_L5_SYS_ADRDEC_FLAGSEL_FLAGB_SEL_ADDR               GPS_L5_SYS_ADRDEC_FLAGSEL_ADDR
#define GPS_L5_SYS_ADRDEC_FLAGSEL_FLAGB_SEL_MASK               0x0000FF00
#define GPS_L5_SYS_ADRDEC_FLAGSEL_FLAGB_SEL_SHFT               8
#define GPS_L5_SYS_ADRDEC_FLAGSEL_FLAGA_SEL_ADDR               GPS_L5_SYS_ADRDEC_FLAGSEL_ADDR
#define GPS_L5_SYS_ADRDEC_FLAGSEL_FLAGA_SEL_MASK               0x000000FF
#define GPS_L5_SYS_ADRDEC_FLAGSEL_FLAGA_SEL_SHFT               0

#define GPS_L5_SYS_ADRDEC_BIST_RESETB_mbist_rst_b_ADDR         GPS_L5_SYS_ADRDEC_BIST_RESETB_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_RESETB_mbist_rst_b_MASK         0x00000001
#define GPS_L5_SYS_ADRDEC_BIST_RESETB_mbist_rst_b_SHFT         0

#define GPS_L5_SYS_ADRDEC_BIST_RPRSTB_mbist_rpst_b_ADDR        GPS_L5_SYS_ADRDEC_BIST_RPRSTB_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_RPRSTB_mbist_rpst_b_MASK        0x00000001
#define GPS_L5_SYS_ADRDEC_BIST_RPRSTB_mbist_rpst_b_SHFT        0

#define GPS_L5_SYS_ADRDEC_BIST_RP_FAIL_gram_rp_fail_ADDR       GPS_L5_SYS_ADRDEC_BIST_RP_FAIL_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_RP_FAIL_gram_rp_fail_MASK       0x00000080
#define GPS_L5_SYS_ADRDEC_BIST_RP_FAIL_gram_rp_fail_SHFT       7
#define GPS_L5_SYS_ADRDEC_BIST_RP_FAIL_tram_rp_fail_ADDR       GPS_L5_SYS_ADRDEC_BIST_RP_FAIL_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_RP_FAIL_tram_rp_fail_MASK       0x00000040
#define GPS_L5_SYS_ADRDEC_BIST_RP_FAIL_tram_rp_fail_SHFT       6
#define GPS_L5_SYS_ADRDEC_BIST_RP_FAIL_mram_rp_fail_ADDR       GPS_L5_SYS_ADRDEC_BIST_RP_FAIL_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_RP_FAIL_mram_rp_fail_MASK       0x00000020
#define GPS_L5_SYS_ADRDEC_BIST_RP_FAIL_mram_rp_fail_SHFT       5
#define GPS_L5_SYS_ADRDEC_BIST_RP_FAIL_xram_rp_fail_ADDR       GPS_L5_SYS_ADRDEC_BIST_RP_FAIL_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_RP_FAIL_xram_rp_fail_MASK       0x00000010
#define GPS_L5_SYS_ADRDEC_BIST_RP_FAIL_xram_rp_fail_SHFT       4
#define GPS_L5_SYS_ADRDEC_BIST_RP_FAIL_yram_rp_fail_ADDR       GPS_L5_SYS_ADRDEC_BIST_RP_FAIL_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_RP_FAIL_yram_rp_fail_MASK       0x00000008
#define GPS_L5_SYS_ADRDEC_BIST_RP_FAIL_yram_rp_fail_SHFT       3
#define GPS_L5_SYS_ADRDEC_BIST_RP_FAIL_pram_rp_fail_ADDR       GPS_L5_SYS_ADRDEC_BIST_RP_FAIL_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_RP_FAIL_pram_rp_fail_MASK       0x00000004
#define GPS_L5_SYS_ADRDEC_BIST_RP_FAIL_pram_rp_fail_SHFT       2
#define GPS_L5_SYS_ADRDEC_BIST_RP_FAIL_uram_rp_fail_ADDR       GPS_L5_SYS_ADRDEC_BIST_RP_FAIL_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_RP_FAIL_uram_rp_fail_MASK       0x00000002
#define GPS_L5_SYS_ADRDEC_BIST_RP_FAIL_uram_rp_fail_SHFT       1
#define GPS_L5_SYS_ADRDEC_BIST_RP_FAIL_share_rp_fail_ADDR      GPS_L5_SYS_ADRDEC_BIST_RP_FAIL_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_RP_FAIL_share_rp_fail_MASK      0x00000001
#define GPS_L5_SYS_ADRDEC_BIST_RP_FAIL_share_rp_fail_SHFT      0

#define GPS_L5_SYS_ADRDEC_BIST_RP_OK_gram_rp_ok_ADDR           GPS_L5_SYS_ADRDEC_BIST_RP_OK_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_RP_OK_gram_rp_ok_MASK           0x00000080
#define GPS_L5_SYS_ADRDEC_BIST_RP_OK_gram_rp_ok_SHFT           7
#define GPS_L5_SYS_ADRDEC_BIST_RP_OK_tram_rp_ok_ADDR           GPS_L5_SYS_ADRDEC_BIST_RP_OK_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_RP_OK_tram_rp_ok_MASK           0x00000040
#define GPS_L5_SYS_ADRDEC_BIST_RP_OK_tram_rp_ok_SHFT           6
#define GPS_L5_SYS_ADRDEC_BIST_RP_OK_mram_rp_ok_ADDR           GPS_L5_SYS_ADRDEC_BIST_RP_OK_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_RP_OK_mram_rp_ok_MASK           0x00000020
#define GPS_L5_SYS_ADRDEC_BIST_RP_OK_mram_rp_ok_SHFT           5
#define GPS_L5_SYS_ADRDEC_BIST_RP_OK_xram_rp_ok_ADDR           GPS_L5_SYS_ADRDEC_BIST_RP_OK_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_RP_OK_xram_rp_ok_MASK           0x00000010
#define GPS_L5_SYS_ADRDEC_BIST_RP_OK_xram_rp_ok_SHFT           4
#define GPS_L5_SYS_ADRDEC_BIST_RP_OK_yram_rp_ok_ADDR           GPS_L5_SYS_ADRDEC_BIST_RP_OK_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_RP_OK_yram_rp_ok_MASK           0x00000008
#define GPS_L5_SYS_ADRDEC_BIST_RP_OK_yram_rp_ok_SHFT           3
#define GPS_L5_SYS_ADRDEC_BIST_RP_OK_pram_rp_ok_ADDR           GPS_L5_SYS_ADRDEC_BIST_RP_OK_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_RP_OK_pram_rp_ok_MASK           0x00000004
#define GPS_L5_SYS_ADRDEC_BIST_RP_OK_pram_rp_ok_SHFT           2
#define GPS_L5_SYS_ADRDEC_BIST_RP_OK_uram_rp_ok_ADDR           GPS_L5_SYS_ADRDEC_BIST_RP_OK_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_RP_OK_uram_rp_ok_MASK           0x00000002
#define GPS_L5_SYS_ADRDEC_BIST_RP_OK_uram_rp_ok_SHFT           1
#define GPS_L5_SYS_ADRDEC_BIST_RP_OK_share_rp_ok_ADDR          GPS_L5_SYS_ADRDEC_BIST_RP_OK_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_RP_OK_share_rp_ok_MASK          0x00000001
#define GPS_L5_SYS_ADRDEC_BIST_RP_OK_share_rp_ok_SHFT          0

#define GPS_L5_SYS_ADRDEC_REPAIR_ADDR_0_mbist_soft_fuse_0_ADDR GPS_L5_SYS_ADRDEC_REPAIR_ADDR_0_ADDR
#define GPS_L5_SYS_ADRDEC_REPAIR_ADDR_0_mbist_soft_fuse_0_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_REPAIR_ADDR_0_mbist_soft_fuse_0_SHFT 0

#define GPS_L5_SYS_ADRDEC_REPAIR_ADDR_1_mbist_soft_fuse_1_ADDR GPS_L5_SYS_ADRDEC_REPAIR_ADDR_1_ADDR
#define GPS_L5_SYS_ADRDEC_REPAIR_ADDR_1_mbist_soft_fuse_1_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_REPAIR_ADDR_1_mbist_soft_fuse_1_SHFT 0

#define GPS_L5_SYS_ADRDEC_REPAIR_ADDR_2_mbist_soft_fuse_2_ADDR GPS_L5_SYS_ADRDEC_REPAIR_ADDR_2_ADDR
#define GPS_L5_SYS_ADRDEC_REPAIR_ADDR_2_mbist_soft_fuse_2_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_REPAIR_ADDR_2_mbist_soft_fuse_2_SHFT 0

#define GPS_L5_SYS_ADRDEC_REPAIR_FUSE_0_prdata_prefuse_0_ADDR  GPS_L5_SYS_ADRDEC_REPAIR_FUSE_0_ADDR
#define GPS_L5_SYS_ADRDEC_REPAIR_FUSE_0_prdata_prefuse_0_MASK  0x0000FFFF
#define GPS_L5_SYS_ADRDEC_REPAIR_FUSE_0_prdata_prefuse_0_SHFT  0

#define GPS_L5_SYS_ADRDEC_REPAIR_FUSE_1_prdata_prefuse_1_ADDR  GPS_L5_SYS_ADRDEC_REPAIR_FUSE_1_ADDR
#define GPS_L5_SYS_ADRDEC_REPAIR_FUSE_1_prdata_prefuse_1_MASK  0x0000FFFF
#define GPS_L5_SYS_ADRDEC_REPAIR_FUSE_1_prdata_prefuse_1_SHFT  0

#define GPS_L5_SYS_ADRDEC_REPAIR_FUSE_2_prdata_prefuse_2_ADDR  GPS_L5_SYS_ADRDEC_REPAIR_FUSE_2_ADDR
#define GPS_L5_SYS_ADRDEC_REPAIR_FUSE_2_prdata_prefuse_2_MASK  0x0000FFFF
#define GPS_L5_SYS_ADRDEC_REPAIR_FUSE_2_prdata_prefuse_2_SHFT  0

#define GPS_L5_SYS_ADRDEC_REPAIR_FUSE_3_prdata_prefuse_3_ADDR  GPS_L5_SYS_ADRDEC_REPAIR_FUSE_3_ADDR
#define GPS_L5_SYS_ADRDEC_REPAIR_FUSE_3_prdata_prefuse_3_MASK  0x0000FFFF
#define GPS_L5_SYS_ADRDEC_REPAIR_FUSE_3_prdata_prefuse_3_SHFT  0

#define GPS_L5_SYS_ADRDEC_REPAIR_FUSE_4_prdata_prefuse_4_ADDR  GPS_L5_SYS_ADRDEC_REPAIR_FUSE_4_ADDR
#define GPS_L5_SYS_ADRDEC_REPAIR_FUSE_4_prdata_prefuse_4_MASK  0x0000FFFF
#define GPS_L5_SYS_ADRDEC_REPAIR_FUSE_4_prdata_prefuse_4_SHFT  0

#define GPS_L5_SYS_ADRDEC_REPAIR_FUSE_5_prdata_prefuse_5_ADDR  GPS_L5_SYS_ADRDEC_REPAIR_FUSE_5_ADDR
#define GPS_L5_SYS_ADRDEC_REPAIR_FUSE_5_prdata_prefuse_5_MASK  0x0000FFFF
#define GPS_L5_SYS_ADRDEC_REPAIR_FUSE_5_prdata_prefuse_5_SHFT  0

#define GPS_L5_SYS_ADRDEC_MBIST_CROM_FAIL_BUS_crom_mbist_fail_bus_ADDR GPS_L5_SYS_ADRDEC_MBIST_CROM_FAIL_BUS_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_CROM_FAIL_BUS_crom_mbist_fail_bus_MASK 0x000003FF
#define GPS_L5_SYS_ADRDEC_MBIST_CROM_FAIL_BUS_crom_mbist_fail_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_GRAM_FAIL_BUS_gram_mbist_fail_bus_ADDR GPS_L5_SYS_ADRDEC_MBIST_GRAM_FAIL_BUS_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_GRAM_FAIL_BUS_gram_mbist_fail_bus_MASK 0x000001FF
#define GPS_L5_SYS_ADRDEC_MBIST_GRAM_FAIL_BUS_gram_mbist_fail_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_GRAM_RP_FAIL_BUS_gram_mbist_rp_fail_bus_ADDR \
	GPS_L5_SYS_ADRDEC_MBIST_GRAM_RP_FAIL_BUS_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_GRAM_RP_FAIL_BUS_gram_mbist_rp_fail_bus_MASK 0x000001FF
#define GPS_L5_SYS_ADRDEC_MBIST_GRAM_RP_FAIL_BUS_gram_mbist_rp_fail_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_GRAM_RP_OKBUS_gram_mbist_rp_ok_bus_ADDR GPS_L5_SYS_ADRDEC_MBIST_GRAM_RP_OKBUS_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_GRAM_RP_OKBUS_gram_mbist_rp_ok_bus_MASK 0x000001FF
#define GPS_L5_SYS_ADRDEC_MBIST_GRAM_RP_OKBUS_gram_mbist_rp_ok_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_FAIL_BUS_0_tram_mbist_fail_bus_ADDR GPS_L5_SYS_ADRDEC_MBIST_TRAM_FAIL_BUS_0_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_FAIL_BUS_0_tram_mbist_fail_bus_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_FAIL_BUS_0_tram_mbist_fail_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_FAIL_BUS_1_tram_mbist_fail_bus_ADDR GPS_L5_SYS_ADRDEC_MBIST_TRAM_FAIL_BUS_1_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_FAIL_BUS_1_tram_mbist_fail_bus_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_FAIL_BUS_1_tram_mbist_fail_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_FAIL_BUS_2_tram_mbist_fail_bus_ADDR GPS_L5_SYS_ADRDEC_MBIST_TRAM_FAIL_BUS_2_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_FAIL_BUS_2_tram_mbist_fail_bus_MASK 0x0000003F
#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_FAIL_BUS_2_tram_mbist_fail_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_RP_FAIL_BUS_0_tram_mbist_rp_fail_bus_ADDR \
	GPS_L5_SYS_ADRDEC_MBIST_TRAM_RP_FAIL_BUS_0_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_RP_FAIL_BUS_0_tram_mbist_rp_fail_bus_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_RP_FAIL_BUS_0_tram_mbist_rp_fail_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_RP_FAIL_BUS_1_tram_mbist_rp_fail_bus_ADDR \
	GPS_L5_SYS_ADRDEC_MBIST_TRAM_RP_FAIL_BUS_1_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_RP_FAIL_BUS_1_tram_mbist_rp_fail_bus_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_RP_FAIL_BUS_1_tram_mbist_rp_fail_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_RP_FAIL_BUS_2_tram_mbist_rp_fail_bus_ADDR \
	GPS_L5_SYS_ADRDEC_MBIST_TRAM_RP_FAIL_BUS_2_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_RP_FAIL_BUS_2_tram_mbist_rp_fail_bus_MASK 0x0000003F
#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_RP_FAIL_BUS_2_tram_mbist_rp_fail_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_RP_OK_BUS_0_tram_mbist_rp_ok_bus_ADDR \
	GPS_L5_SYS_ADRDEC_MBIST_TRAM_RP_OK_BUS_0_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_RP_OK_BUS_0_tram_mbist_rp_ok_bus_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_RP_OK_BUS_0_tram_mbist_rp_ok_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_RP_OK_BUS_1_tram_mbist_rp_ok_bus_ADDR \
	GPS_L5_SYS_ADRDEC_MBIST_TRAM_RP_OK_BUS_1_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_RP_OK_BUS_1_tram_mbist_rp_ok_bus_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_RP_OK_BUS_1_tram_mbist_rp_ok_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_RP_OK_BUS_2_tram_mbist_rp_ok_bus_ADDR \
	GPS_L5_SYS_ADRDEC_MBIST_TRAM_RP_OK_BUS_2_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_RP_OK_BUS_2_tram_mbist_rp_ok_bus_MASK 0x0000003F
#define GPS_L5_SYS_ADRDEC_MBIST_TRAM_RP_OK_BUS_2_tram_mbist_rp_ok_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_PRAM_FAIL_BUS_pram_mbist_fail_bus_ADDR GPS_L5_SYS_ADRDEC_MBIST_PRAM_FAIL_BUS_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_PRAM_FAIL_BUS_pram_mbist_fail_bus_MASK 0x000000FF
#define GPS_L5_SYS_ADRDEC_MBIST_PRAM_FAIL_BUS_pram_mbist_fail_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_PRAM_RP_FAIL_BUS_pram_mbist_rp_fail_bus_ADDR \
	GPS_L5_SYS_ADRDEC_MBIST_PRAM_RP_FAIL_BUS_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_PRAM_RP_FAIL_BUS_pram_mbist_rp_fail_bus_MASK 0x000000FF
#define GPS_L5_SYS_ADRDEC_MBIST_PRAM_RP_FAIL_BUS_pram_mbist_rp_fail_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_PRAM_RP_OKBUS_pram_mbist_rp_ok_bus_ADDR GPS_L5_SYS_ADRDEC_MBIST_PRAM_RP_OKBUS_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_PRAM_RP_OKBUS_pram_mbist_rp_ok_bus_MASK 0x000000FF
#define GPS_L5_SYS_ADRDEC_MBIST_PRAM_RP_OKBUS_pram_mbist_rp_ok_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_XRAM_FAIL_BUS_xram_mbist_fail_bus_ADDR GPS_L5_SYS_ADRDEC_MBIST_XRAM_FAIL_BUS_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_XRAM_FAIL_BUS_xram_mbist_fail_bus_MASK 0x0000000F
#define GPS_L5_SYS_ADRDEC_MBIST_XRAM_FAIL_BUS_xram_mbist_fail_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_XRAM_RP_FAIL_BUS_xram_mbist_rp_fail_bus_ADDR \
	GPS_L5_SYS_ADRDEC_MBIST_XRAM_RP_FAIL_BUS_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_XRAM_RP_FAIL_BUS_xram_mbist_rp_fail_bus_MASK 0x0000000F
#define GPS_L5_SYS_ADRDEC_MBIST_XRAM_RP_FAIL_BUS_xram_mbist_rp_fail_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_XRAM_RP_OKBUS_xram_mbist_rp_ok_bus_ADDR GPS_L5_SYS_ADRDEC_MBIST_XRAM_RP_OKBUS_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_XRAM_RP_OKBUS_xram_mbist_rp_ok_bus_MASK 0x0000000F
#define GPS_L5_SYS_ADRDEC_MBIST_XRAM_RP_OKBUS_xram_mbist_rp_ok_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_YRAM_FAIL_BUS_yram_mbist_fail_bus_ADDR GPS_L5_SYS_ADRDEC_MBIST_YRAM_FAIL_BUS_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_YRAM_FAIL_BUS_yram_mbist_fail_bus_MASK 0x00001FFF
#define GPS_L5_SYS_ADRDEC_MBIST_YRAM_FAIL_BUS_yram_mbist_fail_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_YRAM_RP_FAIL_BUS_yram_mbist_rp_fail_bus_ADDR \
	GPS_L5_SYS_ADRDEC_MBIST_YRAM_RP_FAIL_BUS_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_YRAM_RP_FAIL_BUS_yram_mbist_rp_fail_bus_MASK 0x00001FFF
#define GPS_L5_SYS_ADRDEC_MBIST_YRAM_RP_FAIL_BUS_yram_mbist_rp_fail_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_YRAM_RP_OKBUS_yram_mbist_rp_ok_bus_ADDR GPS_L5_SYS_ADRDEC_MBIST_YRAM_RP_OKBUS_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_YRAM_RP_OKBUS_yram_mbist_rp_ok_bus_MASK 0x00001FFF
#define GPS_L5_SYS_ADRDEC_MBIST_YRAM_RP_OKBUS_yram_mbist_rp_ok_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_URAM_FAIL_BUS_uram_mbist_fail_bus_ADDR GPS_L5_SYS_ADRDEC_MBIST_URAM_FAIL_BUS_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_URAM_FAIL_BUS_uram_mbist_fail_bus_MASK 0x00000003
#define GPS_L5_SYS_ADRDEC_MBIST_URAM_FAIL_BUS_uram_mbist_fail_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_URAM_RP_FAIL_BUS_uram_mbist_rp_fail_bus_ADDR \
	GPS_L5_SYS_ADRDEC_MBIST_URAM_RP_FAIL_BUS_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_URAM_RP_FAIL_BUS_uram_mbist_rp_fail_bus_MASK 0x00000003
#define GPS_L5_SYS_ADRDEC_MBIST_URAM_RP_FAIL_BUS_uram_mbist_rp_fail_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_URAM_RP_OKBUS_uram_mbist_rp_ok_bus_ADDR GPS_L5_SYS_ADRDEC_MBIST_URAM_RP_OKBUS_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_URAM_RP_OKBUS_uram_mbist_rp_ok_bus_MASK 0x00000003
#define GPS_L5_SYS_ADRDEC_MBIST_URAM_RP_OKBUS_uram_mbist_rp_ok_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_FAIL_BUS_0_mram_mbist_fail_bus_ADDR GPS_L5_SYS_ADRDEC_MBIST_MRAM_FAIL_BUS_0_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_FAIL_BUS_0_mram_mbist_fail_bus_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_FAIL_BUS_0_mram_mbist_fail_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_FAIL_BUS_1_mram_mbist_fail_bus_ADDR GPS_L5_SYS_ADRDEC_MBIST_MRAM_FAIL_BUS_1_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_FAIL_BUS_1_mram_mbist_fail_bus_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_FAIL_BUS_1_mram_mbist_fail_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_FAIL_BUS_2_mram_mbist_fail_bus_ADDR GPS_L5_SYS_ADRDEC_MBIST_MRAM_FAIL_BUS_2_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_FAIL_BUS_2_mram_mbist_fail_bus_MASK 0x0000001F
#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_FAIL_BUS_2_mram_mbist_fail_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_RP_FAIL_BUS_0_mram_mbist_rp_fail_bus_ADDR \
	GPS_L5_SYS_ADRDEC_MBIST_MRAM_RP_FAIL_BUS_0_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_RP_FAIL_BUS_0_mram_mbist_rp_fail_bus_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_RP_FAIL_BUS_0_mram_mbist_rp_fail_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_RP_FAIL_BUS_1_mram_mbist_rp_fail_bus_ADDR \
	GPS_L5_SYS_ADRDEC_MBIST_MRAM_RP_FAIL_BUS_1_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_RP_FAIL_BUS_1_mram_mbist_rp_fail_bus_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_RP_FAIL_BUS_1_mram_mbist_rp_fail_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_RP_FAIL_BUS_2_mram_mbist_rp_fail_bus_ADDR \
	GPS_L5_SYS_ADRDEC_MBIST_MRAM_RP_FAIL_BUS_2_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_RP_FAIL_BUS_2_mram_mbist_rp_fail_bus_MASK 0x0000001F
#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_RP_FAIL_BUS_2_mram_mbist_rp_fail_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_RP_OK_BUS_0_mram_mbist_rp_ok_bus_ADDR \
	GPS_L5_SYS_ADRDEC_MBIST_MRAM_RP_OK_BUS_0_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_RP_OK_BUS_0_mram_mbist_rp_ok_bus_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_RP_OK_BUS_0_mram_mbist_rp_ok_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_RP_OK_BUS_1_mram_mbist_rp_ok_bus_ADDR \
	GPS_L5_SYS_ADRDEC_MBIST_MRAM_RP_OK_BUS_1_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_RP_OK_BUS_1_mram_mbist_rp_ok_bus_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_RP_OK_BUS_1_mram_mbist_rp_ok_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_RP_OK_BUS_2_mram_mbist_rp_ok_bus_ADDR \
	GPS_L5_SYS_ADRDEC_MBIST_MRAM_RP_OK_BUS_2_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_RP_OK_BUS_2_mram_mbist_rp_ok_bus_MASK 0x0000001F
#define GPS_L5_SYS_ADRDEC_MBIST_MRAM_RP_OK_BUS_2_mram_mbist_rp_ok_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MEM_MISC_reg_mem_delsel_sel_ADDR     GPS_L5_SYS_ADRDEC_MEM_MISC_ADDR
#define GPS_L5_SYS_ADRDEC_MEM_MISC_reg_mem_delsel_sel_MASK     0x00004000
#define GPS_L5_SYS_ADRDEC_MEM_MISC_reg_mem_delsel_sel_SHFT     14
#define GPS_L5_SYS_ADRDEC_MEM_MISC_reg_dspram_delsel_sel_ADDR  GPS_L5_SYS_ADRDEC_MEM_MISC_ADDR
#define GPS_L5_SYS_ADRDEC_MEM_MISC_reg_dspram_delsel_sel_MASK  0x00002000
#define GPS_L5_SYS_ADRDEC_MEM_MISC_reg_dspram_delsel_sel_SHFT  13
#define GPS_L5_SYS_ADRDEC_MEM_MISC_reg_prom_delsel_sel_ADDR    GPS_L5_SYS_ADRDEC_MEM_MISC_ADDR
#define GPS_L5_SYS_ADRDEC_MEM_MISC_reg_prom_delsel_sel_MASK    0x00001000
#define GPS_L5_SYS_ADRDEC_MEM_MISC_reg_prom_delsel_sel_SHFT    12
#define GPS_L5_SYS_ADRDEC_MEM_MISC_yram_page_jtag_en_ADDR      GPS_L5_SYS_ADRDEC_MEM_MISC_ADDR
#define GPS_L5_SYS_ADRDEC_MEM_MISC_yram_page_jtag_en_MASK      0x00000020
#define GPS_L5_SYS_ADRDEC_MEM_MISC_yram_page_jtag_en_SHFT      5

#define GPS_L5_SYS_ADRDEC_TMBIST_FUSE_SEL_reg_tmbist_fuse_sel_ADDR GPS_L5_SYS_ADRDEC_TMBIST_FUSE_SEL_ADDR
#define GPS_L5_SYS_ADRDEC_TMBIST_FUSE_SEL_reg_tmbist_fuse_sel_MASK 0x00000001
#define GPS_L5_SYS_ADRDEC_TMBIST_FUSE_SEL_reg_tmbist_fuse_sel_SHFT 0

#define GPS_L5_SYS_ADRDEC_BIST_CROM_DOTEST_MRAM_REPAIR_EN_ADDR GPS_L5_SYS_ADRDEC_BIST_CROM_DOTEST_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_CROM_DOTEST_MRAM_REPAIR_EN_MASK 0x0000001F
#define GPS_L5_SYS_ADRDEC_BIST_CROM_DOTEST_MRAM_REPAIR_EN_SHFT 0

#define GPS_L5_SYS_ADRDEC_BIST_GRAM_DOTEST_GRAM_REPAIR_EN_ADDR GPS_L5_SYS_ADRDEC_BIST_GRAM_DOTEST_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_GRAM_DOTEST_GRAM_REPAIR_EN_MASK 0x000001FF
#define GPS_L5_SYS_ADRDEC_BIST_GRAM_DOTEST_GRAM_REPAIR_EN_SHFT 0

#define GPS_L5_SYS_ADRDEC_BIST_TRAM_DOTEST_TRAM_REPAIR_EN_ADDR GPS_L5_SYS_ADRDEC_BIST_TRAM_DOTEST_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_TRAM_DOTEST_TRAM_REPAIR_EN_MASK 0x000007FF
#define GPS_L5_SYS_ADRDEC_BIST_TRAM_DOTEST_TRAM_REPAIR_EN_SHFT 0

#define GPS_L5_SYS_ADRDEC_BIST_MRAM_DOTEST_MRAM_REPAIR_EN_ADDR GPS_L5_SYS_ADRDEC_BIST_MRAM_DOTEST_ADDR
#define GPS_L5_SYS_ADRDEC_BIST_MRAM_DOTEST_MRAM_REPAIR_EN_MASK 0x000007FF
#define GPS_L5_SYS_ADRDEC_BIST_MRAM_DOTEST_MRAM_REPAIR_EN_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_SHARE_FAIL_BUS_share_mbist_fail_bus_ADDR GPS_L5_SYS_ADRDEC_MBIST_SHARE_FAIL_BUS_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SHARE_FAIL_BUS_share_mbist_fail_bus_MASK 0x00000001
#define GPS_L5_SYS_ADRDEC_MBIST_SHARE_FAIL_BUS_share_mbist_fail_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_SHARE_RP_FAIL_BUS_share_mbist_rp_fail_bus_ADDR \
	GPS_L5_SYS_ADRDEC_MBIST_SHARE_RP_FAIL_BUS_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SHARE_RP_FAIL_BUS_share_mbist_rp_fail_bus_MASK 0x00000001
#define GPS_L5_SYS_ADRDEC_MBIST_SHARE_RP_FAIL_BUS_share_mbist_rp_fail_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_SHARE_RP_OKBUS_share_mbist_rp_ok_bus_ADDR GPS_L5_SYS_ADRDEC_MBIST_SHARE_RP_OKBUS_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SHARE_RP_OKBUS_share_mbist_rp_ok_bus_MASK 0x00000001
#define GPS_L5_SYS_ADRDEC_MBIST_SHARE_RP_OKBUS_share_mbist_rp_ok_bus_SHFT 0

#define GPS_L5_SYS_ADRDEC_SHARE_MISC_share_clk_sw_ADDR         GPS_L5_SYS_ADRDEC_SHARE_MISC_ADDR
#define GPS_L5_SYS_ADRDEC_SHARE_MISC_share_clk_sw_MASK         0x00000001
#define GPS_L5_SYS_ADRDEC_SHARE_MISC_share_clk_sw_SHFT         0

#define GPS_L5_SYS_ADRDEC_ANACTL_0_GPS_ADCKSEL_ADDR            GPS_L5_SYS_ADRDEC_ANACTL_0_ADDR
#define GPS_L5_SYS_ADRDEC_ANACTL_0_GPS_ADCKSEL_MASK            0x00008000
#define GPS_L5_SYS_ADRDEC_ANACTL_0_GPS_ADCKSEL_SHFT            15
#define GPS_L5_SYS_ADRDEC_ANACTL_0_ADC_PATH_SEL_ADDR           GPS_L5_SYS_ADRDEC_ANACTL_0_ADDR
#define GPS_L5_SYS_ADRDEC_ANACTL_0_ADC_PATH_SEL_MASK           0x00000010
#define GPS_L5_SYS_ADRDEC_ANACTL_0_ADC_PATH_SEL_SHFT           4
#define GPS_L5_SYS_ADRDEC_ANACTL_0_GPS_EN_DIGCK_ADDR           GPS_L5_SYS_ADRDEC_ANACTL_0_ADDR
#define GPS_L5_SYS_ADRDEC_ANACTL_0_GPS_EN_DIGCK_MASK           0x00000004
#define GPS_L5_SYS_ADRDEC_ANACTL_0_GPS_EN_DIGCK_SHFT           2
#define GPS_L5_SYS_ADRDEC_ANACTL_0_GPS_EN_GAD_REF_ADDR         GPS_L5_SYS_ADRDEC_ANACTL_0_ADDR
#define GPS_L5_SYS_ADRDEC_ANACTL_0_GPS_EN_GAD_REF_MASK         0x00000002
#define GPS_L5_SYS_ADRDEC_ANACTL_0_GPS_EN_GAD_REF_SHFT         1
#define GPS_L5_SYS_ADRDEC_ANACTL_0_GPS_EN_GAD_ADDR             GPS_L5_SYS_ADRDEC_ANACTL_0_ADDR
#define GPS_L5_SYS_ADRDEC_ANACTL_0_GPS_EN_GAD_MASK             0x00000001
#define GPS_L5_SYS_ADRDEC_ANACTL_0_GPS_EN_GAD_SHFT             0

#define GPS_L5_SYS_ADRDEC_ANACTL_1_rst_by_self_ADDR            GPS_L5_SYS_ADRDEC_ANACTL_1_ADDR
#define GPS_L5_SYS_ADRDEC_ANACTL_1_rst_by_self_MASK            0x00000100
#define GPS_L5_SYS_ADRDEC_ANACTL_1_rst_by_self_SHFT            8
#define GPS_L5_SYS_ADRDEC_ANACTL_1_gps_apsrc_ack_ADDR          GPS_L5_SYS_ADRDEC_ANACTL_1_ADDR
#define GPS_L5_SYS_ADRDEC_ANACTL_1_gps_apsrc_ack_MASK          0x00000002
#define GPS_L5_SYS_ADRDEC_ANACTL_1_gps_apsrc_ack_SHFT          1
#define GPS_L5_SYS_ADRDEC_ANACTL_1_gps_apsrc_req_ADDR          GPS_L5_SYS_ADRDEC_ANACTL_1_ADDR
#define GPS_L5_SYS_ADRDEC_ANACTL_1_gps_apsrc_req_MASK          0x00000001
#define GPS_L5_SYS_ADRDEC_ANACTL_1_gps_apsrc_req_SHFT          0

#define GPS_L5_SYS_ADRDEC_RFCTL_0_GPS_RF_EN_0_ADDR             GPS_L5_SYS_ADRDEC_RFCTL_0_ADDR
#define GPS_L5_SYS_ADRDEC_RFCTL_0_GPS_RF_EN_0_MASK             0x00008000
#define GPS_L5_SYS_ADRDEC_RFCTL_0_GPS_RF_EN_0_SHFT             15
#define GPS_L5_SYS_ADRDEC_RFCTL_0_GPS_IF_SEL_ADDR              GPS_L5_SYS_ADRDEC_RFCTL_0_ADDR
#define GPS_L5_SYS_ADRDEC_RFCTL_0_GPS_IF_SEL_MASK              0x00004000
#define GPS_L5_SYS_ADRDEC_RFCTL_0_GPS_IF_SEL_SHFT              14
#define GPS_L5_SYS_ADRDEC_RFCTL_0_GPS_L1L5_SEL_ADDR            GPS_L5_SYS_ADRDEC_RFCTL_0_ADDR
#define GPS_L5_SYS_ADRDEC_RFCTL_0_GPS_L1L5_SEL_MASK            0x00000800
#define GPS_L5_SYS_ADRDEC_RFCTL_0_GPS_L1L5_SEL_SHFT            11
#define GPS_L5_SYS_ADRDEC_RFCTL_0_GPS_RF_EN_1_ADDR             GPS_L5_SYS_ADRDEC_RFCTL_0_ADDR
#define GPS_L5_SYS_ADRDEC_RFCTL_0_GPS_RF_EN_1_MASK             0x00000400
#define GPS_L5_SYS_ADRDEC_RFCTL_0_GPS_RF_EN_1_SHFT             10
#define GPS_L5_SYS_ADRDEC_RFCTL_0_GPS_RF_EN_L5_0_ADDR          GPS_L5_SYS_ADRDEC_RFCTL_0_ADDR
#define GPS_L5_SYS_ADRDEC_RFCTL_0_GPS_RF_EN_L5_0_MASK          0x00000080
#define GPS_L5_SYS_ADRDEC_RFCTL_0_GPS_RF_EN_L5_0_SHFT          7
#define GPS_L5_SYS_ADRDEC_RFCTL_0_GPS_RF_EN_L5_1_ADDR          GPS_L5_SYS_ADRDEC_RFCTL_0_ADDR
#define GPS_L5_SYS_ADRDEC_RFCTL_0_GPS_RF_EN_L5_1_MASK          0x00000040
#define GPS_L5_SYS_ADRDEC_RFCTL_0_GPS_RF_EN_L5_1_SHFT          6
#define GPS_L5_SYS_ADRDEC_RFCTL_0_GPS_OSC_EN_ADDR              GPS_L5_SYS_ADRDEC_RFCTL_0_ADDR
#define GPS_L5_SYS_ADRDEC_RFCTL_0_GPS_OSC_EN_MASK              0x00000020
#define GPS_L5_SYS_ADRDEC_RFCTL_0_GPS_OSC_EN_SHFT              5

#define GPS_L5_SYS_ADRDEC_RFCTL_1_GPS_THERM_EN_ADDR            GPS_L5_SYS_ADRDEC_RFCTL_1_ADDR
#define GPS_L5_SYS_ADRDEC_RFCTL_1_GPS_THERM_EN_MASK            0x00008000
#define GPS_L5_SYS_ADRDEC_RFCTL_1_GPS_THERM_EN_SHFT            15
#define GPS_L5_SYS_ADRDEC_RFCTL_1_RF_CTL_1_ADDR                GPS_L5_SYS_ADRDEC_RFCTL_1_ADDR
#define GPS_L5_SYS_ADRDEC_RFCTL_1_RF_CTL_1_MASK                0x00007F00
#define GPS_L5_SYS_ADRDEC_RFCTL_1_RF_CTL_1_SHFT                8
#define GPS_L5_SYS_ADRDEC_RFCTL_1_GPS_THERM_DATA_ADDR          GPS_L5_SYS_ADRDEC_RFCTL_1_ADDR
#define GPS_L5_SYS_ADRDEC_RFCTL_1_GPS_THERM_DATA_MASK          0x000000FE
#define GPS_L5_SYS_ADRDEC_RFCTL_1_GPS_THERM_DATA_SHFT          1
#define GPS_L5_SYS_ADRDEC_RFCTL_1_GPS_THERM_RDY_ADDR           GPS_L5_SYS_ADRDEC_RFCTL_1_ADDR
#define GPS_L5_SYS_ADRDEC_RFCTL_1_GPS_THERM_RDY_MASK           0x00000001
#define GPS_L5_SYS_ADRDEC_RFCTL_1_GPS_THERM_RDY_SHFT           0

#define GPS_L5_SYS_ADRDEC_RFCTL_2_RF_EN_BUSY_ADDR              GPS_L5_SYS_ADRDEC_RFCTL_2_ADDR
#define GPS_L5_SYS_ADRDEC_RFCTL_2_RF_EN_BUSY_MASK              0x00008000
#define GPS_L5_SYS_ADRDEC_RFCTL_2_RF_EN_BUSY_SHFT              15

#define GPS_L5_SYS_ADRDEC_RFCTL_3_gps_vco_rdy_ADDR             GPS_L5_SYS_ADRDEC_RFCTL_3_ADDR
#define GPS_L5_SYS_ADRDEC_RFCTL_3_gps_vco_rdy_MASK             0x00008000
#define GPS_L5_SYS_ADRDEC_RFCTL_3_gps_vco_rdy_SHFT             15
#define GPS_L5_SYS_ADRDEC_RFCTL_3_elna_en_ADDR                 GPS_L5_SYS_ADRDEC_RFCTL_3_ADDR
#define GPS_L5_SYS_ADRDEC_RFCTL_3_elna_en_MASK                 0x00000001
#define GPS_L5_SYS_ADRDEC_RFCTL_3_elna_en_SHFT                 0

#define GPS_L5_SYS_ADRDEC_MBIST_SLP0_uram_sleep_test_ADDR      GPS_L5_SYS_ADRDEC_MBIST_SLP0_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP0_uram_sleep_test_MASK      0x00002000
#define GPS_L5_SYS_ADRDEC_MBIST_SLP0_uram_sleep_test_SHFT      13
#define GPS_L5_SYS_ADRDEC_MBIST_SLP0_uram_sleep_inv_ADDR       GPS_L5_SYS_ADRDEC_MBIST_SLP0_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP0_uram_sleep_inv_MASK       0x00001000
#define GPS_L5_SYS_ADRDEC_MBIST_SLP0_uram_sleep_inv_SHFT       12
#define GPS_L5_SYS_ADRDEC_MBIST_SLP0_uram_sleep_w_ADDR         GPS_L5_SYS_ADRDEC_MBIST_SLP0_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP0_uram_sleep_w_MASK         0x00000800
#define GPS_L5_SYS_ADRDEC_MBIST_SLP0_uram_sleep_w_SHFT         11
#define GPS_L5_SYS_ADRDEC_MBIST_SLP0_uram_sleep_r_ADDR         GPS_L5_SYS_ADRDEC_MBIST_SLP0_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP0_uram_sleep_r_MASK         0x00000400
#define GPS_L5_SYS_ADRDEC_MBIST_SLP0_uram_sleep_r_SHFT         10
#define GPS_L5_SYS_ADRDEC_MBIST_SLP0_pram_0_mbist_debug_ADDR   GPS_L5_SYS_ADRDEC_MBIST_SLP0_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP0_pram_0_mbist_debug_MASK   0x00000040
#define GPS_L5_SYS_ADRDEC_MBIST_SLP0_pram_0_mbist_debug_SHFT   6
#define GPS_L5_SYS_ADRDEC_MBIST_SLP0_pram_0_sleep_test_ADDR    GPS_L5_SYS_ADRDEC_MBIST_SLP0_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP0_pram_0_sleep_test_MASK    0x00000020
#define GPS_L5_SYS_ADRDEC_MBIST_SLP0_pram_0_sleep_test_SHFT    5
#define GPS_L5_SYS_ADRDEC_MBIST_SLP0_pram_0_sleep_inv_ADDR     GPS_L5_SYS_ADRDEC_MBIST_SLP0_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP0_pram_0_sleep_inv_MASK     0x00000010
#define GPS_L5_SYS_ADRDEC_MBIST_SLP0_pram_0_sleep_inv_SHFT     4
#define GPS_L5_SYS_ADRDEC_MBIST_SLP0_pram_0_sleep_w_ADDR       GPS_L5_SYS_ADRDEC_MBIST_SLP0_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP0_pram_0_sleep_w_MASK       0x00000008
#define GPS_L5_SYS_ADRDEC_MBIST_SLP0_pram_0_sleep_w_SHFT       3
#define GPS_L5_SYS_ADRDEC_MBIST_SLP0_pram_0_sleep_r_ADDR       GPS_L5_SYS_ADRDEC_MBIST_SLP0_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP0_pram_0_sleep_r_MASK       0x00000004
#define GPS_L5_SYS_ADRDEC_MBIST_SLP0_pram_0_sleep_r_SHFT       2

#define GPS_L5_SYS_ADRDEC_MBIST_SLP1_xram_mbist_debug_ADDR     GPS_L5_SYS_ADRDEC_MBIST_SLP1_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP1_xram_mbist_debug_MASK     0x00004000
#define GPS_L5_SYS_ADRDEC_MBIST_SLP1_xram_mbist_debug_SHFT     14
#define GPS_L5_SYS_ADRDEC_MBIST_SLP1_xram_sleep_test_ADDR      GPS_L5_SYS_ADRDEC_MBIST_SLP1_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP1_xram_sleep_test_MASK      0x00002000
#define GPS_L5_SYS_ADRDEC_MBIST_SLP1_xram_sleep_test_SHFT      13
#define GPS_L5_SYS_ADRDEC_MBIST_SLP1_xram_sleep_inv_ADDR       GPS_L5_SYS_ADRDEC_MBIST_SLP1_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP1_xram_sleep_inv_MASK       0x00001000
#define GPS_L5_SYS_ADRDEC_MBIST_SLP1_xram_sleep_inv_SHFT       12
#define GPS_L5_SYS_ADRDEC_MBIST_SLP1_xram_sleep_w_ADDR         GPS_L5_SYS_ADRDEC_MBIST_SLP1_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP1_xram_sleep_w_MASK         0x00000800
#define GPS_L5_SYS_ADRDEC_MBIST_SLP1_xram_sleep_w_SHFT         11
#define GPS_L5_SYS_ADRDEC_MBIST_SLP1_xram_sleep_r_ADDR         GPS_L5_SYS_ADRDEC_MBIST_SLP1_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP1_xram_sleep_r_MASK         0x00000400
#define GPS_L5_SYS_ADRDEC_MBIST_SLP1_xram_sleep_r_SHFT         10
#define GPS_L5_SYS_ADRDEC_MBIST_SLP1_yram_0_mbist_debug_ADDR   GPS_L5_SYS_ADRDEC_MBIST_SLP1_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP1_yram_0_mbist_debug_MASK   0x00000040
#define GPS_L5_SYS_ADRDEC_MBIST_SLP1_yram_0_mbist_debug_SHFT   6
#define GPS_L5_SYS_ADRDEC_MBIST_SLP1_yram_0_sleep_test_ADDR    GPS_L5_SYS_ADRDEC_MBIST_SLP1_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP1_yram_0_sleep_test_MASK    0x00000020
#define GPS_L5_SYS_ADRDEC_MBIST_SLP1_yram_0_sleep_test_SHFT    5
#define GPS_L5_SYS_ADRDEC_MBIST_SLP1_yram_0_sleep_inv_ADDR     GPS_L5_SYS_ADRDEC_MBIST_SLP1_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP1_yram_0_sleep_inv_MASK     0x00000010
#define GPS_L5_SYS_ADRDEC_MBIST_SLP1_yram_0_sleep_inv_SHFT     4
#define GPS_L5_SYS_ADRDEC_MBIST_SLP1_yram_0_sleep_w_ADDR       GPS_L5_SYS_ADRDEC_MBIST_SLP1_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP1_yram_0_sleep_w_MASK       0x00000008
#define GPS_L5_SYS_ADRDEC_MBIST_SLP1_yram_0_sleep_w_SHFT       3
#define GPS_L5_SYS_ADRDEC_MBIST_SLP1_yram_0_sleep_r_ADDR       GPS_L5_SYS_ADRDEC_MBIST_SLP1_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP1_yram_0_sleep_r_MASK       0x00000004
#define GPS_L5_SYS_ADRDEC_MBIST_SLP1_yram_0_sleep_r_SHFT       2

#define GPS_L5_SYS_ADRDEC_MBIST_SLP2_share_mbist_debug_ADDR    GPS_L5_SYS_ADRDEC_MBIST_SLP2_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP2_share_mbist_debug_MASK    0x00004000
#define GPS_L5_SYS_ADRDEC_MBIST_SLP2_share_mbist_debug_SHFT    14
#define GPS_L5_SYS_ADRDEC_MBIST_SLP2_share_sleep_test_ADDR     GPS_L5_SYS_ADRDEC_MBIST_SLP2_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP2_share_sleep_test_MASK     0x00002000
#define GPS_L5_SYS_ADRDEC_MBIST_SLP2_share_sleep_test_SHFT     13
#define GPS_L5_SYS_ADRDEC_MBIST_SLP2_share_sleep_inv_ADDR      GPS_L5_SYS_ADRDEC_MBIST_SLP2_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP2_share_sleep_inv_MASK      0x00001000
#define GPS_L5_SYS_ADRDEC_MBIST_SLP2_share_sleep_inv_SHFT      12
#define GPS_L5_SYS_ADRDEC_MBIST_SLP2_share_sleep_w_ADDR        GPS_L5_SYS_ADRDEC_MBIST_SLP2_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP2_share_sleep_w_MASK        0x00000800
#define GPS_L5_SYS_ADRDEC_MBIST_SLP2_share_sleep_w_SHFT        11
#define GPS_L5_SYS_ADRDEC_MBIST_SLP2_share_sleep_r_ADDR        GPS_L5_SYS_ADRDEC_MBIST_SLP2_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP2_share_sleep_r_MASK        0x00000400
#define GPS_L5_SYS_ADRDEC_MBIST_SLP2_share_sleep_r_SHFT        10
#define GPS_L5_SYS_ADRDEC_MBIST_SLP2_yram_1_mbist_debug_ADDR   GPS_L5_SYS_ADRDEC_MBIST_SLP2_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP2_yram_1_mbist_debug_MASK   0x00000040
#define GPS_L5_SYS_ADRDEC_MBIST_SLP2_yram_1_mbist_debug_SHFT   6
#define GPS_L5_SYS_ADRDEC_MBIST_SLP2_yram_1_sleep_test_ADDR    GPS_L5_SYS_ADRDEC_MBIST_SLP2_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP2_yram_1_sleep_test_MASK    0x00000020
#define GPS_L5_SYS_ADRDEC_MBIST_SLP2_yram_1_sleep_test_SHFT    5
#define GPS_L5_SYS_ADRDEC_MBIST_SLP2_yram_1_sleep_inv_ADDR     GPS_L5_SYS_ADRDEC_MBIST_SLP2_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP2_yram_1_sleep_inv_MASK     0x00000010
#define GPS_L5_SYS_ADRDEC_MBIST_SLP2_yram_1_sleep_inv_SHFT     4
#define GPS_L5_SYS_ADRDEC_MBIST_SLP2_yram_1_sleep_w_ADDR       GPS_L5_SYS_ADRDEC_MBIST_SLP2_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP2_yram_1_sleep_w_MASK       0x00000008
#define GPS_L5_SYS_ADRDEC_MBIST_SLP2_yram_1_sleep_w_SHFT       3
#define GPS_L5_SYS_ADRDEC_MBIST_SLP2_yram_1_sleep_r_ADDR       GPS_L5_SYS_ADRDEC_MBIST_SLP2_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP2_yram_1_sleep_r_MASK       0x00000004
#define GPS_L5_SYS_ADRDEC_MBIST_SLP2_yram_1_sleep_r_SHFT       2

#define GPS_L5_SYS_ADRDEC_MBIST_SLP3_share_mbist_debug_ADDR    GPS_L5_SYS_ADRDEC_MBIST_SLP3_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP3_share_mbist_debug_MASK    0x00004000
#define GPS_L5_SYS_ADRDEC_MBIST_SLP3_share_mbist_debug_SHFT    14
#define GPS_L5_SYS_ADRDEC_MBIST_SLP3_share_sleep_test_ADDR     GPS_L5_SYS_ADRDEC_MBIST_SLP3_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP3_share_sleep_test_MASK     0x00002000
#define GPS_L5_SYS_ADRDEC_MBIST_SLP3_share_sleep_test_SHFT     13
#define GPS_L5_SYS_ADRDEC_MBIST_SLP3_share_sleep_inv_ADDR      GPS_L5_SYS_ADRDEC_MBIST_SLP3_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP3_share_sleep_inv_MASK      0x00001000
#define GPS_L5_SYS_ADRDEC_MBIST_SLP3_share_sleep_inv_SHFT      12
#define GPS_L5_SYS_ADRDEC_MBIST_SLP3_share_sleep_w_ADDR        GPS_L5_SYS_ADRDEC_MBIST_SLP3_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP3_share_sleep_w_MASK        0x00000800
#define GPS_L5_SYS_ADRDEC_MBIST_SLP3_share_sleep_w_SHFT        11
#define GPS_L5_SYS_ADRDEC_MBIST_SLP3_share_sleep_r_ADDR        GPS_L5_SYS_ADRDEC_MBIST_SLP3_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP3_share_sleep_r_MASK        0x00000400
#define GPS_L5_SYS_ADRDEC_MBIST_SLP3_share_sleep_r_SHFT        10
#define GPS_L5_SYS_ADRDEC_MBIST_SLP3_pram_1_mbist_debug_ADDR   GPS_L5_SYS_ADRDEC_MBIST_SLP3_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP3_pram_1_mbist_debug_MASK   0x00000040
#define GPS_L5_SYS_ADRDEC_MBIST_SLP3_pram_1_mbist_debug_SHFT   6
#define GPS_L5_SYS_ADRDEC_MBIST_SLP3_pram_1_sleep_test_ADDR    GPS_L5_SYS_ADRDEC_MBIST_SLP3_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP3_pram_1_sleep_test_MASK    0x00000020
#define GPS_L5_SYS_ADRDEC_MBIST_SLP3_pram_1_sleep_test_SHFT    5
#define GPS_L5_SYS_ADRDEC_MBIST_SLP3_pram_1_sleep_inv_ADDR     GPS_L5_SYS_ADRDEC_MBIST_SLP3_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP3_pram_1_sleep_inv_MASK     0x00000010
#define GPS_L5_SYS_ADRDEC_MBIST_SLP3_pram_1_sleep_inv_SHFT     4
#define GPS_L5_SYS_ADRDEC_MBIST_SLP3_pram_1_sleep_w_ADDR       GPS_L5_SYS_ADRDEC_MBIST_SLP3_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP3_pram_1_sleep_w_MASK       0x00000008
#define GPS_L5_SYS_ADRDEC_MBIST_SLP3_pram_1_sleep_w_SHFT       3
#define GPS_L5_SYS_ADRDEC_MBIST_SLP3_pram_1_sleep_r_ADDR       GPS_L5_SYS_ADRDEC_MBIST_SLP3_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_SLP3_pram_1_sleep_r_MASK       0x00000004
#define GPS_L5_SYS_ADRDEC_MBIST_SLP3_pram_1_sleep_r_SHFT       2

#define GPS_L5_SYS_ADRDEC_PROM_SIGNATURE_0_prom_signature_0_ADDR GPS_L5_SYS_ADRDEC_PROM_SIGNATURE_0_ADDR
#define GPS_L5_SYS_ADRDEC_PROM_SIGNATURE_0_prom_signature_0_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_PROM_SIGNATURE_0_prom_signature_0_SHFT 0

#define GPS_L5_SYS_ADRDEC_PROM_SIGNATURE_1_prom_signature_1_ADDR GPS_L5_SYS_ADRDEC_PROM_SIGNATURE_1_ADDR
#define GPS_L5_SYS_ADRDEC_PROM_SIGNATURE_1_prom_signature_1_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_PROM_SIGNATURE_1_prom_signature_1_SHFT 0

#define GPS_L5_SYS_ADRDEC_CROM_SIGNATURE_L_0_crom_signature_l_0_ADDR GPS_L5_SYS_ADRDEC_CROM_SIGNATURE_L_0_ADDR
#define GPS_L5_SYS_ADRDEC_CROM_SIGNATURE_L_0_crom_signature_l_0_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_CROM_SIGNATURE_L_0_crom_signature_l_0_SHFT 0

#define GPS_L5_SYS_ADRDEC_CROM_SIGNATURE_L_1_crom_signature_l_1_ADDR GPS_L5_SYS_ADRDEC_CROM_SIGNATURE_L_1_ADDR
#define GPS_L5_SYS_ADRDEC_CROM_SIGNATURE_L_1_crom_signature_l_1_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_CROM_SIGNATURE_L_1_crom_signature_l_1_SHFT 0

#define GPS_L5_SYS_ADRDEC_CROM_SIGNATURE_H_0_crom_signature_h_0_ADDR GPS_L5_SYS_ADRDEC_CROM_SIGNATURE_H_0_ADDR
#define GPS_L5_SYS_ADRDEC_CROM_SIGNATURE_H_0_crom_signature_h_0_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_CROM_SIGNATURE_H_0_crom_signature_h_0_SHFT 0

#define GPS_L5_SYS_ADRDEC_CROM_SIGNATURE_H_1_crom_signature_h_1_ADDR GPS_L5_SYS_ADRDEC_CROM_SIGNATURE_H_1_ADDR
#define GPS_L5_SYS_ADRDEC_CROM_SIGNATURE_H_1_crom_signature_h_1_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_CROM_SIGNATURE_H_1_crom_signature_h_1_SHFT 0

#define GPS_L5_SYS_ADRDEC_MBIST_DIAG_SEL_gpssys_mbsit_diag_sel_ADDR GPS_L5_SYS_ADRDEC_MBIST_DIAG_SEL_ADDR
#define GPS_L5_SYS_ADRDEC_MBIST_DIAG_SEL_gpssys_mbsit_diag_sel_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_MBIST_DIAG_SEL_gpssys_mbsit_diag_sel_SHFT 0

#define GPS_L5_SYS_ADRDEC_PROM_SIGNATURE_2_prom_signature_2_ADDR GPS_L5_SYS_ADRDEC_PROM_SIGNATURE_2_ADDR
#define GPS_L5_SYS_ADRDEC_PROM_SIGNATURE_2_prom_signature_2_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_PROM_SIGNATURE_2_prom_signature_2_SHFT 0

#define GPS_L5_SYS_ADRDEC_PROM_SIGNATURE_3_prom_signature_3_ADDR GPS_L5_SYS_ADRDEC_PROM_SIGNATURE_3_ADDR
#define GPS_L5_SYS_ADRDEC_PROM_SIGNATURE_3_prom_signature_3_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_PROM_SIGNATURE_3_prom_signature_3_SHFT 0

#define GPS_L5_SYS_ADRDEC_DELSEL0_H_CH0_FTRAM_DELSEL_H_ADDR    GPS_L5_SYS_ADRDEC_DELSEL0_H_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL0_H_CH0_FTRAM_DELSEL_H_MASK    0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL0_H_CH0_FTRAM_DELSEL_H_SHFT    0

#define GPS_L5_SYS_ADRDEC_DELSEL1_H_CH1_FTRAM_DELSEL_H_ADDR    GPS_L5_SYS_ADRDEC_DELSEL1_H_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL1_H_CH1_FTRAM_DELSEL_H_MASK    0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL1_H_CH1_FTRAM_DELSEL_H_SHFT    0

#define GPS_L5_SYS_ADRDEC_DELSEL2_H_CH0_SPRAM_DELSEL_H_ADDR    GPS_L5_SYS_ADRDEC_DELSEL2_H_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL2_H_CH0_SPRAM_DELSEL_H_MASK    0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL2_H_CH0_SPRAM_DELSEL_H_SHFT    0

#define GPS_L5_SYS_ADRDEC_DELSEL3_H_CH1_SPRAM_DELSEL_H_ADDR    GPS_L5_SYS_ADRDEC_DELSEL3_H_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL3_H_CH1_SPRAM_DELSEL_H_MASK    0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL3_H_CH1_SPRAM_DELSEL_H_SHFT    0

#define GPS_L5_SYS_ADRDEC_DELSEL4_H_GRAM_DELSEL_H_ADDR         GPS_L5_SYS_ADRDEC_DELSEL4_H_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL4_H_GRAM_DELSEL_H_MASK         0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL4_H_GRAM_DELSEL_H_SHFT         0

#define GPS_L5_SYS_ADRDEC_DELSEL5_H_TRAM_DELSEL_1KX64_H_ADDR   GPS_L5_SYS_ADRDEC_DELSEL5_H_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL5_H_TRAM_DELSEL_1KX64_H_MASK   0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL5_H_TRAM_DELSEL_1KX64_H_SHFT   0

#define GPS_L5_SYS_ADRDEC_DELSEL6_H_MRAM_DELSEL_1KX32_H_ADDR   GPS_L5_SYS_ADRDEC_DELSEL6_H_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL6_H_MRAM_DELSEL_1KX32_H_MASK   0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL6_H_MRAM_DELSEL_1KX32_H_SHFT   0

#define GPS_L5_SYS_ADRDEC_DELSEL7_H_MRAM_DELSEL_1KX64_H_ADDR   GPS_L5_SYS_ADRDEC_DELSEL7_H_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL7_H_MRAM_DELSEL_1KX64_H_MASK   0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL7_H_MRAM_DELSEL_1KX64_H_SHFT   0

#define GPS_L5_SYS_ADRDEC_DELSEL8_H_URAM_DELSEL_H_ADDR         GPS_L5_SYS_ADRDEC_DELSEL8_H_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL8_H_URAM_DELSEL_H_MASK         0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL8_H_URAM_DELSEL_H_SHFT         0

#define GPS_L5_SYS_ADRDEC_DELSEL9_H_YRAM_1KX16_DELSEL_H_ADDR   GPS_L5_SYS_ADRDEC_DELSEL9_H_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL9_H_YRAM_1KX16_DELSEL_H_MASK   0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL9_H_YRAM_1KX16_DELSEL_H_SHFT   0

#define GPS_L5_SYS_ADRDEC_DELSEL10_H_DSPRAM_4KX16_DELSEL_H_ADDR GPS_L5_SYS_ADRDEC_DELSEL10_H_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL10_H_DSPRAM_4KX16_DELSEL_H_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL10_H_DSPRAM_4KX16_DELSEL_H_SHFT 0

#define GPS_L5_SYS_ADRDEC_DELSEL11_H_DSPRAM_3328X16_DELSEL_H_ADDR GPS_L5_SYS_ADRDEC_DELSEL11_H_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL11_H_DSPRAM_3328X16_DELSEL_H_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL11_H_DSPRAM_3328X16_DELSEL_H_SHFT 0

#define GPS_L5_SYS_ADRDEC_DELSEL12_H_DSPRAM_3584X16_DELSEL_H_ADDR GPS_L5_SYS_ADRDEC_DELSEL12_H_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL12_H_DSPRAM_3584X16_DELSEL_H_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL12_H_DSPRAM_3584X16_DELSEL_H_SHFT 0

#define GPS_L5_SYS_ADRDEC_DELSEL13_H_TRAM_DELSEL_1KX128_H_ADDR GPS_L5_SYS_ADRDEC_DELSEL13_H_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL13_H_TRAM_DELSEL_1KX128_H_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL13_H_TRAM_DELSEL_1KX128_H_SHFT 0

#define GPS_L5_SYS_ADRDEC_DELSEL14_H_TRAM_DELSEL_512X64_H_ADDR GPS_L5_SYS_ADRDEC_DELSEL14_H_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL14_H_TRAM_DELSEL_512X64_H_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL14_H_TRAM_DELSEL_512X64_H_SHFT 0

#define GPS_L5_SYS_ADRDEC_DELSEL15_H_MRAM_DELSEL_512X32_H_ADDR GPS_L5_SYS_ADRDEC_DELSEL15_H_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL15_H_MRAM_DELSEL_512X32_H_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL15_H_MRAM_DELSEL_512X32_H_SHFT 0

#define GPS_L5_SYS_ADRDEC_DELSEL16_H_PROM_DELSEL_8KX16_H_ADDR  GPS_L5_SYS_ADRDEC_DELSEL16_H_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL16_H_PROM_DELSEL_8KX16_H_MASK  0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL16_H_PROM_DELSEL_8KX16_H_SHFT  0

#define GPS_L5_SYS_ADRDEC_DELSEL17_H_CROM_DELSEL_6656X32_H_ADDR GPS_L5_SYS_ADRDEC_DELSEL17_H_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL17_H_CROM_DELSEL_6656X32_H_MASK 0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL17_H_CROM_DELSEL_6656X32_H_SHFT 0

#define GPS_L5_SYS_ADRDEC_DELSEL18_L_SHARE_4KX8_L_ADDR         GPS_L5_SYS_ADRDEC_DELSEL18_L_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL18_L_SHARE_4KX8_L_MASK         0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL18_L_SHARE_4KX8_L_SHFT         0

#define GPS_L5_SYS_ADRDEC_DELSEL18_H_SHARE_4KX8_H_ADDR         GPS_L5_SYS_ADRDEC_DELSEL18_H_ADDR
#define GPS_L5_SYS_ADRDEC_DELSEL18_H_SHARE_4KX8_H_MASK         0x0000FFFF
#define GPS_L5_SYS_ADRDEC_DELSEL18_H_SHARE_4KX8_H_SHFT         0

#endif /* __GPS_L5_SYS_ADRDEC_REGS_H__ */

