# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2021 MediaTek Inc.

obj-$(CONFIG_MTK_V4L2_IMGSENSOR) += imgsensor-glue_isp8.o

imgsensor-glue_isp8-objs :=
imgsensor-glue_isp8-objs += \
	imgsensor-glue.o \

$(info imgsensor-virt-sensor-objs : $(obj-$(CONFIG_MTK_V4L2_IMGSENSOR)))
