/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2021 MediaTek Inc.
 */
//[File]            : conn_bus_cr_on.h
//[Revision time]   : Tue Jun 22 15:58:07 2021

#ifndef __CONN_BUS_CR_ON_REGS_H__
#define __CONN_BUS_CR_ON_REGS_H__

//****************************************************************************
//
//                     CONN_BUS_CR_ON CR Definitions                     
//
//****************************************************************************

#define CONN_BUS_CR_ON_BASE                                    (CONN_REG_CONN_INFRA_BUS_CR_ON_ADDR)

#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_IDLE_CTRL_0_ADDR     (CONN_BUS_CR_ON_BASE + 0x000) // E000
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_IDLE_CTRL_1_ADDR     (CONN_BUS_CR_ON_BASE + 0x004) // E004
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_STATUS_ADDR  (CONN_BUS_CR_ON_BASE + 0x020) // E020
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_ADDR    (CONN_BUS_CR_ON_BASE + 0x024) // E024
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_0_ADDR (CONN_BUS_CR_ON_BASE + 0x028) // E028
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_1_ADDR (CONN_BUS_CR_ON_BASE + 0x02C) // E02C
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_2_ADDR (CONN_BUS_CR_ON_BASE + 0x030) // E030
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_STATUS_ADDR   (CONN_BUS_CR_ON_BASE + 0x034) // E034
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_ADDR     (CONN_BUS_CR_ON_BASE + 0x038) // E038
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_0_ADDR (CONN_BUS_CR_ON_BASE + 0x03C) // E03C
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_1_ADDR (CONN_BUS_CR_ON_BASE + 0x040) // E040
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_2_ADDR (CONN_BUS_CR_ON_BASE + 0x044) // E044
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_DOMAIN_ID_ADDR            (CONN_BUS_CR_ON_BASE + 0x050) // E050
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_0_ADDR                    (CONN_BUS_CR_ON_BASE + 0x060) // E060
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_1_ADDR                    (CONN_BUS_CR_ON_BASE + 0x064) // E064
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_2_ADDR                    (CONN_BUS_CR_ON_BASE + 0x068) // E068
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_3_ADDR                    (CONN_BUS_CR_ON_BASE + 0x06C) // E06C
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_4_ADDR                    (CONN_BUS_CR_ON_BASE + 0x070) // E070
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_5_ADDR                    (CONN_BUS_CR_ON_BASE + 0x074) // E074
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_6_ADDR                    (CONN_BUS_CR_ON_BASE + 0x078) // E078
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_7_ADDR                    (CONN_BUS_CR_ON_BASE + 0x07C) // E07C
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_0_ADDR                 (CONN_BUS_CR_ON_BASE + 0x080) // E080
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_1_ADDR                 (CONN_BUS_CR_ON_BASE + 0x084) // E084
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_2_ADDR                 (CONN_BUS_CR_ON_BASE + 0x088) // E088
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_3_ADDR                 (CONN_BUS_CR_ON_BASE + 0x08C) // E08C
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_4_ADDR                 (CONN_BUS_CR_ON_BASE + 0x090) // E090
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_5_ADDR                 (CONN_BUS_CR_ON_BASE + 0x094) // E094
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_6_ADDR                 (CONN_BUS_CR_ON_BASE + 0x098) // E098
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_7_ADDR                 (CONN_BUS_CR_ON_BASE + 0x09C) // E09C
#define CONN_BUS_CR_ON_GALS_AP2CONN_CTRL_ADDR                  (CONN_BUS_CR_ON_BASE + 0x0B0) // E0B0
#define CONN_BUS_CR_ON_AP2CONN_GALS_RX_DBG_ADDR                (CONN_BUS_CR_ON_BASE + 0x0B4) // E0B4
#define CONN_BUS_CR_ON_CONN_VON_BUS_DBG_ADDR                   (CONN_BUS_CR_ON_BASE + 0x0C0) // E0C0
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_ADDR             (CONN_BUS_CR_ON_BASE + 0x100) // E100
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_ADDR             (CONN_BUS_CR_ON_BASE + 0x104) // E104
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_CK_DCM_ADDR           (CONN_BUS_CR_ON_BASE + 0x108) // E108
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_ADDR             (CONN_BUS_CR_ON_BASE + 0x10C) // E10C
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_ADDR             (CONN_BUS_CR_ON_BASE + 0x110) // E110
#define CONN_BUS_CR_ON_CONN_INFRA_APB_SLV_ACCESS_DETECT_EN_ADDR (CONN_BUS_CR_ON_BASE + 0x114) // E114
#define CONN_BUS_CR_ON_CONN_INFRA_CKSYS_CTRL_ADDR              (CONN_BUS_CR_ON_BASE + 0x120) // E120




/* =====================================================================================

  ---CONN_INFRA_VON_BUS_IDLE_CTRL_0 (0x1800E000 + 0x000)---

    VON_BUS_IDLE_MASK[15..0]     - (RW) conn_infra von bus idle mask
    RESERVED16[31..16]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_IDLE_CTRL_0_VON_BUS_IDLE_MASK_ADDR CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_IDLE_CTRL_0_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_IDLE_CTRL_0_VON_BUS_IDLE_MASK_MASK 0x0000FFFF                // VON_BUS_IDLE_MASK[15..0]
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_IDLE_CTRL_0_VON_BUS_IDLE_MASK_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_VON_BUS_IDLE_CTRL_1 (0x1800E000 + 0x004)---

    VON_BUS_IDLE_DEBOUNCE[4..0]  - (RW) conn_infra von bus idle debounce
    RESERVED5[31..5]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_IDLE_CTRL_1_VON_BUS_IDLE_DEBOUNCE_ADDR CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_IDLE_CTRL_1_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_IDLE_CTRL_1_VON_BUS_IDLE_DEBOUNCE_MASK 0x0000001F                // VON_BUS_IDLE_DEBOUNCE[4..0]
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_IDLE_CTRL_1_VON_BUS_IDLE_DEBOUNCE_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_VON_BUS_TIMEOUT_STATUS (0x1800E000 + 0x020)---

    TIMEOUT_STATUS[0]            - (RO) conn_von_bus apb timeout
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_STATUS_TIMEOUT_STATUS_ADDR CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_STATUS_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_STATUS_TIMEOUT_STATUS_MASK 0x00000001                // TIMEOUT_STATUS[0]
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_STATUS_TIMEOUT_STATUS_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_VON_BUS_TIMEOUT_CTRL (0x1800E000 + 0x024)---

    TIMEOUT_ENABLE[0]            - (RW) 1'b1:conn_von_bus timeout function
    TIMEOUT_CLEAR[1]             - (RW) write 1'b0 after write 1'b1 to clear timeout information
    FORCE_RESPONSE_HIGH[2]       - (RW) force bus response ready high
    TIMEOUT_TIME_SETTING[10..3]  - (RW) timeout timming setting with free run clock counter
    RESERVED11[31..11]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_TIMEOUT_TIME_SETTING_ADDR CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_TIMEOUT_TIME_SETTING_MASK 0x000007F8                // TIMEOUT_TIME_SETTING[10..3]
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_TIMEOUT_TIME_SETTING_SHFT 3
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_FORCE_RESPONSE_HIGH_ADDR CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_FORCE_RESPONSE_HIGH_MASK 0x00000004                // FORCE_RESPONSE_HIGH[2]
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_FORCE_RESPONSE_HIGH_SHFT 2
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_TIMEOUT_CLEAR_ADDR CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_TIMEOUT_CLEAR_MASK 0x00000002                // TIMEOUT_CLEAR[1]
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_TIMEOUT_CLEAR_SHFT 1
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_TIMEOUT_ENABLE_ADDR CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_TIMEOUT_ENABLE_MASK 0x00000001                // TIMEOUT_ENABLE[0]
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_TIMEOUT_ENABLE_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_0 (0x1800E000 + 0x028)---

    APB_TIMEOUT_INFO[31..0]      - (RO) depends on timeout apb slave will mapping to different psel and pwrite information

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_0_APB_TIMEOUT_INFO_ADDR CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_0_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_0_APB_TIMEOUT_INFO_MASK 0xFFFFFFFF                // APB_TIMEOUT_INFO[31..0]
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_0_APB_TIMEOUT_INFO_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_1 (0x1800E000 + 0x02C)---

    APB_TIMEOUT_ADDR[31..0]      - (RO) timeout address

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_1_APB_TIMEOUT_ADDR_ADDR CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_1_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_1_APB_TIMEOUT_ADDR_MASK 0xFFFFFFFF                // APB_TIMEOUT_ADDR[31..0]
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_1_APB_TIMEOUT_ADDR_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_2 (0x1800E000 + 0x030)---

    APB_TIMEOUT_WRITE_DATA[31..0] - (RO) timeout write data if write

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_2_APB_TIMEOUT_WRITE_DATA_ADDR CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_2_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_2_APB_TIMEOUT_WRITE_DATA_MASK 0xFFFFFFFF                // APB_TIMEOUT_WRITE_DATA[31..0]
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_2_APB_TIMEOUT_WRITE_DATA_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_ON_BUS_TIMEOUT_STATUS (0x1800E000 + 0x034)---

    TIMEOUT_STATUS[0]            - (RO) conn_infra_on_bus apb timeout
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_STATUS_TIMEOUT_STATUS_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_STATUS_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_STATUS_TIMEOUT_STATUS_MASK 0x00000001                // TIMEOUT_STATUS[0]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_STATUS_TIMEOUT_STATUS_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_ON_BUS_TIMEOUT_CTRL (0x1800E000 + 0x038)---

    TIMEOUT_ENABLE[0]            - (RW) 1'b1:conn_infra_on_bus timeout function
    TIMEOUT_CLEAR[1]             - (RW) write 1'b0 after write 1'b1 to clear timeout information
    FORCE_RESPONSE_HIGH[2]       - (RW) force bus response ready high
    TIMEOUT_TIME_SETTING[10..3]  - (RW) timeout timming setting with free run clock counter
    RESERVED11[31..11]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_TIMEOUT_TIME_SETTING_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_TIMEOUT_TIME_SETTING_MASK 0x000007F8                // TIMEOUT_TIME_SETTING[10..3]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_TIMEOUT_TIME_SETTING_SHFT 3
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_FORCE_RESPONSE_HIGH_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_FORCE_RESPONSE_HIGH_MASK 0x00000004                // FORCE_RESPONSE_HIGH[2]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_FORCE_RESPONSE_HIGH_SHFT 2
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_TIMEOUT_CLEAR_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_TIMEOUT_CLEAR_MASK 0x00000002                // TIMEOUT_CLEAR[1]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_TIMEOUT_CLEAR_SHFT 1
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_TIMEOUT_ENABLE_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_TIMEOUT_ENABLE_MASK 0x00000001                // TIMEOUT_ENABLE[0]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_TIMEOUT_ENABLE_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_0 (0x1800E000 + 0x03C)---

    APB_TIMEOUT_INFO[31..0]      - (RO) depends on timeout apb slave will mapping to different psel and pwrite information

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_0_APB_TIMEOUT_INFO_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_0_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_0_APB_TIMEOUT_INFO_MASK 0xFFFFFFFF                // APB_TIMEOUT_INFO[31..0]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_0_APB_TIMEOUT_INFO_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_1 (0x1800E000 + 0x040)---

    APB_TIMEOUT_ADDR[31..0]      - (RO) timeout address

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_1_APB_TIMEOUT_ADDR_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_1_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_1_APB_TIMEOUT_ADDR_MASK 0xFFFFFFFF                // APB_TIMEOUT_ADDR[31..0]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_1_APB_TIMEOUT_ADDR_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_2 (0x1800E000 + 0x044)---

    APB_TIMEOUT_WRITE_DATA[31..0] - (RO) timeout write data if write

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_2_APB_TIMEOUT_WRITE_DATA_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_2_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_2_APB_TIMEOUT_WRITE_DATA_MASK 0xFFFFFFFF                // APB_TIMEOUT_WRITE_DATA[31..0]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_2_APB_TIMEOUT_WRITE_DATA_SHFT 0

/* =====================================================================================

  ---PCIE2AP_REMAP_DOMAIN_ID (0x1800E000 + 0x050)---

    R_PCIE2AP_REMAP_DOMAIN_ID[3..0] - (RW)  xxx 
    RESERVED4[31..4]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_DOMAIN_ID_R_PCIE2AP_REMAP_DOMAIN_ID_ADDR CONN_BUS_CR_ON_PCIE2AP_REMAP_DOMAIN_ID_ADDR
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_DOMAIN_ID_R_PCIE2AP_REMAP_DOMAIN_ID_MASK 0x0000000F                // R_PCIE2AP_REMAP_DOMAIN_ID[3..0]
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_DOMAIN_ID_R_PCIE2AP_REMAP_DOMAIN_ID_SHFT 0

/* =====================================================================================

  ---PCIE2AP_REMAP_0 (0x1800E000 + 0x060)---

    R_PCIE2AP_PUBLIC_REMAPPING_0[15..0] - (RW)  xxx 
    R_PCIE2AP_PUBLIC_REMAPPING_1[31..16] - (RW)  xxx 

 =====================================================================================*/
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_0_R_PCIE2AP_PUBLIC_REMAPPING_1_ADDR CONN_BUS_CR_ON_PCIE2AP_REMAP_0_ADDR
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_0_R_PCIE2AP_PUBLIC_REMAPPING_1_MASK 0xFFFF0000                // R_PCIE2AP_PUBLIC_REMAPPING_1[31..16]
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_0_R_PCIE2AP_PUBLIC_REMAPPING_1_SHFT 16
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_0_R_PCIE2AP_PUBLIC_REMAPPING_0_ADDR CONN_BUS_CR_ON_PCIE2AP_REMAP_0_ADDR
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_0_R_PCIE2AP_PUBLIC_REMAPPING_0_MASK 0x0000FFFF                // R_PCIE2AP_PUBLIC_REMAPPING_0[15..0]
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_0_R_PCIE2AP_PUBLIC_REMAPPING_0_SHFT 0

/* =====================================================================================

  ---PCIE2AP_REMAP_1 (0x1800E000 + 0x064)---

    R_PCIE2AP_PUBLIC_REMAPPING_2[15..0] - (RW)  xxx 
    R_PCIE2AP_PUBLIC_REMAPPING_3[31..16] - (RW)  xxx 

 =====================================================================================*/
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_1_R_PCIE2AP_PUBLIC_REMAPPING_3_ADDR CONN_BUS_CR_ON_PCIE2AP_REMAP_1_ADDR
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_1_R_PCIE2AP_PUBLIC_REMAPPING_3_MASK 0xFFFF0000                // R_PCIE2AP_PUBLIC_REMAPPING_3[31..16]
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_1_R_PCIE2AP_PUBLIC_REMAPPING_3_SHFT 16
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_1_R_PCIE2AP_PUBLIC_REMAPPING_2_ADDR CONN_BUS_CR_ON_PCIE2AP_REMAP_1_ADDR
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_1_R_PCIE2AP_PUBLIC_REMAPPING_2_MASK 0x0000FFFF                // R_PCIE2AP_PUBLIC_REMAPPING_2[15..0]
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_1_R_PCIE2AP_PUBLIC_REMAPPING_2_SHFT 0

/* =====================================================================================

  ---PCIE2AP_REMAP_2 (0x1800E000 + 0x068)---

    R_PCIE2AP_PUBLIC_REMAPPING_4[15..0] - (RW)  xxx 
    R_PCIE2AP_PUBLIC_REMAPPING_5[31..16] - (RW)  xxx 

 =====================================================================================*/
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_2_R_PCIE2AP_PUBLIC_REMAPPING_5_ADDR CONN_BUS_CR_ON_PCIE2AP_REMAP_2_ADDR
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_2_R_PCIE2AP_PUBLIC_REMAPPING_5_MASK 0xFFFF0000                // R_PCIE2AP_PUBLIC_REMAPPING_5[31..16]
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_2_R_PCIE2AP_PUBLIC_REMAPPING_5_SHFT 16
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_2_R_PCIE2AP_PUBLIC_REMAPPING_4_ADDR CONN_BUS_CR_ON_PCIE2AP_REMAP_2_ADDR
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_2_R_PCIE2AP_PUBLIC_REMAPPING_4_MASK 0x0000FFFF                // R_PCIE2AP_PUBLIC_REMAPPING_4[15..0]
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_2_R_PCIE2AP_PUBLIC_REMAPPING_4_SHFT 0

/* =====================================================================================

  ---PCIE2AP_REMAP_3 (0x1800E000 + 0x06C)---

    R_PCIE2AP_PUBLIC_REMAPPING_6[15..0] - (RW)  xxx 
    R_PCIE2AP_PUBLIC_REMAPPING_7[31..16] - (RW)  xxx 

 =====================================================================================*/
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_3_R_PCIE2AP_PUBLIC_REMAPPING_7_ADDR CONN_BUS_CR_ON_PCIE2AP_REMAP_3_ADDR
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_3_R_PCIE2AP_PUBLIC_REMAPPING_7_MASK 0xFFFF0000                // R_PCIE2AP_PUBLIC_REMAPPING_7[31..16]
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_3_R_PCIE2AP_PUBLIC_REMAPPING_7_SHFT 16
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_3_R_PCIE2AP_PUBLIC_REMAPPING_6_ADDR CONN_BUS_CR_ON_PCIE2AP_REMAP_3_ADDR
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_3_R_PCIE2AP_PUBLIC_REMAPPING_6_MASK 0x0000FFFF                // R_PCIE2AP_PUBLIC_REMAPPING_6[15..0]
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_3_R_PCIE2AP_PUBLIC_REMAPPING_6_SHFT 0

/* =====================================================================================

  ---PCIE2AP_REMAP_4 (0x1800E000 + 0x070)---

    R_PCIE2AP_PUBLIC_REMAPPING_8[15..0] - (RW)  xxx 
    R_PCIE2AP_PUBLIC_REMAPPING_9[31..16] - (RW)  xxx 

 =====================================================================================*/
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_4_R_PCIE2AP_PUBLIC_REMAPPING_9_ADDR CONN_BUS_CR_ON_PCIE2AP_REMAP_4_ADDR
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_4_R_PCIE2AP_PUBLIC_REMAPPING_9_MASK 0xFFFF0000                // R_PCIE2AP_PUBLIC_REMAPPING_9[31..16]
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_4_R_PCIE2AP_PUBLIC_REMAPPING_9_SHFT 16
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_4_R_PCIE2AP_PUBLIC_REMAPPING_8_ADDR CONN_BUS_CR_ON_PCIE2AP_REMAP_4_ADDR
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_4_R_PCIE2AP_PUBLIC_REMAPPING_8_MASK 0x0000FFFF                // R_PCIE2AP_PUBLIC_REMAPPING_8[15..0]
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_4_R_PCIE2AP_PUBLIC_REMAPPING_8_SHFT 0

/* =====================================================================================

  ---PCIE2AP_REMAP_5 (0x1800E000 + 0x074)---

    R_PCIE2AP_PUBLIC_REMAPPING_A[15..0] - (RW)  xxx 
    R_PCIE2AP_PUBLIC_REMAPPING_B[31..16] - (RW)  xxx 

 =====================================================================================*/
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_5_R_PCIE2AP_PUBLIC_REMAPPING_B_ADDR CONN_BUS_CR_ON_PCIE2AP_REMAP_5_ADDR
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_5_R_PCIE2AP_PUBLIC_REMAPPING_B_MASK 0xFFFF0000                // R_PCIE2AP_PUBLIC_REMAPPING_B[31..16]
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_5_R_PCIE2AP_PUBLIC_REMAPPING_B_SHFT 16
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_5_R_PCIE2AP_PUBLIC_REMAPPING_A_ADDR CONN_BUS_CR_ON_PCIE2AP_REMAP_5_ADDR
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_5_R_PCIE2AP_PUBLIC_REMAPPING_A_MASK 0x0000FFFF                // R_PCIE2AP_PUBLIC_REMAPPING_A[15..0]
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_5_R_PCIE2AP_PUBLIC_REMAPPING_A_SHFT 0

/* =====================================================================================

  ---PCIE2AP_REMAP_6 (0x1800E000 + 0x078)---

    R_PCIE2AP_PUBLIC_REMAPPING_C[15..0] - (RW)  xxx 
    R_PCIE2AP_PUBLIC_REMAPPING_D[31..16] - (RW)  xxx 

 =====================================================================================*/
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_6_R_PCIE2AP_PUBLIC_REMAPPING_D_ADDR CONN_BUS_CR_ON_PCIE2AP_REMAP_6_ADDR
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_6_R_PCIE2AP_PUBLIC_REMAPPING_D_MASK 0xFFFF0000                // R_PCIE2AP_PUBLIC_REMAPPING_D[31..16]
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_6_R_PCIE2AP_PUBLIC_REMAPPING_D_SHFT 16
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_6_R_PCIE2AP_PUBLIC_REMAPPING_C_ADDR CONN_BUS_CR_ON_PCIE2AP_REMAP_6_ADDR
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_6_R_PCIE2AP_PUBLIC_REMAPPING_C_MASK 0x0000FFFF                // R_PCIE2AP_PUBLIC_REMAPPING_C[15..0]
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_6_R_PCIE2AP_PUBLIC_REMAPPING_C_SHFT 0

/* =====================================================================================

  ---PCIE2AP_REMAP_7 (0x1800E000 + 0x07C)---

    R_PCIE2AP_PUBLIC_REMAPPING_E[15..0] - (RW)  xxx 
    R_PCIE2AP_PUBLIC_REMAPPING_F[31..16] - (RO)  xxx 

 =====================================================================================*/
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_7_R_PCIE2AP_PUBLIC_REMAPPING_F_ADDR CONN_BUS_CR_ON_PCIE2AP_REMAP_7_ADDR
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_7_R_PCIE2AP_PUBLIC_REMAPPING_F_MASK 0xFFFF0000                // R_PCIE2AP_PUBLIC_REMAPPING_F[31..16]
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_7_R_PCIE2AP_PUBLIC_REMAPPING_F_SHFT 16
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_7_R_PCIE2AP_PUBLIC_REMAPPING_E_ADDR CONN_BUS_CR_ON_PCIE2AP_REMAP_7_ADDR
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_7_R_PCIE2AP_PUBLIC_REMAPPING_E_MASK 0x0000FFFF                // R_PCIE2AP_PUBLIC_REMAPPING_E[15..0]
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_7_R_PCIE2AP_PUBLIC_REMAPPING_E_SHFT 0

/* =====================================================================================

  ---PCIE2AP_REMAP_BT_0 (0x1800E000 + 0x080)---

    R_PCIE2AP_BT_PUBLIC_REMAPPING_0[15..0] - (RW)  xxx 
    R_PCIE2AP_BT_PUBLIC_REMAPPING_1[31..16] - (RW)  xxx 

 =====================================================================================*/
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_0_R_PCIE2AP_BT_PUBLIC_REMAPPING_1_ADDR CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_0_ADDR
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_0_R_PCIE2AP_BT_PUBLIC_REMAPPING_1_MASK 0xFFFF0000                // R_PCIE2AP_BT_PUBLIC_REMAPPING_1[31..16]
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_0_R_PCIE2AP_BT_PUBLIC_REMAPPING_1_SHFT 16
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_0_R_PCIE2AP_BT_PUBLIC_REMAPPING_0_ADDR CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_0_ADDR
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_0_R_PCIE2AP_BT_PUBLIC_REMAPPING_0_MASK 0x0000FFFF                // R_PCIE2AP_BT_PUBLIC_REMAPPING_0[15..0]
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_0_R_PCIE2AP_BT_PUBLIC_REMAPPING_0_SHFT 0

/* =====================================================================================

  ---PCIE2AP_REMAP_BT_1 (0x1800E000 + 0x084)---

    R_PCIE2AP_BT_PUBLIC_REMAPPING_2[15..0] - (RW)  xxx 
    R_PCIE2AP_BT_PUBLIC_REMAPPING_3[31..16] - (RW)  xxx 

 =====================================================================================*/
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_1_R_PCIE2AP_BT_PUBLIC_REMAPPING_3_ADDR CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_1_ADDR
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_1_R_PCIE2AP_BT_PUBLIC_REMAPPING_3_MASK 0xFFFF0000                // R_PCIE2AP_BT_PUBLIC_REMAPPING_3[31..16]
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_1_R_PCIE2AP_BT_PUBLIC_REMAPPING_3_SHFT 16
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_1_R_PCIE2AP_BT_PUBLIC_REMAPPING_2_ADDR CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_1_ADDR
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_1_R_PCIE2AP_BT_PUBLIC_REMAPPING_2_MASK 0x0000FFFF                // R_PCIE2AP_BT_PUBLIC_REMAPPING_2[15..0]
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_1_R_PCIE2AP_BT_PUBLIC_REMAPPING_2_SHFT 0

/* =====================================================================================

  ---PCIE2AP_REMAP_BT_2 (0x1800E000 + 0x088)---

    R_PCIE2AP_BT_PUBLIC_REMAPPING_4[15..0] - (RW)  xxx 
    R_PCIE2AP_BT_PUBLIC_REMAPPING_5[31..16] - (RW)  xxx 

 =====================================================================================*/
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_2_R_PCIE2AP_BT_PUBLIC_REMAPPING_5_ADDR CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_2_ADDR
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_2_R_PCIE2AP_BT_PUBLIC_REMAPPING_5_MASK 0xFFFF0000                // R_PCIE2AP_BT_PUBLIC_REMAPPING_5[31..16]
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_2_R_PCIE2AP_BT_PUBLIC_REMAPPING_5_SHFT 16
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_2_R_PCIE2AP_BT_PUBLIC_REMAPPING_4_ADDR CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_2_ADDR
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_2_R_PCIE2AP_BT_PUBLIC_REMAPPING_4_MASK 0x0000FFFF                // R_PCIE2AP_BT_PUBLIC_REMAPPING_4[15..0]
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_2_R_PCIE2AP_BT_PUBLIC_REMAPPING_4_SHFT 0

/* =====================================================================================

  ---PCIE2AP_REMAP_BT_3 (0x1800E000 + 0x08C)---

    R_PCIE2AP_BT_PUBLIC_REMAPPING_6[15..0] - (RW)  xxx 
    R_PCIE2AP_BT_PUBLIC_REMAPPING_7[31..16] - (RW)  xxx 

 =====================================================================================*/
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_3_R_PCIE2AP_BT_PUBLIC_REMAPPING_7_ADDR CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_3_ADDR
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_3_R_PCIE2AP_BT_PUBLIC_REMAPPING_7_MASK 0xFFFF0000                // R_PCIE2AP_BT_PUBLIC_REMAPPING_7[31..16]
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_3_R_PCIE2AP_BT_PUBLIC_REMAPPING_7_SHFT 16
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_3_R_PCIE2AP_BT_PUBLIC_REMAPPING_6_ADDR CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_3_ADDR
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_3_R_PCIE2AP_BT_PUBLIC_REMAPPING_6_MASK 0x0000FFFF                // R_PCIE2AP_BT_PUBLIC_REMAPPING_6[15..0]
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_3_R_PCIE2AP_BT_PUBLIC_REMAPPING_6_SHFT 0

/* =====================================================================================

  ---PCIE2AP_REMAP_BT_4 (0x1800E000 + 0x090)---

    R_PCIE2AP_BT_PUBLIC_REMAPPING_8[15..0] - (RW)  xxx 
    R_PCIE2AP_BT_PUBLIC_REMAPPING_9[31..16] - (RW)  xxx 

 =====================================================================================*/
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_4_R_PCIE2AP_BT_PUBLIC_REMAPPING_9_ADDR CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_4_ADDR
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_4_R_PCIE2AP_BT_PUBLIC_REMAPPING_9_MASK 0xFFFF0000                // R_PCIE2AP_BT_PUBLIC_REMAPPING_9[31..16]
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_4_R_PCIE2AP_BT_PUBLIC_REMAPPING_9_SHFT 16
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_4_R_PCIE2AP_BT_PUBLIC_REMAPPING_8_ADDR CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_4_ADDR
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_4_R_PCIE2AP_BT_PUBLIC_REMAPPING_8_MASK 0x0000FFFF                // R_PCIE2AP_BT_PUBLIC_REMAPPING_8[15..0]
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_4_R_PCIE2AP_BT_PUBLIC_REMAPPING_8_SHFT 0

/* =====================================================================================

  ---PCIE2AP_REMAP_BT_5 (0x1800E000 + 0x094)---

    R_PCIE2AP_BT_PUBLIC_REMAPPING_A[15..0] - (RW)  xxx 
    R_PCIE2AP_BT_PUBLIC_REMAPPING_B[31..16] - (RW)  xxx 

 =====================================================================================*/
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_5_R_PCIE2AP_BT_PUBLIC_REMAPPING_B_ADDR CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_5_ADDR
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_5_R_PCIE2AP_BT_PUBLIC_REMAPPING_B_MASK 0xFFFF0000                // R_PCIE2AP_BT_PUBLIC_REMAPPING_B[31..16]
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_5_R_PCIE2AP_BT_PUBLIC_REMAPPING_B_SHFT 16
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_5_R_PCIE2AP_BT_PUBLIC_REMAPPING_A_ADDR CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_5_ADDR
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_5_R_PCIE2AP_BT_PUBLIC_REMAPPING_A_MASK 0x0000FFFF                // R_PCIE2AP_BT_PUBLIC_REMAPPING_A[15..0]
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_5_R_PCIE2AP_BT_PUBLIC_REMAPPING_A_SHFT 0

/* =====================================================================================

  ---PCIE2AP_REMAP_BT_6 (0x1800E000 + 0x098)---

    R_PCIE2AP_BT_PUBLIC_REMAPPING_C[15..0] - (RW)  xxx 
    R_PCIE2AP_BT_PUBLIC_REMAPPING_D[31..16] - (RW)  xxx 

 =====================================================================================*/
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_6_R_PCIE2AP_BT_PUBLIC_REMAPPING_D_ADDR CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_6_ADDR
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_6_R_PCIE2AP_BT_PUBLIC_REMAPPING_D_MASK 0xFFFF0000                // R_PCIE2AP_BT_PUBLIC_REMAPPING_D[31..16]
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_6_R_PCIE2AP_BT_PUBLIC_REMAPPING_D_SHFT 16
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_6_R_PCIE2AP_BT_PUBLIC_REMAPPING_C_ADDR CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_6_ADDR
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_6_R_PCIE2AP_BT_PUBLIC_REMAPPING_C_MASK 0x0000FFFF                // R_PCIE2AP_BT_PUBLIC_REMAPPING_C[15..0]
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_6_R_PCIE2AP_BT_PUBLIC_REMAPPING_C_SHFT 0

/* =====================================================================================

  ---PCIE2AP_REMAP_BT_7 (0x1800E000 + 0x09C)---

    R_PCIE2AP_BT_PUBLIC_REMAPPING_E[15..0] - (RW)  xxx 
    R_PCIE2AP_BT_PUBLIC_REMAPPING_F[31..16] - (RO)  xxx 

 =====================================================================================*/
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_7_R_PCIE2AP_BT_PUBLIC_REMAPPING_F_ADDR CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_7_ADDR
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_7_R_PCIE2AP_BT_PUBLIC_REMAPPING_F_MASK 0xFFFF0000                // R_PCIE2AP_BT_PUBLIC_REMAPPING_F[31..16]
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_7_R_PCIE2AP_BT_PUBLIC_REMAPPING_F_SHFT 16
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_7_R_PCIE2AP_BT_PUBLIC_REMAPPING_E_ADDR CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_7_ADDR
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_7_R_PCIE2AP_BT_PUBLIC_REMAPPING_E_MASK 0x0000FFFF                // R_PCIE2AP_BT_PUBLIC_REMAPPING_E[15..0]
#define CONN_BUS_CR_ON_PCIE2AP_REMAP_BT_7_R_PCIE2AP_BT_PUBLIC_REMAPPING_E_SHFT 0

/* =====================================================================================

  ---GALS_AP2CONN_CTRL (0x1800E000 + 0x0B0)---

    RG_AFIFO_SYNC_SEL[1..0]      - (RW)  xxx 
    RESERVED2[31..2]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_GALS_AP2CONN_CTRL_RG_AFIFO_SYNC_SEL_ADDR CONN_BUS_CR_ON_GALS_AP2CONN_CTRL_ADDR
#define CONN_BUS_CR_ON_GALS_AP2CONN_CTRL_RG_AFIFO_SYNC_SEL_MASK 0x00000003                // RG_AFIFO_SYNC_SEL[1..0]
#define CONN_BUS_CR_ON_GALS_AP2CONN_CTRL_RG_AFIFO_SYNC_SEL_SHFT 0

/* =====================================================================================

  ---AP2CONN_GALS_RX_DBG (0x1800E000 + 0x0B4)---

    DBG_INFO[31..0]              - (RO)  xxx 

 =====================================================================================*/
#define CONN_BUS_CR_ON_AP2CONN_GALS_RX_DBG_DBG_INFO_ADDR       CONN_BUS_CR_ON_AP2CONN_GALS_RX_DBG_ADDR
#define CONN_BUS_CR_ON_AP2CONN_GALS_RX_DBG_DBG_INFO_MASK       0xFFFFFFFF                // DBG_INFO[31..0]
#define CONN_BUS_CR_ON_AP2CONN_GALS_RX_DBG_DBG_INFO_SHFT       0

/* =====================================================================================

  ---CONN_VON_BUS_DBG (0x1800E000 + 0x0C0)---

    DBG_INFO[31..0]              - (RO)  xxx 

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_VON_BUS_DBG_DBG_INFO_ADDR          CONN_BUS_CR_ON_CONN_VON_BUS_DBG_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_DBG_DBG_INFO_MASK          0xFFFFFFFF                // DBG_INFO[31..0]
#define CONN_BUS_CR_ON_CONN_VON_BUS_DBG_DBG_INFO_SHFT          0

/* =====================================================================================

  ---CONN_VON_BUS_DCM_CTL_0 (0x1800E000 + 0x100)---

    HCLK_SC_AXI_DCM_DIS[0]       - (RW)  xxx 
    HCLK_CK_RDY_ON_DCM[1]        - (RO)  xxx 
    HCLK_CK_DCM_IDLE[2]          - (RO)  xxx 
    HCLK_DEBOUNCE_EN[3]          - (RW)  xxx 
    HCLK_DEBOUNCE_NUM[15..4]     - (RW)  xxx 
    RESERVED16[31..16]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_HCLK_DEBOUNCE_NUM_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_HCLK_DEBOUNCE_NUM_MASK 0x0000FFF0                // HCLK_DEBOUNCE_NUM[15..4]
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_HCLK_DEBOUNCE_NUM_SHFT 4
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_HCLK_DEBOUNCE_EN_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_HCLK_DEBOUNCE_EN_MASK 0x00000008                // HCLK_DEBOUNCE_EN[3]
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_HCLK_DEBOUNCE_EN_SHFT 3
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_HCLK_CK_DCM_IDLE_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_HCLK_CK_DCM_IDLE_MASK 0x00000004                // HCLK_CK_DCM_IDLE[2]
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_HCLK_CK_DCM_IDLE_SHFT 2
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_HCLK_CK_RDY_ON_DCM_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_HCLK_CK_RDY_ON_DCM_MASK 0x00000002                // HCLK_CK_RDY_ON_DCM[1]
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_HCLK_CK_RDY_ON_DCM_SHFT 1
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_HCLK_SC_AXI_DCM_DIS_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_HCLK_SC_AXI_DCM_DIS_MASK 0x00000001                // HCLK_SC_AXI_DCM_DIS[0]
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_HCLK_SC_AXI_DCM_DIS_SHFT 0

/* =====================================================================================

  ---CONN_VON_BUS_DCM_CTL_1 (0x1800E000 + 0x104)---

    IDLE_CK_DCM_LEVEL_SEL[4..0]  - (RW)  xxx 
    BUSY_CK_DCM_LEVEL_SEL[9..5]  - (RW)  xxx 
    FORCE_FREE_RUN[10]           - (RW)  xxx 
    FORCE_SLOW[11]               - (RW)  xxx 
    FORCE_OFF[12]                - (RW)  xxx 
    SLOW_MODE_ENABLE[13]         - (RW)  xxx 
    OFF_MODE_ENABLE[14]          - (RW)  xxx 
    CK_RDY_ON_DCM[15]            - (RW)  xxx 
    PLL_SEL_NO_SPM[16]           - (RW)  xxx 
    SC_AXI_DCM_DIS_EN[17]        - (RW)  xxx 
    RESERVED18[31..18]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_SC_AXI_DCM_DIS_EN_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_SC_AXI_DCM_DIS_EN_MASK 0x00020000                // SC_AXI_DCM_DIS_EN[17]
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_SC_AXI_DCM_DIS_EN_SHFT 17
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_PLL_SEL_NO_SPM_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_PLL_SEL_NO_SPM_MASK 0x00010000                // PLL_SEL_NO_SPM[16]
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_PLL_SEL_NO_SPM_SHFT 16
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_CK_RDY_ON_DCM_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_CK_RDY_ON_DCM_MASK 0x00008000                // CK_RDY_ON_DCM[15]
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_CK_RDY_ON_DCM_SHFT 15
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_OFF_MODE_ENABLE_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_OFF_MODE_ENABLE_MASK 0x00004000                // OFF_MODE_ENABLE[14]
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_OFF_MODE_ENABLE_SHFT 14
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_SLOW_MODE_ENABLE_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_SLOW_MODE_ENABLE_MASK 0x00002000                // SLOW_MODE_ENABLE[13]
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_SLOW_MODE_ENABLE_SHFT 13
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_FORCE_OFF_ADDR   CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_FORCE_OFF_MASK   0x00001000                // FORCE_OFF[12]
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_FORCE_OFF_SHFT   12
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_FORCE_SLOW_ADDR  CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_FORCE_SLOW_MASK  0x00000800                // FORCE_SLOW[11]
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_FORCE_SLOW_SHFT  11
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_FORCE_FREE_RUN_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_FORCE_FREE_RUN_MASK 0x00000400                // FORCE_FREE_RUN[10]
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_FORCE_FREE_RUN_SHFT 10
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_BUSY_CK_DCM_LEVEL_SEL_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_BUSY_CK_DCM_LEVEL_SEL_MASK 0x000003E0                // BUSY_CK_DCM_LEVEL_SEL[9..5]
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_BUSY_CK_DCM_LEVEL_SEL_SHFT 5
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_IDLE_CK_DCM_LEVEL_SEL_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_IDLE_CK_DCM_LEVEL_SEL_MASK 0x0000001F                // IDLE_CK_DCM_LEVEL_SEL[4..0]
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_IDLE_CK_DCM_LEVEL_SEL_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_ON_BUS_CK_DCM (0x1800E000 + 0x108)---

    OSC_CK_FR_EN[0]              - (RW)  xxx 
    HOST_OSC_CK_FR_EN[1]         - (RW)  xxx 
    RESERVED2[31..2]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_CK_DCM_HOST_OSC_CK_FR_EN_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_CK_DCM_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_CK_DCM_HOST_OSC_CK_FR_EN_MASK 0x00000002                // HOST_OSC_CK_FR_EN[1]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_CK_DCM_HOST_OSC_CK_FR_EN_SHFT 1
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_CK_DCM_OSC_CK_FR_EN_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_CK_DCM_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_CK_DCM_OSC_CK_FR_EN_MASK 0x00000001                // OSC_CK_FR_EN[0]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_CK_DCM_OSC_CK_FR_EN_SHFT 0

/* =====================================================================================

  ---CONN_OFF_BUS_DCM_CTL_0 (0x1800E000 + 0x10C)---

    HCLK_SC_AXI_DCM_DIS[0]       - (RW)  xxx 
    HCLK_CK_RDY_ON_DCM[1]        - (RO)  xxx 
    HCLK_CK_DCM_IDLE[2]          - (RO)  xxx 
    HCLK_DEBOUNCE_EN[3]          - (RW)  xxx 
    HCLK_DEBOUNCE_NUM[15..4]     - (RW)  xxx 
    RESERVED16[31..16]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_HCLK_DEBOUNCE_NUM_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_HCLK_DEBOUNCE_NUM_MASK 0x0000FFF0                // HCLK_DEBOUNCE_NUM[15..4]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_HCLK_DEBOUNCE_NUM_SHFT 4
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_HCLK_DEBOUNCE_EN_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_HCLK_DEBOUNCE_EN_MASK 0x00000008                // HCLK_DEBOUNCE_EN[3]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_HCLK_DEBOUNCE_EN_SHFT 3
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_HCLK_CK_DCM_IDLE_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_HCLK_CK_DCM_IDLE_MASK 0x00000004                // HCLK_CK_DCM_IDLE[2]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_HCLK_CK_DCM_IDLE_SHFT 2
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_HCLK_CK_RDY_ON_DCM_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_HCLK_CK_RDY_ON_DCM_MASK 0x00000002                // HCLK_CK_RDY_ON_DCM[1]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_HCLK_CK_RDY_ON_DCM_SHFT 1
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_HCLK_SC_AXI_DCM_DIS_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_HCLK_SC_AXI_DCM_DIS_MASK 0x00000001                // HCLK_SC_AXI_DCM_DIS[0]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_HCLK_SC_AXI_DCM_DIS_SHFT 0

/* =====================================================================================

  ---CONN_OFF_BUS_DCM_CTL_1 (0x1800E000 + 0x110)---

    IDLE_CK_DCM_LEVEL_SEL[4..0]  - (RW)  xxx 
    BUSY_CK_DCM_LEVEL_SEL[9..5]  - (RW)  xxx 
    FORCE_FREE_RUN[10]           - (RW)  xxx 
    FORCE_SLOW[11]               - (RW)  xxx 
    FORCE_OFF[12]                - (RW)  xxx 
    SLOW_MODE_ENABLE[13]         - (RW)  xxx 
    OFF_MODE_ENABLE[14]          - (RW)  xxx 
    CK_RDY_ON_DCM[15]            - (RW)  xxx 
    PLL_SEL_NO_SPM[16]           - (RW)  xxx 
    SC_AXI_DCM_DIS_EN[17]        - (RW)  xxx 
    OSC_CK_FR_EN[18]             - (RW)  xxx 
    MASK_OFF_OSC_FR_EN_CTRL[19]  - (RW) 1'b0:mask off control
    MASK_OFF_DOMAIN_OFF_MODE_ENABLE_CTRL[20] - (RW) 1'b1:mask off control
    MASK_OFF_DOMAIN_SLOW_MODE_ENABLE_CTRL[21] - (RW) 1'b1:mask off control
    RESERVED22[31..22]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_MASK_OFF_DOMAIN_SLOW_MODE_ENABLE_CTRL_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_MASK_OFF_DOMAIN_SLOW_MODE_ENABLE_CTRL_MASK 0x00200000                // MASK_OFF_DOMAIN_SLOW_MODE_ENABLE_CTRL[21]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_MASK_OFF_DOMAIN_SLOW_MODE_ENABLE_CTRL_SHFT 21
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_MASK_OFF_DOMAIN_OFF_MODE_ENABLE_CTRL_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_MASK_OFF_DOMAIN_OFF_MODE_ENABLE_CTRL_MASK 0x00100000                // MASK_OFF_DOMAIN_OFF_MODE_ENABLE_CTRL[20]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_MASK_OFF_DOMAIN_OFF_MODE_ENABLE_CTRL_SHFT 20
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_MASK_OFF_OSC_FR_EN_CTRL_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_MASK_OFF_OSC_FR_EN_CTRL_MASK 0x00080000                // MASK_OFF_OSC_FR_EN_CTRL[19]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_MASK_OFF_OSC_FR_EN_CTRL_SHFT 19
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_OSC_CK_FR_EN_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_OSC_CK_FR_EN_MASK 0x00040000                // OSC_CK_FR_EN[18]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_OSC_CK_FR_EN_SHFT 18
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_SC_AXI_DCM_DIS_EN_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_SC_AXI_DCM_DIS_EN_MASK 0x00020000                // SC_AXI_DCM_DIS_EN[17]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_SC_AXI_DCM_DIS_EN_SHFT 17
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_PLL_SEL_NO_SPM_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_PLL_SEL_NO_SPM_MASK 0x00010000                // PLL_SEL_NO_SPM[16]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_PLL_SEL_NO_SPM_SHFT 16
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_CK_RDY_ON_DCM_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_CK_RDY_ON_DCM_MASK 0x00008000                // CK_RDY_ON_DCM[15]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_CK_RDY_ON_DCM_SHFT 15
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_OFF_MODE_ENABLE_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_OFF_MODE_ENABLE_MASK 0x00004000                // OFF_MODE_ENABLE[14]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_OFF_MODE_ENABLE_SHFT 14
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_SLOW_MODE_ENABLE_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_SLOW_MODE_ENABLE_MASK 0x00002000                // SLOW_MODE_ENABLE[13]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_SLOW_MODE_ENABLE_SHFT 13
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_FORCE_OFF_ADDR   CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_FORCE_OFF_MASK   0x00001000                // FORCE_OFF[12]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_FORCE_OFF_SHFT   12
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_FORCE_SLOW_ADDR  CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_FORCE_SLOW_MASK  0x00000800                // FORCE_SLOW[11]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_FORCE_SLOW_SHFT  11
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_FORCE_FREE_RUN_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_FORCE_FREE_RUN_MASK 0x00000400                // FORCE_FREE_RUN[10]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_FORCE_FREE_RUN_SHFT 10
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_BUSY_CK_DCM_LEVEL_SEL_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_BUSY_CK_DCM_LEVEL_SEL_MASK 0x000003E0                // BUSY_CK_DCM_LEVEL_SEL[9..5]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_BUSY_CK_DCM_LEVEL_SEL_SHFT 5
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_IDLE_CK_DCM_LEVEL_SEL_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_IDLE_CK_DCM_LEVEL_SEL_MASK 0x0000001F                // IDLE_CK_DCM_LEVEL_SEL[4..0]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_IDLE_CK_DCM_LEVEL_SEL_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_APB_SLV_ACCESS_DETECT_EN (0x1800E000 + 0x114)---

    CONN_INFRA_APB_SLV_ACCESS_DETECT_EN[0] - (WO) SW path for enable conn_infra off apb slave access detect function
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_APB_SLV_ACCESS_DETECT_EN_CONN_INFRA_APB_SLV_ACCESS_DETECT_EN_ADDR CONN_BUS_CR_ON_CONN_INFRA_APB_SLV_ACCESS_DETECT_EN_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_APB_SLV_ACCESS_DETECT_EN_CONN_INFRA_APB_SLV_ACCESS_DETECT_EN_MASK 0x00000001                // CONN_INFRA_APB_SLV_ACCESS_DETECT_EN[0]
#define CONN_BUS_CR_ON_CONN_INFRA_APB_SLV_ACCESS_DETECT_EN_CONN_INFRA_APB_SLV_ACCESS_DETECT_EN_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_CKSYS_CTRL (0x1800E000 + 0x120)---

    CKSYS_CK_REQ_HW_MODE[0]      - (RW) set connsys to cksys host ck request hw mode control by bus status
    CKSYS_CK_REQ_SW_EN[1]        - (RW) sw setting for cksys host ck request if not hw mode
    RESERVED2[31..2]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_CKSYS_CTRL_CKSYS_CK_REQ_SW_EN_ADDR CONN_BUS_CR_ON_CONN_INFRA_CKSYS_CTRL_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_CKSYS_CTRL_CKSYS_CK_REQ_SW_EN_MASK 0x00000002                // CKSYS_CK_REQ_SW_EN[1]
#define CONN_BUS_CR_ON_CONN_INFRA_CKSYS_CTRL_CKSYS_CK_REQ_SW_EN_SHFT 1
#define CONN_BUS_CR_ON_CONN_INFRA_CKSYS_CTRL_CKSYS_CK_REQ_HW_MODE_ADDR CONN_BUS_CR_ON_CONN_INFRA_CKSYS_CTRL_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_CKSYS_CTRL_CKSYS_CK_REQ_HW_MODE_MASK 0x00000001                // CKSYS_CK_REQ_HW_MODE[0]
#define CONN_BUS_CR_ON_CONN_INFRA_CKSYS_CTRL_CKSYS_CK_REQ_HW_MODE_SHFT 0


#endif // __CONN_BUS_CR_ON_REGS_H__
