/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */
#ifndef __CONN_INFRA_BUS_CR_REGS_H__
#define __CONN_INFRA_BUS_CR_REGS_H__

#define CONN_INFRA_BUS_CR_BASE                                 0x1804B000

#define CONN_INFRA_BUS_CR_CONN2AP_REMAP_GPS_EMI_BASE_ADDR_ADDR (CONN_INFRA_BUS_CR_BASE + 0x0360)
#define CONN_INFRA_BUS_CR_CONN2AP_REMAP_GPS_PERI_BASE_ADDR_ADDR (CONN_INFRA_BUS_CR_BASE + 0x036C)


#define CONN_INFRA_BUS_CR_CONN2AP_REMAP_GPS_EMI_BASE_ADDR_CONN2AP_REMAP_GPS_EMI_BASE_ADDR_ADDR \
	CONN_INFRA_BUS_CR_CONN2AP_REMAP_GPS_EMI_BASE_ADDR_ADDR
#define CONN_INFRA_BUS_CR_CONN2AP_REMAP_GPS_EMI_BASE_ADDR_CONN2AP_REMAP_GPS_EMI_BASE_ADDR_MASK 0x000FFFFF
#define CONN_INFRA_BUS_CR_CONN2AP_REMAP_GPS_EMI_BASE_ADDR_CONN2AP_REMAP_GPS_EMI_BASE_ADDR_SHFT 0

#define CONN_INFRA_BUS_CR_CONN2AP_REMAP_GPS_PERI_BASE_ADDR_CONN2AP_REMAP_GPS_PERI_BASE_ADDR_ADDR \
	CONN_INFRA_BUS_CR_CONN2AP_REMAP_GPS_PERI_BASE_ADDR_ADDR
#define CONN_INFRA_BUS_CR_CONN2AP_REMAP_GPS_PERI_BASE_ADDR_CONN2AP_REMAP_GPS_PERI_BASE_ADDR_MASK 0x000FFFFF
#define CONN_INFRA_BUS_CR_CONN2AP_REMAP_GPS_PERI_BASE_ADDR_CONN2AP_REMAP_GPS_PERI_BASE_ADDR_SHFT 0

#endif /* __CONN_INFRA_BUS_CR_REGS_H__ */

