/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */
#ifndef __CONN_WT_SLP_CTL_REG_REGS_H__
#define __CONN_WT_SLP_CTL_REG_REGS_H__

#define CONN_WT_SLP_CTL_REG_BASE                               0x18003000

#define CONN_WT_SLP_CTL_ADDR_WB_SLP_TOP_CK_5_ADDR              (CONN_WT_SLP_CTL_REG_BASE + 0x0134)
#define CONN_WT_SLP_CTL_ADDR_WB_GPS_CTL_ADDR                   (CONN_WT_SLP_CTL_REG_BASE + 0x0200)


#define CONN_WT_SLP_CTL_REG_WB_SLP_TOP_CK_5_WB_SLP_TOP_CK_5_BSY_ADDR CONN_WT_SLP_CTL_ADDR_WB_SLP_TOP_CK_5_ADDR
#define CONN_WT_SLP_CTL_REG_WB_SLP_TOP_CK_5_WB_SLP_TOP_CK_5_BSY_MASK 0x00000002
#define CONN_WT_SLP_CTL_REG_WB_SLP_TOP_CK_5_WB_SLP_TOP_CK_5_BSY_SHFT 1
#define CONN_WT_SLP_CTL_REG_WB_SLP_TOP_CK_5_WB_SLP_TOP_CK_5_ADDR CONN_WT_SLP_CTL_ADDR_WB_SLP_TOP_CK_5_ADDR
#define CONN_WT_SLP_CTL_REG_WB_SLP_TOP_CK_5_WB_SLP_TOP_CK_5_MASK 0x00000001
#define CONN_WT_SLP_CTL_REG_WB_SLP_TOP_CK_5_WB_SLP_TOP_CK_5_SHFT 0

#define CONN_WT_SLP_CTL_REG_WB_GPS_CTL_GPS_HW_MODE_EN_ADDR     CONN_WT_SLP_CTL_ADDR_WB_GPS_CTL_ADDR
#define CONN_WT_SLP_CTL_REG_WB_GPS_CTL_GPS_HW_MODE_EN_MASK     0x00000001
#define CONN_WT_SLP_CTL_REG_WB_GPS_CTL_GPS_HW_MODE_EN_SHFT     0

#endif /* __CONN_WT_SLP_CTL_REG_REGS_H__ */

