/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */
#ifndef __INST2_CONN_WT_SLP_CTL_REG_REGS_H__
#define __INST2_CONN_WT_SLP_CTL_REG_REGS_H__

#define INST2_CONN_WT_SLP_CTL_REG_BASE                               0x18007000

#define INST2_CONN_WT_SLP_CTL_REG_WB_SLP_TOP_CK_5_ADDR              (INST2_CONN_WT_SLP_CTL_REG_BASE + 0x0134)
#define INST2_CONN_WT_SLP_CTL_REG_WB_GPS_CTL_ADDR                   (INST2_CONN_WT_SLP_CTL_REG_BASE + 0x0200)


#define INST2_CONN_WT_SLP_CTL_REG_WB_SLP_TOP_CK_5_WB_SLP_TOP_CK_5_BSY_ADDR \
	INST2_CONN_WT_SLP_CTL_REG_WB_SLP_TOP_CK_5_ADDR
#define INST2_CONN_WT_SLP_CTL_REG_WB_SLP_TOP_CK_5_WB_SLP_TOP_CK_5_BSY_MASK 0x00000002
#define INST2_CONN_WT_SLP_CTL_REG_WB_SLP_TOP_CK_5_WB_SLP_TOP_CK_5_BSY_SHFT 1
#define INST2_CONN_WT_SLP_CTL_REG_WB_SLP_TOP_CK_5_WB_SLP_TOP_CK_5_ADDR \
	INST2_CONN_WT_SLP_CTL_REG_WB_SLP_TOP_CK_5_ADDR
#define INST2_CONN_WT_SLP_CTL_REG_WB_SLP_TOP_CK_5_WB_SLP_TOP_CK_5_MASK 0x00000001
#define INST2_CONN_WT_SLP_CTL_REG_WB_SLP_TOP_CK_5_WB_SLP_TOP_CK_5_SHFT 0

#define INST2_CONN_WT_SLP_CTL_REG_WB_GPS_CTL_GPS_HW_MODE_EN_ADDR     \
	INST2_CONN_WT_SLP_CTL_REG_WB_GPS_CTL_ADDR
#define INST2_CONN_WT_SLP_CTL_REG_WB_GPS_CTL_GPS_HW_MODE_EN_MASK     0x00000001
#define INST2_CONN_WT_SLP_CTL_REG_WB_GPS_CTL_GPS_HW_MODE_EN_SHFT     0

#endif /* __INST2_CONN_WT_SLP_CTL_REG_REGS_H__ */

