/*
 *  For doorbell validation definitions
 */

#ifndef _KBASE_CSF_DB_VALID_DEFS_H_
#define _KBASE_CSF_DB_VALID_DEFS_H_

/* CSFFW interface input/output page */
#define DBVALID_IFACE_IO_PAGE_RESULT			0x0200
#define DBVALID_IFACE_IO_PAGE_RING_QUEUE		0x0400


/* doorbell validation result */
#define DBVALID_RESULT_SIZE				64
#define DBVALID_RESULT_BUFFER_SIZE		(DBVALID_RESULT_SIZE << 1)


/* DBVALID_REQ register */
#define GLB_REQ_DBVALID_EVENT_SHIFT 	(28)
#define GLB_REQ_DBVALID_EVENT_MASK 		(1 << GLB_REQ_DBVALID_EVENT_SHIFT)

#define DBVALID_REQ 					0x0FF0
#define DBVALID_REQ_RESULT_UPDATE_SHIFT (0)
#define DBVALID_REQ_RESULT_UPDATE_MASK 	(1 << DBVALID_REQ_RESULT_UPDATE_SHIFT)

#define DBVALID_ACK 					0x0FF0
#define DBVALID_ACK_RESULT_UPDATE_SHIFT (0)
#define DBVALID_ACK_RESULT_UPDATE_MASK 	(1 << DBVALID_REQ_RESULT_UPDATE_SHIFT)



#endif // _KBASE_CSF_DB_VALID_DEFS_H_