export MTK_PLATFORM_VERSION := mt6833

obj-m += mali_avalon/mali-r49p1/drivers/gpu/arm/midgard/
obj-m += mali_avalon/mali-r49p1/drivers/base/arm/memory_group_manager/
obj-m += mali_avalon/mali-r49p1/drivers/base/arm/protected_memory_allocator/
obj-m += mali_avalon/mali-r49p1/drivers/base/arm/dma_buf_test_exporter/