/*  SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2019 MediaTek Inc.
 */

#ifndef _CONNINFRA_STEP_BASE_H_
#define _CONNINFRA_STEP_BASE_H_

enum step_drv_type {
	STEP_DRV_TYPE_NO_DEFINE = 0,
	STEP_DRV_TYPE_CONNINFRA,
	STEP_DRV_TYPE_BT,
	STEP_DRV_TYPE_FM,
	STEP_DRV_TYPE_GPS,
	STEP_DRV_TYPE_WIFI,

	STEP_DRV_TYPE_MAX,
};

enum step_func_event_id {
	STEP_FUNC_OFF = 0,
	STEP_FUNC_ON
};

enum step_condition_operator_id {
	STEP_OPERATOR_GREATER = 0,
	STEP_OPERATOR_GREATER_EQUAL,
	STEP_OPERATOR_LESS,
	STEP_OPERATOR_LESS_EQUAL,
	STEP_OPERATOR_EQUAL,
	STEP_OPERATOR_NOT_EQUAL,
	STEP_OPERATOR_AND,
	STEP_OPERATOR_OR,
	STEP_OPERATOR_MAX,
};



enum step_action_id {
	STEP_ACTION_INDEX_NO_DEFINE = 0,
	STEP_ACTION_INDEX_EMI = 1,
	STEP_ACTION_INDEX_REGISTER,
	STEP_ACTION_INDEX_GPIO,
	STEP_ACTION_INDEX_PERIODIC_DUMP,
	STEP_ACTION_INDEX_SHOW_STRING,
	STEP_ACTION_INDEX_SLEEP,
	STEP_ACTION_INDEX_CONDITION,
	STEP_ACTION_INDEX_VALUE,
	STEP_ACTION_INDEX_CONDITION_EMI,
	STEP_ACTION_INDEX_CONDITION_REGISTER,
	STEP_ACTION_INDEX_MAX,
};


#endif /* end of _CONNINFRA_STEP_BASE_H_ */

