# SPDX-License-Identifier: GPL-2.0-only
# Support GKI mixed build
ifeq ($(DEVICE_MODULES_PATH),)
DEVICE_MODULES_PATH = $(srctree)
else
LINUXINCLUDE := $(DEVCIE_MODULES_INCLUDE) $(LINUXINCLUDE)
endif

KO_PATH := $(if $(filter /%,$(src)),,$(srctree)/)$(src)

$(info $(DEVICE_MODULES_PATH))
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/smi/
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/mtk-interconnect/
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/iommu
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/iommu
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include/mt-plat/
ccflags-$(CONFIG_MTK_IOMMU_V2) += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
ccflags-y += -I$(KO_PATH)/../camsys/isp8/cam

NOTDIR_DEVICE_MODULES_PATH = $(notdir $(DEVICE_MODULES_PATH))
KERNEL_VERSION = $(patsubst kernel_device_modules-%,%,$(NOTDIR_DEVICE_MODULES_PATH))
#$(info pda sort=$(sort 6.6 $(KERNEL_VERSION)))
#$(info pda word=$(word 1,$(sort 6.6 $(KERNEL_VERSION))))
ifeq (6.6,$(word 1,$(sort 6.6 $(KERNEL_VERSION))))
ccflags-y += -DDMA_BUF_UNLOCKED_API
endif

# driver module
#obj-m := camera_pda_dummy.o
ifneq ($(wildcard $(KO_PATH)/isp_8/pda_mt6991.c),)
obj-m += pda_drv_mt6991.o
endif
ifneq ($(wildcard $(KO_PATH)/isp_8/pda_mt6899.c),)
obj-m += pda_drv_mt6899.o
endif
obj-m += pda_drv_dummy.o

pda_drv_mt6991-objs := isp_8/camera_pda.o isp_8/pda_mt6991.o
pda_drv_mt6899-objs := isp_8/camera_pda.o isp_8/pda_mt6899.o
pda_drv_dummy-objs := isp_8/camera_pda.o isp_8/pda_dummy.o