# SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note
#
# (C) COPYRIGHT 2021-2023 ARM Limited. All rights reserved.
#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU license.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, you can access it online at
# http://www.gnu.org/licenses/gpl-2.0.html.
#
#

ifeq ($(CONFIG_MALI_KUTF_KERNEL_DEFECT_TEST), y)
obj-m := mali_kutf_kernel_defect_test.o

mali_kutf_kernel_defect_test-y := \
    mali_kutf_kernel_defect_GPUCORE-27226.o \
    mali_kutf_kernel_defect_GPUCORE-35490.o \
    mali_kutf_kernel_defect_GPUCORE-37201.o \
    mali_kutf_kernel_defect_GPUCORE-37465.o \
    mali_kutf_kernel_defect_GPUCORE-39614.o \
    mali_kutf_kernel_defect_test_main.o
endif
