################################################################################
# Include Path
################################################################################
MET_VCOREDVFS_INC := $(srctree)/drivers/misc/mediatek/base/power/include/vcorefs_v3
MET_PTPOD_INC := $(srctree)/drivers/misc/mediatek/base/power/cpufreq_v1/src/mach/$(MTK_PLATFORM)/

################################################################################
# Feature Spec
# CPUPMU_VERSION: V8_0/V8_2
################################################################################
CPUPMU_VERSION := V8_0

################################################################################
# Feature On/Off
################################################################################
FEATURE_SSPM_EMI := on
FEATURE_GPU := on
FEATURE_VCOREDVFS := on
FEATURE_PTPOD := on
FEATURE_ONDIEMET := on
