/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2023 MediaTek Inc.
 */
//[File]            : conn_bus_cr_on.h
//[Revision time]   : Thu Aug 31 15:23:49 2023

#ifndef __CONN_BUS_CR_ON_REGS_H__
#define __CONN_BUS_CR_ON_REGS_H__

#ifdef __cplusplus
extern "C" {
#endif


//****************************************************************************
//
//                     CONN_BUS_CR_ON CR Definitions                     
//
//****************************************************************************

#define CONN_BUS_CR_ON_BASE                                    (CONN_BUS_CR_ON_BASE_ADDR_MT6991) // 0x4000E000

#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_IDLE_CTRL_0_ADDR     (CONN_BUS_CR_ON_BASE + 0x000) // E000
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_IDLE_CTRL_1_ADDR     (CONN_BUS_CR_ON_BASE + 0x004) // E004
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_STATUS_ADDR  (CONN_BUS_CR_ON_BASE + 0x020) // E020
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_ADDR    (CONN_BUS_CR_ON_BASE + 0x024) // E024
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_0_ADDR (CONN_BUS_CR_ON_BASE + 0x028) // E028
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_1_ADDR (CONN_BUS_CR_ON_BASE + 0x02C) // E02C
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_2_ADDR (CONN_BUS_CR_ON_BASE + 0x030) // E030
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_STATUS_ADDR   (CONN_BUS_CR_ON_BASE + 0x034) // E034
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_ADDR     (CONN_BUS_CR_ON_BASE + 0x038) // E038
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_0_ADDR (CONN_BUS_CR_ON_BASE + 0x03C) // E03C
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_1_ADDR (CONN_BUS_CR_ON_BASE + 0x040) // E040
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_2_ADDR (CONN_BUS_CR_ON_BASE + 0x044) // E044
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_APB_ID_ADDR   (CONN_BUS_CR_ON_BASE + 0x048) // E048
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_AXI_GALS_RX_CFG_ADDR (CONN_BUS_CR_ON_BASE + 0x0C4) // E0C4
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_DEC_CFG_ADDR         (CONN_BUS_CR_ON_BASE + 0x0CC) // E0CC
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_X2H_CFG_ADDR         (CONN_BUS_CR_ON_BASE + 0x0D8) // E0D8
#define CONN_BUS_CR_ON_CONN_INFRA_ON_HOST_CSR_DEC_CFG_ADDR     (CONN_BUS_CR_ON_BASE + 0x0E8) // E0E8
#define CONN_BUS_CR_ON_CONN_INFRA_ON_OCIP_P2P_CFG_ADDR         (CONN_BUS_CR_ON_BASE + 0x0EC) // E0EC
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_ADDR             (CONN_BUS_CR_ON_BASE + 0x100) // E100
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_ADDR             (CONN_BUS_CR_ON_BASE + 0x104) // E104
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_CK_DCM_ADDR           (CONN_BUS_CR_ON_BASE + 0x108) // E108
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_ADDR             (CONN_BUS_CR_ON_BASE + 0x10C) // E10C
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_ADDR             (CONN_BUS_CR_ON_BASE + 0x110) // E110
#define CONN_BUS_CR_ON_CONN_INFRA_APB_SLV_ACCESS_DETECT_EN_ADDR (CONN_BUS_CR_ON_BASE + 0x114) // E114
#define CONN_BUS_CR_ON_CONN_INFRA_CKSYS_CK_CTRL_ADDR           (CONN_BUS_CR_ON_BASE + 0x120) // E120




/* =====================================================================================

  ---CONN_INFRA_VON_BUS_IDLE_CTRL_0 (0x1800E000 + 0x000)---

    VON_BUS_IDLE_MASK[16..0]     - (RW) conn_infra von bus idle mask
    RESERVED17[31..17]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_IDLE_CTRL_0_VON_BUS_IDLE_MASK_ADDR CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_IDLE_CTRL_0_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_IDLE_CTRL_0_VON_BUS_IDLE_MASK_MASK 0x0001FFFF                // VON_BUS_IDLE_MASK[16..0]
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_IDLE_CTRL_0_VON_BUS_IDLE_MASK_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_VON_BUS_IDLE_CTRL_1 (0x1800E000 + 0x004)---

    VON_BUS_IDLE_DEBOUNCE[4..0]  - (RW) conn_infra von bus idle debounce
    RESERVED5[31..5]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_IDLE_CTRL_1_VON_BUS_IDLE_DEBOUNCE_ADDR CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_IDLE_CTRL_1_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_IDLE_CTRL_1_VON_BUS_IDLE_DEBOUNCE_MASK 0x0000001F                // VON_BUS_IDLE_DEBOUNCE[4..0]
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_IDLE_CTRL_1_VON_BUS_IDLE_DEBOUNCE_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_VON_BUS_TIMEOUT_STATUS (0x1800E000 + 0x020)---

    TIMEOUT_STATUS[0]            - (RO) conn_von_bus apb timeout
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_STATUS_TIMEOUT_STATUS_ADDR CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_STATUS_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_STATUS_TIMEOUT_STATUS_MASK 0x00000001                // TIMEOUT_STATUS[0]
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_STATUS_TIMEOUT_STATUS_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_VON_BUS_TIMEOUT_CTRL (0x1800E000 + 0x024)---

    TIMEOUT_ENABLE[0]            - (RW) 1'b1:conn_von_bus timeout function
    TIMEOUT_CLEAR[1]             - (RW) write 1'b0 after write 1'b1 to clear timeout information
    FORCE_RESPONSE_HIGH[2]       - (RW) force bus response ready high
    TIMEOUT_TIME_SETTING[10..3]  - (RW) timeout timming setting with free run clock counter
    RESERVED11[31..11]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_TIMEOUT_TIME_SETTING_ADDR CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_TIMEOUT_TIME_SETTING_MASK 0x000007F8                // TIMEOUT_TIME_SETTING[10..3]
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_TIMEOUT_TIME_SETTING_SHFT 3
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_FORCE_RESPONSE_HIGH_ADDR CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_FORCE_RESPONSE_HIGH_MASK 0x00000004                // FORCE_RESPONSE_HIGH[2]
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_FORCE_RESPONSE_HIGH_SHFT 2
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_TIMEOUT_CLEAR_ADDR CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_TIMEOUT_CLEAR_MASK 0x00000002                // TIMEOUT_CLEAR[1]
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_TIMEOUT_CLEAR_SHFT 1
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_TIMEOUT_ENABLE_ADDR CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_TIMEOUT_ENABLE_MASK 0x00000001                // TIMEOUT_ENABLE[0]
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_TIMEOUT_CTRL_TIMEOUT_ENABLE_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_0 (0x1800E000 + 0x028)---

    APB_TIMEOUT_INFO[31..0]      - (RO) depends on timeout apb slave will mapping to different psel and pwrite information

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_0_APB_TIMEOUT_INFO_ADDR CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_0_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_0_APB_TIMEOUT_INFO_MASK 0xFFFFFFFF                // APB_TIMEOUT_INFO[31..0]
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_0_APB_TIMEOUT_INFO_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_1 (0x1800E000 + 0x02C)---

    APB_TIMEOUT_ADDR[31..0]      - (RO) timeout address

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_1_APB_TIMEOUT_ADDR_ADDR CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_1_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_1_APB_TIMEOUT_ADDR_MASK 0xFFFFFFFF                // APB_TIMEOUT_ADDR[31..0]
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_1_APB_TIMEOUT_ADDR_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_2 (0x1800E000 + 0x030)---

    APB_TIMEOUT_WRITE_DATA[31..0] - (RO) timeout write data if write

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_2_APB_TIMEOUT_WRITE_DATA_ADDR CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_2_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_2_APB_TIMEOUT_WRITE_DATA_MASK 0xFFFFFFFF                // APB_TIMEOUT_WRITE_DATA[31..0]
#define CONN_BUS_CR_ON_CONN_INFRA_VON_BUS_APB_TIMEOUT_INFO_2_APB_TIMEOUT_WRITE_DATA_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_ON_BUS_TIMEOUT_STATUS (0x1800E000 + 0x034)---

    TIMEOUT_STATUS[0]            - (RO) conn_infra_on_bus apb timeout
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_STATUS_TIMEOUT_STATUS_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_STATUS_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_STATUS_TIMEOUT_STATUS_MASK 0x00000001                // TIMEOUT_STATUS[0]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_STATUS_TIMEOUT_STATUS_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_ON_BUS_TIMEOUT_CTRL (0x1800E000 + 0x038)---

    TIMEOUT_ENABLE[0]            - (RW) 1'b1:conn_infra_on_bus timeout function
    TIMEOUT_CLEAR[1]             - (RW) write 1'b0 after write 1'b1 to clear timeout information
    FORCE_RESPONSE_HIGH[2]       - (RW) force bus response ready high
    TIMEOUT_TIME_SETTING[10..3]  - (RW) timeout timming setting with free run clock counter
    RESERVED11[31..11]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_TIMEOUT_TIME_SETTING_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_TIMEOUT_TIME_SETTING_MASK 0x000007F8                // TIMEOUT_TIME_SETTING[10..3]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_TIMEOUT_TIME_SETTING_SHFT 3
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_FORCE_RESPONSE_HIGH_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_FORCE_RESPONSE_HIGH_MASK 0x00000004                // FORCE_RESPONSE_HIGH[2]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_FORCE_RESPONSE_HIGH_SHFT 2
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_TIMEOUT_CLEAR_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_TIMEOUT_CLEAR_MASK 0x00000002                // TIMEOUT_CLEAR[1]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_TIMEOUT_CLEAR_SHFT 1
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_TIMEOUT_ENABLE_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_TIMEOUT_ENABLE_MASK 0x00000001                // TIMEOUT_ENABLE[0]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_CTRL_TIMEOUT_ENABLE_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_0 (0x1800E000 + 0x03C)---

    APB_TIMEOUT_INFO[31..0]      - (RO) depends on timeout apb slave will mapping to different psel and pwrite information

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_0_APB_TIMEOUT_INFO_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_0_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_0_APB_TIMEOUT_INFO_MASK 0xFFFFFFFF                // APB_TIMEOUT_INFO[31..0]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_0_APB_TIMEOUT_INFO_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_1 (0x1800E000 + 0x040)---

    APB_TIMEOUT_ADDR[31..0]      - (RO) timeout address

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_1_APB_TIMEOUT_ADDR_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_1_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_1_APB_TIMEOUT_ADDR_MASK 0xFFFFFFFF                // APB_TIMEOUT_ADDR[31..0]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_1_APB_TIMEOUT_ADDR_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_2 (0x1800E000 + 0x044)---

    APB_TIMEOUT_WRITE_DATA[31..0] - (RO) timeout write data if write

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_2_APB_TIMEOUT_WRITE_DATA_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_2_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_2_APB_TIMEOUT_WRITE_DATA_MASK 0xFFFFFFFF                // APB_TIMEOUT_WRITE_DATA[31..0]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_APB_TIMEOUT_INFO_2_APB_TIMEOUT_WRITE_DATA_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_ON_BUS_TIMEOUT_APB_ID (0x1800E000 + 0x048)---

    APB_TIMEOUT_APB_ID[6..0]     - (RO) [6:0] apb id
    APB_TIMEOUT_APB_DOMAIN_ID[10..7] - (RO) [10:7] apb domian id
    RESERVED11[31..11]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_APB_ID_APB_TIMEOUT_APB_DOMAIN_ID_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_APB_ID_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_APB_ID_APB_TIMEOUT_APB_DOMAIN_ID_MASK 0x00000780                // APB_TIMEOUT_APB_DOMAIN_ID[10..7]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_APB_ID_APB_TIMEOUT_APB_DOMAIN_ID_SHFT 7
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_APB_ID_APB_TIMEOUT_APB_ID_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_APB_ID_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_APB_ID_APB_TIMEOUT_APB_ID_MASK 0x0000007F                // APB_TIMEOUT_APB_ID[6..0]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_TIMEOUT_APB_ID_APB_TIMEOUT_APB_ID_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_AP2CONN_AXI_GALS_RX_CFG (0x1800E000 + 0x0C4)---

    AP2CONN_AXI_MST_SYNC_SEL[1..0] - (RW)  xxx 
    AP2CONN_AXI_SLV_SYNC_SEL[3..2] - (RW)  xxx 
    AP2CONN_AXI_GALS_SAMPLE_SEL[4] - (RW) SAMPLE SEL MUST = 1
    RESERVED5[31..5]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_AXI_GALS_RX_CFG_AP2CONN_AXI_GALS_SAMPLE_SEL_ADDR CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_AXI_GALS_RX_CFG_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_AXI_GALS_RX_CFG_AP2CONN_AXI_GALS_SAMPLE_SEL_MASK 0x00000010                // AP2CONN_AXI_GALS_SAMPLE_SEL[4]
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_AXI_GALS_RX_CFG_AP2CONN_AXI_GALS_SAMPLE_SEL_SHFT 4
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_AXI_GALS_RX_CFG_AP2CONN_AXI_SLV_SYNC_SEL_ADDR CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_AXI_GALS_RX_CFG_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_AXI_GALS_RX_CFG_AP2CONN_AXI_SLV_SYNC_SEL_MASK 0x0000000C                // AP2CONN_AXI_SLV_SYNC_SEL[3..2]
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_AXI_GALS_RX_CFG_AP2CONN_AXI_SLV_SYNC_SEL_SHFT 2
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_AXI_GALS_RX_CFG_AP2CONN_AXI_MST_SYNC_SEL_ADDR CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_AXI_GALS_RX_CFG_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_AXI_GALS_RX_CFG_AP2CONN_AXI_MST_SYNC_SEL_MASK 0x00000003                // AP2CONN_AXI_MST_SYNC_SEL[1..0]
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_AXI_GALS_RX_CFG_AP2CONN_AXI_MST_SYNC_SEL_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_AP2CONN_DEC_CFG (0x1800E000 + 0x0CC)---

    CONN_VON_BUS_AXI_DEC_SI_WAY_EN[1..0] - (RW) address decode output path enable of each way
    CONN_VON_BUS_AXI_DEC_SI_WAY_INTERLEAVE_EN[3..2] - (RW) slave interface read arbiter interleaving function enable control
    CONN_VON_BUS_AXI_DEC_SI_WAY_OSTD_DIS[4] - (RW) slave interface outstanding capability disable control
    CONN_VON_BUS_AXI_DEC_SI_CTRL_BYPASS[5] - (RW)  xxx 
    CONN_VON_BUS_AXI_DEC_SI_WAY_CG_DIS[6] - (RW)  xxx 
    RESERVED7[31..7]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_DEC_CFG_CONN_VON_BUS_AXI_DEC_SI_WAY_CG_DIS_ADDR CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_DEC_CFG_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_DEC_CFG_CONN_VON_BUS_AXI_DEC_SI_WAY_CG_DIS_MASK 0x00000040                // CONN_VON_BUS_AXI_DEC_SI_WAY_CG_DIS[6]
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_DEC_CFG_CONN_VON_BUS_AXI_DEC_SI_WAY_CG_DIS_SHFT 6
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_DEC_CFG_CONN_VON_BUS_AXI_DEC_SI_CTRL_BYPASS_ADDR CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_DEC_CFG_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_DEC_CFG_CONN_VON_BUS_AXI_DEC_SI_CTRL_BYPASS_MASK 0x00000020                // CONN_VON_BUS_AXI_DEC_SI_CTRL_BYPASS[5]
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_DEC_CFG_CONN_VON_BUS_AXI_DEC_SI_CTRL_BYPASS_SHFT 5
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_DEC_CFG_CONN_VON_BUS_AXI_DEC_SI_WAY_OSTD_DIS_ADDR CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_DEC_CFG_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_DEC_CFG_CONN_VON_BUS_AXI_DEC_SI_WAY_OSTD_DIS_MASK 0x00000010                // CONN_VON_BUS_AXI_DEC_SI_WAY_OSTD_DIS[4]
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_DEC_CFG_CONN_VON_BUS_AXI_DEC_SI_WAY_OSTD_DIS_SHFT 4
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_DEC_CFG_CONN_VON_BUS_AXI_DEC_SI_WAY_INTERLEAVE_EN_ADDR CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_DEC_CFG_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_DEC_CFG_CONN_VON_BUS_AXI_DEC_SI_WAY_INTERLEAVE_EN_MASK 0x0000000C                // CONN_VON_BUS_AXI_DEC_SI_WAY_INTERLEAVE_EN[3..2]
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_DEC_CFG_CONN_VON_BUS_AXI_DEC_SI_WAY_INTERLEAVE_EN_SHFT 2
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_DEC_CFG_CONN_VON_BUS_AXI_DEC_SI_WAY_EN_ADDR CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_DEC_CFG_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_DEC_CFG_CONN_VON_BUS_AXI_DEC_SI_WAY_EN_MASK 0x00000003                // CONN_VON_BUS_AXI_DEC_SI_WAY_EN[1..0]
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_DEC_CFG_CONN_VON_BUS_AXI_DEC_SI_WAY_EN_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_AP2CONN_X2H_CFG (0x1800E000 + 0x0D8)---

    CONN_VON_BUS_A2H_BUFFER_EN[0] - (RW)  xxx 
    CONN_VON_BUS_A2H_BURST_EN[1] - (RW)  xxx 
    CONN_VON_BUS_A2H_ARTHRE[4..2] - (RW)  xxx 
    CONN_VON_BUS_A2H_ARMSK_B[5]  - (RW)  xxx 
    CONN_VON_BUS_A2H_AWBURST[8..6] - (RW)  xxx 
    CONN_VON_BUS_A2H_ARBURST[11..9] - (RW)  xxx 
    CONN_VON_BUS_A2H_FLUSH_THRES[13..12] - (RW)  xxx 
    CONN_VON_BUS_A2H_BYPASS_MODE[14] - (RW)  xxx 
    RESERVED15[31..15]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_X2H_CFG_CONN_VON_BUS_A2H_BYPASS_MODE_ADDR CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_X2H_CFG_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_X2H_CFG_CONN_VON_BUS_A2H_BYPASS_MODE_MASK 0x00004000                // CONN_VON_BUS_A2H_BYPASS_MODE[14]
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_X2H_CFG_CONN_VON_BUS_A2H_BYPASS_MODE_SHFT 14
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_X2H_CFG_CONN_VON_BUS_A2H_FLUSH_THRES_ADDR CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_X2H_CFG_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_X2H_CFG_CONN_VON_BUS_A2H_FLUSH_THRES_MASK 0x00003000                // CONN_VON_BUS_A2H_FLUSH_THRES[13..12]
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_X2H_CFG_CONN_VON_BUS_A2H_FLUSH_THRES_SHFT 12
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_X2H_CFG_CONN_VON_BUS_A2H_ARBURST_ADDR CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_X2H_CFG_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_X2H_CFG_CONN_VON_BUS_A2H_ARBURST_MASK 0x00000E00                // CONN_VON_BUS_A2H_ARBURST[11..9]
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_X2H_CFG_CONN_VON_BUS_A2H_ARBURST_SHFT 9
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_X2H_CFG_CONN_VON_BUS_A2H_AWBURST_ADDR CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_X2H_CFG_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_X2H_CFG_CONN_VON_BUS_A2H_AWBURST_MASK 0x000001C0                // CONN_VON_BUS_A2H_AWBURST[8..6]
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_X2H_CFG_CONN_VON_BUS_A2H_AWBURST_SHFT 6
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_X2H_CFG_CONN_VON_BUS_A2H_ARMSK_B_ADDR CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_X2H_CFG_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_X2H_CFG_CONN_VON_BUS_A2H_ARMSK_B_MASK 0x00000020                // CONN_VON_BUS_A2H_ARMSK_B[5]
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_X2H_CFG_CONN_VON_BUS_A2H_ARMSK_B_SHFT 5
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_X2H_CFG_CONN_VON_BUS_A2H_ARTHRE_ADDR CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_X2H_CFG_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_X2H_CFG_CONN_VON_BUS_A2H_ARTHRE_MASK 0x0000001C                // CONN_VON_BUS_A2H_ARTHRE[4..2]
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_X2H_CFG_CONN_VON_BUS_A2H_ARTHRE_SHFT 2
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_X2H_CFG_CONN_VON_BUS_A2H_BURST_EN_ADDR CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_X2H_CFG_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_X2H_CFG_CONN_VON_BUS_A2H_BURST_EN_MASK 0x00000002                // CONN_VON_BUS_A2H_BURST_EN[1]
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_X2H_CFG_CONN_VON_BUS_A2H_BURST_EN_SHFT 1
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_X2H_CFG_CONN_VON_BUS_A2H_BUFFER_EN_ADDR CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_X2H_CFG_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_X2H_CFG_CONN_VON_BUS_A2H_BUFFER_EN_MASK 0x00000001                // CONN_VON_BUS_A2H_BUFFER_EN[0]
#define CONN_BUS_CR_ON_CONN_INFRA_AP2CONN_X2H_CFG_CONN_VON_BUS_A2H_BUFFER_EN_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_ON_HOST_CSR_DEC_CFG (0x1800E000 + 0x0E8)---

    HOST_CSR_U_DEC_APB_DECODER_WAY_EN[1..0] - (RW) host csr non-security domain & security domain decoder
    RESERVED2[31..2]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_ON_HOST_CSR_DEC_CFG_HOST_CSR_U_DEC_APB_DECODER_WAY_EN_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_HOST_CSR_DEC_CFG_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_HOST_CSR_DEC_CFG_HOST_CSR_U_DEC_APB_DECODER_WAY_EN_MASK 0x00000003                // HOST_CSR_U_DEC_APB_DECODER_WAY_EN[1..0]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_HOST_CSR_DEC_CFG_HOST_CSR_U_DEC_APB_DECODER_WAY_EN_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_ON_OCIP_P2P_CFG (0x1800E000 + 0x0EC)---

    OFF2ON_0_S13_ERROR_FLAG_EN[0] - (RW)  xxx 
    OFF2ON_0_S13_ERROR_CLOCK_CG_EN[1] - (RW)  xxx 
    RESERVED2[31..2]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_ON_OCIP_P2P_CFG_OFF2ON_0_S13_ERROR_CLOCK_CG_EN_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_OCIP_P2P_CFG_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_OCIP_P2P_CFG_OFF2ON_0_S13_ERROR_CLOCK_CG_EN_MASK 0x00000002                // OFF2ON_0_S13_ERROR_CLOCK_CG_EN[1]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_OCIP_P2P_CFG_OFF2ON_0_S13_ERROR_CLOCK_CG_EN_SHFT 1
#define CONN_BUS_CR_ON_CONN_INFRA_ON_OCIP_P2P_CFG_OFF2ON_0_S13_ERROR_FLAG_EN_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_OCIP_P2P_CFG_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_OCIP_P2P_CFG_OFF2ON_0_S13_ERROR_FLAG_EN_MASK 0x00000001                // OFF2ON_0_S13_ERROR_FLAG_EN[0]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_OCIP_P2P_CFG_OFF2ON_0_S13_ERROR_FLAG_EN_SHFT 0

/* =====================================================================================

  ---CONN_VON_BUS_DCM_CTL_0 (0x1800E000 + 0x100)---

    HCLK_SC_AXI_DCM_DIS[0]       - (RW)  xxx 
    HCLK_CK_RDY_ON_DCM[1]        - (RO)  xxx 
    HCLK_CK_DCM_IDLE[2]          - (RO)  xxx 
    HCLK_DEBOUNCE_EN[3]          - (RW)  xxx 
    HCLK_DEBOUNCE_NUM[15..4]     - (RW)  xxx 
    RESERVED16[31..16]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_HCLK_DEBOUNCE_NUM_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_HCLK_DEBOUNCE_NUM_MASK 0x0000FFF0                // HCLK_DEBOUNCE_NUM[15..4]
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_HCLK_DEBOUNCE_NUM_SHFT 4
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_HCLK_DEBOUNCE_EN_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_HCLK_DEBOUNCE_EN_MASK 0x00000008                // HCLK_DEBOUNCE_EN[3]
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_HCLK_DEBOUNCE_EN_SHFT 3
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_HCLK_CK_DCM_IDLE_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_HCLK_CK_DCM_IDLE_MASK 0x00000004                // HCLK_CK_DCM_IDLE[2]
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_HCLK_CK_DCM_IDLE_SHFT 2
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_HCLK_CK_RDY_ON_DCM_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_HCLK_CK_RDY_ON_DCM_MASK 0x00000002                // HCLK_CK_RDY_ON_DCM[1]
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_HCLK_CK_RDY_ON_DCM_SHFT 1
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_HCLK_SC_AXI_DCM_DIS_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_HCLK_SC_AXI_DCM_DIS_MASK 0x00000001                // HCLK_SC_AXI_DCM_DIS[0]
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_0_HCLK_SC_AXI_DCM_DIS_SHFT 0

/* =====================================================================================

  ---CONN_VON_BUS_DCM_CTL_1 (0x1800E000 + 0x104)---

    IDLE_CK_DCM_LEVEL_SEL[4..0]  - (RW)  xxx 
    BUSY_CK_DCM_LEVEL_SEL[9..5]  - (RW)  xxx 
    FORCE_FREE_RUN[10]           - (RW)  xxx 
    FORCE_SLOW[11]               - (RW)  xxx 
    FORCE_OFF[12]                - (RW)  xxx 
    SLOW_MODE_ENABLE[13]         - (RW)  xxx 
    OFF_MODE_ENABLE[14]          - (RW)  xxx 
    CK_RDY_ON_DCM[15]            - (RW)  xxx 
    PLL_SEL_NO_SPM[16]           - (RW)  xxx 
    SC_AXI_DCM_DIS_EN[17]        - (RW)  xxx 
    RESERVED18[31..18]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_SC_AXI_DCM_DIS_EN_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_SC_AXI_DCM_DIS_EN_MASK 0x00020000                // SC_AXI_DCM_DIS_EN[17]
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_SC_AXI_DCM_DIS_EN_SHFT 17
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_PLL_SEL_NO_SPM_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_PLL_SEL_NO_SPM_MASK 0x00010000                // PLL_SEL_NO_SPM[16]
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_PLL_SEL_NO_SPM_SHFT 16
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_CK_RDY_ON_DCM_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_CK_RDY_ON_DCM_MASK 0x00008000                // CK_RDY_ON_DCM[15]
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_CK_RDY_ON_DCM_SHFT 15
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_OFF_MODE_ENABLE_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_OFF_MODE_ENABLE_MASK 0x00004000                // OFF_MODE_ENABLE[14]
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_OFF_MODE_ENABLE_SHFT 14
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_SLOW_MODE_ENABLE_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_SLOW_MODE_ENABLE_MASK 0x00002000                // SLOW_MODE_ENABLE[13]
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_SLOW_MODE_ENABLE_SHFT 13
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_FORCE_OFF_ADDR   CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_FORCE_OFF_MASK   0x00001000                // FORCE_OFF[12]
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_FORCE_OFF_SHFT   12
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_FORCE_SLOW_ADDR  CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_FORCE_SLOW_MASK  0x00000800                // FORCE_SLOW[11]
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_FORCE_SLOW_SHFT  11
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_FORCE_FREE_RUN_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_FORCE_FREE_RUN_MASK 0x00000400                // FORCE_FREE_RUN[10]
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_FORCE_FREE_RUN_SHFT 10
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_BUSY_CK_DCM_LEVEL_SEL_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_BUSY_CK_DCM_LEVEL_SEL_MASK 0x000003E0                // BUSY_CK_DCM_LEVEL_SEL[9..5]
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_BUSY_CK_DCM_LEVEL_SEL_SHFT 5
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_IDLE_CK_DCM_LEVEL_SEL_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_IDLE_CK_DCM_LEVEL_SEL_MASK 0x0000001F                // IDLE_CK_DCM_LEVEL_SEL[4..0]
#define CONN_BUS_CR_ON_CONN_VON_BUS_DCM_CTL_1_IDLE_CK_DCM_LEVEL_SEL_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_ON_BUS_CK_DCM (0x1800E000 + 0x108)---

    OSC_CK_FR_EN[0]              - (RW)  xxx 
    HOST_OSC_CK_FR_EN[1]         - (RW)  xxx 
    RESERVED2[31..2]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_CK_DCM_HOST_OSC_CK_FR_EN_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_CK_DCM_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_CK_DCM_HOST_OSC_CK_FR_EN_MASK 0x00000002                // HOST_OSC_CK_FR_EN[1]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_CK_DCM_HOST_OSC_CK_FR_EN_SHFT 1
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_CK_DCM_OSC_CK_FR_EN_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_CK_DCM_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_CK_DCM_OSC_CK_FR_EN_MASK 0x00000001                // OSC_CK_FR_EN[0]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_CK_DCM_OSC_CK_FR_EN_SHFT 0

/* =====================================================================================

  ---CONN_OFF_BUS_DCM_CTL_0 (0x1800E000 + 0x10C)---

    HCLK_SC_AXI_DCM_DIS[0]       - (RW)  xxx 
    HCLK_CK_RDY_ON_DCM[1]        - (RO)  xxx 
    HCLK_CK_DCM_IDLE[2]          - (RO)  xxx 
    HCLK_DEBOUNCE_EN[3]          - (RW)  xxx 
    HCLK_DEBOUNCE_NUM[15..4]     - (RW)  xxx 
    RESERVED16[31..16]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_HCLK_DEBOUNCE_NUM_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_HCLK_DEBOUNCE_NUM_MASK 0x0000FFF0                // HCLK_DEBOUNCE_NUM[15..4]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_HCLK_DEBOUNCE_NUM_SHFT 4
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_HCLK_DEBOUNCE_EN_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_HCLK_DEBOUNCE_EN_MASK 0x00000008                // HCLK_DEBOUNCE_EN[3]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_HCLK_DEBOUNCE_EN_SHFT 3
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_HCLK_CK_DCM_IDLE_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_HCLK_CK_DCM_IDLE_MASK 0x00000004                // HCLK_CK_DCM_IDLE[2]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_HCLK_CK_DCM_IDLE_SHFT 2
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_HCLK_CK_RDY_ON_DCM_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_HCLK_CK_RDY_ON_DCM_MASK 0x00000002                // HCLK_CK_RDY_ON_DCM[1]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_HCLK_CK_RDY_ON_DCM_SHFT 1
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_HCLK_SC_AXI_DCM_DIS_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_HCLK_SC_AXI_DCM_DIS_MASK 0x00000001                // HCLK_SC_AXI_DCM_DIS[0]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_0_HCLK_SC_AXI_DCM_DIS_SHFT 0

/* =====================================================================================

  ---CONN_OFF_BUS_DCM_CTL_1 (0x1800E000 + 0x110)---

    IDLE_CK_DCM_LEVEL_SEL[4..0]  - (RW)  xxx 
    BUSY_CK_DCM_LEVEL_SEL[9..5]  - (RW)  xxx 
    FORCE_FREE_RUN[10]           - (RW)  xxx 
    FORCE_SLOW[11]               - (RW)  xxx 
    FORCE_OFF[12]                - (RW)  xxx 
    SLOW_MODE_ENABLE[13]         - (RW)  xxx 
    OFF_MODE_ENABLE[14]          - (RW)  xxx 
    CK_RDY_ON_DCM[15]            - (RW)  xxx 
    PLL_SEL_NO_SPM[16]           - (RW)  xxx 
    SC_AXI_DCM_DIS_EN[17]        - (RW)  xxx 
    OSC_CK_FR_EN[18]             - (RW)  xxx 
    MASK_OFF_OSC_FR_EN_CTRL[19]  - (RW) 1'b0:mask off control
    MASK_OFF_DOMAIN_OFF_MODE_ENABLE_CTRL[20] - (RW) 1'b1:mask off control
    MASK_OFF_DOMAIN_SLOW_MODE_ENABLE_CTRL[21] - (RW) 1'b1:mask off control
    RESERVED22[31..22]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_MASK_OFF_DOMAIN_SLOW_MODE_ENABLE_CTRL_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_MASK_OFF_DOMAIN_SLOW_MODE_ENABLE_CTRL_MASK 0x00200000                // MASK_OFF_DOMAIN_SLOW_MODE_ENABLE_CTRL[21]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_MASK_OFF_DOMAIN_SLOW_MODE_ENABLE_CTRL_SHFT 21
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_MASK_OFF_DOMAIN_OFF_MODE_ENABLE_CTRL_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_MASK_OFF_DOMAIN_OFF_MODE_ENABLE_CTRL_MASK 0x00100000                // MASK_OFF_DOMAIN_OFF_MODE_ENABLE_CTRL[20]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_MASK_OFF_DOMAIN_OFF_MODE_ENABLE_CTRL_SHFT 20
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_MASK_OFF_OSC_FR_EN_CTRL_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_MASK_OFF_OSC_FR_EN_CTRL_MASK 0x00080000                // MASK_OFF_OSC_FR_EN_CTRL[19]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_MASK_OFF_OSC_FR_EN_CTRL_SHFT 19
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_OSC_CK_FR_EN_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_OSC_CK_FR_EN_MASK 0x00040000                // OSC_CK_FR_EN[18]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_OSC_CK_FR_EN_SHFT 18
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_SC_AXI_DCM_DIS_EN_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_SC_AXI_DCM_DIS_EN_MASK 0x00020000                // SC_AXI_DCM_DIS_EN[17]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_SC_AXI_DCM_DIS_EN_SHFT 17
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_PLL_SEL_NO_SPM_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_PLL_SEL_NO_SPM_MASK 0x00010000                // PLL_SEL_NO_SPM[16]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_PLL_SEL_NO_SPM_SHFT 16
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_CK_RDY_ON_DCM_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_CK_RDY_ON_DCM_MASK 0x00008000                // CK_RDY_ON_DCM[15]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_CK_RDY_ON_DCM_SHFT 15
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_OFF_MODE_ENABLE_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_OFF_MODE_ENABLE_MASK 0x00004000                // OFF_MODE_ENABLE[14]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_OFF_MODE_ENABLE_SHFT 14
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_SLOW_MODE_ENABLE_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_SLOW_MODE_ENABLE_MASK 0x00002000                // SLOW_MODE_ENABLE[13]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_SLOW_MODE_ENABLE_SHFT 13
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_FORCE_OFF_ADDR   CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_FORCE_OFF_MASK   0x00001000                // FORCE_OFF[12]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_FORCE_OFF_SHFT   12
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_FORCE_SLOW_ADDR  CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_FORCE_SLOW_MASK  0x00000800                // FORCE_SLOW[11]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_FORCE_SLOW_SHFT  11
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_FORCE_FREE_RUN_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_FORCE_FREE_RUN_MASK 0x00000400                // FORCE_FREE_RUN[10]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_FORCE_FREE_RUN_SHFT 10
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_BUSY_CK_DCM_LEVEL_SEL_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_BUSY_CK_DCM_LEVEL_SEL_MASK 0x000003E0                // BUSY_CK_DCM_LEVEL_SEL[9..5]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_BUSY_CK_DCM_LEVEL_SEL_SHFT 5
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_IDLE_CK_DCM_LEVEL_SEL_ADDR CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_IDLE_CK_DCM_LEVEL_SEL_MASK 0x0000001F                // IDLE_CK_DCM_LEVEL_SEL[4..0]
#define CONN_BUS_CR_ON_CONN_OFF_BUS_DCM_CTL_1_IDLE_CK_DCM_LEVEL_SEL_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_APB_SLV_ACCESS_DETECT_EN (0x1800E000 + 0x114)---

    CONN_INFRA_APB_SLV_ACCESS_DETECT_EN[0] - (WO) SW path for enable conn_infra off apb slave access detect function
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_APB_SLV_ACCESS_DETECT_EN_CONN_INFRA_APB_SLV_ACCESS_DETECT_EN_ADDR CONN_BUS_CR_ON_CONN_INFRA_APB_SLV_ACCESS_DETECT_EN_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_APB_SLV_ACCESS_DETECT_EN_CONN_INFRA_APB_SLV_ACCESS_DETECT_EN_MASK 0x00000001                // CONN_INFRA_APB_SLV_ACCESS_DETECT_EN[0]
#define CONN_BUS_CR_ON_CONN_INFRA_APB_SLV_ACCESS_DETECT_EN_CONN_INFRA_APB_SLV_ACCESS_DETECT_EN_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_CKSYS_CK_CTRL (0x1800E000 + 0x120)---

    HOST_CK_REQUEST_HW_MODE[0]   - (RW)  xxx 
    HOST_CK_REQUEST_SW_EN[1]     - (RW)  xxx 
    RESERVED2[31..2]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_CKSYS_CK_CTRL_HOST_CK_REQUEST_SW_EN_ADDR CONN_BUS_CR_ON_CONN_INFRA_CKSYS_CK_CTRL_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_CKSYS_CK_CTRL_HOST_CK_REQUEST_SW_EN_MASK 0x00000002                // HOST_CK_REQUEST_SW_EN[1]
#define CONN_BUS_CR_ON_CONN_INFRA_CKSYS_CK_CTRL_HOST_CK_REQUEST_SW_EN_SHFT 1
#define CONN_BUS_CR_ON_CONN_INFRA_CKSYS_CK_CTRL_HOST_CK_REQUEST_HW_MODE_ADDR CONN_BUS_CR_ON_CONN_INFRA_CKSYS_CK_CTRL_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_CKSYS_CK_CTRL_HOST_CK_REQUEST_HW_MODE_MASK 0x00000001                // HOST_CK_REQUEST_HW_MODE[0]
#define CONN_BUS_CR_ON_CONN_INFRA_CKSYS_CK_CTRL_HOST_CK_REQUEST_HW_MODE_SHFT 0

#ifdef __cplusplus
}
#endif

#endif // __CONN_BUS_CR_ON_REGS_H__
