/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */
#ifndef __CONN_INFRA_CFG_REGS_H__
#define __CONN_INFRA_CFG_REGS_H__

#define CONN_INFRA_CFG_BASE                                    0x18011000

#define CONN_INFRA_CFG_IP_VERSION_ADDR                         (CONN_INFRA_CFG_BASE + 0x0000)
#define CONN_INFRA_CFG_EMI_CTL_TOP_ADDR                        (CONN_INFRA_CFG_BASE + 0x0110)
#define CONN_INFRA_CFG_EMI_CTL_WF_ADDR                         (CONN_INFRA_CFG_BASE + 0x0114)
#define CONN_INFRA_CFG_EMI_CTL_BT_ADDR                         (CONN_INFRA_CFG_BASE + 0x0118)
#define CONN_INFRA_CFG_EMI_CTL_GPS_ADDR                        (CONN_INFRA_CFG_BASE + 0x011C)
#define CONN_INFRA_CFG_EMI_CTL_GPS_L1_ADDR                     (CONN_INFRA_CFG_BASE + 0X0120)


#define CONN_INFRA_CFG_IP_VERSION_IP_VERSION_ADDR              CONN_INFRA_CFG_IP_VERSION_ADDR
#define CONN_INFRA_CFG_IP_VERSION_IP_VERSION_MASK              0xFFFFFFFF
#define CONN_INFRA_CFG_IP_VERSION_IP_VERSION_SHFT              0

#define CONN_INFRA_CFG_EMI_CTL_TOP_EMI_REQ_TOP_ADDR            CONN_INFRA_CFG_EMI_CTL_TOP_ADDR
#define CONN_INFRA_CFG_EMI_CTL_TOP_EMI_REQ_TOP_MASK            0x00000001
#define CONN_INFRA_CFG_EMI_CTL_TOP_EMI_REQ_TOP_SHFT            0

#define CONN_INFRA_CFG_EMI_CTL_GPS_EMI_REQ_GPS_ADDR            CONN_INFRA_CFG_EMI_CTL_GPS_ADDR
#define CONN_INFRA_CFG_EMI_CTL_GPS_EMI_REQ_GPS_MASK            0x00000001
#define CONN_INFRA_CFG_EMI_CTL_GPS_EMI_REQ_GPS_SHFT            0

#define CONN_INFRA_CFG_EMI_CTL_GPS_L1_INFRA_REQ_GPS_L1_ADDR    CONN_INFRA_CFG_EMI_CTL_GPS_L1_ADDR
#define CONN_INFRA_CFG_EMI_CTL_GPS_L1_INFRA_REQ_GPS_L1_MASK    0x00000020
#define CONN_INFRA_CFG_EMI_CTL_GPS_L1_INFRA_REQ_GPS_L1_SHFT    5

#endif /* __CONN_INFRA_CFG_REGS_H__ */

