/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */
#ifndef __BGF_GPS_CFG_ON_REGS_H__
#define __BGF_GPS_CFG_ON_REGS_H__

#define BGF_GPS_CFG_ON_BASE                                    0x80001000

#define BGF_GPS_CFG_ON_GPS_L1_SLP_PWR_CTL_ADDR                 (BGF_GPS_CFG_ON_BASE + 0x0020)
#define BGF_GPS_CFG_ON_GPS_L5_SLP_PWR_CTL_ADDR                 (BGF_GPS_CFG_ON_BASE + 0x0024)
#define BGF_GPS_CFG_ON_GPS_TOP_OFF_PWR_CTL_ADDR                (BGF_GPS_CFG_ON_BASE + 0x002C)


#define BGF_GPS_CFG_ON_GPS_L1_SLP_PWR_CTL_GPS_L1_SLP_HWCTL_ADDR BGF_GPS_CFG_ON_GPS_L1_SLP_PWR_CTL_ADDR
#define BGF_GPS_CFG_ON_GPS_L1_SLP_PWR_CTL_GPS_L1_SLP_HWCTL_MASK 0x00000100
#define BGF_GPS_CFG_ON_GPS_L1_SLP_PWR_CTL_GPS_L1_SLP_HWCTL_SHFT 8
#define BGF_GPS_CFG_ON_GPS_L1_SLP_PWR_CTL_GPS_L1_SLP_PWR_CTL_CS_ADDR BGF_GPS_CFG_ON_GPS_L1_SLP_PWR_CTL_ADDR
#define BGF_GPS_CFG_ON_GPS_L1_SLP_PWR_CTL_GPS_L1_SLP_PWR_CTL_CS_MASK 0x0000000F
#define BGF_GPS_CFG_ON_GPS_L1_SLP_PWR_CTL_GPS_L1_SLP_PWR_CTL_CS_SHFT 0

#define BGF_GPS_CFG_ON_GPS_L5_SLP_PWR_CTL_GPS_L5_SLP_HWCTL_ADDR BGF_GPS_CFG_ON_GPS_L5_SLP_PWR_CTL_ADDR
#define BGF_GPS_CFG_ON_GPS_L5_SLP_PWR_CTL_GPS_L5_SLP_HWCTL_MASK 0x00000100
#define BGF_GPS_CFG_ON_GPS_L5_SLP_PWR_CTL_GPS_L5_SLP_HWCTL_SHFT 8
#define BGF_GPS_CFG_ON_GPS_L5_SLP_PWR_CTL_GPS_L5_SLP_PWR_CTL_CS_ADDR BGF_GPS_CFG_ON_GPS_L5_SLP_PWR_CTL_ADDR
#define BGF_GPS_CFG_ON_GPS_L5_SLP_PWR_CTL_GPS_L5_SLP_PWR_CTL_CS_MASK 0x0000000F
#define BGF_GPS_CFG_ON_GPS_L5_SLP_PWR_CTL_GPS_L5_SLP_PWR_CTL_CS_SHFT 0

#define BGF_GPS_CFG_ON_GPS_TOP_OFF_PWR_CTL_GPS_TOP_OFF_PWR_CTL_CS_ADDR BGF_GPS_CFG_ON_GPS_TOP_OFF_PWR_CTL_ADDR
#define BGF_GPS_CFG_ON_GPS_TOP_OFF_PWR_CTL_GPS_TOP_OFF_PWR_CTL_CS_MASK 0x0000000F
#define BGF_GPS_CFG_ON_GPS_TOP_OFF_PWR_CTL_GPS_TOP_OFF_PWR_CTL_CS_SHFT 0

#endif /* __BGF_GPS_CFG_ON_REGS_H__ */

