/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */

#ifndef __CSI0_CPHY_TOP_H__
#define __CSI0_CPHY_TOP_H__

#define CPHY_RX_CTRL 0x0000
#define CPHY_RX_TR0_LPRX_EN_SHIFT 0
#define CPHY_RX_TR0_LPRX_EN_MASK (0x1 << 0)
#define CPHY_RX_TR1_LPRX_EN_SHIFT 1
#define CPHY_RX_TR1_LPRX_EN_MASK (0x1 << 1)
#define CPHY_RX_TR2_LPRX_EN_SHIFT 2
#define CPHY_RX_TR2_LPRX_EN_MASK (0x1 << 2)
#define CPHY_RX_TR3_LPRX_EN_SHIFT 3
#define CPHY_RX_TR3_LPRX_EN_MASK (0x1 << 3)
#define CPHY_RX_TR0_HSRX_EN_SHIFT 4
#define CPHY_RX_TR0_HSRX_EN_MASK (0x1 << 4)
#define CPHY_RX_TR1_HSRX_EN_SHIFT 5
#define CPHY_RX_TR1_HSRX_EN_MASK (0x1 << 5)
#define CPHY_RX_TR2_HSRX_EN_SHIFT 6
#define CPHY_RX_TR2_HSRX_EN_MASK (0x1 << 6)
#define CPHY_RX_TR3_HSRX_EN_SHIFT 7
#define CPHY_RX_TR3_HSRX_EN_MASK (0x1 << 7)
#define CPHY_RX_TR0_BIST_EN_SHIFT 16
#define CPHY_RX_TR0_BIST_EN_MASK (0x1 << 16)
#define CPHY_RX_TR1_BIST_EN_SHIFT 17
#define CPHY_RX_TR1_BIST_EN_MASK (0x1 << 17)
#define CPHY_RX_TR2_BIST_EN_SHIFT 18
#define CPHY_RX_TR2_BIST_EN_MASK (0x1 << 18)
#define CPHY_RX_TR3_BIST_EN_SHIFT 19
#define CPHY_RX_TR3_BIST_EN_MASK (0x1 << 19)

#define CPHY_RX_OPT 0x0008
#define RG_CPHY_RX_PRBS_GEN_DATA_DELAY_EN_SHIFT 0
#define RG_CPHY_RX_PRBS_GEN_DATA_DELAY_EN_MASK (0x1 << 0)
#define RG_CPHY_RX_LP_MODE_SHIFT 1
#define RG_CPHY_RX_LP_MODE_MASK (0x1 << 1)
#define RG_CPHY_RX_SYNC_DETECT_OPT_SHIFT 4
#define RG_CPHY_RX_SYNC_DETECT_OPT_MASK (0x7 << 4)
#define RG_CPHY_RX_TR0_INIT_WIRE_STATE_SHIFT 16
#define RG_CPHY_RX_TR0_INIT_WIRE_STATE_MASK (0x7 << 16)
#define RG_CPHY_RX_TR1_INIT_WIRE_STATE_SHIFT 20
#define RG_CPHY_RX_TR1_INIT_WIRE_STATE_MASK (0x7 << 20)
#define RG_CPHY_RX_TR2_INIT_WIRE_STATE_SHIFT 24
#define RG_CPHY_RX_TR2_INIT_WIRE_STATE_MASK (0x7 << 24)
#define RG_CPHY_RX_TR3_INIT_WIRE_STATE_SHIFT 28
#define RG_CPHY_RX_TR3_INIT_WIRE_STATE_MASK (0x7 << 28)

#define CPHY_RX_DETECT_CTRL_SYNC 0x0010
#define RG_CPHY_RX_DETECT_7S_DIS_SYNC_SHIFT 0
#define RG_CPHY_RX_DETECT_7S_DIS_SYNC_MASK (0x1 << 0)
#define RG_CPHY_RX_DETECT_7S_MASK_SYNC_SHIFT 1
#define RG_CPHY_RX_DETECT_7S_MASK_SYNC_MASK (0x7f << 1)
#define RG_CPHY_RX_DETECT_7S_WORD_SYNC_SHIFT 8
#define RG_CPHY_RX_DETECT_7S_WORD_SYNC_MASK (0x1fffff << 8)

#define CPHY_RX_DETECT_CTRL_ESCAPE 0x0014
#define RG_CPHY_RX_DETECT_7S_DIS_ESCAPE_SHIFT 0
#define RG_CPHY_RX_DETECT_7S_DIS_ESCAPE_MASK (0x1 << 0)
#define RG_CPHY_RX_DETECT_7S_MASK_ESCAPE_SHIFT 1
#define RG_CPHY_RX_DETECT_7S_MASK_ESCAPE_MASK (0x7f << 1)
#define RG_CPHY_RX_DETECT_7S_WORD_ESCAPE_SHIFT 8
#define RG_CPHY_RX_DETECT_7S_WORD_ESCAPE_MASK (0x1fffff << 8)

#define CPHY_RX_DETECT_CTRL_POST 0x0018
#define RG_CPHY_RX_DETECT_7S_DIS_POST_SHIFT 0
#define RG_CPHY_RX_DETECT_7S_DIS_POST_MASK (0x1 << 0)
#define RG_CPHY_RX_DATA_VALID_POST_EN_SHIFT 4
#define RG_CPHY_RX_DATA_VALID_POST_EN_MASK (0x1 << 4)
#define RG_CPHY_RX_DETECT_7S_WORD_POST_SHIFT 8
#define RG_CPHY_RX_DETECT_7S_WORD_POST_MASK (0x1fffff << 8)

#define CPHY_RX_TRIO0_DEBUG_0 0x0020
#define RO_CPHY_RX_TR0_SYMBOL_STREAM_0_SHIFT 0
#define RO_CPHY_RX_TR0_SYMBOL_STREAM_0_MASK (0xffffffff << 0)

#define CPHY_RX_TRIO0_DEBUG_1 0x0024
#define RO_CPHY_RX_TR0_SYMBOL_STREAM_1_SHIFT 0
#define RO_CPHY_RX_TR0_SYMBOL_STREAM_1_MASK (0x3ff << 0)
#define RO_CPHY_RX_TR0_SYMBOL_STRAM_VALID_SHIFT 12
#define RO_CPHY_RX_TR0_SYMBOL_STRAM_VALID_MASK (0x1 << 12)
#define RO_CPHY_RX_TR0_DETECT_POST_SHIFT 15
#define RO_CPHY_RX_TR0_DETECT_POST_MASK (0x1 << 15)
#define RO_CPHY_RX_TR0_POSITION_SYNC_SHIFT 16
#define RO_CPHY_RX_TR0_POSITION_SYNC_MASK (0x1f << 16)
#define RO_CPHY_RX_TR0_DETECT_SYNC_SHIFT 23
#define RO_CPHY_RX_TR0_DETECT_SYNC_MASK (0x1 << 23)
#define RO_CPHY_RX_TR0_POSITION_ESCAPE_SHIFT 24
#define RO_CPHY_RX_TR0_POSITION_ESCAPE_MASK (0x1f << 24)
#define RO_CPHY_RX_TR0_DETECT_ESCAPE_SHIFT 31
#define RO_CPHY_RX_TR0_DETECT_ESCAPE_MASK (0x1 << 31)

#define CPHY_RX_TRIO1_DEBUG_0 0x0030
#define RO_CPHY_RX_TR1_SYMBOL_STREAM_0_SHIFT 0
#define RO_CPHY_RX_TR1_SYMBOL_STREAM_0_MASK (0xffffffff << 0)

#define CPHY_RX_TRIO1_DEBUG_1 0x0034
#define RO_CPHY_RX_TR1_SYMBOL_STREAM_1_SHIFT 0
#define RO_CPHY_RX_TR1_SYMBOL_STREAM_1_MASK (0x3ff << 0)
#define RO_CPHY_RX_TR1_SYMBOL_STRAM_VALID_SHIFT 12
#define RO_CPHY_RX_TR1_SYMBOL_STRAM_VALID_MASK (0x1 << 12)
#define RO_CPHY_RX_TR1_DETECT_POST_SHIFT 15
#define RO_CPHY_RX_TR1_DETECT_POST_MASK (0x1 << 15)
#define RO_CPHY_RX_TR1_POSITION_SYNC_SHIFT 16
#define RO_CPHY_RX_TR1_POSITION_SYNC_MASK (0x1f << 16)
#define RO_CPHY_RX_TR1_DETECT_SYNC_SHIFT 23
#define RO_CPHY_RX_TR1_DETECT_SYNC_MASK (0x1 << 23)
#define RO_CPHY_RX_TR1_POSITION_ESCAPE_SHIFT 24
#define RO_CPHY_RX_TR1_POSITION_ESCAPE_MASK (0x1f << 24)
#define RO_CPHY_RX_TR1_DETECT_ESCAPE_SHIFT 31
#define RO_CPHY_RX_TR1_DETECT_ESCAPE_MASK (0x1 << 31)

#define CPHY_RX_TRIO2_DEBUG_0 0x0040
#define RO_CPHY_RX_TR2_SYMBOL_STREAM_0_SHIFT 0
#define RO_CPHY_RX_TR2_SYMBOL_STREAM_0_MASK (0xffffffff << 0)

#define CPHY_RX_TRIO2_DEBUG_1 0x0044
#define RO_CPHY_RX_TR2_SYMBOL_STREAM_1_SHIFT 0
#define RO_CPHY_RX_TR2_SYMBOL_STREAM_1_MASK (0x3ff << 0)
#define RO_CPHY_RX_TR2_SYMBOL_STRAM_VALID_SHIFT 12
#define RO_CPHY_RX_TR2_SYMBOL_STRAM_VALID_MASK (0x1 << 12)
#define RO_CPHY_RX_TR2_DETECT_POST_SHIFT 15
#define RO_CPHY_RX_TR2_DETECT_POST_MASK (0x1 << 15)
#define RO_CPHY_RX_TR2_POSITION_SYNC_SHIFT 16
#define RO_CPHY_RX_TR2_POSITION_SYNC_MASK (0x1f << 16)
#define RO_CPHY_RX_TR2_DETECT_SYNC_SHIFT 23
#define RO_CPHY_RX_TR2_DETECT_SYNC_MASK (0x1 << 23)
#define RO_CPHY_RX_TR2_POSITION_ESCAPE_SHIFT 24
#define RO_CPHY_RX_TR2_POSITION_ESCAPE_MASK (0x1f << 24)
#define RO_CPHY_RX_TR2_DETECT_ESCAPE_SHIFT 31
#define RO_CPHY_RX_TR2_DETECT_ESCAPE_MASK (0x1 << 31)

#define CPHY_RX_TRIO3_DEBUG_0 0x0050
#define RO_CPHY_RX_TR3_SYMBOL_STREAM_0_SHIFT 0
#define RO_CPHY_RX_TR3_SYMBOL_STREAM_0_MASK (0xffffffff << 0)

#define CPHY_RX_TRIO3_DEBUG_1 0x0054
#define RO_CPHY_RX_TR3_SYMBOL_STREAM_1_SHIFT 0
#define RO_CPHY_RX_TR3_SYMBOL_STREAM_1_MASK (0x3ff << 0)
#define RO_CPHY_RX_TR3_SYMBOL_STRAM_VALID_SHIFT 12
#define RO_CPHY_RX_TR3_SYMBOL_STRAM_VALID_MASK (0x1 << 12)
#define RO_CPHY_RX_TR3_DETECT_POST_SHIFT 15
#define RO_CPHY_RX_TR3_DETECT_POST_MASK (0x1 << 15)
#define RO_CPHY_RX_TR3_POSITION_SYNC_SHIFT 16
#define RO_CPHY_RX_TR3_POSITION_SYNC_MASK (0x1f << 16)
#define RO_CPHY_RX_TR3_DETECT_SYNC_SHIFT 23
#define RO_CPHY_RX_TR3_DETECT_SYNC_MASK (0x1 << 23)
#define RO_CPHY_RX_TR3_POSITION_ESCAPE_SHIFT 24
#define RO_CPHY_RX_TR3_POSITION_ESCAPE_MASK (0x1f << 24)
#define RO_CPHY_RX_TR3_DETECT_ESCAPE_SHIFT 31
#define RO_CPHY_RX_TR3_DETECT_ESCAPE_MASK (0x1 << 31)

#define CPHY_RX_BIST_TRIO0_PROGSEQ_0 0x0060
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S0_SHIFT 0
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S0_MASK (0x7 << 0)
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S1_SHIFT 4
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S1_MASK (0x7 << 4)
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S2_SHIFT 8
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S2_MASK (0x7 << 8)
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S3_SHIFT 12
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S3_MASK (0x7 << 12)
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S4_SHIFT 16
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S4_MASK (0x7 << 16)
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S5_SHIFT 20
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S5_MASK (0x7 << 20)
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S6_SHIFT 24
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S6_MASK (0x7 << 24)
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S7_SHIFT 28
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S7_MASK (0x7 << 28)

#define CPHY_RX_BIST_TRIO0_PROGSEQ_1 0x0064
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S8_SHIFT 0
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S8_MASK (0x7 << 0)
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S9_SHIFT 4
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S9_MASK (0x7 << 4)
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S10_SHIFT 8
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S10_MASK (0x7 << 8)
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S11_SHIFT 12
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S11_MASK (0x7 << 12)
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S12_SHIFT 16
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S12_MASK (0x7 << 16)
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S13_SHIFT 20
#define RG_CPHY_RX_TR0_BIST_PROGSEQ_S13_MASK (0x7 << 20)

#define CPHY_RX_BIST_TRIO1_PROGSEQ_0 0x0068
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S0_SHIFT 0
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S0_MASK (0x7 << 0)
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S1_SHIFT 4
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S1_MASK (0x7 << 4)
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S2_SHIFT 8
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S2_MASK (0x7 << 8)
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S3_SHIFT 12
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S3_MASK (0x7 << 12)
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S4_SHIFT 16
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S4_MASK (0x7 << 16)
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S5_SHIFT 20
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S5_MASK (0x7 << 20)
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S6_SHIFT 24
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S6_MASK (0x7 << 24)
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S7_SHIFT 28
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S7_MASK (0x7 << 28)

#define CPHY_RX_BIST_TRIO1_PROGSEQ_1 0x006c
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S8_SHIFT 0
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S8_MASK (0x7 << 0)
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S9_SHIFT 4
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S9_MASK (0x7 << 4)
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S10_SHIFT 8
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S10_MASK (0x7 << 8)
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S11_SHIFT 12
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S11_MASK (0x7 << 12)
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S12_SHIFT 16
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S12_MASK (0x7 << 16)
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S13_SHIFT 20
#define RG_CPHY_RX_TR1_BIST_PROGSEQ_S13_MASK (0x7 << 20)

#define CPHY_RX_BIST_TRIO2_PROGSEQ_0 0x0070
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S0_SHIFT 0
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S0_MASK (0x7 << 0)
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S1_SHIFT 4
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S1_MASK (0x7 << 4)
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S2_SHIFT 8
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S2_MASK (0x7 << 8)
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S3_SHIFT 12
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S3_MASK (0x7 << 12)
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S4_SHIFT 16
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S4_MASK (0x7 << 16)
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S5_SHIFT 20
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S5_MASK (0x7 << 20)
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S6_SHIFT 24
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S6_MASK (0x7 << 24)
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S7_SHIFT 28
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S7_MASK (0x7 << 28)

#define CPHY_RX_BIST_TRIO2_PROGSEQ_1 0x0074
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S8_SHIFT 0
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S8_MASK (0x7 << 0)
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S9_SHIFT 4
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S9_MASK (0x7 << 4)
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S10_SHIFT 8
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S10_MASK (0x7 << 8)
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S11_SHIFT 12
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S11_MASK (0x7 << 12)
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S12_SHIFT 16
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S12_MASK (0x7 << 16)
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S13_SHIFT 20
#define RG_CPHY_RX_TR2_BIST_PROGSEQ_S13_MASK (0x7 << 20)

#define CPHY_RX_BIST_TRIO3_PROGSEQ_0 0x0078
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S0_SHIFT 0
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S0_MASK (0x7 << 0)
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S1_SHIFT 4
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S1_MASK (0x7 << 4)
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S2_SHIFT 8
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S2_MASK (0x7 << 8)
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S3_SHIFT 12
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S3_MASK (0x7 << 12)
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S4_SHIFT 16
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S4_MASK (0x7 << 16)
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S5_SHIFT 20
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S5_MASK (0x7 << 20)
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S6_SHIFT 24
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S6_MASK (0x7 << 24)
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S7_SHIFT 28
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S7_MASK (0x7 << 28)

#define CPHY_RX_BIST_TRIO3_PROGSEQ_1 0x007c
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S8_SHIFT 0
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S8_MASK (0x7 << 0)
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S9_SHIFT 4
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S9_MASK (0x7 << 4)
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S10_SHIFT 8
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S10_MASK (0x7 << 8)
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S11_SHIFT 12
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S11_MASK (0x7 << 12)
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S12_SHIFT 16
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S12_MASK (0x7 << 16)
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S13_SHIFT 20
#define RG_CPHY_RX_TR3_BIST_PROGSEQ_S13_MASK (0x7 << 20)

#define CPHY_RX_BIST_TRIO0_CTRL 0x0080
#define RG_CPHY_RX_TR0_PRBS_SEED_0_SHIFT 0
#define RG_CPHY_RX_TR0_PRBS_SEED_0_MASK (0xff << 0)
#define RG_CPHY_RX_TR0_PRBS_SEED_1_SHIFT 8
#define RG_CPHY_RX_TR0_PRBS_SEED_1_MASK (0xff << 8)
#define RG_CPHY_RX_TR0_BIST_COMP_MODE_SHIFT 20
#define RG_CPHY_RX_TR0_BIST_COMP_MODE_MASK (0x1 << 20)
#define RG_CPHY_RX_TR0_FIX_POINT_RST_MODE_SHIFT 21
#define RG_CPHY_RX_TR0_FIX_POINT_RST_MODE_MASK (0x1 << 21)
#define CPHY_RX_TR0_FIX_POINT_RST_SHIFT 22
#define CPHY_RX_TR0_FIX_POINT_RST_MASK (0x1 << 22)
#define RG_CPHY_RX_TR0_PRBS_PAT_SEL_SHIFT 24
#define RG_CPHY_RX_TR0_PRBS_PAT_SEL_MASK (0x7 << 24)

#define CPHY_RX_BIST_TRIO1_CTRL 0x0084
#define RG_CPHY_RX_TR1_PRBS_SEED_0_SHIFT 0
#define RG_CPHY_RX_TR1_PRBS_SEED_0_MASK (0xff << 0)
#define RG_CPHY_RX_TR1_PRBS_SEED_1_SHIFT 8
#define RG_CPHY_RX_TR1_PRBS_SEED_1_MASK (0xff << 8)
#define RG_CPHY_RX_TR1_BIST_COMP_MODE_SHIFT 20
#define RG_CPHY_RX_TR1_BIST_COMP_MODE_MASK (0x1 << 20)
#define RG_CPHY_RX_TR1_FIX_POINT_RST_MODE_SHIFT 21
#define RG_CPHY_RX_TR1_FIX_POINT_RST_MODE_MASK (0x1 << 21)
#define CPHY_RX_TR1_FIX_POINT_RST_SHIFT 22
#define CPHY_RX_TR1_FIX_POINT_RST_MASK (0x1 << 22)
#define RG_CPHY_RX_TR1_PRBS_PAT_SEL_SHIFT 24
#define RG_CPHY_RX_TR1_PRBS_PAT_SEL_MASK (0x7 << 24)

#define CPHY_RX_BIST_TRIO2_CTRL 0x0088
#define RG_CPHY_RX_TR2_PRBS_SEED_0_SHIFT 0
#define RG_CPHY_RX_TR2_PRBS_SEED_0_MASK (0xff << 0)
#define RG_CPHY_RX_TR2_PRBS_SEED_1_SHIFT 8
#define RG_CPHY_RX_TR2_PRBS_SEED_1_MASK (0xff << 8)
#define RG_CPHY_RX_TR2_BIST_COMP_MODE_SHIFT 20
#define RG_CPHY_RX_TR2_BIST_COMP_MODE_MASK (0x1 << 20)
#define RG_CPHY_RX_TR2_FIX_POINT_RST_MODE_SHIFT 21
#define RG_CPHY_RX_TR2_FIX_POINT_RST_MODE_MASK (0x1 << 21)
#define CPHY_RX_TR2_FIX_POINT_RST_SHIFT 22
#define CPHY_RX_TR2_FIX_POINT_RST_MASK (0x1 << 22)
#define RG_CPHY_RX_TR2_PRBS_PAT_SEL_SHIFT 24
#define RG_CPHY_RX_TR2_PRBS_PAT_SEL_MASK (0x7 << 24)

#define CPHY_RX_BIST_TRIO3_CTRL 0x008c
#define RG_CPHY_RX_TR3_PRBS_SEED_0_SHIFT 0
#define RG_CPHY_RX_TR3_PRBS_SEED_0_MASK (0xff << 0)
#define RG_CPHY_RX_TR3_PRBS_SEED_1_SHIFT 8
#define RG_CPHY_RX_TR3_PRBS_SEED_1_MASK (0xff << 8)
#define RG_CPHY_RX_TR3_BIST_COMP_MODE_SHIFT 20
#define RG_CPHY_RX_TR3_BIST_COMP_MODE_MASK (0x1 << 20)
#define RG_CPHY_RX_TR3_FIX_POINT_RST_MODE_SHIFT 21
#define RG_CPHY_RX_TR3_FIX_POINT_RST_MODE_MASK (0x1 << 21)
#define CPHY_RX_TR3_FIX_POINT_RST_SHIFT 22
#define CPHY_RX_TR3_FIX_POINT_RST_MASK (0x1 << 22)
#define RG_CPHY_RX_TR3_PRBS_PAT_SEL_SHIFT 24
#define RG_CPHY_RX_TR3_PRBS_PAT_SEL_MASK (0x7 << 24)

#define CPHY_RX_BIST_DBG_STATUS 0x0090
#define RO_CPHY_RX_TR0_BIST_LP_HS_LP_DONE_SHIFT 0
#define RO_CPHY_RX_TR0_BIST_LP_HS_LP_DONE_MASK (0x1 << 0)
#define RO_CPHY_RX_TR1_BIST_LP_HS_LP_DONE_SHIFT 1
#define RO_CPHY_RX_TR1_BIST_LP_HS_LP_DONE_MASK (0x1 << 1)
#define RO_CPHY_RX_TR2_BIST_LP_HS_LP_DONE_SHIFT 2
#define RO_CPHY_RX_TR2_BIST_LP_HS_LP_DONE_MASK (0x1 << 2)
#define RO_CPHY_RX_TR3_BIST_LP_HS_LP_DONE_SHIFT 3
#define RO_CPHY_RX_TR3_BIST_LP_HS_LP_DONE_MASK (0x1 << 3)

#define CPHY_RX_BIST_PRBS_SEED2 0x0094
#define RG_CPHY_RX_TR0_PRBS_SEED_2_SHIFT 0
#define RG_CPHY_RX_TR0_PRBS_SEED_2_MASK (0xff << 0)
#define RG_CPHY_RX_TR1_PRBS_SEED_2_SHIFT 8
#define RG_CPHY_RX_TR1_PRBS_SEED_2_MASK (0xff << 8)
#define RG_CPHY_RX_TR2_PRBS_SEED_2_SHIFT 16
#define RG_CPHY_RX_TR2_PRBS_SEED_2_MASK (0xff << 16)
#define RG_CPHY_RX_TR3_PRBS_SEED_2_SHIFT 24
#define RG_CPHY_RX_TR3_PRBS_SEED_2_MASK (0xff << 24)

#define CPHY_RX_BIST_PRBS_SEED3 0x0098
#define RG_CPHY_RX_TR0_PRBS_SEED_3_SHIFT 0
#define RG_CPHY_RX_TR0_PRBS_SEED_3_MASK (0xff << 0)
#define RG_CPHY_RX_TR1_PRBS_SEED_3_SHIFT 8
#define RG_CPHY_RX_TR1_PRBS_SEED_3_MASK (0xff << 8)
#define RG_CPHY_RX_TR2_PRBS_SEED_3_SHIFT 16
#define RG_CPHY_RX_TR2_PRBS_SEED_3_MASK (0xff << 16)
#define RG_CPHY_RX_TR3_PRBS_SEED_3_SHIFT 24
#define RG_CPHY_RX_TR3_PRBS_SEED_3_MASK (0xff << 24)

#define CPHY_RX_BIST_TRIO0_STATUS_0 0x00a0
#define RO_CPHY_RX_TR0_BIST_WORD_CNT_0_SHIFT 0
#define RO_CPHY_RX_TR0_BIST_WORD_CNT_0_MASK (0xffffffff << 0)

#define CPHY_RX_BIST_TRIO0_STATUS_1 0x00a4
#define RO_CPHY_RX_TR0_BIST_WORD_CNT_1_SHIFT 0
#define RO_CPHY_RX_TR0_BIST_WORD_CNT_1_MASK (0xffff << 0)
#define RO_CPHY_RX_TR0_BIST_ERR_CNT_SHIFT 16
#define RO_CPHY_RX_TR0_BIST_ERR_CNT_MASK (0x7fff << 16)
#define RO_CPHY_RX_TR0_BIST_WORD_CNT_OVERFLOW_SHIFT 31
#define RO_CPHY_RX_TR0_BIST_WORD_CNT_OVERFLOW_MASK (0x1 << 31)

#define CPHY_RX_BIST_TRIO0_STATUS_2 0x00a8
#define RO_CPHY_RX_TR0_BIST_ERR_RECORD_0_SHIFT 0
#define RO_CPHY_RX_TR0_BIST_ERR_RECORD_0_MASK (0xffffffff << 0)

#define CPHY_RX_BIST_TRIO0_STATUS_3 0x00ac
#define RO_CPHY_RX_TR0_BIST_ERR_RECORD_1_SHIFT 0
#define RO_CPHY_RX_TR0_BIST_ERR_RECORD_1_MASK (0xffff << 0)

#define CPHY_RX_BIST_TRIO1_STATUS_0 0x00b0
#define RO_CPHY_RX_TR1_BIST_WORD_CNT_0_SHIFT 0
#define RO_CPHY_RX_TR1_BIST_WORD_CNT_0_MASK (0xffffffff << 0)

#define CPHY_RX_BIST_TRIO1_STATUS_1 0x00b4
#define RO_CPHY_RX_TR1_BIST_WORD_CNT_1_SHIFT 0
#define RO_CPHY_RX_TR1_BIST_WORD_CNT_1_MASK (0xffff << 0)
#define RO_CPHY_RX_TR1_BIST_ERR_CNT_SHIFT 16
#define RO_CPHY_RX_TR1_BIST_ERR_CNT_MASK (0x7fff << 16)
#define RO_CPHY_RX_TR1_BIST_WORD_CNT_OVERFLOW_SHIFT 31
#define RO_CPHY_RX_TR1_BIST_WORD_CNT_OVERFLOW_MASK (0x1 << 31)

#define CPHY_RX_BIST_TRIO1_STATUS_2 0x00b8
#define RO_CPHY_RX_TR1_BIST_ERR_RECORD_0_SHIFT 0
#define RO_CPHY_RX_TR1_BIST_ERR_RECORD_0_MASK (0xffffffff << 0)

#define CPHY_RX_BIST_TRIO1_STATUS_3 0x00bc
#define RO_CPHY_RX_TR1_BIST_ERR_RECORD_1_SHIFT 0
#define RO_CPHY_RX_TR1_BIST_ERR_RECORD_1_MASK (0xffff << 0)

#define CPHY_RX_BIST_TRIO2_STATUS_0 0x00c0
#define RO_CPHY_RX_TR2_BIST_WORD_CNT_0_SHIFT 0
#define RO_CPHY_RX_TR2_BIST_WORD_CNT_0_MASK (0xffffffff << 0)

#define CPHY_RX_BIST_TRIO2_STATUS_1 0x00c4
#define RO_CPHY_RX_TR2_BIST_WORD_CNT_1_SHIFT 0
#define RO_CPHY_RX_TR2_BIST_WORD_CNT_1_MASK (0xffff << 0)
#define RO_CPHY_RX_TR2_BIST_ERR_CNT_SHIFT 16
#define RO_CPHY_RX_TR2_BIST_ERR_CNT_MASK (0x7fff << 16)
#define RO_CPHY_RX_TR2_BIST_WORD_CNT_OVERFLOW_SHIFT 31
#define RO_CPHY_RX_TR2_BIST_WORD_CNT_OVERFLOW_MASK (0x1 << 31)

#define CPHY_RX_BIST_TRIO2_STATUS_2 0x00c8
#define RO_CPHY_RX_TR2_BIST_ERR_RECORD_0_SHIFT 0
#define RO_CPHY_RX_TR2_BIST_ERR_RECORD_0_MASK (0xffffffff << 0)

#define CPHY_RX_BIST_TRIO2_STATUS_3 0x00cc
#define RO_CPHY_RX_TR2_BIST_ERR_RECORD_1_SHIFT 0
#define RO_CPHY_RX_TR2_BIST_ERR_RECORD_1_MASK (0xffff << 0)

#define CPHY_RX_BIST_TRIO3_STATUS_0 0x00d0
#define RO_CPHY_RX_TR3_BIST_WORD_CNT_0_SHIFT 0
#define RO_CPHY_RX_TR3_BIST_WORD_CNT_0_MASK (0xffffffff << 0)

#define CPHY_RX_BIST_TRIO3_STATUS_1 0x00d4
#define RO_CPHY_RX_TR3_BIST_WORD_CNT_1_SHIFT 0
#define RO_CPHY_RX_TR3_BIST_WORD_CNT_1_MASK (0xffff << 0)
#define RO_CPHY_RX_TR3_BIST_ERR_CNT_SHIFT 16
#define RO_CPHY_RX_TR3_BIST_ERR_CNT_MASK (0x7fff << 16)
#define RO_CPHY_RX_TR3_BIST_WORD_CNT_OVERFLOW_SHIFT 31
#define RO_CPHY_RX_TR3_BIST_WORD_CNT_OVERFLOW_MASK (0x1 << 31)

#define CPHY_RX_BIST_TRIO3_STATUS_2 0x00d8
#define RO_CPHY_RX_TR3_BIST_ERR_RECORD_0_SHIFT 0
#define RO_CPHY_RX_TR3_BIST_ERR_RECORD_0_MASK (0xffffffff << 0)

#define CPHY_RX_BIST_TRIO3_STATUS_3 0x00dc
#define RO_CPHY_RX_TR3_BIST_ERR_RECORD_1_SHIFT 0
#define RO_CPHY_RX_TR3_BIST_ERR_RECORD_1_MASK (0xffff << 0)

#define CPHY_RX_LOOPBACK_OPT 0x00e0
#define CPHY_RX_LB_TRIGGER_SYNC_INIT_SHIFT 0
#define CPHY_RX_LB_TRIGGER_SYNC_INIT_MASK (0x1 << 0)
#define CPHY_RX_LB_RELEASE_SYNC_INIT_SHIFT 1
#define CPHY_RX_LB_RELEASE_SYNC_INIT_MASK (0x1 << 1)
#define RG_PHYD2MAC_CPHY_GEN_EN_SHIFT 8
#define RG_PHYD2MAC_CPHY_GEN_EN_MASK (0x1 << 8)
#define RG_PHYD2MAC_CPHY_GEN_MODE_SHIFT 9
#define RG_PHYD2MAC_CPHY_GEN_MODE_MASK (0x1 << 9)
#define RG_PHYD2MAC_CPHY_GEN_SEL_SHIFT 10
#define RG_PHYD2MAC_CPHY_GEN_SEL_MASK (0x1 << 10)

#define CPHY_RX_FSM_STATUS 0x00e4
#define RO_CPHY_RX_TR0_FSM_SHIFT 0
#define RO_CPHY_RX_TR0_FSM_MASK (0xff << 0)
#define RO_CPHY_RX_TR1_FSM_SHIFT 8
#define RO_CPHY_RX_TR1_FSM_MASK (0xff << 8)
#define RO_CPHY_RX_TR2_FSM_SHIFT 16
#define RO_CPHY_RX_TR2_FSM_MASK (0xff << 16)
#define RO_CPHY_RX_TR3_FSM_SHIFT 24
#define RO_CPHY_RX_TR3_FSM_MASK (0xff << 24)

#define CPHY_RX_BIST_PRBS_LENGTH0 0x00e8
#define RG_CPHY_RX_TRX_PRBS_LENGTH_31_0_SHIFT 0
#define RG_CPHY_RX_TRX_PRBS_LENGTH_31_0_MASK (0xffffffff << 0)

#define CPHY_RX_BIST_PRBS_LENGTH1 0x00ec
#define RG_CPHY_RX_TRX_PRBS_LENGTH_47_32_SHIFT 0
#define RG_CPHY_RX_TRX_PRBS_LENGTH_47_32_MASK (0xffff << 0)

#define CPHY_RX_IRQ_EN 0x00f0
#define RG_CPHY_RX_TR0_ERR_SOT_SYNC_HS_IRQ_EN_SHIFT 0
#define RG_CPHY_RX_TR0_ERR_SOT_SYNC_HS_IRQ_EN_MASK (0x1 << 0)
#define RG_CPHY_RX_TR1_ERR_SOT_SYNC_HS_IRQ_EN_SHIFT 1
#define RG_CPHY_RX_TR1_ERR_SOT_SYNC_HS_IRQ_EN_MASK (0x1 << 1)
#define RG_CPHY_RX_TR2_ERR_SOT_SYNC_HS_IRQ_EN_SHIFT 2
#define RG_CPHY_RX_TR2_ERR_SOT_SYNC_HS_IRQ_EN_MASK (0x1 << 2)
#define RG_CPHY_RX_TR3_ERR_SOT_SYNC_HS_IRQ_EN_SHIFT 3
#define RG_CPHY_RX_TR3_ERR_SOT_SYNC_HS_IRQ_EN_MASK (0x1 << 3)
#define RG_CPHY_RX_TR0_DETECT_ESCAPE_PULSE_IRQ_EN_SHIFT 4
#define RG_CPHY_RX_TR0_DETECT_ESCAPE_PULSE_IRQ_EN_MASK (0x1 << 4)
#define RG_CPHY_RX_TR1_DETECT_ESCAPE_PULSE_IRQ_EN_SHIFT 5
#define RG_CPHY_RX_TR1_DETECT_ESCAPE_PULSE_IRQ_EN_MASK (0x1 << 5)
#define RG_CPHY_RX_TR2_DETECT_ESCAPE_PULSE_IRQ_EN_SHIFT 6
#define RG_CPHY_RX_TR2_DETECT_ESCAPE_PULSE_IRQ_EN_MASK (0x1 << 6)
#define RG_CPHY_RX_TR3_DETECT_ESCAPE_PULSE_IRQ_EN_SHIFT 7
#define RG_CPHY_RX_TR3_DETECT_ESCAPE_PULSE_IRQ_EN_MASK (0x1 << 7)
#define RG_CPHY_RX_ERR_SOT_SEL_SHIFT 8
#define RG_CPHY_RX_ERR_SOT_SEL_MASK (0x1 << 8)
#define RG_CPHY_RX_TR0_ERR_SYNC_HS_IRQ_EN_SHIFT 12
#define RG_CPHY_RX_TR0_ERR_SYNC_HS_IRQ_EN_MASK (0x1 << 12)
#define RG_CPHY_RX_TR1_ERR_SYNC_HS_IRQ_EN_SHIFT 13
#define RG_CPHY_RX_TR1_ERR_SYNC_HS_IRQ_EN_MASK (0x1 << 13)
#define RG_CPHY_RX_TR2_ERR_SYNC_HS_IRQ_EN_SHIFT 14
#define RG_CPHY_RX_TR2_ERR_SYNC_HS_IRQ_EN_MASK (0x1 << 14)
#define RG_CPHY_RX_TR3_ERR_SYNC_HS_IRQ_EN_SHIFT 15
#define RG_CPHY_RX_TR3_ERR_SYNC_HS_IRQ_EN_MASK (0x1 << 15)
#define RG_CPHY_RX_IRQ_W1C_EN_SHIFT 31
#define RG_CPHY_RX_IRQ_W1C_EN_MASK (0x1 << 31)

#define CPHY_RX_IRQ_CLR 0x00f4
#define CPHY_RX_TR0_ERR_SOT_SYNC_HS_IRQ_SHIFT 0
#define CPHY_RX_TR0_ERR_SOT_SYNC_HS_IRQ_MASK (0x1 << 0)
#define CPHY_RX_TR1_ERR_SOT_SYNC_HS_IRQ_SHIFT 1
#define CPHY_RX_TR1_ERR_SOT_SYNC_HS_IRQ_MASK (0x1 << 1)
#define CPHY_RX_TR2_ERR_SOT_SYNC_HS_IRQ_SHIFT 2
#define CPHY_RX_TR2_ERR_SOT_SYNC_HS_IRQ_MASK (0x1 << 2)
#define CPHY_RX_TR3_ERR_SOT_SYNC_HS_IRQ_SHIFT 3
#define CPHY_RX_TR3_ERR_SOT_SYNC_HS_IRQ_MASK (0x1 << 3)
#define CPHY_RX_TR0_DETECT_ESCAPE_PULSE_IRQ_SHIFT 4
#define CPHY_RX_TR0_DETECT_ESCAPE_PULSE_IRQ_MASK (0x1 << 4)
#define CPHY_RX_TR1_DETECT_ESCAPE_PULSE_IRQ_SHIFT 5
#define CPHY_RX_TR1_DETECT_ESCAPE_PULSE_IRQ_MASK (0x1 << 5)
#define CPHY_RX_TR2_DETECT_ESCAPE_PULSE_IRQ_SHIFT 6
#define CPHY_RX_TR2_DETECT_ESCAPE_PULSE_IRQ_MASK (0x1 << 6)
#define CPHY_RX_TR3_DETECT_ESCAPE_PULSE_IRQ_SHIFT 7
#define CPHY_RX_TR3_DETECT_ESCAPE_PULSE_IRQ_MASK (0x1 << 7)
#define CPHY_RX_TR0_ERR_SYNC_HS_IRQ_SHIFT 8
#define CPHY_RX_TR0_ERR_SYNC_HS_IRQ_MASK (0x1 << 8)
#define CPHY_RX_TR1_ERR_SYNC_HS_IRQ_SHIFT 9
#define CPHY_RX_TR1_ERR_SYNC_HS_IRQ_MASK (0x1 << 9)
#define CPHY_RX_TR2_ERR_SYNC_HS_IRQ_SHIFT 10
#define CPHY_RX_TR2_ERR_SYNC_HS_IRQ_MASK (0x1 << 10)
#define CPHY_RX_TR3_ERR_SYNC_HS_IRQ_SHIFT 11
#define CPHY_RX_TR3_ERR_SYNC_HS_IRQ_MASK (0x1 << 11)
#define CPHY_RX_TR0_ERR_SOT_SYNC_HS_IRQ_CLR_SHIFT 16
#define CPHY_RX_TR0_ERR_SOT_SYNC_HS_IRQ_CLR_MASK (0x1 << 16)
#define CPHY_RX_TR1_ERR_SOT_SYNC_HS_IRQ_CLR_SHIFT 17
#define CPHY_RX_TR1_ERR_SOT_SYNC_HS_IRQ_CLR_MASK (0x1 << 17)
#define CPHY_RX_TR2_ERR_SOT_SYNC_HS_IRQ_CLR_SHIFT 18
#define CPHY_RX_TR2_ERR_SOT_SYNC_HS_IRQ_CLR_MASK (0x1 << 18)
#define CPHY_RX_TR3_ERR_SOT_SYNC_HS_IRQ_CLR_SHIFT 19
#define CPHY_RX_TR3_ERR_SOT_SYNC_HS_IRQ_CLR_MASK (0x1 << 19)
#define CPHY_RX_TR0_DETECT_ESCAPE_PULSE_IRQ_CLR_SHIFT 20
#define CPHY_RX_TR0_DETECT_ESCAPE_PULSE_IRQ_CLR_MASK (0x1 << 20)
#define CPHY_RX_TR1_DETECT_ESCAPE_PULSE_IRQ_CLR_SHIFT 21
#define CPHY_RX_TR1_DETECT_ESCAPE_PULSE_IRQ_CLR_MASK (0x1 << 21)
#define CPHY_RX_TR2_DETECT_ESCAPE_PULSE_IRQ_CLR_SHIFT 22
#define CPHY_RX_TR2_DETECT_ESCAPE_PULSE_IRQ_CLR_MASK (0x1 << 22)
#define CPHY_RX_TR3_DETECT_ESCAPE_PULSE_IRQ_CLR_SHIFT 23
#define CPHY_RX_TR3_DETECT_ESCAPE_PULSE_IRQ_CLR_MASK (0x1 << 23)
#define CPHY_RX_TR0_ERR_SYNC_HS_IRQ_CLR_SHIFT 24
#define CPHY_RX_TR0_ERR_SYNC_HS_IRQ_CLR_MASK (0x1 << 24)
#define CPHY_RX_TR1_ERR_SYNC_HS_IRQ_CLR_SHIFT 25
#define CPHY_RX_TR1_ERR_SYNC_HS_IRQ_CLR_MASK (0x1 << 25)
#define CPHY_RX_TR2_ERR_SYNC_HS_IRQ_CLR_SHIFT 26
#define CPHY_RX_TR2_ERR_SYNC_HS_IRQ_CLR_MASK (0x1 << 26)
#define CPHY_RX_TR3_ERR_SYNC_HS_IRQ_CLR_SHIFT 27
#define CPHY_RX_TR3_ERR_SYNC_HS_IRQ_CLR_MASK (0x1 << 27)

#define CPHY_RX_STATUS_0 0x00f8
#define CPHY_RX_ERR_SOT_SYNC_HS_CNT_TRIO0_SHIFT 0
#define CPHY_RX_ERR_SOT_SYNC_HS_CNT_TRIO0_MASK (0xffff << 0)
#define CPHY_RX_ERR_SOT_SYNC_HS_CNT_TRIO1_SHIFT 16
#define CPHY_RX_ERR_SOT_SYNC_HS_CNT_TRIO1_MASK (0xffff << 16)

#define CPHY_RX_STATUS_1 0x00fc
#define CPHY_RX_ERR_SOT_SYNC_HS_CNT_TRIO2_SHIFT 0
#define CPHY_RX_ERR_SOT_SYNC_HS_CNT_TRIO2_MASK (0xffff << 0)
#define CPHY_RX_ERR_SOT_SYNC_HS_CNT_TRIO3_SHIFT 16
#define CPHY_RX_ERR_SOT_SYNC_HS_CNT_TRIO3_MASK (0xffff << 16)

#define CPHY_RX_STATE_CHK_EN 0x0100
#define CPHY_RX_STATE_CHK_EN_TRIO0_SHIFT 0
#define CPHY_RX_STATE_CHK_EN_TRIO0_MASK (0x1 << 0)
#define CPHY_RX_STATE_CHK_EN_TRIO1_SHIFT 1
#define CPHY_RX_STATE_CHK_EN_TRIO1_MASK (0x1 << 1)
#define CPHY_RX_STATE_CHK_EN_TRIO2_SHIFT 2
#define CPHY_RX_STATE_CHK_EN_TRIO2_MASK (0x1 << 2)
#define CPHY_RX_STATE_CHK_EN_TRIO3_SHIFT 3
#define CPHY_RX_STATE_CHK_EN_TRIO3_MASK (0x1 << 3)
#define CPHY_RX_ERR_SOT_SYNC_HS_CNT_INIT_TRIO0_SHIFT 8
#define CPHY_RX_ERR_SOT_SYNC_HS_CNT_INIT_TRIO0_MASK (0x1 << 8)
#define CPHY_RX_ERR_SOT_SYNC_HS_CNT_INIT_TRIO1_SHIFT 9
#define CPHY_RX_ERR_SOT_SYNC_HS_CNT_INIT_TRIO1_MASK (0x1 << 9)
#define CPHY_RX_ERR_SOT_SYNC_HS_CNT_INIT_TRIO2_SHIFT 10
#define CPHY_RX_ERR_SOT_SYNC_HS_CNT_INIT_TRIO2_MASK (0x1 << 10)
#define CPHY_RX_ERR_SOT_SYNC_HS_CNT_INIT_TRIO3_SHIFT 11
#define CPHY_RX_ERR_SOT_SYNC_HS_CNT_INIT_TRIO3_MASK (0x1 << 11)
#define RG_ALPOUT_MASK_SHIFT 16
#define RG_ALPOUT_MASK_MASK (0xff << 16)
#define RG_ALP_POS_DET_MASK_SHIFT 24
#define RG_ALP_POS_DET_MASK_MASK (0xff << 24)

#define CPHY_RX_STATE_CHK_TIMER 0x0104
#define RG_CPHY_RX_STATE_CHK_RX_TIMER_CNT_SHIFT 0
#define RG_CPHY_RX_STATE_CHK_RX_TIMER_CNT_MASK (0xffffffff << 0)

#define CPHY_RX_STATE_CHK_STATUS_TRIO0 0x0110
#define RO_CPHY_RX_STATE_CHK_ERR_TRIO0_SHIFT 0
#define RO_CPHY_RX_STATE_CHK_ERR_TRIO0_MASK (0x1 << 0)
#define RO_CPHY_RX_STATE_CHK_ERR_CNT_TRIO0_SHIFT 4
#define RO_CPHY_RX_STATE_CHK_ERR_CNT_TRIO0_MASK (0x7 << 4)
#define CPHY_RX_STATE_CHK_FAIL_SEQ0_TRIO0_SHIFT 16
#define CPHY_RX_STATE_CHK_FAIL_SEQ0_TRIO0_MASK (0xf << 16)
#define CPHY_RX_STATE_CHK_FAIL_SEQ1_TRIO0_SHIFT 20
#define CPHY_RX_STATE_CHK_FAIL_SEQ1_TRIO0_MASK (0xf << 20)
#define CPHY_RX_STATE_CHK_FAIL_SEQ2_TRIO0_SHIFT 24
#define CPHY_RX_STATE_CHK_FAIL_SEQ2_TRIO0_MASK (0xf << 24)
#define CPHY_RX_STATE_CHK_FAIL_SEQ3_TRIO0_SHIFT 28
#define CPHY_RX_STATE_CHK_FAIL_SEQ3_TRIO0_MASK (0xf << 28)

#define CPHY_RX_STATE_CHK_STATUS_TRIO1 0x0114
#define RO_CPHY_RX_STATE_CHK_ERR_TRIO1_SHIFT 0
#define RO_CPHY_RX_STATE_CHK_ERR_TRIO1_MASK (0x1 << 0)
#define RO_CPHY_RX_STATE_CHK_ERR_CNT_TRIO1_SHIFT 4
#define RO_CPHY_RX_STATE_CHK_ERR_CNT_TRIO1_MASK (0x7 << 4)
#define CPHY_RX_STATE_CHK_FAIL_SEQ0_TRIO1_SHIFT 16
#define CPHY_RX_STATE_CHK_FAIL_SEQ0_TRIO1_MASK (0xf << 16)
#define CPHY_RX_STATE_CHK_FAIL_SEQ1_TRIO1_SHIFT 20
#define CPHY_RX_STATE_CHK_FAIL_SEQ1_TRIO1_MASK (0xf << 20)
#define CPHY_RX_STATE_CHK_FAIL_SEQ2_TRIO1_SHIFT 24
#define CPHY_RX_STATE_CHK_FAIL_SEQ2_TRIO1_MASK (0xf << 24)
#define CPHY_RX_STATE_CHK_FAIL_SEQ3_TRIO1_SHIFT 28
#define CPHY_RX_STATE_CHK_FAIL_SEQ3_TRIO1_MASK (0xf << 28)

#define CPHY_RX_STATE_CHK_STATUS_TRIO2 0x0118
#define RO_CPHY_RX_STATE_CHK_ERR_TRIO2_SHIFT 0
#define RO_CPHY_RX_STATE_CHK_ERR_TRIO2_MASK (0x1 << 0)
#define RO_CPHY_RX_STATE_CHK_ERR_CNT_TRIO2_SHIFT 4
#define RO_CPHY_RX_STATE_CHK_ERR_CNT_TRIO2_MASK (0x7 << 4)
#define CPHY_RX_STATE_CHK_FAIL_SEQ0_TRIO2_SHIFT 16
#define CPHY_RX_STATE_CHK_FAIL_SEQ0_TRIO2_MASK (0xf << 16)
#define CPHY_RX_STATE_CHK_FAIL_SEQ1_TRIO2_SHIFT 20
#define CPHY_RX_STATE_CHK_FAIL_SEQ1_TRIO2_MASK (0xf << 20)
#define CPHY_RX_STATE_CHK_FAIL_SEQ2_TRIO2_SHIFT 24
#define CPHY_RX_STATE_CHK_FAIL_SEQ2_TRIO2_MASK (0xf << 24)
#define CPHY_RX_STATE_CHK_FAIL_SEQ3_TRIO2_SHIFT 28
#define CPHY_RX_STATE_CHK_FAIL_SEQ3_TRIO2_MASK (0xf << 28)

#define CPHY_RX_STATE_CHK_STATUS_TRIO3 0x011c
#define RO_CPHY_RX_STATE_CHK_ERR_TRIO3_SHIFT 0
#define RO_CPHY_RX_STATE_CHK_ERR_TRIO3_MASK (0x1 << 0)
#define RO_CPHY_RX_STATE_CHK_ERR_CNT_TRIO3_SHIFT 4
#define RO_CPHY_RX_STATE_CHK_ERR_CNT_TRIO3_MASK (0x7 << 4)
#define CPHY_RX_STATE_CHK_FAIL_SEQ0_TRIO3_SHIFT 16
#define CPHY_RX_STATE_CHK_FAIL_SEQ0_TRIO3_MASK (0xf << 16)
#define CPHY_RX_STATE_CHK_FAIL_SEQ1_TRIO3_SHIFT 20
#define CPHY_RX_STATE_CHK_FAIL_SEQ1_TRIO3_MASK (0xf << 20)
#define CPHY_RX_STATE_CHK_FAIL_SEQ2_TRIO3_SHIFT 24
#define CPHY_RX_STATE_CHK_FAIL_SEQ2_TRIO3_MASK (0xf << 24)
#define CPHY_RX_STATE_CHK_FAIL_SEQ3_TRIO3_SHIFT 28
#define CPHY_RX_STATE_CHK_FAIL_SEQ3_TRIO3_MASK (0xf << 28)

#define CPHY_RX_CAL_ALP_CTRL 0x0130
#define RG_CPHY_CAL_EN_SHIFT 0
#define RG_CPHY_CAL_EN_MASK (0x1 << 0)
#define RG_CPHY_ALP_EN_SHIFT 1
#define RG_CPHY_ALP_EN_MASK (0x1 << 1)
#define RG_PREAMBLE_DET_SEL_SHIFT 2
#define RG_PREAMBLE_DET_SEL_MASK (0x1 << 2)
#define RG_POST_VALID_OPT_SHIFT 3
#define RG_POST_VALID_OPT_MASK (0x1 << 3)
#define RG_ALP_POS_DET_SEL_SHIFT 4
#define RG_ALP_POS_DET_SEL_MASK (0x1 << 4)
#define RG_ALP_STOP_DET_EN_SHIFT 5
#define RG_ALP_STOP_DET_EN_MASK (0x1 << 5)
#define RG_ALPOUT_MASK_ALP_SHIFT 6
#define RG_ALPOUT_MASK_ALP_MASK (0x1 << 6)
#define RG_ALP_RX_EN_SEL_SHIFT 7
#define RG_ALP_RX_EN_SEL_MASK (0x1 << 7)
#define RG_CPHY_SELCAL_PARAMETER_SHIFT 8
#define RG_CPHY_SELCAL_PARAMETER_MASK (0xff << 8)
#define RG_CPHY_ALP_SETTLE_PARAMETER_SHIFT 16
#define RG_CPHY_ALP_SETTLE_PARAMETER_MASK (0xff << 16)
#define RG_TR_PREAMBLE_DET_CNT_SHIFT 24
#define RG_TR_PREAMBLE_DET_CNT_MASK (0xff << 24)

#define CPHY_RX_INIT 0x0134
#define RG_CPHY_CSI2_TINIT_CNT_SHIFT 0
#define RG_CPHY_CSI2_TINIT_CNT_MASK (0xfffff << 0)
#define RG_CPHY_CSI2_TINIT_CNT_EN_SHIFT 23
#define RG_CPHY_CSI2_TINIT_CNT_EN_MASK (0x1 << 23)
#define RG_CPHY_ALP_HSRX_EN_SEL_SHIFT 31
#define RG_CPHY_ALP_HSRX_EN_SEL_MASK (0x1 << 31)

#define CPHY_LANE_SWAP 0x0138
#define TRIO3_LANE_SWAP_SEL_SHIFT 0
#define TRIO3_LANE_SWAP_SEL_MASK (0x3 << 0)
#define TRIO2_LANE_SWAP_SEL_SHIFT 4
#define TRIO2_LANE_SWAP_SEL_MASK (0x3 << 4)
#define TRIO1_LANE_SWAP_SEL_SHIFT 8
#define TRIO1_LANE_SWAP_SEL_MASK (0x3 << 8)
#define TRIO0_LANE_SWAP_SEL_SHIFT 12
#define TRIO0_LANE_SWAP_SEL_MASK (0x3 << 12)

#define CPHY_FSM_ANA_SYNC_INIT_CTRL 0x0140
#define CSI_CPHY_T0_ANA_SYNC_INIT_EARLY_SHIFT 0
#define CSI_CPHY_T0_ANA_SYNC_INIT_EARLY_MASK (0x1 << 0)
#define CSI_CPHY_T1_ANA_SYNC_INIT_EARLY_SHIFT 1
#define CSI_CPHY_T1_ANA_SYNC_INIT_EARLY_MASK (0x1 << 1)
#define CSI_CPHY_T2_ANA_SYNC_INIT_EARLY_SHIFT 2
#define CSI_CPHY_T2_ANA_SYNC_INIT_EARLY_MASK (0x1 << 2)
#define CSI_CPHY_T3_ANA_SYNC_INIT_EARLY_SHIFT 3
#define CSI_CPHY_T3_ANA_SYNC_INIT_EARLY_MASK (0x1 << 3)

#define CPHY_MISC_COUNTER_CTRL 0x0144
#define CSI_MISSING_SYNC_INIT_DET_CNT_EN_SHIFT 0
#define CSI_MISSING_SYNC_INIT_DET_CNT_EN_MASK (0xf << 0)
#define CSI_SYNC_DET_CNT_EN_SHIFT 4
#define CSI_SYNC_DET_CNT_EN_MASK (0xf << 4)
#define CSI_SYNC_INIT_CNT_EN_SHIFT 8
#define CSI_SYNC_INIT_CNT_EN_MASK (0xf << 8)
#define CSI_LANE_SKEW_CNT_MASK_SHIFT 12
#define CSI_LANE_SKEW_CNT_MASK_MASK (0xf << 12)
#define CSI_LANE_SKEW_CNT_EN_SHIFT 16
#define CSI_LANE_SKEW_CNT_EN_MASK (0x1 << 16)
#define CPHY_PREAMBLE_CNT_EN_SHIFT 17
#define CPHY_PREAMBLE_CNT_EN_MASK (0xf << 17)

#define CPHY_TRIO0_SYNC_INIT_DET_CNT 0x0148
#define CPHY_TRIO0_SYNC_DET_CNT_SHIFT 0
#define CPHY_TRIO0_SYNC_DET_CNT_MASK (0xffff << 0)
#define CPHY_TRIO0_SYNC_INIT_CNT_SHIFT 16
#define CPHY_TRIO0_SYNC_INIT_CNT_MASK (0xffff << 16)

#define CPHY_TRIO0_MISSING_SYNC_INIT_DET_CNT 0x014c
#define CPHY_TRIO0_MISSING_SYNC_DET_CNT_SHIFT 0
#define CPHY_TRIO0_MISSING_SYNC_DET_CNT_MASK (0x7fff << 0)
#define CPHY_TRIO0_MISSING_SYNC_DET_SHIFT 15
#define CPHY_TRIO0_MISSING_SYNC_DET_MASK (0x1 << 15)
#define CPHY_TRIO0_MISSING_SYNC_INIT_CNT_SHIFT 16
#define CPHY_TRIO0_MISSING_SYNC_INIT_CNT_MASK (0x7fff << 16)
#define CPHY_TRIO0_MISSING_SYNC_INIT_SHIFT 31
#define CPHY_TRIO0_MISSING_SYNC_INIT_MASK (0x1 << 31)

#define CPHY_TRIO1_SYNC_INIT_DET_CNT 0x0150
#define CPHY_TRIO1_SYNC_DET_CNT_SHIFT 0
#define CPHY_TRIO1_SYNC_DET_CNT_MASK (0xffff << 0)
#define CPHY_TRIO1_SYNC_INIT_CNT_SHIFT 16
#define CPHY_TRIO1_SYNC_INIT_CNT_MASK (0xffff << 16)

#define CPHY_TRIO1_MISSING_SYNC_INIT_DET_CNT 0x0154
#define CPHY_TRIO1_MISSING_SYNC_DET_CNT_SHIFT 0
#define CPHY_TRIO1_MISSING_SYNC_DET_CNT_MASK (0x7fff << 0)
#define CPHY_TRIO1_MISSING_SYNC_DET_SHIFT 15
#define CPHY_TRIO1_MISSING_SYNC_DET_MASK (0x1 << 15)
#define CPHY_TRIO1_MISSING_SYNC_INIT_CNT_SHIFT 16
#define CPHY_TRIO1_MISSING_SYNC_INIT_CNT_MASK (0x7fff << 16)
#define CPHY_TRIO1_MISSING_SYNC_INIT_SHIFT 31
#define CPHY_TRIO1_MISSING_SYNC_INIT_MASK (0x1 << 31)

#define CPHY_TRIO2_SYNC_INIT_DET_CNT 0x0158
#define CPHY_TRIO2_SYNC_DET_CNT_SHIFT 0
#define CPHY_TRIO2_SYNC_DET_CNT_MASK (0xffff << 0)
#define CPHY_TRIO2_SYNC_INIT_CNT_SHIFT 16
#define CPHY_TRIO2_SYNC_INIT_CNT_MASK (0xffff << 16)

#define CPHY_TRIO2_MISSING_SYNC_INIT_DET_CNT 0x015c
#define CPHY_TRIO2_MISSING_SYNC_DET_CNT_SHIFT 0
#define CPHY_TRIO2_MISSING_SYNC_DET_CNT_MASK (0x7fff << 0)
#define CPHY_TRIO2_MISSING_SYNC_DET_SHIFT 15
#define CPHY_TRIO2_MISSING_SYNC_DET_MASK (0x1 << 15)
#define CPHY_TRIO2_MISSING_SYNC_INIT_CNT_SHIFT 16
#define CPHY_TRIO2_MISSING_SYNC_INIT_CNT_MASK (0x7fff << 16)
#define CPHY_TRIO2_MISSING_SYNC_INIT_SHIFT 31
#define CPHY_TRIO2_MISSING_SYNC_INIT_MASK (0x1 << 31)

#define CPHY_TRIO3_SYNC_INIT_DET_CNT 0x0160
#define CPHY_TRIO3_SYNC_DET_CNT_SHIFT 0
#define CPHY_TRIO3_SYNC_DET_CNT_MASK (0xffff << 0)
#define CPHY_TRIO3_SYNC_INIT_CNT_SHIFT 16
#define CPHY_TRIO3_SYNC_INIT_CNT_MASK (0xffff << 16)

#define CPHY_TRIO3_MISSING_SYNC_INIT_DET_CNT 0x0164
#define CPHY_TRIO3_MISSING_SYNC_DET_CNT_SHIFT 0
#define CPHY_TRIO3_MISSING_SYNC_DET_CNT_MASK (0x7fff << 0)
#define CPHY_TRIO3_MISSING_SYNC_DET_SHIFT 15
#define CPHY_TRIO3_MISSING_SYNC_DET_MASK (0x1 << 15)
#define CPHY_TRIO3_MISSING_SYNC_INIT_CNT_SHIFT 16
#define CPHY_TRIO3_MISSING_SYNC_INIT_CNT_MASK (0x7fff << 16)
#define CPHY_TRIO3_MISSING_SYNC_INIT_SHIFT 31
#define CPHY_TRIO3_MISSING_SYNC_INIT_MASK (0x1 << 31)

#define CPHY_VALID_PIPE_EN 0x0168
#define CPHY_TRIO0_VALID_PIPE_EN_SHIFT 0
#define CPHY_TRIO0_VALID_PIPE_EN_MASK (0x1 << 0)
#define CPHY_TRIO1_VALID_PIPE_EN_SHIFT 1
#define CPHY_TRIO1_VALID_PIPE_EN_MASK (0x1 << 1)
#define CPHY_TRIO2_VALID_PIPE_EN_SHIFT 2
#define CPHY_TRIO2_VALID_PIPE_EN_MASK (0x1 << 2)
#define CPHY_TRIO3_VALID_PIPE_EN_SHIFT 3
#define CPHY_TRIO3_VALID_PIPE_EN_MASK (0x1 << 3)

#define CPHY_ANA_RTERM_CTRIL 0x016c
#define CPHY_TRIO0_TRAIL_RTERM_OFF_SHIFT 0
#define CPHY_TRIO0_TRAIL_RTERM_OFF_MASK (0x1 << 0)
#define CPHY_TRIO1_TRAIL_RTERM_OFF_SHIFT 1
#define CPHY_TRIO1_TRAIL_RTERM_OFF_MASK (0x1 << 1)
#define CPHY_TRIO2_TRAIL_RTERM_OFF_SHIFT 2
#define CPHY_TRIO2_TRAIL_RTERM_OFF_MASK (0x1 << 2)
#define CPHY_TRIO3_TRAIL_RTERM_OFF_SHIFT 3
#define CPHY_TRIO3_TRAIL_RTERM_OFF_MASK (0x1 << 3)

#define CPHY_LANE_SKEW_CNT_0 0x0170
#define TRIO0_SKEW_CNT_MIN_SHIFT 0
#define TRIO0_SKEW_CNT_MIN_MASK (0xf << 0)
#define TRIO0_SKEW_CNT_MAX_SHIFT 4
#define TRIO0_SKEW_CNT_MAX_MASK (0xf << 4)
#define TRIO0_SKEW_CNT_SHIFT 8
#define TRIO0_SKEW_CNT_MASK (0xf << 8)
#define TRIO1_SKEW_CNT_MIN_SHIFT 16
#define TRIO1_SKEW_CNT_MIN_MASK (0xf << 16)
#define TRIO1_SKEW_CNT_MAX_SHIFT 20
#define TRIO1_SKEW_CNT_MAX_MASK (0xf << 20)
#define TRIO1_SKEW_CNT_SHIFT 24
#define TRIO1_SKEW_CNT_MASK (0xf << 24)

#define CPHY_LANE_SKEW_CNT_1 0x0174
#define TRIO2_SKEW_CNT_MIN_SHIFT 0
#define TRIO2_SKEW_CNT_MIN_MASK (0xf << 0)
#define TRIO2_SKEW_CNT_MAX_SHIFT 4
#define TRIO2_SKEW_CNT_MAX_MASK (0xf << 4)
#define TRIO2_SKEW_CNT_SHIFT 8
#define TRIO2_SKEW_CNT_MASK (0xf << 8)
#define TRIO3_SKEW_CNT_MIN_SHIFT 16
#define TRIO3_SKEW_CNT_MIN_MASK (0xf << 16)
#define TRIO3_SKEW_CNT_MAX_SHIFT 20
#define TRIO3_SKEW_CNT_MAX_MASK (0xf << 20)
#define TRIO3_SKEW_CNT_SHIFT 24
#define TRIO3_SKEW_CNT_MASK (0xf << 24)

#define CPHY_PREAMBLE_CNT_0 0x0178
#define TRIO0_PREAMBLE_CNT_SHIFT 0
#define TRIO0_PREAMBLE_CNT_MASK (0xffff << 0)
#define TRIO1_PREAMBLE_CNT_SHIFT 16
#define TRIO1_PREAMBLE_CNT_MASK (0xffff << 16)

#define CPHY_PREAMBLE_CNT_1 0x017c
#define TRIO2_PREAMBLE_CNT_SHIFT 0
#define TRIO2_PREAMBLE_CNT_MASK (0xffff << 0)
#define TRIO3_PREAMBLE_CNT_SHIFT 16
#define TRIO3_PREAMBLE_CNT_MASK (0xffff << 16)

#define CPHY_TRIO0_PREAMBLE_CNT_HIT_PAT 0x0180
#define TRIO0_PREAMBLE_CNT_HIT_PAT_SHIFT 0
#define TRIO0_PREAMBLE_CNT_HIT_PAT_MASK (0x3ff << 0)
#define TRIO0_PREAMBLE_CNT_HIT_PAT_MIN_SHIFT 10
#define TRIO0_PREAMBLE_CNT_HIT_PAT_MIN_MASK (0x3ff << 10)
#define TRIO0_PREAMBLE_CNT_HIT_PAT_MAX_SHIFT 20
#define TRIO0_PREAMBLE_CNT_HIT_PAT_MAX_MASK (0x3ff << 20)

#define CPHY_TRIO1_PREAMBLE_CNT_HIT_PAT 0x0184
#define TRIO1_PREAMBLE_CNT_HIT_PAT_SHIFT 0
#define TRIO1_PREAMBLE_CNT_HIT_PAT_MASK (0x3ff << 0)
#define TRIO1_PREAMBLE_CNT_HIT_PAT_MIN_SHIFT 10
#define TRIO1_PREAMBLE_CNT_HIT_PAT_MIN_MASK (0x3ff << 10)
#define TRIO1_PREAMBLE_CNT_HIT_PAT_MAX_SHIFT 20
#define TRIO1_PREAMBLE_CNT_HIT_PAT_MAX_MASK (0x3ff << 20)

#define CPHY_TRIO2_PREAMBLE_CNT_HIT_PAT 0x0188
#define TRIO2_PREAMBLE_CNT_HIT_PAT_SHIFT 0
#define TRIO2_PREAMBLE_CNT_HIT_PAT_MASK (0x3ff << 0)
#define TRIO2_PREAMBLE_CNT_HIT_PAT_MIN_SHIFT 10
#define TRIO2_PREAMBLE_CNT_HIT_PAT_MIN_MASK (0x3ff << 10)
#define TRIO2_PREAMBLE_CNT_HIT_PAT_MAX_SHIFT 20
#define TRIO2_PREAMBLE_CNT_HIT_PAT_MAX_MASK (0x3ff << 20)

#define CPHY_TRIO3_PREAMBLE_CNT_HIT_PAT 0x018c
#define TRIO3_PREAMBLE_CNT_HIT_PAT_SHIFT 0
#define TRIO3_PREAMBLE_CNT_HIT_PAT_MASK (0x3ff << 0)
#define TRIO3_PREAMBLE_CNT_HIT_PAT_MIN_SHIFT 10
#define TRIO3_PREAMBLE_CNT_HIT_PAT_MIN_MASK (0x3ff << 10)
#define TRIO3_PREAMBLE_CNT_HIT_PAT_MAX_SHIFT 20
#define TRIO3_PREAMBLE_CNT_HIT_PAT_MAX_MASK (0x3ff << 20)

#define CPHY_PRBS_PAT_GEN_CTRL_0 0x0190
#define PRBS_PAT_GEN_LP01_STAGE_CNT_SHIFT 0
#define PRBS_PAT_GEN_LP01_STAGE_CNT_MASK (0x1f << 0)
#define PRBS_PAT_GEN_IDLE_STAGE_CNT_SHIFT 5
#define PRBS_PAT_GEN_IDLE_STAGE_CNT_MASK (0x3 << 5)
#define PRBS_PAT_GEN_PRE_STAGE_CNT_SHIFT 7
#define PRBS_PAT_GEN_PRE_STAGE_CNT_MASK (0x1ff << 7)
#define PRBS_PAT_GEN_LONG_PKT_CNT_SHIFT 16
#define PRBS_PAT_GEN_LONG_PKT_CNT_MASK (0x1f << 16)
#define PRBS_PAT_GEN_DT_SHIFT 22
#define PRBS_PAT_GEN_DT_MASK (0x1 << 22)
#define PRBS_PAT_GEN_VC_SHIFT 23
#define PRBS_PAT_GEN_VC_MASK (0x1f << 23)
#define CDPHY_PRBS_PAT_GEN_MODE_SHIFT 28
#define CDPHY_PRBS_PAT_GEN_MODE_MASK (0x7 << 28)
#define PRBS_PAT_GEN_CPHY_EN_SHIFT 31
#define PRBS_PAT_GEN_CPHY_EN_MASK (0x1 << 31)

#define CPHY_PRBS_PAT_GEN_CTRL_1 0x0194
#define CPHY_PRBS_PAT_GEN_LN2_SKEW_CYCLE_CNT_SHIFT 0
#define CPHY_PRBS_PAT_GEN_LN2_SKEW_CYCLE_CNT_MASK (0x7 << 0)
#define CPHY_PRBS_PAT_GEN_LN1_SKEW_CYCLE_CNT_SHIFT 3
#define CPHY_PRBS_PAT_GEN_LN1_SKEW_CYCLE_CNT_MASK (0x7 << 3)
#define CPHY_PRBS_PAT_GEN_LN0_SKEW_CYCLE_CNT_SHIFT 6
#define CPHY_PRBS_PAT_GEN_LN0_SKEW_CYCLE_CNT_MASK (0x7 << 6)
#define CPHY_PRBS_PAT_GEN_SKEW_EN_SHIFT 9
#define CPHY_PRBS_PAT_GEN_SKEW_EN_MASK (0x1 << 9)
#define CPHY_PRBS_PAT_GEN_CPHY_LRTE_FOOT_CNT_SHIFT 12
#define CPHY_PRBS_PAT_GEN_CPHY_LRTE_FOOT_CNT_MASK (0x1f << 12)
#define CPHY_PRBS_PAT_GEN_LRTE_EN_SHIFT 17
#define CPHY_PRBS_PAT_GEN_LRTE_EN_MASK (0x1 << 17)
#define CPHY_PRBS_PAT_GEN_TRAIL_STAGE_CNT_SHIFT 23
#define CPHY_PRBS_PAT_GEN_TRAIL_STAGE_CNT_MASK (0xff << 23)
#define CPHY_PRBS_PAT_GEN_NONSTOP_LONG_PKT_EN_SHIFT 31
#define CPHY_PRBS_PAT_GEN_NONSTOP_LONG_PKT_EN_MASK (0x1 << 31)

#define CPHY_PRBS_PAT_GEN_STATUS 0x0198
#define PRBS_PAT_GEN_DONE_SHIFT 0
#define PRBS_PAT_GEN_DONE_MASK (0x1 << 0)

#define CPHY_LP_CNT_CTRL 0x019c
#define CPHY_LP11_CNT_SHIFT 0
#define CPHY_LP11_CNT_MASK (0x7f << 0)
#define CPHY_LP11_CNT_EN_SHIFT 7
#define CPHY_LP11_CNT_EN_MASK (0x1 << 7)
#define CPHY_LP10_CNT_SHIFT 8
#define CPHY_LP10_CNT_MASK (0x7f << 8)
#define CPHY_LP10_CNT_EN_SHIFT 15
#define CPHY_LP10_CNT_EN_MASK (0x1 << 15)
#define CPHY_LP01_CNT_SHIFT 16
#define CPHY_LP01_CNT_MASK (0x7f << 16)
#define CPHY_LP01_CNT_EN_SHIFT 23
#define CPHY_LP01_CNT_EN_MASK (0x1 << 23)
#define CPHY_LP00_CNT_SHIFT 24
#define CPHY_LP00_CNT_MASK (0x7f << 24)
#define CPHY_LP00_CNT_EN_SHIFT 31
#define CPHY_LP00_CNT_EN_MASK (0x1 << 31)

#define CPHY_AUTO_DETECT 0x0200
#define CPHY_TRIO0_AUTO_DETECT_CNT_SHIFT 0
#define CPHY_TRIO0_AUTO_DETECT_CNT_MASK (0x3ff << 0)
#define CPHY_TRIO1_AUTO_DETECT_CNT_SHIFT 10
#define CPHY_TRIO1_AUTO_DETECT_CNT_MASK (0x3ff << 10)
#define CPHY_TRIO2_AUTO_DETECT_CNT_SHIFT 20
#define CPHY_TRIO2_AUTO_DETECT_CNT_MASK (0x3ff << 20)
#define CPHY_AUTO_DETECT_EN_SHIFT 31
#define CPHY_AUTO_DETECT_EN_MASK (0x1 << 31)

#define CPHY_FSM_FLUSH_CTRL 0x0204
#define CSI_CPHY_TRIO0_FLUSH_EN_SHIFT 0
#define CSI_CPHY_TRIO0_FLUSH_EN_MASK (0x1 << 0)
#define CSI_CPHY_TRIO1_FLUSH_EN_SHIFT 1
#define CSI_CPHY_TRIO1_FLUSH_EN_MASK (0x1 << 1)
#define CSI_CPHY_TRIO2_FLUSH_EN_SHIFT 2
#define CSI_CPHY_TRIO2_FLUSH_EN_MASK (0x1 << 2)
#define CSI_CPHY_TRIO3_FLUSH_EN_SHIFT 3
#define CSI_CPHY_TRIO3_FLUSH_EN_MASK (0x1 << 3)

#define CPHY_POST_ENCODE 0x0208
#define CPHY_POST_ENCODE_EN_SHIFT 0
#define CPHY_POST_ENCODE_EN_MASK (0x1 << 0)
#define CPHY_POST_REPLACE_EN_SHIFT 1
#define CPHY_POST_REPLACE_EN_MASK (0x1 << 1)
#define CPHY_POST_REPLACE_CNT_SHIFT 4
#define CPHY_POST_REPLACE_CNT_MASK (0xf << 4)

#define SWAP_SECURITY_EN 0x020c
#define SWAP_SECURITY_EN_SHIFT 0
#define SWAP_SECURITY_EN_MASK (0x1 << 0)

#define CPHY_IPM_Version 0x0fe0
#define IPM_VERSION_ECO_SHIFT 0
#define IPM_VERSION_ECO_MASK (0xff << 0)
#define IPM_VERSION_BRANCH_SHIFT 8
#define IPM_VERSION_BRANCH_MASK (0xff << 8)
#define IPM_VERSION_MINOR_SHIFT 16
#define IPM_VERSION_MINOR_MASK (0xff << 16)
#define IPM_VERSION_MAJOR_SHIFT 24
#define IPM_VERSION_MAJOR_MASK (0xff << 24)

#endif
