/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */

#ifndef __SENINF_ASYTOP_E1A_C_HEADER_H__
#define __SENINF_ASYTOP_E1A_C_HEADER_H__

#define SENINF_ASYTOP_SENINF_ASYNC_CFG 0x0000
#define SENINF_ASYTOP_TESTMDL_SEL_SHIFT 0
#define SENINF_ASYTOP_TESTMDL_SEL_MASK (0x3f << 0)
#define SENINF_ASYTOP_MIPI_SPLIT_SHIFT 8
#define SENINF_ASYTOP_MIPI_SPLIT_MASK (0xfff << 8)
#define SENINF_ASYTOP_DEBUG_EN_SHIFT 24
#define SENINF_ASYTOP_DEBUG_EN_MASK (0x3f << 24)

#define SENINF_ASYTOP_SENINF_ASYNC_RSV_0 0x0004
#define SENINF_ASYTOP_RSV_0_SHIFT 0
#define SENINF_ASYTOP_RSV_0_MASK (0xffffffff << 0)

#define SENINF_ASYTOP_SENINF_ASYNC_RSV_1 0x0008
#define SENINF_ASYTOP_RSV_1_SHIFT 0
#define SENINF_ASYTOP_RSV_1_MASK (0xffffffff << 0)

#define SENINF_ASYTOP_SENINF_ASYNC_PRBS_0 0x0030
#define SENINF_ASYTOP_PRBS_CHK_EN_0_SHIFT 0
#define SENINF_ASYTOP_PRBS_CHK_EN_0_MASK (0x1 << 0)
#define SENINF_ASYTOP_PRBS_CHK_MODE_0_SHIFT 1
#define SENINF_ASYTOP_PRBS_CHK_MODE_0_MASK (0x1 << 1)
#define SENINF_ASYTOP_PRBS_CHK_DONE_0_SHIFT 4
#define SENINF_ASYTOP_PRBS_CHK_DONE_0_MASK (0x1 << 4)
#define SENINF_ASYTOP_PRBS_CHK_FAIL_0_SHIFT 5
#define SENINF_ASYTOP_PRBS_CHK_FAIL_0_MASK (0x1 << 5)

#define SENINF_ASYTOP_SENINF_ASYNC_FIFO_BIST_CTRL_0 0x0034
#define SENINF_ASYTOP_AFIFO_BIST_MODE_0_SHIFT 0
#define SENINF_ASYTOP_AFIFO_BIST_MODE_0_MASK (0x1 << 0)
#define SENINF_ASYTOP_AFIFO_BIST_RST_0_SHIFT 1
#define SENINF_ASYTOP_AFIFO_BIST_RST_0_MASK (0x1 << 1)
#define SENINF_ASYTOP_AFIFO_BIST_EN_0_SHIFT 4
#define SENINF_ASYTOP_AFIFO_BIST_EN_0_MASK (0x1 << 4)
#define SENINF_ASYTOP_AFIFO_BIST_SEED_SEL_0_SHIFT 5
#define SENINF_ASYTOP_AFIFO_BIST_SEED_SEL_0_MASK (0x1 << 5)
#define SENINF_ASYTOP_AFIFO_BIST_WRT_LENGTH_0_SHIFT 8
#define SENINF_ASYTOP_AFIFO_BIST_WRT_LENGTH_0_MASK (0xf << 8)
#define SENINF_ASYTOP_AFIFO_BIST_STP_LENGTH_0_SHIFT 12
#define SENINF_ASYTOP_AFIFO_BIST_STP_LENGTH_0_MASK (0xf << 12)
#define SENINF_ASYTOP_AFIFO_BIST_LENGTH_0_SHIFT 16
#define SENINF_ASYTOP_AFIFO_BIST_LENGTH_0_MASK (0xffff << 16)

#define SENINF_ASYTOP_SENINF_ASYNC_FIFO_BIST_STATUS_0 0x0038
#define SENINF_ASYTOP_AFIFO_BIST_FAIL_0_SHIFT 16
#define SENINF_ASYTOP_AFIFO_BIST_FAIL_0_MASK (0x3ff << 16)
#define SENINF_ASYTOP_AFIFO_BIST_DONE_0_SHIFT 31
#define SENINF_ASYTOP_AFIFO_BIST_DONE_0_MASK (0x1 << 31)

#define SENINF_ASYTOP_SENINF_ASYNC_DBG_PORT0_0 0x003c
#define SENINF_ASYTOP_ASYNC_DBG_PORT0_0_SHIFT 0
#define SENINF_ASYTOP_ASYNC_DBG_PORT0_0_MASK (0xffffffff << 0)

#define SENINF_ASYTOP_SENINF_ASYNC_DBG_PORT1_0 0x0040
#define SENINF_ASYTOP_ASYNC_DBG_PORT1_0_SHIFT 0
#define SENINF_ASYTOP_ASYNC_DBG_PORT1_0_MASK (0xffffffff << 0)

#define SENINF_ASYTOP_SENINF_ASYNC_DBG_PORT2_0 0x0044
#define SENINF_ASYTOP_ASYNC_DBG_PORT2_0_SHIFT 0
#define SENINF_ASYTOP_ASYNC_DBG_PORT2_0_MASK (0xffffffff << 0)

#define SENINF_ASYTOP_SENINF_ASYNC_PRBS_1 0x0050
#define SENINF_ASYTOP_PRBS_CHK_EN_1_SHIFT 0
#define SENINF_ASYTOP_PRBS_CHK_EN_1_MASK (0x1 << 0)
#define SENINF_ASYTOP_PRBS_CHK_MODE_1_SHIFT 1
#define SENINF_ASYTOP_PRBS_CHK_MODE_1_MASK (0x1 << 1)
#define SENINF_ASYTOP_PRBS_CHK_DONE_1_SHIFT 4
#define SENINF_ASYTOP_PRBS_CHK_DONE_1_MASK (0x1 << 4)
#define SENINF_ASYTOP_PRBS_CHK_FAIL_1_SHIFT 5
#define SENINF_ASYTOP_PRBS_CHK_FAIL_1_MASK (0x1 << 5)

#define SENINF_ASYTOP_SENINF_ASYNC_FIFO_BIST_CTRL_1 0x0054
#define SENINF_ASYTOP_AFIFO_BIST_MODE_1_SHIFT 0
#define SENINF_ASYTOP_AFIFO_BIST_MODE_1_MASK (0x1 << 0)
#define SENINF_ASYTOP_AFIFO_BIST_RST_1_SHIFT 1
#define SENINF_ASYTOP_AFIFO_BIST_RST_1_MASK (0x1 << 1)
#define SENINF_ASYTOP_AFIFO_BIST_EN_1_SHIFT 4
#define SENINF_ASYTOP_AFIFO_BIST_EN_1_MASK (0x1 << 4)
#define SENINF_ASYTOP_AFIFO_BIST_SEED_SEL_1_SHIFT 5
#define SENINF_ASYTOP_AFIFO_BIST_SEED_SEL_1_MASK (0x1 << 5)
#define SENINF_ASYTOP_AFIFO_BIST_WRT_LENGTH_1_SHIFT 8
#define SENINF_ASYTOP_AFIFO_BIST_WRT_LENGTH_1_MASK (0xf << 8)
#define SENINF_ASYTOP_AFIFO_BIST_STP_LENGTH_1_SHIFT 12
#define SENINF_ASYTOP_AFIFO_BIST_STP_LENGTH_1_MASK (0xf << 12)
#define SENINF_ASYTOP_AFIFO_BIST_LENGTH_1_SHIFT 16
#define SENINF_ASYTOP_AFIFO_BIST_LENGTH_1_MASK (0xffff << 16)

#define SENINF_ASYTOP_SENINF_ASYNC_FIFO_BIST_STATUS_1 0x0058
#define SENINF_ASYTOP_AFIFO_BIST_FAIL_1_SHIFT 16
#define SENINF_ASYTOP_AFIFO_BIST_FAIL_1_MASK (0x3ff << 16)
#define SENINF_ASYTOP_AFIFO_BIST_DONE_1_SHIFT 31
#define SENINF_ASYTOP_AFIFO_BIST_DONE_1_MASK (0x1 << 31)

#define SENINF_ASYTOP_SENINF_ASYNC_DBG_PORT0_1 0x005c
#define SENINF_ASYTOP_ASYNC_DBG_PORT0_1_SHIFT 0
#define SENINF_ASYTOP_ASYNC_DBG_PORT0_1_MASK (0xffffffff << 0)

#define SENINF_ASYTOP_SENINF_ASYNC_DBG_PORT1_1 0x0060
#define SENINF_ASYTOP_ASYNC_DBG_PORT1_1_SHIFT 0
#define SENINF_ASYTOP_ASYNC_DBG_PORT1_1_MASK (0xffffffff << 0)

#define SENINF_ASYTOP_SENINF_ASYNC_DBG_PORT2_1 0x0064
#define SENINF_ASYTOP_ASYNC_DBG_PORT2_1_SHIFT 0
#define SENINF_ASYTOP_ASYNC_DBG_PORT2_1_MASK (0xffffffff << 0)

#define SENINF_ASYTOP_SENINF_ASYNC_PRBS_2 0x0070
#define SENINF_ASYTOP_PRBS_CHK_EN_2_SHIFT 0
#define SENINF_ASYTOP_PRBS_CHK_EN_2_MASK (0x1 << 0)
#define SENINF_ASYTOP_PRBS_CHK_MODE_2_SHIFT 1
#define SENINF_ASYTOP_PRBS_CHK_MODE_2_MASK (0x1 << 1)
#define SENINF_ASYTOP_PRBS_CHK_DONE_2_SHIFT 4
#define SENINF_ASYTOP_PRBS_CHK_DONE_2_MASK (0x1 << 4)
#define SENINF_ASYTOP_PRBS_CHK_FAIL_2_SHIFT 5
#define SENINF_ASYTOP_PRBS_CHK_FAIL_2_MASK (0x1 << 5)

#define SENINF_ASYTOP_SENINF_ASYNC_FIFO_BIST_CTRL_2 0x0074
#define SENINF_ASYTOP_AFIFO_BIST_MODE_2_SHIFT 0
#define SENINF_ASYTOP_AFIFO_BIST_MODE_2_MASK (0x1 << 0)
#define SENINF_ASYTOP_AFIFO_BIST_RST_2_SHIFT 1
#define SENINF_ASYTOP_AFIFO_BIST_RST_2_MASK (0x1 << 1)
#define SENINF_ASYTOP_AFIFO_BIST_EN_2_SHIFT 4
#define SENINF_ASYTOP_AFIFO_BIST_EN_2_MASK (0x1 << 4)
#define SENINF_ASYTOP_AFIFO_BIST_SEED_SEL_2_SHIFT 5
#define SENINF_ASYTOP_AFIFO_BIST_SEED_SEL_2_MASK (0x1 << 5)
#define SENINF_ASYTOP_AFIFO_BIST_WRT_LENGTH_2_SHIFT 8
#define SENINF_ASYTOP_AFIFO_BIST_WRT_LENGTH_2_MASK (0xf << 8)
#define SENINF_ASYTOP_AFIFO_BIST_STP_LENGTH_2_SHIFT 12
#define SENINF_ASYTOP_AFIFO_BIST_STP_LENGTH_2_MASK (0xf << 12)
#define SENINF_ASYTOP_AFIFO_BIST_LENGTH_2_SHIFT 16
#define SENINF_ASYTOP_AFIFO_BIST_LENGTH_2_MASK (0xffff << 16)

#define SENINF_ASYTOP_SENINF_ASYNC_FIFO_BIST_STATUS_2 0x0078
#define SENINF_ASYTOP_AFIFO_BIST_FAIL_2_SHIFT 16
#define SENINF_ASYTOP_AFIFO_BIST_FAIL_2_MASK (0x3ff << 16)
#define SENINF_ASYTOP_AFIFO_BIST_DONE_2_SHIFT 31
#define SENINF_ASYTOP_AFIFO_BIST_DONE_2_MASK (0x1 << 31)

#define SENINF_ASYTOP_SENINF_ASYNC_DBG_PORT0_2 0x007c
#define SENINF_ASYTOP_ASYNC_DBG_PORT0_2_SHIFT 0
#define SENINF_ASYTOP_ASYNC_DBG_PORT0_2_MASK (0xffffffff << 0)

#define SENINF_ASYTOP_SENINF_ASYNC_DBG_PORT1_2 0x0080
#define SENINF_ASYTOP_ASYNC_DBG_PORT1_2_SHIFT 0
#define SENINF_ASYTOP_ASYNC_DBG_PORT1_2_MASK (0xffffffff << 0)

#define SENINF_ASYTOP_SENINF_ASYNC_DBG_PORT2_2 0x0084
#define SENINF_ASYTOP_ASYNC_DBG_PORT2_2_SHIFT 0
#define SENINF_ASYTOP_ASYNC_DBG_PORT2_2_MASK (0xffffffff << 0)

#define SENINF_ASYTOP_SENINF_ASYNC_PRBS_3 0x0090
#define SENINF_ASYTOP_PRBS_CHK_EN_3_SHIFT 0
#define SENINF_ASYTOP_PRBS_CHK_EN_3_MASK (0x1 << 0)
#define SENINF_ASYTOP_PRBS_CHK_MODE_3_SHIFT 1
#define SENINF_ASYTOP_PRBS_CHK_MODE_3_MASK (0x1 << 1)
#define SENINF_ASYTOP_PRBS_CHK_DONE_3_SHIFT 4
#define SENINF_ASYTOP_PRBS_CHK_DONE_3_MASK (0x1 << 4)
#define SENINF_ASYTOP_PRBS_CHK_FAIL_3_SHIFT 5
#define SENINF_ASYTOP_PRBS_CHK_FAIL_3_MASK (0x1 << 5)

#define SENINF_ASYTOP_SENINF_ASYNC_FIFO_BIST_CTRL_3 0x0094
#define SENINF_ASYTOP_AFIFO_BIST_MODE_3_SHIFT 0
#define SENINF_ASYTOP_AFIFO_BIST_MODE_3_MASK (0x1 << 0)
#define SENINF_ASYTOP_AFIFO_BIST_RST_3_SHIFT 1
#define SENINF_ASYTOP_AFIFO_BIST_RST_3_MASK (0x1 << 1)
#define SENINF_ASYTOP_AFIFO_BIST_EN_3_SHIFT 4
#define SENINF_ASYTOP_AFIFO_BIST_EN_3_MASK (0x1 << 4)
#define SENINF_ASYTOP_AFIFO_BIST_SEED_SEL_3_SHIFT 5
#define SENINF_ASYTOP_AFIFO_BIST_SEED_SEL_3_MASK (0x1 << 5)
#define SENINF_ASYTOP_AFIFO_BIST_WRT_LENGTH_3_SHIFT 8
#define SENINF_ASYTOP_AFIFO_BIST_WRT_LENGTH_3_MASK (0xf << 8)
#define SENINF_ASYTOP_AFIFO_BIST_STP_LENGTH_3_SHIFT 12
#define SENINF_ASYTOP_AFIFO_BIST_STP_LENGTH_3_MASK (0xf << 12)
#define SENINF_ASYTOP_AFIFO_BIST_LENGTH_3_SHIFT 16
#define SENINF_ASYTOP_AFIFO_BIST_LENGTH_3_MASK (0xffff << 16)

#define SENINF_ASYTOP_SENINF_ASYNC_FIFO_BIST_STATUS_3 0x0098
#define SENINF_ASYTOP_AFIFO_BIST_FAIL_3_SHIFT 16
#define SENINF_ASYTOP_AFIFO_BIST_FAIL_3_MASK (0x3ff << 16)
#define SENINF_ASYTOP_AFIFO_BIST_DONE_3_SHIFT 31
#define SENINF_ASYTOP_AFIFO_BIST_DONE_3_MASK (0x1 << 31)

#define SENINF_ASYTOP_SENINF_ASYNC_DBG_PORT0_3 0x009c
#define SENINF_ASYTOP_ASYNC_DBG_PORT0_3_SHIFT 0
#define SENINF_ASYTOP_ASYNC_DBG_PORT0_3_MASK (0xffffffff << 0)

#define SENINF_ASYTOP_SENINF_ASYNC_DBG_PORT1_3 0x00a0
#define SENINF_ASYTOP_ASYNC_DBG_PORT1_3_SHIFT 0
#define SENINF_ASYTOP_ASYNC_DBG_PORT1_3_MASK (0xffffffff << 0)

#define SENINF_ASYTOP_SENINF_ASYNC_DBG_PORT2_3 0x00a4
#define SENINF_ASYTOP_ASYNC_DBG_PORT2_3_SHIFT 0
#define SENINF_ASYTOP_ASYNC_DBG_PORT2_3_MASK (0xffffffff << 0)

#define SENINF_ASYTOP_SENINF_ASYNC_PRBS_4 0x00b0
#define SENINF_ASYTOP_PRBS_CHK_EN_4_SHIFT 0
#define SENINF_ASYTOP_PRBS_CHK_EN_4_MASK (0x1 << 0)
#define SENINF_ASYTOP_PRBS_CHK_MODE_4_SHIFT 1
#define SENINF_ASYTOP_PRBS_CHK_MODE_4_MASK (0x1 << 1)
#define SENINF_ASYTOP_PRBS_CHK_DONE_4_SHIFT 4
#define SENINF_ASYTOP_PRBS_CHK_DONE_4_MASK (0x1 << 4)
#define SENINF_ASYTOP_PRBS_CHK_FAIL_4_SHIFT 5
#define SENINF_ASYTOP_PRBS_CHK_FAIL_4_MASK (0x1 << 5)

#define SENINF_ASYTOP_SENINF_ASYNC_FIFO_BIST_CTRL_4 0x00b4
#define SENINF_ASYTOP_AFIFO_BIST_MODE_4_SHIFT 0
#define SENINF_ASYTOP_AFIFO_BIST_MODE_4_MASK (0x1 << 0)
#define SENINF_ASYTOP_AFIFO_BIST_RST_4_SHIFT 1
#define SENINF_ASYTOP_AFIFO_BIST_RST_4_MASK (0x1 << 1)
#define SENINF_ASYTOP_AFIFO_BIST_EN_4_SHIFT 4
#define SENINF_ASYTOP_AFIFO_BIST_EN_4_MASK (0x1 << 4)
#define SENINF_ASYTOP_AFIFO_BIST_SEED_SEL_4_SHIFT 5
#define SENINF_ASYTOP_AFIFO_BIST_SEED_SEL_4_MASK (0x1 << 5)
#define SENINF_ASYTOP_AFIFO_BIST_WRT_LENGTH_4_SHIFT 8
#define SENINF_ASYTOP_AFIFO_BIST_WRT_LENGTH_4_MASK (0xf << 8)
#define SENINF_ASYTOP_AFIFO_BIST_STP_LENGTH_4_SHIFT 12
#define SENINF_ASYTOP_AFIFO_BIST_STP_LENGTH_4_MASK (0xf << 12)
#define SENINF_ASYTOP_AFIFO_BIST_LENGTH_4_SHIFT 16
#define SENINF_ASYTOP_AFIFO_BIST_LENGTH_4_MASK (0xffff << 16)

#define SENINF_ASYTOP_SENINF_ASYNC_FIFO_BIST_STATUS_4 0x00b8
#define SENINF_ASYTOP_AFIFO_BIST_FAIL_4_SHIFT 16
#define SENINF_ASYTOP_AFIFO_BIST_FAIL_4_MASK (0x3ff << 16)
#define SENINF_ASYTOP_AFIFO_BIST_DONE_4_SHIFT 31
#define SENINF_ASYTOP_AFIFO_BIST_DONE_4_MASK (0x1 << 31)

#define SENINF_ASYTOP_SENINF_ASYNC_DBG_PORT0_4 0x00bc
#define SENINF_ASYTOP_ASYNC_DBG_PORT0_4_SHIFT 0
#define SENINF_ASYTOP_ASYNC_DBG_PORT0_4_MASK (0xffffffff << 0)

#define SENINF_ASYTOP_SENINF_ASYNC_DBG_PORT1_4 0x00c0
#define SENINF_ASYTOP_ASYNC_DBG_PORT1_4_SHIFT 0
#define SENINF_ASYTOP_ASYNC_DBG_PORT1_4_MASK (0xffffffff << 0)

#define SENINF_ASYTOP_SENINF_ASYNC_DBG_PORT2_4 0x00c4
#define SENINF_ASYTOP_ASYNC_DBG_PORT2_4_SHIFT 0
#define SENINF_ASYTOP_ASYNC_DBG_PORT2_4_MASK (0xffffffff << 0)

#define SENINF_ASYTOP_SENINF_ASYNC_PRBS_5 0x00d0
#define SENINF_ASYTOP_PRBS_CHK_EN_5_SHIFT 0
#define SENINF_ASYTOP_PRBS_CHK_EN_5_MASK (0x1 << 0)
#define SENINF_ASYTOP_PRBS_CHK_MODE_5_SHIFT 1
#define SENINF_ASYTOP_PRBS_CHK_MODE_5_MASK (0x1 << 1)
#define SENINF_ASYTOP_PRBS_CHK_DONE_5_SHIFT 4
#define SENINF_ASYTOP_PRBS_CHK_DONE_5_MASK (0x1 << 4)
#define SENINF_ASYTOP_PRBS_CHK_FAIL_5_SHIFT 5
#define SENINF_ASYTOP_PRBS_CHK_FAIL_5_MASK (0x1 << 5)

#define SENINF_ASYTOP_SENINF_ASYNC_FIFO_BIST_CTRL_5 0x00d4
#define SENINF_ASYTOP_AFIFO_BIST_MODE_5_SHIFT 0
#define SENINF_ASYTOP_AFIFO_BIST_MODE_5_MASK (0x1 << 0)
#define SENINF_ASYTOP_AFIFO_BIST_RST_5_SHIFT 1
#define SENINF_ASYTOP_AFIFO_BIST_RST_5_MASK (0x1 << 1)
#define SENINF_ASYTOP_AFIFO_BIST_EN_5_SHIFT 4
#define SENINF_ASYTOP_AFIFO_BIST_EN_5_MASK (0x1 << 4)
#define SENINF_ASYTOP_AFIFO_BIST_SEED_SEL_5_SHIFT 5
#define SENINF_ASYTOP_AFIFO_BIST_SEED_SEL_5_MASK (0x1 << 5)
#define SENINF_ASYTOP_AFIFO_BIST_WRT_LENGTH_5_SHIFT 8
#define SENINF_ASYTOP_AFIFO_BIST_WRT_LENGTH_5_MASK (0xf << 8)
#define SENINF_ASYTOP_AFIFO_BIST_STP_LENGTH_5_SHIFT 12
#define SENINF_ASYTOP_AFIFO_BIST_STP_LENGTH_5_MASK (0xf << 12)
#define SENINF_ASYTOP_AFIFO_BIST_LENGTH_5_SHIFT 16
#define SENINF_ASYTOP_AFIFO_BIST_LENGTH_5_MASK (0xffff << 16)

#define SENINF_ASYTOP_SENINF_ASYNC_FIFO_BIST_STATUS_5 0x00d8
#define SENINF_ASYTOP_AFIFO_BIST_FAIL_5_SHIFT 16
#define SENINF_ASYTOP_AFIFO_BIST_FAIL_5_MASK (0x3ff << 16)
#define SENINF_ASYTOP_AFIFO_BIST_DONE_5_SHIFT 31
#define SENINF_ASYTOP_AFIFO_BIST_DONE_5_MASK (0x1 << 31)

#define SENINF_ASYTOP_SENINF_ASYNC_DBG_PORT0_5 0x00dc
#define SENINF_ASYTOP_ASYNC_DBG_PORT0_5_SHIFT 0
#define SENINF_ASYTOP_ASYNC_DBG_PORT0_5_MASK (0xffffffff << 0)

#define SENINF_ASYTOP_SENINF_ASYNC_DBG_PORT1_5 0x00e0
#define SENINF_ASYTOP_ASYNC_DBG_PORT1_5_SHIFT 0
#define SENINF_ASYTOP_ASYNC_DBG_PORT1_5_MASK (0xffffffff << 0)

#define SENINF_ASYTOP_SENINF_ASYNC_DBG_PORT2_5 0x00e4
#define SENINF_ASYTOP_ASYNC_DBG_PORT2_5_SHIFT 0
#define SENINF_ASYTOP_ASYNC_DBG_PORT2_5_MASK (0xffffffff << 0)

#endif
