/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */

#ifndef __SENINF_OUTMUX_E1A_C_HEADER_H__
#define __SENINF_OUTMUX_E1A_C_HEADER_H__

#define SENINF_OUTMUX_SW_CONFIG_MODE 0x0000
#define SENINF_OUTMUX_CONFIG_MODE_SHIFT 0
#define SENINF_OUTMUX_CONFIG_MODE_MASK (0x3 << 0)
#define SENINF_OUTMUX_CFG_SIDEBAND_EN_SHIFT 8
#define SENINF_OUTMUX_CFG_SIDEBAND_EN_MASK (0x1 << 8)
#define SENINF_OUTMUX_SLAVE_MODE_SHIFT 16
#define SENINF_OUTMUX_SLAVE_MODE_MASK (0x1 << 16)
#define SENINF_OUTMUX_SLAVE_REF_SHIFT 17
#define SENINF_OUTMUX_SLAVE_REF_MASK (0x1f << 17)

#define SENINF_OUTMUX_FILT_MODE 0x0004
#define SENINF_OUTMUX_FILT_MODE_SHIFT 0
#define SENINF_OUTMUX_FILT_MODE_MASK (0x3 << 0)

#define SENINF_OUTMUX_PIX_MODE 0x0008
#define SENINF_OUTMUX_PIX_MODE_SHIFT 0
#define SENINF_OUTMUX_PIX_MODE_MASK (0x1 << 0)

#define SENINF_OUTMUX_SOURCE_CONFIG_0 0x000c
#define SENINF_OUTMUX_VSYNC_SRC_SEL_SEN_SHIFT 0
#define SENINF_OUTMUX_VSYNC_SRC_SEL_SEN_MASK (0x3 << 0)
#define SENINF_OUTMUX_VSYNC_SRC_SEL_MIPI_SHIFT 4
#define SENINF_OUTMUX_VSYNC_SRC_SEL_MIPI_MASK (0x7 << 4)
#define SENINF_OUTMUX_REF_VC_SHIFT 8
#define SENINF_OUTMUX_REF_VC_MASK (0x1f << 8)
#define SENINF_OUTMUX_LAST_VC_SHIFT 16
#define SENINF_OUTMUX_LAST_VC_MASK (0x1f << 16)

#define SENINF_OUTMUX_SOURCE_CONFIG_1 0x0010
#define SENINF_OUTMUX_TAG_VC_0_SHIFT 0
#define SENINF_OUTMUX_TAG_VC_0_MASK (0x1f << 0)
#define SENINF_OUTMUX_TAG_VC_1_SHIFT 8
#define SENINF_OUTMUX_TAG_VC_1_MASK (0x1f << 8)
#define SENINF_OUTMUX_TAG_VC_2_SHIFT 16
#define SENINF_OUTMUX_TAG_VC_2_MASK (0x1f << 16)
#define SENINF_OUTMUX_TAG_VC_3_SHIFT 24
#define SENINF_OUTMUX_TAG_VC_3_MASK (0x1f << 24)

#define SENINF_OUTMUX_SOURCE_CONFIG_2 0x0014
#define SENINF_OUTMUX_TAG_VC_4_SHIFT 0
#define SENINF_OUTMUX_TAG_VC_4_MASK (0x1f << 0)
#define SENINF_OUTMUX_TAG_VC_5_SHIFT 8
#define SENINF_OUTMUX_TAG_VC_5_MASK (0x1f << 8)
#define SENINF_OUTMUX_TAG_VC_6_SHIFT 16
#define SENINF_OUTMUX_TAG_VC_6_MASK (0x1f << 16)
#define SENINF_OUTMUX_TAG_VC_7_SHIFT 24
#define SENINF_OUTMUX_TAG_VC_7_MASK (0x1f << 24)

#define SENINF_OUTMUX_SRC_SEL 0x0018
#define SENINF_OUTMUX_SRC_SEL_SEN_SHIFT 0
#define SENINF_OUTMUX_SRC_SEL_SEN_MASK (0x3 << 0)
#define SENINF_OUTMUX_SRC_SEL_MIPI_SHIFT 4
#define SENINF_OUTMUX_SRC_SEL_MIPI_MASK (0x7 << 4)

#define SENINF_OUTMUX_SW_CFG_DONE 0x001c
#define SENINF_OUTMUX_SW_CFG_DONE_SHIFT 0
#define SENINF_OUTMUX_SW_CFG_DONE_MASK (0x1 << 0)

#define SENINF_OUTMUX_CSR_CFG_CTRL 0x0020
#define SENINF_OUTMUX_INT_WCLR_EN_SHIFT 0
#define SENINF_OUTMUX_INT_WCLR_EN_MASK (0x1 << 0)
#define SENINF_OUTMUX_VERIF_EN_SHIFT 4
#define SENINF_OUTMUX_VERIF_EN_MASK (0x1 << 4)
#define SENINF_OUTMUX_CRC_EN_SHIFT 8
#define SENINF_OUTMUX_CRC_EN_MASK (0x1 << 8)
#define SENINF_OUTMUX_HIGH_BIT_MODE_SHIFT 16
#define SENINF_OUTMUX_HIGH_BIT_MODE_MASK (0x1 << 16)
#define SENINF_OUTMUX_CFG_LAG_HANG_RECOVER_SHIFT 24
#define SENINF_OUTMUX_CFG_LAG_HANG_RECOVER_MASK (0x1 << 24)
#define SENINF_OUTMUX_CAM_RDY_GRP_EN_SHIFT 28
#define SENINF_OUTMUX_CAM_RDY_GRP_EN_MASK (0x1 << 28)

#define SENINF_OUTMUX_PATH_DBG_PORT_0 0x0024
#define SENINF_OUTMUX_PATH_DBG_PORT_0_SHIFT 0
#define SENINF_OUTMUX_PATH_DBG_PORT_0_MASK (0xffffffff << 0)

#define SENINF_OUTMUX_PATH_DBG_PORT_1 0x0028
#define SENINF_OUTMUX_PATH_DBG_PORT_1_SHIFT 0
#define SENINF_OUTMUX_PATH_DBG_PORT_1_MASK (0xffffffff << 0)

#define SENINF_OUTMUX_CAM_CFG_RDY 0x002c
#define SENINF_OUTMUX_CAM_CFG_RDY_SHIFT 0
#define SENINF_OUTMUX_CAM_CFG_RDY_MASK (0x1 << 0)

#define SENINF_OUTMUX_BLACK_FRAME 0x0030
#define SENINF_OUTMUX_BLACK_FRAME_SHIFT 0
#define SENINF_OUTMUX_BLACK_FRAME_MASK (0x1 << 0)

#define SENINF_OUTMUX_SW_RST 0x0034
#define SENINF_OUTMUX_LOCAL_SW_RST_SHIFT 0
#define SENINF_OUTMUX_LOCAL_SW_RST_MASK (0x1 << 0)

#define SENINF_OUTMUX_IRQ_EN 0x0040
#define SENINF_OUTMUX_CFG_DONE_IRQ_EN_SHIFT 0
#define SENINF_OUTMUX_CFG_DONE_IRQ_EN_MASK (0x1 << 0)
#define SENINF_OUTMUX_REF_VSYNC_IRQ_EN_SHIFT 1
#define SENINF_OUTMUX_REF_VSYNC_IRQ_EN_MASK (0x1 << 1)
#define SENINF_OUTMUX_CFG_OVERLAP_IRQ_EN_SHIFT 2
#define SENINF_OUTMUX_CFG_OVERLAP_IRQ_EN_MASK (0x1 << 2)
#define SENINF_OUTMUX_CFG_LAG_HANG_IRQ_EN_SHIFT 3
#define SENINF_OUTMUX_CFG_LAG_HANG_IRQ_EN_MASK (0x1 << 3)
#define SENINF_OUTMUX_PIXCVT_OVERRUN_IRQ_EN_SHIFT 4
#define SENINF_OUTMUX_PIXCVT_OVERRUN_IRQ_EN_MASK (0x1 << 4)
#define SENINF_OUTMUX_INCOMP_IRQ_EN_0_SHIFT 8
#define SENINF_OUTMUX_INCOMP_IRQ_EN_0_MASK (0x1 << 8)
#define SENINF_OUTMUX_INCOMP_IRQ_EN_1_SHIFT 9
#define SENINF_OUTMUX_INCOMP_IRQ_EN_1_MASK (0x1 << 9)
#define SENINF_OUTMUX_INCOMP_IRQ_EN_2_SHIFT 10
#define SENINF_OUTMUX_INCOMP_IRQ_EN_2_MASK (0x1 << 10)
#define SENINF_OUTMUX_INCOMP_IRQ_EN_3_SHIFT 11
#define SENINF_OUTMUX_INCOMP_IRQ_EN_3_MASK (0x1 << 11)
#define SENINF_OUTMUX_INCOMP_IRQ_EN_4_SHIFT 12
#define SENINF_OUTMUX_INCOMP_IRQ_EN_4_MASK (0x1 << 12)
#define SENINF_OUTMUX_INCOMP_IRQ_EN_5_SHIFT 13
#define SENINF_OUTMUX_INCOMP_IRQ_EN_5_MASK (0x1 << 13)
#define SENINF_OUTMUX_INCOMP_IRQ_EN_6_SHIFT 14
#define SENINF_OUTMUX_INCOMP_IRQ_EN_6_MASK (0x1 << 14)
#define SENINF_OUTMUX_INCOMP_IRQ_EN_7_SHIFT 15
#define SENINF_OUTMUX_INCOMP_IRQ_EN_7_MASK (0x1 << 15)
#define SENINF_OUTMUX_OVERSIZE_IRQ_EN_0_SHIFT 16
#define SENINF_OUTMUX_OVERSIZE_IRQ_EN_0_MASK (0x1 << 16)
#define SENINF_OUTMUX_OVERSIZE_IRQ_EN_1_SHIFT 17
#define SENINF_OUTMUX_OVERSIZE_IRQ_EN_1_MASK (0x1 << 17)
#define SENINF_OUTMUX_OVERSIZE_IRQ_EN_2_SHIFT 18
#define SENINF_OUTMUX_OVERSIZE_IRQ_EN_2_MASK (0x1 << 18)
#define SENINF_OUTMUX_OVERSIZE_IRQ_EN_3_SHIFT 19
#define SENINF_OUTMUX_OVERSIZE_IRQ_EN_3_MASK (0x1 << 19)
#define SENINF_OUTMUX_OVERSIZE_IRQ_EN_4_SHIFT 20
#define SENINF_OUTMUX_OVERSIZE_IRQ_EN_4_MASK (0x1 << 20)
#define SENINF_OUTMUX_OVERSIZE_IRQ_EN_5_SHIFT 21
#define SENINF_OUTMUX_OVERSIZE_IRQ_EN_5_MASK (0x1 << 21)
#define SENINF_OUTMUX_OVERSIZE_IRQ_EN_6_SHIFT 22
#define SENINF_OUTMUX_OVERSIZE_IRQ_EN_6_MASK (0x1 << 22)
#define SENINF_OUTMUX_OVERSIZE_IRQ_EN_7_SHIFT 23
#define SENINF_OUTMUX_OVERSIZE_IRQ_EN_7_MASK (0x1 << 23)
#define SENINF_OUTMUX_TAG_DONE_IRQ_EN_0_SHIFT 24
#define SENINF_OUTMUX_TAG_DONE_IRQ_EN_0_MASK (0x1 << 24)
#define SENINF_OUTMUX_TAG_DONE_IRQ_EN_1_SHIFT 25
#define SENINF_OUTMUX_TAG_DONE_IRQ_EN_1_MASK (0x1 << 25)
#define SENINF_OUTMUX_TAG_DONE_IRQ_EN_2_SHIFT 26
#define SENINF_OUTMUX_TAG_DONE_IRQ_EN_2_MASK (0x1 << 26)
#define SENINF_OUTMUX_TAG_DONE_IRQ_EN_3_SHIFT 27
#define SENINF_OUTMUX_TAG_DONE_IRQ_EN_3_MASK (0x1 << 27)
#define SENINF_OUTMUX_TAG_DONE_IRQ_EN_4_SHIFT 28
#define SENINF_OUTMUX_TAG_DONE_IRQ_EN_4_MASK (0x1 << 28)
#define SENINF_OUTMUX_TAG_DONE_IRQ_EN_5_SHIFT 29
#define SENINF_OUTMUX_TAG_DONE_IRQ_EN_5_MASK (0x1 << 29)
#define SENINF_OUTMUX_TAG_DONE_IRQ_EN_6_SHIFT 30
#define SENINF_OUTMUX_TAG_DONE_IRQ_EN_6_MASK (0x1 << 30)
#define SENINF_OUTMUX_TAG_DONE_IRQ_EN_7_SHIFT 31
#define SENINF_OUTMUX_TAG_DONE_IRQ_EN_7_MASK (0x1 << 31)

#define SENINF_OUTMUX_IRQ_STATUS 0x0044
#define SENINF_OUTMUX_CFG_DONE_IRQ_STATUS_SHIFT 0
#define SENINF_OUTMUX_CFG_DONE_IRQ_STATUS_MASK (0x1 << 0)
#define SENINF_OUTMUX_REF_VSYNC_IRQ_STATUS_SHIFT 1
#define SENINF_OUTMUX_REF_VSYNC_IRQ_STATUS_MASK (0x1 << 1)
#define SENINF_OUTMUX_CFG_OVERLAP_IRQ_STATUS_SHIFT 2
#define SENINF_OUTMUX_CFG_OVERLAP_IRQ_STATUS_MASK (0x1 << 2)
#define SENINF_OUTMUX_CFG_LAG_HANG_IRQ_STATUS_SHIFT 3
#define SENINF_OUTMUX_CFG_LAG_HANG_IRQ_STATUS_MASK (0x1 << 3)
#define SENINF_OUTMUX_PIXCVT_OVERRUN_IRQ_STATUS_SHIFT 4
#define SENINF_OUTMUX_PIXCVT_OVERRUN_IRQ_STATUS_MASK (0x1 << 4)
#define SENINF_OUTMUX_INCOMP_IRQ_STATUS_0_SHIFT 8
#define SENINF_OUTMUX_INCOMP_IRQ_STATUS_0_MASK (0x1 << 8)
#define SENINF_OUTMUX_INCOMP_IRQ_STATUS_1_SHIFT 9
#define SENINF_OUTMUX_INCOMP_IRQ_STATUS_1_MASK (0x1 << 9)
#define SENINF_OUTMUX_INCOMP_IRQ_STATUS_2_SHIFT 10
#define SENINF_OUTMUX_INCOMP_IRQ_STATUS_2_MASK (0x1 << 10)
#define SENINF_OUTMUX_INCOMP_IRQ_STATUS_3_SHIFT 11
#define SENINF_OUTMUX_INCOMP_IRQ_STATUS_3_MASK (0x1 << 11)
#define SENINF_OUTMUX_INCOMP_IRQ_STATUS_4_SHIFT 12
#define SENINF_OUTMUX_INCOMP_IRQ_STATUS_4_MASK (0x1 << 12)
#define SENINF_OUTMUX_INCOMP_IRQ_STATUS_5_SHIFT 13
#define SENINF_OUTMUX_INCOMP_IRQ_STATUS_5_MASK (0x1 << 13)
#define SENINF_OUTMUX_INCOMP_IRQ_STATUS_6_SHIFT 14
#define SENINF_OUTMUX_INCOMP_IRQ_STATUS_6_MASK (0x1 << 14)
#define SENINF_OUTMUX_INCOMP_IRQ_STATUS_7_SHIFT 15
#define SENINF_OUTMUX_INCOMP_IRQ_STATUS_7_MASK (0x1 << 15)
#define SENINF_OUTMUX_OVERSIZE_IRQ_STATUS_0_SHIFT 16
#define SENINF_OUTMUX_OVERSIZE_IRQ_STATUS_0_MASK (0x1 << 16)
#define SENINF_OUTMUX_OVERSIZE_IRQ_STATUS_1_SHIFT 17
#define SENINF_OUTMUX_OVERSIZE_IRQ_STATUS_1_MASK (0x1 << 17)
#define SENINF_OUTMUX_OVERSIZE_IRQ_STATUS_2_SHIFT 18
#define SENINF_OUTMUX_OVERSIZE_IRQ_STATUS_2_MASK (0x1 << 18)
#define SENINF_OUTMUX_OVERSIZE_IRQ_STATUS_3_SHIFT 19
#define SENINF_OUTMUX_OVERSIZE_IRQ_STATUS_3_MASK (0x1 << 19)
#define SENINF_OUTMUX_OVERSIZE_IRQ_STATUS_4_SHIFT 20
#define SENINF_OUTMUX_OVERSIZE_IRQ_STATUS_4_MASK (0x1 << 20)
#define SENINF_OUTMUX_OVERSIZE_IRQ_STATUS_5_SHIFT 21
#define SENINF_OUTMUX_OVERSIZE_IRQ_STATUS_5_MASK (0x1 << 21)
#define SENINF_OUTMUX_OVERSIZE_IRQ_STATUS_6_SHIFT 22
#define SENINF_OUTMUX_OVERSIZE_IRQ_STATUS_6_MASK (0x1 << 22)
#define SENINF_OUTMUX_OVERSIZE_IRQ_STATUS_7_SHIFT 23
#define SENINF_OUTMUX_OVERSIZE_IRQ_STATUS_7_MASK (0x1 << 23)
#define SENINF_OUTMUX_TAG_DONE_IRQ_STATUS_0_SHIFT 24
#define SENINF_OUTMUX_TAG_DONE_IRQ_STATUS_0_MASK (0x1 << 24)
#define SENINF_OUTMUX_TAG_DONE_IRQ_STATUS_1_SHIFT 25
#define SENINF_OUTMUX_TAG_DONE_IRQ_STATUS_1_MASK (0x1 << 25)
#define SENINF_OUTMUX_TAG_DONE_IRQ_STATUS_2_SHIFT 26
#define SENINF_OUTMUX_TAG_DONE_IRQ_STATUS_2_MASK (0x1 << 26)
#define SENINF_OUTMUX_TAG_DONE_IRQ_STATUS_3_SHIFT 27
#define SENINF_OUTMUX_TAG_DONE_IRQ_STATUS_3_MASK (0x1 << 27)
#define SENINF_OUTMUX_TAG_DONE_IRQ_STATUS_4_SHIFT 28
#define SENINF_OUTMUX_TAG_DONE_IRQ_STATUS_4_MASK (0x1 << 28)
#define SENINF_OUTMUX_TAG_DONE_IRQ_STATUS_5_SHIFT 29
#define SENINF_OUTMUX_TAG_DONE_IRQ_STATUS_5_MASK (0x1 << 29)
#define SENINF_OUTMUX_TAG_DONE_IRQ_STATUS_6_SHIFT 30
#define SENINF_OUTMUX_TAG_DONE_IRQ_STATUS_6_MASK (0x1 << 30)
#define SENINF_OUTMUX_TAG_DONE_IRQ_STATUS_7_SHIFT 31
#define SENINF_OUTMUX_TAG_DONE_IRQ_STATUS_7_MASK (0x1 << 31)

#define SENINF_OUTMUX_IRQ_CCU_EN 0x0048
#define SENINF_OUTMUX_CFG_DONE_IRQ_CCU_EN_SHIFT 0
#define SENINF_OUTMUX_CFG_DONE_IRQ_CCU_EN_MASK (0x1 << 0)
#define SENINF_OUTMUX_REF_VSYNC_IRQ_CCU_EN_SHIFT 1
#define SENINF_OUTMUX_REF_VSYNC_IRQ_CCU_EN_MASK (0x1 << 1)
#define SENINF_OUTMUX_CFG_OVERLAP_IRQ_CCU_EN_SHIFT 2
#define SENINF_OUTMUX_CFG_OVERLAP_IRQ_CCU_EN_MASK (0x1 << 2)
#define SENINF_OUTMUX_CFG_LAG_HANG_IRQ_CCU_EN_SHIFT 3
#define SENINF_OUTMUX_CFG_LAG_HANG_IRQ_CCU_EN_MASK (0x1 << 3)
#define SENINF_OUTMUX_PIXCVT_OVERRUN_IRQ_CCU_EN_SHIFT 4
#define SENINF_OUTMUX_PIXCVT_OVERRUN_IRQ_CCU_EN_MASK (0x1 << 4)
#define SENINF_OUTMUX_INCOMP_IRQ_CCU_EN_0_SHIFT 8
#define SENINF_OUTMUX_INCOMP_IRQ_CCU_EN_0_MASK (0x1 << 8)
#define SENINF_OUTMUX_INCOMP_IRQ_CCU_EN_1_SHIFT 9
#define SENINF_OUTMUX_INCOMP_IRQ_CCU_EN_1_MASK (0x1 << 9)
#define SENINF_OUTMUX_INCOMP_IRQ_CCU_EN_2_SHIFT 10
#define SENINF_OUTMUX_INCOMP_IRQ_CCU_EN_2_MASK (0x1 << 10)
#define SENINF_OUTMUX_INCOMP_IRQ_CCU_EN_3_SHIFT 11
#define SENINF_OUTMUX_INCOMP_IRQ_CCU_EN_3_MASK (0x1 << 11)
#define SENINF_OUTMUX_INCOMP_IRQ_CCU_EN_4_SHIFT 12
#define SENINF_OUTMUX_INCOMP_IRQ_CCU_EN_4_MASK (0x1 << 12)
#define SENINF_OUTMUX_INCOMP_IRQ_CCU_EN_5_SHIFT 13
#define SENINF_OUTMUX_INCOMP_IRQ_CCU_EN_5_MASK (0x1 << 13)
#define SENINF_OUTMUX_INCOMP_IRQ_CCU_EN_6_SHIFT 14
#define SENINF_OUTMUX_INCOMP_IRQ_CCU_EN_6_MASK (0x1 << 14)
#define SENINF_OUTMUX_INCOMP_IRQ_CCU_EN_7_SHIFT 15
#define SENINF_OUTMUX_INCOMP_IRQ_CCU_EN_7_MASK (0x1 << 15)
#define SENINF_OUTMUX_OVERSIZE_IRQ_CCU_EN_0_SHIFT 16
#define SENINF_OUTMUX_OVERSIZE_IRQ_CCU_EN_0_MASK (0x1 << 16)
#define SENINF_OUTMUX_OVERSIZE_IRQ_CCU_EN_1_SHIFT 17
#define SENINF_OUTMUX_OVERSIZE_IRQ_CCU_EN_1_MASK (0x1 << 17)
#define SENINF_OUTMUX_OVERSIZE_IRQ_CCU_EN_2_SHIFT 18
#define SENINF_OUTMUX_OVERSIZE_IRQ_CCU_EN_2_MASK (0x1 << 18)
#define SENINF_OUTMUX_OVERSIZE_IRQ_CCU_EN_3_SHIFT 19
#define SENINF_OUTMUX_OVERSIZE_IRQ_CCU_EN_3_MASK (0x1 << 19)
#define SENINF_OUTMUX_OVERSIZE_IRQ_CCU_EN_4_SHIFT 20
#define SENINF_OUTMUX_OVERSIZE_IRQ_CCU_EN_4_MASK (0x1 << 20)
#define SENINF_OUTMUX_OVERSIZE_IRQ_CCU_EN_5_SHIFT 21
#define SENINF_OUTMUX_OVERSIZE_IRQ_CCU_EN_5_MASK (0x1 << 21)
#define SENINF_OUTMUX_OVERSIZE_IRQ_CCU_EN_6_SHIFT 22
#define SENINF_OUTMUX_OVERSIZE_IRQ_CCU_EN_6_MASK (0x1 << 22)
#define SENINF_OUTMUX_OVERSIZE_IRQ_CCU_EN_7_SHIFT 23
#define SENINF_OUTMUX_OVERSIZE_IRQ_CCU_EN_7_MASK (0x1 << 23)
#define SENINF_OUTMUX_TAG_DONE_IRQ_CCU_EN_0_SHIFT 24
#define SENINF_OUTMUX_TAG_DONE_IRQ_CCU_EN_0_MASK (0x1 << 24)
#define SENINF_OUTMUX_TAG_DONE_IRQ_CCU_EN_1_SHIFT 25
#define SENINF_OUTMUX_TAG_DONE_IRQ_CCU_EN_1_MASK (0x1 << 25)
#define SENINF_OUTMUX_TAG_DONE_IRQ_CCU_EN_2_SHIFT 26
#define SENINF_OUTMUX_TAG_DONE_IRQ_CCU_EN_2_MASK (0x1 << 26)
#define SENINF_OUTMUX_TAG_DONE_IRQ_CCU_EN_3_SHIFT 27
#define SENINF_OUTMUX_TAG_DONE_IRQ_CCU_EN_3_MASK (0x1 << 27)
#define SENINF_OUTMUX_TAG_DONE_IRQ_CCU_EN_4_SHIFT 28
#define SENINF_OUTMUX_TAG_DONE_IRQ_CCU_EN_4_MASK (0x1 << 28)
#define SENINF_OUTMUX_TAG_DONE_IRQ_CCU_EN_5_SHIFT 29
#define SENINF_OUTMUX_TAG_DONE_IRQ_CCU_EN_5_MASK (0x1 << 29)
#define SENINF_OUTMUX_TAG_DONE_IRQ_CCU_EN_6_SHIFT 30
#define SENINF_OUTMUX_TAG_DONE_IRQ_CCU_EN_6_MASK (0x1 << 30)
#define SENINF_OUTMUX_TAG_DONE_IRQ_CCU_EN_7_SHIFT 31
#define SENINF_OUTMUX_TAG_DONE_IRQ_CCU_EN_7_MASK (0x1 << 31)

#define SENINF_OUTMUX_IRQ_CCU_STATUS 0x004c
#define SENINF_OUTMUX_CFG_DONE_IRQ_CCU_STATUS_SHIFT 0
#define SENINF_OUTMUX_CFG_DONE_IRQ_CCU_STATUS_MASK (0x1 << 0)
#define SENINF_OUTMUX_REF_VSYNC_IRQ_CCU_STATUS_SHIFT 1
#define SENINF_OUTMUX_REF_VSYNC_IRQ_CCU_STATUS_MASK (0x1 << 1)
#define SENINF_OUTMUX_CFG_OVERLAP_IRQ_CCU_STATUS_SHIFT 2
#define SENINF_OUTMUX_CFG_OVERLAP_IRQ_CCU_STATUS_MASK (0x1 << 2)
#define SENINF_OUTMUX_CFG_LAG_HANG_IRQ_CCU_STATUS_SHIFT 3
#define SENINF_OUTMUX_CFG_LAG_HANG_IRQ_CCU_STATUS_MASK (0x1 << 3)
#define SENINF_OUTMUX_PIXCVT_OVERRUN_IRQ_CCU_STATUS_SHIFT 4
#define SENINF_OUTMUX_PIXCVT_OVERRUN_IRQ_CCU_STATUS_MASK (0x1 << 4)
#define SENINF_OUTMUX_INCOMP_IRQ_CCU_STATUS_0_SHIFT 8
#define SENINF_OUTMUX_INCOMP_IRQ_CCU_STATUS_0_MASK (0x1 << 8)
#define SENINF_OUTMUX_INCOMP_IRQ_CCU_STATUS_1_SHIFT 9
#define SENINF_OUTMUX_INCOMP_IRQ_CCU_STATUS_1_MASK (0x1 << 9)
#define SENINF_OUTMUX_INCOMP_IRQ_CCU_STATUS_2_SHIFT 10
#define SENINF_OUTMUX_INCOMP_IRQ_CCU_STATUS_2_MASK (0x1 << 10)
#define SENINF_OUTMUX_INCOMP_IRQ_CCU_STATUS_3_SHIFT 11
#define SENINF_OUTMUX_INCOMP_IRQ_CCU_STATUS_3_MASK (0x1 << 11)
#define SENINF_OUTMUX_INCOMP_IRQ_CCU_STATUS_4_SHIFT 12
#define SENINF_OUTMUX_INCOMP_IRQ_CCU_STATUS_4_MASK (0x1 << 12)
#define SENINF_OUTMUX_INCOMP_IRQ_CCU_STATUS_5_SHIFT 13
#define SENINF_OUTMUX_INCOMP_IRQ_CCU_STATUS_5_MASK (0x1 << 13)
#define SENINF_OUTMUX_INCOMP_IRQ_CCU_STATUS_6_SHIFT 14
#define SENINF_OUTMUX_INCOMP_IRQ_CCU_STATUS_6_MASK (0x1 << 14)
#define SENINF_OUTMUX_INCOMP_IRQ_CCU_STATUS_7_SHIFT 15
#define SENINF_OUTMUX_INCOMP_IRQ_CCU_STATUS_7_MASK (0x1 << 15)
#define SENINF_OUTMUX_OVERSIZE_IRQ_CCU_STATUS_0_SHIFT 16
#define SENINF_OUTMUX_OVERSIZE_IRQ_CCU_STATUS_0_MASK (0x1 << 16)
#define SENINF_OUTMUX_OVERSIZE_IRQ_CCU_STATUS_1_SHIFT 17
#define SENINF_OUTMUX_OVERSIZE_IRQ_CCU_STATUS_1_MASK (0x1 << 17)
#define SENINF_OUTMUX_OVERSIZE_IRQ_CCU_STATUS_2_SHIFT 18
#define SENINF_OUTMUX_OVERSIZE_IRQ_CCU_STATUS_2_MASK (0x1 << 18)
#define SENINF_OUTMUX_OVERSIZE_IRQ_CCU_STATUS_3_SHIFT 19
#define SENINF_OUTMUX_OVERSIZE_IRQ_CCU_STATUS_3_MASK (0x1 << 19)
#define SENINF_OUTMUX_OVERSIZE_IRQ_CCU_STATUS_4_SHIFT 20
#define SENINF_OUTMUX_OVERSIZE_IRQ_CCU_STATUS_4_MASK (0x1 << 20)
#define SENINF_OUTMUX_OVERSIZE_IRQ_CCU_STATUS_5_SHIFT 21
#define SENINF_OUTMUX_OVERSIZE_IRQ_CCU_STATUS_5_MASK (0x1 << 21)
#define SENINF_OUTMUX_OVERSIZE_IRQ_CCU_STATUS_6_SHIFT 22
#define SENINF_OUTMUX_OVERSIZE_IRQ_CCU_STATUS_6_MASK (0x1 << 22)
#define SENINF_OUTMUX_OVERSIZE_IRQ_CCU_STATUS_7_SHIFT 23
#define SENINF_OUTMUX_OVERSIZE_IRQ_CCU_STATUS_7_MASK (0x1 << 23)
#define SENINF_OUTMUX_TAG_DONE_IRQ_CCU_STATUS_0_SHIFT 24
#define SENINF_OUTMUX_TAG_DONE_IRQ_CCU_STATUS_0_MASK (0x1 << 24)
#define SENINF_OUTMUX_TAG_DONE_IRQ_CCU_STATUS_1_SHIFT 25
#define SENINF_OUTMUX_TAG_DONE_IRQ_CCU_STATUS_1_MASK (0x1 << 25)
#define SENINF_OUTMUX_TAG_DONE_IRQ_CCU_STATUS_2_SHIFT 26
#define SENINF_OUTMUX_TAG_DONE_IRQ_CCU_STATUS_2_MASK (0x1 << 26)
#define SENINF_OUTMUX_TAG_DONE_IRQ_CCU_STATUS_3_SHIFT 27
#define SENINF_OUTMUX_TAG_DONE_IRQ_CCU_STATUS_3_MASK (0x1 << 27)
#define SENINF_OUTMUX_TAG_DONE_IRQ_CCU_STATUS_4_SHIFT 28
#define SENINF_OUTMUX_TAG_DONE_IRQ_CCU_STATUS_4_MASK (0x1 << 28)
#define SENINF_OUTMUX_TAG_DONE_IRQ_CCU_STATUS_5_SHIFT 29
#define SENINF_OUTMUX_TAG_DONE_IRQ_CCU_STATUS_5_MASK (0x1 << 29)
#define SENINF_OUTMUX_TAG_DONE_IRQ_CCU_STATUS_6_SHIFT 30
#define SENINF_OUTMUX_TAG_DONE_IRQ_CCU_STATUS_6_MASK (0x1 << 30)
#define SENINF_OUTMUX_TAG_DONE_IRQ_CCU_STATUS_7_SHIFT 31
#define SENINF_OUTMUX_TAG_DONE_IRQ_CCU_STATUS_7_MASK (0x1 << 31)

#define SENINF_OUTMUX_IRQ_TRIG 0x0050
#define SENINF_OUTMUX_CFG_DONE_IRQ_TRIG_SHIFT 0
#define SENINF_OUTMUX_CFG_DONE_IRQ_TRIG_MASK (0x1 << 0)
#define SENINF_OUTMUX_REF_VSYNC_IRQ_TRIG_SHIFT 1
#define SENINF_OUTMUX_REF_VSYNC_IRQ_TRIG_MASK (0x1 << 1)
#define SENINF_OUTMUX_CFG_OVERLAP_IRQ_TRIG_SHIFT 2
#define SENINF_OUTMUX_CFG_OVERLAP_IRQ_TRIG_MASK (0x1 << 2)
#define SENINF_OUTMUX_CFG_LAG_HANG_IRQ_TRIG_SHIFT 3
#define SENINF_OUTMUX_CFG_LAG_HANG_IRQ_TRIG_MASK (0x1 << 3)
#define SENINF_OUTMUX_PIXCVT_OVERRUN_IRQ_TRIG_SHIFT 4
#define SENINF_OUTMUX_PIXCVT_OVERRUN_IRQ_TRIG_MASK (0x1 << 4)
#define SENINF_OUTMUX_INCOMP_IRQ_TRIG_0_SHIFT 8
#define SENINF_OUTMUX_INCOMP_IRQ_TRIG_0_MASK (0x1 << 8)
#define SENINF_OUTMUX_INCOMP_IRQ_TRIG_1_SHIFT 9
#define SENINF_OUTMUX_INCOMP_IRQ_TRIG_1_MASK (0x1 << 9)
#define SENINF_OUTMUX_INCOMP_IRQ_TRIG_2_SHIFT 10
#define SENINF_OUTMUX_INCOMP_IRQ_TRIG_2_MASK (0x1 << 10)
#define SENINF_OUTMUX_INCOMP_IRQ_TRIG_3_SHIFT 11
#define SENINF_OUTMUX_INCOMP_IRQ_TRIG_3_MASK (0x1 << 11)
#define SENINF_OUTMUX_INCOMP_IRQ_TRIG_4_SHIFT 12
#define SENINF_OUTMUX_INCOMP_IRQ_TRIG_4_MASK (0x1 << 12)
#define SENINF_OUTMUX_INCOMP_IRQ_TRIG_5_SHIFT 13
#define SENINF_OUTMUX_INCOMP_IRQ_TRIG_5_MASK (0x1 << 13)
#define SENINF_OUTMUX_INCOMP_IRQ_TRIG_6_SHIFT 14
#define SENINF_OUTMUX_INCOMP_IRQ_TRIG_6_MASK (0x1 << 14)
#define SENINF_OUTMUX_INCOMP_IRQ_TRIG_7_SHIFT 15
#define SENINF_OUTMUX_INCOMP_IRQ_TRIG_7_MASK (0x1 << 15)
#define SENINF_OUTMUX_OVERSIZE_IRQ_TRIG_0_SHIFT 16
#define SENINF_OUTMUX_OVERSIZE_IRQ_TRIG_0_MASK (0x1 << 16)
#define SENINF_OUTMUX_OVERSIZE_IRQ_TRIG_1_SHIFT 17
#define SENINF_OUTMUX_OVERSIZE_IRQ_TRIG_1_MASK (0x1 << 17)
#define SENINF_OUTMUX_OVERSIZE_IRQ_TRIG_2_SHIFT 18
#define SENINF_OUTMUX_OVERSIZE_IRQ_TRIG_2_MASK (0x1 << 18)
#define SENINF_OUTMUX_OVERSIZE_IRQ_TRIG_3_SHIFT 19
#define SENINF_OUTMUX_OVERSIZE_IRQ_TRIG_3_MASK (0x1 << 19)
#define SENINF_OUTMUX_OVERSIZE_IRQ_TRIG_4_SHIFT 20
#define SENINF_OUTMUX_OVERSIZE_IRQ_TRIG_4_MASK (0x1 << 20)
#define SENINF_OUTMUX_OVERSIZE_IRQ_TRIG_5_SHIFT 21
#define SENINF_OUTMUX_OVERSIZE_IRQ_TRIG_5_MASK (0x1 << 21)
#define SENINF_OUTMUX_OVERSIZE_IRQ_TRIG_6_SHIFT 22
#define SENINF_OUTMUX_OVERSIZE_IRQ_TRIG_6_MASK (0x1 << 22)
#define SENINF_OUTMUX_OVERSIZE_IRQ_TRIG_7_SHIFT 23
#define SENINF_OUTMUX_OVERSIZE_IRQ_TRIG_7_MASK (0x1 << 23)
#define SENINF_OUTMUX_TAG_DONE_IRQ_TRIG_0_SHIFT 24
#define SENINF_OUTMUX_TAG_DONE_IRQ_TRIG_0_MASK (0x1 << 24)
#define SENINF_OUTMUX_TAG_DONE_IRQ_TRIG_1_SHIFT 25
#define SENINF_OUTMUX_TAG_DONE_IRQ_TRIG_1_MASK (0x1 << 25)
#define SENINF_OUTMUX_TAG_DONE_IRQ_TRIG_2_SHIFT 26
#define SENINF_OUTMUX_TAG_DONE_IRQ_TRIG_2_MASK (0x1 << 26)
#define SENINF_OUTMUX_TAG_DONE_IRQ_TRIG_3_SHIFT 27
#define SENINF_OUTMUX_TAG_DONE_IRQ_TRIG_3_MASK (0x1 << 27)
#define SENINF_OUTMUX_TAG_DONE_IRQ_TRIG_4_SHIFT 28
#define SENINF_OUTMUX_TAG_DONE_IRQ_TRIG_4_MASK (0x1 << 28)
#define SENINF_OUTMUX_TAG_DONE_IRQ_TRIG_5_SHIFT 29
#define SENINF_OUTMUX_TAG_DONE_IRQ_TRIG_5_MASK (0x1 << 29)
#define SENINF_OUTMUX_TAG_DONE_IRQ_TRIG_6_SHIFT 30
#define SENINF_OUTMUX_TAG_DONE_IRQ_TRIG_6_MASK (0x1 << 30)
#define SENINF_OUTMUX_TAG_DONE_IRQ_TRIG_7_SHIFT 31
#define SENINF_OUTMUX_TAG_DONE_IRQ_TRIG_7_MASK (0x1 << 31)

#define SENINF_OUTMUX_RSV_0 0x0064
#define SENINF_OUTMUX_RSV_0_SHIFT 0
#define SENINF_OUTMUX_RSV_0_MASK (0xffffffff << 0)

#define SENINF_OUTMUX_RSV_1 0x0068
#define SENINF_OUTMUX_RSV_1_SHIFT 0
#define SENINF_OUTMUX_RSV_1_MASK (0xffffffff << 0)

#define SENINF_OUTMUX_RSV_DB 0x006c
#define SENINF_OUTMUX_RSV_DB_SHIFT 0
#define SENINF_OUTMUX_RSV_DB_MASK (0xffffffff << 0)

#define SENINF_OUTMUX_CROP_EN 0x0074
#define SENINF_OUTMUX_CROP_EN_0_SHIFT 0
#define SENINF_OUTMUX_CROP_EN_0_MASK (0x1 << 0)
#define SENINF_OUTMUX_CROP_EN_1_SHIFT 1
#define SENINF_OUTMUX_CROP_EN_1_MASK (0x1 << 1)
#define SENINF_OUTMUX_CROP_EN_2_SHIFT 2
#define SENINF_OUTMUX_CROP_EN_2_MASK (0x1 << 2)
#define SENINF_OUTMUX_CROP_EN_3_SHIFT 3
#define SENINF_OUTMUX_CROP_EN_3_MASK (0x1 << 3)
#define SENINF_OUTMUX_CROP_EN_4_SHIFT 4
#define SENINF_OUTMUX_CROP_EN_4_MASK (0x1 << 4)
#define SENINF_OUTMUX_CROP_EN_5_SHIFT 5
#define SENINF_OUTMUX_CROP_EN_5_MASK (0x1 << 5)
#define SENINF_OUTMUX_CROP_EN_6_SHIFT 6
#define SENINF_OUTMUX_CROP_EN_6_MASK (0x1 << 6)
#define SENINF_OUTMUX_CROP_EN_7_SHIFT 7
#define SENINF_OUTMUX_CROP_EN_7_MASK (0x1 << 7)

#define SENINF_OUTMUX_TAG_DISPATCH 0x0078
#define SENINF_OUTMUX_TAG_DISPATCH_0_SHIFT 0
#define SENINF_OUTMUX_TAG_DISPATCH_0_MASK (0x1 << 0)
#define SENINF_OUTMUX_TAG_DISPATCH_1_SHIFT 1
#define SENINF_OUTMUX_TAG_DISPATCH_1_MASK (0x1 << 1)
#define SENINF_OUTMUX_TAG_DISPATCH_2_SHIFT 2
#define SENINF_OUTMUX_TAG_DISPATCH_2_MASK (0x1 << 2)
#define SENINF_OUTMUX_TAG_DISPATCH_3_SHIFT 3
#define SENINF_OUTMUX_TAG_DISPATCH_3_MASK (0x1 << 3)
#define SENINF_OUTMUX_TAG_DISPATCH_4_SHIFT 4
#define SENINF_OUTMUX_TAG_DISPATCH_4_MASK (0x1 << 4)
#define SENINF_OUTMUX_TAG_DISPATCH_5_SHIFT 5
#define SENINF_OUTMUX_TAG_DISPATCH_5_MASK (0x1 << 5)
#define SENINF_OUTMUX_TAG_DISPATCH_6_SHIFT 6
#define SENINF_OUTMUX_TAG_DISPATCH_6_MASK (0x1 << 6)
#define SENINF_OUTMUX_TAG_DISPATCH_7_SHIFT 7
#define SENINF_OUTMUX_TAG_DISPATCH_7_MASK (0x1 << 7)

#define SENINF_OUTMUX_TAG_VCDT_FILT_0 0x0080
#define SENINF_OUTMUX_FILT_EN_0_SHIFT 0
#define SENINF_OUTMUX_FILT_EN_0_MASK (0x1 << 0)
#define SENINF_OUTMUX_FILT_DT_IGNORE_0_SHIFT 4
#define SENINF_OUTMUX_FILT_DT_IGNORE_0_MASK (0x1 << 4)
#define SENINF_OUTMUX_FILT_VC_0_SHIFT 8
#define SENINF_OUTMUX_FILT_VC_0_MASK (0x1f << 8)
#define SENINF_OUTMUX_FILT_DT_0_SHIFT 16
#define SENINF_OUTMUX_FILT_DT_0_MASK (0x3f << 16)

#define SENINF_OUTMUX_TAG_SIZE_0 0x0084
#define SENINF_OUTMUX_HSIZE_0_SHIFT 0
#define SENINF_OUTMUX_HSIZE_0_MASK (0xffff << 0)
#define SENINF_OUTMUX_VSIZE_0_SHIFT 16
#define SENINF_OUTMUX_VSIZE_0_MASK (0xffff << 16)

#define SENINF_OUTMUX_TAG_CROP_PIX_0 0x0088
#define SENINF_OUTMUX_CROP_PIX_S_0_SHIFT 0
#define SENINF_OUTMUX_CROP_PIX_S_0_MASK (0xffff << 0)
#define SENINF_OUTMUX_CROP_PIX_E_0_SHIFT 16
#define SENINF_OUTMUX_CROP_PIX_E_0_MASK (0xffff << 16)

#define SENINF_OUTMUX_TAG_CROP_LIN_0 0x008c
#define SENINF_OUTMUX_CROP_LIN_S_0_SHIFT 0
#define SENINF_OUTMUX_CROP_LIN_S_0_MASK (0xffff << 0)
#define SENINF_OUTMUX_CROP_LIN_E_0_SHIFT 16
#define SENINF_OUTMUX_CROP_LIN_E_0_MASK (0xffff << 16)

#define SENINF_OUTMUX_TAG_DBG_PORT_0 0x0090
#define SENINF_OUTMUX_TAG_DBG_PORT_0_SHIFT 0
#define SENINF_OUTMUX_TAG_DBG_PORT_0_MASK (0xffffffff << 0)

#define SENINF_OUTMUX_TAG_RSV_0 0x0094
#define SENINF_OUTMUX_TAG_RSV_0_SHIFT 0
#define SENINF_OUTMUX_TAG_RSV_0_MASK (0xffffffff << 0)

#define SENINF_OUTMUX_TAG_CRC_PORT_0 0x0098
#define SENINF_OUTMUX_TAG_CRC_PORT_0_SHIFT 0
#define SENINF_OUTMUX_TAG_CRC_PORT_0_MASK (0xffff << 0)

#define SENINF_OUTMUX_TAG_VCDT_FILT_1 0x009c
#define SENINF_OUTMUX_FILT_EN_1_SHIFT 0
#define SENINF_OUTMUX_FILT_EN_1_MASK (0x1 << 0)
#define SENINF_OUTMUX_FILT_DT_IGNORE_1_SHIFT 4
#define SENINF_OUTMUX_FILT_DT_IGNORE_1_MASK (0x1 << 4)
#define SENINF_OUTMUX_FILT_VC_1_SHIFT 8
#define SENINF_OUTMUX_FILT_VC_1_MASK (0x1f << 8)
#define SENINF_OUTMUX_FILT_DT_1_SHIFT 16
#define SENINF_OUTMUX_FILT_DT_1_MASK (0x3f << 16)

#define SENINF_OUTMUX_TAG_SIZE_1 0x00a0
#define SENINF_OUTMUX_HSIZE_1_SHIFT 0
#define SENINF_OUTMUX_HSIZE_1_MASK (0xffff << 0)
#define SENINF_OUTMUX_VSIZE_1_SHIFT 16
#define SENINF_OUTMUX_VSIZE_1_MASK (0xffff << 16)

#define SENINF_OUTMUX_TAG_CROP_PIX_1 0x00a4
#define SENINF_OUTMUX_CROP_PIX_S_1_SHIFT 0
#define SENINF_OUTMUX_CROP_PIX_S_1_MASK (0xffff << 0)
#define SENINF_OUTMUX_CROP_PIX_E_1_SHIFT 16
#define SENINF_OUTMUX_CROP_PIX_E_1_MASK (0xffff << 16)

#define SENINF_OUTMUX_TAG_CROP_LIN_1 0x00a8
#define SENINF_OUTMUX_CROP_LIN_S_1_SHIFT 0
#define SENINF_OUTMUX_CROP_LIN_S_1_MASK (0xffff << 0)
#define SENINF_OUTMUX_CROP_LIN_E_1_SHIFT 16
#define SENINF_OUTMUX_CROP_LIN_E_1_MASK (0xffff << 16)

#define SENINF_OUTMUX_TAG_DBG_PORT_1 0x00ac
#define SENINF_OUTMUX_TAG_DBG_PORT_1_SHIFT 0
#define SENINF_OUTMUX_TAG_DBG_PORT_1_MASK (0xffffffff << 0)

#define SENINF_OUTMUX_TAG_RSV_1 0x00b0
#define SENINF_OUTMUX_TAG_RSV_1_SHIFT 0
#define SENINF_OUTMUX_TAG_RSV_1_MASK (0xffffffff << 0)

#define SENINF_OUTMUX_TAG_CRC_PORT_1 0x00b4
#define SENINF_OUTMUX_TAG_CRC_PORT_1_SHIFT 0
#define SENINF_OUTMUX_TAG_CRC_PORT_1_MASK (0xffff << 0)

#define SENINF_OUTMUX_TAG_VCDT_FILT_2 0x00b8
#define SENINF_OUTMUX_FILT_EN_2_SHIFT 0
#define SENINF_OUTMUX_FILT_EN_2_MASK (0x1 << 0)
#define SENINF_OUTMUX_FILT_DT_IGNORE_2_SHIFT 4
#define SENINF_OUTMUX_FILT_DT_IGNORE_2_MASK (0x1 << 4)
#define SENINF_OUTMUX_FILT_VC_2_SHIFT 8
#define SENINF_OUTMUX_FILT_VC_2_MASK (0x1f << 8)
#define SENINF_OUTMUX_FILT_DT_2_SHIFT 16
#define SENINF_OUTMUX_FILT_DT_2_MASK (0x3f << 16)

#define SENINF_OUTMUX_TAG_SIZE_2 0x00bc
#define SENINF_OUTMUX_HSIZE_2_SHIFT 0
#define SENINF_OUTMUX_HSIZE_2_MASK (0xffff << 0)
#define SENINF_OUTMUX_VSIZE_2_SHIFT 16
#define SENINF_OUTMUX_VSIZE_2_MASK (0xffff << 16)

#define SENINF_OUTMUX_TAG_CROP_PIX_2 0x00c0
#define SENINF_OUTMUX_CROP_PIX_S_2_SHIFT 0
#define SENINF_OUTMUX_CROP_PIX_S_2_MASK (0xffff << 0)
#define SENINF_OUTMUX_CROP_PIX_E_2_SHIFT 16
#define SENINF_OUTMUX_CROP_PIX_E_2_MASK (0xffff << 16)

#define SENINF_OUTMUX_TAG_CROP_LIN_2 0x00c4
#define SENINF_OUTMUX_CROP_LIN_S_2_SHIFT 0
#define SENINF_OUTMUX_CROP_LIN_S_2_MASK (0xffff << 0)
#define SENINF_OUTMUX_CROP_LIN_E_2_SHIFT 16
#define SENINF_OUTMUX_CROP_LIN_E_2_MASK (0xffff << 16)

#define SENINF_OUTMUX_TAG_DBG_PORT_2 0x00c8
#define SENINF_OUTMUX_TAG_DBG_PORT_2_SHIFT 0
#define SENINF_OUTMUX_TAG_DBG_PORT_2_MASK (0xffffffff << 0)

#define SENINF_OUTMUX_TAG_RSV_2 0x00cc
#define SENINF_OUTMUX_TAG_RSV_2_SHIFT 0
#define SENINF_OUTMUX_TAG_RSV_2_MASK (0xffffffff << 0)

#define SENINF_OUTMUX_TAG_CRC_PORT_2 0x00d0
#define SENINF_OUTMUX_TAG_CRC_PORT_2_SHIFT 0
#define SENINF_OUTMUX_TAG_CRC_PORT_2_MASK (0xffff << 0)

#define SENINF_OUTMUX_TAG_VCDT_FILT_3 0x00d4
#define SENINF_OUTMUX_FILT_EN_3_SHIFT 0
#define SENINF_OUTMUX_FILT_EN_3_MASK (0x1 << 0)
#define SENINF_OUTMUX_FILT_DT_IGNORE_3_SHIFT 4
#define SENINF_OUTMUX_FILT_DT_IGNORE_3_MASK (0x1 << 4)
#define SENINF_OUTMUX_FILT_VC_3_SHIFT 8
#define SENINF_OUTMUX_FILT_VC_3_MASK (0x1f << 8)
#define SENINF_OUTMUX_FILT_DT_3_SHIFT 16
#define SENINF_OUTMUX_FILT_DT_3_MASK (0x3f << 16)

#define SENINF_OUTMUX_TAG_SIZE_3 0x00d8
#define SENINF_OUTMUX_HSIZE_3_SHIFT 0
#define SENINF_OUTMUX_HSIZE_3_MASK (0xffff << 0)
#define SENINF_OUTMUX_VSIZE_3_SHIFT 16
#define SENINF_OUTMUX_VSIZE_3_MASK (0xffff << 16)

#define SENINF_OUTMUX_TAG_CROP_PIX_3 0x00dc
#define SENINF_OUTMUX_CROP_PIX_S_3_SHIFT 0
#define SENINF_OUTMUX_CROP_PIX_S_3_MASK (0xffff << 0)
#define SENINF_OUTMUX_CROP_PIX_E_3_SHIFT 16
#define SENINF_OUTMUX_CROP_PIX_E_3_MASK (0xffff << 16)

#define SENINF_OUTMUX_TAG_CROP_LIN_3 0x00e0
#define SENINF_OUTMUX_CROP_LIN_S_3_SHIFT 0
#define SENINF_OUTMUX_CROP_LIN_S_3_MASK (0xffff << 0)
#define SENINF_OUTMUX_CROP_LIN_E_3_SHIFT 16
#define SENINF_OUTMUX_CROP_LIN_E_3_MASK (0xffff << 16)

#define SENINF_OUTMUX_TAG_DBG_PORT_3 0x00e4
#define SENINF_OUTMUX_TAG_DBG_PORT_3_SHIFT 0
#define SENINF_OUTMUX_TAG_DBG_PORT_3_MASK (0xffffffff << 0)

#define SENINF_OUTMUX_TAG_RSV_3 0x00e8
#define SENINF_OUTMUX_TAG_RSV_3_SHIFT 0
#define SENINF_OUTMUX_TAG_RSV_3_MASK (0xffffffff << 0)

#define SENINF_OUTMUX_TAG_CRC_PORT_3 0x00ec
#define SENINF_OUTMUX_TAG_CRC_PORT_3_SHIFT 0
#define SENINF_OUTMUX_TAG_CRC_PORT_3_MASK (0xffff << 0)

#define SENINF_OUTMUX_TAG_VCDT_FILT_4 0x00f0
#define SENINF_OUTMUX_FILT_EN_4_SHIFT 0
#define SENINF_OUTMUX_FILT_EN_4_MASK (0x1 << 0)
#define SENINF_OUTMUX_FILT_DT_IGNORE_4_SHIFT 4
#define SENINF_OUTMUX_FILT_DT_IGNORE_4_MASK (0x1 << 4)
#define SENINF_OUTMUX_FILT_VC_4_SHIFT 8
#define SENINF_OUTMUX_FILT_VC_4_MASK (0x1f << 8)
#define SENINF_OUTMUX_FILT_DT_4_SHIFT 16
#define SENINF_OUTMUX_FILT_DT_4_MASK (0x3f << 16)

#define SENINF_OUTMUX_TAG_SIZE_4 0x00f4
#define SENINF_OUTMUX_HSIZE_4_SHIFT 0
#define SENINF_OUTMUX_HSIZE_4_MASK (0xffff << 0)
#define SENINF_OUTMUX_VSIZE_4_SHIFT 16
#define SENINF_OUTMUX_VSIZE_4_MASK (0xffff << 16)

#define SENINF_OUTMUX_TAG_CROP_PIX_4 0x00f8
#define SENINF_OUTMUX_CROP_PIX_S_4_SHIFT 0
#define SENINF_OUTMUX_CROP_PIX_S_4_MASK (0xffff << 0)
#define SENINF_OUTMUX_CROP_PIX_E_4_SHIFT 16
#define SENINF_OUTMUX_CROP_PIX_E_4_MASK (0xffff << 16)

#define SENINF_OUTMUX_TAG_CROP_LIN_4 0x00fc
#define SENINF_OUTMUX_CROP_LIN_S_4_SHIFT 0
#define SENINF_OUTMUX_CROP_LIN_S_4_MASK (0xffff << 0)
#define SENINF_OUTMUX_CROP_LIN_E_4_SHIFT 16
#define SENINF_OUTMUX_CROP_LIN_E_4_MASK (0xffff << 16)

#define SENINF_OUTMUX_TAG_DBG_PORT_4 0x0100
#define SENINF_OUTMUX_TAG_DBG_PORT_4_SHIFT 0
#define SENINF_OUTMUX_TAG_DBG_PORT_4_MASK (0xffffffff << 0)

#define SENINF_OUTMUX_TAG_RSV_4 0x0104
#define SENINF_OUTMUX_TAG_RSV_4_SHIFT 0
#define SENINF_OUTMUX_TAG_RSV_4_MASK (0xffffffff << 0)

#define SENINF_OUTMUX_TAG_CRC_PORT_4 0x0108
#define SENINF_OUTMUX_TAG_CRC_PORT_4_SHIFT 0
#define SENINF_OUTMUX_TAG_CRC_PORT_4_MASK (0xffff << 0)

#define SENINF_OUTMUX_TAG_VCDT_FILT_5 0x010c
#define SENINF_OUTMUX_FILT_EN_5_SHIFT 0
#define SENINF_OUTMUX_FILT_EN_5_MASK (0x1 << 0)
#define SENINF_OUTMUX_FILT_DT_IGNORE_5_SHIFT 4
#define SENINF_OUTMUX_FILT_DT_IGNORE_5_MASK (0x1 << 4)
#define SENINF_OUTMUX_FILT_VC_5_SHIFT 8
#define SENINF_OUTMUX_FILT_VC_5_MASK (0x1f << 8)
#define SENINF_OUTMUX_FILT_DT_5_SHIFT 16
#define SENINF_OUTMUX_FILT_DT_5_MASK (0x3f << 16)

#define SENINF_OUTMUX_TAG_SIZE_5 0x0110
#define SENINF_OUTMUX_HSIZE_5_SHIFT 0
#define SENINF_OUTMUX_HSIZE_5_MASK (0xffff << 0)
#define SENINF_OUTMUX_VSIZE_5_SHIFT 16
#define SENINF_OUTMUX_VSIZE_5_MASK (0xffff << 16)

#define SENINF_OUTMUX_TAG_CROP_PIX_5 0x0114
#define SENINF_OUTMUX_CROP_PIX_S_5_SHIFT 0
#define SENINF_OUTMUX_CROP_PIX_S_5_MASK (0xffff << 0)
#define SENINF_OUTMUX_CROP_PIX_E_5_SHIFT 16
#define SENINF_OUTMUX_CROP_PIX_E_5_MASK (0xffff << 16)

#define SENINF_OUTMUX_TAG_CROP_LIN_5 0x0118
#define SENINF_OUTMUX_CROP_LIN_S_5_SHIFT 0
#define SENINF_OUTMUX_CROP_LIN_S_5_MASK (0xffff << 0)
#define SENINF_OUTMUX_CROP_LIN_E_5_SHIFT 16
#define SENINF_OUTMUX_CROP_LIN_E_5_MASK (0xffff << 16)

#define SENINF_OUTMUX_TAG_DBG_PORT_5 0x011c
#define SENINF_OUTMUX_TAG_DBG_PORT_5_SHIFT 0
#define SENINF_OUTMUX_TAG_DBG_PORT_5_MASK (0xffffffff << 0)

#define SENINF_OUTMUX_TAG_RSV_5 0x0120
#define SENINF_OUTMUX_TAG_RSV_5_SHIFT 0
#define SENINF_OUTMUX_TAG_RSV_5_MASK (0xffffffff << 0)

#define SENINF_OUTMUX_TAG_CRC_PORT_5 0x0124
#define SENINF_OUTMUX_TAG_CRC_PORT_5_SHIFT 0
#define SENINF_OUTMUX_TAG_CRC_PORT_5_MASK (0xffff << 0)

#define SENINF_OUTMUX_TAG_VCDT_FILT_6 0x0128
#define SENINF_OUTMUX_FILT_EN_6_SHIFT 0
#define SENINF_OUTMUX_FILT_EN_6_MASK (0x1 << 0)
#define SENINF_OUTMUX_FILT_DT_IGNORE_6_SHIFT 4
#define SENINF_OUTMUX_FILT_DT_IGNORE_6_MASK (0x1 << 4)
#define SENINF_OUTMUX_FILT_VC_6_SHIFT 8
#define SENINF_OUTMUX_FILT_VC_6_MASK (0x1f << 8)
#define SENINF_OUTMUX_FILT_DT_6_SHIFT 16
#define SENINF_OUTMUX_FILT_DT_6_MASK (0x3f << 16)

#define SENINF_OUTMUX_TAG_SIZE_6 0x012c
#define SENINF_OUTMUX_HSIZE_6_SHIFT 0
#define SENINF_OUTMUX_HSIZE_6_MASK (0xffff << 0)
#define SENINF_OUTMUX_VSIZE_6_SHIFT 16
#define SENINF_OUTMUX_VSIZE_6_MASK (0xffff << 16)

#define SENINF_OUTMUX_TAG_CROP_PIX_6 0x0130
#define SENINF_OUTMUX_CROP_PIX_S_6_SHIFT 0
#define SENINF_OUTMUX_CROP_PIX_S_6_MASK (0xffff << 0)
#define SENINF_OUTMUX_CROP_PIX_E_6_SHIFT 16
#define SENINF_OUTMUX_CROP_PIX_E_6_MASK (0xffff << 16)

#define SENINF_OUTMUX_TAG_CROP_LIN_6 0x0134
#define SENINF_OUTMUX_CROP_LIN_S_6_SHIFT 0
#define SENINF_OUTMUX_CROP_LIN_S_6_MASK (0xffff << 0)
#define SENINF_OUTMUX_CROP_LIN_E_6_SHIFT 16
#define SENINF_OUTMUX_CROP_LIN_E_6_MASK (0xffff << 16)

#define SENINF_OUTMUX_TAG_DBG_PORT_6 0x0138
#define SENINF_OUTMUX_TAG_DBG_PORT_6_SHIFT 0
#define SENINF_OUTMUX_TAG_DBG_PORT_6_MASK (0xffffffff << 0)

#define SENINF_OUTMUX_TAG_RSV_6 0x013c
#define SENINF_OUTMUX_TAG_RSV_6_SHIFT 0
#define SENINF_OUTMUX_TAG_RSV_6_MASK (0xffffffff << 0)

#define SENINF_OUTMUX_TAG_CRC_PORT_6 0x0140
#define SENINF_OUTMUX_TAG_CRC_PORT_6_SHIFT 0
#define SENINF_OUTMUX_TAG_CRC_PORT_6_MASK (0xffff << 0)

#define SENINF_OUTMUX_TAG_VCDT_FILT_7 0x0144
#define SENINF_OUTMUX_FILT_EN_7_SHIFT 0
#define SENINF_OUTMUX_FILT_EN_7_MASK (0x1 << 0)
#define SENINF_OUTMUX_FILT_DT_IGNORE_7_SHIFT 4
#define SENINF_OUTMUX_FILT_DT_IGNORE_7_MASK (0x1 << 4)
#define SENINF_OUTMUX_FILT_VC_7_SHIFT 8
#define SENINF_OUTMUX_FILT_VC_7_MASK (0x1f << 8)
#define SENINF_OUTMUX_FILT_DT_7_SHIFT 16
#define SENINF_OUTMUX_FILT_DT_7_MASK (0x3f << 16)

#define SENINF_OUTMUX_TAG_SIZE_7 0x0148
#define SENINF_OUTMUX_HSIZE_7_SHIFT 0
#define SENINF_OUTMUX_HSIZE_7_MASK (0xffff << 0)
#define SENINF_OUTMUX_VSIZE_7_SHIFT 16
#define SENINF_OUTMUX_VSIZE_7_MASK (0xffff << 16)

#define SENINF_OUTMUX_TAG_CROP_PIX_7 0x014c
#define SENINF_OUTMUX_CROP_PIX_S_7_SHIFT 0
#define SENINF_OUTMUX_CROP_PIX_S_7_MASK (0xffff << 0)
#define SENINF_OUTMUX_CROP_PIX_E_7_SHIFT 16
#define SENINF_OUTMUX_CROP_PIX_E_7_MASK (0xffff << 16)

#define SENINF_OUTMUX_TAG_CROP_LIN_7 0x0150
#define SENINF_OUTMUX_CROP_LIN_S_7_SHIFT 0
#define SENINF_OUTMUX_CROP_LIN_S_7_MASK (0xffff << 0)
#define SENINF_OUTMUX_CROP_LIN_E_7_SHIFT 16
#define SENINF_OUTMUX_CROP_LIN_E_7_MASK (0xffff << 16)

#define SENINF_OUTMUX_TAG_DBG_PORT_7 0x0154
#define SENINF_OUTMUX_TAG_DBG_PORT_7_SHIFT 0
#define SENINF_OUTMUX_TAG_DBG_PORT_7_MASK (0xffffffff << 0)

#define SENINF_OUTMUX_TAG_RSV_7 0x0158
#define SENINF_OUTMUX_TAG_RSV_7_SHIFT 0
#define SENINF_OUTMUX_TAG_RSV_7_MASK (0xffffffff << 0)

#define SENINF_OUTMUX_TAG_CRC_PORT_7 0x015c
#define SENINF_OUTMUX_TAG_CRC_PORT_7_SHIFT 0
#define SENINF_OUTMUX_TAG_CRC_PORT_7_MASK (0xffff << 0)

#endif
