/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */

#ifndef __SENINF_TOP_E1A_C_HEADER_H__
#define __SENINF_TOP_E1A_C_HEADER_H__

#define SENINF_TOP_ASYNC_SW_RST 0x0000
#define SENINF_TOP_ASYNC_SW_RST_SHIFT 0
#define SENINF_TOP_ASYNC_SW_RST_MASK (0x3f << 0)

#define SENINF_TOP_OUTMUX_SW_RST 0x0004
#define SENINF_TOP_OUTMUX_SW_RST_SHIFT 0
#define SENINF_TOP_OUTMUX_SW_RST_MASK (0x7fffff << 0)

#define SENINF_TOP_ASYNC_CG_EN 0x0008
#define SENINF_TOP_ASYNC_CG_EN_SHIFT 0
#define SENINF_TOP_ASYNC_CG_EN_MASK (0x3f << 0)

#define SENINF_TOP_OUTMUX_CG_EN 0x000c
#define SENINF_TOP_OUTMUX_CG_EN_SHIFT 0
#define SENINF_TOP_OUTMUX_CG_EN_MASK (0x7fffff << 0)

#define SENINF_TOP_CTRL 0x0018
#define SENINF_TOP_INT_WCLR_EN_SHIFT 0
#define SENINF_TOP_INT_WCLR_EN_MASK (0x1 << 0)
#define SENINF_TOP_VERIF_EN_SHIFT 16
#define SENINF_TOP_VERIF_EN_MASK (0x1 << 16)
#define SENINF_TOP_SW_CFG_LEVEL_SHIFT 24
#define SENINF_TOP_SW_CFG_LEVEL_MASK (0x1 << 24)

#define SENINF_TOP_ASYNC_OVERRUN_IRQ_EN 0x0020
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_EN_0_SHIFT 0
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_EN_0_MASK (0x1 << 0)
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_EN_1_SHIFT 1
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_EN_1_MASK (0x1 << 1)
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_EN_2_SHIFT 2
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_EN_2_MASK (0x1 << 2)
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_EN_3_SHIFT 3
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_EN_3_MASK (0x1 << 3)
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_EN_4_SHIFT 4
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_EN_4_MASK (0x1 << 4)
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_EN_5_SHIFT 5
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_EN_5_MASK (0x1 << 5)

#define SENINF_TOP_ASYNC_OVERRUN_IRQ_STATUS 0x0024
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_STATUS_0_SHIFT 0
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_STATUS_0_MASK (0x1 << 0)
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_STATUS_1_SHIFT 1
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_STATUS_1_MASK (0x1 << 1)
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_STATUS_2_SHIFT 2
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_STATUS_2_MASK (0x1 << 2)
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_STATUS_3_SHIFT 3
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_STATUS_3_MASK (0x1 << 3)
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_STATUS_4_SHIFT 4
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_STATUS_4_MASK (0x1 << 4)
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_STATUS_5_SHIFT 5
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_STATUS_5_MASK (0x1 << 5)

#define SENINF_TOP_ASYNC_OVERRUN_IRQ_CCU_EN 0x0060
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_CCU_EN_0_SHIFT 0
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_CCU_EN_0_MASK (0x1 << 0)
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_CCU_EN_1_SHIFT 1
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_CCU_EN_1_MASK (0x1 << 1)
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_CCU_EN_2_SHIFT 2
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_CCU_EN_2_MASK (0x1 << 2)
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_CCU_EN_3_SHIFT 3
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_CCU_EN_3_MASK (0x1 << 3)
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_CCU_EN_4_SHIFT 4
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_CCU_EN_4_MASK (0x1 << 4)
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_CCU_EN_5_SHIFT 5
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_CCU_EN_5_MASK (0x1 << 5)

#define SENINF_TOP_ASYNC_OVERRUN_IRQ_CCU_STATUS 0x0064
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_CCU_STATUS_0_SHIFT 0
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_CCU_STATUS_0_MASK (0x1 << 0)
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_CCU_STATUS_1_SHIFT 1
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_CCU_STATUS_1_MASK (0x1 << 1)
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_CCU_STATUS_2_SHIFT 2
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_CCU_STATUS_2_MASK (0x1 << 2)
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_CCU_STATUS_3_SHIFT 3
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_CCU_STATUS_3_MASK (0x1 << 3)
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_CCU_STATUS_4_SHIFT 4
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_CCU_STATUS_4_MASK (0x1 << 4)
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_CCU_STATUS_5_SHIFT 5
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_CCU_STATUS_5_MASK (0x1 << 5)

#define SENINF_TOP_ASYNC_OVERRUN_IRQ_TRIG 0x00a0
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_TRIG_0_SHIFT 0
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_TRIG_0_MASK (0x1 << 0)
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_TRIG_1_SHIFT 1
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_TRIG_1_MASK (0x1 << 1)
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_TRIG_2_SHIFT 2
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_TRIG_2_MASK (0x1 << 2)
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_TRIG_3_SHIFT 3
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_TRIG_3_MASK (0x1 << 3)
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_TRIG_4_SHIFT 4
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_TRIG_4_MASK (0x1 << 4)
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_TRIG_5_SHIFT 5
#define SENINF_TOP_ASYNC_OVERRUN_IRQ_TRIG_5_MASK (0x1 << 5)

#define SENINF_TOP_DEVICE_GRP_SEL_0 0x00c0
#define SENINF_TOP_DEVICE_GRP_SEL_0_SHIFT 0
#define SENINF_TOP_DEVICE_GRP_SEL_0_MASK (0x7fffff << 0)

#define SENINF_TOP_DEVICE_GRP_SEL_1 0x00c4
#define SENINF_TOP_DEVICE_GRP_SEL_1_SHIFT 0
#define SENINF_TOP_DEVICE_GRP_SEL_1_MASK (0x7fffff << 0)

#define SENINF_TOP_DEVICE_GRP_SEL_2 0x00c8
#define SENINF_TOP_DEVICE_GRP_SEL_2_SHIFT 0
#define SENINF_TOP_DEVICE_GRP_SEL_2_MASK (0x7fffff << 0)

#define SENINF_TOP_DEVICE_GRP_SEL_3 0x00cc
#define SENINF_TOP_DEVICE_GRP_SEL_3_SHIFT 0
#define SENINF_TOP_DEVICE_GRP_SEL_3_MASK (0x7fffff << 0)

#define SENINF_TOP_SW_CFG_DONE 0x0100
#define SENINF_TOP_SW_CFG_DONE_SHIFT 0
#define SENINF_TOP_SW_CFG_DONE_MASK (0x7fffff << 0)

#define SENINF_TOP_LOCK 0x010c
#define SENINF_TOP_LOCK_0_SHIFT 0
#define SENINF_TOP_LOCK_0_MASK (0x1 << 0)
#define SENINF_TOP_LOCK_1_SHIFT 1
#define SENINF_TOP_LOCK_1_MASK (0x1 << 1)
#define SENINF_TOP_LOCK_2_SHIFT 2
#define SENINF_TOP_LOCK_2_MASK (0x1 << 2)
#define SENINF_TOP_LOCK_3_SHIFT 3
#define SENINF_TOP_LOCK_3_MASK (0x1 << 3)
#define SENINF_TOP_LOCK_4_SHIFT 4
#define SENINF_TOP_LOCK_4_MASK (0x1 << 4)
#define SENINF_TOP_LOCK_5_SHIFT 5
#define SENINF_TOP_LOCK_5_MASK (0x1 << 5)
#define SENINF_TOP_LOCK_6_SHIFT 6
#define SENINF_TOP_LOCK_6_MASK (0x1 << 6)
#define SENINF_TOP_LOCK_7_SHIFT 7
#define SENINF_TOP_LOCK_7_MASK (0x1 << 7)
#define SENINF_TOP_LOCK_8_SHIFT 8
#define SENINF_TOP_LOCK_8_MASK (0x1 << 8)
#define SENINF_TOP_LOCK_9_SHIFT 9
#define SENINF_TOP_LOCK_9_MASK (0x1 << 9)
#define SENINF_TOP_LOCK_10_SHIFT 10
#define SENINF_TOP_LOCK_10_MASK (0x1 << 10)
#define SENINF_TOP_LOCK_11_SHIFT 11
#define SENINF_TOP_LOCK_11_MASK (0x1 << 11)
#define SENINF_TOP_LOCK_12_SHIFT 12
#define SENINF_TOP_LOCK_12_MASK (0x1 << 12)
#define SENINF_TOP_LOCK_13_SHIFT 13
#define SENINF_TOP_LOCK_13_MASK (0x1 << 13)
#define SENINF_TOP_LOCK_14_SHIFT 14
#define SENINF_TOP_LOCK_14_MASK (0x1 << 14)
#define SENINF_TOP_LOCK_15_SHIFT 15
#define SENINF_TOP_LOCK_15_MASK (0x1 << 15)
#define SENINF_TOP_LOCK_16_SHIFT 16
#define SENINF_TOP_LOCK_16_MASK (0x1 << 16)
#define SENINF_TOP_LOCK_17_SHIFT 17
#define SENINF_TOP_LOCK_17_MASK (0x1 << 17)
#define SENINF_TOP_LOCK_18_SHIFT 18
#define SENINF_TOP_LOCK_18_MASK (0x1 << 18)
#define SENINF_TOP_LOCK_19_SHIFT 19
#define SENINF_TOP_LOCK_19_MASK (0x1 << 19)
#define SENINF_TOP_LOCK_20_SHIFT 20
#define SENINF_TOP_LOCK_20_MASK (0x1 << 20)
#define SENINF_TOP_LOCK_21_SHIFT 21
#define SENINF_TOP_LOCK_21_MASK (0x1 << 21)
#define SENINF_TOP_LOCK_22_SHIFT 22
#define SENINF_TOP_LOCK_22_MASK (0x1 << 22)

#define SENINF_TOP_EXCLUDE_EN 0x0110
#define SENINF_TOP_EXCLUDE_EN_SHIFT 0
#define SENINF_TOP_EXCLUDE_EN_MASK (0x7fffff << 0)

#define SENINF_TOP_SRC_EXCLUDE 0x0114
#define SENINF_TOP_SRC_SEN_EXCLUDE_0_SHIFT 0
#define SENINF_TOP_SRC_SEN_EXCLUDE_0_MASK (0x3 << 0)
#define SENINF_TOP_SRC_MIPI_EXCLUDE_0_SHIFT 4
#define SENINF_TOP_SRC_MIPI_EXCLUDE_0_MASK (0x7 << 4)
#define SENINF_TOP_SRC_SEN_EXCLUDE_1_SHIFT 8
#define SENINF_TOP_SRC_SEN_EXCLUDE_1_MASK (0x3 << 8)
#define SENINF_TOP_SRC_MIPI_EXCLUDE_1_SHIFT 12
#define SENINF_TOP_SRC_MIPI_EXCLUDE_1_MASK (0x7 << 12)
#define SENINF_TOP_SRC_RSV_SHIFT 16
#define SENINF_TOP_SRC_RSV_MASK (0xff << 16)

#define SENINF_TOP_RSV_0 0x0130
#define SENINF_TOP_RSV_0_SHIFT 0
#define SENINF_TOP_RSV_0_MASK (0xffffffff << 0)

#define SENINF_TOP_RSV_1 0x0134
#define SENINF_TOP_RSV_1_SHIFT 0
#define SENINF_TOP_RSV_1_MASK (0xffffffff << 0)

#endif
