/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */

#ifndef __MIPI_RX_ANA_CDPHY_CSI0A_H__
#define __MIPI_RX_ANA_CDPHY_CSI0A_H__

#define CDPHY_RX_ANA_0 0x0000
#define RG_CSI0_BG_CORE_EN_SHIFT 0
#define RG_CSI0_BG_CORE_EN_MASK (0x1 << 0)
#define RG_CSI0_BG_LPF_EN_SHIFT 1
#define RG_CSI0_BG_LPF_EN_MASK (0x1 << 1)
#define RG_CSI0_EQ_PROTECT_EN_SHIFT 4
#define RG_CSI0_EQ_PROTECT_EN_MASK (0x1 << 4)
#define RG_CSI0_BYTE_CK_RSTB_SEL_SHIFT 5
#define RG_CSI0_BYTE_CK_RSTB_SEL_MASK (0x1 << 5)
#define RG_CSI0_CPHY_T0_HSMODE_EN_SHIFT 6
#define RG_CSI0_CPHY_T0_HSMODE_EN_MASK (0x1 << 6)
#define RG_CSI0_CPHY_T1_HSMODE_EN_SHIFT 7
#define RG_CSI0_CPHY_T1_HSMODE_EN_MASK (0x1 << 7)
#define RG_CSI0_DPHY_L0_CKSEL_SHIFT 8
#define RG_CSI0_DPHY_L0_CKSEL_MASK (0x1 << 8)
#define RG_CSI0_DPHY_L1_CKSEL_SHIFT 9
#define RG_CSI0_DPHY_L1_CKSEL_MASK (0x1 << 9)
#define RG_CSI0_DPHY_L2_CKSEL_SHIFT 10
#define RG_CSI0_DPHY_L2_CKSEL_MASK (0x1 << 10)
#define RG_CSI0_DPHY_L0_CKMODE_EN_SHIFT 12
#define RG_CSI0_DPHY_L0_CKMODE_EN_MASK (0x1 << 12)
#define RG_CSI0_DPHY_L1_CKMODE_EN_SHIFT 13
#define RG_CSI0_DPHY_L1_CKMODE_EN_MASK (0x1 << 13)
#define RG_CSI0_DPHY_L2_CKMODE_EN_SHIFT 14
#define RG_CSI0_DPHY_L2_CKMODE_EN_MASK (0x1 << 14)
#define RG_CSI0_CDPHY_L0_T0_BYTECK_INVERT_SHIFT 16
#define RG_CSI0_CDPHY_L0_T0_BYTECK_INVERT_MASK (0x1 << 16)
#define RG_CSI0_DPHY_L1_BYTECK_INVERT_SHIFT 17
#define RG_CSI0_DPHY_L1_BYTECK_INVERT_MASK (0x1 << 17)
#define RG_CSI0_CDPHY_L2_T1_BYTECK_INVERT_SHIFT 18
#define RG_CSI0_CDPHY_L2_T1_BYTECK_INVERT_MASK (0x1 << 18)
#define RG_CSI0_CPHY_EN_SHIFT 20
#define RG_CSI0_CPHY_EN_MASK (0x1 << 20)
#define RG_CSI0_CPHY_T0_CDR_FIRST_EDGE_EN_SHIFT 21
#define RG_CSI0_CPHY_T0_CDR_FIRST_EDGE_EN_MASK (0x1 << 21)
#define RG_CSI0_CPHY_T1_CDR_FIRST_EDGE_EN_SHIFT 22
#define RG_CSI0_CPHY_T1_CDR_FIRST_EDGE_EN_MASK (0x1 << 22)
#define RG_CSI0_CDPHY_L0_T0_FORCE_INIT_SHIFT 24
#define RG_CSI0_CDPHY_L0_T0_FORCE_INIT_MASK (0x1 << 24)
#define RG_CSI0_DPHY_L1_FORCE_INIT_SHIFT 25
#define RG_CSI0_DPHY_L1_FORCE_INIT_MASK (0x1 << 25)
#define RG_CSI0_CDPHY_L2_T1_FORCE_INIT_SHIFT 26
#define RG_CSI0_CDPHY_L2_T1_FORCE_INIT_MASK (0x1 << 26)
#define RG_CSI0_CDPHY_L0_T0_SYNC_INIT_CTRL_SHIFT 28
#define RG_CSI0_CDPHY_L0_T0_SYNC_INIT_CTRL_MASK (0x1 << 28)
#define RG_CSI0_DPHY_L1_SYNC_INIT_CTRL_SHIFT 29
#define RG_CSI0_DPHY_L1_SYNC_INIT_CTRL_MASK (0x1 << 29)
#define RG_CSI0_CDPHY_L2_T1_SYNC_INIT_CTRL_SHIFT 30
#define RG_CSI0_CDPHY_L2_T1_SYNC_INIT_CTRL_MASK (0x1 << 30)
#define RG_CSI0_FORCE_HSRT_EN_SHIFT 31
#define RG_CSI0_FORCE_HSRT_EN_MASK (0x1 << 31)

#define CDPHY_RX_ANA_1 0x0004
#define RG_CSI0_BG_LPRX_VTL_SEL_SHIFT 0
#define RG_CSI0_BG_LPRX_VTL_SEL_MASK (0x7 << 0)
#define RG_CSI0_BG_LPRX_VTH_SEL_SHIFT 4
#define RG_CSI0_BG_LPRX_VTH_SEL_MASK (0x7 << 4)
#define RG_CSI0_BG_VREF_SEL_SHIFT 8
#define RG_CSI0_BG_VREF_SEL_MASK (0xf << 8)
#define RG_CSI0_CDPHY_DELAYCAL_CK_SEL_SHIFT 12
#define RG_CSI0_CDPHY_DELAYCAL_CK_SEL_MASK (0x7 << 12)
#define RG_CSI0_CDPHY_EQ_DES_VREF_SEL_SHIFT 16
#define RG_CSI0_CDPHY_EQ_DES_VREF_SEL_MASK (0x7 << 16)
#define RG_CSI0_CDPHY_DELAY_VREF_SEL_SHIFT 20
#define RG_CSI0_CDPHY_DELAY_VREF_SEL_MASK (0x7 << 20)
#define RG_CSI0_DPHY_L0_DELAYCAL_EN_SHIFT 24
#define RG_CSI0_DPHY_L0_DELAYCAL_EN_MASK (0x1 << 24)
#define RG_CSI0_DPHY_L1_DELAYCAL_EN_SHIFT 25
#define RG_CSI0_DPHY_L1_DELAYCAL_EN_MASK (0x1 << 25)
#define RG_CSI0_DPHY_L2_DELAYCAL_EN_SHIFT 26
#define RG_CSI0_DPHY_L2_DELAYCAL_EN_MASK (0x1 << 26)
#define RG_CSI0_DPHY_L0_DELAYCAL_RSTB_SHIFT 28
#define RG_CSI0_DPHY_L0_DELAYCAL_RSTB_MASK (0x1 << 28)
#define RG_CSI0_DPHY_L1_DELAYCAL_RSTB_SHIFT 29
#define RG_CSI0_DPHY_L1_DELAYCAL_RSTB_MASK (0x1 << 29)
#define RG_CSI0_DPHY_L2_DELAYCAL_RSTB_SHIFT 30
#define RG_CSI0_DPHY_L2_DELAYCAL_RSTB_MASK (0x1 << 30)

#define CDPHY_RX_ANA_2 0x0008
#define RG_CSI0_L0P_T0A_HSRT_CODE_SHIFT 0
#define RG_CSI0_L0P_T0A_HSRT_CODE_MASK (0x1f << 0)
#define RG_CSI0_L0N_T0B_HSRT_CODE_SHIFT 8
#define RG_CSI0_L0N_T0B_HSRT_CODE_MASK (0x1f << 8)
#define RG_CSI0_CPHY_T0_CDR_SELF_CAL_EN_SHIFT 16
#define RG_CSI0_CPHY_T0_CDR_SELF_CAL_EN_MASK (0x1 << 16)
#define RG_CSI0_CPHY_T1_CDR_SELF_CAL_EN_SHIFT 17
#define RG_CSI0_CPHY_T1_CDR_SELF_CAL_EN_MASK (0x1 << 17)
#define RG_CSI0_CPHY_T0_DELAYCAL_EN_SHIFT 20
#define RG_CSI0_CPHY_T0_DELAYCAL_EN_MASK (0x1 << 20)
#define RG_CSI0_CPHY_T1_DELAYCAL_EN_SHIFT 21
#define RG_CSI0_CPHY_T1_DELAYCAL_EN_MASK (0x1 << 21)
#define RG_CSI0_CPHY_T0_DELAYCAL_RSTB_SHIFT 22
#define RG_CSI0_CPHY_T0_DELAYCAL_RSTB_MASK (0x1 << 22)
#define RG_CSI0_CPHY_T1_DELAYCAL_RSTB_SHIFT 23
#define RG_CSI0_CPHY_T1_DELAYCAL_RSTB_MASK (0x1 << 23)
#define RG_CSI0_BG_ALP_RX_VTL_SEL_SHIFT 24
#define RG_CSI0_BG_ALP_RX_VTL_SEL_MASK (0x7 << 24)
#define RG_CSI0_BG_ALP_RX_VTH_SEL_SHIFT 28
#define RG_CSI0_BG_ALP_RX_VTH_SEL_MASK (0x7 << 28)

#define CDPHY_RX_ANA_3 0x000c
#define RG_CSI0_L1P_T0C_HSRT_CODE_SHIFT 0
#define RG_CSI0_L1P_T0C_HSRT_CODE_MASK (0x1f << 0)
#define RG_CSI0_L1N_T1A_HSRT_CODE_SHIFT 8
#define RG_CSI0_L1N_T1A_HSRT_CODE_MASK (0x1f << 8)
#define RG_CSI0_OS_CAL_CNT_SEL_SHIFT 16
#define RG_CSI0_OS_CAL_CNT_SEL_MASK (0x3 << 16)
#define RG_CSI0_EQ_DES_VREF_SEL_SHIFT 20
#define RG_CSI0_EQ_DES_VREF_SEL_MASK (0x3f << 20)
#define RG_CSI0_CDPHY_16BIT_SEL_SHIFT 27
#define RG_CSI0_CDPHY_16BIT_SEL_MASK (0x1 << 27)
#define RG_CSI0_DPHY_L0_PN_SWAP_EN_SHIFT 28
#define RG_CSI0_DPHY_L0_PN_SWAP_EN_MASK (0x1 << 28)
#define RG_CSI0_DPHY_L1_PN_SWAP_EN_SHIFT 29
#define RG_CSI0_DPHY_L1_PN_SWAP_EN_MASK (0x1 << 29)
#define RG_CSI0_DPHY_L2_PN_SWAP_EN_SHIFT 30
#define RG_CSI0_DPHY_L2_PN_SWAP_EN_MASK (0x1 << 30)

#define CDPHY_RX_ANA_4 0x0010
#define RG_CSI0_L2P_T1B_HSRT_CODE_SHIFT 0
#define RG_CSI0_L2P_T1B_HSRT_CODE_MASK (0x1f << 0)
#define RG_CSI0_L2N_T1C_HSRT_CODE_SHIFT 8
#define RG_CSI0_L2N_T1C_HSRT_CODE_MASK (0x1f << 8)
#define RG_CSI0_CPHY_T0_CDR_RSTB_CODE_SHIFT 16
#define RG_CSI0_CPHY_T0_CDR_RSTB_CODE_MASK (0x7 << 16)
#define RG_CSI0_CPHY_T0_CDR_SEC_EDGE_CODE_SHIFT 20
#define RG_CSI0_CPHY_T0_CDR_SEC_EDGE_CODE_MASK (0x7 << 20)
#define RG_CSI0_CPHY_T1_CDR_RSTB_CODE_SHIFT 24
#define RG_CSI0_CPHY_T1_CDR_RSTB_CODE_MASK (0x7 << 24)
#define RG_CSI0_CPHY_T1_CDR_SEC_EDGE_CODE_SHIFT 28
#define RG_CSI0_CPHY_T1_CDR_SEC_EDGE_CODE_MASK (0x7 << 28)

#define CDPHY_RX_ANA_5 0x0014
#define RG_CSI0_CDPHY_EQ_BW_SHIFT 0
#define RG_CSI0_CDPHY_EQ_BW_MASK (0x3 << 0)
#define RG_CSI0_CDPHY_EQ_IS_SHIFT 2
#define RG_CSI0_CDPHY_EQ_IS_MASK (0x3 << 2)
#define RG_CSI0_CDPHY_EQ_DG0_EN_SHIFT 4
#define RG_CSI0_CDPHY_EQ_DG0_EN_MASK (0x1 << 4)
#define RG_CSI0_CDPHY_EQ_DG1_EN_SHIFT 5
#define RG_CSI0_CDPHY_EQ_DG1_EN_MASK (0x1 << 5)
#define RG_CSI0_CDPHY_EQ_LATCH_EN_SHIFT 6
#define RG_CSI0_CDPHY_EQ_LATCH_EN_MASK (0x1 << 6)
#define RG_CSI0_CDPHY_EQ_SR0_SHIFT 8
#define RG_CSI0_CDPHY_EQ_SR0_MASK (0xf << 8)
#define RG_CSI0_CDPHY_EQ_SR1_SHIFT 12
#define RG_CSI0_CDPHY_EQ_SR1_MASK (0xf << 12)
#define RG_CSI0_L0_T0AB_EQ_MON_EN_SHIFT 16
#define RG_CSI0_L0_T0AB_EQ_MON_EN_MASK (0x1 << 16)
#define RG_CSI0_L1_T1AB_EQ_MON_EN_SHIFT 17
#define RG_CSI0_L1_T1AB_EQ_MON_EN_MASK (0x1 << 17)
#define RG_CSI0_L2_T1BC_EQ_MON_EN_SHIFT 18
#define RG_CSI0_L2_T1BC_EQ_MON_EN_MASK (0x1 << 18)
#define RG_CSI0_XX_T0BC_EQ_MON_EN_SHIFT 24
#define RG_CSI0_XX_T0BC_EQ_MON_EN_MASK (0x1 << 24)
#define RG_CSI0_XX_T0CA_EQ_MON_EN_SHIFT 25
#define RG_CSI0_XX_T0CA_EQ_MON_EN_MASK (0x1 << 25)
#define RG_CSI0_XX_T1CA_EQ_MON_EN_SHIFT 26
#define RG_CSI0_XX_T1CA_EQ_MON_EN_MASK (0x1 << 26)
#define RG_CSI0_T1_EN_SHIFT 28
#define RG_CSI0_T1_EN_MASK (0x1 << 28)
#define RG_CSI0_T0_EN_SHIFT 29
#define RG_CSI0_T0_EN_MASK (0x1 << 29)
#define RG_CSI0_ULPS_IGNORE_EN_SHIFT 30
#define RG_CSI0_ULPS_IGNORE_EN_MASK (0x1 << 30)
#define RG_CSI0_DA_ULPS_EN_INV_SHIFT 31
#define RG_CSI0_DA_ULPS_EN_INV_MASK (0x1 << 31)

#define CDPHY_RX_ANA_6 0x0018
#define RG_CSI0_CPHY_T0_CDR_AB_WIDTH_SHIFT 0
#define RG_CSI0_CPHY_T0_CDR_AB_WIDTH_MASK (0x3f << 0)
#define RG_CSI0_CPHY_T0_CDR_BC_WIDTH_SHIFT 8
#define RG_CSI0_CPHY_T0_CDR_BC_WIDTH_MASK (0x3f << 8)
#define RG_CSI0_CPHY_T0_CDR_CA_WIDTH_SHIFT 16
#define RG_CSI0_CPHY_T0_CDR_CA_WIDTH_MASK (0x3f << 16)
#define RG_CSI0_CPHY_T0_CDR_CK_DELAY_SHIFT 24
#define RG_CSI0_CPHY_T0_CDR_CK_DELAY_MASK (0x3f << 24)

#define CDPHY_RX_ANA_7 0x001c
#define RG_CSI0_CPHY_T1_CDR_AB_WIDTH_SHIFT 0
#define RG_CSI0_CPHY_T1_CDR_AB_WIDTH_MASK (0x3f << 0)
#define RG_CSI0_CPHY_T1_CDR_BC_WIDTH_SHIFT 8
#define RG_CSI0_CPHY_T1_CDR_BC_WIDTH_MASK (0x3f << 8)
#define RG_CSI0_CPHY_T1_CDR_CA_WIDTH_SHIFT 16
#define RG_CSI0_CPHY_T1_CDR_CA_WIDTH_MASK (0x3f << 16)
#define RG_CSI0_CPHY_T1_CDR_CK_DELAY_SHIFT 24
#define RG_CSI0_CPHY_T1_CDR_CK_DELAY_MASK (0x3f << 24)

#define CDPHY_RX_ANA_8 0x0020
#define RG_CSI0_RESERVE_SHIFT 0
#define RG_CSI0_RESERVE_MASK (0xffff << 0)
#define RG_CSI0_L0_T0AB_EQ_OS_CAL_EN_SHIFT 16
#define RG_CSI0_L0_T0AB_EQ_OS_CAL_EN_MASK (0x1 << 16)
#define RG_CSI0_L1_T1AB_EQ_OS_CAL_EN_SHIFT 17
#define RG_CSI0_L1_T1AB_EQ_OS_CAL_EN_MASK (0x1 << 17)
#define RG_CSI0_L2_T1BC_EQ_OS_CAL_EN_SHIFT 18
#define RG_CSI0_L2_T1BC_EQ_OS_CAL_EN_MASK (0x1 << 18)
#define RG_CSI0_XX_T0BC_EQ_OS_CAL_EN_SHIFT 19
#define RG_CSI0_XX_T0BC_EQ_OS_CAL_EN_MASK (0x1 << 19)
#define RG_CSI0_XX_T0CA_EQ_OS_CAL_EN_SHIFT 20
#define RG_CSI0_XX_T0CA_EQ_OS_CAL_EN_MASK (0x1 << 20)
#define RG_CSI0_XX_T1CA_EQ_OS_CAL_EN_SHIFT 21
#define RG_CSI0_XX_T1CA_EQ_OS_CAL_EN_MASK (0x1 << 21)
#define RG_CSI0_OS_CAL_SEL_SHIFT 24
#define RG_CSI0_OS_CAL_SEL_MASK (0x7 << 24)
#define RG_CSI0_OS_CAL_DIV_SHIFT 28
#define RG_CSI0_OS_CAL_DIV_MASK (0x7 << 28)

#define CDPHY_RX_ANA_9 0x0024
#define RGS_CSI0_CPHY_T0_DLL_CODE_SHIFT 0
#define RGS_CSI0_CPHY_T0_DLL_CODE_MASK (0xf << 0)
#define RGS_CSI0_CPHY_T0_MASK_CAL_CPLT_SHIFT 4
#define RGS_CSI0_CPHY_T0_MASK_CAL_CPLT_MASK (0x1 << 4)
#define RGS_CSI0_CPHY_T0_MASK_CAL_OF_SHIFT 5
#define RGS_CSI0_CPHY_T0_MASK_CAL_OF_MASK (0x1 << 5)
#define RGS_CSI0_CPHY_T1_DLL_CODE_SHIFT 8
#define RGS_CSI0_CPHY_T1_DLL_CODE_MASK (0xf << 8)
#define RGS_CSI0_CPHY_T1_MASK_CAL_CPLT_SHIFT 12
#define RGS_CSI0_CPHY_T1_MASK_CAL_CPLT_MASK (0x1 << 12)
#define RGS_CSI0_CPHY_T1_MASK_CAL_OF_SHIFT 13
#define RGS_CSI0_CPHY_T1_MASK_CAL_OF_MASK (0x1 << 13)
#define RGS_CSI0_CDPHY_L0_T0AB_OS_CAL_CPLT_SHIFT 16
#define RGS_CSI0_CDPHY_L0_T0AB_OS_CAL_CPLT_MASK (0x1 << 16)
#define RGS_CSI0_CDPHY_L1_T1AB_OS_CAL_CPLT_SHIFT 17
#define RGS_CSI0_CDPHY_L1_T1AB_OS_CAL_CPLT_MASK (0x1 << 17)
#define RGS_CSI0_CDPHY_L2_T1BC_OS_CAL_CPLT_SHIFT 18
#define RGS_CSI0_CDPHY_L2_T1BC_OS_CAL_CPLT_MASK (0x1 << 18)
#define RGS_CSI0_CPHY_T0BC_OS_CAL_CPLT_SHIFT 19
#define RGS_CSI0_CPHY_T0BC_OS_CAL_CPLT_MASK (0x1 << 19)
#define RGS_CSI0_CPHY_T0CA_OS_CAL_CPLT_SHIFT 20
#define RGS_CSI0_CPHY_T0CA_OS_CAL_CPLT_MASK (0x1 << 20)
#define RGS_CSI0_CPHY_T1CA_OS_CAL_CPLT_SHIFT 21
#define RGS_CSI0_CPHY_T1CA_OS_CAL_CPLT_MASK (0x1 << 21)
#define RGS_CSI0_OS_CAL_CODE_SHIFT 24
#define RGS_CSI0_OS_CAL_CODE_MASK (0xff << 24)

#define CDPHY_RX_ANA_10 0x0028
#define RG_CSI0_CDPHY_L0_T0AB_EQ_OS_CAL_FORCE_CODE_SHIFT 0
#define RG_CSI0_CDPHY_L0_T0AB_EQ_OS_CAL_FORCE_CODE_MASK (0x3f << 0)
#define RG_CSI0_CDPHY_L0_T0AB_EQ_OS_CAL_FORCE_EN_SHIFT 7
#define RG_CSI0_CDPHY_L0_T0AB_EQ_OS_CAL_FORCE_EN_MASK (0x1 << 7)
#define RG_CSI0_CDPHY_XX_T0CA_EQ_OS_CAL_FORCE_CODE_SHIFT 8
#define RG_CSI0_CDPHY_XX_T0CA_EQ_OS_CAL_FORCE_CODE_MASK (0x3f << 8)
#define RG_CSI0_CDPHY_XX_T0CA_EQ_OS_CAL_FORCE_EN_SHIFT 15
#define RG_CSI0_CDPHY_XX_T0CA_EQ_OS_CAL_FORCE_EN_MASK (0x1 << 15)
#define RG_CSI0_CDPHY_XX_T0BC_EQ_OS_CAL_FORCE_CODE_SHIFT 16
#define RG_CSI0_CDPHY_XX_T0BC_EQ_OS_CAL_FORCE_CODE_MASK (0x3f << 16)
#define RG_CSI0_CDPHY_XX_T0BC_EQ_OS_CAL_FORCE_EN_SHIFT 23
#define RG_CSI0_CDPHY_XX_T0BC_EQ_OS_CAL_FORCE_EN_MASK (0x1 << 23)
#define RG_CSI0_CDPHY_L1_T1AB_EQ_OS_CAL_FORCE_CODE_SHIFT 24
#define RG_CSI0_CDPHY_L1_T1AB_EQ_OS_CAL_FORCE_CODE_MASK (0x3f << 24)
#define RG_CSI0_CDPHY_L1_T1AB_EQ_OS_CAL_FORCE_EN_SHIFT 31
#define RG_CSI0_CDPHY_L1_T1AB_EQ_OS_CAL_FORCE_EN_MASK (0x1 << 31)

#define CDPHY_RX_ANA_11 0x002c
#define RG_CSI0_CDPHY_XX_T1CA_EQ_OS_CAL_FORCE_CODE_SHIFT 0
#define RG_CSI0_CDPHY_XX_T1CA_EQ_OS_CAL_FORCE_CODE_MASK (0x3f << 0)
#define RG_CSI0_CDPHY_XX_T1CA_EQ_OS_CAL_FORCE_EN_SHIFT 7
#define RG_CSI0_CDPHY_XX_T1CA_EQ_OS_CAL_FORCE_EN_MASK (0x1 << 7)
#define RG_CSI0_CDPHY_L2_T1BC_EQ_OS_CAL_FORCE_CODE_SHIFT 8
#define RG_CSI0_CDPHY_L2_T1BC_EQ_OS_CAL_FORCE_CODE_MASK (0x3f << 8)
#define RG_CSI0_CDPHY_L2_T1BC_EQ_OS_CAL_FORCE_EN_SHIFT 15
#define RG_CSI0_CDPHY_L2_T1BC_EQ_OS_CAL_FORCE_EN_MASK (0x1 << 15)

#define CDPHY_RX_ANA_12 0x0030
#define RG_CSI0_CPHY_T0_CDR_EN_DLY_SHIFT 0
#define RG_CSI0_CPHY_T0_CDR_EN_DLY_MASK (0x3f << 0)
#define RG_CSI0_CPHY_T1_CDR_EN_DLY_SHIFT 8
#define RG_CSI0_CPHY_T1_CDR_EN_DLY_MASK (0x3f << 8)
#define RG_CSI0_CPHY_T0_EQ_EN_DLY_SHIFT 16
#define RG_CSI0_CPHY_T0_EQ_EN_DLY_MASK (0x3f << 16)
#define RG_CSI0_CPHY_T1_EQ_EN_DLY_SHIFT 24
#define RG_CSI0_CPHY_T1_EQ_EN_DLY_MASK (0x3f << 24)

#define CDPHY_RX_ANA_13 0x0034
#define RG_CSI0_CPHY_T0_CDR_SEL_CODE_SHIFT 0
#define RG_CSI0_CPHY_T0_CDR_SEL_CODE_MASK (0x1f << 0)
#define RG_CSI0_CPHY_T1_CDR_SEL_CODE_SHIFT 8
#define RG_CSI0_CPHY_T1_CDR_SEL_CODE_MASK (0x1f << 8)
#define RG_CSI0_CDPHY_EQ_BW_RDC_SHIFT 16
#define RG_CSI0_CDPHY_EQ_BW_RDC_MASK (0x3 << 16)

#define CDPHY_RX_ANA_14 0x0038
#define RG_CSI0_BG_LDO_VSHIFTL_SEL_SHIFT 0
#define RG_CSI0_BG_LDO_VSHIFTL_SEL_MASK (0x7 << 0)
#define RG_CSI0_BG_LDO_VSHIFTH_SEL_SHIFT 4
#define RG_CSI0_BG_LDO_VSHIFTH_SEL_MASK (0x7 << 4)
#define RG_CSI0_CDPHY_EQ_OS_IS_SHIFT 8
#define RG_CSI0_CDPHY_EQ_OS_IS_MASK (0x1 << 8)
#define RG_CSI0_XX_T1CA_EQ_OS_CAL_CPLT_CG_EN_SHIFT 16
#define RG_CSI0_XX_T1CA_EQ_OS_CAL_CPLT_CG_EN_MASK (0x1 << 16)
#define RG_CSI0_XX_T0CA_EQ_OS_CAL_CPLT_CG_EN_SHIFT 17
#define RG_CSI0_XX_T0CA_EQ_OS_CAL_CPLT_CG_EN_MASK (0x1 << 17)
#define RG_CSI0_XX_T0BC_EQ_OS_CAL_CPLT_CG_EN_SHIFT 18
#define RG_CSI0_XX_T0BC_EQ_OS_CAL_CPLT_CG_EN_MASK (0x1 << 18)
#define RG_CSI0_L2_T1BC_EQ_OS_CAL_CPLT_CG_EN_SHIFT 19
#define RG_CSI0_L2_T1BC_EQ_OS_CAL_CPLT_CG_EN_MASK (0x1 << 19)
#define RG_CSI0_L1_T1AB_EQ_OS_CAL_CPLT_CG_EN_SHIFT 20
#define RG_CSI0_L1_T1AB_EQ_OS_CAL_CPLT_CG_EN_MASK (0x1 << 20)
#define RG_CSI0_L0_T0AB_EQ_OS_CAL_CPLT_CG_EN_SHIFT 21
#define RG_CSI0_L0_T0AB_EQ_OS_CAL_CPLT_CG_EN_MASK (0x1 << 21)
#define RG_CSI0_LDO_LP_EN_SHIFT 24
#define RG_CSI0_LDO_LP_EN_MASK (0x1 << 24)
#define RG_CSI0_LDO_X26M_EN_SHIFT 25
#define RG_CSI0_LDO_X26M_EN_MASK (0x1 << 25)

#define CDPHY_RX_ANA_FORCE_MODE_0 0x0040
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L0P_T0A_LPRX_EN_SHIFT 0
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L0P_T0A_LPRX_EN_MASK (0x1 << 0)
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L0N_T0B_LPRX_EN_SHIFT 1
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L0N_T0B_LPRX_EN_MASK (0x1 << 1)
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L1P_T0C_LPRX_EN_SHIFT 4
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L1P_T0C_LPRX_EN_MASK (0x1 << 4)
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L1N_T1A_LPRX_EN_SHIFT 5
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L1N_T1A_LPRX_EN_MASK (0x1 << 5)
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L2P_T1B_LPRX_EN_SHIFT 8
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L2P_T1B_LPRX_EN_MASK (0x1 << 8)
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L2N_T1C_LPRX_EN_SHIFT 9
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L2N_T1C_LPRX_EN_MASK (0x1 << 9)
#define RO_DA_CSI0_CDPHY_L0P_T0A_LPRX_EN_SHIFT 16
#define RO_DA_CSI0_CDPHY_L0P_T0A_LPRX_EN_MASK (0x1 << 16)
#define RO_DA_CSI0_CDPHY_L0N_T0B_LPRX_EN_SHIFT 17
#define RO_DA_CSI0_CDPHY_L0N_T0B_LPRX_EN_MASK (0x1 << 17)
#define RO_DA_CSI0_CDPHY_L1P_T0C_LPRX_EN_SHIFT 20
#define RO_DA_CSI0_CDPHY_L1P_T0C_LPRX_EN_MASK (0x1 << 20)
#define RO_DA_CSI0_CDPHY_L1N_T1A_LPRX_EN_SHIFT 21
#define RO_DA_CSI0_CDPHY_L1N_T1A_LPRX_EN_MASK (0x1 << 21)
#define RO_DA_CSI0_CDPHY_L2P_T1B_LPRX_EN_SHIFT 24
#define RO_DA_CSI0_CDPHY_L2P_T1B_LPRX_EN_MASK (0x1 << 24)
#define RO_DA_CSI0_CDPHY_L2N_T1C_LPRX_EN_SHIFT 25
#define RO_DA_CSI0_CDPHY_L2N_T1C_LPRX_EN_MASK (0x1 << 25)

#define CDPHY_RX_ANA_FORCE_MODE_EN_0 0x0044
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L0P_T0A_LPRX_EN_SHIFT 0
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L0P_T0A_LPRX_EN_MASK (0x1 << 0)
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L0N_T0B_LPRX_EN_SHIFT 1
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L0N_T0B_LPRX_EN_MASK (0x1 << 1)
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L1P_T0C_LPRX_EN_SHIFT 4
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L1P_T0C_LPRX_EN_MASK (0x1 << 4)
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L1N_T1A_LPRX_EN_SHIFT 5
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L1N_T1A_LPRX_EN_MASK (0x1 << 5)
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L2P_T1B_LPRX_EN_SHIFT 8
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L2P_T1B_LPRX_EN_MASK (0x1 << 8)
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L2N_T1C_LPRX_EN_SHIFT 9
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L2N_T1C_LPRX_EN_MASK (0x1 << 9)
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_ULPS_EN_SHIFT 10
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_ULPS_EN_MASK (0x1 << 10)
#define RG_SW_FORCE_VAL_DA_CSI0_CPHY_T0_ALPRX_EN_SHIFT 16
#define RG_SW_FORCE_VAL_DA_CSI0_CPHY_T0_ALPRX_EN_MASK (0x1 << 16)
#define RG_SW_FORCE_VAL_DA_CSI0_CPHY_T1_ALPRX_EN_SHIFT 17
#define RG_SW_FORCE_VAL_DA_CSI0_CPHY_T1_ALPRX_EN_MASK (0x1 << 17)
#define RG_SW_FORCE_VAL_DA_CSI0_CPHY_T0_SELF_CAL_EN_SHIFT 20
#define RG_SW_FORCE_VAL_DA_CSI0_CPHY_T0_SELF_CAL_EN_MASK (0x1 << 20)
#define RG_SW_FORCE_VAL_DA_CSI0_CPHY_T1_SELF_CAL_EN_SHIFT 21
#define RG_SW_FORCE_VAL_DA_CSI0_CPHY_T1_SELF_CAL_EN_MASK (0x1 << 21)
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_ULPS_EN_SHIFT 24
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_ULPS_EN_MASK (0x1 << 24)

#define CDPHY_RX_ANA_AD_0 0x0048
#define RO_AD_CSI0_CDPHY_L0P_T0A_LPRX_OUT_SHIFT 0
#define RO_AD_CSI0_CDPHY_L0P_T0A_LPRX_OUT_MASK (0x1 << 0)
#define RO_AD_CSI0_CDPHY_L0N_T0B_LPRX_OUT_SHIFT 1
#define RO_AD_CSI0_CDPHY_L0N_T0B_LPRX_OUT_MASK (0x1 << 1)
#define RO_AD_CSI0_CDPHY_L1P_T0C_LPRX_OUT_SHIFT 4
#define RO_AD_CSI0_CDPHY_L1P_T0C_LPRX_OUT_MASK (0x1 << 4)
#define RO_AD_CSI0_CDPHY_L1N_T1A_LPRX_OUT_SHIFT 5
#define RO_AD_CSI0_CDPHY_L1N_T1A_LPRX_OUT_MASK (0x1 << 5)
#define RO_AD_CSI0_CDPHY_L2P_T1B_LPRX_OUT_SHIFT 8
#define RO_AD_CSI0_CDPHY_L2P_T1B_LPRX_OUT_MASK (0x1 << 8)
#define RO_AD_CSI0_CDPHY_L2N_T1C_LPRX_OUT_SHIFT 9
#define RO_AD_CSI0_CDPHY_L2N_T1C_LPRX_OUT_MASK (0x1 << 9)

#define CDPHY_RX_ANA_FORCE_MODE_1 0x0050
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L0_ALPRX_EN_SHIFT 0
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L0_ALPRX_EN_MASK (0x1 << 0)
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L1_ALPRX_EN_SHIFT 4
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L1_ALPRX_EN_MASK (0x1 << 4)
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L2_ALPRX_EN_SHIFT 8
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L2_ALPRX_EN_MASK (0x1 << 8)
#define RO_DA_CSI0_CPHY_T0_ALPRX_EN_SHIFT 16
#define RO_DA_CSI0_CPHY_T0_ALPRX_EN_MASK (0x1 << 16)
#define RO_DA_CSI0_CPHY_T1_ALPRX_EN_SHIFT 20
#define RO_DA_CSI0_CPHY_T1_ALPRX_EN_MASK (0x1 << 20)

#define CDPHY_RX_ANA_FORCE_MODE_EN_1 0x0054
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L0_ALPRX_EN_SHIFT 0
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L0_ALPRX_EN_MASK (0x1 << 0)
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L1_ALPRX_EN_SHIFT 4
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L1_ALPRX_EN_MASK (0x1 << 4)
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L2_ALPRX_EN_SHIFT 8
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L2_ALPRX_EN_MASK (0x1 << 8)

#define CDPHY_RX_ANA_AD_1 0x0058
#define RO_AD_CSI0_CPHY_T0_ALPRX_OUT_SHIFT 0
#define RO_AD_CSI0_CPHY_T0_ALPRX_OUT_MASK (0x1 << 0)
#define RO_AD_CSI0_CPHY_T1_ALPRX_OUT_SHIFT 4
#define RO_AD_CSI0_CPHY_T1_ALPRX_OUT_MASK (0x1 << 4)

#define CDPHY_RX_ANA_FORCE_MODE_2 0x0060
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L0P_T0A_HSRT_EN_SHIFT 0
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L0P_T0A_HSRT_EN_MASK (0x1 << 0)
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L0N_T0B_HSRT_EN_SHIFT 1
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L0N_T0B_HSRT_EN_MASK (0x1 << 1)
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L1P_T0C_HSRT_EN_SHIFT 4
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L1P_T0C_HSRT_EN_MASK (0x1 << 4)
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L1N_T1A_HSRT_EN_SHIFT 5
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L1N_T1A_HSRT_EN_MASK (0x1 << 5)
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L2P_T1B_HSRT_EN_SHIFT 8
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L2P_T1B_HSRT_EN_MASK (0x1 << 8)
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L2N_T1C_HSRT_EN_SHIFT 9
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L2N_T1C_HSRT_EN_MASK (0x1 << 9)
#define RO_DA_CSI0_CDPHY_L0P_T0A_HSRT_EN_SHIFT 16
#define RO_DA_CSI0_CDPHY_L0P_T0A_HSRT_EN_MASK (0x1 << 16)
#define RO_DA_CSI0_CDPHY_L0N_T0B_HSRT_EN_SHIFT 17
#define RO_DA_CSI0_CDPHY_L0N_T0B_HSRT_EN_MASK (0x1 << 17)
#define RO_DA_CSI0_CDPHY_L1P_T0C_HSRT_EN_SHIFT 20
#define RO_DA_CSI0_CDPHY_L1P_T0C_HSRT_EN_MASK (0x1 << 20)
#define RO_DA_CSI0_CDPHY_L1N_T1A_HSRT_EN_SHIFT 21
#define RO_DA_CSI0_CDPHY_L1N_T1A_HSRT_EN_MASK (0x1 << 21)
#define RO_DA_CSI0_CDPHY_L2P_T1B_HSRT_EN_SHIFT 24
#define RO_DA_CSI0_CDPHY_L2P_T1B_HSRT_EN_MASK (0x1 << 24)
#define RO_DA_CSI0_CDPHY_L2N_T1C_HSRT_EN_SHIFT 25
#define RO_DA_CSI0_CDPHY_L2N_T1C_HSRT_EN_MASK (0x1 << 25)
#define RO_DA_CSI0_CDPHY_ULPS_EN_SHIFT 28
#define RO_DA_CSI0_CDPHY_ULPS_EN_MASK (0x1 << 28)

#define CDPHY_RX_ANA_FORCE_MODE_EN_2 0x0064
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L0P_T0A_HSRT_EN_SHIFT 0
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L0P_T0A_HSRT_EN_MASK (0x1 << 0)
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L0N_T0B_HSRT_EN_SHIFT 1
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L0N_T0B_HSRT_EN_MASK (0x1 << 1)
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L1P_T0C_HSRT_EN_SHIFT 4
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L1P_T0C_HSRT_EN_MASK (0x1 << 4)
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L1N_T1A_HSRT_EN_SHIFT 5
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L1N_T1A_HSRT_EN_MASK (0x1 << 5)
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L2P_T1B_HSRT_EN_SHIFT 8
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L2P_T1B_HSRT_EN_MASK (0x1 << 8)
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L2N_T1C_HSRT_EN_SHIFT 9
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L2N_T1C_HSRT_EN_MASK (0x1 << 9)

#define CDPHY_RX_ANA_FORCE_MODE_3 0x0070
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L0_T0AB_EQ_EN_SHIFT 0
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L0_T0AB_EQ_EN_MASK (0x1 << 0)
#define RG_SW_FORCE_VAL_DA_CSI0_CPHY_T0CA_EQ_EN_SHIFT 1
#define RG_SW_FORCE_VAL_DA_CSI0_CPHY_T0CA_EQ_EN_MASK (0x1 << 1)
#define RG_SW_FORCE_VAL_DA_CSI0_CPHY_T0BC_EQ_EN_SHIFT 4
#define RG_SW_FORCE_VAL_DA_CSI0_CPHY_T0BC_EQ_EN_MASK (0x1 << 4)
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L1_T1AB_EQ_EN_SHIFT 5
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L1_T1AB_EQ_EN_MASK (0x1 << 5)
#define RG_SW_FORCE_VAL_DA_CSI0_CPHY_T1CA_EQ_EN_SHIFT 8
#define RG_SW_FORCE_VAL_DA_CSI0_CPHY_T1CA_EQ_EN_MASK (0x1 << 8)
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L2_T1BC_EQ_EN_SHIFT 9
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L2_T1BC_EQ_EN_MASK (0x1 << 9)
#define RO_DA_CSI0_CDPHY_L0_T0AB_EQ_EN_SHIFT 16
#define RO_DA_CSI0_CDPHY_L0_T0AB_EQ_EN_MASK (0x1 << 16)
#define RO_DA_CSI0_CPHY_T0CA_EQ_EN_SHIFT 17
#define RO_DA_CSI0_CPHY_T0CA_EQ_EN_MASK (0x1 << 17)
#define RO_DA_CSI0_CPHY_T0BC_EQ_EN_SHIFT 20
#define RO_DA_CSI0_CPHY_T0BC_EQ_EN_MASK (0x1 << 20)
#define RO_DA_CSI0_CDPHY_L1_T1AB_EQ_EN_SHIFT 21
#define RO_DA_CSI0_CDPHY_L1_T1AB_EQ_EN_MASK (0x1 << 21)
#define RO_DA_CSI0_CPHY_T1CA_EQ_EN_SHIFT 24
#define RO_DA_CSI0_CPHY_T1CA_EQ_EN_MASK (0x1 << 24)
#define RO_DA_CSI0_CDPHY_L2_T1BC_EQ_EN_SHIFT 25
#define RO_DA_CSI0_CDPHY_L2_T1BC_EQ_EN_MASK (0x1 << 25)

#define CDPHY_RX_ANA_FORCE_MODE_EN_3 0x0074
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L0_T0AB_EQ_EN_SHIFT 0
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L0_T0AB_EQ_EN_MASK (0x1 << 0)
#define RG_SW_FORCE_EN_DA_CSI0_CPHY_T0CA_EQ_EN_SHIFT 1
#define RG_SW_FORCE_EN_DA_CSI0_CPHY_T0CA_EQ_EN_MASK (0x1 << 1)
#define RG_SW_FORCE_EN_DA_CSI0_CPHY_T0BC_EQ_EN_SHIFT 4
#define RG_SW_FORCE_EN_DA_CSI0_CPHY_T0BC_EQ_EN_MASK (0x1 << 4)
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L1_T1AB_EQ_EN_SHIFT 5
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L1_T1AB_EQ_EN_MASK (0x1 << 5)
#define RG_SW_FORCE_EN_DA_CSI0_CPHY_T1CA_EQ_EN_SHIFT 8
#define RG_SW_FORCE_EN_DA_CSI0_CPHY_T1CA_EQ_EN_MASK (0x1 << 8)
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L2_T1BC_EQ_EN_SHIFT 9
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L2_T1BC_EQ_EN_MASK (0x1 << 9)

#define CDPHY_RX_ANA_FORCE_MODE_4 0x0080
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L0_SAMP_EN_SHIFT 0
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L0_SAMP_EN_MASK (0x1 << 0)
#define RG_SW_FORCE_VAL_DA_CSI0_CPHY_T0_CDR_EN_SHIFT 1
#define RG_SW_FORCE_VAL_DA_CSI0_CPHY_T0_CDR_EN_MASK (0x1 << 1)
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L1_SAMP_EN_SHIFT 4
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L1_SAMP_EN_MASK (0x1 << 4)
#define RG_SW_FORCE_VAL_DA_CSI0_CPHY_T1_CDR_EN_SHIFT 5
#define RG_SW_FORCE_VAL_DA_CSI0_CPHY_T1_CDR_EN_MASK (0x1 << 5)
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L2_SAMP_EN_SHIFT 8
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L2_SAMP_EN_MASK (0x1 << 8)
#define RO_DA_CSI0_DPHY_L0_SAMP_EN_SHIFT 16
#define RO_DA_CSI0_DPHY_L0_SAMP_EN_MASK (0x1 << 16)
#define RO_DA_CSI0_CPHY_T0_CDR_EN_SHIFT 17
#define RO_DA_CSI0_CPHY_T0_CDR_EN_MASK (0x1 << 17)
#define RO_DA_CSI0_DPHY_L1_SAMP_EN_SHIFT 20
#define RO_DA_CSI0_DPHY_L1_SAMP_EN_MASK (0x1 << 20)
#define RO_DA_CSI0_CPHY_T1_CDR_EN_SHIFT 21
#define RO_DA_CSI0_CPHY_T1_CDR_EN_MASK (0x1 << 21)
#define RO_DA_CSI0_DPHY_L2_SAMP_EN_SHIFT 24
#define RO_DA_CSI0_DPHY_L2_SAMP_EN_MASK (0x1 << 24)

#define CDPHY_RX_ANA_FORCE_MODE_EN_4 0x0084
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L0_SAMP_EN_SHIFT 0
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L0_SAMP_EN_MASK (0x1 << 0)
#define RG_SW_FORCE_EN_DA_CSI0_CPHY_T0_CDR_EN_SHIFT 1
#define RG_SW_FORCE_EN_DA_CSI0_CPHY_T0_CDR_EN_MASK (0x1 << 1)
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L1_SAMP_EN_SHIFT 4
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L1_SAMP_EN_MASK (0x1 << 4)
#define RG_SW_FORCE_EN_DA_CSI0_CPHY_T1_CDR_EN_SHIFT 5
#define RG_SW_FORCE_EN_DA_CSI0_CPHY_T1_CDR_EN_MASK (0x1 << 5)
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L2_SAMP_EN_SHIFT 8
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L2_SAMP_EN_MASK (0x1 << 8)

#define CDPHY_RX_ANA_FORCE_MODE_5 0x0090
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L0_T0_DES_EN_SHIFT 0
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L0_T0_DES_EN_MASK (0x1 << 0)
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L1_DES_EN_SHIFT 1
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L1_DES_EN_MASK (0x1 << 1)
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L2_T1_DES_EN_SHIFT 2
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L2_T1_DES_EN_MASK (0x1 << 2)
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L0_T0_DES_SYNC_INIT_SHIFT 8
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L0_T0_DES_SYNC_INIT_MASK (0x1 << 8)
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L1_DES_SYNC_INIT_SHIFT 9
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L1_DES_SYNC_INIT_MASK (0x1 << 9)
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L2_T1_DES_SYNC_INIT_SHIFT 10
#define RG_SW_FORCE_VAL_DA_CSI0_CDPHY_L2_T1_DES_SYNC_INIT_MASK (0x1 << 10)
#define RO_DA_CSI0_CDPHY_L0_T0_DES_EN_SHIFT 16
#define RO_DA_CSI0_CDPHY_L0_T0_DES_EN_MASK (0x1 << 16)
#define RO_DA_CSI0_DPHY_L1_DES_EN_SHIFT 17
#define RO_DA_CSI0_DPHY_L1_DES_EN_MASK (0x1 << 17)
#define RO_DA_CSI0_CDPHY_L2_T1_DES_EN_SHIFT 18
#define RO_DA_CSI0_CDPHY_L2_T1_DES_EN_MASK (0x1 << 18)
#define RO_DA_CSI0_CDPHY_L0_T0_DES_SYNC_INIT_SHIFT 24
#define RO_DA_CSI0_CDPHY_L0_T0_DES_SYNC_INIT_MASK (0x1 << 24)
#define RO_DA_CSI0_DPHY_L1_DES_SYNC_INIT_SHIFT 25
#define RO_DA_CSI0_DPHY_L1_DES_SYNC_INIT_MASK (0x1 << 25)
#define RO_DA_CSI0_CDPHY_L2_T1_DES_SYNC_INIT_SHIFT 26
#define RO_DA_CSI0_CDPHY_L2_T1_DES_SYNC_INIT_MASK (0x1 << 26)

#define CDPHY_RX_ANA_FORCE_MODE_EN_5 0x0094
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L0_T0_DES_EN_SHIFT 0
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L0_T0_DES_EN_MASK (0x1 << 0)
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L1_DES_EN_SHIFT 1
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L1_DES_EN_MASK (0x1 << 1)
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L2_T1_DES_EN_SHIFT 2
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L2_T1_DES_EN_MASK (0x1 << 2)
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L0_T0_DES_SYNC_INIT_SHIFT 8
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L0_T0_DES_SYNC_INIT_MASK (0x1 << 8)
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L1_DES_SYNC_INIT_SHIFT 9
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L1_DES_SYNC_INIT_MASK (0x1 << 9)
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L2_T1_DES_SYNC_INIT_SHIFT 10
#define RG_SW_FORCE_EN_DA_CSI0_CDPHY_L2_T1_DES_SYNC_INIT_MASK (0x1 << 10)
#define RG_SW_FORCE_EN_DA_CSI0_CPHY_T0_ALPRX_EN_SHIFT 12
#define RG_SW_FORCE_EN_DA_CSI0_CPHY_T0_ALPRX_EN_MASK (0x1 << 12)
#define RG_SW_FORCE_EN_DA_CSI0_CPHY_T1_ALPRX_EN_SHIFT 13
#define RG_SW_FORCE_EN_DA_CSI0_CPHY_T1_ALPRX_EN_MASK (0x1 << 13)
#define RG_SW_FORCE_EN_DA_CSI0_CPHY_T0_SELF_CAL_EN_SHIFT 14
#define RG_SW_FORCE_EN_DA_CSI0_CPHY_T0_SELF_CAL_EN_MASK (0x1 << 14)
#define RG_SW_FORCE_EN_DA_CSI0_CPHY_T1_SELF_CAL_EN_SHIFT 15
#define RG_SW_FORCE_EN_DA_CSI0_CPHY_T1_SELF_CAL_EN_MASK (0x1 << 15)

#define CDPHY_RX_ANA_AD_HS_0 0x00a0
#define RO_AD_CSI0_CPHY_T0BC_SHIFT 0
#define RO_AD_CSI0_CPHY_T0BC_MASK (0xffff << 0)
#define RO_AD_CSI0_CDPHY_L0_T0AB_SHIFT 16
#define RO_AD_CSI0_CDPHY_L0_T0AB_MASK (0xffff << 16)

#define CDPHY_RX_ANA_AD_HS_1 0x00a4
#define RO_AD_CSI0_DPHY_L1_SHIFT 0
#define RO_AD_CSI0_DPHY_L1_MASK (0xffff << 0)
#define RO_AD_CSI0_CPHY_T0CA_SHIFT 16
#define RO_AD_CSI0_CPHY_T0CA_MASK (0xffff << 16)

#define CDPHY_RX_ANA_AD_HS_2 0x00a8
#define RO_AD_CSI0_CDPHY_L2_T1BC_SHIFT 0
#define RO_AD_CSI0_CDPHY_L2_T1BC_MASK (0xffff << 0)
#define RO_AD_CSI0_CPHY_T1AB_SHIFT 16
#define RO_AD_CSI0_CPHY_T1AB_MASK (0xffff << 16)

#define CDPHY_RX_ANA_FORCE_MODE_6 0x00b0
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L0_DELAY_CODE_SHIFT 0
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L0_DELAY_CODE_MASK (0xff << 0)
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L0_DELAY_EN_SHIFT 8
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L0_DELAY_EN_MASK (0x1 << 8)
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L0_DELAY_APPLY_SHIFT 9
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L0_DELAY_APPLY_MASK (0x1 << 9)
#define RO_DA_CSI0_DPHY_L0_DELAY_CODE_SHIFT 16
#define RO_DA_CSI0_DPHY_L0_DELAY_CODE_MASK (0xff << 16)
#define RO_DA_CSI0_DPHY_L0_DELAY_EN_SHIFT 24
#define RO_DA_CSI0_DPHY_L0_DELAY_EN_MASK (0x1 << 24)
#define RO_DA_CSI0_DPHY_L0_DELAY_APPLY_SHIFT 25
#define RO_DA_CSI0_DPHY_L0_DELAY_APPLY_MASK (0x1 << 25)

#define CDPHY_RX_ANA_FORCE_MODE_EN_6 0x00b4
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L0_DELAY_CODE_SHIFT 0
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L0_DELAY_CODE_MASK (0x1 << 0)
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L0_DELAY_EN_SHIFT 8
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L0_DELAY_EN_MASK (0x1 << 8)
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L0_DELAY_APPLY_SHIFT 9
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L0_DELAY_APPLY_MASK (0x1 << 9)
#define RO_AD_CSI0_CPHY_T1CA_SHIFT 16
#define RO_AD_CSI0_CPHY_T1CA_MASK (0xffff << 16)

#define CDPHY_RX_ANA_FORCE_MODE_7 0x00c0
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L1_DELAY_CODE_SHIFT 0
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L1_DELAY_CODE_MASK (0xff << 0)
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L1_DELAY_EN_SHIFT 8
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L1_DELAY_EN_MASK (0x1 << 8)
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L1_DELAY_APPLY_SHIFT 9
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L1_DELAY_APPLY_MASK (0x1 << 9)
#define RO_DA_CSI0_DPHY_L1_DELAY_CODE_SHIFT 16
#define RO_DA_CSI0_DPHY_L1_DELAY_CODE_MASK (0xff << 16)
#define RO_DA_CSI0_DPHY_L1_DELAY_EN_SHIFT 24
#define RO_DA_CSI0_DPHY_L1_DELAY_EN_MASK (0x1 << 24)
#define RO_DA_CSI0_DPHY_L1_DELAY_APPLY_SHIFT 25
#define RO_DA_CSI0_DPHY_L1_DELAY_APPLY_MASK (0x1 << 25)

#define CDPHY_RX_ANA_FORCE_MODE_EN_7 0x00c4
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L1_DELAY_CODE_SHIFT 0
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L1_DELAY_CODE_MASK (0x1 << 0)
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L1_DELAY_EN_SHIFT 8
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L1_DELAY_EN_MASK (0x1 << 8)
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L1_DELAY_APPLY_SHIFT 9
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L1_DELAY_APPLY_MASK (0x1 << 9)

#define CDPHY_RX_ANA_FORCE_MODE_8 0x00d0
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L2_DELAY_CODE_SHIFT 0
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L2_DELAY_CODE_MASK (0xff << 0)
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L2_DELAY_EN_SHIFT 8
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L2_DELAY_EN_MASK (0x1 << 8)
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L2_DELAY_APPLY_SHIFT 9
#define RG_SW_FORCE_VAL_DA_CSI0_DPHY_L2_DELAY_APPLY_MASK (0x1 << 9)
#define RO_DA_CSI0_DPHY_L2_DELAY_CODE_SHIFT 16
#define RO_DA_CSI0_DPHY_L2_DELAY_CODE_MASK (0xff << 16)
#define RO_DA_CSI0_DPHY_L2_DELAY_EN_SHIFT 24
#define RO_DA_CSI0_DPHY_L2_DELAY_EN_MASK (0x1 << 24)
#define RO_DA_CSI0_DPHY_L2_DELAY_APPLY_SHIFT 25
#define RO_DA_CSI0_DPHY_L2_DELAY_APPLY_MASK (0x1 << 25)

#define CDPHY_RX_ANA_FORCE_MODE_EN_8 0x00d4
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L2_DELAY_CODE_SHIFT 0
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L2_DELAY_CODE_MASK (0x1 << 0)
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L2_DELAY_EN_SHIFT 8
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L2_DELAY_EN_MASK (0x1 << 8)
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L2_DELAY_APPLY_SHIFT 9
#define RG_SW_FORCE_EN_DA_CSI0_DPHY_L2_DELAY_APPLY_MASK (0x1 << 9)

#define CDPHY_RX_ANA_SETTING_0 0x00f0
#define CSR_CSI_CLK_MON_SHIFT 0
#define CSR_CSI_CLK_MON_MASK (0x1 << 0)
#define CSR_CSI_CLK_EN_SHIFT 1
#define CSR_CSI_CLK_EN_MASK (0x1 << 1)
#define CSR_ANA_REF_CK_SEL_SHIFT 3
#define CSR_ANA_REF_CK_SEL_MASK (0x1 << 3)
#define CSR_ASYNC_FIFO_GATING_SEL_SHIFT 4
#define CSR_ASYNC_FIFO_GATING_SEL_MASK (0xf << 4)
#define CSR_CSI_MON_MUX_SHIFT 8
#define CSR_CSI_MON_MUX_MASK (0xff << 8)
#define CSR_CSI_RST_MODE_SHIFT 16
#define CSR_CSI_RST_MODE_MASK (0x3 << 16)
#define CSR_SW_RST_SHIFT 24
#define CSR_SW_RST_MASK (0xf << 24)
#define DPHY_SYNC_INIT_EXTEND_EN_SHIFT 28
#define DPHY_SYNC_INIT_EXTEND_EN_MASK (0x1 << 28)
#define DPHY_DELAY_APPLY_D1T_EN_SHIFT 29
#define DPHY_DELAY_APPLY_D1T_EN_MASK (0x1 << 29)
#define DPHY_LRTE_DUMMY_VALID_SHIFT 30
#define DPHY_LRTE_DUMMY_VALID_MASK (0x1 << 30)
#define DPHY_SYNC_INIT_LRTE_SHIFT 31
#define DPHY_SYNC_INIT_LRTE_MASK (0x1 << 31)

#define CDPHY_RX_ANA_SETTING_1 0x00f4
#define RG_CSI0_CDPHY_FMCK_SEL_SHIFT 0
#define RG_CSI0_CDPHY_FMCK_SEL_MASK (0x3 << 0)
#define RG_AFIFO_DUMMY_VALID_EN_SHIFT 2
#define RG_AFIFO_DUMMY_VALID_EN_MASK (0x1 << 2)
#define RG_CSI0_ASYNC_OPTION_SHIFT 4
#define RG_CSI0_ASYNC_OPTION_MASK (0xf << 4)
#define RG_CAL_METHOD_3S_SHIFT 8
#define RG_CAL_METHOD_3S_MASK (0x1 << 8)
#define RG_DA_SYNC_INIT_D1T_SEL_SHIFT 9
#define RG_DA_SYNC_INIT_D1T_SEL_MASK (0x1 << 9)
#define CSR_CSI0_DPHY_L0_ASYNC_FIFO_CG_DIS_SHIFT 12
#define CSR_CSI0_DPHY_L0_ASYNC_FIFO_CG_DIS_MASK (0x1 << 12)
#define CSR_CSI0_DPHY_L1_ASYNC_FIFO_CG_DIS_SHIFT 13
#define CSR_CSI0_DPHY_L1_ASYNC_FIFO_CG_DIS_MASK (0x1 << 13)
#define CSR_CSI0_DPHY_L2_ASYNC_FIFO_CG_DIS_SHIFT 14
#define CSR_CSI0_DPHY_L2_ASYNC_FIFO_CG_DIS_MASK (0x1 << 14)
#define RG_AFIFO_DUMMY_VALID_PREPARE_NUM_SHIFT 16
#define RG_AFIFO_DUMMY_VALID_PREPARE_NUM_MASK (0xf << 16)
#define RG_AFIFO_DUMMY_VALID_NUM_SHIFT 20
#define RG_AFIFO_DUMMY_VALID_NUM_MASK (0xf << 20)
#define AFIFO_DUMMY_VALID_GAP_NUM_SHIFT 24
#define AFIFO_DUMMY_VALID_GAP_NUM_MASK (0x3f << 24)

#define CDPHY_RX_ANA_DBG_OUT 0x00f8
#define CSI_DEBUG_OUT_SHIFT 0
#define CSI_DEBUG_OUT_MASK (0xffffffff << 0)

#define CDPHY_RX_cdphy_spare_reg 0x00fc
#define RG_CSI0_CDPHY_SPARE_REG_SHIFT 0
#define RG_CSI0_CDPHY_SPARE_REG_MASK (0xffffffff << 0)

#define CDPHY_RX_ASYM_AFIFO_CTRL_0 0x0100
#define L0_AFIFO_FLUSH_EN_SHIFT 0
#define L0_AFIFO_FLUSH_EN_MASK (0x1 << 0)
#define L0_AFIFO_LRTE_DUMMY_VALID_EN_SHIFT 1
#define L0_AFIFO_LRTE_DUMMY_VALID_EN_MASK (0x1 << 1)
#define L0_AFIFO_DUMMY_VALID_USE_FREQ_SHIFT 4
#define L0_AFIFO_DUMMY_VALID_USE_FREQ_MASK (0x1 << 4)
#define L1_AFIFO_FLUSH_EN_SHIFT 8
#define L1_AFIFO_FLUSH_EN_MASK (0x1 << 8)
#define L1_AFIFO_LRTE_DUMMY_VALID_EN_SHIFT 9
#define L1_AFIFO_LRTE_DUMMY_VALID_EN_MASK (0x1 << 9)
#define L1_AFIFO_DUMMY_VALID_USE_FREQ_SHIFT 12
#define L1_AFIFO_DUMMY_VALID_USE_FREQ_MASK (0x1 << 12)
#define L2_AFIFO_FLUSH_EN_SHIFT 16
#define L2_AFIFO_FLUSH_EN_MASK (0x1 << 16)
#define L2_AFIFO_LRTE_DUMMY_VALID_EN_SHIFT 17
#define L2_AFIFO_LRTE_DUMMY_VALID_EN_MASK (0x1 << 17)
#define L2_AFIFO_DUMMY_VALID_USE_FREQ_SHIFT 20
#define L2_AFIFO_DUMMY_VALID_USE_FREQ_MASK (0x1 << 20)

#define CDPHY_RX_ULPS_CTRL_0 0x0110
#define CSI_CDPHY_ULPS_L0_T0_EN_SHIFT 0
#define CSI_CDPHY_ULPS_L0_T0_EN_MASK (0x1 << 0)
#define CSI_CDPHY_ULPS_L0_T0_PN_SWAP_SHIFT 1
#define CSI_CDPHY_ULPS_L0_T0_PN_SWAP_MASK (0x1 << 1)
#define CSI_CDPHY_ULPS_L0_T0_CG_FORCE_ON_SHIFT 4
#define CSI_CDPHY_ULPS_L0_T0_CG_FORCE_ON_MASK (0x1 << 4)
#define CSI_CDPHY_ULPS_L1_EN_SHIFT 8
#define CSI_CDPHY_ULPS_L1_EN_MASK (0x1 << 8)
#define CSI_CDPHY_ULPS_L1_PN_SWAP_SHIFT 9
#define CSI_CDPHY_ULPS_L1_PN_SWAP_MASK (0x1 << 9)
#define CSI_CDPHY_ULPS_L1_CG_FORCE_ON_SHIFT 12
#define CSI_CDPHY_ULPS_L1_CG_FORCE_ON_MASK (0x1 << 12)
#define CSI_CDPHY_ULPS_L2_T1_EN_SHIFT 16
#define CSI_CDPHY_ULPS_L2_T1_EN_MASK (0x1 << 16)
#define CSI_CDPHY_ULPS_L2_T1_PN_SWAP_SHIFT 17
#define CSI_CDPHY_ULPS_L2_T1_PN_SWAP_MASK (0x1 << 17)
#define CSI_CDPHY_ULPS_L2_T1_CG_FORCE_ON_SHIFT 20
#define CSI_CDPHY_ULPS_L2_T1_CG_FORCE_ON_MASK (0x1 << 20)

#define CDPHY_RX_ULPS_CTRL_1 0x0114
#define CSI_ESC_INITIAL_WAIT_CNT_SHIFT 0
#define CSI_ESC_INITIAL_WAIT_CNT_MASK (0xffffffff << 0)

#define CDPHY_RX_ULPS_CTRL_2 0x0118
#define CSI_ESC_CLOCK_SAMPLE_DELAY_SHIFT 0
#define CSI_ESC_CLOCK_SAMPLE_DELAY_MASK (0xffff << 0)
#define CSI_ESC_SAMPLE_DELAY_EN_SHIFT 16
#define CSI_ESC_SAMPLE_DELAY_EN_MASK (0x1 << 16)
#define CSI_ESC_ENTRY_CMD_CNT_SHIFT 20
#define CSI_ESC_ENTRY_CMD_CNT_MASK (0xf << 20)
#define CSI_ESC_LPDT_DATA_CNT_SHIFT 24
#define CSI_ESC_LPDT_DATA_CNT_MASK (0xf << 24)

#define CDPHY_RX_ESC_PAT_0 0x0120
#define CSI_ESC_LPDT_PAT_SHIFT 0
#define CSI_ESC_LPDT_PAT_MASK (0xff << 0)
#define CSI_ESC_ULPS_PAT_SHIFT 8
#define CSI_ESC_ULPS_PAT_MASK (0xff << 8)
#define CSI_ESC_UNDEFINED1_PAT_SHIFT 16
#define CSI_ESC_UNDEFINED1_PAT_MASK (0xff << 16)
#define CSI_ESC_UNDEFINED2_PAT_SHIFT 24
#define CSI_ESC_UNDEFINED2_PAT_MASK (0xff << 24)

#define CDPHY_RX_ESC_PAT_1 0x0124
#define CSI_ESC_RT_PAT_SHIFT 0
#define CSI_ESC_RT_PAT_MASK (0xff << 0)
#define CSI_ESC_EHTM_PAT_SHIFT 8
#define CSI_ESC_EHTM_PAT_MASK (0xff << 8)
#define CSI_ESC_UNKNOWN4_PAT_SHIFT 16
#define CSI_ESC_UNKNOWN4_PAT_MASK (0xff << 16)
#define CSI_ESC_UNKNOWN5_PAT_SHIFT 24
#define CSI_ESC_UNKNOWN5_PAT_MASK (0xff << 24)

#define CDPHY_RX_ESC_STATUS_0A_L0T0 0x0130
#define ULPS_DET_L0T0_ESC_EN_SHIFT 0
#define ULPS_DET_L0T0_ESC_EN_MASK (0x1 << 0)
#define ULPS_DET_L0T0_ESC_CODE_SHIFT 8
#define ULPS_DET_L0T0_ESC_CODE_MASK (0xff << 8)
#define ULPS_DET_L0T0_ULPS_EN_SHIFT 16
#define ULPS_DET_L0T0_ULPS_EN_MASK (0x1 << 16)
#define ULPS_DET_L0T0_ESC_INIT_DONE_SHIFT 17
#define ULPS_DET_L0T0_ESC_INIT_DONE_MASK (0x1 << 17)
#define ULPS_DET_L0T0_ESC_FSM_SHIFT 20
#define ULPS_DET_L0T0_ESC_FSM_MASK (0x3f << 20)

#define CDPHY_RX_ESC_STATUS_0A_L1 0x0134
#define ULPS_DET_L1_ESC_EN_SHIFT 0
#define ULPS_DET_L1_ESC_EN_MASK (0x1 << 0)
#define ULPS_DET_L1_ESC_CODE_SHIFT 8
#define ULPS_DET_L1_ESC_CODE_MASK (0xff << 8)
#define ULPS_DET_L1_ULPS_EN_SHIFT 16
#define ULPS_DET_L1_ULPS_EN_MASK (0x1 << 16)
#define ULPS_DET_L1_ESC_INIT_DONE_SHIFT 17
#define ULPS_DET_L1_ESC_INIT_DONE_MASK (0x1 << 17)
#define ULPS_DET_L1_ESC_FSM_SHIFT 20
#define ULPS_DET_L1_ESC_FSM_MASK (0x3f << 20)

#define CDPHY_RX_ESC_STATUS_0A_L2T1 0x0138
#define ULPS_DET_L2T1_ESC_EN_SHIFT 0
#define ULPS_DET_L2T1_ESC_EN_MASK (0x1 << 0)
#define ULPS_DET_L2T1_ESC_CODE_SHIFT 8
#define ULPS_DET_L2T1_ESC_CODE_MASK (0xff << 8)
#define ULPS_DET_L2T1_ULPS_EN_SHIFT 16
#define ULPS_DET_L2T1_ULPS_EN_MASK (0x1 << 16)
#define ULPS_DET_L2T1_ESC_INIT_DONE_SHIFT 17
#define ULPS_DET_L2T1_ESC_INIT_DONE_MASK (0x1 << 17)
#define ULPS_DET_L2T1_ESC_FSM_SHIFT 20
#define ULPS_DET_L2T1_ESC_FSM_MASK (0x3f << 20)

#define CDPHY_ASYM_AFIFO_FREQ_METER 0x0140
#define RO_ASYM_AFIFO_0A_L0T0_METER_PRD_SHIFT 0
#define RO_ASYM_AFIFO_0A_L0T0_METER_PRD_MASK (0x7f << 0)
#define RO_ASYM_AFIFO_0A_L0T0_METER_VLD_SHIFT 7
#define RO_ASYM_AFIFO_0A_L0T0_METER_VLD_MASK (0x1 << 7)
#define RO_ASYM_AFIFO_0A_L1_METER_PRD_SHIFT 8
#define RO_ASYM_AFIFO_0A_L1_METER_PRD_MASK (0x7f << 8)
#define RO_ASYM_AFIFO_0A_L1_METER_VLD_SHIFT 15
#define RO_ASYM_AFIFO_0A_L1_METER_VLD_MASK (0x1 << 15)
#define RO_ASYM_AFIFO_0A_L2T1_METER_PRD_SHIFT 16
#define RO_ASYM_AFIFO_0A_L2T1_METER_PRD_MASK (0x7f << 16)
#define RO_ASYM_AFIFO_0A_L2T1_METER_VLD_SHIFT 23
#define RO_ASYM_AFIFO_0A_L2T1_METER_VLD_MASK (0x1 << 23)

#define CDPHY_ASYM_AFIFO_FREQ_METER_CTRL 0x0144
#define PRB_PRD_SHIFT 0
#define PRB_PRD_MASK (0xf << 0)

#define ULPS_IRQ_CTRL 0x0150
#define RG_ULPS_IRQ_EN_SHIFT 0
#define RG_ULPS_IRQ_EN_MASK (0xff << 0)
#define RG_ULPS_IRQ_CLR_SHIFT 8
#define RG_ULPS_IRQ_CLR_MASK (0xff << 8)

#define ULPS_IRQ_STATUS 0x0154
#define ULPS_MODE_ENTRY_SHIFT 0
#define ULPS_MODE_ENTRY_MASK (0x1 << 0)
#define ULPS_MODE_EXIT_SHIFT 4
#define ULPS_MODE_EXIT_MASK (0x1 << 4)

#define PMSR_CTRL 0x0160
#define CSI_PMSR_EN_SHIFT 0
#define CSI_PMSR_EN_MASK (0x1 << 0)

#define PMSR_STATE 0x0164
#define L0_T0_HS_SHIFT 0
#define L0_T0_HS_MASK (0x1 << 0)
#define L0_T0_LP_SHIFT 1
#define L0_T0_LP_MASK (0x1 << 1)
#define L0_T0_ULPS_SHIFT 2
#define L0_T0_ULPS_MASK (0x1 << 2)

#endif
