/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */
#ifndef __CONN_SEMAPHORE_REGS_H__
#define __CONN_SEMAPHORE_REGS_H__

#define CONN_SEMAPHORE_BASE                                    0x18070000

#define CONN_SEMAPHORE_CONN_SEMA06_M3_OWN_STA_ADDR             (CONN_SEMAPHORE_BASE + 0x3018)
#define CONN_SEMAPHORE_CONN_SEMA12_M3_OWN_STA_ADDR             (CONN_SEMAPHORE_BASE + 0x3030)
#define CONN_SEMAPHORE_CONN_SEMA06_M3_OWN_REL_ADDR             (CONN_SEMAPHORE_BASE + 0x3218)
#define CONN_SEMAPHORE_CONN_SEMA12_M3_OWN_REL_ADDR             (CONN_SEMAPHORE_BASE + 0x3230)
#define CONN_SEMAPHORE_CONN_SEMA00_M5_OWN_STA_ADDR             (CONN_SEMAPHORE_BASE + 0x5000)
#define CONN_SEMAPHORE_CONN_SEMA00_M5_OWN_REL_ADDR             (CONN_SEMAPHORE_BASE + 0x5200)

#define CONN_SEMAPHORE_CONN_SEMA00_M5_OWN_STA_CONN_SEMA00_M5_OWN_STA_ADDR CONN_SEMAPHORE_CONN_SEMA00_M5_OWN_STA_ADDR
#define CONN_SEMAPHORE_CONN_SEMA00_M5_OWN_STA_CONN_SEMA00_M5_OWN_STA_MASK 0x00000001
#define CONN_SEMAPHORE_CONN_SEMA00_M5_OWN_STA_CONN_SEMA00_M5_OWN_STA_SHFT 0

#define CONN_SEMAPHORE_CONN_SEMA06_M3_OWN_STA_CONN_SEMA06_M3_OWN_STA_ADDR CONN_SEMAPHORE_CONN_SEMA06_M3_OWN_STA_ADDR
#define CONN_SEMAPHORE_CONN_SEMA06_M3_OWN_STA_CONN_SEMA06_M3_OWN_STA_MASK 0x00000003
#define CONN_SEMAPHORE_CONN_SEMA06_M3_OWN_STA_CONN_SEMA06_M3_OWN_STA_SHFT 0

#define CONN_SEMAPHORE_CONN_SEMA12_M3_OWN_STA_CONN_SEMA12_M3_OWN_STA_ADDR CONN_SEMAPHORE_CONN_SEMA12_M3_OWN_STA_ADDR
#define CONN_SEMAPHORE_CONN_SEMA12_M3_OWN_STA_CONN_SEMA12_M3_OWN_STA_MASK 0x00000003
#define CONN_SEMAPHORE_CONN_SEMA12_M3_OWN_STA_CONN_SEMA12_M3_OWN_STA_SHFT 0

#define CONN_SEMAPHORE_CONN_SEMA00_M5_OWN_REL_CONN_SEMA00_M5_OWN_REL_ADDR CONN_SEMAPHORE_CONN_SEMA00_M5_OWN_REL_ADDR
#define CONN_SEMAPHORE_CONN_SEMA00_M5_OWN_REL_CONN_SEMA00_M5_OWN_REL_MASK 0x00000001
#define CONN_SEMAPHORE_CONN_SEMA00_M5_OWN_REL_CONN_SEMA00_M5_OWN_REL_SHFT 0

#define CONN_SEMAPHORE_CONN_SEMA06_M3_OWN_REL_CONN_SEMA06_M3_OWN_REL_ADDR CONN_SEMAPHORE_CONN_SEMA06_M3_OWN_REL_ADDR
#define CONN_SEMAPHORE_CONN_SEMA06_M3_OWN_REL_CONN_SEMA06_M3_OWN_REL_MASK 0x00000001
#define CONN_SEMAPHORE_CONN_SEMA06_M3_OWN_REL_CONN_SEMA06_M3_OWN_REL_SHFT 0

#define CONN_SEMAPHORE_CONN_SEMA12_M3_OWN_REL_CONN_SEMA12_M3_OWN_REL_ADDR CONN_SEMAPHORE_CONN_SEMA12_M3_OWN_REL_ADDR
#define CONN_SEMAPHORE_CONN_SEMA12_M3_OWN_REL_CONN_SEMA12_M3_OWN_REL_MASK 0x00000001
#define CONN_SEMAPHORE_CONN_SEMA12_M3_OWN_REL_CONN_SEMA12_M3_OWN_REL_SHFT 0

#endif /* __CONN_SEMAPHORE_REGS_H__ */

