/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */

#ifndef __CONN_VDNR_GEN_ON_DEBUG_CTRL_AO_REGS_H__
#define __CONN_VDNR_GEN_ON_DEBUG_CTRL_AO_REGS_H__

#define CONN_VDNR_GEN_ON_DEBUG_CTRL_AO_BASE                    0x1800F000

#define CONN_VDNR_GEN_ON_DEBUG_CTRL_AO_CONN_INFRA_VDNR_GEN_ON_U_DEBUG_CTRL_AO_CONN_INFRA_ON_RESULT2_ADDR \
			(CONN_VDNR_GEN_ON_DEBUG_CTRL_AO_BASE + 0x408)
#define CONN_VDNR_GEN_ON_DEBUG_CTRL_AO_CONN_INFRA_VDNR_GEN_ON_U_DEBUG_CTRL_AO_CONN_INFRA_ON_RESULT3_ADDR \
			(CONN_VDNR_GEN_ON_DEBUG_CTRL_AO_BASE + 0x40C)
#define CONN_VDNR_GEN_ON_DEBUG_CTRL_AO_CONN_INFRA_VDNR_GEN_ON_U_DEBUG_CTRL_AO_CONN_INFRA_ON_RESULT4_ADDR \
			(CONN_VDNR_GEN_ON_DEBUG_CTRL_AO_BASE + 0x410)
#define CONN_VDNR_GEN_ON_DEBUG_CTRL_AO_CONN_INFRA_VDNR_GEN_ON_U_DEBUG_CTRL_AO_CONN_INFRA_ON_RESULT5_ADDR \
			(CONN_VDNR_GEN_ON_DEBUG_CTRL_AO_BASE + 0x414)
#define CONN_VDNR_GEN_ON_DEBUG_CTRL_AO_CONN_INFRA_VDNR_GEN_ON_U_DEBUG_CTRL_AO_CONN_INFRA_ON_RESULT6_ADDR \
			(CONN_VDNR_GEN_ON_DEBUG_CTRL_AO_BASE + 0x418)
#define CONN_VDNR_GEN_ON_DEBUG_CTRL_AO_CONN_INFRA_VDNR_GEN_ON_U_DEBUG_CTRL_AO_CONN_INFRA_ON_RESULT7_ADDR \
			(CONN_VDNR_GEN_ON_DEBUG_CTRL_AO_BASE + 0x41C)
#define CONN_VDNR_GEN_ON_DEBUG_CTRL_AO_CONN_INFRA_VDNR_GEN_ON_U_DEBUG_CTRL_AO_CONN_INFRA_ON_RESULT8_ADDR \
			(CONN_VDNR_GEN_ON_DEBUG_CTRL_AO_BASE + 0x420)
#define CONN_VDNR_GEN_ON_DEBUG_CTRL_AO_CONN_INFRA_VDNR_GEN_ON_U_DEBUG_CTRL_AO_CONN_INFRA_ON_RESULT9_ADDR \
			(CONN_VDNR_GEN_ON_DEBUG_CTRL_AO_BASE + 0x424)
#define CONN_VDNR_GEN_ON_DEBUG_CTRL_AO_CONN_INFRA_VDNR_GEN_ON_U_DEBUG_CTRL_AO_CONN_INFRA_ON_RESULT10_ADDR \
			(CONN_VDNR_GEN_ON_DEBUG_CTRL_AO_BASE + 0x428)
#define CONN_VDNR_GEN_ON_DEBUG_CTRL_AO_CONN_INFRA_VDNR_GEN_ON_U_DEBUG_CTRL_AO_CONN_INFRA_ON_RESULT11_ADDR \
			(CONN_VDNR_GEN_ON_DEBUG_CTRL_AO_BASE + 0x42C)
#define CONN_VDNR_GEN_ON_DEBUG_CTRL_AO_CONN_INFRA_VDNR_GEN_ON_U_DEBUG_CTRL_AO_CONN_INFRA_ON_RESULT12_ADDR \
			(CONN_VDNR_GEN_ON_DEBUG_CTRL_AO_BASE + 0x430)

#endif /*__CONN_VDNR_GEN_ON_DEBUG_CTRL_AO_REGS_H__*/
