/* SPDX-License-Identifier: BSD-2-Clause */
//[File]            : vlp_uds_ctrl.h
//[Revision time]   : Mon Oct 30 22:49:27 2023
//[Description]     : This file is auto generated by CODA
//[Copyright]       : Copyright (C) 2023 Mediatek Incorportion. All rights reserved.

#ifndef __VLP_UDS_CTRL_REGS_H__
#define __VLP_UDS_CTRL_REGS_H__

#include "hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif


//****************************************************************************
//
//                     VLP_UDS_CTRL CR Definitions                     
//
//****************************************************************************

#define VLP_UDS_CTRL_BASE                                      0x70003000u

#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_ADDR                      (VLP_UDS_CTRL_BASE + 0x000u) // 3000
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL1_ADDR                      (VLP_UDS_CTRL_BASE + 0x004u) // 3004
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL2_ADDR                      (VLP_UDS_CTRL_BASE + 0x008u) // 3008
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL3_ADDR                      (VLP_UDS_CTRL_BASE + 0x00Cu) // 300C
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL4_ADDR                      (VLP_UDS_CTRL_BASE + 0x010u) // 3010
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL5_ADDR                      (VLP_UDS_CTRL_BASE + 0x014u) // 3014
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL6_ADDR                      (VLP_UDS_CTRL_BASE + 0x018u) // 3018
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL7_ADDR                      (VLP_UDS_CTRL_BASE + 0x01cu) // 301C
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL8_ADDR                      (VLP_UDS_CTRL_BASE + 0x020u) // 3020
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_ADDR                      (VLP_UDS_CTRL_BASE + 0x024u) // 3024
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL10_ADDR                     (VLP_UDS_CTRL_BASE + 0x028u) // 3028
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL12_ADDR                     (VLP_UDS_CTRL_BASE + 0x030u) // 3030
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL13_ADDR                     (VLP_UDS_CTRL_BASE + 0x034u) // 3034
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL14_ADDR                     (VLP_UDS_CTRL_BASE + 0x038u) // 3038
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL15_ADDR                     (VLP_UDS_CTRL_BASE + 0x03cu) // 303C
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL16_ADDR                     (VLP_UDS_CTRL_BASE + 0x040u) // 3040
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL17_ADDR                     (VLP_UDS_CTRL_BASE + 0x044u) // 3044
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL18_ADDR                     (VLP_UDS_CTRL_BASE + 0x048u) // 3048
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL19_ADDR                     (VLP_UDS_CTRL_BASE + 0x04cu) // 304C
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL20_ADDR                     (VLP_UDS_CTRL_BASE + 0x050u) // 3050
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL21_ADDR                     (VLP_UDS_CTRL_BASE + 0x054u) // 3054
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_ADDR                        (VLP_UDS_CTRL_BASE + 0x100u) // 3100
#define VLP_UDS_CTRL_CBTOP_ADIE_UDS_RDY_RD_ADDR                (VLP_UDS_CTRL_BASE + 0x104u) // 3104
#define VLP_UDS_CTRL_CBTOP_OSCRDY_CNT_RD_ADDR                  (VLP_UDS_CTRL_BASE + 0x108u) // 3108




/* =====================================================================================

  ---CBTOP_UDS_CTRL0 (0x70003000 + 0x000u)---

    CR_TOP_ACTIVE[0]             - (RW) CBTOP_ACTIVE
                                     0: cbtop not active when sleep(deep sleep)
                                     1 : cbtop  active when sleep(legacy sleep)
    CR_TOP_HW_CTRL[1]            - (RW) HW Control
                                     0 : disable slp ctrl
                                     1 : enable slp ctrl
    CR_SLP_RS_EN[2]              - (RW) cr_slp_rs_en
                                     0 :  disable cr_slp_rs_en (for cmdbt)
                                     1 :  enable cr_slp_rs_en (for cmdbt)
    CR_SLP_BK_EN[3]              - (RW) cr_slp_bk_en
                                     0 :  disable cr_slp_bk_en (for cmdbt)
                                     1 :  enable cr_slp_bk_en (for cmdbt)
    CR_RS_DONE_SYNC[4]           - (RW) 0 :cmdbt rs done signal not sync 2T to f32k domain FSM
                                     1 : cmdbt rs done signal will sync 2T to f32k domain FSM
    CR_BK_DONE_SYNC[5]           - (RW) 0 :cmdbt bk done signal not sync 2T to f32k domain FSM
                                     1 : cmdbt bk done signal will sync 2T to f32k domain FSM
    RESERVED6[7..6]              - (RO) Reserved bits
    CR_ADIE_UDS_RDY_MASK[8]      - (RW) 0 : top sleep FSM monitor adie_uds_rdy
                                     1 : top sleep FSM sleep bypass adie_uds_rdy
    CR_TOP_IO_LAT_BYPASS[9]      - (RW) 0 : top sleep FSM do IO value latch and iso
                                     1 :top sleep FSM bypass IO value latch and iso
    CR_TOP_AO_RS_BYPASS[10]      - (RW) 0 : top sleep FSM do AO domain CR restore
                                     1 :top sleep FSM bypass AO domain CR restore
    CR_TOP_AO_BK_BYPASS[11]      - (RW) 0 : top sleep FSM do AO domain CR backup
                                     1 :top sleep FSM bypass AO domain CR backup
    CR_UDS_ELS_EN[12]            - (RW) 0 : top sleep FSM bypass AO domain ISO
                                     1 :top sleep FSM enable AO domain ISO
    CR_TOP_AON_RST_EN[13]        - (RW) 0 : top sleep FSM bypass AO domain RST
                                     1 :top sleep FSM enable AO domain RST
    CR_PMIC_UDS_EN_EN[14]        - (RW) 0 : top sleep FSM bypass PMIC uds mode
                                     1 : top sleep FSM enable PMIC uds mode
    CR_UDS_AIP_RST_EN[15]        - (RW) 0 : top sleep FSM bypass AIP reset
                                     1 : top sleep FSM enable AIP reset
    CR_TOP_ULPOSC_REQ_FORCE[16]  - (RW) 0: top ulposc req pull low when sleep
                                     1: force top ulposc req pull high when sleep
    CR_ADIE_UDS_RDY_SYNC[17]     - (RW) 0: top sleep FSM wait adie_uds_rdy without sync at state RST_STAT
                                     1: top sleep FSM wait adie_uds_rdy at state CMDBT_BK
    CR_EFUSE_S2P_RDY_BYPASS[18]  - (RW) 0: top sleep FSM wait efuse_s2p_rdy at state CMDBT_RS
                                     1: top sleep FSM bypass efuse_s2p_rdy
    CR_TOP_MEM_LAT_BYPASS[19]    - (RW) 0: top sleep FSM do mem aociso/aoclhenb/sleepb/isointb/pd
                                     1: top sleep FSM bypass mem control
    CR_TOP_XO_REQ_FORCE[20]      - (RW) 0: top xtal req pull low when sleep
                                     1: force top xtal req pull high when sleep
    CR_XO_CLK_SEL[21]            - (RW) 0: top clk req for ulposc
                                     1: top clk req for xtal
    CR_ULPOSC_DYN_OFF_MODE[22]   - (RW) 0: enable ulposc dynamic off mode
                                     1: disable ulposc dynamic off mode
    RESERVED23[31..23]           - (RO) Reserved bits

 =====================================================================================*/
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_ULPOSC_DYN_OFF_MODE_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL0_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_ULPOSC_DYN_OFF_MODE_MASK 0x00400000u                // CR_ULPOSC_DYN_OFF_MODE[22]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_ULPOSC_DYN_OFF_MODE_SHFT 22u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_XO_CLK_SEL_ADDR        VLP_UDS_CTRL_CBTOP_UDS_CTRL0_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_XO_CLK_SEL_MASK        0x00200000u                // CR_XO_CLK_SEL[21]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_XO_CLK_SEL_SHFT        21u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_TOP_XO_REQ_FORCE_ADDR  VLP_UDS_CTRL_CBTOP_UDS_CTRL0_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_TOP_XO_REQ_FORCE_MASK  0x00100000u                // CR_TOP_XO_REQ_FORCE[20]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_TOP_XO_REQ_FORCE_SHFT  20u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_TOP_MEM_LAT_BYPASS_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL0_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_TOP_MEM_LAT_BYPASS_MASK 0x00080000u                // CR_TOP_MEM_LAT_BYPASS[19]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_TOP_MEM_LAT_BYPASS_SHFT 19u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_EFUSE_S2P_RDY_BYPASS_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL0_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_EFUSE_S2P_RDY_BYPASS_MASK 0x00040000u                // CR_EFUSE_S2P_RDY_BYPASS[18]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_EFUSE_S2P_RDY_BYPASS_SHFT 18u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_ADIE_UDS_RDY_SYNC_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL0_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_ADIE_UDS_RDY_SYNC_MASK 0x00020000u                // CR_ADIE_UDS_RDY_SYNC[17]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_ADIE_UDS_RDY_SYNC_SHFT 17u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_TOP_ULPOSC_REQ_FORCE_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL0_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_TOP_ULPOSC_REQ_FORCE_MASK 0x00010000u                // CR_TOP_ULPOSC_REQ_FORCE[16]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_TOP_ULPOSC_REQ_FORCE_SHFT 16u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_UDS_AIP_RST_EN_ADDR    VLP_UDS_CTRL_CBTOP_UDS_CTRL0_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_UDS_AIP_RST_EN_MASK    0x00008000u                // CR_UDS_AIP_RST_EN[15]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_UDS_AIP_RST_EN_SHFT    15u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_PMIC_UDS_EN_EN_ADDR    VLP_UDS_CTRL_CBTOP_UDS_CTRL0_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_PMIC_UDS_EN_EN_MASK    0x00004000u                // CR_PMIC_UDS_EN_EN[14]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_PMIC_UDS_EN_EN_SHFT    14u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_TOP_AON_RST_EN_ADDR    VLP_UDS_CTRL_CBTOP_UDS_CTRL0_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_TOP_AON_RST_EN_MASK    0x00002000u                // CR_TOP_AON_RST_EN[13]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_TOP_AON_RST_EN_SHFT    13u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_UDS_ELS_EN_ADDR        VLP_UDS_CTRL_CBTOP_UDS_CTRL0_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_UDS_ELS_EN_MASK        0x00001000u                // CR_UDS_ELS_EN[12]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_UDS_ELS_EN_SHFT        12u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_TOP_AO_BK_BYPASS_ADDR  VLP_UDS_CTRL_CBTOP_UDS_CTRL0_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_TOP_AO_BK_BYPASS_MASK  0x00000800u                // CR_TOP_AO_BK_BYPASS[11]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_TOP_AO_BK_BYPASS_SHFT  11u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_TOP_AO_RS_BYPASS_ADDR  VLP_UDS_CTRL_CBTOP_UDS_CTRL0_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_TOP_AO_RS_BYPASS_MASK  0x00000400u                // CR_TOP_AO_RS_BYPASS[10]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_TOP_AO_RS_BYPASS_SHFT  10u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_TOP_IO_LAT_BYPASS_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL0_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_TOP_IO_LAT_BYPASS_MASK 0x00000200u                // CR_TOP_IO_LAT_BYPASS[9]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_TOP_IO_LAT_BYPASS_SHFT 9u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_ADIE_UDS_RDY_MASK_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL0_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_ADIE_UDS_RDY_MASK_MASK 0x00000100u                // CR_ADIE_UDS_RDY_MASK[8]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_ADIE_UDS_RDY_MASK_SHFT 8u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_BK_DONE_SYNC_ADDR      VLP_UDS_CTRL_CBTOP_UDS_CTRL0_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_BK_DONE_SYNC_MASK      0x00000020u                // CR_BK_DONE_SYNC[5]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_BK_DONE_SYNC_SHFT      5u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_RS_DONE_SYNC_ADDR      VLP_UDS_CTRL_CBTOP_UDS_CTRL0_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_RS_DONE_SYNC_MASK      0x00000010u                // CR_RS_DONE_SYNC[4]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_RS_DONE_SYNC_SHFT      4u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_SLP_BK_EN_ADDR         VLP_UDS_CTRL_CBTOP_UDS_CTRL0_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_SLP_BK_EN_MASK         0x00000008u                // CR_SLP_BK_EN[3]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_SLP_BK_EN_SHFT         3u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_SLP_RS_EN_ADDR         VLP_UDS_CTRL_CBTOP_UDS_CTRL0_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_SLP_RS_EN_MASK         0x00000004u                // CR_SLP_RS_EN[2]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_SLP_RS_EN_SHFT         2u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_TOP_HW_CTRL_ADDR       VLP_UDS_CTRL_CBTOP_UDS_CTRL0_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_TOP_HW_CTRL_MASK       0x00000002u                // CR_TOP_HW_CTRL[1]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_TOP_HW_CTRL_SHFT       1u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_TOP_ACTIVE_ADDR        VLP_UDS_CTRL_CBTOP_UDS_CTRL0_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_TOP_ACTIVE_MASK        0x00000001u                // CR_TOP_ACTIVE[0]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL0_CR_TOP_ACTIVE_SHFT        0u

/* =====================================================================================

  ---CBTOP_UDS_CTRL1 (0x70003000 + 0x004u)---

    CR_CONNSYS_UDS_POWR_OFF_TOP_EN[0] - (RW) CONNSYS UDS Power Off Cbtop Enable
                                     0 : CONNSYS UDS can not let cbtop enter sleep
                                     1 : CONNSYS UDS can let cbtop enter sleep
    CR_CB_INFRA_POWR_OFF_TOP_EN[1] - (RW) CB_INFRA Power Off Cbtop Enable
                                     0 : can not let cbtop enter sleep
                                     1 : can let cbtop enter sleep
    CR_CONNSYS_DSLP_POWR_OFF_TOP_EN[2] - (RW) CONNSYS DSLP Power Off Cbtop Enable
                                     0 : CONNSYS DSLP can not let cbtop enter sleep
                                     1 : CONNSYS DSLP can let cbtop enter sleep
    RESERVED3[3]                 - (RO) Reserved bits
    CR_CONN_PREVENT_SLP_POWER_OFF_TOP_EN[4] - (RW) PREVENT_SLP Power Off Cbtop Enable
                                     0 : can not let cbtop enter sleep
                                     1 : can let cbtop enter sleep
    CR_XO_REQ_POWER_OFF_TOP_EN[5] - (RW) XO_REQ cmd Power Off Cbtop Enable
                                     0 : PLL_SW_REQ cmd can not let cbtop enter sleep
                                     1 : PLL_SW_REQ cmd can let cbtop enter sleep
    RESERVED6[6]                 - (RO) Reserved bits
    CR_TOP_POWER_OFF_TOP_EN[7]   - (RW) TOP Power Off Cbtop Enable
                                     0 : TOP can not let cbtop enter sleep
                                     1 : TOP can let cbtop enter sleep
    RESERVED8[31..8]             - (RO) Reserved bits

 =====================================================================================*/
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL1_CR_TOP_POWER_OFF_TOP_EN_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL1_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL1_CR_TOP_POWER_OFF_TOP_EN_MASK 0x00000080u                // CR_TOP_POWER_OFF_TOP_EN[7]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL1_CR_TOP_POWER_OFF_TOP_EN_SHFT 7u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL1_CR_XO_REQ_POWER_OFF_TOP_EN_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL1_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL1_CR_XO_REQ_POWER_OFF_TOP_EN_MASK 0x00000020u                // CR_XO_REQ_POWER_OFF_TOP_EN[5]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL1_CR_XO_REQ_POWER_OFF_TOP_EN_SHFT 5u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL1_CR_CONN_PREVENT_SLP_POWER_OFF_TOP_EN_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL1_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL1_CR_CONN_PREVENT_SLP_POWER_OFF_TOP_EN_MASK 0x00000010u                // CR_CONN_PREVENT_SLP_POWER_OFF_TOP_EN[4]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL1_CR_CONN_PREVENT_SLP_POWER_OFF_TOP_EN_SHFT 4u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL1_CR_CONNSYS_DSLP_POWR_OFF_TOP_EN_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL1_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL1_CR_CONNSYS_DSLP_POWR_OFF_TOP_EN_MASK 0x00000004u                // CR_CONNSYS_DSLP_POWR_OFF_TOP_EN[2]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL1_CR_CONNSYS_DSLP_POWR_OFF_TOP_EN_SHFT 2u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL1_CR_CB_INFRA_POWR_OFF_TOP_EN_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL1_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL1_CR_CB_INFRA_POWR_OFF_TOP_EN_MASK 0x00000002u                // CR_CB_INFRA_POWR_OFF_TOP_EN[1]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL1_CR_CB_INFRA_POWR_OFF_TOP_EN_SHFT 1u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL1_CR_CONNSYS_UDS_POWR_OFF_TOP_EN_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL1_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL1_CR_CONNSYS_UDS_POWR_OFF_TOP_EN_MASK 0x00000001u                // CR_CONNSYS_UDS_POWR_OFF_TOP_EN[0]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL1_CR_CONNSYS_UDS_POWR_OFF_TOP_EN_SHFT 0u

/* =====================================================================================

  ---CBTOP_UDS_CTRL2 (0x70003000 + 0x008u)---

    CR_CONNSYS_UDS_POWR_ON_TOP_EN[0] - (RW) CONNSYS UDS Power On Cbtop Enable
                                     0 : CONNSYS UDS can not wake cbtop
                                     1 : CONNSYS UDS can wake cbtop
    CR_CB_INFRA_POWR_ON_TOP_EN[1] - (RW) CB_INFRA Power On Cbtop Enable
                                     0 : CB_INFRA can not wake cbtop
                                     1 : CB_INFRA can wake cbtop
    CR_CONNSYS_DSLP_POWR_ON_TOP_EN[2] - (RW) CONNSYS DSLP Power On Cbtop Enable
                                     0 : CB_INFRA can not wake cbtop
                                     1 : CB_INFRA can wake cbtop
    RESERVED3[4..3]              - (RO) Reserved bits
    CR_XO_REQ_POWER_ON_TOP_EN[5] - (RW) XO_REQ Power On Cbtop Enable
                                     0 : can not wake cbtop
                                     1 : can wake cbtop
    RESERVED6[6]                 - (RO) Reserved bits
    CR_TOP_POWER_ON_TOP_EN[7]    - (RW) TOP Power On Cbtop Enable
                                     0 : TOP can not wake cbtop
                                     1 : TOP can wake cbtop
    RESERVED8[31..8]             - (RO) Reserved bits

 =====================================================================================*/
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL2_CR_TOP_POWER_ON_TOP_EN_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL2_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL2_CR_TOP_POWER_ON_TOP_EN_MASK 0x00000080u                // CR_TOP_POWER_ON_TOP_EN[7]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL2_CR_TOP_POWER_ON_TOP_EN_SHFT 7u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL2_CR_XO_REQ_POWER_ON_TOP_EN_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL2_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL2_CR_XO_REQ_POWER_ON_TOP_EN_MASK 0x00000020u                // CR_XO_REQ_POWER_ON_TOP_EN[5]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL2_CR_XO_REQ_POWER_ON_TOP_EN_SHFT 5u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL2_CR_CONNSYS_DSLP_POWR_ON_TOP_EN_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL2_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL2_CR_CONNSYS_DSLP_POWR_ON_TOP_EN_MASK 0x00000004u                // CR_CONNSYS_DSLP_POWR_ON_TOP_EN[2]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL2_CR_CONNSYS_DSLP_POWR_ON_TOP_EN_SHFT 2u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL2_CR_CB_INFRA_POWR_ON_TOP_EN_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL2_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL2_CR_CB_INFRA_POWR_ON_TOP_EN_MASK 0x00000002u                // CR_CB_INFRA_POWR_ON_TOP_EN[1]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL2_CR_CB_INFRA_POWR_ON_TOP_EN_SHFT 1u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL2_CR_CONNSYS_UDS_POWR_ON_TOP_EN_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL2_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL2_CR_CONNSYS_UDS_POWR_ON_TOP_EN_MASK 0x00000001u                // CR_CONNSYS_UDS_POWR_ON_TOP_EN[0]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL2_CR_CONNSYS_UDS_POWR_ON_TOP_EN_SHFT 0u

/* =====================================================================================

  ---CBTOP_UDS_CTRL3 (0x70003000 + 0x00Cu)---

    CR_TOP_SLP_FSM_TIMEOUT_EN[8..0] - (RW) FSM1~9 TIMEOUT_EN
    RESERVED9[15..9]             - (RO) Reserved bits
    CR_XO_ULPOSC_SWITCH_TIMEOUT[19..16] - (RW)  xxx 
    RESERVED20[26..20]           - (RO) Reserved bits
    CR_ADIE_UDS_TIMEOUT_SET[30..27] - (RW) Unused in uds_vlp_ctrl
    CR_ADIE_UDS_TIMEOUT_EN[31]   - (RW) Unused in uds_vlp_ctrl

 =====================================================================================*/
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL3_CR_ADIE_UDS_TIMEOUT_EN_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL3_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL3_CR_ADIE_UDS_TIMEOUT_EN_MASK 0x80000000u                // CR_ADIE_UDS_TIMEOUT_EN[31]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL3_CR_ADIE_UDS_TIMEOUT_EN_SHFT 31u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL3_CR_ADIE_UDS_TIMEOUT_SET_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL3_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL3_CR_ADIE_UDS_TIMEOUT_SET_MASK 0x78000000u                // CR_ADIE_UDS_TIMEOUT_SET[30..27]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL3_CR_ADIE_UDS_TIMEOUT_SET_SHFT 27u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL3_CR_XO_ULPOSC_SWITCH_TIMEOUT_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL3_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL3_CR_XO_ULPOSC_SWITCH_TIMEOUT_MASK 0x000F0000u                // CR_XO_ULPOSC_SWITCH_TIMEOUT[19..16]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL3_CR_XO_ULPOSC_SWITCH_TIMEOUT_SHFT 16u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL3_CR_TOP_SLP_FSM_TIMEOUT_EN_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL3_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL3_CR_TOP_SLP_FSM_TIMEOUT_EN_MASK 0x000001FFu                // CR_TOP_SLP_FSM_TIMEOUT_EN[8..0]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL3_CR_TOP_SLP_FSM_TIMEOUT_EN_SHFT 0u

/* =====================================================================================

  ---CBTOP_UDS_CTRL4 (0x70003000 + 0x010u)---

    CR_TOP_VON_BK_TIMEOUT[3..0]  - (RW)  xxx 
    CR_ULPOSC_OFF_TIMEOUT[7..4]  - (RW)  xxx 
    CR_RST_STAT_TIMEOUT[11..8]   - (RW)  xxx 
    CR_PMIC_IN_UDS_TIMEOUT[15..12] - (RW)  xxx 
    CR_PMIC_EXT_UDS_TIMEOUT[19..16] - (RW)  xxx 
    CR_DIS_RST_STAT_TIMEOUT[23..20] - (RW)  xxx 
    CR_ULPOSC_ON_TIMEOUT[27..24] - (RW)  xxx 
    CR_TOP_VON_RS_TIMEOUT[31..28] - (RW)  xxx 

 =====================================================================================*/
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL4_CR_TOP_VON_RS_TIMEOUT_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL4_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL4_CR_TOP_VON_RS_TIMEOUT_MASK 0xF0000000u                // CR_TOP_VON_RS_TIMEOUT[31..28]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL4_CR_TOP_VON_RS_TIMEOUT_SHFT 28u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL4_CR_ULPOSC_ON_TIMEOUT_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL4_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL4_CR_ULPOSC_ON_TIMEOUT_MASK 0x0F000000u                // CR_ULPOSC_ON_TIMEOUT[27..24]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL4_CR_ULPOSC_ON_TIMEOUT_SHFT 24u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL4_CR_DIS_RST_STAT_TIMEOUT_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL4_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL4_CR_DIS_RST_STAT_TIMEOUT_MASK 0x00F00000u                // CR_DIS_RST_STAT_TIMEOUT[23..20]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL4_CR_DIS_RST_STAT_TIMEOUT_SHFT 20u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL4_CR_PMIC_EXT_UDS_TIMEOUT_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL4_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL4_CR_PMIC_EXT_UDS_TIMEOUT_MASK 0x000F0000u                // CR_PMIC_EXT_UDS_TIMEOUT[19..16]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL4_CR_PMIC_EXT_UDS_TIMEOUT_SHFT 16u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL4_CR_PMIC_IN_UDS_TIMEOUT_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL4_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL4_CR_PMIC_IN_UDS_TIMEOUT_MASK 0x0000F000u                // CR_PMIC_IN_UDS_TIMEOUT[15..12]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL4_CR_PMIC_IN_UDS_TIMEOUT_SHFT 12u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL4_CR_RST_STAT_TIMEOUT_ADDR  VLP_UDS_CTRL_CBTOP_UDS_CTRL4_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL4_CR_RST_STAT_TIMEOUT_MASK  0x00000F00u                // CR_RST_STAT_TIMEOUT[11..8]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL4_CR_RST_STAT_TIMEOUT_SHFT  8u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL4_CR_ULPOSC_OFF_TIMEOUT_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL4_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL4_CR_ULPOSC_OFF_TIMEOUT_MASK 0x000000F0u                // CR_ULPOSC_OFF_TIMEOUT[7..4]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL4_CR_ULPOSC_OFF_TIMEOUT_SHFT 4u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL4_CR_TOP_VON_BK_TIMEOUT_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL4_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL4_CR_TOP_VON_BK_TIMEOUT_MASK 0x0000000Fu                // CR_TOP_VON_BK_TIMEOUT[3..0]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL4_CR_TOP_VON_BK_TIMEOUT_SHFT 0u

/* =====================================================================================

  ---CBTOP_UDS_CTRL5 (0x70003000 + 0x014u)---

    cr_slp_cnt[11..0]            - (RO) count times of cbtop slp
    RESERVED12[13..12]           - (RO) Reserved bits
    cr_slp_period_en[14]         - (RW) 0 : Disable slp_period counter
                                     1 : Enable slp_period counter
    cr_slp_cnt_en[15]            - (RW) 0 : Disable slp_times counter
                                     1 : Enable slp_times counter
    cr_top_cmdbt_pulse_cnt[19..16] - (RW) 0 : Disable slp_times counter
                                     1 : Enable slp_times counter
    RESERVED20[31..20]           - (RO) Reserved bits

 =====================================================================================*/
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL5_cr_top_cmdbt_pulse_cnt_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL5_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL5_cr_top_cmdbt_pulse_cnt_MASK 0x000F0000u                // cr_top_cmdbt_pulse_cnt[19..16]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL5_cr_top_cmdbt_pulse_cnt_SHFT 16u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL5_cr_slp_cnt_en_ADDR        VLP_UDS_CTRL_CBTOP_UDS_CTRL5_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL5_cr_slp_cnt_en_MASK        0x00008000u                // cr_slp_cnt_en[15]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL5_cr_slp_cnt_en_SHFT        15u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL5_cr_slp_period_en_ADDR     VLP_UDS_CTRL_CBTOP_UDS_CTRL5_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL5_cr_slp_period_en_MASK     0x00004000u                // cr_slp_period_en[14]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL5_cr_slp_period_en_SHFT     14u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL5_cr_slp_cnt_ADDR           VLP_UDS_CTRL_CBTOP_UDS_CTRL5_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL5_cr_slp_cnt_MASK           0x00000FFFu                // cr_slp_cnt[11..0]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL5_cr_slp_cnt_SHFT           0u

/* =====================================================================================

  ---CBTOP_UDS_CTRL6 (0x70003000 + 0x018u)---

    cr_slp_period[31..0]         - (RO) count the total period cbtop enter slp

 =====================================================================================*/
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL6_cr_slp_period_ADDR        VLP_UDS_CTRL_CBTOP_UDS_CTRL6_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL6_cr_slp_period_MASK        0xFFFFFFFFu                // cr_slp_period[31..0]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL6_cr_slp_period_SHFT        0u

/* =====================================================================================

  ---CBTOP_UDS_CTRL7 (0x70003000 + 0x01cu)---

    cr_cbtop_slp_rsv2[31..0]     - (RW) [9] enable restore_OSC_CALI SW mode, [8:0] value of restore_OSC_CALI SW mode

 =====================================================================================*/
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL7_cr_cbtop_slp_rsv2_ADDR    VLP_UDS_CTRL_CBTOP_UDS_CTRL7_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL7_cr_cbtop_slp_rsv2_MASK    0xFFFFFFFFu                // cr_cbtop_slp_rsv2[31..0]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL7_cr_cbtop_slp_rsv2_SHFT    0u

/* =====================================================================================

  ---CBTOP_UDS_CTRL8 (0x70003000 + 0x020u)---

    CR_TOP_UDS_CTRL_DEBUG_SEL_0[7..0] - (RW)  xxx 
    CR_TOP_UDS_CTRL_DEBUG_SEL_1[15..8] - (RW)  xxx 
    RESERVED16[31..16]           - (RO) Reserved bits

 =====================================================================================*/
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL8_CR_TOP_UDS_CTRL_DEBUG_SEL_1_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL8_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL8_CR_TOP_UDS_CTRL_DEBUG_SEL_1_MASK 0x0000FF00u                // CR_TOP_UDS_CTRL_DEBUG_SEL_1[15..8]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL8_CR_TOP_UDS_CTRL_DEBUG_SEL_1_SHFT 8u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL8_CR_TOP_UDS_CTRL_DEBUG_SEL_0_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL8_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL8_CR_TOP_UDS_CTRL_DEBUG_SEL_0_MASK 0x000000FFu                // CR_TOP_UDS_CTRL_DEBUG_SEL_0[7..0]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL8_CR_TOP_UDS_CTRL_DEBUG_SEL_0_SHFT 0u

/* =====================================================================================

  ---CBTOP_UDS_CTRL9 (0x70003000 + 0x024u)---

    RESERVED0[9..0]              - (RO) Reserved bits
    RGU_CB_INFRA_POWERMONITOR_SWCTL_ISOINT[10] - (RW)  xxx 
    RGU_CB_INFRA_POWERMONITOR_SWCTL_SLP[11] - (RW)  xxx 
    RGU_CB_INFRA_POWERMONITOR_SWCTL_PDN[12] - (RW)  xxx 
    RGU_CB_INFRA_POWERMONITOR_HWCTL_SLP[13] - (RW)  xxx 
    RGU_CB_INFRA_POWERMONITOR_HWCTL_PDN[14] - (RW)  xxx 
    RGU_CB_INFRA_METRAM_SWCTL_ISOINT[15] - (RW) CR_CB_INFRA_METRAM_SWCTL_ISOINT
    RGU_CB_INFRA_METRAM_SWCTL_SLP[16] - (RW) CR_CB_INFRA_METRAM_SWCTL_SLP
    RGU_CB_INFRA_METRAM_SWCTL_PDN[17] - (RW) CR_CB_INFRA_METRAM_SWCTL_PDN
    RGU_CB_INFRA_METRAM_HWCTL_SLP[18] - (RW) CR_CB_INFRA_METRAM_HWCTL_SLP
    RGU_CB_INFRA_METRAM_HWCTL_PDN[19] - (RW) CR_CB_INFRA_METRAM_HWCTL_PDN
    RGU_SWCTL_AOCLHENB[20]       - (RW)  xxx 
    RGU_SWCTL_AOCISO[21]         - (RW)  xxx 
    RGU_HWCTL_AOCLHENB[22]       - (RW)  xxx 
    RGU_HWCTL_AOCISO[23]         - (RW)  xxx 
    RGU_CB_INFRA_SYSRAM_SWCTL_ISOINT[24] - (RW)  xxx 
    RGU_CB_INFRA_SYSRAM_SWCTL_SLP[25] - (RW)  xxx 
    RGU_CB_INFRA_SYSRAM_SWCTL_PDN[26] - (RW)  xxx 
    RGU_CB_INFRA_SYSRAM_HWCTL_SLP[27] - (RW)  xxx 
    RGU_CB_INFRA_SYSRAM_HWCTL_PDN[28] - (RW)  xxx 
    RESERVED29[31..29]           - (RO) Reserved bits

 =====================================================================================*/
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_SYSRAM_HWCTL_PDN_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL9_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_SYSRAM_HWCTL_PDN_MASK 0x10000000u                // RGU_CB_INFRA_SYSRAM_HWCTL_PDN[28]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_SYSRAM_HWCTL_PDN_SHFT 28u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_SYSRAM_HWCTL_SLP_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL9_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_SYSRAM_HWCTL_SLP_MASK 0x08000000u                // RGU_CB_INFRA_SYSRAM_HWCTL_SLP[27]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_SYSRAM_HWCTL_SLP_SHFT 27u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_SYSRAM_SWCTL_PDN_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL9_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_SYSRAM_SWCTL_PDN_MASK 0x04000000u                // RGU_CB_INFRA_SYSRAM_SWCTL_PDN[26]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_SYSRAM_SWCTL_PDN_SHFT 26u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_SYSRAM_SWCTL_SLP_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL9_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_SYSRAM_SWCTL_SLP_MASK 0x02000000u                // RGU_CB_INFRA_SYSRAM_SWCTL_SLP[25]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_SYSRAM_SWCTL_SLP_SHFT 25u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_SYSRAM_SWCTL_ISOINT_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL9_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_SYSRAM_SWCTL_ISOINT_MASK 0x01000000u                // RGU_CB_INFRA_SYSRAM_SWCTL_ISOINT[24]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_SYSRAM_SWCTL_ISOINT_SHFT 24u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_HWCTL_AOCISO_ADDR     VLP_UDS_CTRL_CBTOP_UDS_CTRL9_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_HWCTL_AOCISO_MASK     0x00800000u                // RGU_HWCTL_AOCISO[23]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_HWCTL_AOCISO_SHFT     23u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_HWCTL_AOCLHENB_ADDR   VLP_UDS_CTRL_CBTOP_UDS_CTRL9_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_HWCTL_AOCLHENB_MASK   0x00400000u                // RGU_HWCTL_AOCLHENB[22]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_HWCTL_AOCLHENB_SHFT   22u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_SWCTL_AOCISO_ADDR     VLP_UDS_CTRL_CBTOP_UDS_CTRL9_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_SWCTL_AOCISO_MASK     0x00200000u                // RGU_SWCTL_AOCISO[21]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_SWCTL_AOCISO_SHFT     21u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_SWCTL_AOCLHENB_ADDR   VLP_UDS_CTRL_CBTOP_UDS_CTRL9_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_SWCTL_AOCLHENB_MASK   0x00100000u                // RGU_SWCTL_AOCLHENB[20]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_SWCTL_AOCLHENB_SHFT   20u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_METRAM_HWCTL_PDN_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL9_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_METRAM_HWCTL_PDN_MASK 0x00080000u                // RGU_CB_INFRA_METRAM_HWCTL_PDN[19]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_METRAM_HWCTL_PDN_SHFT 19u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_METRAM_HWCTL_SLP_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL9_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_METRAM_HWCTL_SLP_MASK 0x00040000u                // RGU_CB_INFRA_METRAM_HWCTL_SLP[18]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_METRAM_HWCTL_SLP_SHFT 18u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_METRAM_SWCTL_PDN_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL9_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_METRAM_SWCTL_PDN_MASK 0x00020000u                // RGU_CB_INFRA_METRAM_SWCTL_PDN[17]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_METRAM_SWCTL_PDN_SHFT 17u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_METRAM_SWCTL_SLP_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL9_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_METRAM_SWCTL_SLP_MASK 0x00010000u                // RGU_CB_INFRA_METRAM_SWCTL_SLP[16]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_METRAM_SWCTL_SLP_SHFT 16u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_METRAM_SWCTL_ISOINT_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL9_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_METRAM_SWCTL_ISOINT_MASK 0x00008000u                // RGU_CB_INFRA_METRAM_SWCTL_ISOINT[15]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_METRAM_SWCTL_ISOINT_SHFT 15u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_POWERMONITOR_HWCTL_PDN_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL9_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_POWERMONITOR_HWCTL_PDN_MASK 0x00004000u                // RGU_CB_INFRA_POWERMONITOR_HWCTL_PDN[14]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_POWERMONITOR_HWCTL_PDN_SHFT 14u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_POWERMONITOR_HWCTL_SLP_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL9_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_POWERMONITOR_HWCTL_SLP_MASK 0x00002000u                // RGU_CB_INFRA_POWERMONITOR_HWCTL_SLP[13]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_POWERMONITOR_HWCTL_SLP_SHFT 13u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_POWERMONITOR_SWCTL_PDN_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL9_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_POWERMONITOR_SWCTL_PDN_MASK 0x00001000u                // RGU_CB_INFRA_POWERMONITOR_SWCTL_PDN[12]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_POWERMONITOR_SWCTL_PDN_SHFT 12u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_POWERMONITOR_SWCTL_SLP_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL9_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_POWERMONITOR_SWCTL_SLP_MASK 0x00000800u                // RGU_CB_INFRA_POWERMONITOR_SWCTL_SLP[11]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_POWERMONITOR_SWCTL_SLP_SHFT 11u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_POWERMONITOR_SWCTL_ISOINT_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL9_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_POWERMONITOR_SWCTL_ISOINT_MASK 0x00000400u                // RGU_CB_INFRA_POWERMONITOR_SWCTL_ISOINT[10]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL9_RGU_CB_INFRA_POWERMONITOR_SWCTL_ISOINT_SHFT 10u

/* =====================================================================================

  ---CBTOP_UDS_CTRL10 (0x70003000 + 0x028u)---

    CR_ULPOSC_CALI_VALUE_LATCH[0] - (RW) 1 : Latch ULPOSC calibration value to VLP register
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL10_CR_ULPOSC_CALI_VALUE_LATCH_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL10_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL10_CR_ULPOSC_CALI_VALUE_LATCH_MASK 0x00000001u                // CR_ULPOSC_CALI_VALUE_LATCH[0]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL10_CR_ULPOSC_CALI_VALUE_LATCH_SHFT 0u

/* =====================================================================================

  ---CBTOP_UDS_CTRL12 (0x70003000 + 0x030u)---

    CBTOP_SYSRAM_RSV[15..0]      - (RO)  xxx 
    CBTOP_SYSRAM_REPAIR_EFUSE_REG[31..16] - (RW)  xxx 

 =====================================================================================*/
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL12_CBTOP_SYSRAM_REPAIR_EFUSE_REG_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL12_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL12_CBTOP_SYSRAM_REPAIR_EFUSE_REG_MASK 0xFFFF0000u                // CBTOP_SYSRAM_REPAIR_EFUSE_REG[31..16]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL12_CBTOP_SYSRAM_REPAIR_EFUSE_REG_SHFT 16u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL12_CBTOP_SYSRAM_RSV_ADDR    VLP_UDS_CTRL_CBTOP_UDS_CTRL12_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL12_CBTOP_SYSRAM_RSV_MASK    0x0000FFFFu                // CBTOP_SYSRAM_RSV[15..0]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL12_CBTOP_SYSRAM_RSV_SHFT    0u

/* =====================================================================================

  ---CBTOP_UDS_CTRL13 (0x70003000 + 0x034u)---

    CBTOP_SYSRAM_EFUSE_LATCH_BYPASS[0] - (RW)  xxx 
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL13_CBTOP_SYSRAM_EFUSE_LATCH_BYPASS_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL13_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL13_CBTOP_SYSRAM_EFUSE_LATCH_BYPASS_MASK 0x00000001u                // CBTOP_SYSRAM_EFUSE_LATCH_BYPASS[0]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL13_CBTOP_SYSRAM_EFUSE_LATCH_BYPASS_SHFT 0u

/* =====================================================================================

  ---CBTOP_UDS_CTRL14 (0x70003000 + 0x038u)---

    CR_MANUAL_PMIC_PALDO_LPM_EN[0] - (RW)  xxx 
    CR_MANUAL_PMIC_BUCKR_LV_EN[1] - (RW)  xxx 
    CR_MANUAL_PMIC_UDS_EN[2]     - (RW)  xxx 
    CR_MANUAL_CO_CLK_REQ[3]      - (RW) value @ manaul mode for co_clk_req sideband, debug use
    RESERVED4[29..4]             - (RO) Reserved bits
    CR_CO_CLK_MANUAL_MODE_EN[30] - (RW) manaul mode for co_clk_req sideband, debug use
    CR_PMIC_MANUAL_MODE_EN[31]   - (RW)  xxx 

 =====================================================================================*/
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL14_CR_PMIC_MANUAL_MODE_EN_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL14_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL14_CR_PMIC_MANUAL_MODE_EN_MASK 0x80000000u                // CR_PMIC_MANUAL_MODE_EN[31]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL14_CR_PMIC_MANUAL_MODE_EN_SHFT 31u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL14_CR_CO_CLK_MANUAL_MODE_EN_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL14_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL14_CR_CO_CLK_MANUAL_MODE_EN_MASK 0x40000000u                // CR_CO_CLK_MANUAL_MODE_EN[30]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL14_CR_CO_CLK_MANUAL_MODE_EN_SHFT 30u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL14_CR_MANUAL_CO_CLK_REQ_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL14_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL14_CR_MANUAL_CO_CLK_REQ_MASK 0x00000008u                // CR_MANUAL_CO_CLK_REQ[3]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL14_CR_MANUAL_CO_CLK_REQ_SHFT 3u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL14_CR_MANUAL_PMIC_UDS_EN_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL14_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL14_CR_MANUAL_PMIC_UDS_EN_MASK 0x00000004u                // CR_MANUAL_PMIC_UDS_EN[2]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL14_CR_MANUAL_PMIC_UDS_EN_SHFT 2u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL14_CR_MANUAL_PMIC_BUCKR_LV_EN_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL14_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL14_CR_MANUAL_PMIC_BUCKR_LV_EN_MASK 0x00000002u                // CR_MANUAL_PMIC_BUCKR_LV_EN[1]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL14_CR_MANUAL_PMIC_BUCKR_LV_EN_SHFT 1u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL14_CR_MANUAL_PMIC_PALDO_LPM_EN_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL14_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL14_CR_MANUAL_PMIC_PALDO_LPM_EN_MASK 0x00000001u                // CR_MANUAL_PMIC_PALDO_LPM_EN[0]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL14_CR_MANUAL_PMIC_PALDO_LPM_EN_SHFT 0u

/* =====================================================================================

  ---CBTOP_UDS_CTRL15 (0x70003000 + 0x03cu)---

    CR_WAKE_SLEEP_HANG_TIMEOUT_SET[7..0] - (RW) timeout for trigger wake/sleep hang wdt reset
    RESERVED8[8]                 - (RO) Reserved bits
    CR_WAKE_SLEEP_HANG_EN[9]     - (RW) 1: enable for trigger wake/sleep hang wdt reset
    RESERVED10[31..10]           - (RO) Reserved bits

 =====================================================================================*/
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL15_CR_WAKE_SLEEP_HANG_EN_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL15_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL15_CR_WAKE_SLEEP_HANG_EN_MASK 0x00000200u                // CR_WAKE_SLEEP_HANG_EN[9]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL15_CR_WAKE_SLEEP_HANG_EN_SHFT 9u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL15_CR_WAKE_SLEEP_HANG_TIMEOUT_SET_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL15_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL15_CR_WAKE_SLEEP_HANG_TIMEOUT_SET_MASK 0x000000FFu                // CR_WAKE_SLEEP_HANG_TIMEOUT_SET[7..0]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL15_CR_WAKE_SLEEP_HANG_TIMEOUT_SET_SHFT 0u

/* =====================================================================================

  ---CBTOP_UDS_CTRL16 (0x70003000 + 0x040u)---

    CR_VLP_F32K_SOURCE_SEL[1..0] - (RW) 2b'00 : bg_32k
                                     2'b01 : ext32k
                                     2'b10 : int_div_32k
                                     2'b11 : adie_32k
    RESERVED2[31..2]             - (RO) Reserved bits

 =====================================================================================*/
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL16_CR_VLP_F32K_SOURCE_SEL_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL16_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL16_CR_VLP_F32K_SOURCE_SEL_MASK 0x00000003u                // CR_VLP_F32K_SOURCE_SEL[1..0]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL16_CR_VLP_F32K_SOURCE_SEL_SHFT 0u

/* =====================================================================================

  ---CBTOP_UDS_CTRL17 (0x70003000 + 0x044u)---

    CR_SPMI_EN[0]                - (RW) 1: Enable UDS with SPMI mode
    CR_SPMI_BYPASS_SLP_REQ[1]    - (RW) 1: SPMI disconnect state machine bypass sleep_req handhake
    CR_SPMI_BYPASS_HW_DISCONNECT[2] - (RW) 1: cbtop_ulposc_pwr_stat machine bypass HW disconnection, reserved for SW disconnection flow
    CR_SPMI_CK_SWITCH_NORMAL_MODE[3] - (RW) 0: SPMI select xo (default for boot on) 1: SPMI select ulposc (Normal mode after ROM )
    RESERVED4[31..4]             - (RO) Reserved bits

 =====================================================================================*/
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL17_CR_SPMI_CK_SWITCH_NORMAL_MODE_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL17_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL17_CR_SPMI_CK_SWITCH_NORMAL_MODE_MASK 0x00000008u                // CR_SPMI_CK_SWITCH_NORMAL_MODE[3]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL17_CR_SPMI_CK_SWITCH_NORMAL_MODE_SHFT 3u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL17_CR_SPMI_BYPASS_HW_DISCONNECT_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL17_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL17_CR_SPMI_BYPASS_HW_DISCONNECT_MASK 0x00000004u                // CR_SPMI_BYPASS_HW_DISCONNECT[2]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL17_CR_SPMI_BYPASS_HW_DISCONNECT_SHFT 2u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL17_CR_SPMI_BYPASS_SLP_REQ_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL17_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL17_CR_SPMI_BYPASS_SLP_REQ_MASK 0x00000002u                // CR_SPMI_BYPASS_SLP_REQ[1]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL17_CR_SPMI_BYPASS_SLP_REQ_SHFT 1u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL17_CR_SPMI_EN_ADDR          VLP_UDS_CTRL_CBTOP_UDS_CTRL17_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL17_CR_SPMI_EN_MASK          0x00000001u                // CR_SPMI_EN[0]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL17_CR_SPMI_EN_SHFT          0u

/* =====================================================================================

  ---CBTOP_UDS_CTRL18 (0x70003000 + 0x048u)---

    CR_PMIC_UDS_EN_POLARITY_INVERT[0] - (RW) Invert pmic_uds_en polarity
    CR_PMIC_BUCKR_LV_POLARITY_INVERT[1] - (RW) Invert pmic_buckr_lv  polarity
    CR_CO_CLK_REQ_POLARITY_INVERT[2] - (RW) Invert co_clk_req polarity
    RESERVED3[24..3]             - (RO) Reserved bits
    CR_CO_CLK_REQ_TIMEOUT_SET[30..25] - (RW) Set co_clk_req assert by timeout counter target, only affect when CR_CO_CLK_REQ_TIMEOUT_EN = 1
    CR_CO_CLK_REQ_TIMEOUT_EN[31] - (RW) 1: Enable co_clk_req assert by timeout counter in wakeup flow 0:Disable timeout counter, co_clk_req assert with PMIC ready

 =====================================================================================*/
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL18_CR_CO_CLK_REQ_TIMEOUT_EN_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL18_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL18_CR_CO_CLK_REQ_TIMEOUT_EN_MASK 0x80000000u                // CR_CO_CLK_REQ_TIMEOUT_EN[31]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL18_CR_CO_CLK_REQ_TIMEOUT_EN_SHFT 31u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL18_CR_CO_CLK_REQ_TIMEOUT_SET_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL18_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL18_CR_CO_CLK_REQ_TIMEOUT_SET_MASK 0x7E000000u                // CR_CO_CLK_REQ_TIMEOUT_SET[30..25]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL18_CR_CO_CLK_REQ_TIMEOUT_SET_SHFT 25u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL18_CR_CO_CLK_REQ_POLARITY_INVERT_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL18_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL18_CR_CO_CLK_REQ_POLARITY_INVERT_MASK 0x00000004u                // CR_CO_CLK_REQ_POLARITY_INVERT[2]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL18_CR_CO_CLK_REQ_POLARITY_INVERT_SHFT 2u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL18_CR_PMIC_BUCKR_LV_POLARITY_INVERT_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL18_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL18_CR_PMIC_BUCKR_LV_POLARITY_INVERT_MASK 0x00000002u                // CR_PMIC_BUCKR_LV_POLARITY_INVERT[1]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL18_CR_PMIC_BUCKR_LV_POLARITY_INVERT_SHFT 1u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL18_CR_PMIC_UDS_EN_POLARITY_INVERT_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL18_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL18_CR_PMIC_UDS_EN_POLARITY_INVERT_MASK 0x00000001u                // CR_PMIC_UDS_EN_POLARITY_INVERT[0]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL18_CR_PMIC_UDS_EN_POLARITY_INVERT_SHFT 0u

/* =====================================================================================

  ---CBTOP_UDS_CTRL19 (0x70003000 + 0x04cu)---

    cr_met_en[0]                 - (RW) no used, reserve
    cr_met_xo_on[1]              - (RW) cb_infra met used, 1: always enable cb_infra xo CG
    cr_met_ulposc_on[2]          - (RW) cb_infra met used, 1: always enable cb_infra ulposc CG
    RESERVED3[31..3]             - (RO) Reserved bits

 =====================================================================================*/
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL19_cr_met_ulposc_on_ADDR    VLP_UDS_CTRL_CBTOP_UDS_CTRL19_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL19_cr_met_ulposc_on_MASK    0x00000004u                // cr_met_ulposc_on[2]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL19_cr_met_ulposc_on_SHFT    2u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL19_cr_met_xo_on_ADDR        VLP_UDS_CTRL_CBTOP_UDS_CTRL19_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL19_cr_met_xo_on_MASK        0x00000002u                // cr_met_xo_on[1]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL19_cr_met_xo_on_SHFT        1u
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL19_cr_met_en_ADDR           VLP_UDS_CTRL_CBTOP_UDS_CTRL19_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL19_cr_met_en_MASK           0x00000001u                // cr_met_en[0]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL19_cr_met_en_SHFT           0u

/* =====================================================================================

  ---CBTOP_UDS_CTRL20 (0x70003000 + 0x050u)---

    cr_adie_xtal_slp_lpm[0]      - (RW) Only for met power signal, record adie_xtal_slp mode
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL20_cr_adie_xtal_slp_lpm_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL20_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL20_cr_adie_xtal_slp_lpm_MASK 0x00000001u                // cr_adie_xtal_slp_lpm[0]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL20_cr_adie_xtal_slp_lpm_SHFT 0u

/* =====================================================================================

  ---CBTOP_UDS_CTRL21 (0x70003000 + 0x054u)---

    cr_swcfg_first_pwr_on[0]     - (RW) For ulposc_dyn, manual set first_pwr_on since ulpsoc may sleep before UDS
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL21_cr_swcfg_first_pwr_on_ADDR VLP_UDS_CTRL_CBTOP_UDS_CTRL21_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL21_cr_swcfg_first_pwr_on_MASK 0x00000001u                // cr_swcfg_first_pwr_on[0]
#define VLP_UDS_CTRL_CBTOP_UDS_CTRL21_cr_swcfg_first_pwr_on_SHFT 0u

/* =====================================================================================

  ---CBTOP_UDS_RSV (0x70003000 + 0x100u)---

    RESERVED0[7..0]              - (RO) Reserved bits
    CR_TOP_UDS_RSV_ECO2[9..8]    - (RW) ECO for UDS FSM PMIC_IN_UDS timeout setting
    CR_TOP_UDS_RSV_ECO3[11..10]  - (RW) ECO for UDS FSM PMIC_EXT_UDS timeout setting
    CR_TOP_UDS_RSV_ECO4[12]      - (RW) ECO for io_sleep_eco_en
    CR_TOP_UDS_RSV_ECO5[13]      - (RW) ECO for mem_eco_en
    RESERVED14[30..14]           - (RO) Reserved bits
    CR_ADIE_SLP_CK_CG_DISABLE[31] - (RW) Disable slp ck cg to adie

 =====================================================================================*/
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_CR_ADIE_SLP_CK_CG_DISABLE_ADDR VLP_UDS_CTRL_CBTOP_UDS_RSV_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_CR_ADIE_SLP_CK_CG_DISABLE_MASK 0x80000000u                // CR_ADIE_SLP_CK_CG_DISABLE[31]
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_CR_ADIE_SLP_CK_CG_DISABLE_SHFT 31u
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_CR_TOP_UDS_RSV_ECO5_ADDR    VLP_UDS_CTRL_CBTOP_UDS_RSV_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_CR_TOP_UDS_RSV_ECO5_MASK    0x00002000u                // CR_TOP_UDS_RSV_ECO5[13]
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_CR_TOP_UDS_RSV_ECO5_SHFT    13u
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_CR_TOP_UDS_RSV_ECO4_ADDR    VLP_UDS_CTRL_CBTOP_UDS_RSV_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_CR_TOP_UDS_RSV_ECO4_MASK    0x00001000u                // CR_TOP_UDS_RSV_ECO4[12]
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_CR_TOP_UDS_RSV_ECO4_SHFT    12u
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_CR_TOP_UDS_RSV_ECO3_ADDR    VLP_UDS_CTRL_CBTOP_UDS_RSV_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_CR_TOP_UDS_RSV_ECO3_MASK    0x00000C00u                // CR_TOP_UDS_RSV_ECO3[11..10]
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_CR_TOP_UDS_RSV_ECO3_SHFT    10u
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_CR_TOP_UDS_RSV_ECO2_ADDR    VLP_UDS_CTRL_CBTOP_UDS_RSV_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_CR_TOP_UDS_RSV_ECO2_MASK    0x00000300u                // CR_TOP_UDS_RSV_ECO2[9..8]
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_CR_TOP_UDS_RSV_ECO2_SHFT    8u

/* =====================================================================================

  ---CBTOP_ADIE_UDS_RDY_RD (0x70003000 + 0x104u)---

    ADIE_UDS_RDY_SYNC[0]         - (RO) Read only CR for cmdbt polling adie uds rdy
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define VLP_UDS_CTRL_CBTOP_ADIE_UDS_RDY_RD_ADIE_UDS_RDY_SYNC_ADDR VLP_UDS_CTRL_CBTOP_ADIE_UDS_RDY_RD_ADDR
#define VLP_UDS_CTRL_CBTOP_ADIE_UDS_RDY_RD_ADIE_UDS_RDY_SYNC_MASK 0x00000001u                // ADIE_UDS_RDY_SYNC[0]
#define VLP_UDS_CTRL_CBTOP_ADIE_UDS_RDY_RD_ADIE_UDS_RDY_SYNC_SHFT 0u

/* =====================================================================================

  ---CBTOP_OSCRDY_CNT_RD (0x70003000 + 0x108u)---

    WAKEUP_TO_OSC_RDY_CNTER[9..0] - (RO) Read only CR for counter to record UDS wakeup to osc_rdy
    SLEEP_TO_UDS_CNTER[19..10]   - (RO) Read only CR for counter to record UDS sleep flow
    RESERVED20[31..20]           - (RO) Reserved bits

 =====================================================================================*/
#define VLP_UDS_CTRL_CBTOP_OSCRDY_CNT_RD_SLEEP_TO_UDS_CNTER_ADDR VLP_UDS_CTRL_CBTOP_OSCRDY_CNT_RD_ADDR
#define VLP_UDS_CTRL_CBTOP_OSCRDY_CNT_RD_SLEEP_TO_UDS_CNTER_MASK 0x000FFC00u                // SLEEP_TO_UDS_CNTER[19..10]
#define VLP_UDS_CTRL_CBTOP_OSCRDY_CNT_RD_SLEEP_TO_UDS_CNTER_SHFT 10u
#define VLP_UDS_CTRL_CBTOP_OSCRDY_CNT_RD_WAKEUP_TO_OSC_RDY_CNTER_ADDR VLP_UDS_CTRL_CBTOP_OSCRDY_CNT_RD_ADDR
#define VLP_UDS_CTRL_CBTOP_OSCRDY_CNT_RD_WAKEUP_TO_OSC_RDY_CNTER_MASK 0x000003FFu                // WAKEUP_TO_OSC_RDY_CNTER[9..0]
#define VLP_UDS_CTRL_CBTOP_OSCRDY_CNT_RD_WAKEUP_TO_OSC_RDY_CNTER_SHFT 0u

#ifdef __cplusplus
}
#endif

#endif // __VLP_UDS_CTRL_REGS_H__
