/* SPDX-License-Identifier: BSD-2-Clause */
//[File]            : wf_uwtbl_top.h
//[Revision time]   : Mon Oct 30 22:53:53 2023
//[Description]     : This file is auto generated by CODA
//[Copyright]       : Copyright (C) 2023 Mediatek Incorportion. All rights reserved.
// remove HW description see https://wiki.mediatek.inc/display/WTKB/CODA+HW+description+separation


#ifndef __WF_UWTBL_TOP_REGS_H__
#define __WF_UWTBL_TOP_REGS_H__

#include "hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif








#define WF_UWTBL_TOP_BASE                                      0x820c4000u

#define WF_UWTBL_TOP_KTVLBR0_ADDR                              (WF_UWTBL_TOP_BASE + 0x0000u) 
#define WF_UWTBL_TOP_UCR_ADDR                                  (WF_UWTBL_TOP_BASE + 0x0100u) 
#define WF_UWTBL_TOP_WDUCR_ADDR                                (WF_UWTBL_TOP_BASE + 0x0104u) 
#define WF_UWTBL_TOP_KTCR_ADDR                                 (WF_UWTBL_TOP_BASE + 0x0108u) 
#define WF_UWTBL_TOP_WIUCR_ADDR                                (WF_UWTBL_TOP_BASE + 0x0110u) 
#define WF_UWTBL_TOP_WMUDR_ADDR                                (WF_UWTBL_TOP_BASE + 0x0114u) 
#define WF_UWTBL_TOP_WMUMR_ADDR                                (WF_UWTBL_TOP_BASE + 0x0118u) 
#define WF_UWTBL_TOP_PICR0_ADDR                                (WF_UWTBL_TOP_BASE + 0x0120u) 
#define WF_UWTBL_TOP_PICR1_ADDR                                (WF_UWTBL_TOP_BASE + 0x0124u) 
#define WF_UWTBL_TOP_ITCR_ADDR                                 (WF_UWTBL_TOP_BASE + 0x0130u) 
#define WF_UWTBL_TOP_ITDR0_ADDR                                (WF_UWTBL_TOP_BASE + 0x0138u) 
#define WF_UWTBL_TOP_ITDR1_ADDR                                (WF_UWTBL_TOP_BASE + 0x013Cu) 
#define WF_UWTBL_TOP_PSCCR_ADDR                                (WF_UWTBL_TOP_BASE + 0x0140u) 
#define WF_UWTBL_TOP_DSCR00_ADDR                               (WF_UWTBL_TOP_BASE + 0x0200u) 
#define WF_UWTBL_TOP_SRCR00_ADDR                               (WF_UWTBL_TOP_BASE + 0x0300u) 
#define WF_UWTBL_TOP_NSEPPCR00_ADDR                            (WF_UWTBL_TOP_BASE + 0x0400u) 
#define WF_UWTBL_TOP_DFR_ADDR                                  (WF_UWTBL_TOP_BASE + 0x1FD0u) 
#define WF_UWTBL_TOP_WTBLSNO_ADDR                              (WF_UWTBL_TOP_BASE + 0x1FE0u) 
#define WF_UWTBL_TOP_WTBLENO_ADDR                              (WF_UWTBL_TOP_BASE + 0x1FE4u) 
#define WF_UWTBL_TOP_KTBLNO_ADDR                               (WF_UWTBL_TOP_BASE + 0x1FE8u) 
#define WF_UWTBL_TOP_DMY0_ADDR                                 (WF_UWTBL_TOP_BASE + 0x1FF0u) 
#define WF_UWTBL_TOP_DMY1_ADDR                                 (WF_UWTBL_TOP_BASE + 0x1FF4u) 
#define WF_UWTBL_TOP_WTBL_DW_ADDR                              (WF_UWTBL_TOP_BASE + 0x1FF8u) 
#define WF_UWTBL_TOP_WTBL_BASE_ADDR                            (WF_UWTBL_TOP_BASE + 0x1FFCu) 





#define WF_UWTBL_TOP_KTVLBR0_VLB_ADDR                          WF_UWTBL_TOP_KTVLBR0_ADDR
#define WF_UWTBL_TOP_KTVLBR0_VLB_MASK                          0xFFFFFFFFu                
#define WF_UWTBL_TOP_KTVLBR0_VLB_SHFT                          0u


#define WF_UWTBL_TOP_UCR_MAX_BIPN_RANGE_ADDR                   WF_UWTBL_TOP_UCR_ADDR
#define WF_UWTBL_TOP_UCR_MAX_BIPN_RANGE_MASK                   0xFFFF0000u                
#define WF_UWTBL_TOP_UCR_MAX_BIPN_RANGE_SHFT                   16u
#define WF_UWTBL_TOP_UCR_PN_INCR_MODE_ADDR                     WF_UWTBL_TOP_UCR_ADDR
#define WF_UWTBL_TOP_UCR_PN_INCR_MODE_MASK                     0x00000001u                
#define WF_UWTBL_TOP_UCR_PN_INCR_MODE_SHFT                     0u


#define WF_UWTBL_TOP_WDUCR_TARGET_ADDR                         WF_UWTBL_TOP_WDUCR_ADDR
#define WF_UWTBL_TOP_WDUCR_TARGET_MASK                         0x80000000u                
#define WF_UWTBL_TOP_WDUCR_TARGET_SHFT                         31u
#define WF_UWTBL_TOP_WDUCR_GROUP_ADDR                          WF_UWTBL_TOP_WDUCR_ADDR
#define WF_UWTBL_TOP_WDUCR_GROUP_MASK                          0x0000003Fu                
#define WF_UWTBL_TOP_WDUCR_GROUP_SHFT                          0u


#define WF_UWTBL_TOP_KTCR_REASON_ADDR                          WF_UWTBL_TOP_KTCR_ADDR
#define WF_UWTBL_TOP_KTCR_REASON_MASK                          0xC0000000u                
#define WF_UWTBL_TOP_KTCR_REASON_SHFT                          30u
#define WF_UWTBL_TOP_KTCR_OPERATION_ADDR                       WF_UWTBL_TOP_KTCR_ADDR
#define WF_UWTBL_TOP_KTCR_OPERATION_MASK                       0x0000C000u                
#define WF_UWTBL_TOP_KTCR_OPERATION_SHFT                       14u
#define WF_UWTBL_TOP_KTCR_INDEX_ADDR                           WF_UWTBL_TOP_KTCR_ADDR
#define WF_UWTBL_TOP_KTCR_INDEX_MASK                           0x00001FFFu                
#define WF_UWTBL_TOP_KTCR_INDEX_SHFT                           0u


#define WF_UWTBL_TOP_WIUCR_IU_BUSY_ADDR                        WF_UWTBL_TOP_WIUCR_ADDR
#define WF_UWTBL_TOP_WIUCR_IU_BUSY_MASK                        0x80000000u                
#define WF_UWTBL_TOP_WIUCR_IU_BUSY_SHFT                        31u
#define WF_UWTBL_TOP_WIUCR_DW_ADDR                             WF_UWTBL_TOP_WIUCR_ADDR
#define WF_UWTBL_TOP_WIUCR_DW_MASK                             0x0F000000u                
#define WF_UWTBL_TOP_WIUCR_DW_SHFT                             24u
#define WF_UWTBL_TOP_WIUCR_MASK_UPDATE_ADDR                    WF_UWTBL_TOP_WIUCR_ADDR
#define WF_UWTBL_TOP_WIUCR_MASK_UPDATE_MASK                    0x00100000u                
#define WF_UWTBL_TOP_WIUCR_MASK_UPDATE_SHFT                    20u
#define WF_UWTBL_TOP_WIUCR_PNSN_CLEAR_ADDR                     WF_UWTBL_TOP_WIUCR_ADDR
#define WF_UWTBL_TOP_WIUCR_PNSN_CLEAR_MASK                     0x00040000u                
#define WF_UWTBL_TOP_WIUCR_PNSN_CLEAR_SHFT                     18u
#define WF_UWTBL_TOP_WIUCR_PEERINFO_UPDATE_ADDR                WF_UWTBL_TOP_WIUCR_ADDR
#define WF_UWTBL_TOP_WIUCR_PEERINFO_UPDATE_MASK                0x00002000u                
#define WF_UWTBL_TOP_WIUCR_PEERINFO_UPDATE_SHFT                13u
#define WF_UWTBL_TOP_WIUCR_INDEX_ADDR                          WF_UWTBL_TOP_WIUCR_ADDR
#define WF_UWTBL_TOP_WIUCR_INDEX_MASK                          0x00000FFFu                
#define WF_UWTBL_TOP_WIUCR_INDEX_SHFT                          0u


#define WF_UWTBL_TOP_WMUDR_UPDATE_DATA_ADDR                    WF_UWTBL_TOP_WMUDR_ADDR
#define WF_UWTBL_TOP_WMUDR_UPDATE_DATA_MASK                    0xFFFFFFFFu                
#define WF_UWTBL_TOP_WMUDR_UPDATE_DATA_SHFT                    0u


#define WF_UWTBL_TOP_WMUMR_UPDATE_MASK_ADDR                    WF_UWTBL_TOP_WMUMR_ADDR
#define WF_UWTBL_TOP_WMUMR_UPDATE_MASK_MASK                    0xFFFFFFFFu                
#define WF_UWTBL_TOP_WMUMR_UPDATE_MASK_SHFT                    0u


#define WF_UWTBL_TOP_PICR0_DW0_WTBL_ADDR                       WF_UWTBL_TOP_PICR0_ADDR
#define WF_UWTBL_TOP_PICR0_DW0_WTBL_MASK                       0xFFFFFFFFu                
#define WF_UWTBL_TOP_PICR0_DW0_WTBL_SHFT                       0u


#define WF_UWTBL_TOP_PICR1_DW1_WTBL_ADDR                       WF_UWTBL_TOP_PICR1_ADDR
#define WF_UWTBL_TOP_PICR1_DW1_WTBL_MASK                       0xFFFFFFFFu                
#define WF_UWTBL_TOP_PICR1_DW1_WTBL_SHFT                       0u


#define WF_UWTBL_TOP_ITCR_EXECUTE_ADDR                         WF_UWTBL_TOP_ITCR_ADDR
#define WF_UWTBL_TOP_ITCR_EXECUTE_MASK                         0x80000000u                
#define WF_UWTBL_TOP_ITCR_EXECUTE_SHFT                         31u
#define WF_UWTBL_TOP_ITCR_SELECT_ADDR                          WF_UWTBL_TOP_ITCR_ADDR
#define WF_UWTBL_TOP_ITCR_SELECT_MASK                          0x03000000u                
#define WF_UWTBL_TOP_ITCR_SELECT_SHFT                          24u
#define WF_UWTBL_TOP_ITCR_OP_ADDR                              WF_UWTBL_TOP_ITCR_ADDR
#define WF_UWTBL_TOP_ITCR_OP_MASK                              0x00010000u                
#define WF_UWTBL_TOP_ITCR_OP_SHFT                              16u
#define WF_UWTBL_TOP_ITCR_INDEX_ADDR                           WF_UWTBL_TOP_ITCR_ADDR
#define WF_UWTBL_TOP_ITCR_INDEX_MASK                           0x0000003Fu                
#define WF_UWTBL_TOP_ITCR_INDEX_SHFT                           0u


#define WF_UWTBL_TOP_ITDR0_INDIRECT_TABLE_DATA_ADDR            WF_UWTBL_TOP_ITDR0_ADDR
#define WF_UWTBL_TOP_ITDR0_INDIRECT_TABLE_DATA_MASK            0xFFFFFFFFu                
#define WF_UWTBL_TOP_ITDR0_INDIRECT_TABLE_DATA_SHFT            0u


#define WF_UWTBL_TOP_ITDR1_INDIRECT_TABLE_DATA_ADDR            WF_UWTBL_TOP_ITDR1_ADDR
#define WF_UWTBL_TOP_ITDR1_INDIRECT_TABLE_DATA_MASK            0xFFFFFFFFu                
#define WF_UWTBL_TOP_ITDR1_INDIRECT_TABLE_DATA_SHFT            0u


#define WF_UWTBL_TOP_PSCCR_EXECUTE_ADDR                        WF_UWTBL_TOP_PSCCR_ADDR
#define WF_UWTBL_TOP_PSCCR_EXECUTE_MASK                        0x80000000u                
#define WF_UWTBL_TOP_PSCCR_EXECUTE_SHFT                        31u
#define WF_UWTBL_TOP_PSCCR_OP_ADDR                             WF_UWTBL_TOP_PSCCR_ADDR
#define WF_UWTBL_TOP_PSCCR_OP_MASK                             0x01000000u                
#define WF_UWTBL_TOP_PSCCR_OP_SHFT                             24u
#define WF_UWTBL_TOP_PSCCR_TARGET_ADDR                         WF_UWTBL_TOP_PSCCR_ADDR
#define WF_UWTBL_TOP_PSCCR_TARGET_MASK                         0x00070000u                
#define WF_UWTBL_TOP_PSCCR_TARGET_SHFT                         16u
#define WF_UWTBL_TOP_PSCCR_MLD_ID_ADDR                         WF_UWTBL_TOP_PSCCR_ADDR
#define WF_UWTBL_TOP_PSCCR_MLD_ID_MASK                         0x00000FFFu                
#define WF_UWTBL_TOP_PSCCR_MLD_ID_SHFT                         0u


#define WF_UWTBL_TOP_DSCR00_DSCR00_02_ADDR                     WF_UWTBL_TOP_DSCR00_ADDR
#define WF_UWTBL_TOP_DSCR00_DSCR00_02_MASK                     0xFFFF0000u                
#define WF_UWTBL_TOP_DSCR00_DSCR00_02_SHFT                     16u
#define WF_UWTBL_TOP_DSCR00_DSCR00_01_ADDR                     WF_UWTBL_TOP_DSCR00_ADDR
#define WF_UWTBL_TOP_DSCR00_DSCR00_01_MASK                     0x0000FF00u                
#define WF_UWTBL_TOP_DSCR00_DSCR00_01_SHFT                     8u
#define WF_UWTBL_TOP_DSCR00_DSCR00_ADDR                        WF_UWTBL_TOP_DSCR00_ADDR
#define WF_UWTBL_TOP_DSCR00_DSCR00_MASK                        0x000000FFu                
#define WF_UWTBL_TOP_DSCR00_DSCR00_SHFT                        0u


#define WF_UWTBL_TOP_SRCR00_SRCR00_02_ADDR                     WF_UWTBL_TOP_SRCR00_ADDR
#define WF_UWTBL_TOP_SRCR00_SRCR00_02_MASK                     0xFFFF0000u                
#define WF_UWTBL_TOP_SRCR00_SRCR00_02_SHFT                     16u
#define WF_UWTBL_TOP_SRCR00_SRCR00_01_ADDR                     WF_UWTBL_TOP_SRCR00_ADDR
#define WF_UWTBL_TOP_SRCR00_SRCR00_01_MASK                     0x0000FF00u                
#define WF_UWTBL_TOP_SRCR00_SRCR00_01_SHFT                     8u
#define WF_UWTBL_TOP_SRCR00_SRCR00_ADDR                        WF_UWTBL_TOP_SRCR00_ADDR
#define WF_UWTBL_TOP_SRCR00_SRCR00_MASK                        0x000000FFu                
#define WF_UWTBL_TOP_SRCR00_SRCR00_SHFT                        0u


#define WF_UWTBL_TOP_NSEPPCR00_NSEPPCR00_02_ADDR               WF_UWTBL_TOP_NSEPPCR00_ADDR
#define WF_UWTBL_TOP_NSEPPCR00_NSEPPCR00_02_MASK               0xFFFF0000u                
#define WF_UWTBL_TOP_NSEPPCR00_NSEPPCR00_02_SHFT               16u
#define WF_UWTBL_TOP_NSEPPCR00_NSEPPCR00_01_ADDR               WF_UWTBL_TOP_NSEPPCR00_ADDR
#define WF_UWTBL_TOP_NSEPPCR00_NSEPPCR00_01_MASK               0x0000FF00u                
#define WF_UWTBL_TOP_NSEPPCR00_NSEPPCR00_01_SHFT               8u
#define WF_UWTBL_TOP_NSEPPCR00_NSEPPCR00_ADDR                  WF_UWTBL_TOP_NSEPPCR00_ADDR
#define WF_UWTBL_TOP_NSEPPCR00_NSEPPCR00_MASK                  0x000000FFu                
#define WF_UWTBL_TOP_NSEPPCR00_NSEPPCR00_SHFT                  0u


#define WF_UWTBL_TOP_DFR_DEBUG_FSM_ADDR                        WF_UWTBL_TOP_DFR_ADDR
#define WF_UWTBL_TOP_DFR_DEBUG_FSM_MASK                        0xFFFFFFFFu                
#define WF_UWTBL_TOP_DFR_DEBUG_FSM_SHFT                        0u


#define WF_UWTBL_TOP_WTBLSNO_WTBL_STD_NO_ADDR                  WF_UWTBL_TOP_WTBLSNO_ADDR
#define WF_UWTBL_TOP_WTBLSNO_WTBL_STD_NO_MASK                  0xFFFFFFFFu                
#define WF_UWTBL_TOP_WTBLSNO_WTBL_STD_NO_SHFT                  0u


#define WF_UWTBL_TOP_WTBLENO_WTBL_EXT_NO_ADDR                  WF_UWTBL_TOP_WTBLENO_ADDR
#define WF_UWTBL_TOP_WTBLENO_WTBL_EXT_NO_MASK                  0xFFFFFFFFu                
#define WF_UWTBL_TOP_WTBLENO_WTBL_EXT_NO_SHFT                  0u


#define WF_UWTBL_TOP_KTBLNO_KTBL_NO_ADDR                       WF_UWTBL_TOP_KTBLNO_ADDR
#define WF_UWTBL_TOP_KTBLNO_KTBL_NO_MASK                       0xFFFFFFFFu                
#define WF_UWTBL_TOP_KTBLNO_KTBL_NO_SHFT                       0u


#define WF_UWTBL_TOP_DMY0_DMY0_ADDR                            WF_UWTBL_TOP_DMY0_ADDR
#define WF_UWTBL_TOP_DMY0_DMY0_MASK                            0xFFFFFFFFu                
#define WF_UWTBL_TOP_DMY0_DMY0_SHFT                            0u


#define WF_UWTBL_TOP_DMY1_DMY1_ADDR                            WF_UWTBL_TOP_DMY1_ADDR
#define WF_UWTBL_TOP_DMY1_DMY1_MASK                            0xFFFFFFFFu                
#define WF_UWTBL_TOP_DMY1_DMY1_SHFT                            0u


#define WF_UWTBL_TOP_WTBL_DW_WTBL_DW_ADDR                      WF_UWTBL_TOP_WTBL_DW_ADDR
#define WF_UWTBL_TOP_WTBL_DW_WTBL_DW_MASK                      0xFFFFFFFFu                
#define WF_UWTBL_TOP_WTBL_DW_WTBL_DW_SHFT                      0u


#define WF_UWTBL_TOP_WTBL_BASE_WTBL_BASE_ADDR                  WF_UWTBL_TOP_WTBL_BASE_ADDR
#define WF_UWTBL_TOP_WTBL_BASE_WTBL_BASE_MASK                  0xFFFFFFFFu                
#define WF_UWTBL_TOP_WTBL_BASE_WTBL_BASE_SHFT                  0u

#ifdef __cplusplus
}
#endif

#endif // __WF_UWTBL_TOP_REGS_H__
