/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * Copyright (c) 2021 MediaTek Inc.
 */

//[File]            : conn_bus_cr_on.h
//[Revision time]   : Thu Nov 11 16:09:32 2021
//[Description]     : This file is auto generated by CODA
//[Copyright]       : Copyright (C) 2021 Mediatek Incorportion. All rights reserved.

#ifndef __CONN_BUS_CR_ON_REGS_H__
#define __CONN_BUS_CR_ON_REGS_H__

#include "hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif


//****************************************************************************
//
//                     CONN_BUS_CR_ON CR Definitions                     
//
//****************************************************************************

#define CONN_BUS_CR_ON_BASE                                    (0x1800E000 + CONN_INFRA_REMAPPING_OFFSET)

#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_ADDR   (CONN_BUS_CR_ON_BASE + 0x000) // E000
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_1_ADDR   (CONN_BUS_CR_ON_BASE + 0x004) // E004
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_ON_DCM_CTL_ADDR (CONN_BUS_CR_ON_BASE + 0x008) // E008
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_ADDR (CONN_BUS_CR_ON_BASE + 0x00C) // E00C
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_1_ADDR (CONN_BUS_CR_ON_BASE + 0x010) // E010
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_2_ADDR (CONN_BUS_CR_ON_BASE + 0x014) // E014
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_ADDR (CONN_BUS_CR_ON_BASE + 0x018) // E018
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_4_ADDR (CONN_BUS_CR_ON_BASE + 0x01C) // E01C
#define CONN_BUS_CR_ON_CONN_VON_IDLE_MASK_ADDR                 (CONN_BUS_CR_ON_BASE + 0x100) // E100
#define CONN_BUS_CR_ON_CONN_VON_BUS_IDLE_DEBOUNCE_ADDR         (CONN_BUS_CR_ON_BASE + 0x104) // E104
#define CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_EN_ADDR            (CONN_BUS_CR_ON_BASE + 0x108) // E108
#define CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_THRE_ADDR          (CONN_BUS_CR_ON_BASE + 0x10C) // E10C
#define CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_CLR_ADDR           (CONN_BUS_CR_ON_BASE + 0x110) // E110
#define CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_IRQ_ADDR           (CONN_BUS_CR_ON_BASE + 0x114) // E114
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_EN_ADDR               (CONN_BUS_CR_ON_BASE + 0x118) // E118
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_THRE_ADDR             (CONN_BUS_CR_ON_BASE + 0x11C) // E11C
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_CLR_ADDR              (CONN_BUS_CR_ON_BASE + 0x120) // E120
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_IRQ_ADDR              (CONN_BUS_CR_ON_BASE + 0x124) // E124
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N7_TIMEOUT_INFO_0_ADDR (CONN_BUS_CR_ON_BASE + 0x128) // E128
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N7_TIMEOUT_INFO_1_ADDR (CONN_BUS_CR_ON_BASE + 0x12C) // E12C
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N7_TIMEOUT_ADDR_ADDR  (CONN_BUS_CR_ON_BASE + 0x130) // E130
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N7_TIMEOUT_WDATA_ADDR (CONN_BUS_CR_ON_BASE + 0x134) // E134
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N9_TIMEOUT_INFO_ADDR  (CONN_BUS_CR_ON_BASE + 0x138) // E138
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N9_TIMEOUT_ADDR_ADDR  (CONN_BUS_CR_ON_BASE + 0x13C) // E13C
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N9_TIMEOUT_WDATA_ADDR (CONN_BUS_CR_ON_BASE + 0x140) // E140
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_APB_SLV_ACCESS_DETECT_EN_ADDR (CONN_BUS_CR_ON_BASE + 0x200) // E200
#define CONN_BUS_CR_ON_CONN_INFRA_CKSYS_CK_CTRL_ADDR           (CONN_BUS_CR_ON_BASE + 0x320) // E320
#define CONN_BUS_CR_ON_CONN_INFRA_SECURITY_CTRL_ADDR           (CONN_BUS_CR_ON_BASE + 0x500) // E500
#define CONN_BUS_CR_ON_ADDR_AP2CONN_AHB_GALS_CFG_ADDR          (CONN_BUS_CR_ON_BASE + 0xA00) // EA00
#define CONN_BUS_CR_ON_ADDR_AP2CONN_AHB_GALS_DBG_ADDR          (CONN_BUS_CR_ON_BASE + 0xA04) // EA04




/* =====================================================================================

  ---ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0 (0x1800E000 + 0x000)---

    cr_host_clock_group_ctrl_sc_axi_dcm_dis_en[0] - (RW)  xxx 
    cr_host_clock_group_ctrl_pllck_sel_no_spm[1] - (RW) enable DCM
    cr_host_clock_group_ctrl_pllck_sel_2_clk_rdy_on_dcm[2] - (RW)  xxx 
    cr_host_ck_ctrl_clkoff_en[3] - (RW) DCM off mode
    cr_host_ck_ctrl_clkslow_en[4] - (RW) DCM slow mode
    cr_host_ck_ctrl_force_clkoff[5] - (RW) DCM force off
    cr_host_ck_ctrl_force_clkslow[6] - (RW) DCM force slow
    cr_host_ck_ctrl_force_on[7]  - (RW) DCM force free run
    cr_host_ck_ctrl_fsel[12..8]  - (RW) normal mode clk_out freq
                                     [12] = 1: div1
                                     [11] = 1: div2
                                     [10] = 1: div4
                                     [9] = 1: div8
                                     [8] = 1: div16
    cr_host_ck_ctrl_sfsel[17..13] - (RW) slow mode clk_out freq
                                     [17] = 1: div1
                                     [16] = 1: div2
                                     [15] = 1: div4
                                     [14] = 1: div8
                                     [13] = 1: div16
    RESERVED18[31..18]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_cr_host_ck_ctrl_sfsel_ADDR CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_cr_host_ck_ctrl_sfsel_MASK 0x0003E000                // cr_host_ck_ctrl_sfsel[17..13]
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_cr_host_ck_ctrl_sfsel_SHFT 13
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_cr_host_ck_ctrl_fsel_ADDR CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_cr_host_ck_ctrl_fsel_MASK 0x00001F00                // cr_host_ck_ctrl_fsel[12..8]
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_cr_host_ck_ctrl_fsel_SHFT 8
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_cr_host_ck_ctrl_force_on_ADDR CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_cr_host_ck_ctrl_force_on_MASK 0x00000080                // cr_host_ck_ctrl_force_on[7]
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_cr_host_ck_ctrl_force_on_SHFT 7
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_cr_host_ck_ctrl_force_clkslow_ADDR CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_cr_host_ck_ctrl_force_clkslow_MASK 0x00000040                // cr_host_ck_ctrl_force_clkslow[6]
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_cr_host_ck_ctrl_force_clkslow_SHFT 6
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_cr_host_ck_ctrl_force_clkoff_ADDR CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_cr_host_ck_ctrl_force_clkoff_MASK 0x00000020                // cr_host_ck_ctrl_force_clkoff[5]
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_cr_host_ck_ctrl_force_clkoff_SHFT 5
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_cr_host_ck_ctrl_clkslow_en_ADDR CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_cr_host_ck_ctrl_clkslow_en_MASK 0x00000010                // cr_host_ck_ctrl_clkslow_en[4]
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_cr_host_ck_ctrl_clkslow_en_SHFT 4
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_cr_host_ck_ctrl_clkoff_en_ADDR CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_cr_host_ck_ctrl_clkoff_en_MASK 0x00000008                // cr_host_ck_ctrl_clkoff_en[3]
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_cr_host_ck_ctrl_clkoff_en_SHFT 3
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_cr_host_clock_group_ctrl_pllck_sel_2_clk_rdy_on_dcm_ADDR CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_cr_host_clock_group_ctrl_pllck_sel_2_clk_rdy_on_dcm_MASK 0x00000004                // cr_host_clock_group_ctrl_pllck_sel_2_clk_rdy_on_dcm[2]
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_cr_host_clock_group_ctrl_pllck_sel_2_clk_rdy_on_dcm_SHFT 2
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_cr_host_clock_group_ctrl_pllck_sel_no_spm_ADDR CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_cr_host_clock_group_ctrl_pllck_sel_no_spm_MASK 0x00000002                // cr_host_clock_group_ctrl_pllck_sel_no_spm[1]
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_cr_host_clock_group_ctrl_pllck_sel_no_spm_SHFT 1
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_cr_host_clock_group_ctrl_sc_axi_dcm_dis_en_ADDR CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_cr_host_clock_group_ctrl_sc_axi_dcm_dis_en_MASK 0x00000001                // cr_host_clock_group_ctrl_sc_axi_dcm_dis_en[0]
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_0_cr_host_clock_group_ctrl_sc_axi_dcm_dis_en_SHFT 0

/* =====================================================================================

  ---ADDR_CONN_VON_BUS_GLUE_DCM_CTL_1 (0x1800E000 + 0x004)---

    cr_host_ck_dbc_ctrl_dbc_num[11..0] - (RW)  xxx 
    cr_host_ck_dbc_ctrl_dbc_en[12] - (RW)  xxx 
    ro_host_ck_dcm_idle[13]      - (RO)  xxx 
    ro_host_ck_rdy_on_dcm[14]    - (RO)  xxx 
    cr_host_ck_sc_axi_dcm_dis[15] - (RW)  xxx 
    cr_force_on_host_ck_dcm[16]  - (RW)  xxx 
    RESERVED17[31..17]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_1_cr_force_on_host_ck_dcm_ADDR CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_1_cr_force_on_host_ck_dcm_MASK 0x00010000                // cr_force_on_host_ck_dcm[16]
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_1_cr_force_on_host_ck_dcm_SHFT 16
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_1_cr_host_ck_sc_axi_dcm_dis_ADDR CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_1_cr_host_ck_sc_axi_dcm_dis_MASK 0x00008000                // cr_host_ck_sc_axi_dcm_dis[15]
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_1_cr_host_ck_sc_axi_dcm_dis_SHFT 15
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_1_ro_host_ck_rdy_on_dcm_ADDR CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_1_ro_host_ck_rdy_on_dcm_MASK 0x00004000                // ro_host_ck_rdy_on_dcm[14]
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_1_ro_host_ck_rdy_on_dcm_SHFT 14
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_1_ro_host_ck_dcm_idle_ADDR CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_1_ro_host_ck_dcm_idle_MASK 0x00002000                // ro_host_ck_dcm_idle[13]
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_1_ro_host_ck_dcm_idle_SHFT 13
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_1_cr_host_ck_dbc_ctrl_dbc_en_ADDR CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_1_cr_host_ck_dbc_ctrl_dbc_en_MASK 0x00001000                // cr_host_ck_dbc_ctrl_dbc_en[12]
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_1_cr_host_ck_dbc_ctrl_dbc_en_SHFT 12
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_1_cr_host_ck_dbc_ctrl_dbc_num_ADDR CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_1_cr_host_ck_dbc_ctrl_dbc_num_MASK 0x00000FFF                // cr_host_ck_dbc_ctrl_dbc_num[11..0]
#define CONN_BUS_CR_ON_ADDR_CONN_VON_BUS_GLUE_DCM_CTL_1_cr_host_ck_dbc_ctrl_dbc_num_SHFT 0

/* =====================================================================================

  ---ADDR_CONN_INFRA_VDNR_GLUE_ON_DCM_CTL (0x1800E000 + 0x008)---

    cr_conn_infra_vdnr_on_osc_ck_dcm_dis[0] - (RW) disable DCM
    cr_conn_infra_vdnr_on_host_osc_ck_dcm_dis[1] - (RW) disable DCM
    RESERVED2[31..2]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_ON_DCM_CTL_cr_conn_infra_vdnr_on_host_osc_ck_dcm_dis_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_ON_DCM_CTL_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_ON_DCM_CTL_cr_conn_infra_vdnr_on_host_osc_ck_dcm_dis_MASK 0x00000002                // cr_conn_infra_vdnr_on_host_osc_ck_dcm_dis[1]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_ON_DCM_CTL_cr_conn_infra_vdnr_on_host_osc_ck_dcm_dis_SHFT 1
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_ON_DCM_CTL_cr_conn_infra_vdnr_on_osc_ck_dcm_dis_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_ON_DCM_CTL_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_ON_DCM_CTL_cr_conn_infra_vdnr_on_osc_ck_dcm_dis_MASK 0x00000001                // cr_conn_infra_vdnr_on_osc_ck_dcm_dis[0]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_ON_DCM_CTL_cr_conn_infra_vdnr_on_osc_ck_dcm_dis_SHFT 0

/* =====================================================================================

  ---ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0 (0x1800E000 + 0x00C)---

    cr_conn_infra_hclk_clock_group_ctrl_sc_axi_dcm_dis_en[0] - (RW)  xxx 
    cr_conn_infra_hclk_clock_group_ctrl_pllck_sel_no_spm[1] - (RW) enable DCM
    cr_conn_infra_hclk_clock_group_ctrl_pllck_sel_2_clk_rdy_on_dcm[2] - (RW)  xxx 
    cr_conn_infra_hclk_ctrl_clkoff_en[3] - (RW) DCM off mode
    cr_conn_infra_hclk_ctrl_clkslow_en[4] - (RW) DCM slow mode
    cr_conn_infra_hclk_ctrl_force_clkoff[5] - (RW) DCM force off
    cr_conn_infra_hclk_ctrl_force_clkslow[6] - (RW) DCM force slow
    cr_conn_infra_hclk_ctrl_force_on[7] - (RW) DCM force free run
    cr_conn_infra_hclk_ctrl_fsel[12..8] - (RW) normal mode clk_out freq
                                     [12] = 1: div1
                                     [11] = 1: div2
                                     [10] = 1: div4
                                     [9] = 1: div8
                                     [8] = 1: div16
    cr_conn_infra_hclk_ctrl_sfsel[17..13] - (RW) slow mode clk_out freq
                                     [17] = 1: div1
                                     [16] = 1: div2
                                     [15] = 1: div4
                                     [14] = 1: div8
                                     [13] = 1: div16
    RESERVED18[31..18]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_cr_conn_infra_hclk_ctrl_sfsel_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_cr_conn_infra_hclk_ctrl_sfsel_MASK 0x0003E000                // cr_conn_infra_hclk_ctrl_sfsel[17..13]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_cr_conn_infra_hclk_ctrl_sfsel_SHFT 13
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_cr_conn_infra_hclk_ctrl_fsel_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_cr_conn_infra_hclk_ctrl_fsel_MASK 0x00001F00                // cr_conn_infra_hclk_ctrl_fsel[12..8]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_cr_conn_infra_hclk_ctrl_fsel_SHFT 8
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_cr_conn_infra_hclk_ctrl_force_on_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_cr_conn_infra_hclk_ctrl_force_on_MASK 0x00000080                // cr_conn_infra_hclk_ctrl_force_on[7]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_cr_conn_infra_hclk_ctrl_force_on_SHFT 7
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_cr_conn_infra_hclk_ctrl_force_clkslow_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_cr_conn_infra_hclk_ctrl_force_clkslow_MASK 0x00000040                // cr_conn_infra_hclk_ctrl_force_clkslow[6]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_cr_conn_infra_hclk_ctrl_force_clkslow_SHFT 6
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_cr_conn_infra_hclk_ctrl_force_clkoff_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_cr_conn_infra_hclk_ctrl_force_clkoff_MASK 0x00000020                // cr_conn_infra_hclk_ctrl_force_clkoff[5]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_cr_conn_infra_hclk_ctrl_force_clkoff_SHFT 5
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_cr_conn_infra_hclk_ctrl_clkslow_en_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_cr_conn_infra_hclk_ctrl_clkslow_en_MASK 0x00000010                // cr_conn_infra_hclk_ctrl_clkslow_en[4]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_cr_conn_infra_hclk_ctrl_clkslow_en_SHFT 4
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_cr_conn_infra_hclk_ctrl_clkoff_en_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_cr_conn_infra_hclk_ctrl_clkoff_en_MASK 0x00000008                // cr_conn_infra_hclk_ctrl_clkoff_en[3]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_cr_conn_infra_hclk_ctrl_clkoff_en_SHFT 3
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_cr_conn_infra_hclk_clock_group_ctrl_pllck_sel_2_clk_rdy_on_dcm_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_cr_conn_infra_hclk_clock_group_ctrl_pllck_sel_2_clk_rdy_on_dcm_MASK 0x00000004                // cr_conn_infra_hclk_clock_group_ctrl_pllck_sel_2_clk_rdy_on_dcm[2]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_cr_conn_infra_hclk_clock_group_ctrl_pllck_sel_2_clk_rdy_on_dcm_SHFT 2
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_cr_conn_infra_hclk_clock_group_ctrl_pllck_sel_no_spm_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_cr_conn_infra_hclk_clock_group_ctrl_pllck_sel_no_spm_MASK 0x00000002                // cr_conn_infra_hclk_clock_group_ctrl_pllck_sel_no_spm[1]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_cr_conn_infra_hclk_clock_group_ctrl_pllck_sel_no_spm_SHFT 1
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_cr_conn_infra_hclk_clock_group_ctrl_sc_axi_dcm_dis_en_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_cr_conn_infra_hclk_clock_group_ctrl_sc_axi_dcm_dis_en_MASK 0x00000001                // cr_conn_infra_hclk_clock_group_ctrl_sc_axi_dcm_dis_en[0]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_0_cr_conn_infra_hclk_clock_group_ctrl_sc_axi_dcm_dis_en_SHFT 0

/* =====================================================================================

  ---ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_1 (0x1800E000 + 0x010)---

    cr_conn_infra_hclk_dbc_ctrl_dbc_num[11..0] - (RW)  xxx 
    cr_conn_infra_hclk_dbc_ctrl_dbc_en[12] - (RW)  xxx 
    ro_conn_infra_hclk_dcm_idle[13] - (RO)  xxx 
    ro_conn_infra_hclk_dcm_rdy_on[14] - (RO)  xxx 
    cr_conn_infra_hclk_sc_axi_dcm_dis[15] - (RW)  xxx 
    cr_force_on_conn_infra_hclk_dcm[16] - (RW)  xxx 
    cr_conn_infra_hclk_bus_idle_sync_mask[17] - (RW)  xxx 
    RESERVED18[31..18]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_1_cr_conn_infra_hclk_bus_idle_sync_mask_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_1_cr_conn_infra_hclk_bus_idle_sync_mask_MASK 0x00020000                // cr_conn_infra_hclk_bus_idle_sync_mask[17]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_1_cr_conn_infra_hclk_bus_idle_sync_mask_SHFT 17
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_1_cr_force_on_conn_infra_hclk_dcm_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_1_cr_force_on_conn_infra_hclk_dcm_MASK 0x00010000                // cr_force_on_conn_infra_hclk_dcm[16]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_1_cr_force_on_conn_infra_hclk_dcm_SHFT 16
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_1_cr_conn_infra_hclk_sc_axi_dcm_dis_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_1_cr_conn_infra_hclk_sc_axi_dcm_dis_MASK 0x00008000                // cr_conn_infra_hclk_sc_axi_dcm_dis[15]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_1_cr_conn_infra_hclk_sc_axi_dcm_dis_SHFT 15
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_1_ro_conn_infra_hclk_dcm_rdy_on_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_1_ro_conn_infra_hclk_dcm_rdy_on_MASK 0x00004000                // ro_conn_infra_hclk_dcm_rdy_on[14]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_1_ro_conn_infra_hclk_dcm_rdy_on_SHFT 14
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_1_ro_conn_infra_hclk_dcm_idle_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_1_ro_conn_infra_hclk_dcm_idle_MASK 0x00002000                // ro_conn_infra_hclk_dcm_idle[13]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_1_ro_conn_infra_hclk_dcm_idle_SHFT 13
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_1_cr_conn_infra_hclk_dbc_ctrl_dbc_en_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_1_cr_conn_infra_hclk_dbc_ctrl_dbc_en_MASK 0x00001000                // cr_conn_infra_hclk_dbc_ctrl_dbc_en[12]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_1_cr_conn_infra_hclk_dbc_ctrl_dbc_en_SHFT 12
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_1_cr_conn_infra_hclk_dbc_ctrl_dbc_num_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_1_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_1_cr_conn_infra_hclk_dbc_ctrl_dbc_num_MASK 0x00000FFF                // cr_conn_infra_hclk_dbc_ctrl_dbc_num[11..0]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_1_cr_conn_infra_hclk_dbc_ctrl_dbc_num_SHFT 0

/* =====================================================================================

  ---ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_2 (0x1800E000 + 0x014)---

    cr_forced_release_osc_clk_dcm[0] - (RW) disable DCM
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_2_cr_forced_release_osc_clk_dcm_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_2_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_2_cr_forced_release_osc_clk_dcm_MASK 0x00000001                // cr_forced_release_osc_clk_dcm[0]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_2_cr_forced_release_osc_clk_dcm_SHFT 0

/* =====================================================================================

  ---ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3 (0x1800E000 + 0x018)---

    cr_conn_infra_aclk_clock_group_ctrl_sc_axi_dcm_dis_en[0] - (RW)  xxx 
    cr_conn_infra_aclk_clock_group_ctrl_pllck_sel_no_spm[1] - (RW) enable DCM
    cr_conn_infra_aclk_clock_group_ctrl_pllck_sel_2_clk_rdy_on_dcm[2] - (RW)  xxx 
    cr_conn_infra_aclk_ctrl_clkoff_en[3] - (RW) DCM off mode
    cr_conn_infra_aclk_ctrl_clkslow_en[4] - (RW) DCM slow mode
    cr_conn_infra_aclk_ctrl_force_clkoff[5] - (RW) DCM force off
    cr_conn_infra_aclk_ctrl_force_clkslow[6] - (RW) DCM force slow
    cr_conn_infra_aclk_ctrl_force_on[7] - (RW) DCM force free run
    cr_conn_infra_aclk_ctrl_fsel[12..8] - (RW) normal mode clk_out freq
                                     [12] = 1: div1
                                     [11] = 1: div2
                                     [10] = 1: div4
                                     [9] = 1: div8
                                     [8] = 1: div16
    cr_conn_infra_aclk_ctrl_sfsel[17..13] - (RW) slow mode clk_out freq
                                     [17] = 1: div1
                                     [16] = 1: div2
                                     [15] = 1: div4
                                     [14] = 1: div8
                                     [13] = 1: div16
    RESERVED18[31..18]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_cr_conn_infra_aclk_ctrl_sfsel_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_cr_conn_infra_aclk_ctrl_sfsel_MASK 0x0003E000                // cr_conn_infra_aclk_ctrl_sfsel[17..13]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_cr_conn_infra_aclk_ctrl_sfsel_SHFT 13
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_cr_conn_infra_aclk_ctrl_fsel_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_cr_conn_infra_aclk_ctrl_fsel_MASK 0x00001F00                // cr_conn_infra_aclk_ctrl_fsel[12..8]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_cr_conn_infra_aclk_ctrl_fsel_SHFT 8
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_cr_conn_infra_aclk_ctrl_force_on_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_cr_conn_infra_aclk_ctrl_force_on_MASK 0x00000080                // cr_conn_infra_aclk_ctrl_force_on[7]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_cr_conn_infra_aclk_ctrl_force_on_SHFT 7
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_cr_conn_infra_aclk_ctrl_force_clkslow_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_cr_conn_infra_aclk_ctrl_force_clkslow_MASK 0x00000040                // cr_conn_infra_aclk_ctrl_force_clkslow[6]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_cr_conn_infra_aclk_ctrl_force_clkslow_SHFT 6
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_cr_conn_infra_aclk_ctrl_force_clkoff_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_cr_conn_infra_aclk_ctrl_force_clkoff_MASK 0x00000020                // cr_conn_infra_aclk_ctrl_force_clkoff[5]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_cr_conn_infra_aclk_ctrl_force_clkoff_SHFT 5
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_cr_conn_infra_aclk_ctrl_clkslow_en_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_cr_conn_infra_aclk_ctrl_clkslow_en_MASK 0x00000010                // cr_conn_infra_aclk_ctrl_clkslow_en[4]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_cr_conn_infra_aclk_ctrl_clkslow_en_SHFT 4
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_cr_conn_infra_aclk_ctrl_clkoff_en_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_cr_conn_infra_aclk_ctrl_clkoff_en_MASK 0x00000008                // cr_conn_infra_aclk_ctrl_clkoff_en[3]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_cr_conn_infra_aclk_ctrl_clkoff_en_SHFT 3
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_cr_conn_infra_aclk_clock_group_ctrl_pllck_sel_2_clk_rdy_on_dcm_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_cr_conn_infra_aclk_clock_group_ctrl_pllck_sel_2_clk_rdy_on_dcm_MASK 0x00000004                // cr_conn_infra_aclk_clock_group_ctrl_pllck_sel_2_clk_rdy_on_dcm[2]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_cr_conn_infra_aclk_clock_group_ctrl_pllck_sel_2_clk_rdy_on_dcm_SHFT 2
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_cr_conn_infra_aclk_clock_group_ctrl_pllck_sel_no_spm_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_cr_conn_infra_aclk_clock_group_ctrl_pllck_sel_no_spm_MASK 0x00000002                // cr_conn_infra_aclk_clock_group_ctrl_pllck_sel_no_spm[1]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_cr_conn_infra_aclk_clock_group_ctrl_pllck_sel_no_spm_SHFT 1
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_cr_conn_infra_aclk_clock_group_ctrl_sc_axi_dcm_dis_en_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_cr_conn_infra_aclk_clock_group_ctrl_sc_axi_dcm_dis_en_MASK 0x00000001                // cr_conn_infra_aclk_clock_group_ctrl_sc_axi_dcm_dis_en[0]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_3_cr_conn_infra_aclk_clock_group_ctrl_sc_axi_dcm_dis_en_SHFT 0

/* =====================================================================================

  ---ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_4 (0x1800E000 + 0x01C)---

    cr_conn_infra_aclk_dbc_ctrl_dbc_num[11..0] - (RW)  xxx 
    cr_conn_infra_aclk_dbc_ctrl_dbc_en[12] - (RW)  xxx 
    ro_conn_infra_aclk_dcm_idle[13] - (RO)  xxx 
    ro_conn_infra_aclk_dcm_rdy_on[14] - (RO)  xxx 
    cr_conn_infra_aclk_sc_axi_dcm_dis[15] - (RW)  xxx 
    cr_force_on_conn_infra_aclk_dcm[16] - (RW)  xxx 
    RESERVED17[31..17]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_4_cr_force_on_conn_infra_aclk_dcm_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_4_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_4_cr_force_on_conn_infra_aclk_dcm_MASK 0x00010000                // cr_force_on_conn_infra_aclk_dcm[16]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_4_cr_force_on_conn_infra_aclk_dcm_SHFT 16
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_4_cr_conn_infra_aclk_sc_axi_dcm_dis_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_4_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_4_cr_conn_infra_aclk_sc_axi_dcm_dis_MASK 0x00008000                // cr_conn_infra_aclk_sc_axi_dcm_dis[15]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_4_cr_conn_infra_aclk_sc_axi_dcm_dis_SHFT 15
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_4_ro_conn_infra_aclk_dcm_rdy_on_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_4_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_4_ro_conn_infra_aclk_dcm_rdy_on_MASK 0x00004000                // ro_conn_infra_aclk_dcm_rdy_on[14]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_4_ro_conn_infra_aclk_dcm_rdy_on_SHFT 14
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_4_ro_conn_infra_aclk_dcm_idle_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_4_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_4_ro_conn_infra_aclk_dcm_idle_MASK 0x00002000                // ro_conn_infra_aclk_dcm_idle[13]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_4_ro_conn_infra_aclk_dcm_idle_SHFT 13
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_4_cr_conn_infra_aclk_dbc_ctrl_dbc_en_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_4_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_4_cr_conn_infra_aclk_dbc_ctrl_dbc_en_MASK 0x00001000                // cr_conn_infra_aclk_dbc_ctrl_dbc_en[12]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_4_cr_conn_infra_aclk_dbc_ctrl_dbc_en_SHFT 12
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_4_cr_conn_infra_aclk_dbc_ctrl_dbc_num_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_4_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_4_cr_conn_infra_aclk_dbc_ctrl_dbc_num_MASK 0x00000FFF                // cr_conn_infra_aclk_dbc_ctrl_dbc_num[11..0]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_VDNR_GLUE_DCM_CTL_4_cr_conn_infra_aclk_dbc_ctrl_dbc_num_SHFT 0

/* =====================================================================================

  ---CONN_VON_IDLE_MASK (0x1800E000 + 0x100)---

    cr_von_bus_idle_mask[31..0]  - (RW)  xxx 

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_VON_IDLE_MASK_cr_von_bus_idle_mask_ADDR CONN_BUS_CR_ON_CONN_VON_IDLE_MASK_ADDR
#define CONN_BUS_CR_ON_CONN_VON_IDLE_MASK_cr_von_bus_idle_mask_MASK 0xFFFFFFFF                // cr_von_bus_idle_mask[31..0]
#define CONN_BUS_CR_ON_CONN_VON_IDLE_MASK_cr_von_bus_idle_mask_SHFT 0

/* =====================================================================================

  ---CONN_VON_BUS_IDLE_DEBOUNCE (0x1800E000 + 0x104)---

    cr_von_bus_idle_debounce[4..0] - (RW)  xxx 
    RESERVED5[31..5]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_VON_BUS_IDLE_DEBOUNCE_cr_von_bus_idle_debounce_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_IDLE_DEBOUNCE_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_IDLE_DEBOUNCE_cr_von_bus_idle_debounce_MASK 0x0000001F                // cr_von_bus_idle_debounce[4..0]
#define CONN_BUS_CR_ON_CONN_VON_BUS_IDLE_DEBOUNCE_cr_von_bus_idle_debounce_SHFT 0

/* =====================================================================================

  ---CONN_VON_BUS_TIMEOUT_EN (0x1800E000 + 0x108)---

    CR_CONN_VON_VDNR_GLUE_BUS_S2P_N6_TIMEOUT_EN[0] - (RW)  xxx 
    CR_CONN_VON_VDNR_GLUE_BUS_P_D_N54_57_TIMEOUT_EN[1] - (RW)  xxx 
    RESERVED2[31..2]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_EN_CR_CONN_VON_VDNR_GLUE_BUS_P_D_N54_57_TIMEOUT_EN_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_EN_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_EN_CR_CONN_VON_VDNR_GLUE_BUS_P_D_N54_57_TIMEOUT_EN_MASK 0x00000002                // CR_CONN_VON_VDNR_GLUE_BUS_P_D_N54_57_TIMEOUT_EN[1]
#define CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_EN_CR_CONN_VON_VDNR_GLUE_BUS_P_D_N54_57_TIMEOUT_EN_SHFT 1
#define CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_EN_CR_CONN_VON_VDNR_GLUE_BUS_S2P_N6_TIMEOUT_EN_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_EN_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_EN_CR_CONN_VON_VDNR_GLUE_BUS_S2P_N6_TIMEOUT_EN_MASK 0x00000001                // CR_CONN_VON_VDNR_GLUE_BUS_S2P_N6_TIMEOUT_EN[0]
#define CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_EN_CR_CONN_VON_VDNR_GLUE_BUS_S2P_N6_TIMEOUT_EN_SHFT 0

/* =====================================================================================

  ---CONN_VON_BUS_TIMEOUT_THRE (0x1800E000 + 0x10C)---

    CR_CONN_VON_VDNR_GLUE_BUS_S2P_N6_TIMEOUT_LIMIT[7..0] - (RW)  xxx 
    CR_CONN_VON_VDNR_GLUE_BUS_P_D_N54_57_TIMEOUT_LIMIT[15..8] - (RW)  xxx 
    RESERVED16[31..16]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_THRE_CR_CONN_VON_VDNR_GLUE_BUS_P_D_N54_57_TIMEOUT_LIMIT_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_THRE_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_THRE_CR_CONN_VON_VDNR_GLUE_BUS_P_D_N54_57_TIMEOUT_LIMIT_MASK 0x0000FF00                // CR_CONN_VON_VDNR_GLUE_BUS_P_D_N54_57_TIMEOUT_LIMIT[15..8]
#define CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_THRE_CR_CONN_VON_VDNR_GLUE_BUS_P_D_N54_57_TIMEOUT_LIMIT_SHFT 8
#define CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_THRE_CR_CONN_VON_VDNR_GLUE_BUS_S2P_N6_TIMEOUT_LIMIT_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_THRE_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_THRE_CR_CONN_VON_VDNR_GLUE_BUS_S2P_N6_TIMEOUT_LIMIT_MASK 0x000000FF                // CR_CONN_VON_VDNR_GLUE_BUS_S2P_N6_TIMEOUT_LIMIT[7..0]
#define CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_THRE_CR_CONN_VON_VDNR_GLUE_BUS_S2P_N6_TIMEOUT_LIMIT_SHFT 0

/* =====================================================================================

  ---CONN_VON_BUS_TIMEOUT_CLR (0x1800E000 + 0x110)---

    CR_CONN_VON_VDNR_GLUE_BUS_S2P_N6_TIMEOUT_CLEAR[0] - (RW)  xxx 
    CR_CONN_VON_VDNR_GLUE_BUS_P_D_N54_57_TIMEOUT_CLEAR[1] - (RW)  xxx 
    RESERVED2[31..2]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_CLR_CR_CONN_VON_VDNR_GLUE_BUS_P_D_N54_57_TIMEOUT_CLEAR_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_CLR_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_CLR_CR_CONN_VON_VDNR_GLUE_BUS_P_D_N54_57_TIMEOUT_CLEAR_MASK 0x00000002                // CR_CONN_VON_VDNR_GLUE_BUS_P_D_N54_57_TIMEOUT_CLEAR[1]
#define CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_CLR_CR_CONN_VON_VDNR_GLUE_BUS_P_D_N54_57_TIMEOUT_CLEAR_SHFT 1
#define CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_CLR_CR_CONN_VON_VDNR_GLUE_BUS_S2P_N6_TIMEOUT_CLEAR_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_CLR_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_CLR_CR_CONN_VON_VDNR_GLUE_BUS_S2P_N6_TIMEOUT_CLEAR_MASK 0x00000001                // CR_CONN_VON_VDNR_GLUE_BUS_S2P_N6_TIMEOUT_CLEAR[0]
#define CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_CLR_CR_CONN_VON_VDNR_GLUE_BUS_S2P_N6_TIMEOUT_CLEAR_SHFT 0

/* =====================================================================================

  ---CONN_VON_BUS_TIMEOUT_IRQ (0x1800E000 + 0x114)---

    CONN_VON_VDNR_GLUE_BUS_S2P_N6_TIMEOUT_IRQ[0] - (RO)  xxx 
    CONN_VON_VDNR_GLUE_BUS_P_D_N54_57_TIMEOUT_IRQ[1] - (RO)  xxx 
    RESERVED2[31..2]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_IRQ_CONN_VON_VDNR_GLUE_BUS_P_D_N54_57_TIMEOUT_IRQ_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_IRQ_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_IRQ_CONN_VON_VDNR_GLUE_BUS_P_D_N54_57_TIMEOUT_IRQ_MASK 0x00000002                // CONN_VON_VDNR_GLUE_BUS_P_D_N54_57_TIMEOUT_IRQ[1]
#define CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_IRQ_CONN_VON_VDNR_GLUE_BUS_P_D_N54_57_TIMEOUT_IRQ_SHFT 1
#define CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_IRQ_CONN_VON_VDNR_GLUE_BUS_S2P_N6_TIMEOUT_IRQ_ADDR CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_IRQ_ADDR
#define CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_IRQ_CONN_VON_VDNR_GLUE_BUS_S2P_N6_TIMEOUT_IRQ_MASK 0x00000001                // CONN_VON_VDNR_GLUE_BUS_S2P_N6_TIMEOUT_IRQ[0]
#define CONN_BUS_CR_ON_CONN_VON_BUS_TIMEOUT_IRQ_CONN_VON_VDNR_GLUE_BUS_S2P_N6_TIMEOUT_IRQ_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_ON_BUS_EN (0x1800E000 + 0x118)---

    CR_CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_EN[0] - (RW)  xxx 
    CR_CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_EN[1] - (RW)  xxx 
    RESERVED2[31..2]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_EN_CR_CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_EN_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_EN_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_EN_CR_CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_EN_MASK 0x00000002                // CR_CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_EN[1]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_EN_CR_CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_EN_SHFT 1
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_EN_CR_CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_EN_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_EN_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_EN_CR_CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_EN_MASK 0x00000001                // CR_CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_EN[0]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_EN_CR_CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_EN_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_ON_BUS_THRE (0x1800E000 + 0x11C)---

    CR_CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_LIMIT[7..0] - (RW)  xxx 
    CR_CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_LIMIT[15..8] - (RW)  xxx 
    RESERVED16[31..16]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_THRE_CR_CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_LIMIT_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_THRE_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_THRE_CR_CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_LIMIT_MASK 0x0000FF00                // CR_CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_LIMIT[15..8]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_THRE_CR_CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_LIMIT_SHFT 8
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_THRE_CR_CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_LIMIT_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_THRE_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_THRE_CR_CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_LIMIT_MASK 0x000000FF                // CR_CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_LIMIT[7..0]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_THRE_CR_CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_LIMIT_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_ON_BUS_CLR (0x1800E000 + 0x120)---

    CR_CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_CLEAR[0] - (RW)  xxx 
    CR_CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_CLEAR[1] - (RW)  xxx 
    RESERVED2[31..2]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_CLR_CR_CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_CLEAR_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_CLR_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_CLR_CR_CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_CLEAR_MASK 0x00000002                // CR_CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_CLEAR[1]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_CLR_CR_CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_CLEAR_SHFT 1
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_CLR_CR_CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_CLEAR_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_CLR_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_CLR_CR_CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_CLEAR_MASK 0x00000001                // CR_CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_CLEAR[0]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_CLR_CR_CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_CLEAR_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_ON_BUS_IRQ (0x1800E000 + 0x124)---

    CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_IRQ[0] - (RO)  xxx 
    CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_IRQ[1] - (RO)  xxx 
    RESERVED2[31..2]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_IRQ_CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_IRQ_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_IRQ_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_IRQ_CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_IRQ_MASK 0x00000002                // CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_IRQ[1]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_IRQ_CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_IRQ_SHFT 1
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_IRQ_CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_IRQ_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_IRQ_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_IRQ_CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_IRQ_MASK 0x00000001                // CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_IRQ[0]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_BUS_IRQ_CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_IRQ_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_ON_P_D_N7_TIMEOUT_INFO_0 (0x1800E000 + 0x128)---

    CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_INFO_31_0[31..0] - (RO)  xxx 

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N7_TIMEOUT_INFO_0_CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_INFO_31_0_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N7_TIMEOUT_INFO_0_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N7_TIMEOUT_INFO_0_CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_INFO_31_0_MASK 0xFFFFFFFF                // CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_INFO_31_0[31..0]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N7_TIMEOUT_INFO_0_CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_INFO_31_0_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_ON_P_D_N7_TIMEOUT_INFO_1 (0x1800E000 + 0x12C)---

    CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_INFO_33_32[1..0] - (RO)  xxx 
    RESERVED2[31..2]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N7_TIMEOUT_INFO_1_CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_INFO_33_32_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N7_TIMEOUT_INFO_1_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N7_TIMEOUT_INFO_1_CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_INFO_33_32_MASK 0x00000003                // CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_INFO_33_32[1..0]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N7_TIMEOUT_INFO_1_CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_INFO_33_32_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_ON_P_D_N7_TIMEOUT_ADDR (0x1800E000 + 0x130)---

    CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_ADDR[31..0] - (RO)  xxx 

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N7_TIMEOUT_ADDR_CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_ADDR_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N7_TIMEOUT_ADDR_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N7_TIMEOUT_ADDR_CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_ADDR_MASK 0xFFFFFFFF                // CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_ADDR[31..0]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N7_TIMEOUT_ADDR_CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_ADDR_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_ON_P_D_N7_TIMEOUT_WDATA (0x1800E000 + 0x134)---

    CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_WDATA[31..0] - (RO)  xxx 

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N7_TIMEOUT_WDATA_CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_WDATA_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N7_TIMEOUT_WDATA_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N7_TIMEOUT_WDATA_CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_WDATA_MASK 0xFFFFFFFF                // CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_WDATA[31..0]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N7_TIMEOUT_WDATA_CONN_INFRA_VDNR_GLUE_ON_P_D_N7_TIMEOUT_WDATA_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_ON_P_D_N9_TIMEOUT_INFO (0x1800E000 + 0x138)---

    CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_INFO[31..0] - (RO)  xxx 

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N9_TIMEOUT_INFO_CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_INFO_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N9_TIMEOUT_INFO_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N9_TIMEOUT_INFO_CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_INFO_MASK 0xFFFFFFFF                // CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_INFO[31..0]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N9_TIMEOUT_INFO_CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_INFO_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_ON_P_D_N9_TIMEOUT_ADDR (0x1800E000 + 0x13C)---

    CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_ADDR[31..0] - (RO)  xxx 

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N9_TIMEOUT_ADDR_CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_ADDR_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N9_TIMEOUT_ADDR_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N9_TIMEOUT_ADDR_CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_ADDR_MASK 0xFFFFFFFF                // CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_ADDR[31..0]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N9_TIMEOUT_ADDR_CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_ADDR_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_ON_P_D_N9_TIMEOUT_WDATA (0x1800E000 + 0x140)---

    CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_WDATA[31..0] - (RO)  xxx 

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N9_TIMEOUT_WDATA_CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_WDATA_ADDR CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N9_TIMEOUT_WDATA_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N9_TIMEOUT_WDATA_CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_WDATA_MASK 0xFFFFFFFF                // CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_WDATA[31..0]
#define CONN_BUS_CR_ON_CONN_INFRA_ON_P_D_N9_TIMEOUT_WDATA_CONN_INFRA_VDNR_GLUE_ON_P_D_N9_TIMEOUT_WDATA_SHFT 0

/* =====================================================================================

  ---ADDR_CONN_INFRA_APB_SLV_ACCESS_DETECT_EN (0x1800E000 + 0x200)---

    cr_conn_infra_apb_slv_access_detect_en[0] - (RW)  xxx 
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_APB_SLV_ACCESS_DETECT_EN_cr_conn_infra_apb_slv_access_detect_en_ADDR CONN_BUS_CR_ON_ADDR_CONN_INFRA_APB_SLV_ACCESS_DETECT_EN_ADDR
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_APB_SLV_ACCESS_DETECT_EN_cr_conn_infra_apb_slv_access_detect_en_MASK 0x00000001                // cr_conn_infra_apb_slv_access_detect_en[0]
#define CONN_BUS_CR_ON_ADDR_CONN_INFRA_APB_SLV_ACCESS_DETECT_EN_cr_conn_infra_apb_slv_access_detect_en_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_CKSYS_CK_CTRL (0x1800E000 + 0x320)---

    cr_host_ck_request_hw_mode[0] - (RW)  xxx 
    cr_host_ck_request_sw_en[1]  - (RW)  xxx 
    RESERVED2[31..2]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_CKSYS_CK_CTRL_cr_host_ck_request_sw_en_ADDR CONN_BUS_CR_ON_CONN_INFRA_CKSYS_CK_CTRL_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_CKSYS_CK_CTRL_cr_host_ck_request_sw_en_MASK 0x00000002                // cr_host_ck_request_sw_en[1]
#define CONN_BUS_CR_ON_CONN_INFRA_CKSYS_CK_CTRL_cr_host_ck_request_sw_en_SHFT 1
#define CONN_BUS_CR_ON_CONN_INFRA_CKSYS_CK_CTRL_cr_host_ck_request_hw_mode_ADDR CONN_BUS_CR_ON_CONN_INFRA_CKSYS_CK_CTRL_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_CKSYS_CK_CTRL_cr_host_ck_request_hw_mode_MASK 0x00000001                // cr_host_ck_request_hw_mode[0]
#define CONN_BUS_CR_ON_CONN_INFRA_CKSYS_CK_CTRL_cr_host_ck_request_hw_mode_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_SECURITY_CTRL (0x1800E000 + 0x500)---

    CR_CONN_INFRA_SECURITY_LOCK[0] - (RW)  xxx 
    CR_CONN_INFRA_SECURITY_PROTECT_EN[1] - (RW)  xxx 
    CR_CONN_INFRA_CHECK_HSECURE_B_EN[2] - (RW)  xxx 
    CR_CONN_INFRA_CHECK_DOMAIN_EN[3] - (RW)  xxx 
    CR_CONN_INFRA_SECURITY_PROTECT_DOMAIN_ID[7..4] - (RW)  xxx 
    RESERVED8[31..8]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_CONN_INFRA_SECURITY_CTRL_CR_CONN_INFRA_SECURITY_PROTECT_DOMAIN_ID_ADDR CONN_BUS_CR_ON_CONN_INFRA_SECURITY_CTRL_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_SECURITY_CTRL_CR_CONN_INFRA_SECURITY_PROTECT_DOMAIN_ID_MASK 0x000000F0                // CR_CONN_INFRA_SECURITY_PROTECT_DOMAIN_ID[7..4]
#define CONN_BUS_CR_ON_CONN_INFRA_SECURITY_CTRL_CR_CONN_INFRA_SECURITY_PROTECT_DOMAIN_ID_SHFT 4
#define CONN_BUS_CR_ON_CONN_INFRA_SECURITY_CTRL_CR_CONN_INFRA_CHECK_DOMAIN_EN_ADDR CONN_BUS_CR_ON_CONN_INFRA_SECURITY_CTRL_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_SECURITY_CTRL_CR_CONN_INFRA_CHECK_DOMAIN_EN_MASK 0x00000008                // CR_CONN_INFRA_CHECK_DOMAIN_EN[3]
#define CONN_BUS_CR_ON_CONN_INFRA_SECURITY_CTRL_CR_CONN_INFRA_CHECK_DOMAIN_EN_SHFT 3
#define CONN_BUS_CR_ON_CONN_INFRA_SECURITY_CTRL_CR_CONN_INFRA_CHECK_HSECURE_B_EN_ADDR CONN_BUS_CR_ON_CONN_INFRA_SECURITY_CTRL_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_SECURITY_CTRL_CR_CONN_INFRA_CHECK_HSECURE_B_EN_MASK 0x00000004                // CR_CONN_INFRA_CHECK_HSECURE_B_EN[2]
#define CONN_BUS_CR_ON_CONN_INFRA_SECURITY_CTRL_CR_CONN_INFRA_CHECK_HSECURE_B_EN_SHFT 2
#define CONN_BUS_CR_ON_CONN_INFRA_SECURITY_CTRL_CR_CONN_INFRA_SECURITY_PROTECT_EN_ADDR CONN_BUS_CR_ON_CONN_INFRA_SECURITY_CTRL_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_SECURITY_CTRL_CR_CONN_INFRA_SECURITY_PROTECT_EN_MASK 0x00000002                // CR_CONN_INFRA_SECURITY_PROTECT_EN[1]
#define CONN_BUS_CR_ON_CONN_INFRA_SECURITY_CTRL_CR_CONN_INFRA_SECURITY_PROTECT_EN_SHFT 1
#define CONN_BUS_CR_ON_CONN_INFRA_SECURITY_CTRL_CR_CONN_INFRA_SECURITY_LOCK_ADDR CONN_BUS_CR_ON_CONN_INFRA_SECURITY_CTRL_ADDR
#define CONN_BUS_CR_ON_CONN_INFRA_SECURITY_CTRL_CR_CONN_INFRA_SECURITY_LOCK_MASK 0x00000001                // CR_CONN_INFRA_SECURITY_LOCK[0]
#define CONN_BUS_CR_ON_CONN_INFRA_SECURITY_CTRL_CR_CONN_INFRA_SECURITY_LOCK_SHFT 0

/* =====================================================================================

  ---ADDR_AP2CONN_AHB_GALS_CFG (0x1800E000 + 0xA00)---

    conn_infra_top2conn_gals_rx_rg_afifo_sync_sel[1..0] - (RW) specify synchronizer depth
                                     00: 2 stage
                                     01: 3 stage
                                     10: 4 stage
                                     11: 4 stage
    RESERVED2[31..2]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_BUS_CR_ON_ADDR_AP2CONN_AHB_GALS_CFG_conn_infra_top2conn_gals_rx_rg_afifo_sync_sel_ADDR CONN_BUS_CR_ON_ADDR_AP2CONN_AHB_GALS_CFG_ADDR
#define CONN_BUS_CR_ON_ADDR_AP2CONN_AHB_GALS_CFG_conn_infra_top2conn_gals_rx_rg_afifo_sync_sel_MASK 0x00000003                // conn_infra_top2conn_gals_rx_rg_afifo_sync_sel[1..0]
#define CONN_BUS_CR_ON_ADDR_AP2CONN_AHB_GALS_CFG_conn_infra_top2conn_gals_rx_rg_afifo_sync_sel_SHFT 0

/* =====================================================================================

  ---ADDR_AP2CONN_AHB_GALS_DBG (0x1800E000 + 0xA04)---

    conn_infra_top2conn_gals_rx_debug_out[31..0] - (RO)  xxx 

 =====================================================================================*/
#define CONN_BUS_CR_ON_ADDR_AP2CONN_AHB_GALS_DBG_conn_infra_top2conn_gals_rx_debug_out_ADDR CONN_BUS_CR_ON_ADDR_AP2CONN_AHB_GALS_DBG_ADDR
#define CONN_BUS_CR_ON_ADDR_AP2CONN_AHB_GALS_DBG_conn_infra_top2conn_gals_rx_debug_out_MASK 0xFFFFFFFF                // conn_infra_top2conn_gals_rx_debug_out[31..0]
#define CONN_BUS_CR_ON_ADDR_AP2CONN_AHB_GALS_DBG_conn_infra_top2conn_gals_rx_debug_out_SHFT 0

#ifdef __cplusplus
}
#endif

#endif // __CONN_BUS_CR_ON_REGS_H__
