/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2018 MediaTek Inc.
 *
 * Author: Daniel Huang <daniel.huang@mediatek.com>
 *
 */

#ifndef _MTK_IMGSYS_CMDQ_PLAT_8_H_
#define _MTK_IMGSYS_CMDQ_PLAT_8_H_

#include "mtk_imgsys-cmdq.h"
#include "mtk_imgsys-engine-isp8.h"

#define IMGSYS_QOS_SET_BY_SCEN (1)

#define IMGSYS_SECURE_ENABLE   (1)

#ifdef GCE_SUPPORT_REPLACE_MODE
#undef GCE_SUPPORT_REPLACE_MODE
#endif
#define GCE_SUPPORT_REPLACE_MODE    (0)

/* Record info definitions */
#define GCE_REC_MAX_FRAME_BLOCK     (20)
#define GCE_REC_MAX_TILE_BLOCK      (20)
#if GCE_SUPPORT_REPLACE_MODE
#define GCE_REC_MAX_LABEL_COUNT     (2048)
#endif

enum ISP8_IMG_PWR {
	ISP8_PWR_START = 0,
	ISP8_PWR_DIP = ISP8_PWR_START,
	ISP8_PWR_TRAW,
	ISP8_PWR_WPE_1_EIS,
	ISP8_PWR_WPE_2_TNR,
	ISP8_PWR_WPE_3_LITE,
	ISP8_PWR_NUM
};

#define IMGSYS_NOR_THD			(13)
#define	IMGSYS_PWR_THD			(5)
#define IMGSYS_QOS_THD			(1)
#define IMGSYS_SEC_THD			(1)

#define PRE_PWR_ON_2 (1UL << 4)
#define PRE_PWR_ON_3 (1UL << 5)
#define PRE_PWR_OFF_2 (1UL << 6)
#define PRE_PWR_OFF_3 (1UL << 7)

#define IMGSYS_QOS_MAX 56
#define IMGSYS_MAX_FPS 60

#define IMGSYS_VSS_FREQ_FLOOR	660000000
#define IMGSYS_SMVR_FREQ_FLOOR1	312000000
#define IMGSYS_SMVR_FREQ_FLOOR2	416000000
#define IMGSYS_SMVR_FREQ_FLOOR3	546000000
#define IMGSYS_SMVR_FREQ_FLOOR4	660000000
#define IMGSYS_SMVR_FPS_FLOOR1	120
#define IMGSYS_SMVR_FPS_FLOOR2	240
#define IMGSYS_SMVR_FPS_FLOOR3	480
#define IMGSYS_SMVR_FPS_FLOOR4	960
#define IMGSYS_SMVR_SIZE_FLOOR1	(192*112)
#define IMGSYS_SMVR_SIZE_FLOOR2	(288*176)
#define IMGSYS_SMVR_SIZE_FLOOR3	(576*336)

#define IMGSYS_CMDQ_HW_TOKEN_BEGIN	665
#define IMGSYS_CMDQ_HW_TOKEN_END	680
#define IMGSYS_CMDQ_SW_EVENT1_BEGIN	514
#define IMGSYS_CMDQ_SW_EVENT1_END	646
#define IMGSYS_CMDQ_SW_EVENT2_BEGIN	694
#define IMGSYS_CMDQ_SW_EVENT2_END	711
#define IMGSYS_CMDQ_SW_EVENT3_BEGIN	714
#define IMGSYS_CMDQ_SW_EVENT3_END	767
#define IMGSYS_CMDQ_SW_EVENT4_BEGIN	784
#define IMGSYS_CMDQ_SW_EVENT4_END	799
#define IMGSYS_CMDQ_SW_EVENT5_BEGIN	833
#define IMGSYS_CMDQ_SW_EVENT5_END	861
#define IMGSYS_CMDQ_SW_EVENT6_BEGIN	901
#define IMGSYS_CMDQ_SW_EVENT6_END	950
#define IMGSYS_CMDQ_GPR_EVENT_BEGIN	997
#define IMGSYS_CMDQ_GPR_EVENT_END	1006
#define IMGSYS_CMDQ_SYNC_POOL_NUM	300
#define IMGSYS_CMDQ_QOF_EVENT_BEGIN	862
#define IMGSYS_CMDQ_QOF_EVENT_END	873
#define IMGSYS_CMDQ_VSDOF_EVENT_BEGIN	874
#define IMGSYS_CMDQ_VSDOF_EVENT_END	889
/* TODO */
#define WPE_SMI_PORT_NUM	8
#define ME_SMI_PORT_NUM	2
#define PQ_DIP_SMI_PORT_NUM	6
#define TRAW_SMI_PORT_NUM	18
#define LTRAW_SMI_PORT_NUM	7
#define XTRAW_SMI_PORT_NUM	16
#define DIP_SMI_PORT_NUM	39
#define DIP0_SMI_PORT_NUM	20
#define DIP1_SMI_PORT_NUM	19
#define ADL_SMI_PORT_NUM	2


#define IMGSYS_QOS_FHD_SIZE		(1920*1080/2)
#define IMGSYS_QOS_4K_SIZE		(4000*2000/2)
#define IMGSYS_QOS_FHD_30_BW_0	0//1328
#define IMGSYS_QOS_FHD_30_BW_1	0//905
#define IMGSYS_QOS_FHD_60_BW_0	2458
#define IMGSYS_QOS_FHD_60_BW_1	1355
#define IMGSYS_QOS_4K_30_BW_0	0//2350
#define IMGSYS_QOS_4K_30_BW_1	0//1258
#define IMGSYS_QOS_4K_60_BW_0	2244
#define IMGSYS_QOS_4K_60_BW_1	2360

#define IMGSYS_CMDQ_CBPARAM_NUM	(90*5)

#define IMGSYS_POLL_TIME_10MS	(0x341)
#define IMGSYS_POLL_TIME_20MS	(IMGSYS_POLL_TIME_10MS*2)
#define IMGSYS_POLL_TIME_30MS	(IMGSYS_POLL_TIME_10MS*3)
#define IMGSYS_POLL_TIME_40MS	(IMGSYS_POLL_TIME_10MS*4)
#define IMGSYS_POLL_TIME_50MS	(IMGSYS_POLL_TIME_10MS*5)
#define IMGSYS_POLL_TIME_INFINI	(0xFFFF)

#define IMGSYS_IMG_CLK_LV1		660000000
#define IMGSYS_IMG_CLK_LV2		550000000
#define IMGSYS_IMG_CLK_LV3		416000000
#define IMGSYS_IMG_CLK_LV4		312000000
#define IMGSYS_SMI_CLK_LV1		624000000
#define IMGSYS_SMI_CLK_LV2		458000000
#define IMGSYS_SMI_CLK_LV3		364000000
#define IMGSYS_SMI_CLK_LV4		218000000

enum mtk_imgsys_event {
	/* HW event */
	IMGSYS_CMDQ_EVENT_IMG_TRAW0_CQ_THR_DONE_TRAW0_0 = 0,
	IMGSYS_CMDQ_EVENT_IMG_TRAW0_CQ_THR_DONE_TRAW0_1,
	IMGSYS_CMDQ_EVENT_IMG_TRAW0_CQ_THR_DONE_TRAW0_2,
	IMGSYS_CMDQ_EVENT_IMG_TRAW0_CQ_THR_DONE_TRAW0_3,
	IMGSYS_CMDQ_EVENT_IMG_TRAW0_CQ_THR_DONE_TRAW0_4,
	IMGSYS_CMDQ_EVENT_IMG_TRAW0_CQ_THR_DONE_TRAW0_5,
	IMGSYS_CMDQ_EVENT_IMG_TRAW1_CQ_THR_DONE_TRAW0_0,
	IMGSYS_CMDQ_EVENT_IMG_TRAW1_CQ_THR_DONE_TRAW0_1,
	IMGSYS_CMDQ_EVENT_IMG_TRAW1_CQ_THR_DONE_TRAW0_2,
	IMGSYS_CMDQ_EVENT_IMG_TRAW1_CQ_THR_DONE_TRAW0_3,
	IMGSYS_CMDQ_EVENT_IMG_TRAW1_CQ_THR_DONE_TRAW0_4,
	IMGSYS_CMDQ_EVENT_IMG_TRAW1_CQ_THR_DONE_TRAW0_5,
	IMGSYS_CMDQ_EVENT_IMG_DIP_CQ_THR_DONE_P2_0,
	IMGSYS_CMDQ_EVENT_IMG_DIP_CQ_THR_DONE_P2_1,
	IMGSYS_CMDQ_EVENT_IMG_DIP_CQ_THR_DONE_P2_2,
	IMGSYS_CMDQ_EVENT_IMG_DIP_CQ_THR_DONE_P2_3,
	IMGSYS_CMDQ_EVENT_IMG_DIP_CQ_THR_DONE_P2_4,
	IMGSYS_CMDQ_EVENT_IMG_DIP_CQ_THR_DONE_P2_5,
	IMGSYS_CMDQ_EVENT_IMG_PQDIP_A_CQ_THR_DONE_P2_0,
	IMGSYS_CMDQ_EVENT_IMG_PQDIP_A_CQ_THR_DONE_P2_1,
	IMGSYS_CMDQ_EVENT_IMG_PQDIP_A_CQ_THR_DONE_P2_2,
	IMGSYS_CMDQ_EVENT_IMG_PQDIP_A_CQ_THR_DONE_P2_3,
	IMGSYS_CMDQ_EVENT_IMG_PQDIP_A_CQ_THR_DONE_P2_4,
	IMGSYS_CMDQ_EVENT_IMG_PQDIP_A_CQ_THR_DONE_P2_5,
	IMGSYS_CMDQ_EVENT_IMG_PQDIP_B_CQ_THR_DONE_P2_0,
	IMGSYS_CMDQ_EVENT_IMG_PQDIP_B_CQ_THR_DONE_P2_1,
	IMGSYS_CMDQ_EVENT_IMG_PQDIP_B_CQ_THR_DONE_P2_2,
	IMGSYS_CMDQ_EVENT_IMG_PQDIP_B_CQ_THR_DONE_P2_3,
	IMGSYS_CMDQ_EVENT_IMG_PQDIP_B_CQ_THR_DONE_P2_4,
	IMGSYS_CMDQ_EVENT_IMG_PQDIP_B_CQ_THR_DONE_P2_5,
	IMGSYS_CMDQ_EVENT_IMG_WPE_EIS_CQ_THR_DONE_P2_0,
	IMGSYS_CMDQ_EVENT_IMG_WPE_EIS_CQ_THR_DONE_P2_1,
	IMGSYS_CMDQ_EVENT_IMG_WPE_EIS_CQ_THR_DONE_P2_2,
	IMGSYS_CMDQ_EVENT_IMG_WPE_EIS_CQ_THR_DONE_P2_3,
	IMGSYS_CMDQ_EVENT_IMG_WPE_EIS_CQ_THR_DONE_P2_4,
	IMGSYS_CMDQ_EVENT_IMG_WPE_EIS_CQ_THR_DONE_P2_5,
	IMGSYS_CMDQ_EVENT_IMG_OMC_TNR_CQ_THR_DONE_P2_0,
	IMGSYS_CMDQ_EVENT_IMG_OMC_TNR_CQ_THR_DONE_P2_1,
	IMGSYS_CMDQ_EVENT_IMG_OMC_TNR_CQ_THR_DONE_P2_2,
	IMGSYS_CMDQ_EVENT_IMG_OMC_TNR_CQ_THR_DONE_P2_3,
	IMGSYS_CMDQ_EVENT_IMG_OMC_TNR_CQ_THR_DONE_P2_4,
	IMGSYS_CMDQ_EVENT_IMG_OMC_TNR_CQ_THR_DONE_P2_5,
	IMGSYS_CMDQ_EVENT_IMG_WPE_LITE_CQ_THR_DONE_P2_0,
	IMGSYS_CMDQ_EVENT_IMG_WPE_LITE_CQ_THR_DONE_P2_1,
	IMGSYS_CMDQ_EVENT_IMG_WPE_LITE_CQ_THR_DONE_P2_2,
	IMGSYS_CMDQ_EVENT_IMG_WPE_LITE_CQ_THR_DONE_P2_3,
	IMGSYS_CMDQ_EVENT_IMG_WPE_LITE_CQ_THR_DONE_P2_4,
	IMGSYS_CMDQ_EVENT_IMG_WPE_LITE_CQ_THR_DONE_P2_5,
	IMGSYS_CMDQ_EVENT_IMG_OMC_LITE_CQ_THR_DONE_P2_0,
	IMGSYS_CMDQ_EVENT_IMG_OMC_LITE_CQ_THR_DONE_P2_1,
	IMGSYS_CMDQ_EVENT_IMG_OMC_LITE_CQ_THR_DONE_P2_2,
	IMGSYS_CMDQ_EVENT_IMG_OMC_LITE_CQ_THR_DONE_P2_3,
	IMGSYS_CMDQ_EVENT_IMG_OMC_LITE_CQ_THR_DONE_P2_4,
	IMGSYS_CMDQ_EVENT_IMG_OMC_LITE_CQ_THR_DONE_P2_5,
	IMGSYS_CMDQ_EVENT_IMG_IMGSYS_IPE_ME_DONE,
	IMGSYS_CMDQ_EVENT_IMG_ADL_TILE_DONE_EVENT,
	/* SW event */
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_START,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_WPE_EIS = IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_START,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_OMC_TNR,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_WPE_LITE,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_TRAW,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_LTRAW,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_DIP,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_PQDIP_A,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_PQDIP_B,
	IMGSYS_CMDQ_SYNC_TOKEN_IPESYS_ME,
	IMGSYS_CMDQ_SYNC_TOKEN_APUSYS_APU,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_VSS_TRAW,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_VSS_LTRAW,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_VSS_DIP,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_OMC_LITE,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_START,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_1 = IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_START,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_2,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_3,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_4,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_5,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_6,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_7,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_8,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_9,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_10,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_11,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_12,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_13,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_14,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_15,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_16,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_17,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_18,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_19,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_20,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_21,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_22,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_23,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_24,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_25,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_26,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_27,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_28,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_29,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_30,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_31,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_32,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_33,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_34,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_35,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_36,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_37,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_38,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_39,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_40,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_41,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_42,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_43,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_44,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_45,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_46,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_47,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_48,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_49,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_50,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_51,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_52,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_53,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_54,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_55,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_56,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_57,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_58,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_59,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_60,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_61,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_62,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_63,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_64,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_65,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_66,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_67,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_68,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_69,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_70,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_71,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_72,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_73,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_74,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_75,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_76,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_77,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_78,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_79,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_80,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_81,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_82,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_83,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_84,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_85,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_86,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_87,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_88,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_89,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_90,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_91,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_92,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_93,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_94,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_95,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_96,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_97,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_98,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_99,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_100,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_101,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_102,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_103,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_104,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_105,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_106,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_107,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_108,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_109,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_110,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_111,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_112,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_113,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_114,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_115,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_116,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_117,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_118,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_119,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_120,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_121,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_122,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_123,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_124,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_125,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_126,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_127,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_128,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_129,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_130,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_131,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_132,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_133,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_134,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_135,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_136,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_137,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_138,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_139,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_140,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_141,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_142,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_143,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_144,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_145,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_146,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_147,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_148,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_149,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_150,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_151,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_152,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_153,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_154,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_155,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_156,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_157,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_158,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_159,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_160,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_161,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_162,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_163,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_164,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_165,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_166,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_167,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_168,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_169,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_170,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_171,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_172,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_173,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_174,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_175,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_176,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_177,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_178,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_179,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_180,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_181,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_182,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_183,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_184,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_185,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_186,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_187,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_188,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_189,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_190,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_191,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_192,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_193,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_194,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_195,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_196,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_197,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_198,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_199,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_200,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_201,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_202,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_203,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_204,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_205,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_206,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_207,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_208,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_209,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_210,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_211,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_212,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_213,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_214,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_215,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_216,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_217,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_218,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_219,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_220,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_221,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_222,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_223,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_224,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_225,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_226,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_227,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_228,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_229,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_230,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_231,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_232,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_233,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_234,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_235,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_236,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_237,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_238,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_239,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_240,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_241,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_242,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_243,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_244,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_245,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_246,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_247,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_248,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_249,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_250,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_251,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_252,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_253,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_254,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_255,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_256,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_257,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_258,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_259,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_260,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_261,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_262,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_263,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_264,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_265,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_266,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_267,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_268,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_269,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_270,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_271,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_272,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_273,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_274,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_275,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_276,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_277,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_278,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_279,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_280,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_281,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_282,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_283,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_284,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_285,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_286,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_287,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_288,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_289,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_290,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_291,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_292,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_293,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_294,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_295,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_296,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_297,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_298,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_299,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_300,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_END = IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_300,
	IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_1,
	IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_2,
	IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_3,
	IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_4,
	IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_5,
	IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_6,
	IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_7,
	IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_8,
	IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_9,
	IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_10,
	IMGSYS_CMDQ_SYNC_TOKEN_TZMP_ISP_WAIT,
	IMGSYS_CMDQ_SYNC_TOKEN_TZMP_ISP_SET,
	IMGSYS_CMDQ_SYNC_TOKEN_TZMP_ADL_WAIT,
	IMGSYS_CMDQ_SYNC_TOKEN_TZMP_ADL_SET,
	IMGSYS_CMDQ_EVENT_MAX
};

static struct imgsys_event_table imgsys_event[] = {
	/*TRAW frame done*/
	{IMGSYS_CMDQ_EVENT_IMG_TRAW0_CQ_THR_DONE_TRAW0_0, "traw-cq-thread0-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_TRAW0_CQ_THR_DONE_TRAW0_1, "traw-cq-thread1-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_TRAW0_CQ_THR_DONE_TRAW0_2, "traw-cq-thread2-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_TRAW0_CQ_THR_DONE_TRAW0_3, "traw-cq-thread3-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_TRAW0_CQ_THR_DONE_TRAW0_4, "traw-cq-thread4-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_TRAW0_CQ_THR_DONE_TRAW0_5, "traw-cq-thread5-frame-done"},
	/*LTRAW frame done*/
	{IMGSYS_CMDQ_EVENT_IMG_TRAW1_CQ_THR_DONE_TRAW0_0, "ltraw-cq-thread0-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_TRAW1_CQ_THR_DONE_TRAW0_1, "ltraw-cq-thread1-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_TRAW1_CQ_THR_DONE_TRAW0_2, "ltraw-cq-thread2-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_TRAW1_CQ_THR_DONE_TRAW0_3, "ltraw-cq-thread3-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_TRAW1_CQ_THR_DONE_TRAW0_4, "ltraw-cq-thread4-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_TRAW1_CQ_THR_DONE_TRAW0_5, "ltraw-cq-thread5-frame-done"},
	/*DIP frame done*/
	{IMGSYS_CMDQ_EVENT_IMG_DIP_CQ_THR_DONE_P2_0, "dip-cq-thread0-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_DIP_CQ_THR_DONE_P2_1, "dip-cq-thread1-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_DIP_CQ_THR_DONE_P2_2, "dip-cq-thread2-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_DIP_CQ_THR_DONE_P2_3, "dip-cq-thread3-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_DIP_CQ_THR_DONE_P2_4, "dip-cq-thread4-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_DIP_CQ_THR_DONE_P2_5, "dip-cq-thread5-frame-done"},
	/*PQ_DIP_A frame done*/
	{IMGSYS_CMDQ_EVENT_IMG_PQDIP_A_CQ_THR_DONE_P2_0, "pqa-cq-thread0-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_PQDIP_A_CQ_THR_DONE_P2_1, "pqa-cq-thread1-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_PQDIP_A_CQ_THR_DONE_P2_2, "pqa-cq-thread2-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_PQDIP_A_CQ_THR_DONE_P2_3, "pqa-cq-thread3-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_PQDIP_A_CQ_THR_DONE_P2_4, "pqa-cq-thread4-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_PQDIP_A_CQ_THR_DONE_P2_5, "pqa-cq-thread5-frame-done"},
	/*PQ_DIP_B frame done*/
	{IMGSYS_CMDQ_EVENT_IMG_PQDIP_B_CQ_THR_DONE_P2_0, "pqb-cq-thread0-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_PQDIP_B_CQ_THR_DONE_P2_1, "pqb-cq-thread1-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_PQDIP_B_CQ_THR_DONE_P2_2, "pqb-cq-thread2-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_PQDIP_B_CQ_THR_DONE_P2_3, "pqb-cq-thread3-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_PQDIP_B_CQ_THR_DONE_P2_4, "pqb-cq-thread4-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_PQDIP_B_CQ_THR_DONE_P2_5, "pqb-cq-thread5-frame-done"},
	/*WPE_EIS frame done*/
	{IMGSYS_CMDQ_EVENT_IMG_WPE_EIS_CQ_THR_DONE_P2_0, "wpe-eis-cq-thread0-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_EIS_CQ_THR_DONE_P2_1, "wpe-eis-cq-thread1-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_EIS_CQ_THR_DONE_P2_2, "wpe-eis-cq-thread2-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_EIS_CQ_THR_DONE_P2_3, "wpe-eis-cq-thread3-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_EIS_CQ_THR_DONE_P2_4, "wpe-eis-cq-thread4-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_EIS_CQ_THR_DONE_P2_5, "wpe-eis-cq-thread5-frame-done"},
	/*OMC_TNR frame done*/
	{IMGSYS_CMDQ_EVENT_IMG_OMC_TNR_CQ_THR_DONE_P2_0, "omc-tnr-cq-thread0-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_OMC_TNR_CQ_THR_DONE_P2_1, "omc-tnr-cq-thread1-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_OMC_TNR_CQ_THR_DONE_P2_2, "omc-tnr-cq-thread2-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_OMC_TNR_CQ_THR_DONE_P2_3, "omc-tnr-cq-thread3-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_OMC_TNR_CQ_THR_DONE_P2_4, "omc-tnr-cq-thread4-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_OMC_TNR_CQ_THR_DONE_P2_5, "omc-tnr-cq-thread5-frame-done"},
	/*WPE_LITE frame done*/
	{IMGSYS_CMDQ_EVENT_IMG_WPE_LITE_CQ_THR_DONE_P2_0, "wpe-lite-cq-thread0-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_LITE_CQ_THR_DONE_P2_1, "wpe-lite-cq-thread1-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_LITE_CQ_THR_DONE_P2_2, "wpe-lite-cq-thread2-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_LITE_CQ_THR_DONE_P2_3, "wpe-lite-cq-thread3-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_LITE_CQ_THR_DONE_P2_4, "wpe-lite-cq-thread4-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_LITE_CQ_THR_DONE_P2_5, "wpe-lite-cq-thread5-frame-done"},
	/*OMC_LITE frame done*/
	{IMGSYS_CMDQ_EVENT_IMG_OMC_LITE_CQ_THR_DONE_P2_0, "omc-lite-cq-thread0-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_OMC_LITE_CQ_THR_DONE_P2_1, "omc-lite-cq-thread1-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_OMC_LITE_CQ_THR_DONE_P2_2, "omc-lite-cq-thread2-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_OMC_LITE_CQ_THR_DONE_P2_3, "omc-lite-cq-thread3-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_OMC_LITE_CQ_THR_DONE_P2_4, "omc-lite-cq-thread4-frame-done"},
	{IMGSYS_CMDQ_EVENT_IMG_OMC_LITE_CQ_THR_DONE_P2_5, "omc-lite-cq-thread5-frame-done"},
	/*ME done*/
	{IMGSYS_CMDQ_EVENT_IMG_IMGSYS_IPE_ME_DONE, "me-done"},
	/*ADL done*/
	{IMGSYS_CMDQ_EVENT_IMG_ADL_TILE_DONE_EVENT, "adl-tile-done"},
	/* SW event */
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_WPE_EIS, "wpe-eis-sync-token"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_OMC_TNR, "omc-tnr-sync-token"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_WPE_LITE, "wpe-lite-sync-token"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_TRAW, "traw-sync-token"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_LTRAW, "ltraw-sync-token"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_DIP, "dip-sync-token"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_PQDIP_A, "pqdip-a-sync-token"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_PQDIP_B, "pqdip-b-sync-token"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IPESYS_ME, "me-sync-token"},
	{IMGSYS_CMDQ_SYNC_TOKEN_APUSYS_APU, "apu-sync-token"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_VSS_TRAW, "vss-traw-sync-token"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_VSS_LTRAW, "vss-ltraw-sync-token"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_VSS_DIP, "vss-dip-sync-token"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_OMC_LITE, "omc-lite-sync-token"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_1, "sw-sync-token-pool-1"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_2, "sw-sync-token-pool-2"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_3, "sw-sync-token-pool-3"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_4, "sw-sync-token-pool-4"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_5, "sw-sync-token-pool-5"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_6, "sw-sync-token-pool-6"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_7, "sw-sync-token-pool-7"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_8, "sw-sync-token-pool-8"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_9, "sw-sync-token-pool-9"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_10, "sw-sync-token-pool-10"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_11, "sw-sync-token-pool-11"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_12, "sw-sync-token-pool-12"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_13, "sw-sync-token-pool-13"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_14, "sw-sync-token-pool-14"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_15, "sw-sync-token-pool-15"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_16, "sw-sync-token-pool-16"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_17, "sw-sync-token-pool-17"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_18, "sw-sync-token-pool-18"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_19, "sw-sync-token-pool-19"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_20, "sw-sync-token-pool-20"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_21, "sw-sync-token-pool-21"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_22, "sw-sync-token-pool-22"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_23, "sw-sync-token-pool-23"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_24, "sw-sync-token-pool-24"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_25, "sw-sync-token-pool-25"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_26, "sw-sync-token-pool-26"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_27, "sw-sync-token-pool-27"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_28, "sw-sync-token-pool-28"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_29, "sw-sync-token-pool-29"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_30, "sw-sync-token-pool-30"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_31, "sw-sync-token-pool-31"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_32, "sw-sync-token-pool-32"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_33, "sw-sync-token-pool-33"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_34, "sw-sync-token-pool-34"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_35, "sw-sync-token-pool-35"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_36, "sw-sync-token-pool-36"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_37, "sw-sync-token-pool-37"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_38, "sw-sync-token-pool-38"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_39, "sw-sync-token-pool-39"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_40, "sw-sync-token-pool-40"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_41, "sw-sync-token-pool-41"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_42, "sw-sync-token-pool-42"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_43, "sw-sync-token-pool-43"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_44, "sw-sync-token-pool-44"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_45, "sw-sync-token-pool-45"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_46, "sw-sync-token-pool-46"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_47, "sw-sync-token-pool-47"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_48, "sw-sync-token-pool-48"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_49, "sw-sync-token-pool-49"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_50, "sw-sync-token-pool-50"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_51, "sw-sync-token-pool-51"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_52, "sw-sync-token-pool-52"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_53, "sw-sync-token-pool-53"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_54, "sw-sync-token-pool-54"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_55, "sw-sync-token-pool-55"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_56, "sw-sync-token-pool-56"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_57, "sw-sync-token-pool-57"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_58, "sw-sync-token-pool-58"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_59, "sw-sync-token-pool-59"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_60, "sw-sync-token-pool-60"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_61, "sw-sync-token-pool-61"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_62, "sw-sync-token-pool-62"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_63, "sw-sync-token-pool-63"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_64, "sw-sync-token-pool-64"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_65, "sw-sync-token-pool-65"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_66, "sw-sync-token-pool-66"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_67, "sw-sync-token-pool-67"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_68, "sw-sync-token-pool-68"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_69, "sw-sync-token-pool-69"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_70, "sw-sync-token-pool-70"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_71, "sw-sync-token-pool-71"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_72, "sw-sync-token-pool-72"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_73, "sw-sync-token-pool-73"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_74, "sw-sync-token-pool-74"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_75, "sw-sync-token-pool-75"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_76, "sw-sync-token-pool-76"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_77, "sw-sync-token-pool-77"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_78, "sw-sync-token-pool-78"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_79, "sw-sync-token-pool-79"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_80, "sw-sync-token-pool-80"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_81, "sw-sync-token-pool-81"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_82, "sw-sync-token-pool-82"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_83, "sw-sync-token-pool-83"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_84, "sw-sync-token-pool-84"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_85, "sw-sync-token-pool-85"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_86, "sw-sync-token-pool-86"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_87, "sw-sync-token-pool-87"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_88, "sw-sync-token-pool-88"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_89, "sw-sync-token-pool-89"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_90, "sw-sync-token-pool-90"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_91, "sw-sync-token-pool-91"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_92, "sw-sync-token-pool-92"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_93, "sw-sync-token-pool-93"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_94, "sw-sync-token-pool-94"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_95, "sw-sync-token-pool-95"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_96, "sw-sync-token-pool-96"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_97, "sw-sync-token-pool-97"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_98, "sw-sync-token-pool-98"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_99, "sw-sync-token-pool-99"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_100, "sw-sync-token-pool-100"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_101, "sw-sync-token-pool-101"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_102, "sw-sync-token-pool-102"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_103, "sw-sync-token-pool-103"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_104, "sw-sync-token-pool-104"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_105, "sw-sync-token-pool-105"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_106, "sw-sync-token-pool-106"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_107, "sw-sync-token-pool-107"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_108, "sw-sync-token-pool-108"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_109, "sw-sync-token-pool-109"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_110, "sw-sync-token-pool-110"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_111, "sw-sync-token-pool-111"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_112, "sw-sync-token-pool-112"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_113, "sw-sync-token-pool-113"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_114, "sw-sync-token-pool-114"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_115, "sw-sync-token-pool-115"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_116, "sw-sync-token-pool-116"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_117, "sw-sync-token-pool-117"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_118, "sw-sync-token-pool-118"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_119, "sw-sync-token-pool-119"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_120, "sw-sync-token-pool-120"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_121, "sw-sync-token-pool-121"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_122, "sw-sync-token-pool-122"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_123, "sw-sync-token-pool-123"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_124, "sw-sync-token-pool-124"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_125, "sw-sync-token-pool-125"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_126, "sw-sync-token-pool-126"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_127, "sw-sync-token-pool-127"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_128, "sw-sync-token-pool-128"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_129, "sw-sync-token-pool-129"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_130, "sw-sync-token-pool-130"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_131, "sw-sync-token-pool-131"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_132, "sw-sync-token-pool-132"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_133, "sw-sync-token-pool-133"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_134, "sw-sync-token-pool-134"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_135, "sw-sync-token-pool-135"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_136, "sw-sync-token-pool-136"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_137, "sw-sync-token-pool-137"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_138, "sw-sync-token-pool-138"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_139, "sw-sync-token-pool-139"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_140, "sw-sync-token-pool-140"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_141, "sw-sync-token-pool-141"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_142, "sw-sync-token-pool-142"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_143, "sw-sync-token-pool-143"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_144, "sw-sync-token-pool-144"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_145, "sw-sync-token-pool-145"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_146, "sw-sync-token-pool-146"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_147, "sw-sync-token-pool-147"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_148, "sw-sync-token-pool-148"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_149, "sw-sync-token-pool-149"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_150, "sw-sync-token-pool-150"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_151, "sw-sync-token-pool-151"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_152, "sw-sync-token-pool-152"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_153, "sw-sync-token-pool-153"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_154, "sw-sync-token-pool-154"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_155, "sw-sync-token-pool-155"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_156, "sw-sync-token-pool-156"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_157, "sw-sync-token-pool-157"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_158, "sw-sync-token-pool-158"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_159, "sw-sync-token-pool-159"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_160, "sw-sync-token-pool-160"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_161, "sw-sync-token-pool-161"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_162, "sw-sync-token-pool-162"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_163, "sw-sync-token-pool-163"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_164, "sw-sync-token-pool-164"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_165, "sw-sync-token-pool-165"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_166, "sw-sync-token-pool-166"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_167, "sw-sync-token-pool-167"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_168, "sw-sync-token-pool-168"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_169, "sw-sync-token-pool-169"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_170, "sw-sync-token-pool-170"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_171, "sw-sync-token-pool-171"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_172, "sw-sync-token-pool-172"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_173, "sw-sync-token-pool-173"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_174, "sw-sync-token-pool-174"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_175, "sw-sync-token-pool-175"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_176, "sw-sync-token-pool-176"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_177, "sw-sync-token-pool-177"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_178, "sw-sync-token-pool-178"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_179, "sw-sync-token-pool-179"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_180, "sw-sync-token-pool-180"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_181, "sw-sync-token-pool-181"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_182, "sw-sync-token-pool-182"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_183, "sw-sync-token-pool-183"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_184, "sw-sync-token-pool-184"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_185, "sw-sync-token-pool-185"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_186, "sw-sync-token-pool-186"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_187, "sw-sync-token-pool-187"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_188, "sw-sync-token-pool-188"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_189, "sw-sync-token-pool-189"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_190, "sw-sync-token-pool-190"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_191, "sw-sync-token-pool-191"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_192, "sw-sync-token-pool-192"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_193, "sw-sync-token-pool-193"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_194, "sw-sync-token-pool-194"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_195, "sw-sync-token-pool-195"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_196, "sw-sync-token-pool-196"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_197, "sw-sync-token-pool-197"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_198, "sw-sync-token-pool-198"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_199, "sw-sync-token-pool-199"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_200, "sw-sync-token-pool-200"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_201, "sw-sync-token-pool-201"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_202, "sw-sync-token-pool-202"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_203, "sw-sync-token-pool-203"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_204, "sw-sync-token-pool-204"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_205, "sw-sync-token-pool-205"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_206, "sw-sync-token-pool-206"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_207, "sw-sync-token-pool-207"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_208, "sw-sync-token-pool-208"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_209, "sw-sync-token-pool-209"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_210, "sw-sync-token-pool-210"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_211, "sw-sync-token-pool-211"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_212, "sw-sync-token-pool-212"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_213, "sw-sync-token-pool-213"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_214, "sw-sync-token-pool-214"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_215, "sw-sync-token-pool-215"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_216, "sw-sync-token-pool-216"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_217, "sw-sync-token-pool-217"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_218, "sw-sync-token-pool-218"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_219, "sw-sync-token-pool-219"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_220, "sw-sync-token-pool-220"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_221, "sw-sync-token-pool-221"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_222, "sw-sync-token-pool-222"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_223, "sw-sync-token-pool-223"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_224, "sw-sync-token-pool-224"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_225, "sw-sync-token-pool-225"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_226, "sw-sync-token-pool-226"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_227, "sw-sync-token-pool-227"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_228, "sw-sync-token-pool-228"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_229, "sw-sync-token-pool-229"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_230, "sw-sync-token-pool-230"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_231, "sw-sync-token-pool-231"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_232, "sw-sync-token-pool-232"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_233, "sw-sync-token-pool-233"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_234, "sw-sync-token-pool-234"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_235, "sw-sync-token-pool-235"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_236, "sw-sync-token-pool-236"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_237, "sw-sync-token-pool-237"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_238, "sw-sync-token-pool-238"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_239, "sw-sync-token-pool-239"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_240, "sw-sync-token-pool-240"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_241, "sw-sync-token-pool-241"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_242, "sw-sync-token-pool-242"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_243, "sw-sync-token-pool-243"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_244, "sw-sync-token-pool-244"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_245, "sw-sync-token-pool-245"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_246, "sw-sync-token-pool-246"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_247, "sw-sync-token-pool-247"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_248, "sw-sync-token-pool-248"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_249, "sw-sync-token-pool-249"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_250, "sw-sync-token-pool-250"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_251, "sw-sync-token-pool-251"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_252, "sw-sync-token-pool-252"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_253, "sw-sync-token-pool-253"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_254, "sw-sync-token-pool-254"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_255, "sw-sync-token-pool-255"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_256, "sw-sync-token-pool-256"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_257, "sw-sync-token-pool-257"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_258, "sw-sync-token-pool-258"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_259, "sw-sync-token-pool-259"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_260, "sw-sync-token-pool-260"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_261, "sw-sync-token-pool-261"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_262, "sw-sync-token-pool-262"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_263, "sw-sync-token-pool-263"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_264, "sw-sync-token-pool-264"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_265, "sw-sync-token-pool-265"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_266, "sw-sync-token-pool-266"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_267, "sw-sync-token-pool-267"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_268, "sw-sync-token-pool-268"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_269, "sw-sync-token-pool-269"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_270, "sw-sync-token-pool-270"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_271, "sw-sync-token-pool-271"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_272, "sw-sync-token-pool-272"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_273, "sw-sync-token-pool-273"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_274, "sw-sync-token-pool-274"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_275, "sw-sync-token-pool-275"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_276, "sw-sync-token-pool-276"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_277, "sw-sync-token-pool-277"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_278, "sw-sync-token-pool-278"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_279, "sw-sync-token-pool-279"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_280, "sw-sync-token-pool-280"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_281, "sw-sync-token-pool-281"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_282, "sw-sync-token-pool-282"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_283, "sw-sync-token-pool-283"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_284, "sw-sync-token-pool-284"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_285, "sw-sync-token-pool-285"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_286, "sw-sync-token-pool-286"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_287, "sw-sync-token-pool-287"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_288, "sw-sync-token-pool-288"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_289, "sw-sync-token-pool-289"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_290, "sw-sync-token-pool-290"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_291, "sw-sync-token-pool-291"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_292, "sw-sync-token-pool-292"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_293, "sw-sync-token-pool-293"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_294, "sw-sync-token-pool-294"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_295, "sw-sync-token-pool-295"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_296, "sw-sync-token-pool-296"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_297, "sw-sync-token-pool-297"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_298, "sw-sync-token-pool-298"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_299, "sw-sync-token-pool-299"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_300, "sw-sync-token-pool-300"},
	{IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_1, "sw-sync-token-camsys-pool-1"},
	{IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_2, "sw-sync-token-camsys-pool-2"},
	{IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_3, "sw-sync-token-camsys-pool-3"},
	{IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_4, "sw-sync-token-camsys-pool-4"},
	{IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_5, "sw-sync-token-camsys-pool-5"},
	{IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_6, "sw-sync-token-camsys-pool-6"},
	{IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_7, "sw-sync-token-camsys-pool-7"},
	{IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_8, "sw-sync-token-camsys-pool-8"},
	{IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_9, "sw-sync-token-camsys-pool-9"},
	{IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_10, "sw-sync-token-camsys-pool-10"},
	{IMGSYS_CMDQ_SYNC_TOKEN_TZMP_ISP_WAIT, "sw-sync-token-tzmp-isp-wait"},
	{IMGSYS_CMDQ_SYNC_TOKEN_TZMP_ISP_SET, "sw-sync-token-tzmp-isp-set"},
	{IMGSYS_CMDQ_SYNC_TOKEN_TZMP_ADL_WAIT, "sw-sync-token-tzmp-adl-wait"},
	{IMGSYS_CMDQ_SYNC_TOKEN_TZMP_ADL_SET, "sw-sync-token-tzmp-adl-set"},
	{IMGSYS_CMDQ_EVENT_MAX, "imgsys-event-max"},
};

static struct cmdq_client *imgsys_clt[IMGSYS_NOR_THD];
static struct cmdq_client *imgsys_sec_clt[IMGSYS_SEC_THD];

enum mtk_imgsys_m4u_port {
	/* SMI COMMON */
	IMGSYS_COMMON_0_R,
	IMGSYS_COMMON_0_W,
	IMGSYS_COMMON_1_R,
	IMGSYS_COMMON_1_W,
	IMGSYS_M4U_PORT_MAX
};


struct BlockRecord {
#if GCE_SUPPORT_REPLACE_MODE
	uint32_t            label_min;
	uint32_t            label_max;
	uint32_t            label_count;
#endif
	uint32_t            cmd_offset;
	uint32_t            cmd_length;
};

enum GCE_REC_BLOCK_ENUM {
	GCE_REC_NONE_BLOCK = -1,
	GCE_REC_FRAME_BLOCK = 0,
	GCE_REC_TILE_BLOCK
};

enum GCE_REC_MODE_ENUM {
	GCE_REC_APPEND_MODE = 0,
	GCE_REC_REPLACE_MODE
};

struct GCERecoder {
	uint32_t            header_code;

	// Record command offset
	uint32_t            cmd_offset;

	uint32_t            check_pre;

	// Reocrd command buffer info
	uint32_t            *pOutput;

	uint32_t            check_post;

	uint32_t            *pBuffer;
	uint32_t            max_length;
	uint32_t            curr_length;

	// Each frame block info
	struct BlockRecord  frame_record[GCE_REC_MAX_FRAME_BLOCK];
	uint32_t            frame_block;
	uint32_t            curr_frame;

	// Each tile block info
	struct BlockRecord  tile_record[GCE_REC_MAX_TILE_BLOCK];
	uint32_t            tile_block;
	uint32_t            curr_tile;

	// Record current block type
	enum GCE_REC_BLOCK_ENUM  curr_block;

	// Current mode setting
	enum GCE_REC_MODE_ENUM   curr_mode;

#if GCE_SUPPORT_REPLACE_MODE
	// Append/Replace mode switch
	uint32_t            orig_index;
	uint32_t            *pOrig_out;
	uint32_t            curr_label;

	// Current label mode setting
	enum GCE_REC_BLOCK_ENUM  label_block;

	// Each frame command label
	uint32_t            frame_label[GCE_REC_MAX_LABEL_COUNT];
	uint32_t            frame_count;

	// Each tile command label
	uint32_t            tile_label[GCE_REC_MAX_LABEL_COUNT];
	uint32_t            tile_count;
#endif

	uint32_t            footer_code;
};

static struct imgsys_dvfs_group  dvfs_group[MTK_IMGSYS_DVFS_GROUP] = {
	{0, (IMGSYS_ENG_WPE_LITE
			|IMGSYS_ENG_OMC_LITE
			|IMGSYS_ENG_TRAW
			|IMGSYS_ENG_LTR
			|IMGSYS_ENG_XTR
			|IMGSYS_ENG_ME)},
	{1, (IMGSYS_ENG_WPE_TNR
			|IMGSYS_ENG_OMC_TNR
			|IMGSYS_ENG_DIP)},
	{2, (IMGSYS_ENG_WPE_EIS
			|IMGSYS_ENG_PQDIP_A
			|IMGSYS_ENG_PQDIP_B)}
};

static struct imgsys_dvfs_group  qos_group[MTK_IMGSYS_QOS_GROUP] = {
	{0, (IMGSYS_ENG_WPE_EIS
			|IMGSYS_ENG_WPE_LITE
			|IMGSYS_ENG_TRAW
			|IMGSYS_ENG_LTR
			|IMGSYS_ENG_DIP
			|IMGSYS_ENG_PQDIP_A)},
	{1, (IMGSYS_ENG_WPE_TNR
			|IMGSYS_ENG_DIP
			|IMGSYS_ENG_PQDIP_B
			|IMGSYS_ENG_ME)}
};

static const u32 pwr_group[ISP8_PWR_NUM] = {
	[ISP8_PWR_DIP] = (IMGSYS_ENG_DIP),
	[ISP8_PWR_TRAW] = (IMGSYS_ENG_TRAW),
	[ISP8_PWR_WPE_1_EIS] = (IMGSYS_ENG_WPE_EIS | IMGSYS_ENG_PQDIP_A) |
			(IMGSYS_ENG_OMC_TNR | IMGSYS_ENG_PQDIP_B), // wa for gce thd lacked
	[ISP8_PWR_WPE_2_TNR] = (IMGSYS_ENG_OMC_TNR | IMGSYS_ENG_PQDIP_B),
	[ISP8_PWR_WPE_3_LITE] = (IMGSYS_ENG_WPE_LITE | IMGSYS_ENG_OMC_LITE),
};

struct smi_port_t {
	uint32_t portenum;
	uint32_t portbw;
} __packed;

struct wpe_bw_t {
	uint32_t totalbw;
	struct smi_port_t smiport[WPE_SMI_PORT_NUM];
} __packed;

struct me_bw_t {
	uint32_t totalbw;
	struct smi_port_t smiport[ME_SMI_PORT_NUM];
} __packed;

struct pqdip_bw_t {
	uint32_t totalbw;
	struct smi_port_t smiport[PQ_DIP_SMI_PORT_NUM];
} __packed;

struct traw_bw_t {
	uint32_t totalbw;
	struct smi_port_t smiport[TRAW_SMI_PORT_NUM];
} __packed;

struct ltraw_bw_t {
	uint32_t totalbw;
	struct smi_port_t smiport[LTRAW_SMI_PORT_NUM];
} __packed;

struct dip_bw_t {
	uint32_t totalbw;
	struct smi_port_t smiport[DIP_SMI_PORT_NUM];
} __packed;

struct adl_bw_t {
	uint32_t totalbw;
	struct smi_port_t smiport[ADL_SMI_PORT_NUM];
} __packed;

struct frame_bw_t {
	struct wpe_bw_t wpe_eis;
	struct wpe_bw_t wpe_tnr;
	struct wpe_bw_t wpe_lite;
	struct me_bw_t me;
	struct pqdip_bw_t pqdip_a;
	struct pqdip_bw_t pqdip_b;
	struct traw_bw_t traw;
	struct ltraw_bw_t ltraw;
	struct dip_bw_t dip;
	struct adl_bw_t ad;
} __packed;

/* ##### */

void imgsys_cmdq_init_plat8(struct mtk_imgsys_dev *imgsys_dev, const int nr_imgsys_dev);
void imgsys_cmdq_release_plat8(struct mtk_imgsys_dev *imgsys_dev);
void imgsys_cmdq_streamon_plat8(struct mtk_imgsys_dev *imgsys_dev);
void imgsys_cmdq_streamoff_plat8(struct mtk_imgsys_dev *imgsys_dev);
int imgsys_cmdq_sendtask_plat8(struct mtk_imgsys_dev *imgsys_dev,
				struct swfrm_info_t *frm_info,
				void (*cmdq_cb)(struct cmdq_cb_data data,
					uint32_t uinfo_idx, bool isLastTaskInReq,
					uint32_t batchnum, uint32_t is_capture),
				void (*cmdq_err_cb)(struct cmdq_cb_data data,
					uint32_t fail_uinfo_idx, bool isHWhang,
					uint32_t hangEvent),
				u64 (*imgsys_get_iova)(struct dma_buf *dma_buf, s32 ionFd,
					struct mtk_imgsys_dev *imgsys_dev,
					struct mtk_imgsys_dev_buffer *dev_buf),
				int (*is_singledev_mode)(struct mtk_imgsys_request *req));
int imgsys_cmdq_parser_plat8(struct mtk_imgsys_dev *imgsys_dev,
				struct swfrm_info_t *frm_info, struct cmdq_pkt *pkt,
				struct Command *cmd, u32 hw_comb, int sw_ridx,
				dma_addr_t dma_pa, uint32_t *num, u32 thd_idx,
				u64 (*imgsys_get_iova)(struct dma_buf *dma_buf, s32 ionFd,
					struct mtk_imgsys_dev *imgsys_dev,
					struct mtk_imgsys_dev_buffer *dev_buf),
				int (*is_singledev_mode)(struct mtk_imgsys_request *req));
int imgsys_cmdq_sec_sendtask_plat8(struct mtk_imgsys_dev *imgsys_dev);
void imgsys_cmdq_sec_cmd_plat8(struct cmdq_pkt *pkt);
void imgsys_cmdq_clearevent_plat8(int event_id);

#if DVFS_QOS_READY
void mtk_imgsys_power_ctrl_plat8(struct mtk_imgsys_dev *imgsys_dev, bool isPowerOn);
#endif

bool imgsys_cmdq_ts_enable_plat8(void);
u32 imgsys_wpe_bwlog_enable_plat8(void);
bool imgsys_cmdq_ts_dbg_enable_plat8(void);
bool imgsys_cmdq_dbg_enable_plat8(void);
bool imgsys_dvfs_dbg_enable_plat8(void);
bool imgsys_qos_dbg_enable_plat8(void);
bool imgsys_quick_onoff_enable_plat8(void);
bool imgsys_fence_dbg_enable_plat8(void);
bool imgsys_fine_grain_dvfs_enable_plat8(void);
bool imgsys_iova_dbg_enable_plat8(void);
u32 imgsys_iova_dbg_port_plat8(void);
u32 imgsys_cmdq_is_stream_off(void);

#endif /* _MTK_IMGSYS_CMDQ_PLAT_8_H_ */
