/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2021 MediaTek Inc.
 */
//[File]            : conn_dbg_ctl.h
//[Revision time]   : Fri Oct 21 15:04:28 2022

#ifndef __CONN_DBG_CTL_REGS_H__
#define __CONN_DBG_CTL_REGS_H__

//****************************************************************************
//
//                     CONN_DBG_CTL CR Definitions                     
//
//****************************************************************************

#define CONN_DBG_CTL_BASE                                      (CONN_REG_CONN_INFRA_DBG_CTL_ADDR)

#define CONN_DBG_CTL_CLOCK_DETECT_ADDR                         (CONN_DBG_CTL_BASE + 0) // 3000
#define CONN_DBG_CTL_CONN_INFRA_MONFLAG_OUT_ADDR               (CONN_DBG_CTL_BASE + 512) // 3200
#define CONN_DBG_CTL_CONN_INFRA_IO_TOP_DBG_SEL_ADDR            (CONN_DBG_CTL_BASE + 516) // 3204
#define CONN_DBG_CTL_CONN_INFRA_BUS_TIMEOUT_IRQ_ADDR           (CONN_DBG_CTL_BASE + 1024) // 3400
#define CONN_DBG_CTL_CONN_INFRA_OFF_BUS_DBG_OUT_ADDR           (CONN_DBG_CTL_BASE + 1028) // 3404
#define CONN_DBG_CTL_CONN_INFRA_OFF_BUS_DBG_SEL_ADDR           (CONN_DBG_CTL_BASE + 1032) // 3408
#define CONN_DBG_CTL_CONN_INFRA_OFF_DEBUGSYS_CTRL_ADDR         (CONN_DBG_CTL_BASE + 1036) // 340C
#define CONN_DBG_CTL_CONN_VON_BUS_APB_TIMEOUT_INFO_ADDR        (CONN_DBG_CTL_BASE + 1040) // 3410
#define CONN_DBG_CTL_CONN_VON_BUS_APB_TIMEOUT_ADDR_ADDR        (CONN_DBG_CTL_BASE + 1044) // 3414
#define CONN_DBG_CTL_CONN_VON_BUS_APB_TIMEOUT_WDATA_ADDR       (CONN_DBG_CTL_BASE + 1048) // 3418
#define CONN_DBG_CTL_CONN_INFRA_VON_BUS_DEBUG_INFO_ADDR        (CONN_DBG_CTL_BASE + 1052) // 341C
#define CONN_DBG_CTL_WF_MONFLAG_OFF_OUT_ADDR                   (CONN_DBG_CTL_BASE + 1536) // 3600
#define CONN_DBG_CTL_WF_MCU_DBGOUT_SEL_ADDR                    (CONN_DBG_CTL_BASE + 1540) // 3604
#define CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR            (CONN_DBG_CTL_BASE + 1544) // 3608
#define CONN_DBG_CTL_WF_MCU_DBG_PC_LOG_SEL_ADDR                (CONN_DBG_CTL_BASE + 1548) // 360C
#define CONN_DBG_CTL_WF_MCU_DBG_PC_LOG_ADDR                    (CONN_DBG_CTL_BASE + 1552) // 3610
#define CONN_DBG_CTL_WF_MCU_DBG_GPR_LOG_SEL_ADDR               (CONN_DBG_CTL_BASE + 1556) // 3614
#define CONN_DBG_CTL_WF_MCU_DBG_EN_FR_HIF_ADDR                 (CONN_DBG_CTL_BASE + 1560) // 3618
#define CONN_DBG_CTL_WF_MCU_DBG_SEL_FR_HIF_ADDR                (CONN_DBG_CTL_BASE + 1564) // 361C
#define CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR              (CONN_DBG_CTL_BASE + 1568) // 3620
#define CONN_DBG_CTL_WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_DEBUGSYS_CTRL_ADDR (CONN_DBG_CTL_BASE + 1576) // 3628
#define CONN_DBG_CTL_WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_BUS_TIMEOUT_IRQ_ADDR (CONN_DBG_CTL_BASE + 1580) // 362C
#define CONN_DBG_CTL_BGF_MONFLAG_OFF_OUT_ADDR                  (CONN_DBG_CTL_BASE + 2560) // 3A00
#define CONN_DBG_CTL_CR_DBGCTL2BGF_OFF_DEBUG_SEL_ADDR          (CONN_DBG_CTL_BASE + 2564) // 3A04
#define CONN_DBG_CTL_GPSAON2HOST_DEBUG_ADDR                    (CONN_DBG_CTL_BASE + 2568) // 3A08
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_ADDR                   (CONN_DBG_CTL_BASE + 3072) // 3C00
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_ADDR                  (CONN_DBG_CTL_BASE + 3088) // 3C10
#define CONN_DBG_CTL_CR_CONN_TEST_DO_SEL_ADDR                  (CONN_DBG_CTL_BASE + 3616) // 3E20
#define CONN_DBG_CTL_CR_AP2WF_HOST_ON_CFG_ADDR                 (CONN_DBG_CTL_BASE + 3620) // 3E24
#define CONN_DBG_CTL_DBG_CTL_LAST_CR_ADDR                      (CONN_DBG_CTL_BASE + 4092) // 3FFC




/* =====================================================================================

  ---CLOCK_DETECT (0x18023000 + 0)---

    CLK_DETECT_BUS_CLR_PULSE[0]  - (WO) Host set this bit to reset bus detect state
                                     This cr will generate a reset signal for bus clock detecion state
                                     After write 1, you have to write 0 to release rst
    HCLK_FR_CK_DETECT[1]         - (RO) Connsys bus hclk detection status
                                     0 : bus hclk non-alive
                                     1 : bus hclk alive
                                     User could write 1 to clear detection status.
                                     After write 1 clear status and then read back to check clock status. It can check bus hclk alive or not.
    OSC_CLK_DETECT[2]            - (RO) Connsys osc clock detection status
                                     0 : osc clock non-alive
                                     1 : osc clock alive
                                     User could write 1 to clear detection status.
                                     After write 1 clear status and then read back to check clock status. It can check osc clock alive or not.
    RESERVED3[31..3]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_DBG_CTL_CLOCK_DETECT_OSC_CLK_DETECT_ADDR          CONN_DBG_CTL_CLOCK_DETECT_ADDR
#define CONN_DBG_CTL_CLOCK_DETECT_OSC_CLK_DETECT_MASK          0x00000004                // OSC_CLK_DETECT[2]
#define CONN_DBG_CTL_CLOCK_DETECT_OSC_CLK_DETECT_SHFT          2
#define CONN_DBG_CTL_CLOCK_DETECT_HCLK_FR_CK_DETECT_ADDR       CONN_DBG_CTL_CLOCK_DETECT_ADDR
#define CONN_DBG_CTL_CLOCK_DETECT_HCLK_FR_CK_DETECT_MASK       0x00000002                // HCLK_FR_CK_DETECT[1]
#define CONN_DBG_CTL_CLOCK_DETECT_HCLK_FR_CK_DETECT_SHFT       1
#define CONN_DBG_CTL_CLOCK_DETECT_CLK_DETECT_BUS_CLR_PULSE_ADDR CONN_DBG_CTL_CLOCK_DETECT_ADDR
#define CONN_DBG_CTL_CLOCK_DETECT_CLK_DETECT_BUS_CLR_PULSE_MASK 0x00000001                // CLK_DETECT_BUS_CLR_PULSE[0]
#define CONN_DBG_CTL_CLOCK_DETECT_CLK_DETECT_BUS_CLR_PULSE_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_MONFLAG_OUT (0x18023000 + 512)---

    CONN_INFRA_MONFLAG_OUT[31..0] - (RO)  xxx 

 =====================================================================================*/
#define CONN_DBG_CTL_CONN_INFRA_MONFLAG_OUT_CONN_INFRA_MONFLAG_OUT_ADDR CONN_DBG_CTL_CONN_INFRA_MONFLAG_OUT_ADDR
#define CONN_DBG_CTL_CONN_INFRA_MONFLAG_OUT_CONN_INFRA_MONFLAG_OUT_MASK 0xFFFFFFFF                // CONN_INFRA_MONFLAG_OUT[31..0]
#define CONN_DBG_CTL_CONN_INFRA_MONFLAG_OUT_CONN_INFRA_MONFLAG_OUT_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_IO_TOP_DBG_SEL (0x18023000 + 516)---

    CONN_INFRA_IO_TOP_DBG_SEL[31..0] - (RW)  xxx 

 =====================================================================================*/
#define CONN_DBG_CTL_CONN_INFRA_IO_TOP_DBG_SEL_CONN_INFRA_IO_TOP_DBG_SEL_ADDR CONN_DBG_CTL_CONN_INFRA_IO_TOP_DBG_SEL_ADDR
#define CONN_DBG_CTL_CONN_INFRA_IO_TOP_DBG_SEL_CONN_INFRA_IO_TOP_DBG_SEL_MASK 0xFFFFFFFF                // CONN_INFRA_IO_TOP_DBG_SEL[31..0]
#define CONN_DBG_CTL_CONN_INFRA_IO_TOP_DBG_SEL_CONN_INFRA_IO_TOP_DBG_SEL_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_BUS_TIMEOUT_IRQ (0x18023000 + 1024)---

    CONN_INFRA_OFF_BUS_TIMEOUT[0] - (RO) merge "CONN_INFRA_OFF_C6_TIMEOUT" & "CONN_INFRA_OFF_CONN2AP_TIMEOUT"
    CONN_INFRA_OFF_VDNR_TIMEOUT_IRQ[1] - (RO) conn_infra_off_bus timeout (VDNR gen)
    CONN_INFRA_OFF_AXI_LAYER_TIMEOUT[2] - (RO) conn_infra_off_axi_layer_bus timeout (hand-code)
    CONN_INFRA_OFF_CONN2AP_TIMEOUT[3] - (RO) conn_infra_off_bus c12 AHB decoder timeout (hand-code)
    CONN_INFRA_OFF_C6_TIMEOUT[4] - (RO) conn_infra_off_bus c6 AHB decoder timeout (hand-code)
    CONN_VON_BUS_TIMEOUT[5]      - (RO) conn_von_bus timeout (hand-code)
    CONN_INFRA_ON_BUS_TIMEOUT_IRQ[6] - (RO) conn_infra_on_bus timeout (hand-code)
    RESERVED7[31..7]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_DBG_CTL_CONN_INFRA_BUS_TIMEOUT_IRQ_CONN_INFRA_ON_BUS_TIMEOUT_IRQ_ADDR CONN_DBG_CTL_CONN_INFRA_BUS_TIMEOUT_IRQ_ADDR
#define CONN_DBG_CTL_CONN_INFRA_BUS_TIMEOUT_IRQ_CONN_INFRA_ON_BUS_TIMEOUT_IRQ_MASK 0x00000040                // CONN_INFRA_ON_BUS_TIMEOUT_IRQ[6]
#define CONN_DBG_CTL_CONN_INFRA_BUS_TIMEOUT_IRQ_CONN_INFRA_ON_BUS_TIMEOUT_IRQ_SHFT 6
#define CONN_DBG_CTL_CONN_INFRA_BUS_TIMEOUT_IRQ_CONN_VON_BUS_TIMEOUT_ADDR CONN_DBG_CTL_CONN_INFRA_BUS_TIMEOUT_IRQ_ADDR
#define CONN_DBG_CTL_CONN_INFRA_BUS_TIMEOUT_IRQ_CONN_VON_BUS_TIMEOUT_MASK 0x00000020                // CONN_VON_BUS_TIMEOUT[5]
#define CONN_DBG_CTL_CONN_INFRA_BUS_TIMEOUT_IRQ_CONN_VON_BUS_TIMEOUT_SHFT 5
#define CONN_DBG_CTL_CONN_INFRA_BUS_TIMEOUT_IRQ_CONN_INFRA_OFF_C6_TIMEOUT_ADDR CONN_DBG_CTL_CONN_INFRA_BUS_TIMEOUT_IRQ_ADDR
#define CONN_DBG_CTL_CONN_INFRA_BUS_TIMEOUT_IRQ_CONN_INFRA_OFF_C6_TIMEOUT_MASK 0x00000010                // CONN_INFRA_OFF_C6_TIMEOUT[4]
#define CONN_DBG_CTL_CONN_INFRA_BUS_TIMEOUT_IRQ_CONN_INFRA_OFF_C6_TIMEOUT_SHFT 4
#define CONN_DBG_CTL_CONN_INFRA_BUS_TIMEOUT_IRQ_CONN_INFRA_OFF_CONN2AP_TIMEOUT_ADDR CONN_DBG_CTL_CONN_INFRA_BUS_TIMEOUT_IRQ_ADDR
#define CONN_DBG_CTL_CONN_INFRA_BUS_TIMEOUT_IRQ_CONN_INFRA_OFF_CONN2AP_TIMEOUT_MASK 0x00000008                // CONN_INFRA_OFF_CONN2AP_TIMEOUT[3]
#define CONN_DBG_CTL_CONN_INFRA_BUS_TIMEOUT_IRQ_CONN_INFRA_OFF_CONN2AP_TIMEOUT_SHFT 3
#define CONN_DBG_CTL_CONN_INFRA_BUS_TIMEOUT_IRQ_CONN_INFRA_OFF_AXI_LAYER_TIMEOUT_ADDR CONN_DBG_CTL_CONN_INFRA_BUS_TIMEOUT_IRQ_ADDR
#define CONN_DBG_CTL_CONN_INFRA_BUS_TIMEOUT_IRQ_CONN_INFRA_OFF_AXI_LAYER_TIMEOUT_MASK 0x00000004                // CONN_INFRA_OFF_AXI_LAYER_TIMEOUT[2]
#define CONN_DBG_CTL_CONN_INFRA_BUS_TIMEOUT_IRQ_CONN_INFRA_OFF_AXI_LAYER_TIMEOUT_SHFT 2
#define CONN_DBG_CTL_CONN_INFRA_BUS_TIMEOUT_IRQ_CONN_INFRA_OFF_VDNR_TIMEOUT_IRQ_ADDR CONN_DBG_CTL_CONN_INFRA_BUS_TIMEOUT_IRQ_ADDR
#define CONN_DBG_CTL_CONN_INFRA_BUS_TIMEOUT_IRQ_CONN_INFRA_OFF_VDNR_TIMEOUT_IRQ_MASK 0x00000002                // CONN_INFRA_OFF_VDNR_TIMEOUT_IRQ[1]
#define CONN_DBG_CTL_CONN_INFRA_BUS_TIMEOUT_IRQ_CONN_INFRA_OFF_VDNR_TIMEOUT_IRQ_SHFT 1
#define CONN_DBG_CTL_CONN_INFRA_BUS_TIMEOUT_IRQ_CONN_INFRA_OFF_BUS_TIMEOUT_ADDR CONN_DBG_CTL_CONN_INFRA_BUS_TIMEOUT_IRQ_ADDR
#define CONN_DBG_CTL_CONN_INFRA_BUS_TIMEOUT_IRQ_CONN_INFRA_OFF_BUS_TIMEOUT_MASK 0x00000001                // CONN_INFRA_OFF_BUS_TIMEOUT[0]
#define CONN_DBG_CTL_CONN_INFRA_BUS_TIMEOUT_IRQ_CONN_INFRA_OFF_BUS_TIMEOUT_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_OFF_BUS_DBG_OUT (0x18023000 + 1028)---

    CONN_INFRA_OFF_BUS_DBG_OUT[31..0] - (RO) conn_infra_off_bus debug output (idle, gals_dbg, timeout_info)

 =====================================================================================*/
#define CONN_DBG_CTL_CONN_INFRA_OFF_BUS_DBG_OUT_CONN_INFRA_OFF_BUS_DBG_OUT_ADDR CONN_DBG_CTL_CONN_INFRA_OFF_BUS_DBG_OUT_ADDR
#define CONN_DBG_CTL_CONN_INFRA_OFF_BUS_DBG_OUT_CONN_INFRA_OFF_BUS_DBG_OUT_MASK 0xFFFFFFFF                // CONN_INFRA_OFF_BUS_DBG_OUT[31..0]
#define CONN_DBG_CTL_CONN_INFRA_OFF_BUS_DBG_OUT_CONN_INFRA_OFF_BUS_DBG_OUT_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_OFF_BUS_DBG_SEL (0x18023000 + 1032)---

    CONN_INFRA_OFF_BUS_DBG_SEL[4..0] - (RW) conn_infra_off_bus debug selection
    RESERVED5[31..5]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_DBG_CTL_CONN_INFRA_OFF_BUS_DBG_SEL_CONN_INFRA_OFF_BUS_DBG_SEL_ADDR CONN_DBG_CTL_CONN_INFRA_OFF_BUS_DBG_SEL_ADDR
#define CONN_DBG_CTL_CONN_INFRA_OFF_BUS_DBG_SEL_CONN_INFRA_OFF_BUS_DBG_SEL_MASK 0x0000001F                // CONN_INFRA_OFF_BUS_DBG_SEL[4..0]
#define CONN_DBG_CTL_CONN_INFRA_OFF_BUS_DBG_SEL_CONN_INFRA_OFF_BUS_DBG_SEL_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_OFF_DEBUGSYS_CTRL (0x18023000 + 1036)---

    CONN_INFRA_OFF_DEBUGSYS_CTRL[31..0] - (RW) latch information when conn_von_bus timeout

 =====================================================================================*/
#define CONN_DBG_CTL_CONN_INFRA_OFF_DEBUGSYS_CTRL_CONN_INFRA_OFF_DEBUGSYS_CTRL_ADDR CONN_DBG_CTL_CONN_INFRA_OFF_DEBUGSYS_CTRL_ADDR
#define CONN_DBG_CTL_CONN_INFRA_OFF_DEBUGSYS_CTRL_CONN_INFRA_OFF_DEBUGSYS_CTRL_MASK 0xFFFFFFFF                // CONN_INFRA_OFF_DEBUGSYS_CTRL[31..0]
#define CONN_DBG_CTL_CONN_INFRA_OFF_DEBUGSYS_CTRL_CONN_INFRA_OFF_DEBUGSYS_CTRL_SHFT 0

/* =====================================================================================

  ---CONN_VON_BUS_APB_TIMEOUT_INFO (0x18023000 + 1040)---

    CONN_VON_BUS_APB_TIMEOUT_INFO[31..0] - (RO) latch information when conn_von_bus timeout

 =====================================================================================*/
#define CONN_DBG_CTL_CONN_VON_BUS_APB_TIMEOUT_INFO_CONN_VON_BUS_APB_TIMEOUT_INFO_ADDR CONN_DBG_CTL_CONN_VON_BUS_APB_TIMEOUT_INFO_ADDR
#define CONN_DBG_CTL_CONN_VON_BUS_APB_TIMEOUT_INFO_CONN_VON_BUS_APB_TIMEOUT_INFO_MASK 0xFFFFFFFF                // CONN_VON_BUS_APB_TIMEOUT_INFO[31..0]
#define CONN_DBG_CTL_CONN_VON_BUS_APB_TIMEOUT_INFO_CONN_VON_BUS_APB_TIMEOUT_INFO_SHFT 0

/* =====================================================================================

  ---CONN_VON_BUS_APB_TIMEOUT_ADDR (0x18023000 + 1044)---

    CONN_VON_BUS_APB_TIMEOUT_ADDR[31..0] - (RO) latch information when conn_von_bus timeout

 =====================================================================================*/
#define CONN_DBG_CTL_CONN_VON_BUS_APB_TIMEOUT_ADDR_CONN_VON_BUS_APB_TIMEOUT_ADDR_ADDR CONN_DBG_CTL_CONN_VON_BUS_APB_TIMEOUT_ADDR_ADDR
#define CONN_DBG_CTL_CONN_VON_BUS_APB_TIMEOUT_ADDR_CONN_VON_BUS_APB_TIMEOUT_ADDR_MASK 0xFFFFFFFF                // CONN_VON_BUS_APB_TIMEOUT_ADDR[31..0]
#define CONN_DBG_CTL_CONN_VON_BUS_APB_TIMEOUT_ADDR_CONN_VON_BUS_APB_TIMEOUT_ADDR_SHFT 0

/* =====================================================================================

  ---CONN_VON_BUS_APB_TIMEOUT_WDATA (0x18023000 + 1048)---

    CONN_VON_BUS_APB_TIMEOUT_WDATA[31..0] - (RO) latch information when conn_von_bus timeout

 =====================================================================================*/
#define CONN_DBG_CTL_CONN_VON_BUS_APB_TIMEOUT_WDATA_CONN_VON_BUS_APB_TIMEOUT_WDATA_ADDR CONN_DBG_CTL_CONN_VON_BUS_APB_TIMEOUT_WDATA_ADDR
#define CONN_DBG_CTL_CONN_VON_BUS_APB_TIMEOUT_WDATA_CONN_VON_BUS_APB_TIMEOUT_WDATA_MASK 0xFFFFFFFF                // CONN_VON_BUS_APB_TIMEOUT_WDATA[31..0]
#define CONN_DBG_CTL_CONN_VON_BUS_APB_TIMEOUT_WDATA_CONN_VON_BUS_APB_TIMEOUT_WDATA_SHFT 0

/* =====================================================================================

  ---CONN_INFRA_VON_BUS_DEBUG_INFO (0x18023000 + 1052)---

    CONN_INFRA_VON_BUS_DEBUG_INFO[31..0] - (RO) conn_von_bus debug information

 =====================================================================================*/
#define CONN_DBG_CTL_CONN_INFRA_VON_BUS_DEBUG_INFO_CONN_INFRA_VON_BUS_DEBUG_INFO_ADDR CONN_DBG_CTL_CONN_INFRA_VON_BUS_DEBUG_INFO_ADDR
#define CONN_DBG_CTL_CONN_INFRA_VON_BUS_DEBUG_INFO_CONN_INFRA_VON_BUS_DEBUG_INFO_MASK 0xFFFFFFFF                // CONN_INFRA_VON_BUS_DEBUG_INFO[31..0]
#define CONN_DBG_CTL_CONN_INFRA_VON_BUS_DEBUG_INFO_CONN_INFRA_VON_BUS_DEBUG_INFO_SHFT 0

/* =====================================================================================

  ---WF_MONFLAG_OFF_OUT (0x18023000 + 1536)---

    WF_MONFLAG_OFF_OUT[31..0]    - (RO)  xxx 

 =====================================================================================*/
#define CONN_DBG_CTL_WF_MONFLAG_OFF_OUT_WF_MONFLAG_OFF_OUT_ADDR CONN_DBG_CTL_WF_MONFLAG_OFF_OUT_ADDR
#define CONN_DBG_CTL_WF_MONFLAG_OFF_OUT_WF_MONFLAG_OFF_OUT_MASK 0xFFFFFFFF                // WF_MONFLAG_OFF_OUT[31..0]
#define CONN_DBG_CTL_WF_MONFLAG_OFF_OUT_WF_MONFLAG_OFF_OUT_SHFT 0

/* =====================================================================================

  ---WF_MCU_DBGOUT_SEL (0x18023000 + 1540)---

    WF_MCU_DBGOUT_SEL[2..0]      - (RW)  xxx 
    RESERVED3[31..3]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_DBG_CTL_WF_MCU_DBGOUT_SEL_WF_MCU_DBGOUT_SEL_ADDR  CONN_DBG_CTL_WF_MCU_DBGOUT_SEL_ADDR
#define CONN_DBG_CTL_WF_MCU_DBGOUT_SEL_WF_MCU_DBGOUT_SEL_MASK  0x00000007                // WF_MCU_DBGOUT_SEL[2..0]
#define CONN_DBG_CTL_WF_MCU_DBGOUT_SEL_WF_MCU_DBGOUT_SEL_SHFT  0

/* =====================================================================================

  ---WF_MCU_GPR_BUS_DBGOUT_LOG (0x18023000 + 1544)---

    WF_MCU_GPR_BUS_DBGOUT_LOG[31..0] - (RO) select by "WF_MCU_DBGOUT_SEL"

 =====================================================================================*/
#define CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR
#define CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK 0xFFFFFFFF                // WF_MCU_GPR_BUS_DBGOUT_LOG[31..0]
#define CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT 0

/* =====================================================================================

  ---WF_MCU_DBG_PC_LOG_SEL (0x18023000 + 1548)---

    WF_MCU_DBG_PC_LOG_SEL[5..0]  - (RW)  xxx 
    RESERVED6[31..6]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_DBG_CTL_WF_MCU_DBG_PC_LOG_SEL_WF_MCU_DBG_PC_LOG_SEL_ADDR CONN_DBG_CTL_WF_MCU_DBG_PC_LOG_SEL_ADDR
#define CONN_DBG_CTL_WF_MCU_DBG_PC_LOG_SEL_WF_MCU_DBG_PC_LOG_SEL_MASK 0x0000003F                // WF_MCU_DBG_PC_LOG_SEL[5..0]
#define CONN_DBG_CTL_WF_MCU_DBG_PC_LOG_SEL_WF_MCU_DBG_PC_LOG_SEL_SHFT 0

/* =====================================================================================

  ---WF_MCU_DBG_PC_LOG (0x18023000 + 1552)---

    WF_MCU_DBG_PC_LOG[31..0]     - (RO) select by "WF_MCU_DBG_PC_LOG_SEL"

 =====================================================================================*/
#define CONN_DBG_CTL_WF_MCU_DBG_PC_LOG_WF_MCU_DBG_PC_LOG_ADDR  CONN_DBG_CTL_WF_MCU_DBG_PC_LOG_ADDR
#define CONN_DBG_CTL_WF_MCU_DBG_PC_LOG_WF_MCU_DBG_PC_LOG_MASK  0xFFFFFFFF                // WF_MCU_DBG_PC_LOG[31..0]
#define CONN_DBG_CTL_WF_MCU_DBG_PC_LOG_WF_MCU_DBG_PC_LOG_SHFT  0

/* =====================================================================================

  ---WF_MCU_DBG_GPR_LOG_SEL (0x18023000 + 1556)---

    WF_MCU_DBG_GPR_LOG_SEL[5..0] - (RW)  xxx 
    RESERVED6[31..6]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_DBG_CTL_WF_MCU_DBG_GPR_LOG_SEL_WF_MCU_DBG_GPR_LOG_SEL_ADDR CONN_DBG_CTL_WF_MCU_DBG_GPR_LOG_SEL_ADDR
#define CONN_DBG_CTL_WF_MCU_DBG_GPR_LOG_SEL_WF_MCU_DBG_GPR_LOG_SEL_MASK 0x0000003F                // WF_MCU_DBG_GPR_LOG_SEL[5..0]
#define CONN_DBG_CTL_WF_MCU_DBG_GPR_LOG_SEL_WF_MCU_DBG_GPR_LOG_SEL_SHFT 0

/* =====================================================================================

  ---WF_MCU_DBG_EN_FR_HIF (0x18023000 + 1560)---

    WF_MCU_DBG_EN_FR_HIF[0]      - (RW)  xxx 
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_DBG_CTL_WF_MCU_DBG_EN_FR_HIF_WF_MCU_DBG_EN_FR_HIF_ADDR CONN_DBG_CTL_WF_MCU_DBG_EN_FR_HIF_ADDR
#define CONN_DBG_CTL_WF_MCU_DBG_EN_FR_HIF_WF_MCU_DBG_EN_FR_HIF_MASK 0x00000001                // WF_MCU_DBG_EN_FR_HIF[0]
#define CONN_DBG_CTL_WF_MCU_DBG_EN_FR_HIF_WF_MCU_DBG_EN_FR_HIF_SHFT 0

/* =====================================================================================

  ---WF_MCU_DBG_SEL_FR_HIF (0x18023000 + 1564)---

    WF_MCU_DBG_SEL_FR_HIF[27..0] - (RW)  xxx 
    RESERVED28[31..28]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_DBG_CTL_WF_MCU_DBG_SEL_FR_HIF_WF_MCU_DBG_SEL_FR_HIF_ADDR CONN_DBG_CTL_WF_MCU_DBG_SEL_FR_HIF_ADDR
#define CONN_DBG_CTL_WF_MCU_DBG_SEL_FR_HIF_WF_MCU_DBG_SEL_FR_HIF_MASK 0x0FFFFFFF                // WF_MCU_DBG_SEL_FR_HIF[27..0]
#define CONN_DBG_CTL_WF_MCU_DBG_SEL_FR_HIF_WF_MCU_DBG_SEL_FR_HIF_SHFT 0

/* =====================================================================================

  ---WF_CORE_PC_INDEX_FR_HIF (0x18023000 + 1568)---

    WF_CORE_PC_INDEX_FR_HIF[5..0] - (RW)  xxx 
    RESERVED6[31..6]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_ADDR CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR
#define CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK 0x0000003F                // WF_CORE_PC_INDEX_FR_HIF[5..0]
#define CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT 0

/* =====================================================================================

  ---WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_DEBUGSYS_CTRL (0x18023000 + 1576)---

    WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_DEBUGSYS_CTRL[31..0] - (RW)  xxx 

 =====================================================================================*/
#define CONN_DBG_CTL_WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_DEBUGSYS_CTRL_WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_DEBUGSYS_CTRL_ADDR CONN_DBG_CTL_WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_DEBUGSYS_CTRL_ADDR
#define CONN_DBG_CTL_WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_DEBUGSYS_CTRL_WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_DEBUGSYS_CTRL_MASK 0xFFFFFFFF                // WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_DEBUGSYS_CTRL[31..0]
#define CONN_DBG_CTL_WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_DEBUGSYS_CTRL_WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_DEBUGSYS_CTRL_SHFT 0

/* =====================================================================================

  ---WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_BUS_TIMEOUT_IRQ (0x18023000 + 1580)---

    WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_BUS_TIMEOUT_IRQ[0] - (RO)  xxx 
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_DBG_CTL_WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_BUS_TIMEOUT_IRQ_WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_BUS_TIMEOUT_IRQ_ADDR CONN_DBG_CTL_WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_BUS_TIMEOUT_IRQ_ADDR
#define CONN_DBG_CTL_WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_BUS_TIMEOUT_IRQ_WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_BUS_TIMEOUT_IRQ_MASK 0x00000001                // WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_BUS_TIMEOUT_IRQ[0]
#define CONN_DBG_CTL_WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_BUS_TIMEOUT_IRQ_WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_BUS_TIMEOUT_IRQ_SHFT 0

/* =====================================================================================

  ---BGF_MONFLAG_OFF_OUT (0x18023000 + 2560)---

    BGF_MONFLAG_OFF_OUT[31..0]   - (RO) select by "CR_DBGCTL2BGF_OFF_DEBUG_SEL"

 =====================================================================================*/
#define CONN_DBG_CTL_BGF_MONFLAG_OFF_OUT_BGF_MONFLAG_OFF_OUT_ADDR CONN_DBG_CTL_BGF_MONFLAG_OFF_OUT_ADDR
#define CONN_DBG_CTL_BGF_MONFLAG_OFF_OUT_BGF_MONFLAG_OFF_OUT_MASK 0xFFFFFFFF                // BGF_MONFLAG_OFF_OUT[31..0]
#define CONN_DBG_CTL_BGF_MONFLAG_OFF_OUT_BGF_MONFLAG_OFF_OUT_SHFT 0

/* =====================================================================================

  ---CR_DBGCTL2BGF_OFF_DEBUG_SEL (0x18023000 + 2564)---

    CR_DBGCTL2BGF_OFF_DEBUG_SEL[31..0] - (RW)  xxx 

 =====================================================================================*/
#define CONN_DBG_CTL_CR_DBGCTL2BGF_OFF_DEBUG_SEL_CR_DBGCTL2BGF_OFF_DEBUG_SEL_ADDR CONN_DBG_CTL_CR_DBGCTL2BGF_OFF_DEBUG_SEL_ADDR
#define CONN_DBG_CTL_CR_DBGCTL2BGF_OFF_DEBUG_SEL_CR_DBGCTL2BGF_OFF_DEBUG_SEL_MASK 0xFFFFFFFF                // CR_DBGCTL2BGF_OFF_DEBUG_SEL[31..0]
#define CONN_DBG_CTL_CR_DBGCTL2BGF_OFF_DEBUG_SEL_CR_DBGCTL2BGF_OFF_DEBUG_SEL_SHFT 0

/* =====================================================================================

  ---GPSAON2HOST_DEBUG (0x18023000 + 2568)---

    GPSAON2HOST_DEBUG[11..0]     - (RO)  xxx 
    RESERVED12[31..12]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_DBG_CTL_GPSAON2HOST_DEBUG_GPSAON2HOST_DEBUG_ADDR  CONN_DBG_CTL_GPSAON2HOST_DEBUG_ADDR
#define CONN_DBG_CTL_GPSAON2HOST_DEBUG_GPSAON2HOST_DEBUG_MASK  0x00000FFF                // GPSAON2HOST_DEBUG[11..0]
#define CONN_DBG_CTL_GPSAON2HOST_DEBUG_GPSAON2HOST_DEBUG_SHFT  0

/* =====================================================================================

  ---CONN_DBG_CTL_IRQ_FOR_APMCU_STAT (0x18023000 + 3072)---

    GPS_L5_IRQ_BUS_B[2..0]       - (RO) BGFSYS
    GPS_L1_IRQ_BUS_B[5..3]       - (RO) BGFSYS
    CONN2AP_SW_IRQ_B[6]          - (RO) BGFSYS
    BGF2AP_BTIF0_WAKEUP_OUT_B[7] - (RO) BGFSYS
    BT2AP_STACK_ISOCH_IRQ_B[8]   - (RO) BGFSYS
    BT2AP_ISOCH_IRQ_B[9]         - (RO) BGFSYS
    BT_CVSD_INT_B[10]            - (RO) BGFSYS
    CONN_GPS_HIF_ON_HOST_INT_B[11] - (RO) conn_infra_on.conn_host_csr_top
    CONN_BGF_HIF_ON_HOST_INT_B[12] - (RO) conn_infra_on.conn_host_csr_top
    CONN_WF1_HIF_ON_HOST_INT_B[13] - (RO) conn_infra_on.conn_host_csr_top
    CONN_WF_HIF_ON_HOST_INT_B[14] - (RO) conn_infra_on.conn_host_csr_top
    WF2AP_WAKEUP_B[15]           - (RO) WFSYS
    WFSYS_WDT_IRQ_B[16]          - (RO) WFSYS
    BGFSYS_WDT_IRQ_B[17]         - (RO) BGFSYS
    CCIF_BGF2AP_SW_IRQ_B[18]     - (RO) conn_infra_on.conn_ccif
    CCIF_WF2AP_SW_IRQ_B[19]      - (RO) conn_infra_on.conn_ccif
    SEMA_M3_TIMEOUT_INT_B[20]    - (RO) conn_infra.conn_semaphone
    SEMA_M2_TIMEOUT_INT_B[21]    - (RO) conn_infra.conn_semaphone
    SEMA_RELEASE_INFORM_M3_INT_B[22] - (RO) conn_infra.conn_semaphone
    SEMA_RELEASE_INFORM_M2_INT_B[23] - (RO) conn_infra.conn_semaphone
    CONN_MAWD2AP_IRQ_B[24]       - (RO) conn_infra.mawd_top
    FM_EXT_IRQ_B[25]             - (RO) conn_infra.conn_fm_ctrl
    GPS_DMA_IRQ_B[26]            - (RO) GPSSYS
    CONN_VON_BUS_BUS_TIMEOUT[27] - (RO) conn_von_top.conn_von_bus_glue
    CONN_INFRA_ON_BUS_TIMEOUT_IRQ[28] - (RO) conn_infra_on.conn_infra_vdnr_glue_on
    CONN_INFRA_OFF_AXI_LAYER_TIMEOUT[29] - (RO) conn_infra.conn_infra_vdnr_glue
    CONN_INFRA_OFF_CONN2AP_TIMEOUT[30] - (RO) conn_infra.conn_infra_vdnr_glue
    CONN_INFRA_OFF_C6_TIMEOUT[31] - (RO) conn_infra.conn_infra_vdnr_glue

 =====================================================================================*/
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CONN_INFRA_OFF_C6_TIMEOUT_ADDR CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CONN_INFRA_OFF_C6_TIMEOUT_MASK 0x80000000                // CONN_INFRA_OFF_C6_TIMEOUT[31]
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CONN_INFRA_OFF_C6_TIMEOUT_SHFT 31
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CONN_INFRA_OFF_CONN2AP_TIMEOUT_ADDR CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CONN_INFRA_OFF_CONN2AP_TIMEOUT_MASK 0x40000000                // CONN_INFRA_OFF_CONN2AP_TIMEOUT[30]
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CONN_INFRA_OFF_CONN2AP_TIMEOUT_SHFT 30
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CONN_INFRA_OFF_AXI_LAYER_TIMEOUT_ADDR CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CONN_INFRA_OFF_AXI_LAYER_TIMEOUT_MASK 0x20000000                // CONN_INFRA_OFF_AXI_LAYER_TIMEOUT[29]
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CONN_INFRA_OFF_AXI_LAYER_TIMEOUT_SHFT 29
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CONN_INFRA_ON_BUS_TIMEOUT_IRQ_ADDR CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CONN_INFRA_ON_BUS_TIMEOUT_IRQ_MASK 0x10000000                // CONN_INFRA_ON_BUS_TIMEOUT_IRQ[28]
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CONN_INFRA_ON_BUS_TIMEOUT_IRQ_SHFT 28
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CONN_VON_BUS_BUS_TIMEOUT_ADDR CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CONN_VON_BUS_BUS_TIMEOUT_MASK 0x08000000                // CONN_VON_BUS_BUS_TIMEOUT[27]
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CONN_VON_BUS_BUS_TIMEOUT_SHFT 27
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_GPS_DMA_IRQ_B_ADDR     CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_GPS_DMA_IRQ_B_MASK     0x04000000                // GPS_DMA_IRQ_B[26]
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_GPS_DMA_IRQ_B_SHFT     26
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_FM_EXT_IRQ_B_ADDR      CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_FM_EXT_IRQ_B_MASK      0x02000000                // FM_EXT_IRQ_B[25]
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_FM_EXT_IRQ_B_SHFT      25
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CONN_MAWD2AP_IRQ_B_ADDR CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CONN_MAWD2AP_IRQ_B_MASK 0x01000000                // CONN_MAWD2AP_IRQ_B[24]
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CONN_MAWD2AP_IRQ_B_SHFT 24
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_SEMA_RELEASE_INFORM_M2_INT_B_ADDR CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_SEMA_RELEASE_INFORM_M2_INT_B_MASK 0x00800000                // SEMA_RELEASE_INFORM_M2_INT_B[23]
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_SEMA_RELEASE_INFORM_M2_INT_B_SHFT 23
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_SEMA_RELEASE_INFORM_M3_INT_B_ADDR CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_SEMA_RELEASE_INFORM_M3_INT_B_MASK 0x00400000                // SEMA_RELEASE_INFORM_M3_INT_B[22]
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_SEMA_RELEASE_INFORM_M3_INT_B_SHFT 22
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_SEMA_M2_TIMEOUT_INT_B_ADDR CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_SEMA_M2_TIMEOUT_INT_B_MASK 0x00200000                // SEMA_M2_TIMEOUT_INT_B[21]
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_SEMA_M2_TIMEOUT_INT_B_SHFT 21
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_SEMA_M3_TIMEOUT_INT_B_ADDR CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_SEMA_M3_TIMEOUT_INT_B_MASK 0x00100000                // SEMA_M3_TIMEOUT_INT_B[20]
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_SEMA_M3_TIMEOUT_INT_B_SHFT 20
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CCIF_WF2AP_SW_IRQ_B_ADDR CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CCIF_WF2AP_SW_IRQ_B_MASK 0x00080000                // CCIF_WF2AP_SW_IRQ_B[19]
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CCIF_WF2AP_SW_IRQ_B_SHFT 19
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CCIF_BGF2AP_SW_IRQ_B_ADDR CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CCIF_BGF2AP_SW_IRQ_B_MASK 0x00040000                // CCIF_BGF2AP_SW_IRQ_B[18]
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CCIF_BGF2AP_SW_IRQ_B_SHFT 18
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_BGFSYS_WDT_IRQ_B_ADDR  CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_BGFSYS_WDT_IRQ_B_MASK  0x00020000                // BGFSYS_WDT_IRQ_B[17]
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_BGFSYS_WDT_IRQ_B_SHFT  17
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_WFSYS_WDT_IRQ_B_ADDR   CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_WFSYS_WDT_IRQ_B_MASK   0x00010000                // WFSYS_WDT_IRQ_B[16]
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_WFSYS_WDT_IRQ_B_SHFT   16
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_WF2AP_WAKEUP_B_ADDR    CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_WF2AP_WAKEUP_B_MASK    0x00008000                // WF2AP_WAKEUP_B[15]
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_WF2AP_WAKEUP_B_SHFT    15
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CONN_WF_HIF_ON_HOST_INT_B_ADDR CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CONN_WF_HIF_ON_HOST_INT_B_MASK 0x00004000                // CONN_WF_HIF_ON_HOST_INT_B[14]
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CONN_WF_HIF_ON_HOST_INT_B_SHFT 14
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CONN_WF1_HIF_ON_HOST_INT_B_ADDR CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CONN_WF1_HIF_ON_HOST_INT_B_MASK 0x00002000                // CONN_WF1_HIF_ON_HOST_INT_B[13]
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CONN_WF1_HIF_ON_HOST_INT_B_SHFT 13
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CONN_BGF_HIF_ON_HOST_INT_B_ADDR CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CONN_BGF_HIF_ON_HOST_INT_B_MASK 0x00001000                // CONN_BGF_HIF_ON_HOST_INT_B[12]
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CONN_BGF_HIF_ON_HOST_INT_B_SHFT 12
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CONN_GPS_HIF_ON_HOST_INT_B_ADDR CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CONN_GPS_HIF_ON_HOST_INT_B_MASK 0x00000800                // CONN_GPS_HIF_ON_HOST_INT_B[11]
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CONN_GPS_HIF_ON_HOST_INT_B_SHFT 11
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_BT_CVSD_INT_B_ADDR     CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_BT_CVSD_INT_B_MASK     0x00000400                // BT_CVSD_INT_B[10]
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_BT_CVSD_INT_B_SHFT     10
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_BT2AP_ISOCH_IRQ_B_ADDR CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_BT2AP_ISOCH_IRQ_B_MASK 0x00000200                // BT2AP_ISOCH_IRQ_B[9]
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_BT2AP_ISOCH_IRQ_B_SHFT 9
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_BT2AP_STACK_ISOCH_IRQ_B_ADDR CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_BT2AP_STACK_ISOCH_IRQ_B_MASK 0x00000100                // BT2AP_STACK_ISOCH_IRQ_B[8]
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_BT2AP_STACK_ISOCH_IRQ_B_SHFT 8
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_BGF2AP_BTIF0_WAKEUP_OUT_B_ADDR CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_BGF2AP_BTIF0_WAKEUP_OUT_B_MASK 0x00000080                // BGF2AP_BTIF0_WAKEUP_OUT_B[7]
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_BGF2AP_BTIF0_WAKEUP_OUT_B_SHFT 7
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CONN2AP_SW_IRQ_B_ADDR  CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CONN2AP_SW_IRQ_B_MASK  0x00000040                // CONN2AP_SW_IRQ_B[6]
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_CONN2AP_SW_IRQ_B_SHFT  6
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_GPS_L1_IRQ_BUS_B_ADDR  CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_GPS_L1_IRQ_BUS_B_MASK  0x00000038                // GPS_L1_IRQ_BUS_B[5..3]
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_GPS_L1_IRQ_BUS_B_SHFT  3
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_GPS_L5_IRQ_BUS_B_ADDR  CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_GPS_L5_IRQ_BUS_B_MASK  0x00000007                // GPS_L5_IRQ_BUS_B[2..0]
#define CONN_DBG_CTL_IRQ_FOR_APMCU_STAT_GPS_L5_IRQ_BUS_B_SHFT  0

/* =====================================================================================

  ---CONN_DBG_CTL_EINT_FOR_APMCU_STAT (0x18023000 + 3088)---

    GPS_L5_IRQ_BUS_B[2..0]       - (RO) BGFSYS
    GPS_L1_IRQ_BUS_B[5..3]       - (RO) BGFSYS
    CONN2AP_SW_IRQ_B[6]          - (RO) BGFSYS
    BGF2AP_BTIF0_WAKEUP_OUT_B[7] - (RO) BGFSYS
    BT2AP_STACK_ISOCH_IRQ_B[8]   - (RO) BGFSYS
    BT2AP_ISOCH_IRQ_B[9]         - (RO) BGFSYS
    BT_CVSD_INT_B[10]            - (RO) BGFSYS
    CONN_GPS_HIF_ON_HOST_INT_B[11] - (RO) conn_infra_on.conn_host_csr_top
    CONN_BGF_HIF_ON_HOST_INT_B[12] - (RO) conn_infra_on.conn_host_csr_top
    CONN_WF1_HIF_ON_HOST_INT_B[13] - (RO) conn_infra_on.conn_host_csr_top
    CONN_WF_HIF_ON_HOST_INT_B[14] - (RO) conn_infra_on.conn_host_csr_top
    WF2AP_WAKEUP_B[15]           - (RO) WFSYS
    WFSYS_WDT_IRQ_B[16]          - (RO) WFSYS
    BGFSYS_WDT_IRQ_B[17]         - (RO) BGFSYS
    CCIF_BGF2AP_SW_IRQ_B[18]     - (RO) conn_infra_on.conn_ccif
    CCIF_WF2AP_SW_IRQ_B[19]      - (RO) conn_infra_on.conn_ccif
    SEMA_M3_TIMEOUT_INT_B[20]    - (RO) conn_infra.conn_semaphone
    SEMA_M2_TIMEOUT_INT_B[21]    - (RO) conn_infra.conn_semaphone
    SEMA_RELEASE_INFORM_M3_INT_B[22] - (RO) conn_infra.conn_semaphone
    SEMA_RELEASE_INFORM_M2_INT_B[23] - (RO) conn_infra.conn_semaphone
    CONN_MAWD2AP_IRQ_B[24]       - (RO) conn_infra.mawd_top
    FM_EXT_IRQ_B[25]             - (RO) conn_infra.conn_fm_ctrl
    CONN2AP_WFDMA_IRQ_B[26]      - (RO) WFDMA
    RESERVED27[31..27]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_CONN2AP_WFDMA_IRQ_B_ADDR CONN_DBG_CTL_EINT_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_CONN2AP_WFDMA_IRQ_B_MASK 0x04000000                // CONN2AP_WFDMA_IRQ_B[26]
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_CONN2AP_WFDMA_IRQ_B_SHFT 26
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_FM_EXT_IRQ_B_ADDR     CONN_DBG_CTL_EINT_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_FM_EXT_IRQ_B_MASK     0x02000000                // FM_EXT_IRQ_B[25]
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_FM_EXT_IRQ_B_SHFT     25
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_CONN_MAWD2AP_IRQ_B_ADDR CONN_DBG_CTL_EINT_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_CONN_MAWD2AP_IRQ_B_MASK 0x01000000                // CONN_MAWD2AP_IRQ_B[24]
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_CONN_MAWD2AP_IRQ_B_SHFT 24
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_SEMA_RELEASE_INFORM_M2_INT_B_ADDR CONN_DBG_CTL_EINT_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_SEMA_RELEASE_INFORM_M2_INT_B_MASK 0x00800000                // SEMA_RELEASE_INFORM_M2_INT_B[23]
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_SEMA_RELEASE_INFORM_M2_INT_B_SHFT 23
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_SEMA_RELEASE_INFORM_M3_INT_B_ADDR CONN_DBG_CTL_EINT_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_SEMA_RELEASE_INFORM_M3_INT_B_MASK 0x00400000                // SEMA_RELEASE_INFORM_M3_INT_B[22]
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_SEMA_RELEASE_INFORM_M3_INT_B_SHFT 22
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_SEMA_M2_TIMEOUT_INT_B_ADDR CONN_DBG_CTL_EINT_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_SEMA_M2_TIMEOUT_INT_B_MASK 0x00200000                // SEMA_M2_TIMEOUT_INT_B[21]
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_SEMA_M2_TIMEOUT_INT_B_SHFT 21
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_SEMA_M3_TIMEOUT_INT_B_ADDR CONN_DBG_CTL_EINT_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_SEMA_M3_TIMEOUT_INT_B_MASK 0x00100000                // SEMA_M3_TIMEOUT_INT_B[20]
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_SEMA_M3_TIMEOUT_INT_B_SHFT 20
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_CCIF_WF2AP_SW_IRQ_B_ADDR CONN_DBG_CTL_EINT_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_CCIF_WF2AP_SW_IRQ_B_MASK 0x00080000                // CCIF_WF2AP_SW_IRQ_B[19]
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_CCIF_WF2AP_SW_IRQ_B_SHFT 19
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_CCIF_BGF2AP_SW_IRQ_B_ADDR CONN_DBG_CTL_EINT_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_CCIF_BGF2AP_SW_IRQ_B_MASK 0x00040000                // CCIF_BGF2AP_SW_IRQ_B[18]
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_CCIF_BGF2AP_SW_IRQ_B_SHFT 18
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_BGFSYS_WDT_IRQ_B_ADDR CONN_DBG_CTL_EINT_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_BGFSYS_WDT_IRQ_B_MASK 0x00020000                // BGFSYS_WDT_IRQ_B[17]
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_BGFSYS_WDT_IRQ_B_SHFT 17
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_WFSYS_WDT_IRQ_B_ADDR  CONN_DBG_CTL_EINT_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_WFSYS_WDT_IRQ_B_MASK  0x00010000                // WFSYS_WDT_IRQ_B[16]
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_WFSYS_WDT_IRQ_B_SHFT  16
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_WF2AP_WAKEUP_B_ADDR   CONN_DBG_CTL_EINT_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_WF2AP_WAKEUP_B_MASK   0x00008000                // WF2AP_WAKEUP_B[15]
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_WF2AP_WAKEUP_B_SHFT   15
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_CONN_WF_HIF_ON_HOST_INT_B_ADDR CONN_DBG_CTL_EINT_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_CONN_WF_HIF_ON_HOST_INT_B_MASK 0x00004000                // CONN_WF_HIF_ON_HOST_INT_B[14]
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_CONN_WF_HIF_ON_HOST_INT_B_SHFT 14
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_CONN_WF1_HIF_ON_HOST_INT_B_ADDR CONN_DBG_CTL_EINT_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_CONN_WF1_HIF_ON_HOST_INT_B_MASK 0x00002000                // CONN_WF1_HIF_ON_HOST_INT_B[13]
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_CONN_WF1_HIF_ON_HOST_INT_B_SHFT 13
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_CONN_BGF_HIF_ON_HOST_INT_B_ADDR CONN_DBG_CTL_EINT_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_CONN_BGF_HIF_ON_HOST_INT_B_MASK 0x00001000                // CONN_BGF_HIF_ON_HOST_INT_B[12]
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_CONN_BGF_HIF_ON_HOST_INT_B_SHFT 12
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_CONN_GPS_HIF_ON_HOST_INT_B_ADDR CONN_DBG_CTL_EINT_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_CONN_GPS_HIF_ON_HOST_INT_B_MASK 0x00000800                // CONN_GPS_HIF_ON_HOST_INT_B[11]
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_CONN_GPS_HIF_ON_HOST_INT_B_SHFT 11
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_BT_CVSD_INT_B_ADDR    CONN_DBG_CTL_EINT_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_BT_CVSD_INT_B_MASK    0x00000400                // BT_CVSD_INT_B[10]
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_BT_CVSD_INT_B_SHFT    10
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_BT2AP_ISOCH_IRQ_B_ADDR CONN_DBG_CTL_EINT_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_BT2AP_ISOCH_IRQ_B_MASK 0x00000200                // BT2AP_ISOCH_IRQ_B[9]
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_BT2AP_ISOCH_IRQ_B_SHFT 9
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_BT2AP_STACK_ISOCH_IRQ_B_ADDR CONN_DBG_CTL_EINT_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_BT2AP_STACK_ISOCH_IRQ_B_MASK 0x00000100                // BT2AP_STACK_ISOCH_IRQ_B[8]
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_BT2AP_STACK_ISOCH_IRQ_B_SHFT 8
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_BGF2AP_BTIF0_WAKEUP_OUT_B_ADDR CONN_DBG_CTL_EINT_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_BGF2AP_BTIF0_WAKEUP_OUT_B_MASK 0x00000080                // BGF2AP_BTIF0_WAKEUP_OUT_B[7]
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_BGF2AP_BTIF0_WAKEUP_OUT_B_SHFT 7
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_CONN2AP_SW_IRQ_B_ADDR CONN_DBG_CTL_EINT_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_CONN2AP_SW_IRQ_B_MASK 0x00000040                // CONN2AP_SW_IRQ_B[6]
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_CONN2AP_SW_IRQ_B_SHFT 6
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_GPS_L1_IRQ_BUS_B_ADDR CONN_DBG_CTL_EINT_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_GPS_L1_IRQ_BUS_B_MASK 0x00000038                // GPS_L1_IRQ_BUS_B[5..3]
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_GPS_L1_IRQ_BUS_B_SHFT 3
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_GPS_L5_IRQ_BUS_B_ADDR CONN_DBG_CTL_EINT_FOR_APMCU_STAT_ADDR
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_GPS_L5_IRQ_BUS_B_MASK 0x00000007                // GPS_L5_IRQ_BUS_B[2..0]
#define CONN_DBG_CTL_EINT_FOR_APMCU_STAT_GPS_L5_IRQ_BUS_B_SHFT 0

/* =====================================================================================

  ---CR_CONN_TEST_DO_SEL (0x18023000 + 3616)---

    CR_CONN_TEST_DO_SEL[31..0]   - (RW)  xxx 

 =====================================================================================*/
#define CONN_DBG_CTL_CR_CONN_TEST_DO_SEL_CR_CONN_TEST_DO_SEL_ADDR CONN_DBG_CTL_CR_CONN_TEST_DO_SEL_ADDR
#define CONN_DBG_CTL_CR_CONN_TEST_DO_SEL_CR_CONN_TEST_DO_SEL_MASK 0xFFFFFFFF                // CR_CONN_TEST_DO_SEL[31..0]
#define CONN_DBG_CTL_CR_CONN_TEST_DO_SEL_CR_CONN_TEST_DO_SEL_SHFT 0

/* =====================================================================================

  ---CR_AP2WF_HOST_ON_CFG (0x18023000 + 3620)---

    CR_AP2WF_HOST_ON_CFG[15..0]  - (RW)  xxx 
    RESERVED16[31..16]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_DBG_CTL_CR_AP2WF_HOST_ON_CFG_CR_AP2WF_HOST_ON_CFG_ADDR CONN_DBG_CTL_CR_AP2WF_HOST_ON_CFG_ADDR
#define CONN_DBG_CTL_CR_AP2WF_HOST_ON_CFG_CR_AP2WF_HOST_ON_CFG_MASK 0x0000FFFF                // CR_AP2WF_HOST_ON_CFG[15..0]
#define CONN_DBG_CTL_CR_AP2WF_HOST_ON_CFG_CR_AP2WF_HOST_ON_CFG_SHFT 0

/* =====================================================================================

  ---DBG_CTL_LAST_CR (0x18023000 + 4092)---

    LAST_REG[31..0]              - (RO) fixed value

 =====================================================================================*/
#define CONN_DBG_CTL_DBG_CTL_LAST_CR_LAST_REG_ADDR             CONN_DBG_CTL_DBG_CTL_LAST_CR_ADDR
#define CONN_DBG_CTL_DBG_CTL_LAST_CR_LAST_REG_MASK             0xFFFFFFFF                // LAST_REG[31..0]
#define CONN_DBG_CTL_DBG_CTL_LAST_CR_LAST_REG_SHFT             0

#endif // __CONN_DBG_CTL_REGS_H__
