/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */
#ifndef __GPS_CFG_ON_REGS_H__
#define __GPS_CFG_ON_REGS_H__

#define GPS_CFG_ON_BASE                                        0x80001000

#define GPS_CFG_ON_GPS_L1_SLP_PWR_CTL_ADDR                     (GPS_CFG_ON_BASE + 0x0020)
#define GPS_CFG_ON_GPS_L5_SLP_PWR_CTL_ADDR                     (GPS_CFG_ON_BASE + 0x0024)
#define GPS_CFG_ON_GPS_CLKGEN1_CTL_ADDR                        (GPS_CFG_ON_BASE + 0x003C)

#define GPS_CFG_ON_GPS_ON_MET_CTL0_ADDR                        (GPS_CFG_ON_BASE + 0x400)
#define GPS_CFG_ON_GPS_ON_MET_CTL1_ADDR                        (GPS_CFG_ON_BASE + 0x404)
#define GPS_CFG_ON_GPS_ON_MET_DEGE_DET_ADDR                    (GPS_CFG_ON_BASE + 0x408)
#define GPS_CFG_ON_GPS_ON_MET_START_ADDR_ADDR                  (GPS_CFG_ON_BASE + 0x40c)
#define GPS_CFG_ON_GPS_ON_MET_END_ADDR_ADDR                    (GPS_CFG_ON_BASE + 0x410)
#define GPS_CFG_ON_GPS_ON_MET_WRITE_PTR_ADDR                   (GPS_CFG_ON_BASE + 0x414)
#define GPS_CFG_ON_GPS_ON_MET_READ_PTR_ADDR                    (GPS_CFG_ON_BASE + 0x418)
#define GPS_CFG_ON_GPS_ON_MET_FLAG_ADDR                        (GPS_CFG_ON_BASE + 0x41c)
#define GPS_CFG_ON_GPS_ON_MET_EVENT_SEL0_ADDR                  (GPS_CFG_ON_BASE + 0x420)
#define GPS_CFG_ON_GPS_ON_MET_SWCTL_ADDR                       (GPS_CFG_ON_BASE + 0x424)
#define GPS_CFG_ON_GPS_ON_MET_SIGNAL_SEL_ADDR                  (GPS_CFG_ON_BASE + 0x428)

#define GPS_CFG_ON_GPS_L1_SLP_PWR_CTL_GPS_L1_SLP_PWR_CTL_CS_ADDR GPS_CFG_ON_GPS_L1_SLP_PWR_CTL_ADDR
#define GPS_CFG_ON_GPS_L1_SLP_PWR_CTL_GPS_L1_SLP_PWR_CTL_CS_MASK 0x0000000F
#define GPS_CFG_ON_GPS_L1_SLP_PWR_CTL_GPS_L1_SLP_PWR_CTL_CS_SHFT 0

#define GPS_CFG_ON_GPS_L5_SLP_PWR_CTL_GPS_L5_SLP_PWR_CTL_CS_ADDR GPS_CFG_ON_GPS_L5_SLP_PWR_CTL_ADDR
#define GPS_CFG_ON_GPS_L5_SLP_PWR_CTL_GPS_L5_SLP_PWR_CTL_CS_MASK 0x0000000F
#define GPS_CFG_ON_GPS_L5_SLP_PWR_CTL_GPS_L5_SLP_PWR_CTL_CS_SHFT 0

#define GPS_CFG_ON_GPS_CLKGEN1_CTL_CR_GPS_DIGCK_DIV_EN_ADDR    GPS_CFG_ON_GPS_CLKGEN1_CTL_ADDR
#define GPS_CFG_ON_GPS_CLKGEN1_CTL_CR_GPS_DIGCK_DIV_EN_MASK    0x00000010
#define GPS_CFG_ON_GPS_CLKGEN1_CTL_CR_GPS_DIGCK_DIV_EN_SHFT    4


#define GPS_CFG_ON_GPS_ON_MET_CTL0_GPS_MET_DATA_MASK_ADDR      GPS_CFG_ON_GPS_ON_MET_CTL0_ADDR
#define GPS_CFG_ON_GPS_ON_MET_CTL0_GPS_MET_DATA_MASK_MASK      0xFFFF0000
#define GPS_CFG_ON_GPS_ON_MET_CTL0_GPS_MET_DATA_MASK_SHFT      16
#define GPS_CFG_ON_GPS_ON_MET_CTL0_GPS_MET_OSC_CNT_TARGET_ADDR GPS_CFG_ON_GPS_ON_MET_CTL0_ADDR
#define GPS_CFG_ON_GPS_ON_MET_CTL0_GPS_MET_OSC_CNT_TARGET_MASK 0x00007F00
#define GPS_CFG_ON_GPS_ON_MET_CTL0_GPS_MET_OSC_CNT_TARGET_SHFT 8
#define GPS_CFG_ON_GPS_ON_MET_CTL0_GPS_MET_EVENT_SEL_ADDR      GPS_CFG_ON_GPS_ON_MET_CTL0_ADDR
#define GPS_CFG_ON_GPS_ON_MET_CTL0_GPS_MET_EVENT_SEL_MASK      0x000000F0
#define GPS_CFG_ON_GPS_ON_MET_CTL0_GPS_MET_EVENT_SEL_SHFT      4
#define GPS_CFG_ON_GPS_ON_MET_CTL0_GPS_MET_IRQ_B_ADDR          GPS_CFG_ON_GPS_ON_MET_CTL0_ADDR
#define GPS_CFG_ON_GPS_ON_MET_CTL0_GPS_MET_IRQ_B_MASK          0x00000008
#define GPS_CFG_ON_GPS_ON_MET_CTL0_GPS_MET_IRQ_B_SHFT          3
#define GPS_CFG_ON_GPS_ON_MET_CTL0_GPS_MET_CLK_EN_ADDR         GPS_CFG_ON_GPS_ON_MET_CTL0_ADDR
#define GPS_CFG_ON_GPS_ON_MET_CTL0_GPS_MET_CLK_EN_MASK         0x00000002
#define GPS_CFG_ON_GPS_ON_MET_CTL0_GPS_MET_CLK_EN_SHFT         1
#define GPS_CFG_ON_GPS_ON_MET_CTL0_GPS_MET_RECORD_EN_ADDR      GPS_CFG_ON_GPS_ON_MET_CTL0_ADDR
#define GPS_CFG_ON_GPS_ON_MET_CTL0_GPS_MET_RECORD_EN_MASK      0x00000001
#define GPS_CFG_ON_GPS_ON_MET_CTL0_GPS_MET_RECORD_EN_SHFT      0


#define GPS_CFG_ON_GPS_ON_MET_CTL1_GPS_MET_DBG_CNT_EN_ADDR     GPS_CFG_ON_GPS_ON_MET_CTL1_ADDR
#define GPS_CFG_ON_GPS_ON_MET_CTL1_GPS_MET_DBG_CNT_EN_MASK     0x00020000
#define GPS_CFG_ON_GPS_ON_MET_CTL1_GPS_MET_DBG_CNT_EN_SHFT     17
#define GPS_CFG_ON_GPS_ON_MET_CTL1_GPS_MET_MCUCK_INFO_MASK_ADDR GPS_CFG_ON_GPS_ON_MET_CTL1_ADDR
#define GPS_CFG_ON_GPS_ON_MET_CTL1_GPS_MET_MCUCK_INFO_MASK_MASK 0x00010000
#define GPS_CFG_ON_GPS_ON_MET_CTL1_GPS_MET_MCUCK_INFO_MASK_SHFT 16
#define GPS_CFG_ON_GPS_ON_MET_CTL1_GPS_MET_DATA_CNT4IRQ_ADDR   GPS_CFG_ON_GPS_ON_MET_CTL1_ADDR
#define GPS_CFG_ON_GPS_ON_MET_CTL1_GPS_MET_DATA_CNT4IRQ_MASK   0x0000FF00
#define GPS_CFG_ON_GPS_ON_MET_CTL1_GPS_MET_DATA_CNT4IRQ_SHFT   8
#define GPS_CFG_ON_GPS_ON_MET_CTL1_GPS_MET_RING_BUF_FULL_SEL_ADDR GPS_CFG_ON_GPS_ON_MET_CTL1_ADDR
#define GPS_CFG_ON_GPS_ON_MET_CTL1_GPS_MET_RING_BUF_FULL_SEL_MASK 0x00000002
#define GPS_CFG_ON_GPS_ON_MET_CTL1_GPS_MET_RING_BUF_FULL_SEL_SHFT 1
#define GPS_CFG_ON_GPS_ON_MET_CTL1_GPS_MET_RING_BUF_MODE_ADDR  GPS_CFG_ON_GPS_ON_MET_CTL1_ADDR
#define GPS_CFG_ON_GPS_ON_MET_CTL1_GPS_MET_RING_BUF_MODE_MASK  0x00000001
#define GPS_CFG_ON_GPS_ON_MET_CTL1_GPS_MET_RING_BUF_MODE_SHFT  0


#define GPS_CFG_ON_GPS_ON_MET_DEGE_DET_GPS_MET_POSEDGE_DET_EN_ADDR GPS_CFG_ON_GPS_ON_MET_DEGE_DET_ADDR
#define GPS_CFG_ON_GPS_ON_MET_DEGE_DET_GPS_MET_POSEDGE_DET_EN_MASK 0xFFFF0000
#define GPS_CFG_ON_GPS_ON_MET_DEGE_DET_GPS_MET_POSEDGE_DET_EN_SHFT 16
#define GPS_CFG_ON_GPS_ON_MET_DEGE_DET_GPS_MET_NEGEDGE_DET_EN_ADDR GPS_CFG_ON_GPS_ON_MET_DEGE_DET_ADDR
#define GPS_CFG_ON_GPS_ON_MET_DEGE_DET_GPS_MET_NEGEDGE_DET_EN_MASK 0x0000FFFF
#define GPS_CFG_ON_GPS_ON_MET_DEGE_DET_GPS_MET_NEGEDGE_DET_EN_SHFT 0


#define GPS_CFG_ON_GPS_ON_MET_START_ADDR_GPS_MET_START_ADDR_ADDR GPS_CFG_ON_GPS_ON_MET_START_ADDR_ADDR
#define GPS_CFG_ON_GPS_ON_MET_START_ADDR_GPS_MET_START_ADDR_MASK 0xFFFFFFFF
#define GPS_CFG_ON_GPS_ON_MET_START_ADDR_GPS_MET_START_ADDR_SHFT 0


#define GPS_CFG_ON_GPS_ON_MET_END_ADDR_GPS_MET_END_ADDR_ADDR   GPS_CFG_ON_GPS_ON_MET_END_ADDR_ADDR
#define GPS_CFG_ON_GPS_ON_MET_END_ADDR_GPS_MET_END_ADDR_MASK   0xFFFFFFFF
#define GPS_CFG_ON_GPS_ON_MET_END_ADDR_GPS_MET_END_ADDR_SHFT   0


#define GPS_CFG_ON_GPS_ON_MET_WRITE_PTR_GPS_MET_WR_PTR_ADDR    GPS_CFG_ON_GPS_ON_MET_WRITE_PTR_ADDR
#define GPS_CFG_ON_GPS_ON_MET_WRITE_PTR_GPS_MET_WR_PTR_MASK    0xFFFFFFFF
#define GPS_CFG_ON_GPS_ON_MET_WRITE_PTR_GPS_MET_WR_PTR_SHFT    0


#define GPS_CFG_ON_GPS_ON_MET_READ_PTR_GPS_MET_RD_PTR_ADDR     GPS_CFG_ON_GPS_ON_MET_READ_PTR_ADDR
#define GPS_CFG_ON_GPS_ON_MET_READ_PTR_GPS_MET_RD_PTR_MASK     0xFFFFFFFF
#define GPS_CFG_ON_GPS_ON_MET_READ_PTR_GPS_MET_RD_PTR_SHFT     0


#define GPS_CFG_ON_GPS_ON_MET_FLAG_GPS_MET_MCUCK_INFO_ERR_FLAG_ADDR GPS_CFG_ON_GPS_ON_MET_FLAG_ADDR
#define GPS_CFG_ON_GPS_ON_MET_FLAG_GPS_MET_MCUCK_INFO_ERR_FLAG_MASK 0x00000008
#define GPS_CFG_ON_GPS_ON_MET_FLAG_GPS_MET_MCUCK_INFO_ERR_FLAG_SHFT 3
#define GPS_CFG_ON_GPS_ON_MET_FLAG_GPS_MET_AHB_ERR_FLAG_ADDR   GPS_CFG_ON_GPS_ON_MET_FLAG_ADDR
#define GPS_CFG_ON_GPS_ON_MET_FLAG_GPS_MET_AHB_ERR_FLAG_MASK   0x00000004
#define GPS_CFG_ON_GPS_ON_MET_FLAG_GPS_MET_AHB_ERR_FLAG_SHFT   2
#define GPS_CFG_ON_GPS_ON_MET_FLAG_GPS_MET_WRAP_ERR_FLAG_ADDR  GPS_CFG_ON_GPS_ON_MET_FLAG_ADDR
#define GPS_CFG_ON_GPS_ON_MET_FLAG_GPS_MET_WRAP_ERR_FLAG_MASK  0x00000002
#define GPS_CFG_ON_GPS_ON_MET_FLAG_GPS_MET_WRAP_ERR_FLAG_SHFT  1
#define GPS_CFG_ON_GPS_ON_MET_FLAG_GPS_MET_SLEEP_TIMER_OVERFLOW_ADDR GPS_CFG_ON_GPS_ON_MET_FLAG_ADDR
#define GPS_CFG_ON_GPS_ON_MET_FLAG_GPS_MET_SLEEP_TIMER_OVERFLOW_MASK 0x00000001
#define GPS_CFG_ON_GPS_ON_MET_FLAG_GPS_MET_SLEEP_TIMER_OVERFLOW_SHFT 0


#define GPS_CFG_ON_GPS_ON_MET_EVENT_SEL0_GPS_MET_GPS_EVENT_SEL_ADDR GPS_CFG_ON_GPS_ON_MET_EVENT_SEL0_ADDR
#define GPS_CFG_ON_GPS_ON_MET_EVENT_SEL0_GPS_MET_GPS_EVENT_SEL_MASK 0xFF000000
#define GPS_CFG_ON_GPS_ON_MET_EVENT_SEL0_GPS_MET_GPS_EVENT_SEL_SHFT 24
#define GPS_CFG_ON_GPS_ON_MET_EVENT_SEL0_GPS_MET_CFG_ON_EVENT_SEL_ADDR GPS_CFG_ON_GPS_ON_MET_EVENT_SEL0_ADDR
#define GPS_CFG_ON_GPS_ON_MET_EVENT_SEL0_GPS_MET_CFG_ON_EVENT_SEL_MASK 0x00030000
#define GPS_CFG_ON_GPS_ON_MET_EVENT_SEL0_GPS_MET_CFG_ON_EVENT_SEL_SHFT 16


#define GPS_CFG_ON_GPS_ON_MET_SWCTL_GPS_MET_SWCTL_ADDR         GPS_CFG_ON_GPS_ON_MET_SWCTL_ADDR
#define GPS_CFG_ON_GPS_ON_MET_SWCTL_GPS_MET_SWCTL_MASK         0x0000FFFF
#define GPS_CFG_ON_GPS_ON_MET_SWCTL_GPS_MET_SWCTL_SHFT         0


#define GPS_CFG_ON_GPS_ON_MET_SIGNAL_SEL_GPS_MET_TEMP_SIGNAL_SEL_ADDR GPS_CFG_ON_GPS_ON_MET_SIGNAL_SEL_ADDR
#define GPS_CFG_ON_GPS_ON_MET_SIGNAL_SEL_GPS_MET_TEMP_SIGNAL_SEL_MASK 0xFFFF0000
#define GPS_CFG_ON_GPS_ON_MET_SIGNAL_SEL_GPS_MET_TEMP_SIGNAL_SEL_SHFT 16
#define GPS_CFG_ON_GPS_ON_MET_SIGNAL_SEL_GPS_MET_SIGNAL_SEL_ADDR GPS_CFG_ON_GPS_ON_MET_SIGNAL_SEL_ADDR
#define GPS_CFG_ON_GPS_ON_MET_SIGNAL_SEL_GPS_MET_SIGNAL_SEL_MASK 0x0000FFFF
#define GPS_CFG_ON_GPS_ON_MET_SIGNAL_SEL_GPS_MET_SIGNAL_SEL_SHFT 0

#endif /* __GPS_CFG_ON_REGS_H__ */

