/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */
#ifndef __BGF_GPS_RGU_ON_REGS_H__
#define __BGF_GPS_RGU_ON_REGS_H__

#define BGF_GPS_RGU_ON_BASE                                    0x80000000

#define BGF_GPS_RGU_ON_GPS_L1_CR_ADDR                          (BGF_GPS_RGU_ON_BASE + 0x014)
#define BGF_GPS_RGU_ON_GPS_L1_DSPPRAM_PDN_EN_ADDR              (BGF_GPS_RGU_ON_BASE + 0x048)
#define BGF_GPS_RGU_ON_GPS_L1_DSPPRAM_SLP_EN_ADDR              (BGF_GPS_RGU_ON_BASE + 0x04c)
#define BGF_GPS_RGU_ON_GPS_L1_DSPXRAM_PDN_EN_ADDR              (BGF_GPS_RGU_ON_BASE + 0x050)
#define BGF_GPS_RGU_ON_GPS_L1_DSPXRAM_SLP_EN_ADDR              (BGF_GPS_RGU_ON_BASE + 0x054)
#define BGF_GPS_RGU_ON_GPS_L1_DSPYRAM_PDN_EN_ADDR              (BGF_GPS_RGU_ON_BASE + 0x058)
#define BGF_GPS_RGU_ON_GPS_L1_DSPYRAM_SLP_EN_ADDR              (BGF_GPS_RGU_ON_BASE + 0x05c)
#define BGF_GPS_RGU_ON_GPS_L1_DLY_CHAIN_CTL_ADDR               (BGF_GPS_RGU_ON_BASE + 0x160)
#define BGF_GPS_RGU_ON_GPS_L1_MEM_DLY_CTL_ADDR                 (BGF_GPS_RGU_ON_BASE + 0x164)
#define BGF_GPS_RGU_ON_GPS_L5_CR_ADDR                          (BGF_GPS_RGU_ON_BASE + 0x214)
#define BGF_GPS_RGU_ON_GPS_L5_DSPPRAM_PDN_EN_ADDR              (BGF_GPS_RGU_ON_BASE + 0x248)
#define BGF_GPS_RGU_ON_GPS_L5_DSPPRAM_SLP_EN_ADDR              (BGF_GPS_RGU_ON_BASE + 0x24c)
#define BGF_GPS_RGU_ON_GPS_L5_DSPXRAM_PDN_EN_ADDR              (BGF_GPS_RGU_ON_BASE + 0x250)
#define BGF_GPS_RGU_ON_GPS_L5_DSPXRAM_SLP_EN_ADDR              (BGF_GPS_RGU_ON_BASE + 0x254)
#define BGF_GPS_RGU_ON_GPS_L5_DSPYRAM_PDN_EN_ADDR              (BGF_GPS_RGU_ON_BASE + 0x258)
#define BGF_GPS_RGU_ON_GPS_L5_DSPYRAM_SLP_EN_ADDR              (BGF_GPS_RGU_ON_BASE + 0x25c)
#define BGF_GPS_RGU_ON_GPS_L5_MEM_DLY_CTL_ADDR                 (BGF_GPS_RGU_ON_BASE + 0x364)
#define BGF_GPS_RGU_ON_GPS_L5_DLY_CHAIN_CTL_ADDR               (BGF_GPS_RGU_ON_BASE + 0x360)

#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_SOFT_RST_B_ADDR        BGF_GPS_RGU_ON_GPS_L1_CR_ADDR
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_SOFT_RST_B_MASK        0x00000020
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_SOFT_RST_B_SHFT        5
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_ON_ADDR                BGF_GPS_RGU_ON_GPS_L1_CR_ADDR
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_ON_MASK                0x00000001
#define GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_ON_SHFT                0

#define GPS_RGU_ON_GPS_L1_DSPPRAM_PDN_EN_RGU_GPS_L1_PRAM_HWCTL_PDN_ADDR BGF_GPS_RGU_ON_GPS_L1_DSPPRAM_PDN_EN_ADDR
#define GPS_RGU_ON_GPS_L1_DSPPRAM_PDN_EN_RGU_GPS_L1_PRAM_HWCTL_PDN_MASK 0x000003FF
#define GPS_RGU_ON_GPS_L1_DSPPRAM_PDN_EN_RGU_GPS_L1_PRAM_HWCTL_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPPRAM_SLP_EN_RGU_GPS_L1_PRAM_HWCTL_SLP_ADDR BGF_GPS_RGU_ON_GPS_L1_DSPPRAM_SLP_EN_ADDR
#define GPS_RGU_ON_GPS_L1_DSPPRAM_SLP_EN_RGU_GPS_L1_PRAM_HWCTL_SLP_MASK 0x000003FF
#define GPS_RGU_ON_GPS_L1_DSPPRAM_SLP_EN_RGU_GPS_L1_PRAM_HWCTL_SLP_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPXRAM_PDN_EN_RGU_GPS_L1_XRAM_HWCTL_PDN_ADDR BGF_GPS_RGU_ON_GPS_L1_DSPXRAM_PDN_EN_ADDR
#define GPS_RGU_ON_GPS_L1_DSPXRAM_PDN_EN_RGU_GPS_L1_XRAM_HWCTL_PDN_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L1_DSPXRAM_PDN_EN_RGU_GPS_L1_XRAM_HWCTL_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPXRAM_SLP_EN_RGU_GPS_L1_XRAM_HWCTL_SLP_ADDR BGF_GPS_RGU_ON_GPS_L1_DSPXRAM_SLP_EN_ADDR
#define GPS_RGU_ON_GPS_L1_DSPXRAM_SLP_EN_RGU_GPS_L1_XRAM_HWCTL_SLP_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L1_DSPXRAM_SLP_EN_RGU_GPS_L1_XRAM_HWCTL_SLP_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPYRAM_PDN_EN_RGU_GPS_L1_YRAM_HWCTL_PDN_ADDR BGF_GPS_RGU_ON_GPS_L1_DSPYRAM_PDN_EN_ADDR
#define GPS_RGU_ON_GPS_L1_DSPYRAM_PDN_EN_RGU_GPS_L1_YRAM_HWCTL_PDN_MASK 0x000007FF
#define GPS_RGU_ON_GPS_L1_DSPYRAM_PDN_EN_RGU_GPS_L1_YRAM_HWCTL_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L1_DSPYRAM_SLP_EN_RGU_GPS_L1_YRAM_HWCTL_SLP_ADDR BGF_GPS_RGU_ON_GPS_L1_DSPYRAM_SLP_EN_ADDR
#define GPS_RGU_ON_GPS_L1_DSPYRAM_SLP_EN_RGU_GPS_L1_YRAM_HWCTL_SLP_MASK 0x000007FF
#define GPS_RGU_ON_GPS_L1_DSPYRAM_SLP_EN_RGU_GPS_L1_YRAM_HWCTL_SLP_SHFT 0

#define GPS_RGU_ON_GPS_L1_DLY_CHAIN_CTL_RGU_GPS_L1_MEM_PDN_DELAY_DUMMY_NUM_ADDR BGF_GPS_RGU_ON_GPS_L1_DLY_CHAIN_CTL_ADDR
#define GPS_RGU_ON_GPS_L1_DLY_CHAIN_CTL_RGU_GPS_L1_MEM_PDN_DELAY_DUMMY_NUM_MASK 0x000F0000
#define GPS_RGU_ON_GPS_L1_DLY_CHAIN_CTL_RGU_GPS_L1_MEM_PDN_DELAY_DUMMY_NUM_SHFT 16

#define GPS_RGU_ON_GPS_L1_MEM_DLY_CTL_RGU_GPSSYS_L1_MEM_ADJ_DLY_EN_ADDR BGF_GPS_RGU_ON_GPS_L1_MEM_DLY_CTL_ADDR
#define GPS_RGU_ON_GPS_L1_MEM_DLY_CTL_RGU_GPSSYS_L1_MEM_ADJ_DLY_EN_MASK 0x80000000
#define GPS_RGU_ON_GPS_L1_MEM_DLY_CTL_RGU_GPSSYS_L1_MEM_ADJ_DLY_EN_SHFT 31

#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_SOFT_RST_B_ADDR        BGF_GPS_RGU_ON_GPS_L5_CR_ADDR
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_SOFT_RST_B_MASK        0x00000020
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_SOFT_RST_B_SHFT        5
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_ON_ADDR                BGF_GPS_RGU_ON_GPS_L5_CR_ADDR
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_ON_MASK                0x00000001
#define GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_ON_SHFT                0

#define GPS_RGU_ON_GPS_L5_DSPPRAM_PDN_EN_RGU_GPS_L5_PRAM_HWCTL_PDN_ADDR BGF_GPS_RGU_ON_GPS_L5_DSPPRAM_PDN_EN_ADDR
#define GPS_RGU_ON_GPS_L5_DSPPRAM_PDN_EN_RGU_GPS_L5_PRAM_HWCTL_PDN_MASK 0x000003FF
#define GPS_RGU_ON_GPS_L5_DSPPRAM_PDN_EN_RGU_GPS_L5_PRAM_HWCTL_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPPRAM_SLP_EN_RGU_GPS_L5_PRAM_HWCTL_SLP_ADDR BGF_GPS_RGU_ON_GPS_L5_DSPPRAM_SLP_EN_ADDR
#define GPS_RGU_ON_GPS_L5_DSPPRAM_SLP_EN_RGU_GPS_L5_PRAM_HWCTL_SLP_MASK 0x000003FF
#define GPS_RGU_ON_GPS_L5_DSPPRAM_SLP_EN_RGU_GPS_L5_PRAM_HWCTL_SLP_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPXRAM_PDN_EN_RGU_GPS_L5_XRAM_HWCTL_PDN_ADDR BGF_GPS_RGU_ON_GPS_L5_DSPXRAM_PDN_EN_ADDR
#define GPS_RGU_ON_GPS_L5_DSPXRAM_PDN_EN_RGU_GPS_L5_XRAM_HWCTL_PDN_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L5_DSPXRAM_PDN_EN_RGU_GPS_L5_XRAM_HWCTL_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPXRAM_SLP_EN_RGU_GPS_L5_XRAM_HWCTL_SLP_ADDR BGF_GPS_RGU_ON_GPS_L5_DSPXRAM_SLP_EN_ADDR
#define GPS_RGU_ON_GPS_L5_DSPXRAM_SLP_EN_RGU_GPS_L5_XRAM_HWCTL_SLP_MASK 0x0000000F
#define GPS_RGU_ON_GPS_L5_DSPXRAM_SLP_EN_RGU_GPS_L5_XRAM_HWCTL_SLP_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPYRAM_PDN_EN_RGU_GPS_L5_YRAM_HWCTL_PDN_ADDR BGF_GPS_RGU_ON_GPS_L5_DSPYRAM_PDN_EN_ADDR
#define GPS_RGU_ON_GPS_L5_DSPYRAM_PDN_EN_RGU_GPS_L5_YRAM_HWCTL_PDN_MASK 0x000003FF
#define GPS_RGU_ON_GPS_L5_DSPYRAM_PDN_EN_RGU_GPS_L5_YRAM_HWCTL_PDN_SHFT 0

#define GPS_RGU_ON_GPS_L5_DSPYRAM_SLP_EN_RGU_GPS_L5_YRAM_HWCTL_SLP_ADDR BGF_GPS_RGU_ON_GPS_L5_DSPYRAM_SLP_EN_ADDR
#define GPS_RGU_ON_GPS_L5_DSPYRAM_SLP_EN_RGU_GPS_L5_YRAM_HWCTL_SLP_MASK 0x000003FF
#define GPS_RGU_ON_GPS_L5_DSPYRAM_SLP_EN_RGU_GPS_L5_YRAM_HWCTL_SLP_SHFT 0

#define GPS_RGU_ON_GPS_L5_MEM_DLY_CTL_RGU_GPSSYS_L5_MEM_ADJ_DLY_EN_ADDR BGF_GPS_RGU_ON_GPS_L5_MEM_DLY_CTL_ADDR
#define GPS_RGU_ON_GPS_L5_MEM_DLY_CTL_RGU_GPSSYS_L5_MEM_ADJ_DLY_EN_MASK 0x80000000
#define GPS_RGU_ON_GPS_L5_MEM_DLY_CTL_RGU_GPSSYS_L5_MEM_ADJ_DLY_EN_SHFT 31

#define GPS_RGU_ON_GPS_L5_DLY_CHAIN_CTL_RGU_GPS_L5_MEM_PDN_DELAY_DUMMY_NUM_ADDR BGF_GPS_RGU_ON_GPS_L5_DLY_CHAIN_CTL_ADDR
#define GPS_RGU_ON_GPS_L5_DLY_CHAIN_CTL_RGU_GPS_L5_MEM_PDN_DELAY_DUMMY_NUM_MASK 0x000F0000
#define GPS_RGU_ON_GPS_L5_DLY_CHAIN_CTL_RGU_GPS_L5_MEM_PDN_DELAY_DUMMY_NUM_SHFT 16

#endif /* __BGF_GPS_RGU_ON_REGS_H__ */

