ccflags-y += \
		 -I$(DEVICE_MODULES_PATH)/drivers/rpmsg/ \
		 -I$(DEVICE_MODULES_PATH)/drivers/remoteproc/

cam-ut-objs := mtk_cam_ut-cam.o \
	       mtk_cam_ut-seninf.o \
	       mtk_cam_ut.o \
	       mtk_cam_ut-camsv.o

obj-$(CONFIG_VIDEO_MTK_ISP_CAMSYS) += cam-ut.o
