# Sources path
KO_CODE_PATH := $(if $(filter /%,$(src)),,$(srctree)/)$(src)

# KO specfied attributes
WLAN_CHIP_ID := 6891
MTK_COMBO_CHIP := CONNAC2X2_SOC3_0
WIFI_IP_SET := 1
CONNAC_VER := 2_0
CONFIG_MTK_COMBO_WIFI_HIF := axi
MTK_ANDROID_EMI := y
MTK_ANDROID_WMT := y

MTK_WIFI_PLAT_ALPS := y
MODULE_NAME := wlan_drv_gen4m_6891

include $(KO_CODE_PATH)/Kbuild.main