# Sources path
KO_CODE_PATH := $(if $(filter /%,$(src)),,$(srctree)/)$(src)

# KO specfied attributes
WLAN_CHIP_ID := 6853
MTK_COMBO_CHIP := SOC2_2X2
WIFI_IP_SET := 3
CONNAC_VER := 1_0
CONFIG_MTK_COMBO_WIFI_HIF := axi
CONFIG_MTK_WIFI_CONNAC1X := y
MTK_ANDROID_WMT := y
MTK_ANDROID_EMI := y
MODULE_NAME := wlan_drv_gen4m_6853

include $(KO_CODE_PATH)/Kbuild.main
