# Sources path
KO_CODE_PATH := $(if $(filter /%,$(src)),,$(srctree)/)$(src)

# KO specfied attributes
WLAN_CHIP_ID := 6653
MTK_COMBO_CHIP := MT6653
CONNAC_VER := 3_0
CONFIG_MTK_COMBO_WIFI_HIF := pcie
MTK_ANDROID_WMT := y
MTK_ANDROID_EMI := y

MODULE_NAME := wlan_drv_gen4m_6989_6653
CONFIG_WLAN_PLATFORM := mt6989
include $(KO_CODE_PATH)/Kbuild.main