###############################################################################
# Necessary Check
###############################################################################
ifneq ($(KERNEL_OUT),)
    ccflags-y += -imacros $(KERNEL_OUT)/include/generated/autoconf.h
endif

ifndef TOP
    TOP := $(srctree)/..
endif

# Force build fail on modpost warning
KBUILD_MODPOST_FAIL_ON_WARNINGS := y

###############################################################################
# WIFI PAGE POOL Module
###############################################################################
MODULE_NAME := wlan_page_pool
obj-m += $(MODULE_NAME).o
$(MODULE_NAME)-objs += wifi_page_pool.o
