/* SPDX-License-Identifier: GPL-2.0 OR BSD-3-Clause */
/*
 * Copyright (c) 2019 MediaTek Inc.
 */

#ifndef __WF_WTBLON_TOP_REGS_H__
#define __WF_WTBLON_TOP_REGS_H__

#include "hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif


/* ************************************************************************** */
/*  */
/* WF_WTBLON_TOP CR Definitions */
/*  */
/* ************************************************************************** */

#define WF_WTBLON_TOP_BASE                                     0x820d4000

#define WF_WTBLON_TOP_RVCDAR00_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0000) /* 4000 */
#define WF_WTBLON_TOP_RVCDAR01_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0004) /* 4004 */
#define WF_WTBLON_TOP_RVCDAR02_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0008) /* 4008 */
#define WF_WTBLON_TOP_RVCDAR03_ADDR \
	(WF_WTBLON_TOP_BASE + 0x000C) /* 400C */
#define WF_WTBLON_TOP_RVCDAR_EXT_00_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0080) /* 4080 */
#define WF_WTBLON_TOP_PSCDAR00_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0100) /* 4100 */
#define WF_WTBLON_TOP_PSCDAR01_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0104) /* 4104 */
#define WF_WTBLON_TOP_PSCDAR02_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0108) /* 4108 */
#define WF_WTBLON_TOP_PSCDAR03_ADDR \
	(WF_WTBLON_TOP_BASE + 0x010C) /* 410C */
#define WF_WTBLON_TOP_PSCDAR_EXT_00_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0180) /* 4180 */
#define WF_WTBLON_TOP_TCGSBR_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0300) /* 4300 */
#define WF_WTBLON_TOP_TCGSBRe_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0308) /* 4308 */
#define WF_WTBLON_TOP_ACGSBR_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0320) /* 4320 */
#define WF_WTBLON_TOP_ACGSBRe_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0328) /* 4328 */
#define WF_WTBLON_TOP_RCGSBR_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0340) /* 4340 */
#define WF_WTBLON_TOP_RSCR_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0360) /* 4360 */
#define WF_WTBLON_TOP_RDWLR0_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0364) /* 4364 */
#define WF_WTBLON_TOP_RDWLR1_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0368) /* 4368 */
#define WF_WTBLON_TOP_RDWLR2_ADDR \
	(WF_WTBLON_TOP_BASE + 0x036C) /* 436C */
#define WF_WTBLON_TOP_WDUCR_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0370) /* 4370 */
#define WF_WTBLON_TOP_WTBLOR_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0374) /* 4374 */
#define WF_WTBLON_TOP_WIUCR_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0380) /* 4380 */
#define WF_WTBLON_TOP_WMUDR_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0384) /* 4384 */
#define WF_WTBLON_TOP_WMUMR_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0388) /* 4388 */
#define WF_WTBLON_TOP_RICR0_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0390) /* 4390 */
#define WF_WTBLON_TOP_RICR1_ADDR \
	(WF_WTBLON_TOP_BASE + 0x0394) /* 4394 */
#define WF_WTBLON_TOP_RIUCR0_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03A0) /* 43A0 */
#define WF_WTBLON_TOP_RIUCR1_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03A4) /* 43A4 */
#define WF_WTBLON_TOP_RIUCR2_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03A8) /* 43A8 */
#define WF_WTBLON_TOP_RIUCR3_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03AC) /* 43AC */
#define WF_WTBLON_TOP_ITCR_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03B0) /* 43B0 */
#define WF_WTBLON_TOP_ITDR0_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03B8) /* 43B8 */
#define WF_WTBLON_TOP_ITDR1_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03BC) /* 43BC */
#define WF_WTBLON_TOP_MBIST_0_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03D0) /* 43D0 */
#define WF_WTBLON_TOP_MBIST_3_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03D4) /* 43D4 */
#define WF_WTBLON_TOP_MBIST_4_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03D8) /* 43D8 */
#define WF_WTBLON_TOP_MBIST_5_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03DC) /* 43DC */
#define WF_WTBLON_TOP_MBIST_11_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03E0) /* 43E0 */
#define WF_WTBLON_TOP_MBIST_12_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03E4) /* 43E4 */
#define WF_WTBLON_TOP_MBIST_13_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03E8) /* 43E8 */
#define WF_WTBLON_TOP_MBIST_14_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03EC) /* 43EC */
#define WF_WTBLON_TOP_DMY0_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03F0) /* 43F0 */
#define WF_WTBLON_TOP_DMY1_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03F4) /* 43F4 */
#define WF_WTBLON_TOP_DFR_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03F8) /* 43F8 */
#define WF_WTBLON_TOP_DBG_ADDR \
	(WF_WTBLON_TOP_BASE + 0x03FC) /* 43FC */


#define WF_WTBLON_TOP_WDUCR_GROUP_ADDR WF_WTBLON_TOP_WDUCR_ADDR
#define WF_WTBLON_TOP_WDUCR_GROUP_MASK 0x0000001F      /* GROUP[4..0] */
#define WF_WTBLON_TOP_WDUCR_GROUP_SHFT 0

#ifdef __cplusplus
}
#endif

#endif /* __WF_WTBLON_TOP_REGS_H__ */
