/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */
#ifndef __CONN_CLKGEN_ON_TOP_H__
#define __CONN_CLKGEN_ON_TOP_H__

#define CONN_CLKGEN_ON_TOP_BASE                                 0x18009000

#define CONN_CLKGEN_ON_TOP_CKGEN_BUS_ADDR                      (CONN_CLKGEN_ON_TOP_BASE + 0xA00)

#define CONN_INFRA_CFG_CKGEN_BUS_ADDR                           CONN_CLKGEN_ON_TOP_CKGEN_BUS_ADDR

#define CONN_INFRA_CFG_CKGEN_BUS_CONN_CO_EXT_UART_PTA_OSC_CKEN_ADDR CONN_CLKGEN_ON_TOP_CKGEN_BUS_ADDR
#define CONN_INFRA_CFG_CKGEN_BUS_CONN_CO_EXT_UART_PTA_OSC_CKEN_MASK 0x00000020
#define CONN_INFRA_CFG_CKGEN_BUS_CONN_CO_EXT_UART_PTA_OSC_CKEN_SHFT 5
#define CONN_INFRA_CFG_CKGEN_BUS_CONN_CO_EXT_UART_PTA_HCLK_CKEN_ADDR CONN_CLKGEN_ON_TOP_CKGEN_BUS_ADDR
#define CONN_INFRA_CFG_CKGEN_BUS_CONN_CO_EXT_UART_PTA_HCLK_CKEN_MASK 0x00000010
#define CONN_INFRA_CFG_CKGEN_BUS_CONN_CO_EXT_UART_PTA_HCLK_CKEN_SHFT 4
#define CONN_INFRA_CFG_CKGEN_BUS_CONN_CO_EXT_UART_PTA5_OSC_CKEN_ADDR CONN_CLKGEN_ON_TOP_CKGEN_BUS_ADDR
#define CONN_INFRA_CFG_CKGEN_BUS_CONN_CO_EXT_UART_PTA5_OSC_CKEN_MASK 0x00000008
#define CONN_INFRA_CFG_CKGEN_BUS_CONN_CO_EXT_UART_PTA5_OSC_CKEN_SHFT 3
#define CONN_INFRA_CFG_CKGEN_BUS_CONN_CO_EXT_UART_PTA5_HCLK_CKEN_ADDR CONN_CLKGEN_ON_TOP_CKGEN_BUS_ADDR
#define CONN_INFRA_CFG_CKGEN_BUS_CONN_CO_EXT_UART_PTA5_HCLK_CKEN_MASK 0x00000004
#define CONN_INFRA_CFG_CKGEN_BUS_CONN_CO_EXT_UART_PTA5_HCLK_CKEN_SHFT 2



#endif /* _CONN_CLKGEN_ON_TOP_H_ */

