/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * Copyright (c) 2021 MediaTek Inc.
 */

#ifndef __CONN_DBG_CTL_REGS_H__
#define __CONN_DBG_CTL_REGS_H__

#include "hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif

#define CONN_DBG_CTL_BASE \
	(0x18023000 + CONN_INFRA_REMAPPING_OFFSET)

#define CONN_DBG_CTL_CONN_INFRA_BUS_CLK_DETECT_ADDR \
	(CONN_DBG_CTL_BASE + 0x000)
#define CONN_DBG_CTL_CONN_INFRA_MONFLAG_OUT_ADDR \
	(CONN_DBG_CTL_BASE + 0x200)
#define CONN_DBG_CTL_CONN_INFRA_BUS_TIMEOUT_IRQ_ADDR \
	(CONN_DBG_CTL_BASE + 0x400)
#define CONN_DBG_CTL_CONN_INFRA_OFF_BUS_DBG_OUT_ADDR \
	(CONN_DBG_CTL_BASE + 0x404)
#define CONN_DBG_CTL_CONN_INFRA_OFF_BUS_DBG_SEL_ADDR \
	(CONN_DBG_CTL_BASE + 0x408)
#define CONN_DBG_CTL_CONN_INFRA_OFF_DEBUGSYS_CTRL_ADDR \
	(CONN_DBG_CTL_BASE + 0x40C)
#define CONN_DBG_CTL_CONN_VON_VDNR_GLUE_BUS_S2P_N6_TIMEOUT_INFO_ADDR \
	(CONN_DBG_CTL_BASE + 0x410)
#define CONN_DBG_CTL_CONN_VON_VDNR_GLUE_BUS_S2P_N6_TIMEOUT_ADDR_ADDR \
	(CONN_DBG_CTL_BASE + 0x414)
#define CONN_DBG_CTL_CONN_VON_VDNR_GLUE_BUS_S2P_N6_TIMEOUT_WDATA_ADDR \
	(CONN_DBG_CTL_BASE + 0x418)
#define CONN_DBG_CTL_CONN_VON_VDNR_GLUE_BUS_P_D_N54_TIMEOUT_INFO_ADDR \
	(CONN_DBG_CTL_BASE + 0x41C)
#define CONN_DBG_CTL_CONN_VON_VDNR_GLUE_BUS_P_D_N54_TIMEOUT_ADDR_ADDR \
	(CONN_DBG_CTL_BASE + 0x420)
#define CONN_DBG_CTL_CONN_VON_VDNR_GLUE_BUS_P_D_N54_TIMEOUT_WDATA_ADDR \
	(CONN_DBG_CTL_BASE + 0x424)
#define CONN_DBG_CTL_CONN_VON_VDNR_GLUE_BUS_P_D_N57_TIMEOUT_INFO_ADDR \
	(CONN_DBG_CTL_BASE + 0x428)
#define CONN_DBG_CTL_CONN_VON_VDNR_GLUE_BUS_P_D_N57_TIMEOUT_ADDR_ADDR \
	(CONN_DBG_CTL_BASE + 0x42C)
#define CONN_DBG_CTL_CONN_VON_VDNR_GLUE_BUS_P_D_N57_TIMEOUT_WDATA_ADDR \
	(CONN_DBG_CTL_BASE + 0x430)

#define CONN_DBG_CTL_CONN_DEADFEED_PROT_EN_ADDR \
	(CONN_DBG_CTL_BASE + 0x434)

#define CONN_DBG_CTL_WF_MCU_DBGOUT_SEL_ADDR \
	(CONN_DBG_CTL_BASE + 0x604)
#define CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR \
	(CONN_DBG_CTL_BASE + 0x608)
#define CONN_DBG_CTL_WF_MCU_DBG_PC_LOG_SEL_ADDR \
	(CONN_DBG_CTL_BASE + 0x60C)
#define CONN_DBG_CTL_WF_MCU_DBG_PC_LOG_ADDR \
	(CONN_DBG_CTL_BASE + 0x610)
#define CONN_DBG_CTL_WF_MCU_DBG_GPR_LOG_SEL_ADDR \
	(CONN_DBG_CTL_BASE + 0x614)
#define CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR \
	(CONN_DBG_CTL_BASE + 0x620)
#define CONN_DBG_CTL_WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_DEBUGSYS_CTRL_ADDR \
	(CONN_DBG_CTL_BASE + 0x628)
#define CONN_DBG_CTL_WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_BUS_TIMEOUT_IRQ_ADDR \
	(CONN_DBG_CTL_BASE + 0x62C)
#define CONN_DBG_CTL_WF_VON_DEBUG_OUT_ADDR \
	(CONN_DBG_CTL_BASE + 0x638)

#define CONN_DBG_CTL_CR_HOSTCR2BG_OFF_DEBUG_SEL_ADDR \
	(CONN_DBG_CTL_BASE + 0xA0C)
#define CONN_DBG_CTL_BGSYS_OFF_MONFLG_OUT_ADDR \
	(CONN_DBG_CTL_BASE + 0xA10)
#define CONN_DBG_CTL_CR_HOSTCR2BG_ON_DEBUG_SEL_ADDR \
	(CONN_DBG_CTL_BASE + 0xA1C)
#define CONN_DBG_CTL_BGSYS_ON_MONFLG_OUT_ADDR \
	(CONN_DBG_CTL_BASE + 0xA20)

#define CONN_DBG_CTL_WF_MCU_DBGOUT_SEL_WF_MCU_DBGOUT_SEL_ADDR \
	CONN_DBG_CTL_WF_MCU_DBGOUT_SEL_ADDR
#define CONN_DBG_CTL_WF_MCU_DBGOUT_SEL_WF_MCU_DBGOUT_SEL_MASK \
	0x00000007
#define CONN_DBG_CTL_WF_MCU_DBGOUT_SEL_WF_MCU_DBGOUT_SEL_SHFT \
	0

#define CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR \
	CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_ADDR
#define CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_MASK \
	0xFFFFFFFF
#define CONN_DBG_CTL_WF_MCU_GPR_BUS_DBGOUT_LOG_WF_MCU_GPR_BUS_DBGOUT_LOG_SHFT \
	0

#define CONN_DBG_CTL_WF_MCU_DBG_PC_LOG_SEL_WF_MCU_DBG_PC_LOG_SEL_ADDR \
	CONN_DBG_CTL_WF_MCU_DBG_PC_LOG_SEL_ADDR
#define CONN_DBG_CTL_WF_MCU_DBG_PC_LOG_SEL_WF_MCU_DBG_PC_LOG_SEL_MASK \
	0x0000003F
#define CONN_DBG_CTL_WF_MCU_DBG_PC_LOG_SEL_WF_MCU_DBG_PC_LOG_SEL_SHFT \
	0

#define CONN_DBG_CTL_WF_MCU_DBG_PC_LOG_WF_MCU_DBG_PC_LOG_ADDR \
	CONN_DBG_CTL_WF_MCU_DBG_PC_LOG_ADDR
#define CONN_DBG_CTL_WF_MCU_DBG_PC_LOG_WF_MCU_DBG_PC_LOG_MASK \
	0xFFFFFFFF
#define CONN_DBG_CTL_WF_MCU_DBG_PC_LOG_WF_MCU_DBG_PC_LOG_SHFT \
	0

#define CONN_DBG_CTL_WF_MCU_DBG_GPR_LOG_SEL_WF_MCU_DBG_GPR_LOG_SEL_ADDR \
	CONN_DBG_CTL_WF_MCU_DBG_GPR_LOG_SEL_ADDR
#define CONN_DBG_CTL_WF_MCU_DBG_GPR_LOG_SEL_WF_MCU_DBG_GPR_LOG_SEL_MASK \
	0x0000003F
#define CONN_DBG_CTL_WF_MCU_DBG_GPR_LOG_SEL_WF_MCU_DBG_GPR_LOG_SEL_SHFT \
	0

#define CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_ADDR \
	CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_ADDR
#define CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_MASK \
	0x00001FFF
#define CONN_DBG_CTL_WF_CORE_PC_INDEX_FR_HIF_WF_CORE_PC_INDEX_FR_HIF_SHFT \
	0

#define CONN_DBG_CTL_WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_DEBUGSYS_CTRL_WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_DEBUGSYS_CTRL_ADDR \
	CONN_DBG_CTL_WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_DEBUGSYS_CTRL_ADDR
#define CONN_DBG_CTL_WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_DEBUGSYS_CTRL_WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_DEBUGSYS_CTRL_MASK \
	0xFFFFFFFF
#define CONN_DBG_CTL_WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_DEBUGSYS_CTRL_WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_DEBUGSYS_CTRL_SHFT \
	0

#define CONN_DBG_CTL_WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_BUS_TIMEOUT_IRQ_WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_BUS_TIMEOUT_IRQ_ADDR \
	CONN_DBG_CTL_WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_BUS_TIMEOUT_IRQ_ADDR
#define CONN_DBG_CTL_WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_BUS_TIMEOUT_IRQ_WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTR_AO_BUS_TIMEOUT_IRQ_MASK \
	0x00000001
#define CONN_DBG_CTL_WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_BUS_TIMEOUT_IRQ_WF_MCUSYS_INFRA_VDNR_GEN_DEBUG_CTRL_AO_BUS_TIMEOUT_IRQ_SHFT \
	0

#define CONN_DBG_CTL_WF_VON_DEBUG_OUT_WF_VON_DEBUG_OUT_ADDR \
	CONN_DBG_CTL_WF_VON_DEBUG_OUT_ADDR
#define CONN_DBG_CTL_WF_VON_DEBUG_OUT_WF_VON_DEBUG_OUT_MASK \
	0xFFFFFFFF
#define CONN_DBG_CTL_WF_VON_DEBUG_OUT_WF_VON_DEBUG_OUT_SHFT \
	0

#define CONN_DBG_CTL_CONN_INFRA_BUS_CLK_DETECT_LP_OSC_CK_DETECT_ADDR \
	CONN_DBG_CTL_CONN_INFRA_BUS_CLK_DETECT_ADDR
#define CONN_DBG_CTL_CONN_INFRA_BUS_CLK_DETECT_LP_OSC_CK_DETECT_MASK \
	0x00000008
#define CONN_DBG_CTL_CONN_INFRA_BUS_CLK_DETECT_LP_OSC_CK_DETECT_SHFT \
	3
#define CONN_DBG_CTL_CONN_INFRA_BUS_CLK_DETECT_OSC_CK_DETECT_ADDR \
	CONN_DBG_CTL_CONN_INFRA_BUS_CLK_DETECT_ADDR
#define CONN_DBG_CTL_CONN_INFRA_BUS_CLK_DETECT_OSC_CK_DETECT_MASK \
	0x00000004
#define CONN_DBG_CTL_CONN_INFRA_BUS_CLK_DETECT_OSC_CK_DETECT_SHFT \
	2
#define CONN_DBG_CTL_CONN_INFRA_BUS_CLK_DETECT_CONN_INFRA_HCLK_FR_DETECT_ADDR \
	CONN_DBG_CTL_CONN_INFRA_BUS_CLK_DETECT_ADDR
#define CONN_DBG_CTL_CONN_INFRA_BUS_CLK_DETECT_CONN_INFRA_HCLK_FR_DETECT_MASK \
	0x00000002
#define CONN_DBG_CTL_CONN_INFRA_BUS_CLK_DETECT_CONN_INFRA_HCLK_FR_DETECT_SHFT \
	1

#ifdef __cplusplus
}
#endif

#endif
