/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */

#ifndef __CONN_BUS_CR_REGS_H__
#define __CONN_BUS_CR_REGS_H__

#include "hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif

#define CONN_BUS_CR_BASE \
	(0x18048000 + CONN_INFRA_REMAPPING_OFFSET)

#define CONN_BUS_CR_ADDR_CONN2SUBSYS_0_AHB_GALS_DBG_ADDR \
	(CONN_BUS_CR_BASE + 0xA14)


#define CONN_BUS_CR_ADDR_CONN2SUBSYS_0_AHB_GALS_DBG_CONN2SUBSYS_0_GALS_TX_DEBUG_OUT_ADDR \
	CONN_BUS_CR_ADDR_CONN2SUBSYS_0_AHB_GALS_DBG_ADDR
#define CONN_BUS_CR_ADDR_CONN2SUBSYS_0_AHB_GALS_DBG_CONN2SUBSYS_0_GALS_TX_DEBUG_OUT_MASK \
	0xFFFFFFFF
#define CONN_BUS_CR_ADDR_CONN2SUBSYS_0_AHB_GALS_DBG_CONN2SUBSYS_0_GALS_TX_DEBUG_OUT_SHFT \
	0

#ifdef __cplusplus
}
#endif

#endif
