/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * Copyright (c) 2021 MediaTek Inc.
 */

#ifndef __CONN_RGU_ON_REGS_H__
#define __CONN_RGU_ON_REGS_H__

#include "hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif

#define CONN_RGU_ON_BASE \
	(0x18000000 + CONN_INFRA_REMAPPING_OFFSET)

#define CONN_RGU_ON_CONN_INFRA_OFF_TOP_PWR_CTL_ADDR \
	(CONN_RGU_ON_BASE + 0x000)
#define CONN_RGU_ON_CONN_INFRA_OFF_TOP_PWR_ON_S_EN_ADDR \
	(CONN_RGU_ON_BASE + 0x004)
#define CONN_RGU_ON_WFSYS_ON_TOP_PWR_CTL_ADDR \
	(CONN_RGU_ON_BASE + 0x010)
#define CONN_RGU_ON_WFSYS_ON_TOP_PWR_ON_S_EN_ADDR \
	(CONN_RGU_ON_BASE + 0x014)
#define CONN_RGU_ON_BGFSYS_ON_TOP_PWR_CTL_ADDR \
	(CONN_RGU_ON_BASE + 0x020)
#define CONN_RGU_ON_BGFSYS_ON_TOP_PWR_ON_S_EN_ADDR \
	(CONN_RGU_ON_BASE + 0x024)
#define CONN_RGU_ON_BGFSYS_ON_TOP_PWR_CTL_1_ADDR \
	(CONN_RGU_ON_BASE + 0x028)
#define CONN_RGU_ON_WFSYS_SLPPROT_RDY_CTL_ADDR \
	(CONN_RGU_ON_BASE + 0x030)
#define CONN_RGU_ON_BGFSYS_SLPPROT_RDY_CTL_ADDR \
	(CONN_RGU_ON_BASE + 0x034)
#define CONN_RGU_ON_MEM_PWR_CTL_ADDR \
	(CONN_RGU_ON_BASE + 0x040)
#define CONN_RGU_ON_SYSRAM_SHIFT_CHAIN_CTL_ADDR \
	(CONN_RGU_ON_BASE + 0x044)
#define CONN_RGU_ON_SYSRAM_HWCTL_PDN_ADDR \
	(CONN_RGU_ON_BASE + 0x050)
#define CONN_RGU_ON_SYSRAM_HWCTL_SLP_ADDR \
	(CONN_RGU_ON_BASE + 0x054)
#define CONN_RGU_ON_SYSRAM_SWCTL_PDN_ADDR \
	(CONN_RGU_ON_BASE + 0x058)
#define CONN_RGU_ON_SYSRAM_SWCTL_SLP_ADDR \
	(CONN_RGU_ON_BASE + 0x05C)
#define CONN_RGU_ON_SYSRAM_SWCTL_CKISO_ADDR \
	(CONN_RGU_ON_BASE + 0x060)
#define CONN_RGU_ON_SYSRAM_SWCTL_ISOINT_ADDR \
	(CONN_RGU_ON_BASE + 0x064)
#define CONN_RGU_ON_CO_EXT_MEM_HWCTL_PDN_ADDR \
	(CONN_RGU_ON_BASE + 0x070)
#define CONN_RGU_ON_CO_EXT_MEM_HWCTL_SLP_ADDR \
	(CONN_RGU_ON_BASE + 0x074)
#define CONN_RGU_ON_CO_EXT_MEM_SWCTL_PDN_ADDR \
	(CONN_RGU_ON_BASE + 0x078)
#define CONN_RGU_ON_CO_EXT_MEM_SWCTL_SLP_ADDR \
	(CONN_RGU_ON_BASE + 0x07C)
#define CONN_RGU_ON_CO_EXT_MEM_SWCTL_CKISO_ADDR \
	(CONN_RGU_ON_BASE + 0x080)
#define CONN_RGU_ON_CO_EXT_MEM_SWCTL_ISOINT_ADDR \
	(CONN_RGU_ON_BASE + 0x084)
#define CONN_RGU_ON_FM_CTRL_MEM_HWCTL_PDN_ADDR \
	(CONN_RGU_ON_BASE + 0x090)
#define CONN_RGU_ON_FM_CTRL_MEM_HWCTL_SLP_ADDR \
	(CONN_RGU_ON_BASE + 0x094)
#define CONN_RGU_ON_FM_CTRL_MEM_SWCTL_PDN_ADDR \
	(CONN_RGU_ON_BASE + 0x098)
#define CONN_RGU_ON_FM_CTRL_MEM_SWCTL_SLP_ADDR \
	(CONN_RGU_ON_BASE + 0x09C)
#define CONN_RGU_ON_FM_CTRL_MEM_SWCTL_CKISO_ADDR \
	(CONN_RGU_ON_BASE + 0x0A0)
#define CONN_RGU_ON_ECC_CTRL_MEM_HWCTL_PDN_ADDR \
	(CONN_RGU_ON_BASE + 0x0A8)
#define CONN_RGU_ON_ECC_CTRL_MEM_SWCTL_PDN_ADDR \
	(CONN_RGU_ON_BASE + 0x0AC)
#define CONN_RGU_ON_ECC_CTRL_MEM_SWCTL_ISOINT_ADDR \
	(CONN_RGU_ON_BASE + 0x0B0)
#define CONN_RGU_ON_WFSYS_WM_WDT_EN_ADDR \
	(CONN_RGU_ON_BASE + 0x100)
#define CONN_RGU_ON_WFSYS_WA_WDT_EN_ADDR \
	(CONN_RGU_ON_BASE + 0x104)
#define CONN_RGU_ON_BGFSYS_WDT_EN_ADDR \
	(CONN_RGU_ON_BASE + 0x108)
#define CONN_RGU_ON_BGFSYS1_WDT_EN_ADDR \
	(CONN_RGU_ON_BASE + 0x10C)
#define CONN_RGU_ON_WFSYS_CPU_SW_RST_B_ADDR \
	(CONN_RGU_ON_BASE + 0x120)
#define CONN_RGU_ON_BGFSYS_CPU_SW_RST_B_ADDR \
	(CONN_RGU_ON_BASE + 0x124)
#define CONN_RGU_ON_BGFSYS1_CPU_SW_RST_B_ADDR \
	(CONN_RGU_ON_BASE + 0x128)
#define CONN_RGU_ON_WFSYS_SW_RST_B_ADDR \
	(CONN_RGU_ON_BASE + 0x140)
#define CONN_RGU_ON_BGFSYS_SW_RST_B_ADDR \
	(CONN_RGU_ON_BASE + 0x144)
#define CONN_RGU_ON_BGFSYS1_SW_RST_B_ADDR \
	(CONN_RGU_ON_BASE + 0x148)
#define CONN_RGU_ON_SEMA_M0_SW_RST_B_ADDR \
	(CONN_RGU_ON_BASE + 0x158)
#define CONN_RGU_ON_SEMA_M1_SW_RST_B_ADDR \
	(CONN_RGU_ON_BASE + 0x15C)
#define CONN_RGU_ON_SEMA_M2_SW_RST_B_ADDR \
	(CONN_RGU_ON_BASE + 0x160)
#define CONN_RGU_ON_SEMA_M3_SW_RST_B_ADDR \
	(CONN_RGU_ON_BASE + 0x164)
#define CONN_RGU_ON_WFSYS_ON_TOP_PWR_ST_ADDR \
	(CONN_RGU_ON_BASE + 0x400)
#define CONN_RGU_ON_BGFSYS_ON_TOP_PWR_ST_ADDR \
	(CONN_RGU_ON_BASE + 0x404)
#define CONN_RGU_ON_CONN_INFRA_OFF_TOP_PWR_ST_ADDR \
	(CONN_RGU_ON_BASE + 0x408)
#define CONN_RGU_ON_WFSYS_ON_TOP_PWR_ACK_ST_ADDR \
	(CONN_RGU_ON_BASE + 0x410)
#define CONN_RGU_ON_BGFSYS_ON_TOP_PWR_ACK_ST_ADDR \
	(CONN_RGU_ON_BASE + 0x414)
#define CONN_RGU_ON_CONN_INFRA_OFF_TOP_PWR_ACK_ST_ADDR \
	(CONN_RGU_ON_BASE + 0x418)
#define CONN_RGU_ON_WFSYS_OFF_TOP_PWR_ACK_ST_ADDR \
	(CONN_RGU_ON_BASE + 0x420)
#define CONN_RGU_ON_BGFSYS_OFF_TOP_PWR_ACK_ST_ADDR \
	(CONN_RGU_ON_BASE + 0x424)
#define CONN_RGU_ON_BGFSYS_OFF1_TOP_PWR_ACK_ST_ADDR \
	(CONN_RGU_ON_BASE + 0x428)
#define CONN_RGU_ON_SYSRAM_PDN_ST_ADDR \
	(CONN_RGU_ON_BASE + 0x440)
#define CONN_RGU_ON_SYSRAM_SLP_ST_ADDR \
	(CONN_RGU_ON_BASE + 0x444)
#define CONN_RGU_ON_SYSRAM_CKISO_ST_ADDR \
	(CONN_RGU_ON_BASE + 0x448)
#define CONN_RGU_ON_SYSRAM_ISOINT_ST_ADDR \
	(CONN_RGU_ON_BASE + 0x44C)
#define CONN_RGU_ON_CO_EXT_MEM_PDN_ST_ADDR \
	(CONN_RGU_ON_BASE + 0x450)
#define CONN_RGU_ON_CO_EXT_MEM_SLP_ST_ADDR \
	(CONN_RGU_ON_BASE + 0x454)
#define CONN_RGU_ON_CO_EXT_MEM_CKISO_ST_ADDR \
	(CONN_RGU_ON_BASE + 0x458)
#define CONN_RGU_ON_CO_EXT_MEM_ISOINT_ST_ADDR \
	(CONN_RGU_ON_BASE + 0x45C)
#define CONN_RGU_ON_FM_CTRL_MEM_PDN_ST_ADDR \
	(CONN_RGU_ON_BASE + 0x460)
#define CONN_RGU_ON_FM_CTRL_MEM_SLP_ST_ADDR \
	(CONN_RGU_ON_BASE + 0x464)
#define CONN_RGU_ON_FM_CTRL_MEM_CKISO_ST_ADDR \
	(CONN_RGU_ON_BASE + 0x468)
#define CONN_RGU_ON_FM_CTRL_MEM_ISOINT_ST_ADDR \
	(CONN_RGU_ON_BASE + 0x46C)
#define CONN_RGU_ON_ECC_CTRL_MEM_PDN_ST_ADDR \
	(CONN_RGU_ON_BASE + 0x470)
#define CONN_RGU_ON_ECC_CTRL_MEM_ISOINT_ST_ADDR \
	(CONN_RGU_ON_BASE + 0x474)

#ifdef __cplusplus
}
#endif

#endif /* __CONN_RGU_ON_REGS_H__*/
