/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * Copyright (c) 2021 MediaTek Inc.
 */

#ifndef __CONN_CLKGEN_TOP_REGS_H__
#define __CONN_CLKGEN_TOP_REGS_H__

#include "hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif

#define CONN_CLKGEN_TOP_BASE \
	(0x18012000 + CONN_INFRA_REMAPPING_OFFSET)

#define CONN_CLKGEN_TOP_CKGEN_BUS_BPLL_DIV_1_ADDR \
	(CONN_CLKGEN_TOP_BASE + 0x000)
#define CONN_CLKGEN_TOP_CKGEN_BUS_WPLL_DIV_1_ADDR \
	(CONN_CLKGEN_TOP_BASE + 0x008)
#define CONN_CLKGEN_TOP_CLKGEN_RFSPI_CK_CTRL_ADDR \
	(CONN_CLKGEN_TOP_BASE + 0x038)
#define CONN_CLKGEN_TOP_CLKGEN_RFSPI_MUX_STATUS_ADDR \
	(CONN_CLKGEN_TOP_BASE + 0x03C)
#define CONN_CLKGEN_TOP_CLKGEN_BUS_PLL_REQ_CTRL_0_ADDR \
	(CONN_CLKGEN_TOP_BASE + 0x040)
#define CONN_CLKGEN_TOP_CLKGEN_BUS_PLL_REQ_CTRL_1_ADDR \
	(CONN_CLKGEN_TOP_BASE + 0x044)
#define CONN_CLKGEN_TOP_CLKGEN_BUS_PLL_REQ_CTRL_1_SET_ADDR \
	(CONN_CLKGEN_TOP_BASE + 0x048)
#define CONN_CLKGEN_TOP_CLKGEN_BUS_PLL_REQ_CTRL_1_CLR_ADDR \
	(CONN_CLKGEN_TOP_BASE + 0x04C)
#define CONN_CLKGEN_TOP_CKGEN_BUS_ADDR \
	(CONN_CLKGEN_TOP_BASE + 0x050)
#define CONN_CLKGEN_TOP_CONN_INFRA_CKGEN_ECC_ADDR \
	(CONN_CLKGEN_TOP_BASE + 0x054)
#define CONN_CLKGEN_TOP_CONN_INFRA_CKGEN_COEX_ADDR \
	(CONN_CLKGEN_TOP_BASE + 0x058)
#define CONN_CLKGEN_TOP_CKGEN_COEX_0_ADDR \
	(CONN_CLKGEN_TOP_BASE + 0x060)
#define CONN_CLKGEN_TOP_CKGEN_COEX_0_SET_ADDR \
	(CONN_CLKGEN_TOP_BASE + 0x064)
#define CONN_CLKGEN_TOP_CKGEN_COEX_0_CLR_ADDR \
	(CONN_CLKGEN_TOP_BASE + 0x068)
#define CONN_CLKGEN_TOP_CKGEN_COEX_1_ADDR \
	(CONN_CLKGEN_TOP_BASE + 0x070)
#define CONN_CLKGEN_TOP_CKGEN_COEX_1_SET_ADDR \
	(CONN_CLKGEN_TOP_BASE + 0x074)
#define CONN_CLKGEN_TOP_CKGEN_COEX_1_CLR_ADDR \
	(CONN_CLKGEN_TOP_BASE + 0x078)
#define CONN_CLKGEN_TOP_CKGEN_RFSPI_PLL_REQ_ADDR \
	(CONN_CLKGEN_TOP_BASE + 0x080)
#define CONN_CLKGEN_TOP_CKGEN_RFSPI_PLL_REQ_SET_ADDR \
	(CONN_CLKGEN_TOP_BASE + 0x084)
#define CONN_CLKGEN_TOP_CKGEN_RFSPI_PLL_REQ_CLR_ADDR \
	(CONN_CLKGEN_TOP_BASE + 0x088)
#define CONN_CLKGEN_TOP_CKGEN_FREQ_METER_ADDR \
	(CONN_CLKGEN_TOP_BASE + 0x090)
#define CONN_CLKGEN_TOP_CKGEN_CLK_DETECT_ADDR \
	(CONN_CLKGEN_TOP_BASE + 0x094)
#define CONN_CLKGEN_TOP_CKGEN_SENSORHUB_1_ADDR \
	(CONN_CLKGEN_TOP_BASE + 0x0A0)
#define CONN_CLKGEN_TOP_CKGEN_SENSORHUB_1_SET_ADDR \
	(CONN_CLKGEN_TOP_BASE + 0x0A4)
#define CONN_CLKGEN_TOP_CKGEN_SENSORHUB_1_CLR_ADDR \
	(CONN_CLKGEN_TOP_BASE + 0x0A8)

#ifdef __cplusplus
}
#endif

#endif /* __CONN_CLKGEN_TOP_REGS_H__ */
