/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * Copyright (c) 2021 MediaTek Inc.
 */

#ifndef __EEF_TOP_REGS_H__
#define __EEF_TOP_REGS_H__

#include "hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif

#define EEF_TOP_BASE \
	0x70021000

#define EEF_TOP_EFUSE_CTRL_ADDR \
	(EEF_TOP_BASE + 0x008)
#define EEF_TOP_EFUSE_RDATA0_ADDR \
	(EEF_TOP_BASE + 0x030)
#define EEF_TOP_EFUSE_RDATA1_ADDR \
	(EEF_TOP_BASE + 0x034)


#define EEF_TOP_EFUSE_CTRL_ext_ee_sel_ADDR \
	EEF_TOP_EFUSE_CTRL_ADDR
#define EEF_TOP_EFUSE_CTRL_ext_ee_sel_MASK \
	0x80000000
#define EEF_TOP_EFUSE_CTRL_ext_ee_sel_SHFT \
	31
#define EEF_TOP_EFUSE_CTRL_EFSROM_KICK_ADDR \
	EEF_TOP_EFUSE_CTRL_ADDR
#define EEF_TOP_EFUSE_CTRL_EFSROM_KICK_MASK \
	0x40000000
#define EEF_TOP_EFUSE_CTRL_EFSROM_KICK_SHFT \
	30
#define EEF_TOP_EFUSE_CTRL_EFSROM_DOUT_VLD_ADDR \
	EEF_TOP_EFUSE_CTRL_ADDR
#define EEF_TOP_EFUSE_CTRL_EFSROM_DOUT_VLD_MASK \
	0x20000000
#define EEF_TOP_EFUSE_CTRL_EFSROM_DOUT_VLD_SHFT \
	29
#define EEF_TOP_EFUSE_CTRL_EFSROM_AIN_ADDR \
	EEF_TOP_EFUSE_CTRL_ADDR
#define EEF_TOP_EFUSE_CTRL_EFSROM_AIN_MASK \
	0x0FFF0000
#define EEF_TOP_EFUSE_CTRL_EFSROM_AIN_SHFT \
	16
#define EEF_TOP_EFUSE_CTRL_EFSROM_MODE_ADDR \
	EEF_TOP_EFUSE_CTRL_ADDR
#define EEF_TOP_EFUSE_CTRL_EFSROM_MODE_MASK \
	0x000000C0
#define EEF_TOP_EFUSE_CTRL_EFSROM_MODE_SHFT \
	6
#define EEF_TOP_EFUSE_CTRL_EFSROM_AOUT_ADDR \
	EEF_TOP_EFUSE_CTRL_ADDR
#define EEF_TOP_EFUSE_CTRL_EFSROM_AOUT_MASK \
	0x0000003F
#define EEF_TOP_EFUSE_CTRL_EFSROM_AOUT_SHFT \
	0

#define EEF_TOP_EFUSE_RDATA0_EFSROM_DATA0_ADDR \
	EEF_TOP_EFUSE_RDATA0_ADDR
#define EEF_TOP_EFUSE_RDATA0_EFSROM_DATA0_MASK \
	0xFFFFFFFF
#define EEF_TOP_EFUSE_RDATA0_EFSROM_DATA0_SHFT \
	0

#define EEF_TOP_EFUSE_RDATA1_EFSROM_DATA1_ADDR \
	EEF_TOP_EFUSE_RDATA1_ADDR
#define EEF_TOP_EFUSE_RDATA1_EFSROM_DATA1_MASK \
	0xFFFFFFFF
#define EEF_TOP_EFUSE_RDATA1_EFSROM_DATA1_SHFT \
	0

#ifdef __cplusplus
}
#endif

#endif
