/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * Copyright (c) 2021 MediaTek Inc.
 */

#ifndef __SSUSB_EPCTL_CSR_REGS_H__
#define __SSUSB_EPCTL_CSR_REGS_H__

#include "hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif

#define SSUSB_EPCTL_CSR_BASE	(0x74011800)

#define SSUSB_EPCTL_CSR_DEVICE_CONF_ADDR \
	(SSUSB_EPCTL_CSR_BASE + 0x000)
#define SSUSB_EPCTL_CSR_EP_RST_ADDR \
	(SSUSB_EPCTL_CSR_BASE + 0x004)
#define SSUSB_EPCTL_CSR_USB3_ERDY_TIMING_PARAMETER_ADDR \
	(SSUSB_EPCTL_CSR_BASE + 0x008)
#define SSUSB_EPCTL_CSR_USB3_EPCTRL_CAP_ADDR \
	(SSUSB_EPCTL_CSR_BASE + 0x00c)
#define SSUSB_EPCTL_CSR_USB2_ISOINEP_INCOMP_INTR_ADDR \
	(SSUSB_EPCTL_CSR_BASE + 0x010)
#define SSUSB_EPCTL_CSR_USB2_ISOOUTEP_INCOMP_ERR_ADDR \
	(SSUSB_EPCTL_CSR_BASE + 0x014)
#define SSUSB_EPCTL_CSR_ISO_UNDERRUN_INTR_ADDR \
	(SSUSB_EPCTL_CSR_BASE + 0x018)
#define SSUSB_EPCTL_CSR_ISO_OVERRUN_INTR_ADDR \
	(SSUSB_EPCTL_CSR_BASE + 0x01c)
#define SSUSB_EPCTL_CSR_USB2_RX_EP_DATAERR_INTR_ADDR \
	(SSUSB_EPCTL_CSR_BASE + 0x020)
#define SSUSB_EPCTL_CSR_USB2_EPCTRL_CAP_ADDR \
	(SSUSB_EPCTL_CSR_BASE + 0x024)
#define SSUSB_EPCTL_CSR_USB2_EPCTL_LPM_ADDR \
	(SSUSB_EPCTL_CSR_BASE + 0x028)
#define SSUSB_EPCTL_CSR_USB3_SW_ERDY_ADDR \
	(SSUSB_EPCTL_CSR_BASE + 0x030)
#define SSUSB_EPCTL_CSR_EP_FLOW_CTRL_ADDR \
	(SSUSB_EPCTL_CSR_BASE + 0x040)
#define SSUSB_EPCTL_CSR_USB3_EP_ACT_ADDR \
	(SSUSB_EPCTL_CSR_BASE + 0x044)
#define SSUSB_EPCTL_CSR_USB3_EP_PACKET_PENDING_ADDR \
	(SSUSB_EPCTL_CSR_BASE + 0x048)
#define SSUSB_EPCTL_CSR_DEV_LINK_INTR_ENABLE_ADDR \
	(SSUSB_EPCTL_CSR_BASE + 0x050)
#define SSUSB_EPCTL_CSR_DEV_LINK_INTR_ADDR \
	(SSUSB_EPCTL_CSR_BASE + 0x054)
#define SSUSB_EPCTL_CSR_USB2_EPCTL_LPM_FC_CHK_ADDR \
	(SSUSB_EPCTL_CSR_BASE + 0x060)
#define SSUSB_EPCTL_CSR_DEVICE_MONITOR_ADDR \
	(SSUSB_EPCTL_CSR_BASE + 0x064)
#define SSUSB_EPCTL_CSR_USB2_ISOINEP_INCOMP_INTR_MD_ADDR \
	(SSUSB_EPCTL_CSR_BASE + 0x070)
#define SSUSB_EPCTL_CSR_USB2_ISOOUTEP_INCOMP_ERR_MD_ADDR \
	(SSUSB_EPCTL_CSR_BASE + 0x074)
#define SSUSB_EPCTL_CSR_ISO_UNDERRUN_INTR_MD_ADDR \
	(SSUSB_EPCTL_CSR_BASE + 0x078)
#define SSUSB_EPCTL_CSR_ISO_OVERRUN_INTR_MD_ADDR \
	(SSUSB_EPCTL_CSR_BASE + 0x07c)
#define SSUSB_EPCTL_CSR_USB2_RX_EP_DATAERR_INTR_MD_ADDR \
	(SSUSB_EPCTL_CSR_BASE + 0x080)
#define SSUSB_EPCTL_CSR_EP_RST_OPT_ADDR \
	(SSUSB_EPCTL_CSR_BASE + 0x090)

#ifdef __cplusplus
}
#endif

#endif /* __SSUSB_EPCTL_CSR_REGS_H__ */
