/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * Copyright (c) 2021 MediaTek Inc.
 */

#ifndef __VLP_UDS_CTRL_REGS_H__
#define __VLP_UDS_CTRL_REGS_H__

#include "hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif

#define VLP_UDS_CTRL_BASE \
	0x70003000

#define VLP_UDS_CTRL_CBTOP_UDS_RSV_ADDR \
	(VLP_UDS_CTRL_BASE + 0x100)
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_ADDR \
	(VLP_UDS_CTRL_BASE + 0x300)
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_ADDR \
	(VLP_UDS_CTRL_BASE + 0x304)

#define VLP_UDS_CTRL_CBTOP_UDS_RSV_UDS_RSV_ADDR \
	VLP_UDS_CTRL_CBTOP_UDS_RSV_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_UDS_RSV_MASK \
	0xFFF80000
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_UDS_RSV_SHFT \
	19
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_BG32K_REQ_ZB_ADDR \
	VLP_UDS_CTRL_CBTOP_UDS_RSV_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_BG32K_REQ_ZB_MASK \
	0x00040000
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_BG32K_REQ_ZB_SHFT \
	18
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_BG32K_REQ_BT_ADDR \
	VLP_UDS_CTRL_CBTOP_UDS_RSV_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_BG32K_REQ_BT_MASK \
	0x00020000
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_BG32K_REQ_BT_SHFT \
	17
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_BG32K_REQ_WF_ADDR \
	VLP_UDS_CTRL_CBTOP_UDS_RSV_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_BG32K_REQ_WF_MASK \
	0x00010000
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_BG32K_REQ_WF_SHFT \
	16
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_CR_TOP_UDS_RSV_ADDR \
	VLP_UDS_CTRL_CBTOP_UDS_RSV_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_CR_TOP_UDS_RSV_MASK \
	0x0000C000
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_CR_TOP_UDS_RSV_SHFT \
	14
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_CR_TOP_UDS_RSV_ECO5_ADDR \
	VLP_UDS_CTRL_CBTOP_UDS_RSV_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_CR_TOP_UDS_RSV_ECO5_MASK \
	0x00002000
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_CR_TOP_UDS_RSV_ECO5_SHFT \
	13
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_CR_TOP_UDS_RSV_ECO4_ADDR \
	VLP_UDS_CTRL_CBTOP_UDS_RSV_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_CR_TOP_UDS_RSV_ECO4_MASK \
	0x00001000
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_CR_TOP_UDS_RSV_ECO4_SHFT \
	12
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_CR_TOP_UDS_RSV_ECO3_ADDR \
	VLP_UDS_CTRL_CBTOP_UDS_RSV_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_CR_TOP_UDS_RSV_ECO3_MASK \
	0x00000C00
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_CR_TOP_UDS_RSV_ECO3_SHFT \
	10
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_CR_TOP_UDS_RSV_ECO2_ADDR \
	VLP_UDS_CTRL_CBTOP_UDS_RSV_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_CR_TOP_UDS_RSV_ECO2_MASK \
	0x00000300
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_CR_TOP_UDS_RSV_ECO2_SHFT \
	8
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_CR_TOP_UDS_RSV_ECO1_ADDR \
	VLP_UDS_CTRL_CBTOP_UDS_RSV_ADDR
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_CR_TOP_UDS_RSV_ECO1_MASK \
	0x000000FF
#define VLP_UDS_CTRL_CBTOP_UDS_RSV_CR_TOP_UDS_RSV_ECO1_SHFT \
	0

#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_RG_cbtopaon_ulposc_sel_ADDR \
	VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_ADDR
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_RG_cbtopaon_ulposc_sel_MASK \
	0x80000000
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_RG_cbtopaon_ulposc_sel_SHFT \
	31
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_RG_enable_wakeup_sel_ADDR \
	VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_ADDR
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_RG_enable_wakeup_sel_MASK \
	0x40000000
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_RG_enable_wakeup_sel_SHFT \
	30
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_RG_OSC_DIV_ADDR \
	VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_ADDR
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_RG_OSC_DIV_MASK \
	0x3F000000
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_RG_OSC_DIV_SHFT \
	24
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_RG_OSC_BIAS_ADDR \
	VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_ADDR
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_RG_OSC_BIAS_MASK \
	0x00FF0000
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_RG_OSC_BIAS_SHFT \
	16
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_RG_OSC_CP_EN_ADDR \
	VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_ADDR
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_RG_OSC_CP_EN_MASK \
	0x00008000
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_RG_OSC_CP_EN_SHFT \
	15
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_RG_OSC_DIV2_EN_ADDR \
	VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_ADDR
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_RG_OSC_DIV2_EN_MASK \
	0x00004000
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_RG_OSC_DIV2_EN_SHFT \
	14
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_RG_OSC_MOD_ADDR \
	VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_ADDR
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_RG_OSC_MOD_MASK \
	0x00003000
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_RG_OSC_MOD_SHFT \
	12
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_RG_OSC_FBAND_ADDR \
	VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_ADDR
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_RG_OSC_FBAND_MASK \
	0x00000F00
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_RG_OSC_FBAND_SHFT \
	8
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_RG_OSC_IBAND_ADDR \
	VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_ADDR
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_RG_OSC_IBAND_MASK \
	0x0000007F
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL0_RG_OSC_IBAND_SHFT \
	0

#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_RG_OSC_CALI_sw_ADDR \
	VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_ADDR
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_RG_OSC_CALI_sw_MASK \
	0x80000000
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_RG_OSC_CALI_sw_SHFT \
	31
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_RG_div1_num_ADDR \
	VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_ADDR
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_RG_div1_num_MASK \
	0x1F000000
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_RG_div1_num_SHFT \
	24
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_RG_div2_num_ADDR \
	VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_ADDR
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_RG_div2_num_MASK \
	0x001F0000
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_RG_div2_num_SHFT \
	16
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_RG_k_target_value_ADDR \
	VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_ADDR
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_RG_k_target_value_MASK \
	0x0000FFFF
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_RG_k_target_value_SHFT \
	0

#ifdef __cplusplus
}
#endif

#endif
