/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * Copyright (c) 2021 MediaTek Inc.
 */

#ifndef __WF_TOP_CFG_ON_REGS_H__
#define __WF_TOP_CFG_ON_REGS_H__

#include "hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif

#define WF_TOP_CFG_ON_BASE \
	0x81021000

#define WF_TOP_CFG_ON_ROMCODE_INDEX_ADDR \
	(WF_TOP_CFG_ON_BASE + 0x604)
#define WF_TOP_CFG_ON_DEBUG_FLAG0_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB00)
#define WF_TOP_CFG_ON_DEBUG_FLAG1_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB04)
#define WF_TOP_CFG_ON_DEBUG_FLAG2_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB08)
#define WF_TOP_CFG_ON_DEBUG_FLAG3_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB0C)
#define WF_TOP_CFG_ON_DEBUG_FLAG4_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB10)
#define WF_TOP_CFG_ON_DEBUG_FLAG5_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB14)
#define WF_TOP_CFG_ON_DEBUG_FLAG6_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB18)
#define WF_TOP_CFG_ON_DEBUG_FLAG7_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB1C)
#define WF_TOP_CFG_ON_DEBUG_FLAG8_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB20)
#define WF_TOP_CFG_ON_DEBUG_FLAG9_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB24)
#define WF_TOP_CFG_ON_DEBUG_FLAG10_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB28)
#define WF_TOP_CFG_ON_DEBUG_FLAG11_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB2C)
#define WF_TOP_CFG_ON_DEBUG_FLAG12_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB30)
#define WF_TOP_CFG_ON_DEBUG_FLAG13_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB34)
#define WF_TOP_CFG_ON_DEBUG_FLAG14_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB38)
#define WF_TOP_CFG_ON_DEBUG_FLAG15_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB3C)
#define WF_TOP_CFG_ON_DEBUG_FLAG16_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB40)
#define WF_TOP_CFG_ON_DEBUG_FLAG17_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB50)
#define WF_TOP_CFG_ON_DEBUG_FLAG18_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB54)
#define WF_TOP_CFG_ON_DEBUG_FLAG19_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB58)
#define WF_TOP_CFG_ON_DEBUG_FLAG20_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB5C)
#define WF_TOP_CFG_ON_DEBUG_FLAG21_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB60)
#define WF_TOP_CFG_ON_DEBUG_FLAG22_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB64)
#define WF_TOP_CFG_ON_DEBUG_FLAG23_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB68)
#define WF_TOP_CFG_ON_DEBUG_FLAG24_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB6C)
#define WF_TOP_CFG_ON_DEBUG_FLAG25_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB70)
#define WF_TOP_CFG_ON_DEBUG_FLAG26_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB74)
#define WF_TOP_CFG_ON_DEBUG_FLAG27_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB78)
#define WF_TOP_CFG_ON_DEBUG_FLAG28_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB7C)
#define WF_TOP_CFG_ON_DEBUG_FLAG29_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB80)
#define WF_TOP_CFG_ON_DEBUG_FLAG30_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB84)
#define WF_TOP_CFG_ON_DEBUG_FLAG31_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB88)
#define WF_TOP_CFG_ON_DEBUG_FLAG32_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB8C)
#define WF_TOP_CFG_ON_DEBUG_FLAG33_ADDR \
	(WF_TOP_CFG_ON_BASE + 0xB90)


#define WF_TOP_CFG_ON_ROMCODE_INDEX_ROM_CODE_INDEX_ADDR \
	WF_TOP_CFG_ON_ROMCODE_INDEX_ADDR
#define WF_TOP_CFG_ON_ROMCODE_INDEX_ROM_CODE_INDEX_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_ROMCODE_INDEX_ROM_CODE_INDEX_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG0_DEBUG_FLAG0_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG0_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG0_DEBUG_FLAG0_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG0_DEBUG_FLAG0_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG1_DEBUG_FLAG1_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG1_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG1_DEBUG_FLAG1_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG1_DEBUG_FLAG1_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG2_DEBUG_FLAG2_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG2_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG2_DEBUG_FLAG2_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG2_DEBUG_FLAG2_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG3_DEBUG_FLAG3_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG3_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG3_DEBUG_FLAG3_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG3_DEBUG_FLAG3_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG4_DEBUG_FLAG4_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG4_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG4_DEBUG_FLAG4_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG4_DEBUG_FLAG4_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG5_DEBUG_FLAG5_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG5_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG5_DEBUG_FLAG5_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG5_DEBUG_FLAG5_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG6_DEBUG_FLAG6_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG6_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG6_DEBUG_FLAG6_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG6_DEBUG_FLAG6_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG7_DEBUG_FLAG7_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG7_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG7_DEBUG_FLAG7_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG7_DEBUG_FLAG7_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG8_DEBUG_FLAG8_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG8_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG8_DEBUG_FLAG8_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG8_DEBUG_FLAG8_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG9_DEBUG_FLAG9_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG9_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG9_DEBUG_FLAG9_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG9_DEBUG_FLAG9_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG10_DEBUG_FLAG10_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG10_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG10_DEBUG_FLAG10_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG10_DEBUG_FLAG10_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG11_DEBUG_FLAG11_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG11_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG11_DEBUG_FLAG11_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG11_DEBUG_FLAG11_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG12_DEBUG_FLAG12_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG12_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG12_DEBUG_FLAG12_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG12_DEBUG_FLAG12_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG13_DEBUG_FLAG13_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG13_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG13_DEBUG_FLAG13_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG13_DEBUG_FLAG13_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG14_DEBUG_FLAG14_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG14_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG14_DEBUG_FLAG14_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG14_DEBUG_FLAG14_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG15_DEBUG_FLAG15_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG15_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG15_DEBUG_FLAG15_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG15_DEBUG_FLAG15_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG16_DEBUG_FLAG16_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG16_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG16_DEBUG_FLAG16_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG16_DEBUG_FLAG16_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG17_DEBUG_FLAG17_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG17_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG17_DEBUG_FLAG17_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG17_DEBUG_FLAG17_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG18_DEBUG_FLAG18_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG18_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG18_DEBUG_FLAG18_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG18_DEBUG_FLAG18_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG19_DEBUG_FLAG19_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG19_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG19_DEBUG_FLAG19_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG19_DEBUG_FLAG19_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG20_DEBUG_FLAG20_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG20_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG20_DEBUG_FLAG20_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG20_DEBUG_FLAG20_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG21_DEBUG_FLAG21_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG21_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG21_DEBUG_FLAG21_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG21_DEBUG_FLAG21_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG22_DEBUG_FLAG22_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG22_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG22_DEBUG_FLAG22_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG22_DEBUG_FLAG22_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG23_DEBUG_FLAG23_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG23_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG23_DEBUG_FLAG23_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG23_DEBUG_FLAG23_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG24_DEBUG_FLAG24_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG24_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG24_DEBUG_FLAG24_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG24_DEBUG_FLAG24_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG25_DEBUG_FLAG25_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG25_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG25_DEBUG_FLAG25_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG25_DEBUG_FLAG25_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG26_DEBUG_FLAG26_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG26_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG26_DEBUG_FLAG26_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG26_DEBUG_FLAG26_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG27_DEBUG_FLAG27_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG27_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG27_DEBUG_FLAG27_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG27_DEBUG_FLAG27_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG28_DEBUG_FLAG28_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG28_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG28_DEBUG_FLAG28_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG28_DEBUG_FLAG28_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG29_DEBUG_FLAG29_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG29_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG29_DEBUG_FLAG29_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG29_DEBUG_FLAG29_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG30_DEBUG_FLAG30_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG30_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG30_DEBUG_FLAG30_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG30_DEBUG_FLAG30_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG31_DEBUG_FLAG31_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG31_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG31_DEBUG_FLAG31_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG31_DEBUG_FLAG31_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG32_DEBUG_FLAG32_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG32_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG32_DEBUG_FLAG32_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG32_DEBUG_FLAG32_SHFT \
	0

#define WF_TOP_CFG_ON_DEBUG_FLAG33_DEBUG_FLAG33_ADDR \
	WF_TOP_CFG_ON_DEBUG_FLAG33_ADDR
#define WF_TOP_CFG_ON_DEBUG_FLAG33_DEBUG_FLAG33_MASK \
	0xFFFFFFFF
#define WF_TOP_CFG_ON_DEBUG_FLAG33_DEBUG_FLAG33_SHFT \
	0

#ifdef __cplusplus
}
#endif

#endif
