/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * Copyright (c) 2021 MediaTek Inc.
 */

//[File]            : wf_wtblon_top.h
//[Revision time]   : Wed Jun 16 13:34:41 2021
//[Description]     : This file is auto generated by CODA
//[Copyright]       : Copyright (C) 2021 Mediatek Incorportion. All rights reserved.

#ifndef __WF_WTBLON_TOP_REGS_H__
#define __WF_WTBLON_TOP_REGS_H__

#include "hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif


//****************************************************************************
//
//                     WF_WTBLON_TOP CR Definitions
//
//****************************************************************************

#define WF_WTBLON_TOP_BASE                                     0x820d4000

#define WF_WTBLON_TOP_RVCDAR00_ADDR                            (WF_WTBLON_TOP_BASE + 0x0000) // 4000
#define WF_WTBLON_TOP_RVCDAR01_ADDR                            (WF_WTBLON_TOP_BASE + 0x0004) // 4004
#define WF_WTBLON_TOP_RVCDAR02_ADDR                            (WF_WTBLON_TOP_BASE + 0x0008) // 4008
#define WF_WTBLON_TOP_RVCDAR03_ADDR                            (WF_WTBLON_TOP_BASE + 0x000C) // 400C
#define WF_WTBLON_TOP_RVCDAR_EXT_00_ADDR                       (WF_WTBLON_TOP_BASE + 0x0080) // 4080
#define WF_WTBLON_TOP_PSCDAR00_ADDR                            (WF_WTBLON_TOP_BASE + 0x0100) // 4100
#define WF_WTBLON_TOP_PSCDAR01_ADDR                            (WF_WTBLON_TOP_BASE + 0x0104) // 4104
#define WF_WTBLON_TOP_PSCDAR02_ADDR                            (WF_WTBLON_TOP_BASE + 0x0108) // 4108
#define WF_WTBLON_TOP_PSCDAR03_ADDR                            (WF_WTBLON_TOP_BASE + 0x010C) // 410C
#define WF_WTBLON_TOP_PSCDAR_EXT_00_ADDR                       (WF_WTBLON_TOP_BASE + 0x0180) // 4180
#define WF_WTBLON_TOP_TCGSBR_ADDR                              (WF_WTBLON_TOP_BASE + 0x0300) // 4300
#define WF_WTBLON_TOP_TCGSBRe_ADDR                             (WF_WTBLON_TOP_BASE + 0x0308) // 4308
#define WF_WTBLON_TOP_ACGSBR_ADDR                              (WF_WTBLON_TOP_BASE + 0x0320) // 4320
#define WF_WTBLON_TOP_ACGSBRe_ADDR                             (WF_WTBLON_TOP_BASE + 0x0328) // 4328
#define WF_WTBLON_TOP_RCGSBR_ADDR                              (WF_WTBLON_TOP_BASE + 0x0340) // 4340
#define WF_WTBLON_TOP_RSCR_ADDR                                (WF_WTBLON_TOP_BASE + 0x0360) // 4360
#define WF_WTBLON_TOP_RDWLR0_ADDR                              (WF_WTBLON_TOP_BASE + 0x0364) // 4364
#define WF_WTBLON_TOP_RDWLR1_ADDR                              (WF_WTBLON_TOP_BASE + 0x0368) // 4368
#define WF_WTBLON_TOP_RDWLR2_ADDR                              (WF_WTBLON_TOP_BASE + 0x036C) // 436C
#define WF_WTBLON_TOP_WDUCR_ADDR                               (WF_WTBLON_TOP_BASE + 0x0370) // 4370
#define WF_WTBLON_TOP_WTBLOR_ADDR                              (WF_WTBLON_TOP_BASE + 0x0374) // 4374
#define WF_WTBLON_TOP_WIUCR_ADDR                               (WF_WTBLON_TOP_BASE + 0x0380) // 4380
#define WF_WTBLON_TOP_WMUDR_ADDR                               (WF_WTBLON_TOP_BASE + 0x0384) // 4384
#define WF_WTBLON_TOP_WMUMR_ADDR                               (WF_WTBLON_TOP_BASE + 0x0388) // 4388
#define WF_WTBLON_TOP_RICR0_ADDR                               (WF_WTBLON_TOP_BASE + 0x0390) // 4390
#define WF_WTBLON_TOP_RICR1_ADDR                               (WF_WTBLON_TOP_BASE + 0x0394) // 4394
#define WF_WTBLON_TOP_RIUCR0_ADDR                              (WF_WTBLON_TOP_BASE + 0x03A0) // 43A0
#define WF_WTBLON_TOP_RIUCR1_ADDR                              (WF_WTBLON_TOP_BASE + 0x03A4) // 43A4
#define WF_WTBLON_TOP_RIUCR2_ADDR                              (WF_WTBLON_TOP_BASE + 0x03A8) // 43A8
#define WF_WTBLON_TOP_RIUCR3_ADDR                              (WF_WTBLON_TOP_BASE + 0x03AC) // 43AC
#define WF_WTBLON_TOP_ITCR_ADDR                                (WF_WTBLON_TOP_BASE + 0x03B0) // 43B0
#define WF_WTBLON_TOP_ITDR0_ADDR                               (WF_WTBLON_TOP_BASE + 0x03B8) // 43B8
#define WF_WTBLON_TOP_ITDR1_ADDR                               (WF_WTBLON_TOP_BASE + 0x03BC) // 43BC
#define WF_WTBLON_TOP_MBIST_0_ADDR                             (WF_WTBLON_TOP_BASE + 0x03D0) // 43D0
#define WF_WTBLON_TOP_MBIST_3_ADDR                             (WF_WTBLON_TOP_BASE + 0x03D4) // 43D4
#define WF_WTBLON_TOP_MBIST_4_ADDR                             (WF_WTBLON_TOP_BASE + 0x03D8) // 43D8
#define WF_WTBLON_TOP_MBIST_5_ADDR                             (WF_WTBLON_TOP_BASE + 0x03DC) // 43DC
#define WF_WTBLON_TOP_MBIST_11_ADDR                            (WF_WTBLON_TOP_BASE + 0x03E0) // 43E0
#define WF_WTBLON_TOP_MBIST_12_ADDR                            (WF_WTBLON_TOP_BASE + 0x03E4) // 43E4
#define WF_WTBLON_TOP_MBIST_13_ADDR                            (WF_WTBLON_TOP_BASE + 0x03E8) // 43E8
#define WF_WTBLON_TOP_MBIST_14_ADDR                            (WF_WTBLON_TOP_BASE + 0x03EC) // 43EC
#define WF_WTBLON_TOP_DMY0_ADDR                                (WF_WTBLON_TOP_BASE + 0x03F0) // 43F0
#define WF_WTBLON_TOP_DMY1_ADDR                                (WF_WTBLON_TOP_BASE + 0x03F4) // 43F4
#define WF_WTBLON_TOP_DFR_ADDR                                 (WF_WTBLON_TOP_BASE + 0x03F8) // 43F8
#define WF_WTBLON_TOP_DBG_ADDR                                 (WF_WTBLON_TOP_BASE + 0x03FC) // 43FC




/* =====================================================================================

  ---RVCDAR00 (0x820d4000 + 0x0000)---

    RVCDAR00[7..0]               - (RW) Each bit is mapped to RV bit in bit 28@WTBL.
                                     SW uses this CR to read/write RV bit when Wi-Fi enters deep sleep mode.
                                     If wlan_idx > 32, RVCDAR+0x4*i store RV for wlan_idx 32*i ~32*(i+1)-1
                                     HW will update WTBL.RV automatically when this flag is updated.
    RVCDAR00_01[15..8]           - (RW) The same as RVCDAR00
    RVCDAR00_02[31..16]          - (RW) The same as RVCDAR00

 =====================================================================================*/
#define WF_WTBLON_TOP_RVCDAR00_RVCDAR00_02_ADDR                WF_WTBLON_TOP_RVCDAR00_ADDR
#define WF_WTBLON_TOP_RVCDAR00_RVCDAR00_02_MASK                0xFFFF0000                // RVCDAR00_02[31..16]
#define WF_WTBLON_TOP_RVCDAR00_RVCDAR00_02_SHFT                16
#define WF_WTBLON_TOP_RVCDAR00_RVCDAR00_01_ADDR                WF_WTBLON_TOP_RVCDAR00_ADDR
#define WF_WTBLON_TOP_RVCDAR00_RVCDAR00_01_MASK                0x0000FF00                // RVCDAR00_01[15..8]
#define WF_WTBLON_TOP_RVCDAR00_RVCDAR00_01_SHFT                8
#define WF_WTBLON_TOP_RVCDAR00_RVCDAR00_ADDR                   WF_WTBLON_TOP_RVCDAR00_ADDR
#define WF_WTBLON_TOP_RVCDAR00_RVCDAR00_MASK                   0x000000FF                // RVCDAR00[7..0]
#define WF_WTBLON_TOP_RVCDAR00_RVCDAR00_SHFT                   0

/* =====================================================================================

  ---RVCDAR01 (0x820d4000 + 0x0004)---

    RVCDAR01[31..0]              - (RW) The same as RVCDAR00

 =====================================================================================*/
#define WF_WTBLON_TOP_RVCDAR01_RVCDAR01_ADDR                   WF_WTBLON_TOP_RVCDAR01_ADDR
#define WF_WTBLON_TOP_RVCDAR01_RVCDAR01_MASK                   0xFFFFFFFF                // RVCDAR01[31..0]
#define WF_WTBLON_TOP_RVCDAR01_RVCDAR01_SHFT                   0

/* =====================================================================================

  ---RVCDAR02 (0x820d4000 + 0x0008)---

    RVCDAR02[31..0]              - (RW) The same as RVCDAR00

 =====================================================================================*/
#define WF_WTBLON_TOP_RVCDAR02_RVCDAR02_ADDR                   WF_WTBLON_TOP_RVCDAR02_ADDR
#define WF_WTBLON_TOP_RVCDAR02_RVCDAR02_MASK                   0xFFFFFFFF                // RVCDAR02[31..0]
#define WF_WTBLON_TOP_RVCDAR02_RVCDAR02_SHFT                   0

/* =====================================================================================

  ---RVCDAR03 (0x820d4000 + 0x000C)---

    RVCDAR03[31..0]              - (RW) The same as RVCDAR00

 =====================================================================================*/
#define WF_WTBLON_TOP_RVCDAR03_RVCDAR03_ADDR                   WF_WTBLON_TOP_RVCDAR03_ADDR
#define WF_WTBLON_TOP_RVCDAR03_RVCDAR03_MASK                   0xFFFFFFFF                // RVCDAR03[31..0]
#define WF_WTBLON_TOP_RVCDAR03_RVCDAR03_SHFT                   0

/* =====================================================================================

  ---RVCDAR_EXT_00 (0x820d4000 + 0x0080)---

    RVCDAR_EXT_00[3..0]          - (RW) The same as RVCDAR00
    RVCDAR_EXT_00_01[7..4]       - (RW) The same as RVCDAR00
    RESERVED8[31..8]             - (RO) Reserved bits

 =====================================================================================*/
#define WF_WTBLON_TOP_RVCDAR_EXT_00_RVCDAR_EXT_00_01_ADDR      WF_WTBLON_TOP_RVCDAR_EXT_00_ADDR
#define WF_WTBLON_TOP_RVCDAR_EXT_00_RVCDAR_EXT_00_01_MASK      0x000000F0                // RVCDAR_EXT_00_01[7..4]
#define WF_WTBLON_TOP_RVCDAR_EXT_00_RVCDAR_EXT_00_01_SHFT      4
#define WF_WTBLON_TOP_RVCDAR_EXT_00_RVCDAR_EXT_00_ADDR         WF_WTBLON_TOP_RVCDAR_EXT_00_ADDR
#define WF_WTBLON_TOP_RVCDAR_EXT_00_RVCDAR_EXT_00_MASK         0x0000000F                // RVCDAR_EXT_00[3..0]
#define WF_WTBLON_TOP_RVCDAR_EXT_00_RVCDAR_EXT_00_SHFT         0

/* =====================================================================================

  ---PSCDAR00 (0x820d4000 + 0x0100)---

    PSCDAR00[7..0]               - (RW) Each bit is mapped to PS INFO bit (calculate by WTBL).
                                     SW uses this CR to read/write PS INFO bit when Wi-Fi enters deep sleep mode.
                                     If wlan_idx > 32, PSCDAR+0x4*i store PS for wlan_idx 32*i ~32*(i+1)-1
    PSCDAR00_01[15..8]           - (RW) The same as PSCDAR00
    PSCDAR00_02[31..16]          - (RW) The same as PSCDAR00

 =====================================================================================*/
#define WF_WTBLON_TOP_PSCDAR00_PSCDAR00_02_ADDR                WF_WTBLON_TOP_PSCDAR00_ADDR
#define WF_WTBLON_TOP_PSCDAR00_PSCDAR00_02_MASK                0xFFFF0000                // PSCDAR00_02[31..16]
#define WF_WTBLON_TOP_PSCDAR00_PSCDAR00_02_SHFT                16
#define WF_WTBLON_TOP_PSCDAR00_PSCDAR00_01_ADDR                WF_WTBLON_TOP_PSCDAR00_ADDR
#define WF_WTBLON_TOP_PSCDAR00_PSCDAR00_01_MASK                0x0000FF00                // PSCDAR00_01[15..8]
#define WF_WTBLON_TOP_PSCDAR00_PSCDAR00_01_SHFT                8
#define WF_WTBLON_TOP_PSCDAR00_PSCDAR00_ADDR                   WF_WTBLON_TOP_PSCDAR00_ADDR
#define WF_WTBLON_TOP_PSCDAR00_PSCDAR00_MASK                   0x000000FF                // PSCDAR00[7..0]
#define WF_WTBLON_TOP_PSCDAR00_PSCDAR00_SHFT                   0

/* =====================================================================================

  ---PSCDAR01 (0x820d4000 + 0x0104)---

    PSCDAR01[31..0]              - (RW) The same as PSCDAR00

 =====================================================================================*/
#define WF_WTBLON_TOP_PSCDAR01_PSCDAR01_ADDR                   WF_WTBLON_TOP_PSCDAR01_ADDR
#define WF_WTBLON_TOP_PSCDAR01_PSCDAR01_MASK                   0xFFFFFFFF                // PSCDAR01[31..0]
#define WF_WTBLON_TOP_PSCDAR01_PSCDAR01_SHFT                   0

/* =====================================================================================

  ---PSCDAR02 (0x820d4000 + 0x0108)---

    PSCDAR02[31..0]              - (RW) The same as PSCDAR00

 =====================================================================================*/
#define WF_WTBLON_TOP_PSCDAR02_PSCDAR02_ADDR                   WF_WTBLON_TOP_PSCDAR02_ADDR
#define WF_WTBLON_TOP_PSCDAR02_PSCDAR02_MASK                   0xFFFFFFFF                // PSCDAR02[31..0]
#define WF_WTBLON_TOP_PSCDAR02_PSCDAR02_SHFT                   0

/* =====================================================================================

  ---PSCDAR03 (0x820d4000 + 0x010C)---

    PSCDAR03[31..0]              - (RW) The same as PSCDAR00

 =====================================================================================*/
#define WF_WTBLON_TOP_PSCDAR03_PSCDAR03_ADDR                   WF_WTBLON_TOP_PSCDAR03_ADDR
#define WF_WTBLON_TOP_PSCDAR03_PSCDAR03_MASK                   0xFFFFFFFF                // PSCDAR03[31..0]
#define WF_WTBLON_TOP_PSCDAR03_PSCDAR03_SHFT                   0

/* =====================================================================================

  ---PSCDAR_EXT_00 (0x820d4000 + 0x0180)---

    PSCDAR_EXT_00[3..0]          - (RW) The same as PSCDAR00
    PSCDAR_EXT_00_01[7..4]       - (RW) The same as PSCDAR00
    RESERVED8[31..8]             - (RO) Reserved bits

 =====================================================================================*/
#define WF_WTBLON_TOP_PSCDAR_EXT_00_PSCDAR_EXT_00_01_ADDR      WF_WTBLON_TOP_PSCDAR_EXT_00_ADDR
#define WF_WTBLON_TOP_PSCDAR_EXT_00_PSCDAR_EXT_00_01_MASK      0x000000F0                // PSCDAR_EXT_00_01[7..4]
#define WF_WTBLON_TOP_PSCDAR_EXT_00_PSCDAR_EXT_00_01_SHFT      4
#define WF_WTBLON_TOP_PSCDAR_EXT_00_PSCDAR_EXT_00_ADDR         WF_WTBLON_TOP_PSCDAR_EXT_00_ADDR
#define WF_WTBLON_TOP_PSCDAR_EXT_00_PSCDAR_EXT_00_MASK         0x0000000F                // PSCDAR_EXT_00[3..0]
#define WF_WTBLON_TOP_PSCDAR_EXT_00_PSCDAR_EXT_00_SHFT         0

/* =====================================================================================

  ---TCGSBR (0x820d4000 + 0x0300)---

    TX_CNT_STATUS_BITMAP_0_7[0]  - (RW) Group bitmap for TX count status
                                     Each bit is mapped to 8 entries in WLAN entry. For example, bit0 -> WLAN entry 0~7; bit1 -> WLAN entry 8~15, etc. SW should read to clear the bitmap when interrupt occurs.
                                     If the entries are absent (i.e. STA mode does not have WLAN entry 33~255), the mapping group bits will be invalid.
    TX_CNT_STATUS_BITMAP_8_15[1] - (RW) same as TX_CNT_STATUS_BITMAP_0_7
    TX_CNT_STATUS_BITMAP_16_31[3..2] - (RW) same as TX_CNT_STATUS_BITMAP_0_7
    TX_CNT_STATUS_BITMAP_32_63[7..4] - (RW) same as TX_CNT_STATUS_BITMAP_0_7
    TX_CNT_STATUS_BITMAP_64_127[15..8] - (RW) same as TX_CNT_STATUS_BITMAP_0_7
    RESERVED16[31..16]           - (RO) Reserved bits

 =====================================================================================*/
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_64_127_ADDR  WF_WTBLON_TOP_TCGSBR_ADDR
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_64_127_MASK  0x0000FF00                // TX_CNT_STATUS_BITMAP_64_127[15..8]
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_64_127_SHFT  8
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_32_63_ADDR   WF_WTBLON_TOP_TCGSBR_ADDR
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_32_63_MASK   0x000000F0                // TX_CNT_STATUS_BITMAP_32_63[7..4]
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_32_63_SHFT   4
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_16_31_ADDR   WF_WTBLON_TOP_TCGSBR_ADDR
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_16_31_MASK   0x0000000C                // TX_CNT_STATUS_BITMAP_16_31[3..2]
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_16_31_SHFT   2
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_8_15_ADDR    WF_WTBLON_TOP_TCGSBR_ADDR
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_8_15_MASK    0x00000002                // TX_CNT_STATUS_BITMAP_8_15[1]
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_8_15_SHFT    1
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_0_7_ADDR     WF_WTBLON_TOP_TCGSBR_ADDR
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_0_7_MASK     0x00000001                // TX_CNT_STATUS_BITMAP_0_7[0]
#define WF_WTBLON_TOP_TCGSBR_TX_CNT_STATUS_BITMAP_0_7_SHFT     0

/* =====================================================================================

  ---TCGSBRe (0x820d4000 + 0x0308)---

    TX_CNT_STATUS_BITMAP_e0_7[0] - (RW) same as TX_CNT_STATUS_BITMAP_0_7
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WF_WTBLON_TOP_TCGSBRe_TX_CNT_STATUS_BITMAP_e0_7_ADDR   WF_WTBLON_TOP_TCGSBRe_ADDR
#define WF_WTBLON_TOP_TCGSBRe_TX_CNT_STATUS_BITMAP_e0_7_MASK   0x00000001                // TX_CNT_STATUS_BITMAP_e0_7[0]
#define WF_WTBLON_TOP_TCGSBRe_TX_CNT_STATUS_BITMAP_e0_7_SHFT   0

/* =====================================================================================

  ---ACGSBR (0x820d4000 + 0x0320)---

    ADM_CNT_STATUS_BITMAP_0_7[0] - (RW) Group bitmap for ADM count status
                                     Each bit is mapped to 8 entries in WLAN entry. For example, bit0 -> WLAN entry 0~7; bit1 -> WLAN entry 8~15, etc. SW should read to clear the bitmap when interrupt occurs.
                                     If the entries are absent (i.e. STA mode does not have WLAN entry 33~255), the mapping group bits will be invalid.
    ADM_CNT_STATUS_BITMAP_8_15[1] - (RW) same as ADM_CNT_STATUS_BITMAP_0_7
    ADM_CNT_STATUS_BITMAP_16_31[3..2] - (RW) same as ADM_CNT_STATUS_BITMAP_0_7
    ADM_CNT_STATUS_BITMAP_32_63[7..4] - (RW) same as ADM_CNT_STATUS_BITMAP_0_7
    ADM_CNT_STATUS_BITMAP_64_127[15..8] - (RW) same as ADM_CNT_STATUS_BITMAP_0_7
    RESERVED16[31..16]           - (RO) Reserved bits

 =====================================================================================*/
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_64_127_ADDR WF_WTBLON_TOP_ACGSBR_ADDR
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_64_127_MASK 0x0000FF00                // ADM_CNT_STATUS_BITMAP_64_127[15..8]
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_64_127_SHFT 8
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_32_63_ADDR  WF_WTBLON_TOP_ACGSBR_ADDR
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_32_63_MASK  0x000000F0                // ADM_CNT_STATUS_BITMAP_32_63[7..4]
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_32_63_SHFT  4
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_16_31_ADDR  WF_WTBLON_TOP_ACGSBR_ADDR
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_16_31_MASK  0x0000000C                // ADM_CNT_STATUS_BITMAP_16_31[3..2]
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_16_31_SHFT  2
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_8_15_ADDR   WF_WTBLON_TOP_ACGSBR_ADDR
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_8_15_MASK   0x00000002                // ADM_CNT_STATUS_BITMAP_8_15[1]
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_8_15_SHFT   1
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_0_7_ADDR    WF_WTBLON_TOP_ACGSBR_ADDR
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_0_7_MASK    0x00000001                // ADM_CNT_STATUS_BITMAP_0_7[0]
#define WF_WTBLON_TOP_ACGSBR_ADM_CNT_STATUS_BITMAP_0_7_SHFT    0

/* =====================================================================================

  ---ACGSBRe (0x820d4000 + 0x0328)---

    ADM_CNT_STATUS_BITMAP_e0_7[0] - (RW) same as ADM_CNT_STATUS_BITMAP_0_7
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WF_WTBLON_TOP_ACGSBRe_ADM_CNT_STATUS_BITMAP_e0_7_ADDR  WF_WTBLON_TOP_ACGSBRe_ADDR
#define WF_WTBLON_TOP_ACGSBRe_ADM_CNT_STATUS_BITMAP_e0_7_MASK  0x00000001                // ADM_CNT_STATUS_BITMAP_e0_7[0]
#define WF_WTBLON_TOP_ACGSBRe_ADM_CNT_STATUS_BITMAP_e0_7_SHFT  0

/* =====================================================================================

  ---RCGSBR (0x820d4000 + 0x0340)---

    RATE_CHANGE_STATUS_BITMAP[31..0] - (RW) Group bitmap for rate change status
                                     Each bit is mapped to 8 entries in WLAN entry.
                                     For example,
                                     a = WTBL_NO/8.
                                     bit 0->WLAN entry a*n,
                                     bit 1->WLAN entry a*n+1,
                                     ...
                                     bit m->WLAN entry a*n+m (m <= a).
                                     SW should read to clear the bitmap when interrupt occurs.
                                     If the entries are absent (i.e. STA mode does not have WLAN entry 33~255), the mapping group bits will be invalid.

 =====================================================================================*/
#define WF_WTBLON_TOP_RCGSBR_RATE_CHANGE_STATUS_BITMAP_ADDR    WF_WTBLON_TOP_RCGSBR_ADDR
#define WF_WTBLON_TOP_RCGSBR_RATE_CHANGE_STATUS_BITMAP_MASK    0xFFFFFFFF                // RATE_CHANGE_STATUS_BITMAP[31..0]
#define WF_WTBLON_TOP_RCGSBR_RATE_CHANGE_STATUS_BITMAP_SHFT    0

/* =====================================================================================

  ---RSCR (0x820d4000 + 0x0360)---

    WTBL_SU_SEARCH[0]            - (RW) WTBL search mode
    WTBL_PRECISE_MATCH[1]        - (RW) Precise match when checking peer address
                                     WTBL do NOT ignore individual/group bit in address check when comparing the peer address with A2
    RESERVED2[2]                 - (RO) Reserved bits
    WTBL_TA_SEARCH_CHECK_BAND[3] - (RW) WTBL search should check band id
                                     for TA search only
    WTBL_RA_SEARCH_CHECK_BAND[4] - (RW) WTBL search should check band id
                                     for RA search only
    WTBL_ENABLE_RA_SEARCH[5]     - (RW) RA search mode
    RESERVED6[30..6]             - (RO) Reserved bits
    WTBL_ACCESS_CONCURRENT[31]   - (RW) WTBL allows non-ID table access & ID table access in the same time to reduce the processing time

 =====================================================================================*/
#define WF_WTBLON_TOP_RSCR_WTBL_ACCESS_CONCURRENT_ADDR         WF_WTBLON_TOP_RSCR_ADDR
#define WF_WTBLON_TOP_RSCR_WTBL_ACCESS_CONCURRENT_MASK         0x80000000                // WTBL_ACCESS_CONCURRENT[31]
#define WF_WTBLON_TOP_RSCR_WTBL_ACCESS_CONCURRENT_SHFT         31
#define WF_WTBLON_TOP_RSCR_WTBL_ENABLE_RA_SEARCH_ADDR          WF_WTBLON_TOP_RSCR_ADDR
#define WF_WTBLON_TOP_RSCR_WTBL_ENABLE_RA_SEARCH_MASK          0x00000020                // WTBL_ENABLE_RA_SEARCH[5]
#define WF_WTBLON_TOP_RSCR_WTBL_ENABLE_RA_SEARCH_SHFT          5
#define WF_WTBLON_TOP_RSCR_WTBL_RA_SEARCH_CHECK_BAND_ADDR      WF_WTBLON_TOP_RSCR_ADDR
#define WF_WTBLON_TOP_RSCR_WTBL_RA_SEARCH_CHECK_BAND_MASK      0x00000010                // WTBL_RA_SEARCH_CHECK_BAND[4]
#define WF_WTBLON_TOP_RSCR_WTBL_RA_SEARCH_CHECK_BAND_SHFT      4
#define WF_WTBLON_TOP_RSCR_WTBL_TA_SEARCH_CHECK_BAND_ADDR      WF_WTBLON_TOP_RSCR_ADDR
#define WF_WTBLON_TOP_RSCR_WTBL_TA_SEARCH_CHECK_BAND_MASK      0x00000008                // WTBL_TA_SEARCH_CHECK_BAND[3]
#define WF_WTBLON_TOP_RSCR_WTBL_TA_SEARCH_CHECK_BAND_SHFT      3
#define WF_WTBLON_TOP_RSCR_WTBL_PRECISE_MATCH_ADDR             WF_WTBLON_TOP_RSCR_ADDR
#define WF_WTBLON_TOP_RSCR_WTBL_PRECISE_MATCH_MASK             0x00000002                // WTBL_PRECISE_MATCH[1]
#define WF_WTBLON_TOP_RSCR_WTBL_PRECISE_MATCH_SHFT             1
#define WF_WTBLON_TOP_RSCR_WTBL_SU_SEARCH_ADDR                 WF_WTBLON_TOP_RSCR_ADDR
#define WF_WTBLON_TOP_RSCR_WTBL_SU_SEARCH_MASK                 0x00000001                // WTBL_SU_SEARCH[0]
#define WF_WTBLON_TOP_RSCR_WTBL_SU_SEARCH_SHFT                 0

/* =====================================================================================

  ---RDWLR0 (0x820d4000 + 0x0364)---

    RXD_DUP_WHITE_LIST0[7..0]    - (RW) White list for RXD duplication
                                     |07|06|05|04|03|02|01|00|
                                     |AC      |SUBTYPE        | TYPE |
                                     AC field is valid when TYPE = DATA and SUBTYPE = QOS*
    RXD_DUP_WHITE_LIST1[15..8]   - (RW) The same as RXD_DUP_WHITE_LIST0
    RXD_DUP_WHITE_LIST2[23..16]  - (RW) The same as RXD_DUP_WHITE_LIST0
    RXD_DUP_WHITE_LIST3[31..24]  - (RW) The same as RXD_DUP_WHITE_LIST0

 =====================================================================================*/
#define WF_WTBLON_TOP_RDWLR0_RXD_DUP_WHITE_LIST3_ADDR          WF_WTBLON_TOP_RDWLR0_ADDR
#define WF_WTBLON_TOP_RDWLR0_RXD_DUP_WHITE_LIST3_MASK          0xFF000000                // RXD_DUP_WHITE_LIST3[31..24]
#define WF_WTBLON_TOP_RDWLR0_RXD_DUP_WHITE_LIST3_SHFT          24
#define WF_WTBLON_TOP_RDWLR0_RXD_DUP_WHITE_LIST2_ADDR          WF_WTBLON_TOP_RDWLR0_ADDR
#define WF_WTBLON_TOP_RDWLR0_RXD_DUP_WHITE_LIST2_MASK          0x00FF0000                // RXD_DUP_WHITE_LIST2[23..16]
#define WF_WTBLON_TOP_RDWLR0_RXD_DUP_WHITE_LIST2_SHFT          16
#define WF_WTBLON_TOP_RDWLR0_RXD_DUP_WHITE_LIST1_ADDR          WF_WTBLON_TOP_RDWLR0_ADDR
#define WF_WTBLON_TOP_RDWLR0_RXD_DUP_WHITE_LIST1_MASK          0x0000FF00                // RXD_DUP_WHITE_LIST1[15..8]
#define WF_WTBLON_TOP_RDWLR0_RXD_DUP_WHITE_LIST1_SHFT          8
#define WF_WTBLON_TOP_RDWLR0_RXD_DUP_WHITE_LIST0_ADDR          WF_WTBLON_TOP_RDWLR0_ADDR
#define WF_WTBLON_TOP_RDWLR0_RXD_DUP_WHITE_LIST0_MASK          0x000000FF                // RXD_DUP_WHITE_LIST0[7..0]
#define WF_WTBLON_TOP_RDWLR0_RXD_DUP_WHITE_LIST0_SHFT          0

/* =====================================================================================

  ---RDWLR1 (0x820d4000 + 0x0368)---

    RXD_DUP_WHITE_LIST4[7..0]    - (RW) The same as RXD_DUP_WHITE_LIST0
    RXD_DUP_WHITE_LIST5[15..8]   - (RW) The same as RXD_DUP_WHITE_LIST0
    RXD_DUP_WHITE_LIST6[23..16]  - (RW) The same as RXD_DUP_WHITE_LIST0
    RXD_DUP_WHITE_LIST7[31..24]  - (RW) The same as RXD_DUP_WHITE_LIST0

 =====================================================================================*/
#define WF_WTBLON_TOP_RDWLR1_RXD_DUP_WHITE_LIST7_ADDR          WF_WTBLON_TOP_RDWLR1_ADDR
#define WF_WTBLON_TOP_RDWLR1_RXD_DUP_WHITE_LIST7_MASK          0xFF000000                // RXD_DUP_WHITE_LIST7[31..24]
#define WF_WTBLON_TOP_RDWLR1_RXD_DUP_WHITE_LIST7_SHFT          24
#define WF_WTBLON_TOP_RDWLR1_RXD_DUP_WHITE_LIST6_ADDR          WF_WTBLON_TOP_RDWLR1_ADDR
#define WF_WTBLON_TOP_RDWLR1_RXD_DUP_WHITE_LIST6_MASK          0x00FF0000                // RXD_DUP_WHITE_LIST6[23..16]
#define WF_WTBLON_TOP_RDWLR1_RXD_DUP_WHITE_LIST6_SHFT          16
#define WF_WTBLON_TOP_RDWLR1_RXD_DUP_WHITE_LIST5_ADDR          WF_WTBLON_TOP_RDWLR1_ADDR
#define WF_WTBLON_TOP_RDWLR1_RXD_DUP_WHITE_LIST5_MASK          0x0000FF00                // RXD_DUP_WHITE_LIST5[15..8]
#define WF_WTBLON_TOP_RDWLR1_RXD_DUP_WHITE_LIST5_SHFT          8
#define WF_WTBLON_TOP_RDWLR1_RXD_DUP_WHITE_LIST4_ADDR          WF_WTBLON_TOP_RDWLR1_ADDR
#define WF_WTBLON_TOP_RDWLR1_RXD_DUP_WHITE_LIST4_MASK          0x000000FF                // RXD_DUP_WHITE_LIST4[7..0]
#define WF_WTBLON_TOP_RDWLR1_RXD_DUP_WHITE_LIST4_SHFT          0

/* =====================================================================================

  ---RDWLR2 (0x820d4000 + 0x036C)---

    RXD_DUP_WHITE_LIST8[7..0]    - (RW) The same as RXD_DUP_WHITE_LIST0
    RXD_DUP_WHITE_LIST9[15..8]   - (RW) The same as RXD_DUP_WHITE_LIST0
    RXD_DUP_WHITE_LIST10[23..16] - (RW) The same as RXD_DUP_WHITE_LIST0
    RXD_DUP_WHITE_LIST11[31..24] - (RW) The same as RXD_DUP_WHITE_LIST0

 =====================================================================================*/
#define WF_WTBLON_TOP_RDWLR2_RXD_DUP_WHITE_LIST11_ADDR         WF_WTBLON_TOP_RDWLR2_ADDR
#define WF_WTBLON_TOP_RDWLR2_RXD_DUP_WHITE_LIST11_MASK         0xFF000000                // RXD_DUP_WHITE_LIST11[31..24]
#define WF_WTBLON_TOP_RDWLR2_RXD_DUP_WHITE_LIST11_SHFT         24
#define WF_WTBLON_TOP_RDWLR2_RXD_DUP_WHITE_LIST10_ADDR         WF_WTBLON_TOP_RDWLR2_ADDR
#define WF_WTBLON_TOP_RDWLR2_RXD_DUP_WHITE_LIST10_MASK         0x00FF0000                // RXD_DUP_WHITE_LIST10[23..16]
#define WF_WTBLON_TOP_RDWLR2_RXD_DUP_WHITE_LIST10_SHFT         16
#define WF_WTBLON_TOP_RDWLR2_RXD_DUP_WHITE_LIST9_ADDR          WF_WTBLON_TOP_RDWLR2_ADDR
#define WF_WTBLON_TOP_RDWLR2_RXD_DUP_WHITE_LIST9_MASK          0x0000FF00                // RXD_DUP_WHITE_LIST9[15..8]
#define WF_WTBLON_TOP_RDWLR2_RXD_DUP_WHITE_LIST9_SHFT          8
#define WF_WTBLON_TOP_RDWLR2_RXD_DUP_WHITE_LIST8_ADDR          WF_WTBLON_TOP_RDWLR2_ADDR
#define WF_WTBLON_TOP_RDWLR2_RXD_DUP_WHITE_LIST8_MASK          0x000000FF                // RXD_DUP_WHITE_LIST8[7..0]
#define WF_WTBLON_TOP_RDWLR2_RXD_DUP_WHITE_LIST8_SHFT          0

/* =====================================================================================

  ---WDUCR (0x820d4000 + 0x0370)---

    GROUP[4..0]                  - (RW) The selected group of wtbl
                                     128 entries for each group
    RESERVED5[31..5]             - (RO) Reserved bits

 =====================================================================================*/
#define WF_WTBLON_TOP_WDUCR_GROUP_ADDR                         WF_WTBLON_TOP_WDUCR_ADDR
#define WF_WTBLON_TOP_WDUCR_GROUP_MASK                         0x0000001F                // GROUP[4..0]
#define WF_WTBLON_TOP_WDUCR_GROUP_SHFT                         0

/* =====================================================================================

  ---WTBLOR (0x820d4000 + 0x0374)---

    LOCK_WLAN_IDX[11..0]         - (RW) Target for locking
    LOCK_RATE[12]                - (RW) Lock rate update
                                     Read this flag to know if it is locked or not.
    RESERVED13[19..13]           - (RO) Reserved bits
    LOCK_ADM_CNT[20]             - (RW) Lock admission control counter update
                                     Read this flag to know if it is locked or not.
    RESERVED21[23..21]           - (RO) Reserved bits
    LOCK_TX_CNT[24]              - (RW) Lock TX/RTS/retry counter update
                                     Read this flag to know if it is locked or not.
    RESERVED25[27..25]           - (RO) Reserved bits
    LOCK_RX_STAT_CNT[28]         - (RW) Lock RX counter update
                                     Read this flag to know if it is locked or not.
    RESERVED29[31..29]           - (RO) Reserved bits

 =====================================================================================*/
#define WF_WTBLON_TOP_WTBLOR_LOCK_RX_STAT_CNT_ADDR             WF_WTBLON_TOP_WTBLOR_ADDR
#define WF_WTBLON_TOP_WTBLOR_LOCK_RX_STAT_CNT_MASK             0x10000000                // LOCK_RX_STAT_CNT[28]
#define WF_WTBLON_TOP_WTBLOR_LOCK_RX_STAT_CNT_SHFT             28
#define WF_WTBLON_TOP_WTBLOR_LOCK_TX_CNT_ADDR                  WF_WTBLON_TOP_WTBLOR_ADDR
#define WF_WTBLON_TOP_WTBLOR_LOCK_TX_CNT_MASK                  0x01000000                // LOCK_TX_CNT[24]
#define WF_WTBLON_TOP_WTBLOR_LOCK_TX_CNT_SHFT                  24
#define WF_WTBLON_TOP_WTBLOR_LOCK_ADM_CNT_ADDR                 WF_WTBLON_TOP_WTBLOR_ADDR
#define WF_WTBLON_TOP_WTBLOR_LOCK_ADM_CNT_MASK                 0x00100000                // LOCK_ADM_CNT[20]
#define WF_WTBLON_TOP_WTBLOR_LOCK_ADM_CNT_SHFT                 20
#define WF_WTBLON_TOP_WTBLOR_LOCK_RATE_ADDR                    WF_WTBLON_TOP_WTBLOR_ADDR
#define WF_WTBLON_TOP_WTBLOR_LOCK_RATE_MASK                    0x00001000                // LOCK_RATE[12]
#define WF_WTBLON_TOP_WTBLOR_LOCK_RATE_SHFT                    12
#define WF_WTBLON_TOP_WTBLOR_LOCK_WLAN_IDX_ADDR                WF_WTBLON_TOP_WTBLOR_ADDR
#define WF_WTBLON_TOP_WTBLOR_LOCK_WLAN_IDX_MASK                0x00000FFF                // LOCK_WLAN_IDX[11..0]
#define WF_WTBLON_TOP_WTBLOR_LOCK_WLAN_IDX_SHFT                0

/* =====================================================================================

  ---WIUCR (0x820d4000 + 0x0380)---

    WLAN_IDX[11..0]              - (RW) Target index for indirect update
    RESERVED12[12]               - (RO) Reserved bits
    PEERINFO_UPDATE[13]          - (W1) Updates Peer information according to the value of RICRn (n=0~1)
    ADM_CNT_CLEAR[14]            - (W1) Clear ADM counter to 0
    RATE_UPDATE[15]              - (W1) Updates rate information according to the value of RIUCRn (n=0~3) and clears rate_idx, mpdu_cnt
    TX_RATE_CNT_CLEAR[16]        - (W1) Clear TX rate/BW CNTs and CHK_PER to 0
    RX_CNT_CLEAR[17]             - (W1) Sets RCPI, RSSI, SNR to initial value.
    RTS_CNT_CLEAR[18]            - (W1) Clear RTS counter & RTS_FAIL_CNT_AC* to 0
    RETRY_CNT_CLEAR[19]          - (W1) Clear retry counter to 0
    MASK_UPDATE[20]              - (W1) Mask Update
                                     WTBL loads target wlan_idx & dw and update the target field by WMUDR & WMUMR
    RESERVED21[23..21]           - (RO) Reserved bits
    DW[29..24]                   - (RW) Target double word
    RESERVED30[30]               - (RO) Reserved bits
    IU_BUSY[31]                  - (RO) Indirect update status
                                     HW will set up this bit when it is updating WTBL.

 =====================================================================================*/
#define WF_WTBLON_TOP_WIUCR_IU_BUSY_ADDR                       WF_WTBLON_TOP_WIUCR_ADDR
#define WF_WTBLON_TOP_WIUCR_IU_BUSY_MASK                       0x80000000                // IU_BUSY[31]
#define WF_WTBLON_TOP_WIUCR_IU_BUSY_SHFT                       31
#define WF_WTBLON_TOP_WIUCR_DW_ADDR                            WF_WTBLON_TOP_WIUCR_ADDR
#define WF_WTBLON_TOP_WIUCR_DW_MASK                            0x3F000000                // DW[29..24]
#define WF_WTBLON_TOP_WIUCR_DW_SHFT                            24
#define WF_WTBLON_TOP_WIUCR_MASK_UPDATE_ADDR                   WF_WTBLON_TOP_WIUCR_ADDR
#define WF_WTBLON_TOP_WIUCR_MASK_UPDATE_MASK                   0x00100000                // MASK_UPDATE[20]
#define WF_WTBLON_TOP_WIUCR_MASK_UPDATE_SHFT                   20
#define WF_WTBLON_TOP_WIUCR_RETRY_CNT_CLEAR_ADDR               WF_WTBLON_TOP_WIUCR_ADDR
#define WF_WTBLON_TOP_WIUCR_RETRY_CNT_CLEAR_MASK               0x00080000                // RETRY_CNT_CLEAR[19]
#define WF_WTBLON_TOP_WIUCR_RETRY_CNT_CLEAR_SHFT               19
#define WF_WTBLON_TOP_WIUCR_RTS_CNT_CLEAR_ADDR                 WF_WTBLON_TOP_WIUCR_ADDR
#define WF_WTBLON_TOP_WIUCR_RTS_CNT_CLEAR_MASK                 0x00040000                // RTS_CNT_CLEAR[18]
#define WF_WTBLON_TOP_WIUCR_RTS_CNT_CLEAR_SHFT                 18
#define WF_WTBLON_TOP_WIUCR_RX_CNT_CLEAR_ADDR                  WF_WTBLON_TOP_WIUCR_ADDR
#define WF_WTBLON_TOP_WIUCR_RX_CNT_CLEAR_MASK                  0x00020000                // RX_CNT_CLEAR[17]
#define WF_WTBLON_TOP_WIUCR_RX_CNT_CLEAR_SHFT                  17
#define WF_WTBLON_TOP_WIUCR_TX_RATE_CNT_CLEAR_ADDR             WF_WTBLON_TOP_WIUCR_ADDR
#define WF_WTBLON_TOP_WIUCR_TX_RATE_CNT_CLEAR_MASK             0x00010000                // TX_RATE_CNT_CLEAR[16]
#define WF_WTBLON_TOP_WIUCR_TX_RATE_CNT_CLEAR_SHFT             16
#define WF_WTBLON_TOP_WIUCR_RATE_UPDATE_ADDR                   WF_WTBLON_TOP_WIUCR_ADDR
#define WF_WTBLON_TOP_WIUCR_RATE_UPDATE_MASK                   0x00008000                // RATE_UPDATE[15]
#define WF_WTBLON_TOP_WIUCR_RATE_UPDATE_SHFT                   15
#define WF_WTBLON_TOP_WIUCR_ADM_CNT_CLEAR_ADDR                 WF_WTBLON_TOP_WIUCR_ADDR
#define WF_WTBLON_TOP_WIUCR_ADM_CNT_CLEAR_MASK                 0x00004000                // ADM_CNT_CLEAR[14]
#define WF_WTBLON_TOP_WIUCR_ADM_CNT_CLEAR_SHFT                 14
#define WF_WTBLON_TOP_WIUCR_PEERINFO_UPDATE_ADDR               WF_WTBLON_TOP_WIUCR_ADDR
#define WF_WTBLON_TOP_WIUCR_PEERINFO_UPDATE_MASK               0x00002000                // PEERINFO_UPDATE[13]
#define WF_WTBLON_TOP_WIUCR_PEERINFO_UPDATE_SHFT               13
#define WF_WTBLON_TOP_WIUCR_WLAN_IDX_ADDR                      WF_WTBLON_TOP_WIUCR_ADDR
#define WF_WTBLON_TOP_WIUCR_WLAN_IDX_MASK                      0x00000FFF                // WLAN_IDX[11..0]
#define WF_WTBLON_TOP_WIUCR_WLAN_IDX_SHFT                      0

/* =====================================================================================

  ---WMUDR (0x820d4000 + 0x0384)---

    UPDATE_DATA[31..0]           - (RW) Data to update wlan entry

 =====================================================================================*/
#define WF_WTBLON_TOP_WMUDR_UPDATE_DATA_ADDR                   WF_WTBLON_TOP_WMUDR_ADDR
#define WF_WTBLON_TOP_WMUDR_UPDATE_DATA_MASK                   0xFFFFFFFF                // UPDATE_DATA[31..0]
#define WF_WTBLON_TOP_WMUDR_UPDATE_DATA_SHFT                   0

/* =====================================================================================

  ---WMUMR (0x820d4000 + 0x0388)---

    UPDATE_MASK[31..0]           - (RW) Mask of data to update wlan entry

 =====================================================================================*/
#define WF_WTBLON_TOP_WMUMR_UPDATE_MASK_ADDR                   WF_WTBLON_TOP_WMUMR_ADDR
#define WF_WTBLON_TOP_WMUMR_UPDATE_MASK_MASK                   0xFFFFFFFF                // UPDATE_MASK[31..0]
#define WF_WTBLON_TOP_WMUMR_UPDATE_MASK_SHFT                   0

/* =====================================================================================

  ---RICR0 (0x820d4000 + 0x0390)---

    DW0_WTBL[31..0]              - (RW) The value of DW in WTBL for updating
                                     the data are updated to WTBL when WIUCR.PEERINFO_UPDATE is asserted.

 =====================================================================================*/
#define WF_WTBLON_TOP_RICR0_DW0_WTBL_ADDR                      WF_WTBLON_TOP_RICR0_ADDR
#define WF_WTBLON_TOP_RICR0_DW0_WTBL_MASK                      0xFFFFFFFF                // DW0_WTBL[31..0]
#define WF_WTBLON_TOP_RICR0_DW0_WTBL_SHFT                      0

/* =====================================================================================

  ---RICR1 (0x820d4000 + 0x0394)---

    DW1_WTBL[31..0]              - (RW) The value of DW in WTBL for updating
                                     the data are updated to WTBL when WIUCR.PEERINFO_UPDATE is asserted.

 =====================================================================================*/
#define WF_WTBLON_TOP_RICR1_DW1_WTBL_ADDR                      WF_WTBLON_TOP_RICR1_ADDR
#define WF_WTBLON_TOP_RICR1_DW1_WTBL_MASK                      0xFFFFFFFF                // DW1_WTBL[31..0]
#define WF_WTBLON_TOP_RICR1_DW1_WTBL_SHFT                      0

/* =====================================================================================

  ---RIUCR0 (0x820d4000 + 0x03A0)---

    DW10_WTBL[31..0]             - (RW) The value of DW in WTBL for updating
                                     the data are updated to WTBL when WIUCR.RATE_UPDATE is asserted.

 =====================================================================================*/
#define WF_WTBLON_TOP_RIUCR0_DW10_WTBL_ADDR                    WF_WTBLON_TOP_RIUCR0_ADDR
#define WF_WTBLON_TOP_RIUCR0_DW10_WTBL_MASK                    0xFFFFFFFF                // DW10_WTBL[31..0]
#define WF_WTBLON_TOP_RIUCR0_DW10_WTBL_SHFT                    0

/* =====================================================================================

  ---RIUCR1 (0x820d4000 + 0x03A4)---

    DW11_WTBL[31..0]             - (RW) The value of DW in WTBL for updating
                                     the data are updated to WTBL when WIUCR.RATE_UPDATE is asserted.

 =====================================================================================*/
#define WF_WTBLON_TOP_RIUCR1_DW11_WTBL_ADDR                    WF_WTBLON_TOP_RIUCR1_ADDR
#define WF_WTBLON_TOP_RIUCR1_DW11_WTBL_MASK                    0xFFFFFFFF                // DW11_WTBL[31..0]
#define WF_WTBLON_TOP_RIUCR1_DW11_WTBL_SHFT                    0

/* =====================================================================================

  ---RIUCR2 (0x820d4000 + 0x03A8)---

    DW12_WTBL[31..0]             - (RW) The value of DW in WTBL for updating
                                     the data are updated to WTBL when WIUCR.RATE_UPDATE is asserted.

 =====================================================================================*/
#define WF_WTBLON_TOP_RIUCR2_DW12_WTBL_ADDR                    WF_WTBLON_TOP_RIUCR2_ADDR
#define WF_WTBLON_TOP_RIUCR2_DW12_WTBL_MASK                    0xFFFFFFFF                // DW12_WTBL[31..0]
#define WF_WTBLON_TOP_RIUCR2_DW12_WTBL_SHFT                    0

/* =====================================================================================

  ---RIUCR3 (0x820d4000 + 0x03AC)---

    DW13_WTBL[31..0]             - (RW) The value of DW in WTBL for updating
                                     the data are updated to WTBL when WIUCR.RATE_UPDATE is asserted.

 =====================================================================================*/
#define WF_WTBLON_TOP_RIUCR3_DW13_WTBL_ADDR                    WF_WTBLON_TOP_RIUCR3_ADDR
#define WF_WTBLON_TOP_RIUCR3_DW13_WTBL_MASK                    0xFFFFFFFF                // DW13_WTBL[31..0]
#define WF_WTBLON_TOP_RIUCR3_DW13_WTBL_SHFT                    0

/* =====================================================================================

  ---ITCR (0x820d4000 + 0x03B0)---

    INDEX[5..0]                  - (RW) index
    RESERVED6[15..6]             - (RO) Reserved bits
    OP[16]                       - (RW) Operation
    RESERVED17[23..17]           - (RO) Reserved bits
    SELECT[25..24]               - (RW) indirect table select
    RESERVED26[30..26]           - (RO) Reserved bits
    EXECUTE[31]                  - (WO) execute the command

 =====================================================================================*/
#define WF_WTBLON_TOP_ITCR_EXECUTE_ADDR                        WF_WTBLON_TOP_ITCR_ADDR
#define WF_WTBLON_TOP_ITCR_EXECUTE_MASK                        0x80000000                // EXECUTE[31]
#define WF_WTBLON_TOP_ITCR_EXECUTE_SHFT                        31
#define WF_WTBLON_TOP_ITCR_SELECT_ADDR                         WF_WTBLON_TOP_ITCR_ADDR
#define WF_WTBLON_TOP_ITCR_SELECT_MASK                         0x03000000                // SELECT[25..24]
#define WF_WTBLON_TOP_ITCR_SELECT_SHFT                         24
#define WF_WTBLON_TOP_ITCR_OP_ADDR                             WF_WTBLON_TOP_ITCR_ADDR
#define WF_WTBLON_TOP_ITCR_OP_MASK                             0x00010000                // OP[16]
#define WF_WTBLON_TOP_ITCR_OP_SHFT                             16
#define WF_WTBLON_TOP_ITCR_INDEX_ADDR                          WF_WTBLON_TOP_ITCR_ADDR
#define WF_WTBLON_TOP_ITCR_INDEX_MASK                          0x0000003F                // INDEX[5..0]
#define WF_WTBLON_TOP_ITCR_INDEX_SHFT                          0

/* =====================================================================================

  ---ITDR0 (0x820d4000 + 0x03B8)---

    INDIRECT_TABLE_DATA[31..0]   - (RW) data for updating indirect table

 =====================================================================================*/
#define WF_WTBLON_TOP_ITDR0_INDIRECT_TABLE_DATA_ADDR           WF_WTBLON_TOP_ITDR0_ADDR
#define WF_WTBLON_TOP_ITDR0_INDIRECT_TABLE_DATA_MASK           0xFFFFFFFF                // INDIRECT_TABLE_DATA[31..0]
#define WF_WTBLON_TOP_ITDR0_INDIRECT_TABLE_DATA_SHFT           0

/* =====================================================================================

  ---ITDR1 (0x820d4000 + 0x03BC)---

    INDIRECT_TABLE_DATA[31..0]   - (RW) data for updating indirect table

 =====================================================================================*/
#define WF_WTBLON_TOP_ITDR1_INDIRECT_TABLE_DATA_ADDR           WF_WTBLON_TOP_ITDR1_ADDR
#define WF_WTBLON_TOP_ITDR1_INDIRECT_TABLE_DATA_MASK           0xFFFFFFFF                // INDIRECT_TABLE_DATA[31..0]
#define WF_WTBLON_TOP_ITDR1_INDIRECT_TABLE_DATA_SHFT           0

/* =====================================================================================

  ---MBIST_0 (0x820d4000 + 0x03D0)---

    RESERVED0[2..0]              - (RO) Reserved bits
    MEM_USE_DEFAULT_DELSEL[3]    - (RW)  xxx
    RESERVED4[31..4]             - (RO) Reserved bits

 =====================================================================================*/
#define WF_WTBLON_TOP_MBIST_0_MEM_USE_DEFAULT_DELSEL_ADDR      WF_WTBLON_TOP_MBIST_0_ADDR
#define WF_WTBLON_TOP_MBIST_0_MEM_USE_DEFAULT_DELSEL_MASK      0x00000008                // MEM_USE_DEFAULT_DELSEL[3]
#define WF_WTBLON_TOP_MBIST_0_MEM_USE_DEFAULT_DELSEL_SHFT      3

/* =====================================================================================

  ---MBIST_3 (0x820d4000 + 0x03D4)---

    MEM_DELSEL_0[31..0]          - (RW)  xxx

 =====================================================================================*/
#define WF_WTBLON_TOP_MBIST_3_MEM_DELSEL_0_ADDR                WF_WTBLON_TOP_MBIST_3_ADDR
#define WF_WTBLON_TOP_MBIST_3_MEM_DELSEL_0_MASK                0xFFFFFFFF                // MEM_DELSEL_0[31..0]
#define WF_WTBLON_TOP_MBIST_3_MEM_DELSEL_0_SHFT                0

/* =====================================================================================

  ---MBIST_4 (0x820d4000 + 0x03D8)---

    MEM_DELSEL_1[31..0]          - (RW)  xxx

 =====================================================================================*/
#define WF_WTBLON_TOP_MBIST_4_MEM_DELSEL_1_ADDR                WF_WTBLON_TOP_MBIST_4_ADDR
#define WF_WTBLON_TOP_MBIST_4_MEM_DELSEL_1_MASK                0xFFFFFFFF                // MEM_DELSEL_1[31..0]
#define WF_WTBLON_TOP_MBIST_4_MEM_DELSEL_1_SHFT                0

/* =====================================================================================

  ---MBIST_5 (0x820d4000 + 0x03DC)---

    MEM_DELSEL_2[31..0]          - (RW)  xxx

 =====================================================================================*/
#define WF_WTBLON_TOP_MBIST_5_MEM_DELSEL_2_ADDR                WF_WTBLON_TOP_MBIST_5_ADDR
#define WF_WTBLON_TOP_MBIST_5_MEM_DELSEL_2_MASK                0xFFFFFFFF                // MEM_DELSEL_2[31..0]
#define WF_WTBLON_TOP_MBIST_5_MEM_DELSEL_2_SHFT                0

/* =====================================================================================

  ---MBIST_11 (0x820d4000 + 0x03E0)---

    MBIST_REG_FUSE_SEL[0]        - (RW)  xxx
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WF_WTBLON_TOP_MBIST_11_MBIST_REG_FUSE_SEL_ADDR         WF_WTBLON_TOP_MBIST_11_ADDR
#define WF_WTBLON_TOP_MBIST_11_MBIST_REG_FUSE_SEL_MASK         0x00000001                // MBIST_REG_FUSE_SEL[0]
#define WF_WTBLON_TOP_MBIST_11_MBIST_REG_FUSE_SEL_SHFT         0

/* =====================================================================================

  ---MBIST_12 (0x820d4000 + 0x03E4)---

    LMACON_MBIST_PREFUSE_0[15..0] - (RO)  xxx
    RESERVED16[31..16]           - (RO) Reserved bits

 =====================================================================================*/
#define WF_WTBLON_TOP_MBIST_12_LMACON_MBIST_PREFUSE_0_ADDR     WF_WTBLON_TOP_MBIST_12_ADDR
#define WF_WTBLON_TOP_MBIST_12_LMACON_MBIST_PREFUSE_0_MASK     0x0000FFFF                // LMACON_MBIST_PREFUSE_0[15..0]
#define WF_WTBLON_TOP_MBIST_12_LMACON_MBIST_PREFUSE_0_SHFT     0

/* =====================================================================================

  ---MBIST_13 (0x820d4000 + 0x03E8)---

    LMACON_MBIST_PREFUSE_D_0[15..0] - (RO)  xxx
    RESERVED16[31..16]           - (RO) Reserved bits

 =====================================================================================*/
#define WF_WTBLON_TOP_MBIST_13_LMACON_MBIST_PREFUSE_D_0_ADDR   WF_WTBLON_TOP_MBIST_13_ADDR
#define WF_WTBLON_TOP_MBIST_13_LMACON_MBIST_PREFUSE_D_0_MASK   0x0000FFFF                // LMACON_MBIST_PREFUSE_D_0[15..0]
#define WF_WTBLON_TOP_MBIST_13_LMACON_MBIST_PREFUSE_D_0_SHFT   0

/* =====================================================================================

  ---MBIST_14 (0x820d4000 + 0x03EC)---

    FUSE_LOAD_SEL[0]             - (RW)  xxx
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WF_WTBLON_TOP_MBIST_14_FUSE_LOAD_SEL_ADDR              WF_WTBLON_TOP_MBIST_14_ADDR
#define WF_WTBLON_TOP_MBIST_14_FUSE_LOAD_SEL_MASK              0x00000001                // FUSE_LOAD_SEL[0]
#define WF_WTBLON_TOP_MBIST_14_FUSE_LOAD_SEL_SHFT              0

/* =====================================================================================

  ---DMY0 (0x820d4000 + 0x03F0)---

    DMY0[31..0]                  - (RW) Dummy Register with default value 0 for ECO purpose
                                     [31:16] : wtbloff
                                     [15:0] : wtblon

 =====================================================================================*/
#define WF_WTBLON_TOP_DMY0_DMY0_ADDR                           WF_WTBLON_TOP_DMY0_ADDR
#define WF_WTBLON_TOP_DMY0_DMY0_MASK                           0xFFFFFFFF                // DMY0[31..0]
#define WF_WTBLON_TOP_DMY0_DMY0_SHFT                           0

/* =====================================================================================

  ---DMY1 (0x820d4000 + 0x03F4)---

    DMY1[31..0]                  - (RW) Dummy Register with default value 1 for ECO purpose
                                     [31:16] : wtbloff
                                     [15:0] : wtblon

 =====================================================================================*/
#define WF_WTBLON_TOP_DMY1_DMY1_ADDR                           WF_WTBLON_TOP_DMY1_ADDR
#define WF_WTBLON_TOP_DMY1_DMY1_MASK                           0xFFFFFFFF                // DMY1[31..0]
#define WF_WTBLON_TOP_DMY1_DMY1_SHFT                           0

/* =====================================================================================

  ---DFR (0x820d4000 + 0x03F8)---

    SRAMIF_CS[15..0]             - (RO) SRAM interface FSM
    RESERVED16[19..16]           - (RO) Reserved bits
    MLOIF_DBG[23..20]            - (RO) MDP interface debug
    RESERVED24[27..24]           - (RO) Reserved bits
    SIFIF_CS[30..28]             - (RO) SIF interface FSM
    RESERVED31[31]               - (RO) Reserved bits

 =====================================================================================*/
#define WF_WTBLON_TOP_DFR_SIFIF_CS_ADDR                        WF_WTBLON_TOP_DFR_ADDR
#define WF_WTBLON_TOP_DFR_SIFIF_CS_MASK                        0x70000000                // SIFIF_CS[30..28]
#define WF_WTBLON_TOP_DFR_SIFIF_CS_SHFT                        28
#define WF_WTBLON_TOP_DFR_MLOIF_DBG_ADDR                       WF_WTBLON_TOP_DFR_ADDR
#define WF_WTBLON_TOP_DFR_MLOIF_DBG_MASK                       0x00F00000                // MLOIF_DBG[23..20]
#define WF_WTBLON_TOP_DFR_MLOIF_DBG_SHFT                       20
#define WF_WTBLON_TOP_DFR_SRAMIF_CS_ADDR                       WF_WTBLON_TOP_DFR_ADDR
#define WF_WTBLON_TOP_DFR_SRAMIF_CS_MASK                       0x0000FFFF                // SRAMIF_CS[15..0]
#define WF_WTBLON_TOP_DFR_SRAMIF_CS_SHFT                       0

/* =====================================================================================

  ---DBG (0x820d4000 + 0x03FC)---

    DBG_USER_SEL[5..0]           - (RW) Select the user for debug flag
    RESERVED6[14..6]             - (RO) Reserved bits
    DBG_MODE[15]                 - (RW) debug mode
    RESERVED16[30..16]           - (RO) Reserved bits
    CKEN_ERROR[31]               - (RO) HW debug info

 =====================================================================================*/
#define WF_WTBLON_TOP_DBG_CKEN_ERROR_ADDR                      WF_WTBLON_TOP_DBG_ADDR
#define WF_WTBLON_TOP_DBG_CKEN_ERROR_MASK                      0x80000000                // CKEN_ERROR[31]
#define WF_WTBLON_TOP_DBG_CKEN_ERROR_SHFT                      31
#define WF_WTBLON_TOP_DBG_DBG_MODE_ADDR                        WF_WTBLON_TOP_DBG_ADDR
#define WF_WTBLON_TOP_DBG_DBG_MODE_MASK                        0x00008000                // DBG_MODE[15]
#define WF_WTBLON_TOP_DBG_DBG_MODE_SHFT                        15
#define WF_WTBLON_TOP_DBG_DBG_USER_SEL_ADDR                    WF_WTBLON_TOP_DBG_ADDR
#define WF_WTBLON_TOP_DBG_DBG_USER_SEL_MASK                    0x0000003F                // DBG_USER_SEL[5..0]
#define WF_WTBLON_TOP_DBG_DBG_USER_SEL_SHFT                    0

#ifdef __cplusplus
}
#endif

#endif // __WF_WTBLON_TOP_REGS_H__
