# SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note
#
# (C) COPYRIGHT 2017-2023 ARM Limited. All rights reserved.
#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU license.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, you can access it online at
# http://www.gnu.org/licenses/gpl-2.0.html.
#
#
src:=$(if $(patsubst /%,,$(src)),$(srctree)/$(src),$(src))

ccflags-y += -I$(src)/include \
             -I$(src)

subdir-ccflags-y += -I$(src)/include \
                    -I$(src)

obj-$(CONFIG_MALI_KUTF) += kutf/
obj-$(CONFIG_MALI_KUTF_IRQ_TEST) += mali_kutf_irq_test/
obj-$(CONFIG_MALI_KUTF_CLK_RATE_TRACE) += mali_kutf_clk_rate_trace/kernel/
obj-$(CONFIG_MALI_KUTF_MGM_INTEGRATION) += mali_kutf_mgm_integration_test/

obj-$(CONFIG_MALI_KUTF_CSF_TESTS) += mali_kutf_csf_fault_unit_test/kernel/
obj-$(CONFIG_MALI_KUTF_CSF_TESTS) += mali_kutf_csf_ipa_control_unit_test/kernel/
obj-$(CONFIG_MALI_KUTF_CSF_TESTS) += mali_kutf_csf_tiler_heap_unit_test/kernel/
obj-$(CONFIG_MALI_KUTF_CSF_TESTS) += mali_kutf_csf_timeout_unit_test/kernel/
obj-$(CONFIG_MALI_KUTF_IPA_UNIT_TEST) += mali_kutf_ipa_unit_test/kernel/
obj-$(CONFIG_MALI_KUTF_KERNEL_DEFECT_TEST) += mali_kutf_kernel_defect_test/kernel/
obj-$(CONFIG_MALI_KUTF_KERNEL_POWER_TEST) += mali_kutf_kernel_power_test/kernel/
obj-$(CONFIG_MALI_KUTF_CSF_TESTS) += mali_kutf_pma_unit_test/kernel/

