/*  SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2019 MediaTek Inc.
 */

#ifndef CONNSYS_SMC_H
#define CONNSYS_SMC_H

#include "plat_def.h"

#define CONNSYS_SMC_CALL_VOID(OPID, x2, x3, x4, x5, x6, x7) \
struct arm_smccc_res res; \
arm_smccc_smc(MTK_SIP_KERNEL_CONNSYS_CONTROL, OPID, \
	      x2, x3, x4, x5, x6, x7, &res)

#define CONNSYS_SMC_CALL_RET(OPID, x2, x3, x4, x5, x6, x7, ret) \
struct arm_smccc_res res; \
arm_smccc_smc(MTK_SIP_KERNEL_CONNSYS_CONTROL, OPID, \
	      x2, x3, x4, x5, x6, x7, &res);  \
ret = res.a0;

enum conn_smc_opid
{
	/* init */
	SMC_CONNSYS_INIT_ATF_DATA_OPID = 0,

	/* consys_hw_ops */
	SMC_CONSYS_POLLING_CHIPID_OPID = 10,
	SMC_CONNSYS_D_DIE_CFG_OPID,
	SMC_CONNSYS_SPI_MASTER_CFG_OPID,
	SMC_CONNSYS_A_DIE_CFG_OPID,
	SMC_CONNSYS_AFE_SW_PATCH_OPID,
	SMC_CONNSYS_AFE_WBG_CAL_OPID,
	SMC_CONNSYS_SUBSYS_PLL_INITIAL_OPID,
	SMC_CONNSYS_LOW_POWER_SETTING_OPID,
	SMC_CONSYS_CONNINFRA_WAKEUP_OPID,
	SMC_CONSYS_CONNINFRA_SLEEP_OPID,

	SMC_CONNSYS_SPI_READ_OPID,
	SMC_CONNSYS_SPI_WRITE_OPID,
	SMC_CONNSYS_SPI_UPDATE_BITS_OPID,
	SMC_CONNSYS_SPI_CLOCK_SWITCH_OPID,
	SMC_CONNSYS_SUBSYS_STATUS_UPDATE_OPID,
	SMC_CONNSYS_THERMAL_QUERY_OPID,
	SMC_CONNSYS_RESET_POWER_STATE_OPID,
	SMC_CONNSYS_POWER_STATE_DUMP_START_OPID,
	SMC_CONNSYS_POWER_STATE_DUMP_2_OPID,
	SMC_CONNSYS_POWER_STATE_DUMP_3_OPID,

	SMC_CONNSYS_POWER_STATE_DUMP_4_OPID,
	SMC_CONNSYS_POWER_STATE_DUMP_5_OPID,
	SMC_CONNSYS_POWER_STATE_DUMP_6_OPID,
	SMC_CONNSYS_POWER_STATE_DUMP_7_OPID,
	SMC_CONNSYS_POWER_STATE_DUMP_8_OPID,
	SMC_CONNSYS_POWER_STATE_DUMP_END_OPID,
	SMC_CONNSYS_SET_MCU_CONTROL_OPID,
	SMC_CONNSYS_PRE_CAL_BACKUP_OPID,
	SMC_CONNSYS_PRE_CAL_CLEAN_DATA_OPID,

	/* g_consys_reg_ops */
	SMC_CONNSYS_DEBUG_INIT_OPID = 50,
	SMC_CONNSYS_DEBUG_DEINIT_OPID,
	SMC_CONNSYS_CHECK_CONNINFRA_OFF_DOMAIN_OPID,
	SMC_CONNSYS_CHECK_CONNINFRA_IRQ_STATUS_OPID,
	SMC_CONNSYS_PRINT_DEBUG_OPID,
	SMC_CONNSYS_CHECK_CONNINFRA_BUS_HANG_CLOCK_OPID,

	/* consys_platform_emi_ops */
	SMC_CONNSYS_EMI_SET_REMAPPING_REG_OPID = 70,

	/* consys_platform_coredump_ops */
	SMC_CONNSYS_SETUP_DUMP_REGION_OPID = 80,
	SMC_CONNSYS_SETUP_DYNAMIC_REMAP_OPID,

	/* customize */
	SMC_CONNSYS_ADIE_CLK_ENABLE_OPID = 90,
};

#endif	/* CONNSYS_SMC_H */
