ifneq (,$(filter $(CONFIG_MTK_MET),y m))
ORIGIN_SRC := $(if $(filter /%,$(src)),,$(srctree)/)$(src)
override src := $(ORIGIN_SRC)/../..

include $(src)/Kbuild

override src := $(ORIGIN_SRC)

obj-$(CONFIG_MTK_MET) := met_backlight_api.o
endif
