
C2PS_TOP := $(if $(filter /%,$(src)),,$(srctree)/)$(src)
C2PS_COMMON_TOP = $(C2PS_TOP)/common
C2PS_MONITOR_TOP = $(C2PS_TOP)/monitor
C2PS_REGULATOR_TOP = $(C2PS_TOP)/regulator

subdir-ccflags-y += \
        -I$(srctree)/include \
        -I$(srctree)/kernel \
        -I$(DEVICE_MODULES_PATH)/include/ \
        -I$(DEVICE_MODULES_PATH)/kernel/ \
        -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/sched/ \
        -I$(C2PS_COMMON_TOP)/include/ \
        -I$(C2PS_MONITOR_TOP)/include/ \
        -I$(C2PS_REGULATOR_TOP)/include/

$(info mtk_c2ps DEVICE_MODULES_PATH=$(DEVICE_MODULES_PATH))
NOTDIR_DEVICE_MODULES_PATH = $(notdir $(DEVICE_MODULES_PATH))
$(info mtk_c2ps NOTDIR_DEVICE_MODULES_PATH=$(NOTDIR_DEVICE_MODULES_PATH))
KERNEL_VERSION = $(patsubst kernel_device_modules-%,%,$(NOTDIR_DEVICE_MODULES_PATH))
$(info mtk_c2ps KERNEL_VERSION=$(KERNEL_VERSION))

ifeq (6.6,$(word 1,$(sort 6.6 $(KERNEL_VERSION))))
ccflags-y += -DNEW_C2PS_API_K66
endif

#c2ps_main
MTK_C2PS_MAIN = c2ps_main.o
#common
include $(C2PS_COMMON_TOP)/Kbuild
MTK_C2PS_COMMON = $(mtk_c2ps_common_objs:%.o=common/%.o)

#monitor
include $(C2PS_MONITOR_TOP)/Kbuild
MTK_C2PS_MONITOR = $(mtk_c2ps_monitor_objs:%.o=monitor/%.o)

#uclamp regulator
include $(C2PS_REGULATOR_TOP)/Kbuild
MTK_C2PS_REGULATOR = $(mtk_c2ps_regulator_objs:%.o=regulator/%.o)

MTK_C2PS_SRC = $(MTK_C2PS_MAIN) $(MTK_C2PS_COMMON) $(MTK_C2PS_MONITOR) $(MTK_C2PS_REGULATOR)
mtk_c2ps-objs += $(MTK_C2PS_SRC)
obj-$(CONFIG_MTK_C2PS) += mtk_c2ps.o
