# SPDX-License-Identifier: GPL-2.0-only
# Support GKI mixed build
ifeq ($(DEVICE_MODULES_PATH),)
DEVICE_MODULES_PATH = $(srctree)
else
LINUXINCLUDE := $(DEVCIE_MODULES_INCLUDE) $(LINUXINCLUDE)
endif

KO_CODE_PATH := $(if $(filter /%,$(src)),,$(srctree)/)$(src)

IMGSYS_ISP71_MODULE := mtk_imgsys_isp71

#platform dependent
ccflags-y += -I$(KO_CODE_PATH)/../../../mtk-hcp/legacy
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/cmdq/mailbox/
ccflags-y += -I$(KO_CODE_PATH)/../../common/
ccflags-y += -I$(KO_CODE_PATH)/../cmdq/legacy
ccflags-y += -I$(KO_CODE_PATH)/
ccflags-y += -I$(KO_CODE_PATH)/../../../mtk-ipesys-me/
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/mtk-interconnect/
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/smi/
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/iommu
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/iommu
ccflags-y += -I$(DEVICE_MODULES_PATH)/include/soc/mediatek
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include/

ccflags-y += -ferror-limit=0

$(info "imgsys, isp71 device_module_path = $(DEVICE_MODULES_PATH)")
$(info "imgsys, isp71 srctree_path = $(srctree)")
$(info "imgsys, isp71 src_path = $(src)")
$(info "imgsys, isp71 ko_code_path = $(KO_CODE_PATH)")

#register TF CB
ifneq ($(wildcard $(DEVICE_MODULES_PATH)/include/dt-bindings/memory/mt6983-larb-port.h),)
  subdir-ccflags-y += -DWPE_TF_DUMP_71_1
else ifneq ($(wildcard $(DEVICE_MODULES_PATH)/include/dt-bindings/memory/mt6879-larb-port.h),)
  subdir-ccflags-y += -DWPE_TF_DUMP_71_2
  subdir-ccflags-y += -DONEPIXEL_MODE
endif

$(info "imgsys, subdir-ccflags-y = $(subdir-ccflags-y)")

subdir-ccflags-y += -DMTK_IOVA_SINK2KERNEL

#mtk_imgsys_v4l2-y += mtk_imgsys-trace.o
#CFLAGS_mtk_imgsys-trace.o	:=-I$(src)
# Utilities to provide frame-based streaming model
# with v4l2 user interfaces and alloc context managing
# memory shared between ISP and coprocessor
$(IMGSYS_ISP71_MODULE)-objs := \
mtk_imgsys-isp71.o \
mtk_imgsys-v4l2.o \
mtk_imgsys-dev.o \
mtk_imgsys-sys.o \
mtk_imgsys-debug.o \
imgsys_modules/mtk_imgsys-dip.o \
imgsys_modules/mtk_imgsys-traw.o \
imgsys_modules/mtk_imgsys-pqdip.o \
imgsys_modules/mtk_imgsys-wpe.o \
imgsys_modules/mtk_imgsys-adl.o

obj-${CONFIG_VIDEO_MTK_ISP_IMGSYS_71} += $(IMGSYS_ISP71_MODULE).o