/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */

#ifndef __CONN_SEMAPHORE_REGS_H__
#define __CONN_SEMAPHORE_REGS_H__

#include "hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif

#define CONN_SEMAPHORE_BASE                                    0x18070000

#define CONN_SEMAPHORE_CONN_SEMA00_M0_OWN_STA_ADDR             (CONN_SEMAPHORE_BASE + 0x0000)
#define CONN_SEMAPHORE_CONN_SEMA01_M0_OWN_STA_ADDR             (CONN_SEMAPHORE_BASE + 0x0004)
#define CONN_SEMAPHORE_CONN_SEMA02_M0_OWN_STA_ADDR             (CONN_SEMAPHORE_BASE + 0x0008)
#define CONN_SEMAPHORE_CONN_SEMA03_M0_OWN_STA_ADDR             (CONN_SEMAPHORE_BASE + 0x000C)
#define CONN_SEMAPHORE_CONN_SEMA04_M0_OWN_STA_ADDR             (CONN_SEMAPHORE_BASE + 0x0010)
#define CONN_SEMAPHORE_CONN_SEMA05_M0_OWN_STA_ADDR             (CONN_SEMAPHORE_BASE + 0x0014)
#define CONN_SEMAPHORE_CONN_SEMA06_M0_OWN_STA_ADDR             (CONN_SEMAPHORE_BASE + 0x0018)
#define CONN_SEMAPHORE_CONN_SEMA07_M0_OWN_STA_ADDR             (CONN_SEMAPHORE_BASE + 0x001C)
#define CONN_SEMAPHORE_CONN_SEMA08_M0_OWN_STA_ADDR             (CONN_SEMAPHORE_BASE + 0x0020)
#define CONN_SEMAPHORE_CONN_SEMA09_M0_OWN_STA_ADDR             (CONN_SEMAPHORE_BASE + 0x0024)
#define CONN_SEMAPHORE_CONN_SEMA10_M0_OWN_STA_ADDR             (CONN_SEMAPHORE_BASE + 0x0028)
#define CONN_SEMAPHORE_CONN_SEMA11_M0_OWN_STA_ADDR             (CONN_SEMAPHORE_BASE + 0x002C)
#define CONN_SEMAPHORE_CONN_SEMA12_M0_OWN_STA_ADDR             (CONN_SEMAPHORE_BASE + 0x0030)
#define CONN_SEMAPHORE_CONN_SEMA13_M0_OWN_STA_ADDR             (CONN_SEMAPHORE_BASE + 0x0034)
#define CONN_SEMAPHORE_CONN_SEMA14_M0_OWN_STA_ADDR             (CONN_SEMAPHORE_BASE + 0x0038)
#define CONN_SEMAPHORE_CONN_SEMA15_M0_OWN_STA_ADDR             (CONN_SEMAPHORE_BASE + 0x003C)
#define CONN_SEMAPHORE_CONN_SEMA16_M0_OWN_STA_ADDR             (CONN_SEMAPHORE_BASE + 0x0040)
#define CONN_SEMAPHORE_CONN_SEMA17_M0_OWN_STA_ADDR             (CONN_SEMAPHORE_BASE + 0x0044)
#define CONN_SEMAPHORE_CONN_SEMA18_M0_OWN_STA_ADDR             (CONN_SEMAPHORE_BASE + 0x0048)
#define CONN_SEMAPHORE_CONN_SEMA19_M0_OWN_STA_ADDR             (CONN_SEMAPHORE_BASE + 0x004C)
#define CONN_SEMAPHORE_CONN_SEMA20_M0_OWN_STA_ADDR             (CONN_SEMAPHORE_BASE + 0x0050)
#define CONN_SEMAPHORE_CONN_SEMA21_M0_OWN_STA_ADDR             (CONN_SEMAPHORE_BASE + 0x0054)
#define CONN_SEMAPHORE_CONN_SEMA22_M0_OWN_STA_ADDR             (CONN_SEMAPHORE_BASE + 0x0058)
#define CONN_SEMAPHORE_CONN_SEMA23_M0_OWN_STA_ADDR             (CONN_SEMAPHORE_BASE + 0x005C)
#define CONN_SEMAPHORE_CONN_SEMA24_M0_OWN_STA_ADDR             (CONN_SEMAPHORE_BASE + 0x0060)
#define CONN_SEMAPHORE_CONN_SEMA00_M0_OWN_REL_ADDR             (CONN_SEMAPHORE_BASE + 0x0200)
#define CONN_SEMAPHORE_CONN_SEMA01_M0_OWN_REL_ADDR             (CONN_SEMAPHORE_BASE + 0x0204)
#define CONN_SEMAPHORE_CONN_SEMA02_M0_OWN_REL_ADDR             (CONN_SEMAPHORE_BASE + 0x0208)
#define CONN_SEMAPHORE_CONN_SEMA03_M0_OWN_REL_ADDR             (CONN_SEMAPHORE_BASE + 0x020C)
#define CONN_SEMAPHORE_CONN_SEMA04_M0_OWN_REL_ADDR             (CONN_SEMAPHORE_BASE + 0x0210)
#define CONN_SEMAPHORE_CONN_SEMA05_M0_OWN_REL_ADDR             (CONN_SEMAPHORE_BASE + 0x0214)
#define CONN_SEMAPHORE_CONN_SEMA06_M0_OWN_REL_ADDR             (CONN_SEMAPHORE_BASE + 0x0218)
#define CONN_SEMAPHORE_CONN_SEMA07_M0_OWN_REL_ADDR             (CONN_SEMAPHORE_BASE + 0x021C)
#define CONN_SEMAPHORE_CONN_SEMA08_M0_OWN_REL_ADDR             (CONN_SEMAPHORE_BASE + 0x0220)
#define CONN_SEMAPHORE_CONN_SEMA09_M0_OWN_REL_ADDR             (CONN_SEMAPHORE_BASE + 0x0224)
#define CONN_SEMAPHORE_CONN_SEMA10_M0_OWN_REL_ADDR             (CONN_SEMAPHORE_BASE + 0x0228)
#define CONN_SEMAPHORE_CONN_SEMA11_M0_OWN_REL_ADDR             (CONN_SEMAPHORE_BASE + 0x022C)
#define CONN_SEMAPHORE_CONN_SEMA12_M0_OWN_REL_ADDR             (CONN_SEMAPHORE_BASE + 0x0230)
#define CONN_SEMAPHORE_CONN_SEMA13_M0_OWN_REL_ADDR             (CONN_SEMAPHORE_BASE + 0x0234)
#define CONN_SEMAPHORE_CONN_SEMA14_M0_OWN_REL_ADDR             (CONN_SEMAPHORE_BASE + 0x0238)
#define CONN_SEMAPHORE_CONN_SEMA15_M0_OWN_REL_ADDR             (CONN_SEMAPHORE_BASE + 0x023C)
#define CONN_SEMAPHORE_CONN_SEMA16_M0_OWN_REL_ADDR             (CONN_SEMAPHORE_BASE + 0x0240)
#define CONN_SEMAPHORE_CONN_SEMA17_M0_OWN_REL_ADDR             (CONN_SEMAPHORE_BASE + 0x0244)
#define CONN_SEMAPHORE_CONN_SEMA18_M0_OWN_REL_ADDR             (CONN_SEMAPHORE_BASE + 0x0248)
#define CONN_SEMAPHORE_CONN_SEMA19_M0_OWN_REL_ADDR             (CONN_SEMAPHORE_BASE + 0x024C)
#define CONN_SEMAPHORE_CONN_SEMA20_M0_OWN_REL_ADDR             (CONN_SEMAPHORE_BASE + 0x0250)
#define CONN_SEMAPHORE_CONN_SEMA21_M0_OWN_REL_ADDR             (CONN_SEMAPHORE_BASE + 0x0254)
#define CONN_SEMAPHORE_CONN_SEMA22_M0_OWN_REL_ADDR             (CONN_SEMAPHORE_BASE + 0x0258)
#define CONN_SEMAPHORE_CONN_SEMA23_M0_OWN_REL_ADDR             (CONN_SEMAPHORE_BASE + 0x025C)
#define CONN_SEMAPHORE_CONN_SEMA24_M0_OWN_REL_ADDR             (CONN_SEMAPHORE_BASE + 0x0260)

#define CONN_SEMAPHORE_CONN_SEMA00_M0_OWN_REL_CONN_SEMA00_M0_OWN_REL_ADDR CONN_SEMAPHORE_CONN_SEMA00_M0_OWN_REL_ADDR
#define CONN_SEMAPHORE_CONN_SEMA00_M0_OWN_REL_CONN_SEMA00_M0_OWN_REL_MASK 0x00000001
#define CONN_SEMAPHORE_CONN_SEMA00_M0_OWN_REL_CONN_SEMA00_M0_OWN_REL_SHFT 0

#define CONN_SEMAPHORE_CONN_SEMA01_M0_OWN_REL_CONN_SEMA01_M0_OWN_REL_ADDR CONN_SEMAPHORE_CONN_SEMA01_M0_OWN_REL_ADDR
#define CONN_SEMAPHORE_CONN_SEMA01_M0_OWN_REL_CONN_SEMA01_M0_OWN_REL_MASK 0x00000001
#define CONN_SEMAPHORE_CONN_SEMA01_M0_OWN_REL_CONN_SEMA01_M0_OWN_REL_SHFT 0

#define CONN_SEMAPHORE_CONN_SEMA02_M0_OWN_REL_CONN_SEMA02_M0_OWN_REL_ADDR CONN_SEMAPHORE_CONN_SEMA02_M0_OWN_REL_ADDR
#define CONN_SEMAPHORE_CONN_SEMA02_M0_OWN_REL_CONN_SEMA02_M0_OWN_REL_MASK 0x00000001
#define CONN_SEMAPHORE_CONN_SEMA02_M0_OWN_REL_CONN_SEMA02_M0_OWN_REL_SHFT 0

#define CONN_SEMAPHORE_CONN_SEMA03_M0_OWN_REL_CONN_SEMA03_M0_OWN_REL_ADDR CONN_SEMAPHORE_CONN_SEMA03_M0_OWN_REL_ADDR
#define CONN_SEMAPHORE_CONN_SEMA03_M0_OWN_REL_CONN_SEMA03_M0_OWN_REL_MASK 0x00000001
#define CONN_SEMAPHORE_CONN_SEMA03_M0_OWN_REL_CONN_SEMA03_M0_OWN_REL_SHFT 0

#define CONN_SEMAPHORE_CONN_SEMA04_M0_OWN_REL_CONN_SEMA04_M0_OWN_REL_ADDR CONN_SEMAPHORE_CONN_SEMA04_M0_OWN_REL_ADDR
#define CONN_SEMAPHORE_CONN_SEMA04_M0_OWN_REL_CONN_SEMA04_M0_OWN_REL_MASK 0x00000001
#define CONN_SEMAPHORE_CONN_SEMA04_M0_OWN_REL_CONN_SEMA04_M0_OWN_REL_SHFT 0

#define CONN_SEMAPHORE_CONN_SEMA05_M0_OWN_REL_CONN_SEMA05_M0_OWN_REL_ADDR CONN_SEMAPHORE_CONN_SEMA05_M0_OWN_REL_ADDR
#define CONN_SEMAPHORE_CONN_SEMA05_M0_OWN_REL_CONN_SEMA05_M0_OWN_REL_MASK 0x00000001
#define CONN_SEMAPHORE_CONN_SEMA05_M0_OWN_REL_CONN_SEMA05_M0_OWN_REL_SHFT 0

#define CONN_SEMAPHORE_CONN_SEMA06_M0_OWN_REL_CONN_SEMA06_M0_OWN_REL_ADDR CONN_SEMAPHORE_CONN_SEMA06_M0_OWN_REL_ADDR
#define CONN_SEMAPHORE_CONN_SEMA06_M0_OWN_REL_CONN_SEMA06_M0_OWN_REL_MASK 0x00000001
#define CONN_SEMAPHORE_CONN_SEMA06_M0_OWN_REL_CONN_SEMA06_M0_OWN_REL_SHFT 0

#define CONN_SEMAPHORE_CONN_SEMA07_M0_OWN_REL_CONN_SEMA07_M0_OWN_REL_ADDR CONN_SEMAPHORE_CONN_SEMA07_M0_OWN_REL_ADDR
#define CONN_SEMAPHORE_CONN_SEMA07_M0_OWN_REL_CONN_SEMA07_M0_OWN_REL_MASK 0x00000001
#define CONN_SEMAPHORE_CONN_SEMA07_M0_OWN_REL_CONN_SEMA07_M0_OWN_REL_SHFT 0

#define CONN_SEMAPHORE_CONN_SEMA08_M0_OWN_REL_CONN_SEMA08_M0_OWN_REL_ADDR CONN_SEMAPHORE_CONN_SEMA08_M0_OWN_REL_ADDR
#define CONN_SEMAPHORE_CONN_SEMA08_M0_OWN_REL_CONN_SEMA08_M0_OWN_REL_MASK 0x00000001
#define CONN_SEMAPHORE_CONN_SEMA08_M0_OWN_REL_CONN_SEMA08_M0_OWN_REL_SHFT 0

#define CONN_SEMAPHORE_CONN_SEMA09_M0_OWN_REL_CONN_SEMA09_M0_OWN_REL_ADDR CONN_SEMAPHORE_CONN_SEMA09_M0_OWN_REL_ADDR
#define CONN_SEMAPHORE_CONN_SEMA09_M0_OWN_REL_CONN_SEMA09_M0_OWN_REL_MASK 0x00000001
#define CONN_SEMAPHORE_CONN_SEMA09_M0_OWN_REL_CONN_SEMA09_M0_OWN_REL_SHFT 0

#define CONN_SEMAPHORE_CONN_SEMA10_M0_OWN_REL_CONN_SEMA10_M0_OWN_REL_ADDR CONN_SEMAPHORE_CONN_SEMA10_M0_OWN_REL_ADDR
#define CONN_SEMAPHORE_CONN_SEMA10_M0_OWN_REL_CONN_SEMA10_M0_OWN_REL_MASK 0x00000001
#define CONN_SEMAPHORE_CONN_SEMA10_M0_OWN_REL_CONN_SEMA10_M0_OWN_REL_SHFT 0

#define CONN_SEMAPHORE_CONN_SEMA11_M0_OWN_REL_CONN_SEMA11_M0_OWN_REL_ADDR CONN_SEMAPHORE_CONN_SEMA11_M0_OWN_REL_ADDR
#define CONN_SEMAPHORE_CONN_SEMA11_M0_OWN_REL_CONN_SEMA11_M0_OWN_REL_MASK 0x00000001
#define CONN_SEMAPHORE_CONN_SEMA11_M0_OWN_REL_CONN_SEMA11_M0_OWN_REL_SHFT 0

#define CONN_SEMAPHORE_CONN_SEMA12_M0_OWN_REL_CONN_SEMA12_M0_OWN_REL_ADDR CONN_SEMAPHORE_CONN_SEMA12_M0_OWN_REL_ADDR
#define CONN_SEMAPHORE_CONN_SEMA12_M0_OWN_REL_CONN_SEMA12_M0_OWN_REL_MASK 0x00000001
#define CONN_SEMAPHORE_CONN_SEMA12_M0_OWN_REL_CONN_SEMA12_M0_OWN_REL_SHFT 0

#define CONN_SEMAPHORE_CONN_SEMA13_M0_OWN_REL_CONN_SEMA13_M0_OWN_REL_ADDR CONN_SEMAPHORE_CONN_SEMA13_M0_OWN_REL_ADDR
#define CONN_SEMAPHORE_CONN_SEMA13_M0_OWN_REL_CONN_SEMA13_M0_OWN_REL_MASK 0x00000001
#define CONN_SEMAPHORE_CONN_SEMA13_M0_OWN_REL_CONN_SEMA13_M0_OWN_REL_SHFT 0

#define CONN_SEMAPHORE_CONN_SEMA14_M0_OWN_REL_CONN_SEMA14_M0_OWN_REL_ADDR CONN_SEMAPHORE_CONN_SEMA14_M0_OWN_REL_ADDR
#define CONN_SEMAPHORE_CONN_SEMA14_M0_OWN_REL_CONN_SEMA14_M0_OWN_REL_MASK 0x00000001
#define CONN_SEMAPHORE_CONN_SEMA14_M0_OWN_REL_CONN_SEMA14_M0_OWN_REL_SHFT 0

#define CONN_SEMAPHORE_CONN_SEMA15_M0_OWN_REL_CONN_SEMA15_M0_OWN_REL_ADDR CONN_SEMAPHORE_CONN_SEMA15_M0_OWN_REL_ADDR
#define CONN_SEMAPHORE_CONN_SEMA15_M0_OWN_REL_CONN_SEMA15_M0_OWN_REL_MASK 0x00000001
#define CONN_SEMAPHORE_CONN_SEMA15_M0_OWN_REL_CONN_SEMA15_M0_OWN_REL_SHFT 0

#define CONN_SEMAPHORE_CONN_SEMA16_M0_OWN_REL_CONN_SEMA16_M0_OWN_REL_ADDR CONN_SEMAPHORE_CONN_SEMA16_M0_OWN_REL_ADDR
#define CONN_SEMAPHORE_CONN_SEMA16_M0_OWN_REL_CONN_SEMA16_M0_OWN_REL_MASK 0x00000001
#define CONN_SEMAPHORE_CONN_SEMA16_M0_OWN_REL_CONN_SEMA16_M0_OWN_REL_SHFT 0

#define CONN_SEMAPHORE_CONN_SEMA17_M0_OWN_REL_CONN_SEMA17_M0_OWN_REL_ADDR CONN_SEMAPHORE_CONN_SEMA17_M0_OWN_REL_ADDR
#define CONN_SEMAPHORE_CONN_SEMA17_M0_OWN_REL_CONN_SEMA17_M0_OWN_REL_MASK 0x00000001
#define CONN_SEMAPHORE_CONN_SEMA17_M0_OWN_REL_CONN_SEMA17_M0_OWN_REL_SHFT 0

#define CONN_SEMAPHORE_CONN_SEMA18_M0_OWN_REL_CONN_SEMA18_M0_OWN_REL_ADDR CONN_SEMAPHORE_CONN_SEMA18_M0_OWN_REL_ADDR
#define CONN_SEMAPHORE_CONN_SEMA18_M0_OWN_REL_CONN_SEMA18_M0_OWN_REL_MASK 0x00000001
#define CONN_SEMAPHORE_CONN_SEMA18_M0_OWN_REL_CONN_SEMA18_M0_OWN_REL_SHFT 0

#define CONN_SEMAPHORE_CONN_SEMA19_M0_OWN_REL_CONN_SEMA19_M0_OWN_REL_ADDR CONN_SEMAPHORE_CONN_SEMA19_M0_OWN_REL_ADDR
#define CONN_SEMAPHORE_CONN_SEMA19_M0_OWN_REL_CONN_SEMA19_M0_OWN_REL_MASK 0x00000001
#define CONN_SEMAPHORE_CONN_SEMA19_M0_OWN_REL_CONN_SEMA19_M0_OWN_REL_SHFT 0

#define CONN_SEMAPHORE_CONN_SEMA20_M0_OWN_REL_CONN_SEMA20_M0_OWN_REL_ADDR CONN_SEMAPHORE_CONN_SEMA20_M0_OWN_REL_ADDR
#define CONN_SEMAPHORE_CONN_SEMA20_M0_OWN_REL_CONN_SEMA20_M0_OWN_REL_MASK 0x00000001
#define CONN_SEMAPHORE_CONN_SEMA20_M0_OWN_REL_CONN_SEMA20_M0_OWN_REL_SHFT 0

#define CONN_SEMAPHORE_CONN_SEMA21_M0_OWN_REL_CONN_SEMA21_M0_OWN_REL_ADDR CONN_SEMAPHORE_CONN_SEMA21_M0_OWN_REL_ADDR
#define CONN_SEMAPHORE_CONN_SEMA21_M0_OWN_REL_CONN_SEMA21_M0_OWN_REL_MASK 0x00000001
#define CONN_SEMAPHORE_CONN_SEMA21_M0_OWN_REL_CONN_SEMA21_M0_OWN_REL_SHFT 0

#define CONN_SEMAPHORE_CONN_SEMA22_M0_OWN_REL_CONN_SEMA22_M0_OWN_REL_ADDR CONN_SEMAPHORE_CONN_SEMA22_M0_OWN_REL_ADDR
#define CONN_SEMAPHORE_CONN_SEMA22_M0_OWN_REL_CONN_SEMA22_M0_OWN_REL_MASK 0x00000001
#define CONN_SEMAPHORE_CONN_SEMA22_M0_OWN_REL_CONN_SEMA22_M0_OWN_REL_SHFT 0

#define CONN_SEMAPHORE_CONN_SEMA23_M0_OWN_REL_CONN_SEMA23_M0_OWN_REL_ADDR CONN_SEMAPHORE_CONN_SEMA23_M0_OWN_REL_ADDR
#define CONN_SEMAPHORE_CONN_SEMA23_M0_OWN_REL_CONN_SEMA23_M0_OWN_REL_MASK 0x00000001
#define CONN_SEMAPHORE_CONN_SEMA23_M0_OWN_REL_CONN_SEMA23_M0_OWN_REL_SHFT 0

#define CONN_SEMAPHORE_CONN_SEMA24_M0_OWN_REL_CONN_SEMA24_M0_OWN_REL_ADDR CONN_SEMAPHORE_CONN_SEMA24_M0_OWN_REL_ADDR
#define CONN_SEMAPHORE_CONN_SEMA24_M0_OWN_REL_CONN_SEMA24_M0_OWN_REL_MASK 0x00000001
#define CONN_SEMAPHORE_CONN_SEMA24_M0_OWN_REL_CONN_SEMA24_M0_OWN_REL_SHFT 0

#ifdef __cplusplus
}
#endif

#endif
