/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */

#ifndef __CONN_INFRA_RGU_ON_REGS_H__
#define __CONN_INFRA_RGU_ON_REGS_H__

#include "hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif

#define CONN_INFRA_RGU_ON_BASE                                 0x18000000

#define CONN_INFRA_RGU_ON_WFSYS_ON_TOP_PWR_CTL_ADDR            (CONN_INFRA_RGU_ON_BASE + 0x010)
#define CONN_INFRA_RGU_ON_WFSYS_CPU_SW_RST_B_ADDR              (CONN_INFRA_RGU_ON_BASE + 0x120)
#define CONN_INFRA_RGU_ON_WFSYS_SW_RST_B_ADDR                  (CONN_INFRA_RGU_ON_BASE + 0x140)

#define CONN_INFRA_RGU_ON_WFSYS_ON_TOP_PWR_CTL_WFSYS_ON_TOP_WRITE_KEY_ADDR CONN_INFRA_RGU_ON_WFSYS_ON_TOP_PWR_CTL_ADDR
#define CONN_INFRA_RGU_ON_WFSYS_ON_TOP_PWR_CTL_WFSYS_ON_TOP_WRITE_KEY_MASK 0xFFFF0000
#define CONN_INFRA_RGU_ON_WFSYS_ON_TOP_PWR_CTL_WFSYS_ON_TOP_WRITE_KEY_SHFT 16
#define CONN_INFRA_RGU_ON_WFSYS_ON_TOP_PWR_CTL_WFSYS_ON_TOP_PWR_ON_ADDR CONN_INFRA_RGU_ON_WFSYS_ON_TOP_PWR_CTL_ADDR
#define CONN_INFRA_RGU_ON_WFSYS_ON_TOP_PWR_CTL_WFSYS_ON_TOP_PWR_ON_MASK 0x00000080
#define CONN_INFRA_RGU_ON_WFSYS_ON_TOP_PWR_CTL_WFSYS_ON_TOP_PWR_ON_SHFT 7

#define CONN_INFRA_RGU_ON_WFSYS_CPU_SW_RST_B_WFSYS_CPU_SW_RST_B_ADDR CONN_INFRA_RGU_ON_WFSYS_CPU_SW_RST_B_ADDR
#define CONN_INFRA_RGU_ON_WFSYS_CPU_SW_RST_B_WFSYS_CPU_SW_RST_B_MASK 0x00000001
#define CONN_INFRA_RGU_ON_WFSYS_CPU_SW_RST_B_WFSYS_CPU_SW_RST_B_SHFT 0

#define CONN_INFRA_RGU_ON_WFSYS_SW_RST_B_WFSYS_SW_RST_B_ADDR   CONN_INFRA_RGU_ON_WFSYS_SW_RST_B_ADDR
#define CONN_INFRA_RGU_ON_WFSYS_SW_RST_B_WFSYS_SW_RST_B_MASK   0x00000001
#define CONN_INFRA_RGU_ON_WFSYS_SW_RST_B_WFSYS_SW_RST_B_SHFT   0

#ifdef __cplusplus
}
#endif

#endif
