/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2021 MediaTek Inc.
 */

#ifndef __CONN_INFRA_CLKGEN_TOP_REGS_H__
#define __CONN_INFRA_CLKGEN_TOP_REGS_H__

#include "hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif

#define CONN_INFRA_CLKGEN_TOP_BASE                             0x18012000

#define CONN_INFRA_CLKGEN_TOP_CKGEN_COEX_0_SET_ADDR            (CONN_INFRA_CLKGEN_TOP_BASE + 0x064)
#define CONN_INFRA_CLKGEN_TOP_CKGEN_COEX_0_CLR_ADDR            (CONN_INFRA_CLKGEN_TOP_BASE + 0x068)
#define CONN_INFRA_CLKGEN_TOP_CKGEN_COEX_1_SET_ADDR            (CONN_INFRA_CLKGEN_TOP_BASE + 0x074)
#define CONN_INFRA_CLKGEN_TOP_CKGEN_COEX_1_CLR_ADDR            (CONN_INFRA_CLKGEN_TOP_BASE + 0x078)

#define CONN_INFRA_CLKGEN_TOP_CKGEN_COEX_0_SET_CONN_CO_EXT_PTA_HCLK_CKEN_M0_MASK 0x01000000
#define CONN_INFRA_CLKGEN_TOP_CKGEN_COEX_0_SET_CONN_CO_EXT_PTA_OSC_CKEN_M0_MASK 0x00010000
#define CONN_INFRA_CLKGEN_TOP_CKGEN_COEX_0_SET_CONN_CO_EXT_UART_PTA_HCLK_CKEN_M0_MASK 0x00000100
#define CONN_INFRA_CLKGEN_TOP_CKGEN_COEX_0_SET_CONN_CO_EXT_UART_PTA_OSC_CKEN_M0_MASK 0x00000001

#define CONN_INFRA_CLKGEN_TOP_CKGEN_COEX_1_SET_CONN_BSI_CNS_HCLK_CKEN_M0_MASK 0x00000100
#define CONN_INFRA_CLKGEN_TOP_CKGEN_COEX_1_SET_CONN_CO_EXT_FDD_COEX_HCLKCKEN_M0_MASK 0x00000001

#ifdef __cplusplus
}
#endif

#endif
