/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2021 MediaTek Inc.
 */

#ifndef __WF_MCU_CONFG_LS_REGS_H__
#define __WF_MCU_CONFG_LS_REGS_H__

#include "hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif

#define WF_MCU_CONFG_LS_BASE                                   0x184F0000

#define WF_MCU_CONFG_LS_BUSHANGCTRLA_ADDR                      (WF_MCU_CONFG_LS_BASE + 0x0430)
#define WF_MCU_CONFG_LS_BUSHANGCR_ADDR                         (WF_MCU_CONFG_LS_BASE + 0x0440)
#define WF_MCU_CONFG_LS_BUSHANGADDR_ADDR                       (WF_MCU_CONFG_LS_BASE + 0x0444)
#define WF_MCU_CONFG_LS_BUSHANGID_ADDR                         (WF_MCU_CONFG_LS_BASE + 0x044C)
#define WF_MCU_CONFG_LS_BUSHANGBUS_ADDR                        (WF_MCU_CONFG_LS_BASE + 0x0450)

#define WF_MCU_CONFG_LS_BUSHANGCR_BUS_HANG_DEBUG_EN_ADDR       WF_MCU_CONFG_LS_BUSHANGCR_ADDR
#define WF_MCU_CONFG_LS_BUSHANGCR_BUS_HANG_DEBUG_EN_MASK       0x80000000
#define WF_MCU_CONFG_LS_BUSHANGCR_BUS_HANG_DEBUG_EN_SHFT       31
#define WF_MCU_CONFG_LS_BUSHANGCR_BUS_HANG_DEBUG_CG_EN_ADDR    WF_MCU_CONFG_LS_BUSHANGCR_ADDR
#define WF_MCU_CONFG_LS_BUSHANGCR_BUS_HANG_DEBUG_CG_EN_MASK    0x10000000
#define WF_MCU_CONFG_LS_BUSHANGCR_BUS_HANG_DEBUG_CG_EN_SHFT    28
#define WF_MCU_CONFG_LS_BUSHANGCR_BUS_HANG_TIME_LIMIT_ADDR     WF_MCU_CONFG_LS_BUSHANGCR_ADDR
#define WF_MCU_CONFG_LS_BUSHANGCR_BUS_HANG_TIME_LIMIT_MASK     0x000000FF
#define WF_MCU_CONFG_LS_BUSHANGCR_BUS_HANG_TIME_LIMIT_SHFT     0

#ifdef __cplusplus
}
#endif

#endif
