/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */
#ifndef __BG_GPS_RGU_ON_REGS_H__
#define __BG_GPS_RGU_ON_REGS_H__

#define BG_GPS_RGU_ON_BASE                                     0x81020000

#define BG_GPS_RGU_ON_GPS_L1_CR_ADDR                           (BG_GPS_RGU_ON_BASE + 0x014)
#define BG_GPS_RGU_ON_GPS_L1_DSPPRAM_PDN_EN_ADDR               (BG_GPS_RGU_ON_BASE + 0x048)
#define BG_GPS_RGU_ON_GPS_L1_DSPPRAM_SLP_EN_ADDR               (BG_GPS_RGU_ON_BASE + 0x04c)
#define BG_GPS_RGU_ON_GPS_L1_DSPXRAM_PDN_EN_ADDR               (BG_GPS_RGU_ON_BASE + 0x050)
#define BG_GPS_RGU_ON_GPS_L1_DSPXRAM_SLP_EN_ADDR               (BG_GPS_RGU_ON_BASE + 0x054)
#define BG_GPS_RGU_ON_GPS_L1_DSPYRAM_PDN_EN_ADDR               (BG_GPS_RGU_ON_BASE + 0x058)
#define BG_GPS_RGU_ON_GPS_L1_DSPYRAM_SLP_EN_ADDR               (BG_GPS_RGU_ON_BASE + 0x05c)
#define BG_GPS_RGU_ON_GPS_L1_N1_MEM_PDN_EN_ADDR                (BG_GPS_RGU_ON_BASE + 0x068)
#define BG_GPS_RGU_ON_GPS_L1_N1_MEM_SLP_EN_ADDR                (BG_GPS_RGU_ON_BASE + 0x06c)
#define BG_GPS_RGU_ON_GPS_L1_DLY_CHAIN_CTL_ADDR                (BG_GPS_RGU_ON_BASE + 0x160)
#define BG_GPS_RGU_ON_GPS_L5_CR_ADDR                           (BG_GPS_RGU_ON_BASE + 0x214)
#define BG_GPS_RGU_ON_GPS_L5_DSPPRAM_PDN_EN_ADDR               (BG_GPS_RGU_ON_BASE + 0x248)
#define BG_GPS_RGU_ON_GPS_L5_DSPPRAM_SLP_EN_ADDR               (BG_GPS_RGU_ON_BASE + 0x24c)
#define BG_GPS_RGU_ON_GPS_L5_DSPXRAM_PDN_EN_ADDR               (BG_GPS_RGU_ON_BASE + 0x250)
#define BG_GPS_RGU_ON_GPS_L5_DSPXRAM_SLP_EN_ADDR               (BG_GPS_RGU_ON_BASE + 0x254)
#define BG_GPS_RGU_ON_GPS_L5_DSPYRAM_PDN_EN_ADDR               (BG_GPS_RGU_ON_BASE + 0x258)
#define BG_GPS_RGU_ON_GPS_L5_DSPYRAM_SLP_EN_ADDR               (BG_GPS_RGU_ON_BASE + 0x25c)
#define BG_GPS_RGU_ON_GPS_L5_DLY_CHAIN_CTL_ADDR                (BG_GPS_RGU_ON_BASE + 0x360)

#define BG_GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_SOFT_RST_B_ADDR     BG_GPS_RGU_ON_GPS_L1_CR_ADDR
#define BG_GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_SOFT_RST_B_MASK     0x00000020
#define BG_GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_SOFT_RST_B_SHFT     5
#define BG_GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_ON_ADDR             BG_GPS_RGU_ON_GPS_L1_CR_ADDR
#define BG_GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_ON_MASK             0x00000001
#define BG_GPS_RGU_ON_GPS_L1_CR_RGU_GPS_L1_ON_SHFT             0

#define BG_GPS_RGU_ON_GPS_L1_DSPPRAM_PDN_EN_RGU_GPS_L1_PRAM_HWCTL_PDN_ADDR \
	BG_GPS_RGU_ON_GPS_L1_DSPPRAM_PDN_EN_ADDR
#define BG_GPS_RGU_ON_GPS_L1_DSPPRAM_PDN_EN_RGU_GPS_L1_PRAM_HWCTL_PDN_MASK 0x0000007F
#define BG_GPS_RGU_ON_GPS_L1_DSPPRAM_PDN_EN_RGU_GPS_L1_PRAM_HWCTL_PDN_SHFT 0

#define BG_GPS_RGU_ON_GPS_L1_DSPPRAM_SLP_EN_RGU_GPS_L1_PRAM_HWCTL_SLP_ADDR \
	BG_GPS_RGU_ON_GPS_L1_DSPPRAM_SLP_EN_ADDR
#define BG_GPS_RGU_ON_GPS_L1_DSPPRAM_SLP_EN_RGU_GPS_L1_PRAM_HWCTL_SLP_MASK 0x0000007F
#define BG_GPS_RGU_ON_GPS_L1_DSPPRAM_SLP_EN_RGU_GPS_L1_PRAM_HWCTL_SLP_SHFT 0

#define BG_GPS_RGU_ON_GPS_L1_DSPXRAM_PDN_EN_RGU_GPS_L1_XRAM_HWCTL_PDN_ADDR \
	BG_GPS_RGU_ON_GPS_L1_DSPXRAM_PDN_EN_ADDR
#define BG_GPS_RGU_ON_GPS_L1_DSPXRAM_PDN_EN_RGU_GPS_L1_XRAM_HWCTL_PDN_MASK 0x00000003
#define BG_GPS_RGU_ON_GPS_L1_DSPXRAM_PDN_EN_RGU_GPS_L1_XRAM_HWCTL_PDN_SHFT 0

#define BG_GPS_RGU_ON_GPS_L1_DSPXRAM_SLP_EN_RGU_GPS_L1_XRAM_HWCTL_SLP_ADDR \
	BG_GPS_RGU_ON_GPS_L1_DSPXRAM_SLP_EN_ADDR
#define BG_GPS_RGU_ON_GPS_L1_DSPXRAM_SLP_EN_RGU_GPS_L1_XRAM_HWCTL_SLP_MASK 0x00000003
#define BG_GPS_RGU_ON_GPS_L1_DSPXRAM_SLP_EN_RGU_GPS_L1_XRAM_HWCTL_SLP_SHFT 0

#define BG_GPS_RGU_ON_GPS_L1_DSPYRAM_PDN_EN_RGU_GPS_L1_YRAM_HWCTL_PDN_ADDR \
	BG_GPS_RGU_ON_GPS_L1_DSPYRAM_PDN_EN_ADDR
#define BG_GPS_RGU_ON_GPS_L1_DSPYRAM_PDN_EN_RGU_GPS_L1_YRAM_HWCTL_PDN_MASK 0x007FFFFF
#define BG_GPS_RGU_ON_GPS_L1_DSPYRAM_PDN_EN_RGU_GPS_L1_YRAM_HWCTL_PDN_SHFT 0

#define BG_GPS_RGU_ON_GPS_L1_DSPYRAM_SLP_EN_RGU_GPS_L1_YRAM_HWCTL_SLP_ADDR \
	BG_GPS_RGU_ON_GPS_L1_DSPYRAM_SLP_EN_ADDR
#define BG_GPS_RGU_ON_GPS_L1_DSPYRAM_SLP_EN_RGU_GPS_L1_YRAM_HWCTL_SLP_MASK 0x007FFFFF
#define BG_GPS_RGU_ON_GPS_L1_DSPYRAM_SLP_EN_RGU_GPS_L1_YRAM_HWCTL_SLP_SHFT 0

#define BG_GPS_RGU_ON_GPS_L1_N1_MEM_PDN_EN_RGU_GPS_L1_N1_MEM_HWCTL_PDN_ADDR \
	BG_GPS_RGU_ON_GPS_L1_N1_MEM_PDN_EN_ADDR
#define BG_GPS_RGU_ON_GPS_L1_N1_MEM_PDN_EN_RGU_GPS_L1_N1_MEM_HWCTL_PDN_MASK 0x00001FFF
#define BG_GPS_RGU_ON_GPS_L1_N1_MEM_PDN_EN_RGU_GPS_L1_N1_MEM_HWCTL_PDN_SHFT 0

#define BG_GPS_RGU_ON_GPS_L1_N1_MEM_SLP_EN_RGU_GPS_L1_N1_MEM_HWCTL_SLP_ADDR \
	BG_GPS_RGU_ON_GPS_L1_N1_MEM_SLP_EN_ADDR
#define BG_GPS_RGU_ON_GPS_L1_N1_MEM_SLP_EN_RGU_GPS_L1_N1_MEM_HWCTL_SLP_MASK 0x00001FFF
#define BG_GPS_RGU_ON_GPS_L1_N1_MEM_SLP_EN_RGU_GPS_L1_N1_MEM_HWCTL_SLP_SHFT 0

#define BG_GPS_RGU_ON_GPS_L1_DLY_CHAIN_CTL_RGU_GPS_L1_MEM_PDN_DELAY_DUMMY_NUM_ADDR \
	BG_GPS_RGU_ON_GPS_L1_DLY_CHAIN_CTL_ADDR
#define BG_GPS_RGU_ON_GPS_L1_DLY_CHAIN_CTL_RGU_GPS_L1_MEM_PDN_DELAY_DUMMY_NUM_MASK 0x000F0000
#define BG_GPS_RGU_ON_GPS_L1_DLY_CHAIN_CTL_RGU_GPS_L1_MEM_PDN_DELAY_DUMMY_NUM_SHFT 16

#define BG_GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_SOFT_RST_B_ADDR     BG_GPS_RGU_ON_GPS_L5_CR_ADDR
#define BG_GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_SOFT_RST_B_MASK     0x00000020
#define BG_GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_SOFT_RST_B_SHFT     5
#define BG_GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_ON_ADDR             BG_GPS_RGU_ON_GPS_L5_CR_ADDR
#define BG_GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_ON_MASK             0x00000001
#define BG_GPS_RGU_ON_GPS_L5_CR_RGU_GPS_L5_ON_SHFT             0

#define BG_GPS_RGU_ON_GPS_L5_DSPPRAM_PDN_EN_RGU_GPS_L5_PRAM_HWCTL_PDN_ADDR \
	BG_GPS_RGU_ON_GPS_L5_DSPPRAM_PDN_EN_ADDR
#define BG_GPS_RGU_ON_GPS_L5_DSPPRAM_PDN_EN_RGU_GPS_L5_PRAM_HWCTL_PDN_MASK 0x0000003F
#define BG_GPS_RGU_ON_GPS_L5_DSPPRAM_PDN_EN_RGU_GPS_L5_PRAM_HWCTL_PDN_SHFT 0

#define BG_GPS_RGU_ON_GPS_L5_DSPPRAM_SLP_EN_RGU_GPS_L5_PRAM_HWCTL_SLP_ADDR \
	BG_GPS_RGU_ON_GPS_L5_DSPPRAM_SLP_EN_ADDR
#define BG_GPS_RGU_ON_GPS_L5_DSPPRAM_SLP_EN_RGU_GPS_L5_PRAM_HWCTL_SLP_MASK 0x0000003F
#define BG_GPS_RGU_ON_GPS_L5_DSPPRAM_SLP_EN_RGU_GPS_L5_PRAM_HWCTL_SLP_SHFT 0

#define BG_GPS_RGU_ON_GPS_L5_DSPXRAM_PDN_EN_RGU_GPS_L5_XRAM_HWCTL_PDN_ADDR \
	BG_GPS_RGU_ON_GPS_L5_DSPXRAM_PDN_EN_ADDR
#define BG_GPS_RGU_ON_GPS_L5_DSPXRAM_PDN_EN_RGU_GPS_L5_XRAM_HWCTL_PDN_MASK 0x00000003
#define BG_GPS_RGU_ON_GPS_L5_DSPXRAM_PDN_EN_RGU_GPS_L5_XRAM_HWCTL_PDN_SHFT 0

#define BG_GPS_RGU_ON_GPS_L5_DSPXRAM_SLP_EN_RGU_GPS_L5_XRAM_HWCTL_SLP_ADDR \
	BG_GPS_RGU_ON_GPS_L5_DSPXRAM_SLP_EN_ADDR
#define BG_GPS_RGU_ON_GPS_L5_DSPXRAM_SLP_EN_RGU_GPS_L5_XRAM_HWCTL_SLP_MASK 0x00000003
#define BG_GPS_RGU_ON_GPS_L5_DSPXRAM_SLP_EN_RGU_GPS_L5_XRAM_HWCTL_SLP_SHFT 0

#define BG_GPS_RGU_ON_GPS_L5_DSPYRAM_PDN_EN_RGU_GPS_L5_YRAM_HWCTL_PDN_ADDR \
	BG_GPS_RGU_ON_GPS_L5_DSPYRAM_PDN_EN_ADDR
#define BG_GPS_RGU_ON_GPS_L5_DSPYRAM_PDN_EN_RGU_GPS_L5_YRAM_HWCTL_PDN_MASK 0x00000FFF
#define BG_GPS_RGU_ON_GPS_L5_DSPYRAM_PDN_EN_RGU_GPS_L5_YRAM_HWCTL_PDN_SHFT 0

#define BG_GPS_RGU_ON_GPS_L5_DSPYRAM_SLP_EN_RGU_GPS_L5_YRAM_HWCTL_SLP_ADDR \
	BG_GPS_RGU_ON_GPS_L5_DSPYRAM_SLP_EN_ADDR
#define BG_GPS_RGU_ON_GPS_L5_DSPYRAM_SLP_EN_RGU_GPS_L5_YRAM_HWCTL_SLP_MASK 0x00000FFF
#define BG_GPS_RGU_ON_GPS_L5_DSPYRAM_SLP_EN_RGU_GPS_L5_YRAM_HWCTL_SLP_SHFT 0

#define BG_GPS_RGU_ON_GPS_L5_DLY_CHAIN_CTL_RGU_GPS_L5_MEM_PDN_DELAY_DUMMY_NUM_ADDR \
	BG_GPS_RGU_ON_GPS_L5_DLY_CHAIN_CTL_ADDR
#define BG_GPS_RGU_ON_GPS_L5_DLY_CHAIN_CTL_RGU_GPS_L5_MEM_PDN_DELAY_DUMMY_NUM_MASK 0x000F0000
#define BG_GPS_RGU_ON_GPS_L5_DLY_CHAIN_CTL_RGU_GPS_L5_MEM_PDN_DELAY_DUMMY_NUM_SHFT 16


#endif /* __BG_GPS_RGU_ON_REGS_H__*/
