ifeq ($(DEVICE_MODULES_PATH),)
DEVICE_MODULES_PATH = $(srctree)
else
LINUXINCLUDE := $(DEVCIE_MODULES_INCLUDE) $(LINUXINCLUDE)
endif

KO_CODE_PATH := $(if $(filter /%,$(src)),,$(srctree)/)$(src)

subdir-ccflags-y += -I$(KO_CODE_PATH)/

obj-$(CONFIG_MTK_ISP_PSPM) += isp_pspm_ioctl/
