include $(CLEAR_VARS)

LOCAL_MODULE := $(WIFI_NAME).ko
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MODULE_OWNER := mtk
LOCAL_INIT_RC := init.wlan_mt79xx_drv.rc

include $(MTK_KERNEL_MODULE)

WIFI_OPTS := CONFIG_MTK_COMBO_WIFI_HIF=$(WIFI_HIF) MODULE_NAME=$(WIFI_NAME) MTK_COMBO_CHIP=$(WIFI_CHIP) CONFIG_MTK_PLATFORM=$(MTK_PLATFORM) MTK_ANDROID_WMT=$(WIFI_WMT) MTK_ANDROID_EMI=$(WIFI_EMI)

$(linked_module): OPTS += $(WIFI_OPTS)
