# Sources path
KO_CODE_PATH := $(if $(filter /%,$(src)),,$(srctree)/)$(src)

# KO specfied attributes
WLAN_CHIP_ID := 7961
MTK_COMBO_CHIP := MT7961
WIFI_IP_SET := 1
CONNAC_VER := 2_0
CONFIG_MTK_COMBO_WIFI_HIF := pcie
MTK_ANDROID_WMT := n
MTK_ANDROID_EMI := n
MODULE_NAME := wlan_drv_gen4_mt7961.ko

include $(KO_CODE_PATH)/Kbuild.main
