/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2021 MediaTek Inc.
 */

#ifndef __BG_GPS_MET_TOP_REGS_H__
#define __BG_GPS_MET_TOP_REGS_H__

#define BG_GPS_MET_TOP_BASE                                    0x80023000

#define BG_GPS_MET_TOP_BG_GPS_MET_CTL0_ADDR                    (BG_GPS_MET_TOP_BASE + 0x000)
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL1_ADDR                    (BG_GPS_MET_TOP_BASE + 0x004)
#define BG_GPS_MET_TOP_BG_GPS_MET_EDGE_DET_ADDR                (BG_GPS_MET_TOP_BASE + 0x008)
#define BG_GPS_MET_TOP_BG_GPS_MET_START_ADDR_ADDR              (BG_GPS_MET_TOP_BASE + 0x00C)
#define BG_GPS_MET_TOP_BG_GPS_MET_END_ADDR_ADDR                (BG_GPS_MET_TOP_BASE + 0x010)
#define BG_GPS_MET_TOP_BG_GPS_MET_WRITE_PTR_ADDR               (BG_GPS_MET_TOP_BASE + 0x014)
#define BG_GPS_MET_TOP_BG_GPS_MET_READ_PTR_ADDR                (BG_GPS_MET_TOP_BASE + 0x018)
#define BG_GPS_MET_TOP_BG_GPS_MET_FLAG_ADDR                    (BG_GPS_MET_TOP_BASE + 0x01C)
#define BG_GPS_MET_TOP_BG_GPS_MET_EVENT_SEL0_ADDR              (BG_GPS_MET_TOP_BASE + 0x020)
#define BG_GPS_MET_TOP_BG_GPS_MET_SWCTL_ADDR                   (BG_GPS_MET_TOP_BASE + 0x024)
#define BG_GPS_MET_TOP_BG_GPS_MET_SIGNAL_SEL_ADDR              (BG_GPS_MET_TOP_BASE + 0x028)
#define BG_GPS_MET_TOP_BG_GPS_MET_CLK_CTL_ADDR                 (BG_GPS_MET_TOP_BASE + 0x02C)
#define BG_GPS_MET_TOP_BG_GPS_MET_AFE_SEL_ADDR                 (BG_GPS_MET_TOP_BASE + 0x030)
#define BG_GPS_MET_TOP_BG_GPS_MET_IRQ_CTL_ADDR                 (BG_GPS_MET_TOP_BASE + 0x100)
#define BG_GPS_MET_TOP_BG_GPS_MET_IRQ_STATUS_ADDR              (BG_GPS_MET_TOP_BASE + 0x104)

#define BG_GPS_MET_TOP_BG_GPS_MET_CTL0_MET_DATA_MASK_ADDR      BG_GPS_MET_TOP_BG_GPS_MET_CTL0_ADDR
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL0_MET_DATA_MASK_MASK      0xFFFF0000
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL0_MET_DATA_MASK_SHFT      16
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL0_MET_OSC_CNT_TARGET_ADDR BG_GPS_MET_TOP_BG_GPS_MET_CTL0_ADDR
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL0_MET_OSC_CNT_TARGET_MASK 0x00007F00
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL0_MET_OSC_CNT_TARGET_SHFT 8
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL0_MET_EVENT_SEL_ADDR      BG_GPS_MET_TOP_BG_GPS_MET_CTL0_ADDR
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL0_MET_EVENT_SEL_MASK      0x000000F0
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL0_MET_EVENT_SEL_SHFT      4
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL0_MET_USE_EMI_EN_ADDR     BG_GPS_MET_TOP_BG_GPS_MET_CTL0_ADDR
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL0_MET_USE_EMI_EN_MASK     0x00000008
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL0_MET_USE_EMI_EN_SHFT     3
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL0_MET_RECORD_SLEEP_EN_ADDR BG_GPS_MET_TOP_BG_GPS_MET_CTL0_ADDR
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL0_MET_RECORD_SLEEP_EN_MASK 0x00000004
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL0_MET_RECORD_SLEEP_EN_SHFT 2
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL0_MET_CLK_EN_ADDR         BG_GPS_MET_TOP_BG_GPS_MET_CTL0_ADDR
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL0_MET_CLK_EN_MASK         0x00000002
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL0_MET_CLK_EN_SHFT         1
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL0_MET_RECORD_EN_ADDR      BG_GPS_MET_TOP_BG_GPS_MET_CTL0_ADDR
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL0_MET_RECORD_EN_MASK      0x00000001
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL0_MET_RECORD_EN_SHFT      0


#define BG_GPS_MET_TOP_BG_GPS_MET_CTL1_MET_DBG_CNT_EN_ADDR     BG_GPS_MET_TOP_BG_GPS_MET_CTL1_ADDR
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL1_MET_DBG_CNT_EN_MASK     0x00020000
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL1_MET_DBG_CNT_EN_SHFT     17
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL1_MET_MCUCK_INFO_MASK_ADDR BG_GPS_MET_TOP_BG_GPS_MET_CTL1_ADDR
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL1_MET_MCUCK_INFO_MASK_MASK 0x00010000
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL1_MET_MCUCK_INFO_MASK_SHFT 16
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL1_MET_DATA_CNT4IRQ_ADDR   BG_GPS_MET_TOP_BG_GPS_MET_CTL1_ADDR
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL1_MET_DATA_CNT4IRQ_MASK   0x0000FF00
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL1_MET_DATA_CNT4IRQ_SHFT   8
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL1_MET_RING_BUF_FULL_SEL_ADDR BG_GPS_MET_TOP_BG_GPS_MET_CTL1_ADDR
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL1_MET_RING_BUF_FULL_SEL_MASK 0x00000002
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL1_MET_RING_BUF_FULL_SEL_SHFT 1
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL1_MET_RING_BUF_MODE_ADDR  BG_GPS_MET_TOP_BG_GPS_MET_CTL1_ADDR
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL1_MET_RING_BUF_MODE_MASK  0x00000001
#define BG_GPS_MET_TOP_BG_GPS_MET_CTL1_MET_RING_BUF_MODE_SHFT  0


#define BG_GPS_MET_TOP_BG_GPS_MET_EDGE_DET_MET_POSEDGE_DET_EN_ADDR BG_GPS_MET_TOP_BG_GPS_MET_EDGE_DET_ADDR
#define BG_GPS_MET_TOP_BG_GPS_MET_EDGE_DET_MET_POSEDGE_DET_EN_MASK 0xFFFF0000
#define BG_GPS_MET_TOP_BG_GPS_MET_EDGE_DET_MET_POSEDGE_DET_EN_SHFT 16
#define BG_GPS_MET_TOP_BG_GPS_MET_EDGE_DET_MET_NEGEDGE_DET_EN_ADDR BG_GPS_MET_TOP_BG_GPS_MET_EDGE_DET_ADDR
#define BG_GPS_MET_TOP_BG_GPS_MET_EDGE_DET_MET_NEGEDGE_DET_EN_MASK 0x0000FFFF
#define BG_GPS_MET_TOP_BG_GPS_MET_EDGE_DET_MET_NEGEDGE_DET_EN_SHFT 0


#define BG_GPS_MET_TOP_BG_GPS_MET_START_ADDR_MET_START_ADDR_ADDR BG_GPS_MET_TOP_BG_GPS_MET_START_ADDR_ADDR
#define BG_GPS_MET_TOP_BG_GPS_MET_START_ADDR_MET_START_ADDR_MASK 0xFFFFFFFF
#define BG_GPS_MET_TOP_BG_GPS_MET_START_ADDR_MET_START_ADDR_SHFT 0


#define BG_GPS_MET_TOP_BG_GPS_MET_END_ADDR_MET_END_ADDR_ADDR   BG_GPS_MET_TOP_BG_GPS_MET_END_ADDR_ADDR
#define BG_GPS_MET_TOP_BG_GPS_MET_END_ADDR_MET_END_ADDR_MASK   0xFFFFFFFF
#define BG_GPS_MET_TOP_BG_GPS_MET_END_ADDR_MET_END_ADDR_SHFT   0


#define BG_GPS_MET_TOP_BG_GPS_MET_WRITE_PTR_MET_WR_PTR_ADDR    BG_GPS_MET_TOP_BG_GPS_MET_WRITE_PTR_ADDR
#define BG_GPS_MET_TOP_BG_GPS_MET_WRITE_PTR_MET_WR_PTR_MASK    0xFFFFFFFF
#define BG_GPS_MET_TOP_BG_GPS_MET_WRITE_PTR_MET_WR_PTR_SHFT    0


#define BG_GPS_MET_TOP_BG_GPS_MET_READ_PTR_MET_RD_PTR_ADDR     BG_GPS_MET_TOP_BG_GPS_MET_READ_PTR_ADDR
#define BG_GPS_MET_TOP_BG_GPS_MET_READ_PTR_MET_RD_PTR_MASK     0xFFFFFFFF
#define BG_GPS_MET_TOP_BG_GPS_MET_READ_PTR_MET_RD_PTR_SHFT     0


#define BG_GPS_MET_TOP_BG_GPS_MET_FLAG_MET_MCUCK_INFO_ERR_FLAG_ADDR BG_GPS_MET_TOP_BG_GPS_MET_FLAG_ADDR
#define BG_GPS_MET_TOP_BG_GPS_MET_FLAG_MET_MCUCK_INFO_ERR_FLAG_MASK 0x00000008
#define BG_GPS_MET_TOP_BG_GPS_MET_FLAG_MET_MCUCK_INFO_ERR_FLAG_SHFT 3
#define BG_GPS_MET_TOP_BG_GPS_MET_FLAG_MET_AHB_ERR_FLAG_ADDR   BG_GPS_MET_TOP_BG_GPS_MET_FLAG_ADDR
#define BG_GPS_MET_TOP_BG_GPS_MET_FLAG_MET_AHB_ERR_FLAG_MASK   0x00000004
#define BG_GPS_MET_TOP_BG_GPS_MET_FLAG_MET_AHB_ERR_FLAG_SHFT   2
#define BG_GPS_MET_TOP_BG_GPS_MET_FLAG_MET_WRAP_ERR_FLAG_ADDR  BG_GPS_MET_TOP_BG_GPS_MET_FLAG_ADDR
#define BG_GPS_MET_TOP_BG_GPS_MET_FLAG_MET_WRAP_ERR_FLAG_MASK  0x00000002
#define BG_GPS_MET_TOP_BG_GPS_MET_FLAG_MET_WRAP_ERR_FLAG_SHFT  1
#define BG_GPS_MET_TOP_BG_GPS_MET_FLAG_MET_SLEEP_TIMER_OVERFLOW_ADDR BG_GPS_MET_TOP_BG_GPS_MET_FLAG_ADDR
#define BG_GPS_MET_TOP_BG_GPS_MET_FLAG_MET_SLEEP_TIMER_OVERFLOW_MASK 0x00000001
#define BG_GPS_MET_TOP_BG_GPS_MET_FLAG_MET_SLEEP_TIMER_OVERFLOW_SHFT 0


#define BG_GPS_MET_TOP_BG_GPS_MET_EVENT_SEL0_MET_GPS_EVENT_SEL_ADDR BG_GPS_MET_TOP_BG_GPS_MET_EVENT_SEL0_ADDR
#define BG_GPS_MET_TOP_BG_GPS_MET_EVENT_SEL0_MET_GPS_EVENT_SEL_MASK 0xFF000000
#define BG_GPS_MET_TOP_BG_GPS_MET_EVENT_SEL0_MET_GPS_EVENT_SEL_SHFT 24
#define BG_GPS_MET_TOP_BG_GPS_MET_EVENT_SEL0_MET_CFG_ON_EVENT_SEL_ADDR BG_GPS_MET_TOP_BG_GPS_MET_EVENT_SEL0_ADDR
#define BG_GPS_MET_TOP_BG_GPS_MET_EVENT_SEL0_MET_CFG_ON_EVENT_SEL_MASK 0x00030000
#define BG_GPS_MET_TOP_BG_GPS_MET_EVENT_SEL0_MET_CFG_ON_EVENT_SEL_SHFT 16


#define BG_GPS_MET_TOP_BG_GPS_MET_SWCTL_MET_SWCTL_ADDR         BG_GPS_MET_TOP_BG_GPS_MET_SWCTL_ADDR
#define BG_GPS_MET_TOP_BG_GPS_MET_SWCTL_MET_SWCTL_MASK         0x0000FFFF
#define BG_GPS_MET_TOP_BG_GPS_MET_SWCTL_MET_SWCTL_SHFT         0


#define BG_GPS_MET_TOP_BG_GPS_MET_SIGNAL_SEL_MET_TEMP_SIGNAL_SEL_ADDR BG_GPS_MET_TOP_BG_GPS_MET_SIGNAL_SEL_ADDR
#define BG_GPS_MET_TOP_BG_GPS_MET_SIGNAL_SEL_MET_TEMP_SIGNAL_SEL_MASK 0xFFFF0000
#define BG_GPS_MET_TOP_BG_GPS_MET_SIGNAL_SEL_MET_TEMP_SIGNAL_SEL_SHFT 16
#define BG_GPS_MET_TOP_BG_GPS_MET_SIGNAL_SEL_MET_SIGNAL_SEL_ADDR BG_GPS_MET_TOP_BG_GPS_MET_SIGNAL_SEL_ADDR
#define BG_GPS_MET_TOP_BG_GPS_MET_SIGNAL_SEL_MET_SIGNAL_SEL_MASK 0x0000FFFF
#define BG_GPS_MET_TOP_BG_GPS_MET_SIGNAL_SEL_MET_SIGNAL_SEL_SHFT 0


#define BG_GPS_MET_TOP_BG_GPS_MET_CLK_CTL_MET_CK_SEL_ADDR      BG_GPS_MET_TOP_BG_GPS_MET_CLK_CTL_ADDR
#define BG_GPS_MET_TOP_BG_GPS_MET_CLK_CTL_MET_CK_SEL_MASK      0x00000100
#define BG_GPS_MET_TOP_BG_GPS_MET_CLK_CTL_MET_CK_SEL_SHFT      8
#define BG_GPS_MET_TOP_BG_GPS_MET_CLK_CTL_MET_CK_32K_TARGET_ADDR BG_GPS_MET_TOP_BG_GPS_MET_CLK_CTL_ADDR
#define BG_GPS_MET_TOP_BG_GPS_MET_CLK_CTL_MET_CK_32K_TARGET_MASK 0x000000FF
#define BG_GPS_MET_TOP_BG_GPS_MET_CLK_CTL_MET_CK_32K_TARGET_SHFT 0


#define BG_GPS_MET_TOP_BG_GPS_MET_AFE_SEL_MET_AFE_SEL_ADDR     BG_GPS_MET_TOP_BG_GPS_MET_AFE_SEL_ADDR
#define BG_GPS_MET_TOP_BG_GPS_MET_AFE_SEL_MET_AFE_SEL_MASK     0x000000FF
#define BG_GPS_MET_TOP_BG_GPS_MET_AFE_SEL_MET_AFE_SEL_SHFT     0


#define BG_GPS_MET_TOP_BG_GPS_MET_IRQ_CTL_MET_IRQ_ENABLE_ADDR  BG_GPS_MET_TOP_BG_GPS_MET_IRQ_CTL_ADDR
#define BG_GPS_MET_TOP_BG_GPS_MET_IRQ_CTL_MET_IRQ_ENABLE_MASK  0x00000008
#define BG_GPS_MET_TOP_BG_GPS_MET_IRQ_CTL_MET_IRQ_ENABLE_SHFT  3


#define BG_GPS_MET_TOP_BG_GPS_MET_IRQ_STATUS_MET_IRQ_STATUS_ADDR BG_GPS_MET_TOP_BG_GPS_MET_IRQ_STATUS_ADDR
#define BG_GPS_MET_TOP_BG_GPS_MET_IRQ_STATUS_MET_IRQ_STATUS_MASK 0x00000008
#define BG_GPS_MET_TOP_BG_GPS_MET_IRQ_STATUS_MET_IRQ_STATUS_SHFT 3


#endif /* __BG_GPS_MET_TOP_REGS_H__ */
