/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2021 MediaTek Inc.
 */

#ifndef __BGF_GPS_MET_TOP_REGS_H__
#define __BGF_GPS_MET_TOP_REGS_H__

#define BGF_GPS_MET_TOP_BASE                                   0x80030000

#define BGF_GPS_MET_TOP_BGF_GPS_MET_CTL0_ADDR                  (BGF_GPS_MET_TOP_BASE + 0x000)
#define BGF_GPS_MET_TOP_BGF_GPS_MET_CTL1_ADDR                  (BGF_GPS_MET_TOP_BASE + 0x004)
#define BGF_GPS_MET_TOP_BGF_GPS_MET_EDGE_DET_ADDR              (BGF_GPS_MET_TOP_BASE + 0x008)
#define BGF_GPS_MET_TOP_BGF_GPS_MET_START_ADDR_ADDR            (BGF_GPS_MET_TOP_BASE + 0x00C)
#define BGF_GPS_MET_TOP_BGF_GPS_MET_END_ADDR_ADDR              (BGF_GPS_MET_TOP_BASE + 0x010)
#define BGF_GPS_MET_TOP_BGF_GPS_MET_WRITE_PTR_ADDR             (BGF_GPS_MET_TOP_BASE + 0x014)
#define BGF_GPS_MET_TOP_BGF_GPS_MET_READ_PTR_ADDR              (BGF_GPS_MET_TOP_BASE + 0x018)
#define BGF_GPS_MET_TOP_BGF_GPS_MET_FLAG_ADDR                  (BGF_GPS_MET_TOP_BASE + 0x01C)
#define BGF_GPS_MET_TOP_BGF_GPS_MET_EVENT_SEL0_ADDR            (BGF_GPS_MET_TOP_BASE + 0x020)
#define BGF_GPS_MET_TOP_BGF_GPS_MET_SWCTL_ADDR                 (BGF_GPS_MET_TOP_BASE + 0x024)
#define BGF_GPS_MET_TOP_BGF_GPS_MET_SIGNAL_SEL_ADDR            (BGF_GPS_MET_TOP_BASE + 0x028)

#define BGF_GPS_MET_TOP_BGF_GPS_MET_CTL0_MET_DATA_MASK_ADDR    BGF_GPS_MET_TOP_BGF_GPS_MET_CTL0_ADDR
#define BGF_GPS_MET_TOP_BGF_GPS_MET_CTL0_MET_DATA_MASK_MASK    0xFFFF0000
#define BGF_GPS_MET_TOP_BGF_GPS_MET_CTL0_MET_DATA_MASK_SHFT    16

#define BGF_GPS_MET_TOP_BGF_GPS_MET_CTL0_MET_OSC_CNT_TARGET_ADDR BGF_GPS_MET_TOP_BGF_GPS_MET_CTL0_ADDR
#define BGF_GPS_MET_TOP_BGF_GPS_MET_CTL0_MET_OSC_CNT_TARGET_MASK 0x00007F00
#define BGF_GPS_MET_TOP_BGF_GPS_MET_CTL0_MET_OSC_CNT_TARGET_SHFT 8

#define BGF_GPS_MET_TOP_BGF_GPS_MET_CTL0_MET_CLK_EN_ADDR       BGF_GPS_MET_TOP_BGF_GPS_MET_CTL0_ADDR
#define BGF_GPS_MET_TOP_BGF_GPS_MET_CTL0_MET_CLK_EN_MASK       0x00000002
#define BGF_GPS_MET_TOP_BGF_GPS_MET_CTL0_MET_CLK_EN_SHFT       1

#define BGF_GPS_MET_TOP_BGF_GPS_MET_CTL0_MET_RECORD_EN_ADDR    BGF_GPS_MET_TOP_BGF_GPS_MET_CTL0_ADDR
#define BGF_GPS_MET_TOP_BGF_GPS_MET_CTL0_MET_RECORD_EN_MASK    0x00000001
#define BGF_GPS_MET_TOP_BGF_GPS_MET_CTL0_MET_RECORD_EN_SHFT    0

#define BGF_GPS_MET_TOP_BGF_GPS_MET_CTL1_MET_RING_BUF_MODE_ADDR BGF_GPS_MET_TOP_BGF_GPS_MET_CTL1_ADDR
#define BGF_GPS_MET_TOP_BGF_GPS_MET_CTL1_MET_RING_BUF_MODE_MASK 0x00000001
#define BGF_GPS_MET_TOP_BGF_GPS_MET_CTL1_MET_RING_BUF_MODE_SHFT 0

#define BGF_GPS_MET_TOP_BGF_GPS_MET_EDGE_DET_MET_POSEDGE_DET_EN_ADDR BGF_GPS_MET_TOP_BGF_GPS_MET_EDGE_DET_ADDR
#define BGF_GPS_MET_TOP_BGF_GPS_MET_EDGE_DET_MET_POSEDGE_DET_EN_MASK 0xFFFF0000
#define BGF_GPS_MET_TOP_BGF_GPS_MET_EDGE_DET_MET_POSEDGE_DET_EN_SHFT 16

#define BGF_GPS_MET_TOP_BGF_GPS_MET_EDGE_DET_MET_NEGEDGE_DET_EN_ADDR BGF_GPS_MET_TOP_BGF_GPS_MET_EDGE_DET_ADDR
#define BGF_GPS_MET_TOP_BGF_GPS_MET_EDGE_DET_MET_NEGEDGE_DET_EN_MASK 0x0000FFFF
#define BGF_GPS_MET_TOP_BGF_GPS_MET_EDGE_DET_MET_NEGEDGE_DET_EN_SHFT 0

#define BGF_GPS_MET_TOP_BGF_GPS_MET_START_ADDR_MET_START_ADDR_ADDR BGF_GPS_MET_TOP_BGF_GPS_MET_START_ADDR_ADDR
#define BGF_GPS_MET_TOP_BGF_GPS_MET_START_ADDR_MET_START_ADDR_MASK 0xFFFFFFFF
#define BGF_GPS_MET_TOP_BGF_GPS_MET_START_ADDR_MET_START_ADDR_SHFT 0

#define BGF_GPS_MET_TOP_BGF_GPS_MET_END_ADDR_MET_END_ADDR_ADDR BGF_GPS_MET_TOP_BGF_GPS_MET_END_ADDR_ADDR
#define BGF_GPS_MET_TOP_BGF_GPS_MET_END_ADDR_MET_END_ADDR_MASK 0xFFFFFFFF
#define BGF_GPS_MET_TOP_BGF_GPS_MET_END_ADDR_MET_END_ADDR_SHFT 0

#define BGF_GPS_MET_TOP_BGF_GPS_MET_EVENT_SEL0_MET_GPS_EVENT_SEL_ADDR BGF_GPS_MET_TOP_BGF_GPS_MET_EVENT_SEL0_ADDR
#define BGF_GPS_MET_TOP_BGF_GPS_MET_EVENT_SEL0_MET_GPS_EVENT_SEL_MASK 0x7F000000
#define BGF_GPS_MET_TOP_BGF_GPS_MET_EVENT_SEL0_MET_GPS_EVENT_SEL_SHFT 24

#define BGF_GPS_MET_TOP_BGF_GPS_MET_SIGNAL_SEL_MET_TEMP_SIGNAL_SEL_ADDR BGF_GPS_MET_TOP_BGF_GPS_MET_SIGNAL_SEL_ADDR
#define BGF_GPS_MET_TOP_BGF_GPS_MET_SIGNAL_SEL_MET_TEMP_SIGNAL_SEL_MASK 0xFFFF0000
#define BGF_GPS_MET_TOP_BGF_GPS_MET_SIGNAL_SEL_MET_TEMP_SIGNAL_SEL_SHFT 16

#define BGF_GPS_MET_TOP_BGF_GPS_MET_SIGNAL_SEL_MET_SIGNAL_SEL_ADDR BGF_GPS_MET_TOP_BGF_GPS_MET_SIGNAL_SEL_ADDR
#define BGF_GPS_MET_TOP_BGF_GPS_MET_SIGNAL_SEL_MET_SIGNAL_SEL_MASK 0x0000FFFF
#define BGF_GPS_MET_TOP_BGF_GPS_MET_SIGNAL_SEL_MET_SIGNAL_SEL_SHFT 0

#endif /* __BGF_GPS_MET_TOP_REGS_H__ */

