LOCAL_PATH := $(call my-dir)

MT76XX_CHIPS := MT7668 MT7663 MT7921
ifeq ($(filter $(MT76XX_CHIPS), $(MTK_COMBO_CHIP)),)
include $(CLEAR_VARS)
LOCAL_MODULE := wmt_drv.ko
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MODULE_OWNER := mtk

LOCAL_INIT_RC := init.wmt_drv.rc
LOCAL_SRC_FILES := $(patsubst $(LOCAL_PATH)/%,%,$(shell find $(LOCAL_PATH) -type f -name '*.[cho]')) Makefile
LOCAL_REQUIRED_MODULES :=

include $(MTK_KERNEL_MODULE)

WMT_OPTS := MTK_CONSYS_ADIE=$(MTK_CONSYS_ADIE)
WMT_OPTS += MTK_PLATFORM_WMT=$(MTK_PLATFORM)
WMT_OPTS += TARGET_BOARD_PLATFORM_WMT=$(TARGET_BOARD_PLATFORM)

$(linked_module): OPTS += $(WMT_OPTS)
endif